import {advancedQuestion} from './advanced-author';
import type {SourceRow} from './source-author';

const EDITION="Chirurgie generală și specialități chirurgicale, ediția pentru rezidențiat MG 2025";
const pdfOffset=(p:number)=>p-58;
const q=(n:number,row:SourceRow,score:number,reason:string,expressions:string[],related:number[]=[])=>
 advancedQuestion('arsuri',10,pdfOffset,`arsuri-adv-${String(n).padStart(3,'0')}`,row,[score,reason],expressions,undefined,related,'Lawrence',EDITION);

export const ARSURI_D=[
q(51,['Anatomia tegumentului relevantă pentru vindecarea arsurii (Figura 10-1) se caracterizează prin:',
 ['Celulele epiteliale căptușesc foliculii piloși și glandele sudoripare, structuri care pătrund profund în derm și uneori îl depășesc','Chiar și arsurile de grosime parțială foarte profunde se pot vindeca dacă anexele epidermale supraviețuiesc','Capilarele dermice și terminațiile nervoase din dermul profund supraviețuiesc în majoritatea arsurilor de grosime parțială','Anexele epidermale sunt distruse în arsura de grosime parțială, vindecarea spontană fiind imposibilă fără grefă','Terminațiile nervoase lipsesc din derm, durerea arsurii parțiale fiind de origine fascială'],'ABC',108,'Figura 10-1 — Anexe epidermale și derm profund',
 'Recunoașterea anexelor (foliculi, glande sudoripare) ca rezervor de epiteliu și a persistenței capilarelor/nervilor în arsura parțială.',
 ['Textul plasează epiteliul pe foliculi și glande sudoripare, cu pătrundere profundă, uneori dincolo de derm.','Supraviețuirea anexelor explică vindecarea arsurilor parțiale foarte profunde.','Capilarele și terminațiile din dermul profund persistă în majoritatea arsurilor parțiale.','Anexele pot supraviețui tocmai în arsura parțială; grefa nu este de principiu.','Terminațiile nervoase sunt în dermul profund, de aceea arsura parțială este dureroasă.']],
 8,'Neagă vindecarea pe anexe, deși figura de deschidere o face mecanismul central al arsurii parțiale.',['foliculii piloşi','anexe epiderma le']),

q(52,['Identificați afirmația corectă referitoare la arsurile de grad III prin lichide fierbinți:',
 ['Au adesea culoarea vișiniu închis, cu suprafață uscată, și nu se albesc la presiune directă','Se albesc prompt, cu flictene lichidiene abundente, identic gradului II superficial','Sunt nedureroase doar dacă rămân hiperemice și umede','Culoarea este invariabil negru carbonizat, lichidele fierbinți neputând produce grad III','Contracția de tip garou este imposibilă, proteinele dermice necoagulând în aceste leziuni'],'A',110,'Arsuri de toată grosimea — Lichide fierbinți',
 'Recunoașterea aspectului vișiniu uscat, fără albire, al gradului III prin lichide, distinct de flictenele umede de grad II.',
 ['Textul atribuie lichidelor fierbinți culoarea vișiniu închis, suprafața uscată și absența albirii.','Albirea și flictenele lichidiene definesc gradul II superficial.','Gradul III este uscat și nedureros prin distrugerea nervilor, nu prin hiperemia umedă.','Negrul carbonizat ține de flacără; lichidele fierbinți pot produce totuși grad III.','Coagularea proteinelor dermice produce tocmai retracția de tip garou.']],
 8,'Mută flictenele și albirea de la gradul II asupra gradului III prin lichide, capcana de culoare vișinie.',['culoarea vişiniu','nu se albesc la presiune']),

q(53,['Conform Tabelului 10-1, concentrația de COHb de 20–30% se asociază cu:',
 ['Deces în decurs de minute','Absența simptomelor, ca la fumătorul cu 0–10%','Cefalee pulsatilă la nivelul tâmplelor','Comă, convulsii intermitente și respirație Cheyne-Stokes','Doar dilatația vaselor cutanate, fără cefalee'],'C',111,'Tabelul 10-1 — COHb 20–30%',
 'Aplicarea rândului 20–30% (cefalee pulsatilă temporală), distinct de 0–10% asimptomatic și de 50–60% (comă).',
 ['Decesul în minute aparține intervalului 90–100%.','0–10% este fără simptome (până la 10% la fumători).','Rândul 20–30% listează cefaleea pulsatilă la tâmple.','Coma și Cheyne-Stokes țin de 50–60%.','Dilatația cutanată fără acest tip de cefalee aparține intervalului 10–20%.']],
 8,'Permutează cefaleea pulsatilă de 20–30% cu pragurile de comă sau de deces din același tabel.',['20-30','Cefalee pulsatilă']),

q(54,['Selectați enunțurile adevărate despre concentrațiile de COHb din Tabelul 10-1:',
 ['Intervalul 30–40% produce cefalee severă, slăbiciune, amețeală, tulburări de vedere, greață, vărsături și colaps','Intervalul 60–70% se asociază cu comă, convulsii intermitente, depresia funcțiilor respiratorie și cardiacă, cu posibil deces','Intervalul 0–10% produce deces într-o oră','Intervalul 90–100% este fără simptome','Intervalul 10–20% produce bradicardie și deces în minute'],'AB',111,'Tabelul 10-1 — COHb 30–40% și 60–70%',
 'Contrastarea rândului 30–40% (colaps cu simptome vegetative) cu 60–70% (comă și posibil deces), față de extremele tabelului.',
 ['Lista de simptome a rândului 30–40% este explicită.','Rândul 60–70% include comă, convulsii, depresie cardio-respiratorie și posibil deces.','Decesul într-o oră aparține intervalului 80–90%.','90–100% este deces în minute, nu absența simptomelor.','10–20% produce presiune frontală și cefalee moderată, nu bradicardie.']],
 8,'Inversează rândurile mediane ale tabelului cu extremele 0–10% și 90–100%.',['30-40','60-70']),

q(55,['Medicii fără experiență, la documentarea arsurii pe diagrama Lund și Browder, au tendința de a:',
 ['Subestima sistematic atât mărimea, cât și profunzimea','Supraevalua mărimea și profunzimea arsurii','Ignora zona capului la copil, considerând-o neglijabilă','Include doar arsurile epidermice în totalul %SCT','Înlocui diagrama cu palma examinatorului ca 9% SCT'],'B',113,'Diagrama Lund și Browder — Eroarea de estimare',
 'Recunoașterea tendinței de supraevaluare a mărimii și profunzimii la examinatorul neexperimentat.',
 ['Subestimarea nu este tendința citată.','Textul legendelor diagramei precizează supraevaluarea mărimii și profunzimii.','Capul copilului este disproporționat de mare în diagramă, nu de ignorat.','Doar gradele 2 și 3 se includ, nu epidermicele.','Palma pacientului cu degete este ≈1% SCT, nu 9%.']],
 8,'Inversează supraevaluarea clasică a noviceului într-o subestimare, pe o legendă ușor de omis.',['supraevalua mărimea','Lund şi Browder']),

q(56,['Resuscitarea lichidiană, dincolo de formula de start, se caracterizează prin:',
 ['Soluțiile cristaloide izotone sunt preferate inițial fiind ieftine, disponibile și administrabile în cantități crescute fără reacții adverse dăunătoare','Nu oprește extravazarea către interstițiu, ci echilibrează pierderile continue, care scad în timp','Semnele vitale, hematocritul și alte teste de laborator trebuie monitorizate cu atenție, pe lângă diureză','Coloizii înlocuiesc cristaloizii din primul minut, capilarele fiind impermeabile pentru proteine','Extravazarea se oprește imediat ce începe infuzia, hematocritul nemaifiind util'],'ABC',115,'Tabelul 10-3 — Principii și monitorizare',
 'Aplicarea principiului cristaloizilor (ieftini, în volume mari) și a scopului de a echilibra, nu de a opri, pierderea capilară.',
 ['Principiul A al tabelului justifică cristaloizii izotoni prin cost, disponibilitate și toleranța volumelor mari.','Textul precizează că infuzia nu oprește extravazarea, ci o echilibrează.','Hematocritul și semnele vitale completează diureza ca ghid.','Capilarele sunt permeabile pentru proteine în primele ore, deci coloizii nu se folosesc inițial.','Pierderile continuă; hematocritul rămâne un parametru de urmărit.']],
 8,'Tratează infuzia ca stop al extravazării și reintroduce coloizii din minutul zero, inversul principiilor A–B.',['cristaloide izotone','hematocritul']),

q(57,['Următoarele afirmații despre escarotomie și perioada de acoperire a leziunii sunt adevărate:',
 ['Escarotomiile, fiind efectuate prin țesuturi deja arse, sunt reparate la excizie-grefare și de obicei nu lasă cicatrici suplimentare','Perioada de acoperire începe imediat după resuscitarea cu fluide și durează zile–săptămâni, până la vindecare primară sau grefare reușită, reprezentând cea mai mare parte a îngrijirii spitalicești','Escarotomia se suturează cosmetic în urgență, pentru a evita cicatricea pe tegument intact','Acoperirea se amână luni de zile, până după încheierea reabilitării','Pacienții la care leziunea se vindecă nu mai au nevoie de program de reabilitare'],'AB',116,'Escarotomie fără cicatrice suplimentară — Faza de acoperire',
 'Contrastarea absenței cicatricii suplimentare (incizie prin escară) cu durata spitalicească a fazei de acoperire.',
 ['Repararea la excizie-grefare și absența cicatricilor suplimentare sunt explicite.','Fereastra zile–săptămâni și ponderea spitalicească a fazei de acoperire sunt citate.','Incizia trece prin țesut deja ars, nu prin tegument intact de suturat în urgență.','Acoperirea urmează imediat resuscitării, nu reabilitării.','Textul precizează că, după vindecare, poate urma un program prelungit de reabilitare.']],
 8,'Suturează escarotomia pe tegument intact și amână acoperirea după reabilitare, inversul celor două paragrafe.',['cicatrici suplimentare','zile -săptămâni']),

q(58,['Suprafața pielii arse, din punct de vedere bacteriologic imediat post-injurie:',
 ['Este, teoretic, sterilă 24–48 de ore, apoi se repopulează treptat cu bacterii','Este colonizată masiv cu Pseudomonas din primul minut','Rămâne sterilă până la grefare, indiferent de durată','Escara profundă avasculară este un mediu ostil, incompatibil cu multiplicarea germenilor','Sterilitatea persistă 3 săptămâni, fără nicio colonizare'],'A',117,'Controlul infecției — Fereastra de sterilitate',
 'Recunoașterea ferestrei teoretice de 24–48 de ore înaintea recolonizării, față de escara ca mediu de cultură.',
 ['Sterilitatea teoretică 24–48 de ore și recolonizarea treptată sunt explicite.','Pseudomonas devine problemă ulterior, nu din primul minut.','Recolonizarea începe după 24–48 de ore, nu așteaptă grefarea.','Escara groasă avasculară este un mediu ideal de cultură.','3 săptămâni depășește fereastra citată.']],
 8,'Permutează fereastra 24–48 de ore cu colonizarea imediată sau cu sterilitatea până la grefă.',['24-48 ore după arsură','repopulată treptat']),

q(59,['Măștile faciale compresive și prognosticul social după arsura majoră:',
 ['Măștile faciale elastice purtate lung tind să deformeze mandibula la copii; în locul lor se confecționează măști rigide din plastic transparent, purtate de obicei cel puțin un an','Produșii care aderă de leziune și eliberează treptat argint trebuie supravegheați de un clinician experimentat, infecția de sub ei fiind greu de diagnosticat și tratat','Marea majoritate a pacienților se întorc la muncă sau la școală, chiar și după arsuri de 70% SCT sau mai mari','Măștile elastice sunt preferate la copii tocmai pentru a stimula creșterea mandibulară','Arsura de 70% SCT exclude revenirea la școală sau la muncă'],'ABC',118,'Reabilitare — Mască facială și 70% SCT',
 'Contrastarea măștii rigide (evitând deformarea mandibulară) cu revenirea funcțională după arsuri ≥70% SCT.',
 ['Deformarea mandibulară a măștilor elastice și alternativa rigidă ≥1 an sunt din legenda figurii.','Supravegherea produșilor cu eliberare de argint și dificultatea diagnosticului de sub ei sunt explicite.','Revenirea la muncă/școală după 70% SCT este citată.','Elasticele sunt evitate la copii din cauza deformării, nu preferate.','Textul afirmă revenirea majorității, inclusiv după 70% SCT.']],
 8,'Preferă masca elastică la copil (care deformează mandibula) și neagă reinserția după 70% SCT.',['deformări ale mandibulei','70% SCT'],[119]),

q(60,['Tratamentul inițial al arsurii chimice, dincolo de clasa agentului, include:',
 ['Îndepărtarea completă a îmbrăcăminții, perierea pulberilor uscate de pe piele, apoi spălarea cu apă din abundență','Monitorizarea pH-ului soluției irigate, când se cunoaște compoziția, ca indicator al eficacității și al finalizării irigării','Determinarea gazometriei arteriale, a electroliților și a enzimelor hepatice, din cauza anomaliilor de pH și a toxicităților (de exemplu organofosfați)','Lăsarea pulberilor pe piele și acoperirea cu sulfadiazină, irigarea fiind evitată','Considerarea leziunilor alcaline ca mai superficiale decât par, cu necesar lichidian mai mic decât al acizilor'],'ABC',119,'Arsuri chimice — Decontaminare, pH, laboratoare',
 'Aplicarea secvenței periere–irigare, a pH-ului ca ghid de spălare și a bilanțului metabolic (inclusiv organofosfați).',
 ['Perierea pulberilor, dezbrăcarea și spălarea abundentă sunt gesturile inițiale.','pH-ul irigatului este descris ca indicator al eficacității.','Gazometria, electroliții, enzimele hepatice și exemplul organofosfaților sunt cerute.','Pulberile se perie și se spală, nu se acoperă.','Alcalinele pot pătrunde dincolo de ceea ce este vizibil și cer mai multe lichide.']],
 8,'Lasă pulberea pe piele și inversează profunzimea/necesarul lichidian alcali versus acizi.',['pulberile uscate','organofosfaţii']),

q(61,['În leziunea de înaltă tensiune, distribuția leziunii tisulare se explică prin:',
 ['Curentul traversează țesuturile cu cea mai mică rezistență — în general nervi, vase de sânge și mușchi — pentru a ieși prin pământ','Țesuturile cu cea mai mare rezistență generează cea mai mare căldură; mușchii profundi de lângă oase pot fi lezați, în timp ce mușchii superficiali par intacți','Pielea are rezistență nulă, deci leziunea este maximă la epiderm și minimă lângă os','Curentul evită nervii și vasele, preferând țesutul adipos','Extensia reală a deteriorării este evidentă la inspecția inițială a pielii'],'AB',119,'Leziuni electrice — Rezistență, căldură, mușchi periostali',
 'Aplicarea paradoxului: calea de minimă rezistență versus căldura maximă în țesuturile rezistente, cu leziune periostală ocultă.',
 ['Traiectul prin nervi, vase și mușchi către pământ este explicit.','Căldura maximă în țesuturile rezistente și leziunea mușchilor profunzi lângă os sunt citate.','Pielea are rezistență ridicată; leziunea profundă lângă os este adesea mai severă.','Nervii, vasele și mușchii sunt tocmai calea preferată.','Textul precizează că extensia reală poate fi imposibil de determinat la examinarea inițială.']],
 8,'Mută leziunea maximă pe epiderm și declară inspecția cutanată suficientă, inversul paradoxului periostal.',['nervi, vase de sânge','cea mai mare căldură']),

q(62,['Pe lângă trecerea trans-tisulară a curentului, leziunile electrice se mai pot asocia cu:',
 ['Arc electric sau leziuni de tip „flash”','Arsuri prin flacără după aprinderea îmbrăcămintei, fără ca tot curentul să treacă prin pacient','Căderi și contuzii prin contracții musculare tetanice; pacienții trebuie imobilizați și tratați ca politraumatizați','Un tablou limitat la eritem solar, fără risc de arc sau cădere','Absența oricărei aritmii, ECG-ul fiind superfluu'],'ABC',120,'Leziuni electrice — Arc, flacără, tetanie',
 'Recunoașterea triadului arc/flash, flacără de îmbrăcăminte și traumatism prin tetanie/cădere, dincolo de arsura de contact.',
 ['Arcul și leziunile flash sunt enumerate.','Aprinderea hainelor fără trecerea completă a curentului este citată.','Căderile, tetania și tratarea ca politraumatism sunt cerute.','Arcul, flacăra și căderea sunt tocmai riscurile asociate.','Mulți mor prin fibrilație ventriculară sau stop indus electric; ECG-ul este obligatoriu la toți.']],
 8,'Reduce electrocuția la eritem solar și anulează arc, cădere și aritmie, trei complicații din același paragraf.',['arc electric','contracţiile musculare tetanice'],[119]),

q(63,['Un electrician cu electrocuție de înaltă tensiune are urină culoarea ceaiului. Pentru clearance-ul mioglobinei, bicarbonatul (alcalinizarea urinii) și manitolul:',
 ['S-au dovedit eficienți în toate studiile prospective, deci se administrează de rutină','Nu s-au dovedit eficienți în studii prospective; folosirea lor trebuie individualizată după experiența practicianului','Înlocuiesc infuzia de lichide, diureza-țintă nemaifiind relevantă','Sunt contraindicați în orice pigmenturie, chiar și când mioglobinuria persistă sub resuscitare','Se administrează înainte de a opri sursa de curent'],'B',120,'Mioglobinurie — Bicarbonat și manitol',
 'Recunoașterea lipsei de dovezi prospective pentru alcalinizare/manitol, față de individualizarea după experiență.',
 ['Eficiența de rutină nu este susținută de studiile prospective citate.','Textul neagă eficiența în studii prospective și cere individualizare.','Lichidele pentru diureză ≥100 mL/oră rămân baza, nu sunt înlocuite.','Adjuvanții pot fi folosiți individualizat, nu sunt interziși absolut.','Sursa de curent se oprește înaintea oricărui tratament.']],
 8,'Transformă bicarbonatul și manitolul în rutină dovedită, deși paragraful le lasă la latitudinea experienței.',['nu s-au dovedit eficiente','manitolului']),

q(64,['Îngrijirea topică a arsurii minore, potrivit capitolului:',
 ['Arsurile epidermice fără flictene nu necesită îngrijire topică','Flictenele pot fi adesea lăsate intacte; odată rupte, se îndepărtează pentru curățarea plăgii','Pansamentele cu argint înglobat în hidrofibre, pe plasă de polietilenă sau nanocristalin permit intervale mai lungi între schimburi, reducând durerea și infecția față de preparatele tradiționale de argint','Antibioticele orale sunt de rutină în arsura neinfectată','Gheața prelungită este superioară apei de 12–25°C'],'ABC',120,'Arsuri minore — Flictene și pansamente cu argint',
 'Contrastarea absenței topicului în arsura epidermică fără flictene cu pansamentele de argint cu schimb rar.',
 ['Absența îngrijirii topice la epidermicele fără flictene este explicită.','Păstrarea flictenelor intacte până la ruptură este descrisă.','Hidrofibrele, plasa de polietilenă și argintul nanocristalin prelungesc intervalul și reduc durerea/infecția.','Antibioticele orale nu sunt necesare în arsura neinfectată.','Gheața crește necroza; apa de 12–25°C este eficientă.']],
 8,'Impune antibiotic oral și gheață asupra arsurii minore, anulând pansamentele de argint cu schimb rar.',['flictene nu necesită','argintul nanocristalin']),

q(65,['Conform Tabelului 10-4, dozele și particularitățile analgezicelor/sedativelor la adultul ars includ:',
 ['Sulfatul de morfină 0,03–0,1 mg/kg IV; morfina, fentanilul și hidromorfona pot fi folosite în analgezia controlată de pacient','Fentanil 50–100 µg IV; ketamina 0,5–1 mg/kg IV, asociată cu delir și coșmaruri, putând fi dată intramuscular pentru proceduri scurte ambulatorii','Propofolul 0,5–1 mg/kg IV pentru sedare de procedură sau pacient ventilat, cu necesitatea suportului căilor respiratorii','Clonidina 0,1–0,3 mg la 6–12 ore pe cale orală, disponibilă și ca plasture, nu ca agent unic pentru controlul durerii','Benzodiazepinele au efect analgezic suficient, opioidele fiind superflue'],'ABCD',121,'Tabelul 10-4 — Doze de analgezie și sedare',
 'Aplicarea dozelor tabelate (morfină, fentanil, ketamină, propofol, clonidină) și a limitelor (PCA, căi aeriene, nu agent unic).',
 ['Doza de morfină și mențiunea PCA pentru cei trei opioizi IV sunt din tabel.','Dozele de fentanil și ketamină, plus delirul/coșmarurile și calea IM ambulatorie, sunt citate.','Propofolul și cerința suportului de căi sunt explicite.','Doza de clonidină, plasturele și interdicția ca agent unic sunt din comentariu.','Tabelul precizează că benzodiazepinele nu au efect analgezic suficient.']],
 8,'Atribuie benzodiazepinelor analgezie suficientă și amestecă dozele tabelate ale morfinei, ketaminei și propofolului.',['0,03-0, 1 mg/kg IV','50-100 µg IV']),

q(66,['Metodele nefarmacologice pentru durerea arsului includ:',
 ['Tehnici cognitive (exerciții de respirație, întărirea comportamentului pozitiv, imagini adecvate vârstei, repetiție comportamentală)','Distragerea atenției prin muzică, filme și jocuri; sistemele de realitate virtuală au redus semnificativ durerea la schimbarea pansamentelor','Hipnoza, care combină relaxarea, imaginația și cogniția','Definirea realității virtuale ca imersie totală într-o lume artificială, textul respingând suprapunerea pe lumea fizică','Evitarea oricărei distrageri, care ar crește percepția nociceptivă'],'ABC',122,'Analgezie nefarmacologică — VR și hipnoză',
 'Recunoașterea triadului cognitiv / distragere-VR / hipnoză, cu VR ca suprapunere pe lumea fizică, nu ca imersie.',
 ['Tehnicile cognitive enumerate sunt explicite.','Muzica, filmele, jocurile și reducerea durerii la pansamente prin VR sunt citate.','Definiția hipnozei (relaxare, imaginație, cogniție) este dată.','Textul definește VR-ul ca suprapunere pe lumea fizică, nu ca imersie.','Distragerea este descrisă ca utilă, nu de evitat.']],
 8,'Inversează definiția VR (imersie versus suprapunere) și contraindică distragerea, două puncte din același paragraf.',['realitate virtuală','Hipnoza']),

q(67,['Mecanismul imun al NET/SSJ, potrivit capitolului, constă în:',
 ['Distrugerea celulelor epiteliale bazale de către celulele CD8+ și macrofagele din dermul superficial, analog bolii grefă-versus-gazdă','O infecție stafilococică invazivă a fasciai, identică gangrenei Fournier','Un depozit de IgE cu degranulare mastocitară, ca în urticaria acută','O arsură termică profundă prin flacără, fără componentă imună','Colonizarea escarei cu Pseudomonas, fără implicarea keratinocitelor'],'A',122,'NET/SSJ — Patogenie celulară',
 'Recunoașterea citotoxicității CD8+/macrofag asupra keratinocitului bazal, analog GVHD, nu a unei infecții de țesuturi moi.',
 ['CD8+, macrofagele dermice și analogia grefă-versus-gazdă sunt explicite.','Fournier este o infecție necrozantă, nu mecanismul NET.','IgE/mastocitul nu este calea descrisă.','NET este o reacție imună medicamentoasă/infecțioasă, nu o arsură termică.','Keratinocitele sunt ținta; Pseudomonas nu este patogenia.']],
 8,'Înlocuiește citotoxicitatea CD8+/macrofag cu o infecție necrozantă sau cu IgE, pe un analog GVHD ușor de omis.',['celulele CD8+','grefă-versus-gazdă']),

q(68,['Tabloul clinic și confirmarea diagnosticului de NET/SSJ se caracterizează prin:',
 ['O fază prodromală de tip viroză (febră, stare de rău), urmată de o erupție maculară care se răspândește, adesea confluentă','Poate implica orice suprafață de mucoasă, inclusiv orofaringele, ochii, tractul gastrointestinal și arborele traheobronșic','Biopsia se face de la marginea zonei cu flictene și de la pielea indemnă adiacentă, pentru a distinge de sindromul pielii opărite stafilococice sau de exanteme virale','Mucosa este cruțată, diagnosticul cerând doar radiografie pulmonară','Biopsia este superfluă, semnul Nikolsky înlocuind diagnosticul diferențial'],'ABC',122,'NET/SSJ — Prodrom, mucoase, biopsie',
 'Secvența prodrom–erupție, extensia mucoasă (inclusiv digestiv și traheobronșic) și biopsia de la marginea flictenei plus pielea indemnă.',
 ['Prodromul febril și erupția maculară confluentă sunt descrise.','Lista de mucoase, inclusiv tub digestiv și arbore traheobronșic, este explicită.','Biopsia comparativă (margine + piele indemnă) și diagnosticele diferențiale sunt cerute.','Mucosa poate fi atinsă; radiografia nu înlocuiește biopsia.','Nikolsky este frecvent, dar biopsia distinge de infecții/exanteme.']],
 8,'Cruță mucoasele și anulează biopsia, două elemente distinctive față de arsura termică obișnuită.',['fază prodromală','pielii opărite stafilococice']),

q(69,['În managementul NET, dincolo de acoperirea plăgii, sunt adevărate:',
 ['Afectarea oculară este frecventă și până la jumătate dintre supraviețuitori rămân cu sechele severe; consultația oftalmologică se face la debut pentru conjunctivită pseudo- sau membranoasă','Steroizii sistemici reduc răspunsul inflamator, dar nu au îmbunătățit supraviețuirea după apariția descuamării','Imunoglobulina a fost recomandată prin inhibarea CD95 în model experimental, însă studiile clinice nu au demonstrat beneficii','Ceea ce pare să facă diferența este îngrijirea pe protocol într-un centru de arși experimentat (reechilibrare, ventilație, nutriție, fizioterapie)','Steroizii după descuamare cresc invariabil supraviețuirea, oftalmologia amânându-se până la cicatrizare'],'ABCD',123,'NET — Ochi, steroizi, IVIG, protocol de centru',
 'Contrastarea absenței beneficiului de supraviețuire al steroizilor/IVIG după descuamare cu oftalmologia de la debut și protocolul de centru.',
 ['Frecvența sechelelor oculare (până la jumătate) și consultația de la debut sunt explicite.','Steroizii reduc inflamația fără câștig de supraviețuire după descuamare.','CD95 experimental versus lipsa de beneficiu clinic a imunoglobulinei sunt citate.','Protocolul de centru de arși este prezentat ca elementul care face diferența.','Oftalmologia nu se amână; steroizii nu au îmbunătățit supraviețuirea după descuamare.']],
 8,'Reabilitează steroizii și IVIG după descuamare și amână oftalmologia, inversul datelor din paragraf.',['Consultaţia oftalmologică','imunoglobulinei']),

q(70,['Sechelele NET și infecțiile necrozante îndrumate către centrul de arși:',
 ['Sechelele pe termen lung ale NET includ pigmentare anormală, pierderea plăcilor unghiale, fimoză, sinechii vaginale, disfagie, cicatrizare conjunctivală, ectropion și simblefaron (aderența pleoapei de globul ocular)','Infecțiile necrozante — indiferent de termenii fasciită necrozantă, gangrena Fournier sau gangrena Meleney — au evoluție rapidă, toxicitate severă și necroză ce se poate extinde rapid, iar centrele de arși sunt echipate pentru exciziile largi','Simblefaronul exclude diagnosticul de NET, textul negând orice sechelă oculară','Gangrena Fournier este o entitate fără necroză, tratată doar cu antibiotice orale','Centrele de arși nu primesc infecții de țesuturi moi, fiind rezervate arsurii solare'],'AB',123,'NET — Sechele; infecții necrozante în centrul de arși',
 'Listarea sechelelor muco-cutanate (inclusiv simblefaron) și a trăsăturilor comune ale infecțiilor necrozante tratate în centrul de arși.',
 ['Lista de sechele, cu definiția simblefaronului, este explicită.','Confuzia terminologică Fournier/Meleney și caracteristicile comune, plus rolul centrului de arși, sunt citate.','Simblefaronul este o sechelă recunoscută, nu un semn de excludere.','Fournier face parte din spectrul necrozant, nu dintr-o entitate fără necroză.','Textul menționează direcționarea infecțiilor necrozante către centrele de arși.']],
 8,'Neagă simblefaronul și reduce Fournier la o infecție fără necroză, două capcane de final de capitol.',['simblefaron','gangrena Fumier']),
];
