import {rewriter} from './rewrite-author';
import {RETIRED_ARSURI} from './retired/arsuri';

// Rewritten after the 2026-09-24 cue audit (Lawrence, cap. 10, p. 108–123).
const q=rewriter(RETIRED_ARSURI,(p:number)=>p-58,{shuffle:true});

export const ARSURI_V2=[
q('arsuri-adv-001',['Arsurile epidermice (grad I):',
 ['se albesc la presiune și nu lasă cicatrice','au flictene destinse, cu conținut proteic','au escară avasculară, uscată și nedureroasă','au textură alb-cerată, cu durere redusă','necesită grefare în formele extensive'],'A',108,'Fiziopatologia leziunilor din arsură',
 'Recunoașterea arsurii epidermice.',
 ['Hiperemia se albește, iar cicatrizarea din derm lipsește.','Descrie gradul II superficial.','Descrie gradul III.','Descrie gradul II profund.','Necesită doar tratament suportiv.']],
 [8,'Distractorii descriu celelalte grade de profunzime.'],['digitopresiune','epidermul'],[109]),

q('arsuri-adv-032',['Arsurile epidermice extensive:',
 ['au efecte fiziologice limitate','se tratează suportiv, cu analgezice și hidratare orală','se vindecă în câteva zile, prin exfoliere','necesită resuscitare după formula Consensus','se includ în calculul %SCT arse'],'ABC',109,'Arsurile epidermice',
 'Aplicarea conduitei în arsurile epidermice.',
 ['Efectele fiziologice sunt limitate.','Tratamentul este suportiv.','Epidermul se exfoliază în câteva zile.','Nu necesită resuscitare formală.','Doar gradele 2 și 3 intră în %SCT.']],
 [8,'Distractorii tratează gradul I ca arsură majoră.'],['neomicină','exfoliază'],[112]),

q('arsuri-adv-010',['Arsurile de profunzime parțială superficiale:',
 ['au flictene destinse cu lichid proteic','au dermul umed, care se albește la presiune','sunt foarte dureroase','au textură uscată, alb-cerată','nu se albesc la presiune directă'],'ABC',109,'Arsurile de profunzime parțială',
 'Recunoașterea arsurii de grad II superficial.',
 ['Flictenele conțin lichid proteic extravazat.','Dermul este umed și se albește.','Nervii din dermul profund sunt intacți.','Descrie gradul II profund.','Se albesc la presiune.']],
 [8,'Distractorii preiau trăsăturile formelor profunde.'],['flictene destinse','dureros']),

q('arsuri-adv-051',['Arsurile de profunzime parțială profunde:',
 ['au adesea textură uscată, alb-cerată','sunt mai puțin dureroase decât cele superficiale','se tratează de regulă prin excizie și grefare','se pot vindeca din anexele epidermale supraviețuitoare','se vindecă fără cicatrice, dermul regenerându-se'],'ABCD',109,'Arsurile de profunzime parțială',
 'Recunoașterea arsurii de grad II profund.',
 ['Necroza de coagulare dă textură uscată, alb-cerată.','Multe terminații nervoase sunt distruse.','Excizia urmată de grefare este conduita corectă.','Anexele pătrund profund în derm.','Dermul nu se regenerează, apare cicatrice.']],
 [8,'Singurul distractor contrazice lipsa de regenerare a dermului.'],['alb-cerate','grefare'],[108]),

q('arsuri-adv-011',['În arsurile de profunzime parțială superficiale, escara se detașează în:',
 ['10–14 zile','24–48 de ore','3–4 săptămâni','2–3 luni','5–7 zile'],'A',109,'Escara',
 'Aplicarea evoluției escarei în arsurile superficiale.',
 ['Detașarea are loc în 10–14 zile, cu muguri epiteliali.','Este intervalul formării escarei.','Nu este intervalul citat.','Nu este intervalul citat.','Nu este intervalul citat.']],
 [8,'Distractorii sunt intervale plauzibile.'],['10-14 zile','muguri']),

q('arsuri-adv-012',['Arsurile de toată grosimea (grad III):',
 ['au escară uscată, avasculară și nedureroasă','pot produce retracție tip garou a extremității','prin lichide fierbinți pot avea culoare vișinie','se albesc la presiune directă, ca gradul II','extinse se vindecă spontan, prin anexele restante'],'ABC',110,'Arsurile de toată grosimea',
 'Recunoașterea arsurii de grad III.',
 ['Terminațiile nervoase sunt distruse.','Contracția proteinelor dermice produce garou.','Culoarea vișiniu închis apare la lichidele fierbinți.','Nu se albesc la presiune.','Leziunile extinse necesită grefare.']],
 [8,'Distractorii preiau trăsăturile gradului II.'],['garou','vişiniu']),

q('arsuri-adv-052',['Termenul de „arsură de grad patru” descrie leziunile care:',
 ['se extind în profunzime până la os','interesează dermul profund și anexele','sunt produse de curentul electric','depășesc 50% din SCT','afectează căile aeriene'],'A',110,'Arsurile de toată grosimea',
 'Recunoașterea categoriei de grad IV.',
 ['Gradul IV se extinde până la os.','Descrie gradul II profund.','Nu definește gradul IV.','Nu definește gradul IV.','Nu definește gradul IV.']],
 [8,'Distractorii confundă profunzimea cu etiologia sau extinderea.'],['grad patru','os']),

q('arsuri-adv-006',['Leziunile inhalatorii:',
 ['pot cauza morbiditate mai mare decât arsurile cutanate','apar mai ales în incendiile din spații închise','pot fi silențioase în primele 24–48 de ore','impun intubație și PEEP ca tratament suportiv','sunt de regulă evidente clinic de la prezentare'],'ABCD',110,'Fiziopatologia leziunilor inhalatorii',
 'Recunoașterea leziunilor inhalatorii.',
 ['Morbiditatea poate depăși arsura cutanată.','Spațiul închis este contextul tipic.','Simptomele pot lipsi 24–48 de ore.','Intubația și PEEP sunt esențiale.','Sunt adesea mai puțin aparente la prezentare.']],
 [8,'Singurul distractor contrazice caracterul insidios.'],['spaţiu închis','PEEP'],[112]),

q('arsuri-adv-002',['Intoxicația cu monoxid de carbon la ars:',
 ['e principala cauză de deces imediat în incendii','nu este detectată corect de puls-oximetrie','se tratează cu oxigen 100% cât mai precoce','afectează mai ales rinichiul și ficatul, nu creierul','se confirmă prin puls-oximetrie normală'],'ABC',110,'Intoxicația cu CO',
 'Recunoașterea și tratamentul intoxicației cu CO.',
 ['Este principala cauză de deces imediat în clădiri.','Este necesară gazometria cu saturație directă.','Oxigenul 100% se începe cât mai repede.','Inima și creierul sunt cele mai vulnerabile.','Puls-oximetria nu detectează intoxicația.']],
 [8,'Distractorii inversează organele țintă și rolul puls-oximetriei.'],['puls-oximetria','100%']),

q('arsuri-adv-034',['Terapia cu oxigen hiperbar în intoxicația cu CO:',
 ['la 3 atmosfere dă o PaO2 de ~1.500 mm Hg','scade timpul de înjumătățire al COHb la ~20 de minute','se indică mai ales la simptome neurologice acute','prelungește timpul de înjumătățire al COHb','are prioritate față de resuscitarea volemică'],'ABC',111,'Intoxicația cu CO',
 'Aplicarea oxigenoterapiei hiperbare.',
 ['PaO2 ajunge la 1.500 mm Hg.','De la 80 la ~20 de minute.','Simptomele neurologice cer scădere rapidă.','Scurtează timpul de înjumătățire.','Se integrează cu celelalte priorități.']],
 [8,'Distractorii inversează efectul și prioritatea.'],['80 de minute','hiperbar'],[110]),

q('arsuri-adv-053',['Conform Tabelului 10-1:',
 ['COHb 20–30% produce cefalee pulsatilă temporală','COHb 50–60% poate produce respirație Cheyne-Stokes','COHb 80–90% produce deces într-o oră','COHb până la 10% poate fi normală la fumători','COHb 10–20% produce comă și convulsii'],'ABCD',111,'Tabelul 10-1',
 'Corelarea nivelului COHb cu simptomele.',
 ['20–30%: cefalee pulsatilă temporală.','50–60%: Cheyne-Stokes, comă, convulsii.','80–90%: deces într-o oră.','Fumătorii pot avea până la 10%.','10–20% dă cefalee moderată.']],
 [8,'Singurul distractor mută simptomele severe la valori mici.'],['Cheyne-Stokes','tâmplelor']),

q('arsuri-adv-035',['Un tânăr cu arsuri faciale profunde după o explozie respiră normal la 45 de minute. Conduita imediată este:',
 ['intubația profilactică precoce','observație până la apariția stridorului','oxigen pe mască și reevaluare la 24 de ore','bronhoscopie amânată la 48 de ore','traheostomie de principiu'],'A',111,'Arsurile căilor aeriene superioare',
 'Aplicarea securizării precoce a căilor aeriene.',
 ['Edemul facial progresează rapid; intubația precoce e esențială.','Așteptarea riscă obstrucția.','Edemul se instalează în primele ore.','Nu securizează calea aeriană.','Nu este conduita citată.']],
 [8,'Distractorii amână securizarea căii aeriene.'],['intubarea profilactică','edem facial masiv']),

q('arsuri-adv-013',['Intoxicația cu cianură la ars:',
 ['rezultă mai ales din arderea plasticului','produce acidoză metabolică persistentă','se tratează cu hidroxicobalamină','răspunde prompt la resuscitarea lichidiană','se tratează cu oxigen hiperbar ca antidot'],'ABC',112,'Leziunile căilor respiratorii inferioare',
 'Recunoașterea intoxicației cu cianură.',
 ['Cianura rezultă din arderea plasticului.','Acidoza persistă sub resuscitare.','Hidroxicobalamina colorează urina violet.','Acidoza nu răspunde la lichide.','Antidotul citat este hidroxicobalamina.']],
 [8,'Distractorii contrazic semnul distinctiv și antidotul.'],['hidroxicobalamină','violet']),

q('arsuri-adv-036',['Oprirea procesului de ardere:',
 ['se face înaintea oricărei măsuri terapeutice','presupune răcirea cu apă a lichidelor vâscoase','presupune diluarea causticelor cu multă apă','impune oprirea sursei de curent înainte de abordare','permite masca de oxigen pe haina care mocnește'],'ABCD',112,'Oprirea procesului de ardere',
 'Aplicarea primelor măsuri la ars.',
 ['Oprirea arderii precedă orice tratament.','Smoala și plasticele se răcesc cu apă.','Causticele se diluează cu multă apă.','Victima poate conduce curentul.','Masca poate reaprinde îmbrăcămintea.']],
 [8,'Singurul distractor ignoră riscul de reaprindere.'],['mocnit','smoala']),

q('arsuri-adv-037',['La arsul cu leziuni aparent majore, calculul formal al necesarului de lichide se face:',
 ['după evaluarea secundară','înaintea evaluării ABC','după aplicarea cremelor antibiotice','după prima grefare','la 24 de ore de la internare'],'A',112,'Resuscitarea',
 'Aplicarea secvenței evaluării arsului.',
 ['Calculul se amână după evaluarea secundară.','ABC are prioritate.','Cremele nu se aplică înainte de evaluare.','Resuscitarea precedă grefarea.','Resuscitarea nu se amână.']],
 [8,'Distractorii dereglează ordinea priorităților.'],['evaluarea secundară','Foley']),

q('arsuri-adv-014',['Estimarea suprafeței arse:',
 ['exclude arsurile epidermice (grad 1)','poate folosi palma pacientului, cu degete, ca 1%','poate folosi regula lui 9 sau diagrama Lund-Browder','se face înaintea examenului fizic complet','folosește palma examinatorului ca 5% SCT'],'ABC',112,'Evaluarea secundară',
 'Aplicarea metodelor de estimare a %SCT.',
 ['Doar gradele 2 și 3 se includ.','Palma pacientului ≈1% SCT.','Ambele metode sunt citate.','Se face după evaluarea secundară.','Se folosește palma pacientului, ≈1%.']],
 [8,'Distractorii schimbă referința și momentul.'],['regula lui 9','Lund']),

q('arsuri-adv-015',['Conform diagramei Lund și Browder:',
 ['capul reprezintă 19% din SCT la naștere','capul reprezintă 7% din SCT la adult','coapsa crește procentual odată cu vârsta','toracele anterior scade procentual cu vârsta','medicii fără experiență subestimează aria'],'ABC',113,'Figura 10-7',
 'Aplicarea diagramei Lund și Browder.',
 ['Capul: 19% la naștere.','Capul: 7% la adult.','Coapsa: 5½% → 9½%.','Toracele anterior rămâne 13%.','Tendința este de supraevaluare.']],
 [8,'Distractorii inversează tendința și constanța toracelui.'],['Lund','supraevalua']),

q('arsuri-adv-016',['Conform Tabelului 10-2, criterii de transfer către centrul de arsuri sunt:',
 ['arsura de grad 2 peste 10% SCT','arsurile feței, mâinilor sau perineului','arsurile de grad 3 la orice vârstă','arsurile chimice și electrice','arsura de grad 2 de 5% SCT la trunchi'],'ABCD',114,'Tabelul 10-2',
 'Aplicarea criteriilor de transfer.',
 ['Peste 10% SCT de grad 2.','Zonele speciale sunt criteriu.','Gradul 3 la orice vârstă.','Chimice și electrice, inclusiv fulgerul.','Nu întrunește niciun criteriu.']],
 [8,'Singurul distractor nu întrunește criteriile.'],['articulaţile majore','fulger']),

q('arsuri-adv-039',['Conform Tabelului 10-2, justifică transferul și:',
 ['comorbiditățile care complică managementul','trauma asociată, când arsura are riscul cel mai mare','copiii din spitale fără echipament pediatric','nevoia de reabilitare socială și emoțională','arsura solară epidermică extinsă, fără flictene'],'ABCD',114,'Tabelul 10-2',
 'Aplicarea criteriilor de transfer 7–10.',
 ['Comorbiditățile sunt criteriu.','Trauma asociată este criteriu.','Copiii fără resurse locale sunt criteriu.','Reabilitarea specială este criteriu.','Gradul I nu este criteriu.']],
 [8,'Singurul distractor este o arsură epidermică.'],['reintegrare socială','preexistente']),

q('arsuri-adv-017',['Resuscitarea lichidiană în arsuri:',
 ['devine necesară formal la arsuri ≥10–15% SCT','peste 15–20% SCT, pierderea capilară devine sistemică','folosește inițial cristaloizi izotoni','folosește inițial coloizi, capilarele fiind impermeabile','oprește extravazarea spre interstițiu'],'ABC',114,'Perioada de resuscitare',
 'Aplicarea principiilor resuscitării arsului.',
 ['≥10–15% SCT cer resuscitare formală.','≥15–20% SCT produc șoc post-combustional.','Cristaloizii izotoni sunt preferați.','Capilarele sunt permeabile la proteine.','Nu oprește extravazarea.']],
 [8,'Distractorii inversează permeabilitatea și efectul.'],['post-combustional','10-15%'],[115]),

q('arsuri-adv-003',['Formula Consensus:',
 ['calculează 2–4 mL Ringer lactat/kg/%SCT pe 24 de ore','administrează jumătate din volum în primele 8 ore','dă câte un sfert în turele 2 și 3 de 8 ore','indică un volum fix, neajustat după diureză','administrează jumătate din volum în ultimele 8 ore'],'ABC',115,'Tabelul 10-3',
 'Aplicarea formulei Consensus.',
 ['2–4 mL × kg × %SCT.','Jumătate în primele 8 ore.','Câte un sfert în turele următoare.','Formula indică doar punctul de pornire.','Jumătatea se dă primele 8 ore.']],
 [8,'Distractorii contrazic dinamica resuscitării.'],['Consensus','Ringer lactat'],[114]),

q('arsuri-adv-041',['Un bărbat de 100 kg are arsuri pe 65% SCT. Cu formula Consensus minimă (2 mL/kg/%SCT), rata în primele 8 ore este de aproximativ:',
 ['812 mL/oră','406 mL/oră','1.625 mL/oră','1.083 mL/oră','3.250 mL/oră'],'A',115,'Tabelul 10-3',
 'Calculul ratei inițiale după formula Consensus.',
 ['13.000 mL/24 h; 6.500 mL în 8 ore = 812 mL/oră.','Este rata turelor 2 și 3.','Este rata maximă (4 mL).','Este volumul împărțit egal pe 24 h.','Nu este o rată orară.']],
 [8,'Distractorii sunt erori de calcul plauzibile.'],['812','13.000']),

q('arsuri-adv-040',['Debitul urinar-țintă în resuscitarea Consensus la adult este:',
 ['≥30 mL/oră','≥100 mL/oră','≥0,5 mL/kg/oră','≥5 mL/oră','≥200 mL/oră'],'A',114,'Perioada de resuscitare',
 'Aplicarea țintei de diureză în resuscitarea arsului.',
 ['≥30 mL/oră la adult.','Este ținta din mioglobinurie.','Nu este ținta citată.','Este insuficient.','Nu este ținta citată.']],
 [8,'Distractorii sunt ținte din alte contexte.'],['30','1-1,5']),

q('arsuri-adv-018',['Ajustarea ratei de infuzie în resuscitarea arsului:',
 ['la scăderea diurezei, rata crește cu 10–20%','diureticele nu se folosesc de rutină la oligurie','după stabilizare, rata scade cu 10–15%/oră','la oligurie se administrează furosemid întâi','rata inițială rămâne fixă 24 de ore'],'ABC',115,'Tabelul 10-3',
 'Aplicarea ajustării dinamice a resuscitării.',
 ['Rata crește cu 10–20%.','Majoritatea experților nu folosesc diuretice.','Rata scade cu 10–15%/oră.','Diureticul nu este soluția.','Rata se ajustează după răspuns.']],
 [8,'Distractorii folosesc diuretice și volume fixe.'],['10-20%','diuretic']),

q('arsuri-adv-005',['Escarotomia:',
 ['tratează circulația compromisă în arsura circumferențială','nu reduce edemul, ci compresia produsă de acesta','se poate face și la nivelul toracelui','reduce direct formarea edemului din primele ore','lasă de obicei cicatrici suplimentare inestetice'],'ABC',116,'Escarotomia',
 'Aplicarea escarotomiei.',
 ['Incizia escarei restabilește circulația.','Tratează compresia, nu edemul.','Escarotomiile toracice sunt posibile.','Nu reduce edemul.','Se face prin țesut ars, fără cicatrici suplimentare.']],
 [8,'Distractorii atribuie escarotomiei efecte greșite.'],['escarotomia','toracelui']),

q('arsuri-adv-043',['La arsul resuscitat cu edem masiv:',
 ['fasciotomia poate fi necesară în arsurile foarte profunde','fasciotomia este mai frecventă în electrocuția de înaltă tensiune','poate apărea sindrom de compartiment abdominal','sindromul de compartiment abdominal se tratează cu diuretic','escarotomia este indicată la presiuni sub 5 cm H2O'],'ABC',116,'Escarotomia și fasciotomia',
 'Recunoașterea sindroamelor de compartiment la ars.',
 ['Fasciotomia decomprimă când escarotomia nu ajunge.','Este mai frecventă la înaltă tensiune.','Acumularea abdominală poate cere laparotomie.','Se tratează prin laparotomie.','Presiunea măsurată a fost peste 30 cm H2O.']],
 [8,'Distractorii inversează tratamentul și pragul.'],['fasciotomii','laparotomie']),

q('arsuri-adv-042',['Leziunea inhalatorie și SDRA la ars:',
 ['cresc frecvent necesarul de fluide','SDRA are aspect de „geam mat” radiologic','ventilația folosește volume curente mici','necesarul de cristaloizi scade','resuscitarea excesivă ameliorează SDRA'],'ABC',116,'Suportul respirator',
 'Aplicarea resuscitării și ventilației în leziunea inhalatorie.',
 ['Pierderile oculte cresc necesarul.','Geamul mat definește radiologic SDRA.','Volumele mici reduc barotrauma.','Necesarul crește.','Resuscitarea excesivă agravează SDRA.']],
 [8,'Distractorii inversează necesarul și efectul fluidelor.'],['geam mat','volume curente']),

q('arsuri-adv-044',['Excizia fascială, comparativ cu cea tangențială:',
 ['se face relativ fără sângerare','asigură o rată bună de prindere a grefei','este mutilantă, cu rigiditate articulară','salvează elementele dermice intacte','are rezultate cosmetice adesea superioare'],'ABC',117,'Excizia leziunilor',
 'Compararea tehnicilor de excizie.',
 ['Excizia fascială sângerează puțin.','Prinderea grefei este bună.','Este mutilantă.','Tangențiala salvează dermul.','Tangențiala are rezultate superioare.']],
 [8,'Distractorii preiau avantajele exciziei tangențiale.'],['fascia','tangenţială']),

q('arsuri-adv-008',['Excizia precoce și acoperirea plăgii:',
 ['majoritatea centrelor practică excizia precoce','se amână de obicei până după resuscitare','acoperirea permanentă cere pielea proprie a pacientului','escara netratată se separă în câteva zile','excizia tangențială sângerează mai puțin'],'ABC',117,'Excizia leziunilor și grefarea pielii',
 'Aplicarea principiilor exciziei precoce.',
 ['Excizia precoce este preferată.','Se așteaptă stabilizarea volemică.','Autogrefa asigură acoperirea permanentă.','Separarea durează săptămâni sau luni.','Tangențiala sângerează semnificativ.']],
 [8,'Distractorii scurtează evoluția escarei și inversează sângerarea.'],['autogrefă','excizia precoce']),

q('arsuri-adv-020',['Grefele de piele:',
 ['grefa de grosime parțială are 0,1–0,38 mm','zona donatoare parțială se vindecă spontan în 7–14 zile','grefa de toată grosimea se recoltează inghinal sau din flanc','zona donatoare de toată grosimea se vindecă spontan','grefa parțială are tipic 2–3 mm grosime, cu tot dermul'],'ABC',117,'Grefarea pielii',
 'Diferențierea grefelor de grosime parțială și totală.',
 ['Grosimea tipică este 0,1–0,38 mm.','Zona donatoare se vindecă în 7–14 zile.','Se recoltează eliptic inghinal sau din flanc.','Zona donatoare se închide primar.','Dermul superficial doar.']],
 [8,'Distractorii inversează închiderea și grosimea.'],['0,38','7-14 zile']),

q('arsuri-adv-021',['Când autogrefele sunt insuficiente:',
 ['allogrefa de cadavru este cel mai folosit substitut','grefele perforate (mesh) acoperă suprafețe mai mari','culturile epidermale proprii sunt scumpe și fragile','dermul artificial nu mai necesită acoperire cu autogrefă','culturile epidermale sunt rezistente la infecție'],'ABC',117,'Grefarea pielii',
 'Recunoașterea substituenților de piele.',
 ['Allogrefa de cadavru este cea mai folosită.','Perforarea extinde acoperirea.','Sunt scumpe, fragile, sensibile la infecție.','Necesită acoperire cu autogrefe subțiri.','Sunt sensibile la infecție.']],
 [8,'Distractorii supraestimează substituenții.'],['allogrefa','culturile']),

q('arsuri-adv-058',['După arsură, suprafața pielii este teoretic sterilă timp de:',
 ['24–48 de ore','1–2 ore','7–10 zile','3 săptămâni','până la grefare'],'A',117,'Controlul infecției',
 'Aplicarea cineticii colonizării plăgii arse.',
 ['Sterilă 24–48 de ore, apoi se repopulează.','Nu este intervalul citat.','Nu este intervalul citat.','Nu este intervalul citat.','Recolonizarea începe mult înainte.']],
 [8,'Distractorii sunt intervale plauzibile.'],['24-48','repopulată']),

q('arsuri-adv-022',['Antimicrobienele topice în arsură:',
 ['nitratul de argint a fost primul topic răspândit','mafenidul și sulfadiazina au controlat gram-negativii','se reaplică de cel puțin două ori pe zi','rămân eficiente câteva zile după aplicare','sunt mai eficiente decât excizia precoce'],'ABC',118,'Controlul infecției',
 'Aplicarea tratamentului topic în arsuri.',
 ['Nitratul de argint a fost primul.','Au controlat gram-negativii.','Se reaplică cel puțin de două ori pe zi.','Sunt eficiente doar câteva ore.','Excizia precoce este cea mai eficientă.']],
 [8,'Distractorii supraestimează topicele.'],['Sulfamylon','două ori pe zi'],[117]),

q('arsuri-adv-045',['Infecțiile la arsul spitalizat:',
 ['pneumonia este una dintre cele mai comune infecții','sepsisul de plagă apare azi rar în centrele de arși','pot apărea tromboflebite septice pe catetere','sepsisul de plagă este cea mai frecventă cauză actuală de deces','bacteriile multirezistente au dispărut'],'ABC',118,'Controlul infecției',
 'Recunoașterea spectrului actual al infecțiilor la ars.',
 ['Pneumonia este acum printre cele mai comune.','Sepsisul de plagă apare rar azi.','Tromboflebita septică este citată.','Era cauza principală până recent.','Multirezistenții sunt patogeni importanți.']],
 [8,'Distractorii descriu situația istorică.'],['Pneumonia','Tromboflebita'],[117]),

q('arsuri-adv-023',['Suportul nutrițional la arsul major:',
 ['metabolismul poate depăși de două ori normalul','hrănirea enterală este superioară celei intravenoase','aportul proteic este 1,5–2 g/kg/zi','necesarul se estimează fiabil prin formule standard','excreția de azot scade după arsură'],'ABC',118,'Suportul nutrițional',
 'Aplicarea suportului nutrițional la ars.',
 ['Metabolismul poate depăși dublul normalului.','Enterala este net superioară.','1,5–2,0 g/kg/zi.','Nicio formulă nu e satisfăcătoare.','Excreția de azot crește.']],
 [8,'Distractorii supraestimează formulele și inversează azotul.'],['calorimetrie indirectă','1,5-2,0']),

q('arsuri-adv-029',['Reabilitarea după arsură:',
 ['începe la momentul leziunii','cicatricea se remodelează cel puțin un an','îmbrăcămintea compresivă previne cicatricile hipertrofice','măștile elastice sunt preferate la copii','începe după închiderea plăgilor'],'ABC',119,'Faza de reabilitare',
 'Aplicarea principiilor reabilitării arsului.',
 ['Reabilitarea începe la momentul leziunii.','Remodelarea durează cel puțin un an.','Compresia previne hipertrofia.','Deformează mandibula; se folosesc măști rigide.','Nu se așteaptă închiderea.']],
 [8,'Distractorii amână reabilitarea și preferă măștile elastice.'],['cicatricilor','un an'],[118]),

q('arsuri-adv-059',['După arsuri de 70% SCT sau mai mari, marea majoritate a pacienților:',
 ['se întorc la muncă sau la școală','rămân dependenți de îngrijire','necesită pensionare de invaliditate','nu mai pot purta îmbrăcăminte compresivă','rămân cu contracturi imobilizante'],'A',119,'Faza de reabilitare',
 'Aplicarea prognosticului funcțional după arsuri majore.',
 ['Marea majoritate revin la muncă sau școală.','Nu este prognosticul citat.','Nu este prognosticul citat.','Nu este prognosticul citat.','Contracturile se previn prin reabilitare.']],
 [8,'Distractorii subestimează recuperarea.'],['70% SCT','şcoală']),

q('arsuri-adv-046',['Arsurile chimice:',
 ['alcalinele pătrund mai profund, prin ionii de hidroxid','acizii produc escară mai puțin profundă','compușii organici dizolvă membranele celulare','acizii pătrund mai profund decât alcalinele','compușii organici nu au toxicitate sistemică'],'ABC',119,'Arsuri chimice',
 'Diferențierea claselor de agenți chimici.',
 ['Proteinatele alcaline pătrund profund.','Hidroliza acidă dă escară mai superficială.','Solvenții grăsimilor dizolvă membranele.','Alcalinele pătrund mai profund.','Toate clasele au risc sistemic.']],
 [8,'Distractorii inversează profunzimea și toxicitatea.'],['proteinaţi','hidroliză']),

q('arsuri-adv-060',['Tratamentul inițial al arsurii chimice:',
 ['impune protecția personalului înaintea îngrijirii','presupune perierea pulberilor uscate, apoi spălarea','poate fi ghidat de pH-ul soluției de irigație','alcalinele cer mai puține lichide decât acizii','arsurile acide sunt mai profunde decât par'],'ABC',119,'Arsuri chimice',
 'Aplicarea decontaminării în arsura chimică.',
 ['Personalul se protejează.','Pulberile se periază, apoi se spală.','pH-ul irigației indică eficiența.','Alcalinele cer mai multe lichide.','Acizii pot fi mai superficiali decât par.']],
 [8,'Distractorii inversează comportamentul acizilor și alcalinelor.'],['pH-ului','organofosfaţii']),

q('arsuri-adv-047',['Leziunile electrice:',
 ['de joasă tensiune sunt sub 1.000 V','de înaltă tensiune pot avea piele puțin afectată','lezează mai sever țesuturile de lângă os','se extind cel mai mult la mușchii superficiali','au extensia reală evidentă la inspecție'],'ABC',119,'Arsuri electrice',
 'Recunoașterea particularităților leziunii electrice.',
 ['Pragul este 1.000 V.','Pielea poate fi puțin afectată.','Țesuturile de lângă os rețin căldura.','Mușchii superficiali pot părea intacți.','Extensia poate fi imposibil de apreciat inițial.']],
 [8,'Distractorii inversează distribuția leziunii.'],['joasă tensiune','oaselor']),

q('arsuri-adv-061',['În leziunea electrică, curentul străbate preferențial:',
 ['nervii, vasele și mușchii','tegumentul și țesutul adipos subcutanat','osul cortical','tendoanele și fascia','epidermul superficial'],'A',119,'Arsuri electrice',
 'Explicarea traiectului curentului.',
 ['Țesuturile cu rezistență mică: nervi, vase, mușchi.','Pielea are rezistență ridicată.','Nu este traiectul citat.','Nu este traiectul citat.','Nu este traiectul citat.']],
 [8,'Distractorii sunt țesuturi cu rezistență mare.'],['vase de sânge','rezistenţă']),

q('arsuri-adv-024',['La victima electrocuției:',
 ['se efectuează ECG la toate victimele','se monitorizează 24 h la înaltă tensiune','se tratează ca politraumatizat, prin risc de cădere','se renunță la ECG dacă tegumentul e intact','aritmiile sunt rare și neimportante'],'ABC',120,'Arsuri electrice',
 'Aplicarea monitorizării după electrocuție.',
 ['ECG la toate victimele.','Telemetrie cel puțin 24 de ore.','Căderile și contracțiile tetanice cer imobilizare.','ECG-ul se face indiferent de piele.','Fibrilația ventriculară este cauză de deces.']],
 [8,'Distractorii subestimează riscul cardiac.'],['telemetrie','24 de ore']),

q('arsuri-adv-007',['Rabdomioliza după electrocuția de înaltă tensiune:',
 ['colorează urina ca ceaiul','impune diureză de ≥100 mL/oră','nu are beneficiu dovedit al bicarbonatului și manitolului','impune diureză de 30 mL/oră','are manitolul ca tratament de rutină dovedit'],'ABC',120,'Arsuri electrice',
 'Aplicarea conduitei în mioglobinurie.',
 ['Urina cu mioglobină are culoarea ceaiului.','Ținta este ≥100 mL/oră.','Studiile prospective nu au arătat eficiență.','Este ținta din arsura termică.','Nu s-a dovedit eficient.']],
 [8,'Distractorii preiau ținta arsurii termice și supraestimează adjuvanții.'],['ceaiului','100 mL/oră']),

q('arsuri-adv-048',['Leziunile prin fulger:',
 ['sunt electrocuții prin curent continuu de voltaj înalt','pot produce ruptura timpanului','se pot complica tardiv cu cataractă','produc doar arsuri superficiale de flacără','nu produc neuropatie periferică'],'ABC',120,'Arsuri electrice',
 'Recunoașterea leziunilor prin fulger.',
 ['Curent continuu de voltaj înalt.','Explozia poate rupe timpanul.','Cataracta este complicație tardivă.','Explozia poate produce traume semnificative.','Neuropatia periferică este complicație tardivă.']],
 [8,'Distractorii minimizează leziunea.'],['fulger','timpanului']),

q('arsuri-adv-025',['Arsura minoră:',
 ['peste 75% dintre prezentări sunt sub 10% SCT','la copil și vârstnic, arsura minoră este sub 5% SCT','apa de robinet la 12–25°C reduce leziunea','gheața reduce necroza în modelele experimentale','dimensiunea este de regulă subestimată'],'ABC',120,'Arsurile minore',
 'Aplicarea îngrijirii arsurii minore.',
 ['Peste 75% sunt minore.','Pragul este 5% SCT la copil și vârstnic.','Apa de 12–25°C reduce dauna și durerea.','Gheața crește necroza.','Dimensiunea este supraestimată.']],
 [8,'Distractorii inversează efectul gheții și estimarea.'],['12-25°C','75%']),

q('arsuri-adv-064',['Îngrijirea topică a arsurii minore:',
 ['arsurile epidermice fără flictene nu necesită topice','flictenele rupte se îndepărtează','antibioticele orale nu sunt necesare fără infecție','pansamentele noi cu argint se schimbă mai des','nitratul de argint rămâne activ zile în plagă'],'ABC',120,'Arsurile minore',
 'Aplicarea îngrijirii locale a arsurii minore.',
 ['Nu necesită îngrijire topică.','Flictenele rupte se îndepărtează.','Antibioticele orale nu sunt necesare.','Se schimbă mai rar.','Este inactivat în plagă.']],
 [8,'Distractorii inversează intervalul de schimbare și durata de acțiune.'],['flictenele','argint']),

q('arsuri-adv-026',['Arsurile a căror vindecare durează mai mult de 3 săptămâni:',
 ['formează cicatrici hipertrofice','se vindecă fără cicatrice','nu mai necesită excizie','devin arsuri de grad IV','sunt de obicei arsuri superficiale de grad II'],'A',121,'Arsurile minore',
 'Aplicarea pragului de 3 săptămâni pentru excizie.',
 ['Formează cicatrici hipertrofice și epiteliu instabil.','Formează cicatrici.','Excizia precoce este optimă.','Gradul IV este definit anatomic.','Superficialele se vindecă mai repede.']],
 [8,'Distractorii contrazic riscul de cicatrizare.'],['3 săptămâni','hipertrofice']),

q('arsuri-adv-027',['Analgezia arsului acut:',
 ['opioidele sunt baza analgeziei acute','calea intravenoasă este preferată în resuscitare','analgezicele se dau programat, înainte de accentuarea durerii','calea intramusculară este preferată în resuscitare','benzodiazepinele au efect analgezic suficient'],'ABC',121,'Tratamentul durerii',
 'Aplicarea analgeziei la ars.',
 ['Morfina este cea mai folosită.','Calea IV este preferată.','Programarea este cea mai eficientă.','Absorbția IM este imprevizibilă.','Nu au efect analgezic suficient.']],
 [8,'Distractorii preferă calea IM și benzodiazepinele.'],['Morfina','intramusculară']),

q('arsuri-adv-065',['Conform Tabelului 10-4:',
 ['ketamina se asociază cu delir și coșmaruri','propofolul cere suport al căilor respiratorii','clonidina nu se folosește ca agent unic','oxicodona e mai puternică decât morfina','benzodiazepinele sunt suficiente ca analgezice'],'ABC',121,'Tabelul 10-4',
 'Recunoașterea particularităților analgezicelor și sedativelor.',
 ['Ketamina dă delir și coșmaruri.','Propofolul necesită suportul căilor respiratorii.','Clonidina nu este agent unic.','Este mai puțin puternică.','Nu au efect analgezic suficient.']],
 [8,'Distractorii inversează potența și efectul analgezic.'],['Ketamină','Propofol']),

q('arsuri-adv-066',['Metodele nefarmacologice pentru durerea arsului:',
 ['tehnicile cognitive pot reduce durerea','realitatea virtuală a redus durerea la pansamente','hipnoza combină relaxarea, imaginația și cogniția','realitatea virtuală presupune imersia totală','distragerea atenției accentuează durerea'],'ABC',122,'Tratamentul durerii',
 'Aplicarea metodelor nefarmacologice.',
 ['Tehnicile cognitive sunt citate.','Realitatea virtuală a redus durerea.','Hipnoza este definită astfel.','Suprapune imagini pe lumea fizică.','Distragerea ajută.']],
 [8,'Distractorii contrazic definiția și efectul.'],['realitate virtuală','Hipnoza']),

q('arsuri-adv-049',['Pruritul după arsură:',
 ['afectează moderat-sever ~50% dintre pacienți','apare și în arsurile sub 2% SCT','poate persista până la 12 ani','răspunde bine la tratament la majoritatea','dispare de obicei în câteva săptămâni'],'ABC',122,'Pruritul',
 'Recunoașterea pruritului post-arsură.',
 ['50% au prurit moderat-sever.','Apare în 32% din arsurile <2% SCT.','Poate persista 12 ani.','Doar 36% au raportat beneficiu.','Persistă ani.']],
 [8,'Distractorii subestimează durata și rezistența la tratament.'],['12 ani','36%']),

q('arsuri-adv-050',['Necroliza epidermică toxică și sindromul Stevens-Johnson:',
 ['NET are descuamare peste 30% din SC','SSJ are afectare sub 10% din SC','80% din NET sunt produse de medicamente','semnul Nikolsky este frecvent','SSJ are descuamare peste 30% din SC'],'ABCD',122,'Afecțiunile cutanate',
 'Diferențierea NET de SSJ.',
 ['NET: >30%.','SSJ: <10%.','80% sunt medicamentoase.','Nikolsky este frecvent.','Pragul de 30% definește NET.']],
 [8,'Singurul distractor inversează pragurile.'],['Nikolsky','80%']),

q('arsuri-adv-067',['Mecanismul imun al NET/SSJ constă în:',
 ['distrugerea celulelor bazale de către CD8+','infecție stafilococică invazivă a fasciei superficiale','degranulare mastocitară mediată de IgE','depunere de complexe imune în derm','toxicitate directă asupra melanocitelor'],'A',122,'Afecțiunile cutanate',
 'Explicarea mecanismului NET/SSJ.',
 ['CD8+ și macrofagele distrug celulele bazale.','Nu este mecanismul citat.','Nu este mecanismul citat.','Nu este mecanismul citat.','Nu este mecanismul citat.']],
 [8,'Distractorii sunt alte mecanisme de hipersensibilitate.'],['CD8','grefă-versus-gazdă']),

q('arsuri-adv-068',['Tabloul și diagnosticul NET/SSJ:',
 ['debutează cu o fază prodromală de tip viroză','poate afecta orice mucoasă','se confirmă prin biopsie de la marginea leziunii','începe terapeutic cu oprirea agentului declanșator','cruță de regulă mucoasa orală și oculară'],'ABCD',122,'Afecțiunile cutanate',
 'Recunoașterea tabloului NET/SSJ.',
 ['Febra și starea de rău preced erupția.','Orice mucoasă poate fi afectată.','Biopsia distinge de alte afecțiuni.','Oprirea agentului începe tratamentul.','Mucoasele sunt frecvent afectate.']],
 [8,'Singurul distractor contrazice afectarea mucoaselor.'],['prodromală','biopsia']),

q('arsuri-adv-069',['Tratamentul necrolizei epidermice toxice:',
 ['se face optim pe protocol într-un centru de arși','evită agenții topici sulfamidici, implicați etiologic','impune consult oftalmologic la debut','beneficiază de steroizi după descuamare','beneficiază de imunoglobulină, cu eficiență dovedită'],'ABC',123,'Afecțiunile cutanate',
 'Aplicarea tratamentului NET.',
 ['Protocolul într-un centru experimentat face diferența.','Sulfamidele sunt implicate etiologic.','Conjunctivita trebuie tratată precoce.','Nu au îmbunătățit supraviețuirea.','Studiile clinice nu au arătat beneficiu.']],
 [8,'Distractorii supraestimează terapiile sistemice.'],['sulfamidă','oftalmologică']),

q('arsuri-adv-028',['Sunt factori de risc de deces în NET:',
 ['vârsta peste 40 de ani','malignitatea asociată','bicarbonatul seric sub 20 mEq/L','frecvența cardiacă peste 120/minut','descuamarea sub 10% SCT'],'ABCD',123,'Afecțiunile cutanate',
 'Recunoașterea factorilor de prognostic în NET.',
 ['Vârsta >40 de ani.','Malignitatea.','Acidoza cu bicarbonat <20 mEq/L.','FC >120/minut.','Riscul crește la descuamare >10%.']],
 [8,'Singurul distractor inversează pragul de descuamare.'],['40 de ani','120']),

q('arsuri-adv-070',['Sechelele pe termen lung ale NET includ:',
 ['simblefaronul','fimoza','pierderea plăcilor unghiale','sinechiile vaginale','alopecia cicatricială'],'ABCD',123,'Afecțiunile cutanate',
 'Recunoașterea sechelelor NET.',
 ['Simblefaronul este citat.','Fimoza este citată.','Pierderea unghiilor este citată.','Sinechiile vaginale sunt citate.','Nu este citată.']],
 [8,'Singurul distractor nu figurează printre sechele.'],['simblefaron','fimoză']),
];
