import {advancedQuestion} from './advanced-author';
import type {SourceRow} from './source-author';
const pdfOffset=(p:number)=>p-182;
const q=(n:number,row:SourceRow,score:number,reason:string,expressions:string[],related:number[]=[])=>
 advancedQuestion('ati',10,pdfOffset,`ati-adv-${String(n).padStart(3,'0')}`,row,[score,reason],expressions,undefined,related);

export const ATI_D=[
q(39,['Cel mai sensibil indicator clinic al creșterii dificultății respiratorii, potrivit capitolului, este:',
 ['Creșterea frecvenței respiratorii','O SpO2 normală la pacientul cu oxigen suplimentar','Prezența constantă a pulsului paradoxal','Un VEM crescut pe pulsoximetru','Normalizarea PaCO2 în hipoventilație'],'A',225,'Insuficiența respiratorie — Evaluare clinică',
 'Reținerea tahipneei ca semnul cel mai sensibil, distinct de pulsul paradoxal (rar) și de falsa liniștire a SpO2.',
 ['Creșterea frecvenței respiratorii este numită cel mai sensibil indicator clinic.','SpO2 normală pe oxigen nu exclude hipoventilația cu retenție de CO2.','Pulsul paradoxal este rareori prezent, nu este indicatorul cel mai sensibil.','VEM nu se măsoară cu pulsoximetrul.','În hipoventilație PaCO2 crește, nu se normalizează.']],
 8,'Distractorii sunt limite reale ale pulsoximetriei și ale pulsului paradoxal, ușor de confunda cu „cel mai sensibil” semnal.',['Cel mai sensibil indicator clinic','frecvenţei respiratorii']),

q(40,['Indicele de respirație rapidă superficială (frecvență/volum curent), ca predictor al extubării, este interpretat astfel:',
 ['Un scor sub 100 este un predictor relativ bun al reușitei extubării, întâlnit la pacientul care respiră ușor, confortabil, cu volum curent adecvat, cu condiția să fie îndeplinite și celelalte precondiții','Un scor peste 400 permite extubarea fără a verifica tusea sau protecția căii aeriene','Valoarea 100 contraindică orice tentativă de respirație spontană','Indicele înlocuiește gazele sanguine și mecanica pulmonară','Se calculează doar la pacientul obnubilat, fără cale aeriană protejată'],'A',232,'Extubarea — Indicele de respirație rapidă superficială',
 'Reținerea pragului <100 ca predictor condiționat, nu ca substitut al protecției căii aeriene.',
 ['<100, respirația ușoară cu Vt adecvat și condiționarea de celelalte precondiții sunt fraza din text.','Un scor mare sugerează respirație rapidă superficială, nu succes; tusea și protecția rămân necesare.','100 nu contraindică tentativa de respirație spontană.','Gazele și mecanica rămân criterii obiective paralele.','Obnubilatul fără protecție nu este candidatul de extubare pe baza indicelui.']],
 8,'Distractorii ridică indicele <100 la rang de criteriu suficient sau inversat, contrar condiționării explicite din text.',['mai mic de 100','predictor relativ bun']),

q(41,['Capnografia, în utilizările din capitol, include:',
 ['Confirmarea intubației traheale','Monitorizarea continuă a PCO2 end-tidal, care aproximează PaCO2 la pacienții normali și evaluează eficacitatea ventilației','Detectarea problemelor acute ale căilor aeriene (canulă/traheostomă blocate sau dislocate), esențială doar la pacientul stabil, nu la canula blocată','Înlocuirea gazelor arteriale la pacientul cu BPOC, bulele de aer neinfluențând PCO2','Confirmarea doar a poziției gastrice a sondei, fără rol în intubație'],'AB',225,'Capnografia',
 'Reținerea perechii intubație / end-tidal, distinct de substituirea gazelor arteriale.',
 ['Confirmarea intubației deschide lista de utilizări.','End-tidal ca aproximare a PaCO2 la normali este a doua utilizare.','Detectarea canulei blocate/dislocate, inclusiv în transport, este o utilizare reală, nu una rezervată pacientului stabil.','Gazele arteriale rămân necesare; bulele scad PCO2-ul probei.','Capnografia confirmă intubația traheală, nu poziția gastrică.']],
 8,'Distractorii mută capnografia pe sondă gastrică, o rezervă pacientului stabil și o transformă într-un substitut al gazelor.',['confirmarea intubaţiei traheale','end-tidal PCO2']),

q(42,['Pneumotoracele în tensiune la pacientul ventilat, în semnele din capitol, se recunoaște prin:',
 ['Dezvoltarea sau agravarea hipoxiei, hipercapniei, detresei respiratorii și o creștere inexplicabilă a presiunii în căile aeriene','Hipotensiune și tahicardie, uneori cu creșterea PVC','Examen: expansiune inegală, deplasare mediastinală de partea pneumotoracelui (trahee deviată, șoc apexian deplasat) și hipersonoritate a unui hemitorace','Murmur vezicular intensificat de partea leziunii, mediastinul deplasându-se contralateral','TA crescută cu bradicardie, presiunea în căile aeriene scăzând inexplicabil'],'ABC',228,'Complicațiile ventilației — Pneumotoracele în tensiune',
 'Asocierea hipoxie/presiune de cale crescută, a hipotensiunii cu PVC crescută și a deplasării mediastinale ipsilaterale descrise în text.',
 ['Hipoxie, hipercapnie, detresă și presiune de cale inexplicabil crescută deschid semnele.','Hipotensiunea, tahicardia și PVC-ul crescut sunt hemodinamica.','Expansiunea inegală, deplasarea mediastinală și hipersonoritatea sunt ale examenului.','Textul plasează deplasarea mediastinală de partea pneumotoracelui; murmurul este frecvent diminuat, nu intensificat.','Hipotensiune cu tahicardie, nu HTA cu bradicardie; presiunea de cale crește, nu scade.']],
 8,'Distractorii inversează deplasarea mediastinală și transformă hipotensiunea/tahicardia în HTA/bradicardie.',['pneumotorace în tensiune','creştere inexplicabilă a presiunii']),

q(43,['Efectele cardiovasculare și leziunile pulmonare asociate ventilației cu presiune pozitivă, potrivit capitolului, includ:',
 ['Presiunea pozitivă împiedică întoarcerea venoasă și destinde alveolele, „întinzând” capilarele pulmonare și crescând rezistența vasculară pulmonară; ambele mecanisme pot scădea debitul cardiac','Tradițional, colapsul alveolar periferic era prevenit cu volume curente de 10-12 ml/kg, dar presiunile înalte și supradistensia, plus deschiderea/închiderea repetată a căilor distale, pot distruge membrana alveolo-capilară','Creșterea permeabilității microvasculare și eliberarea de mediatori produc leziuni pulmonare asociate ventilatorului (barotraumă și volutraumă), cu pneumomediastin, emfizem subcutanat, pneumotorace și pneumoperitoneu','Riscul de pneumotorace este crescut în pneumonia necrotizantă, emfizem, astm sau fracturi costale','Volumele de 10-12 ml/kg protejează membrana alveolo-capilară, barotrauma fiind imposibilă la pacientul ventilat'],'ABCD',228,'Complicații cardiovasculare și respiratorii ale VMI',
 'Integrarea scăderii DC prin PVR/întoarcere, a Vt tradițional 10-12 ml/kg ca mecanism de VILI și a spectrului baro/volutraumă.',
 ['Întoarcerea venoasă, întinderea capilarelor și PVR cu scăderea DC deschid hemodinamica.','10-12 ml/kg și distrugerea membranei prin presiune/ciclare sunt ale VILI.','Permeabilitatea, mediatorii și cele patru localizări de aer extra-alveolar definesc baro/volutrauma.','Pneumonia necrotizantă, emfizemul, astmul și fracturile costale sunt grupurile cu risc.','10-12 ml/kg este tocmai strategia tradițională incriminată, nu una protectivă.']],
 8,'Distractorul transformă Vt-ul tradițional 10-12 ml/kg, cauza VILI, într-o strategie protectivă.',['10-12 ml/kg','barotraumă']),

q(44,['Ventilația cu suport de presiune (PSV), în parametrii din capitol, se caracterizează prin:',
 ['Respirațiile spontane sunt amplificate cu un nivel prestabilit de presiune pozitivă, de obicei 5-20 cmH2O, declanșat de efortul pacientului','Volumul curent este determinat de presiunea setată, de efortul pacientului și de mecanica pulmonară; presiunea de suport se poate reduce progresiv pe măsură ce starea se îmbunătățește','PSV impune absența efortului spontan, volumul curent fiind fixat independent de mecanică, ca în VMC cu volum controlat','Nivelul uzual este 40-60 cmH2O, fără posibilitate de scădere progresivă','Declanșarea este independentă de efortul pacientului, PSV înlocuind PEEP-ul de 5-8 cmH2O'],'AB',229,'Ventilația cu suport de presiune',
 'Reținerea ferestrei 5-20 cmH2O declanșate de efort și a Vt-ului rezultat din presiune × efort × mecanică.',
 ['5-20 cmH2O și declanșarea de efortul spontan sunt definiția.','Determinanții Vt și reducerea progresivă sunt conduita de sevraj.','Absența efortului și Vt fix țin de VMC, nu de PSV.','40-60 cmH2O depășește fereastra citată.','PSV este declanșată de efort; PEEP-ul 5-8 cmH2O este o setare separată.']],
 8,'Distractorii confundă PSV (efort-declanșat, 5-20 cmH2O) cu VMC cu volum controlat sau cu PEEP-ul de 5-8 cmH2O.',['5-20 cm H20','suport de presiune']),

q(45,['Schimburile gazoase extracorporeale, în distincția din capitol, includ:',
 ['ECMO veno-venos: sângele este extras prin canulă groasă cu vârful în VCI, trece prin oxigenator cu membrană și se întoarce în VCS, complet oxigenat și cu CO2 eliminat','ECCO2-R folosește debite mai mici de sânge, îndepărtând eficient CO2, dar oxigenarea este mai puțin eficientă','Ambele tehnici au fost folosite pentru a reduce nevoile de ventilație și astfel leziunile pulmonare induse de ventilator','ECCO2-R este mai ușor de realizat decât oxigenarea extracorporeală completă','ECMO veno-venos întoarce sângele în artera femurală, fără a elimina CO2'],'ABCD',230,'ECMO veno-venos; ECCO2-R',
 'Contrastarea circuitului VCI→VCS al ECMO VV de debitele mici și oxigenarea slabă ale ECCO2-R, plus scopul de a reduce VILI.',
 ['Traiectul VCI – oxigenator – VCS este descrierea figurii 10.28.','Debitele mici, eficiența pe CO2 și oxigenarea inferioară definesc ECCO2-R.','Reducerea ventilației și a VILI este scopul comun.','Ușurința relativă a ECCO2-R față de oxigenarea extracorporeală completă este explicită.','Întoarcerea este venoasă în VCS, nu arterială femorală; CO2 este eliminat.']],
 8,'Distractorul mută întoarcerea din VCS în artera femurală și neagă eliminarea CO2.',['oxigenator cu membrană','debite mai mici de sânge']),

q(46,['Cauzele directe frecvente și mai puțin frecvente de ARDS, conform Cadranului 10.17, includ:',
 ['Frecvente directe: pneumonie și aspirația conținutului gastric','Mai puțin frecvente directe: contuzie pulmonară, leziuni prin explozie, embolie grăsoasă, înec, leziuni inhalatorii, leziune de reperfuzie după transplant/embolectomie, embolie cu lichid amniotic','Indirecte frecvente: sepsis; altele: traumatism sever cu șoc și transfuzii multiple, bypass cardiopulmonar, supradozaj (heroină, barbiturice), pancreatită acută','Cauza directă dominantă este pancreatita, pneumonia fiind o cauză indirectă rară','Embolia cu lichid amniotic și aspirația gastrică sunt clasificate ca leziuni indirecte, sepsisul ca leziune alveolară directă'],'ABC',232,'Cadranul 10.17 — Cauze de ARDS',
 'Perecherea pneumonie/aspirație ca directe frecvente de lista rară (grăsime, amniotic, înec) și de sepsisul indirect.',
 ['Pneumonia și aspirația gastrică deschid cauzele directe frecvente.','Contuzia, explozia, grăsimea, înecul, inhalarea, reperfuzia și amnioticul sunt directe mai rare.','Sepsisul ca indirect frecvent și lista (traumatism, bypass, droguri, pancreatită) închid cadranul.','Pancreatita este indirectă; pneumonia este directă frecventă.','Aspirația este directă frecventă; sepsisul este indirect.']],
 8,'Distractorii permută pneumonia (directă) cu pancreatita/sepsisul (indirecte), cele două coloane ale aceluiași cadran.',['Pneumonie','Aspiraţia conţinutului gastric']),
];
