import {advancedQuestion} from './advanced-author';
import type {SourceRow} from './source-author';
const pdfOffset=(p:number)=>p-182;
const q=(n:number,row:SourceRow,score:number,reason:string,expressions:string[],related:number[]=[])=>
 advancedQuestion('ati',10,pdfOffset,`ati-adv-${String(n).padStart(3,'0')}`,row,[score,reason],expressions,undefined,related);

export const ATI_C=[
q(31,['Terapia vasodilatatoare în terapia intensivă, dincolo de nitroglicerină, se caracterizează prin:',
 ['Reducerea postsarcinii crește volumul-bătaie și scade necesarul miocardic de oxigen prin reducerea tensiunii sistolice a peretelui ventricular; vasodilatația scade și dimensiunea inimii în diastole, îmbunătățind fluxul coronarian','Este deosebit de utilă când curba funcției ventriculare este aplatizată (șoc cardiogen, edem pulmonar cardiogen, regurgitare mitrală), uneori combinată cu suport inotropic','Nitroprusiatul dilată arteriolele și vasele de capacitanță venoasă, plus vascularizația pulmonară, prin eliberare de NO; efectele se instalează rapid și sunt reversibile în câteva minute; intoxicația cu cianură este un risc la perfuzii prelungite, în doze mari','Vasodilatatoarele sunt rezervate hipovolemiei, nitroprusiatul fiind lipsit de efect pe postsarcină','Intoxicația cu cianură apare după doze unice de nitroglicerină, nu după nitroprusiat'],'ABC',224,'Terapia vasodilatatoare — NPS și indicații',
 'Integrarea indicației pe curba aplatizată, a efectului biventricular al nitroprusiatului și a riscului de cianură la perfuzii prelungite.',
 ['Reducerea postsarcinii, a tensiunii de perete și îmbunătățirea fluxului coronarian deschid paragraful.','Curba aplatizată, șocul cardiogen, edemul pulmonar și regurgitarea mitrală sunt indicațiile.','NO, reversibilitatea în minute și cianura la doze mari prelungite definesc NPS.','Vasodilatația este pentru insuficiență cu presarcină deja crescută, nu pentru hipovolemie.','Cianura este atribuită nitroprusiatului, nu NTG.']],
 8,'Distractorii mută cianura de pe nitroprusiat pe NTG și rezervă vasodilatația hipovolemiei.',['Nitroprusiatul de sodiu','Intoxicaţia cu cianură']),

q(32,['Respirația paradoxală, în evaluarea clinică a insuficienței respiratorii, constă în:',
 ['Deplasarea compartimentelor abdominal și toracic în direcții opuse','O discrepanță doar temporală între momentele mișcării abdominal și toracic, fără inversarea direcției','Alternarea relativă a participării intercostalilor și a diafragmei, fără inversare de direcție','Puls paradoxal constant, cu creștere inspiratorie a TA','Tiraj intercostal izolat, fără modificare a abdomenului'],'A',225,'Insuficiența respiratorie — Respirația paradoxală',
 'Separarea paradoxului (direcții opuse) de asincronie (discrepanță de moment) și de alternanța respiratorie.',
 ['Definiția prin direcții opuse este cea din text.','Discrepanța de moment, fără inversare, definește respirația asincronă.','Alternanța intercostali/diafragm este un al treilea pattern, distinct.','Pulsul paradoxal este rareori prezent și nu definește paradoxul toraco-abdominal.','Tirajul este un semn de efort, nu definiția paradoxului.']],
 8,'Distractorii sunt celelalte două patternuri reale din aceeași listă (asincronie, alternanță), ușor de confunda cu paradoxul.',['respiraţia paradoxală','direcţii opuse']),

q(33,['Limitele pulsoximetriei și ale probei de gaze sanguine, potrivit capitolului, includ:',
 ['O SpO2 normală la un pacient cu oxigen suplimentar nu exclude hipoventilația cu retenție de CO2; valorile pot fi inexacte la perfuzie periferică scăzută','Proba de gaze trebuie analizată imediat sau seringa scufundată în apă cu gheață (metabolismul leucocitar continuu scade PO2 și crește PCO2); bulele de aer scad PCO2 și de obicei cresc PO2','Pulsoximetria este un indicator sensibil al hipoventilației, bulele de aer neinfluențând gazele','Gheața crește PO2-ul probei, aerul din seringă scăzând PO2 și crescând PCO2','SpO2 normală pe oxigen exclude retenția de CO2, pulsoximetrul necesitând calibrare înaintea fiecărei măsurători'],'AB',225,'Pulsoximetria; Analiza gazelor sanguine',
 'Contrastarea falsei liniștiri a SpO2 pe oxigen de artefactele de gheață versus bule de aer ale seringii.',
 ['Falsul negativ pentru hipercapnie și inexactitatea la hipoperfuzie sunt limitele pulsoximetrului.','Gheața versus bulele (PCO2↓, PO2↑) sunt regulile de prelevare.','Pulsoximetria nu este sensibilă pentru hipoventilație; bulele influențează gazele.','Gheața previne scăderea PO2; aerul scade PCO2 și de obicei crește PO2.','SpO2 normală pe oxigen nu exclude retenția de CO2; dispozitivele nu necesită calibrare.']],
 8,'Distractorii inversează efectul bulelor de aer pe PO2/PCO2 și transformă SpO2 într-un garant al ventilației.',['Pulsoximetria nu este un indicator sensibil','bulele de aer']),

q(34,['Raportul PaO2/FiO2, în utilizarea din capitol, este:',
 ['O aproximare simplă a gradientului alveolo-arterial, folosită pentru a evalua severitatea insuficienței respiratorii, în special în ARDS; se calculează ca PO2 arterial în mmHg raportat la FiO2 ca fracție din 1','Identic PaCO2 end-tidal, fără legătură cu ARDS','Rezervat doar BPOC, calculat ca FiO2/PaO2 inversat','Un substitut al capnografiei pentru confirmarea intubației','Independent de FiO2, util doar în hipercapnia cronică'],'A',225,'Raportul PaO2/FiO2',
 'Reținerea formulei PaO2(mmHg)/FiO2(fracție) ca aproximare de severitate, mai ales în ARDS.',
 ['Definiția, utilitatea în ARDS și modul de calcul sunt din paragraf.','End-tidal PCO2 ține de capnografie, nu de raportul de oxigenare.','Raportul este PaO2/FiO2, nu inversul, și este discutat la ARDS.','Confirmarea intubației este o utilizare a capnografiei.','Calculul depinde explicit de FiO2.']],
 8,'Distractorii confundă raportul de oxigenare cu capnografia sau inversează PaO2 și FiO2.',['Raportul Pa02/F;02','ARDS']),

q(35,['Ventilația non-invazivă (VNI), în principiile de aplicare din capitol, se caracterizează prin:',
 ['Este indicată pacienților conștienți, cooperanți, capabili să-și protejeze căile aeriene și să expectoreze eficient','Presiunea se aplică prin mască nazo-facială sau cască; ventilatoarele furnizează BiPAP, cu IPAP și EPAP (și timpii) reglate independent, respirația spontană rămânând posibilă','Avantaje: risc redus de VAP, conservarea vorbirii, înghițirii și tusei, sedare de obicei inutilă; poate reduce intubația, durata de ATI/spitalizare și, la unii, mortalitatea','Este deosebit de utilă în insuficiența hipercapnică acută din BPOC, dacă pacientul nu este profund hipoxic sau obnubilat','VNI se rezervă pacientului obnubilat, fără protecție a căii aeriene, masca fiind contraindicată în BPOC'],'ABCD',230,'Ventilația non-invazivă',
 'Integrarea criteriilor de conștiență/protecție, a BiPAP (IPAP/EPAP) și a beneficiului în BPOC hipercapnic neobnubilat.',
 ['Conștiența, cooperarea, protecția căii și expectorația sunt criteriile de selecție.','Masca/casca și IPAP/EPAP independente definesc BiPAP.','VAP↓, vorbire/deglutiție/tuse și impactul pe intubație/durată/mortalitate sunt avantajele.','BPOC hipercapnic, fără hipoxie profundă/obnubilare, este indicația-cheie.','Obnubilarea și absența protecției sunt contraindicații; BPOC-ul hipercapnic este tocmai indicația.']],
 8,'Distractorul inversează criteriile (obnubilat versus conștient) și mută VNI în afara BPOC-ului hipercapnic.',['Ventilaţia non-invazivă','BiPAP'],[231]),

q(36,['Indicațiile și contraindicațiile VNI, conform Cadranului 10.16, includ:',
 ['Indicații: exacerbarea acută a BPOC (H+ >44 nmol/L; pH <7,35), edem pulmonar cardiogen, deformități de perete toracic/boală neuromusculară hipercapnică, apnee obstructivă de somn','Contraindicații: chirurgie facială sau a căilor aeriene superioare, nivel scăzut al conștienței, incapacitatea de protejare a căilor aeriene','VNI este de asemenea utilă la imunocompromiși cu insuficiență respiratorie acută și după extubarea hipercapnicilor','Indicația principală este obnubilarea profundă cu pH >7,50, chirurgia facială fiind o indicație de elecție','Contraindicațiile lipsesc, VNI înlocuind intubația la pacientul fără protecție a căii aeriene'],'ABC',231,'Cadranul 10.16 — VNI',
 'Reținerea pragului pH <7,35 / H+ >44 în BPOC și a triadei de contraindicații (față, conștiență, protecție).',
 ['BPOC cu pH <7,35, edemul cardiogen, neuromuscular/perete și OSA deschid cadranul.','Chirurgia facială, conștiența scăzută și absența protecției sunt contraindicațiile.','Imunocompromisul și post-extubarea hipercapnică sunt din textul adiacent.','pH >7,50 și obnubilarea nu sunt indicații; chirurgia facială contraindică.','Protecția căii aeriene este o precondiție, nu un substitut.']],
 8,'Distractorii transformă contraindicațiile (față, obnubilare) în indicații și inversează pragul de pH al BPOC.',['pH < 7,35','Chirurgie facială']),

q(37,['Polineuropatia bolilor critice se deosebește de sindromul Guillain–Barré, potrivit capitolului, prin:',
 ['Este o neuropatie axonală primară; studiile de conducere confirmă deteriorare axonală, iar proteinele LCR sunt normale sau minim crescute','În Guillain–Barré, conducerea arată de regulă demielinizare, iar proteinele LCR sunt de obicei ridicate','Polineuropatia critică este demielinizantă, cu proteine LCR foarte crescute, nervii cranieni fiind constant afectați','Cauza este cunoscută, iar un tratament specific scurtează sevrajul la sub 48 de ore','Nervii cranieni sunt afectați constant, LCR-ul foarte crescut confirmând diagnosticul de neuropatie critică'],'AB',231,'Polineuropatia bolilor critice',
 'Contrastarea axonului cu LCR aproape normal de demielinizarea GBS cu proteinorahie crescută.',
 ['Patternul axonal și LCR normal/minim crescut sunt ale neuropatiei critice.','Demielinizarea și proteinorahia crescută definesc GBS în același paragraf.','Aceste trăsături sunt ale GBS, nu ale neuropatiei critice.','Cauza nu este cunoscută și nu există tratament specific.','Nervii cranieni sunt rar afectați; LCR foarte crescut ține de GBS.']],
 8,'Distractorii aplică profilul GBS (demielinizare, LCR crescut, cranieni) asupra neuropatiei critice axonale.',['neuropatie axonală primară','proteinele LCR']),

q(38,['Măsurile adjuncte în ARDS, dincolo de ventilația protectivă și de balanța hidrică negativă, includ:',
 ['Pronația precoce și perioadele prelungite, față de supinație, asociază beneficii substanțiale de mortalitate, prin redistribuirea densităților dependente și reducerea șuntului','Oxidul nitric inhalat ameliorează oxigenarea la „responderi”, dar nu s-a dovedit creșterea supraviețuirii; prostaciclinele inhalatorii au efecte similare și sunt mai ușor de administrat','Steroizii în ARDS persistent pot îmbunătăți funcția pulmonară, dar nu par să îmbunătățească rezultatele; utilizarea rămâne controversată','Mortalitatea a scăzut de la circa 60% la 20-40% în două decenii, rămânând însă foarte mare în sepsisul intra-abdominal față de ARDS „primar”','Pronația tardivă scurtă este superioară celei precoce; NO inhalat reduce mortalitatea în toate studiile, steroizii fiind de rutină'],'ABCD',233,'ARDS — Pronație, NO, steroizi, prognostic',
 'Integrarea pronației precoce prelungite, a NO fără beneficiu de supraviețuire, a steroizilor controversați și a scăderii mortalității 60%→20-40%.',
 ['Redistribuția densităților și mortalitatea la pronație precoce/prelungită sunt din paragraf.','NO și prostaciclinele îmbunătățesc oxigenarea, nu supraviețuirea.','Disocierea funcție versus outcome a steroizilor este explicită.','60%→20-40% și contrastul abdominal versus primar închid prognosticul.','Beneficiul de mortalitate este al pronației precoce prelungite; NO și steroizii nu au dovezi clare de supraviețuire.']],
 8,'Distractorul inversează timingul pronației și atribuie NO/steroizilor un beneficiu de mortalitate pe care textul îl neagă.',['poziţionarea în pronaţie','20-40%']),
];
