import {advancedQuestion} from './advanced-author';
import type {SourceRow} from './source-author';
const pdfOffset=(p:number)=>p-182;
const q=(n:number,row:SourceRow,score:number,reason:string,expressions:string[],related:number[]=[])=>
 advancedQuestion('ati',10,pdfOffset,`ati-adv-${String(n).padStart(3,'0')}`,row,[score,reason],expressions,undefined,related);

export const ATI_ADVANCED=[
q(11,['Terapia precoce ghidată de obiective (early goal-directed therapy), cu intenția de a menține saturația venoasă centrală de oxigen >70% la pacienții cu sepsis sever sau șoc septic:',
 ['Nu pare să îmbunătățească evoluția, în ciuda optimismului inițial','Reduce mortalitatea în toate studiile citate din capitol','Înlocuiește monitorizarea volumului-bătaie și a debitului cardiac la pacientul chirurgical','Impune creșterea DO2 și VO2 peste limitele normale, cu beneficiu demonstrat','Este superioară menținerii simple a oxigenării, volemiei și tensiunii arteriale adecvate'],'A',224,'Obiectivele hemodinamicii și transportului de oxigen',
 'Recunoașterea eșecului EGDT cu prag ScvO2 >70% și a lipsei de beneficiu al supranormalizării DO2/VO2.',
 ['Textul precizează că, în ciuda optimismului inițial, această strategie nu pare să îmbunătățească evoluția în sepsisul sever sau șocul septic.','Concluzia capitolului este absența beneficiului, nu reducerea mortalității.','La pacientul chirurgical cu risc, substituția volemică și inotropele trebuie ghidate de volumul-bătaie și debitul cardiac, nu înlocuite de ScvO2.','Creșterea DO2 și VO2 peste normal nu aduce beneficiu, putând fi chiar dăunătoare.','Menținerea oxigenării, volumului circulator și tensiunii arteriale adecvate rămâne obiectivul perioperator descris.']],
 8,'Distractorii reînvie optimismul inițial al EGDT și confundă pragul ScvO2 cu supranormalizarea DO2, ambele contrazise de același paragraf.',['early goal-directed therapy','>70%']),

q(12,['Care dintre următoarele afirmații diferențiază corect insuficiența respiratorie de tip I de cea de tip II?',
 ['Tipul I asociază PaO2 scăzută cu PaCO2 normală sau scăzută','Tipul II asociază PaO2 scăzută cu PaCO2 ridicată','În termeni practici, insuficiența respiratorie este prezentă când PaO2 <8 kPa (60 mmHg) sau PaCO2 >7 kPa (55 mmHg)','Cea mai frecventă cauză de tip II este pneumonia comunitară','Tipul I rezultă din hipoventilație alveolară globală, iar tipul II din șunt dreapta-stânga'],'ABC',224,'Insuficiența respiratorie — Clasificare și etiologie',
 'Aplicarea definiției gazometrice (8 kPa / 7 kPa) și a profilului PaCO2 care separă tipul hipoxemic de cel ventilator.',
 ['Aceasta este definiția tipului I (insuficiență acută hipoxemică).','PaCO2 ridicată, alături de hipoxemie, definește tipul II (insuficiență ventilatorie).','Pragurile practice 8 kPa și 7 kPa sunt cele enunțate în capitol.','Cea mai frecventă cauză de tip II este BPOC, nu pneumonia (cauză tipică de tip I).','Sensurile sunt inversate: tipul I ține de șunt sau de alterarea V/Q, tipul II de ventilație alveolară inadecvată.']],
 8,'Distractorii inversează mecanismele șunt versus hipoventilație și atribuie pneumoniei etiologia tipului II, rezervată BPOC-ului.',['Pa02 <8 kPa','insuficienţă ventilatorie'],[225]),

q(13,['Selectați enunțurile adevărate despre administrarea oxigenului și toxicitatea acestuia:',
 ['Măștile Venturi cu performanță fixă permit controlul concentrației de oxigen și sunt folosite la pacienții cu BPOC și insuficiență cronică de tip II','Hipoxemia severă este mai periculoasă decât hipercapnia','Saturațiile de 98-100% cu FiO2 crescut sunt ținta recomandată după infarctul miocardic','O perioadă scurtă de hiperoxie după intubarea de urgență nu influențează mortalitatea','Canulele nazale asigură o concentrație inspirată fixă, independent de respirația bucală'],'AB',226,'Oxigenoterapia; Toxicitatea oxigenului',
 'Contrastarea dispozitivelor cu performanță fixă versus variabilă și a țintei 90-92% față de hiperoxie.',
 ['Dispozitivele Venturi sunt cele indicate când controlul FiO2 contează, ca în BPOC cu insuficiență cronică de tip II.','Textul precizează că hipoxemia severă este mai periculoasă decât hipercapnia.','Saturațiile 90-92% sunt probabil adecvate; vizarea unor saturații mai mari, inclusiv post-IMA, poate fi dăunătoare.','Chiar o hiperoxie scurtă, inclusiv după intubarea de urgență, poate crește mortalitatea comparativ cu normoxia.','Canulele nazale au performanță variabilă; concentrația se diluează prin respirația bucală.']],
 8,'Distractorii inversează ierarhia hipoxemie–hipercapnie și transformă avertismentul de hiperoxie într-o țintă de saturație de 98-100%.',['Hipoxemia severă','90-92%'],[227]),

q(14,['În insuficiența ventilatorie acută din miastenia gravis, sindromul Guillain–Barré sau leziunile medulare înalte, instituirea ventilației mecanice:',
 ['Se face de obicei atunci când capacitatea vitală a scăzut la 10 mL/kg sau mai puțin','Are ca scop evitarea atelectaziei, a infecției și a stopului respirator','Găsește în PaCO2 ridicat, cu trend în creștere, o indicație de ventilație urgentă','Se bazează pe volumul curent și pe frecvența respiratorie, care se modifică precoce și specific','Este impusă de orice scădere a capacității vitale, independent de starea clinică'],'ABC',227,'Indicații pentru ventilație mecanică',
 'Reținerea pragului de 10 mL/kg și a valorii tardive a volumului curent/frecvenței, versus PaCO2 în creștere.',
 ['Pragul de 10 mL/kg este cel citat pentru instituirea ventilației în aceste boli neuromusculare.','Prevenirea atelectaziei, infecției și stopului respirator este scopul enunțat.','PaCO2 ridicat cu trend în creștere este indicație de ventilație urgentă.','Volumul curent și frecvența sunt indicatori relativ nespecifici, cu modificări tardive.','Nu toți pacienții cu capacitate vitală redusă necesită ventilație; evaluarea clinică individuală rămâne esențială.']],
 8,'Distractorii transformă indicatorii tardivi (Vt, frecvență) în semne precoce și fac din orice scădere a CV o indicație absolută, contrar textului.',['10 ml/kg','PaC02 ridicat']),

q(15,['Referitor la sedarea pacientului ventilat mecanic, sunt adevărate:',
 ['Minimizarea nivelului de sedare cu scoruri de sedare și „trezire zilnică", adesea combinată cu moduri de respirație spontană, se asociază cu reducerea duratei de ventilație și cu externare mai rapidă','Combinația unui opiaceu cu o benzodiazepină sau cu propofol este adesea folosită pentru a facilita ventilația','Sedarea profundă continuă, fără treziri planificate, scurtează internarea în ATI','Blocanții neuromusculari sunt necesari la toți pacienții ventilați, independent de severitate','Evitarea totală a sedativelor prelungește durata ventilației mecanice'],'AB',228,'Sedarea, analgezia și relaxarea musculară',
 'Contrastarea strategiei de sedare minimă / trezire zilnică cu sedarea profundă continuă.',
 ['Reducerea duratei de ventilație și externarea mai rapidă sunt asociate explicit cu minimizarea sedării și trezirea zilnică.','Asocierea opiaceu plus benzodiazepină sau propofol este regimul citat.','Sedarea profundă fără treziri nu este strategia asociată cu internare mai scurtă.','Relaxarea musculară poate fi necesară la unii pacienți, nu la toți.','Textul precizează că chiar evitarea totală a sedativelor se asociază cu reduceri ale duratei de ventilație, nu cu prelungire.']],
 8,'Distractorii inversează efectul trezirii zilnice și generalizează blocul neuromuscular de la excepție la regulă.',['trezire zilnică','opiaceu cu o benzodiazepină']),

q(16,['Alegeți afirmațiile corecte referitoare la traheostomie și la calea aeriană chirurgicală de urgență:',
 ['Traheostomia percutanată prin dilatare, efectuată în ATI, este mai rapidă și asociată cu o rată de infecție a plăgii mult mai redusă comparativ cu traheostomia chirurgicală din sala de operație','Traheostomia chirurgicală se rezervează când factorii anatomici împiedică abordarea percutanată sau există îngrijorare privind coagularea anormală','Obstrucția căilor aeriene superioare care pune viața în pericol, și care nu poate fi ocolită cu o canulă endotraheală, poate fi rezolvată prin cricotiroidotomie, mai sigură, mai rapidă și mai ușor de realizat decât traheostomia clasică','Traheostomia percutanată este contraindicată în ATI și rămâne o procedură de sală de operație','Traheostomia nu are mortalitate asociată, complicațiile fiind doar locale și tardive'],'ABC',228,'Traheostomia; Cadranul 10.15',
 'Diferențierea indicațiilor traheostomiei percutanate, chirurgicale și ale cricotiroidotomiei de urgență.',
 ['Avantajul de viteză și rata mai mică de infecție a plăgii sunt cele atribuite tehnicii percutanate din ATI.','Anatomia nefavorabilă și coagulopatia sunt motivele explicitate pentru abordul chirurgical.','Cricotiroidotomia este descrisă ca mai sigură, mai rapidă și mai ușoară decât traheostomia clasică în obstrucția care nu poate fi intubată.','Textul precizează că traheostomia se efectuează acum cel mai frecvent în ATI, percutanat.','Există o rată de mortalitate mică, dar totuși semnificativă.']],
 8,'Distractorii mută procedura percutanată înapoi în sala de operație și neagă mortalitatea recunoscută ca mică, dar semnificativă.',['dilatare percutanată','cricotiroidotomie']),

q(17,['Identificați afirmația corectă referitoare la oxigenul nazal cu flux înalt (HFNO):',
 ['Împiedică tusea, expectorația și alimentația, similar măștii faciale etanșe','Instituirea HFNO la pacienții cu insuficiență respiratorie de tip I poate fi echivalentă și, în unele circumstanțe, mai eficientă decât ventilația non-invazivă în prevenirea deteriorării și evitarea ventilației invazive','Este rezervat insuficienței de tip II hipercapnice, unde înlocuiește BiPAP','Înlocuiește ECMO în hipoxemia refractară','Crește spațiul mort mai mult decât masca facială, motiv pentru care este evitat în tipul I'],'B',229,'Presiunea pozitivă continuă în căile aeriene — HFNO',
 'Plasarea HFNO ca alternativă tolerabilă a CPAP/VNI în insuficiența hipoxemică de tip I.',
 ['Textul subliniază că pacientul poate tuși, expectora, comunica și se poate alimenta.','Echivalența (și uneori superioritatea) față de VNI în tipul I este concluzia citată.','HFNO este discutat la insuficiența de tip I, nu ca substitut al BiPAP în tipul II.','ECMO rămâne o tehnică extracorporeală pentru hipoxemia refractară, distinctă de HFNO.','Tolerabilitatea superioară, nu creșterea spațiului mort, este argumentul în favoarea HFNO.']],
 8,'Distractorii mută HFNO pe teritoriul tipului II sau al ECMO și neagă avantajul de tolerabilitate (tuse, alimentație) din același paragraf.',['high-flow nasal oxygen','insuficienţă respiratorie de tip I']),

q(18,['Următoarele afirmații despre sevrajul de ventilație și miopatia bolii critice sunt adevărate:',
 ['O miopatie cvadriplegică severă a fost asociată cu administrarea de steroizi și miorelaxante la pacienții ventilați mecanic pentru astm sever acut','SIMV, ca tehnică de sevraj, implică o reducere progresivă a frecvenței respiratorii controlate, cu respirații spontane de obicei asistate prin suport de presiune','Pacienții ventilați sub 24-48 de ore, de exemplu după chirurgie electivă majoră, își pot relua de regulă respirația spontană imediat, fără un proces formal de sevraj','O evaluare subiectivă, de către un clinician experimentat, a răspunsului la o tentativă scurtă de respirație spontană este cel mai de încredere predictor al reușitei sau al eșecului sevrajului','Indicele de respirație rapidă superficială înlocuiește necesitatea de a tuși, a înghiți și a proteja căile aeriene înainte de extubare'],'ABCD',231,'Slăbiciunea neuromusculară; Tehnici de sevraj; Extubarea',
 'Integrarea miopatiei induse de steroizi/miorelaxante cu tehnicile de sevraj și cu valoarea tentativei de respirație spontană, fără a substitui protecția căii aeriene printr-un indice.',
 ['Asocierea steroizi plus miorelaxante în astmul acut sever este contextul citat al miopatiei cvadriplegice.','Reducerea progresivă a frecvenței obligatorii, cu PSV pe respirațiile spontane, este metoda SIMV de sevraj.','Intervalul sub 24-48 de ore, exemplificat prin chirurgia electivă, permite reluarea imediată.','Tentativa scurtă de respirație spontană, judecată de un clinician experimentat, este numită cel mai de încredere predictor.','Extubarea cere tuse, deglutiție și protecția căii aeriene; indicele este doar un predictor condiționat, nu un substitut.']],
 8,'Patru afirmații din secțiuni diferite trebuie ținute împreună; distractorul ridică indicele de respirație rapidă la rang de criteriu suficient de extubare.',['miopatie cvadriplegică','24-48 de ore']),

q(19,['Sindromul de detresă respiratorie acută, potrivit definiției Berlin prezentate, se caracterizează prin:',
 ['Aproximativ 10% din internările la terapie intensivă sunt conforme cu definiția Berlin','Mortalitatea prezisă variază de la 27% (forme ușoare) la 32% (moderate) și 45% (severe)','Cel mai frecvent factor predispozant este sepsisul; 20-40% dintre pacienții cu sepsis sever vor dezvolta ARDS','Diagnosticul cere, printre altele, cauză non-cardiacă, cu presiune de ocluzie a arterei pulmonare <18 mmHg sau indici cardiaci normali','ARDS rezultă numai din leziuni pulmonare directe, cauzele extrapulmonare fiind excluse din definiție'],'ABCD',232,'ARDS — Definiție și etiologie; Cadranul 10.17',
 'Reținerea epidemiologiei (10% din internările ATI, mortalitate pe clase Berlin, sepsis 20-40%) și a criteriului non-cardiogen (POAP <18 mmHg).',
 ['Proporția de 10% din internările ATI este cifra din text.','Cele trei mortalități 27/32/45% corespund claselor ușor/moderat/sever.','Sepsisul este de departe cel mai frecvent factor, cu 20-40% progresie către ARDS.','POAP <18 mmHg sau ecocardiografie/indici cardiaci normali definesc originea non-cardiogenă.','Cadranul 10.17 include atât leziuni directe, cât și indirecte (sepsis, pancreatită, TRALI, politraumatism).']],
 8,'Cere simultaneitatea a trei procente epidemiologice și a pragului POAP <18 mmHg; distractorul restrânge ARDS la cauze pulmonare directe.',['10% din internările','<18 mmHg']),

q(20,['Prognosticul ARDS, potrivit capitolului, este corect descris de:',
 ['Majoritatea deceselor apar ca urmare a disfuncției multiple de organ și a instabilității hemodinamice, mai degrabă decât a deteriorării schimbului de gaze','Când ARDS apare în asociere cu sepsisul intra-abdominal, rata mortalității rămâne foarte mare, spre deosebire de ARDS „primar" (pneumonie, aspirație, contuzie)','Steroizii în ARDS persistent îmbunătățesc rezultatele clinice, motiv pentru care sunt recomandați de rutină','Pronația tardivă, de scurtă durată, este superioară pronației precoce prelungite asupra mortalității','Diagnosticul diferențial radiologic exclude fibroza pulmonară și insuficiența cardiacă'],'AB',233,'ARDS — Prognosticul; Tratament',
 'Separarea cauzei decesului (MODS, nu hipoxemia) de impactul etiologiei (sepsis abdominal versus ARDS primar).',
 ['Textul atribuie majoritatea deceselor MODS și instabilității hemodinamice, nu eșecului schimbului gazos.','Contrastul mortalității foarte mari din sepsisul intra-abdominal versus mortalitatea mai mică din ARDS primar este explicit.','Steroizii pot îmbunătăți funcția pulmonară, dar nu par să îmbunătățească rezultatele; utilizarea rămâne controversată.','Beneficiul asupra mortalității este asociat pronației precoce și perioadelor prelungite, nu celei tardive scurte.','Diagnosticul diferențial include insuficiența cardiacă și fibroza pulmonară.']],
 8,'Distractorii inversează mesajul despre steroizi și despre timingul pronației și închid un diagnostic diferențial pe care textul îl lasă deschis.',['sepsisul intra-abdominal','disfuncţie multiplă de organ']),

q(21,['În limitarea edemului pulmonar din ARDS, obiectivul descris este:',
 ['Expansiune volemică agresivă, pentru a susține debitul cardiac','Obținerea unei balanțe hidrice negative semnificative, prin restricție, diuretice sau, dacă aceste măsuri eșuează, hemofiltrare','Menținerea unei balanțe pozitive de 2-3 L/zi, pentru a evita hipoperfuzia','Coloizi ca fluid de primă intenție, în locul restricției','Doar pronația, fără intervenție asupra bilanțului hidric'],'B',233,'Limitarea edemului pulmonar',
 'Identificarea balanței negative ca obiectiv, inclusiv rolul hemofiltrării când restricția și diureticele nu sunt suficiente.',
 ['Expansiunea agresivă contravine obiectivului de a limita formarea edemului.','Restricția, diureticele și, la eșec, hemofiltrarea pentru o balanță negativă semnificativă sunt strategia citată.','Balanța pozitivă de 2-3 L/zi este opusul obiectivului enunțat.','Nu sunt propuși coloizii ca substitut al restricției.','Pronația este o măsură separată; limitarea edemului rămâne un obiectiv de sine stătător.']],
 8,'Distractorii aplică logica șocului hipovolemic (umplere, balanță pozitivă) unui sindrom de permeabilitate în care textul cere balanță negativă.',['balanţe negative semnificative','hemofiltrare']),

q(22,['Suportul circulator în terapia intensivă, dincolo de vasodilatatoarele deja discutate, include următoarele afirmații corecte:',
 ['Intoxicația cu cianură reprezintă un risc la pacienții cu perfuzii prelungite de nitroprusiat, în doze mari','Contrapulsația cu balon intra-aortic este tehnica folosită cel mai frecvent pentru suportul mecanic în insuficiența miocardică','Creșterea DO2 și VO2 la nivele peste limita normală aduce beneficiu demonstrat la pacientul critic','Valoarea utilizării de rutină a inodilatoarelor precum dopexamina este bine stabilită','Early goal-directed therapy cu ScvO2 >70% înlocuiește contrapulsația în șocul cardiogen'],'AB',224,'Terapia vasodilatatoare; Suportul mecanic al miocardului',
 'Recunoașterea toxicității cianurice a nitroprusiatului și a BCPIA ca suport mecanic de primă linie, distinct de supranormalizarea DO2.',
 ['Riscul de intoxicație cu cianură la perfuzii prelungite, în doze mari, este enunțat pentru nitroprusiat.','BCPIA este numită tehnica cea mai frecventă de suport mecanic în insuficiența miocardică.','Supranormalizarea DO2/VO2 nu aduce beneficiu, putând fi dăunătoare.','Valoarea dopexaminei de rutină rămâne incertă.','EGDT vizează sepsisul, nu înlocuiește suportul mecanic din șocul cardiogen.']],
 8,'Distractorii reiau supranormalizarea DO2 și EGDT, deja infirmate în același capitol, ca alternative la BCPIA.',['Intoxicaţia cu cianură','balon intra-aortic']),
];
