import {advancedQuestion} from './advanced-author';
import type {SourceRow} from './source-author';

const EDITION='Chirurgie generală și specialități chirurgicale, ediția pentru rezidențiat MG 2025';
const pdfOffset=(p:number)=>p-88;
const q=(n:number,row:SourceRow,score:number,reason:string,expressions:string[],related:number[]=[])=>
 advancedQuestion('biliar',16,pdfOffset,`biliar-adv-${String(n).padStart(3,'0')}`,row,[score,reason],expressions,undefined,related,'Lawrence',EDITION);

export const BILIAR_D=[
q(47,['CBP, înainte de a se deschide în duoden, se caracterizează prin:',
 ['Trece prin capul pancreasului și, de regulă, se unește cu ductul pancreatic la circa 1 cm de peretele duodenal, formând un canal comun care se deschide prin ampula Vater','Fluxul biliar în duoden este reglat de sfincterul Oddi, care manșonează acest canal comun','Se unește cu ductul pancreatic la 10 cm de duoden, Oddi lipsind ca sfincter','Ampula Vater se deschide în prima porțiune duodenală, fără canal comun','CBP evită capul pancreasului, unindu-se cu canalul cistic în duoden'],'AB',242,'Anatomie — Ampula Vater și Oddi',
 'Recunoașterea unirii CBP–Wirsung la circa 1 cm de duoden și a rolului sfincterului Oddi pe canalul comun.',
 ['Traiectul prin capul pancreasului, unirea la circa 1 cm și ampula Vater sunt explicite.','Manșonarea canalului comun de către Oddi este citată.','Distanța citată este 1 cm, nu 10 cm; Oddi există.','Deschiderea este în a doua porțiune duodenală.','CBP trece prin capul pancreasului; cisticul se unește mai proximal, formând CBP.']],
 8,'Permutează 1 cm cu 10 cm și anulează Oddi, două repere de la sfârșitul paragrafului de anatomie.',['circa 1 cm','sfincterul lui Oddi']),

q(48,['Formarea de calculi biliari poate fi prevenită, potrivit capitolului, prin:',
 ['Evitarea obezității','Dietă bogată în fibre, pentru inhibarea circuitului enterohepatic al acizilor biliari dehidroxilați','Mese la intervale regulate, pentru scăderea timpului de stocare a bilei în veziculă, și alimente sărace în acizi grași saturați, pentru reducerea nucleației bilei litogene','Dietă hipercalorică, mese unice zilnice și grăsimi saturate în exces, pentru a accelera evacuarea veziculei','Creșterea stocării bilei în colecist, nucleația fiind independentă de dietă'],'ABC',242,'Prevenția litiazei — Dietă și ritm alimentar',
 'Aplicarea triadului evitare obezitate / fibre / mese regulate + grăsimi nesaturate ca prevenție a nucleației.',
 ['Evitarea obezității deschide lista de prevenție.','Fibrele și circuitul enterohepatic al acizilor dehidroxilați sunt citate.','Mesele regulate și reducerea grăsimilor saturate închid paragraful.','Hipercaloric, masă unică și saturate cresc, nu scad, riscul.','Stocarea prelungită favorizează nucleația; dieta o influențează.']],
 8,'Inversează sfaturile dietetice (fibre, mese regulate) în stază și grăsimi saturate, exact ce textul cere evitat.',['conţinut bogat în fibre','acizi graşi saturaţi'],[243]),

q(49,['Amilaza și lipaza serice, în patologia biliară acută:',
 ['Pot fi ușor crescute atât în colecistita acută, cât și în colangita acută','Creșterea marcată sugerează pancreatită acută','O creștere ușoară în colecistită este echivalentă diagnosticului de pancreatită necrotico-hemoragică','Lipaza rămâne normală în pancreatita biliară, amilaza crescând doar în colica necomplicată','Enzimele pancreatice nu se dozează în icterul obstructiv, fiind specifice ulcerului perforat'],'AB',244,'Laborator — Amilază și lipază',
 'Contrastarea creșterii ușoare din colecistită/colangită cu creșterea marcată care orientează spre pancreatită.',
 ['Creșterea ușoară în ambele infecții biliare este explicită.','Creșterea marcată ca indicator de pancreatită este citată.','Creșterea ușoară nu echivalează pancreatita severă.','Ambele enzime cresc marcat în pancreatită, nu doar amilaza în colică.','Textul le plasează tocmai în bilanțul biliar acut.']],
 8,'Egalizează creșterea ușoară din colecistită cu pancreatita necrotico-hemoragică.',['Amilaza serică şi lipaza','pancreatită acută']),

q(50,['Ecografia în colecistita acută, dincolo de vizualizarea calculilor, arată frecvent:',
 ['Distensie veziculară, îngroșarea peretelui (>3–4 mm) și lichid pericolecistic','Semnul Murphy ecografic: cel mai sensibil punct la sondă corespunde proiecției colecistului, prezent la 98% dintre pacienții cu colecistită acută','Dacă vezicula e destinsă și canalele sunt dilatate, obstacolul e probabil distal de joncțiunea cistic–hepatic comun','Peretele sub 1 mm și absența lichidului pericolecistic sunt patognomonice pentru gangrenă','Murphy ecografic e prezent la 10% din cazuri, obstacolul distal dilatând doar cisticul, nu hepaticul'],'ABC',246,'Ecografie — Perete >3–4 mm și Murphy 98%',
 'Aplicarea semnelor de inflamație (>3–4 mm, lichid) și a Murphy ecografic (98%), plus localizarea obstacolului distal de joncțiune.',
 ['Distensia, pragul >3–4 mm și lichidul pericolecistic sunt explicite.','Definiția Murphy ecografic și cifra 98% sunt citate.','Regula veziculă destinsă + căi dilatate → obstacol distal de joncțiune este de pe pagina anterioară.','Peretele subțire fără lichid nu definește gangrena.','98%, nu 10%; obstacolul distal dilată și hepaticul.']],
 8,'Coboară Murphy ecografic de la 98% la 10% și inversează pragul de îngroșare parietală.',['>3-4 mm','98% dintre pacienţii'],[245]),

q(51,['Scintigrafia HIDA, dincolo de criteriile de colecistită, se caracterizează prin:',
 ['Presupune injectarea IV a unui derivat de acid iminodiacetic marcat cu 99m-tehnețiu, excretat de ficat în bilă în concentrații mari','Este utilă și în identificarea unei posibile fistule biliare postoperatorii, dar în prezent este rar folosită în acest scop','Este investigația de elecție pentru calculii veziculari și ai CBP, înlocuind ecografia','Trasorul nu ajunge în bilă, fiind reținut doar renal','Fistula postoperatorie se diagnostichează doar prin radiografie simplă, HIDA fiind abandonată de la introducere'],'AB',246,'HIDA — 99mTc și fistula postoperatorie',
 'Recunoașterea trasorului 99mTc-iminodiacetic și a rolului rar, actual, în fistula biliară postoperatorie.',
 ['Marcajul cu 99m-tehnețiu și excreția hepatică în bilă sunt explicite.','Utilitatea istorică pentru fistulă și folosirea rară actuală sunt citate.','HIDA nu identifică calculii veziculari sau ai CBP.','Trasorul este excretat în bilă, nu reținut renal.','Textul îi recunoaște încă un rol, deși rar, în fistulă.']],
 8,'Transformă HIDA în testul de elecție pentru calculi și îi neagă excreția biliară.',['99"\'techneţiu','fistule biliare postoperatorii']),

q(52,['Tratamentul inițial și momentul colecistectomiei în colecistita acută includ:',
 ['Oprirea aportului oral, lichide IV și antibiotice care acoperă Gram-negativele aerobe și enterococul (E. coli, Klebsiella pneumoniae, Streptococcus faecalis)','Cel mai mare beneficiu îl aduce colecistectomia precoce, la câteva zile de la prezentare, după hidratare și antibiotice','Sonda nazogastrică este rareori necesară, dar e recomandată în caz de vărsături','Colecistectomia se amână 6 luni de principiu, antibioticele fără Gram-negative fiind suficiente','Sonda nazogastrică se montează de rutină, chiar fără vărsături, înlocuind antibioticele'],'ABC',248,'Colecistita acută — Antibiotice și colecistectomie precoce',
 'Aplicarea spectrului E. coli/Klebsiella/enterococ, a ferestrei de câteva zile și a NG doar la vărsături.',
 ['NPO, lichidele și spectrul bacterian sunt explicite.','Colecistectomia precoce la câteva zile, după resuscitare, este cerută.','NG rareori, exceptând vărsăturile, este citată.','Amânarea de 6 luni crește inflamația și complicațiile.','NG nu înlocuiește antibioticele și nu e de rutină.']],
 8,'Amână colecistectomia 6 luni și golește antibioticele de Gram-negative, inversul algoritmului precoce.',['Escherichia coli','câteva zile de la prezentare']),

q(53,['Momentul operației în colecistita acută trebuie întârziat, respectiv avansat, când:',
 ['Se amână dacă trebuie gestionate alte probleme medicale majore','Se practică mai devreme dacă se suspicionează perforație sau abces','Intervențiile de urgență au mortalitate și morbiditate ușor mai ridicate decât electivele, adesea prin boli cardiovasculare, pulmonare sau metabolice','Se amână până la gangrenă, urgența fiind rezervată colicii necomplicate','Mortalitatea de urgență este mai mică decât a electivei, comorbiditățile neavând rol'],'ABC',248,'Colecistita acută — Amânare versus urgență',
 'Contrastarea amânării pentru comorbidități majore cu avansarea la suspiciune de perforație/abces și cu excesul de risc al urgenței.',
 ['Amânarea pentru probleme medicale majore este explicită.','Avansarea la perforație sau abces este citată.','Excesul de mortalitate/morbiditate al urgenței și cauzele (CV, pulmonar, metabolic) sunt descrise.','Gangrena e tocmai o complicație de evitat prin operație precoce.','Urgența are risc ușor mai mare, nu mai mic.']],
 8,'Inversează amânarea (comorbidități) cu avansarea (perforație) și declară urgența mai sigură decât electiva.',['perforaţiei sau abcesului','mortalitate şi morbiditate']),

q(54,['După un episod de pancreatită biliară, colecistectomia și sfincterotomia se poziționează astfel:',
 ['În forme ușoare/moderate, colecistectomia laparoscopică se poate face în primele 48–72 de ore, când durerea s-a remis și amilaza a revenit la normal','Amânarea este justificată în pancreatita acută severă; ERCP cu sfincterotomie endoscopică poate reduce recidiva la 2–5% pentru următorii 2 ani','Sfincterotomia de urgență cu extracție poate fi salvatoare în forma severă dacă evoluția nu se îmbunătățește în 24–36 de ore, la resuscitare adecvată, cu suspiciune înaltă de coledocolitiază','Colecistectomia se amână 6 luni după orice formă ușoară, sfincterotomia crescând recidiva la 60%','Fereastra 24–36 de ore contraindică ERCP-ul, amilaza normală interzicând colecistectomia precoce'],'ABC',250,'Pancreatită biliară — 48–72 h versus 24–36 h',
 'Diferențierea ferestrei 48–72 h pentru colecistectomia formelor ușoare de fereastra 24–36 h a sfincterotomiei de urgență și de reducerea recidivei la 2–5%.',
 ['48–72 de ore, remisia durerii și normalizarea amilazei sunt explicite.','Amânarea în severă și cifra 2–5% la 2 ani sunt citate.','Fereastra 24–36 de ore pentru ES de urgență este descrisă.','60%/6 luni este recidiva FĂRĂ colecistectomie, nu un protocol după forma ușoară.','ES de urgență este tocmai indicată la 24–36 de ore dacă nu se ameliorează.']],
 8,'Permutează 48–72 h (colecistectomie ușoară) cu 24–36 h (ES de urgență) și inversează efectul sfincterotomiei asupra recidivei.',['2-5%','24--36 de ore']),

q(55,['Colangiografia intraoperatorie în pancreatita biliară, la momentul colecistectomiei:',
 ['Trebuie efectuată pentru a confirma absența calculilor din calea biliară','Antibioterapia se administrează în formele severe și pentru complicațiile septice; în colecistita acută asociată se poate face mai întâi colecistostomie','IOC-ul se omite de principiu, calculii reziduali fiind inofensivi după pancreatită','Antibioticele se dau de rutină în toate formele ușoare, colecistostomia înlocuind colecistectomia la tânărul fără comorbidități','Confirmarea absenței calculilor se face doar prin radiografie abdominală simplă, fără contrast'],'AB',250,'Pancreatită biliară — IOC și antibiotice',
 'Recunoașterea IOC-ului ca verificare a CBP la colecistectomie și a rezervării antibioticelor/colecistostomiei pentru formele severe.',
 ['IOC-ul pentru confirmarea absenței calculilor este explicit.','Antibioticele în severă/sepsis și colecistostomia ca punte sunt citate.','IOC-ul este cerut, nu omis.','Antibioticele nu sunt de rutină în ușoare; colecistostomia e pentru grav, nu pentru tânărul fără comorbidități.','Confirmarea se face prin colangiografie cu contrast, nu prin radiografie simplă.']],
 8,'Omit IOC-ul și generalizează antibioticele asupra formelor ușoare, două gesturi din același paragraf de închidere.',['Colangiografia intraoperatorie','Terapia antibiotică']),

q(56,['Icterul în cancerul avansat de veziculă biliară este prezent la:',
 ['Aproximativ 50% dintre acești pacienți, prin diseminare precoce directă la ficat și structurile hilului hepatic și prin metastaze în ganglionii regionali','Sub 1% dintre cazuri, cancerul rămânând strict intramural','90% din formele incidente, descoperite pe piesa de colecistectomie pentru colică','Doar în vezicula de porțelan, fără extensie hilară','Pacienții cu durere persistentă în HD, dar fără scădere ponderală, icterul fiind excepțional'],'A',252,'Cancer de veziculă avansat — Icter 50%',
 'Recunoașterea prevalenței de circa 50% a icterului prin extensie hilară precoce, nu a formelor incidente intramurale.',
 ['Cifra de aproximativ 50% și căile de diseminare (ficat, hil, ganglioni) sunt explicite.','Formele avansate nu rămân intramurale.','Formele incidente au adesea simptome litiazice, nu icterul a 90%.','Porțelanul e factor de risc, nu unica situație de icter.','Boala avansată asociază durere, scădere ponderală, astenie și frecvent icter.']],
 8,'Coboară icterul de la 50% sub 1% și îl rezervă formelor incidente, inversul paragrafului de boală avansată.',['aproximativ 50%','hitul hepatic']),

q(57,['Tumorile mai mari de veziculă, adiacente sau extinse în parenchimul hepatic, se tratează prin:',
 ['Rezecție hepatică cuneiformă a patului colecistic și limfadenectomie regională','Tumorile avansate pot necesita o rezecție hepatică formală','Limfadenectomiei de hil îi lipsește standardizarea, din cauza proximității cu structuri vitale și a absenței unui mezenter mobil','Rata de supraviețuire la 5 ani rămâne <5% la 5 ani, exceptând cancerul incipient descoperit incidental','Sempla colecistectomie laparoscopică cu margini pozitive asigură 80% supraviețuire la 5 ani și în formele avansate'],'ABCD',253,'Cancer de veziculă — Rezecție cuneiformă versus formală',
 'Contrastarea rezecției cuneiforme plus limfadenectomie cu rezecția hepatică formală și cu supraviețuirea <5% a formelor avansate.',
 ['Rezecția cuneiformă a patului și limfadenectomia regională sunt explicite.','Rezecția hepatică formală pentru avansate este citată.','Lipsa de standardizare a limfadenectomiei hilare este enunțată.','<5% la 5 ani, exceptând incidentalul incipient, este cifra de prognostic.','80% la 5 ani ține de adenocarcinomul mucinos incipient cu margini negative, nu de avansat.']],
 8,'Extinde supraviețuirea de 80% a incidentalului incipient asupra tumorilor avansate care cer rezecție hepatică.',['rezecţie hepatică cuneiformă','<5% la 5 ani'],[252]),

q(58,['Colangiocarcinomul, dincolo de clasificarea anatomică, se caracterizează prin:',
 ['Histologic sunt de obicei adenocarcinoame mucinoase; sunt tumori local-avansate, cu dezvoltare lentă, care metastazează rar la distanță','Rezecția curativă este mai degrabă excepție decât regulă, din cauza relațiilor cu ficatul, vena portă și artera hepatică','PTC facilitează evaluarea leziunilor proximale și accesul anterograd pentru stentare','Metastazele pulmonare multiple sunt regula de prezentare, rezecția fiind posibilă la peste 90%','PTC este inutilă proximal, stentarea anterogradă fiind imposibilă'],'ABC',253,'Colangiocarcinom — Biologie și PTC proximal',
 'Recunoașterea biologiei local-avansate (metastaze distante rare) și a rolului PTC în leziunile proximale.',
 ['Adenocarcinomul mucinos, creșterea lentă și raritatea metastazelor distante sunt explicite.','Excepția rezecției curative din cauza vecinătăților vitale este citată.','Rolul PTC proximal și stentarea anterogradă sunt descrise.','Metastazele distante sunt rare, nu regula; rezecția curativă e excepția.','PTC este tocmai utilă proximal.']],
 8,'Transformă colangiocarcinomul într-o boală cu metastaze distante de rutină și neagă PTC-ul proximal.',['metastazează la distanţă','PTC facilitează']),

q(59,['Colecistectomia laparoscopică electivă, la pacientul altfel sănătos, se caracterizează prin:',
 ['Majoritatea intervențiilor se pot efectua cu externarea în aceeași zi','Chiar cu comorbidități grave sau pentru colecistită acută, spitalizarea este de obicei de numai 24–48 de ore','Avantajele includ durere postoperatorie redusă, mai puține complicații de plagă și pulmonare și reluarea precoce a activităților','Scăderea durerii postoperatorii față de colecistectomia deschisă explică toleranța la spitalizarea scurtă','Complicațiile de plagă și pulmonare cresc față de abordul deschis, recuperarea fiind mai lentă'],'ABCD',254,'Colecistectomia laparoscopică — Externare în aceeași zi',
 'Aplicarea externării în aceeași zi (electiv sănătos) versus 24–48 de ore (comorbidități/acut) și a avantajelor de durere/plagă/pulmonar.',
 ['Externarea în aceeași zi la electivul sănătos este explicită.','Fereastra 24–48 de ore pentru comorbidități/acut este citată.','Durerea redusă, complicațiile de plagă/pulmonare și reluarea precoce sunt listate.','Textul leagă toleranța la spitalizarea scurtă de scăderea semnificativă a durerii față de abordul deschis.','Complicațiile de plagă și pulmonare scad, nu cresc.']],
 8,'Înlocuiește externarea în aceeași zi cu internarea de 14 zile și inversează avantajul de plagă/pulmonar.',['aceeaşi zi','24-48 de ore']),

q(60,['Riscurile specifice abordului laparoscopic al colecistectomiei includ:',
 ['Leziuni ale căilor biliare, ale intestinului și ale vaselor principale, de obicei prin inserția trocarului în orb sau utilizarea abuzivă a electrocauterului','Dacă reperele anatomice sunt dificil de identificat sau apar dificultăți tehnice, procedura trebuie convertită la abord deschis','Majoritatea chirurgilor folosesc o abordare selectivă a colangiografiei intraoperatorii, nu de rutină','Trocarul în orb și electrocauterul abolesc riscul de leziune, conversia fiind interzisă','Colangiografia de rutină înlocuiește conversia, anatomia dificilă nemaicerând abord deschis'],'ABC',254,'Laparoscopie — Trocar, electrocauter, conversie',
 'Recunoașterea mecanismelor de leziune (trocar orb, electrocauter) și a regulii de conversie plus IOC selectivă.',
 ['Leziunile de cale, intestin și vase prin trocar orb/electrocauter sunt explicite.','Conversia la anatomie dificilă este cerută.','Abordarea selectivă a IOC este practica majorității.','Trocarul orb și electrocauterul sunt tocmai sursele de risc.','Controversa rutină versus selectivă se încheie cu selectivul; conversia rămâne o opțiune.']],
 8,'Interzice conversia și declară trocarul orb inofensiv, inversul paragrafului de complicații.',['inserţia trocarului în orb','electrocauterului']),

q(61,['După explorarea deschisă a CBP, drenajul peritoneal și clamparea tubului în T:',
 ['Drenajul peritoneal este suprimat la 24–48 de ore după ce tubul în T a fost clampat','Drenajul unor cantități semnificative de sânge sau bilă necesită investigații suplimentare','Tubul în T se extrage odată cu drenajul peritoneal, în primele 12 ore, fără clampare','Sângele sau bila pe dren se ignoră, fiind așteptate fără investigație','Clamparea tubului în T este contraindicată, drenajul peritoneal rămânând pe termen nedefinit'],'AB',255,'Tub în T — Clampare și dren peritoneal',
 'Secvența clampare → suprimarea drenului peritoneal la 24–48 de ore și investigarea sângerării/bilei semnificative.',
 ['Fereastra 24–48 de ore după clampare este explicită.','Indicația de investigație la sânge sau bilă semnificative este citată.','Tubul în T se menține săptămâni, nu se extrage odată cu drenul la 12 ore.','Cantitățile semnificative cer investigație.','Clamparea precede suprimarea drenului, nu este contraindicată.']],
 8,'Extrage tubul în T odată cu drenul la 12 ore, invertind fereastra 24–48 de ore de după clampare.',['24--48 de ore','tubul în T']),

q(62,['Când persistă calculi restanți sau sunt numeroși în CBP, opțiunile după explorarea deschisă includ:',
 ['Efectuarea unei derivații biliare (coledoco-duodeno-anastomoză sau coledoco-jejuno-anastomoză), astfel încât calculii restanți să poată trece în intestin','Extracția prin ERCP; alternativ, avansarea unei sonde cu coșuleț de sârmă prin tubul în T, sub control fluoroscopic','Reexplorarea chirurgicală a CBP, în rarele situații în care aceste metode eșuează','Derivația biliară este contraindicată tocmai când calculii sunt numeroși','Coșulețul prin tubul în T se evită, fluoroscopia fiind inutilă'],'ABC',255,'Calculi restanți — Derivație, ERCP, coșuleț pe tub T',
 'Ierarhia derivație biliară / ERCP / coșuleț pe tub T / reexplorare rară, când persistă calculi după explorarea deschisă.',
 ['Derivația coledoco-duodenală sau jejunală pentru calculi numeroși/suspecți restanți este explicită.','ERCP și coșulețul pe tub T sub fluoroscopie sunt citate.','Reexplorarea ca ultimă soluție este descrisă.','Derivația este tocmai indicată când calculii sunt numeroși.','Coșulețul sub fluoroscopie este o alternativă recunoscută.']],
 8,'Contraindică derivația tocmai la calculii numeroși și anulează coșulețul pe tub T, două ieșiri din impasul restantului.',['derivaţie biliară','coşuleţ de sârmă']),

q(63,['Identificați afirmația corectă privind ecografia ca explorare inițială în afecțiunile biliare:',
 ['A înlocuit colecistografia orală pentru explorarea de rutină a pacienților cu colici; este non-invazivă, rapidă, relativ ieftină și nu iradiază','Colecistografia orală rămâne testul de primă intenție, ecografia fiind abandonată din cauza iradierii','Ecografia este rezervată doar pancreatitei necrotico-hemoragice, colica cerând de primă intenție ERCP','Iradierea ecografică depășește CT-ul, deci se evită la tineri','Rapiditatea este inferioară colecistografiei orale, care nu necesită contrast'],'A',244,'Ecografie versus colecistografie orală',
 'Recunoașterea înlocuirii colecistografiei orale de către ecografia non-invazivă, rapidă și neiradiantă.',
 ['Înlocuirea colecistografiei orale și calitățile (non-invaziv, rapid, ieftin, fără iradiere) sunt explicite.','Ecografia, nu colecistografia orală, este explorarea inițială de elecție.','ERCP nu este primul test în colica necomplicată.','Ecografia nu iradiază, spre deosebire de CT.','Rapiditatea este un avantaj al ecografiei, nu un dezavantaj.']],
 8,'Readuce colecistografia orală ca prim test și atribuie ecografiei iradiere, inversul paragrafului de deschidere imagistică.',['colecistografia orală','nu iradiază'],[245]),

q(64,['Un pacient cu scădere ponderală rapidă după chirurgie bariatrică, privind riscul litogenic:',
 ['Se poate confrunta cu apariția calculilor biliari; scăderea ponderală rapidă crește indexul de saturație biliară și staza în veziculă','Medicamentele hipocolesterolemiante predispun prin alterarea biosintezei de acizi biliari și colesterol','Scăderea ponderală rapidă protejează de calculi, saturarea bilei scăzând','Chirurgia bariatrică aboleste staza veziculară, calculii fiind imposibili ulterior','Hipocolesterolemiantele dizolvă calculii existenți, similar ursodeoxicolicului, fără risc litogenic'],'AB',242,'Litogeneză — Bariatric și hipocolesterolemiante',
 'Recunoașterea stazei și a saturației crescute după scădere ponderală rapidă (inclusiv bariatric) și a rolului hipocolesterolemianelor.',
 ['Apariția calculilor după bariatric și mecanismul (saturație + stază) sunt explicite.','Alterarea biosintezei de acizi biliari și colesterol de către hipocolesterolemiante este citată.','Scăderea ponderală rapidă predispune, nu protejează.','Staza veziculară este tocmai crescută.','Hipocolesterolemiantele predispun la calculi, nu îi dizolvă ca ursodeoxicolicul.']],
 8,'Transformă scăderea ponderală rapidă și hipocolesterolemiantele în factori protectori, inversul listei de predispoziție.',['scădere ponderală rapidă','medicamente hipocolesterolemiante'],[243]),

q(65,['Conform Tabelului 16-1, ileusul biliar se recunoaște prin:',
 ['Pacient vârstnic, tarat, cu ocluzie intestinală incompletă','Radiografia poate arăta ocluzie (de obicei intestin subțire distal), aer în căile biliare și un calcul mare obstructiv','CT-ul reunește aceste elemente; ecografia poate arăta ± litiază veziculară și aer în arborele biliar','Este o colică de 1–4 ore la tânăr, fără ocluzie și fără aerobilie','Radiografia exclude aerobilia, CT-ul fiind superfluu la vârstnicul tarat'],'ABC',252,'Tabelul 16-1 — Ileus biliar',
 'Reținerea profilului vârstnic tarat / ocluzie incompletă / aerobilie + calcul obstructiv, ca rând tabelat distinct de colică.',
 ['Profilul vârstnic tarat și ocluzia incompletă sunt tabelate.','Triada radiologică (ocluzie distală, aerobilie, calcul) este citată.','CT-ul ca sumă și eco ± litiază/aerobilie închid rândul.','Colica de 1–4 ore este alt sindrom tabelat, la pacientul ne-ocluziv.','Aerobilia este un semn căutat, nu exclus; CT-ul este investigația de elecție în text.']],
 8,'Reduce ileusul tabelat la o colică de 1–4 ore și neagă aerobilia, două rânduri alăturate din Tabelul 16-1.',['Pacient vârstnic, tarat','aer în cai le bi lare']),

q(66,['Operația Whipple pentru colangiocarcinomul distal al CBP presupune:',
 ['Rezecția CBP distale (inclusiv tumora), a capului pancreasului și a duodenului','Trei anastomoze care conectează, consecutiv, pancreasul restant, ductul hepatic și duodenul la o ansă jejunală mobilizată','Dacă leziunile distale sunt nerezecabile, se practică bypass chirurgical sau stent biliar paliativ','O singură anastomoză pancreatico-gastrică, fără reconstrucție biliară sau duodenală','Rezecția se limitează la veziculă, duodenul și pancreasul fiind conservate de principiu'],'ABC',253,'Whipple — Trei anastomoze',
 'Recunoașterea piesei de rezecție (CBP distală, cap pancreatic, duoden) și a celor trei anastomoze pe ansă jejunală, plus paliativul.',
 ['Cele trei structuri rezecate sunt explicite.','Cele trei anastomoze pe ansă jejunală sunt descrise.','Bypass-ul sau stentul paliativ pentru nerezecabile sunt citate.','Reconstrucția are trei, nu o singură, anastomoze.','Duodenul și capul pancreatic fac parte din piesă, nu se conservă.']],
 8,'Reduce Whipple-ul la o colecistectomie sau la o singură anastomoză, anulând triada de reconstrucție.',['operaţia Whipple','Trei anastomoze']),
];
