import {advancedQuestion} from './advanced-author';
import type {SourceRow} from './source-author';
const pdfOffset=(p:number)=>p<=1048?p-837:p<=1107?p-839:p-851;
const q=(n:number,row:SourceRow,score:number,reason:string,expressions:string[],related:number[]=[])=>
 advancedQuestion('cardiologie',30,pdfOffset,`cardiologie-adv-${String(n).padStart(3,'0')}`,row,[score,reason],expressions,undefined,related);

export const CARDIOLOGIE_G=[
q(259,['În STEMI, oxigenoterapia pe mască se administrează dacă saturația este sub:',
 ['90%','98%, identic țintei post-ROSC 94-98%','70%, altfel oxigenul este inutil','100%, de rutină la toți pacienții','80%, doar în șocul cardiogen Killip IV'],'A',1088,'STEMI — Oxigen sub 90%',
 'Reținerea pragului SpO2 <90% pentru oxigenul pe mască, distinct de țintele post-resuscitare.',
 ['Textul: oxigen pe mască dacă saturația este mai mică de 90%.','94-98% este ținta post-ROSC, nu pragul de start al oxigenului în STEMI.','70% este prea jos.','Oxigenul 100% de rutină nu este indicat.','Pragul citat este 90%, nu doar Killip IV.']],
 8,'Confundă pragul STEMI <90% cu ținta post-ROSC 94-98% sau cu oxigenul 100% de rutină.',['oxigenoterapia','mască']),

q(260,['Conform Cadranului 30.39, un scor TIMI STEMI de 5 puncte corespunde unei mortalități la 30 de zile de circa:',
 ['0,8%','4,4%','12,4%','35,9%','1,6%'],'C',1088,'STEMI — TIMI scor 5 → 12,4%',
 'Memorarea treptei 5 puncte → 12,4%, intercalată între 4,4% (3 puncte) și 35,9% (9-16).',
 ['0,8% este scorul 0.','4,4% este scorul 3.','Cadranul: 5 → 12,4%.','35,9% este banda 9-16.','1,6% este scorul 1.']],
 8,'Permutează treptele consecutive ale aceluiași tabel; doar scorul 5 dă 12,4%.',['12,4%','30 zile']),

q(261,['La vârstnici sau diabetici, infarctul miocardic se poate prezenta atipic prin:',
 ['Dispnee, astenie, presincopă sau sincopă','Durere care cedează prompt la nitroglicerină sublinguală, identic anginei stabile','Absența oricăror simptome vegetative','Un ECG normal constant, fără indicație de repetare','Localizare doar posterioară, fără alte teritorii'],'A',1088,'STEMI — Prezentarea atipică',
 'Recunoașterea echivalentelor (dispnee, astenie, sincopă) la vârstnic și diabetic.',
 ['Textul enumeră dispnee, astenie, presincopă sau sincopă.','Durerea de STEMI nu cedează de obicei la nitratul sublingual.','Simptomele vegetative sunt frecvente.','Prima ECG e rar normală; se repetă la 15 minute dacă durerea persistă.','Atipia se referă la simptome, nu la o localizare unică.']],
 8,'Atribuie STEMI-ului răspunsul la nitrat al anginei stabile și anulează simptomele vegetative.',['diabetici','presincopă']),

q(262,['Evoluția electrocardiografică a STEMI (Fig. 30.70) include:',
 ['Minute: unde T ample, ascuțite, simetrice și supradenivelare ST','Ore: T se negativează, voltajul R scade, apar unde Q','Zile: ST redevine izoelectric; săptămâni/luni: T se pozitivează, Q persistă','Undele Q dispar în primele minute, ST-ul rămânând neschimbat luni de zile','T negative din primul minut exclud infarctul'],'ABC',1090,'STEMI — Evoluția ECG minute–ore–zile',
 'Secvența T hiperacute → Q și T negative → ST izoelectric → T recuperat cu Q persistent.',
 ['Modificările din primele minute sunt descrise.','Ore: T negative, R mic, Q.','Zile: ST izoelectric; tardiv T se normalizează, Q rămâne.','Q apar după ore, nu dispar în minute.','T hiperacute, nu negative, marchează debutul.']],
 8,'Inversează cronologia Q/ST: face Q-ul evanescent în minute și ST-ul persistent luni.',['câteva minute','undele Q']),

q(263,['Ruptura de perete liber post-STEMI:',
 ['Este o complicație mecanică precoce, cel mai frecvent fatală','Produce colaps și stop prin disociație electromecanică','În forma subacută, pericardiocenteza urmată de chirurgie precoce poate fi salvatoare','Anevrismul ventricular în teritoriul infarctizat este o complicație tardivă care poate cere reparare chirurgicală','Este o complicație tardivă benignă, fără risc de disociație electromecanică'],'ABCD',1090,'STEMI — Ruptura de perete liber și anevrismul',
 'Contrastul rupturii precoce fatale (EMD) cu anevrismul tardiv și cu fereastra subacută salvabilă.',
 ['Precoce și de obicei fatală este explicit.','Disociația electromecanică este mecanismul de stop.','Forma subacută: pericardiocenteză apoi chirurgie.','Anevrismul este complicație tardivă.','Ruptura nu este tardivă benignă.']],
 8,'Mută ruptura fatală precoce în „complicație tardivă benignă”, inversând prognosticul.',['disociaţie electromecanică','forma subacută']),

q(264,['Insuficiența cardiacă ușoară post-STEMI poate răspunde la:',
 ['Furosemid 40-80 mg în bolus i.v. și nitroglicerină în perfuzie, dacă tensiunea permite','Un IECA din primele 24-48 de ore, dacă tensiunea este normală','Oxigen pe mască cu monitorizare prin pulsoximetrie','Digoxin i.v. de primă linie, înaintea diureticului','Interzicerea IECA în primele 7 zile, indiferent de tensiune'],'ABC',1090,'STEMI — IC ușoară, furosemid 40-80 mg',
 'Aplicarea bolusului 40-80 mg și a ferestrei IECA 24-48 de ore la tensiune normală.',
 ['Doza 40-80 mg și nitratul condiționat de TA sunt explicite.','IECA în 24-48 de ore dacă TA e normală.','Oxigenul cu pulsoximetrie este menționat.','Digoxinul nu este prima linie a IC ușoare post-STEMI.','Textul permite IECA precoce dacă TA e normală.']],
 8,'Interzice IECA-ul din 24-48 de ore — fereastra citată — și pune digoxinul înaintea diureticului.',['40-80 mg','24-48 ore']),

q(265,['Alte etiologii ale stenozei mitrale, dincolo de reumatism, includ:',
 ['Stenoza congenitală și sindromul Lutembacher (SM dobândită + DSA)','Calcificarea extensivă a inelului mitral, mai ales la vârstnici și în boala renală avansată','Tumori carcinoide cu metastaze pulmonare sau carcinoid primar bronșic','Doar bicuspidia aortică, fără DSA','Lutembacher ca asociere SM + stenoza aortică, fără defect septal'],'ABC',1092,'Stenoza mitrală — Lutembacher, inel calcificat, carcinoid',
 'Recunoașterea Lutembacher (SM+DSA), a calcificării de inel la vârstnic/CKD și a carcinoidului cu metastaze pulmonare.',
 ['Congenitala și Lutembacher sunt listate.','Calcificarea de inel la vârstnici și boală renală avansată este explicită.','Carcinoidul cu metastaze pulmonare sau primar bronșic este citat.','Bicuspidia ține de valva aortică.','Lutembacher asociază SM cu DSA, nu cu stenoza aortică.']],
 8,'Înlocuiește DSA-ul din Lutembacher cu stenoza aortică, capcana eponimică clasică.',['Lutembacher','calcificarea inelului mitral']),

q(266,['În țările cu venituri mici-medii, stenoza mitrală reumatismală afectează circa:',
 ['20 de milioane de oameni','20.000 de oameni','2% din nou-născuți, identic bicuspidiei','1 din 500, identic CMH','Sub 1.000, fiind o raritate occidentală recentă'],'A',1092,'Stenoza mitrală — 20 de milioane',
 'Reținerea ordinului 20 de milioane în țările cu venituri mici-medii.',
 ['Textul: aproximativ 20 de milioane de oameni.','20.000 subestimează cu trei ordine.','1-2% este bicuspidia, nu SM reumatismală.','1/500 este CMH.','Ordinul este de zeci de milioane, nu mii.']],
 8,'Subestimează cu trei ordine prevalența reumatismală din țările cu venituri mici-medii.',['20 de milioane','reumatismale']),

q(267,['Faciesul mitral (flush malar) se caracterizează prin:',
 ['Pete roșiatice sau cianotice la pomeți, prin stază vasculară și anastomoze arterio-venoase','Un puls cu amplitudine redusă; ulterior complet neregulat dacă se instalează FA','Pulsație amplă parasternal stâng, corespunzând S1, prin VD dilatat care deplasează VS posterior','Facies palid de anemie, fără stază malară','Puls săltăreț, identic regurgitării aortice'],'ABC',1092,'Stenoza mitrală — Flush malar și palpare',
 'Potrivirea flush-ului malar cu pulsul mic și cu pulsația parasternală de VD dilatat.',
 ['Petele malare și mecanismul (stază, anastomoze) sunt explicite.','Pulsul de amplitudine redusă, apoi neregulat în FA, este descris.','Pulsația parasternală de S1 prin VD dilatat este din text.','Nu este faciesul de anemie.','Pulsul săltăreț ține de regurgitarea aortică.']],
 8,'Atribuie stenozei mitrale pulsul săltăreț al regurgitării aortice și anulează flush-ul malar.',['flush malar','pomeţilor']),

q(268,['Fiziopatologia regurgitării mitrale acute versus cronice:',
 ['În forma cronică, atriul dilatat progresiv are complianță crescută, cu creștere minimă a presiunii intraatriale','În forma acută, atriul de dimensiuni normale nu se dilată suficient; unda „v” este semnificativ crescută, cu edem pulmonar acut','Volumul-bătaie crește progresiv pentru a menține debitul net, dilatând VS','În acut, unda „v” este mică, edemul pulmonar fiind rar','Complianța atriului normal previne orice creștere de presiune în regurgitarea acută'],'ABC',1095,'Regurgitarea mitrală — Unda v și forma acută',
 'Contrastul atriului compliant cronic versus unda v și EPA din regurgitarea acută.',
 ['Complianța atriului cronic dilatat este explicită.','Unda v și EPA din acut sunt descrise.','Creșterea volumului-bătaie și dilatarea VS sunt din text.','În acut unda v este crescută, nu mică.','Atriul normal tocmai nu previne creșterea de presiune.']],
 8,'Inversează unda v (mare în acut) și neagă edemul pulmonar — tabloul clasic al RM acute.',['unda „v"','edemului pulmo']),

q(269,['Semne auscultatorii și ECG în regurgitarea mitrală, dincolo de suflul holosistolic:',
 ['Clic mezosistolic pe valve mixomatoase, prin prolaps brusc și tensionarea cordajelor; poate fi urmat de suflu telesistolic','S3 accentuat prin umplere rapidă protodiastolică a VS dilatat; uneori uruitură mezodiastolică scurtă după S3','HVS la ECG: S în V1 + R în V5/V6 >35 mm','S3 lipsește, umplerea VS fiind lentă ca în stenoza mitrală','Cașexia este incompatibilă cu regurgitarea mitrală avansată'],'ABC',1095,'Regurgitarea mitrală — Clic mixomatos și Sokolow >35 mm',
 'Recunoașterea clic-ului mixomatos, a S3 de umplere rapidă și a sumei Sokolow >35 mm.',
 ['Clicul mezosistolic și suflul telesistolic sunt descrise.','S3 și uruitura scurtă sunt explicite.','Suma >35 mm este din text.','S3 este accentuat prin umplere rapidă, nu absent.','Cașexia poate fi prezentă în stadiile avansate.']],
 8,'Neagă S3-ul de umplere rapidă — semnul VS dilatat — și anulează cașexia stadiilor avansate.',['>35 mm','Clic mezosistolic']),

q(270,['Stenoza tricuspidiană:',
 ['Simptome: dureri abdominale (hepatomegalie), distensie (ascită) și edeme periferice','În sinus: undă jugulară „a” proeminentă, palpată și la ficat; suflu mezodiastolic la marginea sternală stângă inferioară, accentuat în inspir','Pe ECG, dilatarea AD: unde P înalte (>3 mm) în DII','Este, de regulă, o leziune izolată, fără afectare mitrală/aortică reumatismală','Suflul se ameliorează în inspir, identic suflurilor stângi'],'ABC',1101,'Stenoza tricuspidiană — Unda a, P >3 mm',
 'Potrivirea congestiei drepte cu unda a hepatică, suflul inspirator și P >3 mm în DII.',
 ['Simptomele de congestie sistemică sunt explicite.','Unda a, palparea hepatică și suflul inspirator sunt descrise.','P >3 mm în DII marchează dilatarea AD.','Textul: pacienții au de obicei și valve stângi reumatismale; ST este rar izolată.','Suflul se accentuează în inspir, nu se ameliorează.']],
 8,'Izolează stenoza tricuspidă de reumatismul stâng — deși textul o leagă aproape constant de valvele stângi.',['>3 mm','edeme periferice']),

q(271,['Regurgitarea tricuspidiană organică se caracterizează prin:',
 ['Cauze: reumatism, endocardită, sindrom carcinoid, boala Ebstein și alte anomalii congenitale ale valvelor AV','Semne: undă jugulară „cv” mare, ficat pulsatil sistolic, suflu holosistolic inspirator la marginea sternală stângă inferioară','Forma funcțională nu dispare după tratamentul medical al cauzei de dilatare a VD','Protezarea este primul gest la orice regurgitare funcțională ușoară','Suflul se ameliorează în inspir, identic suflurilor stângi'],'AB',1101,'Regurgitarea tricuspidă — Ebstein și undă cv',
 'Potrivirea etiologiilor organice (Ebstein, carcinoid) cu unda cv și ficatul pulsatil.',
 ['Lista organică include Ebstein și carcinoidul.','Unda cv, ficatul pulsatil și suflul inspirator sunt din figură/text.','Forma funcțională dispare de obicei după tratamentul medical.','Protezarea este rară; funcționalul se tratează medical.','Suflul se accentuează în inspir, nu se ameliorează.']],
 8,'Transformă forma funcțională — care cedează medical — în indicație de proteză de primă intenție.',['Ebstein','consumatorii de droguri']),

q(272,['Stenoza pulmonară congenitală se poate asocia cu:',
 ['Tetralogia Fallot, sindromul Noonan sau rubeola congenitală','Localizare valvulară, subvalvulară sau supravalvulară','Obstrucție la ejecția VD, cu hipertrofie de VD și dilatare atrială dreaptă','Doar boala Barlow a femeii tinere, fără Fallot/Noonan','Localizare doar infundibulară, valva fiind constant normală'],'ABC',1102,'Stenoza pulmonară — Fallot, Noonan, rubeolă',
 'Recunoașterea asocierilor congenitale (Fallot, Noonan, rubeolă) și a celor trei nivele de obstrucție.',
 ['Cele trei asocieri sunt enumerate.','Cele trei etaje (valvular/sub/supra) sunt explicite.','HVD și dilatarea AD sunt consecințele obstrucției.','Barlow ține de mitrală.','Obstrucția poate fi valvulară, nu doar infundibulară.']],
 8,'Mută stenoza pulmonară pe Barlow și neagă Fallot/Noonan, asocierile congenitale citate.',['Noonan','rubeola congenitală'],[1101]),

q(273,['Criteriile Duke majore microbiologice, dincolo de S. aureus și viridans, includ:',
 ['Abiotrophia species și Granulicatella species printre microorganismele tipice, în absența unui focar primar','Un test serologic de imunofluorescență pozitiv pentru febra Q, cu anticorpi IgG de fază 1 în titru >1:800','Hemoculturi persistente: același germen la interval de minimum 12 ore, sau 3 din ≥4 seturi','Un singur set recoltat pe cateterul central, fără interval de 12 ore','Febra Q cu IgG de fază 1 în titru 1:20, ca echivalent al hemoculturilor persistente'],'ABC',1104,'Endocardita — Duke: Abiotrophia, febra Q >1:800',
 'Completarea criteriului major cu Abiotrophia/Granulicatella și titrul IgG de fază 1 >1:800 pentru Coxiella.',
 ['Abiotrophia și Granulicatella figurează lângă viridans, bovis, HACEK, S. aureus comunitar și enterococ.','Titrul >1:800 de IgG fază 1 pentru febra Q este criteriu major.','Persistența la ≥12 ore sau 3/≥4 seturi este explicită.','Un set de pe cateter nu îndeplinește criteriul major.','Titrul citat este >1:800, nu 1:20.']],
 8,'Reduce bacteriologia Duke la un set de cateter și comprimă titrul Q de la >1:800 la 1:20.',['Abiotrophia','>1:800']),

q(274,['Criteriile de suspiciune clinică înaltă de endocardită includ:',
 ['Leziune valvulară nouă sau suflu de regurgitare nou; evenimente embolice de cauză necunoscută; sepsis fără focar','Hematurie/glomerulonefrită/infarct renal; febră plus material protetic, CDIV, aritmii/tulburări de conducere noi sau prima IC','Leziuni Osler/Janeway/Roth sau abcese periferice (renale, splenice, spinale) fără focar','Febra izolată, fără niciunul dintre elementele de mai sus, ca suspiciune înaltă','O singură hemocultură negativă exclude diagnosticul și face eco-ul superfluu'],'ABC',1105,'Endocardita — Suspiciune înaltă versus joasă',
 'Listarea semnalelor de alarmă (suflu nou, embolie, proteză, Roth/Osler) versus febra izolată (suspiciune joasă).',
 ['Suflul nou, embolia și sepsisul fără focar sunt primele criterii.','Febră plus proteză/CDIV/conducere nouă/IC inaugurală sunt listate.','Osler, Janeway, Roth și abcesele fără focar completează setul.','Febra izolată definește suspiciunea joasă.','Eco negativă nu exclude; o cultură negativă nu închide cazul.']],
 8,'Promotează febra izolată — tocmai suspiciunea joasă — ca alarmă înaltă și tratează o cultură negativă ca excludere.',['Noduli Osler','Leziuni Janeway']),

q(275,['Explorarea și durata antibioterapiei în endocardită:',
 ['Ecocardiografia nu este un test de screening la probabilitate pre-test redusă (doar febră sau o singură hemocultură pozitivă)','O eco negativă nu exclude diagnosticul; ETE și PET-CT pot ajuta, mai ales pe proteză','Tratamentul durează 4-6 săptămâni; combinațiile pot fi sinergice și scad rezistența','Un singur set de hemoculturi după prima doză de antibiotic înlocuiește protocolul','Eco-ul negativ la febră izolată confirmă endocardita și impune chirurgie imediată'],'ABC',1105,'Endocardita — Eco nu e screening; 4-6 săptămâni',
 'Restrângerea eco-ului ca screening, rolul PET-CT pe proteză și fereastra 4-6 săptămâni.',
 ['Textul interzice screening-ul la probabilitate joasă.','Eco negativă nu exclude; ETE/PET-CT pe proteză.','4-6 săptămâni și sinergia combinațiilor sunt explicite.','Hemoculturile se recoltează înaintea empiricului.','La febră izolată eco-ul nu confirmă boala.']],
 8,'Transformă eco-ul negativ al febrei izolate în confirmare chirurgicală, inversul regulii de screening.',['4-6 săptămâni','PET-CT'],[1106]),

q(276,['Din Cadranul 30.48, schemele empirice/țintite includ:',
 ['Fără suspiciune de stafilococ: penicilină 1,2 g la 4 ore plus gentamicină 80 mg la 12 ore','Suspiciune stafilococică (CDIV, dispozitive, chirurgie recentă): vancomicină 1 g la 12 ore plus gentamicină 80-120 mg la 8 ore','Enterococ fără rezistență înaltă la gentamicină: ampicilină/amoxicilină 2 g la 4 ore plus gentamicină 80 mg la 12 ore','Penicilină 1,2 g ca monoterapie orală, fără gentamicină, în suspiciunea stafilococică','Vancomicina se evită la CDIV, fiind rezervată streptococului oral'],'ABC',1106,'Endocardita — Cadranul 30.48 (doze)',
 'Potrivirea penicilină 1,2 g q4h versus vancomicină 1 g q12h la suspiciunea stafilococică.',
 ['Schema non-stafilococică este din tabel.','Vancomicina plus gentamicina q8h este linia de suspiciune stafilococică.','Ampicilina 2 g q4h plus gentamicina este schema enterococică.','Stafilococul suspectat nu se tratează cu penicilină orală izolată.','Vancomicina este tocmai linia CDIV/dispozitive.']],
 8,'Inversează schemele: pune penicilina orală pe stafilococ și scoate vancomicina de la CDIV.',['1,2 g','Vancomicină 1 g']),

q(277,['Alergia la penicilină în endocardită:',
 ['Penicilinele sunt fundamentale; alergia poate pune probleme serioase de alegere a schemei','Trebuie investigat caracterul alergiei, ca pacientul să nu fie privat inutil de antibioticul adecvat','Șocul anafilactic are altă pondere decât un simplu disconfort gastro-intestinal','Un disconfort digestiv echivalează anafilaxia și interzice orice beta-lactamină fără evaluare','Gentamicina și vancomicina nu se monitorizează, toxicitatea fiind neglijabilă'],'ABC',1106,'Endocardita — Alergia la penicilină',
 'Diferențierea anafilaxiei de disconfortul digestiv înainte de a priva pacientul de penicilină.',
 ['Penicilinele rămân fundamentale.','Investigarea caracterului alergiei este explicită.','Anafilaxia versus disconfortul GI au ponderi diferite.','Disconfortul digestiv nu echivalează anafilaxia.','Nivelurile de gentamicină și vancomicină trebuie monitorizate.']],
 8,'Echivalează disconfortul digestiv cu anafilaxia — tocmai distincția pe care textul o cere.',['Şocul anafilactic','penicilină']),

q(278,['IRM-ul în miocardita acută evidențiază:',
 ['Edem miocardic pe secvențe ponderate T2','Captare neuniformă de gadoliniu, în stratul mediu și epicardic','Ecocardiografie, cu funcție biventriculară normală sau redusă și anomalii de cinetică regională','Captare subendocardică transmură, identic infarctului în teritoriul unei coronare','Serologia virală ca substitut al IRM-ului de confirmare'],'ABC',1119,'Miocardită — T2, gadoliniu medio-epicardic',
 'Contrastul captării medio-epicardice neuniforme cu pattern-ul subendocardic de infarct.',
 ['Edemul T2 este explicit.','Captarea neuniformă medio-epicardică este descrisă (Fig. 30.106).','Eco-ul este menționat, cu funcție normală sau redusă.','Pattern-ul de infarct este subendocardic/transmural coronarian, nu medio-epicardic.','Serologia virală de obicei nu este utilă; IRM confirmă.']],
 8,'Atribuie miocarditei captarea subendocardică de infarct, inversând localizarea gadoliniului.',['gadoliniu','ponderate T2']),

q(279,['Penetranța CMH în funcție de genă și vârstă:',
 ['Hipertrofia poate fi absentă înainte de adolescență, ceea ce îngreunează diagnosticul la copii','CMH prin mutația proteinei de legare a miozinei poate să nu se manifeste până la decada a șasea sau mai târziu','Rata cea mai înaltă de moarte subită (până la 6% pe an) este la adolescenți sau adulți tineri','Hipertrofia este constant vizibilă de la naștere, indiferent de genă','Rata de moarte subită la adolescenți este sub 0,1% pe an, identică populației generale'],'ABC',1120,'CMH — Decada a șasea, adolescență, 6%/an',
 'Potrivirea ferestrei pre-adolescență (hipertrofie absentă), a MYBPC până după 50 de ani și a vârfului de 6%/an.',
 ['Absența hipertrofiei înainte de adolescență este explicită.','MYBPC poate debuta în decada a șasea.','Până la 6% pe an la adolescenți/tineri.','Hipertrofia poate lipsi la copii.','6% pe an, nu 0,1%, este vârful citat.']],
 8,'Comprimă moartea subită a adolescentului de la 6%/an la 0,1% și cere hipertrofie neonatală constantă.',['6% pe an','decada a şasea']),

q(280,['Semnele CMH și impactul fibrilației atriale:',
 ['Pulsație apicală dublă (contracție atrială puternică care produce S4)','Puls carotidian sacadat, prin ejecție rapidă și obstrucție bruscă telesistolică a tractului','Dacă apare FA, deteriorare rapidă prin pierderea contracției atriale și tahicardie, cu creșterea presiunii în AS și edem pulmonar acut','Unde Q patologice, mai ales în derivațiile infero-laterale','Apex hiperdinamic deplasat, identic regurgitării aortice, fără puls sacadat'],'ABCD',1120,'CMH — Apex dublu, puls sacadat, FA cu EPA',
 'Reunirea apexului dublu, a pulsului sacadat, a Q infero-laterale și a EPA la debutul FA.',
 ['Apexul dublu și S4 sunt explicite.','Pulsul sacadat este descris.','FA → EPA prin pierderea contracției atriale este din text.','Q infero-laterale sunt listate.','Apexul dublu și pulsul sacadat, nu apexul hiperdinamic al RA, definesc palparea.']],
 8,'Atribuie CMH apexul hiperdinamic al regurgitării aortice și neagă EPA-ul de la debutul FA.',['Pulsaţie apicală dublă','sacadat']),

q(281,['Ecocardiografia și chirurgia septului în CMH:',
 ['Clasic: HVS asimetrică (sept > perete posterior), SAM mitral și VS care se contractă puternic','Poate exista orice tipar, inclusiv hipertrofie concentrică și apicală','Uneori este indicată rezecția chirurgicală a miocardului septal','Hipertrofia este constant simetrică, SAM fiind incompatibil cu diagnosticul','Rezecția septală este interzisă, ablația cu alcool fiind lipsită de alternative chirurgicale'],'ABC',1120,'CMH — SAM, hipertrofie apicală, rezecție septală',
 'Recunoașterea tiparelor (asimetric, concentric, apical) și a rezecției septale ca alternativă a alcoolului.',
 ['Triada clasică eco este explicită.','Concentricul și apicalul sunt acceptate.','Rezecția chirurgicală este menționată.','SAM face parte din mecanismul obstrucției, nu o exclude.','Chirurgia septală este o opțiune, nu o interdicție.']],
 8,'Interzice rezecția septală — opțiunea citată — și cere hipertrofie simetrică fără SAM.',['mişcare anterioară','rezecţia chirurgicală'],[1121]),

q(282,['Tabloul și limita imagisticii în cardiomiopatia aritmogenă:',
 ['Cei mai mulți pacienți sunt asimptomatici; ocazional IC dreaptă în stadiile tardive','Aspectul morfologic al VD este frecvent normal, în ciuda unor aritmii semnificative','Testarea genetică ar putea deveni gold standard; transplantul este ocazional indicat pentru aritmie netratabilă sau IC','Eco-ul este suficient în toate stadiile, IRM-ul neaducând informații despre infiltrația fibro-grăsoasă','Transplantul este interzis, aritmiile fiind constant controlate de beta-blocant'],'ABC',1121,'CMA — VD morfologic normal, transplant',
 'Reținerea discordanței (aritmii severe, VD eco-normal) și a nișei de transplant.',
 ['Asimptomaticii și IC dreaptă tardivă sunt descrise.','VD frecvent normal la screening, totuși aritmii semnificative.','Genetica ca viitor gold standard și transplantul ocazional sunt din text.','IRM evaluează VD mai acurat și poate arăta infiltrație fibro-grăsoasă.','Transplantul este menționat pentru aritmie netratabilă sau IC.']],
 8,'Anulează transplantul — nișa aritmiei refractare — și supraestimează eco-ul față de IRM.',['asimptomatici','transplantul cardiac'],[1122]),

q(283,['CMD familială autosomal dominantă implică, printre altele, gene pentru:',
 ['Actină, desmină, troponină T, lanțul greu al β-miozinei, sarcoglicani, vinculină și lamin a/c','Distrofină în forma X-linkată','Asocieri cu miopatie scheletică sau boală a sistemului de conducere','Distrofina ca genă a formei AD, lamin a/c ca formă X-linkată','Grosime parietală marcat crescută, identic CMH'],'ABC',1122,'CMD — Actină, desmină, sarcoglicani',
 'Completarea listei de proteine citoscheletale AD și a asocierii cu miopatia/conducerea.',
 ['Lista AD este din Fig. 30.114/text.','Distrofina este forma X-linkată.','Miopatia scheletică și boala de conducere diferențiază unele mutații.','Atribuirea genelor este inversată.','Pereții sunt prezervați ca grosime, nu hipertrofiați.']],
 8,'Inversează distrofina XL cu lamin a/c AD și pune hipertrofia CMH pe CMD.',['Desmină','sarcoglican']),

q(284,['Investigațiile în cardiomiopatia dilatativă includ:',
 ['Eco: aspect globulos, camere dilatate, funcție globală redusă','IRM: poate arăta fibroză, inclusiv hipercaptare septală medio-miocardică','Angiografie coronariană sau angio-CT la toți cei la risc (în general >40 de ani, sau mai tineri cu factori de risc/simptome)','Biopsie de rutină la toți pacienții, ca în amiloidoză','ECG-ul este constant normal, fără aritmii sau tulburări de conducere'],'ABC',1123,'CMD — Cord globulos, fibroză medio-miocardică, >40 ani',
 'Ierarhia eco globulos → IRM medio-miocardic → excluderea bolii coronariene peste 40 de ani, fără biopsie de rutină.',
 ['Aspectul globulos este din Fig. 30.115.','Hipercaptarea septală medio-miocardică este descrisă.','Pragul >40 de ani (sau mai tineri cu risc) este explicit.','Biopsia nu este de rutină, spre deosebire de amiloid.','ECG-ul poate arăta ST-T difuze, tahicardie, conducere anormală, FA, ESV, TV.']],
 8,'Promotează biopsia de rutină — explicit nerezervată CMD — și declară ECG-ul normal.',['globulos','medio-miocardică']),

q(285,['Cardiomiopatia restrictivă primară se asociază, printre altele, cu:',
 ['Amiloidoză (cea mai frecventă), sarcoidoză, endocardită Loeffler și fibroză endomiocardică','Eozinofilie în Loeffler și fibroza endomiocardică, cu fibroză mio- și endocardică','Formă idiopatică posibil familială','NCVS apicală spongiformă ca echivalent restrictiv, fără dilatare biatrială','PVJ plat, fără Friedreich sau Kussmaul'],'ABC',1123,'Restrictivă — Loeffler, eozinofilie, familială',
 'Potrivirea Loeffler/fibrozei endomiocardice cu eozinofilia, distincte de noncompactarea apicală.',
 ['Cele patru asocieri, amiloidul fiind cea mai frecventă, sunt listate.','Eozinofilia celor două fibroze este explicită.','Idiopatica poate fi familială.','NCVS este o altă entitate, apicală spongiformă.','PVJ accentuat, Friedreich și Kussmaul sunt descrise.']],
 8,'Suprapune restrictiva peste noncompactarea apicală și anulează semnele venoase clasice.',['Loeffler','eozinofilie']),

q(286,['Etiologii mai puțin uzuale de pericardită (Cadranul 30.53) includ:',
 ['Medicamente: procainamidă, hidralazină, izoniazidă, doxorubicină, ciclofosfamidă','Bacterii: stafilococ, streptococ, pneumococ, meningococ, H. influenzae, micoplasmă, borelioză, chlamidii','Post-iradiere; post-pericardiotomie; familială/idiopatică','Doar virusurile Coxsackie, fără cauze medicamentoase','Hidralazina ca protecție față de pericardită, fără risc autoimun'],'ABC',1125,'Pericardită — Procainamidă, hidralazină, bacterii',
 'Listarea medicamentelor lupogene/citotoxice și a spectrului bacterian din cadran.',
 ['Cele cinci medicamente sunt în cadran.','Spectrul bacterian este enumerat.','Iradierea, post-pericardiotomia și forma familială sunt listate.','Cadranul include și medicamente, bacterii, uremie, mixedem.','Hidralazina este o cauză autoimună indusă, nu protecție.']],
 8,'Transformă hidralazina — cauză clasică de pericardită indusă — în factor protector.',['procainamidă','hidralazină']),

q(287,['Pericardita malignă:',
 ['Cele mai frecvente cauze: carcinom bronșic, carcinom mamar și limfom Hodgkin','Leucemia și melanomul se asociază de asemenea','Revărsatul mare este tipic, adesea hemoragic, prin obstrucția drenajului limfatic cardiac','Radioterapia toracică poate da revărsat seros sau hemoragic și fibroză pericardică','Melanomul este incompatibil cu pericardita, drenajul limfatic rămânând intact'],'ABCD',1126,'Pericardită malignă — Hodgkin, revărsat hemoragic',
 'Potrivirea triadului sân/pulmon/Hodgkin cu caracterul hemoragic prin obstrucție limfatică.',
 ['Cele trei cauze cele mai frecvente sunt explicite.','Leucemia și melanomul sunt menționate.','Revărsatul mare hemoragic prin obstrucție limfatică este descris.','Iradierea produce revărsat și fibroză.','Melanomul este asociat, nu incompatibil.']],
 8,'Scoate melanomul din lista de cauze — deși textul îl leagă explicit de pericardită.',['limfomul Hodgkin','hemoragic']),

q(288,['Pericardita incesantă/cronică, dincolo de definiții:',
 ['Tratamentul de primă linie: AINS sau aspirină plus colchicină, până la 6 luni','În rezistență, corticoterapia orală poate fi eficientă; la unii, pericardectomia','CT sau IRM pot arăta îngroșare (>4 mm) sau inflamație pericardică','Colchicina se oprește la 48 de ore, pericardectomia fiind primul gest','Îngroșarea >4 mm infirmă constricția și face imagistica superfluă'],'ABC',1126,'Pericardită incesantă — Colchicină 6 luni, >4 mm',
 'Fereastra de până la 6 luni a colchicinei și pragul imagistic >4 mm de îngroșare.',
 ['AINS/aspirină + colchicină până la 6 luni este explicit.','Steroiizii orali și pericardectomia sunt menționate la rezistență.','>4 mm pe CT/IRM este pragul citat.','6 luni, nu 48 de ore; pericardectomia nu este primul gest.','Îngroșarea >4 mm orientează spre constricție/inflamație, nu o infirmă.']],
 8,'Comprimă colchicina de la 6 luni la 48 de ore și promovează pericardectomia ca primă linie.',['6 luni','>4 mm']),

q(289,['Pericardita constrictivă — particularități față de tamponadă:',
 ['Agoniștii dopaminergici (cabergolină, pergolidă) pot produce fibroză pericardică','Un clacment pericardic protodiastolic la marginea sternală stângă inferioară','FA la circa 30% din cazuri, prin dilatare atrială','FA este incompatibilă cu constricția, atriile rămânând mici','Cabergolina protejează de fibroză, fibroza ținând doar de TB'],'ABC',1127,'Constricție — Cabergolină, clacment, FA 30%',
 'Reținerea cabergolinei/pergolidei ca fibrizanți, a clacmentului protodiastolic și a FA la 30%.',
 ['Cabergolina și pergolida sunt citate.','Clacmentul protodiastolic la marginea sternală stângă inferioară este explicit.','30% au FA prin dilatare atrială.','30% au FA, atriile nu rămân mici.','Cabergolina este cauză de fibroză, nu protecție.']],
 8,'Scoate cabergolina din lista de fibrizanți — etiologia medicamentoasă citată — și neagă FA-ul de 30%.',['cabergolina','30% din cazuri'],[1126]),

q(290,['Pericardiocenteza și fenestrația pericardică:',
 ['Pericardiocenteza (aseptic, ghidaj eco) este indicată la suspiciune de revărsat tuberculos, malign sau purulent','Biopsia pericardică poate fi necesară dacă se suspectează TB, iar puncția nu e diagnostică','La refill neoplazic (cauza cea mai frecventă de recidivă în UK) se poate crea o fereastră pericardică, percutan sau chirurgical','Cele mai multe revărsate se acumulează fatal, fără remisiune spontană posibilă','Fenestrația este interzisă în neoplazii, fiind rezervată constricției calcificate'],'ABC',1127,'Revărsat — Pericardiocenteză TB/malign și fereastră',
 'Nișa puncției (TB, malign, purulent) și a fenestrației pentru refill-ul neoplazic britanic.',
 ['Cele trei suspiciuni de puncție sunt explicite.','Biopsia după puncție nediagnostică în TB este menționată.','Fereastra pentru refill neoplazic (UK) este descrisă.','Cele mai multe revărsate se remit spontan.','Fenestrația este tocmai pentru recidiva neoplazică, nu pentru constricția calcificată.']],
 8,'Interzice fenestrația neoplazică — indicația citată — și neagă remisiunea spontană a majorității revărsatelor.',['fenestrarea pericardică','Pericardiocenteza']),

q(291,['Oxalatul de naftidrofuril în claudicația intermitentă:',
 ['Este un vasodilatator care inhibă receptorii vasculari și trombocitari 5-HT2 și poate reduce lactatul','Doza 100-200 mg ×3/zi poate crește distanța de mers și calitatea vieții','Se consideră o probă de 3-6 luni când pacientul evită intervenția, iar efortul supervizat nu controlează simptomele','Înlocuiește controlul factorilor de risc și programul de 2 ore/săptămână','Se dă de primă intenție înaintea oricărui efort, ca substitut al angioplastiei'],'ABC',1128,'BVP — Naftidrofuril 100-200 mg, 5-HT2',
 'Nișa 3-6 luni a naftidrofurilului 100-200 mg ×3, după eșecul efortului supervizat.',
 ['Mecanismul 5-HT2 și lactatul sunt explicite.','Doza 100-200 mg ×3/zi este din text.','Proba 3-6 luni după efort insuficient este citată.','Nu înlocuiește controlul riscului și cele 2 ore de efort.','Nu este prima linie înaintea efortului.']],
 8,'Pune naftidrofurilul înaintea efortului supervizat, deși textul îl rezervă eșecului reabilitării.',['naftidrofuril','5-hidroxitriptamină2']),

q(292,['Diagnosticul diferențial al claudicației, dincolo de canalul spinal și Buerger, include:',
 ['Compresia arterei poplitee la tineri, care pot avea pulsuri normale','Displazia fibromusculară','Claudicația venoasă: tensiune la mers, TVP în antecedente','Displazia fibromusculară nu figurează în diagnosticul diferențial al claudicației','Compresia poplitee apare doar la vârstnici cu pulsuri absente'],'ABC',1128,'BVP — Poplitee, displazie fibromusculară',
 'Adăugarea compresiei poplitee a tânărului cu pulsuri prezente și a displaziei fibromusculare la lista DD.',
 ['Popliteea tinerilor cu pulsuri normale este listată.','Displazia fibromusculară figurează.','Claudicația venoasă este descrisă.','Displazia fibromusculară este în lista DD.','Popliteea este a tinerilor, care pot avea pulsuri normale.']],
 8,'Mută compresia poplitee pe vârstnicul fără pulsuri și scoate displazia fibromusculară din lista DD.',['poplitee','fibromusculară']),

q(293,['Sensibilitatea indicelui gleznă-braț poate fi îmbunătățită prin:',
 ['Urmărirea scăderii IGB după efort','Înlocuirea Doppler-ului tibial cu palparea izolată a pulsului radial','Măsurarea doar a presiunii brahiale, fără gleznă','Ignorarea arterelor calcificate, IGB rămânând valid','Interzicerea presiunii de la degete la diabeticul cu artere incompresibile'],'A',1128,'BVP — IGB după efort',
 'Reținerea manevrei de efort care crește sensibilitatea IGB, distinctă de falsa creștere pe calcificare.',
 ['Textul: sensibilitatea poate fi îmbunătățită urmărind scăderea IGB după efort.','Palparea radială nu înlocuiește Doppler-ul tibial.','Raportul gleznă/braț cere ambele măsurători.','Pe calcificare IGB e fals crescut.','La incompresibile, presiunea de la degete este mai sensibilă.']],
 8,'Anulează manevra de efort — metoda citată de a crește sensibilitatea IGB.',['după efort','1GB']),

q(294,['Revascularizarea claudicației intermitente:',
 ['Nu este în general recomandată, cu excepția simptomelor severe sau invalidante','Angioplastia transluminală percutană este prima opțiune, pe cateter inserat în artera femurală','Controlul agresiv al riscului rămâne necesar, BVP expunând la BCI și boală cerebrovasculară','Angioplastia se oferă de primă intenție tuturor claudicanților CCS I, înaintea efortului','ASD este screening-ul de primă linie la toți asimptomaticii Fontaine I'],'ABC',1128,'BVP — PTA femurală, nu rutină',
 'Rezervarea angioplastiei cazurilor invalidante, cu abord femural ca primă opțiune intervențională.',
 ['Intervenția nu este de rutină, ci la simptome severe/invalidante.','PTA pe cateter femural este prima opțiune.','Riscul de BCI/AVC justifică tratamentul medical agresiv.','Efortul supervizat precede intervenția la claudicația neseveră.','ASD se folosește imediat anterior intervenției, nu ca screening Fontaine I.']],
 8,'Oferă PTA-ul de primă intenție claudicației ușoare, sărind efortul supervizat de 2 ore.',['Angioplastia transluminală','femurală']),

q(295,['Mortalitatea asociată bolilor cardiovasculare și cerebrovasculare coexistente în BVP face ca:',
 ['Doar o parte dintre pacienții cu BVP să ajungă la amputație','Amputația să fie regula, peste 90% din cazuri','Boala aorto-iliacă să fie lipsită de risc de BCI','Fontaine I să însemne gangrenă','IGB să fie inutil, diagnosticul fiind pur clinic'],'A',1128,'BVP — Amputația nu este regula',
 'Reținerea că mortalitatea CV/cerebrovasculară coexistente „fură” pacienții înaintea amputației.',
 ['Textul: numai o parte ajung la amputație, din cauza mortalității CV coexistente.','Amputația nu este regula.','Aorto-iliacul asociază risc de BCI.','Fontaine I este forma asimptomatică.','IGB stratifică severitatea.']],
 8,'Transformă amputația — evitată de mortalitatea CV competitivă — în soarta a peste 90% din BVP.',['amputaţie','cerebrovasculare']),

q(296,['IRM-ul cardiac în CMH poate detecta:',
 ['Atât hipertrofia, cât și fibroza miocardică','Doar calcificări pericardice, fără hipertrofie','Captare subendocardică transmură de infarct, ca singur pattern','Absența oricărei fibroze, diagnosticul fiind pur auscultator','Gradientul LVOTO, IRM-ul fiind inutil dacă eco-ul arată SAM'],'A',1120,'CMH — IRM: hipertrofie și fibroză',
 'Reținerea dublului rol al IRM (masă + fibroză), ilustrat în Fig. 30.109.',
 ['Textul: IRM detectează atât hipertrofia, cât și fibroza.','Calcificările pericardice țin de constricție.','Pattern-ul de infarct nu epuizează fibroza CMH.','Fibroza este vizibilă pe IRM (gadoliniu).','IRM aduce informații despre fibroză, dincolo de SAM-ul eco.']],
 8,'Reduce IRM-ul CMH la un eco de SAM și neagă fibroza — tocmai ceea ce Fig. 30.109 arată.',['fibroză','hipertrofia']),

q(297,['CMD sporadică poate fi cauzată de:',
 ['Miocardită: Coxsackie, adeno, eritrovirus, HIV, bacterii, fungi, micobacterii, paraziți (Chagas)','Toxice: alcool, chimioterapie, metale (cobalt, plumb, mercur, arsen)','Boli autoimmune, endocrine și neuromusculare','Doar mutația MYH7, identic CMH sarcomerică','Grosime parietală crescută, fără dilatare'],'ABC',1122,'CMD sporadică — Eritrovirus, metale, autoimun',
 'Completarea listei sporadice cu eritrovirusul, micobacteriile și metalele (Co/Pb/Hg/As).',
 ['Spectrul infecțios, inclusiv eritrovirus și Chagas, este enumerat.','Toxicele includ cele patru metale.','Autoimun, endocrin și neuromuscular completează lista.','MYH7 este a CMH, nu epuizează CMD sporadică.','Pereții sunt prezervați, cavitățile dilatate.']],
 8,'Reduce CMD sporadică la MYH7 sarcomeric și cere hipertrofie, fenotipul CMH.',['eritrovirusuri','cobalt']),

q(298,['Evaluarea rudelor în CMD permite:',
 ['Identificarea bolii în stadii precoce, asimptomatice, înaintea complicațiilor','Includerea istoricului familial și a arborelui genealogic în evaluarea clinică','Manifestare prin IC, aritmii, tulburări de conducere, embolii sau moarte subită','Așteptarea complicațiilor embolice înaintea oricărui screening familial','Ignorarea arborelui genealogic, boala fiind strict non-familială'],'ABC',1122,'CMD — Screening-ul rudelor',
 'Rolul screening-ului familial înaintea complicațiilor (embolie, MSC, blocuri).',
 ['Identificarea precoce asimptomatică este explicită.','Arborele genealogic face parte din evaluare.','Spectrul de prezentare include emboliile și MSC.','Screening-ul precede, nu urmează, complicațiile.','Există forma familială AD, deci arborele contează.']],
 8,'Amână screening-ul familial până după embolie, deși textul îl plasează înaintea complicațiilor.',['rudelor','arborelui genealogic']),

q(299,['CRT și ICD în CMD, la clasa NYHA III-IV:',
 ['Abordarea include tratamentul general al IC, cu opțiunea CRT și ICD','Transplantul este recomandat la unii pacienți','Biopsia rămâne de primă intenție, înaintea oricărei terapii de IC','NYHA I este indicația preferată de CRT-D, nu III-IV','Transplantul este interzis, fibroza medio-miocardică fiind o contraindicație absolută'],'AB',1123,'CMD — CRT/ICD în NYHA III-IV',
 'Reținerea nișei CRT+ICD la NYHA III-IV și a transplantului la selecționați.',
 ['CRT și ICD la NYHA III și IV sunt explicite.','Transplantul la unii pacienți este menționat.','Biopsia nu este de rutină.','Textul indică NYHA III-IV, nu I.','Fibroza IRM nu contraindică transplantul în acest paragraf.']],
 8,'Mută CRT-D de la NYHA III-IV la clasa I și interzice transplantul.',['NYHA III','IV']),

q(300,['Chilopericardul și pericardita mixedematoasă:',
 ['Figurează ca entități distincte în Cadranul 30.53','Mixedemul ține de etiologiile metabolice, alături de forma uremică','Chilopericardul înlocuiește uremia ca etiologie dominantă occidentală','Mixedemul este o cauză de BAV complet, nu de pericardită','Chilopericardul este identic tamponadei maligne, fără linie proprie în cadran'],'AB',1125,'Pericard — Chilopericard și mixedem',
 'Recunoașterea celor două linii mai puțin citate din Cadranul 30.53 (chilopericard, mixedem).',
 ['Ambele figurează în cadran.','Mixedemul stă lângă uremie.','Uremia rămâne o cauză clasică, nu este înlocuită.','Mixedemul este etiologie de pericardită în cadran.','Chilopericardul are linie proprie în cadran.']],
 8,'Scoate mixedemul din pericard — deși cadranul îl listează — și îl mută pe BAV.',['Chilopericardul','mixedematoasă']),

q(301,['Radiografia de profil în pericardita constrictivă este utilă pentru:',
 ['Detectarea calcificărilor omise pe incidența postero-anterioară','Înlocuirea ECG-ului, QRS-ul fiind constant normal','Confirmarea că orice calcificare echivalează constricția','Demonstrarea cordului globulos, identic tamponadei','Excluderea CT/IRM-ului din evaluarea grosimii pericardului'],'A',1127,'Constricție — Radiografie de profil',
 'Reținerea nișei incidenței de profil pentru calcificări omise pe clişeul PA.',
 ['Textul: o radiografie de profil poate fi utilă în detectarea calcificărilor omise pe PA.','ECG-ul arată microvoltaj cu T aplatizate/inversate.','Un pericard calcificat nu înseamnă constricție.','Constricția are cord relativ mic, nu globulos.','CT și IRM evaluează grosimea pericardului.']],
 8,'Transformă profilul — manevră pentru calcificări omise — într-un substitut de ECG normal sau de cord globulos.',['de profil','postero-anterioară']),

q(302,['Semnele tamponadei, pe măsură ce revărsatul crește, includ:',
 ['Creșterea PVJ, cu ascuțirea pantei descendente X','Semnul Kussmaul (turgescență jugulară crescută în inspir)','Puls paradoxal: scădere a presiunii sistolice ≥10 mmHg în inspir','Descendent y adânc (Friedreich), identic constricției','Zgomote cardiace accentuate și apex hiperdinamic, ca în regurgitarea aortică'],'ABC',1127,'Tamponadă — Pantă X, Kussmaul, paradox ≥10 mmHg',
 'Potrivirea pantei X ascuțite și a paradoxului ≥10 mmHg, distincte de y-ul constricției.',
 ['Panta X ascuțită este explicită.','Kussmaul este listat.','Paradoxul ≥10 mmHg este definit.','Y adânc/Friedreich aparține constricției.','Zgomotele sunt diminuate, apexul mascat.']],
 8,'Atribuie tamponadei descendentul y al constricției și apexul hiperdinamic al regurgitării aortice.',['10 mmHg','Kussmaul'],[1126]),

q(303,['Eco-semne de tamponadă, dincolo de colabarea AD/VD, includ:',
 ['Deplasarea septului interventricular spre VS în inspir','Inversarea fluxului diastolic în venele hepatice în expir','Dilatarea VCI este incompatibilă cu tamponada','Septul se deplasează spre VD în inspir, identic constricției fără lichid','Fluxul hepatic se inversează în inspir, nu în expir'],'AB',1127,'Tamponadă — Sept spre VS, vene hepatice',
 'Completarea criteriilor eco cu septul inspirator către VS și inversarea hepatică expiratorie.',
 ['Deplasarea septului spre VS în inspir este explicită.','Inversarea hepatică expiratorie este listată.','VCI este dilatată, cu colaps inspirator <50%.','Deplasarea este spre VS, nu spre VD.','Inversarea hepatică este în expir, nu în inspir.']],
 8,'Inversează direcția septului (spre VS) și timing-ul fluxului hepatic (expir).',['venele hepatice','septului']),

q(304,['CT sau IRM-ul cardiac sunt utile în revărsatele pericardice:',
 ['Închistate, post-chirurgie cardiacă','Doar ca substitut al eco-ului la toți pacienții cu frecătură','În locul pericardiocentezei, când se suspectează puroi','Pentru a evita ghidajul eco al puncției','Ca screening la pericardita virală autolimitată fără revărsat'],'A',1127,'Revărsat — CT/IRM pentru loculări postoperatorii',
 'Reținerea nișei CT/IRM: revărsate închistate după chirurgie cardiacă.',
 ['Textul rezervă CT/IRM revărsatelor închistate post-chirurgie.','Eco-ul rămâne cea mai utilă tehnică de demonstrare a revărsatului.','Puroiul este o indicație de puncție, nu de a o înlocui prin CT.','Puncția se face sub ghidaj eco.','Forma virală autolimitată fără revărsat nu cere CT/IRM.']],
 8,'Extinde CT/IRM-ul loculat postoperator la screening-ul pericarditei virale fără lichid.',['închistate','post-chirurgie cardiacă']),

q(305,['În cazurile dificile de constricție versus cardiomiopatie restrictivă, poate fi utilă:',
 ['Biopsia endomiocardică','Doar palparea apexului, fără imagistică','Înlocuirea CT/IRM-ului cu o radiografie de față, fără profil','Cateterismul care arată presiuni telediastolice inegale VS/VD, ca și cum ar infirma egalizarea','Interzicerea oricărei biopsii, diferențierea fiind imposibilă'],'A',1127,'Constricție — Biopsie versus restrictivă',
 'Reținerea biopsiei endomiocardice ca instrument de diferențiere constricție/restrictivă în cazurile dificile.',
 ['Textul: biopsia poate fi utilă în cazurile dificile, pentru diferențierea de restrictivă.','Palparea izolată nu înlocuiește imagistica.','CT/IRM evaluează grosimea; profilul completează PA.','Cateterismul arată presiuni telediastolice egale, nu inegale.','Biopsia este menționată tocmai pentru diferențiere.']],
 8,'Anulează biopsia — metoda citată de a despărți constricția de restrictivă — și inversează egalizarea presiunilor.',['Biopsia endomiocardică','restrictivă']),

q(306,['După pericardiocenteza pentru tamponadă, textul prevede și:',
 ['Un dren poate fi lăsat temporar pe loc, pentru eliminarea suficientă a lichidului','Căutarea și tratarea cauzei subiacente ori de câte ori este posibil','Hemoculturi sau determinări de autoanticorpi, după caz','Drenajul prelungit înlocuiește căutarea cauzei, revărsatul neputând recidiva','Fenestrația este primul gest la orice revărsat viral autolimitat'],'ABC',1127,'Revărsat — Dren temporar și cauza subiacentă',
 'Nișa drenului temporar post-puncție și a investigațiilor etiologice (culturi, autoanticorpi).',
 ['Drenul temporar este explicit.','Cauza subiacentă trebuie căutată și tratată.','Hemoculturile și autoanticorpii sunt menționate.','Revărsatul se poate reface; cauza rămâne esențială.','Fenestrația este pentru refill-ul neoplazic, nu pentru forma virală autolimitată.']],
 8,'Pune fenestrația pe revărsatul viral autolimitat și anulează căutarea cauzei după puncție.',['dren','autoanticorpi']),

q(307,['Conform Cadranului 30.39, un scor TIMI STEMI de 7 puncte corespunde unei mortalități la 30 de zile de circa:',
 ['4,4%','12,4%','23,4%','35,9%','0,8%'],'C',1088,'STEMI — TIMI scor 7 → 23,4%',
 'Memorarea treptei 7 puncte → 23,4%, intercalată între 16,1% (6 puncte) și 26,8% (8 puncte).',
 ['4,4% este scorul 3.','12,4% este scorul 5.','Cadranul: 7 → 23,4%.','35,9% este banda 9-16.','0,8% este scorul 0.']],
 8,'Permutează treptele 5/7/9-16 ale aceluiași tabel; doar scorul 7 dă 23,4%.',['23,4%','30 zile']),

q(308,['Protezele valvulare pot avea o durabilitate de peste:',
 ['20 de ani','2 ani, după care se înlocuiesc de rutină','6 luni, identic DAPT post-stent','48 de ore, cât fereastra de cardioversie a FA','1 an, identic degenerării biologice complete'],'A',1095,'Proteze — Durabilitate peste 20 de ani',
 'Reținerea durabilității >20 de ani a protezelor, distinctă de degenerarea biologică la circa 10 ani.',
 ['Textul: protezele pot avea durabilitate de peste 20 de ani.','2 ani subestimează net.','6 luni este DAPT, nu durata protezei.','48 de ore este fereastra FA.','Biologicele degenerează după circa 10 ani; >20 de ani este cifra de durabilitate citată aici.']],
 8,'Comprimă durabilitatea de peste 20 de ani la ferestre din SCA/FA (6 luni, 48 de ore).',['20 de ani','Protezele valvulare'],[1102]),
];
