import {advancedQuestion} from './advanced-author';
import type {SourceRow} from './source-author';
const pdfOffset=(p:number)=>p<=1048?p-837:p<=1107?p-839:p-851;
const q=(n:number,row:SourceRow,score:number,reason:string,expressions:string[],related:number[]=[])=>
 advancedQuestion('cardiologie',30,pdfOffset,`cardiologie-adv-${String(n).padStart(3,'0')}`,row,[score,reason],expressions,undefined,related);

export const CARDIOLOGIE_D=[
q(109,['Precizați enunțul corect privind decesele din primele 24 de ore de la simptomele cardiace, în Marea Britanie:',
 ['Până la 100.000 de decese; aproape jumătate survin rapid, majoritatea prin fibrilație ventriculară sau tahicardie ventriculară rapidă','Majoritatea sunt produse de bradiaritmii severe, FV fiind rară','Ischemia tranzitorie este exclusă ca factor declanșator','Supraviețuitorii prezintă, în marea lor majoritate, infarct acut evident clinic','BLS se amână până la confirmarea necrozei pe markeri'],'A',1045,'Proceduri terapeutice — Resuscitarea cardiacă',
 'Reținerea ordinii de mărime 100.000, a ponderii deceselor rapide și a mecanismului FV/TV, nu bradiaritmic.',
 ['Textul: până la 100.000 de decese în primele 24 de ore; aproape jumătate survin rapid; majoritatea prin FV sau TV rapidă.','Bradiaritmiile severe produc o proporție mai mică de decese.','Ischemia tranzitorie este suspectată ca factor declanșator major.','Doar o mică proporție dintre supraviețuitori au infarct acut evident.','BLS trebuie inițiat imediat la stop, nu după markerii de necroză.']],
 8,'Inversează mecanismul dominant (FV/TV) cu bradiaritmia și amână BLS până la enzime.',['100.000 de decese','tahicardie ventriculară rapidă']),

q(110,['Inițierea suportului vital de bază la un pacient neresponsiv:',
 ['Primul pas este evitarea expunerii la pericole suplimentare','Urmează testarea la stimuli verbali sau dureroși; dacă nu respiră sau respiră anormal, BLS se începe imediat','Cu cât durata stopului cardio-respirator este mai lungă, cu atât șansa de revenire este mai mică','Primul gest este palparea prelungită a pulsului, înaintea oricărei alte măsuri','Ajutorul se solicită abia după 10 minute de observație pasivă'],'ABC',1045,'Proceduri terapeutice — Primii pași BLS',
 'Ordinea: siguranța scenei, stimuli, apel, apoi BLS dacă respirația lipsește sau este anormală.',
 ['Textul plasează evitarea pericolelor ca prim pas al BLS.','Apoi testarea la stimuli; BLS imediat dacă nu respiră sau respiră anormal.','Durata mai lungă a stopului reduce șansa de revenire.','Detectarea pulsului poate fi dificilă; nu este primul pas.','Dacă nu se obține răspuns, ajutorul se solicită imediat.']],
 8,'Pune palparea pulsului înaintea siguranței scenei, inversând algoritmul BLS.',['pericole suplimentare','stimuli verbali']),

q(111,['Fiecare dintre cele două respirații de salvare eficiente, după 30 de compresiuni la adult, durează:',
 ['3-4 secunde, pentru o expansiune toracică maximală','10 secunde, identic ventilației post-intubație','1 secundă','30 de secunde, câte una per ciclu BLS','15 secunde, ca la copilul cu salvator unic'],'C',1046,'Suportul vital de bază — Respirația de salvare',
 'Reținerea duratei de 1 secundă a fiecărei respirații eficiente la adult.',
 ['3-4 secunde este o durată excesivă față de text.','10/minut este rata după abordarea avansată a căilor aeriene, nu durata insuflației BLS.','Textul: două respirații eficiente timp de 1 secundă fiecare.','30 de secunde nu este durata unei insuflații.','La copil, salvatorul unic aplică cel puțin un minut de RCP înainte de a cere ajutor, nu insuflații de 15 secunde.']],
 8,'Confundă durata de 1 secundă a insuflației cu rata 10/min post-intubație sau cu fereastra pediatrică de 1 minut.',['1 secundă','Două respiraţii eficiente']),

q(112,['Suportul vital cardiac avansat, odată ce BLS este asigurat, constă în:',
 ['Monitorizare ECG, management avansat al căilor aeriene și abord venos periferic mare sau central','Abord intraosos dacă abordul venos este imposibil','Stabilirea tipului de ritm (DAE sau defibrilator standard) și aplicarea algoritmului ACLS','Începerea ACLS înaintea oricărei compresiuni, fără BLS','Limitarea abordului vascular la venele de pe dorsul mâinii'],'ABC',1046,'Suportul vital avansat — Componente ACLS',
 'Recunoașterea triadei monitorizare–căi aeriene–acces vascular, inclusiv opțiunea intraosoasă.',
 ['Textul enumeră monitorizarea ECG, intubația/dispozitivele supraglotice și cateterele venoase.','Abordul intraosos este permis când abordul venos nu este posibil.','Ritmul (DAE sau defibrilator standard) determină abordarea ulterioară.','ACLS urmează după ce BLS a fost asigurat.','Se vizează vene periferice mari sau o venă centrală, nu doar dorsul mâinii.']],
 8,'Inversează ordinea BLS→ACLS și limitează accesul vascular la venele mici de la mână.',['intraosos','algoritmul ACLS']),

q(113,['Tratamentul imediat după revenirea circulației spontane include:',
 ['Algoritmul ABCDE','Țintă SpO2 94-98%','Țintă PaCO2 normal','ECG în 12 derivații, tratamentul cauzei și controlul temperaturii','Hiperventilație pentru PaCO2 foarte scăzut, fără ECG'],'ABCD',1047,'Post-ROSC — Ținte imediate',
 'Aplicarea ABCDE, a ferestrei SpO2 94-98% și a PaCO2 normal după ROSC.',
 ['Algoritmul ABCDE este listat ca tratament imediat post-RCP.','Ținta de saturație este 94-98%.','Se urmărește PaCO2 normal, nu hipocapnie indusă.','ECG în 12 derivații, cauza și temperatura sunt explicite.','Hiperventilația agresivă și omiterea ECG nu apar în algoritm.']],
 8,'Înlocuiește țintele 94-98% și PaCO2 normal cu hiperventilație, eroare clasică post-ROSC.',['94-98%','Algoritmul ABCDE']),

q(114,['După abordarea avansată a căilor respiratorii, ventilația în timpul RCP continuă cu:',
 ['20/minut, cu întreruperea masajului la fiecare ciclu','Raport 30:2, identic BLS-ului fără cale avansată','10/minut, fără a întrerupe masajul cardiac','6/minut, doar în asistolă','Apnee până la ROSC'],'C',1048,'ACLS — Ventilație după cale aeriană avansată',
 'Reținerea ratei de 10/minut fără întreruperea compresiilor, odată calea aeriană asigurată.',
 ['20/minut cu pauze de masaj este contrar textului.','30:2 este raportul BLS înaintea căii avansate.','Textul: rată de ventilație de 10/minut fără a întrerupe masajul.','6/minut nu este rata citată.','Ventilația continuă; nu se așteaptă ROSC în apnee.']],
 8,'Păstrează 30:2 sau 20/min cu pauze — tocmai ce textul abandonează după intubație.',['10/minut','masajul cardiac']),

q(115,['Pozițiile acceptate ale padelor de defibrilare sunt:',
 ['Una la dreapta sternului superior și cealaltă deasupra apexului cardiac','Una sub vârful scapulei stângi și cealaltă pe peretele anterior al hemitoracelui stâng','Ambele pe abdomen, pentru a evita miocardul','Doar sub scapula dreaptă, poziția stern-apex fiind abandonată','Padelele monofazice sunt preferate pentru că necesită energie mai mică decât cele bifazice'],'AB',1048,'Defibrilarea — Plasarea padelor',
 'Memorarea celor două poziții (stern-apex și scapulă stângă–hemitorace stâng anterior).',
 ['Prima poziție este descrisă explicit.','A doua poziție (scapulă stângă + perete anterior stâng) este alternativa citată.','Padelele se aplică pe torace, nu pe abdomen.','Poziția stern-apex este una dintre cele două acceptate.','Bifazicele necesită energie mai mică și sunt din ce în ce mai utilizate.']],
 8,'Inversează ierarhia bifazic/monofazic și anulează una dintre cele două poziții clasice.',['dreapta sternului','scapulei stângi']),

q(116,['Recuperarea neurologică după stop cardiac pare mai bună la pacienții cu:',
 ['Absența oricărei activități EEG timp de 3 săptămâni','Areactie prelungită, fără mișcări voluntare','Hipertermie menținută la 40°C','Mișcări voluntare și activitate electroencefalografică în primele 3 zile','Evitarea oricărui control al temperaturii corporale'],'D',1048,'Post resuscitare — Prognostic neurologic',
 'Reținerea ferestrei de 3 zile (mișcări voluntare + EEG) ca marker de prognostic mai bun.',
 ['Lipsa EEG prelungită nu este markerul favorabil citat.','Areactia fără mișcări voluntare este nefavorabilă.','Hipertermia 40°C nu este strategia descrisă.','Textul: prognostic mai bun dacă există mișcări voluntare și activitate EEG în primele 3 zile.','Controlul temperaturii face parte din îngrijirea post-ROSC.']],
 8,'Transformă fereastra favorabilă de 3 zile într-un argument pentru areactie prelungită sau hipertermie.',['3 zile','mişcări voluntare']),

q(117,['Funcția nodului sinusal și ritmul sinusal normal:',
 ['Parasimpaticul predomină în mod normal, scăzând rata de descărcare de la circa 100 la circa 70 b.p.m.','Undele P sunt pozitive în DI și DII și negative în aVR','Frecvența sinusului este ușor mai crescută la femei','Tonusul vagal crescut al sportivului produce tahicardie de efort patologică','Aritmia sinusală inspiratorie (creșterea frecvenței) este patologică la copii și tineri'],'ABC',1051,'Aritmii — Nodul sinusal și aritmia sinusală',
 'Contrastul modulării vagale 100→70 b.p.m. cu polaritatea P și cu caracterul fiziologic al aritmiei sinusale.',
 ['Textul: parasimpaticul scade rata de la 100 la aproximativ 70 b.p.m.','P pozitive în DI/DII, negative în aVR.','Frecvența este ușor mai crescută la femei.','La sportivi, bradicardia fiziologică se datorează tonusului vagal crescut.','Variația inspiratorie este normală, mai ales la copii și tineri.']],
 8,'Etichetează aritmia sinusală a tânărului și bradicardia sportivului drept patologie, deși textul le consideră fiziologice.',['70 b.p.m','negative în AVR']),

q(118,['Activitatea declanșată (trigger) se caracterizează prin:',
 ['Post-potențiale precoce, de obicei la sfârșitul fazei 3, înainte ca potențialul transmembranar să atingă pragul','Post-potențiale tardive care apar înainte de sfârșitul fazei 3, identic celor precoce','Agravare de către catecolamine, tulburări electrolitice, hipoxie, acidoză, medicamente sau stimulare; tahicardiile atriale din intoxicația digitalică au acest mecanism','Reintrare care cere un miez excitabil, fără zonă cicatricială','Originea majorității tahicardiilor paroxistice regulate în automatismul sinusal izolat'],'AC',1052,'Mecanisme aritmogene — Post-potențiale',
 'Diferențierea post-potențialelor precoce (sfârșit de fază 3) de cele tardive și legătura cu digitala.',
 ['Definiția post-potențialelor precoce este explicită.','Tardivele apar după ce potențialul transmembranar atinge pragul, nu înainte.','Oscilațiile sunt agravate de factorii citați; digitala acționează prin trigger.','Reintrarea se organizează în jurul unui miez inexcitabil (cicatrice).','Majoritatea tahicardiilor paroxistice regulate au la bază reintrarea.']],
 8,'Suprapune precocele peste tardive și atribuie tahicardiilor paroxistice automatismul sinusal, nu reintrarea.',['post-potenţiale precoce','intoxicaţia digitalică']),

q(119,['În sincopa vasovagală se recomandă:',
 ['Evitarea situațiilor declanșatoare, clinostatism sau poziție șezândă și manevre de contrapresiune la prodrom','Aport crescut de sare, ciorapi de compresie, midodrină, beta-blocante sau disopiramidă','Ablația de nod AV ca tratament de primă linie','Interzicerea poziției șezânde, care ar agrava prodromul','La forma „malignă” (traumatisme și asistolă documentată) stimulare bicamerală cu funcție „rate drop response”'],'ABE',1053,'Bradicardii — Tratamentul sincopei vasovagale',
 'Recunoașterea măsurilor non-farmacologice, a midodrinei și a stimulării cu rate-drop în forma malignă.',
 ['Măsurile posturale și contrapresiunea sunt descrise.','Sarea, compresia, midodrina, beta-blocantele și disopiramida sunt listate.','Ablația de nod AV nu este tratamentul sincopei vasovagale.','Clinostatismul sau poziția șezândă sunt recomandate, nu interzise.','Textul rezervă „rate drop response” formei maligne cu asistolă.']],
 8,'Înlocuiește contrapresiunea și midodrina cu ablația de nod AV, strategie a FA-ului „ablate and pace”.',['midodrina','rate drop response']),

q(120,['Identificați afirmația corectă referitoare la BAV de gradul I:',
 ['Se definește prin prelungirea PR peste 0,20 sec, fiecare depolarizare atrială fiind totuși condusă la ventriculi','Nicio undă P nu este condusă','PR scade progresiv până la o undă P blocată','Este identic cu Mobitz II, având QRS >0,12 sec de rutină','Conducerea 2:1 definește BAV de gradul I'],'A',1053,'BAV — Gradul I',
 'Fixarea pragului PR >0,20 sec cu conducere 1:1, distinct de Mobitz și de conducerea 2:1.',
 ['Textul: PR peste 0,20 sec; fiecare depolarizare atrială este condusă, dar cu întârziere.','Absența conducerii definește BAV complet.','Prelungirea progresivă până la o P blocată este Mobitz I.','Mobitz II este un subtip de BAV II, nu gradul I.','Conducerea 2:1 este o formă aparte de BAV II.']],
 8,'Confundă BAV I (toate P conduse, PR lung) cu Mobitz sau cu conducerea 2:1.',['0,20 sec','BAV de gradul I'],[1054]),

q(121,['Cauzele blocului atrioventricular complet (Cadranul 30.13) includ:',
 ['Boala Lev (fibroză distală progresivă la vârstnici) și boala Lenegre (fibroză proximală la tineri)','Boala Lyme, boala Chagas și LES matern în forma congenitală','Hipertiroidismul netratat ca etiologie dominantă a BAV complet','Digoxin, beta-blocante, non-dihidropiridinice, amiodaronă; post-înlocuire de valvă aortică','Doar ischemia, fără cauze infecțioase, iatrogene sau infiltrative'],'ABD',1055,'BAV complet — Etiologie (Cadranul 30.13)',
 'Potrivirea Lev/Lenegre cu vârsta și a cauzelor infecțioase (Lyme, Chagas) și medicamentoase.',
 ['Cadranul opune fibroza distală a vârstnicului (Lev) celei proximale a tânărului (Lenegre).','Lyme, Chagas și LES matern sunt listate.','Hipertiroidismul nu figurează ca etiologie dominantă a BAV complet.','Medicamentele citate și chirurgia aortică/CABG/DSV sunt în tabel.','Cauzele includ infecții, infiltrative, iatrogene și neuromusculare, nu doar ischemia.']],
 8,'Reduce BAV complet la ischemie și ignoră perechea Lev/Lenegre și infecțiile clasice (Lyme, Chagas).',['Boala Lev','Boala Lyme']),

q(122,['Ritmul de scăpare cu QRS larg (>0,12 sec) în BAV complet:',
 ['Are originea în fasciculul His, cu frecvență 50-60 b.p.m. și este relativ stabil','Are originea sub His, frecvență 15-40 b.p.m., este instabil și se asociază cu sincopa Stokes-Adams','Cardiostimularea permanentă este indicată, întrucât reduce semnificativ mortalitatea','Atropina vindecă durabil forma cronică distală, stimularea fiind superfluă','Boala Lev a vârstnicului afectează sistemul His-Purkinje proximal, nu distal'],'BC',1055,'BAV complet — Scăpare cu QRS larg',
 'Contrastul scăpării distale lente (15-40, Stokes-Adams) față de cea hisiană 50-60.',
 ['50-60 b.p.m. și originea hisiană aparțin scăpării cu QRS îngust.','Textul: origine sub His, 15-40 b.p.m., instabil, Stokes-Adams.','Stimularea permanentă reduce semnificativ mortalitatea.','Atropina poate fi încercată în BAV recent cu QRS îngust și cauză tranzitorie, nu ca vindecare a formei distale cronice.','Lev este fibroza distală a vârstnicului; Lenegre este proximală la tineri.']],
 8,'Atribuie scăpării largi frecvența hisiană 50-60 și inversează sediul Lev/Lenegre.',['15-40 b.p.m','Stokes-Adams']),

q(123,['Care dintre următoarele afirmații diferențiază corect blocul de ramură dreaptă de cel stâng?',
 ['BRD: activare tardivă a VD, unde S adânci în DI și V6, unde R ample tardive în V1','BRS: undă S adâncă în V1 și undă R amplă tardivă în DI și V6; produce și unde Q anormale','BRD determină de regulă o dedublare distanțată dar fiziologică a zgomotului 2; BRS poate cauza dedublare inversată','BRD lasă neschimbată activarea, fără S în DI','BRS nu modifică zgomotul 2, pe când BRD produce dedublare paradoxală'],'ABC',1056,'Bloc de ramură — ECG și zgomotul 2',
 'Opunerea vectorilor BRD/BRS și a dedublării fiziologice largi versus paradoxale.',
 ['Descrierea ECG a BRD este explicită.','BRS are modificări opuse și, inițiind activarea, produce unde Q anormale.','Dedublarea distanțată fiziologică (BRD) versus inversată (BRS) este descrisă.','BRD produce S adânci în DI și V6.','Relația cu Z2 este inversată în această afirmație.']],
 8,'Inversează dedublarea Z2 (fiziologică largă în BRD versus paradoxală în BRS).',['dedublare distanţată','unde Q anormale']),

q(124,['Tahicardia sinusală inadecvată și tahicardia sinusală secundară:',
 ['IST: creștere persistentă a frecvenței de repaus, disproporționată față de stres; mai frecventă la femei tinere','Cauze acute de tahicardie sinusală secundară: efort, durere, febră, infecții, ICA, embolie pulmonară, hipovolemie','Ivabradina (blocant If) poate fi folosită când beta-blocantele nu sunt tolerate','Este diagnosticul de primă intenție la bărbatul vârstnic cu boală structurală','Tratamentul răspunsului compensator are prioritate față de identificarea cauzei'],'ABC',1057,'TSV — Tahicardia sinusală inadecvată',
 'Recunoașterea terenului (femei tinere) și a ivabradinei ca alternativă, după tratarea cauzei secundare.',
 ['Definiția și predominanța la femei tinere sunt explicite.','Lista cauzelor acute este din text.','Ivabradina este menționată când beta-blocantele nu sunt tolerate.','IST nu este diagnosticul de primă intenție al vârstnicului cu boală structurală.','Identificarea și tratarea factorului declanșator sunt preferabile tratamentului răspunsului compensator.']],
 8,'Pune IST pe bărbatul vârstnic structural și tratează compensarea înaintea cauzei.',['femeile tinere','ivabradina']),

q(125,['Conform Cadranului 30.14, cea mai frecventă tahicardie la pacienții peste 65 de ani este:',
 ['AVNRT, ca la tinerii cu cord normal','Fibrilația atrială','Tahicardia atrială multifocală','Tahicardia joncțională accelerată','AVRT prin fascicul Kent'],'B',1058,'TSV — Cadranul 30.14 (comentarii)',
 'Reținerea FA ca tahicardie dominantă peste 65 de ani, distinct de AVNRT a tânărului.',
 ['AVNRT este cea mai comună cauză de palpitații la cord normal, nu tahicardia dominantă a vârstnicului.','Cadranul: FA — cea mai frecventă tahicardie la pacienții >65 ani.','MAT este rară, asociată BPOC semnificativ.','Tahicardia joncțională accelerată este rară la adulți.','AVRT se datorează unei căi accesorii, nu este aritmia dominantă a vârstei.']],
 8,'Atribuie vârstnicului AVNRT-ul tânărului cu cord normal, deși tabelul rezervă FA categoriei >65 ani.',['>65 ani','Fibrilaţia atrială']),

q(126,['AVNRT atipică și alte TSV din Cadranul 30.14:',
 ['În 5-10% din cazuri, AVNRT este „fast-slow”, cu interval AP\' lung','Tahicardia atrială multifocală: unde P cu ≥3 morfologii și RR neregulate, cel mai frecvent în BPOC semnificativă','Flutterul nu trebuie luat în considerare la TSV regulată cu 150/min','AVNRT este cea mai comună cauză de palpitații la pacienții cu cord normal','Tahicardia joncțională accelerată este cea mai frecventă TSV a adultului'],'ABD',1058,'TSV — AVNRT fast-slow și MAT',
 'Memorarea ponderii 5-10% a formei fast-slow și a asocierii MAT–BPOC.',
 ['Textul: 5-10%, anterograd pe calea rapidă, retrograd pe cea lentă, AP\' lung.','MAT: P cu morfologii diferite și RR neregulate; BPOC.','La TSV regulată 150/min trebuie considerat flutterul.','Comentariul cadranului atribuie AVNRT palpitațiile de cord normal.','Tahicardia joncțională accelerată este rară la adulți.']],
 8,'Omite flutterul de la 150/min — capcana clasică de TSV regulată — și umflă raritatea joncționalei.',['5-10%','fast-slow']),

q(127,['Manifestările clinice ale AVNRT și AVRT includ:',
 ['Palpitații regulate cu debut și final brusc, adesea terminate prin Valsalva','Poliurie prin eliberare de peptid natriuretic atrial, mai ales în AVNRT și fibrilație atrială','Verapamilul i.v. este de primă intenție imediat după un beta-blocant, inclusiv la QRS >0,12 sec','Adenozina nu influențează aceste TSV, fiind rezervată tahicardiei ventriculare','Pulsații venoase jugulare proeminente în AVNRT, prin contracție atrială pe valve AV închise'],'ABE',1059,'AVNRT/AVRT — Tablou clinic',
 'Reunirea Valsalvei, a poliuriei prin ANP și a pulsațiilor jugulare din AVNRT.',
 ['Debut/final brusc și terminarea prin Valsalva sunt caracteristice.','Poliuria prin ANP este descrisă, mai ales în AVNRT și FA.','Verapamilul nu se dă după beta-blocante și nici la QRS larg.','Adenozina este foarte eficientă în AVNRT/AVRT și influențează rar TV.','Pulsațiile jugulare din AVNRT sunt explicite.']],
 8,'Interzice adenozina (tocmai agentul de elecție) și asociază verapamilul cu beta-blocantul la QRS larg.',['peptid natriuretic atrial','Valsalva'],[1058]),

q(128,['Alegeți afirmațiile corecte referitoare la tratamentul acut al AVNRT/AVRT:',
 ['Instabilitatea hemodinamică (hipotensiune, edem pulmonar) impune cardioversie de urgență','Manevrele vagale (masaj carotidian, Valsalva, imersie facială în apă rece) pot opri criza','Digoxinul i.v. este antiaritmicul de elecție în WPW cu QRS larg','Verapamil 5-10 mg i.v. se administrează imediat după un beta-blocant la QRS >0,12 sec','Diagnosticul diferențial AVNRT versus AVRT trebuie elucidat înaintea oricărei manevre, tratamentele fiind radical diferite'],'AB',1059,'AVNRT/AVRT — Tratament acut',
 'Prioritatea cardioversiei la instabil și a manevrelor vagale la stabil, înaintea adenozinei.',
 ['Textul: instabilitatea impune cardioversie de urgență.','Cele trei manevre vagale sunt enumerate.','Digoxinul (ca și verapamilul) poate accelera conducerea pe calea accesorie în FA preexcitată.','Verapamilul nu se dă după beta-blocante și nici la QRS larg.','Diferențierea nu este esențială acut: ambele răspund la același tratament.']],
 8,'Cere diferențierea AVNRT/AVRT înaintea manevrelor, deși textul spune că tratamentul acut este comun.',['cardioversie de urgenţă','imersia feţei']),

q(129,['Fibrilația atrială — mecanism electric și prezentare:',
 ['Activare atrială continuă, rapidă (300-600/min), adesea din focare de la venele pulmonare','La circa 30% dintre pacienți este o descoperire incidentală','Fără tratament, frecvența ventriculară este de obicei 120-180/min','Pulsul rămâne neregulat și în timpul efortului, spre deosebire de extrasistole','Undele P înalte, regulate, definesc fibrilația'],'ABCD',1060,'Fibrilația atrială — Mecanism și tablou',
 'Aplicarea ferestrelor 300-600/min atrial, 120-180 ventricular netratat și a ponderii 30% incidente.',
 ['Frecvența atrială 300-600 și originea venoasă pulmonară sunt explicite.','Aproximativ 30% sunt descoperiri incidentale.','Fără tratament, răspunsul ventricular este de obicei 120-180/min.','Neregularitatea persistă la efort, spre deosebire de extrasistole sau Wenckebach.','FA se caracterizează prin absența undelor P și oscilații fine ale liniei de bază.']],
 8,'Pune unde P regulate pe FA — tocmai aritmia definită prin absența lor.',['300-600 b.p.m.','120-180 b.p.m']),

q(130,['Ca strategie primară, controlul frecvenței în fibrilația atrială:',
 ['Se obține în general prin combinație de digoxin, beta-blocante sau non-dihidropiridinice (verapamil, diltiazem)','Digoxinul în monoterapie poate fi suficient la vârstnicii inactivi; la tineri efectul vagotonic este anulat de catecolamine','La vârstnici cu control slab sub terapie optimă se poate abla nodul AV și implanta un stimulator („ablate and pace”), cu anticoagulare continuă','Ținta de repaus este sub 50/min la toți tinerii, fără Holter','Ablația de nod AV permite oprirea anticoagulării, riscul trombotic dispărând'],'ABC',1061,'Fibrilația atrială — Controlul frecvenței și „ablate and pace”',
 'Recunoașterea combinației digoxin/BB/non-DHP și a strategiei ablate-and-pace cu anticoagulare pe viață.',
 ['Combinația celor trei clase este explicită.','Monoterapia cu digoxin la vârstnicii inactivi și limita la tineri sunt descrise.','„Ablate and pace” amelioră simptomele, dar anticoagularea rămâne necesară.','Țintele citate sunt <110 în repaus, apoi 60-80 și <110 la efort dacă simptomele persistă; tinerii au nevoie de Holter și test de efort.','Riscul tromboembolic persistă după ablația de nod.']],
 8,'Oprește anticoagularea după „ablate and pace”, deși textul o menține din cauza riscului trombotic persistent.',['ablate and pace','Digoxinul în monoterapie']),

q(131,['Rata complicațiilor majore (accident vascular cerebral și sângerări) ale ablației de fibrilație atrială este de circa:',
 ['20%','50%','2%','0,01%','35%'],'C',1061,'Fibrilația atrială — Riscurile ablației',
 'Reținerea ordinii de mărime 2% pentru AVC și sângerări post-ablație.',
 ['20% este cu un ordin de mărime peste text.','50% nu apare.','Textul: AVC și sângerări în aproximativ 2% din cazuri.','0,01% subestimează riscul.','35% este o altă ordine de mărime, necitată.']],
 8,'Umflă complicațiile ablației de la 2% la 20-50%, ordine de mărime alăturate dar false.',['2% din cazuri','vene pulmonare']),

q(132,['Anticoagularea orală în fibrilația atrială non-valvulară:',
 ['Warfarină cu INR 2,0-3,0 sau un DOAC: dabigatran (inhibitor direct de trombină) ori rivaroxaban/apixaban (anti-Xa)','DOAC: acțiune mai rapidă, timp de înjumătățire mai scurt, mai puține interacțiuni, fără monitorizare INR','Antiagregantele plachetare sunt alternativa recomandată anticoagulării pentru prevenția AVC','La contraindicație sau intoleranță se poate considera închiderea percutană a urechiușei atriale stângi','Antiagregantele nu sunt recomandate pentru prevenția accidentului vascular cerebral'],'ABDE',1062,'Fibrilația atrială — DOAC, warfarină și LAAO',
 'Contrastul cascadei DOAC versus warfarină și respingerea antiagregantelor ca substitut de prevenție a AVC.',
 ['INR 2,0-3,0 și cele două clase DOAC sunt explicite.','Avantajele farmacocinetice față de warfarină sunt listate.','Textul: antiagregantele nu sunt recomandate pentru prevenția AVC.','LAAO este opțiunea la contraindicație/intoleranță.','Afirmația E reia concluzia cadranului/textului.']],
 8,'Pune antiagregantul în locul anticoagulării — strategie pe care textul o respinge explicit.',['INR de 2,0-3,0','urechiuşei atriale stângi']),

q(133,['Un scor CHA2DS2-VASc de 0 puncte corespunde unui risc anual de AVC ischemic de:',
 ['2,2%, cu anticoagulare orală imediată','0%, fără profilaxie','5%, identic HAS-BLED ≥3','1,3%, ca la 1 punct','35,9%, ca TIMI STEMI 9-16'],'B',1062,'Fibrilația atrială — CHA2DS2-VASc 0 puncte',
 'Reținerea perechii 0 puncte = 0% risc, fără profilaxie.',
 ['2,2% este pragul de la 2+ puncte.','Cadranul: 0 puncte = 0% risc, fără profilaxie.','>5% este riscul hemoragic HAS-BLED ≥3, nu riscul trombotic CHA2DS2-VASc 0.','1,3% corespunde 1 punct.','35,9% aparține TIMI STEMI, nu CHA2DS2-VASc.']],
 8,'Confundă 0% de la 0 puncte cu 2,2% (2+ puncte) sau cu HAS-BLED hemoragic.',['0% risc','Fără profilaxie']),

q(134,['Flutterul atrial — polaritatea undelor F și conducerea 1:1:',
 ['În forma antiorară, undele F sunt negative în derivațiile inferioare și pozitive în V1-V2','În forma orară, orientarea undelor F este inversă','Conducerea 1:1 produce frecvență ventriculară de 300/min','Antiorarul are F pozitive inferior și negative în V1','Masajul sinusului carotidian nu poate demasca undele F'],'ABC',1062,'Flutter atrial — Antiorar, orar și 1:1',
 'Opunerea polarității F antiorar/orar și recunoașterea răspunsului 1:1 la 300/min.',
 ['Polaritatea antiorară este descrisă astfel.','Orarul inversează orientarea F.','Fiecare undă condusă dă 300/min ventricular.','Aceasta este polaritatea orarului, nu a antiorarului.','Masajul carotidian sau adenozina/verapamilul pot demasca undele F.']],
 8,'Inversează polaritatea F antiorar/orar și neagă manevra de demascare a flutterului.',['flutter antiorar','300 b.p.m.']),

q(135,['Tahicardia atrială prin automatism crescut:',
 ['Are frecvențe 125-250/min și prezintă adesea „warm-up” și „cool-down”','Focarul este cel mai frecvent pe crista terminalis, lângă o venă pulmonară sau în jurul unei urechiușe','Masajul sinusului carotidian o oprește constant, ca pe AVNRT','Poate fi incesantă și conduce la cardiomiopatie tahiaritmică','Este mai lentă decât forma prin reintrare (125-150/min)'],'ABD',1063,'Tahicardia atrială — Automatism',
 'Contrastul 125-250/min cu warm-up față de forma prin reintrare mai lentă și a riscului de cardiomiopatie.',
 ['Frecvențele și fenomenele warm-up/cool-down sunt explicite.','Localizările focarului sunt cele trei citate.','Masajul crește gradul de BAV și ajută diagnosticul, dar nu oprește tahicardia.','Forma incesantă poate produce cardiomiopatie tahiaritmică.','Forma prin reintrare este de obicei mai lentă (125-150), nu mai rapidă.']],
 8,'Oprește tahicardia atrială cu masaj carotidian — manevră care doar crește BAV-ul — și inversează vitezele automatism/reintrare.',['warm-up','cristei terminalis']),

q(136,['Proporția tahicardiilor cu complexe largi care sunt ventriculare este de circa:',
 ['80%, și mai mare la pacienții cu boală cardiacă structurală','5%, restul fiind TSV cu aberanță','50% fără boală structurală și 10% cu boală structurală','Sub 1%, dacă QRS depășește 0,14 sec','100%, dacă QRS este sub 0,12 sec'],'A',1063,'TV versus TSV cu aberanță — Ponderea 80%',
 'Reținerea regulii 80% (și mai mult la boală structurală) în fața unei tahicardii cu QRS larg.',
 ['Textul: 80% din tahicardiile cu complexe largi sunt ventriculare; proporția e și mai mare la boală structurală.','5% subestimează net.','Raportul 50/10 este inversat față de mesajul textului.','QRS >0,14 sec orientează spre TV, nu o face rară.','QRS îngust nu definește TV.']],
 8,'Subestimează ponderea TV în tahicardia cu QRS larg, deși textul o plasează la 80%.',['80%','complexe largi']),

q(137,['Fibrilația ventriculară în relație cu infarctul miocardic acut:',
 ['Dacă episodul apare în primele 1-2 zile post-IMA, terapia profilactică nu este de obicei necesară','Dacă episodul nu este legat de un IMA, riscul pe termen lung de stop și moarte subită este mare','ICD este tratament de primă linie la supraviețuitori în absența unei cauze reversibile','Orice FV peri-infarct impune ICD înaintea externării, inclusiv în primele 24 de ore','Cauzele reversibile (IMA, tulburări metabolice severe) nu modifică indicația de ICD'],'ABC',1064,'Fibrilația ventriculară — Fereastra peri-infarct',
 'Aplicarea ferestrei 1-2 zile: FV precoce post-IMA fără profilaxie versus FV fără cauză reversibilă cu ICD.',
 ['Textul: în primele 1-2 zile post-IMA, profilaxia nu este probabil necesară.','În afara infarctului, riscul pe termen lung este mare.','ICD este prima linie la supraviețuitori fără cauză reversibilă.','FV din primele 1-2 zile nu impune de la sine ICD.','Cauzele reversibile (IMA, metabolice) schimbă strategia.']],
 8,'Implantează ICD pentru FV-ul precoce post-IMA, tocmai scenariul în care textul nu cere profilaxie.',['1-2 zile','Defibrilatoarele implantabile']),

q(138,['Sindromul Brugada — genetică și modalități de prezentare:',
 ['În 20% din cazuri este moștenit prin mutație SCN5A, cu pierderea funcției canalelor de sodiu','Au fost implicate și SCN5B, GPD1L și subunități ale canalelor de calciu (CACNA1C, CACNB2)','Beta-blocantele sunt tratamentul de elecție și reduc mortalitatea','Este mai frecvent la femei vârstnice din Europa de Nord decât la bărbați tineri din Asia de Sud-Est','Prezentări: moarte subită în somn, stop resuscitat, sincopă, sau descoperire incidentală/familială'],'ABE',1064,'Sindromul Brugada — Gene și prezentare',
 'Reținerea ponderii 20% SCN5A și a prezentării nocturne, față de ineficiența beta-blocantelor.',
 ['20% SCN5A cu loss-of-function este explicit.','Celelalte gene sunt enumerate.','Beta-blocantele nu sunt utile, putând fi chiar nocive; tratamentul eficient este ICD.','Predomină tinerii de sex masculin din Asia de Sud-Est.','Somnul, stopul, sincopa și forma incidentală sunt listate.']],
 8,'Păstrează beta-blocantul ca elecție — agent pe care textul îl consideră inutil sau nociv — și inversează epidemiologia.',['20% din cazuri','SCN5A']),

q(139,['Tratamentul sindromului QT lung congenital, dincolo de faza acută:',
 ['Beta-blocante, uneori stimulator, uneori denervare simpatică cardiacă stângă','LQT1 răspunde bine la beta-blocante; LQT3 mai bine la blocante ale canalelor de sodiu','Isoprenalina intravenoasă este prima linie și în forma congenitală','Pacienții care rămân simptomatici, cu QT marcat și istoric familial de MSC, necesită de obicei ICD','Între crize, QTc măsoară de obicei peste 0,50 sec'],'ABDE',1065,'QT lung congenital — Tratament de durată',
 'Potrivirea LQT1–beta-blocant versus LQT3–blocant de Na+ și a pragului QTc >0,50 sec.',
 ['Strategia pe termen lung include aceste trei axe.','Răspunsul diferențiat LQT1/LQT3 este explicit.','Isoprenalina este contraindicată în forma congenitală (utilă în cea dobândită).','ICD-ul este rezervat simptomaticilor cu QT marcat sau istoric familial de MSC.','QTc >0,50 sec este pragul citat între episoade.']],
 8,'Folosește isoprenalina — utilă în QT dobândit — ca primă linie în forma congenitală, unde este contraindicată.',['0,50 sec','denervare simpatică']),

q(140,['Sindromul QT scurt și extrasistolele ventriculare:',
 ['Sunt descrise doar 2 tipuri, fără risc de moarte subită','Sunt descrise 5 tipuri; pot predispune la aritmii ventriculare și MSC, ICD fiind tratamentul optim','Fenomenul R pe T poate precipita fibrilația ventriculară, mai ales post-infarct','Extrasistolele ventriculare se tratează de rutină cu antiaritmice de clasă Ic după un infarct','După ESV nu urmează pauză compensatorie, nodul AV rămânând excitabil'],'BC',1066,'QT scurt și extrasistole ventriculare',
 'Reținerea celor 5 tipuri de QT scurt cu indicație de ICD și a riscului R-pe-T post-IMA.',
 ['Nu sunt 2 tipuri fără risc.','Textul: 5 tipuri, risc de MSC, ICD optim.','R pe T poate duce la FV, mai ales post-infarct.','ESV se tratează doar dacă sunt simptomatice; clasa I post-IMA a crescut mortalitatea în CAST.','De obicei urmează o pauză compensatorie completă.']],
 8,'Reduce QT scurt la o raritate benignă și tratează ESV post-IMA cu clasa Ic, strategia CAST nocivă.',['5 tipuri','R pe T']),

q(141,['Antiaritmicele de clasă I (blocante de sodiu):',
 ['Reduc influxul de sodiu, pot încetini conducerea, prelungi repolarizarea și reduce automatismul','CAST: clasa Ic a crescut mortalitatea la extrasistole ventriculare post-IMA; chinidina (Ia) a crescut-o la FA','Utilizarea clasei I, inclusiv flecainida, se limitează la absența bolii coronariene, a disfuncției de VS sau a altei boli structurale semnificative','Clasa Ib (lidocaină, mexiletină) scurtează potențialul de acțiune','Clasa Ic prelungește potențialul de acțiune, identic Ia'],'ABCD',1067,'Antiaritmice — Clasa I și CAST',
 'Aplicarea lecției CAST: clasa I se evită pe cord ischemic/structural; Ib scurtează PA, Ic nu-l afectează.',
 ['Mecanismul de clasă I este descris astfel.','CAST (Ic) și datele cu chinidina (Ia) sunt citate.','Limitarea la cord fără BCI/disfuncție/boală structurală este explicită.','Cadranul 30.19: Ib scurtează potențialul de acțiune.','Ic nu afectează durata potențialului de acțiune.']],
 8,'Atribuie clasei Ic prelungirea de PA a Ia, deși tabelul o lasă fără efect pe durata PA.',['trialurile CAST','canalelor de sodiu']),

q(142,['Mecanismul principal al antiaritmicelor de clasă III este:',
 ['Blocarea influxului de sodiu în faza 0, ca clasa I','Antagonism beta pur, fără efect pe potasiu','Prelungirea potențialului de acțiune prin blocarea componentei rapide a curentului de potasiu (IKr), fără a afecta transportul de sodiu','Scurtarea fazei de platou, identic verapamilului','Agonism pe canalele de calciu'],'C',1067,'Antiaritmice — Clasa III (IKr)',
 'Reținerea blocadei IKr fără efect pe sodiu ca mecanism de clasă III.',
 ['Blocarea sodiului este clasa I.','Sotalolul are și efect beta, dar clasa III nu se reduce la antagonism beta pur.','Textul: prelungesc PA prin blocarea IKr, fără a afecta transportul de Na+.','Scurtarea platoului este clasa IV.','Agonismul calciu nu este mecanismul clasei III.']],
 8,'Reduce clasa III la un beta-blocant pur sau o confundă cu clasa I/IV, deși nucleul este IKr.',['curentului de potasiu','sotalolul']),

q(143,['Ablația căilor accesorii și a preexcitației:',
 ['Rata de succes a ablației de AVNRT și de cale accesorie este mai mare de 95%','Căile care conduc doar retrograd nu au risc crescut de moarte subită, dar pot produce AVRT','Profilactic, se recomandă ablația căii accesorii la asimptomatici cu traseu ECG sugestiv WPW','Riscul principal la calea stângă este blocul de ramură izolat, nu tromboembolismul','TV pe cord structural normal are risc de MSC identic bolii structurale'],'ABC',1068,'Ablație — WPW simptomatic, ascuns și profilactic',
 'Contrastul căii doar retrograde (fără MSC) versus recomandarea profilactică la ECG WPW și succesul >95%.',
 ['Succesul >95% este explicit.','Căile doar retrograde: fără risc crescut de MSC, dar cu AVRT posibilă.','Ablația profilactică la ECG WPW asimptomatic este recomandată.','La calea stângă, riscul principal este tromboembolismul.','TV pe cord normal nu are risc crescut de MSC și se tratează ușor prin ablație.']],
 8,'Neagă indicația profilactică la WPW-ul ECG și înlocuiește tromboembolismul căii stângi cu un BRD inofensiv.',['mai mare de 95%','pre-excitaţie']),

q(144,['În prevenția secundară după o tahiaritmie ventriculară amenințătoare de viață, ICD:',
 ['A îmbunătățit supraviețuirea în trialul AVID (antiaritmice versus ICD)','Are baterie de litiu pentru circa 100 de șocuri de 30 J','Șocurile sunt nedureroase dacă pacientul este conștient','Reduce moartea subită la 40% pe an','Nu poate avea sondă atrială, ci doar ventriculară'],'AB',1068,'ICD — AVID, energie și durere',
 'Reținerea AVID, a celor 100 de șocuri de 30 J și a caracterului dureros al șocului la conștient.',
 ['AVID a demonstrat beneficiu de supraviețuire.','Circa 100 de șocuri de 30 J sunt cifrele din text.','Șocurile sunt dureroase la conștient; overdrive-ul este nedureros.','Rata MSC scade la 2% pe an; 40% este mortalitatea în primul an fără strategie adecvată.','Dispozitivele moderne pot avea sonde în AD și VD.']],
 8,'Umflă MSC sub ICD de la 2% la 40% pe an — tocmai mortalitatea netratată din primul an.',['100 şocuri','30 J']),

q(145,['Dincolo de cifrele de incidență deja cunoscute, insuficiența cardiacă:',
 ['Este cauza principală de spitalizare după vârsta de 65 de ani','Costul managementului în Marea Britanie depășește 1 miliard de lire sterline pe an','Printre cauzele „alte” se numără trastuzumab/imatinib, circulația hiperdinamică (anemie, tireotoxicoză, Paget) și bolile pericardice','În Occident, cauza dominantă rămâne boala reumatică','Prognosticul s-a înrăutățit în ultimii 10 ani, mortalitatea la 5 ani fiind sub 5%'],'ABC',1069,'Insuficiența cardiacă — Spitalizări, cost și cauze rare',
 'Completarea epidemiologiei cu spitalizarea post-65 de ani, costul >1 miliard și etiologiile chimioterapice/hiperdinamice.',
 ['Textul: cauza principală de spitalizare după 65 de ani.','Costul depășește 1 miliard de lire/an.','Cadranul 30.20 include chimioterapia, stările hiperdinamice și pericardul.','În țările occidentale cauza cea mai frecventă este boala coronariană.','Prognosticul s-a îmbunătățit; mortalitatea la 5 ani rămâne circa 50%, nu sub 5%.']],
 8,'Repune reumatismul ca etiologie occidentală dominantă și comprimă mortalitatea la 5 ani de la 50% la 5%.',['1 miliard','trastuzumab']),

q(146,['Adaptările hemodinamice din insuficiența cardiacă severă:',
 ['Redistribuția sângelui menține perfuzia inimii, creierului și rinichilor, în detrimentul tegumentelor și mușchilor','Creșterea postsarcinii crește debitul și micșorează volumul telediastolic','Activarea simpatică cronică este un mecanism pur protector, fără down-regulation de receptori-β','În forma foarte severă, debitul scade și în repaus, deși presiunile venoase sunt mari','În disfuncție ușoară, debitul de repaus se poate menține prin creșterea presiunii venoase'],'ADE',1070,'Insuficiența cardiacă — Redistribuție și postsarcină',
 'Recunoașterea redistribuției spre organele vitale și a menținerii debitului de repaus prin presiune venoasă în disfuncția ușoară.',
 ['Redistribuția inimă–creier–rinichi versus tegumente/mușchi este explicită.','Postsarcina crescută scade debitul, crește VTD și dilată VS, mărind și mai mult postsarcina.','Activarea simpatică cronică este nocivă (neurohormoni, apoptoză) și e compensată prin down-regulation.','În IC foarte severă debitul scade și în repaus.','Disfuncția ușoară menține debitul prin creșterea presiunii venoase.']],
 8,'Prezintă hiperpostsarcina ca un mecanism care crește debitul, inversând cercul vicios Laplace.',['inimii, creierului şi rinichilor','tegumentelor şi muşchilor']),

q(147,['Funcția endotelială și hormonul antidiuretic în insuficiența cardiacă:',
 ['Vasodilatația dependentă de endoteliu este afectată în vasele periferice și poate contribui la scăderea toleranței la efort','Endotelina plasmatică este crescută și se corelează cu severitatea hemodinamică; antagoniștii de ET i.v. ameliorează acut tulburările hemodinamice','ADH crește în IC cronică severă, mai ales sub diuretice; hiponatremia precipitată este un indicator prognostic nefavorabil','Oxidul nitric este în exces și explică vasodilatația de efort','CNP este secretat predominant de ventriculi, identic BNP'],'ABC',1071,'Insuficiența cardiacă — Endotelină și ADH',
 'Legarea disfuncției endoteliale și a ET crescute de hiponatremia prin ADH ca marker nefavorabil.',
 ['Textul leagă disfuncția endotelială de toleranța scăzută la efort.','ET crescută, corelația hemodinamică și efectul acut al antagoniștilor sunt descrise.','ADH crescut sub diuretice și hiponatremia ca prognostic nefavorabil sunt explicite.','Activitatea NO este insuficientă, nu în exces.','CNP este limitat la endoteliu și SNC, nu este echivalentul ventricular al BNP.']],
 8,'Pune NO-ul — descris ca insuficient — în exces și mută CNP-ul în ventricul.',['endotelina','Hormonul antidiuretic']),

q(148,['Investigațiile imagistice în insuficiența cardiacă includ:',
 ['Radiografia, care nu evaluează liniile Kerley B sau redistribuția către lobii superiori','Ecocardiografia de stres cu dobutamină, care identifică rezerva contractilă a miocardului siderat sau hibernant','Biopsia endomiocardică de primă linie la toți pacienții cu HFpEF','IRM-ul pentru structură, funcție și viabilitate (dobutamină sau gadoliniu tardiv, „imagistica de infarct”)','Cateterismul, care nu măsoară presiunea capilară pulmonară blocată'],'BD',1072,'Insuficiența cardiacă — Investigații (eco de stres, IRM)',
 'Rolul dobutaminei pentru rezerva contractilă și al IRM cu gadoliniu tardiv ca „imagistică de infarct”.',
 ['Radiografia evaluează tocmai cardiomegalia, redistribuția, scizurile, Kerley B și edemul.','Eco de stres cu dobutamină: rezervă contractilă a sideratului/hibernantului.','Biopsia este pentru amiloidoză și rejet de graft, nu screening HFpEF.','IRM-ul cu cele două tehnici de viabilitate este descris.','Cateterismul măsoară PAP, presiunea atrială stângă (capilară blocată) și PTDVS.']],
 8,'Anulează liniile Kerley B — semn radiologic clasic de IC — și promovează biopsia ca screening HFpEF.',['Kerley B','imagistica de infarct']),

q(149,['Recomandările privind stilul de viață în insuficiența cardiacă cronică includ:',
 ['Restricție de sare; în forma severă, reducerea aportului de lichide și cântărire zilnică','Exerciții de anduranță de nivel scăzut (20-30 min de mers 3-5×/săptămână sau 20 min de bicicletă la 70-80% din FCmax, 5×/săptămână); efortul izometric intens se evită','Vaccinare împotriva infecției pneumococice și a gripei','În Marea Britanie, pacienții cu IC simptomatică sau FEVS <40% au interdicție de a conduce camioane mari și autobuze','Nitrații se asociază de rutină cu sildenafil, pentru a crește toleranța la efort'],'ABCD',1073,'Insuficiența cardiacă — Stil de viață, vaccin și condus',
 'Aplicarea ferestrelor de antrenament, a vaccinării și a pragului FEVS <40% pentru vehicule grele.',
 ['Restricția de sare/lichide și cântărirea zilnică sunt explicite.','Protocolul de anduranță și interdicția efortului izometric sunt din text.','Vaccinarea pneumococică și gripală este recomandată.','Interdicția UK pentru camioane/autobuze la simptome sau FEVS <40% este citată.','Nitrații plus inhibitori PDE5 pot induce hipotensiune severă.']],
 8,'Asociază nitrații cu sildenafil — combinație pe care textul o interzice din cauza hipotensiunii.',['20-30 min','FEVS mai mică de 40%']),

q(150,['La testul de efort cardiopulmonar din insuficiența cardiacă, consumul maxim de oxigen (VO2) este:',
 ['Fără valoare prognostică','Util doar pentru diagnosticul de astm','Un substitut al radiografiei toracice','O indicație de a opri diureticele','Predictiv pentru spitalizări și mortalitate; testul de mers de 6 minute este o alternativă'],'E',1073,'Insuficiența cardiacă — VO2 și testul de 6 minute',
 'Reținerea valorii prognostice a VO2 și a testului de 6 minute ca alternativă.',
 ['VO2 este predictiv, nu lipsit de valoare.','Nu este un test de astm.','Nu înlocuiește radiografia.','Nu ghidează oprirea diureticelor.','Textul: VO2 predictiv pentru spitalizări și mortalitate; 6 minute ca alternativă.']],
 8,'Neagă valoarea prognostică a VO2, deși textul o leagă explicit de spitalizări și mortalitate.',['V02','6 minute']),

q(151,['Din Cadranul 30.25, dozele și precauțiile relevante includ:',
 ['Ramipril 1,25-2,5 mg/zi inițial, maxim 10 mg/zi; prudență dacă creatinina >250 µmol/L sau TAS <90 mmHg','Sacubitril/valsartan: oprirea IECA cu 3 zile înainte; ARA se opresc în ziua administrării','Bisoprolol 1,25 mg → 10 mg/zi; de evitat în IC acută până la stabilizare cardiovasculară','Digoxinul se crește peste 2,5 mg/zi de rutină când eRFG <30 ml/min/1,73 m²','Metolazona este interzisă în IC severă'],'ABC',1074,'Insuficiența cardiacă — Cadranul 30.25 (doze)',
 'Aplicarea treptelor ramipril/bisoprolol, a ferestrei de 3 zile IECA→ARNI și a pragului de creatinină 250 µmol/L.',
 ['Dozele de ramipril și pragurile de prudență sunt din tabel.','Wash-out-ul IECA 3 zile și oprirea ARA în ziua ARNI sunt explicite.','Bisoprololul și precauția din acut sunt listate.','Peste 2,5 mg/zi de digoxin sunt rar necesare; eficiența scade la eRFG <30.','Metolazona se folosește în IC severă.']],
 8,'Crește digoxinul peste 2,5 mg tocmai la eRFG <30, unde tabelul cere prudență și doze mici.',['3 zile înainte','250 µmol/L']),

q(152,['Nebivololul, în insuficiența cardiacă, se utilizează:',
 ['În forma stabilă, ușoară sau moderată, la pacienți cu vârsta peste 70 de ani','Ca substitut al diureticelor de ansă la tineri','Doar în NYHA IV refractar, în locul transplantului','Intravenos, ca inotrop de primă linie în FA rapidă','Fiind contraindicat peste 70 de ani'],'A',1074,'Insuficiența cardiacă — Nebivolol',
 'Reținerea nișei nebivololului: IC stabilă ușoară/moderată la >70 de ani.',
 ['Textul delimitează exact această populație.','Nu înlocuiește diureticele.','Nu este alternativa transplantului în NYHA IV.','Nu este inotrop i.v. pentru FA.','Indicația citată este tocmai peste 70 de ani, nu contraindicația.']],
 8,'Inversează nișa de vârstă: din indicație la >70 de ani în contraindicație.',['peste 70 de ani','Nebivololul']),

q(153,['Miocardul hibernant se deosebește de cel siderat prin:',
 ['Hibernant: disfuncție reversibilă prin boală coronariană cronică, viabil la stres inotrop, recuperare după revascularizare','Siderat: disfuncție reversibilă care persistă după un episod de ischemie, deși fluxul a revenit la normal (mismatch flux-funcție)','Hibernarea este consecința necrozei transmurale ireversibile','Hibernarea rezultă din episoade repetate de siderare, de exemplu la efort repetat','Sideratul contraindică revascularizarea, fiind echivalent cicatricii'],'ABD',1075,'Miocard hibernant versus siderat',
 'Contrastul hipoperfuziei cronice viabile (hibernant) versus mismatch-ul post-ischemic cu flux restabilit (siderat).',
 ['Definiția hibernantului este explicită.','Sideratul este mismatch-ul flux-funcție după ischemie.','Necroza/cicatricea nu se tratează; hibernantul și sideratul răspund la revascularizare.','Textul leagă hibernarea de episoade repetate de siderare.','Ambele entități justifică revascularizarea, spre deosebire de cicatrice.']],
 8,'Echivalează hibernarea cu necroza ireversibilă, inversând tocmai rațiunea revascularizării.',['Miocardul siderat','mismatch']),

q(154,['Revascularizarea chirurgicală la pacientul cu angină și disfuncție de ventricul stâng:',
 ['Are mortalitate perioperatorie sub 0,1%','Se asociază cu mortalitate chirurgicală 10-20%, dar acești pacienți au cel mai mult de câștigat ulterior (simptome și prognostic)','Decizia ține cont de simptome, vârstă, comorbidități și de dovada ischemiei reversibile','Rolul revascularizării în IC este pe deplin clarificat, fără incertitudini','Inotropele i.v. reduc mortalitatea pe termen lung față de placebo'],'BC',1075,'Insuficiența cardiacă — Revascularizare la disfuncție de VS',
 'Reținerea paradoxului 10-20% mortalitate chirurgicală versus cel mai mare câștig ulterior.',
 ['0,1% subestimează net riscul citat.','Cifrele 10-20% și beneficiul ulterior sunt explicite.','Factorii de decizie sunt listați.','Textul spune că rolul revascularizării în IC nu este clarificat.','Inotropele ameliorează hemodinamica, dar nu s-a dovedit că scad mortalitatea pe termen lung.']],
 8,'Comprimă mortalitatea chirurgicală de la 10-20% la 0,1% și atribuie inotropelor un beneficiu de supraviețuire nedovedit.',['10-20%','Miocardul „hibernant']),

q(155,['Complicațiile și limitele transplantului cardiac includ:',
 ['Infecții tardive (2-6 luni) cu germeni oportuniști (toxoplasmoză, CMV, fungi, Pneumocystis)','Vasculopatia de alogrefă la 30-50% dintre pacienți la 5 ani, principală cauză de eșec tardiv al grefei','Contraindicații: vârstă >60 de ani (variază între centre), rezistențe vasculare pulmonare crescute, cancer activ','Denervarea scade frecvența de repaus și crește variabilitatea tensională diurnă','NYHA IV în stadiu final este indicația preferată de ICD izolat, fără CRT'],'ABC',1076,'Transplant cardiac — Infecții, vasculopatie, contraindicații',
 'Memorarea ferestrei 2-6 luni a oportuniștilor și a vasculopatiei 30-50% la 5 ani.',
 ['Cadranul 30.26: oportuniștii în lunile 2-6.','30-50% la 5 ani, cauză principală de eșec tardiv.','Cadranul 30.27 include vârsta >60, RVP și cancerul.','Denervarea crește frecvența de repaus și pierde variabilitatea TA diurne.','NYHA IV terminal nu este, în general, candidat la ICD.']],
 8,'Inversează efectele denervării (tahicardie de repaus, pierderea variației diurne) și promovează ICD-ul în NYHA IV terminal.',['30-50%','2-6 luni']),

q(156,['Sindroamele clinice din Cadranul 30.28 (ICA) includ:',
 ['ICA hipertensivă: tensiune crescută, funcție de VS păstrată, edem pulmonar radiologic','Șoc cardiogen: TAS <90 mmHg, diureză <0,5 ml/kg pe oră, frecvență >60 b.p.m.','Insuficiență cardiacă dreaptă: debit scăzut, PVJ crescută, hepatomegalie, hipotensiune','Edem pulmonar acut: saturație >98% în aerul atmosferic, fără raluri','IC cu debit crescut: periferie caldă, congestie pulmonară, tensiune posibil scăzută (ex. șoc septic)'],'ABCE',1077,'Insuficiența cardiacă acută — Cadranul 30.28',
 'Potrivirea celor patru fenotipuri (hipertensiv, șoc, drept, debit crescut) cu saturația <90% din edemul pulmonar.',
 ['Definiția ICA hipertensive este din tabel.','Pragurile de șoc sunt cele din cadran.','IC dreaptă are acest tablou de congestie sistemică.','Edemul pulmonar acut: tahipnee, ortopnee, raluri, saturație <90%, nu >98% fără raluri.','Debitul crescut (periferie caldă, ex. septic) este listat.']],
 8,'Definește edemul pulmonar prin saturație >98% fără raluri, inversul cadranului (<90%, raluri, ortopnee).',['<90 mmHg','Periferie caldă']),

q(157,['Doza inițială de furosemid intravenos menționată în terapia ICA este:',
 ['5 mg, identic atenololului i.v.','500 mg bolus unic, fără reevaluare','1 mg subcutanat','50 mg i.v.','0,125 mg, ca digoxinul de întreținere'],'D',1077,'Insuficiența cardiacă acută — Furosemid inițial',
 'Reținerea bolusului de 50 mg i.v. de furosemid ca terapie inițială, alături de oxigen.',
 ['5 mg este doza de atenolol i.v. din SCA, nu de furosemid.','500 mg depășește doza inițială citată.','Calea este i.v., nu s.c. 1 mg.','Textul: furosemid 50 mg i.v.','0,125 mg este doza de digoxin, nu de diuretic.']],
 8,'Confundă 50 mg furosemid cu 5 mg atenolol sau 0,125 mg digoxin, doze din același capitol.',['50 mg i.v.','furosemid']),

q(158,['Monitorizarea și vasodilatatoarele în insuficiența cardiacă acută:',
 ['Anticoagularea profilactică cu heparină cu masă moleculară mică este necesară','Nitrații i.v. (gliceril trinitrat 10-200 µg/min) cer monitorizare atentă a tensiunii, de exemplu în ischemie concomitentă sau hipertensiune severă','Deteriorarea hemodinamică poate necesita linie arterială, cateter venos central și cateter de arteră pulmonară','Gliceril trinitratul este de primă intenție la TAS <85 mmHg, înaintea inotropelor','Ecocardiografia transtoracică se amână 7 zile, până după diuretic'],'ABC',1077,'ICA — HGMM, GTN și monitorizare invazivă',
 'Aplicarea ferestrei GTN 10-200 µg/min și a anticoagulației profilactice, nu a nitratului la TAS <85 mmHg.',
 ['Textul: toți pacienții necesită HGMM profilactic.','Doza 10-200 µg/min și indicațiile (ischemie, HTA severă) sunt explicite.','Cele trei linii de monitorizare invazivă sunt listate.','La TAS <85 mmHg algoritmul indică inotrope/vasopresoare, nu nitratul ca primă intenție.','ETT trebuie efectuată fără întârziere.']],
 8,'Pune nitratul ca primă linie la TAS <85 mmHg — pragul la care textul trece pe inotrope/vasopresoare.',['10-200 µg/min','heparină cu greutate mole']),
];
