import {advancedQuestion} from './advanced-author';
import type {SourceRow} from './source-author';
const pdfOffset=(p:number)=>p<=1048?p-837:p<=1107?p-839:p-851;
const q=(n:number,row:SourceRow,score:number,reason:string,expressions:string[],related:number[]=[])=>
 advancedQuestion('cardiologie',30,pdfOffset,`cardiologie-adv-${String(n).padStart(3,'0')}`,row,[score,reason],expressions,undefined,related);

export const CARDIOLOGIE_F=[
q(209,['Studiul multinațional din 2013 privind temperatura țintită după stop cardiac a arătat:',
 ['Rezultate similare ale hipotermiei moderate (33°C) față de normotermie (36°C)','Rezultate neurologice mai bune (dar nu și de mortalitate) într-un grup cu ritmuri neșocabile','Că 28°C timp de 72 de ore este standardul actual, superior celor 33°C','Că importanța hipotermiei terapeutice rămâne încă neclară','Că hipertermia la 40°C ameliorează mortalitatea în ritmurile șocabile'],'ABD',1048,'Post resuscitare — Studiul de temperatură 2013',
 'Reținerea comparației 33 versus 36°C și a nuanței că beneficiul neurologic din ritmurile neșocabile nu clarifică încă rolul hipotermiei.',
 ['Textul citează rezultate similare la 33°C versus 36°C.','În ritmuri neșocabile s-au raportat rezultate neurologice mai bune, fără câștig de mortalitate.','28°C/72 de ore nu este protocolul citat.','Concluzia paragrafului: importanța hipotermiei terapeutice este încă neclară.','Hipertermia nu este strategia descrisă.']],
 8,'Confundă țintele 33/36°C cu o hipotermie profundă de 28°C, deși textul lasă importanța metodei neclară.',['33°C','normotermie']),

q(210,['Automatismul accelerat se caracterizează prin:',
 ['Depolarizare diastolică lentă până la prag, urmată de potențialul de acțiune al celulelor pacemaker','Accelerare prin creșterea pantei depolarizării diastolice sau prin modificarea potențialului prag','Stimulare simpatică cu eliberare de adrenalină, producând tahicardie sinusală, ritmuri de scăpare și ritmuri joncționale accelerate','Un miez inexcitabil cicatricial ca element necesar','Originea majorității tahicardiilor paroxistice regulate, identic reintrării'],'ABC',1051,'Aritmii — Automatismul accelerat',
 'Diferențierea automatismului (pantă fază 4 / prag) de reintrarea în jurul unui miez inexcitabil.',
 ['Automatismul normal este descris astfel.','Cele două modalități de accelerare sunt explicite.','Adrenalina leagă tahicardia sinusală de ritmurile de scăpare și joncționale accelerate.','Miezul inexcitabil aparține reintrării, nu automatismului.','Majoritatea tahicardiilor paroxistice regulate au la bază reintrarea.']],
 8,'Atribuie automatismului miezul cicatricial al reintrării, două mecanisme consecutive din Fig. 30.38.',['potenţialul prag','ritmuri de scăpare']),

q(211,['Cauzele extrinseci ale bradicardiei sinusale și reflexul Bezold-Jarisch includ:',
 ['Hipotermia, hipotiroidismul, icterul colestatic și hipertensiunea intracraniană','Tratamentul cu beta-blocante, digitalice sau alte antiaritmice','Reflexul Bezold-Jarisch, care poate produce bradicardie (sinusală, oprire sinusală sau BAV) și vasodilatație periferică','Hipertiroidismul netratat ca etiologie dominantă a bradicardiei sinusale','Ischemia acută a nodului sinusal, clasată printre cauzele extrinseci, nu intrinseci'],'ABC',1052,'Bradicardii — Cauze extrinseci și Bezold-Jarisch',
 'Potrivirea listei extrinseci (inclusiv icterul colestatic) cu reflexul care asociază bradicardie și vasodilatație.',
 ['Cele patru cauze sistemice sunt enumerate.','Medicamentele antiaritmice/beta-blocante/digitalice sunt cauze extrinseci.','Bezold-Jarisch produce atât bradicardie, cât și vasodilatație.','Hipertiroidismul cauzează tahicardie, nu bradicardie.','Ischemia/infarctul nodului sinusal sunt cauze intrinseci.']],
 8,'Mută ischemia nodului — cauză intrinsecă — în lista extrinsecă și pune hipertiroidismul pe bradicardie.',['icterul colestatic','Bezold- Jarisch']),

q(212,['Sindromul de tahicardie ortostatică posturală (POTS) și sincopa iatrogenă:',
 ['POTS: creștere acută semnificativă a frecvenței, cu TA normală sau ușor redusă la ortostatism','Mecanismul este vasoconstricția periferică insuficientă, compensată prin creșterea frecvenței','Medicamentele antihipertensive, antidepresivele triciclice și neurolepticele pot cauza sincopă, mai ales la vârstnici','POTS se definește prin hipotensiune severă fără creșterea frecvenței','Sincopa iatrogenă se evită prin creșterea dozelor și prin asocierea a două sedative'],'ABC',1052,'Bradicardii — POTS și sincopa medicamentoasă',
 'Recunoașterea vasoconstricției insuficiente ca mecanism POTS și a claselor care precipită sincopa vârstnicului.',
 ['Definiția hemodinamică este explicită.','Vasoconstricția insuficientă compensată tahicardic este mecanismul citat.','Cele trei clase medicamentoase sunt listate.','TA este normală sau ușor redusă, nu hipotensiune fără tahicardie.','Textul cere adaptarea posologiei și evitarea asocierii a două medicamente care pot produce pierderea conștienței.']],
 8,'Inversează hemodinamica POTS (tahicardie cu TA păstrată) într-o hipotensiune fără răspuns cronotrop.',['ortostatică posturală','neurolep']),

q(213,['Cardiostimularea temporară în bradicardia sinusală este indicată:',
 ['La cauze reversibile, până la restaurarea ritmului sinusal','La afectarea cronică degenerativă, până la implantarea stimulatorului permanent','Ca substitut definitiv al stimulării DDD în boala de nod simptomatică','Doar după eșecul ablației de nod AV','În POTS, ca primă linie, înaintea oricărei măsuri de hidratare'],'AB',1053,'Bradicardii — Stimulare temporară',
 'Delimitarea ferestrei temporare: cauză reversibilă până la sinus versus punte către stimulatorul permanent.',
 ['Textul rezervă stimularea temporară cauzelor reversibile până la restaurarea sinusului.','La degenerarea cronică, temporarul este punte către implantul permanent.','Boala de nod simptomatică poate necesita DDD permanent, nu un temporar ca substitut definitiv.','Ablația de nod AV nu este pasul prealabil al temporarului din bradicardia sinusală.','POTS nu are ca primă linie cardiostimularea temporară.']],
 8,'Transformă puntea temporară într-un substitut definitiv al DDD, inversând treptele de tratament.',['Cardiostimularea temporară','restaurarea ritmului sinusal']),

q(214,['Printre cauzele de BAV complet din Cadranul 30.13 se numără:',
 ['Chirurgia cardiacă: post-înlocuire de valvă aortică, by-pass coronarian, corectarea DSV','Iatrogen: ablația cu radiofrecvență a nodului AV și implantarea de stimulator','Boli neuromusculare, de exemplu distrofia musculară Duchenne','Hipertiroidismul ca etiologie dominantă, înaintea fibrozei idiopatice','Doar ischemia, fără cauze chirurgicale sau neuromusculare'],'ABC',1055,'BAV complet — Chirurgie, iatrogen, Duchenne',
 'Completarea cadranului cu porțile chirurgicală, iatrogenă și Duchenne, distincte de ischemia deja cunoscută.',
 ['Cele trei contexte chirurgicale sunt listate.','Ablația de nod AV figurează la iatrogene.','Duchenne este exemplul neuromuscular.','Hipertiroidismul nu este cauza dominantă din cadran.','Cadranul include și chirurgie, infecții, boli reumatice, nu doar ischemia.']],
 8,'Reduce etiologia BAV complet la ischemie, deși cadranul include AVR, DSV și Duchenne.',['Duchenne','By-pass coronarian']),

q(215,['Blocul bifascicular se caracterizează prin:',
 ['Combinația dintre blocul de ramură dreaptă și hemiblocul antero-superior sau postero-inferior','Faptul că blocarea fasciculului rămas determină BAV complet','Sincope prin bloc complet intermitent sau tahiaritmii ventriculare, care cer monitorizare ECG și studiu electrofiziologic','Identitatea cu hemiblocul antero-superior izolat, fără BRD','Un QRS constant sub 0,10 sec, fără risc de BAV complet'],'ABC',1056,'Blocuri — Blocul bifascicular',
 'Recunoașterea combinației BRD + hemibloc și a riscului ca al treilea fascicul să închidă BAV-ul complet.',
 ['Definiția combinației este explicită.','Blocul fasciculului rămas produce BAV complet.','Sincopele (bloc intermitent sau TV) impun monitorizare și studiu EP.','Hemiblocul izolat nu este bifascicular.','Blocul complet de ramură presupune QRS ≥0,12 sec; riscul de BAV există.']],
 8,'Reduce bifascicularul la un hemibloc izolat și anulează riscul de BAV la blocarea fasciculului rămas.',['Blocul bifascicular','hemibloc']),

q(216,['Printre cauzele cronice de tahicardie sinusală secundară se numără:',
 ['Sarcina, anemia, hipertiroidismul și excesul de catecolamine','Doar efortul fizic acut, fără cauze persistente','Blocul de ramură stângă complet, ca etiologie dominantă','Hipotermia și icterul colestatic, identic bradicardiei sinusale','Identificarea cauzei fiind superfluă, ivabradina înlocuind orice anchetă'],'A',1057,'TSV — Cauze cronice de tahicardie sinusală',
 'Reținerea listei cronice (sarcină, anemie, tireotoxicoză, catecolamine), distinctă de cauzele acute.',
 ['Cele patru cauze cronice sunt enumerate explicit.','Efortul, durerea, febra țin de cauzele acute.','BRS este o tulburare de conducere, nu o cauză de tahicardie sinusală.','Hipotermia și icterul colestatic produc bradicardie.','Identificarea factorului declanșator este preferabilă tratamentului răspunsului compensator.']],
 8,'Mută cauzele de bradicardie (hipotermie, icter) pe tahicardia sinusală cronică.',['hipertiroidismul','excesul de catecolamine']),

q(217,['Căile accesorii (fascicule Kent) și sindromul WPW:',
 ['Cele mai frecvente căi Kent sunt în peretele liber sau septal','Căile bidirecționale vizibile pe ECG de suprafață se numesc căi manifeste','WPW asociază istoricul de palpitații cu preexcitație pe ECG (PR scurt și undă delta)','Fibrele Mahaim sunt localizate constant pe inelul mitral stâng, nu în regiunea ramurii drepte','Căile ascunse conduc anterograd și sunt vizibile în sinus prin undă delta'],'ABC',1058,'TSV — Fascicule Kent, căi manifeste și WPW',
 'Potrivirea Kent (perete liber/septal) cu definiția WPW (palpitații + preexcitație) și a căilor manifeste.',
 ['Localizarea perete liber sau septal este explicită.','Căile bidirecționale vizibile = manifeste.','WPW = palpitații + preexcitație (PR scurt, undă delta).','Mahaim pătrund în miocardul ventricular în regiunea ramurii drepte.','Căile ascunse conduc doar ventricul→atriu și nu sunt vizibile în sinus.']],
 8,'Inversează Mahaim (ramură dreaptă) cu inelul mitral și face din calea ascunsă o cale anterogradă cu undă delta.',['fascicule Kent','undă delta']),

q(218,['Adenozina în tratamentul acut al AVNRT/AVRT:',
 ['Se dă inițial 6 mg i.v. bolus, apoi 12 mg dacă este nevoie','Este o nucleozidă purinică cu acțiune scurtă, care produce BAV complet pentru o fracțiune de secundă','Efectele adverse (durere toracică, senzație de moarte iminentă, bronhospasm, roșeață) sunt de scurtă durată; se folosește cu precauție la astmatici','Influențează foarte rar tahicardiile ventriculare','Este antiaritmicul de elecție în FA preexcitată cu QRS larg, împreună cu verapamilul'],'ABCD',1059,'AVNRT/AVRT — Adenozina 6/12 mg',
 'Aplicarea dozelor 6 apoi 12 mg, a BAV-ului tranzitor și a precauției la astmatici, nu a folosirii în FA-WPW.',
 ['Schema 6 mg apoi 12 mg este explicită.','Nucleozida purinică și BAV-ul de o fracțiune de secundă sunt descrise.','Lista de efecte scurte și precauția la astmatici sunt din text.','Influențează foarte rar tahicardiile ventriculare.','Verapamilul/digoxinul sunt interzise în FA-WPW; adenozina nu este elecția QRS-ului larg preexcitat.']],
 8,'Extinde adenozina — utilă în AVNRT — la FA preexcitată, unde textul interzice blocantele de nod.',['6 mg i.v.','12 mg']),

q(219,['Verapamilul, diltiazemul și beta-blocantele, ca tratament de durată al AVNRT/AVRT, s-au dovedit eficiente în circa:',
 ['60-80% dintre cazuri','10% dintre cazuri','96%, identic modificării căii lente','1%, identic riscului de BAV la ablație','50%, identic recurenței după ablația unei căi accesorii'],'A',1059,'AVNRT/AVRT — Eficiența 60-80%',
 'Reținerea ferestrei 60-80% a blocantelor de nod, distinctă de 96%/95% ale ablației.',
 ['Textul: eficiență în 60-80% dintre cazuri.','10% subestimează.','96% este succesul modificării căii lente.','1% este riscul de BAV complet la ablația căii lente.','5% este recurența după ablația unei căi accesorii, nu 50%.']],
 8,'Confundă 60-80% al medicamentelor cu 96% al ablației de cale lentă, două procente alăturate pe aceeași pagină.',['60-80%','Verapamilul']),

q(220,['Fibrilația atrială familială și forma de pe stenoză mitrală reumatismală:',
 ['Defectele genelor de pe cromozomii 10, 6, 5 și 4 se asociază cu FA familială','Când este cauzată de stenoza mitrală reumatismală, debutul FA corespunde unei agravări considerabile a insuficienței cardiace','Răspunsul ventricular depinde de proprietățile nodului AV și de echilibrul simpatic–parasimpatic','Genele implicate sunt doar ale canalelor de calciu, fără proteine de joncțiune gap','Pe stenoza mitrală, FA ameliorează prognosticul prin scăderea presiunii venoase pulmonare'],'ABC',1060,'Fibrilația atrială — Cromozomi 10/6/5/4 și SM reumatismală',
 'Potrivirea lociilor cromozomiale familiale cu deteriorarea hemodinamică de la debutul FA pe stenoza mitrală.',
 ['Cei patru cromozomi sunt enumerați.','Debutul FA pe SM reumatismală agravează considerabil IC.','Răspunsul ventricular depinde de nodul AV și de tonusul vegetativ.','Textul menționează canale de sodiu, potasiu, proteine gap și izomerism, nu doar calciul.','FA pe SM agravează, nu ameliorează, insuficiența.']],
 8,'Anulează agravarea clasică a stenozei mitrale la debutul FA și reduce genetica familială la canalele de calciu.',['cromozomii 10, 6, 5','stenoză mitrală reumatismală']),

q(221,['Un scor CHA2DS2-VASc de 1 punct corespunde unui risc anual de AVC ischemic de:',
 ['0%, fără nicio discuție de anticoagulare','1,3%, cu luarea în considerare a anticoagulării la bărbați','2,2%, cu anticoagulare orală imediată, identic pragului de 2+ puncte','>5%, identic HAS-BLED ≥3','35,9%, ca TIMI STEMI 9-16'],'B',1062,'Fibrilația atrială — CHA2DS2-VASc 1 punct',
 'Reținerea treptei 1,3% (1 punct, de luat în considerare la bărbați), intercalată între 0% și 2,2%.',
 ['0% este scorul 0.','Cadranul: 1 punct = 1,3%; se ia în considerare anticoagularea la bărbați.','2,2% este pragul de la 2+ puncte.','>5% este riscul hemoragic HAS-BLED ≥3.','35,9% aparține TIMI STEMI.']],
 8,'Confundă 1,3% (1 punct) cu 0% sau 2,2%, treptele adiacente ale aceluiași cadran.',['1,3% risc','1 puncte']),

q(222,['Itemii scorului HAS-BLED includ:',
 ['Hipertensiune cu sistolică ≥160 mmHg','Funcție renală sau hepatică anormală; AVC în antecedente; hemoragie; INR labil','Vârstnic ≥65 de ani; medicație concomitentă; consum de alcool','Diabetul zaharat și sexul feminin, identic CHA2DS2-VASc','Un scor 0 corespunde unui risc hemoragic anual >5%'],'ABC',1062,'Fibrilația atrială — Itemii HAS-BLED',
 'Listarea componentelor HAS-BLED (inclusiv TAS ≥160 mmHg), distincte de diabet/sexul din CHA2DS2-VASc.',
 ['TAS ≥160 mmHg este primul item.','Renal/hepatic, AVC, hemoragie și INR labil sunt listate.','Vârsta ≥65, medicația și alcoolul completează scorul.','Diabetul și sexul feminin țin de CHA2DS2-VASc.','Scorul 0 are risc circa 1%; >5% este la scor ≥3.']],
 8,'Introduce diabetul/sexul din CHA2DS2-VASc în HAS-BLED și inversează riscul scorului 0 cu al scorului ≥3.',['160 mmHg','INR labil']),

q(223,['Comparativ cu warfarina, DOAC-urile:',
 ['Blochează specific o singură treaptă a cascadei, pe când warfarina acționează pe factorii vitamina K-dependenți II, VII, IX și X','Au acțiune mai rapidă, timp de înjumătățire mai scurt, mai puține interacțiuni și nu cer monitorizarea INR','Datele de studii le arată la fel de eficiente și probabil mai sigure decât warfarina','Inhibă simultan toți factorii II, VII, IX și X, identic AVK','Antiagregantele rămân alternativa recomandată când DOAC-ul este disponibil'],'ABC',1062,'Fibrilația atrială — Factorii II, VII, IX, X versus DOAC',
 'Contrastul inhibiției pe o treaptă (DOAC) versus factorii vitamina K II/VII/IX/X (warfarină).',
 ['Mecanismul pe o treaptă versus cei patru factori este explicit.','Farmacocinetica și absența INR sunt din text.','Eficacitatea similară și siguranța probabil superioară sunt citate.','Warfarina, nu DOAC-ul, acționează pe II, VII, IX și X.','Antiagregantele nu sunt recomandate pentru prevenția AVC.']],
 8,'Atribuie DOAC-ului spectrul de factori vitamina K al warfarinei, inversând mecanismele.',['factorul 11, VI I, IX','monitorizarea INR']),

q(224,['Extrasistolele atriale:',
 ['Sunt cel mai frecvent asimptomatice; uneori sunt resimțite ca bătăi neregulate sau puternice','Pe ECG: unde P precoce sau cu morfologie anormală, de cele mai multe ori urmate de QRS normale','Tratamentul nu este de obicei necesar; dacă precipită aritmii semnificative, beta-blocantele pot fi eficiente','Impun ablație de nod AV de primă intenție','Sunt urmate constant de o pauză compensatorie identică extrasistolelor ventriculare, fără QRS normal'],'AB',1063,'Tahiaritmii atriale — Extrasistolele atriale',
 'Recunoașterea benignității uzuale și a opțiunii de beta-blocant doar când precipită aritmii semnificative.',
 ['Simptomatologia discretă este descrisă.','Morfologia P precoce/anormală și QRS de obicei normale sunt explicite.','Tratamentul nu este de obicei necesar; BB dacă duc la aritmii semnificative.','Ablația de nod nu este prima linie.','Pauza compensatorie completă este descrisă la extrasistolele ventriculare, nu ca regulă aici.']],
 8,'Promovează ablația de nod — terapie de rezervă a FA — ca tratament al extrasistolei atriale benigne.',['Extrasistolele atriale','beta-blocantele']),

q(225,['Tahicardia ventriculară susținută se caracterizează clinic și electrocardiografic prin:',
 ['Durată >30 de secunde; frecvență 120-220 b.p.m.; unde „a” intermitente la jugulare și variabilitate a intensității zgomotului 1','Pe ECG: QRS largi (frecvent ≥0,14 sec), unde P aleatorii, capturi ventriculare și bătăi de fuziune','Dacă există incertitudine, tahicardia cu QRS larg se consideră ventriculară','Instabilitatea (hipotensiune, edem pulmonar) impune cardioversie electrică de urgență','La pacientul stabil, primul gest este ablația de istm cavo-tricuspidian, fără antiaritmice i.v.'],'ABCD',1063,'TV susținută — Capturi, fuziune și 120-220/min',
 'Reunirea semnelor de disociație AV (unde a, S1 variabil, capturi/fuziune) cu regula „la incertitudine = TV”.',
 ['Definiția >30 s, fereastra 120-220 și semnele de disociație sunt explicite.','Capturile (QRS înguste intermitente) și fuziunile sunt descrise.','Textul: în caz de incertitudine se consideră ventriculară.','Instabilul cere cardioversie de urgență.','La stabil se pot folosi esmolol, clasa I sau amiodaronă; ablația de istm ține de flutter.']],
 8,'Înlocuiește cardioversia instabilului și antiaritmicele stabilului cu ablația de flutter, o procedură de pe pagina anterioară.',['capturi ventriculare','120-220 b.p.m.']),

q(226,['Cauze dobândite de sindrom QT lung (Cadranul 30.18) includ:',
 ['Hipopotasemia, hipomagnezemia și hipocalcemia','Quinidină/disopiramidă, sotalol/amiodaronă, triciclice, fenotiazine, haloperidol, macrolide, quinolone, metadonă','Organofosforice; bradicardie; prolaps de valvă mitrală; infarct acut; diabet; post prelungit; distrofie miotonică','Hiperkaliemia ca etiologie dominantă, fără hipomagnezemie','Beta-blocantele, care prelungesc QT identic sotalolului, fiind interzise în LQTS congenital'],'ABC',1064,'QT lung dobândit — Cadranul 30.18',
 'Listarea electrolitilor, a claselor medicamentoase și a cauzelor „diverse” (MVP, post, distrofie miotonică).',
 ['Cei trei ioni scăzuți sunt în tabel.','Lista de medicamente este din cadran.','Organofosforicele și cauzele diverse sunt enumerate.','Hiperkaliemia nu figurează; deficitul de K/Mg/Ca da.','Beta-blocantele sunt tratamentul de durată al formei congenitale, nu o cauză de QT lung.']],
 8,'Pune hiperkaliemia — inversul hipoK din tabel — și interzice beta-blocantul, terapia LQTS congenital.',['Hipomagnezemia','Metadonă']),

q(227,['Extrasistolele ventriculare frecvente și pulsus bigeminus:',
 ['După ESV urmează de obicei o pauză compensatorie completă, nodul AV sau ventriculul fiind refractar la impulsul sinusal următor','O frecvență crescută a bătăilor premature predispone la disfuncție de ventricul stâng','Dacă originea este un singur focar, ablația poate fi foarte eficientă, mai ales din ventriculul drept','Pulsus bigeminus apare când după fiecare bătaie sinusală urmează regulat o extrasistolă','ESV se tratează de rutină cu antiaritmice de clasă Ic după un infarct, pentru a reduce mortalitatea'],'ABCD',1066,'ESV — Bigeminism, disfuncție de VS și ablație',
 'Legarea încărcăturii de ESV de disfuncția de VS și a focarului drept de ablația eficientă, plus bigeminismul.',
 ['Pauza compensatorie completă este explicită.','Frecvența crescută predispone la disfuncție de VS.','Ablația focarului unic, mai ales drept, este foarte eficientă.','Definiția pulsus bigeminus este din text.','CAST a arătat creșterea mortalității cu clasa Ic post-IMA; ESV se tratează dacă sunt simptomatice, de obicei cu beta-blocante.']],
 8,'Reactivează clasa Ic post-infarct — tocmai situația interzisă de CAST — ca tratament de rutină al ESV.',['pulsus bigeminus','ventriculul drept']),

q(228,['Antiaritmicele de clasă II (beta-blocante):',
 ['Acționează prin prevenirea efectelor catecolaminelor asupra potențialului de acțiune','Cele cardioselective (β1) includ metoprolol, bisoprolol, atenolol și acebutolol','Încetinesc conducerea în nodul AV; sunt antiischemice și antiadrenergice, cu beneficiu post-IMA (prevenția FV) și în IC congestivă','Scurtează potențialul de acțiune identic clasei Ib, fără efect pe nodul AV','Sunt contraindicate ca monoterapie la tahiaritmiile simptomatice cu boală coronariană'],'ABC',1067,'Antiaritmice — Clasa II (β1 cardioselective)',
 'Potrivirea listei β1 (metoprolol, bisoprolol, atenolol, acebutolol) cu prevenția FV post-infarct.',
 ['Mecanismul simpaticolitic este explicit.','Cele patru cardioselective sunt enumerate.','Încetinirea nodului AV, efectul antiischemic și prevenția FV post-IMA sunt descrise.','Scurtarea PA aparține clasei Ib; clasa II acționează predominant pe nodul sinusal.','Sunt recomandate ca monoterapie sau combinație tocmai la tahiaritmiile simptomatice, mai ales ischemice.']],
 8,'Atribuie clasei II scurtarea PA a lidocainei și interzice beta-blocantul la ischemic — indicația citată.',['acebutolol','fibrilaţiei ventriculare']),

q(229,['Izolarea venelor pulmonare pentru FA paroxistică:',
 ['Procedura durează de obicei mai mult de 4 ore','În centrele experimentate, complicațiile importante totale sunt sub 2% (AVC, pericardită hemoragică, stenoză de vene pulmonare, fistule atrio-esofagiene)','Succesul pe termen lung 70-80% vizează tinerii cu FA paroxistică, AS normal și fără boală structurală','Fistula atrio-esofagiană este regula, apărând la peste jumătate dintre proceduri','Complicațiile dispar dacă se folosește doar crioenergia, fără radiofrecvență'],'ABC',1068,'Ablație FA — Durata >4 ore și fistula atrio-esofagiană',
 'Memorarea duratei >4 ore, a plafonului <2% de complicații majore și a listei (inclusiv fistula atrio-esofagiană).',
 ['Durata peste 4 ore este explicită.','Plafonul <2% și lista de complicații (inclusiv fistula) sunt din text.','Populația 70-80% este cea descrisă.','Fistula este o complicație rară în centre experimentate, nu regula.','Atât radiofrecvența, cât și crioenergia sunt menționate; complicațiile nu dispar prin schimbarea energiei.']],
 8,'Transformă fistula atrio-esofagiană — complicație rară <2% — într-o regulă de peste 50%.',['mai mult de 4 ore','fistule atrio-esofagiene']),

q(230,['Homeostazia calciului în insuficiența cardiacă:',
 ['Excitarea membranei lasă calciul extracelular să intre rapid prin canale; acesta declanșează eliberarea din reticulul sarcoplasmic','Relaxarea urmează recaptării în reticul, proces controlat de modificările oxidului nitric','În IC, curentul de calciu este prelungit și se asociază cu prelungirea contracției și a relaxării','Calciul nu participă la cuplajul excitație-contracție','În IC, curentul de calciu este scurtat, accelerând relaxarea'],'ABC',1071,'Insuficiența cardiacă — Curentul de calciu prelungit',
 'Legarea curentului de Ca2+ prelungit de contracția și relaxarea prelungite, cu rolul NO în recaptare.',
 ['Intrarea și trigger-ul de SR sunt descrise.','Recaptarea controlată de NO este explicită.','Prelungirea curentului, a contracției și a relaxării este din text.','Calciul are rol esențial în reglarea funcției contractile.','Curentul este prelungit, nu scurtat.']],
 8,'Scurtează curentul de calciu — inversul fiziopatologiei citate — și anulează cuplajul excitație-contracție.',['reticulul sarcoplasmic','oxidului nitric']),

q(231,['Diagnosticul HFpEF, conform Cadranului 30.24, necesită:',
 ['Simptome caracteristice de insuficiență cardiacă','Semne caracteristice de insuficiență cardiacă','Fracție de ejecție normală sau ușor redusă și ventricul stâng nedilatat, plus modificări structurale relevante (HVS/dilatare de AS) și/sau disfuncție diastolică','Doar FE scăzută, identic celor trei condiții ale HFrEF','Absența oricărei anomalii diastolice, diagnosticul fiind pur simptomatic'],'ABC',1072,'Insuficiența cardiacă — Cele patru condiții HFpEF',
 'Contrastul a patru condiții HFpEF (inclusiv VS nedilatat și HVS/AS) versus triada HFrEF.',
 ['Simptomele sunt prima condiție.','Semnele sunt a doua.','FE păstrată, VS nedilatat și HVS/AS sau disfuncție diastolică completează setul de patru.','HFrEF cere trei condiții, inclusiv FE scăzută; HFpEF cere patru.','Disfuncția diastolică sau remodelarea (HVS/AS) este cerută, nu absentă.']],
 8,'Reduce HFpEF la triada HFrEF (FE scăzută), deși cadranul cere patru condiții cu FE păstrată.',['HFPEF','atriu stâng']),

q(232,['Disfuncția sistolică a ventriculului drept poate fi:',
 ['Secundară bolilor cronice ale cordului stâng','Cauzată de hipertensiune pulmonară primară sau secundară, infarct de VD, cardiomiopatie aritmogenă de VD sau boli congenitale ale adultului','Identică HFpEF, cu FE de VS >50% ca singur criteriu','O contraindicație de a evalua hipertensiunea pulmonară','Produsă doar de stenoza aortică calcificată, fără cauze de VD'],'AB',1072,'Insuficiența cardiacă — Disfuncția de ventricul drept',
 'Recunoașterea DSVD ca urmare a cordului stâng cronic sau a HTP/infarctului de VD/CMA/congenitalelor.',
 ['Secundaritatea față de cordul stâng este explicită.','Lista HTP, infarct VD, CMA și congenitale este din text.','HFpEF este un fenotip de VS, nu definiția DSVD.','HTP este tocmai o cauză de căutat.','Stenoza aortică ține de VS, nu epuizează DSVD.']],
 8,'Suprapune DSVD peste HFpEF și anulează hipertensiunea pulmonară, o cauză citată.',['ventriculului drept','hipertensiunea pulmonară']),

q(233,['Contraindicațiile IECA în insuficiența cardiacă includ:',
 ['Stenoza de arteră renală','Sarcina','Antecedente de angioedem','Tusea izolată, care impune oprirea fără a trece pe un ARA','Inițierea în doză maximă, fără monitorizarea creatininei'],'ABC',1073,'Insuficiența cardiacă — Contraindicațiile IECA',
 'Listarea stenozei de arteră renală, sarcinii și angioedemului, plus inițierea în doză mică.',
 ['Stenoza de arteră renală este contraindicație.','Sarcina este contraindicație.','Antecedentele de angioedem sunt contraindicație.','Tusea orientează către ARA, nu interzice orice blocadă a SRAA.','Se inițiază în doză mică, cu creștere treptată și monitorizare.']],
 8,'Transformă tusea — motiv de trecere pe ARA — într-o interdicție absolută a întregii clase SRAA.',['stenoza de arteră renală','angio-edem']),

q(234,['Durata medie de internare a unei decompensări de insuficiență cardiacă este de:',
 ['5-10 zile','24 de ore, fără monitorizare ulterioară','6 luni, identic interdicției de efort din miocardită','3 săptămâni de terapie intensivă ca durată medie citată','Sub 12 ore, diureticul oral fiind suficient'],'A',1073,'Insuficiența cardiacă — Durata internării',
 'Reținerea ferestrei 5-10 zile ca durată medie de internare.',
 ['Textul: durata medie de internare este între 5 și 10 zile.','24 de ore subestimează; spitalizările repetate sunt frecvente.','6 luni este interdicția de sport din miocardită, nu internarea IC.','3 săptămâni de TI nu este cifra citată.','Decompensarea cere adesea internare, nu doar 12 ore de diuretic oral.']],
 8,'Comprimă internarea de 5-10 zile la 24 de ore sau o dilată la 6 luni, ferestre din alte secțiuni.',['5 şi 10 zile','internare']),

q(235,['Din Cadranul 30.25, treptele de dozaj relevante includ:',
 ['Candesartan 4 mg/zi inițial, maxim 32 mg/zi','Carvedilol 3,125 mg ×2/zi → 50 mg ×2/zi','Sacubitril/valsartan 24/26–49/51 mg ×2/zi, maxim 97/103 mg ×2/zi','Digoxinul se crește peste 2,5 mg/zi de rutină la eRFG <30 ml/min/1,73 m²','Metoprololul succinat are doză maximă de 25 mg/zi, identic spironolactonei'],'ABC',1074,'Insuficiența cardiacă — Candesartan 32 mg, carvedilol, ARNI',
 'Memorarea treptelor 4→32 mg (candesartan), 3,125→50×2 (carvedilol) și 97/103 mg (ARNI).',
 ['Treptele candesartanului sunt din tabel.','Carvedilolul 3,125×2 → 50×2 este explicit.','Fereastra ARNI până la 97/103 mg ×2/zi este listată.','Peste 2,5 mg/zi de digoxin sunt rar necesare; eficiența scade la eRFG <30.','Metoprolol succinat CR/XL: 12,5-25 → 200 mg/zi, nu plafon 25 mg.']],
 8,'Plafonează metoprololul la 25 mg — doza inițială — și crește digoxinul tocmai la eRFG <30.',['32 mg zilnic','97/103']),

q(236,['Studiile CIBIS, CIBIS II, MERIT-HF și COMET, în insuficiența cardiacă:',
 ['Au evaluat efectele beta-blocantelor la grade diferite de severitate','Susțin că bisoprololul și carvedilolul reduc mortalitatea în toate gradele de severitate','Cer inițierea în doză mică, cu creștere treptată, monitorizând frecvența și tensiunea, în IC semnificativă','Demonstrează că nebivololul înlocuiește bisoprololul la tinerii cu NYHA IV','Permit inițierea beta-blocantului în IC acută instabilă, înaintea stabilizării'],'ABC',1074,'Insuficiența cardiacă — CIBIS, MERIT-HF, COMET',
 'Potrivirea trialurilor de beta-blocant cu regula dozei mici în IC semnificativă, nu cu nebivololul tânărului instabil.',
 ['Cele patru studii sunt citate pentru grade diferite de severitate.','Bisoprololul și carvedilolul reduc mortalitatea în toate gradele.','Inițierea în doză mică cu titrare este explicită.','Nebivololul este pentru IC stabilă ușoară/moderată la >70 de ani.','Beta-blocantele se evită în IC acută până la stabilizare.']],
 8,'Mută nebivololul (>70 ani, IC stabilă) pe tânărul cu NYHA IV instabil, inversul nișei din același paragraf.',['CIBIS','MERIT-HF']),

q(237,['Insuficiența cardiacă se asociază cu o creștere a riscului de accident vascular cerebral de circa:',
 ['Patru ori','0,1 ori, riscul fiind neglijabil','Identică riscului din CHA2DS2-VASc 0 puncte (0%)','20 de ori, identic complicațiilor IABP','O reducere de 23%, ca ICD în SCD-HeFT'],'A',1075,'Insuficiența cardiacă — Riscul de AVC ×4',
 'Reținerea multiplicatorului de patru ori al riscului de AVC în IC.',
 ['Textul: IC se asociază cu creșterea de patru ori a riscului de AVC.','0,1 ori contrazice cifra.','CHA2DS2-VASc 0 are risc 0%, nu este multiplicatorul IC.','20% sunt complicațiile IABP, nu multiplicatorul de AVC.','23% este reducerea de mortalitate cu ICD în SCD-HeFT.']],
 8,'Înlocuiește multiplicatorul ×4 cu 0% din CHA2DS2-VASc 0 sau cu 23% din SCD-HeFT.',['patru ori','accident vascular cerebral']),

q(238,['Epidemiologia bolii coronariene în Marea Britanie (2010) include:',
 ['Peste 180.000 de decese prin boli cardiovasculare, cauza cea mai frecventă de mortalitate','BC a produs 1 din 5 decese la bărbați și 1 din 10 la femei (circa 80.000 de decese)','1 din 6 infarcte acute prezintă moartea subită ca prim, ultim și unic simptom','Mortalitatea cardiovasculară a fost sub 1.000 de decese, limitată la STEMI neperfuzat','Moartea subită este exclusă ca primă manifestare a infarctului'],'ABC',1079,'Boala coronariană — 180.000 de decese și 1 din 6',
 'Aplicarea ordinului 180.000/80.000 și a ponderii 1 din 6 infarcte prezentate ca moarte subită.',
 ['Peste 180.000 de decese CV sunt explicite.','1 din 5 bărbați și 1 din 10 femei (≈80.000) sunt din text.','1 din 6 IMA cu moarte subită ca unic simptom este citat.','Ordinul este de sute de mii, nu mii.','Moartea subită poate fi primul, ultimul și unicul simptom.']],
 8,'Subestimează cu două ordine mortalitatea britanică și neagă moartea subită ca primă manifestare.',['180.000 de decese','1 din 6 infarcte']),

q(239,['Fluxul coronarian poate fi redus, iar necesarul de oxigen crescut, prin:',
 ['Obstrucție mecanică: ateroscleroză, tromboză supraadăugată, spasm, embolie, stenoze ostiale, vasculite (ex. LES)','Scăderea sângelui oxigenat: anemie, carboxihemoglobină, hipotensiune (presiune de perfuzie scăzută)','Creșterea necesarului: debit crescut (tireotoxicoză) sau hipertrofie (stenoză aortică, HTA sistemică)','Doar spasmul, fără rolul plăcii aterosclerotice','Anemia, care scade necesarul de oxigen și previne ischemia'],'ABC',1079,'Boala coronariană — Aport versus necesar',
 'Potrivirea celor trei axe (obstrucție, conținut de O2, hipertrofie/debit) care produc ischemia.',
 ['Lista de obstrucții mecanice include LES.','Anemia, carboxihemoglobina și hipotensiunea scad aportul oxigenat.','Tireotoxicoza și stenoza aortică/HTA cresc necesarul.','Ateroscleroza stenozantă este cauza cea mai frecventă, nu spasmul izolat.','Anemia scade aportul, nu necesarul, și favorizează ischemia.']],
 8,'Anulează placa — cauza dominantă — și prezintă anemia ca protecție față de ischemie.',['carboxihemoglobinemia','tireotoxicoză']),

q(240,['Progresia leziunii aterosclerotice coronariene include:',
 ['Stria lipidică (fatty streak) din celule spumoase încărcate cu LDL','Placa de tranziție, cu lipide extracelulare subendotelial','Placa fibroasă avansată, apoi placa complicată (ulcerare, tromboză, ocluzie acută)','PDGF și TGF-β, care stimulează acumularea de macrofage și migrarea celulelor musculare netede din medie','Stria lipidică ca leziune finală, fără progresie spre placă fibroasă'],'ABCD',1079,'Ateroscleroză — Strie lipidică, PDGF, placă complicată',
 'Secvența strie → placă de tranziție → fibroasă avansată/complicată, cu rolul PDGF/TGF-β.',
 ['Stria din celule spumoase este explicită.','Placa de tranziție este denumită astfel.','Placa complicată închide secvența.','PDGF și TGF-β sunt citate.','Stria poate progresa, nu este stadiul final.']],
 8,'Oprește aterogeneza la stria lipidică, deși textul o duce până la placa complicată ocluzivă.',['strii lipidice','celulelor spumoase']),

q(241,['O reducere cu 50% a diametrului luminal coronarian corespunde unei reduceri de suprafață de circa:',
 ['70%, cu arteriole distale dilatate maximal și rezervă de flux zero','10%, fără ischemie la efort','50%, identic reducerii de diametru, rezerva rămânând intactă','90%, doar în vasculitele din LES','0%, stenoza fiind nesemnificativă până la 90% diametru'],'A',1080,'Boala coronariană — Stenoză 50% diametru / 70% arie',
 'Reținerea echivalenței 50% diametru ↔ 70% arie, cu rezerva coronariană epuizată.',
 ['Textul: 50% diametru corespunde cca 70% din suprafață; rezerva este zero.','10% subestimează.','Reducerea de arie este mai mare decât cea de diametru; rezerva este epuizată.','90% nu este cifra de arie citată.','Stenoza de 50% diametru este deja hemodinamic semnificativă.']],
 8,'Echivalează greșit 50% diametru cu 50% arie și păstrează rezerva, deși textul o pune la zero.',['50%','70%']),

q(242,['Riscul transversal al aterosclerozei și recunoașterea infarctului:',
 ['Claudicația intermitentă asociază un risc de 2-4 ori mai mare de BC, AVC sau IC','După primul infarct, riscul de IC sau AVC crește de 3-6 ori; după AVC, riscul de IC și infarct se dublează','Unul din trei infarcte rămâne inițial nerecunoscut; 30-40% dintre SCA nu au simptome prealabile de alarmă','Boala periferică protejează de BC, riscul fiind inversat','Toate infarctele sunt recunoscute la debut, SCA având constant angină prealabilă'],'ABC',1080,'Boala coronariană — Riscul 2-4× și infarctul tăcut',
 'Aplicarea multiplicatorilor 2-4× / 3-6× / 2× și a ponderilor 1/3 infarct tăcut și 30-40% SCA fără prodrom.',
 ['2-4 ori este cifra claudicației.','3-6 ori post-IMA și dublarea post-AVC sunt explicite.','1 din 3 IMA nerecunoscut și 30-40% fără alarmă sunt din text.','BVP crește, nu scade, riscul de BC.','Textul subliniază tocmai infarctul tăcut și SCA-ul fără prodrom.']],
 8,'Inversează protecția falsă a BVP și neagă infarctul tăcut, deși un IMA din trei trece nerecunoscut.',['două până la de patru','30 şi 40%']),

q(243,['Prevenția primară NICE și suspiciunea de hipercolesterolemie familială:',
 ['Scala QRISK3 identifică riscul înalt: ≥10% la 10 ani','Un tablou lipidic complet include colesterol total, HDL, non-HDL și trigliceride','Colesterol >7,5 mmol/L plus istoric familial de BC precoce poate indica hipercolesterolemie familială','QRISK3 se folosește doar în prevenția secundară, după un STEMI','Colesterolul >7,5 mmol/L infirmă orice formă familială'],'ABC',1080,'Boala coronariană — QRISK3 ≥10% și 7,5 mmol/L',
 'Aplicarea pragului QRISK3 ≥10%/10 ani și a ferestrei >7,5 mmol/L pentru forma familială.',
 ['Definiția riscului înalt ≥10% la 10 ani este explicită.','Componentele lipidogramei sunt listate.','>7,5 mmol/L cu istoric familial orientează spre forma familială.','QRISK3 este pentru prevenția primară.','>7,5 mmol/L plus istoric familial ridică, nu infirmă, suspiciunea.']],
 8,'Mută QRISK3 în prevenția secundară post-STEMI și tratează 7,5 mmol/L ca argument împotriva formei familiale.',['7,5 mmol/L','QRISK']),

q(244,['Tromboza pe placa aterosclerotică se produce prin:',
 ['Eroziune endotelială superficială: matricea subendotelială expusă, adeziune plachetară la colagen, tromb aderent la suprafața plăcii','Ulcerarea/fisura capișonului peste miezul lipidic: sânge în placă, factor tisular din macrofage, extindere în lumen','Doar stenoza progresivă lentă, fără tromb','Eroziunea ca mecanism care ocolește plachetele, fără contact cu colagenul','Miezul lipidic ca element antitrombotic, care previne ocluzia'],'AB',1080,'SCA — Eroziune superficială versus ruptură profundă',
 'Contrastul celor două mecanisme din Fig. 30.61: eroziune de suprafață versus ruptură de miez lipidic.',
 ['Primul mecanism (eroziune, tromb aderent) este descris.','Al doilea (ruptură, factor tisular, extindere luminală) este descris.','Tromb local, nu doar stenoza lentă.','Eroziunea expune colagenul și inițiază adeziunea plachetară.','Miezul lipidic are potențial trombogenic major.']],
 8,'Anulează trombul — elementul comun al celor două mecanisme — și face din miezul lipidic un factor protector.',['eroziunea endotelială','Miezul lipidic']),

q(245,['Durerea anginoasă este indusă de metaboliți ischemici, inclusiv adenozina, care:',
 ['Stimulează terminațiile nervoase libere miocardice','Nu au rol în geneza durerii, angina fiind pur psihogenă','Blochează nociceptorii, explicând infarctul tăcut ca regulă','Acționează doar în pericard, nu în miocard','Înlocuiesc nitroglicerina ca tratament de primă linie'],'A',1081,'Angina — Adenozina și terminațiile nervoase',
 'Reținerea adenozinei ca metabolit care stimulează terminațiile nervoase libere și produce durerea.',
 ['Textul leagă adenozina de stimularea terminațiilor nervoase libere.','Durerea este ischemică, nu pur psihogenă.','Infarctul tăcut există, dar nu pentru că adenozina ar bloca nociceptorii.','Terminațiile sunt miocardice.','Adenozina este mediator al durerii, nu tratament antianginos.']],
 8,'Transformă adenozina — mediator al durerii — în analgezic sau antianginos, inversul fiziologiei.',['adenozina','terminaţiile nervoase libere']),

q(246,['Clasa CCS III și angina refractară se definesc astfel:',
 ['CCS III: angină la activități de intensitate redusă, de exemplu mers 50-100 m pe plat sau urcarea unui etaj, cu limitare marcată','Refractară: BC severă la care revascularizarea nu este realizabilă și simptomele nu sunt controlabile medicamentos','CCS III: angină doar la efort intens, identic clasei I','Refractară înseamnă angină de efort controlată de un singur beta-blocant','CCS IV exclude angina de repaus'],'AB',1081,'Angina — CCS III (50-100 m) și forma refractară',
 'Fixarea pragului 50-100 m / un etaj pentru CCS III și a definiției refractare (nerevascularizabilă, necontrolabilă).',
 ['Cadranul 30.31: 50-100 m sau un etaj, limitare marcată.','Definiția refractare este explicită.','Efortul intens fără limitare zilnică este CCS I.','Refractara presupune eșec medicamentos și imposibilitatea revascularizării.','CCS IV include angina în repaus sau la orice nivel de activitate.']],
 8,'Degradează CCS III la efortul intens al clasei I și golește refractara de conținutul ei (nerevascularizabilă).',['50-100 m','Angina refractară']),

q(247,['Factori de risc potențial modificabili ai bolii coronariene (Cadranul 30.30) includ:',
 ['Creșterea fibrinogenului și a factorului VII plasmatic; creșterea PCR; hiperhomocisteinemia','Guta; duritatea redusă a apei; contraceptivele orale, analogii de nucleozide, inhibitorii COX-2, rosiglitazona','Deleția DD a genei ECA, ca factor nemodificabil alături de vârstă, sex masculin și AHC','Guta și apa dură ca factori protectori, care infirmă riscul','Contraceptivele orale ca factor nemodificabil, identic vârstei'],'ABC',1081,'Boala coronariană — Cadranul 30.30 (fibrinogen, gută, apă)',
 'Recunoașterea itemilor mai puțin citați (fibrinogen/VII, PCR, homocisteină, gută, apă moale, COX-2).',
 ['Coagularea, PCR și homocisteina sunt în coloana modificabilă.','Guta, apa moale și medicamentele listate sunt din cadran.','DD a ECA este în coloana nemodificabilă.','Guta și apa moale sunt factori de risc, nu protecție.','Contraceptivele sunt potențial modificabile, vârsta nu.']],
 8,'Transformă guta și apa moale în factori protectori și mută contraceptivele lângă vârstă, în coloana nemodificabilă.',['fibrinogenului','Duritatea redusă a apei']),

q(248,['Rezerva fracționată de flux și complicațiile PCI:',
 ['Leziunile cu FFR >0,80 pot fi tratate medicamentos, fără stent, cu prognostic bun','Complicații majore: infarct acut 2%, accident vascular cerebral 0,4%, deces 1%','Stenturile metalice simple au risc de restenoză de 20-30% în primele 6-9 luni','FFR >0,80 impune stentare imediată, tratamentul medicamentos fiind insuficient','Restenoza BMS este rară sub 1% în primul an, identică mortalității chirurgicale CABG'],'ABC',1082,'PCI — FFR >0,80, restenoză BMS 20-30%',
 'Aplicarea pragului FFR 0,80 și a triadului 2%/0,4%/1%, plus restenoza BMS 20-30% la 6-9 luni.',
 ['FFR >0,80 permite tratament medicamentos cu prognostic bun.','Cele trei procente majore sunt explicite.','20-30% la 6-9 luni este restenoza BMS.','Peste 0,80 se poate evita stentul.','<1% este mortalitatea CABG la FE conservată, nu restenoza BMS.']],
 8,'Inversează pragul FFR (stentează tocmai leziunile >0,80) și comprimă restenoza BMS de la 20-30% la 1%.',['0,80','20-30%']),

q(249,['Stenturile farmacologic active și abordul arterial în PCI:',
 ['Abordul radial este preferat în prezent și reduce complicațiile de la locul puncției','Prima generație DES (sirolimus, paclitaxel) a redus restenoza, dar producea tromboză tardivă de stent','A doua generație are rețea mai subțire și polimeri biodegradabili sau biocompatibili','Abordul femural este standardul actual în Marea Britanie, radialul fiind abandonat','Prima generație DES a eliminat tromboza de stent, restenoza rămânând 20-30%'],'ABC',1082,'PCI — Radial, DES de generația I/II',
 'Contrastul trombozei tardive a primei generații DES cu polimerii biocompatibili ai celei de-a doua, plus preferința radială.',
 ['Radialul este tehnica standard în UK, cu mai puține complicații locale.','Sirolimus/paclitaxel: mai puțină restenoză, tromboză tardivă.','Generația a doua: struturi subțiri, polimeri biodegradabili/biocompatibili.','Radialul, nu femuralul, este standardul citat.','Prima generație a redus restenoza dar a adus tromboză tardivă; 20-30% este restenoza BMS.']],
 8,'Pune femuralul ca standard UK — inversul textului — și atribuie primei generații DES restenoza BMS.',['sirolimus','paclitaxel']),

q(250,['Dozele din Cadranul 30.33 și dubla antiagregare după stentare:',
 ['Nitroglicerina 0,3-1,0 mg sublingual, repetată după 5 minute dacă angina persistă','Ivabradina 2,5-7,5 mg ×2/zi; nicorandil 5-30 mg ×2/zi','DAPT (aspirină plus inhibitor P2Y12) 6-12 luni după stentare; BMS pot fi preferate dacă e nevoie de anticoagulare prelungită sau de chirurgie precoce','Nitroglicerina 80 mg, identic atorvastatinei de prevenție secundară','DAPT se limitează la 24 de ore, BMS fiind interzise înaintea oricărei anticoagulări'],'ABC',1083,'Angina — NTG 0,3-1,0 mg, DAPT 6-12 luni',
 'Fixarea dozei de NTG cu repetare la 5 minute, a ferestrelor ivabradină/nicorandil și a DAPT 6-12 luni.',
 ['0,3-1,0 mg și repetarea la 5 minute sunt din tabel.','Dozele de ivabradină și nicorandil sunt listate.','6-12 luni de DAPT și nișa BMS (anticoagulare prelungită/chirurgie precoce) sunt explicite.','80 mg este atorvastatina, nu NTG.','DAPT ține luni, nu 24 de ore; BMS au tocmai nișa anticoagulării prelungite.']],
 8,'Confundă 0,3-1,0 mg de NTG cu 80 mg de atorvastatină și comprimă DAPT de la 6-12 luni la 24 de ore.',['0,3-1,0 mg','6-12 luni']),

q(251,['Tahicardiile, comparativ cu bradicardiile, tind să fie mai simptomatice atunci când:',
 ['Sunt mai rapide și mai susținute, iar funcția miocardică este depreciată','Sunt lente și nesusținute, pe cord structural normal','Apar doar nocturn, sub 50 b.p.m., identic definiției bradicardiei','Sunt extrasistole atriale izolate, fără tahicardie susținută','Prognosticul vital rămâne neinfluențat chiar la funcție miocardică depreciată'],'A',1051,'Aritmii — Simptomatologia tahicardiilor',
 'Reținerea relației viteză/durată și a agravării simptomelor când funcția de pompă este depreciată.',
 ['Textul: cu cât sunt mai rapide și mai susținute, tahicardiile tind să fie mai simptomatice; la funcție depreciată influențează prognosticul.','Pe cord normal, unele aritmii pot fi paucisimptomatice.','<50 nocturn definește bradicardia, nu tahicardia simptomatică.','Extrasistola atrială izolată nu este tahicardie susținută.','Când funcția e depreciată, aritmiile influențează prognosticul vital.']],
 8,'Atribuie simptomatologia maximă bradicardiei nocturne, inversul paragrafului despre tahicardiile rapide susținute.',['mai rapide şi mai susţinute','funcţia miocardică']),

q(252,['Metoda „pill in pocket” pentru cardioversia FA presupune:',
 ['Administrarea orală a flecainidei sau propafenonei, testate în prealabil în spital și considerate sigure pentru acel pacient','Digoxin oral la domiciliu, fără testare spitalicească','Amiodaronă i.v. de rutină, fără evaluare prealabilă','Ablația de nod AV ca gest de buzunar','Oprirea anticoagulării în ziua dozei, riscul trombotic dispărând'],'A',1061,'Fibrilația atrială — Pill in pocket',
 'Reținerea flecainidei/propafenonei orale, testate spitalicește, ca metodă „pill in pocket”.',
 ['Textul descrie antiaritmic oral (flecainidă sau propafenonă) testat în spital.','Digoxinul nu este metoda de buzunar.','Amiodarona i.v. este o altă cale de cardioversie medicamentoasă, nu pill in pocket.','Ablația de nod nu este un gest de buzunar.','Anticoagularea peri-cardioversie rămâne o problemă separată.']],
 8,'Înlocuiește flecainida/propafenona testate în spital cu digoxinul de domiciliu, capcana clasică a metodei.',['flecainidă','propafenonă']),

q(253,['În tahicardia cu complexe largi, dacă persistă incertitudinea diagnostică între TV și TSV cu aberanță, se va considera:',
 ['Tahicardie ventriculară','TSV cu aberanță, până la dovada contrarie','Flutter antiorar cu conducere 1:1','AVNRT tipică slow-fast','Extrasistolie atrială bigeminată'],'A',1063,'TV versus TSV — Regula incertitudinii',
 'Aplicarea regulii că, la incertitudine, tahicardia cu QRS larg se tratează ca ventriculară (80% sunt TV).',
 ['Textul: în caz de incertitudine se va considera tahicardia ca fiind ventriculară.','Asumarea TSV este tocmai eroarea interzisă.','Flutterul 1:1 este o TSV particulară, nu presupunerea de primă linie.','AVNRT are de obicei QRS îngust.','Bigeminismul atrial nu explică o tahicardie regulată cu QRS larg.']],
 8,'Inversează regula de siguranță (incertitudine = TV) în favoarea TSV cu aberanță.',['incertitudine','ventriculară']),

q(254,['Endotelina în insuficiența cardiacă: secreția este stimulată de:',
 ['Hipoxie, catecolamine și angiotensină II','Doar de peptidul natriuretic C','Oxidul nitric în exces','Adenozina din terminațiile nervoase ale anginei','Ivabradină, care blochează If'],'A',1071,'Insuficiența cardiacă — Stimulii endotelinei',
 'Reținerea triadului hipoxie–catecolamine–angiotensină II ca stimuli ai secreției de ET.',
 ['Cei trei stimuli sunt enumerați explicit.','CNP are efecte similare ANP/BNP, nu stimulează ET.','Activitatea NO este insuficientă, nu în exces.','Adenozina ține de durerea anginoasă, nu de secreția de ET.','Ivabradina inhibă If sinoatrial, nu secreția de ET.']],
 8,'Înlocuiește triadul hipoxie/catecolamine/angiotensină II cu NO-ul — descris ca insuficient — sau cu ivabradina.',['angiotensina li','catecolaminele']),

q(255,['Recomandările dietetice pentru prevenția bolii coronariene includ și:',
 ['Grăsimi ≤30% din calorii, saturate ≤7%, colesterol <300 mg/zi; saturatele se înlocuiesc cu mono- și polinesaturate (rapiță, măsline)','Limitarea zaharurilor rafinate (ex. fructoză); patru-cinci porții de nuci, semințe și legume nesărate pe săptămână','Colesterol alimentar nelimitat, saturatele fiind preferate nesaturatelor','Efortul se evită după 45 de ani, pentru a proteja placa','IMC țintă ≥30 kg/m², ca rezervă energetică'],'AB',1081,'Boala coronariană — Grăsimi ≤30%/≤7% și 4-5 porții de nuci',
 'Completarea dietei cu plafoanele 30%/7%/<300 mg și cu 4-5 porții săptămânale de nuci/semințe.',
 ['Plafoanele de grăsimi și colesterol, plus rapița/măslinele, sunt explicite.','Fructoza se limitează; 4-5 porții de nuci/semințe/legume nesărate sunt listate.','Colesterolul trebuie <300 mg/zi; saturatele se înlocuiesc.','Efortul aerobic este recomandat.','IMC țintă este <25 kg/m².']],
 8,'Preferă saturatele și IMC ≥30, inversul dietei cu ≤7% saturate și IMC <25.',['300 mg/zi','rapiţă']),

q(256,['Durerea toracică non-anginoasă este probabilă dacă este:',
 ['Continuă, nelegată de efort, accentuată de mișcările respiratorii sau asociată cu amețeli, palpitații sau disfagie','Retrosternală de efort, cedează la nitrat, identic anginei clasice','Doar cele trei caracteristici NICE ale anginei clasice, simultan','Echivalentul CCS IV, cu indicație de PCI primară','Un criteriu suficient de STEMI, fără ECG'],'A',1082,'Angina — Durerea non-anginoasă probabilă',
 'Recunoașterea clusterului (continuă, nerespirator-independentă, disfagie/palpitații) ca durere non-anginoasă.',
 ['Textul listează tocmai aceste trăsături ca durere non-anginoasă probabilă.','Retrosternalul de efort care cedează la nitrat este angina clasică.','Cele trei caracteristici definesc forma clasică, nu non-anginoasa.','Non-anginoasa cu ECG normal se investighează pentru diagnostice alternative, nu PCI primară.','STEMI cere criterii ECG, nu acest tipar.']],
 8,'Trimite durerea continuă respirator-dependentă la PCI primară, sărind algoritmul NICE.',['disfagie','nelegată de efort']),

q(257,['Reintrarea (Fig. 30.38C) apare atunci când:',
 ['Există țesut miocardic normal dispus circular în jurul unui miez inexcitabil (ex. cicatrice)','O extrasistolă găsește o cale în perioadă refractară (bloc unidirecțional), cealaltă fiind excitabilă','Timpul de conducere pe circuit este mai lung decât perioadele refractare, întreținând tahicardia','Miezul trebuie să fie excitabil, iar extrasistola este superfluă','Majoritatea tahicardiilor paroxistice regulate au alt mecanism decât reintrarea'],'ABC',1052,'Aritmii — Reintrarea (miez inexcitabil)',
 'Recunoașterea triadei miez inexcitabil – bloc unidirecțional – timp de circuit > refractaritate.',
 ['Miezul inexcitabil (cicatrice) este explicit.','Extrasistola și blocul unidirecțional inițiază circuitul.','Conducerea mai lentă decât refractaritatea întreține tahicardia.','Miezul este inexcitabil, nu excitabil.','Majoritatea tahicardiilor paroxistice regulate au la bază reintrarea.']],
 8,'Cere un miez excitabil și neagă reintrarea ca mecanism dominant al tahicardiilor paroxistice regulate.',['miez','inexcitabil']),

q(258,['Dozele cronice de diuretice și vasodilatatoare din Cadranul 30.25 includ:',
 ['Furosemid 20-40 mg/zi inițial, până la 250-500 mg/zi','Bumetanid 0,5-1,0 mg/zi, maxim 5-10 mg/zi','Isosorbid dinitrat 20-40 mg ×3/zi și hidralazină 37,5-75 mg ×3/zi','Furosemid 50 mg i.v. ca doză cronică orală unică, fără treaptă de 20-40 mg','Bumetanidul este interzis în IC, fiind rezervat edemului pulmonar acut'],'ABC',1074,'Insuficiența cardiacă — Furosemid 250-500 mg, bumetanid, hidralazină',
 'Memorarea treptelor orale de furosemid (până la 250-500 mg) și bumetanid (5-10 mg), plus schema hidralazină-nitrat ×3/zi.',
 ['Treptele 20-40 → 250-500 mg furosemid sunt din tabel.','Bumetanidul 0,5-1,0 → 5-10 mg este explicit.','Isosorbidul 20-40 ×3 și hidralazina 37,5-75 ×3 sunt listate.','50 mg i.v. este doza inițială din ICA, nu treapta cronică orală.','Bumetanidul figurează în cadranul de IC cronică.']],
 8,'Confundă bolusul i.v. de 50 mg din ICA cu treapta cronică orală 20-40/250-500 mg.',['250-500 mg zilnic','37,5-75 mg']),
];
