import {advancedQuestion} from './advanced-author';
import type {SourceRow} from './source-author';
const pdfOffset=(p:number)=>p<=1048?p-837:p<=1107?p-839:p-851;
const q=(n:number,row:SourceRow,score:number,reason:string,expressions:string[],related:number[]=[])=>
 advancedQuestion('cardiologie',30,pdfOffset,`cardiologie-adv-${String(n).padStart(3,'0')}`,row,[score,reason],expressions,undefined,related);

export const CARDIOLOGIE_B=[
q(19,['În țările occidentale, boala arterială coronariană reprezintă aproximativ:',
 ['88% din cauzele de moarte subită','50% din cauzele de moarte subită','88% din decesele prin bradiaritmii severe','Cauza dominantă a stopului doar când infarctul acut este evident clinic','O minoritate a deceselor din primele 24 de ore de la simptomele cardiace'],'A',1045,'Proceduri terapeutice — Resuscitarea cardiacă',
 'Cunoașterea ponderii bolii coronariene în moartea subită și a mecanismului aritmic dominant.',
 ['Textul precizează că boala arterială coronariană reprezintă aproximativ 88% din cauzele de moarte subită în țările occidentale.','Valoarea 50% se referă la decesele care survin rapid, nu la ponderea bolii coronariene.','Bradiaritmiile severe produc o proporție mai mică de decese, nu 88%.','Doar o mică proporție din supraviețuitori prezintă semne evidente de infarct miocardic acut.','Până la 100.000 de decese în Marea Britanie se produc în primele 24 de ore; majoritatea au cauză coronariană, nu o minoritate.']],
 8,'Confundă ponderea 88% a bolii coronariene cu jumătatea de decese rapide și cu mecanismul bradiaritmic minor.',['88%','moarte subită']),

q(20,['Lanțul supraviețuirii și deschiderea căilor aeriene în suportul vital de bază:',
 ['Include recunoașterea timpurie a stopului, alertarea, RCP imediată, defibrilarea rapidă și îngrijirea post-resuscitare','Căile aeriene se deschid prin flexia gâtului și extensia capului, manevră nerecomandată dacă se suspectează leziune cervicală','Protezele dentare mobile trebuie îndepărtate, iar obstacolele orale (sânge, mucus) eliminate','Primul pas al BLS este palparea imediată a pulsului carotidian, înaintea oricărei alte măsuri','Manevra Heimlich este rezervată doar obstrucției de căi aeriene inferioare, nu celei faringiene'],'ABC',1045,'Proceduri terapeutice — Lanțul supraviețuirii și căile aeriene',
 'Recunoașterea celor cinci verigi ale lanțului supraviețuirii și a manevrei de deschidere a căilor aeriene, cu excepția leziunii cervicale.',
 ['Textul enumeră cele cinci componente ale lanțului supraviețuirii.','Flexia gâtului și extensia capului deschid căile aeriene, dar nu se recomandă la suspiciune de leziune a coloanei cervicale.','Obstacolele din cavitatea bucală sau faringe și protezele dentare mobile trebuie îndepărtate.','Primul pas este evitarea pericolelor suplimentare, apoi testarea la stimuli; detectarea pulsului poate fi dificilă.','Compresiunile abdominale și/sau toracice (Heimlich) se aplică obstrucției din cavitatea bucală posterioară sau căile aeriene superioare.']],
 8,'Inversează ordinea BLS (puls înaintea siguranței) și limitează greșit Heimlich la căile inferioare.',['Lanţul supravieţuirii','manevra Heimlich']),

q(21,['Selectați enunțurile adevărate despre suportul respirator și circulator în BLS:',
 ['Resucitarea cardiopulmonară mecanică este metoda de rutină în afara spitalului','Pentru persoanele neinițiate, compresiunile izolate (hands only BLS) mențin perfuzia cerebrală și coronariană până la sosirea personalului calificat','Oboseala din timpul compresiunilor scade eficiența acestora, iar calitatea resuscitării se reduce','Raportul 15:2 se aplică de rutină adultului, iar 30:2 doar copilului','RCP trebuie întreruptă la fiecare minut pentru verificarea pulsului, chiar fără semne de viață'],'BC',1046,'Suportul vital de bază — Compresiuni și respirație',
 'Diferențierea BLS „hands only” de RCP mecanică și recunoașterea efectului oboselii asupra calității compresiunilor.',
 ['Textul precizează că RCP mecanică este posibilă, dar nu este utilizată încă de rutină.','Hands only BLS este mai ușor pentru neinițiați și menține perfuzia cerebrală și coronariană.','Dovezile arată că oboseala scade eficiența compresiunilor și calitatea resuscitării.','Raportul este 30:2 la adulți și 15:2 la pacienții pediatrici, nu invers.','RCP nu trebuie întreruptă pentru reevaluare decât dacă apar semne de viață și respirație normală.']],
 8,'Transformă o tehnică încă nedevenită rutină în standard și inversează rapoartele adult/copil deja clasice.',['hands only BLS','Resucitarea cardiopulmonara mecanică']),

q(22,['În algoritmul suportului vital avansat la adult se recomandă:',
 ['Pentru ritm șocabil (FV/TV fără puls), un șoc bifazic nesincronizat de 150-200 J, urmat imediat de 2 minute de RCP','Pentru ritm neșocabil (asistolă/AEP), 1 mg adrenalină la intervale de minute de RCP','Amiodaronă după 3 șocuri, în timpul RCP','Șoc monofazic de 150 J ca standard actual, bifazicul fiind abandonat','După abordarea avansată a căilor aeriene, ventilație 20/minut cu întreruperea masajului la fiecare ciclu'],'ABC',1047,'Suportul vital cardiac avansat — Algoritmul ACLS',
 'Aplicarea energiilor de defibrilare, a adrenalinei în ritmurile neșocabile și a momentului amiodaronei.',
 ['Textul indică șoc bifazic nesincronizat de 150-200 J (360 J monofazic), urmat imediat de 2 minute de RCP.','În asistolă sau AEP se administrează 1 mg adrenalină la intervale de minute de RCP.','Algoritmul prevede amiodaronă după 3 șocuri.','Defibrilatoarele bifazice necesită energie mai puțină și sunt din ce în ce mai utilizate; 150-200 J este doza bifazică, nu monofazică.','După suport respirator avansat, RCP continuă cu ventilație 10/minut fără a întrerupe masajul.']],
 8,'Schimbă energia bifazică cu cea monofazică și dublează rata de ventilație post-intubație, două praguri adiacente din algoritm.',['150-200 J','Amiodaronă după 3 şocuri'],[1048]),

q(23,['Tratamentul cauzelor reversibile ale stopului („patru H și patru T”) include:',
 ['Hipoxia, combătută prin oxigen pe mască cu rezervor, intubație sau dispozitive supraglotice, cu verificarea ventilației ambelor arii pulmonare','Hipovolemia, cauză frecventă de AEP pe fond hemoragic, care impune repleție volemică','Hiperpotasemia, în care clorura de calciu intravenos poate fi utilă, la fel ca în hipocalcemie','Pneumotoracele în tensiune, diagnosticat clinic (deviere traheală, hipersonoritate, absența murmurului, ecografie) și tratat prin toracocenteză sau toracostomie','Hipotermia, exclusă cu un termometru obișnuit de cameră, fără încălzire internă'],'ABCD',1048,'Suportul vital avansat — Cauze reversibile (4H și 4T)',
 'Recunoașterea tratamentului specific al hipoxiei, hipovolemiei, tulburărilor de potasiu și pneumotoracelui în tensiune.',
 ['Hipoxia se limitează prin ventilație cu oxigen suplimentar pe mască cu rezervor, intubație sau dispozitive supraglotice.','Hipovolemia este o cauză frecventă de AEP pe fond de hemoragie și necesită repleție volemică.','Clorura de calciu i.v. poate fi utilă în hiperpotasemie sau hipocalcemie.','Diagnosticul clinic și toracocenteza cu ac sau toracostomia sunt descrise pentru pneumotoracele în tensiune.','Hipotermia se exclude cu un termometru pentru temperaturi scăzute și se tratează prin încălzire externă și internă.']],
 8,'Patru măsuri specifice sunt corecte, iar distractorul înlocuiește termometrul de hipotermie și încălzirea internă cu un instrument obișnuit.',['clorura de calciu','Hipovolemia'],[1047]),

q(24,['Hipotermia terapeutică post-resuscitare la adultul inconștient, după stop prin fibrilație ventriculară extraspatial, vizează:',
 ['28-30°C timp de 48-72 de ore','32-34°C timp de 12-24 de ore','36-37°C ca unică țintă, hipotermia fiind interzisă','40°C pentru prevenirea infecțiilor nosocomiale','Normotermie strictă doar în ritmurile șocabile, nu și în cele neșocabile'],'B',1048,'Post resuscitare — Hipotermia terapeutică',
 'Reținerea intervalului termic 32-34°C și a duratei 12-24 de ore, cu nuanța studiului din 2013.',
 ['Intervalul 28-30°C și durata de zile nu apar în text.','Studiile au arătat că 32-34°C pentru 12-24 de ore poate îmbunătăți prognosticul la adulții inconștienți după FV extraspatială.','Un studiu din 2013 a găsit rezultate similare la 33°C versus 36°C; importanța hipotermiei rămâne neclară, dar ținta clasică citată este 32-34°C.','Hipertermia nu este strategia post-resuscitare descrisă.','Studiul din 2013 a inclus și ritmuri neșocabile, cu rezultate neurologice mai bune, nu o interdicție.']],
 8,'Alege între trei ferestre termice plauzibile; doar 32-34°C/12-24 h este cifra din paragraf.',['32-34°C','12-24 ore']),

q(25,['Cardioversia cu curent direct a tahiaritmiilor instabile hemodinamic:',
 ['Folosește un anestezic cu acțiune scurtă; miorelaxantele nu sunt utilizate de rutină','Șocul este nesincronizat, identic defibrilării fibrilației ventriculare','Transmiterea șocului trebuie să coincidă cu panta descendentă a complexului QRS (sincron)','Este rezervată doar tahiaritmiilor care au răspuns deja la tratamentul medicamentos','Padelele se plasează doar sub scapula stângă, poziția stern-apex fiind interzisă'],'AC',1048,'Cardioversia cu curent direct',
 'Diferențierea șocului sincronizat pe panta descendentă a QRS de defibrilarea nesincronizată.',
 ['Textul precizează anestezic cu acțiune scurtă și lipsa utilizării de rutină a miorelaxantelor.','Între defibrilare și cardioversie există o diferență fundamentală: cardioversia este sincronă.','Șocul trebuie să coincidă cu panta descendentă a QRS; aparatul declanșează automat șocul sincron.','Indicația este tocmai tahiaritmia care nu răspunde medicamentos sau este instabilă.','Sunt descrise două poziții de padele, inclusiv dreapta sternului superior și apexul.']],
 8,'Confundă cardioversia sincronă cu defibrilarea FV și anulează una dintre cele două poziții clasice de padele.',['panta descendentă','Cardioversia cu curent direct']),

q(26,['Alegeți afirmațiile corecte referitoare la balonul de contrapulsație aortică și la definițiile aritmiilor:',
 ['Complicațiile IABP apar la aproximativ 20% dintre pacienți (disecție de aortă, ischemie de membru, embolizare, ruptură de balon)','Bradicardia este frecvență <60 b.p.m. ziua sau <50 b.p.m. nocturn','Tahicardia este frecvență >100 b.p.m.','Complicațiile embolice ale IABP sunt frecvente chiar sub heparină','Bradicardia sinusală fiziologică a sportivului se datorează tonusului simpatic crescut'],'ABC',1051,'Aritmiile cardiace — Definiții; contrapulsația aortică',
 'Memorarea ratei de complicații a IABP și a pragurilor numerice care definesc bradi- și tahicardia.',
 ['Textul indică complicații la aproximativ 20% (disecție, ischemie de membru, embolizare, ruptură).','Bradicardia: <60 b.p.m. în timpul zilei sau <50 b.p.m. nocturn.','Tahicardia: frecvență cardiacă rapidă (>100 b.p.m.).','Complicațiile embolice sunt rare dacă se utilizează anticoagulare cu heparină.','La sportivi bradicardia se datorează tonusului vagal crescut, nu simpatic.']],
 8,'Modifică 20% în „embolie frecventă sub heparină” și inversează tonusul vegetativ al bradicardiei de sportiv.',['20%','<60 b.p.m.'],[1052]),

q(27,['Mecanismul tahicardiilor atriale din intoxicația digitalică este:',
 ['Reintrarea în jurul unui miez cicatricial ventricular','Activitatea declanșată (trigger) prin postdepolarizări','Automatismul sinusului carotidian','Blocul unidirecțional pe o cale accesorie Kent','Creșterea izolată a pantei fazei 0 fără postpotențiale'],'B',1052,'Mecanismele de producere a aritmiilor — Activitatea declanșată',
 'Identificarea activității trigger ca mecanism al tahicardiei atriale digitalice, distinct de reintrare.',
 ['Reintrarea explică majoritatea tahicardiilor paroxistice regulate, nu specific intoxicația digitalică.','Textul precizează că tahicardiile atriale din intoxicația digitalică au ca mecanism activitatea declanșată (trigger).','Sinusul carotidian este implicat în sindroame mediate neural, nu în digitală.','Calea Kent aparține AVRT, nu intoxicației digitalice.','Post-potențialele precoce sau tardive definesc activitatea trigger, nu absența lor.']],
 8,'Atribuie digitalicei mecanismul de reintrare sau de cale accesorie, deși textul o leagă explicit de postdepolarizări.',['intoxicaţia digitalică','post-potenţiale']),

q(28,['Următoarele afirmații despre sindroamele mediate neural și boala de nod sinusal sunt adevărate:',
 ['Sindromul de sinus carotidian apare la vârstnici și determină frecvent bradicardie','POTS este o creștere acută semnificativă a frecvenței, cu TA normală sau ușor redusă la ortostatism','Hipersensibilitatea carotidiană cu asistolă >3 sec, simptomatică reproductibil, poate beneficia de stimulare permanentă','Sincopa vasovagală afectează doar vârstnicii, fiind rară la adulții tineri','Boala de nod simptomatică se tratează doar cu ablație, stimularea DDD fiind contraindicată'],'ABC',1053,'Bradicardiile — Sindroame mediate neural și boala de nod',
 'Diferențierea sinusului carotidian, POTS și indicația de pacing la asistolă >3 sec de sincopa vasovagală a tânărului.',
 ['Textul situează sindromul de sinus carotidian la vârstnici, cu bradicardie frecventă.','POTS este definit prin creștere acută a frecvenței cu TA normală sau ușor redusă la ortostatism.','Asistola >3 sec, cu simptome reproductibile la masaj, poate beneficia de cardiostimulare permanentă.','Sincopa reflexă (vasovagală) afectează mai frecvent adulții tineri, putând apărea și la vârstnici.','Boala de nod simptomatică poate necesita stimulare permanentă DDD, asociată cu antiaritmice sau ablație pentru tahicardii.']],
 8,'Inversează vârsta sincopei vasovagale și interzice stimularea DDD, deși textul o indică în boala de nod simptomatică.',['asistolă >3 sec','POTS'],[1052]),

q(29,['Blocul atrioventricular de gradul II se caracterizează prin:',
 ['Mobitz I (Wenckebach): prelungirea progresivă a PR până la o undă P blocată','Mobitz II: undă P blocată fără prelungirea progresivă a PR, de obicei cu QRS >0,12 sec','Conducerea 2:1 sau 3:1 nu se clasifică nici ca Mobitz I, nici ca Mobitz II','Wenckebach este de obicei infranodal, iar Mobitz II la nivelul nodului AV','Riscul de progresie spre BAV complet este mai mare în Mobitz II decât în Wenckebach'],'ABCE',1053,'Bradicardiile — BAV de gradul II',
 'Localizarea nodalu versus infranodală a subtipurilor Mobitz și recunoașterea conducerii 2:1 ca formă aparte.',
 ['Definiția Wenckebach este prelungirea progresivă a PR până la P blocată.','Mobitz II nu are prelungire progresivă; QRS este de obicei larg (>0,12 sec).','Textul precizează că 2:1 sau 3:1 este o formă aparte, neîncadrată ca Mobitz I sau II.','Relația este inversă: Wenckebach la nivelul nodului AV, Mobitz II infranodal (fascicul His).','Riscul de progresie spre BAV complet este mai mare în Mobitz II, ritmul de scăpare fiind mai puțin eficient.']],
 8,'Inversează sediul Wenckebach/Mobitz II, capcana clasică de localizare a blocului de grad II.',['Mobitz I','conducere 2: 1']),

q(30,['În infarctul miocardic acut complicat cu BAV de gradul II:',
 ['BAV II din infarctul inferior se recomandă monitorizare și cardiostimulare temporară','BAV II din infarctul anterior are risc mai mare de progresie spre BAV complet și indică stimulare percutană temporară până la stimulator permanent','BAV II din infarctul anterior este benign și nu necesită stimulare','Blocurile 2:1 se localizează doar infranodal','Atropina vindecă durabil blocul anterior cu QRS larg'],'AB',1055,'Bradicardiile — BAV II în infarctul miocardic',
 'Diferențierea prognosticului BAV II din infarctul inferior față de cel anterior.',
 ['Textul recomandă monitorizare și cardiostimulare temporară în BAV II din infarct inferior.','BAV II din infarct anterior are risc mai mare de progresie; se indică stimulare percutană temporară până la implant permanent.','Forma anterioară nu este benignă; riscul de BAV complet este mai mare.','Blocurile 2:1 se pot localiza atât la nivelul nodului AV, cât și infranodal.','Atropina este discutată la BAV cu complexe înguste și cauze tranzitorii, nu ca vindecare a blocului anterior distal.']],
 8,'Inversează gravitatea infarctului anterior versus inferior, perechea clasică de prognostic al BAV peri-infarct.',['infarctul miocardic anterior','cardiostimulare temporară'],[1053]),

q(31,['Identificați afirmația corectă privind BAV congenital complet:',
 ['Nu necesită stimulare dacă este asimptomatic, spre deosebire de forma dobândită','Răspunde durabil la verapamil intravenos','Se asociază doar cu boala Lev a vârstnicului','Cardiostimularea este recomandată pentru BAV congenitale, chiar dacă sunt asimptomatice','Ritmul de scăpare este constant 15-20 b.p.m., indiferent de lățimea QRS'],'D',1055,'BAV complet — Forme congenitale',
 'Recunoașterea indicației de pacing în BAV congenital chiar asimptomatic.',
 ['Textul recomandă cardiostimulare și pentru BAV congenitale asimptomatice.','Verapamilul nu este tratamentul BAV congenital.','Boala Lev este fibroza distală a vârstnicului, nu forma congenitală (LES matern, transpoziție).','Cardiostimularea este recomandată pentru BAV congenitale, chiar dacă sunt asimptomatice.','Ritmul de scăpare depinde de sediu: 50-60 b.p.m. dacă QRS îngust, 15-40 dacă QRS larg.']],
 8,'Extinde „watchful waiting” al BAV dobândit îngust asimptomatic la forma congenitală, pe care textul o pacează.',['BAV congenitale','LES matern']),

q(32,['Blocurile de ramură și hemiblocurile se caracterizează prin:',
 ['Blocul incomplet alungește QRS până la 0,12 sec; blocul complet presupune QRS ≥0,12 sec','BRD: unde S adânci în DI și V6, unde R ample tardive în V1','Hemiblocul antero-superior produce deviație axială stângă','BRS lasă neschimbată activarea inițială, fără unde Q anormale','Hemiblocul postero-inferior orientează axul QRS inferior și spre dreapta'],'ABCE',1056,'Blocul de ramură — ECG și hemiblocuri',
 'Corelarea morfologiei QRS și a axului cu ramul sau fasciculul blocat.',
 ['Întârzierea de ramură incompletă alungește QRS până la 0,12 sec; blocul complet are QRS ≥0,12 sec.','BRD activează tardiv VD: S adânci în DI/V6 și R ample tardive în V1.','Blocarea fasciculului anterior orientează activarea spre stânga-superior (deviație axială stângă).','BRS determină și unde Q anormale, fiind ramul care inițiază activarea ventriculară.','Fasciculul postero-inferior blochează axul inferior și spre dreapta.']],
 8,'Neagă undele Q ale BRS, deși textul le leagă de inițierea stângă a activării ventriculare.',['0,12 sec','deviaţie axială stângă']),

q(33,['Etiologia blocului de ramură dreaptă:',
 ['Poate fi anomalie congenitală izolată, prezentă la 5% din populația sănătoasă','Asocierea BRD cu deviație axială stângă se întâlnește în DSA tip ostium primum','BRD izolat rotește constant axul electric spre dreapta, chiar fără hipertrofie de VD','BRS complet este rar asociat cu insuficiența ventriculară stângă','DSA ostium secundum produce tipic BRS complet, nu BRD'],'AB',1057,'Bloc de ramură dreaptă — Etiologie',
 'Recunoașterea BRD-ului congenital la 5% din sănătoși și a asocierii ostium primum cu BRD plus ax stâng.',
 ['BRD poate fi anomalie congenitală izolată la 5% din populația sănătoasă.','Asocierea BRD cu deviație axială stângă este întâlnită în DSA ostium primum.','BRD izolat nu afectează în general axul, decât cu HVD, suprasarcină de VD sau bloc fascicular.','BRS complet este frecvent asociat cu insuficiența ventriculară stângă.','Ostium primum, nu secundum, este legat de BRD plus ax stâng.']],
 8,'Transformă BRD-ul izolat într-un determinant al axului drept și mută markerul ostium primum pe ostium secundum.',['5% din populaţia sănătoasă','ostium primum']),

q(34,['Tahicardia prin reintrare în nodul atrioventricular (AVNRT):',
 ['Este de două ori mai frecventă la femei','Prevalența TSV paroxistice dependente de nodul AV este de aproximativ 2,5/1.000, cu debut uzual între 12 și 30 de ani','Forma tipică „slow-fast” folosește anterograd calea lentă și retrograd calea rapidă','Calea lentă are perioadă refractară lungă, iar calea rapidă perioadă scurtă','Tahicardia sinusală inadecvată este diagnosticul de primă intenție la bărbatul vârstnic cu boală structurală'],'ABC',1057,'TSV — AVNRT și tahicardia sinusală inadecvată',
 'Aplicarea epidemiologiei (femei ×2, 2,5/1.000, vârsta 12-30) și a circuitului slow-fast.',
 ['AVNRT este de două ori mai frecventă la femei.','Debutul TSV paroxistice dependente de nod este de obicei între 12 și 30 de ani, prevalența aproximativ 2,5/1.000.','În forma tipică, extrasistola cade pe calea rapidă refractară și conduce pe calea lentă, apoi retrograd pe cea rapidă (slow-fast).','Textul atribuie căii lente perioada refractară scurtă și conducere lentă, căii rapide perioada lungă și conducere rapidă.','Tahicardia sinusală inadecvată apare mai frecvent la femeile tinere, nu la bărbatul vârstnic cu boală structurală.']],
 8,'Inversează proprietățile electrofiziologice ale căilor lentă/rapidă, capcana clasică a AVNRT.',['2,5/1.000','slow-fast']),

q(35,['Pe ECG, AVNRT tipică se caracterizează cel mai adesea prin:',
 ['QRS normale, regulate, 140-240/min, cu unde P absente sau imediat înainte/după QRS','Unde F în dinți de fierăstrău la 300/min cu conducere 2:1','Intervale RR neregulate neregulate și absența activității atriale organizate','PR scurt și undă delta în tahicardie ortodromică','QRS larg prin activare ventriculară pe calea Kent, ca regulă'],'A',1058,'TSV — Aspectul ECG al AVNRT',
 'Recunoașterea QRS îngust 140-240/min cu P simultane ca tipar al AVNRT, distinct de flutter, FA și WPW.',
 ['Textul descrie QRS normale, regulate, 140-240/min; undele P lipsesc sau sunt imediat înainte/după QRS.','Undele de flutter cu 300 b.p.m. aparțin flutterului atrial.','RR neregulate neregulate definesc fibrilația atrială.','PR scurt și unda delta sunt ale preexcitației în ritm sinusal, nu ale AVNRT.','AVNRT are de obicei QRS îngust; QRS largul prin Kent este al AVRT antidromice.']],
 8,'Oferă tipare ECG reale ale altor TSV din același cadran ca alternative la AVNRT.',['140-240/min','AVNRT']),

q(36,['În fibrilația atrială preexcitată din sindromul WPW:',
 ['O cale accesorie cu perioadă refractară anterogradă <250 ms poate conduce la frecvență ventriculară foarte înaltă, cu risc de FV','Incidența morții subite este 0,15-0,39% per pacient-an, putând fi prima manifestare la tineri','Verapamilul sau digoxinul pot accelera conducerea pe calea accesorie și precipita FV, deci nu se folosesc','Adenozina 6 mg apoi 12 mg este tratamentul de elecție al FA preexcitate cu QRS larg','AVRT ortodromică produce, de regulă, tahicardie cu QRS larg'],'ABC',1059,'WPW — Fibrilația atrială preexcitată',
 'Recunoașterea pragului <250 ms, a riscului de moarte subită și a interdicției verapamil/digoxin în FA-WPW.',
 ['Perioada refractară anterogradă <250 ms permite conducere foarte rapidă, cu risc de fibrilație ventriculară.','Incidența morții subite este 0,15-0,39% per pacient-an.','Verapamilul sau digoxinul pot cauza conducere mai rapidă pe calea accesorie; nu se folosesc în FA asociată WPW.','Adenozina termină AVNRT/AVRT; FA preexcitată cu QRS larg nu se tratează astfel.','AVRT ortodromică produce de obicei QRS înguste; antidromica produce QRS largi.']],
 8,'Extinde adenozina (utilă în AVNRT) la FA preexcitată și inversează lățimea QRS a AVRT ortodromice.',['<250 ms','0,15-0,39%']),

q(37,['Ablația cu cateter în tahicardiile dependente de nodul AV:',
 ['Modificarea căii lente este eficientă la 96% dintre pacienții cu AVNRT, cu risc de 1% de BAV complet','Ablația unei singure căi accesorii are succes de 95%, cu recurență de 5%','Succesul în AVNRT este de circa 50%, iar BAV complet apare la 20%','Verapamilul după beta-blocante este asocierea de elecție în tahicardia cu QRS >0,12 sec','Adenozina este interzisă la astmatici, fără nicio posibilitate de administrare cu precauție'],'AB',1059,'AVNRT/AVRT — Tratament pe termen lung și ablație',
 'Memorarea ratelor de succes 96%/95% și a riscului de 1% BAV la modificarea căii lente.',
 ['Modificarea căii lente: eficiență 96%, risc 1% de bloc AV complet.','Ablația unei căi accesorii: succes 95%, recurență 5%.','Cifrele 50% și 20% nu apar; succesul este net superior, iar BAV-ul este rar.','Verapamil nu trebuie administrat după beta-blocante sau în tahicardii cu QRS >0,12 sec.','Adenozina se utilizează cu precauție la astmatici, nu ca interdicție absolută.']],
 8,'Înlocuiește 96%/1% și 95%/5% cu eșecuri de ordinul zecilor de procente, plauzibile pentru o procedură „invazivă”.',['96%','risc de 1%']),

q(38,['Epidemiologia și cauzele fibrilației atriale:',
 ['Apare la 1-2% din populația generală și la 5-15% dintre persoanele peste 75 de ani','Hipertensiunea și insuficiența cardiacă sunt cele mai frecvente cauze în țările dezvoltate','Aproximativ 30-40% dintre pacienți, mai ales tineri, au cel puțin un părinte cu FA','Apare la o treime dintre pacienții post-chirurgie cardiacă','Cauza clasică dominantă în țările dezvoltate rămâne boala reumatică, nu hipertensiunea'],'ABCD',1059,'Fibrilația atrială — Epidemiologie',
 'Aplicarea cifrelor 1-2%, 5-15% peste 75 de ani, 30-40% istoric parental și o treime postoperator.',
 ['Prevalența 1-2% în populație și 5-15% peste 75 de ani este explicită.','Hipertensiunea și insuficiența cardiacă sunt cele mai frecvente cauze în țările dezvoltate.','Aproximativ 30-40% au cel puțin un părinte cu FA.','FA apare la o treime din pacienții post-chirurgie cardiacă.','Boala reumatică, alcoolul și tireotoxicoza sunt cauze clasice, dar nu cele mai frecvente în țările dezvoltate.']],
 8,'Păstrează etiologia „clasică” reumatică ca dominantă în Occident, deși textul o înlocuiește cu HTA și IC.',['1-2%','5-15%'],[1060]),

q(39,['Clasificarea clinică a fibrilației atriale include:',
 ['Paroxistică — convertită spontan în cel mult 7 zile','Persistentă — continuă, durată >7 zile','Persistentă îndelungată — continuă, durată >1 an','Permanentă — orice FA de peste 48 de ore, indiferent de decizia de conversie','Nou diagnosticată se defineste doar dacă durata este sub 24 de ore'],'ABC',1060,'Fibrilația atrială — Clasificare clinică',
 'Diferențierea pragurilor de 7 zile și 1 an și a FA permanente ca decizie comună, nu ca durată brută.',
 ['Paroxistică: convertită spontan în cel mult 7 zile.','Persistentă: continuă, durată >7 zile.','Persistentă îndelungată: continuă, durată >1 an.','Permanentă înseamnă decizia comună de a abandona reconversia, nu simpla durată de 48 de ore.','Nou diagnosticată este independentă de durată sau severitatea simptomelor.']],
 8,'Confundă pragul de anticoagulare al cardioversiei (48 h) cu definiția FA permanente.',['7 zile','>1 an'],[1061]),

q(40,['În vederea cardioversiei elective a fibrilației atriale cu durată peste 48 de ore:',
 ['Anticoagularea 3 săptămâni înainte nu este necesară dacă se folosește un DOAC','Se anticoagulă 3 săptămâni anterior (warfarină INR 2,0-3,0 sau DOAC) și cel puțin 4 săptămâni după','Conversia electrică reușește la aproximativ 80% dintre pacienți; unda bifazică este mai eficientă','Ecografia transesofagiană este inutilă dacă cardioversia este urgentă și pacientul nu este anticoagulat','Metoda „pill in pocket” folosește doar digoxin oral la domiciliu, fără testare spitalicească'],'BC',1061,'Fibrilația atrială — Cardioversie și anticoagulare peri-procedurală',
 'Aplicarea ferestrei 3 săptămâni înainte / 4 după și a ratei de succes de 80% a cardioversiei electrice.',
 ['DOAC sau warfarina se folosesc 3 săptămâni înainte, exceptând FA <48 de ore; DOAC nu scutesc de această fereastră.','Textul precizează 3 săptămâni anterior și cel puțin 4 săptămâni după.','Conversia electrică reușește la aproximativ 80%; defibrilarea bifazică este mai eficientă.','Dacă cardioversia este urgentă fără anticoagulare, ETE exclude trombii intraatriali.','Pill in pocket înseamnă flecainidă sau propafenonă orală, testate în prealabil în spital.']],
 8,'Anulează fereastra de 3 săptămâni sub pretextul DOAC și înlocuiește antiaritmicul de buzunar cu digoxin.',['3 săptămâni','80%']),

q(41,['Controlul ritmului versus controlul frecvenței în fibrilația atrială:',
 ['Studiile AFFIRM (>65 ani) și AF-CHF nu au arătat o diferență netă de mortalitate între strategii','La insuficiență cardiacă sau hipertrofie de VS se recomandă doar amiodarona pentru menținerea sinusului','Frecvența de repaus se consideră controlată sub 110 b.p.m.; dacă simptomele persistă, ținta este 60-80 în repaus și <110 la efort moderat','Ablația de vene pulmonare elimină necesitatea anticoagulării ulterioare','Amiodarona este antiaritmicul de primă alegere la tânărul fără boală structurală, înaintea clasei Ic'],'ABC',1061,'Fibrilația atrială — Controlul ritmului și al frecvenței',
 'Aplicarea rezultatelor AFFIRM/AF-CHF, a restricției amiodaronei în IC/HVS și a țintelor de frecvență <110 apoi 60-80.',
 ['AFFIRM și AF-CHF nu arată diferență netă de mortalitate sau simptomatologie între strategii.','În IC sau hipertrofie de VS se recomandă doar amiodarona.','Controlul este FC de repaus <110; dacă persistă simptome, 60-80 în repaus și <110 la efort moderat.','O ablație aparent reușită nu elimină necesitatea unei anticoagulări eficiente.','Amiodarona se rezervă cazurilor în care celelalte antiaritmice au eșuat, din cauza efectelor extracardiace.']],
 8,'Transformă ablația într-un substitut al anticoagulării și promovează amiodarona ca primă linie la cordul structural normal.',['AFFIRM','sub 110 b.p.m.']),

q(42,['Un scor HAS-BLED de 3 sau mai mult corespunde unui risc anual de hemoragie majoră sub anticoagulante:',
 ['De circa 1%, identic scorului 0','Peste 5% (risc crescut)','Sub 0,1%, neglijabil clinic','Identic riscului de AVC al CHA2DS2-VASc 0','Doar riscului de sângerare gingivală, nu de hemoragie majoră'],'B',1062,'Fibrilația atrială — Scorul HAS-BLED',
 'Reținerea pragului HAS-BLED ≥3 ca risc anual de hemoragie majoră >5%.',
 ['Scorul 0 are risc anual de circa 1% (risc scăzut).','Textul precizează risc >5% la un scor de 3 sau mai mult (risc crescut).','Valoarea <0,1% nu apare.','HAS-BLED estimează sângerarea, nu AVC-ul.','Definiția este hemoragie majoră, nu sângerare minoră.']],
 8,'Confundă 1% al scorului 0 cu >5% al scorului ≥3, două capete ale aceleiași scale.',['HAS-BLED','>5%']),

q(43,['Flutterul atrial tipic (dependent de istm):',
 ['Este un ritm atrial organizat, 250-350 b.p.m., cu circuit de macro-reintrare în jurul inelului tricuspidian','Modelul cel mai frecvent este antiorar, cu unde F negative în derivațiile inferioare și pozitive în V1-V2','Cea mai frecventă conducere AV este 2:1, cu frecvență ventriculară 150 b.p.m.','Undele F antiorare sunt pozitive inferior și negative în V1','Ablația de istm cavo-tricuspidian este o opțiune de rezervă, ineficientă în flutterul tipic'],'ABC',1062,'Flutterul atrial — Mecanism și ECG',
 'Recunoașterea circuitului antiorar 250-350/min și a conducerii 2:1 la 150 b.p.m.',
 ['Flutterul tipic: 250-350 b.p.m., macro-reintrare atrial dreaptă în jurul inelului tricuspidian.','Antiorar: F negative inferior, pozitive în V1 și V2.','Cel mai frecvent, fiecare a doua undă este condusă → 150 b.p.m.','Orientarea descrisă este a flutterului orar, nu antiorar.','Ablația de istm este terapia de elecție în flutterul tipic recurent, aproape definitivă.']],
 8,'Inversează polaritatea undelor F antiorar/orar și degradează ablația de istm, metoda de elecție.',['250-350 b.p.m.','dinţi de fierăstrău'],[1063]),

q(44,['Tahicardia atrială:',
 ['Prevalența este sub 1% din toate tipurile de aritmii','Forma prin automatism crescut (125-250 b.p.m.) prezintă frecvent „warm-up” și „cool-down”','Masajul sinusului carotidian oprește constant tahicardia atrială, ca pe AVNRT','Tahicardia atrială cu bloc este, de obicei, extrasistolică benignă, fără legătură cu digitala','Forma prin reintrare este tipic mai rapidă (peste 250 b.p.m.) decât cea automată'],'AB',1063,'Tahicardia atrială',
 'Diferențierea formei automate cu warm-up/cool-down de reintrarea mai lentă 125-150 și de efectul masajului carotidian.',
 ['Prevalența este sub 1% din toate tipurile de aritmii.','Automatismul crescut: 125-250 b.p.m., cu creștere și scădere progresivă a frecvenței.','Masajul poate crește gradul de BAV și ajută diagnosticul, dar nu oprește tahicardia.','Tahicardia atrială cu bloc este de multe ori rezultatul intoxicației digitalice.','Reintrarea este de obicei mai lentă (125-150 b.p.m.), nu mai rapidă.']],
 8,'Atribuie masajului carotidian oprirea AVNRT-like și inversează vitezele reintrare versus automatism.',['warm-up','sub 1%']),

q(45,['Diagnosticul diferențial ECG între tahicardia ventriculară și TSV cu aberanță este orientat spre TV dacă există:',
 ['QRS foarte larg (>0,14 sec)','Disociație atrioventriculară','Concordanță QRS (aceeași polaritate în V1-V6)','Undă S adâncă în V6','QRS îngust (<0,10 sec) cu morphologie tipică de BRD'],'ABCD',1063,'Aritmiile ventriculare — Criterii ECG (Cadranul 30.17)',
 'Aplicarea criteriilor din Cadranul 30.17 și a regulii că 80% dintre tahicardiile cu QRS larg sunt ventriculare.',
 ['Cadranul 30.17 include QRS foarte larg (>0,14 sec).','Disociația AV pledează pentru TV.','Concordanța QRS în precordialele V1-V6 este criteriu de TV.','Unda S adâncă în V6 este enumerată.','QRS îngust cu morphologie tipică de bloc de ramură pledează pentru TSV cu aberanță, nu pentru TV.']],
 8,'Cele patru criterii reale stau alături de morphologia care, dimpotrivă, susține TSV cu aberanță.',['>0,14 sec','disociaţie atrioventriculară']),

q(46,['Identificați afirmația corectă referitoare la sindromul Brugada:',
 ['Beta-blocantele sunt tratamentul de elecție și reduc mortalitatea','Mutația SCN5A explică toate cazurile, fiind constantă','Singurul tratament eficient este implantarea ICD; beta-blocantele nu sunt utile, putând fi chiar nocive','Testul de provocare se face cu amiodaronă, nu cu flecainidă sau ajmalină','Este mai frecvent la femei vârstnice din Europa de Nord decât la tinerii de sex masculin din Asia de Sud-Est'],'C',1064,'Sindromul Brugada',
 'Recunoașterea ICD ca unică terapie eficientă și a potențialului nociv al beta-blocantelor.',
 ['Beta-blocantele nu sunt utile, putând fi chiar nocive.','Doar în 20% din cazuri este moștenită prin mutația SCN5A; există și alte gene.','Textul precizează că singurul tratament eficient este ICD-ul; beta-blocantele pot fi nocive.','Testul de provocare folosește antiaritmice de clasă I (flecainidă sau ajmalină).','Se întâlnește mai frecvent la tineri de sex masculin și în Asia de Sud-Est.']],
 8,'Promovează beta-blocantul — util în LQTS — ca terapie Brugada, deși textul îl consideră potențial nociv.',['SCN5A','sindrom Brugada']),

q(47,['Sindromul QT lung congenital:',
 ['Jervell-Lange-Nielsen asociază surditate și este autozomal recesiv; Romano-Ward este autozomal dominant, fără surditate','LQT1 (KCNQ1): aritmii declanșate de efort, în special înot','LQT2 (KCNH2): aritmii declanșate de emoții sau stimuli acustici','LQT3 (SCN5A): aritmii în efortul maximal, nu în somn','Isoprenalina este tratamentul de elecție al formei congenitale, nu al celei dobândite'],'ABC',1065,'Sindromul QT lung congenital — LQT1–3',
 'Potrivirea genei cu trigger-ul (înot, stimuli acustici, somn) și a transmiterii Jervell versus Romano-Ward.',
 ['Jervell-Lange-Nielsen: autozomal recesiv cu surditate; Romano-Ward: autozomal dominant fără surditate.','LQT1: efort, în special înot.','LQT2: emoții sau stimuli acustici.','LQT3 (SCN5A): aritmii în repaus sau în timpul somnului, nu la efort maximal.','Isoprenalina poate fi eficientă în QT lung dobândit și este contraindicată în forma congenitală.']],
 8,'Schimbă trigger-ul LQT3 cu efortul (al LQT1) și inversează indicația isoprenalinei congenital/dobândit.',['LQT1','Romano-Ward'],[1064]),

q(48,['Tratamentul acut al torsadei din QT lung dobândit include:',
 ['Sulfat de magneziu 8 mmol în 10-15 minute','Isoprenalină intravenos, eficientă în forma dobândită','Isoprenalină ca primă linie și în forma congenitală','Prelungirea bradicardiei pentru a scurta QT','Menținerea medicamentului cauzator până la dispariția aritmiei'],'AB',1065,'QT lung dobândit — Tratament acut',
 'Reținerea dozei de magneziu 8 mmol și a distincției isoprenalină: utilă dobândit, contraindicată congenital.',
 ['Textul indică sulfat de magneziu 8 mmol (Mg2+) în 10-15 min pentru QT lung dobândit.','Isoprenalina i.v. poate fi eficientă în QT lung dobândit.','Isoprenalina este contraindicată la pacienții cu QT lung congenital.','Prelungirea QT și torsada sunt provocate de obicei de bradicardie; se menține frecvența prin stimulare.','Se sistează medicamentele care induc QT lung.']],
 8,'Extinde isoprenalina — legitimă în forma dobândită — la LQTS congenital, unde textul o contraindică.',['8 mmol','lsoprenalină']),

q(49,['Tahicardia ventriculară nesusținută (TVNS):',
 ['Este definită ca ≥5 bătăi ventriculare consecutive, cu durată sub 30 de secunde','Poate apărea la 6% dintre pacienții cu cord structural normal, de regulă fără tratament','Apare la 60-80% dintre pacienții cu boală cardiacă structurală','Supresia cu antiaritmice de clasă I este necesară pentru îmbunătățirea prognosticului','ICD nu aduce beneficiu la fracție de ejecție <30%'],'ABC',1066,'Tahicardia ventriculară nesusținută',
 'Aplicarea definiției ≥5 bătăi/<30 s și a prevalențelor 6% versus 60-80%.',
 ['Definiția este o succesiune de 5 sau mai multe bătăi ventriculare, durată sub 30 de secunde.','TVNS poate apărea la 6% cu cord structural normal, de regulă fără tratament.','Apare la 60-80% din pacienții cu boală cardiacă structurală.','Supresia cu antiaritmice nu este necesară; beta-blocantele pot îmbunătăți calitatea vieții.','ICD a îmbunătățit supraviețuirea la pacienții cu fracție de ejecție <30%.']],
 8,'Inversează indicația ICD la FE<30% și transformă antiaritmicele de clasă I în terapie de prognostic.',['5 sau mai multe','<30%']),

q(50,['Precizați enunțul corect despre tahicardia ventriculară idiopatică pe cord structural normal:',
 ['Are prognostic infaust, similar TV din cardiopatia ischemică','Ablația cu radiofrecvență este curativă în 90% din cazuri la simptomatici','Originea este constant în atriul stâng, fără posibilitate de localizare în tractul de ejecție al VD','Verapamilul este contraindicat în formele idiopatice, inclusiv în varianta sensibilă la blocante de calciu','Tahicardia Gallavardin este o formă scurtă, nesusținută, fără risc de cardiomiopatie'],'B',1066,'TV pe cord structural normal',
 'Reținerea ratei de 90% a ablației curative și a originii RVOT/septal stâng.',
 ['Textul o consideră de obicei benignă, cu prognostic excelent pe termen lung.','La simptomatici, ablația cu radiofrecvență este foarte eficientă, curativă în 90% din cazuri.','Poate origina în tractul de ejecție al VD sau la nivelul VS septal.','Există o formă sensibilă la verapamil, care răspunde la blocantele de calciu non-dihidropiridinice.','Gallavardin este forma incesantă care, netratată, poate conduce la cardiomiopatie.']],
 8,'Atribuie formei idiopatice prognosticul TV ischemice și interzice verapamilul, deși există o variantă sensibilă la acesta.',['90% din cazuri','tahicardia Gallavardin']),

q(51,['Clasificarea Vaughan Williams, dincolo de subclasele Ia/Ib/Ic deja cunoscute:',
 ['Clasa Ia (disopiramidă) prelungește potențialul de acțiune','Clasa II sunt beta-blocante (atenolol, bisoprolol, propranolol, esmolol)','Clasa IV (verapamil, diltiazem) scurtează potențialul de acțiune (faza de platou)','Vernakalantul este un beta-blocant pur, fără efect pe canale multiple','Regula generală: clasa Ic la cord structural, clasa III doar la cord normal'],'ABC',1067,'Antiaritmice — Vaughan Williams (clasele II, III, IV)',
 'Completarea tabelului: Ia prelungește PA, II = beta-blocante, IV scurtează platoul; vernakalant pentru cardioversia FA.',
 ['Cadranul 30.19: clasa Ia prelungește potențialul de acțiune (disopiramidă).','Clasa II: atenolol, acebutolol, bisoprolol, propranolol, esmolol.','Clasa IV scurtează potențialul de acțiune (faza de platou): verapamil, diltiazem.','Vernakalant este blocant al mai multor canale, aprobat i.v. pentru cardioversia FA paroxistice.','Regula generală este inversă: Ic la cord structural normal, III la boli structurale.']],
 8,'Inversează regula Ic/III pe cord normal versus structural și degradează vernakalantul la un beta-blocant pur.',['Prelungesc potenţialul de acţiune','Vernakalant']),

q(52,['Ablația cu cateter și defibrilatorul implantabil:',
 ['Este foarte eficientă în AVNRT, AVRT/WPW, TV pe cord normal, flutter, tahicardie atrială și FA paroxistică (izolare de vene pulmonare)','Pacienții simptomatici cu preexcitație (WPW) sunt sfătuiți să recurgă la ablație ca terapie de primă linie','Izolarea venelor pulmonare are succes pe termen lung 70-80% la tineri cu FA paroxistică, AS normal și fără boală structurală','Ablația flutterului tipic este eficientă în 90-95% din cazuri','ICD-ul recunoaște TV/FV dar nu poate livra overdrive pacing, ci doar șocuri'],'ABCD',1068,'Ablația cu cateter și ICD',
 'Reținerea ratelor de succes (PV 70-80%, flutter 90-95%) și a ablației WPW ca primă linie.',
 ['Lista indicațiilor de înaltă eficiență include aceste tahiaritmii.','WPW simptomatic: ablație ca terapie de primă linie, din cauza riscului de moarte subită.','Succes 70-80% la tineri cu FA paroxistică, AS normal, fără boală structurală.','Ablația flutterului tipic: 90-95%.','TV poate fi suprimată și prin overdrive pacing, procedură lipsită de durere.']],
 8,'Neagă overdrive pacing-ul nedureros, deși textul îl opune explicit șocurilor dureroase la conștient.',['70-80%','90-95%']),

q(53,['În prevenția primară a morții subite, ICD:',
 ['A redus mortalitatea cu 23-31% față de tratamentul convențional în MADIT II și SCD-HeFT','Poate fi indicat la IC cu FEVS ≤35% și NYHA <IV; dacă există BRS major (QRS >120 ms) se poate asocia CRT','Șansele de supraviețuire a unui stop extraspatial sunt de 80%, deci prevenția primară este inutilă','NYHA IV în stadiu final este indicația preferată de ICD, nu CRT-D','Doar canalopatiile, nu și CMD/CMH/ARVC familiale, au indicație de prevenție primară'],'AB',1068,'ICD — Prevenție primară (MADIT II, SCD-HeFT)',
 'Aplicarea reducerii de mortalitate 23-31% și a criteriului FEVS ≤35% cu NYHA <IV.',
 ['MADIT II și SCD-HeFT: reducere a mortalității cu 23-31% față de tratamentul convențional.','Grupa cu FEVS ≤35% și NYHA <IV; BRS cu QRS >120 ms aduce beneficiu adițional CRT-D.','Șansele de supraviețuire a unui stop extraspatial sunt de doar 10%.','NYHA IV sau comorbidități care reduc durata de viață nu sunt, în general, candidați la ICD.','Textul include CMD, CMH, QT lung, Brugada, canalopatii cu istoric familial și ARVD.']],
 8,'Înlocuiește 10% supraviețuire extraspatială cu 80% și face din NYHA IV indicația preferată, contrar textului.',['23-31%','35%']),

q(54,['Epidemiologia insuficienței cardiace:',
 ['Afectează aproximativ 26 de milioane de persoane; în Marea Britanie incidența globală este circa 2 din 1.000','Rata mortalității rămâne ridicată: aproximativ 50% dintre pacienți decedează la 5 ani','În țările occidentale, cea mai frecventă cauză este boala coronariană','Reprezintă 25% din internările în secțiile medicale, nu 5%','Prognosticul nu s-a modificat în ultimii 10 ani, terapia bazată pe dovezi fiind ineficace'],'ABC',1069,'Insuficiența cardiacă — Epidemiologie',
 'Reținerea cifrelor 26 de milioane, 2/1.000, mortalitate 50% la 5 ani și a bolii coronariene ca etiologie dominantă occidentală.',
 ['Incidența mondială implică circa 26 de milioane; în UK circa 2 din 1.000.','Aproximativ 50% decedează la 5 ani.','În țările occidentale cea mai frecventă cauză este boala coronariană.','Textul indică 5% din internările în secțiile medicale, nu 25%.','Prognosticul s-a îmbunătățit în ultimii 10 ani datorită terapiei bazate pe dovezi.']],
 8,'Umflă ponderea internărilor de la 5% la 25% și neagă îmbunătățirea prognosticului din ultimul deceniu.',['26 de milioane','2 din 1.000']),

q(55,['Cauzele principale și fiziopatologia insuficienței cardiace:',
 ['Boala ischemică 35-40%, cardiomiopatia dilatativă 30-34%, hipertensiunea 15-20%','Fracția de ejecție scade precoce; tahicardia sinusală compensează scăderea volumului-bătaie','Legea Laplace: tensiunea miocardică este proporțională cu presiunea ori raza cavității','Activarea simpatică cronică este benefic nerestricționată, fără down-regulation de receptori-β','Peptidele natriuretice compensează parțial retenția de sodiu'],'ABCE',1070,'Insuficiența cardiacă — Fiziopatologie și cauze',
 'Aplicarea ponderilor etiologice și a consecințelor legii Laplace și ale activării simpatice cronice.',
 ['Cadranul 30.20: ischemică 35-40%, dilatativă 30-34%, HTA 15-20%.','FE scade precoce; tahicardia sinusală compensează volumul-bătaie scăzut.','Tensiunea T este proporțională cu P × R (Laplace).','Activarea simpatică cronică este nocivă (neurohormoni, apoptoză) și e compensată prin down-regulation de receptori-β.','Retenția de sodiu este parțial compensată de peptidele natriuretice și ADH.']],
 8,'Prezintă hiperactivarea simpatică cronică ca mecanism pur protector, deși textul o descrie ca cerc vicios.',['35-40%','legea Laplace'],[1069]),

q(56,['Terapiile care au redus morbiditatea și mortalitatea în insuficiența cardiacă au avut beneficii dovedite:',
 ['Doar la pacienții cu HFrEF (fracție de ejecție <40%)','Identic în HFpEF (FE >50%) și HFrEF','Doar în HFmrEF (FE 40-50%)','Doar în disfuncția izolată de ventricul drept','Indiferent de fracția de ejecție, inclusiv în pericardita constrictivă'],'A',1071,'HFrEF versus HFpEF',
 'Recunoașterea faptului că beneficiul de mortalitate al terapiilor clasice este demonstrat în HFrEF (FE <40%).',
 ['Textul precizează că terapiile care au redus morbiditatea și mortalitatea au avut beneficii doar la grupul HFrEF (FE <40%).','HFpEF este definită simptomatic cu FE >50%; aceleași terapii nu au același nivel de dovadă.','HFmrEF (40-50%) este o zonă gri recent clasificată, nu singurul grup cu beneficiu.','DSVD are cauze proprii, fără această afirmație de mortalitate.','Pericardita constrictivă nu este HFrEF.']],
 8,'Extinde beneficiul de mortalitate al IECA/BB/ARNI de la HFrEF la HFpEF, eroarea terapeutică clasică.',['fracţie de ejecţie <40%','HFREF']),

q(57,['Peptidele natriuretice și fenotipurile de insuficiență cardiacă:',
 ['ANP este eliberat din miocitele atriale la întindere; induce diureză, natriureză, vasodilatație și suprimă SRAA','BNP este secretat predominant de ventriculi; NT-proBNP este proteina inactivă scindată din proBNP','HFpEF (FE >50%) este mai frecventă la hipertensivii vârstnici și în cardiomiopatii hipertrofice/restrictive/infiltrative','Monitorizarea de rutină a BNP ghidează fiecare ajustare de doză, ca standard terapeutic','CNP este secretat predominant de ventriculul stâng, identic BNP'],'ABC',1071,'Peptidele natriuretice; HFpEF',
 'Diferențierea originii ANP (atrii) versus BNP (ventriculi) și a terenului HFpEF al vârstnicului hipertensiv.',
 ['ANP: miocite atriale, răspuns la stretch, diureză/natriureză/vasodilatație/supresie SRAA.','BNP: predominant ventriculi; NT-proBNP inactiv din proBNP.','IC diastolică/HFpEF: mai frecventă la hipertensivi vârstnici și în CMH, CMR, infiltrative.','Nivelele se corelează cu severitatea, dar monitorizarea nu se folosește de rutină pentru ghidarea tratamentului.','CNP este limitat la endoteliul vascular și SNC, nu este echivalentul ventricular al BNP.']],
 8,'Transformă BNP-ul de prognostic într-un ghid de rutină al dozelor și mută CNP-ul în ventricul.',['NT-proBNP','HFPEF'],[1072]),

q(58,['Clasificarea NYHA a insuficienței cardiace:',
 ['Clasa I: fără limitarea activității fizice obișnuite','Clasa IV: simptome în repaus, exacerbate de orice activitate fizică','Clasa II înseamnă simptome în repaus, identic clasei IV','Clasa III: simptome doar la efort intens, peste activitatea obișnuită','Diagnosticul HFrEF după ESC cere doar FE scăzută, fără simptome sau semne'],'AB',1072,'Insuficiența cardiacă — Clasificarea NYHA',
 'Fixarea extremelor NYHA I și IV și a triadei simptome-semne-FE pentru diagnosticul HFrEF.',
 ['Clasa I: fără limitare; activitatea obișnuită nu determină oboseală, dispnee sau palpitații.','Clasa IV: simptome în repaus, exacerbate de orice activitate.','Clasa II: fără simptome în repaus, simptome la activitatea obișnuită.','Clasa III: simptome la activitate mai scăzută decât cea obișnuită, nu la efort intens.','Diagnosticul HFrEF necesită trei condiții: simptome, semne și FE scăzută.']],
 8,'Suprapune clasa II peste IV (simptome de repaus) și anulează cerința clinică a criteriilor ESC.',['Clasa I','Clasa IV']),

q(59,['Tratamentul medicamentos al insuficienței cardiace cronice — IECA, ARA și diuretice:',
 ['IECA (CONSENSUS, SOLVD) ameliorează simptomele și reduc mortalitatea în toate clasele NYHA I-IV','ARA (candesartan în CHARM alternativ) sunt linia a doua la intoleranța la IECA și nu determină tuse','Dovezile privind efectul diureticelor asupra supraviețuirii sunt limitate, deși ameliorează dispneea','IECA se inițiază în doză maximă, fără monitorizarea creatininei','Combinația diuretic de ansă plus tiazidă este interzisă în IC severă'],'ABC',1073,'Insuficiența cardiacă — IECA, ARA, diuretice',
 'Recunoașterea beneficiului IECA pe tot spectrul NYHA, a ARA ca alternativă fără tuse și a limitei de supraviețuire a diureticelor.',
 ['CONSENSUS și SOLVD: IECA reduc mortalitatea; beneficiu în NYHA I-IV.','ARA sunt linia a doua la intoleranță; nu afectează metabolismul bradikininei și nu determină tuse; CHARM alternativ.','Diureticele ameliorează dispneea și toleranța la efort, dar dovezile de supraviețuire sunt limitate.','IECA se inițiază în doză mică, cu creștere treptată și monitorizarea TA și funcției renale.','În IC severă poate fi necesară combinația ansă plus tiazidă, inclusiv metolazona.']],
 8,'Inițiază IECA la doză maximă fără monitorizare renală și interzice dubla diureză folosită tocmai în IC severă.',['CONSENS','CHARM']),

q(60,['Studiul SHIFT cu ivabradină în insuficiența cardiacă a arătat:',
 ['Creșterea mortalității la pacienții în fibrilație atrială','Scăderea deceselor cardiovasculare și a spitalizărilor la IC cronică cu FEVS ≤35% în ritm sinusal','Absența oricărui efect dacă frecvența rămâne crescută sub beta-blocant','Eficiență superioară ICD în prevenția morții subite','Indicație ca substitut al diureticelor de ansă'],'B',1075,'Insuficiența cardiacă — Ivabradina (SHIFT)',
 'Reținerea populației SHIFT: ritm sinusal, FEVS ≤35%, reducere a deceselor CV și a spitalizărilor.',
 ['SHIFT nu vizează FA ca populație principală; ivabradina inhibă If sinoatrial.','Studiul SHIFT a raportat scăderea deceselor cardiovasculare și a spitalizărilor la IC cronică cu disfuncție de VS (FEVS ≤35%) în ritm sinusal.','Ivabradina poate fi folosită tocmai când FC rămâne crescută sub beta-blocante sau la intoleranță.','În SCD-HeFT, ICD a redus mortalitatea cu 23%; amiodarona nu a avut beneficiu — nu ivabradina versus ICD.','Ivabradina scade selectiv frecvența, fără să înlocuiască diureticele.']],
 8,'Mută populația SHIFT din sinus cu FE≤35% în FA și o pune în competiție falsă cu ICD.',['Studiul SHIFT','ritm sinusal']),

q(61,['Selectați enunțurile adevărate despre digoxin, vasodilatatoare și amiodaronă în IC:',
 ['Studiul DIG a arătat că digoxinul reduce spitalizările; o subanaliză ROCKET AF a sugerat însă mortalitate posibil crescută','Hidralazină plus nitrați au redus mortalitatea la afro-americani în A-HeFT și se folosesc la intoleranța la IECA/ARA','Amiodarona a redus mortalitatea cu 23% față de placebo în SCD-HeFT, superior ICD','Digoxinul este inotropul de primă linie în SCA cu IC','Anticoagularea orală se recomandă în IC în ritm sinusal fără tromb, anevrism sau tromboembolism anterior'],'AB',1075,'Insuficiența cardiacă — Digoxin, hidralazină-nitrați, SCD-HeFT',
 'Contrastul DIG (spitalizări) versus ROCKET AF (mortalitate) și al A-HeFT, față de absența beneficiului amiodaronei în SCD-HeFT.',
 ['DIG: reducerea spitalizărilor; ROCKET AF: mortalitate posibil crescută.','Veterans Administration și A-HeFT susțin hidralazină-nitrați, inclusiv la afro-americani.','SCD-HeFT: amiodarona fără beneficiu versus placebo; ICD a redus mortalitatea cu 23%.','Digoxinul se evită în SCA (cadranul de IC acută); nu este inotrop de primă linie acut coronarian.','Anticoagularea orală în sinus: istoric de tromboembolism, anevrism de VS sau tromb, nu rutina.']],
 8,'Atribuie amiodaronei reducerea de 23% care aparține ICD în același trial SCD-HeFT.',['studiul DIG','A-HeFT']),

q(62,['Terapia de resincronizare, miocardul hibernant și transplantul:',
 ['Miocardul hibernant este prezent la circa 33% dintre pacienții cu boală coronariană evaluați după revascularizare','CRT (CARE-HF, COMPANION) ameliorează simptomele și reduce mortalitatea în NYHA III-IV cu QRS prelungit/BRS','Transplantul, la recipienți selecționați, oferă supraviețuire >90% la 1 an și 75% la 5 ani','NYHA IV terminal este indicația preferată de ICD izolat, fără CRT','Rezistențele vasculare pulmonare crescute sunt o indicație, nu o contraindicație, de transplant'],'ABC',1076,'CRT, miocard hibernant și transplant cardiac',
 'Reținerea prevalenței 33% a hibernării, a trialurilor CARE-HF/COMPANION și a supraviețuirii post-transplant 90%/75%.',
 ['Hibernarea este estimată la 33% după ameliorarea cineticii post-revascularizare.','CARE-HF și COMPANION: ameliorare simptomatică, mai puține evenimente, mortalitate mai mică în NYHA III-IV.','Speranța de supraviețuire: peste 90% la 1 an și 75% la 5 ani.','NYHA IV sau comorbidități care reduc durata de viață nu sunt, în general, candidați la ICD.','Creșterea rezistențelor pulmonare și cancerul activ sunt contraindicații absolute.']],
 8,'Transformă contraindicația de rezistențe pulmonare crescute în indicație și promovează ICD-ul în NYHA IV terminal.',['33%','CARE-HF']),

q(63,['Insuficiența cardiacă acută — prognostic și investigații inițiale:',
 ['Mortalitatea este aproape 10% la 60 de zile, iar mortalitatea sau respitalizarea 35% la 60 de zile','În edemul pulmonar acut, mortalitatea intra-spital este 12% și crește la 30% în 12 luni','BNP >100 pg/ml sau NT-proBNP >300 pg/ml sunt sugestive pentru insuficiență cardiacă','PCWP >16 mmHg, hiponatremia, VS telediastolic mărit și consumul scăzut de O2 sunt indicatori nefavorabili','Un BNP sub aceste praguri confirmă diagnosticul de ICA și face ETT inutilă'],'ABCD',1077,'Insuficiența cardiacă acută — Prognostic și diagnostic',
 'Aplicarea ratelor de mortalitate 10%/35% la 60 de zile și 12%/30% în edemul pulmonar, plus pragurile de peptide.',
 ['Textul citează mortalitate aproape 10% la 60 de zile și mortalitate sau respitalizare 35% la 60 de zile.','Edem pulmonar acut: 12% intra-spital, 30% la 12 luni.','BNP >100 sau NT-proBNP >300 pg/ml sunt sugestive.','PCWP >16 mmHg, Na scăzut, dimensiune telediastolică crescută și consum miocardic de O2 scăzut sunt nefavorabili.','Peptidele sugestive nu înlocuiesc ETT, care trebuie efectuată fără întârziere.']],
 8,'Folosește pragurile reale de peptide ca argument fals că ecografia ar deveni superfluă.',['10% la 60 de zile','NT-proB'],[1076]),
];
