import {advancedQuestion} from './advanced-author';
import type {SourceRow} from './source-author';
const pdfOffset=(p:number)=>p<=1048?p-837:p<=1107?p-839:p-851;
const q=(n:number,row:SourceRow,score:number,reason:string,expressions:string[],related:number[]=[])=>
 advancedQuestion('cardiologie',30,pdfOffset,`cardiologie-adv-${String(n).padStart(3,'0')}`,row,[score,reason],expressions,undefined,related);

export const CARDIOLOGIE_C=[
q(64,['Terapia farmacologică în insuficiența cardiacă acută (Cadranul 30.29):',
 ['Dopamina în doză mică (<2 µg/kg/min) acționează pe receptorii periferici dopaminergici, cu vasodilatație renală/splanhnică, fără dovezi clare de prognostic','Dopamina în doză medie (>2 µg/kg/min) stimulează receptorii β, crescând contractilitatea și debitul','Levosimendanul crește sensibilitatea proteinelor contractile la calciu și deschide canalele de potasiu','CPAP/NIPPV ameliorează precoce dispneea față de oxigenul pe mască, dar nu afectează mortalitatea','Digoxinul 0,5 mg i.v. este inotropul de primă intenție în SCA cu IC acută'],'ABCD',1078,'Insuficiența cardiacă acută — Terapie farmacologică',
 'Diferențierea treptelor de doză ale dopaminei, a mecanismului levosimendanului și a efectului CPAP asupra dispneei, nu a mortalității.',
 ['Doza mică acționează pe receptorii dopaminergici periferici; nu există dovezi de ameliorare semnificativă a prognosticului.','Doza medie acționează pe receptorii β, crescând contractilitatea și debitul.','Levosimendan: inotrop pozitiv vasodilatator prin sensibilizarea la calciu și deschiderea canalelor de K+.','CPAP/NIPPV ameliorează precoce dispneea; mortalitatea nu este însă afectată.','Cadranul precizează: de utilizat în FA; de evitat în SCA.']],
 8,'Inversează interdicția digoxinului în SCA și confundă beneficiul simptomatic al CPAP cu un efect de mortalitate.',['Levosimendan','<2 µg/kg pe min']),

q(65,['Dispozitivele de asistare ventriculară (VAD):',
 ['LVAD preia sânge din ventriculul stâng și îl trimite în aortă; RVAD din ventriculul drept în artera pulmonară','Complicațiile principale sunt tromboembolismul, sângerările, infecțiile și defecțiunile dispozitivului','Dispozitivele extracorporale sunt destinate suportului pe termen lung ca terapie de destinație','RVAD ejectează în aortă, iar LVAD în artera pulmonară','VAD-urile nu au rol de punte către transplant'],'AB',1079,'Dispozitive de asistare ventriculară',
 'Recunoașterea circuitelor LVAD/RVAD și a complicațiilor trombotice, hemoragice și infecțioase.',
 ['LVAD: VS → aortă; RVAD: VD → arteră pulmonară.','Principalele complicații: tromboembolism, sângerări, infecții, defecțiuni.','Extracorporalele sunt pentru asistare de scurtă durată; intracorporalele pentru termen lung, punte sau destinație.','Direcțiile de ejecție sunt inverse față de această afirmație.','Textul le descrie ca punte către chirurgie/transplant sau ca terapie de destinație.']],
 8,'Inversează destinațiile LVAD/RVAD și atribuie extracorporealului rolul de destinație pe termen lung.',['LVAD','tromboembolismul']),

q(66,['Fiziopatologia stenozei coronariene și prezentarea bolii:',
 ['Reducerea cu 50% a diametrului luminal corespunde unei reduceri de circa 70% a suprafeței, cu rezervă de flux zero distal','Unul din trei infarcte rămâne nerecunoscut inițial','Între 30 și 40% dintre pacienții cu SCA nu au simptome precedente de alarmă','După un infarct, riscul de IC sau AVC crește de 3-6 ori','Rezerva coronariană rămâne intactă până la stenoze de 90% din diametru'],'ABCD',1080,'Boala coronariană — Stenoză critică și prezentare clinică',
 'Aplicarea echivalenței 50% diametru ≈ 70% arie și a ponderii infarctelor silențioase sau fără pródrom.',
 ['Reducerea 50% a diametrului = circa 70% a suprafeței; arteriolele distale sunt dilatate maximal.','Unul din trei infarcte rămâne nerecunoscut inițial.','30-40% dintre SCA se prezintă fără simptome precedente de alarmă.','După primul infarct, riscul de IC sau AVC este de 3-6 ori mai mare.','La 50% diametru rezerva de flux este deja zero, nu la 90%.']],
 8,'Mută pragul de rezervă zero de la 50% diametru la 90%, deși textul leagă ischemia de dilatarea maximală distală.',['50%','70%']),

q(67,['Doza de atorvastatină recomandată de NICE este:',
 ['20 mg în prevenția primară la risc CV la 10 ani ≥10%; 80 mg în boala cardiovasculară confirmată, dacă nu există interacțiuni sau intoleranță','80 mg în prevenția primară și 20 mg după un eveniment','10 mg indiferent de context, ca doză unică','Nicio statină în prevenția primară, doar ezetimib','Rosuvastatină 5 mg ca înlocuitor de rutină al atorvastatinei 80 mg'],'A',1081,'Boala coronariană — Tratamentul cu statine',
 'Diferențierea atorvastatinei 20 mg (prevenție primară QRISK ≥10%) de 80 mg (boală confirmată).',
 ['NICE: atorvastatină 20 mg în prevenție primară la risc ≥10% la 10 ani; 80 mg în BCV confirmată, cu excepțiile citate.','Raportul 80/20 este inversat față de text.','Doza unică 10 mg nu este recomandarea NICE citată.','Statinele sunt fundamentul prevenției, nu ezetimibul izolat.','Textul nu impune înlocuirea de rutină cu rosuvastatină 5 mg.']],
 8,'Inversează dozele 20 mg (primară) și 80 mg (secundară), perechea NICE cea mai ușor de confuzat.',['Atorvastatina 20 mg','80 mg']),

q(68,['Angina pectorală — epidemiologie și forme speciale:',
 ['La femei, prevalența este 5-7% între 45-64 ani și 10-12% între 65-84 ani; la bărbați 4-7% respectiv 12-14%','Angina vasospastică (Prinzmetal) apare fără declanșator, de obicei în repaus, mai frecvent la femei, cu supradenivelare ST tranzitorie','Angina microvasculară: angină de efort fără stenoze semnificative; prognostic general favorabil, dar simptome adesea incomplete controlate','Mortalitatea anuală a anginei stabile este 10-15%','Angina clasică, după NICE, are o singură caracteristică din trei'],'ABC',1081,'Angina — Epidemiologie, Prinzmetal și forma microvasculară',
 'Reținerea prevalențelor pe sexe/vârste și a tiparului ECG al anginei Prinzmetal.',
 ['Cifrele 5-7%/10-12% la femei și 4-7%/12-14% la bărbați sunt explicite.','Prinzmetal: fără declanșator, de obicei în repaus, mai frecvent la femei, cu supradenivelare ST tranzitorie.','Microvasculară: fără stenoze semnificative, prognostic favorabil, răspuns incomplet.','Mortalitatea anuală variază între 1,2 și 2,4%, cu deces cardiac 0,6-1,4%.','Angina clasică are cele trei caracteristici; atipică are 2/3, non-anginoasă 1/3.']],
 8,'Umflă mortalitatea anuală de la 1,2-2,4% la 10-15% și degradează angina clasică la un singur criteriu NICE.',['Prinzmetal','5-7%']),

q(69,['Clasificarea CCS a anginei și rezerva fracționată de flux:',
 ['CCS I: fără angină la activitățile zilnice obișnuite; angină la efort intens','Leziunile cu FFR >0,80 pot fi tratate medicamentos, fără stent, cu prognostic bun','CCS IV corespunde anginei doar la urcatul rapid al scărilor','FFR sub 0,50 contraindică orice tratament medicamentos','CCS III înseamnă angină doar nocturnă, fără limitare diurnă'],'AB',1082,'Angina stabilă — CCS și FFR',
 'Aplicarea CCS I versus IV și a pragului FFR >0,80 pentru tratament conservator.',
 ['Clasa I: fără angină la activitățile zilnice; angină la efort intens.','FFR >0,80: tratament medicamentos fără stent, prognostic bun.','Urcatul rapid al scărilor este exemplu de clasă II; clasa IV este angină în repaus sau la orice nivel.','FFR >0,80 permite tratament medicamentos, nu un prag 0,50 de interdicție.','Clasa III: angină la efort redus (50-100 m, un etaj), cu limitare marcată.']],
 8,'Atribuie clasei IV un exemplu de clasă II și inventează un prag FFR 0,50 inexistent.',['0,80','Clasa I'],[1081]),

q(70,['Intervenția coronariană percutană în angina stabilă:',
 ['Complicațiile majore includ infarct acut (2%), accident vascular cerebral (0,4%) și deces (1%)','Abordul radial este preferat, reducând complicațiile de punctie','DAPT (aspirină + inhibitor P2Y12) se administrează 6-12 luni după stentare','BMS au restenoză 20-30% în 6-9 luni; DES de generația a doua sunt recomandate la majoritatea','Stenturile metalice simple sunt preferate de rutină tuturor pacienților, DES fiind abandonate'],'ABCD',1082,'PCI — Complicații, stenturi și DAPT',
 'Memorarea ratelor 2%/0,4%/1% și a ferestrei DAPT 6-12 luni, cu superioritatea DES de generația a doua.',
 ['Infarct 2%, AVC 0,4%, deces 1% sunt cifrele din text.','Abordul radial reduce hematoamele, disecțiile și pseudoanevrismele.','DAPT 6-12 luni după stentare.','BMS: restenoză 20-30% la 6-9 luni; DES II superioare, recomandate la majoritatea.','DES II sunt recomandate la majoritate; BMS pot fi preferate doar dacă e nevoie de anticoagulare prelungită sau chirurgie precoce.']],
 8,'Inversează ierarhia DES versus BMS, deși textul rezervă BMS doar unor nișe (anticoagulare, chirurgie precoce).',['20-30%','6-12 luni'],[1083]),

q(71,['PCI versus CABG în boala coronariană complexă:',
 ['Mortalitatea chirurgicală a CABG este sub 1% la funcție sistolică de VS normală','Grafturile arteriale (mamare interne in situ, gastro-epiploice) funcționează mai durabil decât cele venoase','PCI este preferată în boala uni- sau bivasculară fără IVA proximală sau trunchi comun','CABG este preferat în boala trivasculară cu diabet sau SYNTAX >22','SYNTAX scăzut (0-22) contraindică atât PCI cât și CABG în stenoza de IVA proximală'],'ABCD',1083,'Revascularizare — PCI versus CABG (SYNTAX)',
 'Aplicarea pragului SYNTAX >22, a preferinței CABG în diabetul trivascular și a mortalității CABG <1%.',
 ['Mortalitatea chirurgicală <1% la FE conservată.','Arterele mamare interne și gastro-epiploice au durată mai lungă decât grafturile venoase.','PCI preferată în uni-/bivascular fără IVA sau TC.','CABG preferat în trivascular + diabet sau SYNTAX >22.','La SYNTAX 0-22, atât CABG cât și PCI pot fi folosite în IVA proximală, TC sau trivascular fără diabet.']],
 8,'Transformă fereastra SYNTAX 0-22 — unde ambele metode sunt posibile — într-o dublă contraindicație.',['SYNTAX','sub 1%'],[1084]),

q(72,['Definiția universală a infarctului și troponina înalt sensibilă:',
 ['Tipul 1 este IM spontan prin eveniment coronarian primar (eroziune/ruptură/fisură/disecție de placă)','Tipul 2 este secundar dezechilibrului ofertă/necesar (spasm, embolie, anemie, aritmii, hiper-/hipotensiune)','Tipul 4a este IM determinat de PCI, iar 4b de tromboza de stent; tipul 5 de CABG','Un rezultat <5 ng/L are valoare predictivă negativă de 99,4%; dacă primul test e negativ, se repetă la 3 ore','Tipul 3 este IM fără necroză, diagnosticat doar prin durere atipică'],'ABCD',1085,'SCA — Tipurile de IM și troponina',
 'Potrivirea tipurilor 1, 2, 4a/4b și 5 cu mecanismul și a NPV 99,4% la pragul <5 ng/L.',
 ['Tipul 1: eveniment coronarian primar pe placă.','Tipul 2: dezechilibru ofertă-necesar.','4a = PCI, 4b = tromboză de stent, 5 = CABG.','<5 ng/L: VPN 99,4%; repetare la 3 ore dacă primul test e negativ.','Tipul 3 este IM cu moarte cardiacă subită, nu absența necrozei.']],
 8,'Înlocuiește tipul 3 (moarte subită) cu un tablou de durere atipică fără necroză.',['5 ng/L','99,4%'],[1084]),

q(73,['Scorul TIMI în NSTEMI/angină instabilă punctează, printre altele:',
 ['Vârsta >75 ani cu 3 puncte, identic STEMI TIMI','Vârsta >65 ani; >3 factori de risc; stenoze >50%; aspirină în ultimele 7 zile; angină de repaus >2 episoade/24 h; modificare ST; markeri de necroză','Doar troponina, fără date clinice sau ECG','Greutatea >67 kg și întârzierea tratamentului >4 ore, ca în STEMI','Clasa Killip ca unic determinant'],'B',1085,'SCA — Scorul TIMI NSTEMI/AI',
 'Recunoașterea celor 7 itemi TIMI pentru NSTEMI, distinct de itemii TIMI STEMI.',
 ['Vârsta >75 cu 3 puncte aparține TIMI STEMI, nu NSTEMI.','Cadranul 30.35 enumeră cei 7 factori (vârstă >65, factori de risc, stenoze >50%, aspirină 7 zile, angină de repaus, ST, enzime).','Scorul combină clinic, ECG și markeri, nu troponina izolată.','Greutatea >67 kg și întârzierea >4 ore sunt itemi TIMI STEMI.','Killip intră în GRACE, nu ca unic item TIMI NSTEMI.']],
 8,'Amestecă itemii TIMI NSTEMI cu cei STEMI (greutate, delay, vârstă >75 cu 3 puncte).',['TIMI','>65 ani']),

q(74,['Conform scorului GRACE în NSTEMI, riscul intra-spitalicesc scăzut corespunde:',
 ['Unui scor >140, cu mortalitate >3%','Unui scor ≤108, cu mortalitate <1%','Unui scor 126-154, intervalul STEMI de risc mediu','Unui scor ≥200, indiferent de prezentare','Lipsei oricărei stratificări, GRACE fiind rezervat STEMI'],'B',1086,'SCA — Scorul GRACE',
 'Reținerea pragului GRACE ≤108 pentru mortalitate intra-spital <1% în NSTEMI.',
 ['>140 este riscul înalt NSTEMI intra-spital (>3%).','Cadranul 30.37: NSTEMI intra-spital, risc scăzut ≤108, mortalitate <1%.','126-154 este riscul mediu STEMI intra-spital.','≥200 nu este o categorie GRACE de NSTEMI intra-spital.','GRACE se aplică atât NSTEMI cât și STEMI, cu praguri diferite.']],
 8,'Confundă pragul NSTEMI ≤108 (<1%) cu pragul de risc înalt >140 sau cu benzile STEMI.',['108','<1']),

q(75,['Momentul coronarografiei în NSTEMI, după riscul ESC:',
 ['Risc foarte înalt (angină persistentă, IC, șoc, aritmii maligne): coronarografie <2 ore','Risc înalt (troponină în crescendo, ST dinamic, GRACE >140): în primele 24 de ore','Risc intermediar (diabet, eRFG <60, FEVS <40%, GRACE 109-140, PCI/CABG anterior): în primele 72 de ore','Risc înalt se amână la 7 zile, pentru „stabilizarea plăcii”','GRACE 109-140 impune angiografie de urgență sub 2 ore, identic șocului'],'ABC',1087,'NSTEMI — Stratificarea și timing-ul angiografiei',
 'Aplicarea ferestrelor <2 h / 24 h / 72 h în funcție de GRACE și de instabilitatea clinică.',
 ['Foarte înalt: <2 ore.','Înalt, inclusiv GRACE >140: 24 de ore.','Intermediar, inclusiv GRACE 109-140: 72 de ore.','Risc înalt nu se amână o săptămână.','GRACE 109-140 este intermediar (72 h), nu urgență de șoc.']],
 8,'Suprapune banda intermediară GRACE 109-140 peste urgența de sub 2 ore a șocului.',['<2 ore','>140']),

q(76,['Fiziopatologia STEMI și mortalitatea intra-spitalicească:',
 ['Necroza începe în 15-30 de minute de la ocluzie, întâi subendocardic, apoi transmural cu undă Q','Mortalitatea intra-spitalicească este între 6 și 14%','Reperfuzia precoce salvează miocard și reduce mortalitatea și morbiditatea','Necroza transmurală este completă în sub 5 minute, fără zonă subendocardică prealabilă','Mortalitatea intra-spital depășește 50% în STEMI necomplicat'],'ABC',1088,'STEMI — Fiziopatologie și mortalitate',
 'Reținerea ferestrei 15-30 de minute până la necroză și a mortalității intra-spital 6-14%.',
 ['Necroza în 15-30 de minute, întâi subendocardic, apoi transmural cu undă Q.','Mortalitatea intra-spital este între 6 și 14%.','Reperfuzia precoce salvează miocard și reduce mortalitatea și morbiditatea.','Primul afectat este miocardul subendocardic; transmuralul urmează pe măsură ce ischemia se prelungește.','6-14%, nu peste 50% în forma necomplicată.']],
 8,'Comprimă necroza la 5 minute sau umflă mortalitatea peste 50%, deși textul dă 15-30 min și 6-14%.',['15-30 minute','6 şi 14%']),

q(77,['Reperfuzia în STEMI:',
 ['PCI primară, cu ghid distal de ocluzie în primele 60 de minute de la prezentare, este metoda preferată în centre cu laborator','Tromboliza este indicată dacă PCI primară nu poate fi efectuată în primele 120 de minute de la diagnostic','În primele 6 ore, tromboliza poate preveni 30 de decese la 1.000 de pacienți tratați; între 7-12 ore, 20 la 1.000','După 12 ore beneficiile sunt limitate, mai ales la vârstnici, prin risc crescut de AVC','Tromboaspirația de rutină este recomandată în toate PCI primare'],'ABCD',1089,'STEMI — PCI primară și tromboliză',
 'Aplicarea ferestrelor 60 min (PCI) și 120 min (switch la liza), plus 30 versus 20 decese evitate la 1.000.',
 ['Ghidul distal în primele 60 de minute este ținta PCI primare.','Liza dacă PCI nu e posibilă în 120 de minute.','Meta-analiza: 30/1000 în 6 ore, 20/1000 între 7-12 ore.','După 12 ore beneficiul e limitat; vârstnicii au risc mai mare de AVC.','Tromboaspirația de rutină nu este recomandată.']],
 8,'Adaugă tromboaspirația de rutină, pe care textul o respinge explicit în PCI primară.',['60 de minute','120 minute'],[1088]),

q(78,['În PCI primară pentru STEMI se preferă:',
 ['Abordul radial, care reduce complicațiile arteriale și poate ameliora supraviețuirea (RIVAL, RIFLE STEACS)','Stenturile farmacologic active față de stenturile metalice simple','Aspirină plus prasugrel sau ticagrelor ca duală antiagregare','Utilizarea de rutină a inhibitorilor GP IIb/IIIa','Revascularizarea doar a leziunii culprit, completarea fiind amânată 6 luni în toate cazurile'],'ABC',1089,'STEMI — Detalii de PCI primară',
 'Recunoașterea abordului radial, a DES și a dualei aspirină+prasugrel/ticagrelor, față de GP IIb/IIIa nedevenită rutină.',
 ['RIVAL și RIFLE STEACS susțin artera radială.','DES sunt preferate față de BMS în PCI primară.','Antiagregarea preferată: aspirină plus prasugrel sau ticagrelor.','Utilizarea de rutină a inhibitorilor GP IIb/IIIa nu mai este recomandată.','Ghidurile ESC recomandă revascularizare completă în timpul spitalizării inițiale, înainte de externare.']],
 8,'Păstrează GP IIb/IIIa ca rutină — strategie abandonată — și amână completarea revascularizării 6 luni.',['artera radială','prasugrel sau ticagrelor']),

q(79,['Clasificarea Killip post-STEMI:',
 ['Clasa I: fără raluri și fără galop; clasa II: raluri pe < jumătate din baze sau galop; clasa III: raluri pe >50% din câmpuri; clasa IV: șoc cardiogen','Contraindicațiile absolute ale trombolizei includ AVC hemoragic de orice durată, AVC ischemic în ultimele 3 luni, disecție de aortă și sângerare digestivă în luna precedentă','Killip II se definește prin șoc cardiogen','AVC ischemic vechi de 5 ani este contraindicație absolută identică hemoragicului','Hipertensiunea refractară (TAS >180 mmHg) este contraindicație absolută, nu relativă'],'AB',1090,'STEMI — Killip și contraindicațiile trombolizei',
 'Fixarea celor patru clase Killip și a contraindicațiilor absolute de liza, distincte de cele relative.',
 ['Cele patru clase sunt descrise exact astfel.','Cadranul 30.41 enumeră aceste contraindicații absolute.','Șocul cardiogen este Killip IV, nu II.','AVC ischemic în ultimele 3 luni este absolut; unul vechi de 5 ani nu este listat ca atare.','TAS >180 mmHg refractară este contraindicație relativă.']],
 8,'Mută șocul din Killip IV în II și promovează o HTA relativă la rang de contraindicație absolută.',['Kil/ip IV','Disecţia de aortă']),

q(80,['Defectul septal ventricular post-STEMI:',
 ['Apare la 1-2% dintre pacienți și, fără corecție chirurgicală, mortalitatea la 12 luni poate ajunge la 92%','Este o complicație benignă, cu mortalitate sub 5% la 1 an fără intervenție','Se tratează doar cu diuretice orale, balonul de contrapulsație fiind contraindicat','Apare la peste 30% dintre STEMI reperfuzate precoce','Diagnosticul se pune pe radiografia de torace, fără ecografie'],'A',1090,'Complicațiile STEMI — Defect septal ventricular',
 'Reținerea incidenței 1-2% și a mortalității 92% la 12 luni fără chirurgie.',
 ['Textul: 1-2% dintre STEMI; mortalitate 92% la 12 luni în lipsa chirurgiei.','Mortalitatea este foarte mare, nu benignă.','IABP și angiografia pot permite diagnosticul complet înaintea chirurgiei.','Se asociază cu fibrinoliză tardivă sau ineficace, nu cu reperfuzia precoce.','Fig. 30.72 și contextul clinic/eco ghidează diagnosticul, nu radiografia izolată.']],
 8,'Transformă o complicație cu mortalitate 92% într-o evoluție „benignă”, inversând prognosticul real.',['1-2%','92%']),

q(81,['Complicațiile mecanice și aritmice precoce ale STEMI:',
 ['Insuficiența mitrală severă are trei mecanisme; ETE este necesară pentru etiologie','Ruptura de mușchi papilar produce edem pulmonar acut și șoc, cu indicație de IABP, coronarografie și chirurgie precoce','Potasiul seric trebuie menținut peste 4,5 mmol/L; TV/FV incesantă poate răspunde la magneziu 8 mmol în 15 minute','Ruptura de perete liber este de obicei bine tolerată, fără risc de disociație electromecanică','Bradiaritmiile nu se tratează cu atropină, ci doar cu stimulare permanentă imediată'],'ABC',1091,'STEMI — IM mitrală, ruptură și aritmii',
 'Diferențierea celor trei mecanisme de IM mitrală și a țintelor K+ >4,5 mmol/L și Mg 8 mmol.',
 ['Trei mecanisme (dilatare de inel, disfuncție de papilar inferior, ruptură); ETE precizează etiologia.','Ruptura de papilar: EPA + șoc; IABP, coronarografie și chirurgie precoce.','K+ >4,5 mmol/L; magneziu IV 8 mmol în 15 minute pentru TV/FV incesantă.','Ruptura de perete liber este cel mai frecvent fatală, prin disociație electromecanică.','Bradiaritmiile se tratează inițial cu atropină 0,5 mg i.v., repetată până la șase ori în 4 ore.']],
 8,'Minimizează ruptura de perete liber — complicație de obicei fatală — și interzice atropina, primul pas al bradiaritmiei.',['4,5 mmol/L','8 mmol/L']),

q(82,['După stentare la un pacient cu FA permanentă, strategia antithrombotică depinde de HAS-BLED:',
 ['HAS-BLED 0-2: triplă terapie 6 luni, apoi dublă (antiagregant + AVK/DOAC)','HAS-BLED >2: triplă 4 săptămâni, apoi dublă încă 11 luni','HAS-BLED >2: triplă terapie 12 luni, fără de-escaladare','Antagonistul de aldosteron se evită dacă FEVS <40% și există semne de IC','Ținta LDL post-IMA este <3,5 mmol/L, nu <1,8 mmol/L'],'AB',1091,'Post-SCA — Tripla terapie și prevenție secundară',
 'Aplicarea ferestrelor 6 luni versus 4 săptămâni de triplă terapie după HAS-BLED.',
 ['HAS-BLED 0-2: triplă 6 luni, apoi dublă.','HAS-BLED >2: triplă 4 săptămâni, apoi dublă 11 luni.','De-escaladarea este explicită, nu tripla continuă 12 luni la risc hemoragic înalt.','Antagonistul de aldosteron este indicat dacă există semne de IC și FEVS <40%, cu creatinine și K controlate.','Ținta LDL este <1,8 mmol/L cu statină de potență înaltă.']],
 8,'Prelungește tripla terapie la 12 luni tocmai la HAS-BLED înalt, unde textul o scurtează la 4 săptămâni.',['HAS-BLED','<1.8 mmol/L']),

q(83,['Stenoza mitrală reumatismală se caracterizează prin:',
 ['Aria normală 4-6 cm²; stenoza severă este definită sub 1 cm²','Afectează mai frecvent femeile decât bărbații','Simptomele apar de obicei când aria devine <2 cm²','În Europa, intervalul de la RAA la stenoză severă este de câteva decenii; în țările mai puțin dezvoltate, stenoză severă de la 10-20 de ani','Aria normală este 1 cm², iar stenoza severă sub 4 cm²'],'ABCD',1092,'Stenoza mitrală — Arie valvulară și epidemiologie',
 'Aplicarea pragurilor 4-6 cm² (normal), <2 cm² (simptome) și <1 cm² (sever) și a diferenței geografice de evoluție.',
 ['Orificiul normal 4-6 cm²; sever <1 cm².','Afectează mai frecvent femeile.','Simptomele apar de obicei la arie <2 cm².','Europa: decenii de la RAA; țări cu venituri mici-medii: stenoză severă la 10-20 de ani.','Valorile sunt inversate față de text.']],
 8,'Inversează ariile normal/sever (4-6 versus <1), capcana numerică centrală a stenozei mitrale.',['4-6 cm2','sub 1 cm2']),

q(84,['Semnele auscultatorii și ECG în stenoza mitrală:',
 ['Zgomot 1 întărit dacă valvele sunt mobile, urmat de clacment de deschidere și uruitură diastolică la apex, în decubit lateral stâng, în expir','Accentuarea presistolică apare la pacienții în ritm sinusal, prin contracție atrială stângă','Suflul Graham-Steell este uruitura diastolică pulmonară a regurgitării pulmonare din hipertensiunea pulmonară','Unda P bifidă (P mitral) reflectă activarea întârziată a atriului stâng','Zgomotul 1 este constant diminuat, chiar la valve mobile necicatrizate'],'ABCD',1093,'Stenoza mitrală — Auscultație și P mitral',
 'Reconstituirea secvenței S1 intens – clacment – uruitură, a accentuării presistolice și a suflului Graham-Steell.',
 ['S1 întărit la valve mobile, clacment, uruitură la apex în DDS, în expir.','Accentuare presistolică în sinus, prin contracție atrială.','Graham-Steell: suflu diastolic pulmonar al regurgitării pulmonare din HTP.','P bifidă prin activare întârziată a AS.','S1 este întărit dacă valvele sunt mobile; diminuarea apare la calcificare.']],
 8,'Inversează intensitatea S1 la valvele mobile, semnul clasic al stenozei mitrale încă „pliabile”.',['clacment de deschidere','Graham-Steell'],[1092]),

q(85,['La evaluarea ecografică, stenoza mitrală severă corespunde unui timp de înjumătățire a presiunii (PHT):',
 ['40-70 ms','71-139 ms','140-219 ms','Peste 219 ms','Sub 40 ms, identic valvei normale'],'D',1094,'Stenoza mitrală — Cadranul 30.42 (PHT)',
 'Reținerea PHT >219 ms (și arie <1,0 cm²) ca prag de stenoză mitrală severă.',
 ['40-70 ms este intervalul normal.','71-139 ms corespunde formei ușoare.','140-219 ms este forma moderată.','Cadranul 30.42: PHT >219 ms, gradient mediu >10 mmHg, arie <1,0 cm² = severă.','Sub 40 ms nu este categoria de severitate.']],
 8,'Cele patru benzi PHT din același tabel sunt aproape consecutive; doar >219 ms este severă.',['>219','<1,0']),

q(86,['Indicațiile chirurgicale ESC în regurgitarea mitrală severă includ:',
 ['Pacienți simptomatici cu FEVS >30% și diametru telediastolic al VS <55 mm','Asimptomatici cu disfuncție de VS (diametru telesistolic >45 mm și/sau FEVS <60%)','Asimptomatici cu FE prezervată dacă există FA și/sau hipertensiune pulmonară','Urmărire conservatoare nelimitată la regurgitarea severă simptomatică cu FE 55%','MitraClip-ul înlocuiește chirurgia la toți candidații operabili'],'ABC',1097,'Regurgitarea mitrală — Indicații chirurgicale ESC',
 'Aplicarea pragurilor FEVS >30%/LVEDD <55 mm la simptomatici și LVESD >45 mm sau FEVS <60% la asimptomatici.',
 ['ESC: simptomatici cu FEVS >30% și DTD <55 mm.','Asimptomatici cu DTS >45 mm și/sau FEVS <60%.','FA și/sau HTP la asimptomatici cu FE prezervată justifică luarea în considerare.','RM severă simptomatică are indicație chirurgicală, nu urmărire nelimitată.','MitraClip este o opțiune la cei neeligibili chirurgical, nu un substitut universal.']],
 8,'Amână chirurgia la simptomaticul cu FE 55% — tocmai populația cu indicație clară.',['>45 mm','FEVS <60%']),

q(87,['Prolapsul de valvă mitrală (boala Barlow) și bicuspidia aortică:',
 ['Barlow: exces de țesut, inel dilatat, cordaje alungite, degenerescență mixomatoasă; mai frecvent la femei tinere, posibil familial, asociat Marfan/Ehlers-Danlos','Bicuspidia aortică afectează 1-2% dintre nou-născuți; circa 9% din cazuri au transmitere familială și se poate asocia cu coarctație, dilatare de rădăcină și disecție','Barlow este mai frecvent la bărbații vârstnici decât la femeile tinere','Bicuspidia este o anomalie rar familială, sub 0,1% din nou-născuți','BAVC (valva calcificată a vârstnicului) este o leziune congenitală, nu un proces inflamator cu macrofage și limfocite T'],'AB',1097,'Prolaps mitral (Barlow) și bicuspidie aortică',
 'Contrastul Barlow (femei tinere, mixomatos) versus bicuspidia 1-2% cu 9% familial și risc de coarctație/disecție.',
 ['Descrierea histologică și epidemiologică a bolii Barlow este explicită.','BA 1-2% din nou-născuți, 9% familială, asocieri aortice.','Textul: mai des la femei tinere decât la bărbați sau femei în vârstă.','1-2% este cea mai frecventă anomalie congenitală, nu 0,1%.','BAVC este proces inflamator al vârstnicului, cu macrofage și limfocite T, nu o malformație.']],
 8,'Inversează sexul/vârsta Barlow și reduce bicuspidia de la 1-2% la o raritate de 0,1%.',['1-2%','boală Barlow']),

q(88,['Stenoza aortică severă la ecografie (Cadranul 30.43) și prognosticul după simptome:',
 ['Velocitate maximă >4,0 m/s, gradient maxim >64 mmHg, gradient mediu >40 mmHg, arie <1,0 cm²','Din momentul simptomelor, decesul survine în medie la 2-3 ani fără corecție','Simptomele (sincopă de efort, angină, dispnee) apar când orificiul scade la circa o treime din normal','Funcția sistolică de VS este de cele mai multe ori prezervată','Velocitatea >2,0 m/s definește deja stenoza critică, cu arie >2,0 cm²'],'ABCD',1098,'Stenoza aortică — Severitate eco și prognostic',
 'Aplicarea pragurilor eco de severitate și a ferestrei prognostice 2-3 ani de la simptome.',
 ['Cadranul 30.43: Vmax >4,0, Gmax >64, Gmed >40, AVA <1,0.','Prognostic rezervat: deces în medie la 2-3 ani fără corecție.','Simptomele la reducerea orificiului la o treime.','Funcția sistolică este de cele mai multe ori prezervată.','Vmax >2,0 m/s este încă în banda ușoară (1,7-2,9); aria >2,0 este normală.']],
 8,'Folosește pragul de stenoză ușoară (≈2 m/s) ca „critic”, inversând tabelul 30.43.',['>4,0','2-3 ani'],[1099]),

q(89,['Implantarea transcateter a valvei aortice (TAVI) s-a dovedit:',
 ['De succes în 86% din cazuri, cu mortalitate periprocedurală 2% și la 30 de zile 12%','Ineficace (succes sub 20%) și cu mortalitate periprocedurală de 40%','Echivalentă valvuloplastiei cu balon la adult, ca soluție definitivă','Contraindicată la pacienții inoperabili, fiind rezervată tinerilor cu valvă necalcificată','Identică valvulotomiei chirurgicale a copilului, ca punte de zeci de ani'],'A',1099,'Stenoza aortică — TAVI',
 'Reținerea triadei 86% succes, 2% mortalitate periprocedurală și 12% la 30 de zile.',
 ['Textul: succes 86%, mortalitate periprocedurală 2%, la 30 de zile 12%.','Cifrele 20%/40% nu apar.','Valvuloplastia cu balon la adult are rezultate slabe; TAVI este alternativa inoperabililor.','TAVI este tocmai pentru cei la care nu se poate interveni chirurgical.','Valvulotomia copilului este temporară; TAVI este o alternativă a chirurgiei clasice la inoperabili.']],
 8,'Înlocuiește 86/2/12 cu un eșec de 20/40, ordine de mărime alăturate dar false.',['86%','12%']),

q(90,['Semnele circulației hiperdinamice în regurgitarea aortică includ:',
 ['Semnul Quincke — pulsații capilare în patul unghial','Semnul de Musset — mișcarea capului cu fiecare bătaie','Semnul Duroziez — suflu continuu „du-te vino” pe femurale comprimate distal','Uruitura Austin Flint — suflu mezodiastolic apical prin impedarea cuspei mitrale anterioare','Șoc apexian nedeplasat și susținut, identic stenozei aortice'],'ABCD',1100,'Regurgitarea aortică — Semne periferice',
 'Recunoașterea semnelor Quincke, de Musset, Duroziez și a uruiturii Austin Flint, distincte de apexul nedeplasat al stenozei.',
 ['Quincke: pulsații unghiale.','de Musset: mișcarea capului.','Duroziez: suflu continuu femoral la comprimare distală, semn de RA severă.','Austin Flint: jetul împiedică deschiderea cuspei mitrale anterioare.','Șocul apexian în RA este hiperdinamic, deplasat inferior și lateral; nedeplasat/susținut este al stenozei.']],
 8,'Atribuie regurgitării apexul nedeplasat al stenozei aortice, semnul palpator clasic de confuzie SA/RA.',['Quincke','Austin Flint']),

q(91,['Valva tricuspidă și regurgitarea pulmonară:',
 ['Stenoza tricuspidiană este mai frecventă la femei, de obicei reumatică și asociată mitralei/aorticei; poate apărea și în carcinoid','Regurgitarea tricuspidiană funcțională dispare de obicei după tratamentul medical al cauzei de dilatare a cordului drept','Suflul Graham Steell al regurgitării pulmonare este protodiastolic, accentuat în inspir, dificil de diferențiat de regurgitarea aortică','TR organică a consumatorului i.v. cu endocardită impune de la început proteză mecanică, fără excizia valvei','ST izolată este cea mai frecventă valvulopatie unică a adultului'],'ABC',1101,'Valva tricuspidă și suflul Graham Steell',
 'Diferențierea ST reumatică/carcinoidă de TR funcțională reversibilă și de suflul Graham Steell inspirator.',
 ['ST: femei, reumatism, asociere mitrală/aortică, carcinoid.','TR funcțională dispare de obicei după tratamentul medicamentos.','Graham Steell: protodiastolic SICS 2-4, accentuat în inspir, greu de deosebit de RA.','La CDIV cu endocardită tricuspidă se recomandă îndepărtarea chirurgicală a valvei pentru eradicarea infecției, de obicei bine tolerată pe termen scurt.','ST este rară și aproape nu se întâlnește ca leziune izolată.']],
 8,'Înlocuiește excizia valvei infectate a CDIV — strategie citată explicit — cu protezarea mecanică de primă intenție.',['Graham Steell','sindromului carcinoid'],[1102]),

q(92,['Anticoagularea protezelor valvulare mecanice:',
 ['Valve slab trombogene (Carbomedics aortic, Medtronic Hall, St Jude fără Silzone): INR 2,5 fără factori adiționali și 3,0 cu factori','Valve înalt trombogene (Lillehei-Kaster, Omniscience, Starr-Edwards): INR 3,5 fără factori și 4,0 cu factori','Nu există indicație pentru DOAC la protezele valvulare','Biologicele se anticoagulează pe viață la INR 4,0, identic Starr-Edwards','Întreruperea anticoagulării pentru extracție dentară se face cu 5 zile înainte, ca la chirurgia majoră'],'ABC',1103,'Proteze valvulare — INR țintă și DOAC',
 'Aplicarea treptelor INR 2,5/3,0 versus 3,5/4,0 după trombogenitate și a absenței indicației DOAC.',
 ['Slab trombogene: 2,5 fără factori, 3,0 cu factori.','Înalt trombogene: 3,5 fără factori, 4,0 cu factori.','Nu există indicație pentru DOAC în cazul protezelor valvulare.','Biologicele: anticoagulare limitată (ESC 3 luni, INR 2,5) sau aspirină 75-100 mg, apoi întrerupere dacă nu persistă alt risc.','Pentru extracții dentare și endoscopie diagnostică, anticoagularea nu trebuie întreruptă; INR țintă redus la 2,0.']],
 8,'Pune biologicul la INR 4,0 pe viață și tratează extracția dentară ca o chirurgie majoră cu întrerupere de 5 zile.',['INR 2,5','DOAC'],[1102]),

q(93,['Incidența anuală a endocarditei infecțioase în Marea Britanie este de circa:',
 ['6-7/100.000, iar fără tratament mortalitatea se apropie de 100%','1/1.000.000, cu mortalitate spontană sub 5%','50% din populația adultă, ca colonizare valvulară','Identică gripei sezoniere, fără risc vital','0,1/100.000, limitată la proteze'],'A',1103,'Endocardita infecțioasă — Epidemiologie',
 'Reținerea incidenței 6-7/100.000 și a mortalității aproape complete fără tratament.',
 ['Textul: 6-7/100.000 în UK, mai mare în țările în curs de dezvoltare; fără tratament, mortalitatea se apropie de 100%.','Incidența și mortalitatea spontană sunt net superioare acestor valori.','Nu este o colonizare de masă.','Morbiditatea și mortalitatea rămân mari chiar cu tratament.','Nu este limitată la proteze; incidența citată este populațională.']],
 8,'Subestimează cu două ordine de mărime o infecție a cărei mortalitate netratată se apropie de 100%.',['6-7 /100.000','100%']),

q(94,['Criteriile Duke modificate și endocardita pe proteză:',
 ['Diagnosticul clinic cert cere 2 criterii majore, sau 1 major + 3 minore, sau 5 minore','Hemoculturi persistente pozitive (același germen la ≥12 ore, sau 3/≥4 seturi) sunt criteriu major','Endocardita precoce pe proteză survine în primele 60 de zile, de obicei stafilococ nosocomial, cu prognostic rezervat','Endocardita tardivă, după 60 de zile, este mai degrabă comunitară: viridans 50-70%, S. aureus 25%','Un singur set de hemoculturi dintr-un cateter central stabilește criteriul major microbiologic'],'ABCD',1104,'Endocardita — Duke și proteza precoce/tardivă',
 'Aplicarea combinațiilor Duke și a pragului de 60 de zile care separă endocardita precoce stafilococică de cea tardivă streptococică.',
 ['Două majore, sau un major și trei minore, sau cinci minore.','Hemoculturile persistente sunt criteriu major.','Precoce: primele 60 de zile, S. aureus/S. epidermidis, prognostic rezervat.','Tardivă: după 60 de zile, viridans 50-70%, S. aureus 25%.','Criteriul major cere două hemoculturi tipice fără focar primar sau persistență pe multiple seturi, nu un singur set de pe cateter.']],
 8,'Reduce bacteriologia Duke la un singur set de pe cateter, tocmai scenariul de contaminare.',['60 de zile','HACEK']),

q(95,['Frecvența aproximativă a manifestărilor în endocardită (Cadranul 30.46):',
 ['Pirexie circa 90%; suflu circa 90%; stare generală alterată circa 95%','Degete hipocratice circa 10%; noduli Osler circa 15%; pete Roth circa 5%','Hematurie circa 70%; splenomegalie circa 40%; emboli cerebrali circa 20%','Insuficiență cardiacă circa 50%; artralgii circa 25%','Pete Roth la 90% și hipocratism la 2% dintre pacienți'],'ABCD',1105,'Endocardita — Tablou clinic (procente)',
 'Memorarea ordinelor de mărime: febră/suflu ~90%, hipocratism 10%, Roth 5%, hematurie 70%.',
 ['Pirexie 90%, suflu 90%, stare alterată 95%.','Hipocratism 10%, Osler 15%, Roth 5%.','Hematurie 70%, splenomegalie 40%, emboli cerebrali 20%.','IC 50%, artralgii 25%.','Roth este 5%, nu 90%; hipocratismul este 10%, nu 2%.']],
 8,'Schimbă petele Roth (5%) cu febra (90%), două procente din același tabel.',['90','Pete Roth']),

q(96,['Profilaxia antibiotică ESC (2015) a endocarditei se adresează grupurilor cu risc major:',
 ['Proteze valvulare (inclusiv TAVI) sau material intracardiac de reparare','Endocardită infecțioasă în antecedente','Congenitale cianogene necorectate sau cu șunturi paliative; după corecție completă, risc crescut 6 luni','Toți pacienții cu stenoza mitrală ușoară, la orice procedură digestivă','AHA exclude transplantul cardiac cu valvulopatie din grupul de risc înalt, contrar ESC'],'ABC',1106,'Endocardita — Profilaxie ESC',
 'Recunoașterea celor trei grupuri ESC de risc major și a ferestrei de 6 luni post-corecție congenitală.',
 ['Protezele, inclusiv transcateter, și materialul de reparare.','Antecedentele de endocardită.','Cianogene necorectate/șunturi; 6 luni după corecție completă.','ESC limitează profilaxia la proceduri stomatologice cu manipulare gingivală/periapicală/mucoasă, la grupurile de risc major, nu la SM ușoară la orice gest digestiv.','AHA consideră că și transplantul cu boală valvulară trebuie socotit risc înalt.']],
 8,'Extinde profilaxia la stenoza mitrală ușoară și orice gest digestiv, contrar restricției ESC la stomatologie de risc.',['proteze valvulare','6 luni']),

q(97,['Miocardita acută — diagnostic și evoluție:',
 ['Serologia virală de obicei nu este utilă; VSH, PCR, troponina și CK sunt frecvent crescute în faza acută','IRM: edem pe T2 și captare neuniformă de gadoliniu; biopsia este gold standard, rezervată formelor fulminante','Sportul se evită 6 luni; majoritatea cazurilor se vindecă în câteva săptămâni','Miocardita cu celule gigante are evoluție rapid progresivă, prognostic infaust, și se tratează imunosupresor','Serologia virală înlocuiește IRM-ul ca test de confirmare de primă linie'],'ABCD',1119,'Bolile miocardului — Miocardita acută',
 'Recunoașterea inutilității serologiei virale, a IRM de confirmare și a ferestrei de 6 luni fără sport.',
 ['Serologia virală de obicei nu este utilă; markerii inflamatori și de necroză cresc.','IRM confirmă; biopsia e gold standard la fulminant/agravare.','Repaus în acut; sport evitat 6 luni; vindecare în săptămâni la majoritate.','Celule gigante: progresie rapidă, prognostic infaust, imunosupresie.','Serologia nu înlocuiește IRM-ul, recomandat pentru confirmare.']],
 8,'Pune serologia virală — explicit neutilă — în locul IRM-ului de confirmare.',['6 luni','celule gigante']),

q(98,['Cardiomiopatia hipertrofică:',
 ['Afectează 1 din 500 de locuitori și este cea mai frecventă cauză de moarte subită cardiacă la tineri','Cele mai frecvente mutații sunt MYH7 (lanțul greu al β-miozinei) și MYBPC3 (proteina C de legare a miozinei)','Circa 25% au obstrucție dinamică a tractului de ejecție, prin HVS, SAM mitral și ejecție rapidă','Mutațiile troponinei T se asociază cu hipertrofie marcată, dar risc scăzut de moarte subită','Formele de depozit (Danon, Pompe, Fabry) sunt ușor de distins ecografic de CMH sarcomerică'],'ABC',1119,'Cardiomiopatia hipertrofică — Genetică și LVOTO',
 'Reținerea prevalenței 1/500, a genelor MYH7/MYBPC3 și a obstrucției dinamice la 25%.',
 ['1 din 500; cea mai frecventă cauză de MSC la tineri.','MYH7 și MYBPC3 sunt cele mai frecvente.','Aproximativ 25% au obstrucție dinamică (HVS + SAM + ejecție rapidă).','Troponina T: hipertrofie ușoară, dar risc crescut de moarte subită; hipertrofia marcată e mai degrabă MYH7.','Bolile de depozit sunt dificil de diferențiat ecografic de CMH ereditară.']],
 8,'Inversează fenotipul troponinei T (hipertrofie ușoară, risc înalt) cu cel al MYH7 (hipertrofie marcată).',['1 din 500','25%'],[1120]),

q(99,['Factorii de risc de moarte subită în CMH includ:',
 ['Grosime parietală >30 mm','Istoric familial de MSC sub 50 de ani','TV nesusținută la Holter; sincopă inexplicabilă; răspuns TA plat sau hipotensiv la efort','Suflu care scade în Valsalva și crește la ghemuit','ICD se discută de obicei la un singur factor minor, amiodarona fiind superioară ICD la risc înalt'],'ABC',1120,'CMH — Risc de moarte subită și suflu dinamic',
 'Listarea celor cinci markeri de risc și a regulii ≥2 factori pentru evaluare ICD.',
 ['HVS masivă >30 mm.','Istoric familial de MSC <50 ani.','TVNS, sincopă inexplicabilă, răspuns TA anormal la efort.','Suflul de obstrucție se amplifică la Valsalva/ortostatism (scade postsarcina) și se diminuează la ghemuit.','≥2 factori: evaluare pentru ICD; la risc mai mic, amiodarona este alternativă, nu superioară ICD-ului de risc înalt.']],
 8,'Inversează dinamica suflului la Valsalva/ghemuit, manevra clasică de obstrucție dinamică.',['>30 mm','Valsalva']),

q(100,['Identificați afirmația corectă privind investigațiile în cardiomiopatia aritmogenă:',
 ['ECG-ul este constant cu BRS și unde Q inferioare, fără unde epsilon','Undele epsilon (potențiale mici la sfârșitul QRS) și inversarea T în V1-V3 pot fi prezente; beta-blocantele sunt prima linie în aritmiile neamenințătoare','Ecocardiografia este suficientă în toate stadiile, IRM-ul neaducând informații despre infiltrația fibro-grăsoasă','Amiodarona este contraindicată, iar ICD-ul nu are loc în aritmiile refractare','Boala se manifestă doar prin insuficiență de VS, fără aritmii'],'B',1122,'Cardiomiopatia aritmogenă — ECG și tratament',
 'Recunoașterea undelor epsilon/T inversate precordiale drepte și a beta-blocantului ca primă linie.',
 ['ECG-ul este de obicei normal; pot apărea T inversate în V1-V3, unde epsilon, BRD.','Undele epsilon și T inversate în V1-V3 sunt descrise; beta-blocantele sunt prima linie pentru aritmii neamenințătoare.','Eco poate fi normală; IRM evaluează VD mai acurat și poate arăta infiltrație fibro-grăsoasă.','Amiodarona sau sotalolul se folosesc în aritmii simptomatice; ICD în cele refractare/amenințătoare.','Aritmiile și riscul de moarte subită domină stadiile precoce.']],
 8,'Neagă unda epsilon — semnul ECG eponim — și inversează cronologia aritmii versus insuficiență.',['unde epsilon','V1-'],[1121]),

q(101,['Noncompactarea de ventricul stâng și cardiomiopatia restrictivă:',
 ['NCVS: aspect spongiform apical; diagnostic eco/IRM/angiografic; evoluție cu IC, tromboembolism, aritmii și moarte subită','Restrictiva primară: volume ventriculare normale/scăzute, dilatare biatrială, pereți și valve normale, umplere restrictivă, FE aproape normală','Amiloidoza: miocard „strălucitor”, aspect de „șine de tramvai” în mod M; biopsia este frecvent utilă, spre deosebire de alte cardiomiopatii','NCVS afectează predominant bazele ventriculului drept, nu apexul stâng','În restrictivă, PVJ este plat, fără Friedreich sau Kussmaul'],'ABC',1123,'Noncompactare VS și cardiomiopatie restrictivă',
 'Recunoașterea fenotipului spongiform apical și a profilului restrictiv cu semne de umplere (Friedreich, Kussmaul) și a aspectului de amiloid.',
 ['NCVS: spongiform, predominant apical; IC, embolii, aritmii, MSC.','Restrictiva: VS/VD nedilatate, biatrială, pereți normali, umplere alterată, FE aproape normală.','Amiloid: strălucitor, „șine/linii de tramvai”; biopsia e utilă.','NCVS afectează predominant segmentele apicale ale VS.','PVJ accentuat, colaps diastolic (Friedreich) și Kussmaul sunt descrise.']],
 8,'Mută noncompactarea de la apexul stâng la bazele drepte și anulează semnele venoase clasice ale restrictivei.',['şine de tramvai','spongiform'],[1124]),

q(102,['Cardiomiopatiile dobândite Tako-tsubo și peripartum:',
 ['Tako-tsubo: durere și dispnee, ECG și biomarkeri ca în IM, coronare neobstruate, akinezie medio-apicală cu baze prezervate','Este mai frecventă la femeile de vârstă medie; recuperare de obicei în 4-6 săptămâni, cu posibile recurențe','Peripartum: ultimul trimestru sau primele 5 luni postpartum; mai frecventă la obeze, multipare, >30 de ani, cu preeclampsie','Aproape jumătate recuperează funcția în 6 luni','Tako-tsubo este mai frecventă la bărbații tineri, cu recuperare în 24 de ore și fără recurențe'],'ABCD',1124,'Tako-tsubo și cardiomiopatia peripartum',
 'Potrivirea terenului (femei de vârstă medie versus multipare >30 ani) și a ferestrelor de recuperare 4-6 săptămâni / 6 luni.',
 ['Prezentare de SCA cu coronare libere și balonizare apicală.','Femei de vârstă medie; recuperare 4-6 săptămâni; recurențe posibile.','Ultimul trimestru sau 5 luni postpartum; obezitate, multiparitate, >30 ani, preeclampsie.','Aproape jumătate recuperează în 6 luni.','Terenul și evoluția descrise sunt ale femeii de vârstă medie, nu ale bărbatului tânăr cu vindecare într-o zi.']],
 8,'Mută Tako-tsubo pe bărbatul tânăr cu vindecare într-o zi, inversând epidemiologia și cinetica de recuperare.',['Tako-tsubo','4-6 săptămâni']),

q(103,['Pericardita acută:',
 ['Poate explica 5% din prezentările de urgență pentru durere toracică; este mai frecventă la bărbați tineri','Diagnosticul clinic cere două din patru: durere, frecătură, ST concav în sus (șa) cu PR coborât, revărsat','Aspirină 750-1.000 mg ×3/zi sau ibuprofen 600-800 mg ×3/zi, 1-2 săptămâni, plus colchicină 0,5 mg ×2/zi, 3 luni','Corticosteroizii se rezervă etiologiei imune, fiind asociați cu risc crescut de recurență','Atleții pot relua efortul în 48 de ore, fără a aștepta normalizarea markerilor'],'ABCD',1125,'Pericardita acută — Diagnostic și tratament',
 'Aplicarea regulii 2 din 4, a dozelor de AINS+colchicină și a rezervei de steroizi, plus interdicția sportului.',
 ['5% din durerile toracice de urgență; predominanță masculină tânără.','Două din cele patru criterii susțin diagnosticul.','Dozele și durata AINS plus colchicina 3 luni sunt explicite.','Steroiizii: etiologii imune; risc crescut de recurență.','Atleții evită efortul cel puțin 3 luni; se limitează activitatea până la normalizarea markerilor.']],
 8,'Comprimă interdicția de efort a atleților de la 3 luni la 48 de ore, contrar textului.',['5%','colchicină']),

q(104,['Pericardita incesantă, cronică și tuberculoasă:',
 ['Incesantă: recurență în până la 6 săptămâni; cronică: durată >3 luni','În țările în curs de dezvoltare, TB poate depăși 50% din pericardite, iar la HIV peste 90%','Sindromul Dressler este o pericardită autoimună tardivă post-infarct','Prednisolonul 60 mg, 2-6 săptămâni, se asociază tratamentului antituberculos','Pericardita TB reprezintă >50% din cazuri în țările dezvoltate, Dressler-ul fiind o formă virală primară'],'ABCD',1126,'Pericardită incesantă, TB și Dressler',
 'Diferențierea incesantă (≤6 săptămâni) versus cronică (>3 luni) și a ponderii TB >50%/>90% HIV în țările în dezvoltare.',
 ['Incesantă până la 6 săptămâni; cronică >3 luni.','TB: rar <5% în țări dezvoltate; >50% în dezvoltare; >90% la HIV.','Dressler: reacție autoimună tardivă post-IM.','Prednisolon 60 mg zilnic, 2-6 săptămâni, plus tratamentul TB.','În țările dezvoltate TB este <5%; Dressler este post-injurie, nu virală primară.']],
 8,'Mută ponderea TB >50% din țările în dezvoltare în Occident, unde textul o plasează sub 5%.',['6 săptămâni','Dressler']),

q(105,['Revărsatul pericardic cu tamponadă se caracterizează prin:',
 ['QRS microvoltate (<0,5 mV în derivațiile membrelor), tahicardie sinusală și posibilă alternanță electrică','Radiografie: cord globulos/„în pară”, cu vene pulmonare tipic nedilatate','Eco: colabare telediastolică a AD, protodiastolică a VD, VCI dilatată cu colaps inspirator <50%','Semnul lui Ewart: matitate sub unghiul scapulei stângi prin comprimarea bazei pulmonare stângi','Cord mic, cu vene pulmonare foarte dilatate, ca în constricție'],'ABCD',1127,'Revărsat pericardic și tamponadă',
 'Reunirea alternanței electrice, a siluetei „în pară”, a colabării AD/VD și a semnului Ewart.',
 ['Microvoltaj <0,5 mV, tahicardie, alternanță electrică.','Cord globulos/pară, vene pulmonare nedilatate.','Colabare AD telediastolică, VD protodiastolică, VCI cu colaps <50%.','Ewart: matitate sub unghiul scapulei stângi.','Cordul mic cu constricție; tamponada produce siluetă mărită, globuloasă.']],
 8,'Atribuie tamponadei cordul mic al constricției, inversând perechea radiologică clasică.',['semnul lui Ewart','alternanţă electrică'],[1126]),

q(106,['Precizați enunțul corect despre investigațiile din pericardita constrictivă:',
 ['Calcificări pericardice pot fi prezente în până la 50% din cazuri, dar un pericard calcificat nu înseamnă constricție','Radiografia arată constant un cord globulos, ca în tamponadă','ECG-ul este normal, fără microvoltaj','Cateterismul arată presiuni telediastolice inegale între VS și VD','Pericardectomia se amână până la atrofie miocardică maximă, pentru a reduce riscul'],'A',1127,'Pericardita constrictivă — Imagistică și cateterism',
 'Reținerea calcificărilor la până la 50% și a faptului că ele nu echivalează constricția, plus egalizarea presiunilor telediastolice.',
 ['Calcifierile pot fi prezente în până la 50%; un pericard calcificat nu înseamnă constricție.','Radiografia: cord relativ mic în context de IC; tamponada dă siluetă globuloasă.','ECG: QRS microvoltate cu T aplatizate sau inversate.','Cateterismul: presiuni telediastolice egale în VS și VD.','Pericardectomia precoce este recomandată înainte de constricție severă și atrofie, procedura fiind riscantă tocmai din cauza atrofiei.']],
 8,'Transformă calcificarea într-un echivalent de constricție și amână chirurgia până la atrofia care crește riscul.',['50%','telediastolice']),

q(107,['În constricția tuberculoasă, strategia chirurgicală este:',
 ['Dacă există calcificări (afectare cronică), pericardectomie precoce sub tratament antituberculos','Fără calcificări, se încearcă mai întâi cura antituberculoasă; dacă statusul e staționar sau se deteriorează după 4-6 săptămâni, se indică pericardectomia','Pericardectomia imediată, fără antituberculoase, la orice caz fără calcificări','Așteptare 12 luni de terapie, indiferent de hemodinamică, înaintea oricărei chirurgii','Calcificarea contraindică pericardectomia, fiind un semn de vindecare'],'AB',1127,'Pericardita constrictivă — Momentul pericardectomiei în TB',
 'Diferențierea cazului calcificat (chirurgie precoce sub tuberculostatice) de cel necalcificat (probă terapeutică 4-6 săptămâni).',
 ['Cu calcificări: pericardectomie precoce sub medicație antituberculoasă.','Fără calcificări: tratament medical întâi; chirurgie dacă nu se ameliorează în 4-6 săptămâni.','Fără calcificări nu se operează imediat, fără tratament etiologic.','Pragul citat este 4-6 săptămâni, nu 12 luni.','Calcificarea marchează cronicitatea și orientează spre chirurgie precoce, nu contraindică.']],
 8,'Inversează rolul calcificării: din argument de chirurgie precoce în „semn de vindecare” care ar interzice operația.',['4-6 săptămâni','Calcificărilor pericardice']),

q(108,['Febra persistentă în endocardita infecțioasă, după 48 de ore de antibiotic adecvat, impune căutarea:',
 ['Extensiei paravalvulare și a unui posibil abces','Reacției adverse medicamentoase (febra cedează la întrerupere)','Infecției nosocomiale (loc de puncție, urinar) sau a emboliei pulmonare','Schimbării empirice imediate a schemei, chiar cu culturi negative și fără suspiciune de alergie','Colaborării cu microbiologia și a consultului de chirurgie cardio-vasculară, rezistența nouă fiind rară'],'ABCE',1106,'Endocardita — Febra persistentă',
 'Interpretarea febrei după 48 de ore ca abces, alergie, infecție nosocomială sau embolie, nu ca semnal de schimbare empirică a antibioticului.',
 ['Abcesul paravalvular este prima preocupare.','Reacția adversă: febra cedează după întrerupere.','Nosocomial și embolia (mai ales endocardită dreaptă sau spitalizare lungă).','Schimbarea empirică trebuie evitată, exceptând culturi noi pozitive sau alergie.','Rezistența nouă este rară; se colaborează cu microbiologia și chirurgia.']],
 8,'Transformă febra persistentă într-un pretext de schimbare empirică, pe care textul o descurajează explicit.',['48 de ore','Febra persistentă']),
];
