import {advancedQuestion} from './advanced-author';
import type {SourceRow} from './source-author';
const pdfOffset=(p:number)=>p<=1048?p-837:p<=1107?p-839:p-851;
const q=(n:number,row:SourceRow,score:number,reason:string,expressions:string[],related:number[]=[])=>
 advancedQuestion('cardiologie',30,pdfOffset,`cardiologie-adv-${String(n).padStart(3,'0')}`,row,[score,reason],expressions,undefined,related);

export const CARDIOLOGIE_E=[
q(159,['Terapia inițială din Cadranul 30.29 (ICA) include:',
 ['Oxigen inspirat în concentrație de 35-50%','Morfină 2,5-5,0 mg i.v., cu metoclopramid 10 mg i.v.','Enoxaparină 1 mg/kg s.c. ×2/zi în SCA sau 40 mg s.c. zilnic profilactic','Dopamina în doză mare (<2 µg/kg/min) ca prim inotrop în toate formele','Oxigen 100% de rutină, fără NIPPV'],'ABC',1078,'Insuficiența cardiacă acută — Oxigen, morfină, HGMM',
 'Aplicarea concentrației 35-50%, a morfinei cu antiemetic și a celor două doze de enoxaparină.',
 ['Cadranul: oxigen inspirat 35-50%.','Doza de morfină și metoclopramidul sunt explicite.','Cele două scheme de enoxaparină (SCA vs profilaxie) sunt din tabel.','Doza mare de dopamină este >5 µg/kg/min, nu <2 (doza mică).','NIPPV/CPAP figurează alături de oxigen, nu este exclusă.']],
 8,'Inversează treptele de dopamină și impune oxigen 100% în locul ferestrei 35-50%.',['35-50%','metoclopramid 10 mg']),

q(160,['Dobutamina și dopamina în doze mari, în ICA:',
 ['Dobutamina se titratează 2-20 µg/kg/min; pacienții sub beta-blocante pot necesita doze mari','Dopamina în doză mare (>5 µg/kg/min) acționează ca vasopresor','Milrinona: bolus 25-75 µg/kg în 10-20 min, apoi 0,375-0,75 µg/kg/min','Dobutamina este contraindicată dacă pacientul primea beta-blocant cronic','Dopamina >5 µg/kg/min este inotropul de elecție în SCA cu IC acută, înaintea oricărei alte măsuri'],'ABC',1078,'ICA — Doze de dobutamină, dopamină mare, milrinonă',
 'Memorarea ferestrelor 2-20 (dobutamină) și >5 (dopamină vasopresoare) plus bolusul de milrinonă.',
 ['Dozele de dobutamină și mențiunea beta-blocantelor sunt din cadran.','Doza mare de dopamină este vasopresoare.','Bolusul și perfuzia de milrinonă sunt listate.','Textul spune că sub beta-blocante pot fi necesare doze mari de dobutamină, nu că este contraindicată.','Cadranul de IC acută evită digoxinul/inotropele ca primă linie în SCA; dopamina mare nu este elecția universală.']],
 8,'Interzice dobutamina la beta-blocant — tocmai situația în care tabelul cere doze mai mari.',['2-20 µg/kg pe min','>5 µg/kg pe min']),

q(161,['Fiziopatologia sindromului coronarian acut:',
 ['Mecanismul comun este ruptura sau eroziunea capișonului fibros al plăcii','Miez lipidic abundent și capișon fibros subțire se asociază cu risc crescut de ruptură','Serotonina și tromboxanul A2 eliberate din plachete produc vasoconstricție și ischemie','SCA se produce doar prin stenoză progresivă lentă, fără tromb','Capișonul gros și miezul sărac în lipide sunt leziunile cele mai vulnerabile'],'ABC',1080,'SCA — Placa vulnerabilă și tromboxanul A2',
 'Recunoașterea substratului (capișon subțire, miez lipidic) și a vasoconstricției prin serotonină/TxA2.',
 ['Ruptura/eroziunea capișonului este mecanismul comun.','Asocierea miez lipidic + capișon subțire este explicită.','Serotonina și TxA2 reduc fluxul coronarian.','Tromb local, vasoconstricție și embolizare distală sunt descrise, nu doar stenoza lentă.','Vulnerabile sunt tocmai leziunile cu capișon subțire și miez lipidic.']],
 8,'Inversează morfologia plăcii vulnerabile (capișon subțire/miez lipidic versus capișon gros).',['capişonului fibros','tromboxanului A2'],[1085]),

q(162,['Modificările de stil de viață pentru prevenția bolii coronariene includ:',
 ['Cel puțin 150 de minute de activitate aerobică moderată sau 75 de minute de intensitate crescută pe săptămână','IMC <25 kg/m²; în UK, sub 14 măsuri de alcool pe săptămână, distribuite în ≥3 zile','Cel puțin cinci porții de fructe și legume pe zi și două porții de pește pe săptămână','Colesterol alimentar nelimitat, grăsimile saturate fiind preferate celor nesaturate','Efortul fizic se evită complet după 45 de ani, pentru a proteja placa'],'ABC',1081,'Boala coronariană — Stil de viață',
 'Aplicarea ferestrelor 150/75 minute, IMC <25 și a pragului de 14 unități de alcool.',
 ['Recomandarea de efort săptămânal este explicită.','IMC <25 și <14 măsuri de alcool în ≥3 zile sunt din text.','Porțiile de fructe/legume și pește sunt listate.','Colesterolul alimentar trebuie <300 mg/zi; saturatele se înlocuiesc cu nesaturate.','Efortul aerobic este recomandat, nu interzis.']],
 8,'Interzice efortul și preferă grăsimile saturate, inversul dietei și al protocolului de 150 de minute.',['150 minute','<25 kg/m2']),

q(163,['Conform NICE, angina atipică și cea instabilă se definesc astfel:',
 ['Atipică: durere toracică cu numai 2 dintre cele 3 caracteristici ale anginei clasice','Instabilă: debut recent (<24 de ore) sau agravare a anginei stabile, adesea în repaus, suprapusă definiției de SCA','Non-anginoasă: toate cele trei caracteristici, identic formei clasice','Clasică: o singură caracteristică din trei','Instabilă înseamnă angină doar la efort intens, identic CCS I'],'AB',1081,'Angina — Definiții NICE și forma instabilă',
 'Diferențierea 3/3 (clasică), 2/3 (atipică), 1/3 (non-anginoasă) și a ferestrei <24 de ore a instabilei.',
 ['NICE: atipică = 2 din 3.','Instabilă: <24 de ore sau agravare, adesea în repaus.','Non-anginoasă are o singură caracteristică din trei, nu pe toate trei.','Clasică are toate cele trei caracteristici.','CCS I este angina la efort intens, fără limitare zilnică, nu instabilitatea.']],
 8,'Degradează angina clasică la un singur criteriu și confundă instabilitatea cu CCS I.',['<24 ore','2 dintre cele 3']),

q(164,['Parcursul diagnostic al durerii toracice fără boală coronariană cunoscută:',
 ['Angina tipică sau atipică, ori durerea non-anginoasă cu modificări ST sau unde Q, se îndrumă la angio-CT coronarian multi-slice ≥64','Dacă angio-CT este neconcludent, urmează teste funcționale neinvazive (SPECT, eco de stres, IRM de stres)','Pacienții trebuie informați că prognosticul vital este bun (mortalitate anuală <2%)','Durerea non-anginoasă cu ECG normal se îndrumă de primă intenție la PCI primară','Examenul obiectiv este suficient, gerontoxonul și stenoza aortică fiind irelevante'],'ABC',1082,'Angina stabilă — Angio-CT și prognostic <2%',
 'Algoritmul CT ≥64 slice-uri, apoi teste funcționale, plus mesajul de mortalitate anuală <2%.',
 ['Calea către angio-CT multi-slice ≥64 este explicită.','Testele funcționale urmează unui CT neconcludent.','Mortalitatea anuală <2% este mesajul de consiliere.','Durerea non-anginoasă cu ECG normal se investighează pentru diagnostice alternative, nu PCI primară.','Examenul caută anemie, hipertiroidism, gerontoxon/xantelasme și stenoză aortică.']],
 8,'Trimite durerea non-anginoasă cu ECG normal la PCI primară, sărind algoritmul NICE.',['64 slice','<2%']),

q(165,['În algoritmul NICE al anginei stabile, după un beta-blocant sau un blocant de calciu nesusținut:',
 ['Se poate trece pe nitrat cu acțiune prelungită, ivabradină, nicorandil sau ranolazină','Dacă rămâne simptomatic, se asociază beta-blocant cu blocant de calciu','Sub două antianginoase, se consideră revascularizarea','Se începe de la început cu triple terapie plus GPIIb/IIIa de rutină','Revascularizarea se rezervă doar anginei CCS I, fără a încerca un al doilea antianginos'],'ABC',1082,'Angina stabilă — Algoritmul Fig. 30.64',
 'Secvența: un antianginos → schimb sau asociere → două antianginoase → revascularizare.',
 ['Linia a doua include cele patru agenți.','Asocierea BB + BCC este pasul următor.','Revascularizarea se consideră sub două antianginoase.','GPIIb/IIIa nu apar în algoritmul anginei stabile.','Revascularizarea se discută la simptome persistente, nu la CCS I controlată.']],
 8,'Sare la triple+GPIIb/IIIa și rezervă revascularizarea clasei I, inversând Fig. 30.64.',['Nicorandil','Ranolazină'],[1083]),

q(166,['Din Cadranul 30.33, particularitățile antianginoaselor de linia a doua includ:',
 ['Nicorandilul este activator al canalelor de K+ sensibile la ATP, cu proprietăți de nitrat; poate da ulcerații orale','Ranolazina (375-750 mg ×2/zi) inhibă canalele de Na+ din cardiomiocite, e metabolizată de CYP3A4 și poate prelungi QT','Ivabradina poate produce fosfene și bradicardie; se folosește în ritm sinusal','Verapamilul este de elecție în BAV II-III și în staza pulmonară','Nitroglicerina sublinguală se asociază de rutină cu sildenafil'],'ABC',1083,'Angina — Nicorandil, ranolazină, ivabradină',
 'Recunoașterea ulcerațiilor orale (nicorandil), a ferestrei 375-750 mg și a fosfenelor ivabradinei.',
 ['Mecanismul și ulcerațiile orale sunt din tabel.','Doza, CYP3A4 și QT sunt explicite.','Fosfenele, bradicardia și folosirea în sinus sunt listate.','Verapamilul și diltiazemul sunt contraindicate în BAV II-III și în IVS cu stază.','Nitrații sunt contraindicate cu inhibitorii PDE5.']],
 8,'Pune verapamilul pe BAV II-III — contraindicație de tabel — și asociază nitratul cu sildenafil.',['ulceraţii orale','375-750 mg']),

q(167,['Ținta de colesterol LDL cu atorvastatină 80 mg în angina stabilă, conform cadranului, este:',
 ['<3,5 mmol/L','<1,8 mmol/L','<5,0 mmol/L, identic prevenției primare fără risc','Nicio țintă, statinele fiind interzise în angină','<0,5 mmol/L, prin ezetimib izolat'],'B',1083,'Angina — Ținta LDL',
 'Reținerea țintei LDL <1,8 mmol/L sub atorvastatină 80 mg.',
 ['3,5 mmol/L nu este ținta citată.','Cadranul: reducerea LDL la <1,8 mmol/L.','5,0 mmol/L nu apare.','Statinele sunt fundamentul reducerii evenimentelor.','Ezetimibul izolat nu înlocuiește atorvastatina 80 mg.']],
 8,'Mută ținta de la <1,8 la <3,5 mmol/L, praguri alăturate dar false.',['<1,8 mmol/L','Atorvastatina 80 mg']),

q(168,['Diferența dintre angina instabilă și NSTEMI constă în:',
 ['Apariția trombusului ocluziv care duce la necroză și creșterea troponinei sau CK-MB în NSTEMI','Faptul că AI decurge fără durere, iar NSTEMI se însoțește constant de undă Q','Identitatea lor completă, markerii fiind superfluți','Prezența BRS nou ca criteriu de AI, nu de STEMI','NSTEMI se diagnostichează doar radiologic, fără ECG sau troponină'],'A',1084,'SCA — AI versus NSTEMI',
 'Reținerea necrozei (troponină/CK-MB) ca element care desparte NSTEMI de angina instabilă.',
 ['Textul: diferența este trombusul ocluziv cu necroză și creștere enzimatică în NSTEMI.','AI poate avea durere; unda Q nu definește NSTEMI.','Nu sunt identice; markerii definesc necroza.','BRS nou orientează spre STEMI/reperfuzie, nu spre AI.','Diagnosticul combină anamneză, ECG și markeri.']],
 8,'Anulează rolul troponinei — tocmai criteriul care desparte NSTEMI de AI.',['trombusului ocluziv','CK-MB']),

q(169,['Conform Cadranului 30.34, un nivel de troponină I >9 ng/ml în SCA corespunde unei mortalități la 42 de zile de circa:',
 ['1,0%','1,7%','3,4%','7,5%','0,1%'],'D',1085,'SCA — Troponina I și mortalitatea la 42 de zile',
 'Memorarea treptei >9 ng/ml → 7,5% mortalitate la 42 de zile, versus 1% la valori nedetectabile.',
 ['1,0% corespunde intervalului 0–<0,4 ng/ml.','1,7% este 0,4–<1,0.','3,4% este 1,0–<2,0.','Cadranul: >9,0 ng/ml → 7,5%.','0,1% subestimează net.']],
 8,'Cele cinci trepte consecutive din același tabel sunt ușor de permutat; doar >9 ng/ml dă 7,5%.',['>9,0','7,5']),

q(170,['După externarea din NSTEMI, riscul GRACE scăzut la 6 luni corespunde:',
 ['Unui scor >118, cu mortalitate >8%','Unui scor ≤88, cu mortalitate <3%','Unui scor 126-154, banda STEMI intra-spital medie','Unui scor ≥200, indiferent de moment','Lipsei oricărei stratificări post-externare'],'B',1086,'SCA — GRACE la 6 luni (NSTEMI)',
 'Reținerea pragului ≤88 (<3%) pentru NSTEMI la 6 luni, distinct de >118 (>8%) și de benzile STEMI.',
 ['>118 este riscul înalt NSTEMI la 6 luni (>8%).','Cadranul 30.37: NSTEMI la 6 luni, scăzut ≤88, mortalitate <3%.','126-154 este STEMI intra-spital mediu.','≥200 nu este categoria de 6 luni NSTEMI.','GRACE stratifică și post-externare.']],
 8,'Confundă ≤88 (<3% la 6 luni) cu pragul înalt >118 sau cu benzile STEMI intra-spital.',[':S88','<3']),

q(171,['Duala antiagregare în SCA și țintele beta-blocantului:',
 ['Aspirină 300 mg încărcare, apoi 75-100 mg/zi','Prasugrel 60 mg încărcare, apoi 10 mg/zi; ticagrelor 180 mg apoi 90 mg ×2/zi','Beta-blocantele se titrează către o frecvență de repaus de 50-60/min, în absența contraindicațiilor','Clopidogrel 300-600 mg încărcare, apoi 75 mg/zi','GPIIb/IIIa se dau de rutină, indiferent de încărcarea trombotică'],'ABCD',1086,'SCA — DAPT și frecvența 50-60/min',
 'Fixarea dozelor de încărcare (inclusiv clopidogrel 300-600 mg) și a țintei de frecvență 50-60/min.',
 ['Încărcarea și întreținerea aspirinei sunt explicite.','Dozele de prasugrel și ticagrelor sunt din text.','Ținta 50-60/min este citată.','Încărcarea de clopidogrel 300-600 mg apoi 75 mg este din text.','GPIIb/IIIa se rezervă încărcării trombotice marcate sau complicațiilor PCI.']],
 8,'Atribuie prasugrelului încărcarea de clopidogrel și readuce GPIIb/IIIa ca rutină.',['50-60 pe minut','60 mg']),

q(172,['Fondaparinux și bivalirudina în SCA:',
 ['Fondaparinux este un pentazaharid care activează antitrombina și inactivează factorul Xa, fără a inactiva trombina direct și fără efect antiplachetar','Bivalirudina se leagă reversibil de trombină; în ACUITY a avut eficacitate similară heparinei+GPIIb/IIIa, cu risc hemoragic mai mic','Enoxaparina este superioară heparinei nefracționate și se dă subcutanat de două ori pe zi','Fondaparinux inactivează trombina direct, ca un DOAC oral','HNF nu necesită monitorizare aPTT'],'ABC',1086,'SCA — Antitrombinice',
 'Contrastul fondaparinux (anti-Xa via AT) versus bivalirudină (inhibitor direct reversibil) și superioritatea enoxaparinei.',
 ['Mecanismul fondaparinux este descris astfel.','ACUITY și legarea reversibilă sunt explicite.','Enoxaparina s.c. ×2/zi este superioară HNF.','Fondaparinux nu inactivează trombina direct.','HNF cere aPTT la 6-12 ore.']],
 8,'Transformă fondaparinux-ul — pentazaharid anti-Xa — într-un inhibitor direct de trombină.',['Fondaparinux','bivalirudina']),

q(173,['Din Cadranul 30.38, particularități de dozaj în SCA includ:',
 ['Prasugrel 10 mg/zi, redus la 5 mg/zi dacă pacientul are <60 kg sau >75 de ani','Fondaparinux 2,5 mg s.c. pe zi, până la 8 zile','Morfina 2,5-5,0 mg i.v., asociată cu metoclopramid 10 mg i.v.','Aspirina se evită în SCA, fiind înlocuită de rutină cu GPIIb/IIIa','Atenololul i.v. este de primă linie în astm, IC și bradiaritmii'],'ABC',1087,'SCA — Prasugrel 5 mg, fondaparinux 2,5 mg',
 'Aplicarea reducerii prasugrelului la vârstnici/greutate mică și a ferestrei fondaparinux 8 zile.',
 ['Reducerea la 5 mg sub 60 kg sau peste 75 de ani este din tabel.','2,5 mg s.c. până la 8 zile este explicit.','Morfina cu antiemetic este listată.','Aspirina 150-300 mg mestecabilă rămâne baza.','Beta-blocantele sunt contraindicate în astm, IC, hipotensiune, bradiaritmii.']],
 8,'Omite reducerea prasugrelului la >75 de ani/<60 kg — capcana de dozaj a cadranului.',['<60 kg','2,5 mg s.c.']),

q(174,['Scorul TIMI în STEMI punctează, printre altele:',
 ['Vârsta >75 ani cu 3 puncte','Greutatea >67 kg și întârzierea tratamentului >4 ore','TA sistolică <100 mmHg, FC >100/min, Killip II-IV, IM anterior sau BRS','Doar troponina, identic NSTEMI fără date clinice','Un scor 0 corespunde unei mortalități la 30 de zile de 35,9%'],'ABC',1088,'STEMI — Scorul TIMI (Cadranul 30.39)',
 'Recunoașterea itemilor STEMI (vârstă >75 cu 3 puncte, greutate, delay) distincți de TIMI NSTEMI.',
 ['Vârsta >75 primește 3 puncte.','Greutatea >67 kg și delay >4 ore sunt itemi STEMI.','TAS, FC, Killip și localizarea/BRS sunt în tabel.','TIMI STEMI combină clinic și ECG, nu troponina izolată.','Scorul 0 are mortalitate 0,8%; 35,9% este banda 9-16.']],
 8,'Atribuie scorului 0 mortalitatea benzii 9-16 (35,9%) și reduce TIMI STEMI la troponină.',['>75 ani','>67 kg']),

q(175,['Electrocardiograma în STEMI — praguri și timing:',
 ['ECG în primele 10 minute de la primul contact medical; dacă e neschimbat și durerea persistă, se repetă la 15 minute','Supradenivelare ST nouă ≥0,2 mV la punctul J în V1-V3 și ≥0,1 mV în alte derivații orientează spre IM anterior','Durerea tipică depășește 20 de minute și nu cedează de obicei la nitroglicerină sublinguală','BRS major nou sau presupus nou nu necesită reperfuzie, diagnosticul ECG fiind imposibil','Prima ECG normală exclude infarctul și face monitorizarea ritmului superfluă'],'ABC',1088,'STEMI — ECG, 10 minute și 0,2 mV',
 'Aplicarea ferestrei de 10/15 minute, a pragului 0,2 mV în V1-V3 și a durerii >20 de minute.',
 ['Timing-ul 10 minute și repetarea la 15 minute sunt explicite.','Pragurile 0,2/0,1 mV sunt din text.','Durerea >20 de minute, refractară la nitrat, este tabloul clasic.','BRS nou asociază ocluzie și cere reperfuzie urgentă.','ECG inițial e rar normal; monitorizarea ritmului rămâne necesară.']],
 8,'Anulează reperfuzia din BRS nou — indicație explicită — și tratează prima ECG normală ca excludere.',['10 minute','20 de minute']),

q(176,['După tromboliza sistemică în STEMI se urmărește:',
 ['Bolusul de lytic în primele 10 minute de la diagnostic','Scăderea supradenivelării ST cu >50% față de referință la 60-90 de minute; altfel, PCI de salvare','Aspirină plus clopidogrel ca antiagregante; HNF, enoxaparină sau fondaparinux 5-7 zile','Tromboaspirația de rutină în locul lizelor','GPIIb/IIIa de rutină la toți trombolizații, fără heparină'],'ABC',1089,'STEMI — Tromboliză, salvare și 5-7 zile',
 'Reținerea bolusului în 10 minute, a criteriului 50% la 60-90 min și a anticoagulației 5-7 zile.',
 ['Ținta de 10 minute este explicită.','Eșecul (ST nu scade >50% la 60-90 min) duce la PCI de salvare.','Antiagregantele și fereastra 5-7 zile sunt din text.','Tromboaspirația de rutină nu este recomandată (nici în PCI primară).','GPIIb/IIIa de rutină nu mai este recomandată.']],
 8,'Înlocuiește criteriul 50%/60-90 min de salvare cu tromboaspirație de rutină, respinsă de text.',['10 minute','60-90 minute']),

q(177,['În Europa, boala cardiacă ischemică cauzează anual circa:',
 ['1,8 milioane de decese','18.000 de decese','1,8% din populație, fără mortalitate','Aceeași mortalitate ca pericardita acută (5% din durerile de urgență)','Sub 1.000 de decese, limitate la STEMI neperfuzat'],'A',1088,'STEMI — Epidemiologie europeană',
 'Reținerea ordinii de mărime 1,8 milioane de decese anuale prin BCI în Europa.',
 ['Textul: aproximativ 1,8 milioane de oameni mor anual în Europa din cauza BCI.','18.000 subestimează cu două ordine.','Nu este o prevalență de 1,8% fără mortalitate.','5% este ponderea pericarditei în durerile de urgență, nu mortalitatea BCI.','Ordinul de mărime este de milioane, nu mii.']],
 8,'Subestimează cu două-trei ordine de mărime mortalitatea europeană prin BCI.',['1,8 milioane','boala cardiacă ischemică']),

q(178,['Valvulotomia mitrală cu balon prin puncție transseptală este preferabilă când:',
 ['Valvele sunt suple, aparatul subvalvular minim afectat și regurgitarea mitrală minimă','ETE preprocedurală exclude tromboza atrială stângă','Calcificările importante, RM mai mult decât ușoară sau trombul atrial sunt prezente','Se asociază RM moderată, pe care balonul o ameliorează constant','Nu este nevoie de ghidaj, septul nefiind puncționat'],'AB',1094,'Stenoza mitrală — Valvuloplastie cu balon',
 'Criteriile de fezabilitate (valve suple, RM minimă) și rolul ETE de excludere a trombului.',
 ['Textul rezervă procedura valvei suple cu aparat subvalvular și RM minime.','ETE exclude trombul înaintea puncției.','Calcificarea importantă, RM > ușoară și trombul sunt contraindicații.','RM mai mult decât ușoară contraindică, nu este un argument.','Procedura puncționează septul din vena femurală.']],
 8,'Transformă contraindicațiile (calcificare, RM, tromb) în indicații ale balonului.',['trombozei atriale stângi','puncţie transseptală']),

q(179,['Scorul Wilkins evaluează, pentru fezabilitatea valvuloplastiei mitrale:',
 ['Mobilitatea, îngroșarea și calcificarea cuspelor, plus îngroșarea aparatului subvalvular','Doar gradientul mediu, fără morfologie','Doar prezența FA, fără ecografie','Grosimea peretelui VS, identic CMH','Diametrul rădăcinii aortice'],'A',1094,'Stenoza mitrală — Scorul Wilkins',
 'Reținerea celor patru itemi Wilkins (mobilitate, îngroșare, calcificare, subvalvular).',
 ['Cei patru parametri sunt enumerați explicit.','Gradientul completează cadranul 30.42, dar Wilkins este morfologic.','FA influențează anticoagularea, nu scorul Wilkins.','Grosimea VS nu este item Wilkins.','Rădăcina aortică ține de valva aortică.']],
 8,'Înlocuiește cei patru itemi morfologici Wilkins cu un gradient izolat sau cu grosimea din CMH.',['Scorul Wilkins','aparatului subvalvular']),

q(180,['Regurgitarea mitrală — cauze, Carpentier și semne:',
 ['Cauze frecvente: degenerescență mixomatoasă, ischemie, reumatism, endocardită; medicamente: fenfluramină, cabergolină','Carpentier: A mobilitate normală, B crescută/prolaps, C restricționată','Șoc apexian difuz deplasat, S1 diminuat, suflu holosistolic către axilă; HVS ECG la circa 50%','Tromboembolia este mai frecventă decât în stenoza mitrală, endocardita fiind rară','S1 este constant întărit, ca în stenoza mitrală cu valve mobile'],'ABC',1095,'Regurgitarea mitrală — Carpentier și auscultație',
 'Potrivirea clasificării Carpentier cu suflul holosistolic axillary și HVS la 50%.',
 ['Etiologiile și medicamentele (fenfluramină, cabergolină) sunt listate.','Cele trei tipuri Carpentier sunt din figură/text.','Semnele și HVS la 50% sunt explicite.','Tromboembolia este mai rară decât în SM; endocardita subacută este mai frecventă.','S1 este diminuat prin apoziție incompletă, nu întărit.']],
 8,'Inversează S1 (diminuat în RM versus întărit în SM) și umflă riscul embolic peste pe cel al stenozei.',['fenfluramină','50%'],[1096]),

q(181,['Stenoza aortică simptomatică și bicuspidia cu aortă dilatată:',
 ['Prezența simptomelor este un bun indicator de severitate; simptomaticii trebuie să beneficieze de înlocuire valvulară','La bicuspidie, chirurgia se consideră dacă aorta ascendentă depășește 50 mm sau crește cu peste 5 mm/an','Asimptomaticii cu SA severă au indicație dacă apar simptome/scădere TA la efort, FEVS <50%, Vmax >5,5 m/s, PAPS >60 mmHg sau creștere Vmax >0,3 m/s/an','Valvuloplastia cu balon la adult este soluția definitivă, superioară TAVI','Simptomaticii se urmăresc conservator nelimitat dacă FEVS este 55%'],'ABC',1099,'Stenoza aortică — Indicații chirurgicale',
 'Aplicarea pragurilor 50 mm/5 mm/an la bicuspidie și a criteriilor eco (5,5 m/s, 60 mmHg, 0,3 m/s/an).',
 ['Simptomele orientează către înlocuire.','Cele două praguri aortice sunt explicite.','Lista indicațiilor la asimptomatici este din text.','Valvuloplastia la adult are rezultate slabe; TAVI este alternativa inoperabililor.','Simptomaticul are indicație de corecție, nu urmărire nelimitată.']],
 8,'Amână chirurgia simptomaticului cu FE 55% și promovează balonul adultului ca soluție definitivă.',['50 mm','5,5 m/s'],[1098]),

q(182,['Fiziopatologia regurgitării aortice cronice:',
 ['Reflux diastolic în VS; pentru a menține debitul net, volumul ejectat în aortă trebuie să crească, dilatând VS','Tensiunea diastolică scade, deci și perfuzia coronariană; VS dilatat este mai puțin eficient, cu necesar de O2 crescut și ischemie','Simptomele semnificative apar târziu, odată cu insuficiența de VS; aritmiile sunt relativ rare','TA diastolică crește, ameliorând perfuzia coronariană','Șocul apexian este nedeplasat și susținut, identic stenozei aortice'],'ABC',1100,'Regurgitarea aortică — Fiziopatologie',
 'Legarea scăderii TA diastolice de hipoperfuzia coronariană și de ischemia VS dilatat.',
 ['Creșterea volumului ejectat și dilatarea VS sunt explicite.','Scăderea TA diastolice și ischemia prin ineficiență mecanică sunt descrise.','Simptomele tardive și raritatea aritmiilor sunt din text.','TA diastolică scade, nu crește.','Apexul este hiperdinamic, deplasat inferior și lateral.']],
 8,'Crește TA diastolică — inversul fiziopatologiei RA — și atribuie apexul nedeplasat al stenozei.',['perfuzia coronariană','Austin Flint'],[1099]),

q(183,['Cauzele regurgitării aortice acute (Cadranul 30.44) includ:',
 ['Reumatism articular acut, endocardită infecțioasă, disecție de aortă, anevrism de sinus Valsalva rupt, proteză disfuncțională','Sifilisul și osteogenesis imperfecta ca etiologii acute de primă linie','Doar stenoza aortică calcificată a vârstnicului','Hipotiroidismul mixedematos','Pericardita constrictivă'],'A',1100,'Regurgitarea aortică — Cadranul 30.44 (acută)',
 'Listarea cauzelor acute (RAA, endocardită, disecție, Valsalva, proteză), distincte de Marfan/sifilis cronice.',
 ['Cele cinci cauze acute sunt din cadran.','Sifilisul și osteogenesis imperfecta sunt la forma cronică.','BAVC este o boală a stenozei vârstnicului, nu cauza RA acute.','Mixedemul ține de pericard, nu de RA acută.','Constricția nu figurează în cadran.']],
 8,'Mută sifilisul/Marfan din forma cronică în cea acută, amestecând cele două coloane ale tabelului.',['Disecţie de aortă','sinus Valsalva']),

q(184,['Stenoza pulmonară se caracterizează clinic prin:',
 ['Suflu mezosistolic rugos de ejecție, maxim în inspir, în spațiul II intercostal stâng, adesea cu freamăt','P2 întârziată și diminuată; clic de ejecție dacă obstrucția este valvulară','Forma ușoară impune valvulotomie imediată, identic celei critice','Suflu protodiastolic Graham Steell, accentuat în inspir, ca leziune primară','P2 întărită de rutină, identic hipertensiunii pulmonare din regurgitare'],'AB',1102,'Stenoza pulmonară — Semne și tratament',
 'Contrastul P2 diminuate din stenoză versus P2 întărite din regurgitarea pe HTP.',
 ['Suflul de ejecție inspirator în SICS II este explicit.','P2 întârziată/diminută și clic ul valvular sunt descrise.','Ușoara e asimptomatică; severa se tratează prin valvulotomie.','Graham Steell aparține regurgitării pulmonare.','P2 întărită este a regurgitării pe fond de HTP, nu a stenozei.']],
 8,'Pune P2 întărită și Graham Steell pe stenoza pulmonară, semnele regurgitării de HTP.',['spaţiul li intercostal','valvulotomie pulmo']),

q(185,['Protezele valvulare — durabilitate, INR intermediar și auscultație:',
 ['Mecanicele sunt mai durabile; biologicele degenerează după circa 10 ani, dar sunt mai puțin trombogene','Valve moderat trombogene (Björk-Shiley, alte bidisc): INR 3,0 fără factori și 3,5 cu factori','Zgomotele mecanicelor sunt mai puternice, audibile la deschidere și închidere; biologicele seamănă nativelor','Factorii adiționali de tromboembolism includ FA, diametrul AS >50 mm și FEVS <35%','DOAC sunt de primă linie la protezele mecanice'],'ABCD',1102,'Proteze — Durabilitate 10 ani și INR 3,0/3,5',
 'Completarea treptei intermediare INR 3,0/3,5, a degenerării la circa 10 ani și a factorilor adiționali (AS >50 mm, FEVS <35%).',
 ['Durabilitatea versus trombogenitatea este explicită.','Treptele 3,0/3,5 pentru moderat trombogene sunt din listă.','Contrastul auscultator mecanic/biologic este descris.','Lista factorilor adiționali (inclusiv AS >50 mm și FEVS <35%) este din text.','Nu există indicație DOAC la proteze.']],
 8,'Pune biologicul la INR 4,0 pe viață — treapta Starr-Edwards — și introduce DOAC-ul interzis.',['10 ani','INR 3,0'],[1103]),

q(186,['Anticoagularea protezei mecanice în sarcină:',
 ['Warfarina traversează placenta, cu risc de 5-12% de embriopatie în primul trimestru și de hemoragie intracraniană fetală','HGMM de două ori pe zi, cu anti-Xa 0,8-1,2 U/ml la 4 ore post-doză, oferă un efect mai consistent','Heparina nefracționată are incidență ridicată (circa 25%) a trombozei valvulare în sarcină','HGMM traversează placenta și cauzează embriopatie identică warfarinei','Mortalitatea maternă asociată protezei mecanice în sarcină este neglijabilă (<0,1%)'],'ABC',1103,'Proteze — Sarcină, anti-Xa și UFH 25%',
 'Aplicarea ferestrei anti-Xa 0,8-1,2 și a riscului 25% de tromboză sub UFH, versus embriopatia 5-12%.',
 ['Trecerea placentară, 5-12% și hemoragia fetală sunt explicite.','Schema HGMM și țintele anti-Xa sunt din text.','25% tromboză sub UFH este cifra citată.','Heparinele nu traversează placenta și nu dau embriopatie.','Mortalitatea maternă este 1-4%, nu <0,1%.']],
 8,'Atribuie HGMM embriopatia warfarinei și comprimă mortalitatea maternă de la 1-4% la 0,1%.',['0,8-1,2 U / ml','25%']),

q(187,['Sursele de bacteriemie în endocardită (Fig. 30.89) includ:',
 ['Cavitatea orală: streptococi viridans α-hemolitici, circa 1/3-1/2 din cazuri, mai multe în țările în dezvoltare','Intestin/perineu: enterococi (E. faecalis); Strep. bovis legat de neoplazie intestinală','CDIV: S. aureus, Candida (rar); heroina dizolvată în zeamă de lămâie contaminată','Strep. bovis ca germen oral dominant, viridansul fiind intestinal','Endocardita precoce pe proteză este comunitară, cu viridans 50-70%'],'ABC',1104,'Endocardita — Porți de intrare',
 'Potrivirea viridans oral, enterococ/bovis intestinal și S. aureus la CDIV.',
 ['Gura: viridans, 1/3-1/2, mai multe în țările în dezvoltare.','Enterococul urinar/spitalicesc și bovis-neoplazie sunt din figură.','CDIV: S. aureus/Candida și zeama de lămâie.','Bovis este intestinal, viridansul oral.','Precocele e nosocomial stafilococic în 60 de zile, nu comunitar streptococic.']],
 8,'Inversează porțile viridans/bovis și tratează precocele de proteză ca infecție comunitară streptococică.',['Strep. bovis','zeamă de lămâie']),

q(188,['Cadranul 30.47 — explorări în endocardită:',
 ['Trei seturi de hemoculturi din locuri de puncție diferite','Serologie pentru Coxiella, Bartonella, Legionella, Chlamydia la culturi negative','PCR scade ca răspuns la terapia eficientă și poate crește din nou în recăderi','Un singur set din cateterul central înlocuiește cele trei seturi periferice','Prelungirea PR este un semn de vindecare, nu de abces de rădăcină aortică'],'ABC',1106,'Endocardita — Cadranul 30.47',
 'Trei seturi, serologia culturilor negative și dinamica PCR sub tratament.',
 ['Trei seturi din locuri diferite sunt prima linie.','Serologia germenilor atipici este de luat în considerare la culturi negative.','PCR scade la terapie eficientă și crește în recăderi.','Un set de pe cateter nu înlocuiește protocolul.','Prelungirea PR se asociază abceselor de rădăcină aortică.']],
 8,'Reduce bacteriologia la un set de pe cateter și interpretează PR lung ca vindecare.',['Trei seturi','proteină C reactivă'],[1105]),

q(189,['Boala Chagas cardiacă:',
 ['Este cauzată de Trypanosoma cruzi; endemică în America de Sud, cu peste 20 de milioane de infectați','Faza acută: miocardită cu febră și IC congestivă; faza cronică: CMD cu tendință la blocuri și aritmii ventriculare','Amiodarona este utilă pentru controlul aritmiilor ventriculare','Este o boală autozomal dominantă sarcomerică, identică CMH','Serologia virală o confirmă de primă intenție, IRM-ul fiind inutil'],'ABC',1119,'Miocard — Boala Chagas',
 'Reținerea ordinii de 20 de milioane, a evoluției acut→CMD și a rolului amiodaronei.',
 ['Parazitul și cifra de 20 de milioane sunt explicite.','Cele două faze sunt descrise.','Amiodarona este menționată pentru aritmii ventriculare.','Chagas este infecțioasă, nu o mutație sarcomerică.','Diagnosticul nu se bazează pe serologie virală (neutilă în miocardita virală).']],
 8,'Transformă Chagas-ul parazitar sud-american într-o CMH sarcomerică.',['20 de milioane','Trypanosoma cruzi']),

q(190,['Clasificarea ESC a cardiomiopatiilor distinge fenotipurile:',
 ['Hipertrofică, aritmogenă, dilatativă, restrictivă și neclasificate, apoi familiale versus non-familiale','Doar ischemice versus hipertensive, fără fenotip morfologic','O singură entitate, „cardiomiopatia nespecifică”','Doar Tako-tsubo și peripartum','Doar bolile de depozit (Danon, Pompe, Fabry)'],'A',1119,'Cardiomiopatii — Clasificarea ESC',
 'Memorarea celor cinci fenotipuri ESC și a diviziunii familial/non-familial.',
 ['Cele cinci categorii și subdiviziunea genetică sunt explicite.','Ischemicul/hipertensivul sunt cauze alternative excluse din definiția CMH, nu clasificarea ESC.','Există fenotipuri distincte, nu o entitate unică.','Tako-tsubo și peripartum sunt cardiomiopatii dobândite, discutate ulterior.','Bolile de depozit mimează CMH, nu epuizează clasificarea.']],
 8,'Reduce clasificarea ESC la etiologii ischemice sau la formele dobândite, ignorând cele cinci fenotipuri.',['cardiomiopatia dilatativă','neclasificate']),

q(191,['Tratamentul obstrucției dinamice din cardiomiopatia hipertrofică:',
 ['Durerea și dispneea: beta-blocante, verapamil sau ambele; disopiramida ca alternativă dacă există LVOTO','Ablația septală cu alcool poate reduce obstrucția, cu risc de BAV complet și infarct','Vasodilatatoarele trebuie evitate, putând agrava LVOTO sau produce hipotensiune refractară','La unii simptomatici cu obstrucție semnificativă se poate implanta un stimulator bicameral','Ablația cu alcool este lipsită de riscuri de conducere'],'ABCD',1120,'CMH — LVOTO, alcool septal și vasodilatatoare',
 'Interdicția vasodilatatoarelor, riscurile ablației septale (BAV, IM) și opțiunea de stimulare bicamerală.',
 ['BB/verapamil/disopiramida sunt linia simptomatică.','Alcoolul septal reduce obstrucția, dar poate da BAV complet și IM.','Vasodilatatoarele agravează LVOTO.','Stimulatorul bicameral este menționat la obstrucție semnificativă simptomatică.','Riscurile de conducere și de IM sunt explicite.']],
 8,'Pune vasodilatatorul — agent care agravează LVOTO — ca primă linie.',['Ablaţia cu alcool','Vasodilatatoarele']),

q(192,['Cardiomiopatia aritmogenă — epidemiologie și genetica recesivă:',
 ['Prevalență 1 la 1.000-5.000; afectare de VS raportată la până la 75%','Naxos: keratodermă plantară și păr lânos, mutație de plakoglobină joncțională','Carvajal: mutație de desmoplakină','RyR2 cauzează Naxos, nu CPVT','Afectarea VS este excepțională, sub 5%'],'ABC',1121,'CMA — 1/1000-5000, Naxos, Carvajal',
 'Contrastul Naxos (plakoglobină) versus Carvajal (desmoplakină) și ponderea 75% a afectării de VS.',
 ['Prevalența și 75% VS sunt explicite.','Naxos: fenotip cutanat + plakoglobină.','Carvajal: desmoplakină.','RyR2 este asociat formei autosomale dominante și CPVT, nu Naxos.','Afectarea VS ajunge la 75%, nu 5%.']],
 8,'Inversează genele Naxos/Carvajal și comprimă afectarea VS de la 75% la 5%.',['75% din cazuri','boala Naxos'],[1120]),

q(193,['Criteriile de lucru pentru diagnosticul CMA includ:',
 ['Anomalii structurale ale VD/tractului de ejecție pe eco sau IRM','Înlocuire fibro-grăsoasă la biopsie; anomalii de repolarizare/conducere, inclusiv ECG cu semnal mediat','TV sau ESV frecvente la Holter; rudă de grad I sau II cu CMA; MSC prematură (<35 de ani) prin CMA','ECG-ul de efort negativ ca unic criteriu suficient','Biopsia este inutilă, fibro-grăsosul nefiind un criteriu'],'ABC',1122,'CMA — Criterii de diagnostic',
 'Listarea criteriilor (structură VD, histologie, ECG/Holter, familie, MSC <35 ani).',
 ['Dilatarea/cinetica VD sunt criterii.','Histologia și ECG-ul (inclusiv signal-averaged) sunt listate.','Holterul, ruda și MSC <35 ani completează setul.','Testul de efort negativ nu este criteriu unic.','Înlocuirea fibro-grăsoasă la biopsie este un criteriu.']],
 8,'Elimină histologia fibro-grăsoasă — criteriu de lucru explicit — și o înlocuiește cu un test de efort negativ.',['<35 ani','fibro-grăsoasă']),

q(194,['Cardiomiopatia dilatativă familială versus sporadică:',
 ['Prevalență 7-12/100.000; dilatare ventriculară și disfuncție sistolică, cu grosime parietală prezervată','Familială: predominant autosomal dominantă, >20 de loci; distrofina în forma X-linkată, lamin a/c în AD','Sporadică: miocardită (Coxsackie, adeno, HIV, Chagas), toxice (alcool, chimio, cobalt/plumb/mercur/arsen), autoimune, endocrine, neuromusculare','Distrofina explică forma AD, iar lamin a/c forma X-linkată','Grosimea parietală este marcat crescută, identic CMH'],'ABC',1122,'CMD — 7-12/100.000, distrofină, toxice',
 'Potrivirea distrofinei X-linkate versus lamin a/c AD și a listei toxice/infecțioase sporadice.',
 ['Prevalența și fenotipul (dilatare, FE scăzută, pereți prezervați) sunt explicite.','>20 de loci, distrofina XL și lamin a/c AD sunt din text.','Cauzele sporadice sunt enumerate.','Atribuirea genelor este inversată.','Pereții sunt prezervați ca grosime, nu hipertrofiați ca în CMH.']],
 8,'Inversează distrofina (XL) cu lamin a/c (AD) și pune hipertrofia CMH pe CMD.',['7-12 cazuri','Distrofină']),

q(195,['Amiloidoza cardiacă, dincolo de aspectul eco:',
 ['Biopsia endomiocardică este frecvent utilă, spre deosebire de alte cardiomiopatii, și poate confirma amiloidul','Prognosticul este mai grav decât în alte forme; amiloidul reapare des după transplant cardiac','Transplantul hepatic poate fi eficient în forma familială (prealbumină mutantă) și poate inversa anomaliile cardiace','Cateterismul nu ajută diferențierea de constricție','Nu există nicio strategie de tratament a IC sau a emboliilor'],'ABC',1124,'Amiloidoză — Biopsie, transplant hepatic',
 'Rolul biopsiei, al recurenței post-transplant cardiac și al transplantului hepatic în forma familială.',
 ['Biopsia este frecvent utilă aici, spre deosebire de alte CM.','Prognosticul mai grav și recurența post-transplant sunt explicite.','Transplantul hepatic în forma familială poate inversa anomaliile cardiace.','Cateterismul (uneori după încărcare volemică) ajută diferențierea de constricție.','IC și emboliile se tratează; transplantul cardiac se discută în forme idiopatice severe.']],
 8,'Neagă utilitatea biopsiei — tocmai excepția amiloidului — și a transplantului hepatic familial.',['prealbumină','Biopsia endomiocardică'],[1123]),

q(196,['Tahicardiomiopatia se caracterizează prin:',
 ['Perioade lungi de tahicardie supra- sau ventriculară care conduc la CMD','Cardioversia și ablația pot restabili sinusul și recupera funcția','Este identică Tako-tsubo, cu coronare libere și balonizare apicală','Apare doar în ultimul trimestru de sarcină','Nu se tratează, funcția fiind ireversibil pierdută'],'AB',1124,'Cardiomiopatii dobândite — Tahicardiomiopatia',
 'Recunoașterea CMD-ului indus de tahicardie prelungită și a reversibilității după cardioversie/ablație.',
 ['Definiția este explicită.','Cardioversia și ablația sunt menționate pentru recuperare.','Tako-tsubo are alt mecanism (catecolamine, balonizare).','Peripartum-ul, nu tahicardiomiopatia, ține de sarcină.','Funcția se poate recupera după controlul ritmului.']],
 8,'Suprapune tahicardiomiopatia peste Tako-tsubo sau peripartum, trei entități consecutive pe aceeași pagină.',['Tahicardiomiopatia','Cardioversia']),

q(197,['Pericardul normal și spectrul bolilor pericardice:',
 ['Sac fibros extern + seros intern (epicard visceral și pericard parietal); 20-49 ml de lichid lubrifiant','Se prezintă ca pericardită acută/incesantă/cronică, revărsat/tamponadă, constricție sau formațiuni','Etiologii: virală (Coxsackie, echo, HIV), Dressler tardiv, uremică, mixedematoasă, post-iradiere, post-pericardiotomie','Cantitatea normală de lichid este 200-500 ml','Pericardita acută este mai frecventă la femei vârstnice decât la bărbați tineri'],'ABC',1125,'Pericard — Anatomie 20-49 ml și etiologii',
 'Reținerea volumului 20-49 ml și a spectrului clinic, plus etiologiile Dressler/uremie/mixedem.',
 ['Anatomia și volumul 20-49 ml sunt explicite.','Cele patru prezentări sunt listate.','Cadranul 30.53 include aceste etiologii.','20-49 ml, nu 200-500 ml (care ar fi deja revărsat mare).','Pericardita acută predomină la bărbați tineri.']],
 8,'Umflă lichidul normal de la 20-49 ml la 200-500 ml și inversează sexul/vârsta.',['20-49 ml','Sindrom Dressler']),

q(198,['Pericardita acută — durere, ECG și formele de risc înalt:',
 ['Durerea poate fi pleuritică, exacerbată de mișcare și ameliorată de aplecarea înainte','ECG: ST concav în sus (șa), ST reciproc coborât în aVR și V1, plus subdenivelare PR','Spitalizare dacă febră >38°C, debut subacut, revărsat mare, tamponadă sau lipsa de răspuns','70-90% din cazuri sunt autolimitate','Atleții reiau efortul în 48 de ore, fără a aștepta markerii'],'ABCD',1125,'Pericardită acută — PR, febră >38°C, 70-90%',
 'Completarea criteriilor cu subdenivelarea PR, ponderea 70-90% autolimitată și pragul de spitalizare >38°C.',
 ['Caracterul postural al durerii este descris.','Șaua, aVR/V1 și PR coborât sunt explicite.','Criteriile de risc înalt includ febra >38°C.','70-90% sunt autolimitate.','Atleții evită efortul cel puțin 3 luni.']],
 8,'Comprimă interdicția de efort a atleților de la 3 luni la 48 de ore.',['70-90%','>38°C']),

q(199,['Aproximativ 20% dintre pericarditele acute evoluează spre:',
 ['Pericardită idiopatică recurentă, care poate fi incesantă','Vindecare în 24 de ore, fără recurență posibilă','Endocardită pe proteză, în toate cazurile','CMH obstructivă','Tamponadă cronică cu cord mic, calcificat'],'A',1126,'Pericardită — Recurența 20%',
 'Reținerea ponderii de 20% a recurenței idiopatice după un episod acut.',
 ['Textul: circa 20% evoluează spre pericardită idiopatică recurentă, posibil incesantă.','Majoritatea sunt autolimitate în săptămâni, nu în 24 de ore fără recurență.','Endocardita pe proteză este o altă entitate.','CMH nu este o sechelă a pericarditei.','Constricția/tamponada au siluete diferite; 20% se referă la recurență.']],
 8,'Înlocuiește recurența de 20% cu vindecare într-o zi sau cu endocardită/CMH.',['20% din cazuri','incesantă'],[1125]),

q(200,['Indicele gleznă-braț în boala arterială periferică:',
 ['Claudicația intermitentă se asociază cu IGB 0,5-0,9','Valori <0,5 se asociază cu ischemie critică de membru','La artere incompresibile (diabet, boală renală) IGB este fals crescut; presiunea de la degete este mai sensibilă','IGB 1,3-1,5 definește ischemia critică','Duplexul are sensibilitate 50% și specificitate 40% față de angiografie'],'ABC',1128,'BVP — IGB 0,5-0,9 versus <0,5',
 'Aplicarea benzilor IGB și a falsei creșteri pe artere calcificate.',
 ['0,5-0,9 = claudicație.','<0,5 = ischemie critică.','Calcificarea dă IGB fals crescut; degetele sunt mai sensibile.','1,3-1,5 sugerează incompresibilitate, nu ischemie critică.','Duplex: sensibilitate 87%, specificitate 95%.']],
 8,'Inversează benzile IGB (pune 1,3-1,5 pe ischemia critică) și degradează duplexul de la 87/95% la 50/40%.',['0,5-0,9','< 0,5']),

q(201,['Boala arterială periferică — epidemiologie și Fontaine:',
 ['Prezentă la 7% dintre bărbații și 4,5% dintre femeile de vârstă medie','Fontaine: I asimptomatic, II claudicație, III durere de repaus/nocturnă, IV necroză/gangrenă','Boala aorto-iliacă produce doar durere de gambă, fără disfuncție erectilă','Predomină femeile tinere, fără ateroscleroză','Stadiul I înseamnă gangrenă, iar IV este forma asimptomatică'],'AB',1128,'BVP — 7%/4,5% și Fontaine',
 'Reținerea prevalențelor 7/4,5% și a celor patru stadii Fontaine, plus sindromul aorto-iliac.',
 ['Cifrele 7% și 4,5% sunt explicite.','Cele patru stadii Fontaine sunt listate.','Boala aorto-iliacă poate da durere de fesă, șold sau coapsă și disfuncție erectilă, nu doar durere de gambă.','Boala este aterosclerotică, mai frecventă la bărbații de vârstă medie.','Stadiile I și IV sunt inversate în această afirmație.']],
 8,'Inversează stadiile Fontaine I/IV și mută epidemiologia pe femeia tânără fără ateroscleroză.',['7%','4,5%']),

q(202,['Investigațiile imagistice în BVP:',
 ['Ultrasonografia duplex (mod B + Doppler color) este de obicei prima linie: sensibilitate 87%, specificitate 95% versus angiografie','Angio-IRM cu contrast: ambele membre, o singură injecție, fără radiație ionizantă','Angio-CT este alternativă când IRM e contraindicată; calcificările extinse pot masca stenozele','ASD (angiografie cu subtracție digitală) se folosește ca screening de primă intenție la toți asimptomaticii','IGB fals scăzut pe artere calcificate face inutilă presiunea de la degete'],'ABC',1128,'BVP — Duplex 87%/95% și angio-IRM',
 'Ierarhia duplex → IRM → CT, cu ASD rezervată imediat înaintea intervenției.',
 ['87% și 95% sunt cifrele duplexului.','Avantajele IRM sunt descrise.','CT-ul e alternativa; calcificările maschează.','ASD cere canulare și contrast iodat; se folosește imediat anterior intervenției, nu ca screening.','Pe artere calcificate IGB e fals crescut; degetele sunt mai sensibile.']],
 8,'Promovează ASD-ul invaziv ca screening și inversează direcția erorii IGB pe calcificare.',['87%','95%']),

q(203,['Tratamentul medical al claudicației intermitente include:',
 ['Control agresiv al factorilor de risc, din cauza riscului asociat de BCI și boală cerebrovasculară','Program supervizat de exerciții: aerobic până la durerea maximală, cel puțin 2 ore pe săptămână','La diabetici, control glicemic atent și evaluări regulate ale picioarelor','Repaus la pat prelungit, fără efort, pentru a proteja placa','IGB nu se folosește, diagnosticul fiind pur clinic'],'ABC',1128,'BVP — Efort 2 ore/săptămână',
 'Protocolul de 2 ore/săptămână până la durerea maximală și controlul riscului CV asociat.',
 ['Riscul de BCI/AVC justifică controlul agresiv.','Cele 2 ore și pragul durerii maximale sunt explicite.','Diabetul cere control glicemic și îngrijirea picioarelor.','Efortul supervizat este tratament, nu repausul.','IGB stratifică severitatea.']],
 8,'Înlocuiește programul de 2 ore până la durere cu repaus la pat, inversul reabilitării.',['2 ore pe săptămână','claudicaţie intermitentă']),

q(204,['Diagnosticul diferențial al claudicației include:',
 ['Claudicația de canal spinal, în care toate pulsurile sunt prezente','Osteoartrita de șold/genunchi; neuropatia periferică cu amorțeală și furnicături','Claudicația venoasă (tensiune la mers, TVP în antecedente) și boala Buerger (bărbați tineri, mari fumători)','Canalul spinal cu pulsuri absente bilateral, ca în ischemie','Buerger-ul la femei vârstnice nefumătoare, fără ischemie digitală'],'ABC',1128,'BVP — Diagnostic diferențial',
 'Opunerea pulsurilor prezente din canalul spinal față de Buerger-ul tânărului fumător.',
 ['Canalul spinal: pulsuri prezente.','Osteoartrita și neuropatia sunt listate.','Claudicația venoasă și Buerger-ul sunt din listă.','Canalul spinal are pulsuri prezente, nu absente.','Buerger: bărbați tineri, mari fumători.']],
 8,'Atribuie canalului spinal pulsuri absente și mută Buerger-ul pe femeia vârstnică nefumătoare.',['canal spinal','boala Buerger']),

q(205,['Ateroscleroza prematură (sub 45 de ani) în BVP se poate asocia cu:',
 ['Trombofilie și hiperhomocisteinemie','Doar fumatul, fără alte trombofilii','Hipotiroidismul mixedematos ca etiologie dominantă','Pericardita familială','Scor Fontaine 0, inexistent'],'A',1128,'BVP — Ateroscleroză prematură <45 ani',
 'Reținerea asocierii <45 de ani cu trombofilie și hiperhomocisteinemie.',
 ['Textul leagă prematuritatea (<45 ani) de trombofilie și hiperhomocisteinemie.','Fumatul este factor de risc comun, dar nu exclude trombofiliile.','Mixedemul ține de pericard.','Pericardita familială nu explică BVP prematură.','Fontaine începe de la stadiul I.']],
 8,'Omite trombofilia/hiperhomocisteinemia — explicația citată a BVP sub 45 de ani.',['sub 45 ani','hiperhomocisteinemie']),

q(206,['Semnele ischemiei cronice de membru includ:',
 ['Membre reci, piele uscată, pilozitate absentă, pulsuri diminuate sau absente','Ulcerație, colorație închisă a degetelor sau gangrenă; abdomenul se palpează pentru anevrism de aortă','Durerea de repaus trezește din somn și e calmată parțial de atârnarea piciorului sau de podeaua rece','Membre calde, cu pulsuri săltărețe, identic regurgitării aortice','Perimetrul de mers este nereproductibil, spre deosebire de claudicația adevărată'],'ABC',1128,'BVP — Semne și durere de repaus',
 'Recunoașterea tegumentelor ischemic și a manevrei de atârnare a piciorului în durerea de repaus.',
 ['Semnele cutanate și pulsurile sunt descrise.','Ulcerația/gangrena și palparea de AAA sunt explicite.','Caracterul nocturn și ameliorarea prin declivitate sunt din text.','Căldura și pulsul săltăreț sunt ale circulației hiperdinamice, nu ale ischemiei.','Perimetrul de mers poate fi reproductibil.']],
 8,'Atribuie ischemiei pulsul săltăreț al regurgitării aortice și neagă reproductibilitatea perimetrului de mers.',['Durere de repaus','anevrism de aortă']),

q(207,['În Tako-tsubo, cazurile severe și gradientul ventricular:',
 ['Se pot prezenta cu șoc cardiogen și edem pulmonar','Pacienții cu gradient ventricular stâng semnificativ pot răspunde la beta-blocante, administrate cu prudență','Recuperarea completă a funcției survine de obicei în 4-6 săptămâni, cu posibile recurențe','Vasodilatatoarele de primă linie ameliorează gradientul, ca în CMH','Coronarele sunt ocluzate proximal, identic STEMI de IVA'],'ABC',1124,'Tako-tsubo — Șoc, gradient și beta-blocant',
 'Nișa beta-blocantului cu prudență la gradient VS și a prezentării cu șoc/EPA.',
 ['Șocul și EPA sunt descrise în formele severe.','Gradientul poate răspunde la BB cu prudență.','Fereastra 4-6 săptămâni și recurențele sunt explicite.','Vasodilatatoarele agravează obstrucția în CMH; textul nu le pune ca primă linie în Tako-tsubo cu gradient.','Coronarele sunt tipic neobstruate.']],
 8,'Ocluzează coronarele — tocmai elementul care desparte Tako-tsubo de STEMI — și pune vasodilatatorul pe gradient.',['şoc cardio','4-6 săptămâni']),

q(208,['Miocardita acută — dincolo de serologie și IRM:',
 ['Un mic procent evoluează agravat și poate necesita transfer către un centru cu ECMO și/sau transplant','Angiografia coronariană se face adesea pentru a exclude ischemia acută ca mimă','Repaus la pat în faza acută; celulele gigante se asociază cu sarcoidoză, timoame și boli autoimune','Serologia virală înlocuiește biopsia ca gold standard la toți pacienții','Sportul se reia la 48 de ore, chiar în forma fulminantă'],'ABC',1119,'Miocardită — ECMO, coronarografie, celule gigante',
 'Rolul ECMO/transplantului în minoritatea agravată și al coronarografiei de excludere a ischemiei.',
 ['Minoritatea agravată și ECMO/transplantul sunt explicite.','Coronarografia de excludere a ischemiei este menționată.','Repausul acut și asocierile celulelor gigante sunt din text.','Serologia virală de obicei nu este utilă; biopsia e gold standard la fulminant.','Sportul se evită 6 luni.']],
 8,'Pune serologia virală — explicit neutilă — în locul biopsiei de la fulminant și comprimă interdicția sportului la 48 de ore.',['extracorporală','celule gigante']),
];
