import {rewriter} from './rewrite-author';
import {RETIRED_DERMATO} from './retired/dermato';

// Rewritten after the 2026-09-24 cue audit (Sinopsis, cap. 9, p. 196–209).
const q=rewriter(RETIRED_DERMATO,(p:number)=>p-195,{shuffle:true});

export const DERMATO_V2=[
q('dermato-adv-001',['Celulita:',
 ['este produsă cel mai des de streptococul de grup A','are culturi cutanate de regulă utile','se tratează cu cefalosporine orale 10–14 zile','are rată de recurență sub 5% după primul episod','este determinată cel mai frecvent de MRSA'],'AC',196,'Infecții — Celulita',
 'Recunoașterea etiologiei și tratamentului celulitei.',
 ['Streptococul de grup A este cel mai frecvent.','Nu: culturile conțin floră comensală sau sunt fals negative.','Cefalosporinele orale sau β-lactaminele rezistente la penicilinază 10–14 zile.','Recurența este 20–50%.','MRSA este frecvent în abcese.']],
 [8,'Distractorii confundă celulita cu abcesul.'],['streptococul de grup A','10-14 zile']),

q('dermato-adv-018',['Abcesele cutanate:',
 ['sunt determinate cel mai frecvent de stafilococi, de obicei MRSA','au mai frecvent etiologie anaerobă axilar decât perineal','se tratează prin incizie, drenaj și antibiotic anti-MRSA','sunt determinate cel mai frecvent de streptococul de grup A','se tratează doar cu antibiotic, fără drenaj'],'AC',196,'Infecții — Abcesele',
 'Aplicarea etiologiei și tratamentului abceselor cutanate.',
 ['Stafilococii, de obicei MRSA, sunt cei mai frecvenți.','Nu: anaerobii sunt mai frecvenți lombar și perineal.','Incizia și drenajul plus cotrimoxazol.','Streptococul de grup A domină în celulită.','Drenajul este esențial.']],
 [8,'Distractorii confundă abcesul cu celulita.'],['MRSA','perineale'],[197]),

q('dermato-adv-023',['Hidradenita supurativă:',
 ['rezultă din ocluzia foliculară și inflamația glandelor apocrine','produce abcese recurente axilare și inghinale','poate necesita antibiotice și excizie chirurgicală','se vindecă fără cicatrici','afectează predominant glandele ecrine ale palmelor și tălpilor'],'ABC',196,'Infecții — Hidradenita',
 'Recunoașterea hidradenitei supurative.',
 ['Ocluzia foliculară cronică și inflamația glandelor apocrine.','Abcesele recurente apar axilar, inghinal și perineal.','Tratamentul poate necesita antibiotice și excizie.','Nu: infecția cronică duce la cicatrici.','Sunt afectate glandele apocrine.']],
 [8,'Singurul distractor schimbă tipul glandei.'],['glandelor apocrine','cicatricilor']),

q('dermato-adv-002',['Fasceita necrozantă:',
 ['este o infecție polimicrobiană rapid progresivă','produce durere redusă față de examenul obiectiv','poate arăta aer subcutanat pe radiografie sau CT','are mortalitate sub 5%, fără complicații sistemice','se tratează de elecție cu antibiotic oral, fără debridare'],'AC',197,'Infecții — Fasceita necrozantă',
 'Recunoașterea și tratamentul fasceitei necrozante.',
 ['Este polimicrobiană, rapid progresivă.','Nu: durerea este disproporționată față de examenul obiectiv.','RX sau CT pot detecta aer subcutanat.','Mortalitatea este de 25%.','Tratamentul este debridarea rapidă și antibiotice IV.']],
 [8,'Distractorii subestimează gravitatea.'],['polimicrobiană','25%']),

q('dermato-adv-019',['Gangrena uscată are aspect de:',
 ['piele uscată, indurată','bule și tumefacție','cruste de culoarea mierii','papule lucioase ombilicate','plăci cu scuame argintii'],'A',197,'Infecții — Gangrena',
 'Diferențierea gangrenei uscate de cea umedă.',
 ['Necroza prin insuficiență arterială produce piele uscată, indurată.','Descrie gangrena umedă.','Descrie impetigo.','Descrie molluscum.','Descrie psoriazisul.']],
 [8,'Distractorii descriu alte leziuni din capitol.'],['Gangrena uscată','indurată']),

q('dermato-adv-003',['Leziunile caracteristice din impetigo sunt:',
 ['crustele de culoarea mierii','papulele lucioase ombilicate','plăcile cu scuame argintii','șanțurile acariene','papulele perlate cu telangiectazii'],'A',197,'Infecții — Impetigo',
 'Recunoașterea leziunii caracteristice din impetigo.',
 ['Crustele gălbui-aurii, de culoarea mierii, sunt caracteristice.','Descrie molluscum.','Descrie psoriazisul.','Descrie scabia.','Descrie carcinomul bazocelular.']],
 [8,'Distractorii sunt leziuni caracteristice altor boli.'],['culoarea mierii','muco-cutanate']),

q('dermato-adv-033',['Impetigo:',
 ['este determinat frecvent de Staphylococcus aureus','este contagios și frecvent la copii','se tratează local cu mupirocin','se tratează în focare epidemice cu cefalexină orală','se tratează de elecție prin debridare chirurgicală'],'ABCD',197,'Infecții — Impetigo',
 'Aplicarea tratamentului impetigo.',
 ['Staphylococcus aureus este agentul frecvent.','Este contagios, frecvent la copii.','Cazurile localizate primesc mupirocin.','Focarele primesc dicloxacilină sau cefalexină.','Debridarea se aplică fasceitei necrozante.']],
 [8,'Singurul distractor preia tratamentul fasceitei.'],['mupirocin','cefalexină']),

q('dermato-adv-004',['Tratamentul acneei vulgare:',
 ['începe cu isotretinoin oral, înaintea retinoizilor topici','cu isotretinoin impune monitorizarea hepatică','cu isotretinoin cere două teste de sarcină negative','este influențat major de săpunuri','include evitarea alimentelor cu legătură demonstrată'],'BC',198,'Infecții — Acneea vulgară',
 'Aplicarea treptelor terapeutice în acnee.',
 ['Nu: retinoizii topici sunt prima linie.','Isotretinoinul impune monitorizarea hepatică și a hCG.','Sunt necesare două teste de sarcină negative.','Săpunurile au efect redus.','Nu există asociere demonstrată cu alimentele.']],
 [8,'Distractorii contrazic notele explicite.'],['Retinoizii topici','două teste de sarcină']),

q('dermato-adv-034',['Acneea vulgară:',
 ['se asociază cu Propionibacterium acnes','este tratată în linia a doua cu benzoil-peroxid','se agravează la contraceptive orale la femei','la adult poate fi cauzată de corticosteroizi','crește în severitate după adolescență, la adult'],'ABD',198,'Infecții — Acneea vulgară',
 'Recunoașterea cauzelor și terapiilor acneei.',
 ['Se asociază cu Propionibacterium acnes.','Benzoil-peroxidul este terapie de linia a doua.','Nu: contraceptivele orale pot fi utile la femei.','Corticosteroizii și excesul de androgeni cauzează acnee la adult.','Severitatea scade la sfârșitul adolescenței.']],
 [8,'Singurul distractor inversează evoluția.'],['Propionibacterium','Benzoil-peroxidul']),

q('dermato-adv-005',['Infecția cu virusul herpes simplex:',
 ['HSV-1 afectează în principal zona orală','persistă în ganglionii neuro-senzitivi','are infecția primară mai ușoară','este vindecată definitiv de aciclovir','HSV-2 afectează în principal zona orală'],'AB',198,'Infecții — HSV',
 'Recunoașterea caracteristicilor infecției HSV.',
 ['HSV-1 afectează oral, HSV-2 genital.','Materialul genetic viral rămâne în ganglioni.','Nu: infecția primară este mai severă, cu simptome gripale.','Boala este incurabilă.','HSV-2 este genital.']],
 [8,'Distractorii inversează localizarea și curabilitatea.'],['ganglionii neuro-senzitivi','HSV-1']),

q('dermato-adv-035',['Evoluția și tratamentul infecției HSV:',
 ['antiviralele scurtează durata recurențelor','terapia supresivă poate reduce frecvența recurențelor','transmiterea perinatală poate da boală neurologică severă','la imunosupresați rămâne limitată mucocutanat','aciclovirul elimină virusul din ganglionii nervoși'],'ABC',198,'Infecții — HSV',
 'Aplicarea tratamentului și complicațiilor HSV.',
 ['Aciclovirul, famciclovirul, valaciclovirul scurtează recurențele.','Terapia continuă scade frecvența.','Transmiterea perinatală poate da boală diseminată.','Nu: la imunosupresați poate produce encefalită, pneumonie, hepatită.','Boala este incurabilă.']],
 [8,'Singurul distractor contrazice incurabilitatea.'],['supresivă','encefalită']),

q('dermato-adv-006',['Infecția cu virusul varicelo-zosterian:',
 ['varicela debutează la ~2 zile după infecție','zona zoster este limitată la unul sau câteva dermatoame','zona zoster pe mai multe dermatoame distincte înseamnă diseminare','leziunile de varicelă sunt infecțioase până la acoperirea cu cruste','nevralgia postherpetică este complicația tipică a varicelei primare'],'BCD',199,'Tabelul 9-1',
 'Diferențierea varicelei de zona zoster.',
 ['Nu: simptomele apar la 2 săptămâni după infecție.','Zona zoster este limitată dermatomal.','Mai multe dermatoame distincte semnifică diseminare.','Sunt infecțioase până la formarea crustei.','Nevralgia postherpetică complică zona zoster.']],
 [8,'Singurul distractor mută complicația.'],['dermatoame','2 săptămâni']),

q('dermato-adv-036',['Verucile și molluscum contagiosum:',
 ['verucile sunt determinate de HPV','verucile se îndepărtează adesea prin crioterapie','molluscum este o infecție cu HPV','molluscum produce papule lucioase ombilicate','molluscum se tratează cu permetrină, ca scabia'],'ABD',200,'Infecții — Verucile și molluscum',
 'Diferențierea verucilor de molluscum contagiosum.',
 ['Verucile sunt determinate de HPV.','Crioterapia sau acidul salicilic le îndepărtează.','Nu: molluscum este produs de un poxvirus.','Papulele sunt lucioase, ombilicate.','Permetrina tratează scabia.']],
 [8,'Singurul distractor preia tratamentul scabiei.'],['poxvirus','ombilicată']),

q('dermato-adv-007',['Scabia:',
 ['este produsă de Sarcoptes scabiei','produce prurit ameliorat de baia fierbinte','se tratează cu permetrină sau ivermectină','impune spălarea în apă fierbinte a lenjeriei','afectează cel mai frecvent scalpul copiilor'],'ACD',200,'Infecții — Scabia',
 'Recunoașterea și tratamentul scabiei.',
 ['Agentul este Sarcoptes scabiei.','Nu: pruritul se agravează după baia fierbinte.','Permetrina sau ivermectina sunt tratamentul.','Hainele și lenjeria se spală în apă fierbinte.','Sunt afectate cel mai frecvent spațiile interdigitale.']],
 [8,'Singurul distractor schimbă localizarea.'],['Permetrina','baie fierbinte']),

q('dermato-adv-008',['Aspectul de „spaghete și chifteluțe” la preparatul KOH este caracteristic pentru:',
 ['tinea versicolor','tinea corporis','intertrigo candidozic','scabie','molluscum contagiosum'],'A',200,'Tabelul 9-2',
 'Recunoașterea aspectului microscopic al tinea versicolor.',
 ['Malassezia furfur produce hife scurte și spori.','Arată doar hife.','Arată pseudohife.','Arată paraziți și ouă.','Arată corpi de incluziune.']],
 [8,'Distractorii sunt alte infecții cutanate.'],['chifteluţe','Malassezia furfur']),

q('dermato-adv-037',['Tinea corporis, spre deosebire de tinea versicolor:',
 ['are margine activă și atenuare centrală','are macule de culoarea somonului pe torace','arată spaghete și chifteluțe la KOH','are pustule periferice în pliuri','are papule lucioase ombilicate'],'A',200,'Tabelul 9-2',
 'Diferențierea formelor de tinea.',
 ['Plăcile pruriginoase au margine activă și atenuare centrală.','Descrie tinea versicolor.','Descrie tinea versicolor.','Descrie intertrigo candidozic.','Descrie molluscum.']],
 [8,'Distractorii descriu alte infecții.'],['margine activă','Trichophyton']),

q('dermato-adv-024',['Reacțiile de hipersensibilitate cutanată:',
 ['tipul I este mediat de degranularea mastocitelor','tipul I produce urticarie la scurt timp după expunere','tipul IV produce erupție morbiliformă după zile','tipul IV stă la baza dermatitei alergice de contact','tipul I stă la baza dermatitei alergice de contact'],'ABCD',201,'Afecțiuni inflamatorii — Hipersensibilitatea',
 'Diferențierea reacțiilor de tip I și IV.',
 ['Tipul I: degranularea mastocitelor.','Urticaria apare rapid și durează ore.','Tipul IV: erupție la câteva zile după a doua expunere.','Tipul IV explică majoritatea dermatitelor de contact.','Tipul IV este mecanismul.']],
 [8,'Singurul distractor inversează mecanismul.'],['mastocitelor','morbiliformă']),

q('dermato-adv-025',['Dermatita alergică de contact:',
 ['poate fi produsă de nichel și latex','are distribuție liniară, bine definită','se tratează ușor cu corticosteroizi topici','impune epinefrină în angioedemul căilor aeriene','se tratează prin menținerea contactului cu alergenul'],'ABCD',201,'Afecțiuni inflamatorii — Dermatita de contact',
 'Aplicarea diagnosticului și tratamentului dermatitei de contact.',
 ['Plantele, nichelul, săpunurile și latexul sunt cauze frecvente.','Distribuția liniară sugerează cauza externă.','Cazurile ușoare primesc corticosteroizi topici.','Epinefrina se indică în angioedem sau anafilaxie.','Agentul declanșator trebuie îndepărtat.']],
 [8,'Singurul distractor contrazice primul pas.'],['nichelul','angioedem'],[202]),

q('dermato-adv-009',['Eritemul polimorf:',
 ['se asociază frecvent cu peniciline și antiepileptice','are HSV și Mycoplasma drept cauze infecțioase frecvente','prezintă leziuni cu distribuție dermatomală, ca zona zoster','arată acantoliză la biopsie, ca pemfigusul vulgar','afectează peste 30% din suprafața corporală'],'AB',202,'Afecțiuni inflamatorii — Eritemul polimorf',
 'Recunoașterea eritemului polimorf.',
 ['Penicilinele, sulfonamidele, AINS, contraceptivele și antiepilepticele sunt frecvente.','HSV și Mycoplasma pneumoniae sunt cauze frecvente.','Nu: leziunile caracteristice sunt în țintă.','Biopsia arată limfocite și keratinocite necrotice.','Descrie necroliza epidermică toxică.']],
 [8,'Distractorii preiau trăsăturile pemfigusului și TEN.'],['Mycoplasma','leziuni în ţintă']),

q('dermato-adv-010',['Sindromul Stevens-Johnson și necroliza epidermică toxică:',
 ['SSJ afectează sub 10% din suprafața corporală','TEN afectează peste 30% din suprafața corporală','SSJ are semnul Nikolsky negativ','TEN scade numărul leucocitelor și hemoglobina','SSJ se tratează în ambulatoriu, fără hidratare'],'ABD',202,'Afecțiuni inflamatorii — SSJ și TEN',
 'Diferențierea SSJ de TEN.',
 ['SSJ afectează mucoasele și <10% BSA.','TEN depășește 30% BSA.','Nu: Nikolsky este pozitiv în SSJ.','TEN scade leucocitele, hemoglobina și hematocritul.','Se tratează adesea în secțiile de arși.']],
 [8,'Singurul distractor contrazice gravitatea.'],['<10%','>30%'],[203]),

q('dermato-adv-026',['Dermatita seboreică:',
 ['este o hiperproliferare cronică a epidermului','se asociază cu Malassezia','este cunoscută la nou-născut ca „crusta de lapte”','are scuame galbene, grăsoase','are scuame argintii pe suprafețele de extensie'],'ABCD',203,'Afecțiuni inflamatorii — Dermatita seboreică',
 'Recunoașterea dermatitei seboreice.',
 ['Este o hiperproliferare cronică epidermică.','Se asociază cu Malassezia.','Cradle cap este forma de pe scalpul nou-născutului.','Plăcile au scuame galbene, grăsoase.','Scuamele argintii caracterizează psoriazisul.']],
 [8,'Singurul distractor descrie psoriazisul.'],['Malassezia','Cradle cap']),

q('dermato-adv-020',['Dermatita atopică:',
 ['are ca factori de risc astmul și rinita alergică','afectează la adult suprafețele de flexie','afectează la nou-născut mai ales fața și scalpul','afectează la adult suprafețele de extensie','are semnul Auspitz pozitiv'],'ABC',203,'Afecțiuni inflamatorii — Dermatita atopică',
 'Recunoașterea distribuției dermatitei atopice.',
 ['Astmul, rinita alergică și istoricul familial sunt factori de risc.','La adult sunt afectate flexoarele.','La nou-născut: față și scalp.','Extensia este afectată în psoriazis.','Auspitz caracterizează psoriazisul.']],
 [8,'Distractorii preiau trăsăturile psoriazisului.'],['rinită alergică','flexie']),

q('dermato-adv-011',['Semnul Auspitz din psoriazis constă în:',
 ['sângerarea plăcii la îndepărtarea scuamei','decolarea epidermului la frecare','depresiuni punctiforme ale unghiei','apariția unei plăci unice înaintea erupției','distribuția în brad de Crăciun'],'A',203,'Afecțiuni inflamatorii — Psoriazisul',
 'Recunoașterea semnului Auspitz.',
 ['Placa sângerează ușor la îndepărtarea scuamei.','Descrie semnul Nikolsky.','Descrie pitting-ul unghial.','Descrie placa heraldică.','Descrie pitiriazisul rozat.']],
 [8,'Distractorii sunt alte semne dermatologice.'],['Auspitz','scuamei']),

q('dermato-adv-038',['Psoriazisul:',
 ['poate produce pitting unghial','arată la biopsie absența stratului granulos','se asociază cu artrită psoriazică la 10–20%','poate fi tratat sever cu metotrexat sau ciclosporină','afectează predominant flexoarele membrelor'],'ABCD',203,'Afecțiuni inflamatorii — Psoriazisul',
 'Recunoașterea caracteristicilor și tratamentului psoriazisului.',
 ['Pot apărea pitting și onicoliză.','Biopsia arată absența stratului granulos.','10–20% au artrită psoriazică.','Fototerapia, metotrexatul și ciclosporina se folosesc în boala severă.','Plăcile sunt pe suprafețele de extensie.']],
 [8,'Singurul distractor inversează distribuția.'],['stratului granulos','10-20%']),

q('dermato-adv-021',['Pitiriazisul rozat:',
 ['începe cu placa heraldică, de până la 5 cm','are distribuție în brad de Crăciun','este autolimitat, tratat cu steroizi topici','are semnul Auspitz patognomonic','afectează peste 30% din suprafața corporală'],'ABC',203,'Afecțiuni inflamatorii — Pitiriazisul rozat',
 'Recunoașterea pitiriazisului rozat.',
 ['Placa heraldică precede erupția cu câteva zile.','Distribuția este în brad de Crăciun.','Boala este autolimitată.','Auspitz caracterizează psoriazisul.','Descrie TEN.']],
 [8,'Distractorii preiau trăsăturile psoriazisului și TEN.'],['heraldice','brad de Crăciun'],[204]),

q('dermato-adv-027',['Eritemul nodos:',
 ['produce noduli dureroși, de obicei pretibiali','este o reacție imunologică de tip întârziat','poate arăta paniculită la biopsie','se tratează cu AINS și iodură de potasiu','are semnul Nikolsky pozitiv, cu decolare epidermică'],'ABCD',204,'Afecțiuni inflamatorii — Eritemul nodos',
 'Recunoașterea eritemului nodos.',
 ['Nodulii dureroși sunt de obicei pretibiali.','Este o reacție de tip întârziat.','Biopsia arată paniculită.','Tratamentul include AINS și iodură de potasiu.','Nikolsky caracterizează pemfigusul și SSJ.']],
 [8,'Singurul distractor preia un semn bulos.'],['paniculită','iodură de potasiu']),

q('dermato-adv-012',['Pemfigusul vulgar, spre deosebire de pemfigoidul bulos:',
 ['are autoanticorpi contra moleculelor de adeziune epidermică','are semnul Nikolsky pozitiv','arată acantoliză cu membrană bazală intactă','afectează majoritar pacienții peste 65 de ani','are autoanticorpi contra membranei bazale'],'ABC',205,'Afecțiuni buloase',
 'Diferențierea pemfigusului de pemfigoid.',
 ['Autoanticorpii vizează moleculele de adeziune epidermice.','Nikolsky este pozitiv.','Biopsia arată acantoliză cu membrană bazală intactă.','Pemfigoidul afectează majoritar peste 65 de ani.','Descrie pemfigoidul.']],
 [8,'Distractorii preiau trăsăturile pemfigoidului.'],['acantoliză','moleculelor de adeziune'],[206]),

q('dermato-adv-041',['Pemfigoidul bulos:',
 ['are autoanticorpi contra membranei bazale','are semnul Nikolsky negativ','afectează majoritar pacienți peste 65 de ani','se tratează cu corticosteroizi sau azatioprină','are imunofluorescență cu anticorpi anti-epidermici'],'ABCD',205,'Afecțiuni buloase — Pemfigoidul',
 'Recunoașterea pemfigoidului bulos.',
 ['Autoanticorpii vizează membrana bazală.','Nikolsky este negativ.','Majoritatea au peste 65 de ani.','Tratamentul: corticosteroizi sau azatioprină.','Imunofluorescența arată anticorpi anti-membrană bazală.']],
 [8,'Singurul distractor preia imunofluorescența pemfigusului.'],['membranei bazale','azatioprină'],[206]),

q('dermato-adv-013',['Porfiria cutanată tardivă:',
 ['este determinată de deficitul de uroporfirinogen-decarboxilază','are drept factori de risc alcoolul și hepatita C','produce hipertricoză și hiperpigmentare','se tratează prin flebotomie periodică','se tratează cu suplimente de fier pentru anemia asociată'],'ABCD',206,'Afecțiuni buloase — Porfiria cutanată tardivă',
 'Recunoașterea porfiriei cutanate tardive.',
 ['Deficitul de uroporfirinogen-decarboxilază hepatică.','Alcoolul, hepatita C, fierul și estrogenii sunt factori de risc.','Pielea este hiperpigmentată, cu hipertricoză.','Flebotomia periodică este tratamentul.','Suplimentele de fier trebuie evitate.']],
 [8,'Singurul distractor contrazice evitarea fierului.'],['uroporfirinogen','flebotomie']),

q('dermato-adv-028',['Keratoza seboreică este:',
 ['o tumoră benignă cu aspect „lipit pe piele”','o leziune precanceroasă spre carcinom scuamocelular','o papulă perlată cu telangiectazii','o placă eritematoasă care metastazează','o papulă eritemato-scuamoasă pe zone expuse la soare'],'A',206,'Neoplasme — Keratoza seboreică',
 'Diferențierea keratozei seboreice de leziunile maligne.',
 ['Tumoră benignă din keratinocite imature, verucoasă, hiperpigmentată.','Descrie keratoza actinică.','Descrie carcinomul bazocelular.','Descrie carcinomul scuamocelular.','Descrie keratoza actinică.']],
 [8,'Distractorii descriu leziuni precanceroase sau maligne.'],['lipit pe piele','keratinocite imature']),

q('dermato-adv-029',['Keratoza actinică:',
 ['este o leziune benignă, fără potențial malign','evoluează spre carcinom scuamocelular în ~0,1% pe an','se tratează cu 5-fluorouracil topic sau imiquimod','impune biopsie pentru excluderea carcinomului','evoluează spre carcinom scuamocelular în ~10% pe an'],'BCD',206,'Neoplasme — Keratoza actinică',
 'Aplicarea riscului și tratamentului keratozei actinice.',
 ['Nu: keratoza actinică este o leziune precanceroasă.','Riscul este de aproximativ 0,1% pe an.','Tratamentul: 5-FU, imiquimod, crioterapie.','Biopsia exclude carcinomul scuamocelular.','Riscul este 0,1% pe an.']],
 [8,'Singurul distractor umflă riscul.'],['0,1%','imiquimod']),

q('dermato-adv-014',['Cancerele cutanate non-melanocitare:',
 ['carcinomul bazocelular este cel mai frecvent cancer cutanat','carcinomul scuamocelular metastazează în 40–50%','carcinomul bazocelular arată celule bazale în palisade','carcinomul bazocelular metastazează frecvent','carcinomul scuamocelular se dezvoltă rar din keratoze actinice'],'AC',207,'Neoplasme — Carcinoamele',
 'Diferențierea carcinoamelor bazocelular și scuamocelular.',
 ['Bazocelularul este cel mai frecvent.','Nu: scuamocelularul metastazează în 5–10%.','Biopsia bazocelularului arată palisade bazofile.','Bazocelularul metastazează rar.','60% se dezvoltă din keratoze actinice.']],
 [8,'Distractorii inversează riscul metastatic și originea.'],['palisade','5-10%'],[206]),

q('dermato-adv-030',['Criteriile ABCDE de monitorizare a nevilor includ:',
 ['asimetria','bordurile neregulate','culoarea variabilă','diametrul peste 6 mm','durerea la palpare'],'ABCD',208,'Neoplasme — Melanomul',
 'Aplicarea criteriilor ABCDE.',
 ['Asimetria este criteriu.','Marginile neregulate sunt criteriu.','Culoarea variabilă este criteriu.','Diametrul >6 mm este criteriu.','Leziunea este de obicei nedureroasă.']],
 [8,'Singurul distractor nu este criteriu.'],['ABCDE','>6']),

q('dermato-adv-016',['Melanomul:',
 ['are grosimea tumorii drept cel mai important factor prognostic','extensiv în suprafață este tipul cel mai frecvent','nodular crește doar vertical','lentigo malign rămâne mult timp in situ','se biopsiază de elecție prin biopsie shave'],'ABCD',208,'Neoplasme — Melanomul',
 'Recunoașterea tipurilor și prognosticului melanomului.',
 ['Grosimea (>0,76 mm) este cel mai important factor.','Extensivul în suprafață este cel mai frecvent.','Nodularul crește vertical și devine rapid invaziv.','Lentigo malign rămâne mult timp in situ.','Biopsia shave nu trebuie folosită.']],
 [8,'Singurul distractor contrazice o regulă explicită.'],['grosimea tumorii','Nodular'],[207]),

q('dermato-adv-042',['Melanomul — tratament și evoluție:',
 ['in situ se excizează cu margine de 0,5 cm','sub 2 mm grosime se excizează cu margine de 1 cm','peste 2 mm grosime se excizează cu margine de 2 cm','acral lentiginos afectează palmele, tălpile și patul unghial','in situ se excizează cu margine de 2 cm, ca leziunile groase'],'ABCD',208,'Neoplasme — Melanomul',
 'Aplicarea marginilor de excizie după grosime.',
 ['In situ: 0,5 cm.','Sub 2 mm: 1 cm.','Peste 2 mm: 2 cm.','Acralul lentiginos afectează palmele, tălpile și patul unghial.','Marginea in situ este 0,5 cm.']],
 [8,'Singurul distractor permută marginea.'],['0,5 cm','patul unghia']),

q('dermato-adv-017',['Grefa de piele despicată (split skin):',
 ['conține epiderm și o parte din derm','se recoltează de pe abdomen, coapse sau fese','nu se contractă în timp','se recoltează tipic de deasupra urechilor','conține epiderm și tot dermul'],'AB',209,'Tabelul 9-3',
 'Recunoașterea caracteristicilor grefei despicate.',
 ['Conține epiderm și o parte din derm.','Locurile donatoare sunt abdomenul, coapsele, fesele.','Nu: grefa despicată se contractă în timp.','Retroauricular se recoltează grefa cu grosime completă.','Descrie grefa cu grosime completă.']],
 [8,'Distractorii descriu grefa cu grosime completă.'],['despicată','Abdomen, coapse, fese']),

q('dermato-adv-022',['Grefa cu grosime completă este compusă din:',
 ['epiderm și tot dermul','epiderm și o parte din derm','țesut subcutanat, fără epiderm','piele cu cartilaj și pat unghial','mușchi transferat fără piele'],'A',209,'Tabelul 9-3',
 'Diferențierea tipurilor de grefe.',
 ['Conține epiderm și tot dermul.','Descrie grefa despicată.','Nu este grefa citată.','Descrie grefa compozită.','Descrie lamboul muscular.']],
 [8,'Distractorii descriu celelalte grefe și lambouri.'],['grosime','tot dermul']),

q('dermato-adv-032',['Grefele de piele pot fi:',
 ['autogrefe, din țesutul aceluiași pacient','alogrefe, de la un alt donator uman','xenogrefe, de la altă specie','lambouri de rotație sau translație','grefe recoltate doar retroauricular'],'ABC',209,'Chirurgie plastică — Grefe și lambouri',
 'Clasificarea grefelor după origine.',
 ['Autogrefa provine de la același pacient.','Alogrefa provine de la alt donator.','Xenogrefa provine din altă specie.','Lamboul liber nu este o grefă de piele după origine.','Există trei tipuri.']],
 [8,'Distractorii confundă grefa cu lamboul.'],['autogrefe','xenogrefe']),
];
