import {advancedQuestion} from './advanced-author';
import type {SourceRow} from './source-author';
const q=(n:number,row:SourceRow,score:number,reason:string,expressions:string[],related:number[]=[])=>
 advancedQuestion('diabet',23,-601,`diabet-adv-${String(n).padStart(3,'0')}`,row,[score,reason],expressions,undefined,related);

export const DIABET_C=[
q(83,['Diabetul zaharat, ca tulburare endocrină, este descris în text ca:',
 ['Cea mai răspândită și importantă din punct de vedere clinic, afectând aproximativ 10% din populația adultă din majoritatea țărilor','O urgență rar întâlnită, fără internări','O boală limitată la copii, fără complicații cardiovasculare','O afecțiune acută autolimitată, fără echipă multidisciplinară','O specialitate chirurgicală, fără medicină internă'],'A',699,'Introducere — Aptitudini și noțiuni de bază',
 'Reținerea formulării de „cea mai răspândită tulburare endocrină” și a prevalenței de circa 10% la adulți.',
 ['Aceasta este fraza de deschidere a capitolului.','Urgențele diabetice sunt cauze frecvente de internare.','Complicațiile CV, renale, oculare și neurologice limitează speranța de viață.','Textul subliniază caracterul cronic și rolul echipei multidisciplinare.','Consultanții sunt instruiți în diabet, endocrinologie și medicină internă generală.']],
 8,'Preluarea cifrei de 10% din prima frază, cu distractori care neagă internarea și caracterul cronic.',['10% din populaţia adultă','tulburarea endocrină']),

q(84,['Anamneza din cadranul 23.1 include, printre altele:',
 ['Dacă pacientul este conducător auto sau are activități cu risc crescut în caz de hipoglicemie','Dacă își monitorizează glicemia capilară sau glucoza interstițială și ține un jurnal','Lungimea acelor folosite pentru injectarea insulinei și rotația locurilor','Omiterea oricărei întrebări despre hipoglicemie, aceasta nefiind relevantă','Înlocuirea istoricului de urgențe cu un singur IMC, suficient pentru tot riscul'],'ABC',700,'Cadranul 23.1 — Anamneza în diabet',
 'Recunoașterea itemilor de siguranță (conducere, jurnal, ace) din anamneza standard.',
 ['Conducerea și activitățile cu risc figurează explicit.','Monitorizarea capilară/interstițială și jurnalul sunt rubrici distincte.','Lungimea acelor și rotația locurilor sunt întrebări de tratament.','Episoadele de hipoglicemie și nevoia de ajutor extern sunt itemi centrali.','IMC-ul ține de evaluarea anuală; anamneza rămâne multidimensională.']],
 8,'Taie din cadran tocmai itemii de siguranță (conducere, hipoglicemie), păstrând restul plauzibil.',['conducători auto','lungime au acele']),

q(85,['La examenul de picior (cadranul 23.3), semnele de boală vasculară periferică includ:',
 ['Paloare sau decolorare și pierderea părului','Tegumente reci și pulsuri periferice absente','Timp redus de reumplere capilară și semne de gangrenă sau infecție','Tegumente calde, cu pulsuri vizibile, ca în neuropatia pură','Piele uscată hiperemică, fără evaluare a pulsurilor'],'ABC',700,'Cadranul 23.3 — Examenul de picior',
 'Reținerea constellationii ischemice (paloare, tegumente reci, pulsuri absente, reumplere redusă).',
 ['Paloarea și pierderea părului sunt primele caracteristici listate.','Tegumentele reci și absența pulsurilor continuă lista.','Reumplerea capilară redusă și gangrena/infecția închid rubricile vasculare.','Tegumentele calde cu pulsuri vizibile caracterizează piciorul neuropat, nu ischemia.','Evaluarea pulsurilor, începând de la picior, este cerută explicit.']],
 8,'Inversează tabloul ischemic cu cel neuropat din cadranul de diferențiere de mai târziu.',['Paloare, decolorare','Timp redus de reumplere']),

q(86,['La examenul obiectiv, semnele cutanate și osteoarticulare asociate diabetului includ:',
 ['Contractură Dupuytren și limitarea mobilității articulare','Granuloame anulare și buloza diabetică','Vitiligo și acanthosis nigricans axilar','Eritem nodos ca semn patognomonic de tip 1','Psoriazis palmoplantar ca marker de deficit absolut de insulină'],'ABC',701,'Examenul obiectiv — Tegumente; Mâini',
 'Separarea semnelor autoimune (vitiligo) de cele de rezistență (acanthosis) și de Dupuytren/buloza.',
 ['Dupuytren și limitarea mobilității articulare figurează la mâini.','Granuloamele anulare și buloza diabetică sunt listate la tegumente.','Vitiligo (autoimun, tip 1) și acanthosis (insulinorezistență) sunt juxtapuse.','Eritemul nodos nu este semnul cutanat din această figură.','Psoriazisul nu orientează spre deficitul absolut de insulină.']],
 8,'Înlocuiește Dupuytren/buloza cu dermatoze din alte capitole, păstrând registrul cutanat.',['Contractură Dupuytren','Buloza diabetică'],[700]),

q(87,['Secreția de insulină la nivelul celulei beta este declanșată astfel:',
 ['Glucoza intră prin GLUT-2, strâns asociat cu glucokinaza','ATP-ul rezultat închide canalele de potasiu, cu depolarizare și influx de calciu','Creșterea calciului activează protein-kinaza dependentă de Ca2+ și exocitoza granulelor de insulină','Glucoza iese prin GLUT-4 al celulei beta, fără glucokinază','Canalele de potasiu se deschid sub ATP, hiperpolarizând membrana și blocând calciul'],'ABC',705,'Fig. 23.4 — Reglarea secreției de insulină',
 'Succesiunea GLUT-2 → glucokinază → ATP → închiderea K+ → Ca2+ → exocitoză.',
 ['Intrarea prin GLUT-2 și cuplajul cu glucokinaza deschid figura.','Închiderea canalelor de K+ și influxul de Ca2+ sunt pașii a și b.','Protein-kinaza dependentă de calciu duce la fuziunea granulelor.','GLUT-4 este transportorul periferic (mușchi/adipos), nu al celulei beta.','ATP închide, nu deschide, canalele de K+.']],
 8,'Inversează GLUT-2/GLUT-4 și sensul efectului ATP asupra canalelor de K+.',['GLUT-2','glucokinază']),

q(88,['Diabetul de tip 1, conform datelor din 2017:',
 ['Peste un milion de copii și adolescenți aveau tip 1, cu circa 132.600 de cazuri noi pe an','Incidența maximă este în jurul pubertății, dar se poate întâlni la orice vârstă','Cele mai mari rate sunt în nordul Europei și în Orientul Mijlociu','LADA este varianta cu progresie lentă a deficitului de insulină, apărută mai târziu în viață','Tipul 1B (non-mediat imun) reprezintă marea majoritate în țările occidentale'],'ABCD',705,'Diabetul de tip 1 — Epidemiologie; LADA',
 'Cuantificarea poverii pediatrice 2017 și recunoașterea LADA ca progresie lentă, distinctă de 1A dominant occidental.',
 ['Cifrele 1 milion și 132.600 sunt explicite.','Vârful pubertar cu posibilitate la orice vârstă este descris.','Geografia nord-europeană și a Orientului Mijlociu este citată.','Definiția LADA este dată în încheiere.','Marea majoritate în Occident au tipul 1A (mediat imun), nu 1B.']],
 8,'Inversează ponderea 1A/1B occidentală, deși textul o precizează imediat după clasificare.',['un milion de copii','LADA']),

q(89,['Ghidul nutrițional din cadranul 23.10 încurajează, printre altele:',
 ['Reducerea consumului de sare la <6 g/zi','Consumul a două porții de pește gras pe săptămână','Limitarea alcoolului la ≤14 unități/săptămână','Creșterea cărnii roșii procesate și a băuturilor îndulcite','Sarea nerestricționată, alcoolul fără plafon săptămânal'],'ABC',713,'Cadranul 23.10 — Ghiduri nutriționale',
 'Reținerea triadei sare <6 g, două porții de pește gras și ≤14 unități de alcool.',
 ['Pragul <6 g/zi de sare este o caracteristică esențială a dietei mediteraneene citate.','Cele două porții de pește gras pe săptămână sunt listate.','Plafonul ≤14 unități/săptămână închide lista.','Textul cere reducerea cărnii roșii procesate și a băuturilor îndulcite.','Atât sarea cât și alcoolul au plafoane explicite.']],
 8,'Cele trei praguri numerice stau în aceeași listă; distractorii inversează direcția alimentelor „de evitat”.',['<6 g/zi','14 unită']),

q(90,['Tratamentul imediat al hipoglicemiei conștiente se face cu:',
 ['15–20 g glucoză orală, repetate după 15 minute dacă glicemia nu a crescut peste 4,0 mmol/L','2 g de sucroză, o singură dată, fără reevaluare','500 ml glucoză 50% oral, pentru a evita recurența','Insulină rapidă, pentru a „echilibra” evenimentul','Oprirea oricărui aport de carbohidrați până a doua zi'],'A',717,'Tratamentul hipoglicemiei',
 'Aplicarea dozei 15–20 g și a reevaluării la 15 minute față de pragul 4,0 mmol/L.',
 ['Doza, intervalul și pragul 4,0 mmol/L sunt explicite; nu se dau mai mulți carbohidrați decât este necesar.','2 g este sub doza citată.','Excesul de carbohidrați este descurajat, pentru a preveni rebound-ul hiperglicemic.','Insulina agravează hipoglicemia.','După recuperare se dau carbohidrați cu acțiune mai lungă, pentru glicogen.']],
 8,'15–20 g și 15 minute/4,0 mmol/L trebuie ținute împreună; distractorii schimbă ordinul de mărime.',['15-20 g glucoză','peste 4,0 mmol/l']),

q(91,['Glucagonul intramuscular în hipoglicemia severă:',
 ['Acționează prin mobilizarea glicogenului hepatic și funcționează aproape la fel de rapid ca glucoza','Poate fi administrat și acasă, de către aparținători','Nu funcționează când glicogenul hepatic este scăzut, de exemplu după un post prelungit','Odată revenit, pacientul trebuie să consume carbohidrați cu acțiune mai lungă, pentru a reînnoi rezervele de glicogen','Este ineficace la domiciliu și se rezervă doar sălii de operație'],'ABCD',717,'Hipoglicemia severă — Glucagon',
 'Articularea mecanismului glicogenic, a administrării la domiciliu și a eșecului după post prelungit.',
 ['Mecanismul și viteza comparabilă cu glucoza sunt explicite.','Simplitatea administrării la domiciliu este subliniată.','Postul prelungit (glicogen hepatic scăzut) este excepția de ineficacitate.','Carbohidrații cu acțiune lungă după revenire reînnoiesc glicogenul.','Textul precizează tocmai că administrarea este simplă și posibilă acasă.']],
 8,'Neagă administrarea la domiciliu — avantajul practic pe care textul îl opune glucozei i.v.',['glicogenului hepatic','post prelungit']),

q(92,['Metforminul: mecanism, eficacitate și contraindicații:',
 ['Poate implica activarea AMP-kinazei; reduce gluconeogeneza hepatică și crește sensibilitatea la insulină, fără a induce hipoglicemie','Scade glicemia bazală cu 2–4 mmol/L, corespunzând unei scăderi HbA1c de 11–22 mmol/mol (1–2%)','Nu se inițiază la RFGe <45 ml/min/1,73 m² și se oprește sub 30 ml/min/1,73 m²','Se oprește înaintea contrastului iodat i.v. și se reia după 48 de ore dacă funcția renală nu s-a deteriorat','Induce hipoglicemie severă de rutină și se inițiază indiferent de RFGe'],'ABCD',717,'Biguanidele: metforminul',
 'Integrarea pragurilor RFGe 45/30, a ferestrei de 48 de ore post-contrast și a magnitudinii 2–4 mmol/L.',
 ['Mecanismul AMPK și absența hipoglicemiei sunt descrise.','Cifrele 2–4 mmol/L și 11–22 mmol/mol sunt cele de eficacitate.','Cele două praguri RFGe sunt explicite.','Regula contrastului iodat și a reluarii la 48 de ore este citată.','Metforminul nu induce hipoglicemie și are praguri clare de RFGe.']],
 8,'45 versus 30 ml/min se inversează ușor; distractorul adaugă o hipoglicemie pe care textul o neagă.',['45 ml/min/1,73m2','48 de ore']),

q(93,['Metforminul reduce absorbția gastrointestinală a vitaminei:',
 ['A','D','B12, dar produce rar anemie','K','C, cu scorbut de rutină'],'C',717,'Metformin — Efecte adverse',
 'Reținerea interferenței cu B12, distinctă de riscul (rar) de anemie.',
 ['Vitamina A nu este citată.','Vitamina D nu este citată aici.','Reducerea absorbției de B12, cu anemie rară, este precizarea din text.','Vitamina K nu figurează.','Scorbutul nu este efectul descris.']],
 8,'B12 este unica vitamină numită; distractorii sunt vitamine plauzibile din alte contexte de malabsorbție.',['vitaminei B12','produce rar anemie']),

q(94,['Sulfonilureele, ca efecte nedorite și supraveghere:',
 ['Creșterea în greutate este de obicei 1–4 kg; hipoglicemia afectează circa o cincime dintre cei tratați','Hipoglicemia severă indusă de sulfoniluree trebuie supravegheată în spital 48 de ore, cu glucoză până la eliminarea medicamentului','Riscul de hipoglicemie crește la derivații cu acțiune mai lungă, alcool excesiv, vârstă înaintată și infecții intercurente','Nu au efect la tipul 1, lipsind masa de celule beta funcționale','Hipoglicemia severă se externează imediat, fără supraveghere, medicamentul fiind inactiv în 30 de minute'],'ABCD',718,'Sulfonilureele — Efecte adverse',
 'Cuantificarea hipoglicemiei (o cincime) și a ferestrei de 48 de ore de supraveghere spitalicească.',
 ['1–4 kg și o cincime sunt cifrele de tolerabilitate.','Cele 48 de ore de supraveghere sunt explicite.','Lista de factori care cresc riscul este enumerată.','Ineficacitatea în tipul 1, prin lipsa celulelor beta, este mecanismul.','Eliminarea lentă impune tocmai supravegherea de 48 de ore, nu externarea imediată.']],
 8,'48 de ore (supraveghere) se confundă cu dispariția „în 30 de minute” a unei hipoglicemii cu insulină rapidă.',['o cincime','48 de ore'],[717]),

q(95,['Meglitinidele (insulinosecretagoge post-prandiale):',
 ['Închid canalul K+-ATP în celulele beta, ca sulfonilureele','Sunt metabolizate rapid, cu durată de acțiune sub 3 ore','Pot fi utile la vârstnicii fragili, unde evitarea hipoglicemiei este imperioasă','Au durată de 24 de ore, superioară glibenclamidului','Sunt mai eficiente decât celelalte orale, cu rol bine stabilit ca primă linie universală'],'ABC',718,'Meglitinidele',
 'Reținerea duratei <3 ore și a nișei geriatric-fragile, distincte de pretenția de primă linie.',
 ['Mecanismul comun cu sulfonilureele este explicit.','Durata sub 3 ore este cifra cheie.','Utilitatea la vârstnicii fragili este menționată.','Durata scurtă, nu 24 de ore, le deosebește.','Textul le consideră mai puțin eficiente, cu rol neclar.']],
 8,'Extinde durata scurtă la 24 de ore și le promovează ca primă linie, contrar evaluării din text.',['mai mică de 3 ore','persoanele în vârstă, fragile']),

q(96,['Pioglitazona (tiazolidindione):',
 ['Reduce rezistența la insulină prin PPAR-γ; efectul maxim pe glucoză poate dura până la 3 luni','Creșterea în greutate de 5–6 kg este cel mai frecvent efect advers; retenția de fluide poate precipita insuficiența cardiacă','Poate fi benefică în steatoza hepatică non-alcoolică','Troglitazona rămâne de primă alegere, fără toxicitate hepatică','Efectul pe glucoză este imediat, în minute, ca al analogilor rapizi'],'ABC',718,'Tiazolidindionele sau „glitazonele”',
 'Asocierea PPAR-γ și a ferestrei de 3 luni cu toxicitatea de retenție/IC și cu nișa NAFLD.',
 ['Receptorul PPAR-γ și întârzierea de până la 3 luni sunt explicite.','5–6 kg și retenția de fluide/IC sunt efectele adverse centrale.','Beneficiul în NAFLD este menționat.','Troglitazona a fost retrasă pentru toxicitate hepatică.','Efectul este indirect, lent, nu imediat.']],
 8,'3 luni (maxim) versus minute (analogi rapizi) este contrastul de cinetică; distractorul reînvie troglitazona retrasă.',['până la 3 luni','5-6 kg']),

q(97,['Agoniștii receptorilor de GLP-1:',
 ['Nu trebuie combinați cu inhibitori DPP-4, inhibitorul neconferind beneficiu suplimentar','Studiile head-to-head arată scăderi HbA1c de 9–19 mmol/mol (0,8–1,8%) și ponderale de 0,6–4,3 kg','Nu trebuie folosiți la persoane cu antecedente de pancreatită, crescând riscul de pancreatită acută','Se asociază de rutină cu un DPP-4, pentru sinergie incretinică maximă','Sunt contraindicate în obezitate, deoarece cresc greutatea'],'ABC',720,'Agoniști GLP-1 — Utilizare clinică; Efecte adverse',
 'Interdicția asocierii cu DPP-4, magnitudinea HbA1c/greutate și contraindicația după pancreatită.',
 ['Absența beneficiului DPP-4 în combinație este explicită.','Intervalele 9–19 mmol/mol și 0,6–4,3 kg sunt din comparațiile directe.','Antecedentele de pancreatită contraindică clasa.','Asocierea cu DPP-4 este tocmai cea descurajată.','Scăderea ponderală îi face potriviți la obezi, nu contraindicați.']],
 8,'Inversează regula „nu se asociază cu DPP-4” și direcția ponderală.',['inhibitori de DPP-4','pancreatită']),

q(98,['Pramlintida, analog de amilină:',
 ['Este aprobată în SUA pentru tipul 1 sau 2 tratat cu insulină','Amilina este co-secretată cu insulina, întârzie golirea gastrică, suprimă glucagonul post-prandial și crește sațietatea','Nu este utilizată pe scară largă','Înlocuiește insulina bazală ca monoterapie universală în Europa','Accelerează golirea gastrică și stimulează glucagonul'],'ABC',720,'Analogii de amilină',
 'Recunoașterea indicației americane pe lângă insulină și a celor trei acțiuni fiziologice ale amilinei.',
 ['Aprobarea FDA pentru T1/T2 insulinat este explicită.','Cele trei acțiuni (golire, glucagon, sațietate) sunt enumerate.','Utilizarea limitată este precizată.','Nu înlocuiește insulina; este adjuvant.','Acțiunile sunt întârzierea golirii și supresia glucagonului, nu opusul.']],
 8,'Inversează efectele asupra golirii gastrice și glucagonului — tocmai mecanismul clasei.',['Pramlintida','co-secretată împreună cu insulina']),

q(99,['Auto-monitorizarea glicemiei capilare și MCG:',
 ['Sângele se obține din partea laterală a pulpei degetului, nu din partea superioară, dens inervată','Senzorii MCG pot fi purtați, la unele dispozitive, până la 14 zile','Dezavantajul principal al MCG este intervalul de 15–20 de minute între modificările glicemiei și glucoza interstițială','La simptome de hipoglicemie se testează glucoza capilară, chiar dacă citirea MCG este normală','Puncția se face din vârful degetului, zona cea mai puțin inervată'],'ABCD',721,'Auto-monitorizarea; Monitorizarea continuă a glucozei',
 'Articularea locului de puncție, a duratei senzorului (14 zile) și a lag-ului 15–20 de minute.',
 ['Partea laterală versus superioară (dens inervată) este instrucțiunea de recoltare.','Cele 14 zile sunt durata maximală citată.','Lag-ul 15–20 de minute este dezavantajul principal.','Testul capilar la simptome, indiferent de MCG, este regula de prudență.','Partea superioară este dens inervată; se evită.']],
 8,'14 zile și 15–20 de minute stau pe aceeași pagină; distractorul inversează locul de puncție.',['partea laterala a pulpei','15-20 de minute'],[720]),

q(100,['O valoare fals scăzută a HbA1c poate rezulta din:',
 ['Deficit de fier','Insuficiență renală','Infecție HIV','Anemie hemolitică, hemoragie acută/cronică sau sarcină (durată de viață eritrocitară scăzută)','Creșterea duratei de viață a eritrocitelor'],'D',721,'Cadranul 23.16 — Limitările HbA1c',
 'Separarea cauzelor de durată scurtă (fals scăzut) de cele de durată lungă (fals crescut).',
 ['Deficitul de fier dă valori fals crescute.','Insuficiența renală figurează la fals crescut.','HIV figurează la fals crescut.','Anemia hemolitică, hemoragia și sarcina scad durata de viață și dau HbA1c fals scăzută.','Durata crescută dă fals crescut, nu scăzut.']],
 8,'Toate opțiunile sunt din același cadran; trebuie recunoscut sensul durată scurtă → fals scăzut.',['Anemia hemolitică','Sarcina']),

q(101,['Variabilitatea biologică a HbA1c include faptul că, la o medie glicemică de 10 mmol/L, HbA1c poate fi între:',
 ['4,0 și 4,2% (20–22 mmol/mol)','6,0 și 9,0% (42–75 mmol/mol), reflectând diferențe în rata de glicare','12 și 15% la toți pacienții, fără excepție','HbA1c identică la toți indivizii cu aceeași medie','Valori negative, HbA1c nefiind o proteină glicată'],'B',721,'Cadranul 23.16 — Variabilitate inter-individuală',
 'Reținerea intervalului 6,0–9,0% (42–75 mmol/mol) la aceeași medie de 10 mmol/L.',
 ['4% este prea jos față de exemplul din cadran.','Exemplul 10 mmol/L → 6,0–9,0% (42–75 mmol/mol) este cel din text.','12–15% nu este intervalul citat.','Tocmai variabilitatea inter-individuală face HbA1c neidentică.','HbA1c este hemoglobina glicată; valorile negative nu există.']],
 8,'6,0–9,0% la 10 mmol/L este exemplul numeric unic din cadran, ușor de înlocuit cu praguri de diagnostic.',['10 mmol/L','6,0% şi 9,0%']),

q(102,['Nefropatia diabetică clasică:',
 ['Se manifestă de obicei la 15–25 de ani după diagnostic și afectează 25–35% dintre cei diagnosticați înainte de 30 de ani','Este principala cauză de deces prematur la pacienții tineri cu diabet','Leziunile nodulare sunt cunoscute ca leziuni Kimmelstiel-Wilson','Odată atinsă proteinuria persistentă, boala renală terminală apare în 5–10 ani, cu rată interindividuală variabilă','Apare în primele 6 săptămâni de la diagnostic, la toți pacienții cu tip 2'],'ABCD',730,'Nefropatia diabetică — Istoric natural',
 'Articularea ferestrei 15–25 de ani, a ponderii 25–35% și a intervalului 5–10 ani până la ESKD după proteinurie persistentă.',
 ['Cele două intervale 15–25 ani și 25–35% sunt de deschidere.','Rolul de cauză principală de deces prematur la tineri este explicit.','Eponimul Kimmelstiel-Wilson este dat leziunilor nodulare.','5–10 ani până la ESKD după proteinuria persistentă, cu variabilitate, este istoria naturală.','Debutul este tardiv (ani), nu în săptămâni, și nu universal la tipul 2.']],
 8,'15–25 ani versus 5–10 ani (după proteinurie) se amestecă ușor; distractorul comprimă istoria la 6 săptămâni.',['15-25 ani','Kimmelstiel-Wilson']),

q(103,['Raportul albumină/creatinină (RAC) din prima urină de dimineață este, la persoanele sănătoase, mai scăzut de:',
 ['2,5 mg/mmol la bărbați și 3,5 mg/mmol la femei','25 mg/mmol la ambele sexe, fără diferență','0,1 mg/mmol, identic cu proteinuria nefrotică','50 mg/mmol ca prag de normalitate','RAC nu se folosește, stripul standard detectând microalbuminuria'],'A',730,'Screeningul nefropatiei — RAC',
 'Reținerea pragurilor diferențiate pe sexe (2,5 vs 3,5 mg/mmol) și a nevoii de repetare (fals pozitive frecvente).',
 ['Acestea sunt pragurile din text; microalbuminuria detectată se repetă de două ori.','25 mg/mmol depășește normalul citat.','0,1 mg/mmol nu este pragul.','50 mg/mmol nu este normalitatea.','Stripurile standard nu detectează microalbuminuria; de aceea se folosește RAC.']],
 8,'2,5 (bărbați) versus 3,5 (femei) sunt perechea ușor de inversat sau de omogenizat.',['2,5 mg/mmol','3,5 mg/mmol']),

q(104,['Nefropatia diabetică non-clasică:',
 ['O proporție scăzută din tipul 1 și până la 50% din tipul 2 au scăderea progresivă a RFG cu albuminurie redusă sau absentă','Anemia normocromă normocitară, VSH și CRP crescute sunt asocieri tipice','Suspiciunea unei cauze non-diabetice crește în absența retinopatiei și în prezența hematiilor urinare','Albuminuria masivă este condiția sine qua non a oricărei nefropatii diabetice','Biopsia renală este necesară de rutină la toți cei cu microalbuminurie confirmată'],'ABC',730,'Nefropatia non-clasică; Alte caracteristici',
 'Recunoașterea fenotipului cu RFG în scădere fără albumină (până la 50% din tipul 2) și a indiciilor pentru altă cauză.',
 ['Fracția de până la 50% din tipul 2 este explicită.','Anemia normocromă normocitară și markerii inflamatori sunt asocieri tipice.','Absența retinopatiei și hematuria orientează spre altă cauză; biopsia se consideră, dar e rar necesară.','Forma non-clasică are tocmai albuminurie redusă sau absentă.','Biopsia este rareori necesară sau utilă.']],
 8,'Transformă forma non-clasică (fără albumină) într-o cerință de proteinurie nefrotică.',['până la 50%','anemie normocromă nor­mocitară']),

q(105,['La testarea funcției autonome la pat, sunt anormale:',
 ['Scăderea TA sistolice în clino-ortostatism ≥30 mmHg (normal ≤10 mmHg)','Diferența FC max–min la 6 respirații profunde/min ≤10 (normal ≥15)','O scădere ortostatică de 2 mmHg, în limitele variației normale','Tahicardia de efort ca unică dovadă de denervare','Absența oricărei modificări tensionale, interpretată ca boală autonomă certă'],'AB',732,'Cadranul 23.23 — Testarea funcției autonome',
 'Aplicarea pragurilor ≥30 mmHg (TA) și ≤10 bătăi (variație respiratorie) care definesc răspunsul anormal.',
 ['≥30 mmHg versus normalul de 10 mmHg este contrastul din cadran.','≤10 versus ≥15 la 6 respirații/min este a doua linie.','2 mmHg este în zona normală (≤10).','Cadranul folosește TA ortostatică și variația respiratorie, nu tahicardia de efort izolată.','Absența variației tensionale nu echivalează, singură, cu diagnosticul de neuropatie autonomă.']],
 8,'10 versus 30 mmHg și 15 versus 10 bătăi sunt perechile din același tabel, ușor de inversat.',['2:30','6 respiraJii']),

q(106,['Polineuropatia simetrică distală se caracterizează prin:',
 ['Senzația de „a umbla pe vată” și pierderea echilibrului la spălatul pe față sau mersul în întuneric (propriocepție alterată)','Implicarea timpurie a mâinilor este mai puțin frecventă și cere cauze non-diabetice','Atrofia interosoasă duce la boltă înaltă și degete în gheară, cu calozități sub capul primului metatarsian','Mâinile pot avea atrofii ale mușchilor mici, de diferențiat de tunelul carpian, mai frecvent în diabet','Implicarea mâinilor în primele săptămâni este regula, fără a căuta altă cauză'],'ABCD',732,'Neuropatia diabetică — Polineuropatia simetrică',
 'Integrarea ataxiei proprioceptive cu deformarea în boltă/gheară și cu diagnosticul diferențial de tunel carpian.',
 ['„A umbla pe vată” și pierderea echilibrului sunt simptomele de deschidere.','Regula mâinilor tardive este explicită.','Secvența motorie interosoasă → boltă/gheară → calozități este descrisă.','Frecvența crescută a tunelului carpian cere diferențiere.','Implicarea precoce a mâinilor nu este regula și impune altă cauză.']],
 8,'Deformarea de picior (boltă/gheară) se confundă cu ischemia; distractorul anulează regula mâinilor tardive.',['a umbla pe vată','boltă înaltă']),

q(107,['O caracteristică a leziunii diabetice de nerv III este că:',
 ['Este dureroasă, cu midriază fixă, fără recuperare','Este nedureroasă, cu reflexe pupilare păstrate (fibrele pupilomotorii neafectate), iar recuperarea integrală spontană în 3–6 luni este regula pentru majoritatea mononevritelor','Impune decompresie chirurgicală de urgență în primele 3 ore','Se asociază constant cu hemipareză contralaterală','Nu atinge nervul VI, doar nervul optic'],'B',732,'Mononevrita — Nervii oculomotori',
 'Reținerea sparing-ului pupilar și a ferestrei de recuperare 3–6 luni, distincte de anevrismul dureros cu midriază.',
 ['Tabloul dureros cu midriază orientează spre compresie anevrismală, nu spre mononevrita diabetică.','Nedorința, reflexele păstrate și recuperarea 3–6 luni sunt textul.','Decompresia nu este tratamentul descris; recuperarea este spontană.','Hemipareza nu face parte din mononevrita de NC III.','Și nervul VI este citat ca frecvent implicat.']],
 8,'Sparing-ul pupilar deosebește mononevrita de compresia de sinus cavernos/anevrism; 3–6 luni este fereastra de recuperare.',['reflexele pupilare sunt păstrate','3-6 luni']),

q(108,['Neuropatia acută dureroasă:',
 ['Poate fi prezentă de la diagnostic sau după ameliorarea bruscă a controlului (ex. inițierea insulinei)','Se remite de obicei spontan după 3–12 luni dacă controlul glicemic este menținut','NICE recomandă duloxetină, triciclice, gabapentin, pregabalin ca primă linie','Atrofia musculară masivă este regula, cu deficit motor obiectiv marcat de la început','Remisiunea nu apare nici după ani de euglicemie, forma acută fiind identică celei cronice tardive'],'ABC',732,'Neuropatia acută dureroasă',
 'Separarea formei acute (3–12 luni, după intensificare) de cea cronică rezistentă și de lista NICE de primă linie.',
 ['Momentul de la diagnostic sau după intensificare este explicit.','Fereastra 3–12 luni este cea de remisiune.','Cele patru clase NICE de primă linie sunt enumerate.','Atrofia lipsește; semnele obiective pot fi minime, cu hiperestezie.','Forma acută se remite; cea cronică tardivă este rezistentă.']],
 8,'3–12 luni (remisiune acută) versus rezistența formei cronice sunt contrastul din același paragraf.',['3-12 luni','Duloxetina']),

q(109,['Disfuncția erectilă la bărbații cu diabet:',
 ['Prevalența globală este 35–40%, crescând la circa 60% peste 60 de ani','Prima manifestare este erecția incompletă, cu posibilă ejaculare retrogradă în neuropatia autonomă','Inhibitorii PDE-5 sunt prima linie la cei fără nitrați; circa 60% dintre bărbații cu diabet beneficiază','Se dozează LH, FSH, testosteron, prolactină și funcția tiroidiană','PDE-5 se asociază de rutină cu nitrații antianginoși, pentru sinergie vasculară'],'ABCD',733,'Disfuncția sexuală',
 'Cuantificarea 35–40%/60% și a răspunsului PDE-5 (~60%), plus panelul hormonal înainte de tratament.',
 ['Cele două prevalențe pe vârstă sunt juxtapuse.','Erecția incompletă și ejacularea retrogradă sunt descrise.','PDE-5 ca primă linie, fără nitrați, cu răspuns ~60%, este explicit.','Panelul LH/FSH/testosteron/prolactină/tiroidă este lista de laborator.','Asocierea cu nitrații este tocmai contraindicația.']],
 8,'35–40%, 60% (vârstă) și 60% (răspuns PDE-5) sunt trei cifre alăturate, ușor de amestecat cu indicația nitraților.',['35-40%','sildenafil']),

q(110,['Alprostadilul intrauretral se începe, conform textului, de la 125 µg până la un maxim de:',
 ['50 µg','250 µg','500 µg; dacă partenera este gravidă, este necesar un contraceptiv de tip barieră','5 mg oral, ca sildenafilul','Nicio prostaglandină nu se folosește uretral'],'C',733,'Disfuncția sexuală — Tratamente alternative',
 'Reținerea plafonului 500 µg uretral și a precauției de barieră dacă partenera este gravidă, distinct de injecția 2,5–40 µg.',
 ['50 µg este sub doza inițială (125 µg).','250 µg nu este maximul citat.','Maximul 500 µg și contraceptivul de barieră la parteneră gravidă sunt explicite.','Calea este uretrală, nu orală ca PDE-5.','Alprostadil uretral figurează ca alternativă.']],
 8,'500 µg (uretral) versus 40 µg (intracavernos) sunt plafoanele alăturate din aceeași listă.',['125 µg','maxim de 500 µg']),

q(111,['Afecțiunile piciorului diabetic:',
 ['Până la 50% dintre vârstnicii cu tip 2 au factori de risc; 10–15% dezvoltă ulcere plantare de-a lungul vieții','Sunt responsabile pentru aproape 50% din internările legate de diabet','Diabetul este cea mai frecventă cauză de amputații non-traumatice de membru inferior','Ulcerele plantare sunt rare (<1%) și nu justifică internarea','Amputațiile diabetice nu pot fi prevenite prin autoîngrijire'],'ABC',733,'Piciorul diabetic — Epidemiologie',
 'Reținerea dublei cifre de 50% (risc la vârstnici; ponderea internărilor) și a intervalului 10–15% pentru ulcere.',
 ['50% factori de risc și 10–15% ulcere sunt de deschidere.','Cei 50% din internări sunt cifra următoare.','Întâietatea ca cauză de amputație non-traumatică este explicită.','Ulcerele nu sunt rare; 10–15% este povara de-a lungul vieții.','Textul subliniază că multe amputații ar putea fi prevenite prin autoîngrijire.']],
 8,'Cele două „50%” (risc vs internări) și 10–15% (ulcere) se țin împreună; distractorii minimizează povara.',['10-15% din pacienţii','aproape 50%']),

q(112,['Neuroartropatia Charcot, după faza acută, se stabilizează de obicei în:',
 ['24 de ore, fără imobilizare','6–12 luni; recuperarea cere imobilizare îndelungată în orteză, uneori cu chirurgie reparatorie','3 zile de mers nerestricționat','O săptămână de AINS, fără orteză','Nicio consolidare, distrucția continuând indefinit la toți'],'B',733,'Neuroartropatia Charcot',
 'Reținerea ferestrei 6–12 luni până la consolidare și a ortezei până la dispariția edemului și a căldurii locale.',
 ['24 de ore este faza acută, nu consolidarea.','6–12 luni, orteza și chirurgia reparatorie sunt descrierea evoluției.','Mersul liber agravează distrucția.','AINS-ul izolat nu înlocuiește imobilizarea.','Procesul se stabilizează, nu continuă indefinit.']],
 8,'6–12 luni (stabilizare) se confundă cu săptămânile de distrucție rapidă din faza netratată.',['6-12 luni','orteză']),

q(113,['Screeningul anual al piciorului include testarea cu monofilament aplicat perpendicular, care se îndoaie la o forță de:',
 ['1 g','5 g','10 g; perceperea acestui nivel conferă sensibilitate protectoare împotriva ulcerațiilor plantare','100 g, rezervat ischemiei critice','Monofilamentul este abandonat în favoarea radiografiei de rutină'],'C',734,'Cadranul 23.25; Screeningul piciorului',
 'Reținerea pragului de 10 g care definește sensibilitatea protectivă plantară.',
 ['1 g este sub pragul protector citat.','5 g nu este forța din text.','10 g și semnificația protectivă sunt explicite.','100 g nu este testul de sensibilitate protectivă.','Monofilamentul este evaluarea reproductibilă recomandată, alături de Doppler.']],
 8,'10 g este pragul unic; distractorii sunt ordine de mărime adiacente.',['forţă de 10 g','sensibilitate protectoare']),

q(114,['Principiile îngrijirii piciorului (cadranul 23.25) includ:',
 ['Inspecție zilnică, hidratarea pielii uscate și prudență la mersul desculț','Verificarea încălțămintei (interior și exterior) înainte de purtare și distanța față de surse de căldură','A nu se trata calozitățile fără ajutor profesional; vizite periodice la pedichiurist/podiatru','Tratarea calozităților acasă cu lame, fără consult','Mersul desculț pe nisip fierbinte, ca terapie de „călire”'],'ABC',734,'Cadranul 23.25 — Principiile îngrijirii piciorului',
 'Reținerea interdicției de autotiraj al calozităților și a evității surselor de căldură (nisip, sticle, radiatoare).',
 ['Inspecția zilnică, hidratarea și mersul desculț figurează în deschidere.','Verificarea încălțămintei și distanța față de căldură sunt itemi expliți.','Calozitățile fără ajutor profesional și vizitele la podiatru închid lista.','Autotirajul calozităților este tocmai interzis.','Nisipul fierbinte este o sursă de căldură de evitat.']],
 8,'Transformă interdicțiile (calozități, nisip fierbinte) în „terapii”, inversul cadranului de prevenție.',['Inspecţia zilnică','calozităţile']),

q(115,['Infecțiile piciorului diabetic, denumite uneori „atac de picior”:',
 ['Trebuie tratate ca urgențe medicale, cu antibiotice cu spectru larg precoce, apoi ajustate după culturi','Microorganismele de la suprafața pielii pot să nu fie cele ale infecției profunde','Radiografii regulate sunt necesare pentru a verifica evoluția; osul infectat poate necesita excizie în osteomielită neresponsivă','Se amână antibioticul până la identificarea certă a germenului de suprafață','Radiografia este superfluă, osteomielita neexistând în diabet'],'ABC',734,'Infecția — Piciorul diabetic',
 'Aplicarea logicii de urgență („atac de picior”), a neîncrederii în cultura de suprafață și a urmăririi radiologice a osteomielitei.',
 ['Urgența și spectrul larg precoce sunt explicite.','Neconcordanța suprafață–profund este avertismentul microbiologic.','Radiografiile de control și excizia osului neresponsiv sunt pașii următori.','Așteptarea culturii de suprafață întârzie un tratament care trebuie început precoce.','Osteomielita este o complicație descrisă, nu o absență.']],
 8,'Cultura de suprafață este capcana: textul cere să nu se amâne spectrul larg pentru ea.',['atac de picior','osteomielitei']),

q(116,['Cheia vindecării unui ulcer de picior diabetic este:',
 ['Purtarea continuă a greutății pe zona ulcerată, pentru „stimulare”','Asigurarea faptului că piciorul afectat nu susține greutatea corpului (pantofi/branțuri/orteze de descărcare)','Oprirea debridării, calozitățile protejând arhitectura plăgii','Antibiotice topice ca unică măsură, fără descărcare','Mersul intens imediat după închidere, fără încălțăminte specială'],'B',734,'Ulcerațiile piciorului',
 'Reținerea descărcării (off-loading) ca element central, urmată de debridare ascuțită a calozităților în piciorul neuropat.',
 ['Purtarea greutății pe ulcer împiedică vindecarea.','Descărcarea cu pantofi, branțuri sau orteze este cheia citată.','Debridarea chirurgicală ascuțită a calozităților este necesară, mai ales în neuropatie.','Antibioticele nu înlocuiesc descărcarea.','După vindecare sunt necesari pantofi speciali pe termen lung.']],
 8,'Off-loading-ul este ușor de înlocuit cu „stimularea prin mers”, inversul principiului.',['nu susţine greutatea','debridarea chirurgicală']),

q(117,['Cataracta acută „în fulg de zăpadă” poate apărea în contextul:',
 ['Unui control foarte slab de durată, cu un grad de cetoză','Unei HbA1c de 5%, fără hiperglicemie','Unei extracții de cristalin, ca efect invariabil al implantului','Unui deficit de fier izolat, fără diabet','Unei hipoglicemii unice, corectate oral'],'A',729,'Alte moduri — Cataracta',
 'Asocierea cataractei acute în fulg de zăpadă cu controlul foarte slab și cetoza.',
 ['Controlul foarte slab de durată cu cetoză este contextul descris.','HbA1c joasă nu produce această cataractă.','Extracția cu implant este tratamentul, nu cauza.','Deficitul de fier ține de artefactul HbA1c, nu de cataractă.','O hipoglicemie unică nu este mecanismul denaturării proteinelor cristalinului.']],
 8,'Eponimul „fulg de zăpadă” este legat de cetoză/control slab, nu de tratamentul chirurgical.',['cataractă în fulg de zăpadă','grad de cetoză']),

q(118,['Fotocoagularea panretinală în retinopatia proliferativă:',
 ['Se folosește când au apărut vase noi pe discul optic; rubeoza se tratează tot prin panretinală','Principiul este reducerea stimulului ischemic prin distrugerea retinei periferice','Câmpul vizual devine permanent mai îngust, cu reducerea adaptării la întuneric: periferia este sacrificată pentru centrul vizual','Lărgește câmpul vizual și îmbunătățește vederea nocturnă','Se evită pe disc, vasele de neoformație discale având prognostic bun fără laser'],'ABC',729,'Fotocoagularea laser',
 'Înțelegerea sacrificiului periferic (câmp îngust, adaptare nocturnă redusă) ca preț al salvării maculei.',
 ['Indicația de vase pe disc și rubeoza sunt explicite.','Distrugerea periferiei ischemice reduce stimulul de neoformație.','Efectele adverse (câmp îngust, adaptare redusă) sunt consecința principială.','Laserul îngustează, nu lărgește, câmpul.','Vasele de pe disc au cel mai nefast prognostic și cer laser de urgență.']],
 8,'Inversează prognosticul vaselor discale și direcția efectului asupra câmpului vizual.',['fotocoagulare panretinală','adaptării la întuneric']),

q(119,['Fenofibratul, în retinopatia diabetică:',
 ['Încetinește progresia retinopatiei, inclusiv a edemului macular','Este recomandată și oprirea fumatului','O deteriorare pe termen scurt poate urma ameliorării rapide a glicemiei, sarcinii sau nefropatiei','Accelerează edemul macular, fiind contraindicat oftalmologic','Fumatul protejează retina și trebuie încurajat'],'ABC',729,'Tratament — Control glicemic; Fenofibrat',
 'Recunoașterea rolului fenofibratului asupra edemului macular și a paradoxului deteriorării după intensificare/sarcină.',
 ['Încetinirea progresiei, inclusiv maculopatia, este atribuită fenofibratului.','Oprirea fumatului este recomandată alături.','Deteriorarea pe termen scurt după intensificare, sarcină sau nefropatie este avertismentul.','Fenofibratul încetinește, nu accelerează, edemul macular.','Fumatul nu este protector; se recomandă oprirea.']],
 8,'Paradoxul „mai bine glicemic → mai rău pe termen scurt la retină” este capcana; fenofibratul se confundă cu un agent dăunător.',['fenofibrat','edemului macu']),

q(120,['Injecțiile intravitreene anti-VEGF (bevacizumab, aflibercept, ranibizumab):',
 ['Pot controla retinopatia proliferativă și maculopatia potențial cauzatoare de cecitate','Au beneficii suplimentare față de laser în acest tip de maculopatie','Efectele adverse includ infecții, glaucom, cataractă sau dezlipire de retină','Triamcinolonul reduce edemul macular pe termen scurt','Înlocuiesc orice laser, fără risc de infecție sau glaucom'],'ABCD',729,'Injecțiile intravitreene',
 'Ierarhia anti-VEGF versus laser în maculopatie și recunoașterea listei de adverse intraoculare.',
 ['Controlul proliferativului și al maculopatiei amenințătoare este indicația.','Superioritatea față de laser în maculopatie este din studii citate.','Infecția, glaucomul, cataracta și dezlipirea sunt lista de adverse.','Triamcinolonul are efect scurt, util când alte tratamente țin mai mult.','Anti-VEGF nu anulează riscurile intraoculare și nu fac laserul superfluu în proliferativ.']],
 8,'Lista de adverse (infecție, glaucom, cataractă, dezlipire) este ușor de omis când se reține doar beneficiul față de laser.',['bevacizumab','triamcinolon']),

q(121,['Anumite microorganisme sunt descrise ca mai virulente în medii hiperglicemice, printre care:',
 ['Serotipuri de Klebsiella și Burkholderia pseudomallei','Pneumocystis, ca unică etiologie a otitei externe maligne','Virusul gripal, fără legătură cu hiperglicemia','Saprofiți cutanați nepatogeni în orice context','Mycobacterium bovis, rezistent la pirazinamidă, ca germene al fasceitei'],'A',735,'Infecțiile',
 'Reținerea perechii Klebsiella / B. pseudomallei ca exemple de virulență augmentată de hiperglicemie.',
 ['Aceste două exemple sunt cele din paragraf, alături de otita externă malignă, pielonefrita emfizematoasă și fasceita necrozantă.','Pneumocystis nu este germenele otitei externe maligne din acest text.','Virusurile (hepatita C, tratamentul HIV) cresc riscul de diabet, nu virulența în hiperglicemie în acest exemplu.','Textul vorbește de virulență crescută, nu de saprofiți inofensivi.','M. bovis ține de capitolul de TB, nu de lista de virulență hiperglicemică.']],
 8,'Klebsiella și B. pseudomallei sunt perechea de nișă; distractorii importă germeni din pneumologie.',['Klebsiella','Burkho/deria pseudomallei']),

q(122,['Selectați enunțurile adevărate despre infecții și diabet:',
 ['Hepatita C și tratamentul pentru HIV/SIDA','Imunitatea umorală pare relativ neafectată, deși hiperglicemia tulbură imunitatea înnăscută','Vaccinarea antigripală anuală, ca factor etiologic major','Deficitul de B12 indus de metformin, ca virus lent','Otita externă malignă, ca infecție virală de primă intenție'],'AB',735,'Infecțiile — Virusuri și risc de diabet',
 'Asocierea hepatitei C și a terapiei HIV/SIDA cu contrastul imunitate înnăscută versus umorală.',
 ['Hepatita C și tratamentul HIV/SIDA sunt cele două situații citate.','Contrastul înnăscut afectat / umoral relativ păstrat deschide paragraful de infecții.','Vaccinarea antigripală nu este incriminată ca etiologie a diabetului.','B12 este un efect al metforminului, nu un virus.','Otita externă malignă este o infecție severă favorizată de microangiopatie, nu un virus cauzator de diabet.']],
 8,'Hepatita C și terapia HIV sunt ușor de înlocuit cu infecții severe listate în același paragraf (otita malignă).',['hepatita C','HIV /SIDA']),
];
