import {advancedQuestion} from './advanced-author';
import type {SourceRow} from './source-author';
const q=(n:number,row:SourceRow,score:number,reason:string,expressions:string[],related:number[]=[])=>
 advancedQuestion('diabet',23,-601,`diabet-adv-${String(n).padStart(3,'0')}`,row,[score,reason],expressions,undefined,related);

export const DIABET_D=[
q(123,['Sub-specializările descrise pentru diabetologi includ:',
 ['Diabetul în sarcină','Tehnologie (pompe de insulină și monitorizare continuă a glucozei)','Transplant de pancreas sau de celule insulare','Formare limitată la chirurgie bariatrică, fără medicină internă','Oprirea oricărei activități de ambulator, internarea fiind regula'],'ABC',699,'Introducere — Sub-specializări',
 'Recunoașterea celor trei nișe (sarcină, tehnologie, transplant), distincte de formarea în medicină internă.',
 ['Sarcina figurează ca domeniu de sub-specializare.','Pompele și MCG sunt rubrica de tehnologie.','Transplantul de pancreas sau insule este listat.','Consultanții se formează și în medicină internă generală.','Majoritatea persoanelor sunt văzute în ambulator.']],
 8,'Lista de sub-specializări se reduce ușor la bariatrică, deși textul o plasează alături de internă.',['diabetul în sar','transplant de pancreas']),

q(124,['La examenul obiectiv, semnele cutanate, oculare și generale asociate diabetului includ:',
 ['Necrobioza lipoidică la membrele inferioare','Xantelasmă palpebrală și candidoză orală','Respirație Kussmaul și ptoză din paralizia nervului III','Eritem nodos palmoplantar, ca semn de deficit absolut de insulină','Psoriazisul unghiilor, ca marker de insulinorezistență'],'ABC',701,'Examenul obiectiv — Tegumente; Ochi; Respirație',
 'Separarea necrobiózei și xantelasmei de urgența acidotică (Kussmaul) și de paralizia de NC III.',
 ['Necrobioza lipoidică este listată la membre.','Xantelasma și candidoza orală figurează la ochi/gură.','Kussmaul și ptoza de NC III sunt pe schema de examen.','Eritemul nodos nu este semnul din această figură.','Psoriazisul nu orientează spre insulinorezistență aici.']],
 8,'Necrobioza și xantelasma stau pe aceeași schemă cu Dupuytren/buloza, deja folosite, și se omit ușor.',['Necrobioza lipoidică','xantelasmă']),

q(125,['Structura, secreția și clearance-ul insulinei, conform textului:',
 ['Este un hormon peptidic de 51 de aminoacizi, cu lanțurile A și B, sintetizat în celulele β ale insulelor Langerhans','Aproximativ 50% din insulina secretată este extrasă și degradată în ficat; restul este descompus de rinichi','Peptidul C este extras doar parțial hepatic și degradat în principal de rinichi','Insulina este un steroid de 21 de carboni, sintetizat în corticosuprarenală','Peptidul C este extras 90% la primul pasaj hepatic, identic cu insulina'],'ABC',702,'Fiziologia insulinei — Structură; Clearance',
 'Cuplarea celor 51 de aminoacizi cu extracția hepatică de 50% și clearance-ul renal al peptidului C.',
 ['Cifra de 51 de aminoacizi și originea β sunt explicite.','Jumătatea extrasă hepatic este citată.','Contrastul peptid C versus insulină la ficat/rinichi este precizat.','Insulina nu este un steroid.','Peptidul C este extras doar parțial, nu 90%.']],
 8,'50% hepatic se atribuie greșit peptidului C, deși textul rezervă extracția majoră rinichiului.',['51 de aminoacizi','Aproximativ 50%']),

q(126,['Consumul cerebral de glucoză, la o persoană de 70 kg, este descris ca:',
 ['1 mg/kg/min, adică aproximativ 100 g pe zi; preluarea nu depinde de insulină','10 g pe zi, strict insulinodependentă prin GLUT-4','500 g pe zi, acoperită doar din gluconeogeneza renală','Zero în repaus, creierul oxidând numai acizi grași','Identic cu necesarul muscular, ambele dependente de GLUT-4'],'A',703,'Utilizarea glucozei — Creierul',
 'Reținerea pachetului 1 mg/kg/min ≈ 100 g/zi și a independenței de insulină.',
 ['Debitul și independența de insulină sunt juxtapuse.','10 g/zi nu este cifra; GLUT-4 nu mediază creierul în acest paragraf.','Gluconeogeneza renală este restul producției, nu tot necesarul cerebral.','Creierul depinde de glucoză, nu de acizi grași.','Mușchiul, nu creierul, folosește GLUT-4 insulinodependent.']],
 8,'100 g/zi cerebral se schimbă ușor cu 200 g/zi producție totală de pe aceeași pagină.',['1 mg/kg greutate','aproximativ 100 g pe zi']),

q(127,['Producția zilnică de glucoză, conform textului:',
 ['Peste 90% din cele circa 200 g utilizate zilnic derivă din glicogenul hepatic și gluconeogeneza hepatică','Restul provine din gluconeogeneza renală','Ficatul stochează glucoza ca glicogen postabsorbtiv și o eliberează între mese','Creierul produce 200 g/zi prin glicogen neuronal','Gluconeogeneza renală acoperă peste 90% din necesar'],'ABC',703,'Producția de glucoză',
 'Ierarhia ficat (>90% din 200 g) versus rinichi (restul), distinctă de consumul cerebral de 100 g.',
 ['Cifrele 90% și 200 g sunt explicite.','Contribuția renală este restul.','Rolul bifazic al ficatului este descris.','Creierul consumă, nu produce, glucoza.','Rinichiul nu acoperă 90%.']],
 8,'200 g (producție) și 100 g (creier) stau pe aceeași pagină și se inversează ca sediu.',['200 g glucoză','gluconeogeneza renală']),

q(128,['Transportorii GLUT și hormonii de contrareglare:',
 ['Funcția GLUT-1–3 este independentă de insulină; insulina stimulează absorbția în mușchi și adipos prin GLUT-4','Când glicemia scade sub normal, se secretă glucagon din celulele α, plus noradrenalină, cortizol și hormon de creștere','Hormonii de contrareglare cresc producția hepatică de glucoză și reduc utilizarea în adipos și mușchi, independent de nivelul insulinei','GLUT-4 este independent de insulină, iar GLUT-1 este translocat de insulină în neuron','Glucagonul se secretă din celulele β, odată cu insulina, când glicemia scade'],'ABC',704,'Transportul glucozei; Reglarea hormonală',
 'Contrastul GLUT-1–3 versus GLUT-4 și lista de contrareglare (glucagon α, NA, cortizol, GH).',
 ['Independența GLUT-1–3 și rolul GLUT-4 sunt explicite.','Răspunsul la hipoglicemie este listat.','Efectul hepatic/periferic independent de insulină este precizat.','Direcția GLUT este inversată în distractor.','Glucagonul vine din celulele α, nu β.']],
 8,'GLUT-4 se mută greșit pe neuron, iar glucagonul pe celula β, două permutări din același paragraf.',['GLUT-1-3','hormoni de contrareglare']),

q(129,['Clasificarea diabetului primar și secundar, conform textului:',
 ['Diabetul gestațional este intoleranța la glucoză care apare pentru prima dată în sarcină','Diabetul secundar se împarte, printre altele, în defecte genetice, boli pancreatice exocrine, boli endocrine, medicamente și infecții','Aproximativ 1–3% din cazurile diagnosticate înainte de 30 de ani sunt monogenice','Tipul 1 reprezintă 90% din toate cazurile, fără deficit de insulină','Formele primare exclud tipul 2, rezervat doar secundarului medicamentos'],'ABC',704,'Clasificarea diabetului',
 'Definirea gestaționalului, lista de secundar și ponderea 1–3% monogenic sub 30 de ani.',
 ['Definiția gestaționalului este explicită.','Categoriile de secundar sunt enumerate.','Intervalul 1–3% înainte de 30 de ani este citat.','Tipul 1 este 5–10% din cazuri, cu deficit sever.','Tipul 2 este primar, nu un secundar medicamentos.']],
 8,'1–3% monogenic se confundă cu 5–10% tip 1 de pe pagina următoare.',['1-3% din cazurile','Diabetul gestaţional']),

q(130,['Diabetul de tip 1, ca pondere și spectru imunologic:',
 ['Reprezintă 5–10% din toate cazurile de diabet și se caracterizează prin deficit de insulină','Este împărțit în tipul 1A (mediat imun) și 1B (non-mediat imun); marea majoritate în țările occidentale au 1A','LADA este varianta cu progresie mai lentă a deficitului, apărută mai târziu în viață','Este 90% din diabetul mondial, fără autoimunitate','Tipul 1B reprezintă marea majoritate în Occident'],'ABC',705,'Diabetul de tip 1 — Epidemiologie; 1A/1B; LADA',
 'Separarea ponderii 5–10% de majoritatea 1A occidentală și de LADA.',
 ['5–10% și deficitul sunt fraza de deschidere.','Diviziunea 1A/1B și predominanța occidentală a 1A sunt explicite.','LADA este definit ca progresie lentă tardivă.','90% este ponderea tipului 2, nu a tipului 1.','În Occident predomină 1A, nu 1B.']],
 8,'5–10% (tip 1) se schimbă cu 90% (tip 2) sau cu >90% HLA-DR3/DR4 de pe pagina 707.',['5-10% din toate cazurile','tipul 1B']),

q(131,['În cadranul de spectru, diabetul de tip 1 se deosebește de tipul 2 prin:',
 ['Vârstă tânără (de obicei <30 ani) și durată a simptomelor de săptămâni, cu debut sezonier','HLA-DR3 sau DR4 la >90% și patogeneză autoimună, cu cetonurie','Dispariția peptidului C, spre deosebire de persistența acestuia în tipul 2, monogenic și secundar','HLA-DR3/DR4 și la tipul 2, cu dispariția peptidului C și în monogenic','Debut sezonier identic în tipul 2 și în monogenic'],'ABC',707,'Cadranul 23.5 — Spectrul diabetului',
 'Ancorarea tripletului HLA >90% / cetonurie / dispariția peptidului C ca marcaje de tip 1.',
 ['Vârsta, durata scurtă și sezonierul sunt din tabel.','HLA >90%, autoimunitatea și cetonuria continuă rândurile.','Dispariția peptidului C contrastează cu celelalte coloane.','Tipul 2 este fără legătură HLA, cu peptid C persistent.','Debutul sezonier este marcat „Da” doar la tipul 1.']],
 8,'Dispariția peptidului C se extinde greșit la monogenic, deși tabelul îi rezervă persistența.',['HLA-DR3 sau DR4','Dispariţia peptidului-C']),

q(132,['Factorii de mediu citați în etiologia tipului 1, dincolo de Coxsackie B4 și vitamina D, includ:',
 ['Factori materni: infecție în sarcină și vârstă înaintată','Toxine din mediu, de exemplu aloxan sau Vacor','Obezitate infantilă și stres psihologic','Haplotipuri HLA ca unică explicație, mediul fiind irelevant','Introducerea tardivă a laptelui de vacă, ca factor protector cert'],'ABC',707,'Diabetul de tip 1 — Factori de mediu',
 'Completarea listei de mediu cu itemii mai puțin citați (aloxan/Vacor, obezitate infantilă, stres).',
 ['Factorii materni deschid lista.','Aloxanul și Vacor sunt exemplele de toxine.','Obezitatea infantilă și stresul închid enumerarea.','Textul subliniază că genetica nu este suficientă.','Laptele de vacă timpuriu, nu tardiv, este incriminat.']],
 8,'Aloxan/Vacor se uită lângă virusuri și vitamina D; stresul și obezitatea infantilă par „netip 1”.',['aloxan, Vacor','obezitatea infantilă']),

q(133,['Autoanticorpii insulari descriși în text includ:',
 ['Anticorpi anti-celulă insulară (ICA), detectați prin imunofluorescență','Anticorpi anti-GAD65 și anti-IA-2/ICA512, care explică o mare parte din colorarea ICA','Transportorul cationic ZnT8 și, mai recent, tetraspanina 7','Anticorpi anti-receptor TSH, ca marker de tip 2','ICA care detectează doar insulina circulantă, fără GAD'],'ABC',707,'Figura 23.8 — Anticorpi anti-insule',
 'Ierarhia ICA (imunofluorescență) versus GAD/IA-2 ca principali și ZnT8/tetraspanina 7 ca adiționali.',
 ['Tehnica ICA este descrisă.','GAD65 și IA-2/ICA512 sunt principalii.','ZnT8 și tetraspanina 7 sunt numiți.','Anti-TSHR ține de tiroidă, nu de insulă.','Autoanticorpii anti-insulină circulanți nu contribuie la reacția ICA.']],
 8,'Tetraspanina 7 și ZnT8 se omit în favoarea ICA „egal anti-insulină”, deși textul le separă.',['tetraspanina 7','Zn T8']),

q(134,['Ajustarea dozelor de insulină și țintele capilare din cadranele 23.11–23.12:',
 ['Ajustarea este de circa 10% din doza curentă','Țintele capilare sunt 4–7 mmol/L înainte de masă și 4–10 mmol/L după mese, dacă se obțin fără hipoglicemii','Cei șase pași ai administrării în siguranță sunt: persoana, insulina, doza, dispozitivul, calea și timpul potrivite','Glicemia crescută înainte de micul dejun se corectează crescând analogul rapid de la cină, nu bazala de seară','Ținta postprandială este 2–3 mmol/L, sub pragul de alertă'],'ABC',716,'Cadranele 23.11 și 23.12 — Ajustare; Siguranță',
 'Cuplarea treptei de 10% cu țintele 4–7 / 4–10 și cu cei șase pași de prescriere.',
 ['Regula de 10% este nota cadranului.','Intervalele pre- și postprandiale sunt explicite.','Cei șase pași sunt listați.','Glicemia de dimineață se ajustează pe bazala/premixul de seară.','2–3 mmol/L este hipoglicemie, nu țintă postprandială.']],
 8,'4–7 preprandial se inversează cu 4–10 postprandial; treapta de 10% se uită.',['aproximativ 10%','4 şi 7 mmol/l']),

q(135,['Definițiile glicemice ale hipoglicemiei, conform consensului citat:',
 ['Hipoglicemia semnificativă este o glicemie sub 3,0 mmol/L (54 mg/dl)','Orice valoare sub 4,0 mmol/L (70 mg/dl) este o valoare de alertă care necesită tratament','Hipoglicemia severă este cea pentru care pacientul necesită ajutorul altei persoane','Hipoglicemia semnificativă începe sub 4,0 mmol/L, iar alerta sub 3,0 mmol/L','Severitatea se definește doar numeric, independent de nevoia de ajutor'],'ABC',716,'Hipoglicemia — Definiții',
 'Separarea pragurilor 3,0 (semnificativă) și 4,0 (alertă) de definiția clinică a formei severe.',
 ['Pragul de 3,0 mmol/L este explicit.','Alerta de 4,0 mmol/L impune tratament.','Nevoia de ajutor definește severitatea.','Direcția pragurilor este inversată în distractor.','Textul definește severitatea prin ajutor extern, nu doar numeric.']],
 8,'3,0 și 4,0 se inversează ușor între „semnificativă” și „alertă”.',['sub 3,0 mmol/l','valoare de alertă']),

q(136,['Inhibitorii SGLT2, dincolo de scăderea pragului renal, se caracterizează prin:',
 ['Scăderea HbA1c cu 7–13 mmol/mol (0,6–1,2%) și pierdere ponderală de circa 2–4 kg în 6–12 luni','Ipoteze pentru beneficiul CV: natriureză cu scăderi mici ale TAS, cetone ca „combustibil” cardiac, vasodilatație prin blocarea SRAA, efecte directe pe cord','Ca adjuvant la insulină în tipul 1, scad HbA1c cu 5–6 mmol/mol (0,4–0,5%) fără a crește hipoglicemia, dar cu risc mai mare de CAD și infecții fungice','Creștere ponderală de 5–6 kg, identică pioglitazonei','Eficacitatea hipoglicemiantă este independentă de funcția renală, fără niciun beneficiu renoprotector la RFGe scăzută'],'ABC',719,'Inhibitorii SGLT2 — Eficacitate; Tip 1',
 'Pachetul 7–13 mmol/mol / 2–4 kg versus adjuvantul din tipul 1 (5–6 mmol/mol, CAD, fungi).',
 ['Cifrele de HbA1c și de greutate sunt explicite.','Cele patru ipoteze CV sunt listate.','Adjuvantul din tipul 1 și capcanele CAD/fungi sunt descrise.','SGLT2 scad, nu cresc, greutatea.','Efectul glicemic depinde de funcția renală; renoprotecția persistă și la RFGe mai mică.']],
 8,'Cele două ferestre HbA1c (0,6–1,2% versus 0,4–0,5% în tipul 1) se confundă; CAD euglicemică se uită.',['2-4 kg','cetoacidoză diabetică']),

q(137,['Efectele nedorite ale inhibitorilor SGLT2 includ:',
 ['Candidoză genitală și deshidratare, ca cele mai frecvente','Cetoacidoză diabetică, gangrena Fournier și amputații de membru inferior, ca reacții mai rare','CAD care poate evolua cu glicemii normale sau doar ușor crescute, inclusiv la persoane etichetate tip 2','Creșterea absorbției de B12, cu policitemie de rutină','Absența oricărui risc de infecție fungică, clasa fiind sterilizantă urinară'],'ABC',719,'Inhibitorii SGLT2 — Efecte adverse',
 'Ierarhia frecvent (candidoză, deshidratare) versus rar (CAD, Fournier, amputații) și capcana CAD euglicemice.',
 ['Perechea frecventă este explicită.','Triada rară este listată.','Glicemia normală/ușor crescută este capcana de diagnostic.','B12 ține de metformin, nu de SGLT2.','Candidoza genitală este tocmai efectul frecvent.']],
 8,'Gangrena Fournier și amputațiile se omit lângă candidoză; CAD euglicemică se atribuie greșit sulfonilureelor.',['gangrena Fournier','glicemiile pot fi normale']),

q(138,['Inhibitorii de alfa-glucozidază (acarboza):',
 ['Împiedică ultima enzimă a digestiei carbohidraților, descompunerea dizaharidelor în monozaharide, încetinind absorbția postprandială','Nu sunt folosiți pe scară largă din cauza eficacității limitate și a efectelor gastrointestinale','Efectele majore sunt flatulență, distensie și diaree, prin fermentarea carbohidraților neabsorbiți','Accelerează absorbția glucozei și sunt prima linie universală, fără efecte digestive','Blochează SGLT2 tubular, identic flozinelor'],'ABC',719,'Inhibitorii alfa-glucozidazei',
 'Mecanismul de ultimă enzimă dizaharidică și motivul utilizării reduse (GI + eficacitate limitată).',
 ['Sediul enzimei și efectul postprandial sunt descrise.','Utilizarea redusă este explicită.','Fermentația intestinală explică simptomele.','Acarboza încetinește, nu accelerează, absorbția.','Sediul este intestinal, nu SGLT2 renal.']],
 8,'Acarboza se mută pe SGLT2, iar flatulența se uită ca preț al carbohidraților neabsorbiți.',['dizaharidelor în monozaharide','carbohidratii neabsor']),

q(139,['Alte terapii orale și originea agoniștilor GLP-1:',
 ['Bromocriptina cu eliberare rapidă, administrată la începutul zilei, pare să reseteze ritmul circadian al dopaminei hipotalamice și scade HbA1c cu 5–8 mmol/mol (0,5–0,7%)','Colesevelamul este o rășină de legare a acizilor biliari, care scade colesterolul și poate reduce glicemiile printr-un mecanism gastrointestinal necunoscut','Un grup de agoniști GLP-1 derivă din exendin (saliva unei șopârle din Arizona), cu 53% omologie cu GLP-1 uman și rezistență la DPP-4','Bromocriptina crește HbA1c cu 2%, fiind rezervată tipului 1','Exendinul are 100% omologie cu GLP-1 și este clivat rapid de DPP-4'],'ABC',719,'Bromocriptină; Colesevelam; Exendin',
 'Nișa circadiană a bromocriptinei, rășina colesevelam și originea exendin 53%.',
 ['Resetarea circadiană și scăderea 5–8 mmol/mol sunt explicite.','Natura de rășină și mecanismul necunoscut sunt citate.','Șopârla, 53% și rezistența la DPP-4 sunt descrise.','Bromocriptina scade, nu crește, HbA1c.','Omologia este 53%, nu 100%; exendinul rezistă clivajului.']],
 8,'53% omologie exendin se rotunjește greșit la 100%; bromocriptina se mută pe axa incretinică.',['53% homologie','şopârle din deşertul']),

q(140,['Analogii GLP-1 umani, spre deosebire de agoniștii pe bază de exendin:',
 ['Reduc riscul de infarct, accident vascular cerebral, moarte cardiovasculară și insuficiență cardiacă','Există preparate cu administrare o dată pe săptămână; formulări orale sunt în dezvoltare','Agoniștii pe bază de exendin reduc aceleași evenimente CV, identic analogilor umani','Se administrează doar de două ori pe zi, fără forme săptămânale','Sunt contraindicate în obezitate, deoarece cresc greutatea'],'AB',719,'Agoniști GLP-1 — CV; Farmacocinetică',
 'Contrastul CV (doar analogii umani) și trecerea de la bid la săptămânal/oral în dezvoltare.',
 ['Beneficiul CV al analogilor umani este explicit.','Săptămânalul și oralele în dezvoltare sunt citate.','Textul precizează că exendin-derivații nu reduc aceleași evenimente.','Formele vechi erau bid; acum există săptămânale.','Clasa scade greutatea, nu o crește.']],
 8,'Beneficiul CV se extinde greșit la tot exendinul, deși textul îl rezervă analogilor umani.',['analogii GLP-1 umani','o dată pe săptămână']),

q(141,['În cadranul de tratament al CAD, după prima oră, ritmul de fluide NaCl 0,9% cu potasiu este:',
 ['1 L în 2 ore, 1 L în 2 ore, apoi 1 L în 4 ore, 1 L în 4 ore și 1 L în 6 ore','500 ml/oră continuu, 48 de ore, fără potasiu','100 ml în 12 ore, ca unică pungă','Glucoză 10% 1 L/oră de la început, înaintea NaCl','Oprirea fluidelor după primul litru, insulina fiind suficientă'],'A',724,'Cadranul 23.19 — Fluide după 60 de minute',
 'Memorarea scării 2–2–4–4–6 ore, distinctă de primul litru din prima oră.',
 ['Succesiunea de intervale este din cadran.','48 de ore la 500 ml fără K nu este schema.','100 ml/12 ore este insuficient.','Glucoza 10% se adaugă când glicemia scade sub 14 mmol/L.','Fluidele continuă după primul litru.']],
 8,'Scara 2–2–4–4–6 se aplatizează greșit la „1 L/oră tot timpul”, ca în prima oră.',['timp de 2 ore','timp de 6 ore']),

q(142,['Deficitele tipice de electroliți în CAD, pe kilogram, sunt de ordinul:',
 ['Sodiu 7–10 mmol/kg, clor 3–5 mmol/kg, potasiu 3–5 mmol/kg','Sodiu 1 mmol/kg, fără deficit de potasiu','Potasiu 20 mmol/kg, fără deficit de sodiu','Clor 30 mmol/kg, ca unică pierdere','Niciun deficit, CAD fiind o stare de retenție salină'],'A',724,'Substituția pierderilor de electroliți',
 'Reținerea tripletului Na 7–10 / Cl 3–5 / K 3–5 mmol/kg.',
 ['Cele trei intervale sunt explicite.','Deficitul de sodiu este substanțial, nu 1 mmol/kg.','Potasiul este 3–5, nu 20 mmol/kg.','Clorul nu este unica pierdere.','CAD produce depleție, nu retenție.']],
 8,'Cele trei intervale se permută între Na, Cl și K.',['7-10 mmol/kg','3-5 mmol/kg']),

q(143,['Un bărbat de 22 de ani cu CAD are potasiu 5,8 mmol/L la prezentare. Conform textului:',
 ['Potasiul se adaugă din primul litru, indiferent de valoare','Potasiul nu ar trebui administrat în substituția inițială de fluide sau dacă kaliemia rămâne peste 5,5 mmol/L','Hipopotasemia nu apare după insulină, potasiul crescând invariabil','Hiperpotasemia inițială exclude orice deficit corporal de potasiu','Monitorizarea potasiului este superfluă după prima oră'],'B',724,'Potasiul în CAD',
 'Pragul de 5,5 mmol/L ca limită peste care K nu se adaugă, în ciuda deficitului corporal.',
 ['Adăugarea de rutină la 5,8 mmol/L contrazine pragul.','Regula >5,5 mmol/L și riscul de IRA prerenală sunt explicite.','Insulina împinge potasiul în celule, deci kaliemia poate cădea rapid.','Deficitul corporal coexistă cu hiperpotasemie inițială.','Monitorizarea frecventă este cerută.']],
 8,'Hiperpotasemia de prezentare maschează deficitul de 3–5 mmol/kg; pragul 5,5 se uită.',['peste 5,5 mmol/L','leziune acută de rinichi']),

q(144,['Acidoza hipercloremică din tratamentul CAD:',
 ['Apare deoarece electroliții cu sarcină negativă pierduți sunt înlocuiți cu clor','Rinichii o corectează de obicei spontan în câteva zile','Impune bicarbonat hiperton de rutină la orice pH <7,3','Este identică găurii anionice mari persistente a cetozei netratate','Nu apare dacă se folosește NaCl 0,9%, acest fluid prevenind hipercloremia'],'AB',724,'Acidoza hipercloremică de recuperare',
 'Mecanismul de substituție cu clor și corecția renală spontană în zile.',
 ['Înlocuirea anionilor cu clor este explicația.','Corecția spontană în câteva zile este citată.','Bicarbonatul se rezervă pH <7,0, rar.','Gaura anionică scade când cetoza se curăță, spre deosebire de hipercloremie.','NaCl 0,9% este tocmai contextul hipercloremiei.']],
 8,'Hipercloremia de recuperare se confundă cu acidoza cetonemică inițială cu gaură anionică mare.',['Acidoza hipercloremică','câteva zile']),

q(145,['Prevalența retinopatiei la tipul 1 diagnosticat înainte de 33 de ani, după durată lungă:',
 ['Aproape toți dezvoltă modificări de fond, iar 60% progresează către retinopatie proliferativă','Sub 5% au orice retinopatie după 40 de ani de evoluție','Proliferativa apare la 2%, fără forme de fond','Modificările de fond exclud orice progresie proliferativă','Prevalența este independentă de durata bolii'],'A',728,'Figura 23.15 — Prevalența retinopatiei',
 'Cuplarea „aproape toți – fond” cu 60% proliferativă la tipul 1 cu debut <33 de ani.',
 ['Cele două ponderi sunt în legendă.','Prevalența crește cu durata, nu stă sub 5%.','60%, nu 2%, este progresia proliferativă.','Fondul precede, nu exclude, proliferativa.','Figura este în funcție de durată.']],
 8,'60% proliferativă se atribuie greșit tuturor tipurilor de diabet, nu doar tipului 1 cu debut <33 de ani.',['înainte de vârsta de 33 ani','60% progresează']),

q(146,['În cadranul gradelor de retinopatie, hemoragiile punctiforme:',
 ['Sunt microanevrisme capilare și deseori primele care apar, în retinopatia neproliferativă','Hemoragiile în pată reflectă scurgeri în straturile retiniene mai profunde','Petele de vată/corpii citoizi țin de stadiul preproliferativ, alături de anse venoase și AMIR','Sunt vase de neoformație pe disc, definind proliferativa','Exsudatele dure sunt reziduuri axoplasmatice, nu depozite lipidice'],'ABC',728,'Cadranul 23.21 — Gradele retinopatiei',
 'Secvența punctiform (microanevrism) → pată profundă → preproliferativ (vată, anse, AMIR).',
 ['Microanevrismele ca prim semn sunt explicite.','Scurgerea în straturile profunde definește hemoragia în pată.','Vata, ansele și AMIR sunt ale preproliferativului.','Neoformația definește proliferativa, nu punctiformele.','Exsudatele dure sunt plasmă bogată în lipide și proteine.']],
 8,'Punctiformele (R1) se promovează greșit la neovase (R3); petele de vată coboară în R1.',['Hemoragii punctiforme','corpi citoizib']),

q(147,['În nefropatia diabetică, țintele tensionale și alegerea antihiperglicemiantelor includ:',
 ['Ținta arterială este <130/80 mmHg; inhibitorii SRAA se administrează și la normotensivi cu microalbuminurie persistentă','Glibenclamidul sau metforminul, parțial excretați renal, trebuie evitați','Dozele de insulină sunt în general reduse, clearance-ul scăzând în boala renală avansată','Inhibitorii SGLT2 încetinesc progresia nefropatiei și mențin funcția renală','Metforminul se inițiază indiferent de RFGe, iar insulina se crește de rutină în BRT'],'ABCD',731,'Nefropatia — Tratament',
 'Pachetul 130/80 + IECA la normotensivi, evitarea glibenclamid/metformin și reducerea insulinei.',
 ['Ținta și indicația SRAA la normotensivi sunt explicite.','Cei doi agenți orali de evitat sunt numiți.','Reducerea dozelor de insulină este citată.','Datele SGLT2 sunt menționate.','Metforminul se evită; insulina se reduce, nu se crește.']],
 8,'IECA-ul „doar la hipertensivi” contrazine indicația din microalbuminurie normotensivă.',['<130/80 mmHg','glibenclamidul sau met']),

q(148,['Tratamentul bolii renale terminale la persoanele cu diabet:',
 ['Șunturile vasculare tind să se calcifice repede, deci dializa peritoneală cronică ambulatorie poate fi preferată hemodializei','Rata de eșec a transplantelor renale este ușor mai crescută față de nediabetici','Cecitatea, neuropatia autonomă și boala vasculară periferică îngreunează tratamentul','Hemodializa este preferată fiindcă șunturile nu se calcifică în diabet','Transplantul are rată de eșec zero, superioară nediabeticilor'],'ABC',731,'Boala renală terminală',
 'Calcificarea rapidă a șunturilor ca argument pentru DPCA și eșecul ușor crescut al grefei.',
 ['Calcificarea și preferința DPCA sunt explicite.','Comparația ratelor de eșec este citată.','Cele trei complicații care îngreunează tratamentul sunt listate.','Șunturile se calcifică, deci hemodializa este mai dificilă.','Eșecul este ușor mai mare, nu zero.']],
 8,'DPCA versus hemodializă se inversează; calcificarea șunturilor se uită.',['calcifice repede','dializa peritoneală']),

q(149,['Infecțiile de tract urinar în diabet, ca leziune renală asociată:',
 ['Sunt relativ mai frecvente la femei, dar nu și la bărbați','Infecțiile ascendente pot urma stazei vezicale din neuropatia autonomă','Infecțiile netratate pot cauza necroză papilară, complicație în prezent foarte rară','Sunt mai frecvente la bărbați decât la femei, fără rol al stazei','Necroza papilară este regula la orice bacteriurie asimptomatică'],'ABC',731,'Infecțiile de tract urinar; Necroza papilară',
 'Asimetria de sex (femei, nu bărbați) plus staza autonomă și raritatea actuală a necrozei papilare.',
 ['Diferența femei versus bărbați este explicită.','Staza vezicală autonomă explică ascenșiunea.','Necroza papilară este descrisă ca foarte rară acum.','Textul neagă excesul la bărbați.','Necroza papilară nu este regula bacteriuriei.']],
 8,'Excesul de ITU se extinde greșit la bărbați; necroza papilară se tratează ca eveniment frecvent.',['nu şi la bărbaţi','necroză renală papilară']),

q(150,['Testarea autonomă la pat, dincolo de ortostatism și respirația profundă, include:',
 ['Raportul dintre cel mai lung și cel mai scurt interval R–R în Valsalva (15 secunde): normal ≥1,21, anormal ≤1,20','Raportul R–R clino/ortostatism al bătăilor 30 și 15: normal ≥1,04, anormal ≤1,00','O scădere tensională ortostatică de 2 mmHg, suficientă pentru diagnosticul de boală autonomă','Tahicardia de efort ca unică dovadă de denervare, fără ECG','Valsalva normal sub 1,00, identic pragului ortostatic'],'AB',732,'Cadranul 23.23 — Valsalva; R–R 30/15',
 'Cele două rapoarte R–R (Valsalva 1,21/1,20 și 30/15: 1,04/1,00), distincte de pragul tensional 30 mmHg.',
 ['Perechea 1,21 / 1,20 este din tabel.','Perechea 1,04 / 1,00 este din tabel.','2 mmHg este în limite normale (anormal ≥30).','Testele sunt ECG de interval, nu doar tahicardie de efort.','Valsalva anormal este ≤1,20, nu sub 1,00.']],
 8,'Cele trei praguri numerice (30 mmHg, 1,21, 1,04) se amestecă între linii.',['2:1,21','2:1,04']),

q(151,['Amiotrofia diabetică se caracterizează prin:',
 ['Prezentare de obicei la bărbați vârstnici, cu atrofii dureroase, adesea asimetrice, ale cvadricepsului','Reflexe rotuliene diminuate sau absente; uneori răspuns extensor plantar și proteine crescute în LCR','Asociere cu perioade de hiperglicemie severă; poate fi prezentă de la diagnostic și dispare odată cu ameliorarea controlului','Atrofie distală simetrică a mușchilor mici, fără durere, identică polineuropatiei senzitive','Remisiunea este imposibilă, forma fiind identică neuropatiei acute dureroase cronice tardive'],'ABC',732,'Amiotrofia diabetică',
 'Profilul vârstnic masculin, cvadriceps asimetric, rotulian abolit și LCR hiperproteinorahic.',
 ['Demografia și cvadricepsul asimetric sunt explicite.','Reflexele, Babinski și LCR sunt citate.','Legătura cu hiperglicemia și reversibilitatea sunt descrise.','Distribuția este proximală, nu distală simetrică.','Textul spune că dispare cu ameliorarea controlului.']],
 8,'Amiotrofia (proximală, asimetrică) se confundă cu polineuropatia simetrică distală de pe aceeași pagină.',['bărbaţii vârstnici','lichidului cefalorahidian']),

q(152,['Țintele cardiovasculare „ideale” din cadranul 23.26 includ:',
 ['HbA1c <7% (53 mmol/mol) și tensiune <130/80 mmHg','Colesterol total <4,0 mmol/L și LDL-c <2,0 mmol/L','HDL-c >1,1 mmol/L (>1,3 la femei) și trigliceride <1,7 mmol/L','HbA1c <8% ca țintă ideală, identică celei „rezonabile”','LDL-c <3,0 mmol/L ca țintă ideală, nu rezonabilă'],'ABC',735,'Cadranul 23.26 — Ținte ideale',
 'Memorarea coloanei „ideal” (7% / 130/80 / CT 4 / LDL 2 / HDL 1,1 / TG 1,7), distinctă de „rezonabil”.',
 ['Perechea HbA1c–TA ideală este din tabel.','Perechea CT–LDL ideală continuă rândurile.','HDL și TG ideale, cu nota pentru femei, închid lipidograma.','<8% este coloana rezonabilă, nu ideală.','LDL <3,0 este rezonabil, nu ideal.']],
 8,'Coloanele ideal/rezonabil (7 vs 8%, LDL 2 vs 3) se permută ușor.',['<7% (53 mmol/mol)','LDLc <2,0']),

q(153,['Statinele la persoanele cu diabet, conform textului:',
 ['Sunt recomandate peste 40 de ani sau după 10 ani de evoluție dacă există complicații microvasculare','Evenimentele CV sunt reduse cu 20% pentru fiecare scădere a LDL-c cu 1 mmol/L','Ezetimibul sau inhibitorii PCSK9 sunt indicați dacă statinele nu sunt tolerate sau ținta nu este atinsă','Se evită după 40 de ani, beneficiul apărând doar la nediabetici','Reducerea LDL nu influențează evenimentele, ezetimibul fiind de primă linie'],'ABC',735,'Prevenția CV — Statine',
 'Fereastra 40 de ani / 10 ani de boală plus regula 20% per 1 mmol/L LDL.',
 ['Cele două praguri de inițiere sunt explicite.','Regula de 20% per mmol/L este citată.','Ezetimib și PCSK9 sunt alternativa.','Recomandarea începe tocmai după 40 de ani.','Statinele sunt prima linie lipidică.']],
 8,'20% per 1 mmol/L se confundă cu 25–35% al IECA de pe același paragraf.',['vârstă peste 40 ani','1 mmol/L']),

q(154,['Aspirina în prevenția cardiovasculară la diabet:',
 ['În doze mici reduce riscul macrovascular, dar asociază morbiditate și mortalitate hemoragică','Beneficiile depășesc riscul de sângerare în prevenția secundară','În Europa nu este recomandată pentru prevenția primară','Este prima linie de prevenție primară, fără risc hemoragic','Înlocuiește statina după 40 de ani, ca unică măsură lipidică'],'ABC',735,'Aspirina',
 'Contrastul secundar (beneficiu > risc) versus primar (nerecomandată în Europa).',
 ['Reducerea macrovasculară și prețul hemoragic sunt explicite.','Prevenția secundară este indicația.','Non-recomandarea europeană în primar este precizată.','Riscul hemoragic există; primarul nu este indicația.','Aspirina nu înlocuiește statina.']],
 8,'Prevenția primară versus secundară se inversează; „Europa nu recomandă primarul” se uită.',['prevenţia secundară','prevenţia primară']),

q(155,['Insuficiența cardiacă în diabet, conform datelor din text:',
 ['Este mai frecventă decât boala CV aterosclerotică; atât FE păstrată, cât și FE redusă apar mai des','Aproximativ două treimi dintre cei cu tip 2 au caractere de disfuncție VS la 5 ani de la diagnostic','După instalarea IC, doar 10% supraviețuiesc la 5 ani','Pioglitazona și saxagliptina au crescut riscul de IC în studii; SGLT2 îl reduc; agoniștii GLP-1 nu au efect asupra IC','IC este mai rară decât ateroscleroza, cu supraviețuire de 90% la 5 ani'],'ABCD',735,'Insuficiența cardiacă',
 'Ponderea 2/3 disfuncție VS la 5 ani, supraviețuirea 10% și polaritatea medicamentelor (pio/saxa versus SGLT2).',
 ['Comparația cu ateroscleroza și cele două fenotipuri FE sunt explicite.','Cifra de două treimi la 5 ani este citată.','Supraviețuirea de 10% la 5 ani este precizată.','Efectele polarizate ale claselor sunt descrise.','Textul afirmă opusul ierarhiei și al supraviețuirii.']],
 8,'10% supraviețuire la 5 ani se inversează cu 90%; 2/3 disfuncție VS se uită.',['două treimi','10% pacienţi supravieţuind']),

q(156,['Infecțiile la persoana cu diabet, potrivit capitolului:',
 ['Hiperglicemia favorizează infecțiile prin tulburări ale imunității înnăscute; imunitatea umorală pare relativ neafectată','Boala microvasculară poate contribui la severitatea otitei externe maligne, a pielonefritei emfizematoase și a fasceitei necrozante','ITU, bacteriuria asimptomatică, infecțiile genitale micotice, infecțiile de părți moi și riscul de tuberculoză sunt crescute','Diabetul controlat crește de mai multe ori riscul infecțios, iar imunitatea umorală este abolită','Otita externă malignă și fasceita necrozantă sunt independente de microangiopatie'],'ABC',735,'Alte complicații — Infecții și imunitate',
 'Separarea imunității înnăscute perturbate de umorala relativ păstrată și a infecțiilor severe legate de microangiopatie.',
 ['Textul leagă hiperglicemia de imunitatea înnăscută, cu umorala relativ neafectată.','Otita externă malignă, pielonefrita emfizematoasă și fasceita necrozantă sunt citate.','ITU, micoticele, părțile moi și TBC sunt enumerate.','Diabetul controlat nu crește predispoziția; umorala nu este abolită.','Microangiopatia este invocată tocmai pentru aceste infecții severe.']],
 8,'Inversează umorala „abolită” și rupe microangiopatia de otita malignă/fasceită, două asocieri de pe aceeași pagină.',['imunitatea umorală','fasceita necrozantă']),

q(157,['Malabsorbția și boala celiacă la persoanele cu diabet:',
 ['Malabsorbția poate urma insuficienței cronice a pancreasului exocrin','Doar 10% din funcția pancreatică este necesară pentru o digestie normală; tratamentul este cu enzime pancreatice','Persoanele cu tip 1 au prevalență mai crescută a bolii celiace','Insuficiența exocrină este regula, 90% din funcție fiind necesară digestiei','Boala celiacă este mai rară în tipul 1 decât în populația generală'],'ABC',735,'Malabsorbție; Boala celiacă',
 'Pragul de 10% funcție exocrină reziduală și excesul de celiacă din tipul 1.',
 ['Cauza exocrină este citată.','Pragul de 10% și enzimele sunt explicite.','Excesul de celiacă în tipul 1 este precizat.','Textul spune 10%, nu 90%.','Prevalența celiacă este crescută, nu scăzută, în tipul 1.']],
 8,'10% funcție suficientă se citește greșit ca 10% cu malabsorbție certă.',['10% din funcţia','bolii celiace']),

q(158,['Infecțiile cutanate, genitale și tuberculoza în diabet:',
 ['Infecțiile genitale micotice sunt mai frecvente, în special la femei','Infecțiile cutanate și ale țesuturilor moi sunt mai des întâlnite','Riscul de tuberculoză este crescut','Imunitatea umorală este abolită, vaccinatele fiind inutile','TB este mai rară decât în populația generală, hiperglicemia fiind protectoare'],'ABC',735,'Infecțiile — Micotice; Cutane; TB',
 'Triada micotice feminine / țesuturi moi / TB crescută, dincolo de Klebsiella și otita malignă deja folosite.',
 ['Predilecția feminină a micozelor genitale este explicită.','Țesuturile moi sunt listate.','Riscul de TB este citat.','Imunitatea umorală pare relativ neafectată.','TB este crescută, nu scăzută.']],
 8,'TB crescută se uită lângă otita malignă; micozele se mută greșit ca predominanță masculină.',['genitale micotice','Riscul de tuberculoză']),

q(159,['La examenul de picior, semnele neuropate din cadranul 23.3 includ:',
 ['Pierderea arcului plantar și degete deformate în gheară','Ulcere neuropate și deformarea articulației (picior Charcot)','Pierderea sensibilității în mănușă sau șosetă, a vibrației, propriocepției și durerii, plus reflexul ahilian','Tegumente reci și pulsuri absente, ca unică manifestare neuropată, fără deformare','Paloarea și pierderea părului, fără evaluare a sensibilității'],'ABC',700,'Cadranul 23.3 — Caracteristici ale neuropatiei',
 'Constelația deformare–ulcer–Charcot–mănușă/șosetă, distinctă de rubrica ischemică (paloare, pulsuri).',
 ['Arcul și gheara deschid semnele neuropate.','Ulcerul și Charcot continuă lista.','Mănușa/șoseta, vibrația și ahilianul închid examenul.','Tegumentele reci și pulsurile absente sunt vasculare.','Paloarea ține de ischemia din aceeași figură.']],
 8,'Rubrica neuropată se înlocuiește cu cea ischemică din același cadran.',['piciorul Charcol','în mănuşă" sau .în şosetă']),

q(160,['Evaluarea anuală din cadranul 23.2, dincolo de ochi, rinichi și picior, include:',
 ['Hemoleucogramă completă, funcție tiroidiană și funcție hepatică','Statusul de fumător, tensiunea arterială, profilul lipidic și riscul CV global (ex. QRISK)','Revizuirea locurilor de injectare a insulinei','Înlocuirea profilului lipidic cu un singur TSH, suficient pentru tot riscul','Omiterea HbA1c dacă greutatea este stabilă'],'ABC',700,'Cadranul 23.2 — Evaluări anuale',
 'Rubricile de laborator sistemic (HLG, tiroidă, ficat) și calculul QRISK, pe lângă triada ochi–rinichi–picior.',
 ['Cele trei probe de laborator sunt listate.','Pachetul CV, inclusiv QRISK, este explicit.','Locurile de injectare figurează la medicație.','Profilul lipidic rămâne o rubrică distinctă.','HbA1c este item de control glicemic, nu se omite.']],
 8,'QRISK și locurile de injectare se omit când se reține doar triada microvasculară.',['Scorul QRISK','Funcţia tiroidiană']),

q(161,['Sinteza, împăturirea și eliberarea insulinei în celula beta:',
 ['Ribozomii produc pre-proinsulină din ARNm; porțiunea hidrofobă „pre” permite transferul în Golgi, apoi este scindată','Proinsulina din granule suferă împăturire stabilizată prin punți disulfidice; peptidul C se desparte, lăsând insulina ca două lanțuri legate','Cantități echimolare de insulină și peptid C sunt eliberate pe calea reglementată; o cantitate mică iese pe calea constitutivă, ocolind granulele','Pre-proinsulina este secretată direct, fără Golgi și fără peptid C','Calea constitutivă este unica cale, granulele fiind absente în celula beta'],'ABC',704,'Figura 23.3 — Sinteza insulinei',
 'Secvența pre-proinsulină → proinsulină → insulină + peptid C echimolar, plus calea constitutivă minoră.',
 ['Etapa pre-proinsulină/Golgi este descrisă.','Împăturirea, punțile și scindarea peptidului C sunt explicite.','Cele două căi de eliberare sunt contrastate.','Pre-proinsulina nu se secretă ca atare.','Calea reglementată prin granule este principala.']],
 8,'Calea constitutivă minoră se promovează ca unică; echimolaritatea insulină–peptid C se uită.',['pre-proinsulina','ca/ea constitutivă']),

q(162,['Lispro, ca analog rapid, este creat prin:',
 ['Inversarea ordinii prolinei și lizinei în pozițiile 28 și 29 ale lanțului B','Înlocuirea prolinei B28 cu acid aspartic, ca la aspart','Înlocuirea asparaginei A21 cu glicină, ca la glargin','Adăugarea unui lanț de acid gras la B29, ca la detemir','Eliminarea treoninei B30, ca la degludec'],'A',703,'Figura 23.2 — Lispro',
 'Reținerea inversiunii B28–B29 (Pro–Lys) ca semnătură a lispro, distinctă de aspart (Asp B28).',
 ['Inversiunea 28–29 este definiția lispro.','Asp B28 definește aspartul, nu lispro.','Glicina A21 este a glarginei.','Acidul gras la B29 ține de detemir/degludec.','Ștergerea B30 ține de detemir/degludec.']],
 8,'Inversiunea Pro–Lys (lispro) se confundă cu substituția Asp (aspart) de pe aceeași figură.',['Lispro este creat','poziţiile 28 şi 29']),
];
