import {rewriter} from './rewrite-author';
import {RETIRED_ELECTROLITI} from './retired/electroliti';

// Rewritten after the 2026-09-24 cue audit (Kumar, cap. 9, p. 172–190).
const q=rewriter(RETIRED_ELECTROLITI,(p:number)=>p-149,{shuffle:true});

export const ELECTROLITI_V2=[
q('electroliti-adv-031',['La un bărbat sănătos de 70 kg:',
 ['apa totală a organismului este de aproximativ 42 L','lichidul intracelular reprezintă circa 28 L','plasma reprezintă circa 14 L, adică 20%','lichidul interstițial este de circa 28 L','apa totală reprezintă 40–50% din masa slabă'],'AB',172,'Apa și electroliții',
 'Fixarea compartimentelor hidrice ale organismului.',
 ['Apa totală este ~42 L.','Lichidul intracelular este ~28 L.','Nu: plasma este ~4,6 L, adică 4–5%.','Interstițiul are ~9,4 L.','40–50% este valoarea la femei.']],
 [8,'Distractorii permută volumele și sexul.'],['42 L','28 L']),

q('electroliti-adv-014',['Distribuția apei între compartimente:',
 ['presiunea osmotică este principalul determinant','ureea traversează greu membranele, fiind osmotic activă','cantitatea totală de Na+ determină volumul extracelular','Na+ determină distribuția dintre interstițiu și plasmă','retenția ureei în insuficiența renală redistribuie apa'],'AC',172,'Presiunea osmotică',
 'Recunoașterea determinanților distribuției apei.',
 ['Presiunea osmotică este determinantul principal.','Nu: ureea traversează membranele și este osmotic inactivă.','Na+ total determină volumul extracelular.','Na+ traversează capilarul și nu contribuie la această distribuție.','Retenția ureei nu modifică distribuția apei.']],
 [8,'Distractorii atribuie efecte osmotice greșite.'],['osmotic inactivă','presiunea osmotică']),

q('electroliti-adv-071',['Conform Figurii 9.3, distribuția apei între vas și interstițiu:',
 ['presiunea hidrostatică scoate lichidul din capilare','presiunea oncotică menține lichidul în vase','limfaticele returnează fluxul net spre exterior','presiunea oncotică scoate lichidul din capilare','spațiile pleural și peritoneal scapă acestor principii'],'ABC',172,'Figura 9.3',
 'Aplicarea principiilor Starling.',
 ['Presiunea hidrostatică forțează ieșirea lichidului.','Presiunea oncotică reține lichidul în vase.','Limfaticele echilibrează fluxul net.','Presiunea oncotică reține lichidul.','Sunt guvernate de principii similare.']],
 [8,'Distractorii inversează forțele Starling.'],['oncotică','limfatic']),

q('electroliti-adv-013',['Distribuția unui litru de lichid administrat intravenos:',
 ['glucoza 5% rămâne în compartimentul vascular','salina 0,9% rămâne în compartimentul extracelular','coloidul rămâne în compartimentul vascular','glucoza 5% rămâne în compartimentul extracelular','salina 0,9% se distribuie egal în toate compartimentele'],'BC',172,'Distribuția lichidelor de substituție',
 'Aplicarea distribuției soluțiilor intravenoase.',
 ['Nu: glucoza este metabolizată, iar apa se distribuie egal în toate compartimentele.','Salina rămâne extracelular.','Coloidul rămâne vascular prin presiune oncotică.','Glucoza 5% se distribuie în toate compartimentele.','Salina rămâne extracelular.']],
 [8,'Distractorii permută glucoza și salina.'],['glucoză 5%','coloidală']),

q('electroliti-adv-072',['Tratamentul corect al depleției de apă extracelulare, conform capitolului, este:',
 ['salina 0,9%','glucoza 5%','soluția coloidală','apa distilată i.v.','glucoza 5% cu KCl'],'A',172,'Distribuția lichidelor de substituție',
 'Alegerea lichidului pentru depleția extracelulară.',
 ['Sodiul menține apa în compartimentul extracelular.','Se distribuie în toate compartimentele.','Rămâne vascular; salina este acum preferată.','Produce liză osmotică.','Se distribuie în toate compartimentele.']],
 [8,'Distractorii sunt lichide cu altă distribuție.'],['ser fiziologic','extracelulară']),

q('electroliti-adv-051',['Volumul arterial sanguin efectiv (VASE):',
 ['este principalul determinant al excreției renale de Na+ și apă','scade la reducerea debitului cardiac','scade la reducerea rezistenței vasculare periferice','crește la vasodilatația arterială periferică','scăzut crește sodiul urinar peste 100 mmol/L'],'ABC',173,'Reglarea volumului extracelular',
 'Recunoașterea rolului VASE în excreția sodiului.',
 ['VASE este principalul determinant.','Debitul cardiac redus scade VASE.','Rezistența periferică redusă scade VASE.','Vasodilatația scade VASE.','Depleția VASE face urina practic lipsită de Na+.']],
 [8,'Distractorii inversează efectul vasodilatației și al depleției.'],['volumul arterial sanguin efectiv','100 mmol/L']),

q('electroliti-adv-052',['Receptorii implicați în reglarea volemică:',
 ['receptorii de presiune înaltă domină controlul volemic','receptorii atriali controlează eliberarea ANP','aparatul juxtaglomerular controlează sistemul RAA','receptorii de volum răspund la concentrația sodiului','ANP este eliberat din aparatul juxtaglomerular'],'ABC',173,'Reglarea neuro-hormonală',
 'Recunoașterea receptorilor reglării volemice.',
 ['Baroreceptorii înalți au influență mai mare.','Receptorii atriali controlează ANP.','Juxtaglomerularul răspunde la perfuzia renală.','Răspund la VASE, nu la sodiu.','ANP provine din atrii.']],
 [8,'Distractorii inversează stimulul și sursa ANP.'],['peptidul natriuretic atrial','juxtaglomerular']),

q('electroliti-adv-017',['Conform Cadranului 9.4, sodiul filtrat este reabsorbit:',
 ['60–70% în tubii proximali','20–25% în ansa lui Henle','~5% în tubii distali','~4% în ductele colectoare','20–25% în ductele colectoare'],'ABCD',175,'Cadranul 9.4',
 'Fixarea reabsorbției segmentare a sodiului.',
 ['Proximal: 60–70%.','Ansa: 20–25%.','Distal: ~5%.','Ductele colectoare: ~4%.','Ductele colectoare reabsorb ~4%.']],
 [8,'Singurul distractor mută procentul ansei.'],['60-70','20-25']),

q('electroliti-adv-016',['Reglarea reabsorbției sodiului în nefron:',
 ['în ansă și tubul distal depinde de fluxul livrat','reglarea neuro-umorală are loc primar proximal și în ductul colector','aldosteronul crește reabsorbția în tubii colectori','reglarea neuro-umorală are loc primar în ansa lui Henle','angiotensina II scade transportul proximal de sodiu'],'ABC',173,'Reglarea volumului extracelular',
 'Localizarea reglării reabsorbției sodiului.',
 ['Reabsorbția în ansă și distal depinde de flux.','Reglarea neuro-umorală este proximală și în colector.','Aldosteronul acționează în tubii colectori.','Ansa depinde de flux.','Angiotensina II crește transportul proximal.']],
 [8,'Distractorii mută sediul reglării și inversează angiotensina.'],['neuro-umorală','tubii colectori'],[175]),

q('electroliti-adv-018',['Sustragerea de la acțiunea mineralocorticoizilor:',
 ['dozele mari de mineralocorticoizi cresc inițial ECF cu 1,5–2 L','explică lipsa edemelor în sindromul Conn','depinde de oferta distală crescută de sodiu','are loc normal în insuficiența cardiacă','face spironolactona ineficientă în insuficiența cardiacă'],'ABC',175,'Mecanismul sustragerii',
 'Explicarea fenomenului de sustragere.',
 ['Volumul crește inițial cu 1,5–2 L.','Explică absența edemelor în hiperaldosteronismul primar.','Oferta distală crescută copleșește aldosteronul.','În insuficiența cardiacă sustragerea lipsește.','Spironolactona produce natriureză substanțială.']],
 [8,'Distractorii inversează situația din stările edematoase.'],['sindromul Conn','1,5-2 L']),

q('electroliti-adv-012',['În ductul colector cortical:',
 ['celulele principale reprezintă aproximativ 15%','celulele principale au canale apicale de Na+ și K+','celulele intercalate manipulează H+ și HCO3−','celulele intercalate sunt sediul efectului ADH asupra apei','celulele intercalate transportă intens NaCl'],'BC',176,'Reglarea excreției apei',
 'Diferențierea celulelor ductului colector.',
 ['Nu: celulele principale sunt ~65%.','Au canale apicale de Na+ și K+.','Intercalatele manipulează H+ și HCO3−.','Efectul ADH apare în celulele principale.','Intercalatele nu transportă NaCl.']],
 [8,'Distractorii mută funcțiile între tipurile celulare.'],['65%','intercalate']),

q('electroliti-adv-075',['Receptorii vasopresinei:',
 ['V1A induce vasoconstricție în musculatura netedă','V1B mediază eliberarea de ACTH','V2 se află pe celulele principale ale ductelor colectoare','V1B mediază reabsorbția apei în ductul colector','V2 induce vasoconstricție arteriolară'],'ABC',176,'Reglarea excreției apei',
 'Asocierea receptorilor vasopresinei cu efectele lor.',
 ['V1A: vasoconstricție.','V1B: eliberarea de ACTH.','V2: răspunsul renal la ADH.','Reabsorbția apei ține de V2.','Vasoconstricția ține de V1A.']],
 [8,'Distractorii permută receptorii.'],['ACTH','vasoconstricţie']),

q('electroliti-adv-076',['Transportul apei mediat de aquaporine (Figura 9.7):',
 ['ADH acționează pe receptorii V2 bazolaterali','inserția aquaporinelor în membrana luminală depinde de AMPc','aquaporinele sunt retrase prin endocitoză după epuizarea ADH','aquaporinele se inserează în membrana bazolaterală','diabetul insipid nefrogen este un deficit de ADH'],'ABC',176,'Figura 9.7',
 'Explicarea mecanismului aquaporinelor.',
 ['V2 este bazolateral.','AMPc mobilizează veziculele spre membrana luminală.','Endocitoza retrage canalele.','Inserția este luminală.','Este o rezistență la ADH.']],
 [8,'Distractorii inversează membrana și mecanismul bolii.'],['aquaporine','endocitoză']),

q('electroliti-adv-036',['Osmoreglarea:',
 ['sub 275 mOsm/kg nu există ADH circulant','natremia este menținută cu devieri de 1–2%','setea previne hipernatremia în diabetul insipid central','ADH reduce pierderea, dar nu corectează deficitul de apă','osmoreceptorii sunt situați în principal în ficat'],'ABCD',176,'Osmolalitatea plasmatică',
 'Aplicarea principiilor osmoreglării.',
 ['Sub 275 mOsm/kg ADH lipsește.','Devierile sunt de 1–2%.','Setea compensează pierderea urinară.','Setea corectează deficitul.','Osmoreceptorii sunt hipotalamici.']],
 [8,'Singurul distractor mută osmoreceptorii.'],['275 mOsm/kg','sete']),

q('electroliti-adv-047',['Pacientul cu diabet insipid central și acces liber la apă prezintă tipic:',
 ['poliurie, cu natremie normală','hipernatremie severă, cu oligurie','hiponatremie de diluție','urină concentrată, cu sete absentă','poliurie cu hiponatremie marcată'],'A',176,'Osmolalitatea plasmatică',
 'Aplicarea rolului setei în diabetul insipid.',
 ['Setea contrabalansează pierderea urinară.','Setea previne hipernatremia.','Descrie SIADH.','Urina este diluată.','Natremia rămâne normală.']],
 [8,'Distractorii ignoră rolul setei.'],['diabet insipid','poliurie']),

q('electroliti-adv-037',['Osmoreglarea și reglarea volemică:',
 ['o încărcare cu apă este excretată în 24–48 de ore','salina 0,9% crește ANP fără să modifice ADH','în SIADH, manipularea sodiului rămâne intactă','încărcarea cu apă crește ANP și suprimă aldosteronul','salina 0,9% suprimă ADH-ul osmotic'],'BC',177,'Osmoreglarea versus reglarea volemică',
 'Separarea căilor de osmoreglare și de reglare volemică.',
 ['Nu: apa este excretată în 4–6 ore prin inhibarea ADH.','Salina crește volumul fără a modifica osmolalitatea.','ANP și aldosteronul funcționează normal.','Apa nu modifică ANP sau SRAA.','ADH rămâne neschimbat.']],
 [8,'Distractorii amestecă cele două căi.'],['4-6 ore','izoosmotică']),

q('electroliti-adv-054',['Ingestia de alune sărate fără apă:',
 ['crește osmolalitatea plasmatică','stimulează setea și ADH-ul','crește ANP și suprimă aldosteronul','produce excreție de Na+ fără apă','suprimă eliberarea de ADH'],'ABCD',177,'Osmoreglarea versus reglarea volemică',
 'Aplicarea activării simultane a celor două căi.',
 ['Excesul de Na+ crește osmolalitatea.','Osmolalitatea stimulează setea și ADH.','Hipervolemia crește ANP și scade aldosteronul.','Efectul net este excreția de Na+ fără apă.','ADH crește.']],
 [8,'Singurul distractor inversează ADH.'],['alune sărate','setea']),

q('electroliti-adv-055',['Edemul periferic prin expansiunea volumului extracelular:',
 ['devine clinic evident la expansiunea ECF cu ≥200 mL','afectează întâi gleznele','apare în regiunea sacrată la imobilizați','afectează fața mai ales seara','apare după expansiunea ECF cu 500 mL'],'BC',177,'Creșterea volumului extracelular',
 'Recunoașterea distribuției clinice a edemului.',
 ['Nu: este necesară expansiunea cu cel puțin 2 L.','Gleznele sunt primele afectate.','Regiunea sacrată la imobilizați.','Fața este afectată mai ales dimineața.','Pragul este de cel puțin 2 L.']],
 [8,'Distractorii schimbă pragul și momentul.'],['2 L','gleznele']),

q('electroliti-adv-019',['Mecanismele edemelor:',
 ['în ciroză, oxidul nitric produce vasodilatație periferică','în nefrotic, crește conductivitatea hidraulică capilară','în nefrotic, Na+/K+-ATP-aza din ductul colector crește','în nefrotic, gradientul oncotic transcapilar crește marcat','în ciroză, VACE crește prin vasoconstricție arterială'],'ABC',177,'Ciroza hepatică și sindromul nefrotic',
 'Explicarea mecanismelor edemului în ciroză și sindromul nefrotic.',
 ['NO produce vasodilatație și reduce VACE.','Conductivitatea hidraulică este mecanismul.','Na+/K+-ATP-aza crește de trei ori.','Gradientul oncotic rămâne nemodificat.','VACE scade prin vasodilatație.']],
 [8,'Distractorii reiau explicațiile clasice infirmate.'],['conductivităţii hidraulice','oxid nitric']),

q('electroliti-adv-077',['În insuficiența cardiacă, retenția de sodiu și apă se datorează:',
 ['activării sistemului renină–angiotensină–aldosteron','eliberării non-osmotice de ADH','creșterii activității simpatice','creșterii volumului arterial efectiv','scăderii rezistenței vasculare renale'],'ABC',177,'Insuficiența cardiacă',
 'Explicarea retenției hidrosaline din insuficiența cardiacă.',
 ['SRAA este activat.','ADH este eliberat non-osmotic.','Simpaticul este activat.','VASE scade.','Rezistența renală crește.']],
 [8,'Distractorii inversează volumul efectiv și rezistența.'],['non-osmotică','simpatic']),

q('electroliti-adv-056',['Retenția de sodiu medicamentoasă:',
 ['tiazolidindionele sunt contraindicate în insuficiența cardiacă','edemul prin TZD răspunde la amilorid sau triamteren','estrogenii au efect slab aldosteron-like','AINS rețin sodiul în ciroză și stenoza renală','amlodipina produce edem prin suprareglarea ENaC'],'ABCD',178,'Retenția sodiului',
 'Recunoașterea retenției hidrosaline medicamentoase.',
 ['TZD sunt contraindicate în IC.','Amiloridul și triamterenul sunt de elecție.','Estrogenii au efect aldosteron-like.','AINS rețin sodiul la SRAA activat.','Amlodipina relaxează arteriolele precapilare.']],
 [8,'Singurul distractor atribuie amlodipinei mecanismul TZD.'],['aldosteron-like','amilorodul']),

q('electroliti-adv-078',['Edemul periferic produs de amlodipină se datorează:',
 ['relaxării arteriolelor precapilare','suprareglării ENaC','creșterii permeabilității capilare la proteine','retenției renale de sodiu prin aldosteron','scăderii presiunii oncotice'],'A',178,'Alte cauze ale edemelor',
 'Explicarea edemului prin dihidropiridine.',
 ['Relaxarea precapilară crește presiunea capilară.','Mecanismul TZD și insulinei.','Mecanismul IL-2 și hiperstimulării ovariene.','Nu este mecanismul citat.','Nu este mecanismul citat.']],
 [8,'Distractorii sunt mecanismele altor edeme.'],['precapilare','amlodipina']),

q('electroliti-adv-079',['Edemul prin creșterea permeabilității capilare la proteine apare în:',
 ['deficiența rară de complement','terapia cu interleukină 2','sindromul de hiperstimulare ovariană','tratamentul cu amlodipină','inițierea insulinei în diabetul de tip 1'],'ABC',178,'Alte cauze ale edemelor',
 'Recunoașterea edemelor prin permeabilitate crescută.',
 ['Sindromul rar de deficiență a complementului.','IL-2 în chimioterapie.','Hiperstimularea ovariană.','Mecanism precapilar.','Mecanism prin ENaC.']],
 [8,'Distractorii au alte mecanisme.'],['interleukinei 2','hiperstimulare ovariană']),

q('electroliti-adv-069',['Edemele idiopatice:',
 ['apar la femei fără boli cardiace, renale sau endocrine','se accentuează premenstrual','se remit după menopauză','reapar la întreruperea diureticelor','se accentuează în decubit, noaptea'],'ABCD',178,'Edemele idiopatice',
 'Recunoașterea edemelor idiopatice.',
 ['Apar la femei fără alte boli.','Se accentuează premenstrual.','Se remit după menopauză.','Reapar la oprirea diureticelor.','Excreția sodiului crește în decubit.']],
 [8,'Singurul distractor inversează variația posturală.'],['premenstrual','menopauză']),

q('electroliti-adv-057',['Tratamentul expansiunii volemice:',
 ['aportul de sodiu se reduce drastic la ~10 mmol/zi','restricția de sodiu este utilă în rezistența la diuretice','diureticele sunt baza tratamentului','restricția sub 20 mmol/zi se obține ușor','repausul la pat înlocuiește diureticele'],'BC',178,'Tratament',
 'Aplicarea tratamentului expansiunii volemice.',
 ['Nu: aportul se reduce ușor, la ~100 mmol (2 g) pe zi.','Restricția ajută la rezistența la diuretice.','Diureticele sunt baza tratamentului.','Sub 100 mmol este greu de obținut.','Are rareori valoare practică.']],
 [8,'Distractorii supraestimează restricția și repausul.'],['100 mmol','2 g']),

q('electroliti-adv-080',['Acumularea de litri de lichid în pleură sau ascită, fără edeme evidente și fără creșterea PVC, definește:',
 ['spațiul al treilea','edemul idiopatic ciclic','sindromul nefrotic','edemul precapilar','hipoalbuminemia'],'A',178,'Retenția sodiului',
 'Recunoașterea conceptului de spațiu al treilea.',
 ['Pleura și ascita devin „spațiul al treilea”.','Nu este definiția.','Nu este definiția.','Nu este definiția.','Nu este definiția.']],
 [8,'Distractorii sunt alte entități edematoase.'],['spaţiul al treilea','ascită']),

q('electroliti-adv-081',['Diureticele de ansă:',
 ['blochează NKCC2 în brațul gros ascendent','cresc capacitanța venoasă înaintea diurezei','produc hipocalciurie, protejând de calculi','reduc excreția calciului, ca tiazidele','nu interferă cu excreția renală a litiului'],'AB',178,'Diureticele de ansă',
 'Recunoașterea mecanismului și efectelor diureticelor de ansă.',
 ['Blochează NKCC2.','Venodilatația precedă diureza.','Nu: produc hipercalciurie, cu risc de calculi.','Cresc excreția calciului.','Interferă cu excreția litiului.']],
 [8,'Distractorii preiau efectul tiazidelor și neagă interacțiunea.'],['capacitanţei venoase','hipercalciurie'],[179]),

q('electroliti-adv-021',['Comparativ cu furosemidul oral, bumetanida orală are:',
 ['biodisponibilitate mai bună','ototoxicitate mai mare','acțiune pe tubul distal','potență mai mică','efect economisitor de potasiu'],'A',179,'Diureticele de ansă',
 'Compararea diureticelor de ansă.',
 ['Biodisponibilitatea este mai bună, mai ales cu edeme severe.','Ototoxicitatea este descrisă mai ales la furosemid.','Acționează pe ansă.','Nu este diferența citată.','Nu economisește potasiul.']],
 [8,'Distractorii sunt diferențe neconfirmate.'],['Bumetadina','biodisponibilitate']),

q('electroliti-adv-082',['Diureticele tiazidice:',
 ['produc mai multă hiperuricemie și intoleranță la glucoză','pot produce hiponatremie','cresc excreția calciului','sunt mai puternice decât diureticele de ansă','cresc excreția urinară de calciu'],'AB',179,'Diureticele tiazidice',
 'Recunoașterea efectelor tiazidelor.',
 ['Retenția de urați și intoleranța la glucoză sunt mai mari.','Interferă cu excreția apei.','Nu: tiazidele reduc excreția calciului.','Sunt mai puțin puternice.','Reduc excreția calciului.']],
 [8,'Distractorii inversează potența și calciul.'],['hiponatremie','calciului']),

q('electroliti-adv-022',['Diureticele economisitoare de potasiu:',
 ['spironolactona scade mortalitatea în insuficiența cardiacă','eplerenona nu are efecte antiandrogenice','amiloridul blochează canalele epiteliale de sodiu','amiloridul blochează receptorul mineralocorticoid','spironolactona este eficientă în sindromul Liddle'],'ABC',179,'Diureticele economisitoare de potasiu',
 'Diferențierea diureticelor economisitoare de potasiu.',
 ['Antagonizează fibroza miocardică.','Eplerenona nu are efecte antiandrogenice.','Amiloridul blochează ENaC.','Blocarea receptorului ține de spironolactonă.','Liddle nu depinde de aldosteron.']],
 [8,'Distractorii confundă mecanismele.'],['Eplerenona','Ami/aridul'],[180]),

q('electroliti-adv-058',['Conform Cadranului 9.6:',
 ['metolazonul face parte din clasa tiazidelor','acetazolamida este folosită și în glaucom','tolvaptanul blochează receptorii V2 ai vasopresinei','torasemidul este un diuretic economisitor de K+','eplerenona inhibă anhidraza carbonică renală'],'ABC',179,'Cadranul 9.6',
 'Clasificarea diureticelor.',
 ['Metolazonul este tiazidic.','Acetazolamida este indicată în glaucom.','Tolvaptanul este aquaretic.','Torasemidul este diuretic de ansă.','Eplerenona este antagonist de aldosteron.']],
 [8,'Distractorii mută medicamentele între clase.'],['Metolazol','Acetazolamida']),

q('electroliti-adv-023',['Rezistența la diuretice:',
 ['furosemidul se limitează la maximum 200 mg/zi','albumina i.v. nu crește natriureza diureticului de ansă','metolazona plus ansă este utilă în ICC refractară','combinațiile de diuretice nu au efect aditiv','albumina i.v. potențează efectul natriuretic al ansei'],'BC',180,'Rezistența la diuretice',
 'Aplicarea tratamentului rezistenței la diuretice.',
 ['Nu: maximul este 2 g/zi, din cauza ototoxicității.','Albumina nu crește natriureza.','Metolazona depinde puțin de RFG.','Combinațiile sunt extrem de utile.','Albumina nu crește natriureza.']],
 [8,'Distractorii inversează efectul albuminei și al combinațiilor.'],['2 g','Metolazona']),

q('electroliti-adv-015',['Inhibitorii SGLT2:',
 ['blochează reabsorbția glucozei și sodiului în tubii proximali','produc diureză osmotică și natriureză','au efect modest antihipertensiv','acționează pe canalele de sodiu din ductele colectoare','produc diureză apoasă fără glicozurie'],'ABC',180,'Inhibitorii SGLT2',
 'Recunoașterea mecanismului inhibitorilor SGLT2.',
 ['Blochează reabsorbția proximală.','Produc diureză osmotică și natriureză.','Efectul antihipertensiv este modest.','Acționează proximal.','Produc glicozurie.']],
 [8,'Distractorii mută sediul și neagă glicozuria.'],['SGLT2','natriu']),

q('electroliti-adv-024',['Semnele depleției volumului extracelular:',
 ['hipotensiunea posturală este un semn timpuriu și specific','turgorul de pe frunte depinde puțin de vârstă','pierderea a până la 1 L poate fi compensată fără semne','tahicardia este un semn constant și de încredere','venoconstricția este semnul dominant în sepsis'],'ABC',181,'Scăderea volumului extracelular',
 'Evaluarea clinică a depleției volemice.',
 ['Este unul dintre cele mai timpurii și specifice semne.','Turgorul frunții depinde mai puțin de vârstă.','Venoconstricția compensează până la 1 L.','Tahicardia nu este de încredere.','În sepsis venoconstricția lipsește.']],
 [8,'Distractorii supraestimează tahicardia și venoconstricția.'],['Hipotensiune posturală','turgor']),

q('electroliti-adv-083',['Conform Cadranului 9.7, cauze de hipotensiune posturală sunt:',
 ['amiloidoza sistemică','antidepresivele triciclice','nitrații','repausul prelungit la pat','sindromul Conn'],'ABCD',181,'Cadranul 9.7',
 'Recunoașterea cauzelor de hipotensiune posturală.',
 ['Insuficiența autonomă.','Interferența cu funcția autonomă.','Interferența cu vasoconstricția.','Afectare cardiovasculară.','Produce hipertensiune.']],
 [8,'Singurul distractor produce hipertensiune.'],['Amiloidoză','Nitraţii']),

q('electroliti-adv-033',['În depleția volumului extracelular:',
 ['testele sanguine sunt în general puțin utile','sodiul urinar este scăzut dacă rinichiul e normal','sodiul urinar induce în eroare la diuretice','osmolalitatea urinară este tipic scăzută','creșterea ureei plasmatice este un semn specific'],'ABC',181,'Scăderea volumului extracelular — investigații',
 'Interpretarea investigațiilor în depleția volemică.',
 ['Testele sanguine sunt puțin utile.','Sodiul urinar este scăzut.','Diureticele fac sodiul urinar înșelător.','Osmolalitatea urinară este crescută.','Creșterea ureei este nespecifică.']],
 [8,'Distractorii inversează osmolalitatea și specificitatea ureei.'],['Sodiul urinar','nespecifică']),

q('electroliti-adv-034',['Înlocuirea pierderilor de apă și sodiu:',
 ['sodiul lent se dă 6–12 tablete/zi cu 2–3 L de apă','bicarbonatul de sodiu oral se folosește în depleția cu acidoză','bicarbonatul e mai puțin eficient decât NaCl în balanța de sodiu','pierderea de plasmă se tratează cu cristaloizi hipotoni','bicarbonatul oral este preferat în depleția fără acidoză'],'ABC',182,'Pierderea de apă și electroliți',
 'Aplicarea înlocuirii orale a pierderilor.',
 ['6–12 tablete/zi în 2–3 L de apă.','BCR, ATR, post-obstructiv.','Este mai puțin eficient.','Se tratează cu plasmă sau substituent.','Se folosește în depleția cu acidoză.']],
 [8,'Distractorii schimbă indicația bicarbonatului și a plasmei.'],['sodiu lent','6-12']),

q('electroliti-adv-035',['Conform Cadranului 9.10:',
 ['salina 0,9% conține Na+ și Cl− câte 150 mmol/L','Hartmann conține 2 mmol/L de calciu','Plasma-Lyte are Cl− mai mic decât salina 0,9%','Hartmann este o soluție coloidală, nu un cristaloid','Plasma-Lyte conține 40 mmol/L de potasiu'],'ABC',182,'Cadranul 9.10',
 'Compararea compoziției cristaloidelor.',
 ['Salina: Na+ și Cl− 150 mmol/L.','Hartmann conține 2 mmol/L calciu.','Plasma-Lyte: Cl− 98 mmol/L.','Hartmann este cristaloid.','Plasma-Lyte are 5 mmol/L de K+.']],
 [8,'Distractorii schimbă natura soluției și potasiul.'],['Plasma-Lyte','Hartmann']),

q('electroliti-adv-084',['Conform Cadranului 9.10, soluția Hartmann sau Plasma-Lyte poate fi mai bună decât salina 0,9% la pacienții cu:',
 ['sepsis și hipovolemie relativă','hipernatremie cu deficit de apă','hiperkaliemie severă','diabet insipid central','hipercalcemie'],'A',182,'Cadranul 9.10',
 'Alegerea cristaloidului balansat.',
 ['Nota 5 citează sepsisul cu hipovolemie relativă.','Deficitul de apă se tratează cu apă.','Nu este indicația citată.','Deficitul de apă se tratează cu apă.','Nu este indicația citată.']],
 [8,'Distractorii sunt situații cu altă conduită.'],['sepsis','hipovolemie relativă']),

q('electroliti-adv-042',['La pacienții critici, cristaloidele balansate comparativ cu salina 0,9%:',
 ['au concentrații de clor mai mici','reduc mortalitatea de orice cauză','reduc noile terapii de substituție renală','cresc disfuncția renală la volume mari','sunt contraindicate în sepsis'],'ABC',183,'Lichidele intravenoase',
 'Compararea cristaloidelor balansate cu salina.',
 ['Clorul este mai mic.','Mortalitatea este mai mică.','Terapiile renale noi sunt mai rare.','Disfuncția renală este mai rară.','Pot fi mai bune în sepsis.']],
 [8,'Distractorii inversează efectul renal.'],['Plasma-Lyte','balansate']),

q('electroliti-adv-043',['Corecția hipovolemiei:',
 ['hipotensiunea și oliguria impun NaCl 0,9% rapid','corecția suprarapidă poate da edem pulmonar','în formele ușoare se dau ~1.000 mL la 4–6 ore','perioperator, supraîncărcarea este inofensivă','chirurgia suprimă retenția de sodiu și apă'],'ABC',183,'Lichidele intravenoase',
 'Aplicarea ritmului de corecție a hipovolemiei.',
 ['Hipotensiunea cere perfuzie rapidă.','Vasoconstricția persistentă duce la supraîncărcare.','1.000 mL la 4–6 ore în formele ușoare.','Supraîncărcarea este la fel de periculoasă.','Chirurgia stimulează retenția.']],
 [8,'Distractorii minimizează supraîncărcarea.'],['4-6 ore','edem pulmonar']),

q('electroliti-adv-045',['Pierderea de apă pură:',
 ['se distribuie egal între toate compartimentele','produce depleție extracelulară abia în formele severe','se tratează cu apă, ca în diabetul insipid','se tratează i.v. cu glucoză 5%, nu cu apă pură','se limitează la compartimentul plasmatic'],'ABCD',183,'Pierderea de apă',
 'Recunoașterea pierderii de apă pură.',
 ['Pierderea se distribuie egal.','Depleția extracelulară apare doar sever.','Tratamentul corect este apa.','Apa pură produce liză osmotică.','Se distribuie în toate compartimentele.']],
 [8,'Singurul distractor contrazice distribuția egală.'],['glucozei 5%','liza osmotică']),

q('electroliti-adv-046',['Studiile Na-IRM recente arată că:',
 ['sodiul se depozitează în mușchi, os și piele fără apă','interstițiul tegumentar este hiperton față de plasmă','homeostazia sodiului implică și mecanisme extrarenale','interstițiul tegumentar rămâne izoton cu plasma sanguină','depozitele tisulare de sodiu conțin apă izotonă'],'ABC',183,'Tulburările concentrației de sodiu',
 'Recunoașterea depozitelor tisulare de sodiu.',
 ['Sodiul este depozitat fără apă.','Interstițiul cutanat este hiperton.','Există mecanisme extrarenale.','Este hiperton.','Sodiul este depozitat fără apă.']],
 [8,'Distractorii contrazic hipertonicitatea.'],['hipertone','extrarenale']),

q('electroliti-adv-038',['Hiponatremia:',
 ['este cea mai comună anomalie biochimică la internați','apare la până la 5% dintre pacienții internați','poate fi falsă în hiperlipidemie','în hiperlipidemie are osmolalitate scăzută','se definește prin Na+ sub 125 mmol/L'],'AC',183,'Hiponatremia',
 'Recunoașterea epidemiologiei și a pseudohiponatremiei.',
 ['Este cea mai comună anomalie.','Nu: apare la până la 35% dintre internați.','Pseudohiponatremia apare în hiperlipidemie.','Osmolalitatea este normală.','Pragul este 135 mmol/L.']],
 [8,'Distractorii schimbă pragul și osmolalitatea.'],['35%','hiperlipidemie']),

q('electroliti-adv-039',['În pseudohiponatremia din hiperlipidemie:',
 ['osmolalitatea plasmatică este normală','se administrează salină 3%','sodiul total al organismului este scăzut','apa totală este crescută','osmolalitatea urinară este scăzută'],'A',183,'Hiponatremia',
 'Interpretarea pseudohiponatremiei.',
 ['Osmolalitatea este normală; nu se tratează.','Tratamentul nu este necesar.','Sodiul real este normal.','Nu este mecanismul.','Nu este criteriul.']],
 [8,'Distractorii tratează artefactul ca hiponatremie reală.'],['pseudohiponatremie','osmolalitatea plasmatică']),

q('electroliti-adv-040',['Hiponatremia hipovolemică:',
 ['extrarenală are Na+ urinar sub 20 mmol/L','renală are Na+ urinar peste 20 mmol/L','stimulează ADH prin receptorii de volum','apare tipic în insuficiența cardiacă congestivă','cu pierderi extrarenale are urină diluată'],'ABC',183,'Hiponatremia cu hipovolemie',
 'Diferențierea pierderilor renale de cele extrarenale.',
 ['Extrarenal: Na+ urinar <20 mmol/L.','Renal: Na+ urinar >20 mmol/L.','Receptorii de volum depășesc osmoreceptorii.','IC produce hiponatremie hipervolemică.','Urina este concentrată.']],
 [8,'Distractorii confundă forma hipervolemică și concentrația urinii.'],['20 mmol/L','receptorii de volum']),

q('electroliti-adv-041',['Conform Cadranului 9.11, cauze renale de hiponatremie hipovolemică sunt:',
 ['tratamentul cu diuretice','insuficiența adrenocorticală','diureza osmotică din hiperglicemie','faza de recuperare a necrozei tubulare acute','pierderile cutanate prin arsuri'],'ABCD',183,'Cadranul 9.11',
 'Clasificarea cauzelor de hiponatremie hipovolemică.',
 ['Diureticele sunt cauză renală.','Insuficiența adrenocorticală este renală.','Diureza osmotică este renală.','Recuperarea NTA este renală.','Arsurile sunt cauză extrarenală.']],
 [8,'Singurul distractor este extrarenal.'],['adrenocorticală','Diureză osmotică']),

q('electroliti-adv-025',['Conform Cadranului 9.12:',
 ['sucul gastric are Na+ ~50 și Cl− ~110 mmol/L','sucul pancreatic are Na+ ~140 și Cl− ~60 mmol/L','ileostoma recentă pierde ~1.500 mL/zi','bila are Na+ ~50 mmol/L, ca sucul gastric','diareea are K+ ~4 mmol/L, ca plasma'],'ABC',184,'Cadranul 9.12',
 'Fixarea compoziției pierderilor digestive.',
 ['Stomac: Na+ 50, Cl− 110.','Pancreas: Na+ 140, Cl− 60.','Ileostoma recentă: 1.500 mL.','Bila are Na+ ~140.','Diareea are K+ 10–30.']],
 [8,'Distractorii preiau valori din alte rânduri.'],['Suc pancreatic','Ileostomie']),

q('electroliti-adv-059',['Hiponatremia postoperatorie:',
 ['apare la ~20% dintre pacienții operați','e cauzată frecvent de glucoză 5% în exces','predispune la encefalopatie femeile premenopauză','apare la 1 L de apă pe oră la rinichi normal','este prevenită de băuturile sportive izotone'],'BC',184,'Hiponatremia cu euvolemie',
 'Recunoașterea hiponatremiei postoperatorii.',
 ['Nu: apare la ~1%.','Glucoza 5% în exces este cauza iatrogenă comună.','ADH postoperator este de 40 de ori mai mare.','La rinichi normal este rară.','Aceste băuturi pot produce hiponatremie.']],
 [8,'Distractorii exagerează aportul oral și protecția băuturilor.'],['1%','40 de ori']),

q('electroliti-adv-070',['Băuturile „sportive izotone” pot produce hiponatremie deoarece:',
 ['conțin puțin sodiu','conțin mult potasiu','stimulează ADH direct','sunt hipertone','conțin cofeină'],'A',184,'Hiponatremia cu euvolemie',
 'Explicarea hiponatremiei alergătorului.',
 ['Osmolalitatea vine din carbohidrați metabolizați.','Nu este mecanismul citat.','Nu este mecanismul citat.','Nu este mecanismul citat.','Nu este mecanismul citat.']],
 [8,'Distractorii sunt mecanisme plauzibile, necitate.'],['izotone','hidraţilor de carbon']),

q('electroliti-adv-085',['Conform Cadranului 9.13, cauze de hiponatremie euvolemică sunt:',
 ['hipotiroidismul','boala Addison','clorpropamidul','depleția severă de potasiu','vărsăturile repetate'],'ABCD',184,'Cadranul 9.13',
 'Recunoașterea cauzelor de hiponatremie euvolemică.',
 ['Hipotiroidismul este citat.','Deficitul de glucocorticoizi este citat.','Clorpropamidul crește sensibilitatea la ADH.','Depleția de K+ este citată.','Vărsăturile dau hiponatremie hipovolemică.']],
 [8,'Singurul distractor aparține formei hipovolemice.'],['Hipotiroidism','Clorpropamid']),

q('electroliti-adv-086',['Hiponatremia de diluție și encefalopatia hiponatremică:',
 ['simptomele neurologice clare apar rar peste 125 mmol/L','la vârstnici, 130–135 mmol/L cresc riscul de cădere','hipoxia este cel mai puternic predictor de mortalitate','copiii sub 16 ani au risc crescut de encefalopatie','femeile postmenopauză au riscul maxim de encefalopatie'],'ABCD',184,'Hiponatremia cu euvolemie',
 'Recunoașterea pragurilor clinice și a factorilor de risc.',
 ['Sub 125 mmol/L apar simptomele clare.','Formele medii cresc riscul de cădere.','Hipoxia este predictorul cel mai puternic.','Raportul creier/craniu este mare.','Riscul maxim îl au femeile premenopauză.']],
 [8,'Singurul distractor inversează grupul de risc.'],['125 mmol/L','Hipoxemia']),

q('electroliti-adv-061',['Salina 3% în hiponatremia acută simptomatică:',
 ['urmărește creșterea Na+ cu 15–20 mmol/L în primele 4 ore','se indică la convulsii sau comă','1 mL/kg crește natremia cu ~1 mmol/L','se administrează până la Na+ 140 mmol/L','se dă în bolus rapid de 500 mmol'],'BC',185,'Hiponatremia — tratament',
 'Aplicarea corecției cu salină hipertonă.',
 ['Nu: ținta este 4–6 mmol/L în primele 4 ore.','Semnele neurologice severe o indică.','1 mL/kg ≈ 1 mmol/L.','Nu se corectează peste 125–130 mmol/L.','Administrarea este lentă.']],
 [8,'Distractorii supracorectează.'],['4-6','513']),

q('electroliti-adv-060',['Pentru a evita demielinizarea osmotică, natremia nu trebuie să crească cu mai mult de:',
 ['8 mmol/L în 24 de ore','20 mmol/L în 24 de ore','8 mmol/L pe oră','2 mmol/L în 24 de ore','30 mmol/L în 48 de ore'],'A',185,'Sindromul de demielinizare osmotică',
 'Aplicarea limitei de corecție a hiponatremiei.',
 ['Maxim 8 mmol/L pe zi.','Depășește limita.','Depășește limita.','Nu este limita citată.','Depășește limita de 18 mmol/L în 48 de ore.']],
 [8,'Distractorii sunt limite plauzibile.'],['8 mmol','demielinizare']),

q('electroliti-adv-087',['Conform Cadranului 9.14:',
 ['SIADH se tratează cu restricție la 500–700 mL/zi','hipovolemia se rehidratează cu salină 0,9%','natremia se verifică chiar la 1–2 ore','corecția poate ajunge la 18 mmol/L în primele 24 de ore','hipervolemia se tratează cu salină 3%'],'ABC',185,'Cadranul 9.14',
 'Aplicarea algoritmului de tratament al hiponatremiei.',
 ['Restricție la 500–700 mL/zi.','Salina 0,9% la hipovolemici.','Sodiul se verifică la 1–2 ore.','Maxim 8 mmol în 24 h și 18 în 48 h.','Hipervolemia: restricție și diuretic de ansă.']],
 [8,'Distractorii dublează limita zilnică.'],['500-700','1-2 ore']),

q('electroliti-adv-027',['Sindromul de demielinizare osmotică:',
 ['are risc mai mare la alcoolici și malnutriți','are risc mai mare la hipokaliemici','are leziunile IRM vizibile în primele 24 de ore','apare prin corectarea prea lentă a hiponatremiei','are leziuni IRM vizibile din primele ore'],'AB',185,'Sindromul de demielinizare osmotică',
 'Recunoașterea SDO.',
 ['Alcoolismul și malnutriția cresc riscul.','Hipokaliemia crește riscul.','Nu: leziunile apar după 2–3 săptămâni.','Apare prin corecție rapidă.','Leziunile apar tardiv.']],
 [8,'Distractorii inversează ritmul și momentul imagistic.'],['cirotici','2 sau 3 săptămâni']),

q('electroliti-adv-062',['După corectarea cauzei reversibile, natremia poate crește prin diureză apoasă cu până la:',
 ['2 mmol/L pe oră','8 mmol/L pe oră','0,5 mmol/L pe zi','20 mmol/L pe oră','1 mmol/L pe zi'],'A',186,'Hiponatremia reversibilă',
 'Anticiparea supracorecției prin diureză apoasă.',
 ['Până la 2 mmol/L pe oră; se previne cu desmopresină.','Nu este valoarea citată.','Nu este valoarea citată.','Nu este valoarea citată.','Nu este valoarea citată.']],
 [8,'Distractorii sunt ritmuri plauzibile.'],['2 mmol/L pe oră','desmopresinei']),

q('electroliti-adv-063',['Antagoniștii vasopresinei (vaptanii):',
 ['tolvaptanul blochează selectiv receptorii V2','conivaptanul blochează V1A și V2','vaptanii nu afectează excreția de Na+ și K+','conivaptanul se administrează oral, pe termen lung','vaptanii cresc excreția de sodiu'],'ABC',186,'Antagoniștii vasopresinei',
 'Recunoașterea vaptanilor.',
 ['Tolvaptanul este selectiv V2.','Conivaptanul blochează ambii receptori.','Produc diureză apoasă selectivă.','Conivaptanul este intravenos.','Nu cresc excreția sodiului.']],
 [8,'Distractorii inversează calea și efectul pe sodiu.'],['tolvaptan','conivaptan']),

q('electroliti-adv-026',['Hiponatremia hipervolemică:',
 ['apare în insuficiența cardiacă și hepatică','se asociază cu reabsorbția proximală avidă de sodiu','este agravată de diuretice','se tratează de primă intenție cu salină 0,9%','are o rată de filtrare glomerulară redusă'],'ABCE',186,'Hiponatremia cu hipervolemie',
 'Recunoașterea hiponatremiei hipervolemice.',
 ['IC și insuficiența hepatică sunt cauze.','Reabsorbția proximală este avidă.','Diureticele agravează diluția.','Se tratează cu restricție.','RFG este redusă.']],
 [8,'Distractorii inversează RFG și tratamentul.'],['Insuficienţa cardiacă','apă liberă']),

q('electroliti-adv-088',['Hipernatremia:',
 ['indică de regulă un deficit de apă','cere o sete deficitară sau acces limitat la apă','poate fi produsă de litiu sau amfotericină B','presupune creșterea sodiului total al organismului','se asociază cu osmolalitate plasmatică scăzută'],'ABC',186,'Hipernatremia',
 'Recunoașterea hipernatremiei.',
 ['Indică aproape mereu un deficit de apă.','Setea previne altfel hipernatremia.','Litiul și amfotericina B dau diabet insipid nefrogen.','Nu implică neapărat creșterea sodiului total.','Osmolalitatea este crescută.']],
 [8,'Distractorii contrazic osmolalitatea și sodiul total.'],['Litiu','Amfotericina']),

q('electroliti-adv-028',['Tratamentul hipernatremiei:',
 ['peste 170 mmol/L începe cu salină 0,9%','urmărește corecția în 48 de ore','în formele mai ușoare folosește glucoză 5% sau 2,5%','în coma hiperosmolară preferă glucoza 10%','urmărește o scădere rapidă, în câteva ore'],'ABC',187,'Hipernatremia — tratament',
 'Aplicarea corecției hipernatremiei.',
 ['Salina 0,9% inițial peste 170 mmol/L.','Corecția în 48 de ore.','Glucoză 5% sau 2,5% în formele ușoare.','Se preferă glucoza 2,5%.','Corecția rapidă dă edem cerebral.']],
 [8,'Distractorii grăbesc corecția.'],['170 mmol/L','48 ore']),

q('electroliti-adv-064',['În diabetul insipid pituitar, administrarea desmopresinei:',
 ['crește osmolalitatea urinară','nu modifică osmolalitatea urinară','produce poliurie','crește natremia','scade sodiul urinar la zero'],'A',186,'Hipernatremia — investigații',
 'Diferențierea diabetului insipid pituitar de cel nefrogen.',
 ['Osmolalitatea urinară crește.','Descrie diabetul insipid nefrogen.','Reduce poliuria.','Reține apă.','Nu este efectul citat.']],
 [8,'Distractorii preiau răspunsul formei nefrogene.'],['desmopresinei','nefrogen']),

q('electroliti-adv-065',['Intrarea potasiului în celule:',
 ['este stimulată de insulină','este stimulată de stimularea β-adrenergică','este scăzută de acidoză','crește prin stimulare α-adrenergică','este stimulată de teofilină'],'ABCE',187,'Reglarea concentrației de potasiu',
 'Recunoașterea factorilor care deplasează potasiul.',
 ['Insulina stimulează intrarea.','β-stimularea stimulează intrarea.','Acidoza scade intrarea.','α-stimularea o scade.','Teofilina stimulează intrarea potasiului în celule.']],
 [8,'Distractorii inversează efectul α și al teofilinei.'],['insulină','teofilină']),

q('electroliti-adv-048',['Majoritatea potasiului din organism (~3.500 mmol la adult) se află:',
 ['intracelular','în plasmă','în lichidul interstițial','în oase','legat de albumină'],'A',187,'Reglarea concentrației de potasiu',
 'Localizarea depozitelor de potasiu.',
 ['Majoritatea este intracelulară.','Plasma conține puțin.','Interstițiul conține puțin.','Nu este datul citat.','Nu este datul citat.']],
 [8,'Distractorii sunt compartimente minore.'],['3.500','intracelular']),

q('electroliti-adv-049',['Manipularea renală a potasiului:',
 ['peste 90% din K+ filtrat se reabsoarbe proximal și în ansă','ductul colector asigură majoritatea excreției','aldosteronul crește secreția de K+','acidoza crește secreția renală de potasiu','reabsorbția proximală a K+ este un proces activ'],'ABC',187,'Reglarea concentrației de potasiu',
 'Recunoașterea manipulării renale a potasiului.',
 ['Peste 90% se reabsoarbe proximal și în ansă.','Secreția celulelor principale asigură excreția.','Aldosteronul stimulează secreția.','Acidoza reduce secreția.','Este pasivă.']],
 [8,'Distractorii inversează acidoza și natura reabsorbției.'],['90%','aldosteron']),

q('electroliti-adv-089',['Pierderile digestive de potasiu:',
 ['lichidul diareic conține 10–30 mmol/L de K+','voma conține 5–10 mmol/L de K+','vărsăturile produc hipokaliemie mai ales prin aldosteron','adenomul vilos poate da pierderi marcate','colonul reabsoarbe tot potasiul din lumen'],'ABCD',187,'Reglarea concentrației de potasiu',
 'Explicarea hipokaliemiei digestive.',
 ['Diareea: 10–30 mmol/L.','Voma: 5–10 mmol/L.','Depleția sodică stimulează aldosteronul.','Adenomul vilos poate da diaree profuză.','Colonul secretă potasiu.']],
 [8,'Singurul distractor neagă secreția colonică.'],['10-30','Adenoamele viloase']),

q('electroliti-adv-020',['Cauze de hipokaliemie prin redistribuție celulară sunt:',
 ['agoniștii β2, ex. salbutamol','tratamentul cu insulină','corecția anemiei megaloblastice','alcaloza metabolică','acidoza metabolică'],'ABCD',188,'Cadranul 9.17',
 'Recunoașterea hipokaliemiei prin redistribuție.',
 ['β-agoniștii introduc K+ în celule.','Insulina introduce K+ în celule.','Eritropoieza nouă consumă K+.','Alcaloza introduce K+ în celule.','Acidoza scoate K+ din celule.']],
 [8,'Singurul distractor inversează direcția.'],['salbutamol','megaloblastice']),

q('electroliti-adv-001',['Sindroamele Gitelman, Bartter și Liddle:',
 ['Gitelman are hipocalciurie','Bartter are renină crescută','Liddle are renină și aldosteron scăzute','Liddle răspunde la spironolactonă','Gitelman are hipertensiune arterială'],'ABC',188,'Sindroamele Bartter, Gitelman și Liddle',
 'Diferențierea tubulopatiilor hipokaliemice.',
 ['Gitelman: hipocalciurie.','Bartter: renină crescută.','Liddle: renină și aldosteron scăzute.','Spironolactona este ineficientă în Liddle.','Gitelman are tensiune normală.']],
 [8,'Distractorii inversează tensiunea și răspunsul terapeutic.'],['Gitelman','Liddle']),

q('electroliti-adv-090',['Sindromul Bartter:',
 ['seamănă cu efectul diureticelor de ansă','are hipercalciurie frecventă','tipul IV asociază surditate senzorio-neurală','are hipertensiune arterială cu renină mică','are renină și aldosteron scăzute'],'ABC',187,'Sindromul Bartter',
 'Recunoașterea sindromului Bartter.',
 ['Este similar diureticelor de ansă.','Hipercalciuria este frecventă.','Barttin: surditate și insuficiență renală.','Tensiunea este normală.','Renina și aldosteronul sunt crescute.']],
 [8,'Distractorii preiau profilul Liddle.'],['Bartter','surditate'],[188]),

q('electroliti-adv-044',['Hipokaliemia:',
 ['severă (<2,5 mmol/L) produce slăbiciune musculară','crește riscul de intoxicație digitalică','poate agrava hiponatremia','produce aritmii grave la cordul sănătos','rezistentă poate indica hipomagneziemie'],'ABCE',188,'Hipokaliemia — tablou clinic',
 'Recunoașterea consecințelor hipokaliemiei.',
 ['Slăbiciunea apare sub 2,5 mmol/L.','Crește legarea digoxinului.','Depleția de K+ poate produce hiponatremie.','Aritmiile grave sunt puțin probabile fără boală cardiacă.','Eșecul corectării poate ține de magneziu.']],
 [8,'Singurul distractor supraestimează riscul aritmic.'],['digitalică','hipomagneziemiei'],[189]),

q('electroliti-adv-050',['Administrarea intravenoasă de potasiu:',
 ['se face în salină 0,9%, nu în glucoză','se face sub 2 mmol/oră la insuficiența renală','este necesară în aritmii sau astenie musculară','se face preferabil în glucoză 5%','este prima opțiune în majoritatea hipokaliemiilor'],'ABC',189,'Hipokaliemia — tratament',
 'Aplicarea suplimentării intravenoase de potasiu.',
 ['Glucoza agravează hipokaliemia.','Sub 2 mmol/oră cu monitorizare.','Aritmiile și astenia o justifică.','Glucoza agravează hipokaliemia.','Calea orală este suficientă de regulă.']],
 [8,'Distractorii aleg vehiculul greșit și devansează calea i.v.'],['2 mmol','soluţii de glucoză'],[188]),

q('electroliti-adv-029',['Sindromul Gordon:',
 ['produce hipertensiune cu renină scăzută','produce hiperkaliemie și acidoză metabolică','răspunde la diuretice tiazidice','se datorează mutațiilor directe ale NCCT','este imaginea în oglindă a sindromului Liddle'],'ABC',189,'Sindromul Gordon',
 'Recunoașterea sindromului Gordon.',
 ['HTA cu renină/aldosteron scăzute.','Hiperkaliemie și acidoză.','Sensibilitatea la tiazide este crescută.','Sunt implicate WNK1 și WNK4.','Este imaginea în oglindă a Gitelman.']],
 [8,'Distractorii schimbă mecanismul genetic și perechea.'],['WNK','tiazidice']),

q('electroliti-adv-066',['Conform Cadranului 9.19, cauze de hiperkaliemie sunt:',
 ['amiloridul','heparina','ciclosporina','succinilcolina','salbutamolul'],'ABCD',189,'Cadranul 9.19',
 'Recunoașterea cauzelor medicamentoase de hiperkaliemie.',
 ['Reduce excreția.','Reduce excreția.','Reduce excreția.','Crește eliberarea din celule.','Introduce K+ în celule.']],
 [8,'Singurul distractor scade kaliemia.'],['Heparina','Succinilcolina']),

q('electroliti-adv-030',['Hiperkaliemia severă:',
 ['peste 7 mmol/L este urgență medicală','poate fi complet asimptomatică clinic','poate duce la oprire cardiacă în asistolă','produce tahicardie și hipertensiune arterială','persistă după efort fizic marcat'],'ABC',190,'Hiperkaliemia — tablou clinic',
 'Recunoașterea gravității hiperkaliemiei.',
 ['Peste 7 mmol/L este urgență.','Poate fi asimptomatică.','Asistola este riscul major.','Produce bradicardie și hipotensiune.','Hiperkaliemia de efort este tranzitorie.']],
 [8,'Distractorii inversează efectul hemodinamic.'],['7.0 mmol/L','asistolă']),

q('electroliti-adv-068',['Conform Figurii 9.12, pe măsură ce hiperkaliemia crește:',
 ['apar unde T înalte, în cort','unda P se diminuează','apare un model sinusoidal cu QRS lărgit','unda T se aplatizează','complexul QRS se îngustează'],'ABC',190,'Figura 9.12',
 'Recunoașterea modificărilor ECG din hiperkaliemie.',
 ['Unda T în cort.','Unda P diminuată.','Model sinusoidal pre-oprire.','Unda T devine ascuțită.','QRS se lărgește.']],
 [8,'Distractorii inversează modificările ECG.'],['Unda T','sinusoidal']),

q('electroliti-adv-067',['Tratamentul de urgență al hiperkaliemiei:',
 ['gluconatul de calciu protejează miocardul fără să scadă K+','insulina cu glucoză scade K+ cu ~5 mmol/L în 60 de minute','glucoza singură nu este recomandată la nediabetic','calciul scade potasiul seric cu ~1 mmol/L într-o oră','rășinile schimbătoare sunt superioare noilor chelatori'],'AC',190,'Hiperkaliemia — tratament',
 'Aplicarea tratamentului de urgență al hiperkaliemiei.',
 ['Calciul protejează membranele.','Nu: insulina scade K+ cu ~1 mmol/L în 60 de minute.','Glucoza singură nu atinge insulina necesară.','Calciul nu modifică potasiul.','Noii chelatori sunt superiori.']],
 [8,'Distractorii atribuie calciului efect hipokaliemiant.'],['gluconat de calciu','60 min']),

q('electroliti-adv-073',['Tratamentul subacut și definitiv al hiperkaliemiei:',
 ['patiromerul leagă potasiul în tractul digestiv','dializa este tratamentul definitiv în insuficiența renală severă','bicarbonatul 1,26% se folosește în acidoza severă','rășinile cresc semnificativ excreția de potasiu','bicarbonatul 8,4% se folosește de rutină'],'ABC',190,'Hiperkaliemia — tratament',
 'Aplicarea măsurilor subacute în hiperkaliemie.',
 ['Patiromerul leagă K+ în tubul digestiv.','Dializa este tratamentul definitiv.','1,26% în acidoza severă.','Nu potențează semnificativ excreția.','8,4% doar în urgență.']],
 [8,'Distractorii supraestimează rășinile și bicarbonatul hiperton.'],['Patiromerul','dializă']),
];
