import {rewriter} from './rewrite-author';
import {RETIRED_ENDOCRINOLOGIE} from './retired/endocrinologie';

// Rewritten after the 2026-09-24 cue audit (Kumar, cap. 21, p. 611–618 until «Gușa»,
// and 621–622 from «Carcinomul tiroidian»).
const q=rewriter(RETIRED_ENDOCRINOLOGIE,(p:number)=>p<=618?p-523:p-525,{shuffle:true});

export const ENDOCRINOLOGIE_V2=[
q('endocrinologie-adv-021',['Conform Cadranului 21.25, hormonii tiroidieni:',
 ['cresc debitul cardiac','cresc numărul receptorilor β-adrenergici','scad 2,3-BPG eritrocitar','scad numărul receptorilor β-adrenergici cardiaci','scad motilitatea intestinală'],'AB',611,'Cadranul 21.25',
 'Recunoașterea efectelor fiziologice ale hormonilor tiroidieni.',
 ['Cresc ritmul și debitul cardiac.','Cresc sensibilitatea la catecolamine și receptorii β.','Nu: hormonii tiroidieni cresc 2,3-BPG, facilitând eliberarea O2.','Scad receptorii α, nu β.','Cresc motilitatea intestinală.']],
 [8,'Distractorii inversează efectele.'],['2,3-BPG','motilitatea intestinului']),

q('endocrinologie-adv-022',['Conform Cadranului 21.26, T3-toxicoza are:',
 ['TSH supresat, fT4 normală, fT3 crescută','TSH supresat, fT4 și fT3 crescute','TSH crescut, fT4 scăzută, fT3 normală','TSH normal, fT4 crescută și fT3 scăzută','TSH ușor crescut, fT4 și fT3 normale'],'A',611,'Cadranul 21.26',
 'Interpretarea profilului hormonal în T3-toxicoză.',
 ['T3-toxicoza: TSH supresat, fT4 normală, fT3 crescută.','Descrie tirotoxicoza obișnuită.','Descrie hipotiroidismul primar.','Nu este profilul citat.','Descrie eutiroidismul compensat.']],
 [8,'Distractorii sunt celelalte profiluri din cadran.'],['T3 Toxicoza','Supresat']),

q('endocrinologie-adv-023',['Conform Cadranului 21.26, eutiroidismul compensat are:',
 ['TSH ușor crescut, de 5–10 mU/L','fT4 normală','fT3 normală','TSH supresat, sub 0,05 mU/L','fT4 scăzută'],'ABC',611,'Cadranul 21.26',
 'Recunoașterea profilului eutiroidismului compensat.',
 ['TSH este ușor ridicat (5–10 mU/L).','fT4 este normală.','fT3 este normală.','Descrie tirotoxicoza.','fT4 scăzută apare în hipotiroidismul primar.']],
 [8,'Distractorii preiau valori din alte profiluri.'],['5-10mU/L','Eutiroidism']),

q('endocrinologie-adv-001',['La persoane eutiroidiene, contraceptivele orale și amiodarona modifică testele tiroidiene astfel:',
 ['CO cresc TBG și T4 totală; amiodarona scade conversia T4→T3','CO cresc TBG și fT4; amiodarona scade conversia T4→T3','CO scad TBG; amiodarona crește conversia T4→T3','CO cresc TBG și T4 totală; amiodarona crește conversia T4→T3','CO stimulează receptorul TSH; amiodarona scade conversia T4→T3'],'A',611,'Testele funcționale tiroidiene',
 'Interpretarea testelor tiroidiene sub medicamente.',
 ['CO cresc TBG și T4 totală, fT4 rămânând normală; amiodarona scade conversia.','fT4 rămâne de regulă normală.','CO cresc TBG.','Amiodarona scade conversia.','Nu este mecanismul citat.']],
 [8,'Distractorii modifică un singur element.'],['TBG','Amiodarona scade conversia']),

q('endocrinologie-adv-006',['În interpretarea testelor tiroidiene discordante:',
 ['boala sistemică severă poate scădea T4/T3 cu TSH normal','rezistența la hormonii tiroidieni asociază T4 crescută cu TSH normal','testele se repetă după rezolvarea bolii de fond','TSH normal cu fT4 scăzută exclude deficitul de TSH','T4 crescută cu TSH normal confirmă adenomul hipofizar'],'ABC',611,'Testele funcționale tiroidiene',
 'Interpretarea situațiilor biochimice discordante.',
 ['„Euthyroid sick syndrome” scade T4/T3 cu TSH normal sau scăzut.','Rezistența asociază T4/T3 crescute cu TSH normal.','Testele se repetă după rezolvarea bolii.','Deficitul de TSH trebuie exclus la TSH normal cu fT4 scăzută.','Diagnosticul diferențial include rezistența și interferențele.']],
 [8,'Distractorii transformă ipoteze în certitudini.'],['euthyroid sick syndrome','TSH normal'],[618]),

q('endocrinologie-adv-002',['Relația corectă dintre autoanticorpii tiroidieni și ținta lor este:',
 ['anti-TPO: peroxidaza; TRAb: receptorul TSH, stimulatori','anti-TPO: receptorul TSH; TRAb: peroxidaza tiroidiană, stimulatori','anti-TPO: tiroglobulina; TRAb: receptorul TSH, stimulatori','anti-TPO: peroxidaza; TRAb: receptorul TSH, de obicei blocanți','anti-TPO: peroxidaza; TRAb: tiroglobulina, stimulatori'],'A',611,'Anticorpii anti-tiroidieni',
 'Recunoașterea țintelor autoanticorpilor tiroidieni.',
 ['Anti-TPO vizează peroxidaza; TRAb stimulează de obicei receptorul TSH.','Țintele sunt inversate.','Antigenul microzomal este TPO.','TRAb doar ocazional blochează.','TRAb vizează receptorul TSH.']],
 [8,'Distractorii permută țintele și efectul.'],['peroxidaza tiroidiană','ocazional blochează']),

q('endocrinologie-adv-046',['Anticorpii anti-tiroidieni:',
 ['anti-TPO se găsesc la până la 20% din populația normală','doar 10–20% dintre purtătorii anti-TPO devin hipotiroidieni','TRAb sunt specifici tiroiditei Hashimoto','anti-TPO lipsesc la persoanele eutiroidiene','majoritatea purtătorilor anti-TPO devin hipotiroidieni'],'AB',611,'Anticorpii anti-tiroidieni',
 'Interpretarea prevalenței și semnificației anticorpilor.',
 ['Până la 20% din populație, mai ales femei vârstnice.','Doar 10–20% dezvoltă hipotiroidism manifest.','Nu: TRAb sunt specifici bolii Graves.','Sunt frecvenți în populația normală.','Doar 10–20% evoluează spre hipotiroidism.']],
 [8,'Distractorii supraestimează semnificația anti-TPO.'],['20% din populaţia','10-20%']),

q('endocrinologie-adv-033',['Hipotiroidismul primar:',
 ['are prevalență în Marea Britanie de peste 2% la femei','are prevalență sub 0,1% la bărbați','se diagnostichează în medie în jurul vârstei de 30 de ani','are prevalență identică la cele două sexe','este de obicei secundar unei boli hipofizare'],'AB',611,'Hipotiroidismul — Fiziopatologie',
 'Fixarea epidemiologiei hipotiroidismului.',
 ['Prevalența depășește 2% la femei.','Este sub 0,1% la bărbați.','Nu: vârsta medie la diagnostic este ~60 de ani.','Predomină net la femei.','Este de obicei primar.']],
 [8,'Distractorii inversează distribuția pe sexe și etiologia.'],['0,1%','60 de ani']),

q('endocrinologie-adv-045',['Hipotiroidismul atrofic autoimun:',
 ['este cea mai frecventă cauză de hipotiroidism','este de șase ori mai frecvent la femei','se asociază cu anemia pernicioasă și vitiligo','este de obicei secundar unei boli hipofizare','are incidență care scade cu vârsta'],'ABC',611,'Boala tiroidiană autoimună',
 'Recunoașterea hipotiroidismului atrofic autoimun.',
 ['Este cea mai frecventă cauză de hipotiroidism.','Forma atrofică este de șase ori mai frecventă la femei.','Se asociază cu alte boli autoimune.','Este o boală tiroidiană primară.','Incidența crește cu vârsta.']],
 [8,'Distractorii inversează etiologia și vârsta.'],['şase ori','vitiligo']),

q('endocrinologie-adv-034',['Tiroidita Hashimoto:',
 ['produce gușă fermă, cauciucată','are anti-TPO adesea în titruri foarte înalte','poate trece printr-o fază toxică inițială','nu răspunde la levotiroxină la pacienții eutiroidieni','produce atrofie fără gușă'],'ABC',612,'Tiroidita Hashimoto',
 'Recunoașterea tiroiditei Hashimoto.',
 ['Glanda este de obicei fermă, cauciucată.','Anti-TPO depășesc adesea 1.000 UI/L.','Poate exista „Hashi-toxicoză”.','Levotiroxina poate reduce gușa chiar la eutiroidieni.','Regenerarea produce gușă.']],
 [8,'Distractorii contrazic gușa și răspunsul la tratament.'],['cauciucată','Hashi-toxicoza']),

q('endocrinologie-adv-047',['Tiroidita postpartum:',
 ['poate produce secvențial hiper- și hipotiroidism','este histologic o tiroidită limfocitară','poate fi confundată cu depresia postnatală','este o tiroidită granulomatoasă virală','nu evoluează spre hipotiroidism permanent'],'ABC',612,'Tiroidita postpartum',
 'Recunoașterea tiroiditei postpartum.',
 ['Poate produce hiper-, hipotiroidism sau ambele secvențial.','Histologic este limfocitară.','Poate fi diagnosticată eronat ca depresie postnatală.','Tiroidita de Quervain este probabil virală.','Anticorpii pozitivi cresc riscul de hipotiroidism permanent.']],
 [8,'Distractorii confundă entitatea cu tiroidita subacută.'],['postpartum','limfocitară']),

q('endocrinologie-adv-024',['Deficitul alimentar de iod:',
 ['produce gușa endemică','poate produce eu- sau hipotiroidism, după severitate','era asociat în India cu ~2 milioane de cazuri de cretinism','a dispărut complet după iodarea sării','nu mai este o problemă în Olanda sau Rusia'],'ABC',612,'Defecte ale sintezei hormonale',
 'Recunoașterea consecințelor deficitului de iod.',
 ['Produce gușă endemică.','Starea funcțională depinde de severitate.','Din 500 de milioane de cazuri, ~2 milioane aveau cretinism.','Succesul prevenției este incomplet.','Deficitul este încă o problemă în aceste zone.']],
 [8,'Distractorii supraestimează succesul iodării.'],['guşă endemică','2 milioane']),

q('endocrinologie-adv-048',['Sindromul Pendred:',
 ['asociază surditate senzorială','se datorează unei deleții pe cromozomul 21','afectează transportorul pendrina','se datorează unei mutații RET','produce surditate de conducere'],'AC',612,'Dishormonogeneza',
 'Recunoașterea sindromului Pendred.',
 ['Asociază surditate senzorială.','Nu: deleția este pe cromozomul 7.','Defectul privește pendrina.','RET privește carcinomul medular.','Surditatea este senzorială.']],
 [8,'Distractorii schimbă defectul genetic și tipul surdității.'],['pendrina','cromozomului 7']),

q('endocrinologie-adv-049',['În hipotiroidismul primar pot apărea:',
 ['anemie macrocitară prin anemie pernicioasă asociată','creșterea creatinkinazei cu miopatie','hiponatremie prin creșterea ADH','hipercolesterolemie','poliglobulie prin exces de eritropoietină'],'ABCD',613,'Investigarea hipotiroidismului',
 'Recunoașterea anomaliilor de laborator din hipotiroidism.',
 ['Anemia poate fi macrocitară prin anemie pernicioasă.','Creatinkinaza crește, cu miopatie asociată.','ADH crescut produce hiponatremie.','Apar hipercolesterolemie și hipertrigliceridemie.','Apare anemie, nu poliglobulie.']],
 [8,'Singurul distractor inversează seria roșie.'],['creatinkinază','hiponatremie']),

q('endocrinologie-adv-035',['Tratamentul cu levotiroxină în hipotiroidismul primar:',
 ['începe cu 100 µg/zi la pacienții tineri și apți','începe cu 25 µg/zi la boala cardiacă ischemică','are doza de întreținere uzuală de 100–150 µg/zi','evită supresia completă a TSH','începe cu 100 µg/zi la vârstnicul ischemic'],'ABCD',613,'Terapia de substituție hormonală',
 'Aplicarea dozării levotiroxinei.',
 ['100 µg la tineri și apți.','25 µg la boala cardiacă ischemică.','Întreținerea este 100–150 µg.','Supresia completă crește riscul de FA și osteoporoză.','Vârstnicul ischemic începe cu doze mici.']],
 [8,'Singurul distractor ignoră riscul cardiac.'],['25','100-150']),

q('endocrinologie-adv-050',['Monitorizarea substituției cu levotiroxină:',
 ['se evaluează după cel puțin 1 săptămână de doză constantă','în sarcină doza crește adesea cu 25–50 µg','fierul și calciul pot scădea absorbția tiroxinei','combinația T4+T3 are beneficiu constant asupra calității vieții','inhibitorii pompei de protoni cresc absorbția tiroxinei'],'BC',613,'Monitorizarea',
 'Aplicarea monitorizării tratamentului substitutiv.',
 ['Nu: evaluarea se face după cel puțin 6 săptămâni.','Doza crește cu 25–50 µg pentru TSH 0,3–2,5 mU/L.','Fierul, calciul și IPP interferă cu absorbția.','RCT nu au arătat beneficiu constant.','IPP scad absorbția.']],
 [8,'Distractorii contrazic datele despre combinație și IPP.'],['6 săptămâni','0,3-2,5']),

q('endocrinologie-adv-036',['Hipotiroidismul de graniță (eutiroidismul compensat):',
 ['se tratează dacă TSH rămâne constant peste 10 mU/L','se retestează la 3–6 luni dacă TSH e marginal crescut','evoluează mai des spre hipotiroidism la titruri mari de anti-TPO','se tratează imediat la orice TSH peste limita normală','evoluează mai des spre hipotiroidism la femei'],'ABC',613,'Hipotiroidismul de graniță',
 'Aplicarea conduitei în hipotiroidismul subclinic.',
 ['TSH constant >10 mU/L justifică tratamentul.','O proporție semnificativă se normalizează la retestare.','Anti-TPO în titru crescut cresc riscul de progresie.','Creșterile marginale se retestează.','Progresia este mai frecventă la bărbați.']],
 [8,'Distractorii grăbesc tratamentul și inversează sexul.'],['10 mU/L','3-6 luni']),

q('endocrinologie-adv-037',['În coma mixedematoasă, majoritatea medicilor recomandă:',
 ['T3 2,5–5 µg la fiecare 8 ore','T4 500 µg în bolus intravenos','T3 100 µg în bolus intravenos','doar reîncălzire rapidă, fără hormoni','levotiroxină 100 µg/zi, ca la tineri'],'A',613,'Coma mixedematoasă',
 'Alegerea tratamentului hormonal în coma mixedematoasă.',
 ['T3 oral sau IV 2,5–5 µg la 8 ore, apoi creștere treptată.','Nu se folosesc doze mari intravenoase.','Nu se folosesc doze mari intravenoase.','Reîncălzirea este treptată și adjuvantă.','Nu este schema citată.']],
 [8,'Distractorii folosesc doze mari sau măsuri izolate.'],['2,5-5','Coma mixedematoasă']),

q('endocrinologie-adv-038',['Hipotiroidismul congenital:',
 ['are incidența de aproximativ 1 la 3.500 de nașteri','produce cretinism dacă este sever și netratat','se depistează prin screeningul TSH din picătura de sânge','are incidența de aproximativ 1 la 50 de nașteri','se tratează eficient chiar după vârsta de 5 ani'],'ABC',613,'Screening-ul hipotiroidismului',
 'Aplicarea screeningului hipotiroidismului congenital.',
 ['Incidența este ~1 la 3.500.','Netratat sever produce cretinism.','Testul Guthrie detectează TSH crescut.','Incidența este 1 la 3.500.','Tratamentul trebuie început în primele luni.']],
 [8,'Distractorii umflă incidența și întârzie tratamentul.'],['3.500','Guthrie']),

q('endocrinologie-adv-039',['Hipertiroidismul:',
 ['afectează 2–5% dintre femei','are raport femei:bărbați de 1:1','are cauză tiroidiană în peste 99% din cazuri','are frecvent o cauză hipofizară, prin exces de TSH','apare cel mai adesea după 70 de ani'],'AC',614,'Hipertiroidismul',
 'Fixarea epidemiologiei hipertiroidismului.',
 ['Afectează 2–5% dintre femei.','Nu: raportul pe sexe este 5:1.','Peste 99% sunt de cauză tiroidiană.','Cauza hipofizară este extrem de rară.','Apare cel mai adesea între 20 și 40 de ani.']],
 [8,'Distractorii contrazic etiologia și vârsta.'],['5:1','>99%'],[613]),

q('endocrinologie-adv-012',['Conform Cadranului 21.29, în diagnosticul tirotoxicozei:',
 ['boala Graves are captare difuză și TRAb în titru ridicat','nodulul toxic are captare focală','tiroidita are captare minimă a trasorului','tiroidita are captare difuză intensă','gușa multinodulară toxică remite durabil după antitiroidiene'],'ABC',614,'Cadranul 21.29',
 'Diferențierea etiologiilor tirotoxicozei.',
 ['Graves: captare difuză și TRAb crescuți.','Nodulul toxic: captare focală, restul glandei suprimat.','Tiroidita: captare minimă.','Captarea este suprimată.','Antitiroidienele rareori induc rezoluția.']],
 [8,'Distractorii inversează captarea și prognosticul.'],['Captare difuză','Captare focală']),

q('endocrinologie-adv-052',['Tiroidita De Quervain:',
 ['este probabil de origine virală','produce durere cervicală și sensibilitate tiroidiană','arată VSH crescut și captare scintigrafică suprimată','este urmată adesea de hipotiroidism tranzitoriu','arată captare scintigrafică difuz crescută'],'ABCD',614,'Tiroidita De Quervain',
 'Recunoașterea tiroiditei subacute.',
 ['Procesul inflamator este probabil viral.','Durerea cervicală și sensibilitatea sunt tipice.','VSH crescut și captare suprimată.','Hipotiroidismul tranzitoriu apare după săptămâni.','Captarea este suprimată.']],
 [8,'Singurul distractor preia captarea din Graves.'],['De Quervain','vâscozitatea plasmatică']),

q('endocrinologie-adv-003',['Tirotoxicoza indusă de amiodaronă:',
 ['tipul I apare pe boală Graves sau gușă multinodulară preexistentă','tipul I este declanșat de conținutul de iod','tipul II este o tiroidită distructivă','tipul II apare pe gușă multinodulară preexistentă','tipul I este o tiroidită distructivă'],'ABC',615,'Tirotoxicoza indusă de amiodaronă',
 'Diferențierea tipurilor de tirotoxicoză indusă de amiodaronă.',
 ['Tipul I apare pe boală tiroidiană preexistentă.','Iodul din amiodaronă declanșează tipul I.','Tipul II rezultă dintr-un efect folicular direct.','Tipul II nu are boală tiroidiană anterioară.','Distrucția caracterizează tipul II.']],
 [8,'Distractorii inversează tipurile.'],['tip I','tiroidită distructivă']),

q('endocrinologie-adv-040',['Tirotoxicoza indusă de inhibitorii punctului de control imun:',
 ['tiroidita apare la ~15% dintre pacienți','hipofizita apare la ~9%','tiroidita apare la 3–12 săptămâni de la inițiere','se tratează cu beta-blocante și analgezice','diabetul de tip 1 e efectul cel mai frecvent'],'ABCD',615,'Tirotoxicoza indusă de imunoterapie',
 'Fixarea efectelor endocrine ale imunoterapiei.',
 ['Tiroidita: 15%.','Hipofizita: 9%.','Tiroidita apare la 3–12 săptămâni.','Beta-blocante, analgezice, rar antitiroidiene.','Diabetul de tip 1 apare sub 1%.']],
 [8,'Singurul distractor inversează frecvența.'],['15%','3 şi 12']),

q('endocrinologie-adv-010',['Semnele oculare și orbitopatia Graves:',
 ['retracția palpebrală apare în orice hipertiroidism','orbitopatia apare și la eutiroidieni','orbitopatia este mai severă la fumători','severitatea oculară urmărește nivelul fT4','orbitopatia poate fi uneori unilaterală'],'ABCE',615,'Anamneză și examen obiectiv',
 'Diferențierea semnelor oculare generale de orbitopatia Graves.',
 ['Retracția palpebrală apare în orice hipertiroidism.','Orbitopatia apare și la eu- sau hipotiroidieni.','Fumatul agravează orbitopatia.','Nu evoluează în paralel cu tirotoxicoza.','Orbitopatia poate fi uneori unilaterală.']],
 [8,'Distractorii leagă orbitopatia de biochimie.'],['retracţia palpebrală','fumători'],[618]),

q('endocrinologie-adv-053',['La vârstnicul cu fibrilație atrială nou apărută, fără alte semne:',
 ['se testează funcția tiroidiană','TSH nu este necesar după 70 de ani','se începe direct carbimazol','se administrează iod radioactiv fără confirmare','ecografia cervicală înlocuiește testele hormonale'],'A',615,'Anamneză și examen obiectiv',
 'Aplicarea screeningului tiroidian în fibrilația atrială.',
 ['Testele tiroidiene sunt obligatorii la orice FA.','Vârsta nu scutește de testare.','Tratamentul cere confirmare biochimică.','Tratamentul cere confirmare biochimică.','Nu este recomandarea citată.']],
 [8,'Distractorii omit confirmarea biochimică.'],['fibrilaţie atrială','obligatorii']),

q('endocrinologie-adv-025',['Diferențierea hipertiroidismului de anxietate se sprijină pe:',
 ['semnele oculare','gușa difuză','tegumentele periferice calde','mâinile reci și umede','scăderea apetitului'],'ABC',616,'Diagnostic diferențial',
 'Aplicarea semnelor clinice discriminante.',
 ['Semnele oculare sunt utile.','Gușa difuză este utilă.','Circulația hiperdinamică dă tegumente calde.','Mâinile reci și umede sugerează anxietatea.','Scăderea ponderală apare cu apetit normal sau crescut.']],
 [8,'Distractorii descriu anxietatea.'],['guşa difuză','mâini reci']),

q('endocrinologie-adv-026',['Confirmarea biochimică a hipertiroidismului:',
 ['TSH este suprimat sub 0,05 mU/L','T3 este mai sensibilă decât T4','TRAb de generația a treia sunt 97–99% specifici pentru Graves','anti-TPO sunt 97–99% specifici pentru Graves','tratamentul se poate începe fără confirmare biochimică'],'ABC',616,'Investigații',
 'Interpretarea testelor în hipertiroidism.',
 ['TSH este suprimat, cu excepția hipersecreției rare de TSH.','T3 este mai sensibilă (T3-toxicoza).','TRAb de generația a treia sunt 97–99% specifici.','Anti-TPO apar și la persoane fără patologie.','Tratamentul nu se instituie fără confirmare.']],
 [8,'Distractorii confundă anticorpii și omit confirmarea.'],['<0,05','97-99%']),

q('endocrinologie-adv-027',['Beta-blocantele în hipertiroidism:',
 ['asigură control simptomatic parțial rapid','scad conversia periferică T4→T3','se preferă fără activitate simpaticomimetică intrinsecă','sunt monoterapie de primă intenție în boala Graves','se preferă cu activitate simpaticomimetică intrinsecă'],'ABC',616,'Tratament',
 'Aplicarea rolului beta-blocantelor.',
 ['Controlează rapid manifestările mediate simpatic.','Scad conversia periferică.','Se preferă propranololul, fără ASI.','Monoterapia se rezervă formelor autolimitante.','Se preferă fără ASI.']],
 [8,'Distractorii contrazic rolul adjuvant.'],['propranolol','conversia periferică']),

q('endocrinologie-adv-041',['Carbimazolul:',
 ['se începe de obicei cu 20–40 mg/zi','are ca metabolit activ tiamazolul','produce agranulocitoză la ~10%','are beneficiu clinic imediat, în primele 48 de ore','se începe de obicei cu 200 mg/zi'],'AB',616,'Medicația antitiroidiană',
 'Aplicarea tratamentului cu carbimazol.',
 ['Doza inițială uzuală este 20–40 mg/zi.','Tiamazolul este metabolitul activ.','Nu: agranulocitoza apare la ~1 din 1.000.','Beneficiul apare după 10–20 de zile.','Doza este 20–40 mg.']],
 [8,'Distractorii schimbă doza și cinetica.'],['20-40 mg','tiamazolul']),

q('endocrinologie-adv-005',['Regimul „blocare și substituție” este contraindicat în sarcină deoarece:',
 ['tiroxina traversează placenta mai slab decât carbimazolul','tiroxina maternă traversează placenta mai ușor decât carbimazolul','antitiroidienele nu traversează placenta','TRAb nu traversează placenta','carbimazolul este teratogen în trimestrul trei'],'A',617,'Hipertiroidismul în sarcină',
 'Explicarea contraindicației regimului bloc-substituție în sarcină.',
 ['Pasajul slab al tiroxinei nu compensează blocarea tiroidei fetale.','Pasajul este invers.','Antitiroidienele traversează placenta.','TSI traversează placenta.','Nu este motivul citat.']],
 [8,'Distractorii inversează pasajul transplacentar.'],['traversează placenta','blocare şi substituţie'],[616]),

q('endocrinologie-adv-054',['Recidiva după o cură de antitiroidiene:',
 ['apare la aproximativ 50% dintre pacienți','apare mai ales în primii 2 ani','este mai probabilă la gușile multinodulare voluminoase','apare la sub 5% după 18 luni de tratament','este mai rară în hipertiroidismul biochimic sever'],'ABC',616,'Medicația antitiroidiană — Recidiva',
 'Fixarea riscului de recidivă.',
 ['Aproximativ 50% recidivează.','Majoritatea în cei 2 ani de după oprire.','Gușile nodulare voluminoase remit rar.','Recidiva este ~50%.','Riscul este mai mare în formele severe.']],
 [8,'Distractorii subestimează recidiva.'],['50%','multinodulare']),

q('endocrinologie-adv-014',['Iodul radioactiv în hipertiroidism:',
 ['impune oprirea mai precoce a PTU decât a carbimazolului','devine complet eficient după câteva luni','impune supravegherea pe termen lung a funcției tiroidiene','agravează mai rar orbitopatia decât antitiroidienele','crește riscul neoplazic'],'ABC',617,'Iodul radioactiv',
 'Aplicarea principiilor tratamentului cu iod radioactiv.',
 ['PTU are efect radioprotector.','Efectul complet apare după câteva luni.','Hipotiroidismul apare la majoritate în 20 de ani.','Agravarea oculară este mai frecventă după IRA.','Nu există risc neoplazic crescut.']],
 [8,'Distractorii inversează riscurile.'],['radioprotectoare','câteva luni']),

q('endocrinologie-adv-028',['Protocolul iodului radioactiv 131I:',
 ['folosește de obicei 400–550 MBq','cere oprirea antitiroidianului cu ≥4 zile înainte','duce de regulă la eutiroidism în 2–3 zile','este permis în sarcină și în alăptare','folosește de obicei 50 MBq în doză unică'],'AB',617,'Iodul radioactiv',
 'Aplicarea protocolului de iod radioactiv.',
 ['Doza empirică este 400–550 MBq.','Antitiroidianul se oprește cu ≥4 zile înainte.','Nu: eutiroidismul apare în 2–3 luni.','Este contraindicat în sarcină și alăptare.','Doza este 400–550 MBq.']],
 [8,'Distractorii schimbă doza și contraindicația.'],['400-550','4 zile']),

q('endocrinologie-adv-029',['Pregătirea preoperatorie pentru tiroidectomie:',
 ['se face doar la pacientul eutiroidian','presupune oprirea antitiroidianului cu 10–14 zile înainte','folosește iodură de potasiu care reduce vascularizația','se face în tirotoxicoză necontrolată','folosește iodură de potasiu care crește sinteza hormonală'],'ABC',617,'Tratamentul chirurgical',
 'Aplicarea pregătirii preoperatorii.',
 ['Tiroidectomia se face doar la eutiroidieni.','Antitiroidianul se oprește cu 10–14 zile înainte.','Iodura reduce vascularizația (efect Wolff–Chaikoff).','Pacientul trebuie eutiroidian.','Iodura inhibă organificarea.']],
 [8,'Distractorii inversează efectul iodurii.'],['10-14 zile','Wolff-Chaikoff']),

q('endocrinologie-adv-030',['Complicațiile tiroidectomiei:',
 ['pareza de nerv laringeu apare în ~1%','hipocalcemia tranzitorie apare în maximum 10%','hipoparatiroidismul permanent apare sub 1%','sângerarea precoce impune suprimarea clipsurilor','pareza de nerv laringeu apare în ~25%'],'ABCD',617,'Tratamentul chirurgical — Complicații',
 'Fixarea frecvenței complicațiilor tiroidectomiei.',
 ['Pareza laringeală: 1%.','Hipocalcemia tranzitorie: ≤10%.','Hipoparatiroidismul permanent: <1%.','Hematomul compresiv impune suprimarea imediată a clipsurilor.','Frecvența este 1%.']],
 [8,'Singurul distractor umflă frecvența.'],['1% din cazuri','10%']),

q('endocrinologie-adv-031',['Tiroidectomia în hipertiroidism:',
 ['subtotală recidivează la 1–3% în primul an','cvasitotală este tehnica preferată','nodulul toxic unic se vindecă prin excizia leziunii','subtotală garantează eutiroidia definitivă','cvasitotală păstrează eutiroidia fără tratament'],'ABC',617,'Tratamentul chirurgical',
 'Compararea tehnicilor de tiroidectomie.',
 ['Subtotala recidivează la 1–3% în primul an, apoi 1%/an.','Cvasitotala reduce mult riscul de recidivă.','Excizia nodulului toxic unic este curativă.','Subtotala produce și hipotiroidism.','Cvasitotala produce hipotiroidism inevitabil.']],
 [8,'Distractorii inversează consecințele funcționale.'],['cvasitotală','1-3%']),

q('endocrinologie-adv-032',['Criza tiroidiană:',
 ['are mortalitate de aproximativ 10%','produce hiperpirexie și tahicardie severă','impune propranolol, iodură, antitiroidian și corticoid','are mortalitate de aproximativ 90%','contraindică iodura de potasiu în faza acută'],'ABC',617,'Criza tiroidiană',
 'Recunoașterea și tratamentul crizei tiroidiene.',
 ['Mortalitatea este de 10%.','Hiperpirexia și tahicardia severă sunt tipice.','Tratamentul combină aceste măsuri de urgență.','Mortalitatea este de 10%.','Iodura face parte din tratament.']],
 [8,'Distractorii umflă mortalitatea și contrazic tratamentul.'],['10%','hiperpirexie']),

q('endocrinologie-adv-055',['Boala Graves maternă și nou-născutul:',
 ['TSI pot persista și după chirurgie sau iod radioactiv','TSI au un timp de înjumătățire de ~3 săptămâni','hipertiroidismul neonatal produce iritabilitate și diaree','simpaticomimeticele tocolitice sunt contraindicate','alăptarea este contraindicată sub carbimazol'],'ABCD',618,'Fătul și boala Graves maternă',
 'Recunoașterea riscurilor fetale și neonatale.',
 ['Anticorpii pot persista și la mama eutiroidiană.','TSI au timp de înjumătățire de ~3 săptămâni.','Manifestările includ iritabilitate, diaree, semne oculare.','Pot provoca tahicardie fetală.','Alăptarea pare sigură la doze uzuale.']],
 [8,'Singurul distractor contrazice siguranța alăptării.'],['3 săptămâni','iritabilitate']),

q('endocrinologie-adv-016',['Rezistența la hormonii tiroidieni:',
 ['este cauzată de anomalii ale receptorului TRβ','asociază T4/T3 crescute cu TSH normal','poate produce efecte tirotoxice cardiace','se diferențiază de adenomul hipofizar secretant de TSH','impune tratament antitiroidian de rutină'],'ABCD',618,'Rezistența la hormonii tiroidieni',
 'Recunoașterea rezistenței la hormonii tiroidieni.',
 ['Mutațiile TRβ cer concentrații hormonale mai mari.','T4/T3 sunt crescute cu TSH normal.','Țesuturile cu receptori normali pot avea efecte tirotoxice.','Diagnosticul diferențial include adenomul TSH-secretant.','Pacientul eutiroidian nu necesită tratament.']],
 [8,'Singurul distractor impune tratament inutil.'],['TR','adenomul hipofizar']),

q('endocrinologie-adv-043',['În evaluarea nodulului tiroidian solitar:',
 ['riscul de malignitate este de ~5%','FNA are ~5% rezultate fals-negative','nodulul rece este malign în ~10% din cazuri','nodulul rece este malign în ~90% din cazuri','scintigrafia a înlocuit FNA în diagnostic'],'ABC',621,'Gușa — FNA și scintigrafie',
 'Interpretarea riscului de malignitate și a limitelor FNA.',
 ['Riscul este 5% la nodulul solitar sau dominant.','FNA are 5% fals-negative; pacientul este consiliat.','Nodulul rece este malign în doar 10% din cazuri.','Doar 10% dintre nodulii reci sunt maligni.','FNA a înlocuit practic scintigrafia.']],
 [8,'Distractorii inversează proporțiile și rolul FNA.'],['risc de malignitate de 5%','10% din cazuri']),

q('endocrinologie-adv-056',['Carcinoamele tiroidiene diferențiate:',
 ['carcinomul papilar reprezintă ~70% din cancerele tiroidiene','carcinomul folicular reprezintă ~20%','peste 75% din cazuri apar la femei','carcinomul folicular reprezintă ~70%','sunt frecvent asociate cu hipertiroidism'],'ABC',621,'Carcinomul tiroidian',
 'Fixarea epidemiologiei cancerelor tiroidiene.',
 ['Papilarul: 70%.','Folicularul: 20%.','Peste 75% apar la femei.','Folicularul: 20%.','Sunt extrem de rar asociate cu hipertiroidism.']],
 [8,'Distractorii permută frecvențele.'],['Papilar 70%','75%'],[622]),

q('endocrinologie-adv-018',['Tiroglobulina după tratamentul cancerului tiroidian diferențiat:',
 ['este folosită ca marker tumoral','este mai sensibilă când TSH este ridicat','poate fi stimulată cu TSH recombinant fără oprirea levotiroxinei','poate deveni neinterpretabilă în prezența anti-Tg','este mai sensibilă când TSH este supresat'],'ABCD',621,'Carcinoamele papilare și foliculare',
 'Aplicarea monitorizării prin tiroglobulină.',
 ['Tg este marker tumoral post-ablație.','Sensibilitatea este maximă la TSH ridicat.','rhTSH 900 µg în 2 doze stimulează Tg.','Anti-Tg pot face dozarea neinterpretabilă.','Sensibilitatea crește la TSH ridicat.']],
 [8,'Singurul distractor inversează condiția.'],['tiroglobulina','rhTSH'],[622]),

q('endocrinologie-adv-044',['Carcinomul medular tiroidian:',
 ['provine din celulele C (calcitonină)','are mutație RET la ~90% dintre pacienți','tiroidectomia profilactică se face de la 5 ani','răspunde bine la iodul radioactiv adjuvant','provine din epiteliul folicular tiroidian'],'AC',622,'Carcinomul medular',
 'Recunoașterea carcinomului medular.',
 ['Provine din celulele C.','Nu: aproximativ 25% au mutație RET.','Purtătorii MEN 2 fac tiroidectomie de la 5 ani.','Răspunde slab la tratament.','Provine din celulele C.']],
 [8,'Distractorii confundă originea și răspunsul.'],['RET','5 ani']),
];
