import {rewriter} from './rewrite-author';
import {RETIRED_ESOFAG} from './retired/esofag';

// Rewritten after the 2026-09-24 cue audit (Lawrence, cap. 12, p. 140–142, 151–164).
// Paraphrase duplicates and items built on the BRGE figures of p. 151 (BRGE is not in
// the syllabus list for this chapter) were retired without replacement.
const q=rewriter(RETIRED_ESOFAG,(p:number)=>p<=142?p-60:p-68);

export const ESOFAG_V2=[
q('esofag-adv-001',['Esofagul:',
 ['are o lungime de aproximativ 25 cm','începe la nivelul vertebrei C4','se termină la nivelul vertebrei T8','se abordează de obicei prin toracotomie stângă','se îngustează la nivelul arcului aortic'],'AE',140,'Anatomia generală',
 'Recunoașterea reperelor anatomice generale ale esofagului.',
 ['Esofagul are aproximativ 25 cm lungime.','Nu: începe la nivelul cartilajului cricoid (C6).','Se termină chiar sub diafragm, la T11.','Aorta coboară pe stânga, deci abordul este de cele mai multe ori prin toracotomie dreaptă.','Arcul aortic este una dintre cele trei zone de îngustare.']],
 [8,'Vertebra de terminare și partea toracotomiei sunt deplasate față de text.'],['cartilajului cricoid','arcului aortic']),

q('esofag-adv-007',['În cartografierea endoscopică și segmentară a esofagului:',
 ['esofagul cervical măsoară 18–22 cm, ca cel toracic','esofagul începe la aproximativ 15 cm de arcada dentară','atriul stâng este situat anterior de esofag','esofagul abdominal distal măsoară 3–6 cm','esofagul se termină la aproximativ 40 cm de arcada dentară'],'BCDE',140,'Anatomia generală — Segmente și repere endoscopice',
 'Aplicarea lungimilor segmentare și a reperelor endoscopice ale esofagului.',
 ['Esofagul cervical are 3–5 cm; 18–22 cm este esofagul toracic proximal și mijlociu.','Esofagul începe la aproximativ 15 cm de arcada dentară.','Traheea și atriul stâng sunt anterioare esofagului.','Esofagul abdominal distal are 3–6 cm.','Esofagul se termină la aproximativ 40 cm de arcada dentară.']],
 [8,'Lungimile segmentelor sunt permutate între ele.'],['15 cm de arcada','18-22 cm']),

q('esofag-adv-008',['Vascularizația arterială a esofagului provine din:',
 ['artera tiroidiană inferioară, pentru esofagul cervical','arterele esofagiene din aorta toracică, pentru esofagul toracic','arterele bronșice, pentru esofagul toracic','ramuri ale arterei gastrice stângi, pentru esofagul distal','artera gastroepiploică dreaptă, pentru esofagul distal'],'ABCD',140,'Vascularizația arterială',
 'Asocierea fiecărui segment esofagian cu sursa sa arterială.',
 ['Esofagul cervical este irigat de artera tiroidiană inferioară, din trunchiul tirocervical.','Esofagul toracic primește și arterele esofagiene din aorta toracică.','Esofagul toracic primește arterele bronșice și arterele esofagiene din aorta toracică.','Esofagul distal este vascularizat de ramuri ale arterei gastrice stângi.','Gastroepiploica dreaptă nu este citată ca sursă esofagiană.']],
 [8,'Distractorii sunt artere vecine ale acelorași regiuni.'],['tiroidiană inferioară','arterei gastrice stângi']),

q('esofag-adv-009',['Referitor la drenajul venos și limfatic al esofagului:',
 ['esofagul toracic drenează venos prin venele azygos și hemiazygos','esofagul distal drenează venos în sistemul port','esofagul cervical drenează limfatic în ganglionii celiaci','esofagul distal drenează limfatic în ganglionii celiaci','plexul venos esofagian inferior poate forma varice în ciroză'],'ABDE',140,'Drenajul venos și limfatic',
 'Maparea drenajului venos și limfatic pe segmentele esofagului.',
 ['Venele azygos și hemiazygos drenează esofagul toracic.','Vena coronariană gastrică și gastrica stângă se varsă în sistemul port.','Esofagul cervical drenează în ganglionii cervicali profunzi (jugulari).','Esofagul distal drenează în ganglionii celiaci, gastrici stângi și parahiatali.','În hipertensiunea portală, plexul inferior face legătura porto-azygos, cu varice.']],
 [8,'Stațiile limfatice sunt mutate între segmentele esofagului.'],['azygos','varicelor esofagiene']),

q('esofag-adv-062',['Esofagul distal drenează limfatic în ganglionii:',
 ['cervicali profunzi (jugulari)','paratraheali și hilari pulmonari','celiaci, gastrici stângi și parahiatali','axilari și supraclaviculari','mezenterici superiori și mezenterici inferiori'],'C',140,'Drenajul limfatic',
 'Identificarea stației limfatice a esofagului distal.',
 ['Ganglionii jugulari drenează esofagul cervical.','Paratrahealii și hilarii drenează esofagul toracic.','Esofagul distal drenează în ganglionii celiaci, gastrici stângi și parahiatali.','Aceste stații nu sunt citate pentru esofag.','Ganglionii mezenterici nu sunt stații esofagiene citate.']],
 [8,'Două distractori sunt stațiile reale ale celorlalte segmente esofagiene.'],['celiaci','parahiatali']),

q('esofag-adv-010',['Peretele esofagian:',
 ['are musculatură netedă pe toată lungimea','nu prezintă strat seros','are musculatură striată în treimea proximală','are o muscularis propria cu strat longitudinal intern','este căptușit de epiteliu cilindric simplu'],'BC',141,'Histologia esofagului',
 'Recunoașterea particularităților histologice ale peretelui esofagian.',
 ['Musculatura este striată în 1/3 proximală și netedă în 2/3 distale.','Spre deosebire de restul tubului digestiv, esofagul nu are seroasă.','Treimea proximală are fibre musculare striate.','Stratul circular este intern, iar cel longitudinal extern.','Epiteliul normal este scuamos stratificat nekeratinizant.']],
 [8,'Distractorii inversează ordinea straturilor musculare și tipul de epiteliu.'],['nu prezintă un strat seros','1/3 proximală']),

q('esofag-adv-031',['La ecoendoscopie, peretele esofagian apare format din:',
 ['trei zone: mucoasă, musculară și seroasă','patru zone, corespunzătoare straturilor histologice','cinci zone, cu mucoasa în două straturi','șase zone, cu musculară dublată de seroasă','cinci zone, cu adventicea complet absentă'],'C',141,'Histologia esofagului — Ecoendoscopia',
 'Corelarea celor cinci zone ecoendoscopice cu straturile histologice.',
 ['Esofagul nu are seroasă.','Histologic sunt patru straturi, dar EUS distinge cinci zone.','EUS: mucoasă superficială, mucoasă profundă, submucoasă, muscularis propria, adventice.','Nu există seroasă și nici șase zone.','Adventicea este a cincea zonă.']],
 [8,'Diferența dintre patru straturi histologice și cinci zone EUS este discriminatorul.'],['cinci zone','mucoasa profundă']),

q('esofag-adv-012',['Esofagul Barrett reprezintă:',
 ['metaplazia scuamoasă a mucoasei gastrice oxintice','displazia epiteliului scuamos al esofagului proximal','o ulcerație peptică profundă a joncțiunii eso-gastrice','metaplazia intestinală columnară a esofagului distal','hiperplazia stratului muscular al esofagului distal'],'D',141,'Histologia esofagului — Esofagul Barrett',
 'Definirea esofagului Barrett ca metaplazie columnară intestinală.',
 ['Mucoasa oxintică este cea normală a stomacului proximal.','Barrett privește esofagul distal, nu displazia proximală.','Ulcerația nu definește Barrett.','Refluxul transformă epiteliul scuamos distal în celule columnare intestinale metaplazice.','Barrett este o modificare epitelială, nu musculară.']],
 [8,'Cere direcția exactă a metaplaziei și sediul ei.'],['esofagul Barrett','columnare intestinale']),

q('esofag-adv-011',['În fiziologia esofagiană:',
 ['presiunea de repaus a SES este de 30–120 mm Hg','presiunea de repaus a SEI este de 30–120 mm Hg','deglutiția este inițiată voluntar de nucleul ambiguu','SEI se contractă în anticiparea bolusului alimentar','SEI rămâne relaxat după pasajul bolusului'],'AC',142,'Fiziologia esofagiană',
 'Aplicarea presiunilor de repaus ale sfincterelor și a secvenței deglutiției.',
 ['SES are 30–120 mm Hg în repaus.','SEI are 15–30 mm Hg în repaus.','Deglutiția este inițiată voluntar de nucleul ambiguu, din bulb.','Nu: SEI se relaxează în anticiparea bolusului.','După pasajul bolusului, SEI revine la presiunea de repaus ridicată.']],
 [8,'Intervalul de presiune al SES este atribuit SEI.'],['30-120 mm Hg','nucleul ambiguu']),

q('esofag-adv-030',['Undele peristaltice secundare esofagiene:',
 ['sunt declanșate în mod normal de deglutiție','sunt unde anormale, nepropulsive','reprezintă contracția tonică a SEI în repaus','sunt inițiate voluntar de nucleul ambiguu','apar la dilatarea sau iritația esofagului'],'E',142,'Fiziologia esofagiană — Undele peristaltice',
 'Diferențierea undelor secundare de cele primare și terțiare.',
 ['Deglutiția declanșează unda primară.','Undele anormale, nepropulsive, sunt terțiare.','Tonusul de repaus al SEI nu este o undă peristaltică.','Nucleul ambiguu inițiază deglutiția și unda primară.','Undele secundare apar la dilatare, iritație sau obstrucție și sunt un proces „de rezervă”.']],
 [8,'Distractorii descriu corect undele primare și terțiare.'],['peristaltice secundare','fibrilaţie']),

q('esofag-adv-063',['Sfincterul esofagian superior este situat la nivelul:',
 ['arcului aortic','mușchiului cricofaringian','hiatusului diafragmatic','bifurcației traheei principale','atriului stâng'],'B',140,'Anatomia generală — Sfincterele funcționale',
 'Localizarea sfincterului esofagian superior față de zonele de îngustare.',
 ['Arcul aortic este o zonă de îngustare, nu un sfincter.','SES este situat la nivelul mușchiului cricofaringian.','Diafragmul este zona de îngustare distală.','Bifurcația traheală nu este citată ca sfincter.','Atriul stâng este o relație anterioară a esofagului.']],
 [8,'Distractorii sunt celelalte repere anatomice ale esofagului, inclusiv zonele de îngustare.'],['sfincter esofagian superior','muşchiului cricofaringian']),

q('esofag-adv-025',['Lezarea nervului laringeu recurent în chirurgia esofagului cervical:',
 ['produce acalazie prin lezarea plexului mienteric','afectează funcția corzilor vocale','crește presiunea de repaus a SEI','perturbă mecanismul de deglutiție al esofagului superior','crește riscul de aspirație'],'BDE',140,'Inervația esofagului',
 'Recunoașterea consecințelor leziunii nervului laringeu recurent.',
 ['Acalazia rezultă din lezarea plexului mienteric intramural.','Leziunea perturbă activitatea corzilor vocale.','Recurentul nu reglează SEI.','Este afectat și mecanismul de deglutiție al esofagului superior.','Riscul de aspirație crește.']],
 [8,'Distractorii atribuie recurentului efecte ale plexului mienteric și ale SEI.'],['riscul de aspiraţie','nervii laringieni']),

q('esofag-adv-028',['Asemănarea dintre durerea esofagiană și angina pectorală se explică prin:',
 ['inervația motorie simpatică a esofagului','o cale senzitivă comună cu fibrele cardiace','irigarea comună din arterele coronare','vecinătatea esofagului cu aorta ascendentă','drenajul venos comun prin vena azygos'],'B',141,'Inervația esofagului — Durerea viscerală',
 'Explicarea mimetismului dintre durerea esofagiană și cea cardiacă.',
 ['Inervația motorie a esofagului este vagală.','Fibrele aferente esofagiene împart cu fibrele senzoriale cardiace o cale similară.','Esofagul nu este irigat de arterele coronare.','Aorta relevantă este cea descendentă toracică, iar vecinătatea nu explică durerea.','Drenajul venos nu explică percepția durerii.']],
 [8,'Distractorii sunt relații anatomice reale, dar fără legătură cu calea senzitivă.'],['durerea cardiacă','fibrele senzoriale cardiace'],[140]),

q('esofag-adv-060',['Plexul mienteric esofagian:',
 ['este situat între straturile circular și longitudinal ale muscularei','este situat în submucoasă','controlează activitatea peristaltică','este format din fibre somatice ale nervului frenic','prin lezare poate produce acalazie'],'ACE',140,'Inervația esofagului — Plexul mienteric',
 'Localizarea și rolul funcțional al plexului mienteric.',
 ['Plexul este intramural, între straturile circular și longitudinal ale muscularei propria.','Nu este situat în submucoasă.','Plexul mienteric controlează activitatea peristaltică.','Este format din fibre simpatice și parasimpatice.','Lezarea lui poate produce acalazie.']],
 [8,'Distractorii schimbă stratul și tipul de fibre ale plexului.'],['plex nervos intramural','acalazie']),

q('esofag-adv-050',['Achalazia:',
 ['se manifestă prin disfagie progresivă, întâi la lichide','se datorează degenerării plexului mienteric Auerbach','este adesea confundată inițial cu BRGE, din cauza regurgitării','poate fi vindecată prin miotomie Heller','asociază peristaltism esofagian păstrat'],'BC',159,'Tulburări ale motilității — Achalazia',
 'Recunoașterea mecanismului și a tabloului clinic al achalaziei.',
 ['Disfagia este progresivă întâi la solide, apoi la lichide.','Anomalia primară este degenerarea plexului mienteric (Auerbach).','Regurgitarea duce inițial adesea la diagnostic greșit de BRGE.','Boala nu poate fi vindecată; intervențiile sunt paliative.','Achalazia asociază absența peristaltismului esofagian.']],
 [8,'Distractorii inversează ordinea disfagiei și caracterul paliativ al tratamentului.'],['disfagie progresivă','eşecul relaxării'],[158]),

q('esofag-adv-018',['În diagnosticul achalaziei:',
 ['tranzitul baritat arată semnul „ciocului de pasăre”','manometria arată relaxarea completă a SEI la deglutiție','endoscopia confirmă diagnosticul prin biopsia SEI','manometria arată absența contracțiilor peristaltice normale','endoscopia este evitată din cauza riscului de perforație'],'AD',159,'Achalazia — Diagnostic',
 'Asocierea investigațiilor cu constatările din achalazie.',
 ['Tranzitul baritat arată clasic semnul ciocului de pasăre.','Manometria arată eșecul relaxării SEI la deglutiție.','Nu: endoscopia exclude alte cauze de obstrucție (pseudoachalazia din carcinom).','Manometria arată absența contracțiilor peristaltice normale.','Precauția endoscopică pentru perforație privește diverticulul Zenker.']],
 [8,'Distractorul endoscopic este preluat de la diverticulul Zenker.'],['ciocului de pasăre','pseudoachalazie']),

q('esofag-adv-051',['În tratamentul achalaziei:',
 ['toxina botulinică are succes durabil, superior miotomiei','nitrații și blocanții de calciu oferă rar ameliorare durabilă','miotomia este preferată la pacienții tineri','dilatarea pneumatică este cea mai eficientă intervenție nechirurgicală','dilatațiile repetate cresc cumulativ riscul de perforație'],'BCDE',159,'Achalazia — Tratament',
 'Ierarhizarea opțiunilor terapeutice nechirurgicale în achalazie.',
 ['Injectarea de toxină botulinică a avut succes limitat.','Medicamentele nu oferă aproape niciodată ameliorare de durată.','Din cauza riscului cumulativ de perforație, la tineri se preferă miotomia.','Dilatarea pneumatică cu balon este cea mai eficientă intervenție nechirurgicală.','Dilatațiile repetate cresc riscul cumulativ de perforație.']],
 [8,'Distractorii inversează preferința pentru miotomie la tineri și rezultatul toxinei botulinice.'],['Dilatarea endoscopică pneumatică','riscului cumulativ de perforaţie'],[160]),

q('esofag-adv-005',['Miotomia Heller laparoscopică pentru achalazie:',
 ['se extinde pe stomac cel puțin 2–3 cm','secționează și mucoasa esofagiană','se asociază cu fundoplicatură, pentru a preveni refluxul','se oprește la joncțiunea eso-gastrică','are o lungime de aproximativ 5 cm'],'ACE',160,'Achalazia — Miotomia Heller',
 'Aplicarea parametrilor tehnici ai miotomiei Heller.',
 ['Miotomia se extinde spre stomac cel puțin 2–3 cm.','Cheia este prezervarea mucoasei.','Fundoplicatura concomitentă previne refluxul după ce SEI devine incompetent.','Extinderea gastrică previne miotomia incompletă.','Figura 12-22: miotomie de 5 cm, cu 2–3 cm la nivelul stomacului.']],
 [8,'Distractorii contrazic prezervarea mucoasei și extinderea gastrică.'],['2-3 cm','miotomie de 5 cm'],[161]),

q('esofag-adv-082',['Tulburările esofagiene spastice (spasmul esofagian distal, esofagul jackhammer):',
 ['se prezintă de obicei cu disfagie și durere toracică noncardiacă','nu au tratament cunoscut, fiind încercate prokineticele','se tratează tipic cu nitrați și blocanți ai canalelor de calciu','pot beneficia de miotomie lungă','se tratează de elecție prin POEM cu fundoplicatură'],'ACD',160,'Tulburări ale peristaltismului',
 'Separarea tulburărilor spastice de motilitatea ineficientă și de achalazie.',
 ['Tabloul tipic este disfagia cu dureri toracice noncardiace.','Absența tratamentului cunoscut caracterizează MEI.','Managementul este tipic limitat la nitrați și blocanți de calciu.','S-a descris miotomia lungă, cu ameliorare.','POEM este descris pentru achalazie și nu asociază fundoplicatură.']],
 [8,'Distractorii preiau caracteristici reale ale MEI și ale POEM.'],['esofagul jackhammer','miotomia lungă']),

q('esofag-adv-053',['Motilitatea esofagiană ineficientă (MEI):',
 ['se tratează standard prin miotomie Heller','este adesea asimptomatică, dar poate da disfagie','se asociază semnului „ciocului de pasăre”','nu are un tratament specific cunoscut','se prezintă tipic cu durere toracică noncardiacă'],'BD',160,'Tulburări ale peristaltismului — MEI',
 'Recunoașterea MEI ca tulburare adesea silențioasă, fără tratament cunoscut.',
 ['Heller este tratamentul achalaziei.','MEI este adesea asimptomatică, dar se poate manifesta ca disfagie.','Ciocul de pasăre este semnul achalaziei.','Nu există un tratament cunoscut; s-au încercat prokinetice.','Durerea toracică noncardiacă caracterizează tulburările spastice.']],
 [8,'Distractorii aparțin achalaziei și tulburărilor spastice din același paragraf.'],['motilitatea esofagiană ineficientă','prokinetice']),

q('esofag-adv-054',['Diverticulii esofagieni de tracțiune:',
 ['sunt localizați de obicei pe esofagul mediotoracic','sunt diverticuli falși, fără strat muscular complet','se dezvoltă adesea de la o adenopatie inflamatorie locală','sunt mai rari decât diverticulii de pulsiune','implică toate straturile peretelui esofagian'],'ACDE',161,'Diverticulii esofagieni',
 'Contrastarea diverticulilor de tracțiune cu cei de pulsiune.',
 ['Diverticulii de tracțiune sunt de obicei mediotoracici.','Diverticulii falși sunt cei de pulsiune.','Ei se dezvoltă adesea de la o adenopatie inflamatorie care tracționează peretele.','Diverticulii de pulsiune sunt mai frecvenți.','Sunt diverticuli adevărați: implică toate straturile peretelui.']],
 [8,'Distractorii atribuie trăsăturile diverticulilor de pulsiune.'],['falşi diverticuli','adenopatie inflamatorie']),

q('esofag-adv-055',['Diverticulul Zenker:',
 ['necesită endoscopie digestivă superioară pentru diagnostic','este un diverticul de pulsiune al esofagului cervical','apare posterior, imediat deasupra mușchiului cricofaringian','se confirmă prin tranzit baritat','se tratează prin miotomie cricofaringiană și diverticulectomie'],'BCDE',161,'Diverticulii esofagieni — Diverticulul Zenker',
 'Recunoașterea mecanismului, sediului, diagnosticului și tratamentului diverticulului Zenker.',
 ['Endoscopia nu este necesară pentru diagnostic și trebuie făcută cu precauție.','Zenker este un diverticul de pulsiune al esofagului cervical.','Apare posterior, la tranziția hipofaringe–esofag, deasupra cricofaringianului.','Diagnosticul se confirmă prin tranzit baritat.','Tratamentul este miotomia cricofaringiană cu diverticulectomie sau diverticulopexie.']],
 [8,'Singurul distractor inversează rolul endoscopiei, cu risc real de perforație.'],['relaxarea necoordonată','diverticulectomie']),

q('esofag-adv-056',['Diverticulul epifrenic simptomatic se abordează chirurgical de obicei prin:',
 ['toracotomie dreaptă','toracotomie stângă','cervicotomie stângă','laparotomie mediană','sternotomie mediană'],'B',161,'Diverticulii esofagieni — Diverticulul epifrenic',
 'Alegerea abordului chirurgical al diverticulului epifrenic.',
 ['Toracotomia dreaptă este abordul uzual al esofagului toracic, nu al epifrenicului.','Abordul se face de obicei prin toracotomie stângă, cu rezecție și esomiotomie distală.','Cervicotomia stângă este abordul diverticulului Zenker.','Laparotomia nu este abordul citat.','Sternotomia nu este abordul citat.']],
 [8,'Toracotomia dreaptă este abordul general al esofagului; epifrenicul este excepția.'],['toracotomie stângă','esomiotomie distală']),

q('esofag-adv-057',['Diverticulii medioesofagieni:',
 ['se asociază frecvent cu adenopatia paratraheală din tuberculoză','sunt de obicei diverticuli falși','sunt de obicei simptomatici și necesită rezecție','pot fistuliza în trahee sau în vasele adiacente','sunt produși de relaxarea necoordonată a cricofaringianului'],'AD',161,'Diverticulii esofagieni — Diverticulul medioesofagian',
 'Recunoașterea etiologiei și a complicațiilor diverticulului medioesofagian.',
 ['Se asociază cu inflamația ganglionului paratraheal din tuberculoză, histoplasmoză sau cancer pulmonar.','Sunt de obicei diverticuli adevărați.','De obicei sunt asimptomatici și nu necesită tratament.','Pot fistuliza în trahee sau în vase, cu simptome respiratorii și hemoragie.','Relaxarea necoordonată a cricofaringianului produce diverticulul Zenker.']],
 [8,'Distractorii preiau trăsături ale diverticulilor de pulsiune și ale Zenker.'],['histoplasmoză','lambou de ţesut']),

q('esofag-adv-020',['Leiomiomul esofagian:',
 ['este cea mai frecventă tumoră benignă a esofagului','se diagnostichează de elecție prin aspirație cu ac fin','este localizat în stratul muscular','se tratează, când este simptomatic, prin esofagectomie','are un risc crescut de recidivă după rezecție'],'AC',162,'Leziuni esofagiene benigne — Leiomiomul',
 'Recunoașterea sediului, diagnosticului și tratamentului leiomiomului.',
 ['Leiomiomul este cea mai frecventă tumoră benignă.','Aspirația cu ac fin se evită: nu diferențiază leiomiomul de leiomiosarcom.','Este localizat în stratul muscular.','Nu: leziunile simptomatice se enucleează, cu reaproximarea muscularei.','Prognosticul este excelent, aproape fără recidivă.']],
 [8,'Distractorii inversează rolul biopsiei și prognosticul.'],['leiomomul','enucleerea leziunii']),

q('esofag-adv-058',['Referitor la leziunile esofagiene benigne, altele decât leiomiomul:',
 ['chistul esofagian este a doua masă benignă ca frecvență','chistul este localizat în mucoasă','tumora cu celule granulare este o leziune mucoasă sau submucoasă','manipularea invazivă a chistului poate produce infecție','polipul fibrovascular apare de obicei pe esofagul cervical'],'ACD',162,'Leziuni esofagiene benigne',
 'Clasificarea maselor benigne după stratul de origine și riscurile manipulării.',
 ['Chistul esofagian este a doua cea mai frecventă masă benignă.','Chistul este localizat în adventice, cu implicare parțială a muscularei.','Tumora cu celule granulare și polipul fibrovascular sunt cele mai frecvente leziuni mucoase/submucoase.','Manipularea invazivă a chistului poate duce la infecție iatrogenă.','Aceste leziuni apar mai ales pe esofagul mijlociu și distal.']],
 [8,'Distractorii mută stratul chistului și sediul polipului.'],['chistul esofagian','polipul fibrovascular']),

q('esofag-adv-021',['În ingestia de corpi străini esofagieni:',
 ['la adulți predomină impactarea alimentară','impactarea apare cel mai des la nivelul arcului aortic','tranzitul baritat este contraindicat','tratamentul de elecție este extracția cu esofagoscop sub anestezie generală','impactarea se produce frecvent pe o strictură peptică distală'],'ACDE',162,'Ingestia de corpi străini',
 'Aplicarea conduitei diagnostice și terapeutice în ingestia de corpi străini.',
 ['La adulți predomină impactarea alimentelor (carne, oase).','Majoritatea impactărilor apar la cricofaringian sau pe o strictură peptică distală.','Tranzitul baritat este contraindicat: risc de aspirație, fără beneficiu terapeutic.','Cel mai bun tratament este extracția blândă cu esofagoscop sub anestezie generală.','Strictura peptică din esofagul distal este un sediu frecvent de impactare.']],
 [8,'Arcul aortic este o zonă reală de îngustare, dar nu sediul frecvent citat.'],['esofagoscop','risc ridicat de aspiraţie']),

q('esofag-adv-022',['În tratamentul ingestiei de substanțe caustice:',
 ['inducerea vărsăturilor nu este recomandată','neutralizarea substanței caustice este recomandată','se montează precoce o sondă nazogastrică','steroizii previn eficient formarea stenozei','menținerea căilor aeriene libere este prima prioritate'],'AE',164,'Ingestia substanțelor caustice — Tratament',
 'Recunoașterea măsurilor inițiale și a celor evitate în ingestia caustică.',
 ['Vărsăturile reexpun esofagul la substanța caustică.','Neutralizarea nu este recomandată: este ineficientă și potențial dăunătoare.','Nu: algoritmul precizează evitarea SNG.','Steroizii nu s-au dovedit eficienți în prevenirea stenozei.','Căile aeriene sunt prima prioritate.']],
 [8,'Distractorii sunt măsuri intuitive, contrazise explicit de text.'],['Inducerea vărsăturilor','nu SNG']),

q('esofag-adv-023',['Conform algoritmului pentru ingestia caustică, în funcție de gradul endoscopic:',
 ['gradul I impune NPO timp de o săptămână','gradul II impune NPO timp de o săptămână','gradul III impune NPO, perfuzii și antibiotic','tranzitul baritat se efectuează la 4–6 zile','gradul I impune antibioterapie intravenoasă'],'BC',164,'Ingestia substanțelor caustice — Algoritm (Figura 12-25)',
 'Aplicarea conduitei diferențiate pe grade a leziunii caustice.',
 ['La gradul I se începe dieta progresiv.','Gradul II: NPO o săptămână.','Gradul III: NPO, perfuzii și antibiotic, cu monitorizarea perforației.','Tranzitul baritat se face la 4–6 săptămâni.','La gradul I nu sunt necesare steroizi sau antibiotice.']],
 [8,'Conduitele gradelor vecine și unitatea de timp a controlului baritat sunt schimbate.'],['NPO 1 săpt','Tranzit baritat la 4']),

q('esofag-adv-024',['Complicațiile și tratamentul tardiv după ingestia caustică:',
 ['stenozele sunt complicația pe termen lung','crește riscul de carcinom esofagian scuamos','rezecția este dificilă din cauza fibrozei periesofagiene','reconstrucția folosește frecvent colonul, stomacul fiind deteriorat','reconstrucția se face de elecție cu stomacul'],'ABCD',164,'Ingestia substanțelor caustice — Complicații tardive',
 'Recunoașterea complicațiilor tardive și a particularităților reconstrucției.',
 ['Complicația pe termen lung este formarea stenozelor.','Crește riscul de cancer esofagian cu celule scuamoase.','Rezecția este dificilă din cauza fibrozei periesofagiene extinse.','Rezecția necesită frecvent interpoziție de colon, stomacul fiind adesea deteriorat.','Stomacul este frecvent deteriorat și nu este grefonul de elecție aici.']],
 [8,'Distractorii aplică regula generală (stomacul ca grefon) unei situații care o contrazice.'],['interpoziţia de colon','celule scuamoase'],[163]),

q('esofag-adv-059',['În ingestia de substanțe caustice, la evaluarea inițială:',
 ['ingestia de alcaline produce leziuni superficiale','ingestia de acizi produce leziuni mai profunde decât alcalinele','endoscopia flexibilă se face în primele 24 de ore','endoscopia se amână peste 72 de ore, pentru a evita perforația','medicul trebuie pregătit pentru intubație cu fibroscop'],'CE',163,'Ingestia substanțelor caustice — Evaluare',
 'Diferențierea leziunilor alcaline de cele acide și a momentului endoscopiei.',
 ['Nu: alcalinele produc vătămare în toată grosimea peretelui.','Acizii produc adesea leziuni mai superficiale.','Endoscopia flexibilă se face precoce, în termen de 24 de ore.','Endoscopia precoce reduce la minimum riscul de perforație.','Edemul căilor aeriene se poate dezvolta rapid, impunând pregătirea intubației cu fibroscop.']],
 [8,'Distractorii inversează severitatea acid/alcalin și momentul endoscopiei.'],['produse alcaline','în termen de 24 de ore']),

q('esofag-adv-072',['Perforația esofagului cervical:',
 ['este cauzată cel mai des de instrumentarea endoscopică','se exclude printr-un tranzit baritat negativ','se poate extinde prin spațiul retrovisceral în mediastin','se tratează prin incizie cervicală pe partea leziunii','necesită de regulă sutura primară, fără drenaj cervical'],'ACD',156,'Perforația esofagului cervical',
 'Recunoașterea cauzei, a căii de extensie și a tratamentului perforației cervicale.',
 ['Majoritatea sunt cauzate de instrumentarea endoscopică, mai ales la cricofaringian.','Tranzitul baritat poate fi negativ în până la 20% din cazuri.','Spațiul retrovisceral conduce infecția spre mediastinul posterior.','Abordul este o incizie cervicală pe partea leziunii, cu drenaj și debridare.','Sutura primară se poate încerca, dar nu este necesară; majoritatea se vindecă prin drenaj.']],
 [8,'Distractorii supraestimează valoarea bariului și necesitatea suturii.'],['spaţiul retrovisceral','sfincterului cricofaringian']),

q('esofag-adv-073',['La perforația esofagului cervical asociată cu o leziune traheală se utilizează:',
 ['un stent esofagian expandabil','un lambou muscular pediculat','o esofagectomie transhiatală','o traheostomie definitivă','un tub T plasat la nivelul perforației'],'B',156,'Perforația esofagului cervical — Leziunea traheală asociată',
 'Prevenirea fistulei eso-traheale în perforația cervicală.',
 ['Stenturile sunt citate pentru paliație sau cancer terminal.','Se folosește un lambou muscular pediculat pentru a preveni fistula eso-traheală.','Esofagectomia nu este gestul citat.','Traheostomia nu este gestul citat.','Tubul T este o alternativă în perforația toracică pe cancer terminal.']],
 [8,'Distractorii sunt soluții reale din alte situații de perforație.'],['lambou muscular','fistulelor eso-traheale']),

q('esofag-adv-044',['Perforația esofagului toracic:',
 ['apare cel mai frecvent după dilatarea unei obstrucții distale','în sindromul Boerhaave are un prognostic mai bun decât cea iatrogenă','se prezintă frecvent cu durere toracică și revărsat pleural','trebuie diferențiată de leziunea Mallory-Weiss, care nu este transmurală','se investighează inițial prin radiografie toracică standard'],'ACDE',157,'Perforația esofagului toracic',
 'Recunoașterea cauzei, tabloului și investigației inițiale în perforația toracică.',
 ['Cel mai frecvent urmează dilatării unei obstrucții distale, precum strictura peptică.','Boerhaave are un tablou mai dramatic și un prognostic mai prost.','Tabloul include durere toracică, detresă respiratorie și revărsat pleural.','Leziunea Mallory-Weiss nu este transmurală și produce mai ales hemoragie.','Investigarea începe cu radiografia toracică standard.']],
 [8,'Singurul distractor inversează prognosticul Boerhaave.'],['sindromul Boerhaave','revărsat pleural']),

q('esofag-adv-074',['Managementul non-operator al perforației esofagiene:',
 ['reprezintă regula în perforațiile toracice','cere o perforație limitată cervical sau mediastinal','se aplică și pacientului instabil','include antibiotice și drenaj nazo-gastric','contraindică nutriția parenterală'],'BD',157,'Perforația esofagului toracic — Tratament conservator',
 'Aplicarea criteriilor tratamentului non-operator.',
 ['Managementul non-operator trebuie să fie excepția, nu regula.','Criteriu: perforație limitată cervical sau mediastinal.','Nu: criteriul este pacientul stabil clinic.','Include antibiotice și drenaj nazo-gastric.','Include alimentație enterală distal de leziune sau nutriție parenterală.']],
 [8,'Distractorii contrazic statutul de excepție și componentele tratamentului.'],['excepţia şi nu regula','drenaj nazo-gastric']),

q('esofag-adv-045',['Tratamentul chirurgical al perforației esofagului toracic include:',
 ['debridarea minuțioasă a țesuturilor infectate','esofagorafie într-un singur strat, fără consolidare','consolidarea suturii, adesea cu lambou intercostal pediculat','amânarea tratamentului obstrucției distale asociate','drenaj cu tub T în cancerul esofagian terminal'],'ACE',157,'Perforația esofagului toracic — Tratament chirurgical',
 'Recunoașterea principiilor reparației chirurgicale a perforației toracice.',
 ['Debridarea minuțioasă este primul principiu.','Esofagorafia se face în două straturi (mucoasă și musculară).','Sutura se consolidează adesea cu lambou intercostal pediculat.','Obstrucția reziduală tensionează sutura și trebuie tratată concomitent.','În cancerul terminal, tubul T sau stentul sunt alternative.']],
 [8,'Distractorii contrazic sutura în două straturi și tratarea obstacolului.'],['esofagorafia în două straturi','lambou intercostal']),

q('esofag-adv-076',['Excluderea esofagiană, la pacientul tarat cu perforație, presupune:',
 ['izolarea segmentului lezat prin capse proximal și distal','esofagostomie cervicală (fistulă salivară)','gastrostomie de drenaj, alimentația fiind orală','anastomoză esofago-gastrică imediată','jejunostomie de alimentație și drenaj larg'],'ABE',157,'Perforația esofagului toracic — Excluderea esofagiană',
 'Recunoașterea componentelor excluderii esofagiene.',
 ['Segmentul lezat se izolează prin suturi sau capse proximal și distal.','Drenajul cervical se face printr-o fistulă salivară.','Alimentația se face prin jejunostomie.','Reconstrucția se face ulterior, după recuperare.','Jejunostomia de alimentație și drenajul larg fac parte din procedură.']],
 [8,'Distractorii înlocuiesc jejunostomia și amânarea reconstrucției.'],['fistulă salivară','jejunostomie de alimentaţie']),

q('esofag-adv-004',['În hernia hiatală de tip II (paraesofagiană adevărată):',
 ['joncțiunea rămâne în abdomen, iar stomacul prolabează','joncțiunea gastroesofagiană alunecă în torace','joncțiunea și stomacul migrează împreună în torace','în torace migrează colonul sau splina','nu există prolaps gastric, doar lărgirea hiatusului'],'A',157,'Herniile hiatale — Clasificare',
 'Recunoașterea criteriului anatomic al herniei hiatale de tip II.',
 ['Tipul II: prolaps gastric prin ligamentul frenoesofagian slăbit, cu joncțiunea intraabdominală.','Alunecarea joncțiunii definește tipul I.','Migrarea joncțiunii și a stomacului definește tipul III.','Herniera altor organe definește tipul IV.','Toate tipurile II–IV implică prolaps de stomac sau alte organe.']],
 [8,'Fiecare distractor descrie exact un alt tip de hernie hiatală.'],['paraesofagiană adevărată','ligament frenoeso']),

q('esofag-adv-046',['Referitor la clasificarea herniilor hiatale:',
 ['tipul II se asociază cu migrarea joncțiunii în torace','tipul I (de alunecare) este cel mai frecvent','tipul I se asociază frecvent cu BRGE','tipul III este cea mai frecventă hernie paraesofagiană, în afară de tipul I','tipul IV include herniere de colon sau splină'],'BCDE',157,'Herniile hiatale — Clasificare',
 'Maparea celor patru tipuri de hernie hiatală.',
 ['În tipul II joncțiunea rămâne în abdomen.','Hernia de alunecare (tip I) este cel mai comun tip.','Tipul I este frecvent asociat cu BRGE.','Figura 12-18: tipul III este cea mai frecventă hernie paraesofagiană (în afară de tipul I).','Tipul IV implică herniere de colon sau splină.']],
 [8,'Singurul distractor transferă criteriul tipului III pe tipul II.'],['hernia hiatală de alunecare','colonul sau splina'],[158]),

q('esofag-adv-047',['Standardul de aur pentru identificarea unei hernii hiatale este:',
 ['radiografia toracică cu nivel hidroaeric','tomografia computerizată toraco-abdominală','endoscopia digestivă superioară cu biopsie','manometria esofagiană de înaltă rezoluție','tranzitul digestiv superior cu contrast'],'E',158,'Herniile hiatale — Diagnostic',
 'Identificarea investigației de referință în hernia hiatală.',
 ['Radiografia poate sugera hernia printr-un nivel hidroaeric, dar nu este standardul.','CT oferă detalii anatomice, dar nu este de obicei necesară.','Endoscopia nu este citată ca standard de aur.','Manometria nu este citată pentru diagnosticul herniei.','Tranzitul digestiv superior cu contrast este standardul de aur.']],
 [8,'Radiografia și CT sunt investigații reale din același paragraf.'],['standardul de aur','nivel hidroaeric']),

q('esofag-adv-048',['Referitor la conduita în herniile hiatale:',
 ['tipul I nu prezintă risc de încarcerare','tipul I se operează de obicei pentru simptome de reflux','tipul II asimptomatic are indicație operatorie de urgență','în tipul II, încarcerarea acută cu necroză este considerată rară','tipul I asimptomatic impune reparație electivă'],'ABD',158,'Herniile hiatale — Indicații chirurgicale',
 'Diferențierea indicației chirurgicale în tipurile I și II.',
 ['Herniile de tip I pot fi asimptomatice, fără risc de încarcerare.','Indicația la tipul I este dată de obicei de simptomele de reflux.','Conduita în tipul II asimptomatic este controversată; observarea este o alternativă rezonabilă.','Încarcerarea acută cu necroză este considerată rară.','Tipul I asimptomatic nu are indicație profilactică.']],
 [8,'Distractorii transformă controversa tipului II într-o indicație fermă.'],['niciun risc pentru încarcerare','observarea atentă']),

q('esofag-adv-049',['Cura chirurgicală a herniei hiatale simptomatice include:',
 ['reducerea completă a sacului herniar','închiderea defectului diafragmatic sub tensiune','obținerea a 2–3 cm de esofag intraabdominal','efectuarea unei fundoplicaturi','la vârstnicul tarat, gastropexie după reducerea stomacului'],'ACDE',158,'Herniile hiatale — Etapele operatorii',
 'Recunoașterea etapelor cheie ale curei herniei hiatale.',
 ['Reducerea completă a sacului este o etapă cheie.','Defectul se închide fără tensiune, cu sau fără plasă resorbabilă.','Se mobilizează esofagul pentru 2–3 cm intraabdominal.','Fundoplicatura este o etapă cheie.','La vârstnicul tarat, reducerea cu gastropexie este adesea suficientă.']],
 [8,'Singurul distractor inversează principiul închiderii fără tensiune.'],['2-3 cm','gastropexie']),

q('esofag-adv-006',['Când stomacul este folosit ca substitut esofagian:',
 ['artera gastrică stângă este păstrată ca pedicul principal','vascularizația depinde de artera gastrică dreaptă și de gastroduodenală','se practică deseori piloromiotomie, vagul fiind secționat','fornixul este expus riscului de ischemie','refluxul este mai frecvent după anastomoza intratoracică'],'BCDE',153,'Substitute esofagiene — Stomacul',
 'Recunoașterea vascularizației și a dezavantajelor grefonului gastric.',
 ['Artera gastrică stângă și gastricele scurte sunt secționate.','Rămân artera gastrică dreaptă și artera gastroduodenală.','Vagul este secționat, deci se practică deseori piloromiotomia.','Fluxul fornixului depinde de colaterale, cu risc de ischemie.','Refluxul este mai frecvent după anastomoza intratoracică decât după cea cervicală.']],
 [8,'Singurul distractor inversează pediculul arterial.'],['gastroduodenală','piloromiotomie']),

q('esofag-adv-041',['Colonul stâng folosit ca substitut esofagian:',
 ['este pediculat pe artera colică stângă, ramură din AMS','este al doilea grefon ca frecvență, după stomac','se montează în manieră izoperistaltică','se plasează preferențial pe cale retrosternală','necesită colonoscopie și angiografie preoperatorie'],'BCE',153,'Substitute esofagiene — Colonul',
 'Recunoașterea pediculului, montajului și evaluării preoperatorii a colonului.',
 ['Artera colică stângă este ramură a arterei mezenterice inferioare.','Colonul stâng este următorul cel mai frecvent după stomac.','Se folosește izoperistaltic.','Calea preferată este mediastinul posterior; retrosternalul crește riscul de cudare.','Colonoscopia și angiografia colonică sunt necesare preoperator.']],
 [8,'Distractorii schimbă originea pediculului și calea de interpunere.'],['izoperistaltic','angiografie colonică']),

q('esofag-adv-068',['Comparativ cu stomacul, colonul ca substitut esofagian:',
 ['are o vascularizație mai bogată și mai ușor de mobilizat','este mai rezistent la refluxul acid','necesită mai puține anastomoze gastrointestinale','necesită două anastomoze suplimentare','ascensionează mai ușor până la esofagul cervical'],'BDE',153,'Substitute esofagiene — Stomac versus colon',
 'Compararea avantajelor și dezavantajelor stomacului și colonului ca grefon.',
 ['Vascularizația bogată și mobilizarea facilă sunt avantaje ale stomacului.','Colonul este mai rezistent la refluxul acid.','Necesarul redus de anastomoze este un avantaj al stomacului.','Colonul necesită două anastomoze suplimentare.','Colonul ascensionează facil până la esofagul cervical.']],
 [8,'Distractorii sunt avantajele reale ale stomacului.'],['refluxul acid','două anastomoze suplimentare']),

q('esofag-adv-042',['Jejunul ca substitut esofagian:',
 ['este grefonul cel mai des utilizat','se pediculează ușor datorită anatomiei vasculare favorabile','se montează retrosternal, pe artera colică stângă','se folosește ocazional ca grefă liberă cervicală','este indicat de elecție după esofagectomia transhiatală'],'D',153,'Substitute esofagiene — Jejunul',
 'Recunoașterea indicației limitate a jejunului ca grefă liberă.',
 ['Stomacul este grefonul cel mai des utilizat.','Grefa jejunală pediculată este dificilă, din cauza anatomiei vasculare nefavorabile.','Artera colică stângă și calea retrosternală țin de colon.','Jejunul se folosește ocazional ca grefă liberă, cu anastomoză microvasculară cervicală.','Transhiatalul folosește de regulă fornixul gastric pentru anastomoza cervicală.']],
 [8,'Distractorii transferă trăsături ale stomacului și colonului.'],['grefă liberă','anastomoza microvasculară']),

q('esofag-adv-069',['Referitor la esofagectomia prin toracotomie:',
 ['abordul Ivor Lewis combină toracotomia dreaptă cu laparotomia','în abordul Ivor Lewis anastomoza este cervicală','procedura McKeown adaugă un timp cervical','McKeown oferă margini proximale mai înguste','fistula cervicală este mai gravă decât cea intratoracică'],'AC',153,'Tehnici chirurgicale — Toracotomia',
 'Compararea abordurilor Ivor Lewis și McKeown.',
 ['Ivor Lewis este toracotomia dreaptă combinată cu laparotomia.','În Ivor Lewis, anastomoza este în hemitoracele drept.','McKeown adaugă incizia cervicală și anastomoza cervicală.','Nu: rezecția proximală mai extinsă oferă margini mai largi.','Consecințele fistulei cervicale sunt mai puțin severe decât ale celei intratoracice.']],
 [8,'Distractorii inversează sediul anastomozei și gravitatea fistulei.'],['triplu abord','margini chirurgicale']),

q('esofag-adv-066',['Pentru o tumoră esofagiană distală extinsă în stomac, cu boală avansată local, unii autori propun:',
 ['incizie toraco-abdominală stângă','esofagectomie transhiatală','abord McKeown cu anastomoză cervicală','toracotomie dreaptă izolată','stent metalic expandabil'],'A',153,'Tehnici chirurgicale — Incizia toraco-abdominală stângă',
 'Alegerea abordului pentru tumora distală extinsă în stomac.',
 ['Incizia toraco-abdominală stângă permite o rezecție extinsă en-block.','Transhiatalul pare ideal pentru tumorile limitate la esofagul distal.','McKeown este descris pentru tumorile proximale sau mediotoracice.','Toracotomia dreaptă se combină cu laparotomia în Ivor Lewis.','Stentul este o soluție paliativă.']],
 [8,'Fiecare distractor este un abord real, cu altă indicație.'],['toraco-abdominală','en-block']),

q('esofag-adv-015',['Esofagectomia transhiatală:',
 ['folosește o incizie abdominală și una cervicală','evită toracotomia și anastomoza intratoracică','oferă acces facil în caz de hemoragie necontrolată','pare ideală pentru tumorile limitate la esofagul distal','permite rezecția extinsă a tumorilor mari mediotoracice'],'ABD',154,'Tehnici chirurgicale — Abordul transhiatal',
 'Cântărirea avantajelor și dezavantajelor abordului transhiatal.',
 ['Operația constă într-o incizie abdominală și una cervicală.','Evită toracotomia dureroasă și anastomoza intratoracică.','Accesul este limitat în cazul unei hemoragii necontrolate.','Pare ideal pentru tumorile limitate la esofagul distal, ca în degenerarea Barrett.','Rezecția tumorilor mari mediotoracice este limitată.']],
 [8,'Distractorii sunt exact dezavantajele citate ale abordului.'],['una cervicală','acces limitat'],[153,155]),

q('esofag-adv-032',['Esofagectomia laparoscopică (minim invazivă):',
 ['are o supraviețuire pe termen lung similară tehnicilor clasice','are o morbiditate chirurgicală crescută','are o curbă de învățare scurtă','s-a dovedit superioară oncologic abordului transhiatal','se efectuează cu succes doar în anumite centre'],'AE',155,'Tehnici chirurgicale — Abordul laparoscopic',
 'Recunoașterea rezultatelor și a limitelor esofagectomiei laparoscopice.',
 ['Rezultatele de supraviețuire sunt similare tehnicilor clasice.','Nu: morbiditatea este redusă datorită inciziilor mai puțin invazive.','Curba de învățare este lungă.','Nu s-a demonstrat superioritatea oncologică a vreunei tehnici.','În prezent, doar anumite centre efectuează esofagectomii laparoscopice de succes.']],
 [8,'Distractorii exagerează beneficiul și inversează curba de învățare.'],['Curba de învăţare','morbiditate chirurgicală redusă']),

q('esofag-adv-002',['Adenocarcinomul esofagian:',
 ['a depășit carcinomul scuamos ca frecvență în America de Nord și Europa','este localizat predominant în treimea medie și proximală','se asociază cu esofagul Barrett din BRGE','este mai frecvent la afro-americani decât la populația albă','și-a crescut incidența de 4 ori în ultimele două decenii'],'ACE',151,'Carcinomul esofagian — Epidemiologie',
 'Separarea epidemiologiei adenocarcinomului de cea a carcinomului scuamos.',
 ['Adenocarcinomul a depășit CSC în America de Nord și Europa.','Treimea medie și proximală este sediul CSC; adenocarcinomul implică esofagul distal.','Este asociat cu esofagul Barrett din BRGE.','Prevalența este mai mare la populația albă.','Incidența în Occident a crescut de 4 ori în ultimele două decenii.']],
 [8,'Distractorii sunt trăsăturile epidemiologice ale carcinomului scuamos.'],['esofagul Barrett','crescut de 4 ori']),

q('esofag-adv-027',['Carcinomul scuamos esofagian:',
 ['este localizat în principal în esofagul distal','are o incidență mai mare la bărbați, cu un raport de aproape 4:1','se asociază puternic cu consumul de alcool și tutun','este mai frecvent la populația albă decât la afro-americani','se asociază cu tiloza și cu sindromul Plummer-Vinson'],'BCE',151,'Carcinomul esofagian — Carcinomul scuamo-celular',
 'Recunoașterea terenului și a factorilor de risc ai carcinomului scuamos.',
 ['CSC este localizat în principal în treimea medie și proximală.','Incidența este mai mare la bărbați (aproape 4:1) și la afro-americani.','Asocierea cu alcoolul și tutunul este puternică.','Prevalența la populația albă caracterizează adenocarcinomul.','Tiloza și sindromul Plummer-Vinson sunt factori de risc citați.']],
 [8,'Distractorii sunt trăsăturile adenocarcinomului.'],['Plummer-Vinson','alcool şi tutun']),

q('esofag-adv-026',['Supraviețuirea generală la 5 ani a pacienților diagnosticați cu cancer esofagian este de aproximativ:',
 ['5%','10%','20%','35%','50%'],'C',151,'Carcinomul esofagian — Prognostic',
 'Fixarea supraviețuirii generale la 5 ani în cancerul esofagian.',
 ['Nu este cifra citată.','Nu este cifra citată.','Supraviețuirea generală la 5 ani rămâne redusă, la aproximativ 20%.','Nu este cifra citată.','50% sau mai mult este supraviețuirea stadiilor precoce.']],
 [8,'Distractorul de 50% este cifra reală a stadiilor precoce.'],['aproximativ 20%','bolii avansate']),

q('esofag-adv-037',['Supraviețuirea la 5 ani în stadiile precoce (I și IIa) ale cancerului esofagian este:',
 ['sub 10%','sub 30%','de aproximativ 20%','de aproximativ 90%','de cel puțin 50%'],'E',152,'Carcinomul esofagian — Stadializare',
 'Distincția prognostică dintre stadiile precoce și cele avansate.',
 ['Nu este cifra citată.','Sub 30% este supraviețuirea stadiilor avansate (IIb–IV).','Aproximativ 20% este rata globală.','Nu este cifra citată.','Stadiile precoce au supraviețuire la 5 ani de 50% sau mai mare.']],
 [8,'Distractorii sunt cifrele reale ale stadiilor avansate și ale ratei globale.'],['50% sau mai mare','<30%']),

q('esofag-adv-038',['În evaluarea paraclinică a cancerului esofagian:',
 ['EUS nu ajută la localizarea ganglionilor suspecți','CT-ul nu distinge invazia tumorală de inflamația locală','endoscopia este necesară pentru confirmarea histologică','ficatul și plămânii sunt sediile metastatice frecvente','bronhoscopia exclude invazia traheobronșică'],'BCDE',152,'Carcinomul esofagian — Diagnostic',
 'Atribuirea rolului fiecărei investigații în cancerul esofagian.',
 ['EUS definește profunzimea invaziei și localizează ganglionii pentru aspirație cu ac fin.','CT nu poate distinge reacția inflamatorie de invazia tumorală.','Evaluarea endoscopică este necesară pentru confirmarea histologică.','Ficatul și plămânii sunt organele cel mai frecvent implicate.','Bronhoscopia se face în tumorile proximale și mediotoracice.']],
 [8,'Distractorii contrazic rolul EUS și sediile metastatice citate.'],['invazia tumorală','bronhoscopia']),

q('esofag-adv-039',['În stadializarea TNM 2017 a cancerului esofagian:',
 ['localizarea tumorii se folosește numai pentru adenocarcinom','carcinomul scuamos și adenocarcinomul sunt clasificate diferit','localizarea tumorii se folosește numai pentru carcinomul scuamos','stadiile ≤IIa nu au afectare ganglionară','stadiul IIa admite metastaze la distanță limitate'],'BCD',152,'Carcinomul esofagian — Stadializare TNM',
 'Aplicarea regulilor de stadializare TNM 2017.',
 ['Localizarea este folosită numai pentru CSC.','CSC și adenocarcinomul sunt clasificate diferit.','Localizarea tumorii se folosește numai pentru stadializarea CSC.','Stadiile ≤IIa au invazie limitată, fără afectare ganglionară.','Stadiile ≤IIa sunt fără metastaze la distanță.']],
 [8,'Distractorul principal inversează tipul histologic la care se aplică localizarea.'],['stadializarea CSC','T2-3 NO MO']),

q('esofag-adv-016',['Terapia neoadjuvantă în cancerul esofagian:',
 ['a îmbunătățit supraviețuirea în toate studiile randomizate','folosește de obicei 5-FU, cisplatină și 45 Gy','reduce morbiditatea și mortalitatea perioperatorie','este urmată de rezecție la o lună de la terminare','aduce cel mai mare beneficiu la răspunsul complet'],'BDE',155,'Carcinomul esofagian — Terapia neoadjuvantă',
 'Aplicarea protocolului neoadjuvant și a limitelor sale.',
 ['Nu toate studiile au demonstrat îmbunătățirea supraviețuirii.','Protocolul uzual: 5-fluorouracil și cisplatină cu 45 Gy în 6–7 săptămâni.','Costul este creșterea morbidității și mortalității perioperatorii.','Rezecția se face la o lună după terminarea tratamentului.','Cel mai mare beneficiu apare la răspunsul complet.']],
 [8,'Distractorii inversează costul și generalizează un beneficiu inconstant.'],['45 Gy','răspuns complet'],[156]),

q('esofag-adv-017',['În paliația cancerului esofagian terminal:',
 ['radiochimioterapia are efect mai durabil, dar întârziat','dilatația endoscopică oferă ameliorare imediată, de scurtă durată','chirurgia este frecvent indicată pentru paliație','intervențiile endoscopice au un risc mai mare de perforație','laserul endoscopic are un risc ridicat de perforație'],'ABDE',156,'Carcinomul esofagian — Tratamentul paliativ',
 'Compararea modalităților paliative după rapiditate, durată și risc.',
 ['Radiochimioterapia este mai durabilă, dar efectul apare după săptămâni.','Dilatația dă ameliorare imediată, de obicei de scurtă durată.','Datorită tehnicilor endoscopice, chirurgia este rar indicată pentru paliație.','Intervențiile endoscopice au un risc mai mare de perforație.','Laserul ghidat endoscopic are un risc ridicat de perforație.']],
 [8,'Distractorii inversează rolul chirurgiei și riscul endoscopic.'],['câteva săptămâni','risc ridicat de perforaţie']),

q('esofag-adv-071',['Stenturile metalice expandabile paliative:',
 ['se folosesc pentru tumorile esofagului cervical','au înlocuit tuburile rigide din plastic','au efect întârziat, după câteva săptămâni','asigură un efect durabil, de mai mulți ani','pot produce reflux semnificativ când sunt montate distal'],'BE',156,'Tratamentul paliativ — Stenturile esofagiene',
 'Recunoașterea indicațiilor și complicațiilor stenturilor paliative.',
 ['Stenturile se folosesc pentru tumorile mediotoracice și distale.','Stenturile metalice expandabile au înlocuit tuburile rigide din plastic.','Efectul este imediat; întârzierea caracterizează radiochimioterapia.','Simptomele pot reapărea în câteva luni, cu reintervenție.','Montate în esofagul distal, pot produce reflux semnificativ.']],
 [8,'Distractorii preiau cinetica radiochimioterapiei și un sediu neindicat.'],['tuburile rigide','migrarea stentului']),

q('esofag-adv-035',['Terapia fotodinamică, comparativ cu laserul endoscopic, are:',
 ['un risc mai mare de perforație','o penetrare tisulară mai mare','un efect mai durabil decât radiochimioterapia','un risc mai mic de perforație și excizie limitată','indicație de primă linie în tumorile esofagiene rezecabile'],'D',156,'Tratamentul paliativ — Terapia fotodinamică',
 'Traducerea penetrării limitate în risc și eficiență.',
 ['Laserul are riscul ridicat de perforație.','Penetrarea tisulară este limitată.','Radiochimioterapia rămâne modalitatea cu efect durabil.','Penetrarea limitată reduce perforația, dar limitează excizia.','Este o modalitate paliativă.']],
 [8,'Cere asocierea corectă a două consecințe ale aceleiași proprietăți.'],['fotodinamică','penetrare tisulară']),
];
