import {rewriter} from './rewrite-author';
import {RETIRED_FICAT_SPLINA} from './retired/ficat-splina';

// Rewritten after the 2026-09-24 cue audit (Lawrence, cap. 20, p. 317–324 și 333–342).
const q=rewriter(RETIRED_FICAT_SPLINA,(p:number)=>p<=324?p-130:p-138,{shuffle:true});

export const FICAT_SPLINA_V2=[
q('ficat-splina-adv-001',['Ficatul:',
 ['cântărește la adult 1.200–1.600 g','primește un sfert din fluxul sanguin prin artera hepatică','are variante arteriale în până la 40% din cazuri','drenează prin trei vene suprahepatice în VCI','primește trei sferturi din flux prin artera hepatică'],'ABCD',317,'Anatomia ficatului',
 'Recunoașterea anatomiei vasculare a ficatului.',
 ['Masa hepatică la adult este 1.200–1.600 g.','Un sfert vine arterial, restul portal.','Variantele arteriale apar în până la 40%.','Cele trei vene suprahepatice drenează în VCI.','Artera hepatică asigură un sfert.']],
 [8,'Singurul distractor inversează aportul arterial și portal.'],['1.200-1.600 g','40%']),

q('ficat-splina-adv-019',['Anatomia chirurgicală a ficatului:',
 ['capsula Glisson se extinde de-a lungul pediculului portal','aria nuda nu este acoperită de peritoneu visceral','segmentarea Couinaud cuprinde opt segmente','fiecare segment are circulație și drenaj biliar comune cu vecinii','ligamentul falciform leagă ficatul de mica curbură gastrică'],'ABC',317,'Anatomia ficatului',
 'Recunoașterea reperelor anatomice hepatice.',
 ['Capsula Glisson urmează vasele intraparenchimatos.','Aria nuda și patul veziculei nu au peritoneu.','Ficatul are opt segmente.','Fiecare segment are circulație și drenaj propriu.','Omentul mic leagă ficatul de mica curbură.']],
 [8,'Distractorii contrazic autonomia segmentară și rolul ligamentelor.'],['capsula Glisson','opt segmente']),

q('ficat-splina-adv-035',['Fiziologia ficatului:',
 ['lobulul hepatic este unitatea funcțională','celulele Kupffer reprezintă 80–90% din macrofagele fixe','hepatocitele regenerează masa hepatică la fiecare 50 de zile','vena hepatică de drenaj se află la periferia lobulului','ligamentul gastrohepatic unește ficatul cu colonul transvers'],'ABC',317,'Fiziologia ficatului',
 'Recunoașterea organizării funcționale a ficatului.',
 ['Lobulul hepatic este unitatea funcțională.','Kupffer: 80–90% din macrofagele fixe.','Regenerarea completă are loc la 50 de zile.','Vena de drenaj este centrală.','Ligamentul gastrohepatic merge la stomac și duoden.']],
 [8,'Distractorii inversează arhitectura lobulului și ligamentul.'],['lobulul','80-90%']),

q('ficat-splina-adv-049',['În leziunile hepatice traumatice, principala indicație de intervenție chirurgicală este:',
 ['instabilitatea hemodinamică','lichidul liber la FAST','lacerarea vizibilă la CT','fracturile coastelor inferioare drepte','creșterea marcată a transaminazelor'],'A',318,'Leziunile hepatice traumatice',
 'Aplicarea indicației operatorii în trauma hepatică.',
 ['Instabilitatea hemodinamică este principala indicație.','Nu este indicația citată.','Nu este indicația citată.','Nu este indicația citată.','Nu este indicația citată.']],
 [8,'Distractorii sunt constatări paraclinice plauzibile.'],['Instabilitatea hemodinamică','computer tomografia'],[317]),

q('ficat-splina-adv-003',['Leziunile hepatice descoperite incidental:',
 ['sunt adesea benigne și nu necesită tratament','impun evitarea biopsiei percutanate precoce la asimptomatici','pot fi însămânțate tumoral prin biopsie','includ leziuni benigne care se rezecă chiar asimptomatice','se biopsiază de rutină înaintea imagisticii'],'ABCD',319,'Tumorile hepatice',
 'Aplicarea principiilor de evaluare a leziunilor incidentale.',
 ['Leziunile benigne sunt frecvente și nu necesită tratament.','Biopsia precoce se evită la asimptomatici.','Biopsia poate da hemoragie și însămânțare.','Unele leziuni benigne se rezecă.','Biopsia nu precede imagistica.']],
 [8,'Singurul distractor inversează rolul biopsiei.'],['însămânţarea tumorală','asimptomatici']),

q('ficat-splina-adv-004',['Hemangiomul cavernos hepatic:',
 ['este cea mai frecventă tumoră hepatică benignă','este de 5 ori mai frecvent la femei','se numește gigant peste 10 cm','apare hiperecogen la ultrasonografie','alterează de regulă funcția hepatică'],'ABCD',319,'Hemangiomul',
 'Recunoașterea hemangiomului hepatic.',
 ['Este cea mai frecventă tumoră benignă.','Frecvența este de 5 ori mai mare la femei.','Peste 10 cm este gigant.','Ultrasonografia arată un focar hiperecogen.','Funcția hepatică rămâne normală.']],
 [8,'Singurul distractor contrazice funcția hepatică.'],['5 ori mai mare','hiperecogen']),

q('ficat-splina-adv-020',['Aspectul CT cu contrast al hemangiomului cavernos hepatic este de:',
 ['captare periferică progresivă spre centru','captare arterială precoce urmată de washout','defect de captare prin lipsa celulelor Kupffer','cicatrice centrală stelată cu septuri','masă hipodensă cu perete bine vascularizat'],'A',319,'Hemangiomul',
 'Diferențierea imagistică a hemangiomului.',
 ['Captarea progresează de la periferie spre centru.','Descrie CHC.','Descrie scintigrafia adenomului.','Descrie HNF.','Descrie abcesul piogen.']],
 [8,'Distractorii descriu celelalte leziuni hepatice.'],['periferia leziunii','hipodensă centrală']),

q('ficat-splina-adv-036',['Hemangiomul cavernos hepatic gigant:',
 ['nu sângerează spontan la urmărirea pe peste 10 ani','produce rar durere, care are adesea altă cauză','poate crește în dimensiuni în timpul vieții','impune rezecție chiar dacă este asimptomatic','se rupe spontan frecvent după 10 ani de evoluție'],'ABC',320,'Hemangiomul',
 'Aplicarea conduitei în hemangiomul gigant.',
 ['Urmăririle de peste 10 ani confirmă absența rupturilor.','Durerea are de regulă altă etiologie.','Leziunile pot crește în timpul vieții.','Nu necesită terapie specifică.','Nu există rupturi spontane la urmărire.']],
 [8,'Distractorii supraestimează riscul.'],['hemoragiilor spontane','altă etiologie'],[319]),

q('ficat-splina-adv-005',['Hiperplazia nodulară focală:',
 ['este un proces regenerativ, fără potențial malign','are cicatrice centrală stelată pe CT','se tratează conservator după diagnosticul imagistic','crește sub contraceptive orale','nu conține ducte biliare, spre deosebire de adenom'],'ABC',320,'Hiperplazia nodulară focală',
 'Recunoașterea și conduita în HNF.',
 ['Este regenerativă și nu are potențial malign.','Cicatricea centrală stelată apare în leziunile mari.','Se tratează conservator.','Creșterea nu este influențată hormonal.','HNF schițează ducte biliare.']],
 [8,'Distractorii preiau trăsăturile adenomului.'],['proces regenerativ','cicatrice centrală']),

q('ficat-splina-adv-037',['În hiperplazia nodulară focală, ecografia Doppler poate arăta:',
 ['semnal vascular în „spițe de roată”','captare centripetă progresivă','masă hipoecogenă cu perete ecogen','defect de captare fără celule Kupffer','washout în faza portală'],'A',320,'Hiperplazia nodulară focală',
 'Recunoașterea aspectului Doppler al HNF.',
 ['Semnalul în spițe de roată este tipic.','Descrie CT-ul hemangiomului.','Descrie abcesul piogen.','Descrie scintigrafia adenomului.','Descrie CHC.']],
 [8,'Distractorii sunt aspecte ale altor leziuni.'],['spiţe de roată','Doppler']),

q('ficat-splina-adv-006',['Adenomul hepatic:',
 ['apare frecvent la femeia de 30–50 de ani','se asociază cu contraceptivele orale de lungă durată','nu conține triade portale sau ducte biliare','captează intens 99mTc prin celulele Kupffer','este de regulă o leziune multiplă, încapsulată'],'ABC',320,'Adenomul hepatic',
 'Recunoașterea adenomului hepatic.',
 ['Apare la femeia de 30–50 de ani.','Majoritatea au expunere la estrogeni.','Este format din hepatocite fără triadă sau duct.','Nu conține celule Kupffer și nu captează.','Este solitar și neîncapsulat.']],
 [8,'Distractorii inversează captarea și structura.'],['neîncapsulate','30 şi 50 de ani']),

q('ficat-splina-adv-051',['Imagistica adenomului hepatic:',
 ['arată pe CT o masă hipodensă cu hemoragie','are aspect heterogen la IRM, patognomonic','arată defect de captare la scintigrafia cu 99mTc','are biopsie cu ac fiabilă, fără erori de prelevare','arată cicatrice centrală stelată cu spițe de roată'],'ABC',320,'Adenomul hepatic',
 'Interpretarea imagisticii adenomului.',
 ['CT: masă hipodensă cu hemoragie.','Heterogenitatea la IRM este patognomonică.','Lipsa celulelor Kupffer dă defect de captare.','Erorile de prelevare complică diferențierea.','Descrie HNF.']],
 [8,'Distractorii supraestimează biopsia și preiau semnele HNF.'],['patognomonic','Kupffer']),

q('ficat-splina-adv-021',['Conduita în adenomul hepatic:',
 ['oprirea contraceptivelor este prima măsură','poate crește sau sângera în 20–40% din cazuri','activarea beta-cateninei indică intervenția chirurgicală','complicațiile sunt mai rare la femeile gravide','nu are indicație chirurgicală nici peste 5 cm'],'ABC',321,'Adenomul hepatic',
 'Aplicarea stratificării riscului în adenom.',
 ['Oprirea contraceptivelor poate duce la regresie.','Creșterea sau sângerarea apar în 20–40%.','Beta-catenina indică risc de malignizare.','Complicațiile sunt mai frecvente în sarcină.','Peste 5 cm complicațiile sunt mai frecvente.']],
 [8,'Distractorii inversează factorii de risc.'],['beta-cateninei','regresie dimensională']),

q('ficat-splina-adv-050',['Hemoragia pe adenom hepatic asociată cu șoc hipovolemic impune:',
 ['tratament de urgență imediat','embolizare, apoi chirurgie programată','oprirea contraceptivelor și observație','biopsie pentru beta-catenină','doar resuscitare volemică'],'A',321,'Adenomul hepatic',
 'Aplicarea conduitei în hemoragia pe adenom.',
 ['Șocul hipovolemic cere tratament de urgență.','Se aplică în celelalte situații hemoragice.','Nu este conduita în șoc.','Nu este conduita în șoc.','Resuscitarea singură nu este suficientă.']],
 [8,'Distractorii sunt conduite din situațiile fără șoc.'],['şoc hipovolemic','embolizare']),

q('ficat-splina-adv-007',['Carcinomul hepatocelular:',
 ['reprezintă 90% din tumorile maligne hepatice primare','apare pe boală hepatică cronică în 70–80% din cazuri','are AFP crescută la 60–80% dintre pacienți','apare doar pe ciroză, nu la purtătorii VHB necirotici','reprezintă cea mai frecventă tumoră malignă din ficat'],'ABC',321,'Carcinomul hepatocelular',
 'Recunoașterea epidemiologiei CHC.',
 ['Reprezintă 90% din tumorile maligne primare.','Apare pe boală cronică în 70–80%.','AFP este crescută la 60–80%.','Apare și la infectați VHB/VHC fără ciroză.','Metastazele sunt cele mai frecvente tumori maligne hepatice.']],
 [8,'Distractorii confundă primar cu total și restrâng contextul.'],['90% din tumorile','60-80%']),

q('ficat-splina-adv-022',['Diagnosticul carcinomului hepatocelular la cirotic:',
 ['impune ecografie de supraveghere bianuală','impune investigarea oricărei leziuni peste 1 cm','se bazează pe captare arterială urmată de washout','impune biopsie chiar la aspect imagistic tipic','este confirmat de o AFP de 200–400 mg/dL'],'ABC',321,'Carcinomul hepatocelular',
 'Aplicarea supravegherii și diagnosticului CHC.',
 ['Ultrasonografia bianuală este recomandată.','Orice formațiune >1 cm se investighează.','Captarea arterială cu washout este tipică.','Biopsia se face doar la aspect atipic.','200–400 mg/dL apare și la cirotici fără CHC.']],
 [8,'Distractorii supraestimează biopsia și AFP moderată.'],['bianual','washout']),

q('ficat-splina-adv-052',['Carcinomul hepatocelular trebuie suspectat la ciroticul cu:',
 ['accentuarea icterului','encefalopatie nou apărută','creșterea ascitei','orice tumoră hepatică solidă','chist simplu seros'],'ABCD',321,'Carcinomul hepatocelular',
 'Recunoașterea situațiilor care sugerează CHC.',
 ['Accentuarea icterului este citată.','Encefalopatia este citată.','Creșterea ascitei este citată.','CHC intră în diagnosticul oricărei tumori solide.','Chistul simplu nu este o tumoră solidă.']],
 [8,'Singurul distractor este o leziune chistică benignă.'],['decompensare clinică','ascitei']),

q('ficat-splina-adv-038',['Sunt factori de risc pentru carcinomul hepatocelular:',
 ['infecția VHB fără ciroză','infecția VHC fără ciroză','steatoza non-alcoolică asociată obezității','consumul de alcool','contraceptivele orale'],'ABCD',321,'Carcinomul hepatocelular',
 'Recunoașterea factorilor de risc ai CHC.',
 ['VHB crește riscul chiar fără ciroză.','VHC crește riscul chiar fără ciroză.','Steatoza non-alcoolică este citată.','Alcoolul este citat.','Contraceptivele se asociază cu adenomul.']],
 [8,'Singurul distractor aparține adenomului.'],['steatoza hepatică','alcool']),

q('ficat-splina-adv-008',['Tratamentul chirurgical al carcinomului hepatocelular:',
 ['pe ficat sănătos permite rezecția a până la 70% din volum','pe ciroză preferă rezecția segmentară','prin transplant elimină și recidiva în ficatul cirotic','pe ciroză permite aceleași rezecții extinse','prin transplant este limitat doar de invazia vasculară'],'ABC',322,'Carcinomul hepatocelular — tratament',
 'Aplicarea opțiunilor chirurgicale în CHC.',
 ['Până la 70% pe parenchim sănătos.','Ciroza limitează regenerarea.','Transplantul elimină parenchimul cirotic restant.','Regenerarea este mult limitată în ciroză.','Limitările sunt donatorii și costurile.']],
 [8,'Distractorii ignoră ciroza și limitările transplantului.'],['70% din volumul','rezecţia segmentară']),

q('ficat-splina-adv-053',['Criteriile Milano pentru transplantul hepatic în carcinomul hepatocelular cer:',
 ['tumoră unică <5 cm sau ≤3 tumori ≤3 cm, fără invazie vasculară','tumoră unică <3 cm sau ≤5 tumori ≤5 cm, fără invazie vasculară','tumoră unică <5 cm sau ≤3 tumori ≤3 cm, cu invazie venoasă portală','tumoră unică <8 cm, indiferent de invazia vasculară','oricâte tumori ≤3 cm, fără metastaze extrahepatice'],'A',322,'Carcinomul hepatocelular — tratament',
 'Aplicarea criteriilor Milano.',
 ['Tumoră unică <5 cm sau ≤3 tumori ≤3 cm, fără invazie.','Valorile sunt inversate.','Invazia vasculară exclude.','Nu este criteriul citat.','Numărul este limitat la trei.']],
 [8,'Distractorii inversează valorile și invazia.'],['Milano','fără invazie vasculară']),

q('ficat-splina-adv-023',['Tratamentele loco-regionale ale carcinomului hepatocelular:',
 ['ablația termică distruge tumora la peste 100°C','chemoembolizarea folosește de obicei doxorubicină','radioembolizarea folosește microsfere cu Y90','radioembolizarea produce ocluzie arterială reală','hepatocarcinomul este irigat preponderent portal'],'ABC',322,'Carcinomul hepatocelular — tratament',
 'Recunoașterea principiilor ablației și embolizării.',
 ['Ablația termică depășește 100°C.','Doxorubicina este agentul uzual.','Y90 în microsfere de sticlă.','Particulele sunt prea mici pentru ocluzie.','CHC este irigat preponderent arterial.']],
 [8,'Distractorii inversează irigația și mecanismul.'],['doxorubicină','Y90']),

q('ficat-splina-adv-024',['După rezecția carcinomului hepatocelular pe ficat cirotic:',
 ['parenchimul restant e sediul recidivei la peste 50%','metastazele apar mai ales în plămân și os','metastazele cerebrale și peritoneale sunt rare','recidiva este rară, sub 10% din cazuri','metastazele apar mai ales în creier și peritoneu'],'ABC',322,'Carcinomul hepatocelular — recidiva',
 'Recunoașterea evoluției după rezecția CHC.',
 ['Recidiva în restant apare la peste 50%.','Plămânul și osul sunt sediile principale.','Creierul și peritoneul sunt mai rare.','Recidiva depășește 50%.','Sunt mult mai puțin frecvente.']],
 [8,'Distractorii inversează frecvența recidivei și sediile.'],['plămânul','peste 50%']),

q('ficat-splina-adv-054',['Colangiocarcinomul:',
 ['poate fi asimptomatic în forma periferică','produce icter obstructiv în forma hilară (Klatskin)','este adesea invizibil pe CT','produce icter cu veziculă biliară destinsă','se tratează de elecție prin chemoembolizare'],'ABC',322,'Colangiocarcinomul',
 'Recunoașterea colangiocarcinomului.',
 ['Leziunile periferice pot fi asimptomatice.','Tumorile Klatskin produc icter.','Frecvent nu există tumoră vizibilă pe CT.','Vezicula biliară este mică.','Se tratează prin rezecție hepatică.']],
 [8,'Distractorii inversează semnul veziculei și tratamentul.'],['Klatskin','colangio-IRM']),

q('ficat-splina-adv-025',['Icterul cu ducte biliare intrahepatice dilatate și veziculă biliară mică sugerează:',
 ['colangiocarcinom hilar','litiază coledociană distală','cancer de cap de pancreas','carcinom hepatocelular periferic','abces hepatic piogen'],'A',322,'Colangiocarcinomul',
 'Localizarea obstrucției biliare după semnele imagistice.',
 ['Obstrucția hilară lasă vezicula mică.','Obstrucția distală destinde vezicula.','Obstrucția distală destinde vezicula.','Nu produce acest tablou.','Nu produce acest tablou.']],
 [8,'Distractorii sunt cauze de obstrucție distală.'],['vezicula biliară','hilar']),

q('ficat-splina-adv-039',['Metastazele hepatice:',
 ['sunt cele mai frecvente tumori maligne din ficat','apar la autopsie la 30–40% din decedații prin cancer','dau supraviețuire de 55–65% la 5 ani după rezecție','sunt de obicei de origine mamară sau melanică','nu se rezecă dacă sunt de origine neuroendocrină'],'ABC',322,'Metastazele hepatice',
 'Recunoașterea epidemiologiei și beneficiului rezecției metastazelor.',
 ['Sunt cele mai frecvente tumori maligne hepatice.','30–40% la autopsie.','În cancerul colorectal: 55–65% la 5 ani.','Sunt de obicei de origine GI.','Tumorile neuroendocrine metastazează specific hepatic.']],
 [8,'Distractorii schimbă originea și indicația.'],['30-40%','55-65%']),

q('ficat-splina-adv-040',['Rezecția metastazelor hepatice colorectale:',
 ['beneficiază mai ales pacienții cu CEA scăzut','beneficiază pacienții fără progresie peste 1 an','este urmată de recidivă la 60–70% dintre pacienți','este inferioară ablației prin radiofrecvență','este contraindicată la leziuni bilobare'],'ABC',322,'Metastazele hepatice',
 'Selecția pacienților pentru rezecția metastazelor.',
 ['CEA scăzut este favorabil.','Peste 1 an fără progresie este favorabil.','Recidiva apare la 60–70%.','Ablația este inferioară rezecției.','Chirurgii abordează și leziuni din ambii lobi.']],
 [8,'Distractorii inversează ierarhia și restrâng indicația.'],['60-70%','ambii lobi'],[323]),

q('ficat-splina-adv-009',['Chistul hepatic simplu:',
 ['apare la 10% dintre pacienți','nu comunică cu arborele biliar','se tratează, când e simptomatic, prin decorticare','se vindecă definitiv prin aspirație','este de regulă multiplu, cu zeci de chisturi'],'ABC',323,'Chisturile hepatice',
 'Recunoașterea și tratamentul chistului simplu.',
 ['Apare la 10% dintre pacienți.','Nu comunică cu arborele biliar.','Decorticarea este tratamentul standard.','Simptomele reapar de obicei după aspirație.','Când sunt multiple, sunt 3–4.']],
 [8,'Distractorii supraestimează aspirația și numărul.'],['10% dintre pacienţi','arborele biliar']),

q('ficat-splina-adv-055',['Boala polichistică hepatică:',
 ['are transmitere autozomal dominantă','se asociază cu boala polichistică renală','poate impune transplant în cazurile extreme','se tratează eficient prin decorticare','are chisturi comunicante cu arborele biliar'],'ABC',323,'Boala polichistică hepatică',
 'Recunoașterea bolii polichistice hepatice.',
 ['Este autozomal dominantă.','Se asociază cu boala polichistică renală.','Transplantul este o opțiune extremă.','Decorticarea este rar eficientă.','Microscopic sunt similare chisturilor simple.']],
 [8,'Distractorii preiau tratamentul chistului simplu.'],['autozomal dominantă','transplantul hepatic']),

q('ficat-splina-adv-026',['Neoplasmul chistic hepatic (chistadenomul):',
 ['apare mai ales la femei după 40 de ani','are conținut mucinos și septuri multiple','se tratează prin excizie chirurgicală','se tratează prin marsupializare sau drenaj intern','are conținut seros, fără septuri sau noduli'],'ABC',323,'Neoplasmul chistic',
 'Recunoașterea neoplasmului chistic hepatic.',
 ['Apare la femei după 40 de ani.','Conținutul este mucinos, cu septuri.','Excizia este tratamentul preferat.','Procedurile non-rezecționale sunt contraindicate.','Are septuri și noduli intramurali.']],
 [8,'Distractorii preiau aspectul chistului simplu.'],['mucinos','marsupializarea']),

q('ficat-splina-adv-027',['Abcesul hepatic piogen:',
 ['produce febră, durere și leucocitoză','are fosfataza alcalină crescută la majoritatea','provine de obicei dintr-o infecție digestivă sau biliară','se tratează doar cu metronidazol, fără drenaj','provine de obicei prin însămânțare hematogenă'],'ABC',323,'Abcesul piogen',
 'Recunoașterea abcesului piogen.',
 ['Durere în hipocondrul drept, febră, leucocitoză.','Fosfataza alcalină este crescută.','Diverticulita, apendicita sau arborele biliar.','Drenajul percutanat este necesar.','Hematogen doar minoritar.']],
 [8,'Distractorii preiau conduita abcesului amebian.'],['Fosfataza alcalină','apendicită']),

q('ficat-splina-adv-028',['Abcesul hepatic amebian:',
 ['apare la ~10% dintre pacienții infectați','are conținut steril, cu aspect de „pastă de anșoa”','răspunde foarte bine la metronidazol','necesită drenaj percutanat ca abcesul piogen','are serologie negativă la majoritatea'],'ABC',324,'Abcesul amebian',
 'Recunoașterea abcesului amebian.',
 ['Apare la circa 10% dintre infectați.','Conținutul este steril, „pastă de anșoa”.','Răspunde foarte bine la metronidazol.','Nu necesită drenaj percutanat.','Anticorpii sunt prezenți la aproape toți.']],
 [8,'Distractorii preiau conduita abcesului piogen.'],['pastă de anşoa','metronidazol']),

q('ficat-splina-adv-010',['Chistul hidatic hepatic:',
 ['este produs de Echinococcus granulosus sau multilocularis','afectează ficatul în două treimi din cazuri','se confirmă prin teste serologice','se confirmă prin puncție-aspirație diagnostică','asociază eozinofilie la toți pacienții'],'ABC',324,'Chistul hidatic',
 'Recunoașterea și diagnosticul chistului hidatic.',
 ['Echinococcus granulosus sau multilocularis.','Două treimi apar în ficat.','Serologia confirmă diagnosticul.','Puncția se evită (însămânțare, anafilaxie).','Eozinofilia apare la o treime–jumătate.']],
 [8,'Distractorii inversează rolul puncției și eozinofiliei.'],['protoscolecşi','serologice']),

q('ficat-splina-adv-041',['Tratamentul chistului hidatic hepatic:',
 ['albendazolul se folosește la chisturile mici uniloculate','chirurgia este cea mai eficientă la chisturi mari cu fistulă biliară','prevenirea însămânțării intraoperatorii este timpul esențial','aspirația percutanată este contraindicată în orice situație','metronidazolul este tratamentul medical de elecție'],'ABC',324,'Chistul hidatic',
 'Aplicarea tratamentului chistului hidatic.',
 ['Albendazolul controlează chisturile mici uniloculate.','Chirurgia este cea mai eficientă la chisturi mari cu fistulă.','Prevenirea însămânțării este timpul cel mai important.','Aspirația se face în cazuri selecționate.','Metronidazolul tratează abcesul amebian.']],
 [8,'Distractorii exclud aspirația și preiau antiamebianul.'],['albendazol','scolicizi']),

q('ficat-splina-adv-011',['Hipertensiunea portală:',
 ['este semnificativă clinic la GPVH ≥10 mmHg','este cauzată de ciroză în ~90% din cazuri în SUA','este produsă la copil în ~50% prin tromboză portală','are ca cauză prehepatică sindromul Budd-Chiari','este ușoară la GPVH între 10 și 15 mmHg'],'ABC',324,'Hipertensiunea portală',
 'Recunoașterea definițiilor și cauzelor hipertensiunii portale.',
 ['GPVH ≥10 mmHg este semnificativ clinic.','Ciroza produce ~90% din cazuri în SUA.','Tromboza venei porte: ~50% la copii.','Budd-Chiari este o cauză posthepatică.','Forma ușoară are GPVH 5–10 mmHg.']],
 [8,'Distractorii mută Budd-Chiari și pragurile.'],['90%','Budd-Chiari']),

q('ficat-splina-adv-042',['Colateralele porto-sistemice din hipertensiunea portală:',
 ['varicele esofagiene drenează spre sistemul azygos','hemoroizii drenează spre sistemul iliac','capul de meduză provine din vena ombilicală','venele retroperitoneale comunică cu vena cavă','varicele esofagiene drenează spre vena splenică'],'ABCD',324,'Hipertensiunea portală',
 'Recunoașterea căilor colaterale porto-sistemice.',
 ['Venele submucoase esofagiene comunică cu azygos.','Venele hemoroidale comunică cu sistemul iliac.','Vena ombilicală produce capul de meduză.','Venele retroperitoneale comunică cu vena cavă.','Drenajul sistemic este spre azygos.']],
 [8,'Singurul distractor inversează sensul colateralei.'],['azygos','capul de meduză']),

q('ficat-splina-adv-029',['Hepatita fulminantă prin intoxicația cu ciuperci:',
 ['produce encefalopatie precoce','duce frecvent la deces în 1–2 săptămâni fără transplant','nu asociază hipertensiune portală sau malnutriție','face transplantul tehnic mai dificil decât în ciroză','permite prelungirea observației fără limită'],'ABC',333,'Insuficiența hepatică fulminantă',
 'Recunoașterea insuficienței hepatice fulminante.',
 ['Encefalopatia apare precoce.','Decesul survine la 1–2 săptămâni fără transplant.','Lipsa bolii cronice exclude HTP și malnutriția.','Transplantul este tehnic mai ușor.','Observația nu trebuie prelungită.']],
 [8,'Distractorii inversează dificultatea transplantului.'],['ciupercile sălbatice','1-2 săptămâni']),

q('ficat-splina-adv-012',['Splina:',
 ['cântărește la adult 75–150 g','primește ~5% din debitul cardiac','este cea mai mare masă limfoidă din organism','are splină accesorie la 10–30% din populație','are splina accesorie mai ales în oment'],'ABCD',333,'Anatomia și fiziologia splinei',
 'Recunoașterea anatomiei splinei.',
 ['Masa splinei este 75–150 g.','Primește ~5% din debitul cardiac.','Este cea mai mare masă limfoidă.','Splina accesorie apare la 10–30%.','Hilul este cea mai frecventă localizare.']],
 [8,'Singurul distractor inversează localizarea splinei accesorii.'],['75-150 g','10-30%']),

q('ficat-splina-adv-043',['Vascularizația splinei:',
 ['artera splenică este ramură a trunchiului celiac','artera splenică merge pe marginea superioară a pancreasului','arterele gastrice scurte asigură flux colateral','vena splenică se unește cu mezenterica superioară','artera splenică trece caudal de vena splenică'],'ABCD',333,'Anatomia și fiziologia splinei',
 'Recunoașterea vascularizației splinei.',
 ['Artera splenică vine din trunchiul celiac.','Merge de-a lungul marginii superioare a pancreasului.','Gastricele scurte asigură colateralitate.','Formează vena portă.','Artera este craniala venei.']],
 [8,'Singurul distractor inversează raportul arteră–venă.'],['trunchiului celiac','gastrice scurte']),

q('ficat-splina-adv-044',['Cea mai frecventă localizare a splinei accesorii este:',
 ['hilul splinei','ligamentul splenocolic','ligamentul gastrocolic','omentul mare','coada pancreasului'],'A',333,'Anatomia și fiziologia splinei',
 'Localizarea splinei accesorii.',
 ['Hilul este cel mai frecvent.','Este a doua localizare.','Este a treia localizare.','Este mai rară.','Nu este cea mai frecventă.']],
 [8,'Distractorii sunt celelalte localizări, în ordine descrescătoare.'],['mezogastrului dorsal','splenocolic']),

q('ficat-splina-adv-030',['Funcția de filtrare a splinei:',
 ['filtrează ~350 L de sânge pe zi','îndepărtează eritrocitele de 110–120 de zile','înlătură corpii Howell-Jolly și Heinz din hematii','depozitează o treime din trombocite','își menține hematopoieza la adult'],'ABCD',334,'Anatomia și fiziologia splinei',
 'Recunoașterea funcției de filtrare splenică.',
 ['Filtrează ~350 L/zi.','Eritrocitele de 110–120 de zile sunt îndepărtate.','Incluziunile sunt înlăturate.','O treime din trombocite este depozitată.','Hematopoieza se oprește după naștere.']],
 [8,'Singurul distractor prelungește hematopoieza splenică.'],['350 L','Howell-Jolly']),

q('ficat-splina-adv-045',['Funcțiile imune ale splinei:',
 ['este cea mai mare sursă de IgM','splenectomia scade producția de opsonină','splenectomia este urmată de trombocitoză pasageră','splina mărită hematologic este de obicei dureroasă','splenectomia crește nivelul IgM'],'ABC',335,'Anatomia și fiziologia splinei',
 'Recunoașterea rolului imun al splinei.',
 ['Este cea mai mare sursă de IgM.','Opsonina scade după splenectomie.','Trombocitoza pasageră urmează splenectomiei.','Splina hematologică nu este de obicei dureroasă.','IgM scade.']],
 [8,'Distractorii inversează IgM și durerea.'],['imunoglobulină M','opsonină']),

q('ficat-splina-adv-046',['Disconfortul la palparea unei spline mărite sugerează:',
 ['infarct sau ruptură splenică','splenomegalie din leucemie','splenomegalie din limfom','hipersplenism congestiv','splenomegalie din mielofibroză'],'A',335,'Anamneza și examenul clinic',
 'Interpretarea sensibilității splenice.',
 ['Infecția, infarctul sau ruptura dau disconfort.','Splina hematologică nu doare de obicei.','Splina hematologică nu doare de obicei.','Nu este cauza citată.','Splina hematologică nu doare de obicei.']],
 [8,'Distractorii sunt splenomegalii nedureroase.'],['infarct splenic','nu este de obicei dureroasă']),

q('ficat-splina-adv-057',['Explorarea imagistică a splinei:',
 ['radiografia pe gol poate sugera splenomegalia indirect','CT-ul cu contrast este cea mai utilă tehnică','ecografia este preferată în monitorizare, fără iradiere','scintigrafia arată splenoza ca absență a captării','radiografia pe gol vizualizează frecvent splina normală'],'ABC',336,'Explorări radiologice și imagistice',
 'Alegerea explorării imagistice splenice.',
 ['Devierea colonului, stomacului sau diafragmul ascensionat.','CT-ul cu contrast este cea mai utilă tehnică.','Ecografia evită iradierea.','Splenoza apare ca hipercaptare ectopică.','Splina normală apare rar.']],
 [8,'Distractorii inversează splenoza și vizibilitatea.'],['pe gol','Computer Tomografia'],[337]),

q('ficat-splina-adv-031',['Scintigrafia splenică cu coloizi de technetiu:',
 ['detectează splinele accesorii după splenectomie','diferențiază splina accesorie de o tumoră pancreatică','arată splenoza prin hipercaptare ectopică','înlocuiește angioCT-ul în trauma splenică','folosește coloizi preluați selectiv de hepatocite'],'ABC',337,'Scintigrafia',
 'Aplicarea scintigrafiei splenice.',
 ['Detectează splinele accesorii restante.','Diferențiază de o tumoră a cozii pancreatice.','Splenoza dă hipercaptare ectopică.','AngioCT-ul este folosit în traumă.','Coloizii sunt preluați de sistemul reticuloendotelial.']],
 [8,'Distractorii schimbă indicația și mecanismul.'],['Splenoza','cozii de pancreas']),

q('ficat-splina-adv-058',['Angiografia și embolizarea splenică:',
 ['angioCT-ul evaluează lacerațiile la traumatizatul stabil','embolizarea preoperatorie reduce sângerarea','embolizarea parțială controlează hipersplenismul la copil','cateterizarea splenică rămâne standardul în traumă','angioCT-ul este inutil în tromboza de venă splenică'],'ABC',337,'Angiografia',
 'Aplicarea angiografiei și embolizării splenice.',
 ['AngioCT-ul a înlocuit cateterizarea.','Embolizarea reduce sângerarea înaintea splenectomiei.','Controlează hipersplenismul la copiii cu HTP.','AngioCT-ul a înlocuit-o.','AngioCT-ul diagnostichează tromboza venei splenice.']],
 [8,'Distractorii contrazic rolul angioCT.'],['hipersplenismului','angioCT']),

q('ficat-splina-adv-059',['Conform Tabelului 20-5, abcesul splenic se asociază deseori cu:',
 ['abuzul de droguri sau SIDA','sferocitoza ereditară','purpura trombotică trombocitopenică','anevrismul de arteră splenică','tromboza de venă splenică'],'A',337,'Tabelul 20-5',
 'Recunoașterea contextului abcesului splenic.',
 ['Abuzul de droguri și SIDA sunt citate.','Este indicație hematologică.','Este indicație hematologică rară.','Este altă indicație din tabel.','Produce varice gastrice.']],
 [8,'Distractorii sunt alte indicații din tabel.'],['SIDA','Abces splenic']),

q('ficat-splina-adv-013',['Splina este organul cel mai frecvent lezat în:',
 ['contuziile abdominale','plăgile abdominale penetrante','traumatismele toracice penetrante','plăgile împușcate ale flancului drept','fracturile de bazin'],'A',337,'Traumatismele splenice',
 'Recunoașterea epidemiologiei traumei splenice.',
 ['Este cel mai frecvent în contuzii.','Este al doilea în plăgile penetrante.','Nu este datul citat.','Nu este datul citat.','Nu este datul citat.']],
 [8,'Distractorii sunt mecanisme de traumă plauzibile.'],['al doilea cel mai frecvent','Trauma reprezintă']),

q('ficat-splina-adv-034',['Traumatismul splenic:',
 ['la pacientul instabil impune splenectomie de urgență','la pacientul stabil permite prezervarea splinei','este cea mai frecventă indicație de splenectomie','la pacientul instabil impune embolizare de primă intenție','tratat non-operator nu necesită vaccinare'],'ABC',338,'Traumatismele splenice',
 'Aplicarea conduitei în trauma splenică.',
 ['Splenectomia de urgență este standardul la instabil.','Prezervarea splinei este posibilă la stabil.','Trauma este cea mai frecventă indicație.','Instabilul se operează.','Trebuie vaccinat și el.']],
 [8,'Distractorii contrazic conduita la instabil și vaccinarea.'],['OPSI','splenectomia de urgenţă'],[337,342]),

q('ficat-splina-adv-060',['Anomaliile funcției splenice:',
 ['mărimea splinei nu se corelează cu funcția','splenectomia este cea mai comună cauză de asplenie','siclemia poate produce asplenie funcțională','asplenia congenitală este frecventă','splenomegalia este sinonimă cu hipersplenismul'],'ABC',338,'Anomaliile funcției splenice',
 'Diferențierea hiposplenismului de hipersplenism.',
 ['Mărimea nu se corelează cu funcția.','Splenectomia este cauza cea mai comună.','Infarctele repetate duc la asplenie funcțională.','Este extrem de rară.','Nu trebuie confundate.']],
 [8,'Distractorii contrazic distincțiile citate.'],['asplenie','Mărimea splinei']),

q('ficat-splina-adv-014',['Sferocitoza ereditară:',
 ['are transmitere autozomal dominantă','implică deficit de spectrină, ankyrină sau banda 3','impune amânarea splenectomiei după 4–5 ani','poate asocia litiază biliară simptomatică','are transmitere autozomal recesivă'],'ABCD',338,'Anemia hemolitică',
 'Recunoașterea sferocitozei ereditare.',
 ['Este autozomal dominantă.','Proteinele membranare deficitare sunt citate.','Riscul OPSI impune amânarea.','Litiaza biliară simptomatică este citată.','Este autozomal dominantă.']],
 [8,'Singurul distractor inversează transmiterea.'],['ankyrină','litiază']),

q('ficat-splina-adv-061',['Splenectomia în talasemii:',
 ['reduce necesarul transfuzional în forma majoră','asociază cel mai mare risc de OPSI','este înlocuită preferabil de embolizare sau rezecție parțială','corectează sinteza de hemoglobină','este de rutină și în siclemia homozigotă'],'ABC',338,'Anemia hemolitică — talasemiile',
 'Aplicarea indicației splenectomiei în talasemii.',
 ['Reduce transfuziile și disconfortul.','Talasemicii au cel mai mare risc de OPSI.','Alternativele sunt preferate.','Defectul de sinteză rămâne.','În siclemie este rar indicată.']],
 [8,'Distractorii supraestimează efectul și extind indicația.'],['talasemia majoră','OPSI']),

q('ficat-splina-adv-032',['Anemiile hemolitice autoimune:',
 ['formele cu anticorpi la cald (IgG) răspund la splenectomie','formele cu anticorpi la rece (IgM) activează complementul','formele Coombs-pozitive se tratează inițial cu corticosteroizi','formele la rece răspund bine la splenectomie','formele Coombs-negative impun splenectomie de primă intenție'],'ABC',339,'Anemia hemolitică',
 'Diferențierea formelor de anemie hemolitică autoimună.',
 ['IgG la cald nu activează complementul și răspund.','IgM la rece activează complementul și aglutinează.','Corticosteroizii sunt prima linie.','Nu răspund la splenectomie.','Se tratează prin înlăturarea agentului.']],
 [8,'Distractorii inversează răspunsul la splenectomie.'],['anticorpi la cald','Coombs'],[338]),

q('ficat-splina-adv-062',['Conform Tabelului 20-7:',
 ['sferocitoza are transmitere autozomal dominantă','deficitul de G6PD are transmitere sex-linkată recesivă','siclemia rezultă din înlocuirea acidului glutamic cu valina','deficitul de G6PD are utilitate uzuală a splenectomiei','deficitul de piruvat-kinază are transmitere dominantă'],'ABC',339,'Tabelul 20-7',
 'Recunoașterea anemiilor hemolitice ereditare.',
 ['Sferocitoza este autozomal dominantă.','G6PD este sex-linkat recesiv.','Glu→Val în poziția 6 a lanțului β.','Splenectomia nu este utilă în G6PD.','Deficitul de PK este autozomal recesiv.']],
 [8,'Distractorii inversează utilitatea și transmiterea.'],['Sex-linkată','valina']),

q('ficat-splina-adv-015',['Trombocitopenia imună:',
 ['are anticorpi antiplachetari la 85% dintre pacienți','are corticosteroizii ca primă linie de tratament','răspunde durabil la splenectomie în 60–85%','are la copil de obicei evoluție cronică','are măduvă cu megacariocite de obicei scăzute'],'ABC',340,'Trombocitopenia imună',
 'Recunoașterea trombocitopeniei imune.',
 ['Anticorpii apar la 85%.','Corticosteroizii sunt prima linie.','Răspunsul durabil este 60–85%.','La copil este adesea autolimitată.','Megacariocitele sunt normale sau crescute.']],
 [8,'Distractorii inversează evoluția pediatrică și măduva.'],['85%','60-85%']),

q('ficat-splina-adv-063',['Splenectomia pentru trombocitopenia imună:',
 ['impune masă trombocitară disponibilă sub 20.000/mm³','cere transfuzia de trombocite după clamparea arterei splenice','poate recidiva prin splină accesorie omisă','accelerează progresia HIV spre SIDA','impune transfuzie de trombocite înainte de incizie'],'ABC',340,'Trombocitopenia imună',
 'Aplicarea conduitei perioperatorii în TI.',
 ['Sub 20.000 se asigură masa trombocitară.','Transfuzia după clampare evită distrugerea.','Splina accesorie sau splenoza explică recidiva.','Nu accelerează progresia spre SIDA.','Trombocitele transfuzate precoce sunt distruse.']],
 [8,'Distractorii inversează momentul transfuziei.'],['20.000','clampării arterei splenice']),

q('ficat-splina-adv-016',['Purpura trombotică trombocitopenică:',
 ['are mortalitate de ~90% netratată','se suspectează la anemie microangiopatică cu trombocitopenie','se tratează de obicei eficient prin plasmafereză','impune splenectomia ca tratament de primă linie','cere prezența pentadei complete pentru diagnostic'],'ABC',340,'Purpura trombotică trombocitopenică',
 'Recunoașterea și tratamentul PTT.',
 ['Mortalitatea netratată este ~90%.','Anemia microangiopatică și trombocitopenia sunt suficiente.','Plasmafereza este de obicei eficientă.','Splenectomia se folosește după eșec.','Pentada completă nu este universală.']],
 [8,'Distractorii devansează splenectomia și cer pentada.'],['90%','Plasmafereza']),

q('ficat-splina-adv-047',['În hipersplenism, splenectomia este indicată în caz de:',
 ['trombocite sub 50.000/mm³ cu hemoragie','neutropenie sub 2.000/mm³, cu sau fără infecții','anemie dependentă de transfuzii','hipersplenism din hipertensiunea portală','splenomegalie fără citopenie'],'ABC',341,'Hipersplenismul',
 'Aplicarea indicațiilor splenectomiei în hipersplenism.',
 ['Trombocite <50.000 cu hemoragie.','Neutropenie <2.000.','Anemia transfuzie-dependentă.','Se tratează hipertensiunea portală.','Citopenia definește hipersplenismul.']],
 [8,'Distractorii omit citopenia sau tratamentul cauzei.'],['50.000','2.000'],[340]),

q('ficat-splina-adv-056',['Splenectomia în hemopatiile maligne:',
 ['nu este indicată în leucemia acută','este rezervată paliației în leucemia cu celule păroase','se practică rar pentru stadializarea bolii Hodgkin','este indicată în limfomul splenic primar','este prima linie în leucemia cu celule păroase'],'ABCD',341,'Afecțiuni hematologice maligne',
 'Aplicarea indicațiilor splenectomiei în hemopatii.',
 ['Nu este indicată în leucemia acută.','Este paliativă; interferonul este prima linie.','Imagistica a înlocuit laparotomia de stadializare.','Limfomul splenic primar este excepția.','Interferonul și deoxicoformicina sunt prima linie.']],
 [8,'Singurul distractor contrazice prima linie.'],['celule păroase','Hodgkin']),

q('ficat-splina-adv-017',['După splenectomie:',
 ['leucocitele cresc cu ~50% și revin în 5–7 zile','trombocitoza >400.000/mm³ apare la 50% dintre pacienți','apar corpi Howell-Jolly pe frotiu','lipsa corpilor Howell-Jolly exclude splina accesorie','leucocitoza persistentă peste 7 zile este normală'],'ABC',341,'Modificări hematologice',
 'Interpretarea modificărilor hematologice postsplenectomie.',
 ['Leucocitele cresc cu 50%, revin în 5–7 zile.','Trombocitoza apare la 50%.','Corpii Howell-Jolly apar pe frotiu.','Lipsa lor sugerează splina accesorie.','Persistența sugerează infecție.']],
 [8,'Distractorii inversează semnificația frotiului și a leucocitozei.'],['Howell-Jolly','5-7 zile']),

q('ficat-splina-adv-033',['Trombocitoza postsplenectomie:',
 ['justifică antiagregare la trombocite >750.000/mm³','justifică antiagregare la mieloproliferativi >400.000/mm³','se tratează cu hidroxiuree în formele extreme','se tratează preferabil cu heparină sau warfarină','impune oprirea antiagregării după 7 zile'],'ABC',342,'Modificări hematologice',
 'Aplicarea profilaxiei trombotice postsplenectomie.',
 ['Toți pacienții peste 750.000/mm³.','Mieloproliferativii peste 400.000/mm³.','Hidroxiureea tratează trombocitozele extreme.','Anticoagularea nu aduce beneficii.','Se menține până la normalizare.']],
 [8,'Distractorii preferă anticoagularea și scurtează durata.'],['750.000','hidroxiuree'],[341]),

q('ficat-splina-adv-018',['Infecția severă postsplenectomie (OPSI):',
 ['are risc de ~2–4% la copilul sănătos','este produsă cel mai frecvent de pneumococ','e mai frecventă după splenectomia pentru boli hematologice','apare de obicei în perioada imediat postoperatorie','are risc egal la copil și la adult'],'ABC',342,'Consecințe imunologice',
 'Recunoașterea riscului de OPSI.',
 ['Copil: 2–4%; adult: 1–2%.','Pneumococul produce 75%.','Riscul maxim este în bolile hematologice.','Nu apare de obicei imediat postoperator.','Riscul este mai mare la copil.']],
 [8,'Distractorii inversează momentul și vârsta.'],['Streptococcus pneumoniae','hematologice']),

q('ficat-splina-adv-048',['Vaccinarea în contextul splenectomiei:',
 ['se vaccinează și trauma splenică tratată non-operator','vaccinarea electivă precedă operația cu peste o săptămână','copiii sub 2 ani nu dezvoltă imunizare eficientă','vaccinarea oferă protecție totală împotriva OPSI la adult','corticoterapia cronică crește răspunsul la vaccinare'],'ABC',342,'Consecințe imunologice',
 'Aplicarea vaccinării la splenectomizați.',
 ['Trauma tratată non-operator se vaccinează.','Peste o săptămână preoperator este suficient.','Sub 2 ani imunizarea este ineficientă.','Protecția nu este totală.','Corticoizii diminuă răspunsul.']],
 [8,'Distractorii supraestimează protecția și inversează efectul corticoizilor.'],['polivalent','2 ani']),

q('ficat-splina-adv-002',['Alte complicații postsplenectomie:',
 ['leziunile pancreatice apar în 1–5% din cazuri','abcesul subfrenic apare la 5–10 zile postoperator','hemoragia persistentă apare sub 1%','atelectazia pulmonară dreaptă este tipică','hemoragia persistentă apare mai ales după trauma'],'ABC',342,'Alte complicații postsplenectomie',
 'Recunoașterea complicațiilor postsplenectomie.',
 ['Leziunile pancreatice: 1–5%.','Abcesul subfrenic apare la 5–10 zile.','Hemoragia persistentă: <1%.','Atelectazia este stângă.','Apare mai ales la indicația pentru trombocitopenie.']],
 [8,'Distractorii inversează partea și indicația.'],['1-5%','pancreatice']),
];
