import {advancedQuestion} from './advanced-author';
import type {SourceRow} from './source-author';
const pdfOffset=(p:number)=>p<=1166?p-871:p<=1176?p-876:p-897;
const q=(n:number,row:SourceRow,score:number,reason:string,expressions:string[],related:number[]=[])=>
 advancedQuestion('gastro',32,pdfOffset,`gastro-adv-${String(n).padStart(3,'0')}`,row,[score,reason],expressions,undefined,related);

export const GASTRO_B=[
q(13,['Prevalența bolii de reflux gastro-esofagian în țările dezvoltate, conform textului, este de:',
 ['1-2%, similară Asiei','5%, limitată la fumători','10-20%','30-50%, identică herniei hiatale prin alunecare','70%, cât hernia hiatală din esofagita erozivă'],'C',1162,'Faringele și esofagul — BAGE: epidemiologie',
 'Diferențierea prevalenței 10-20% a BAGE de valorile herniei hiatale și de contrastul Asia versus Occident.',
 ['1-2% nu este prevalența citată; textul o descrie ca afecțiune frecventă.','5% nu figurează ca prevalență a BAGE.','Textul indică prevalența de 10-20% în țările dezvoltate, mai mare în Occident decât în Asia.','30% este ponderea herniei prin alunecare la peste 50 de ani, nu prevalența BAGE.','70% este asocierea herniei hiatale cu esofagita erozivă din figura de pe pagina următoare, nu prevalența BAGE.']],
 8,'Permutează prevalența BAGE cu procente reale ale herniei hiatale din același capitol.',['10-20%','pirozisul']),

q(14,['Mecanismele care permit refluxul acid în BAGE includ:',
 ['Relaxarea tranzitorie a SEI (ATSEI) apare mai frecvent la pacienții cu BAGE și este cauza principală a refluxului la circa două treimi dintre aceștia','Buzunarul acid de la nivelul stomacului proximal, netamponat postprandial, servește ca rezervor de refluat, în special în hernia hiatală în clinostatism, și poate fi tratat cu antiacide-alginat','Cauza principală izolată este întârzierea evacuării gastrice, SEI rămânând contractat între mese','Contracția diafragmului crural la nivelul SEI crește refluxul, în loc să-l împiedice','Bicarbonatul salivar prelungește contactul acidului cu mucoasa esofagiană distală'],'AB',1162,'Faringele și esofagul — BAGE: fiziopatologie (ATSEI și buzunarul acid)',
 'Corelarea ATSEI ca mecanism dominant (circa 2/3) cu buzunarul acid proximal tratabil prin alginat.',
 ['ATSEI mai frecventă în BAGE, cauză principală la aproximativ două treimi, este explicită.','Buzunarul acid proximal și tratamentul antiacide-alginat sunt descrise.','Evacuarea gastrică întârziată nu este cauza principală citată; SEI se relaxează tranzitoriu între mese.','Diafragmul crural acționează ca piedică împotriva refluxului, nu ca facilitator.','Bicarbonatul salivar neutralizează refluatul, alături de peristaltismul secundar și gravitație.']],
 8,'Inversează rolul barierelor antireflux (crura, saliva) și înlocuiește ATSEI cu o cauză de evacuare, pe fondul buzunarului acid ușor de omis.',['buzunarului acid','două treimi din pacienţii']),

q(15,['Hernia hiatală și durerea toracică de reflux:',
 ['Hernia prin alunecare plasează joncțiunea esofago-gastrică și o parte a stomacului deasupra diafragmului; este prezentă la 30% dintre persoanele peste 50 de ani, iar simptomele țin de reflux, nu de hernie în sine','În hernia para-esofagiană, SEI rămâne competent sub diafragm; ocazional apar dureri intense prin volvulus sau strangulare','Circa 20% dintre cazurile care se prezintă în urgență cu durere toracică au BAGE','Hernia prin alunecare produce prin ea însăși esofagită severă, independent de reflux','Pneumonia de aspirație este obișnuită în BAGE, chiar fără obstacol asociat'],'ABC',1163,'Faringele și esofagul — Hernia hiatală (Cadranul 32.12) și diagnosticul diferențial al durerii',
 'Contrastarea herniei prin alunecare (frecventă, asimptomatică) cu cea para-esofagiană (SEI competent, risc de volvulus) și a ponderii de 20% a BAGE în durerea de urgență.',
 ['Definiția, prevalența de 30% peste 50 de ani și originea simptomelor în reflux sunt explicite.','SEI competent sub diafragm și complicațiile de volvulus/strangulare sunt citate.','20% din durerile de urgență atribuite BAGE sunt pe pagina anterioară, cu Cadranul 32.13 pe aceasta.','Simptomele herniei prin alunecare țin de reflux, nu de hernie ca atare.','Pneumonia de aspirație este neobișnuită fără cauză obstructivă asociată.']],
 8,'Transformă hernia prin alunecare într-o cauză autonomă de esofagită și face din aspirație regula, pe fondul a două anatomii ușor de inversat.',['30% dintre persoanele','para-esofagiană'],[1162]),

q(16,['Tratamentul medicamentos inițial al BAGE, conform textului:',
 ['Aproximativ jumătate dintre pacienții care se adresează medicului de familie pot fi tratați cu antiacide simple, scădere ponderală și ridicarea capului patului','Preparatele cu alginat (10 ml de trei ori pe zi) formează un gel sau o „plută de spumă" cu conținutul gastric','Antiacidele cu magneziu tendințial constipă, iar cele cu aluminiu produc diaree','Circa 60% dintre pacienții cu BAGE devin asimptomatici după 4 săptămâni de IPP o dată pe zi','Formele severe pot necesita IPP de două ori pe zi, ani de zile; osteoporoza și infecțiile cu C. difficile sunt puțin frecvente și tind să apară la pacienții cu risc'],'ABDE',1163,'Faringele și esofagul — BAGE: măsuri generale, alginat și IPP',
 'Reținerea succesului măsurilor de primă linie, a dozei de alginat și a răspunsului de 60% la 4 săptămâni de IPP, cu profilul real de efecte adverse.',
 ['Succesul la jumătate dintre pacienții de familie cu măsuri simple este explicit.','Doza de 10 ml de trei ori pe zi și pluta de spumă sunt citate.','Textul inversează: magneziul tinde să provoace diaree, aluminiul constipație.','Răspunsul de circa 60% la 4 săptămâni de IPP o dată pe zi este explicit.','Necesitatea IPP bid pe termen lung și caracterul puțin frecvent al osteoporozei/C. difficile la cei cu risc sunt descrise.']],
 8,'Inversează efectele intestinale ale cationilor din antiacide, pe fondul dozei de alginat și al procentului de 60% ușor de mutat la 4 săptămâni.',['10 ml de trei ori','60% dintre aceştia']),

q(17,['Clasificarea Los Angeles a esofagitei și BAGE non-erozivă:',
 ['Gradul A înseamnă eroziuni confluente pe peste 75% din circumferința esofagului','Gradul B: cel puțin o discontinuitate mucoasă mai lungă de 5 mm, limitată la pliuri, fără continuitate între vârfurile a două pliuri','Pacienții fără răspuns satisfăcător la IPP și cu endoscopie normală sunt încadrați ca NERD; de obicei femei, simptome adesea funcționale sau esofag hipersensibil','Antagoniștii H2 pot fi folosiți în combinație cu IPP în formele mai severe','Gastroplicatura endoluminală produce o îmbunătățire de durată obiectivată prin pH-metrie esofagiană'],'BCD',1164,'Faringele și esofagul — Clasificarea Los Angeles, NERD și tratamente adjuvante',
 'Atribuirea corectă a gradelor A–D și recunoașterea NERD ca entitate cu endoscopie normală, distinctă de succesul pH-metric al gastroplicaturii.',
 ['Peste 75% din circumferință definește gradul D, nu A.','Definiția gradului B este explicită în legendă.','Încadrarea NERD, predominanța feminină și esofagul hipersensibil sunt citate.','Combinarea H2 cu IPP în forme mai severe este menționată.','Studiile arată beneficiu clinic, dar nu îmbunătățire de durată a pH-ului esofagian.']],
 8,'Atribuie criteriul de 75% gradului A în loc de D și pretinde un câștig pH-metric pe care textul îl neagă gastroplicaturii.',['Grad B','non-erozivă']),

q(18,['În clasificarea Los Angeles, eroziunile confluente care interesează peste 75% din circumferința esofagului definesc:',
 ['Gradul A','Gradul B','Gradul C','Gradul D','Esofagul Barrett circumferețial'],'D',1164,'Faringele și esofagul — Clasificarea endoscopică Los Angeles a esofagitei',
 'Reținerea pragului de 75% ca prag al gradului D, distinct de limitele în milimetri ale gradelor A și B.',
 ['Gradul A: discontinuități limitate la pliuri, care nu depășesc 5 mm.','Gradul B: cel puțin o eroziune >5 mm, fără continuitate între pliuri.','Gradul C: eroziuni între vârfurile pliurilor, dar nu circumferențiale.','Textul definește gradul D prin eroziuni confluente pe peste 75% din circumferință.','Barrett-ul este metaplazie columnară, nu un grad Los Angeles.']],
 8,'Cele patru grade Los Angeles diferă prin praguri ușor de permutat (5 mm versus 75%).',['peste 75%','Los Angeles']),

q(19,['Strictura peptică ca o complicație a BAGE:',
 ['A devenit mult mai puțin frecventă de la apariția IPP; survine de obicei peste 60 de ani, cu disfagie intermitentă pentru solide, care se agravează treptat','Cazurile ușoare pot răspunde numai la IPP; cele severe necesită dilatare endoscopică și IPP pe termen lung; chirurgia, dacă tratamentul medical eșuează','Este tipică tânărului cu obstrucție completă acută pentru lichide','Chirurgia este de primă intenție, înaintea oricărei dilatări','Se asociază aproape constant cu esofagul Barrett, screeningul fiind astfel impus tuturor simptomaticilor'],'AB',1165,'Faringele și esofagul — Complicațiile BAGE: strictura peptică',
 'Recunoașterea profilului vârstnicului cu disfagie intermitentă pentru solide și a ierarhiei IPP → dilatare → chirurgie.',
 ['Reducerea frecvenței după IPP, vârsta peste 60 de ani și disfagia intermitentă pentru solide sunt explicite.','Secvența IPP, dilatare plus IPP, apoi chirurgie la eșec, este citată.','Nu este descrisă ca obstrucție acută la tineri pentru lichide.','Chirurgia este rezervată eșecului medical, nu primei intenții.','Asocierea „aproape întotdeauna" din text privește hernia hiatală în Barrett, nu strictura; screeningul Barrett nu este recomandat.']],
 8,'Mută strictura peptică la tânărul cu obstrucție acută și inversează locul chirurgiei față de dilatarea endoscopică.',['Strictura peptică','disfagie intermitentă']),

q(20,['Esofagul Barrett — diagnostic, clasificare și risc:',
 ['Clasificarea Praga înregistrează lungimea circumferențială (C) și lungimea maximă (M) a mucoasei columnare','Obezitatea abdominală crește riscul de esofag Barrett de 4,3 ori','Variantele cu segment lung (>3 cm) și scurt (<3 cm) se regăsesc la 5%, respectiv 15% dintre pacienții endoscopiați pentru simptome de reflux','Screeningul endoscopic este recomandat tuturor pacienților cu pirozis, corelația simptom–Barrett fiind strânsă','Este adesea diagnosticat incidental; cel mai frecvent la bărbații obezi de vârstă mijlocie'],'ABCE',1165,'Faringele și esofagul — Esofagul Barrett: Praga, epidemiologie și screening',
 'Aplicarea măsurătorilor C/M, a riscului 4,3× prin obezitate abdominală și a prevalențelor 5%/15%, față de absența screeningului populațional.',
 ['Măsurătorile C și M ale clasificării Praga sunt explicite.','Creșterea de 4,3 ori prin obezitate abdominală este citată.','Prevalențele 5% (lung) și 15% (scurt) la endoscopia pentru reflux sunt din text.','Corelația simptom–Barrett este slabă; screeningul nu este recomandat.','Diagnosticul incidental și profilul bărbatului obez de vârstă mijlocie sunt descrise.']],
 8,'Inversează recomandarea de screening pe care textul o neagă, pe fondul unor procente (4,3×, 5%, 15%) ușor de alocat greșit riscului de cancer.',['4,3 ori','Obezitatea abdominală']),

q(21,['Supravegherea și terapia endoscopică în esofagul Barrett:',
 ['La displazie de grad scăzut, endoscopia se repetă de obicei la 6 luni, cu biopsii în cadran la fiecare 1 cm, sub IPP în doză mare','Dacă displazia de grad scăzut persistă, se propune ablație endoscopică sau monitorizare la 6 luni','Displazia de grad înalt pe leziune nodulară se îndepărtează prin rezecție endoscopică mucosală; fără leziune vizibilă, IPP în doze mari și biopsii nu mai târziu de 3 luni','Terapia fotodinamică a înlocuit ablația prin radiofrecvență ca tehnică de elecție','Ecoendoscopia este frecvent folosită pentru stadializare, pentru a exclude cancerul și limfadenopatia semnificativă'],'ABCE',1166,'Faringele și esofagul — Barrett: supraveghere, EMR și RFA',
 'Ierarhizarea intervalelor 6 luni (LGD) versus 3 luni (HGD fără leziune) și recunoașterea RFA ca înlocuitor al terapiei fotodinamice.',
 ['Protocolul de 6 luni cu biopsii la 1 cm și IPP în doză mare este explicit.','Ablația sau supravegherea la 6 luni, dacă LGD persistă, este recomandarea ghidurilor recente din text.','EMR pentru nodul și rebiopsia la cel mult 3 luni fără leziune vizibilă sunt citate.','Textul indică opusul: RFA a înlocuit terapia fotodinamică.','Rolul ecoendoscopiei de stadializare este menționat.']],
 8,'Inversează ierarhia RFA versus terapie fotodinamică și cere reținerea a două intervale (6 luni versus 3 luni) din același algoritm.',['Ablaţia prin radiofrecvenţă','6 luni']),

q(22,['Tabloul clinic al acalaziei, conform textului:',
 ['Incidența este 1:100.000, egală la bărbați și femei; apare la orice vârstă, dar rareori în copilărie','Pacienții au de obicei un lung istoric de disfagie intermitentă, caracteristic atât pentru lichide, cât și pentru solide, de la debut','Scăderea ponderală este de obicei importantă, definitorie pentru diagnostic','Regurgitațiile din esofagul dilatat, mai ales noaptea, pot determina pneumonie de aspirație','Durerea toracică spontană lipsește, ceea ce o diferențiază de ischemia cardiacă'],'ABD',1166,'Faringele și esofagul — Acalazia: tablou clinic',
 'Recunoașterea disfagiei pentru lichide și solide de la debut, a incidenței 1:100.000 și a regurgitațiilor nocturne, cu scădere ponderală minimă.',
 ['Incidența 1:100.000, egalitatea pe sexe și raritatea în copilărie sunt explicite.','Disfagia intermitentă pentru lichide și solide de la debut este caracteristică.','Textul precizează că scăderea ponderală este de obicei minimă.','Regurgitațiile nocturne și pneumonia de aspirație sunt citate.','Durerea toracică spontană prin „spasm" poate fi eronat luată drept cardiacă.']],
 8,'Inversează magnitudinea scăderii ponderale și neagă durerea toracică, două capcane față de cancerul esofagian și ischemia cardiacă.',['1:100.000','disfagie intermitentă']),

q(23,['Incidența acalaziei, egală la bărbați și femei, este de:',
 ['1:100.000','1:1.000','1:10.000','10-20%','1:100'],'A',1166,'Faringele și esofagul — Acalazia: epidemiologie',
 'Diferențierea incidenței 1:100.000 a acalaziei de prevalența BAGE și de alte rate din capitol.',
 ['Textul citează 1:100.000, egală pentru bărbați și femei.','1:1.000 este ordinul transmiterii verticale HIV din alt capitol, nu acalazia.','1:10.000 nu este cifra din text.','10-20% este prevalența BAGE, nu incidența acalaziei.','1:100 ar fi o boală comună, incompatibilă cu descrierea.']],
 8,'Toate ordinele de mărime apar ca procente sau rate în gastroenterologie; doar 1:100.000 este al acalaziei.',['1:100.000','egală pentru bărbaţi']),

q(24,['Patogenia infecției cu Helicobacter pylori include:',
 ['Ureaza convertește ureea în amoniu și clorură, cu efect citotoxic direct','Ulcerele sunt cel mai frecvente când tulpina exprimă CagA și VacA, cu sinteză mai pronunțată de IL-8','Polimorfismele gazdei care cresc IL-1β se asociază cu gastrită atrofică și cancer','H. pylori colonizează numai epiteliul duodenal, nu pe cel gastric','Majoritatea infectaților dezvoltă ulcer duodenal'],'ABC',1173,'Stomacul și duodenul — H. pylori: patogeneză',
 'Corelarea ureazei citotoxice cu virulența CagA/VacA/IL-8 și cu genetica gazdei, față de colonizarea strict gastrică și riscul de doar 15% de UD.',
 ['Conversia ureei în amoniu și clorură este explicită.','Asocierea CagA/VacA cu IL-8 și ulcere este citată.','Polimorfismele IL-1β, gastrita atrofică și cancerul sunt menționate.','Textul precizează colonizarea exclusivă a epiteliului gastric.','Doar 15% dintre infectați dezvoltă ulcere duodenale.']],
 8,'Mută tropismul de pe epiteliul gastric pe duoden și transformă o minoritate (15%) în majoritate.',['CagA','VacA']),

q(25,['Boala ulceroasă peptică — epidemiologie și tablou clinic:',
 ['UD afectează circa 10% din populația adultă și sunt de 2-3 ori mai frecvente decât UG','UD se găsesc cel mai frecvent în prima porțiune a duodenului; UG, pe mica curbură lângă unghiul gastric','Durerea nocturnă din UD este un argument de încredere pentru diagnosticul diferențial față de UG','Indicatul cu un singur deget spre epigastru este puternic sugestiv pentru boala ulceroasă peptică','Netratate, simptomele UD recidivează și remite ulterior, odată cu gastrita atrofică și scăderea acidului'],'ABDE',1173,'Stomacul și duodenul — Boala ulceroasă peptică: epidemiologie și clinică',
 'Cuantificarea UD (10%, 2–3× UG) și recunoașterea valorii semnelor (un deget) versus lipsa de încredere a durerii nocturne.',
 ['Prevalența de circa 10% și raportul 2-3:1 față de UG sunt explicite.','Topografia UD (D1) și UG (mica curbură) este citată.','Textul precizează că durerea nocturnă nu este un argument de încredere.','Semnul unui singur deget este descris ca puternic sugestiv.','Istoria naturală cu remisie tardivă prin gastrită atrofică este menționată.']],
 8,'Transformă durerea nocturnă — explicit nefiabilă — în discriminator clasic, pe fondul procentelor 10% și 2–3×.',['10% din populaţia','2-3 ori']),

q(26,['În investigarea infecției cu H. pylori și a ulcerului gastric:',
 ['Cultura din biopsie este testul de primă linie la toți pacienții, înaintea testului ureazic','Culturile, cu testare de sensibilitate, se folosesc de obicei în infecția refractară la eradicarea standard, nu de rutină','Sensibilitatea histopatologiei este mai puternic influențată de IPP decât a testului ureazic','Pacienții sub 55 de ani cu semne de alarmă pot evita endoscopia dacă antigenul fecal este pozitiv','Toate ulcerele gastrice trebuie biopsiate pentru a exclude un proces malign și reevaluate endoscopic pentru vindecare'],'BE',1174,'Stomacul și duodenul — Culturi, ulcere gastrice și semne de alarmă',
 'Delimitarea culturii ca metodă de salvare, nu de screening, și a biopsiei obligatorii a oricărui ulcer gastric.',
 ['Cultura nu este test de primă linie; CLO, histologia și testele neinvazive preced.','Textul rezervă cultura pacienților refractari, pentru alegerea antibioticului.','Textul indică opusul: histologia este mai puțin influențată de IPP decât testul ureazic.','Semnele de alarmă impun endoscopie, indiferent de vârstă.','Biopsia tuturor UG și reevaluarea vindecării sunt explicite.']],
 8,'Ridică cultura la rang de screening și anulează biopsia UG, două reguli de laborator versus endoscopie ușor de inversat.',['Realizarea de culturi','Toate ulcerele gastrice']),

q(27,['Selectați enunțurile adevărate despre investigarea pacientului cu suspiciune de ulcer peptic:',
 ['Sub 55 de ani, cu simptome tipice și H. pylori pozitiv, se poate începe eradicarea fără alte investigații','Pacienții mai în vârstă necesită diagnostic endoscopic și excluderea unui posibil cancer','Toți cei cu semne de alarmă (anemie feriprivă, scădere ponderală involuntară, anorexie, hematemeză sau melenă, vărsături persistente, masă epigastrică) necesită evaluare endoscopică','Strategia „testează și tratează" sub 55 de ani se aplică în absența semnelor de alarmă, inclusiv pierdere în greutate, anemie, disfagie, vărsături sau istoric familial de cancer digestiv','Examenul obiectiv este, de obicei, diagnostic pentru ulcerul activ'],'ABCD',1174,'Stomacul și duodenul — Algoritmul de investigare a ulcerului peptic',
 'Aplicarea pragului de 55 de ani și a listei de alarmă care impune endoscopie, față de examenul obiectiv nefolositor.',
 ['Strategia fără investigații suplimentare sub 55 de ani, H. pylori pozitiv, simptome tipice, este explicită.','Necesitatea endoscopiei la vârstnici este citată.','Lista semnelor de alarmă este reprodusă din text.','„Testează și tratează" sub 55 de ani, fără alarmă, este descrisă.','Textul precizează că examenul obiectiv este de obicei nefolositor.']],
 8,'Ridică palparea la rang diagnostic și cere reținerea simultană a pragului de 55 de ani și a listei complete de alarmă.',['sub 55 de ani','anemie feriprivă']),

q(28,['La scintigrafia de evacuare gastrică, conținutul rezidual după 4 ore este considerat patologic dacă depășește:',
 ['1%','5%','10%','25%','50%'],'C',1176,'Stomacul și duodenul — Gastropareza: diagnostic scintigrafic',
 'Reținerea pragului de 10% rezidual la 4 ore, distinct de alte procente din aceeași pagină (30%, 50%, 70%).',
 ['1% nu este pragul citat.','5% nu figurează ca prag scintigrafic.','Textul consideră patologică o valoare de peste 10% după 4 ore.','25% este categoria tulburărilor de defecație din alt segment, nu gastropareza.','50% este ponderea leziunilor mucoase la consumatorii de AINS, nu pragul scintigrafic.']],
 8,'Toate procentele apar pe pagina gastroparezei și AINS; doar >10% la 4 ore definește evacuarea întârziată.',['peste 10%','4 ore']),

q(29,['Perforația ulcerului peptic:',
 ['Frecvența este în scădere, parțial datorită eficienței terapiei medicale','UG perforează mai frecvent decât UD, de obicei în retroperitoneu','UD perforează mai frecvent decât UG, de obicei în cavitatea peritoneală; este posibilă și perforația în bursa omentală','Tratamentul conservator (sondă nazogastrică, fluide i.v., antibiotice) nu se folosește, indiferent de teren','Laparotomia deschisă este aleasă de regulă în locul abordului laparoscopic'],'AC',1175,'Stomacul și duodenul — Complicații: perforația',
 'Recunoașterea predominanței perforației UD în peritoneu și a locului chirurgiei laparoscopice, cu rezerva tratamentului conservator la vârstnici tarați.',
 ['Scăderea frecvenței sub terapia medicală este explicită.','Textul indică opusul: UD perforează mai frecvent decât UG.','Predominanța UD, peritoneul și bursa omentală sunt citate.','Tratamentul conservator este folosit ocazional la vârstnici și tarați.','Chirurgia laparoscopică este de obicei aleasă pentru închidere și drenaj.']],
 8,'Inversează care ulcer perforează mai des și înlocuiește laparoscopia cu laparotomia ca regulă.',['UD perforează mai frecvent','Chirurgia laparoscopică']),

q(30,['Insuficiența evacuatorie gastrică din boala ulceroasă:',
 ['Vărsătura, de obicei fără durere, este în jet, cu volum crescut și resturi din prânzuri anterioare','La examen poate fi obiectivat clapotajul a jeun','Vărsăturile severe persistente produc alcaloză metabolică hipokaliemică','Doar circa 30% dintre pacienți pot fi tratați fără intervenție chirurgicală','Vărsăturile se remit adesea sub reechilibrare, drenaj nazogastric și terapie antisecretorie energică; dilatarea endoscopică sau stentul pot fi utile'],'ABCE',1175,'Stomacul și duodenul — Obstrucția orificiului de evacuare',
 'Recunoașterea alcalozei hipokaliemice și a ratei de 70% de succes non-operator, pe fondul clapotajului a jeun.',
 ['Caracterele vărsăturii (fără durere, jet, resturi vechi) sunt explicite.','Clapotajul a jeun este citat.','Alcaloza metabolică hipokaliemică este consecința pierderii de acid.','Textul indică 70%, nu 30%, tratați fără chirurgie.','Remisia sub măsuri medicale și rolul dilatării/stentului sunt descrise.']],
 8,'Înlocuiește 70% non-operator cu 30%, pragul simptomatic al leziunilor AINS de pe pagina alăturată.',['70% dintre pacienţi','clapotajul a jeun']),

q(31,['Consecințele chirurgiei gastrice și asocierile H. pylori:',
 ['Sindromul dumping: greață, distensie, transpirații, leșin, palpitații după gastrectomie parțială cu gastro-jejunoanastomoza, prin evacuare jejunală rapidă și scăderea volumului circulant; poate apărea și hipoglicemie','Pe termen lung: carență de fier, deficit de folat, carență de B12 prin factor intrinsc redus, scădere ponderală prin aport redus','Peste 70% dintre limfoamele gastrice MALT cu celule B au infecție cu H. pylori','Dumping-ul este tipic după vagotomia gastrică proximală fără anastomoză','Incidența adenocarcinomului gastric distal este independentă de prevalența H. pylori'],'ABC',1176,'Stomacul și duodenul — Dumping, carențe nutriționale și MALT',
 'Corelarea dumping-ului cu gastrectomia/anastomoza, a carențelor postgastrectomie și a asocierii de peste 70% H. pylori–MALT.',
 ['Mecanismul dumping-ului după gastrectomie parțială cu anastomoză este explicit.','Cele patru consecințe nutriționale sunt enumerate.','Asocierea de peste 70% H. pylori–MALT este citată.','Dumping-ul este descris după gastrectomie parțială și gastro-jejunoanastomoză, nu după vagotomia proximală.','Incidența cancerului gastric distal este direct proporțională cu cea a H. pylori.']],
 8,'Atribuie dumping-ul vagotomiei proximale și rupe legătura H. pylori–cancer distal, pe fondul procentului MALT de 70%.',['Sindromul dumping','Peste 70%']),

q(32,['Leziunile gastroduodenale induse de AINS, la evaluare endoscopică:',
 ['Circa 50% dintre consumatorii regulați dezvoltă leziuni ale mucoasei gastrice, iar circa 30% prezintă ulcere','Doar circa 5% au simptome, iar 1-2% dezvoltă o complicație majoră (hemoragie sau perforație)','Inhibitorii COX-2 sunt lipsiți de risc cardiovascular, de aceea înlocuiesc orice AINS','H. pylori și AINS sunt factori antagonici, nu synergici','Misoprostolul este mai bine tolerat decât IPP, fără diaree'],'AB',1176,'Stomacul și duodenul — AINS: frecvența leziunilor și a complicațiilor',
 'Cuantificarea cascadei 50% leziuni / 30% ulcere / 5% simptome / 1-2% complicații, distinct de restricția cardiovasculară a COX-2.',
 ['Procentele 50% și 30% sunt explicite.','5% simptomatici și 1-2% complicații majore sunt citate.','Utilizarea COX-2 este limitată de riscul cardiovascular.','H. pylori și AINS sunt factori independenți și sinergici.','IPP sunt mai bine tolerate decât misoprostolul, care provoacă diaree.']],
 8,'Permutează treptele procentuale și anulează restricția cardiovasculară a COX-2, deja folosită într-o vignette din banca existentă, dar aici ca epidemiologie numerică.',['50% dintre pacienţii','30% vor']),

q(33,['Epidemiologia bolilor inflamatorii intestinale:',
 ['Incidența bolii Crohn este circa 4-10/100.000 anual, cu prevalență 25-100/100.000','Incidența colitei ulcerative este stabilă la 6-15/100.000 anual, cu prevalență 80-150/100.000','În jumătate din colitele din spectrul BII nu se poate distinge Crohn de CU','În 10% dintre colitele din spectrul BII diagnosticul rămâne de colită nedeterminată','Circa 25% sunt diagnosticați înainte de 18 ani; debutul tânăr este mai extins și mai agresiv'],'ABDE',1198,'Bolile inflamatorii intestinale — Epidemiologie',
 'Reținerea perechilor incidență/prevalență Crohn versus CU și a ponderilor 10% nedeterminat și 25% pediatric.',
 ['Intervalul 4-10/100.000 și prevalența 25-100 sunt explicite.','6-15/100.000 și 80-150 sunt cifrele CU.','Ponderea nedeterminată este 10%, nu jumătate.','10% colită nedeterminată este citat.','25% înainte de 18 ani și agresivitatea debutului tânăr sunt descrise.']],
 8,'Înlocuiește 10% colită nedeterminată cu 50% și cere atribuirea corectă a patru intervale numerice din același paragraf.',['4-10/100.000','6-15/100.000']),

q(34,['Microbiota intestinală în boala Crohn:',
 ['Diversitatea speciilor microbiene este crescută la pacienții cu BII','Concentrații mai mari de Bacteroides și E. coli și mai mici de bifidobacterii și Faecalibacterium prausnitzii sunt raportate în BC','Niveluri scăzute de F. prausnitzii în specimenele rezecate prezic recăderea endoscopică','PCR-ul a confirmat legătura cu Mycobacterium paratuberculosis, iar trialurile anti-TB au fost eficiente','Microbiota comensală nu are rol imunoregulator în modelele animale de colită'],'BC',1199,'Bolile inflamatorii intestinale — Disbioză și Faecalibacterium prausnitzii',
 'Recunoașterea disbiozei (diversitate redusă, F. prausnitzii scăzut ca predictor de recădere) față de eșecul pistei MAP.',
 ['Constatarea cea mai frecventă este diversitatea redusă, nu crescută.','Profilul Bacteroides/E. coli crescut și bifidobacterii/F. prausnitzii scăzut este explicit.','Valoarea predictivă a F. prausnitzii scăzut pe piesa de rezecție este citată.','PCR nu a confirmat MAP, iar trialurile anti-TB nu au fost eficiente.','Textul atribuie microbiotei comensale un rol imunoregulator protector în modele animale.']],
 8,'Inversează direcția diversității microbiene și reînvie pista MAP infirmată de PCR și de trialuri.',['Faecalibacterium prausnitzii','diversitatea redusă']),

q(35,['Anatomia patologică macroscopică a BII:',
 ['BC are tendință particulară pentru ileonul terminal și colonul ascendent; poate fi discontinuă (skip lesions)','Ulcerele profunde și fisurile produc aspect de „piatră de pavaj"; fistulele și abcesele reflectă caracterul penetrant','CU poate fi proctită, colită stângă sau extensivă; unii au și ileită de reflux','În CU inflamația este transmurală, iar în BC este limitată la mucoasă','Un semn precoce în BC este ulcerația aftoidă colonoscopică'],'ABCE',1200,'Bolile inflamatorii intestinale — Distribuție, skip lesions și piatră de pavaj',
 'Contrastarea distribuției discontinue Crohn cu extinderea continuă CU și recunoașterea pietrei de pavaj ca marcă penetrantă.',
 ['Predilecția ileocolonică și skip lesions sunt explicite.','Piatra de pavaj și caracterul penetrant sunt citate.','Cele trei extensii CU și ileita de reflux sunt descrise.','Textul inversează: BC transmurală, CU limitată la mucoasă.','Ulcerația aftoidă ca semn precoce este menționată.']],
 8,'Inversează adâncimea inflamației (transmural versus mucos), singura confuzie care face restul listei macroscopice să pară coerentă.',['skip lesions','piatră de pavaj']),

q(36,['Artropatiile periferice din BII:',
 ['Tipul 1 (pauciarticular): atacuri acute auto-limitate sub 10 săptămâni, odată cu recăderile BII, asociate altor manifestări extraintestinale','Tipul 2 (poliarticular): durează luni până la ani, independent de activitatea BII, de regulă asociat cu uveita','HLA-B27 se asociază cu sacroiliita','Tipul 1 evoluează independent de activitatea intestinală','Complicațiile articulare sunt cele mai rare manifestări extraintestinale'],'ABC',1201,'Bolile inflamatorii intestinale — Manifestări extra-intestinale: artropatia tip 1 versus tip 2',
 'Diferențierea artropatiei pauciarticulare legate de puseu de cea poliarticulară independentă, cu uveită, și a asocierii HLA-B27–sacroiliită.',
 ['Definiția tipului 1, inclusiv fereastra sub 10 săptămâni, este explicită.','Durata lungă, independența de BII și uveita tipului 2 sunt citate.','Asocierea HLA-B27 cu sacroiliita este menționată.','Independența de activitatea intestinală caracterizează tipul 2, nu tipul 1.','Complicațiile articulare sunt cele mai comune, nu cele mai rare.']],
 8,'Schimbă între ele relația cu activitatea intestinală a celor două tipuri de artropatie.',['Tipul 1 (pauciarticular)','Tipul 2 (poliarticular)']),

q(37,['Tabloul clinic al bolii Crohn:',
 ['Simptomele majore sunt diareea, durerea abdominală și pierderea în greutate','Aproximativ 50% vor necesita rezecție intestinală în primii 5 ani de la diagnostic','La 15% simptomele gastrointestinale pot lipsi','Diareea apare în 80% din cazuri; în boala colonică conține de obicei sânge','Fistulele enterice (vezică, vagin, perete abdominal) apar la sub 5% dintre pacienți'],'ABCD',1202,'Bolile inflamatorii intestinale — Boala Crohn: clinică și complicații fistulizante',
 'Cuantificarea diareei (80%), a rezecției la 5 ani (50%), a absenței simptomelor GI (15%) și a fistulelor (20-40%), față de subestimarea fistulelor.',
 ['Triada diaree–durere–scădere ponderală este explicită.','50% rezecție în 5 ani este citat.','15% fără simptome GI este menționat.','80% diaree, adesea sangvinolentă în forma colonică, este din text.','Fistulele enterice apar în 20-40% din cazuri, nu sub 5%.']],
 8,'Subestimează fistulele (20-40%) la sub 5% și cere reținerea simultană a trei procente din același tablou.',['Diareea apare în 80%','50% dintre pacienţi']),

q(38,['Nutriția enterală exclusivă în boala Crohn:',
 ['Ca unică sursă de nutriție timp de 28 de zile, ratele de inducție a remisiei sunt similare celor obținute cu steroizi','Este subutilizată la adulți din cauza complianței; ratele de recidivă sunt mari, în particular la afectarea colonică','Este tratamentul de primă linie la adultul cu BC colonică, înaintea oricărui steroid','Aminosalicilații au dovezi solide de inducție a remisiei în BC','Steroizii sunt preferați în boala penetrantă intestinală și în sepsisul perianal'],'AB',1203,'Bolile inflamatorii intestinale — Nutriție enterală exclusivă',
 'Recunoașterea echivalenței EEN–steroizi la 28 de zile și a limitei (recidivă colonică, complianță adult).',
 ['Echivalența la 28 de zile cu steroizii este explicită.','Subutilizarea la adulți și recidiva colonică sunt citate.','La adulți EEN este subutilizată, nu prima linie colonică.','Textul găsește foarte puține dovezi pentru aminosalicilați în BC.','Steroizii trebuie evitați în boala penetrantă și sepsisul perianal.']],
 8,'Transformă o opțiune pediatrică/de complianță dificilă în prima linie a adultului colonic și reintroduce steroizii în sepsisul perianal.',['28 de zile','Nutriţie enterală exclusivă']),

q(39,['Terapiile biologice noi în boala Crohn, după eșecul anti-TNF:',
 ['Vedolizumab (anti-α4β7) reduce recrutarea leucocitară în intestinul inflamat','Se folosește în BC moderat-severă activă la intoleranță, contraindicație, răspuns incomplet sau pierderea răspunsului la anti-TNF','Ustekinumab (anti-IL-12/IL-23) se folosește în aceeași populație de eșec/intoleranță anti-TNF','Mongersen (oligonucleotid antisense SMAD7) este prima linie, înaintea steroizilor','Risankizumab țintește subunitatea p40 comună IL-12/IL-23, identic ustekinumabului'],'ABC',1204,'Bolile inflamatorii intestinale — Vedolizumab, ustekinumab și molecule în studiu',
 'Poziționarea vedolizumabului și ustekinumabului după anti-TNF, distinct de agenții încă în faza 3 (mongersen, risankizumab p19).',
 ['Mecanismul anti-α4β7 este explicit.','Indicația după eșecul/intoleranța anti-TNF este citată.','Ustekinumab IL-12/IL-23 în aceeași nișă este menționat.','Mongersen este în studii de fază 3, nu prima linie.','Risankizumab țintește p19 a IL-23, nu p40.']],
 8,'Ridică un agent de fază 3 la rang de primă linie și confundă țintele p19 versus p40 ale anti-IL-23.',['vedolizumab','ustekinumab']),

q(40,['Chirurgia în boala Crohn:',
 ['Studiile de dinaintea biologicelor arată că până la 80% vor necesita o intervenție pe parcursul bolii','Recurența este circa 15% pe an, aproape inevitabilă fără terapie profilactică de menținere','Se evită pe cât posibil; rezecțiile trebuie să fie limitate','Pacienții cu BC sunt candidați buni pentru rezervor ileal (pouch), recurența la acest nivel fiind rară','O cură de 3 luni cu metronidazol reduce recăderea; ileocolonoscopia anastomozei la 6 luni ghidează terapia ulterioară'],'ABCE',1205,'Bolile inflamatorii intestinale — Chirurgia BC: recurență și pouch',
 'Cuantificarea riscului istoric de 80% și a recurenței 15%/an, cu interdicția pouch-ului și fereastra metronidazol 3 luni plus control la 6 luni.',
 ['Până la 80% în era pre-biologică este explicit.','15% pe an fără menținere este citat.','Rezecțiile limitate și evitarea chirurgiei pe cât posibil sunt recomandate.','Textul precizează că pacienții cu BC nu se pretează pentru pouch, recurența fiind mare.','Metronidazolul 3 luni și ileocolonoscopia la 6 luni sunt descrise.']],
 8,'Face din BC indicație de pouch — opusul textului — pe fondul a două procente (80%, 15%/an) și a două intervale (3 luni, 6 luni).',['până la 80%','15% pe an'],[1204]),

q(41,['Megacolonul toxic din colita ulcerativă severă:',
 ['Radiografia abdominală pe gol arată un colon cu pereți subțiri, dilatat, diametru peste 6 cm, plin de gaze, cu pseudopolipi (insule mucoase)','Este un stadiu periculos, cu iminență de perforație și mortalitate 15-25%','Chirurgia de urgență este necesară dacă dilatarea toxică nu s-a remis în 48 de ore sub terapie intensivă','Pragul de diametru citat este 3 cm, ca la hematomul cerebelos','Mortalitatea este sub 1% dacă se continuă numai corticoterapia'],'ABC',1205,'Bolile inflamatorii intestinale — Megacolonul toxic',
 'Reținerea pragului de 6 cm, a mortalității 15-25% și a ferestrei de 48 de ore până la chirurgia de urgență.',
 ['Aspectul radiologic și pragul de 6 cm sunt explicite.','Iminența perforației și mortalitatea 15-25% sunt citate.','Fereastra de 48 de ore până la chirurgia de urgență este din text.','3 cm nu este pragul megacolonului.','Mortalitatea citată este 15-25%, nu sub 1%; continuarea steroizilor singuri întârzie colectomia.']],
 8,'Înlocuiește 6 cm și 48 de ore cu praguri din alte capitole (3 cm, 1%) și subestimează mortalitatea.',['mai mare de 6 cm','15-25%']),

q(42,['După proctocolectomie cu rezervor ileoanal pentru colita ulcerativă:',
 ['O treime dintre pacienți vor prezenta pouchită','Incidența pouchitei este de două ori mai mare la cei cu colangită sclerozantă primitivă și crescută la ANCA pozitivi cu ileită retrogradă prealabilă','Două treimi din cazurile de pouchită vor reapare, acut sau cronic','Prebioticul VSL #3 s-a dovedit eficient în prevenție și în menținerea remisiunii după antibiotice','Colectomia rămâne excepțională: sub 5% dintre pacienții cu CU în 20 de ani de la diagnostic'],'ABCD',1207,'Bolile inflamatorii intestinale — Pouchită, VSL #3 și prognosticul CU',
 'Cuantificarea pouchitei (1/3, dublu în PSC, 2/3 recurență) și a evoluției CU (1/3 episod unic, 1/3 colectomie/20 ani), plus rolul VSL #3.',
 ['O treime cu pouchită este explicită.','Dublarea în PSC și asocierea ANCA/ileită retrogradă sunt citate.','Recurența la două treimi este menționată.','Eficacitatea VSL #3 în prevenție și menținere este din text.','O treime dintre pacienții cu CU fac colectomie în 20 de ani, nu sub 5%.']],
 8,'Subestimează colectomia la 20 de ani (o treime versus sub 5%) și cere reținerea ponderilor pouchitei din același paragraf de prognostic.',['VSL #3','O treime dintre pacienţii']),
];
