import {advancedQuestion} from './advanced-author';
import type {SourceRow} from './source-author';
const pdfOffset=(p:number)=>p<=336?p-275:p-289;
const q=(n:number,row:SourceRow,score:number,reason:string,expressions:string[],related:number[]=[])=>
 advancedQuestion('hematologie',16,pdfOffset,`hematologie-adv-${String(n).padStart(3,'0')}`,row,[score,reason],expressions,undefined,related);

export const HEMATOLOGIE_ADVANCED=[
q(23,['O creștere a volumului plasmatic, ca în sarcină, produce, potrivit Figurii 16.6:',
 ['O hemoglobină fals crescută, similar deshidratării','O anemie falsă, chiar și atunci când este combinată cu o creștere mică a volumului de eritrocite','Policitemie aparentă, prin contracția plasmei','Scăderea volumului eritrocitar cu hemoglobină neschimbată','Creșterea hematocritului disproporționat față de hemoglobină'],'B',327,'Anemia: introducere — Figura 16.6',
 'Separarea anemiei de diluție din sarcină de hemoconcentrația deshidratării și de policitemia aparentă.',
 ['Hemoglobina fals crescută corespunde reducerii volumului plasmatic (deshidratare, policitemie aparentă), nu sarcinii.','Textul descrie anemia falsă din sarcină, posibilă chiar și cu o ușoară creștere a masei eritrocitare.','Policitemia aparentă ține de plasma redusă, nu de hipervolemia sarcinii.','În sarcină volumul eritrocitar poate fi ușor crescut, nu scăzut.','Figura plasează hemoglobina scăzută pe seama plasmei expandate, nu a unui hematocrit crescut.']],
 8,'Distractorii permută cele trei stări din Figura 16.6 (sarcină, deshidratare, policitemie aparentă) păstrând câte un element corect.',['anemie falsă','volumul plasmatic']),

q(24,['Compensarea și tabloul clinic al anemiei, în descrierea introductivă, includ:',
 ['O creștere a 2,3-BPG deplasează curba de disociere a oxigenului spre dreapta, astfel încât oxigenul este eliberat mai ușor în țesuturi','Simptomele sunt nespecifice: dispnee, astenie, fatigabilitate, cefalee, palpitații și lipotimie','Anemia agravează problemele cardiorespiratorii; angina sau claudicația intermitentă pot fi precipitate, mai ales la vârstnici','Un nivel ușor scăzut de hemoglobină nu permite nicio compensare hemodinamică','Deplasarea curbei de disociere spre stânga este mecanismul care facilitează cedarea oxigenului'],'ABC',327,'Anemia: introducere — Tablou clinic',
 'Integrarea deplasării drepte a curbei oxihemoglobinei cu simptomele nespecifice și cu precipitarea ischemiei la vârstnici.',
 ['Creșterea 2,3-BPG și deplasarea spre dreapta sunt mecanismul compensator citat.','Lista de simptome nespecifice este cea din paragraf.','Precipitarea anginei sau a claudicației la vârstnici este exemplul dat.','Textul precizează că un nivel ușor scăzut permite compensarea hemodinamică și îmbunătățirea cedării oxigenului.','Deplasarea care facilitează eliberarea este spre dreapta, nu spre stânga.']],
 8,'Distractorii inversează sensul deplasării curbei (stânga versus dreapta) și neagă compensarea pe care textul o descrie la anemii ușoare.',['2,3-BPG','spre dreapta']),

q(25,['Macrocitoza cu eritropoieză normoblastică, nu megaloblastică, se asociază în bibliografie cu:',
 ['Excesul de alcool, VEM-ul putând servi ca marker de monitorizare a consumului','Un număr crescut de reticulocite, care cresc VEM-ul datorită dimensiunii lor','Deficitul de cobalamină, cu megaloblaști medulari','Carența marțială microcitară, care ridică VEM-ul mediu','Măduvă megaloblastică, cu cromatină nucleară fin dispersată'],'AB',336,'Macrocitoza fără modificări megaloblastice',
 'Separarea cauzelor de macrocitoză normoblastică (alcool, reticulocite) de megaloblastoză și de microcitoză.',
 ['Alcoolul este o cauză frecventă de VEM crescut, utilă și ca marker de consum.','Reticulocitele, mai mari decât hematiile mature, cresc VEM-ul.','Deficitul de cobalamină produce megaloblastoză, nu simplă macrocitoză normoblastică.','Carența marțială scade VEM-ul, nu îl crește.','Megaloblastoza cu cromatină fină definește anemia megaloblastică, categoria din care aceste cauze sunt explicit separate.']],
 8,'Distractorii reintroduc cele două cauze megaloblastice/microcitare din care textul tocmai a scos această listă de macrocitoze normoblastice.',['excesul de alcool','număr crescut de reticulocite']),

q(26,['Tehnicile de obținere a măduvei osoase se diferențiază prin:',
 ['Aspiratul (ac Salah, de obicei creasta iliacă) oferă frotiuri pentru morfologie și probă lichidă pentru imunofenotipare, citogenetică sau cultură microbiologică','Colorația Perls (acid ferocianură) evidențiază fierul pe aspirat','Biopsia osteomedulară (ac Jamshidi, mai lung și mai gros) evaluează arhitectura, celularitatea și infiltratele; decalcifierea poate dura câteva zile','Biopsia este inferioară aspiratului pentru evaluarea celularității în anemia aplastică','Aspiratul nu poate fi folosit pentru investigații citogenetice sau markeri moleculari'],'ABC',328,'Cadranul 16.2 — Tehnici pentru a obține măduvă osoasă',
 'Asocierea acului (Salah versus Jamshidi) cu tipul de informație (citologie versus arhitectură) și cu timpul de decalcifiere.',
 ['Sediul, acul Salah și utilizările probei lichide sunt cele din cadran.','Perls cu acid ferocianură este colorația citată pentru fier pe aspirat.','Acul Jamshidi, decalcifierea de câteva zile și evaluarea arhitecturii caracterizează biopsia.','Cadranul indică biopsia ca evaluare superioară a celularității, de exemplu în aplazie.','Proba lichidă din aspirat este explicit utilizabilă pentru citogenetică și markeri moleculari.']],
 8,'Distractorii inversează superioritatea biopsiei în aplazie și neagă utilizările probei lichide enumerate în același cadran.',['ac special pentru aspirat','Jamshidi']),

q(27,['O cauză fiziologică frecventă de macrocitoză cu măduvă normoblastică este:',
 ['Deficitul de vitamină B12','Deficitul de folat','Sarcina','Anemia aplastică ca stare fiziologică de trimestrul III','Talasemia minoră'],'C',336,'Macrocitoza fără modificări megaloblastice',
 'Identificarea sarcinii (și a nou-născutului) ca macrocitoză fiziologică, distinctă de cauzele megaloblastice și hematologice patologice.',
 ['Deficitul de B12 produce megaloblastoză, nu macrocitoză fiziologică normoblastică.','Deficitul de folat este de asemenea o cauză megaloblastică.','Sarcina este numită cauză fiziologică frecventă; macrocitoza poate apărea și la nou-născut.','Anemia aplastică figurează între cauzele patologice, nu ca adaptare fiziologică de trimestrul III.','Talasemia produce microcitoză, nu macrocitoză.']],
 8,'Distractorii sunt cauze reale de anemie din același capitol, dar fie megaloblastice, fie microcitare, nu fiziologic normoblastice.',['cauză fiziologică frecventă','sarcina']),

q(28,['Anemia aplastică, în definiția și patogeneza din capitol, se caracterizează prin:',
 ['Pancitopenie cu hipocelularitate a măduvei, fără celule leucemice, canceroase sau alte celule anormale în sânge sau măduvă','Scăderea numărului de celule stem pluripotente, cu disfuncție a celor rămase sau cu o reacție imună îndreptată împotriva lor','Celule T citotoxice activate din sânge și măduvă, responsabile pentru insuficiența medulară în multe cazuri dobândite','Aplazia pură eritrocitară, care afectează simultan toate liniile hematopoietice','Imposibilitatea evoluției spre mielodisplazie, hemoglobinurie paroxistică nocturnă sau leucemie mieloidă acută'],'ABC',336,'Anemia datorată insuficienței medulare (anemia aplastică)',
 'Definirea aplaziei ca pancitopenie hipocelulară fără infiltrate și atribuirea ei celulelor T citotoxice, distinct de aplazia de linie unică.',
 ['Definiția prin pancitopenie hipocelulară, fără celule anormale, este cea de deschidere.','Mecanismul stem plus disfuncție sau reacție imună este enunțat explicit.','Rolul limfocitelor T citotoxice activate este precizat pentru cazurile dobândite.','Aplazia pură eritrocitară este insuficiența unei singure linii, nu a tuturor.','Textul menționează posibila evoluție spre mielodisplazie, HPN sau LMA.']],
 8,'Distractorii confundă aplazia de linie unică cu pancitopenia și neagă evoluția clonală pe care textul o admite.',['pancitopenie cu hipocelularitate','Celulele T citotoxice']),

q(29,['Anemia hemolitică autoimună „la cald" se caracterizează prin:',
 ['Clasificare a AHAI în forme „la cald" (65%), „la rece" (30%) și „mixte" (5%)','Răspuns la prednison 1 mg/kg zilnic, cu remisiune la 80% dintre pacienți','Origine primară în 50% din cazuri și secundară în 50%, cel mai des limfoproliferări','Predominanța anticorpilor IgM, complementul rămânând singurul detectat pe eritrocit','Splenectomia ca terapie de linia a doua ineficientă, inferioară alchilanților'],'ABC',352,'Anemiile hemolitice autoimune cu anticorpi „la cald"; Cadranul 16.16',
 'Reținerea proporțiilor 65/30/5, a ratei de răspuns de 80% la prednison și a bilanțului primar/secundar 50/50.',
 ['Proporțiile 65%, 30% și 5% sunt cele din clasificarea după temperatura de legare.','Doza de 1 mg/kg și rata de remisiune de 80% sunt cifrele citate.','Splitul 50/50 și predominanța limfoproliferărilor în forma secundară sunt din text.','În forma la cald predomină IgG; IgM caracterizează forma la rece.','Splenectomia este descrisă ca cea mai eficientă terapie de linia a doua, nu ca ineficientă.']],
 8,'Distractorii mută izotipul IgM și ineficiența splenectomiei din forma la rece asupra formei la cald, unde prednisonul și splenectomia sunt tocmai armele descrise.',['65%','1 mg/kg zilnic'],[351,353]),

q(30,['În investigarea AHAI la cald, sunt corecte:',
 ['Trombocitopenia autoimună și/sau neutropenia pot să apară (sindromul Evans)','Autoanticorpii pot avea afinitate pentru sistemul Rh al grupelor sanguine, de exemplu pentru antigenul e','Testul Coombs este pozitiv numai pentru complement, IgG fiind absentă de pe eritrocit','Steroizii reduc doar distrucția splenică, fără a influența producția de autoanticorpi','CT-ul abdominal este superfluu, limfoamele abdominale neintrând în diagnosticul diferențial'],'AB',352,'AHAI la cald — Investigații; Tratament',
 'Recunoașterea sindromului Evans și a specificității Rh (antigen e), plus rolul CT-ului în căutarea limfomului.',
 ['Asocierea cu trombocitopenie și/sau neutropenie autoimună este denumită sindromul Evans.','Afinitatea pentru sistemul Rh, exemplificată prin antigenul e, este menționată explicit.','Coombs-ul este pozitiv doar cu IgG (35%), cu IgG și complement (56%) sau doar complement (9%), deci IgG este frecvent prezentă.','Steroizii reduc atât producția de autoanticorpi, cât și distrucția celulelor acoperite.','CT-ul abdominal este indicat pentru decelarea unui posibil limfom abdominal.']],
 8,'Distractorii folosesc profilul Coombs al formei la rece (doar C3d) și neagă cele două efecte ale steroizilor descrise în același paragraf.',['Sindromul Evans','antigenul e']),

q(31,['Boala hemolitică a nou-născutului se caracterizează prin:',
 ['Doar anticorpii IgG sunt capabili de pasajul transplacentar de la mamă la făt','Cel mai des întâlnit tip este incompatibilitatea ABO (mamă de grup O, făt de grup A), de obicei o formă ușoară','Icterul nuclear apare când bilirubina neconjugată depășește 250 µmol/L, cu depunere în ganglionii bazali','Anti-D 500 UI intramuscular se administrează în primele 72 de ore dacă mama este RhD-negativă, fătul RhD-pozitiv și nu se detectează anti-D maternal','Sensibilizarea la naștere face ca prima sarcină să fie, de regulă, cea mai grav afectată'],'ABCD',354,'Boala hemolitică a nou-născutului; Prevenția imunizării RhD',
 'Integrarea izotipului care trece placenta, a predominanței ABO, a pragului de kernicterus și a schemei postnatale anti-D 500 UI / 72 ore.',
 ['Pasajul transplacentar este rezervat IgG, nu altor izotipuri.','Perechea mamă O / făt A este tipul cel mai frecvent, de obicei ușor.','Pragul de 250 µmol/L și depunerea în ganglionii bazali definesc icterul nuclear.','Cele trei condiții (mamă RhD-negativă, făt RhD-pozitiv, absența anti-D) și doza de 500 UI în 72 de ore sunt schema postnatală.','Prima sarcină este rar afectată; sensibilizarea se produce de obicei la naștere.']],
 8,'Distractorul inversează epidemiologia (prima sarcină gravă), în timp ce celelalte opțiuni cer simultan izotip, perechea ABO, 250 µmol/L și 500 UI.',['250','500 Ul'],[353]),

q(32,['Evaluarea antenatală și sângele pentru exsanguinotransfuzie în BHNN includ:',
 ['Severitatea anemiei fetale se determină prin măsurarea Doppler a vitezei de curgere în artera cerebrală mijlocie fetală','Sângele trebuie să fie compatibil ABO atât pentru mamă cât și pentru făt, să nu conțină antigenul vizat de anticorpul maternal, să fie proaspăt (nu mai vechi de 5 zile) și iradiat','Testul Kleihauer cuantifică eritrocitele fetale în circulația maternă; HbF este rezistentă la tratamentul acid, spre deosebire de HbA','Profilaxia antenatală se poate face în două doze de 500 UI (săptămânile 28 și 34) sau ca doză unică de 1.500 UI în săptămâna 28 sau între săptămânile 28 și 30','Măsurarea pigmenților biliari în lichidul amniotic rămâne metoda de rutină pentru aprecierea severității'],'ABCD',354,'Evaluarea și tratamentul antenatal; Abordarea postnatală; Prevenția',
 'Înlocuirea spectrofotometriei lichidului amniotic cu Doppler MCA și reținerea celor patru cerințe ale unității de sânge plus schema antenatală anti-D.',
 ['Doppler-ul arterei cerebrale mijlocii a înlocuit măsurarea pigmenților biliari ca metodă de rutină.','Cele patru condiții (compatibilitate ABO dublă, antigen-negativ, ≤5 zile, iradiat) sunt lista din text.','Rezistența HbF la acid, cu vizualizare după eozină, stă la baza testului Kleihauer.','Cele două scheme (2×500 UI sau 1×1500 UI) sunt cele implementate în Marea Britanie.','Textul precizează că măsurarea pigmenților biliari în lichidul amniotic nu mai este folosită de rutină.']],
 8,'Distractorul reînvie o metodă pe care textul o declară abandonată; celelalte opțiuni combină Doppler MCA, patru criterii de unitate și două scheme de doze.',['arterei cerebrale mijlocii','Kleihauer']),

q(33,['Policitemia (eritrocitoza), în distincțiile din capitol, se caracterizează prin:',
 ['Hematocritul este un indicator mai de încredere decât hemoglobina, care poate să scadă disproporționat în deficitul de fier','Policitemia Chuvash, autozomal recesivă, se datorează unei mutații în gena von Hippel–Lindau, cu creșterea producției de eritropoietină','Fumatul intensiv poate produce până la 10% carboxihemoglobină și policitemie prin reducerea capacității de transport a oxigenului','Eritropoietina serică este scăzută în policitemia secundară, similar policitemiei vera','Eritrocitoza relativă înseamnă volum eritrocitar crescut cu volum plasmatic normal'],'ABC',355,'Policitemia — Policitemiile secundare; Cadranul 16.17',
 'Separarea hematocritului de hemoglobină, a căii VHL din policitemia Chuvash și a carboxihemoglobinei de 10% a fumătorului de profilul EPO al policitemiei vera.',
 ['Superioritatea hematocritului când hemoglobina scade prin carență marțială este enunțată explicit.','Defectul VHL cu EPO crescută este mecanismul Chuvash.','Cifra de până la 10% carboxihemoglobină explică policitemia fumătorului.','În policitemia secundară, EPO este normală sau crescută, nu scăzută.','Eritrocitoza relativă are volum eritrocitar normal și volum plasmatic scăzut.']],
 8,'Distractorii aplică EPO-ul scăzut al policitemiei vera asupra formei secundare și inversează definiția eritrocitozei relative.',['Hematocritul','10% carboxihemoglobină']),

q(34,['Cea mai des întâlnită cauză a policitemiei secundare descrisă în text este:',
 ['Hemangioblastomul cerebelos','Carcinomul renal secretant de eritropoietină','Fumatul intensiv','Policitemia vera','Mutația receptorului eritropoietinei'],'C',355,'Policitemiile secundare — Tratament',
 'Identificarea fumatului intensiv, nu a tumorilor rare secretante de EPO, ca cea mai frecventă cauză secundară citată.',
 ['Hemangioblastomul figurează printre cauzele patologice de EPO, nu ca cea mai frecventă.','Carcinomul renal este o cauză patologică, nu cea mai comună.','Textul numește fumatul intensiv cea mai des întâlnită cauză.','Policitemia vera este forma primară neoplazică, nu o policitemie secundară.','Mutațiile receptorului EPO sunt cauze congenitale rare, nu etiologia cea mai frecventă.']],
 8,'Distractorii sunt cauze reale din Cadranul 16.17, dar rare sau primare; textul rezervă superlativul fumatului intensiv.',['cea mai des întâlnită cauză','Fumatul intensiv']),
];
