import {rewriter} from './rewrite-author';
import {RETIRED_HEMATOLOGIE} from './retired/hematologie';

// Rewritten after the 2026-09-24 cue audit (Kumar, cap. 16, p. 327–336 și 351–355).
const q=rewriter(RETIRED_HEMATOLOGIE,(p:number)=>p<=336?p-275:p-289,{shuffle:true});

export const HEMATOLOGIE_V2=[
q('hematologie-adv-035',['Anemia:',
 ['se definește prin Hb sub referința pentru vârstă și sex','poate fi falsă prin expansiune plasmatică, ca în sarcină','se clasifică frecvent după VEM','produce o hemoglobină fals crescută în sarcină','este de regulă primară, fără o cauză de căutat'],'ABC',327,'Anemia: introducere',
 'Recunoașterea definiției și clasificării anemiei.',
 ['Hb sub nivelul de referință pentru vârstă și sex.','Volumul plasmatic crescut produce anemie falsă.','Clasificarea are la bază VEM-ul.','În sarcină apare o anemie falsă.','Este de cele mai multe ori secundară.']],
 [8,'Distractorii inversează efectul sarcinii și natura anemiei.'],['volumului plasmatic','vârsta şi sexul'],[328]),

q('hematologie-adv-023',['Conform Figurii 16.6, hemoglobina este fals crescută în:',
 ['policitemia aparentă','sarcină','hemoragia acută','hipervolemia din sarcină','anemia din boli cronice'],'A',327,'Figura 16.6',
 'Interpretarea hemoglobinei în raport cu volumul plasmatic.',
 ['Volumul plasmatic redus crește fals Hb.','Sarcina produce o anemie falsă.','Scad ambele volume.','Volumul plasmatic crescut scade Hb.','Nu este o modificare de volum plasmatic.']],
 [8,'Distractorii sunt celelalte coloane ale figurii.'],['policitemia aparentă','deshidratare']),

q('hematologie-adv-024',['Tabloul clinic al anemiei:',
 ['creșterea 2,3-BPG deplasează curba de disociere spre dreapta','koilonichia apare în anemia feriprivă de lungă durată','ulcerele gambiere se asociază cu siclemia','deformările osoase apar în anemia feriprivă','pierderea rapidă de sânge dă simptome mai ușoare'],'ABC',327,'Anemia: tablou clinic',
 'Recunoașterea compensării și semnelor specifice anemiei.',
 ['2,3-BPG facilitează cedarea oxigenului.','Koilonichia apare în carența de lungă durată.','Ulcerele gambiere se asociază cu siclemia.','Deformările osoase apar în talasemia majoră.','Pierderea rapidă dă simptome mai severe.']],
 [8,'Distractorii mută semnele și inversează severitatea.'],['2,3-BPG','koilonichia']),

q('hematologie-adv-038',['O hemoglobină scăzută se evaluează împreună cu:',
 ['numărul reticulocitelor','frotiul de sânge periferic','numărul leucocitelor și trombocitelor','indicii eritrocitari','dozarea eritropoietinei'],'ABCD',328,'Investigații',
 'Aplicarea evaluării inițiale a anemiei.',
 ['Reticulocitele indică activitatea măduvei.','Morfologia poate indica diagnosticul.','Leucocitele și trombocitele sunt evaluate.','Indicii eritrocitari sunt evaluați.','Nu face parte din evaluarea inițială citată.']],
 [8,'Singurul distractor este o analiză nerecomandată de rutină.'],['reticulocitelor','frotiu de sânge periferic']),

q('hematologie-adv-039',['Dismorfismul eritrocitar (două populații de hematii) apare, conform textului, în:',
 ['deficitul dublu fier–folat din boala celiacă','talasemia minoră, fără alt deficit asociat','anemia din bolile cronice de lungă durată','sferocitoza ereditară','deficitul izolat de B12 al anemiei pernicioase'],'A',328,'Sângele periferic',
 'Interpretarea dismorfismului eritrocitar.',
 ['Deficiențele duble produc două populații.','Nu este exemplul citat.','Nu este exemplul citat.','Nu este exemplul citat.','Nu este exemplul citat.']],
 [8,'Distractorii sunt anemii cu o singură populație.'],['dismorfism','boala celiacă']),

q('hematologie-adv-026',['Conform Cadranului 16.2:',
 ['aspiratul se face de obicei din creasta iliacă','colorația Perls evidențiază fierul pe aspirat','biopsia evaluează mai bine celularitatea în aplazie','biopsia folosește acul Salah, mai scurt și mai subțire','aspiratul necesită decalcifiere de câteva zile'],'ABC',328,'Cadranul 16.2',
 'Diferențierea aspiratului de biopsia osteomedulară.',
 ['Creasta iliacă este locul uzual.','Perls colorează fierul.','Biopsia evaluează superior celularitatea.','Biopsia folosește acul Jamshidi.','Decalcifierea privește biopsia.']],
 [8,'Distractorii inversează acele și prelucrarea.'],['Jamshidi','Perls']),

q('hematologie-adv-066',['Conform Figurii 16.7, anemiile microcitare includ:',
 ['deficitul de fier','talasemia','anemia sideroblastică','anemia din boli cronice','hipotiroidismul'],'ABCD',328,'Figura 16.7',
 'Clasificarea anemiilor după VEM.',
 ['Deficitul de fier este microcitar.','Talasemia este microcitară.','Anemia sideroblastică este microcitară.','Anemia din boli cronice poate fi microcitară.','Hipotiroidismul dă macrocitoză.']],
 [8,'Singurul distractor aparține macrocitozelor.'],['Talasemia','sideroblastică']),

q('hematologie-adv-037',['Conform Figurii 16.7, macrocitoza cu măduvă normoblastică apare în:',
 ['consumul de alcool','boala hepatică','hipotiroidism','terapia cu azatioprină','deficitul de folat'],'ABCD',328,'Figura 16.7',
 'Diferențierea macrocitozei normoblastice de cea megaloblastică.',
 ['Alcoolul este citat.','Boala hepatică este citată.','Hipotiroidismul este citat.','Azatioprina este citată.','Deficitul de folat este megaloblastic.']],
 [8,'Singurul distractor este megaloblastic.'],['Normoblastică','azatioprină']),

q('hematologie-adv-050',['Fierul alimentar:',
 ['o dietă obișnuită conține 15–20 mg de fier pe zi','în mod normal se absoarbe ~50%','absorbția crește la 20–30% în sarcină','fierul feric (Fe3+) se absoarbe mai ușor','fierul non-heminic se absoarbe mai bine'],'AC',329,'Fierul — aportul dietetic',
 'Fixarea datelor despre aportul și absorbția fierului.',
 ['Dieta conține 15–20 mg.','Nu: în mod normal se absoarbe ~10%.','Absorbția crește la 20–30%.','Fierul feros se absoarbe mai ușor.','Fierul heminic se absoarbe mai bine.']],
 [8,'Distractorii inversează formele de fier.'],['15-20 mg','20-30%']),

q('hematologie-adv-051',['Absorbția fierului:',
 ['are loc mai ales în intestinul subțire proximal','este favorizată de aciditatea gastrică','este scăzută de fitați și fosfați','este scăzută în hemocromatoza ereditară','folosește transportorul HCP1 mai ales în ileon'],'ABC',330,'Cadranul 16.3',
 'Recunoașterea factorilor care influențează absorbția fierului.',
 ['Absorbția este proximală.','Aciditatea menține fierul feros și solubil.','Complexele insolubile scad absorbția.','În hemocromatoza ereditară absorbția este crescută.','HCP1 este bine exprimat în duoden.']],
 [8,'Distractorii inversează hemocromatoza și sediul HCP1.'],['Aciditatea gastrică','supraîncărcarea fierului'],[329]),

q('hematologie-adv-052',['Hepcidina:',
 ['este sintetizată în ficat','determină degradarea feroportinei','crește în inflamație, sub acțiunea IL-6','este crescută de eritroferon','stimulează efluxul de fier în plasmă'],'ABC',330,'Absorbția fierului',
 'Recunoașterea rolului hepcidinei.',
 ['Este o peptidă hepatică de 25 de aminoacizi.','Internalizează și degradează feroportina.','IL-6 stimulează hepcidina.','Nu: eritroferonul scade hepcidina.','Scade efluxul de fier.']],
 [8,'Singurul distractor inversează efectul.'],['eritroferon','feroportina']),

q('hematologie-adv-008',['În talasemie, absorbția excesivă a fierului se explică prin:',
 ['eritroferonul, care scade hepcidina','creșterea hepcidinei induse de IL-6','mutația genei HFE','creșterea expresiei DMT1 prin hipoxie','transfuziile repetate'],'A',330,'Absorbția fierului',
 'Explicarea supraîncărcării cu fier în eritropoieza ineficientă.',
 ['Eritroferonul scade hepcidina și crește feroportina.','Hepcidina crescută limitează absorbția.','Explică hemocromatoza ereditară.','Nu este mecanismul citat.','Explică sideroza transfuzională, nu absorbția.']],
 [8,'Distractorii sunt mecanisme ale altor supraîncărcări.'],['eritroferon','talasemia']),

q('hematologie-adv-053',['Transportul plasmatic al fierului:',
 ['transferina leagă doi atomi de fier feric','transferina este saturată normal peste 90%','fierul transportat provine mai ales din macrofage','fierul seric reflectă fidel depozitele de fier','transferina este sintetizată în măduva osoasă'],'AC',330,'Transportul în sânge',
 'Recunoașterea transportului plasmatic al fierului.',
 ['Fiecare moleculă leagă doi atomi de Fe3+.','Nu: saturația normală este de o treime.','Fierul provine din reciclarea macrofagică.','Fierul seric are utilitate mică.','Transferina este sintetizată în ficat.']],
 [8,'Distractorii supraestimează fierul seric și schimbă sediul sintezei.'],['transferină','o treime']),

q('hematologie-adv-022',['Sursa majoritară a fierului legat de transferină este:',
 ['macrofagele reticuloendoteliale','absorbția intestinală duodenală','eliberarea din mioglobină','mobilizarea hemosiderinei hepatice','absorbția fierului heminic intact'],'A',330,'Transportul în sânge',
 'Identificarea sursei fierului plasmatic.',
 ['Macrofagele reciclează fierul hematiilor senescente.','Absorbția contribuie minoritar.','Nu este sursa citată.','Nu este sursa citată.','Nu este sursa citată.']],
 [8,'Distractorii sunt surse minore de fier.'],['reticuloendotelial','transferină']),

q('hematologie-adv-068',['Depozitele și necesarul de fier:',
 ['două treimi din fier circulă ca hemoglobină','depozitele sunt două treimi feritină, o treime hemosiderină','pierderile zilnice sunt de 5–10 mg','pierderea menstruală peste 100 ml duce la deficit','hemosiderina este solubilă și ușor mobilizabilă'],'ABD',330,'Depozitele de fier',
 'Fixarea distribuției și pierderilor de fier.',
 ['Două treimi circulă ca hemoglobină.','Două treimi feritină, o treime hemosiderină.','Nu: se pierd 0,5–1,0 mg/zi.','Peste 100 ml/lună duce de obicei la deficit.','Hemosiderina este insolubilă.']],
 [8,'Singurul distractor confundă hemosiderina cu feritina.'],['hemosiderină','100 ml']),

q('hematologie-adv-054',['Carența marțială se caracterizează prin:',
 ['VEM <80 fL și HEM <27 pg','saturația transferinei sub 19%','receptori solubili ai transferinei crescuți','feritină care poate fi normală în inflamație','CTLF scăzută, ca în boala cronică'],'ABCD',331,'Investigații',
 'Interpretarea investigațiilor în carența marțială.',
 ['Microcitoză și hipocromie.','Saturația sub 19% indică deficit.','Receptorii solubili cresc.','Feritina este reactant de fază acută.','CTLF este crescută.']],
 [8,'Singurul distractor inversează CTLF.'],['19%','poikilocitoză']),

q('hematologie-adv-006',['Conform Cadranului 16.4:',
 ['anemia din boli cronice are CTLF scăzută','talasemia are fier seric și CTLF normale','anemia sideroblastică are fier eritroblastic inelar','deficitul de fier are fier medular prezent','boala cronică are receptori solubili crescuți'],'ABC',331,'Cadranul 16.4',
 'Diagnosticul diferențial al anemiei microcitare.',
 ['CTLF este scăzută.','Fierul seric și CTLF sunt normale.','Fierul eritroblastic are forme inelare.','Fierul medular este absent.','Receptorii sunt normali.']],
 [8,'Distractorii inversează fierul medular și receptorii.'],['CTLF','Forme inelare']),

q('hematologie-adv-001',['Anemie microcitară la un pacient cu boală inflamatorie și pierderi de sânge: CTLF scăzută, feritină normală, receptori solubili ai transferinei crescuți. Interpretarea corectă este:',
 ['anemie din boli cronice cu depozite de fier suficiente','deficit de fier asociat anemiei din boli cronice','deficit de fier simplu, fără răspuns de fază acută','anemie sideroblastică dobândită cu exces de fier','talasemie cu depozite de fier normale'],'B',331,'Cadranul 16.4',
 'Integrarea parametrilor fierului în anemia mixtă.',
 ['Receptorii crescuți indică deficit asociat.','Receptorii solubili crescuți indică deficit asociat.','CTLF scăzută și feritina normală reflectă inflamația.','Nu explică receptorii crescuți.','Nu explică profilul inflamator.']],
 [8,'Distractorii interpretează izolat câte un parametru.'],['Receptori solubili ai transferinei','CTLF']),

q('hematologie-adv-070',['Carența marțială foarte îndelungată poate produce:',
 ['unghii concave (koilonichie)','stomatită angulară','atrofia papilelor linguale','disfagie cu glosită (Plummer-Vinson)','ulcere la nivelul gambelor'],'ABCD',331,'Deficitul de fier — tablou clinic',
 'Recunoașterea semnelor carenței marțiale îndelungate.',
 ['Koilonichia este citată.','Stomatita angulară este citată.','Atrofia papilelor este citată.','Sindromul Plummer-Vinson este citat.','Ulcerele gambiere țin de siclemie.']],
 [8,'Singurul distractor aparține siclemiei.'],['koilonichie','Plummer-Vinson']),

q('hematologie-adv-056',['Tratamentul oral al carenței marțiale:',
 ['crește Hb cu ~50 g/L pe săptămână','folosește sulfatul feros, 200 mg cu 60 mg fier elementar','poate dura până la 6 luni','este favorizat de ceai, prin tanini','crește Hb mai lent decât fierul parenteral'],'BC',332,'Deficitul de fier — tratament',
 'Aplicarea tratamentului oral cu fier.',
 ['Nu: Hb crește cu ~10 g/L pe săptămână.','200 mg sulfat feros = 60 mg fier elementar.','Refacerea depozitelor poate dura 6 luni.','Taninurile inhibă absorbția.','Răspunsul hematologic parenteral nu este mai rapid.']],
 [8,'Distractorii inversează efectul ceaiului și al căii parenterale.'],['10 g/L','sulfatul feros']),

q('hematologie-adv-071',['Eșecul fierului oral se explică frecvent prin:',
 ['lipsa complianței','pierderi continue de sânge','diagnostic incorect, ex. talasemie','absorbție duodenală excesivă','creșterea prea rapidă a hemoglobinei'],'ABC',332,'Deficitul de fier — tratament',
 'Analiza eșecului tratamentului cu fier oral.',
 ['Lipsa complianței este citată.','Pierderile continue sunt citate.','Diagnosticul incorect este citat.','Nu explică eșecul.','Nu explică eșecul.']],
 [8,'Distractorii nu pot explica un eșec terapeutic.'],['lipsa complianţei','talasemie']),

q('hematologie-adv-055',['Fierul parenteral, comparativ cu cel oral:',
 ['reface mai repede depozitele, nu și hemoglobina','crește hemoglobina de două ori mai repede','se continuă alături de fierul oral, pentru sinergie','este prima linie în carența marțială simplă','nu produce reacții anafilactice'],'A',332,'Deficitul de fier — tratament',
 'Compararea fierului parenteral cu cel oral.',
 ['Depozitele se refac mai repede, răspunsul nu e mai rapid.','Răspunsul hematologic nu este mai rapid.','Fierul oral se întrerupe.','Fierul oral este suficient în majoritatea cazurilor.','Fierul dextran cere testare pentru anafilaxie.']],
 [8,'Distractorii supraestimează calea parenterală.'],['parenteral','anafilactice']),

q('hematologie-adv-057',['Anemia din bolile cronice:',
 ['se asociază cu hepcidină scăzută','are răspuns inadecvat al eritropoietinei','nu răspunde la fierul oral','are CTLF crescută, ca deficitul de fier','are fier absent în macrofagele medulare'],'BC',332,'Anemia din bolile cronice',
 'Recunoașterea anemiei din bolile cronice.',
 ['Nu: hepcidina este crescută și sechestrează fierul.','Răspunsul eritropoietinei este inadecvat.','Pacienții nu răspund la fierul oral.','CTLF este scăzută.','Fierul este prezent în frotiul medular.']],
 [8,'Distractorii preiau profilul carenței marțiale.'],['hepcidină','eritropoietinei']),

q('hematologie-adv-072',['Anemia sideroblastică:',
 ['are sideroblaști inelari evidențiați cu reacția Perls','are forma X-linkată prin defectul δ-ALA-sintetazei','poate răspunde la piridoxină','are în forma dobândită mai ales cauză mielodisplazică','are depozite de fier medulare absente sau scăzute'],'ABCD',332,'Anemia sideroblastică',
 'Recunoașterea anemiei sideroblastice.',
 ['Inelele de fier se văd cu Perls.','δ-ALA-sintetaza este dependentă de piridoxină.','Unii pacienți răspund la piridoxină.','Forma dobândită a adultului este mielodisplazică.','Există exces de fier medular.']],
 [8,'Singurul distractor inversează depozitele.'],['Perls','piridoxină']),

q('hematologie-adv-058',['Anemia megaloblastică:',
 ['are VEM de obicei sub 80 fL','are neutrofile hipersegmentate, cu ≥6 lobi','are LDH de obicei crescută','are metamielocite gigante în măduvă','are reticulocitoză marcată'],'BCD',333,'Anemia megaloblastică',
 'Recunoașterea anemiei megaloblastice.',
 ['Nu: VEM este de obicei >96 fL.','Neutrofilele au șase sau mai mulți lobi.','LDH crește prin eritropoieză ineficientă.','Metamielocitele uriașe sunt frecvente.','Eritropoieza este ineficientă.']],
 [8,'Singurul distractor contrazice eritropoieza ineficientă.'],['96 fL','metamielocitele']),

q('hematologie-adv-010',['Mecanismul biochimic comun al deficitului de B12 și de folat este:',
 ['blocarea metilării dUMP la dTMP','blocarea sintezei de purine prin hidroxiuree','inhibarea directă a ADN-polimerazei','sinteza anormală a hemului','deficitul de metilmalonil-CoA mutază'],'A',333,'Bazele biochimice ale anemiei megaloblastice',
 'Explicarea mecanismului anemiei megaloblastice.',
 ['Metilarea deoxiuridin- la deoxitimidin-monofosfat este blocată.','Este un mecanism medicamentos.','Nu este mecanismul citat.','Descrie anemia sideroblastică.','Nu explică deficitul de folat.']],
 [8,'Distractorii sunt mecanisme ale altor anemii.'],['deoxiuridin monofosfatul','metilen tetrahidrofolat']),

q('hematologie-adv-021',['Reacțiile dependente de cobalamină sunt:',
 ['deoxiadenosil-B12: metilmalonil-CoA → succinil-CoA; metil-B12: homocisteină → metionină','metil-B12: metilmalonil-CoA → succinil-CoA; deoxiadenosil-B12: homocisteină → metionină','metil-B12: metilmalonil-CoA → succinil-CoA; deoxiadenosil-B12: sinteza de dTMP','deoxiadenosil-B12: sinteza de dTMP; metil-B12: demetilarea THF','deoxiadenosil-B12: homocisteină → metionină; metil-B12: donor direct de metil pentru dTMP'],'A',334,'Vitamina B12',
 'Asocierea coenzimelor cobalaminice cu reacțiile lor.',
 ['Corect pentru ambele coenzime.','Coenzimele sunt inversate.','Metil-B12 nu servește metilmalonil-CoA.','Nu sunt reacțiile citate.','Coenzimele sunt inversate.']],
 [8,'Distractorii permută coenzimele.'],['Deoxiadenosilcobalamina','succinil CoA'],[335]),

q('hematologie-adv-073',['Vitamina B12:',
 ['se găsește în carne, pește, ouă și lapte','se absoarbe 2–3 µg din 5–30 µg ingerați zilnic','are depozite de 2–3 mg, suficiente ~2 săptămâni','este distrusă de obicei prin gătirea alimentelor','se găsește în cantități mari în plante'],'AB',334,'Vitamina B12',
 'Fixarea aportului și depozitelor de B12.',
 ['Sursele sunt animale.','Se absorb 2–3 µg zilnic.','Nu: depozitele ajung ~2 ani; deficitul apare după 2 ani sau mai mult.','Gătirea nu o distruge de obicei.','Nu se găsește în plante.']],
 [8,'Distractorii inversează efectul gătitului și sursa.'],['2-3 mg','5-30']),

q('hematologie-adv-059',['Absorbția și transportul vitaminei B12:',
 ['factorul intrinsec este secretat de celulele parietale','complexul cu factorul intrinsec se leagă de cubilina ileală','transcobalamina II livrează B12 activă celulelor','factorul intrinsec intră în enterocit odată cu B12','transcobalamina I transportă B12 activă spre măduvă'],'ABC',334,'Absorbție și transport',
 'Recunoașterea căii de absorbție a B12.',
 ['Celulele parietale secretă factorul intrinsec.','Cubilina ileală este receptorul.','Holotranscobalamina este B12 activă.','Factorul intrinsec rămâne în lumen.','TCII transportă B12 activă.']],
 [8,'Distractorii inversează destinul factorului intrinsec și transportorii.'],['cubilina','holotranscobalamină']),

q('hematologie-adv-060',['Anemia pernicioasă:',
 ['are anticorpi anti-celulă parietală la ~10% dintre pacienți','are anticorpi anti-factor intrinsec specifici, dar doar la ~50%','crește incidența carcinomului gastric','este mai frecventă la bărbați decât la femei','are anticorpi anti-parietali absenți la persoanele sănătoase'],'BC',334,'Anemia pernicioasă',
 'Interpretarea serologiei anemiei pernicioase.',
 ['Nu: anticorpii anti-parietali apar la ~90%.','Anti-FI la 50%, dar specifici.','Carcinomul gastric apare la 1–3%.','Este mai frecventă la femei.','Apar la 10% dintre indivizii normali.']],
 [8,'Distractorii inversează sexul și specificitatea.'],['90%','Addison']),

q('hematologie-adv-003',['În anemia pernicioasă, anticorpii anti-celulă parietală și anti-factor intrinsec se compară astfel:',
 ['anti-parietali: sensibili, puțin specifici; anti-FI: puțin sensibili, specifici','anti-parietali: puțin sensibili, dar specifici; anti-FI: sensibili, puțin specifici','anti-parietali: mai sensibili și mai specifici decât anti-FI','anti-FI: mai sensibili și mai specifici decât anti-parietalii','ambele: specificitate similară, sensibilitate diferită'],'A',334,'Anemia pernicioasă',
 'Compararea performanței autoanticorpilor în anemia pernicioasă.',
 ['90% vs 50%; anti-FI sunt specifici.','Profilele sunt inversate.','Anti-parietalii apar și la 10% dintre normali.','Anti-FI apar doar la 50%.','Specificitatea diferă.']],
 [8,'Distractorii permută sensibilitatea și specificitatea.'],['anti-factor intrinsec','90%']),

q('hematologie-adv-074',['Anemia pernicioasă — tabloul clinic:',
 ['poate da culoare galben-lămâie a tegumentelor','poate produce glosită și stomatită angulară','dă neuropatie la B12 foarte scăzută, sub 60 ng/L','afectează precoce sensibilitatea termoalgică','are neuropatie numai în prezența anemiei'],'ABC',334,'Anemia pernicioasă — tablou clinic',
 'Recunoașterea manifestărilor anemiei pernicioase.',
 ['Paloarea și icterul ușor dau culoarea galben-lămâie.','Glosita și stomatita angulară sunt citate.','Neuropatia apare sub 60 ng/L.','Se pierd precoce sensibilitatea vibratorie și proprioceptivă.','Poate apărea fără anemie clinică.']],
 [8,'Distractorii schimbă sensibilitatea afectată și legătura cu anemia.'],['galben-lămâie','60 ng/L']),

q('hematologie-adv-065',['Diagnosticul deficitului de vitamină B12:',
 ['B12 serică este de obicei sub 160 ng/L','sarcina și contraceptivele scad B12 serică','MMA și homocisteina scad în deficit','testul de absorbție este încă de rutină','absența anti-FI exclude anemia pernicioasă'],'AB',335,'Anemia pernicioasă — investigații',
 'Interpretarea testelor pentru deficitul de B12.',
 ['160 ng/L este limita inferioară.','Sarcina și contraceptivele scad B12.','Nu: MMA și homocisteina cresc în deficit.','Testele de absorbție nu se mai fac.','AP este posibilă și fără anti-FI.']],
 [8,'Distractorii supraestimează testul de absorbție și serologia.'],['160 ng/L','metilmalonic']),

q('hematologie-adv-016',['Folații:',
 ['se pierd 60–90% prin gătire','au depozite de ~10 mg','se epuizează în ~4 luni la dietă deficitară','circulă în ser mai ales ca metil-THF monoglutamat','produc neuropatie în deficit, ca B12'],'ABCD',335,'Acidul folic',
 'Fixarea metabolismului și depozitelor de folat.',
 ['Gătirea pierde 60–90%.','Rezervele sunt ~10 mg.','Deficitul apare în ~4 luni.','Metil-THF monoglutamat este forma serică.','Deficitul de folat nu dă neuropatie.']],
 [8,'Singurul distractor preia neuropatia din deficitul de B12.'],['60-90%','10 mg']),

q('hematologie-adv-061',['Conform Cadranului 16.6, cauze ale deficitului de folat sunt:',
 ['fenitoina','metotrexatul','hemodializa','hemoliza cronică','metforminul'],'ABCD',335,'Cadranul 16.6',
 'Recunoașterea cauzelor deficitului de folat.',
 ['Anticonvulsivantele sunt antifolat.','Metotrexatul este antifolat.','Hemodializa crește pierderea.','Hemoliza crește utilizarea.','Metforminul afectează ușor absorbția B12.']],
 [8,'Singurul distractor ține de vitamina B12.'],['Metotrexat','Hemodializă']),

q('hematologie-adv-076',['Tratamentul anemiei megaloblastice:',
 ['transfuzia poate precipita insuficiența cardiacă la vârstnic','acidul folic singur poate agrava neuropatia din deficitul de B12','în formele grave se dau folat și B12 înaintea confirmării','folatul în doze mari este prima linie indiferent de B12','transfuzia este indicată de rutină în anemia megaloblastică cronică'],'ABC',336,'Tratamentul și prevenția anemiei megaloblastice',
 'Aplicarea principiilor tratamentului anemiei megaloblastice.',
 ['Transfuzia poate precipita IC la vârstnic.','Folatul poate agrava neuropatia.','La pacienții gravi se tratează înainte de confirmare.','Doze mari de folat doar cu B12 normală.','Transfuzia nu este indicată de obicei.']],
 [8,'Distractorii ignoră riscul neurologic și transfuzional.'],['insuficienţa cardiacă','neuropatia']),

q('hematologie-adv-062',['Tratamentul cu hidroxicobalamină:',
 ['se face cu 1.000 µg i.m., până la 5–6 mg în 2 săptămâni','continuă cu 1.000 µg la 3 luni, toată viața','produce reticulocitoză maximă la 5–7 zile','poate produce hipokaliemie','vindecă mereu leziunile medulare vechi'],'ABCD',336,'Tratamentul deficitului de vitamină B12',
 'Aplicarea schemei de substituție cu B12.',
 ['1.000 µg i.m., maxim 5–6 mg în 2 săptămâni.','1.000 µg la 3 luni pe viață.','Reticulocitoza atinge maximul la 5–7 zile.','Hipokaliemia poate apărea.','Afectarea medulară veche este ireversibilă.']],
 [8,'Singurul distractor contrazice ireversibilitatea.'],['5-6 mg','hipokaliemia']),

q('hematologie-adv-077',['Acidul folic:',
 ['se dă 5 mg/zi circa 4 luni în deficit','se dă profilactic 40 µg/zi la începutul sarcinii','se dă 5 mg/zi după un copil cu defect de tub neural','se dă 400 µg/zi în bolile hematologice cronice','se dă 5 mg/zi doar după naștere'],'AC',336,'Tratamentul deficitului de folați',
 'Aplicarea dozelor de acid folic.',
 ['5 mg/zi circa 4 luni.','Nu: doza profilactică este 400 µg/zi.','5 mg/zi după un copil cu DTN.','Bolile hematologice cronice primesc 5 mg.','Profilaxia începe înainte de sarcină.']],
 [8,'Distractorii schimbă doza și momentul.'],['400','tubului neural']),

q('hematologie-adv-078',['Macrocitoza cu măduvă normoblastică:',
 ['apare fiziologic în sarcină','apare în consumul excesiv de alcool','apare în reticulocitoză','dispare la încălzire în aglutininele la rece','asociază deficit de B12 sau folat'],'ABCD',336,'Macrocitoza fără modificări megaloblastice',
 'Recunoașterea macrocitozei non-megaloblastice.',
 ['Sarcina este cauza fiziologică frecventă.','Alcoolul este o cauză frecventă.','Reticulocitele cresc VEM-ul.','VEM scade la normal la 37°C.','B12 și folatul sunt normale.']],
 [8,'Singurul distractor preia mecanismul megaloblastic.'],['sarcina','37°C']),

q('hematologie-adv-028',['Anemia aplastică:',
 ['este o pancitopenie cu măduvă hipocelulară','are cauză idiopatică dobândită în ~67% din cazuri','poate fi produsă de cloramfenicol sau carbimazol','poate evolua spre HPN sau leucemie acută','are infiltrat leucemic sau tumoral medular'],'ABCD',336,'Anemia aplastică',
 'Recunoașterea anemiei aplastice.',
 ['Pancitopenie cu hipocelularitate.','Forma idiopatică dobândită: 67%.','Cloramfenicolul și carbimazolul sunt citate.','Poate evolua spre HPN sau LAM.','Nu există celule leucemice sau canceroase.']],
 [8,'Singurul distractor contrazice definiția.'],['Fanconi','cloramfenicol']),

q('hematologie-adv-040',['Majoritatea anemiilor aplastice idiopatice dobândite au mecanism:',
 ['prin celule T citotoxice activate','prin anticorpi antieritropoietină','prin fibroză medulară primară','prin infiltrarea leucemică a măduvei','prin deficit de fier medular'],'A',336,'Anemia aplastică — etiologie',
 'Explicarea mecanismului anemiei aplastice.',
 ['Celulele T citotoxice produc insuficiența medulară.','Nu este mecanismul citat.','Nu este mecanismul citat.','Contrazice definiția.','Nu este mecanismul citat.']],
 [8,'Distractorii sunt alte mecanisme de insuficiență medulară.'],['citotoxice','imune']),

q('hematologie-adv-041',['Anemia hemolitică dobândită non-imună poate fi produsă de:',
 ['protezele valvulare','arsurile extinse','dapsonă sau sulfasalazină','hemoglobinuria paroxistică nocturnă','aloanticorpii transfuzionali'],'ABCD',351,'Anemia hemolitică dobândită',
 'Clasificarea etiologică a hemolizei dobândite.',
 ['Factorii mecanici sunt citați.','Arsurile denaturează membrana.','Produc hemoliză oxidativă.','HPN este un defect membranar dobândit.','Aloanticorpii sunt o cauză imună.']],
 [8,'Singurul distractor este o cauză imună.'],['dapsona','Arsurile extinse']),

q('hematologie-adv-042',['Testul antiglobulinic direct:',
 ['detectează eritrocite sensibilizate in vivo','este pozitiv în anemia hemolitică autoimună','este negativ în boala hemolitică a nou-născutului','se folosește la proba de compatibilitate pretransfuzională','detectează aloanticorpi liberi în ser'],'AB',351,'Figura 16.26',
 'Diferențierea testelor Coombs direct și indirect.',
 ['Detectează sensibilizarea in vivo.','AHAI are DAT pozitiv.','Nu: BHNN are DAT pozitiv.','Proba de compatibilitate folosește testul indirect.','Testul indirect detectează anticorpii din ser.']],
 [8,'Distractorii descriu testul indirect.'],['in vivo','compatibilitate']),

q('hematologie-adv-029',['Anemia hemolitică autoimună „la cald”:',
 ['reprezintă ~65% din AHAI','are anticorpi mai ales IgG','este secundară în ~50%, mai ales limfoproliferărilor','răspunde la prednison în ~20%','are Coombs pozitiv doar pentru C3d'],'ABC',352,'Anemiile hemolitice autoimune „la cald”',
 'Recunoașterea AHAI la cald.',
 ['Forma la cald reprezintă 65%.','Predomină IgG.','Jumătate sunt secundare, mai ales limfoproliferări.','Nu: prednisonul induce remisiune la ~80%.','Doar C3d caracterizează forma la rece.']],
 [8,'Singurul distractor preia serologia formei la rece.'],['limfoproliferările','80%'],[351]),

q('hematologie-adv-030',['AHAI la cald — investigații și tratament:',
 ['poate asocia trombocitopenie autoimună (sindrom Evans)','impune CT abdominal pentru decelarea unui limfom','are splenectomia ca terapie eficientă de linia a doua','are rituximabul contraindicat la corticorezistenți','are autoanticorpi fără specificitate de grup sanguin'],'ABC',352,'Anemiile hemolitice autoimune „la cald”',
 'Aplicarea investigațiilor și tratamentului AHAI la cald.',
 ['Sindromul Evans poate apărea.','CT-ul caută un limfom abdominal.','Splenectomia este cea mai eficientă a doua linie.','Rituximabul este eficient la corticorezistenți.','Pot avea specificitate Rh (antigenul e).']],
 [8,'Distractorii contrazic rituximabul și specificitatea Rh.'],['Evans','limfom abdominal'],[353]),

q('hematologie-adv-043',['Distrugerea imună a eritrocitelor:',
 ['activarea completă a complementului dă hemoliză intravasculară','IgG fără complement dau hemoliză extravasculară','fagocitoza parțială produce sferocite','IgM fără complement produc hemoliză severă','celulele cu C3d sunt îndepărtate foarte eficient'],'ABC',352,'Distrugerea imună a eritrocitelor',
 'Explicarea mecanismelor hemolizei imune.',
 ['Complementul activat produce liză intravasculară.','IgG fără complement: fagocitoză splenică.','Fagocitoza parțială produce sferocite.','Au efect scăzut sau deloc.','Celulele cu C3d circulă, îndepărtare ineficientă.']],
 [8,'Distractorii inversează eficiența mecanismelor.'],['extravasculară','receptorii Fc'],[351]),

q('hematologie-adv-044',['Boala cronică a hemaglutinării la rece:',
 ['apare mai ales la vârstnici','are aglutinine IgM monoclonale','produce acrocianoză la frig','are Coombs direct pozitiv pentru C3d','răspunde bine la splenectomie'],'ABCD',353,'Boala cronică a hemaglutinării la rece',
 'Recunoașterea bolii aglutininelor la rece.',
 ['Apare de obicei la vârstnici.','Aglutininele IgM sunt monoclonale.','Acrocianoza apare la frig.','DAT este pozitiv pentru C3d.','Splenectomia este de obicei ineficientă.']],
 [8,'Singurul distractor preia tratamentul formei la cald.'],['1:512','acrocianoză']),

q('hematologie-adv-045',['Tratamentul AHAI la rece:',
 ['include evitarea expunerii pacientului la frig','poate folosi rituximab (anti-CD20)','impune transfuzia într-un spațiu cald','se bazează pe prednison, ca forma la cald','folosește splenectomia ca linie a doua'],'ABC',353,'Boala cronică a hemaglutinării la rece',
 'Aplicarea tratamentului AHAI la rece.',
 ['Expunerea la frig se evită.','Rituximabul a fost eficient.','Transfuzia se face la cald.','Steroizii sunt de obicei ineficienți.','Splenectomia este de obicei ineficientă.']],
 [8,'Distractorii preiau tratamentul formei la cald.'],['Rituximab','spaţiu cald']),

q('hematologie-adv-046',['Hemoglobinuria paroxistică la rece:',
 ['se asociază cu rujeola, oreionul sau varicela','are anticorpi IgG bifazici anti-P','se confirmă prin testul Donath–Landsteiner','are anticorpi IgM monoclonali anti-I','produce hemoliză cronică progresivă'],'ABC',353,'Hemoglobinuria paroxistică la rece',
 'Recunoașterea hemoglobinuriei paroxistice la rece.',
 ['Se asociază cu infecțiile copilului.','IgG bifazici, specificitate P.','Testul Donath–Landsteiner confirmă.','Descrie boala aglutininelor la rece.','Hemoliza este autolimitantă.']],
 [8,'Distractorii preiau trăsăturile CHAD.'],['Donath-Landsteiner','bifazici']),

q('hematologie-adv-047',['Diagnosticul anemiei hemolitice imune medicamentoase cere:',
 ['asociere temporală, DAT pozitiv, remisiune la oprire','reintroducerea medicamentului, pentru a proba cauzalitatea','dozarea anticorpilor antimedicament înaintea DAT','DAT negativ și haptoglobină normală','persistența hemolizei după oprire'],'A',353,'Anemia hemolitică imună iatrogenă',
 'Aplicarea criteriilor de diagnostic ale hemolizei medicamentoase.',
 ['Sunt cele trei criterii citate.','Reintroducerea nu se recomandă.','Testarea nu se face uzual.','DAT trebuie să fie pozitiv.','Remisiunea după oprire este criteriu.']],
 [8,'Distractorii inversează criteriile.'],['reintroducerea','temporală']),

q('hematologie-adv-031',['Boala hemolitică a nou-născutului:',
 ['este produsă de anticorpi IgG care traversează placenta','este cel mai des prin incompatibilitate ABO, ușoară','poate produce icter nuclear la bilirubină >25 µmol/L','afectează de regulă cel mai grav prima sarcină','prin incompatibilitate ABO necesită frecvent transfuzii'],'AB',353,'Boala hemolitică a nou-născutului',
 'Recunoașterea bolii hemolitice a nou-născutului.',
 ['Doar IgG trec transplacentar.','Incompatibilitatea ABO este cea mai frecventă, ușoară.','Nu: icterul nuclear apare peste 250 µmol/L.','Primele sarcini sunt rar afectate.','Transfuziile sunt rareori necesare.']],
 [8,'Distractorii inversează sarcina afectată și severitatea ABO.'],['transplacentar','ABO'],[354]),

q('hematologie-adv-032',['Managementul bolii hemolitice a nou-născutului:',
 ['severitatea se apreciază Doppler, pe artera cerebrală medie','sângele transfuzat trebuie iradiat','sângele transfuzat trebuie să fie sub 5 zile','pigmenții biliari amniotici sunt metoda de rutină','fototerapia face bilirubina liposolubilă'],'ABC',354,'Boala hemolitică a nou-născutului',
 'Aplicarea evaluării și tratamentului BHNN.',
 ['Doppler pe artera cerebrală mijlocie fetală.','Iradierea previne GVHD transfuzională.','Sângele trebuie proaspăt, sub 5 zile.','Nu mai sunt folosiți de rutină.','Biliverdina rezultată este hidrosolubilă.']],
 [8,'Distractorii inversează metoda de rutină și solubilitatea.'],['cerebrale mijlocii','iradiat']),

q('hematologie-adv-048',['Profilaxia anti-D:',
 ['se face cu 500 UI i.m. în 30 de zile postpartum','nu se face dacă mama are deja anti-D','se ajustează după testul Kleihauer','se face dacă mama și fătul sunt RhD-pozitivi','se face cu 250 UI după săptămâna 20'],'BC',354,'Prevenția imunizării RhD',
 'Aplicarea profilaxiei anti-D.',
 ['Nu: 500 UI i.m. în primele 72 de ore.','Mama nu trebuie să fie deja imunizată.','Kleihauer cuantifică eritrocitele fetale.','Mama trebuie să fie RhD-negativă.','După 20 de săptămâni doza este 500 UI.']],
 [8,'Distractorii schimbă statusul Rh și doza.'],['Kleihauer','72 de']),

q('hematologie-adv-063',['Hemoglobinuria paroxistică nocturnă:',
 ['rezultă din mutații ale genei PIG-A','are deficit de CD55 și CD59','produce tromboze în situri atipice (Budd-Chiari)','se diagnostichează prin flow-citometrie','are măduvă constant hipercelulară'],'ABCD',354,'Hemoglobinuria paroxistică nocturnă',
 'Recunoașterea HPN.',
 ['Mutațiile PIG-A afectează ancora GPI.','CD55 și CD59 lipsesc.','Trombozele atipice sunt caracteristice.','Flow-citometria cu anti-CD55/CD59.','Măduva poate fi hipoplazică.']],
 [8,'Singurul distractor contrazice hipoplazia posibilă.'],['PIG-A','CD59'],[355]),

q('hematologie-adv-049',['Eculizumabul:',
 ['blochează clivarea C5','reduce riscul trombotic','impune vaccinare antimeningococică prealabilă','se administrează intravenos','reactivează măduva aplazică'],'ABCD',355,'HPN — tratament',
 'Aplicarea tratamentului cu eculizumab.',
 ['Previne clivarea C5.','Scade riscul trombotic.','Vaccinarea anti-N. meningitidis cu 2 săptămâni înainte.','Se administrează i.v.','Nu reactivează măduva.']],
 [8,'Singurul distractor atribuie un efect medular.'],['Neisseria meningitidis','C5']),

q('hematologie-adv-079',['Evoluția hemoglobinuriei paroxistice nocturne:',
 ['urina închisă apare tipic noaptea și dimineața','pierderile urinare pot produce deficit de fier','mediana supraviețuirii este 1–2 ani','clona HPN poate dispărea în timp','poate evolua spre policitemia vera'],'ABD',354,'Hemoglobinuria paroxistică nocturnă',
 'Recunoașterea evoluției HPN.',
 ['Micțiunile nocturne și prima urină sunt închise.','Pierderile urinare dau deficit de fier.','Nu: mediana este 10–15 ani.','Clona poate dispărea.','Evoluează spre aplazie sau leucemie acută.']],
 [8,'Singurul distractor schimbă direcția de evoluție.'],['prima urină','deficit de fier'],[355]),

q('hematologie-adv-064',['Anemia hemolitică mecanică apare în:',
 ['protezele valvulare disfuncționale','hemoglobinuria de maraton','hipertensiunea malignă','coagularea intravasculară diseminată','hemoglobinuria paroxistică la rece'],'ABCD',355,'Anemia hemolitică mecanică',
 'Recunoașterea cauzelor hemolizei mecanice.',
 ['Valvele disfuncționale sunt citate.','Alergarea produce hemoliză.','MAHA în hipertensiunea malignă.','MAHA în CID.','Este o hemoliză imună.']],
 [8,'Singurul distractor este o hemoliză imună.'],['maraton','microangiopatică']),

q('hematologie-adv-033',['Policitemia:',
 ['se apreciază mai fidel prin hematocrit decât prin hemoglobină','forma Chuvash are mutație VHL','poate fi produsă de carcinomul renal','secundară are eritropoietină scăzută','relativă are volum eritrocitar crescut'],'ABC',355,'Policitemia',
 'Diferențierea formelor de policitemie.',
 ['Hb poate scădea disproporționat în carența de fier.','Mutația von Hippel–Lindau.','Producția ectopică de EPO.','EPO este normală sau crescută.','Volumul eritrocitar este normal.']],
 [8,'Distractorii inversează EPO și definiția formei relative.'],['Chuvash','Hematocritul']),

q('hematologie-adv-034',['Cea mai des întâlnită cauză a policitemiei secundare, conform textului, este:',
 ['fumatul intensiv','carcinomul renal','altitudinea','apneea de somn','hemangioblastomul cerebelos'],'A',355,'Policitemia secundară',
 'Identificarea celei mai frecvente cauze de policitemie secundară.',
 ['Fumatul intensiv este cea mai frecventă cauză.','Este o cauză rară.','Nu este cea mai frecventă.','Nu este cea mai frecventă.','Este o cauză rară.']],
 [8,'Distractorii sunt alte cauze din cadran.'],['Fumatul intensiv','carboxihemoglobină']),
];
