import {advancedQuestion} from './advanced-author';
import type {SourceRow} from './source-author';

const pdfOffset=(p:number)=>p===1275?313:p<=1284?p-970:p-973;
const q=(n:number,row:SourceRow,score:number,reason:string,expressions:string[],related:number[]=[])=>
 advancedQuestion('hepatologie',34,pdfOffset,`hepatologie-adv-${String(n).padStart(3,'0')}`,row,[score,reason],expressions,undefined,related);

export const HEPATOLOGIE_ADVANCED=[
q(1,['Sistemele de scor histologic utilizate în hepatita cronică:',
 ['Scorul Knodell (indexul de activitate histologică) însumează patru factori, incluzând inflamația portală și fibroza','Scorul Ishak stadializează fibroza de la 0 (absentă) la 6 (ciroză)','Scorul Brunt este rezervat hepatitei C, iar sistemul METAVIR este aplicat de obicei în NAFLD','Sistemul METAVIR are patru grade și este rezervat de obicei hepatitei C','Scorurile reprezintă măsuri cantitative ale fibrozei, aplicabile identic indiferent de etiologia bolii hepatice'],'ABD',1275,'Hepatita — Hepatita cronică: morfopatologie și scoruri histologice',
 'Diferențierea sistemelor de scor histologic (Knodell, Ishak, METAVIR, Brunt) după componentele evaluate și bolile în care se aplică.',
 ['Textul precizează că scorul Knodell utilizează suma a patru factori: necroza periportală sau în punte, degenerescența intralobulară și necroza focală, inflamația portală și fibroza.','Scorul Ishak stadializează fibroza de la 0 (absentă) la 6 (ciroză), conform textului.','Textul indică inversul: scorul Brunt este aplicat în mod obișnuit pentru NAFLD, iar METAVIR este rezervat hepatitei C.','Sistemul METAVIR are patru grade și, conform textului, este rezervat pentru hepatita C.','Textul subliniază că scorurile nu sunt măsuri cantitative ale fibrozei și că pentru boli diferite se folosesc sisteme diferite.']],
 8,'Cere memorarea corespondenței exacte scor–boală și a intervalului de stadializare Ishak, cu un distractor care inversează Brunt și METAVIR.',['stadializează fibroza','scorul Brunt este aplicat']),

q(2,['Alegeți afirmațiile corecte referitoare la terapia antivirală cu acțiune directă în infecția cu virusul hepatitei C:',
 ['Sofosbuvir este un inhibitor nucleotidic al polimerazei virale','Combinația sofosbuvir/ledipasvir este pangenotipică, iar sofosbuvir/velpatasvir este specifică genotipurilor 1 și 4','Glecaprevir/pibrentasvir se administrează 8 săptămâni la pacienții fără ciroză și 12 săptămâni la cei cu ciroză','După clearance-ul viral, riscul de cancer hepatic persistă la pacienții cu ciroză, deși la un nivel scăzut','Terapia de succes este definită ca virus nedetectabil la 12 săptămâni de la terminarea tratamentului'],'ACDE',1284,'Hepatita virală C — Agenții antivirali',
 'Cunoașterea țintelor, duratelor și spectrului genotipic al regimurilor antivirale orale pentru VHC și a semnificației răspunsului virusologic susținut.',
 ['Textul descrie sofosbuvir drept inhibitor nucleotidic al polimerazei, combinat cu un inhibitor NS5a.','Textul indică inversul: sofosbuvir/velpatasvir este combinația pangenotipică, iar sofosbuvir/ledipasvir este specifică genotipurilor 1 și 4.','Glecaprevir/pibrentasvir implică trei tablete pe zi timp de 8 săptămâni fără ciroză sau 12 săptămâni la pacienții cu ciroză.','După clearance-ul viral progresia fibrozei se oprește, dar la cirotici riscul pentru cancer hepatic persistă, deși la un nivel scăzut.','Terapia de succes este definită ca virus nedetectabil la 12 săptămâni de la terminarea terapiei, după care pacienții fără ciroză pot fi absolviți de urmărire.']],
 8,'Distractorul inversează spectrul genotipic al două combinații cu același inhibitor de polimerază, iar restul opțiunilor cer durate și praguri exacte.',['nucleotidic al polimerazei','progresia fibrozei hepatice este oprită']),

q(3,['Care dintre următoarele afirmații privind infecția cu virusul hepatitei E sunt adevărate?',
 ['Mortalitatea prin insuficiență hepatică fulminantă este de 1-2% și crește la 20% la femeile însărcinate','Infecția nu progresează spre boală hepatică cronică, cu excepția unor pacienți imunosupresați','Este un virus ADN din familia Hepadnaviridae, similar virusului hepatitei B','Diagnosticul se bazează pe biopsia hepatică, testele serologice nefiind disponibile','Ribavirina este tratamentul de primă intenție la imunocompetenții cu hepatită E acută'],'AB',1284,'Hepatita virală E — Evoluție, diagnostic și particularități',
 'Recunoașterea gravității VHE la gravide, a absenței cronicizării la imunocompetenți și a naturii de virus ARN, distinct de VHB.',
 ['Textul precizează o mortalitate de 1-2% prin insuficiență hepatică fulminantă, care crește la 20% la femeile însărcinate.','Textul afirmă că nu există status de purtător și că infecția nu progresează spre boală cronică, cu excepția unor pacienți imunosupresați.','VHE este un virus ARN din familia Hepeviridae; Hepadnaviridae caracterizează VHB.','Textul descrie un test ELISA pentru anticorpi anti-VHE de tip IgG sau IgM și evidențierea ARN VHE în ser sau scaun prin PCR.','La imunocompromiși infecția cronică se tratează prin reducerea imunosupresiei și/sau ribavirină; aceasta nu este linia întâi la imunocompetenți cu infecție acută.']],
 8,'Distractorii atribuie VHE familia și genomul VHB și extind ribavirina de la imunosupresați la toate hepatitele E acute.',['20% la femeile însărcinate','Familia Hepeviridae']),

q(4,['Un bărbat de 58 de ani cu ciroză hepatică prezintă bilirubină serică 45 µmol/L, albumină serică 30 g/L, timp de protrombină prelungit cu 5 secunde peste valoarea normală, ascită mică și fără encefalopatie. Conform clasificării Child-Pugh modificate, pacientul se încadrează în:',
 ['Clasa Child A, cu 6 puncte','Clasa Child B, cu 8 puncte','Clasa Child B, cu 9 puncte','Clasa Child C, cu 10 puncte','Clasa Child A, cu 5 puncte'],'C',1291,'Ciroza hepatică — Prognostic: clasificarea Child-Pugh modificată',
 'Aplicarea punctajului Child-Pugh pe cei cinci parametri la un caz concret și încadrarea în clasa prognostică corespunzătoare.',
 ['Cu 9 puncte pacientul depășește pragul clasei A (<7 puncte); 6 puncte ar cere valori mai favorabile la cel puțin trei parametri.','Clasa este corectă, dar suma este 9, nu 8: fiecare dintre bilirubină (34-50), albumină (28-35), TP (4-6 s) și ascita mică primește 2 puncte, encefalopatia absentă 1 punct.','Tabelul 34.16 indică 2 puncte pentru fiecare dintre bilirubină 34-50 µmol/L, albumină 28-35 g/L, TP prelungit 4-6 s și ascită mică, plus 1 punct pentru absența encefalopatiei: total 9, deci Child B (7-9 puncte).','Clasa C necesită cel puțin 10 puncte; niciun parametru al pacientului nu atinge pragul de 3 puncte.','5 puncte reprezintă minimul posibil și ar cere valori normale la toți cei cinci parametri.']],
 8,'Necesită calculul exact al punctajului din cinci parametri cu praguri numerice și cunoașterea limitelor de clasă, distractorii oferind clasa corectă cu scor greșit.',['Child B (7-9 puncte)','62% la 1 an']),

q(5,['Următoarele afirmații despre transplantul hepatic sunt adevărate:',
 ['Sepsisul activ în alt teritoriu decât arborele hepatobiliar reprezintă o contraindicație absolută','Metastazele hepatice constituie o contraindicație absolută, cu excepția celor neuroendocrine','Donatorul trebuie să fie compatibil atât ABO, cât și HLA cu primitorul','Rejetul acut celular apare de obicei la 5-10 zile după transplant și răspunde bine la terapia imunosupresivă','Rejetul cronic ductopenic se observă între 6 săptămâni și 9 luni, cu rărirea și dispariția căilor biliare'],'ABDE',1292,'Ciroza hepatică — Transplantul hepatic: contraindicații, donatorul și rejetul grefei',
 'Diferențierea contraindicațiilor absolute de cele relative, a cerințelor de compatibilitate a donatorului și a celor două tipuri de rejet al grefei hepatice.',
 ['Textul enumeră sepsisul activ extrahepatic, în afara arborelui hepatobiliar, printre contraindicațiile absolute.','Metastazele hepatice sunt contraindicație absolută, cu excepția celor neuroendocrine, conform textului.','Textul precizează că donatorul trebuie să fie compatibil ABO, dar compatibilitatea HLA nu este necesară.','Respingerea acută sau celulară apare la 5-10 zile, cu infiltrat pleomorf portal dominat de eozinofile, și răspunde bine la imunosupresie.','Respingerea cronică ductopenică apare între 6 săptămâni și 9 luni, cu sindromul dispariției canalelor biliare și arteriopatie.']],
 8,'Combină excepția neuroendocrină de la o contraindicație absolută cu o capcană privind compatibilitatea HLA și cronologia celor două tipuri de rejet.',['compatibil ABO','infiltrat pleomorf portal']),

q(6,['Insuficiența hepatică acută survenită pe o hepatopatie cronică (ACLF) se caracterizează prin:',
 ['Se referă la pacienții internați pentru o complicație acută a cirozei însoțită de insuficiențe de organ','Se estimează că apare la 31% dintre pacienții internați cu o complicație acută a cirozei','Evenimentele precipitante frecvente includ infecțiile bacteriene și consumul excesiv de alcool','Este superpozabilă cirozei decompensate tradiționale, fără particularități de vârstă sau de inflamație','Dispozitivele extracorporeale de susținere a ficatului sunt disponibile de rutină în această indicație'],'ABC',1291,'Ciroza hepatică — Insuficiența hepatică acută survenită pe hepatopatie cronică',
 'Recunoașterea ACLF ca sindrom distinct de decompensarea tradițională, cu mortalitate mare, precipitanți infecțioși sau alcoolici și absența dispozitivelor de rutină.',
 ['Textul definește ACLF ca starea pacienților internați pentru o complicație acută a cirozei însoțită de insuficiențe de organ, cu mortalitate mare pe termen scurt.','Textul estimează apariția la 31% dintre pacienții internați cu o complicație acută a cirozei.','Printre particularități se numără prevalența mai mare a infecțiilor bacteriene sau a consumului excesiv de alcool ca evenimente precipitante.','Textul consideră ACLF diferită de ciroza decompensată tradițională, fiind caracterizată și de vârste tinere, etiologie alcoolică și inflamație sistemică mai înaltă.','Textul precizează că, în prezent, niciun dispozitiv extracorporeal nu este disponibil de rutină.']],
 8,'Distractorii identifică ACLF cu decompensarea obișnuită și presupun disponibilitatea de rutină a suportului extracorporeal, pe care textul o neagă.',['insuficienţe de organ','31% dintre pacienţii']),

q(7,['Un bărbat de 54 de ani cu ciroză alcoolică se prezintă cu hematemeză, TA 90/60 mmHg și hemoglobină 68 g/L; endoscopia de urgență confirmă varice esofagiene sângerânde. În managementul acestui pacient sunt adevărate:',
 ['Sevrajul alcoolic se tratează preferențial cu clordiazepoxid, al cărui timp de înjumătățire scade în boala hepatică avansată','Antibioterapia profilactică tratează și previne infecția, reducând resângerarea precoce și mortalitatea','O hemoglobină țintă de 80 g/L este suficientă, atingerea acestui obiectiv scăzând probabilitatea resângerării precoce','Somatostatina este vasoconstrictorul cu dovezi de reducere a mortalității și se preferă terlipresinei','Terlipresina se administrează 2 mg la 6 ore și nu trebuie dată pacienților cu boală cardiacă ischemică'],'BCE',1294,'Ciroza hepatică — Hemoragia variceală: tratamentul inițial al sângerării acute',
 'Aplicarea măsurilor de resuscitare și a terapiei vasoconstrictoare în hemoragia variceală acută, cu evitarea capcanelor privind ținta transfuzională și sevrajul alcoolic.',
 ['Textul recomandă lorazepam sau oxazepam, deoarece timpul de înjumătățire al clordiazepoxidului crește (nu scade) în boala hepatică avansată.','Antibioterapia profilactică tratează și previne infecția și reduce resângerarea precoce și mortalitatea.','O hemoglobină țintă de 80 g/L este suficientă și atingerea ei scade probabilitatea resângerării precoce.','Terlipresina, nu somatostatina, este vasoconstrictorul cu dovezi de reducere a mortalității; somatostatina este rezervată celor cu contraindicații la terlipresină.','Doza de terlipresină este de 2 mg la 6 ore, iar medicamentul nu trebuie administrat pacienților cu boală cardiacă ischemică.']],
 8,'Inversează relația farmacocinetică a clordiazepoxidului și atribuie somatostatinei beneficiul de mortalitate al terlipresinei, într-un scenariu clinic cu praguri numerice.',['Doza este de 2 mg la 6 ore','reduce resângerarea precoce şi mortalitatea'],[1293]),

q(8,['Profilaxia secundară a hemoragiei variceale:',
 ['Ligaturile elastice repetate se efectuează la intervale de 3 luni până la obliterarea varicelor','Beta-blocantele neselective se dozează astfel încât să reducă frecvența pulsului de repaus cu 25%','Terapia combinată (beta-blocant și ligatură) îmbunătățește semnificativ mortalitatea comparativ cu terapia endoscopică singură','Reducerea gradientului de presiune venoasă hepatică sub 12 mmHg se asociază cu rate foarte mici de resângerare','Procedurile de devascularizare produc encefalopatie mai frecvent decât șunturile portosistemice chirurgicale'],'BD',1295,'Ciroza hepatică — Prevenirea sângerării variceale recurente (profilaxia secundară)',
 'Cunoașterea țintelor hemodinamice ale beta-blocadei, a ritmului ligaturilor și a efectului real al terapiei combinate și al opțiunilor chirurgicale asupra encefalopatiei.',
 ['Textul precizează că ligaturile elastice se repetă la intervale de 2 săptămâni, nu de 3 luni.','Propranololul sau carvedilolul se dozează pentru a reduce frecvența pulsului de repaus cu 25%, ceea ce scade presiunea portală.','Terapia combinată reduce sângerarea comparativ cu terapia endoscopică singură, dar fără o îmbunătățire generală a mortalității.','O reducere semnificativă a HVPG, în special sub 12 mmHg, este asociată cu rate foarte mici de resângerare.','Textul indică inversul: șunturile chirurgicale au encefalopatia drept complicație semnificativă, iar procedurile de devascularizare nu produc encefalopatie.']],
 8,'Cere diferențierea între reducerea sângerării și reducerea mortalității și inversează profilul de encefalopatie al două opțiuni chirurgicale.',['frecvenţei pulsului de repaus cu 25%','sub 12 mmHg']),

q(9,['În tratamentul ascitei din ciroză se recomandă:',
 ['Restricția aportului de sodiu la 40 mmol în 24 de ore, cu menținerea unui aport adecvat de proteine și calorii','Restricția hidrică de rutină, inclusiv la pacienții cu sodiu seric normal','Spironolactona ca diuretic de elecție, începând cu 100 mg pe zi','O pierdere netă de lichid de aproximativ 700 ml în 24 de ore, adică o scădere ponderală de 0,7 kg în absența edemelor','Vaptanii de rutină, deoarece reduc mortalitatea și complicațiile cirozei'],'ACD',1296,'Ciroza hepatică — Ascita: tratament',
 'Stabilirea măsurilor dietetice și diuretice corecte în ascita cirotică, inclusiv țintele numerice și indicațiile reale ale restricției hidrice și ale vaptanilor.',
 ['Textul precizează că aportul de sodiu se poate reduce la 40 mmol în 24 de ore, menținând un aport adecvat de proteine și calorii.','Restricția hidrică nu este necesară decât dacă sodiul seric este <128 mmol/L.','Diureticul de elecție este antagonistul aldosteronului spironolactona, începând cu 100 mg pe zi.','Scopul terapiei diuretice este o pierdere netă apropiată de 700 ml în 24 de ore, adică 0,7 kg (sau 1 kg dacă există edeme periferice).','Vaptanii au un mic efect asupra hiponatremiei și ascitei, dar nu influențează mortalitatea sau complicațiile cirozei, iar utilizarea de rutină nu poate fi recomandată.']],
 8,'Testează praguri numerice precise (40 mmol, 100 mg, 0,7 kg) și două capcane de management frecvent supraestimate: restricția hidrică și vaptanii.',['începând cu 100 mg pe zi','40 mmol în 24 de ore']),

q(10,['O femeie de 61 de ani cu ciroză decompensată și ascită, aflată sub tratament cu propranolol, este internată pentru deteriorarea stării generale, fără febră sau durere abdominală. Paracenteza diagnostică evidențiază 480 neutrofile/mm³. Care dintre următoarele afirmații sunt adevărate?',
 ['Tratamentul antibiotic trebuie amânat până la identificarea germenului în cultura lichidului de ascită','Absența febrei și a durerii abdominale nu infirmă diagnosticul de peritonită bacteriană spontană','Propranololul ar trebui oprit, deoarece continuarea sa crește riscul de insuficiență renală','Riscul de recurență în primul an este redus (sub 10%), astfel că profilaxia secundară nu este justificată','Peritonita bacteriană spontană nu constituie o indicație pentru transplantul hepatic'],'BC',1297,'Ciroza hepatică — Peritonita bacteriană spontană',
 'Recunoașterea prezentării paucisimptomatice a peritonitei bacteriene spontane și aplicarea deciziilor terapeutice imediate, inclusiv oprirea beta-blocantelor.',
 ['Un număr crescut de neutrofile în lichidul de ascită este o dovadă suficientă pentru a începe imediat tratamentul cu antibiotic cu spectru larg.','Textul precizează că durerea și febra sunt frecvent absente, boala trebuind suspectată la orice pacient cu ascită a cărui stare se deteriorează.','Există dovezi că beta-blocantele nonselective ar trebui oprite după diagnosticul de PBS, deoarece continuarea lor crește riscul de insuficiență renală.','Reapariția este frecventă (70% într-un an), iar prevenția secundară cu norfloxacin 400 mg pe zi prelungește supraviețuirea.','Textul descrie PBS drept complicație gravă care reprezintă o indicație pentru transplant hepatic.']],
 8,'Scenariul atipic (fără febră, fără durere) și decizia contraintuitivă de a opri un beta-blocant profilactic testează cunoștințe nuanțate de management.',['durerea şi febra sunt frecvent absente','prescrierea lor în continuare creşte'],[1296]),

q(11,['Precizați enunțul corect privind tratamentul encefalopatiei portosistemice:',
 ['Lactuloza este un purgativ osmotic care reduce pH-ul colonic și limitează absorbția amoniacului','Restricția proteică trebuie menținută peste 48 de ore pentru a limita producția de amoniac','Neomicina este antibioticul preferat pentru profilaxia secundară a episoadelor de encefalopatie','Terapia diuretică trebuie intensificată pentru a favoriza eliminarea metaboliților toxici','Metronidazolul nu are eficacitate în episodul acut, fiind rezervat profilaxiei secundare'],'A',1298,'Ciroza hepatică — Encefalopatia portosistemică: tratament',
 'Identificarea mecanismului lactulozei și evitarea erorilor frecvente de management (restricție proteică prelungită, neomicină, intensificarea diureticelor).',
 ['Textul descrie lactuloza (10-30 ml de trei ori pe zi) ca purgativ osmotic care reduce pH-ul colonic și limitează absorbția amoniacului.','Textul recomandă să nu se restricționeze proteinele mai mult de 48 de ore și să se crească aportul proteic pe măsură ce encefalopatia se ameliorează.','Rifaximina are efect benefic în profilaxia secundară a EPS, în timp ce neomicina trebuie evitată.','Textul recomandă oprirea sau reducerea terapiei diuretice, dezechilibrul electrolitic prin diureză excesivă fiind un factor precipitant.','Metronidazolul (200 mg de patru ori pe zi) poate fi eficient în episodul acut; rifaximina este cea indicată în profilaxia secundară.']],
 8,'Distractorii inversează durata restricției proteice, schimbă rolurile rifaximinei, neomicinei și metronidazolului și propun intensificarea diureticelor, un factor precipitant.',['purgativ osmotic','profilaxia secundară a EPS']),

q(12,['Identificați afirmația corectă referitoare la boala Wilson:',
 ['Gena care codifică o ATPază transportatoare de cupru este situată pe cromozomul 13, iar transmiterea este autozomal recesivă','Scăderea ceruloplasminei serice este alterarea responsabilă pentru depunerile tisulare de cupru','O concentrație hepatică de cupru >180 µg/g greutate uscată la biopsie confirmă diagnosticul','Inelul Kayser-Fleischer este constant prezent la copiii mici, fiind cel mai precoce semn al bolii','Tratamentul cu penicilamină se întrerupe după 2-3 ani, odată cu normalizarea cupruriei'],'A',1302,'Ciroza hepatică — Tipuri de ciroză: boala Wilson',
 'Cunoașterea bazei genetice a bolii Wilson și diferențierea ei de capcanele privind ceruloplasmina, pragul cuprului hepatic, inelul Kayser-Fleischer și durata chelării.',
 ['Textul precizează defectul unei ATPaze transportatoare de cupru codificată de o genă situată pe cromozomul 13, cu transmitere autozomal recesivă.','Scăderea ceruloplasminei este prezentă la peste 80% dintre pacienți, dar textul precizează că nu aceasta este alterarea responsabilă pentru depunerile de cupru.','Pragul diagnostic este >250 µg/g greutate uscată; 180 µmol/g este pragul concentrației hepatice de fier din hemocromatoză.','Inelul Kayser-Fleischer necesită adesea lampa cu fantă și poate să lipsească la copiii mici.','Tratamentul cu penicilamină este pe toată durata vieții; doar doza se reduce după 2-3 ani, sub monitorizarea cuprului urinar.']],
 8,'Distractorii folosesc pragul de fier al hemocromatozei drept prag de cupru și confundă reducerea dozei de penicilamină cu oprirea tratamentului.',['cromozomul 13','membrana lui Descemet'],[1301]),
];
