import {rewriter} from './rewrite-author';
import {RETIRED_HTA} from './retired/hta';

// Rewritten after the 2026-09-24 cue audit (Kumar, cap. 31, p. 1133–1145).
const q=rewriter(RETIRED_HTA,(p:number)=>p-855,{shuffle:true});

export const HTA_V2=[
q('hta-adv-001',['Hipertensiunea arterială:',
 ['este principalul factor de risc de mortalitate global','afectează aproximativ două treimi dintre adulți','este un factor de risc pentru fibrilația atrială','este mai frecventă la femei înainte de menopauză','este frecventă la copii și adolescenți'],'AC',1133,'Introducere',
 'Recunoașterea importanței epidemiologice a hipertensiunii.',
 ['Depășește fumatul și bolile infecțioase ca factor de mortalitate.','Nu: afectează o treime dintre adulți.','Este factor de risc pentru FA, AVC, IMA și BCR terminală.','Femeile au valori mai mici până la menopauză.','Este rară la copii și adolescenți.']],
 [8,'Distractorii inversează distribuția pe vârstă și sex.'],['principalul factor de risc','fibrilaţia atrială'],[1134]),

q('hta-adv-030',['Epidemiologia hipertensiunii arteriale:',
 ['femeile au valori tensionale mai mici până la menopauză','este mai frecventă la rasa neagră și afro-caraibieni','se asociază cu urbanizarea și imigrația','sub 30 de ani, cauzele secundare sunt rare și nu se caută','după menopauză, prevalența rămâne mai mică la femei'],'ABC',1134,'Introducere',
 'Recunoașterea factorilor demografici ai hipertensiunii.',
 ['Hormonii feminini par protectori până la menopauză.','Este mai frecventă în aceste grupuri etnice.','Se asociază cu urbanizarea și imigrația.','Sub 30 de ani se caută atent cauzele secundare.','După menopauză valorile devin egale cu ale bărbaților.']],
 [8,'Distractorii contrazic efectul menopauzei și vârsta tânără.'],['urbanizarea','imigraţia'],[1133]),

q('hta-adv-028',['Organizarea îngrijirii hipertensiunii:',
 ['majoritatea cazurilor sunt tratate în ambulator','rezistența la trei clase justifică evaluarea de specialitate','diagnosticul sub 30 de ani impune căutarea cauzelor secundare','controlul tensional depășește 80% în majoritatea populațiilor','simptomele fără urgență sunt o indicație de tratament'],'ABC',1133,'Introducere',
 'Aplicarea principiilor de organizare a îngrijirii.',
 ['Majoritatea sunt tratați în ambulator.','Lipsa controlului sub minim trei clase justifică trimiterea.','Sub 30 de ani se evaluează atent cauzele secundare.','Rata de control este sub 50%.','Simptomele nu sunt o indicație în absența urgenței.']],
 [8,'Distractorii supraestimează controlul și rolul simptomelor.'],['minim trei clase','sub 30 de ani'],[1134]),

q('hta-adv-002',['Tensiunea arterială:',
 ['prezintă variabilitate inclusiv sezonieră','este mai bine aproximată prin măsurători multiple','se măsoară clasic la brațul non-dominant','la diferențe >10 mmHg se folosește brațul cu TA mai mică','este reprezentată fidel de o singură determinare'],'ABC',1134,'Măsurarea tensiunii arteriale',
 'Aplicarea principiilor de măsurare a TA.',
 ['Variază de la secunde la sezoane.','Măsurătorile multiple aproximează TA uzuală.','Brațul non-dominant este situsul clasic.','Se folosește brațul cu TA mai mare.','O singură determinare poate fi nereprezentativă.']],
 [8,'Distractorii inversează regula brațelor.'],['non-dominant','sezonier']),

q('hta-adv-003',['Măsurarea corectă a TA la cabinet presupune:',
 ['repaus de 5 minute în poziție șezândă','manșeta să acopere cel puțin 40% din circumferința brațului','cel puțin două măsurători la fiecare evaluare','manșeta plasată deasupra nivelului inimii','metoda oscilometrică la pacientul cu fibrilație atrială'],'AC',1135,'Măsurarea tensiunii arteriale',
 'Aplicarea tehnicii corecte de măsurare a TA.',
 ['Repaus de 5 minute, spatele sprijinit.','Nu: manșeta acoperă ≥80% din circumferință.','Se folosesc cel puțin două măsurători.','Manșeta se plasează la nivelul inimii.','În FA se preferă metoda auscultatorie.']],
 [8,'Distractorii schimbă poziția manșetei și metoda în FA.'],['5 minute','80% din circumferinţa'],[1136]),

q('hta-adv-048',['La pacientul cu fibrilație atrială, TA se măsoară preferabil prin:',
 ['metoda auscultatorie clasică','aparat oscilometric automat','monitorizare ambulatorie de 24 h','o singură măsurare la domiciliu','cateter intra-arterial de rutină'],'A',1135,'Măsurarea tensiunii arteriale',
 'Alegerea metodei de măsurare în fibrilația atrială.',
 ['Metoda auscultatorie este preferată în FA.','Aparatele oscilometrice dau măsurători inexacte în FA.','Folosește tot dispozitive oscilometrice.','Nu este metoda citată.','Nu este metoda citată.']],
 [8,'Distractorii sunt metode oscilometrice sau invazive.'],['auscultatorii','fibrilaţia atrială']),

q('hta-adv-004',['Conform Cadranului 31.1:',
 ['hipertensiunea de halat alb are TA normală în afara cabinetului','hipertensiunea mascată are TA normală la cabinet','ambele fenotipuri au risc cardiovascular intermediar','hipertensiunea de halat alb are riscul cardiovascular cel mai mic','hipertensiunea mascată are riscul cel mai crescut'],'ABC',1136,'Cadranul 31.1',
 'Diferențierea fenotipurilor de hipertensiune.',
 ['Crescută la cabinet, normală în afara lui.','Normală la cabinet, crescută în afara lui.','Ambele au risc intermediar.','Riscul cel mai mic îl are normotensivul.','Riscul cel mai crescut îl are hipertensiunea susținută.']],
 [8,'Distractorii mută extremele de risc.'],['halat alb','mascată']),

q('hta-adv-027',['În hipertensiunea de halat alb, medicația antihipertensivă:',
 ['nu este recomandată, din lipsă de dovezi','este recomandată de rutină, ca la hipertensivi','se ghidează după valorile de cabinet','se inițiază la risc intermediar','se ghidează după valorile de domiciliu'],'A',1136,'Tipuri de hipertensiune arterială',
 'Aplicarea conduitei în hipertensiunea de halat alb.',
 ['Nu este recomandată, din lipsă de dovezi clinice.','Nu este recomandată.','Nu este recomandată.','Riscul intermediar nu justifică medicația aici.','Valorile extra-cabinet ghidează hipertensiunea mascată.']],
 [8,'Distractorii preiau conduita din hipertensiunea mascată.'],['halat alb','lipsă de dovezi']),

q('hta-adv-046',['Măsurarea TA la domiciliu:',
 ['presupune măsurători dimineața și seara, timp de 4–7 zile','exclude prima determinare din calculul mediei','dă valori cu ~5/5 mmHg mai mici decât la cabinet','este înalt predictivă pentru evenimente cardiovasculare','dă valori cu ~5/5 mmHg mai mari decât la cabinet'],'ABCD',1136,'Măsurarea TA la domiciliu',
 'Aplicarea protocolului de măsurare la domiciliu.',
 ['Dimineața înainte de tratament și seara, 4–7 zile.','Prima determinare nu se ia în calcul.','Valoarea este cu ~5/5 mmHg mai mică.','Este înalt predictivă.','Valoarea este mai mică decât la cabinet.']],
 [8,'Singurul distractor inversează diferența față de cabinet.'],['4-7 zile','Prima determinare']),

q('hta-adv-047',['Monitorizarea ambulatorie a TA pe 24 de ore:',
 ['măsoară TA la 2–3 minute în perioada activă','este cel mai predictiv indicator pentru evenimentele CV','este recomandată în Marea Britanie pentru diagnostic','dă valori diurne cu 5–10/5 mmHg mai mari decât la cabinet','măsoară TA la 5 minute în timpul somnului'],'BC',1136,'Determinarea TA în ambulator',
 'Aplicarea monitorizării ambulatorii a TA.',
 ['Nu: ziua la 20–30 de minute, noaptea la 30–60.','Media pe 24 h este mai predictivă decât cabinetul sau domiciliul.','În Marea Britanie înlocuiește cabinetul pentru diagnostic.','Valorile diurne sunt mai mici cu 5–10/5 mmHg.','Noaptea se măsoară la 30–60 de minute.']],
 [8,'Distractorii inversează diferența și intervalul nocturn.'],['20-30 de minute','Marea Britanie']),

q('hta-adv-005',['Hipertensiunea sistolică izolată:',
 ['apare prin rigidizarea arterială legată de vârstă','asociază creșterea presiunii pulsului','impune evitarea scăderii TAD sub 60 mmHg','se tratează diferit de hipertensiunea mixtă','nu poate fi produsă de insuficiența aortică'],'ABC',1136,'Hipertensiunea sistolică izolată',
 'Recunoașterea hipertensiunii sistolice izolate.',
 ['Rigidizarea arterială crește TAS și scade TAD.','Presiunea pulsului crescută asociază injurie vasculară.','TAD sub 60 mmHg poate afecta fluxul coronarian.','Tratamentul este același ca în forma mixtă.','Insuficiența aortică poate produce același fenotip.']],
 [8,'Distractorii contrazic tratamentul și diagnosticul diferențial.'],['60 mmHg','presiunii pulsului']),

q('hta-adv-006',['Hipotensiunea ortostatică se definește prin scăderea TAS cu peste 20 mmHg sau a TAD cu peste 10 mmHg:',
 ['la 3 minute de ortostatism','imediat după ridicare','la 10 minute de ortostatism','la 30 de secunde de ortostatism','după 5 minute de clinostatism'],'A',1137,'Hipotensiunea ortostatică',
 'Aplicarea definiției hipotensiunii ortostatice.',
 ['Scăderea susținută se evaluează la 3 minute.','Nu este intervalul citat.','Nu este intervalul citat.','Nu este intervalul citat.','Nu este intervalul citat.']],
 [8,'Distractorii sunt intervale plauzibile.'],['3 minute','ortostatism']),

q('hta-adv-049',['Hipotensiunea ortostatică:',
 ['este mai frecventă la vârstnici','se asociază cu diabetul și boala Parkinson','este de obicei asimptomatică','impune ghidarea tratamentului după TA în ortostatism','este rară în neuropatiile autonome'],'ABCD',1137,'Hipotensiunea ortostatică',
 'Recunoașterea hipotensiunii ortostatice.',
 ['Este mai frecventă la vârste înaintate.','Diabetul și boala Parkinson sunt citate.','De obicei este asimptomatică.','TA în ortostatism ghidează tratamentul.','Este frecventă în neuropatiile autonome.']],
 [8,'Singurul distractor contrazice asocierea cu neuropatia autonomă.'],['boala Parkinson','asimptomatică']),

q('hta-adv-007',['Etiologia hipertensiunii arteriale:',
 ['până la 90% dintre pacienți au hipertensiune primară','fiecare genă contribuie individual cu ~5–10 mmHg','genele combinate pot determina 60% din nivelul TA','factorii de mediu determină ~90% din nivelul TA','termenul „esențială” este preferat celui de „primară”'],'AC',1137,'Etiologia hipertensiunii arteriale',
 'Recunoașterea bazei poligenice a hipertensiunii primare.',
 ['Până la 90% nu au o cauză identificabilă.','Nu: fiecare genă contribuie cu 0,5–1 mmHg.','Combinate, genele determină 60%.','Mediul și stilul de viață mediază până la 40%.','Termenul „primară” este preferat.']],
 [8,'Distractorii inversează ponderea genetică și terminologia.'],['0,5-1 mmHg','60%']),

q('hta-adv-017',['Hipertensiunea arterială rezistentă se definește, de obicei, ca TA necontrolată în pofida:',
 ['a trei antihipertensive din clase diferite','a două antihipertensive din clase diferite','a monoterapiei în doză maximă','a modificărilor stilului de viață timp de 3 luni','a trei antihipertensive din aceeași clasă'],'A',1137,'Etiologia hipertensiunii arteriale',
 'Aplicarea definiției hipertensiunii rezistente.',
 ['Trei antihipertensive din clase diferite, recomandate de ghid.','Nu este definiția citată.','Nu este definiția citată.','Nu este definiția citată.','Clasele trebuie să fie diferite.']],
 [8,'Distractorii schimbă numărul și clasele.'],['trei antihipertensive']),

q('hta-adv-033',['Sunt asociate cu creșterea TA:',
 ['aportul crescut de sare','aportul ridicat de carbohidrați simpli','consumul excesiv de lemn dulce (liquorice)','aportul redus de legume și fructe','exercițiile fizice de forță regulate'],'ABCD',1137,'Aspecte legate de stilul de viață',
 'Recunoașterea factorilor dietetici ai hipertensiunii.',
 ['Sarea crește TA.','Carbohidrații simpli sunt citați.','Liquorice permite cortizolului să activeze receptorul mineralocorticoid.','Aportul redus de legume și fructe este citat.','Exercițiile de forță se asociază cu TA mai mică.']],
 [8,'Singurul distractor inversează efectul exercițiului.'],['liquorice','carbohidraţi simpli']),

q('hta-adv-058',['Apariția bruscă a hipertensiunii severe la un pacient anterior bine controlat impune în primul rând:',
 ['evaluarea aderenței la tratament','denervarea simpatică renală','angiografia arterelor renale','dozarea metanefrinelor plasmatice','monitorizarea ambulatorie de 24 h'],'A',1137,'Etiologia hipertensiunii arteriale',
 'Aplicarea evaluării agravării bruște a hipertensiunii.',
 ['Aderența se evaluează înaintea cauzelor secundare.','Nu este prima etapă.','Cauzele secundare se caută dacă pacientul aderă.','Cauzele secundare se caută dacă pacientul aderă.','Nu este prima etapă citată.']],
 [8,'Distractorii sar peste evaluarea aderenței.'],['aderenţei la tratament','bine controlată']),

q('hta-adv-025',['Pot crește tensiunea arterială:',
 ['AINS','inhibitorii de calcineurină','venlafaxina','contraceptivele orale','beta-blocantele'],'ABCD',1138,'Medicamente și droguri',
 'Recunoașterea medicamentelor care cresc TA.',
 ['AINS sunt citate.','Inhibitorii de calcineurină sunt citați.','Venlafaxina este citată.','Pilulele contraceptive sunt citate.','Beta-blocantele scad TA.']],
 [8,'Singurul distractor este o clasă cardiovasculară uzuală.'],['calcineurină','venlafaxină']),

q('hta-adv-008',['Hipertensiunea arterială secundară:',
 ['reprezintă ~10% din totalul hipertensivilor','are o proporție mai mare sub 30 de ani','are ca cauză frecventă hiperaldosteronismul primar','include ca principale cauze apneea de somn și obezitatea','reprezintă ~50% din totalul hipertensivilor'],'ABCD',1138,'Hipertensiunea arterială secundară',
 'Recunoașterea frecvenței și cauzelor hipertensiunii secundare.',
 ['Reprezintă numai 10%.','Proporția e mai mare sub 30 de ani.','Hiperaldosteronismul primar este printre cele mai frecvente.','Apneea de somn și obezitatea sunt citate.','Reprezintă 10%.']],
 [8,'Singurul distractor umflă frecvența.'],['10%','apneea obstructivă de somn']),

q('hta-adv-050',['Sarcina și tensiunea arterială:',
 ['TA scade fiziologic mai ales în trimestrul al doilea','scăderea se datorează vasodilatației semnificative','HTA de sarcină crește riscul ulterior de HTA precoce','volumul circulant scade fiziologic pe parcursul sarcinii','TA crește fiziologic în trimestrul al doilea'],'ABC',1138,'Hipertensiunea arterială secundară — sarcina',
 'Recunoașterea adaptării tensionale din sarcină.',
 ['TA scade mai ales în trimestrul al doilea.','Vasodilatația compensează creșterea volumului.','Aceste femei devin hipertensive mai precoce.','Volumul circulant crește.','TA scade în trimestrul al doilea.']],
 [8,'Distractorii inversează volumul și direcția TA.'],['vasodilataţie','volumului circulant']),

q('hta-adv-022',['Conform capitolului, în hipertensiunea de gradul 1:',
 ['se insistă inițial pe modificarea stilului de viață','tratamentul imediat se rezervă riscului CV >1% pe an','tratamentul imediat se indică la leziuni de organ țintă','medicația se indică dacă TA nu se normalizează în 3–12 luni','medicația se amână până la trecerea în gradul 2 de HTA'],'ABCD',1138,'Valori de referință și ținte',
 'Aplicarea conduitei în hipertensiunea de gradul 1.',
 ['Stilul de viață este prima abordare.','Riscul CV >1%/an justifică tratamentul imediat.','Leziunile de organ țintă justifică tratamentul imediat.','Medicația se recomandă după 3–12 luni fără normalizare.','Medicația nu se amână până la gradul 2.']],
 [8,'Singurul distractor amână nejustificat medicația.'],['3-12 luni','>1% pe an']),

q('hta-adv-021',['Țintele tensionale:',
 ['SPRINT a susținut ținta <130/80 mmHg la toți pacienții','NICE sugerează 150/90 mmHg peste 80 de ani','ESC/ESH vizează <130/80 mmHg la vârstnicii cu status bun','NICE a adoptat deja ținta <130/80 mmHg pentru toți','la vârstnicii fragili se recomandă reducere agresivă'],'ABC',1138,'Valori de referință și ținte',
 'Compararea țintelor tensionale din ghiduri.',
 ['SPRINT a susținut ținta <130/80 mmHg.','NICE sugerează 150/90 mmHg peste 80 de ani.','ESC/ESH vizează <130/80 mmHg dacă e tolerată.','NICE nu a adoptat încă această țintă.','La fragili reducerea este prudentă.']],
 [8,'Distractorii contrazic poziția NICE și prudența la fragili.'],['SPRINT','150/90 mmHg']),

q('hta-adv-020',['Conform Figurii 31.2, pragurile de diagnostic ale hipertensiunii sunt:',
 ['sub 80 de ani, la cabinet: >140 sau >90 mmHg','sub 80 de ani, la domiciliu: >135 sau >85 mmHg','peste 80 de ani, la cabinet: >160 sau >90 mmHg','peste 80 de ani, la domiciliu: >160 sau >90 mmHg','sub 80 de ani, la domiciliu: >140 sau >90 mmHg'],'ABC',1135,'Figura 31.2',
 'Aplicarea pragurilor de diagnostic după vârstă și metodă.',
 ['Sub 80 de ani, cabinet: >140 sau >90.','Sub 80 de ani, domiciliu: >135 sau >85.','Peste 80 de ani, cabinet: >160 sau >90.','Peste 80 de ani, domiciliu: >150 sau >85.','Sub 80 de ani, domiciliu: >135 sau >85.']],
 [8,'Distractorii preiau pragurile de cabinet pentru domiciliu.'],['Sub 80 ani','Peste 80 ani']),

q('hta-adv-034',['Conform Cadranului 31.3, la cabinet:',
 ['gradul 1 corespunde valorilor 140–159/90–99 mmHg','gradul 2 corespunde valorilor 160–179/100–109 mmHg','TA normal înaltă corespunde valorilor 130–139/80–89 mmHg','hipertensiunea severă începe de la valori >170 sau >105 mmHg','sistolica izolată are TAS >140 cu TAD >90 mmHg'],'ABC',1140,'Cadranul 31.3',
 'Clasificarea valorilor tensionale.',
 ['Gradul 1: 140–159/90–99.','Gradul 2: 160–179/100–109.','Normal înaltă: 130–139/80–89.','La cabinet severa este >180/>110; >170/>105 este extra-cabinet.','Sistolica izolată are TAD <90.']],
 [8,'Distractorii preiau pragurile extra-cabinet și inversează TAD.'],['140-159','normal înaltă']),

q('hta-adv-009',['Retinopatia hipertensivă, în clasificarea în trei clase:',
 ['forma ușoară include încrucișarea arteriovenoasă','forma moderată include pete cu aspect de vată','forma severă adaugă edemul papilar','forma ușoară include microanevrismele','forma moderată are asociere modestă cu evenimentele CV'],'ABC',1140,'Leziunile organelor țintă — ochii',
 'Clasificarea retinopatiei hipertensive.',
 ['Ușoară: îngustare arteriolară, încrucișare AV.','Moderată: hemoragii, microanevrisme, vată, exsudate.','Severă: semnele moderate plus edem papilar.','Microanevrismele sunt din forma moderată.','Forma moderată are asociere puternică.']],
 [8,'Distractorii mută semne și asocieri între clase.'],['Keith-Wagener-Barker','edem papilar']),

q('hta-adv-010',['Hipertrofia ventriculară stângă hipertensivă:',
 ['are criterii ECG cu sensibilitate de 70–80%','are criterii ECG cu specificitate >90%','este evaluată mai sensibil prin ecocardiografie și RMN','este de regulă simptomatică, cu dispnee de efort','are criterii ECG cu sensibilitate >90%'],'BC',1140,'Leziunile organelor țintă — cordul',
 'Interpretarea performanței ECG în HVS.',
 ['Nu: sensibilitatea este modestă, 20–50%.','Specificitatea este >90%.','Imagistica este mai sensibilă și specifică.','HVS este de obicei asimptomatică.','Specificitatea, nu sensibilitatea, este >90%.']],
 [8,'Distractorii inversează sensibilitatea și simptomatologia.'],['20-50%','>90%']),

q('hta-adv-031',['Afectarea renală hipertensivă:',
 ['se detectează precoce prin raportul albumină:creatinină','este atât cauză, cât și consecință a HTA','permite scăderea inițială a RFG cu până la 40%','contraindică urmărirea funcției renale după inițiere','se manifestă inițial prin scăderea RFG cu peste 25%'],'AB',1140,'Leziunile organelor țintă — rinichii',
 'Interpretarea funcției renale la inițierea tratamentului.',
 ['Microalbuminuria/RAC detectează stadiile precoce.','Boala renală este cauză și consecință.','Nu: este permisă reducerea RFG cu până la 10%.','Urmărirea regulată este necesară.','Stadiile precoce se văd prin albuminurie.']],
 [8,'Distractorii contrazic monitorizarea și semnul precoce.'],['10%','cauză, cât şi o consecinţă']),

q('hta-adv-011',['O reducere a TA cu 10/5 mmHg se asociază cu scăderea:',
 ['mortalității de toate cauzele cu ~15%','accidentelor vasculare cerebrale cu ~35%','insuficienței cardiace cu ~40%','infarctului miocardic cu ~20%','infarctului miocardic acut cu ~40%'],'ABCD',1140,'Tratament',
 'Fixarea beneficiului reducerii TA.',
 ['Mortalitatea scade cu 15%.','AVC scad cu 35%.','Insuficiența cardiacă scade cu 40%.','Infarctul scade cu 20%.','Infarctul scade cu 20%.']],
 [8,'Singurul distractor permută procentele.'],['15%','35%']),

q('hta-adv-012',['Conform Cadranului 31.4, reduc TA în medie cu:',
 ['exercițiile regulate — ~5 mmHg','reducerea sării <6 g/zi — ~5 mmHg','mai multe fructe și legume — ~10 mmHg','scăderea ponderală — ~1 mmHg/kg','alcoolul <2 unități/zi — ~10 mmHg'],'ABCD',1142,'Cadranul 31.4',
 'Fixarea impactului modificărilor stilului de viață.',
 ['Exercițiile: 5 mmHg.','Sarea <6 g/zi: 5 mmHg.','Fructe și legume: 10 mmHg.','Greutatea: 1 mmHg/kg.','Alcoolul <2 unități/zi: 3 mmHg.']],
 [8,'Singurul distractor umflă efectul alcoolului.'],['1 mmHg/kg','10 mmHg']),

q('hta-adv-016',['Prevenția cardiovasculară la hipertensiv:',
 ['statinele se recomandă la risc CV total >5% pe an','la tineri se ia în calcul riscul pe durata vieții','aspirina nu mai este recomandată în prevenția primară','aspirina rămâne indicată la diabetici în prevenția primară','statinele se recomandă doar după un eveniment coronarian'],'BC',1142,'Tratament',
 'Aplicarea prevenției cardiovasculare globale.',
 ['Nu: statinele se recomandă la risc >1%/an.','Pragul poate să nu fie atins la tineri.','Hemoragiile anulează beneficiul aspirinei.','Nici la diabetici nu există beneficiu net.','Sunt recomandate în prevenția primară la risc >1%/an.']],
 [8,'Distractorii restrâng statinele și extind aspirina.'],['statine puternice','aspirina în doze mici'],[1140]),

q('hta-adv-013',['Conform ghidurilor NICE, alegerea terapiei inițiale:',
 ['folosește vârsta și etnia ca surogat al reninei','preferă BCC la vârstnici și la descendenții africani','preferă IECA sau ARA la pacienții albi tineri','preferă IECA față de ARA, fiind mai bine tolerați','preferă IECA la descendenții negrilor africani'],'ABC',1142,'Tratamentul medicamentos',
 'Aplicarea alegerii terapiei inițiale după NICE.',
 ['Vârsta și etnia sunt surogate ale reninei.','Renina scăzută favorizează BCC.','IECA sau ARA la albii tineri.','ARA sunt mai bine tolerați.','Răspunsul la IECA este redus în acest grup.']],
 [8,'Distractorii inversează toleranța și grupul țintă.'],['surogate','angioedemului']),

q('hta-adv-052',['Conform studiului PATHWAY-2, cel mai bun medicament de linia a patra în hipertensiunea rezistentă este:',
 ['spironolactona','bisoprololul','doxazosinul','un BCC non-DHP (verapamil)','un diuretic de ansă'],'A',1142,'Tratamentul medicamentos',
 'Alegerea terapiei de linia a patra.',
 ['Spironolactona este preferată beta- sau alfa-blocantelor.','Este inferior spironolactonei.','Este inferior spironolactonei.','Nu este opțiunea citată.','Nu este opțiunea citată.']],
 [8,'Distractorii sunt comparatorii studiului.'],['PATHWAY-2','linia a patra']),

q('hta-adv-035',['Aderența la tratamentul antihipertensiv:',
 ['până la o zecime dintre pacienți nu își iau medicația','chestionarele se corelează slab cu testele toxicologice','se îmbunătățește prin combinații într-o singură pilulă','se estimează fiabil prin rata de reînnoire a rețetelor','depășește 90% la pacienții din centrele de specialitate'],'BC',1142,'Tratamentul medicamentos — aderența',
 'Interpretarea datelor despre aderență.',
 ['Nu: până la două treimi nu își iau medicația.','Chestionarele se corelează slab cu dovezile obiective.','Combinațiile într-o pilulă cresc aderența.','Reînnoirea rețetelor se corelează slab.','Până la două treimi sunt non-aderenți.']],
 [8,'Distractorii supraestimează aderența și metodele indirecte.'],['două treimi','Morisky']),

q('hta-adv-051',['Pe Scala Morisky-8, un scor de 7 sugerează:',
 ['aderență scăzută','aderență bună','aderență perfectă','non-aderență totală','intoleranță medicamentoasă'],'A',1142,'Cadranul 31.5',
 'Interpretarea scalei Morisky.',
 ['Scorul 7 sugerează aderență scăzută.','Aderența bună corespunde scorului 8.','Nu este interpretarea citată.','Nu este interpretarea citată.','Scala măsoară aderența.']],
 [8,'Distractorii sunt interpretări apropiate.'],['Morisky','aderenţă scăzută']),

q('hta-adv-037',['Conform Cadranului 31.6, diureticele:',
 ['tiazid-like au ca contraindicație absolută guta','tiazid-like pot produce hiperuricemie și hiperglicemie','economisitoare de K sunt contraindicate la K >5,0 mmol/L','economisitoare de K produc hipopotasemie','tiazid-like sunt contraindicate în insuficiența cardiacă'],'ABC',1143,'Cadranul 31.6',
 'Recunoașterea profilului diureticelor.',
 ['Guta este contraindicație absolută.','Hiperuricemia și hiperglicemia sunt citate.','K >5,0 mmol/L și RFGe <30 sunt contraindicații.','Produc hiperpotasemie.','Insuficiența cardiacă este indicație specială.']],
 [8,'Distractorii inversează potasiul și indicația.'],['Gută','ginecomastie']),

q('hta-adv-044',['Conform Cadranului 31.6, beta-blocantele:',
 ['au ca indicație specială insuficiența cardiacă cu FE redusă','au ca contraindicație absolută astmul','includ labetalolul, utilizat în sarcină','au ca indicație specială feocromocitomul suspectat','au ca contraindicație absolută guta'],'ABC',1143,'Cadranul 31.6',
 'Recunoașterea profilului beta-blocantelor.',
 ['IC cu FE redusă și cardiopatia ischemică sunt indicații.','Astmul și BAV înalt sunt contraindicații.','Labetalolul este utilizat în sarcină.','Feocromocitomul este indicația alfa-blocantelor.','Guta contraindică diureticele tiazid-like.']],
 [8,'Distractorii preiau rubrici ale altor clase.'],['Labetalol utilizat','Astm']),

q('hta-adv-054',['Conform Cadranului 31.6:',
 ['IECA pot produce tuse și angioedem','BCC dihidropiridinice pot produce edeme și cefalee','agenții centrali pot produce rebound la întrerupere','alfa-blocantele pot produce incontinență urinară','BCC non-DHP sunt indicați în blocul AV de grad înalt'],'ABCD',1143,'Cadranul 31.6',
 'Recunoașterea efectelor adverse ale antihipertensivelor.',
 ['Tusea și angioedemul sunt citate.','Constipație, cefalee, edeme.','Hipertensiunea de rebound la oprire.','Incontinența urinară este citată.','BAV înalt este contraindicație absolută.']],
 [8,'Singurul distractor inversează contraindicația.'],['rebound','Angioedem']),

q('hta-adv-036',['Denervarea simpatică renală:',
 ['folosește cateterizare endovasculară','poate folosi radiofrecvență, ultrasunete sau alcool','scade TA cu o amploare similară monoterapiei','are siguranță pe termen lung bine stabilită','are studii de prognostic pe evenimente CV'],'ABC',1143,'Abordări viitoare',
 'Evaluarea locului denervării renale.',
 ['Accesul este endovascular.','Energia sau neurotoxinele se aplică pe peretele arterei renale.','Efectul este similar monoterapiei.','Siguranța pe termen lung nu este clară.','Nu există studii de prognostic.']],
 [8,'Distractorii supraestimează dovezile.'],['radio-frecvenţă','monoterapiei']),

q('hta-adv-014',['Hipertensiunea în perioada perioperatorie:',
 ['HTA necontrolată amână frecvent chirurgia electivă','reducerea bruscă preoperatorie nu are beneficiu dovedit','antihipertensivele se continuă de regulă perioperator','HTA necontrolată justifică amânarea chirurgiei de urgență','inducția anesteziei scade de regulă TA cu 30 mmHg'],'ABC',1144,'Perioada perioperatorie',
 'Aplicarea conduitei perioperatorii în hipertensiune.',
 ['HTA necontrolată anulează frecvent chirurgia electivă.','Nu există dovezi clare de beneficiu.','Se continuă, cu excepții.','Nu este motiv de amânare a urgenței.','Inducția poate crește TA cu 30 mmHg.']],
 [8,'Distractorii extind amânarea și inversează efectul inducției.'],['intervenţie chirurgicală de urgenţă','nu există dovezi clare'],[1143]),

q('hta-adv-038',['Intraoperator și postoperator:',
 ['inducția anesteziei poate crește TA cu ≥30 mmHg','în menținerea anesteziei TA tinde să scadă','durerea și omiterea medicației cauzează HTA postoperatorie','postoperator se vizează activ TA <120/80 mmHg','HTA intraoperatorie se tratează înainte de verificarea căii aeriene'],'ABC',1144,'Perioada perioperatorie',
 'Aplicarea conduitei intra- și postoperatorii.',
 ['Activarea simpatică crește TA la inducție.','Simpatoliza și vasodilatația scad TA.','Sunt cele mai frecvente cauze.','Se menține TA sub 180/110 mmHg.','Problemele respiratorii se exclud mai întâi.']],
 [8,'Distractorii schimbă ținta și ordinea evaluării.'],['30 mmHg','dozare inadecvată']),

q('hta-adv-055',['Înaintea unei intervenții elective, medicația antihipertensivă cronică:',
 ['se continuă de regulă perioperator','se oprește cu 7 zile înainte','se înlocuiește cu nifedipină sublinguală','se dublează în dimineața intervenției','se oprește definitiv după intervenție'],'A',1144,'Perioada perioperatorie',
 'Aplicarea conduitei preoperatorii cu antihipertensive.',
 ['Se continuă, cu excepția hipotensiunii sau IRA.','Nu este recomandarea citată.','Nu este recomandarea citată.','Nu este recomandarea citată.','Nu este recomandarea citată.']],
 [8,'Distractorii sunt conduite perioperatorii plauzibile.'],['temporizată','24 de ore preoperator']),

q('hta-adv-039',['Hipertensiunea descoperită în salon, fără urgență hipertensivă:',
 ['nu necesită tratament imediat','se tratează dacă depășește constant 180/110 mmHg','se abordează prin titrarea terapiilor cronice','se tratează cu nitroglicerină sublingual','se tratează cu nifedipină cu acțiune scurtă'],'ABC',1144,'Tensiunea arterială în salon',
 'Aplicarea conduitei în hipertensiunea din salon.',
 ['Fără urgență nu necesită tratament imediat.','Valorile constant >180/110 se abordează.','Se titrează terapiile cronice.','NTG sublingual nu este justificată.','Nifedipina cu acțiune scurtă nu este justificată.']],
 [8,'Distractorii folosesc agenți cu acțiune scurtă.'],['distensia vezicii','nu necesită un tratament imediat']),

q('hta-adv-040',['Urgențele hipertensive:',
 ['apar la o minoritate a pacienților cu TA >180/120 mmHg','au gravitate dependentă de rapiditatea creșterii TA','impun terapie intravenoasă','apar la majoritatea pacienților cu TA >180/120 mmHg','se tratează preferabil cu terapie orală'],'ABC',1144,'Urgențele hipertensive',
 'Recunoașterea urgențelor hipertensive.',
 ['Doar o minoritate au leziune acută de organ.','Rapiditatea și amploarea contează.','Terapia i.v. este indicată.','Doar o minoritate au leziuni acute.','Terapia este intravenoasă.']],
 [8,'Distractorii inversează frecvența și calea.'],['intravenoasă','Rapiditatea']),

q('hta-adv-045',['La femeile tinere, pre-eclampsia poate apărea chiar de la o TA de peste:',
 ['140/90 mmHg','160/110 mmHg','180/110 mmHg','180/120 mmHg','90/60 mmHg'],'A',1144,'Urgențele hipertensive',
 'Aplicarea pragului relativ în pre-eclampsie.',
 ['TA obișnuită poate fi 90–110/60–70, deci >140/90 este relevant.','Nu este pragul citat.','Nu este pragul citat.','Este pragul uzual al urgențelor.','Se încadrează în TA obișnuită a femeilor tinere.']],
 [8,'Distractorii sunt praguri din alte contexte.'],['140/90 mmHg','pre-eclampsia']),

q('hta-adv-041',['Justifică trimiterea la un centru de specialitate:',
 ['HTA necontrolată sub ≥3 clase de antihipertensive','vârsta sub 30–40 de ani','TA normală cu leziuni de organ țintă','TA labilă sau extrem de variabilă','HTA controlată cu o singură clasă'],'ABCD',1144,'Dirijarea către centre de specialitate',
 'Aplicarea criteriilor de trimitere.',
 ['Hipertensiunea rezistentă este criteriu.','Vârsta tânără sugerează cauză secundară.','Leziunile de organ cu TA normală sunt criteriu.','TA labilă este criteriu.','Nu este criteriu de trimitere.']],
 [8,'Singurul distractor descrie un pacient controlat.'],['labilă','injurii ale organelor']),

q('hta-adv-015',['Conform Cadranului 31.7, țintele terapeutice sunt:',
 ['disecția de aortă: TAS 100–120 mmHg, imediat','edemul pulmonar acut: TAS <140 mmHg, imediat','hipertensiunea malignă: TAM −25% în câteva ore','pre-eclampsia: TAS <160 și TAD <105 mmHg','encefalopatia: TAM −25% abia în câteva zile'],'ABCD',1145,'Cadranul 31.7',
 'Aplicarea țintelor din urgențele hipertensive.',
 ['Disecție: TAS 100–120, FC 50–60.','EPA: TAS <140 imediat.','Malignă: TAM −25% în câteva ore.','Pre-eclampsie: <160/105 imediat.','Encefalopatie: TAM −25% imediat.']],
 [8,'Singurul distractor încetinește ținta din encefalopatie.'],['100-120','câteva ore']),

q('hta-adv-042',['Conform Cadranului 31.7, investigația de elecție în encefalopatia hipertensivă este:',
 ['rezonanța magnetică cerebrală','bandeleta urinară pentru proteinurie','angiografia CT a aortei','radiografia toracică','ECG și troponina serică'],'A',1145,'Cadranul 31.7',
 'Alegerea investigației în encefalopatia hipertensivă.',
 ['RMN arată edemul fosei posterioare (SEPR).','Este investigația pre-eclampsiei.','Este investigația disecției.','Este investigația EPA.','Este investigația SCA.']],
 [8,'Distractorii sunt investigațiile celorlalte urgențe.'],['SEPR','fosei cerebrale']),

q('hta-adv-043',['Conform Cadranului 31.7, hipertensiunea malignă:',
 ['asociază retinopatie absentă sau minimă','poate produce injurie renală acută','se tratează cu labetalol sau nicardipină i.v.','necesită reducerea TAM cu 50% imediat','se confirmă prin RMN cerebral'],'BC',1145,'Cadranul 31.7',
 'Recunoașterea hipertensiunii maligne.',
 ['Nu: retinopatia moderat-severă este tipică.','Necroza fibrinoidă poate da IRA.','Labetalol sau nicardipină i.v.','Ținta este −25% în câteva ore.','RMN este investigația encefalopatiei.']],
 [8,'Distractorii umflă ținta și preiau investigația encefalopatiei.'],['necrozei','atenololul']),

q('hta-adv-057',['Conform Cadranului 31.7, disecția acută de aortă:',
 ['poate asocia diferență de TA între membrele superioare','impune controlul frecvenței cardiace la 90–100/min','poate primi vasodilatatoare după controlul frecvenței','se tratează de primă intenție cu NTG și morfină','se confirmă prin RMN cerebral cu edem al fosei posterioare'],'AC',1145,'Cadranul 31.7',
 'Aplicarea conduitei în disecția de aortă.',
 ['Diferența de puls sau TA între brațe.','Nu: ținta FC este 50–60/min.','Vasodilatatoarele se adaugă după controlul FC.','NTG și morfina tratează EPA.','Angio-CT sau ETE arată faldul.']],
 [8,'Distractorii preiau tratamentul EPA și investigația encefalopatiei.'],['transesofagiană','înjunghiere']),

q('hta-adv-056',['Conform Cadranului 31.7, magneziul i.v. face parte din tratamentul:',
 ['pre-eclampsiei, alături de labetalol','edemului pulmonar, alături de NTG','SCA, alături de NTG și labetalol','disecției de aortă, după controlul FC','encefalopatiei, alături de nicardipină'],'A',1145,'Cadranul 31.7',
 'Alegerea tratamentului adjuvant în pre-eclampsie.',
 ['Magneziul previne convulsiile din eclampsie.','Se folosesc NTG și morfina.','Se folosesc NTG și labetalolul.','Se folosește labetalolul.','Se folosesc labetalolul sau nicardipina.']],
 [8,'Distractorii sunt celelalte urgențe din cadran.'],['Magneziu','eclampsie']),

q('hta-adv-029',['Conform Cadranului 31.2:',
 ['coarctația se investighează prin angio-RMN/CT a aortei','stenoza renală poate da edem pulmonar cu cord normal','feocromocitomul se asociază cu neurofibromatoza tip 1','feocromocitomul se investighează inițial prin IGF-1 seric','hiperaldosteronismul primar asociază K+ crescut'],'ABC',1139,'Cadranul 31.2',
 'Recunoașterea cauzelor secundare de hipertensiune.',
 ['Angiografie RMN/CT a întregii aorte.','Edemul pulmonar cu funcție cardiacă normală este citat.','Asocierea cu NF-1 este citată.','Se dozează metanefrinele plasmatice.','K+ este scăzut.']],
 [8,'Distractorii schimbă investigația și potasiul.'],['Metanefrine plasmatice','Coarctaţie']),

q('hta-adv-032',['Conform Cadranului 31.2, investigațiile de elecție sunt:',
 ['hipercortizolism: testul supresiv la doze mici de dexametazonă','acromegalie: IGF-1 seric','apnee de somn: puls-oximetrie nocturnă, apoi polisomnografie','hiperaldosteronism: raportul aldosteron/renină','feocromocitom: scintigrafie MIBG înaintea metanefrinelor'],'ABCD',1139,'Cadranul 31.2',
 'Alegerea investigației pentru cauzele secundare.',
 ['Testul supresiv la doze mici.','IGF-1 seric.','Puls-oximetrie, apoi polisomnografie.','Raportul aldosteron/renină crescut.','MIBG servește localizării după metanefrine.']],
 [8,'Singurul distractor inversează ordinea investigațiilor.'],['IGF-1','Polisomnografie']),
];
