import {advancedQuestion} from './advanced-author';
import type {SourceRow} from './source-author';
const q=(n:number,row:SourceRow,score:number,reason:string,expressions:string[],related:number[]=[])=>
 advancedQuestion('hta',31,-855,`hta-adv-${String(n).padStart(3,'0')}`,row,[score,reason],expressions,undefined,related);

export const HTA_C=[
q(30,['Hipertensiunea în raport cu sexul, etnia și urbanizarea, în datele de deschidere:',
 ['Hormonii sexuali feminini par a proteja împotriva creșterii TA; femeile au valori mai mici până la menopauză','După menopauză, atât prevalența hipertensiunii cât și valorile efective ale TA sunt aproximativ egale cu cele ale bărbaților','Este mai frecventă în anumite grupuri etnice (rasa neagră, afro-caraibienii) și se asociază cu urbanizarea și imigrația','Femeile au TA mai mare decât bărbații înainte de menopauză, etnia neinfluențând prevalența','Urbanizarea scade TA, hormonii feminini crescând-o înainte de menopauză'],'ABC',1134,'Introducere — Sex, etnie, urbanizare',
 'Contrastarea protecției hormonale premenopauză de egalizarea postmenopauză și de excesul din grupurile negre/afro-caraibiene.',
 ['Protecția hormonală și valorile mai mici până la menopauză sunt din închiderea paginii precedente.','Egalizarea postmenopauză a prevalenței și a valorilor este fraza de deschidere.','Etnia neagră/afro-caraibiană și urbanizarea/imigrația completează epidemiologia.','Relația premenopauză este inversată.','Urbanizarea se asociază cu creștere, nu cu scădere, a TA.']],
 8,'Distractorii inversează protecția premenopauză și transformă urbanizarea din factor de risc în protecție.',['hormonii sexuali feminini','până la menopauză'],[1133]),

q(31,['Relația continuă dintre TA și evenimentele cardiovasculare, ilustrată în Figura 31.1, motivează, potrivit capitolului:',
 ['O tendință către inițierea tratamentului chiar la valori-limită mai mici și către utilizarea riscului cardiovascular pentru a decide dacă reducerea TA este benefică în anumite cazuri particulare','Abandonarea oricărui prag numeric, tratamentul începând doar după un eveniment coronarian','Ignorarea riscului CV global, doar valoarea de cabinet numărând','Inițierea doar la TA >220/140 mmHg, relația cu evenimentele fiind în trepte, nu continuă','Utilizarea riscului CV doar după AVC, valorile-limită mai mici fiind abandonate'],'A',1133,'Figura 31.1 — Relația continuă TA–CV',
 'Recunoașterea consecinței clinice a relației continue: praguri mai joase plus decizie ghidată de riscul CV.',
 ['Tendința către valori-limită mai mici și decizia după riscul CV sunt fraza de după figură.','Textul păstrează praguri, dar le coboară; nu așteaptă evenimentul.','Riscul CV global este tocmai instrumentul de decizie.','Relația este continuă, nu în trepte de 220/140.','Valorile-limită mai mici sunt tocmai tendința descrisă, nu un abandon.']],
 8,'Distractorii transformă relația continuă din Fig. 31.1 într-un prag unic 220/140 sau într-un tratament doar post-eveniment.',['Fig. 31.1','riscului cardiovascular'],[1134]),

q(32,['În Cadranul 31.2, asocierile clinic–paraclinic ale unor cauze metabolice, endocrine și respiratorii includ:',
 ['Apneea obstructivă de somn — somnolență diurnă (scor Epworth), sforăit, cefalee matinală; scor Mallampati 3 sau 4; puls-oximetrie nocturnă, apoi polisomnografie; CPAP sau dispozitiv de avansare mandibulară','Hipercortizolismul — distribuție centripetă, hirsutism, striuri pigmentare; test supresiv la doze mici de dexametazonă (cortizolul ar trebui să scadă în mod normal)','Hiperaldosteronismul primar — slăbiciune, K+ scăzut, raport aldosteron/renină crescut; suprarenalectomie laparoscopică dacă secreția este unilaterală','Acromegalia — mâini/picioare mărite, separare interdentală, hemianopsie bitemporală; IGF-1 seric; rezecția glandei pituitare','Apneea de somn se confirmă prin IGF-1, acromegalia prin scor Epworth, iar aldosteronomul prin CPAP'],'ABCD',1139,'Cadranul 31.2 — OSA, Cushing, aldosteron, acromegalie',
 'Perecherea semnelor (Epworth/Mallampati, centripet, K↓, IGF-1) cu testele specifice, fără a amesteca rândurile.',
 ['Epworth, Mallampati, oximetria/polisomnografia și CPAP sunt ale OSA.','Fenotipul cushingoid și testul la dexametazonă sunt ale hipercortizolismului.','K scăzut, ARR crescut și laparoscopia unilaterală sunt ale aldosteronomului.','IGF-1 și rezecția pituitară sunt ale acromegaliei.','Testele sunt permutate între cele patru rânduri.']],
 8,'Distractorul permută IGF-1, Epworth și CPAP între patru rânduri vecine ale aceluiași cadran.',['scor Epworth','IGF-1 seric']),

q(33,['Măsurile de stil de viață din Cadranul 31.2, dincolo de enumerarea medicamentelor care cresc TA, includ:',
 ['Consiliere alimentară ghidată de excreția de sodiu în 24 de ore','Reducerea consumului de alcool sub 14 unități/săptămână','Alcoolul se crește peste 40 de unități/săptămână ca măsură antihipertensivă','Excreția de sodiu în 24 de ore este superfluă, sarea neinfluențând TA','Aderența se îmbunătățește prin evitarea implicării pacientului în decizie'],'AB',1139,'Cadranul 31.2 — Stil de viață',
 'Reținerea sodiului urinar pe 24 de ore și a pragului de alcool <14 unități/săptămână.',
 ['Excreția de Na pe 24 de ore ghidează consilierea alimentară.','<14 unități/săptămână este ținta de alcool din cadran.','Reducerea, nu creșterea, alcoolului scade TA.','Sodiul urinar este tocmai instrumentul de monitorizare a sării.','Cadranul cere implicarea pacientului în decizia terapeutică.']],
 8,'Distractorii inversează pragul de alcool <14 U și anulează sodiul urinar ca ghid dietetic.',['<14 unităţi','Excreţia sodiului în 24h']),

q(34,['Valorile prag de diagnostic din Cadranul 31.3, pe grade, sunt:',
 ['Gradul 1: 140-159 sau 90-99 mmHg la cabinet, respectiv 135-149 sau 85-94 mmHg în ambulator/domiciliu','Gradul 2: 160-179 sau 100-109 mmHg la cabinet, respectiv 150-169 sau 95-104 mmHg extra-cabinet','Hipertensiune severă: >180 sau >110 mmHg la cabinet, respectiv >170 sau >105 mmHg extra-cabinet; sistolică izolată: >140 cu diastolică <90 la cabinet','Gradul 1 începe de la 180/110 mmHg, gradul 2 fiind sub 130/80 mmHg','Sistolica izolată se definește prin diastolică >110 mmHg cu sistolică <130 mmHg'],'ABC',1140,'Cadranul 31.3 — Grade de hipertensiune',
 'Aplicarea ferestrelor 140-159 / 160-179 / >180 și a echivalentelor extra-cabinet, plus sistolica izolată >140/<90.',
 ['Perechea 140-159/90-99 și 135-149/85-94 este a gradului 1.','160-179/100-109 și 150-169/95-104 sunt ale gradului 2.','>180/>110, extra-cabinet >170/>105 și sistolica izolată >140/<90 închid tabelul.','180/110 este hipertensiunea severă, nu gradul 1; 130/80 este TA normală.','Sistolica izolată are sistolică înaltă cu diastolică <90, nu invers.']],
 8,'Distractorii inversează gradul 1 cu hipertensiunea severă și permută sistolică versus diastolică în forma izolată.',['140-159','Hipertensiune sistolică izolată']),

q(35,['Aderența la tratamentul antihipertensiv, în datele din capitol, se caracterizează prin:',
 ['Tehnicile de analiză a medicamentului în plasmă sau urină arată o corelație slabă a chestionarelor/reînnoirii rețetelor cu prezența obiectivă a substanței','Până la două treimi dintre pacienții aflați sub tratament de specialitate nu își administrează, parțial sau total, medicamentele','Controlul tensional obținut doar după o perioadă lungă (>6 luni) asociază risc cardiovascular ridicat, de unde tendința de a abandona monoterapia inițială','Ghidurile ESH/ESC sugerează inițierea cu o combinație în o singură pilulă, asocierile îmbunătățind aderența','Aderența depășește 95% în centrele de specialitate, monoterapia rămânând superioară combinațiilor'],'ABCD',1142,'Aderența — Combinații și monoterapie',
 'Integrarea celor două treimi non-aderente, a pragului >6 luni și a pilulei combinate ESH/ESC.',
 ['Corelația slabă chestionar versus plasmă/urină este explicită.','Cifra de până la două treimi este din același paragraf.','>6 luni și abandonul monoterapiei inițiale sunt argumentul de risc.','Pilula combinată ESH/ESC închide recomandarea.','Textul dă până la două treimi non-aderenți, nu 95% aderenți.']],
 8,'Distractorul transformă eșecul de aderență (două treimi) într-un succes de 95% și reînvie monoterapia.',['două treimi','>6 luni']),

q(36,['Denervarea simpatică renală, în descrierea abordărilor viitoare, constă în:',
 ['Cateterizare endovasculară a nervilor simpatici renali din proximitatea arterei renale, cu eliberare de radiofrecvență, ultrasunete sau neurotoxine (alcool) pe peretele arterial, pentru a anula semnalizarea aferentă către centrii vasomotori','Ablatie chirurgicală deschisă a nervilor vagi cervicali, ca antihipertensiv de primă linie la toți tinerii','Stentarea carotidiană de rutină, care înlocuiește medicamentele','Iradierea externă a hipotalamusului, fără acces endovascular','Injectarea de spironolactonă în artera renală, ca substitut al cateterului'],'A',1143,'Abordări viitoare — Denervare renală',
 'Recunoașterea accesului endovascular pe artera renală și a celor trei forme de energie/neurotoxină.',
 ['Radiofrecvența, ultrasunetele și alcoolul pe peretele arterei renale sunt tehnica citată.','Nervii vagi cervicali nu sunt ținta; procedura nu este primă linie universală.','Stentarea carotidiană nu este metoda descrisă.','Accesul este endovascular renal, nu iradiere hipotalamică.','Spironolactona rămâne medicament oral de linia a patra, nu injectat arterial.']],
 8,'Distractorii mută denervarea de pe artera renală pe vag, carotidă sau hipotalamus.',['Denervarea simpatică renală','radio-frecvenţă']),

q(37,['Contraindicațiile și efectele adverse din Cadranul 31.6 pentru diuretice includ:',
 ['Tiazid-like (indapamidă 1,5-2,5 mg): hiposodemie, hipopotasemie, hiperuricemie, hiperglicemie; contraindicație absolută — guta','Economisitoare de potasiu (spironolactonă 25-50 mg): hiposodemie, hiperpotasemie, ginecomastie; contraindicații — RFGe <30 ml/min și K >5,0 mmol/L','Tiazidele sunt indicate în gută, iar spironolactona este contraindicată în hiperaldosteronismul primar','Indapamida are doza 120-480 mg, ca verapamilul, fără efect pe uricemie','Spironolactona este evitată în hipertensiunea rezistentă, RFGe <30 fiind o indicație'],'AB',1143,'Cadranul 31.6 — Diuretice',
 'Contrastarea profilelor tiazid (gută, uricemie) versus economisitor (RFGe <30, K >5,0), cu dozele indapamidă/spironolactonă.',
 ['Lista de efecte și guta ca CI absolută sunt ale tiazid-like.','RFGe <30 și K >5,0 sunt CI ale economisitoarelor; doza 25-50 mg este exemplul.','Guta contraindică tiazidul; hiperaldosteronismul este indicație specială a spironolactonei.','120-480 mg este doza de verapamil, nu de indapamidă.','Hipertensiunea rezistentă este indicație specială; RFGe <30 este contraindicație.']],
 8,'Distractorii inversează guta și hiperaldosteronismul ca indicație versus contraindicație și mută doza de verapamil pe indapamidă.',['Gută','K >5,0 mmol/L']),

q(38,['În perioada perioperatorie, dincolo de anularea chirurgiei elective, capitolul precizează:',
 ['Inducția anesteziei generale poate crește TA cu 30 mmHg sau mai mult la hipertensivul netratat','În menținerea anesteziei, TA tinde să scadă prin simpatoliză, vasodilatație și pierderea reglării baroreflexe; hipertensivul necontrolat este mai predispus la variații (hipo- sau hipertensiune)','Postoperator, durerea și omiterea medicamentelor antihipertensive sunt cele mai frecvente cauze; fără leziune acută de organ, se urmărește menținerea sub 180/110 mmHg, parțial pentru riscul hemoragic','Inducția scade TA cu 30 mmHg, menținerea crescând-o constant; postoperator se vizează 90/60 mmHg de rutină','Hipertensiunea intraoperatorie se tratează înainte de a verifica calea aeriană sau oxigenul ventilatorului'],'ABC',1144,'Perioada perioperatorie — Intra- și postoperator',
 'Secvența +30 mmHg la inducție, scăderea din menținere și ținta postoperatorie <180/110, fără TOD acută.',
 ['Creșterea de 30 mmHg la inducție este cifra citată.','Scăderea din menținere și variațiile hipertensivului necontrolat completează intraoperatorul.','Durerea, omiterea medicației și <180/110 închid postoperatorul.','Sensurile inducție versus menținere sunt inversate; 90/60 nu este ținta.','Textul cere mai întâi excluderea problemelor de cale aeriană/oxigen, hipertensiunea intraoperatorie ținând cel mai frecvent de dozarea inadecvată a anestezicului.']],
 8,'Distractorii inversează +30 mmHg de la inducție la menținere și coboară ținta postoperatorie la 90/60.',['30 mmHg','180/110 mmHg']),

q(39,['Hipertensiunea la pacientul internat în salon, fără urgență hipertensivă, se abordează astfel:',
 ['În absența unei urgențe sau a unei comorbidități care cere tratament de urgență (ex. tromboliză în AVC acut), hipertensiunea necontrolată nu necesită tratament imediat','Este uzual ca valorile constant peste 180/110 mmHg să fie abordate terapeutic, mai ales fără alt precipitant; se preferă titrarea terapiilor cronice, nu nitroglicerina sublinguală sau nifedipina','NTG sublingual și nifedipina sunt de primă intenție la orice creștere tensională de salon','Orice valoare peste 140/90 mmHg în salon impune vasodilatator cu durată scurtă','Omiterea medicamentelor, durerea, distensia vezicală și sevrajul nu influențează TA de salon'],'AB',1144,'Tensiunea arterială în salonul de spital',
 'Separarea pragului de îngrijorare 180/110 de interdicția vasodilatatoarelor scurte (NTG SL, nifedipină) în hipertensiunea necomplicată de salon.',
 ['Absența tratamentului imediat fără urgență/comorbiditate este prima regulă.','180/110 și preferința pentru terapiile cronice versus NTG/nifedipină sunt din închidere.','Textul spune că NTG SL și nifedipina nu își găsesc justificare.','140/90 nu este pragul de salon citat; vasodilatatorul scurt este evitat.','Acești precipitanți sunt tocmai lista din paragraf.']],
 8,'Distractorii transformă NTG SL/nifedipina din non-indicație în primă intenție la pragul de 140/90.',['180/110 mmHg','nifedipina']),

q(40,['În urgențele hipertensive, capitolul subliniază că:',
 ['Rapiditatea și amploarea creșterii tensionale pot fi mai importante decât nivelul absolut al TA în determinarea gravității leziunii de organ','La femeile tinere, TA obișnuită poate fi 90-110/60-70 mmHg, astfel încât pre-eclampsia poate apărea chiar de la peste 140/90 mmHg','Doar o minoritate dintre pacienții cu TA semnificativ crescută (de obicei >180/120 mmHg) au leziune acută de organ; în urgență este indicată terapia intravenoasă','Pre-eclampsia apare doar peste 220/140 mmHg, TA obișnuită a tinerei fiind 180/110 mmHg','Amploarea creșterii este irelevantă, doar valoarea absolută numărând, iar terapia orală înlocuiește IV-ul în urgență'],'ABC',1144,'Urgențele hipertensive — Principii',
 'Contrastarea ratei de creștere și a bazalei 90-110/60-70 a tinerei de pragul de 140/90 al pre-eclampsiei, versus 180/120 al urgenței clasice.',
 ['Rata de creștere versus valoarea absolută este teza de deschidere.','90-110/60-70 și pre-eclampsia de la 140/90 sunt exemplul obstetrical.','Minoritatea cu TOD la >180/120 și indicația IV închid paragraful.','Bazala tinerei nu este 180/110; pre-eclampsia poate începe de la 140/90.','Textul spune opusul: rata contează, iar IV-ul este indicat în urgență.']],
 8,'Distractorii mută bazala tinerei la 180/110 și anulează importanța ratei de creștere.',['90-110/60-70 mmHg','140/90 mmHg']),

q(41,['Printre motivele de trimitere la un centru de specialitate, dincolo de urgențele hipertensive, se numără:',
 ['Hipertensiune necontrolată sub ≥3 clase diferite de antihipertensive','Vârsta tânără (<30-40 de ani) sau date clinice (ex. suflu abdominal) care sugerează o cauză secundară','Valori normale ale TA, însă cu injurii ale organelor țintă','TA labilă sau extrem de variabilă; intoleranță care împiedică tratamentul după ghid','Trimiterea se rezervă doar octogenarilor cu TA <120/70 mmHg, fără leziuni țintă'],'ABCD',1144,'Dirijarea către centre de specialitate',
 'Reținerea pachetului ≥3 clase, <30-40 de ani, TOD la TA normală și TA labilă, distinct de octogenarul cu țintă joasă.',
 ['≥3 clase definește rezistența ca motiv de trimitere.','Fereastra <30-40 de ani și suflul abdominal sunt exemplele de secundar.','TOD la TA normală este un rând separat.','Labilitatea și intoleranța închid lista.','Textul nu rezervă trimiterea octogenarului hipotensiv fără TOD.']],
 8,'Patru criterii reale de trimitere; distractorul inversează vârsta tânără și TOD-ul către octogenarul fără leziuni.',['<30-40 ani','injurii ale organelor ţintă']),

q(42,['Encefalopatia hipertensivă, în Cadranul 31.7, se recunoaște prin:',
 ['Tulburări vizuale, cefalee, convulsii, confuzie, comă, adesea cu retinopatie moderat-severă','Investigația de elecție: RMN cerebral cu edem al fosei cerebrale posterioare (SEPR)','Ținta: reducerea cu 25% a TAM imediată, cu labetalol sau nicardipină IV','Investigația de elecție este bandeleta urinară, ținta fiind TAS 100-120 mmHg ca în disecție','SEPR contraindică labetalolul, ținta fiind creșterea TAM cu 25%'],'ABC',1145,'Cadranul 31.7 — Encefalopatia hipertensivă',
 'Asocierea clinicii, a SEPR la RMN și a reducerii imediate cu 25% a TAM, distinct de ținta disecției.',
 ['Clinica neurologică plus retinopatia sunt din rândul encefalopatiei.','SEPR (edem de fosă posterioară) este investigația de elecție.','25% TAM imediată cu labetalol/nicardipină este ținta.','Bandeleta și 100-120 mmHg sunt ale pre-eclampsiei, respectiv disecției.','SEPR motivează reducerea, nu creșterea, TAM; labetalolul este terapia de primă intenție.']],
 8,'Distractorii mută ținta 100-120 mmHg a disecției pe encefalopatie și inversează 25% (creștere versus scădere).',['SEPR','edem al fosei cerebrale posterioare']),

q(43,['Hipertensiunea malignă, în notele Cadranului 31.7, se caracterizează prin:',
 ['Tulburări vizuale și cefalee, cu retinopatie moderat-severă','Țintă: reducerea cu 25% a TAM în câteva ore, nu o normalizare bruscă; labetalol sau nicardipină IV (unii autori consideră atenololul oral suficient)','Uneori asociază injurie renală acută prin necroză fibrinoidă a arteriolelor','Ținta este TAS 100-120 mmHg în minute, ca în disecția de aortă','Necroza fibrinoidă contraindică orice scădere a TAM, atenololul oral fiind evitat'],'ABC',1145,'Cadranul 31.7 — Hipertensiunea malignă',
 'Separarea ferestrei „25% TAM în câteva ore” și a necrozei fibrinoide de ținta imediată 100-120 mmHg a disecției.',
 ['Clinica vizuală/cefalee cu retinopatie este rândul de istoric/examen.','25% în câteva ore, IV-ul și nota despre atenolol oral sunt din țintă/terapie.','Necroza fibrinoidă arteriolară explică IRA asociată.','100-120 mmHg imediat este ținta disecției, nu a formei maligne.','Textul cere scădere graduală 25%, nu interzicerea scăderii.']],
 8,'Distractorii aplică ținta de disecție (100-120 mmHg imediat) asupra formei maligne, unde cadranul cere 25% în câteva ore.',['necrozei fibrinoide','câteva ore']),

q(44,['Agenții centrali din Cadranul 31.6, exemplificați prin metildopa, se caracterizează prin:',
 ['Metildopa 250-500 mg de 3 ori pe zi este utilizată în sarcină','Simpaticoliza centrală asociază depresie, amețeli, uscăciune bucală; la întrerupere poate apărea hipertensiune de rebound','Metildopa este contraindicată în sarcină, doza uzuală fiind 2,5-10 mg zilnic ca ramiprilul','Rebound-ul lipsește, clasa fiind indicată în tulburările de dispoziție și în IC cu FE redusă','Alfa-blocantele, nu agenții centrali, poartă riscul de hipertensiune la oprire'],'AB',1143,'Cadranul 31.6 — Agenți centrali',
 'Reținerea dozei de metildopa 250-500 mg × 3 (sarcină) și a hipertensiunii de rebound la întrerupere.',
 ['Doza 250-500 mg × 3 și indicația din sarcină sunt din rândul central.','Efectele (depresie, amețeli, uscăciune) și rebound-ul sunt din aceleași coloane.','2,5-10 mg este doza de ramipril; metildopa este folosită în sarcină.','Tulburările de dispoziție și IC cu FE redusă sunt contraindicații, nu indicații; rebound-ul este notat.','Rebound-ul este atribuit agenților centrali, nu alfa-blocantelor.']],
 8,'Distractorii mută doza de ramipril pe metildopa și transformă contraindicațiile (dispoziție, IC) în indicații.',['Metildopa 250-500','uscăciune bucală']),
];
