import {advancedQuestion} from './advanced-author';
import type {SourceRow} from './source-author';

const EDITION='Chirurgie generală și specialități chirurgicale, ediția pentru rezidențiat MG 2025';
const pdfOffset=(p:number)=>p<=199?p-78:p-82;
const q=(n:number,row:SourceRow,score:number,reason:string,expressions:string[],related:number[]=[])=>
 advancedQuestion('intestin',14,pdfOffset,`intestin-adv-${String(n).padStart(3,'0')}`,row,[score,reason],expressions,undefined,related,'Lawrence',EDITION);

export const INTESTIN_ADVANCED=[
q(1,['Identificați afirmația corectă referitoare la hernia Richter:',
 ['Poate prezenta o masă ireductibilă fără ocluzie intestinală, deoarece lumenul rămâne permeabil de-a lungul părții mezenterice','Este o hernie internă a fosetei paraduodenale, cu risc scăzut de strangulare','Permite reducerea prin presiune chiar după tumefacția peretelui și distensia lumenului','Produce ocluzie completă prin compromiterea întregii circumferințe luminale, similar volvulusului','Apare după bypass gastric laparoscopic, prin defectele mezenterice mici create de procedură'],'A',193,'Ocluzia intestinului subțire — Cauze extrinseci',
 'Diferențierea herniei Richter (porțiune antimezenterică, lumen incomplet compromis) de herniile interne și de încarcerarea cu ocluzie completă.',
 ['Textul descrie hernia Richter ca prindere doar a porțiunii antimezenterice, cu masă ireductibilă fără ocluzie, lumenul rămânând permeabil pe partea mezenterică.','Hernia paraduodenală este o hernie internă cu risc ridicat de strangulare, nu o hernie Richter.','După tumefacție, intestinul încarcerat nu mai poate fi repoziționat; hernia devine ireductibilă.','În hernia Richter lumenul nu este complet compromis, spre deosebire de ocluzia circumferențială.','Hernia internă post-bypass gastric este un exemplu separat de hernie internă, nu de hernie Richter.']],
 8,'Confruntă trei entități herniale din aceeași pagină (Richter, internă, post-bypass) pe un detaliu anatomic ușor de inversat.',['hernie Richter','porţiunea antimezenterică']),

q(2,['Alegeți afirmațiile corecte referitoare la etiologia ocluziei intestinului subțire:',
 ['În țările industrializate, aderențele postoperatorii sunt cea mai frecventă cauză a OIS','Procedeele laparoscopice produc cu aproximativ 80% mai puține aderențe decât procedeele deschise','La nivel mondial, în regiunile cu chirurgie abdominală rară, hernia este cea mai frecventă cauză a OIS','Stricturile maligne asociază frecvent strangulare, deoarece mezenterul este compromis de la debut','Sindromul arterei mezenterice superioare comprimă prima porțiune duodenală după o creștere ponderală rapidă'],'ABC',193,'Ocluzia intestinului subțire — Etiologie',
 'Recunoașterea cauzelor extrinseci dominante (aderențe vs hernie) și a mecanismului SAMS față de stricturile fără strangulare.',
 ['Textul identifică aderențele postoperatorii drept cea mai frecventă cauză de OIS în țările industrializate.','Reducerea cu aproximativ 80% a aderențelor după laparoscopie este citată explicit.','Hernia (inghinală sau ombilicală) este descrisă ca respectiva cauză dominantă unde chirurgia abdominală este rară.','La stricturi mezenterul nu este compromis, iar strangularea este improbabilă.','SAMS comprimă a treia porțiune duodenală după o scădere ponderală rapidă, nu prima porțiune după creștere.']],
 8,'Inversează localizarea SAMS și relația strictură-strangulare, pe fondul contrastului epidemiologic aderențe versus hernie.',['80% mai puţine aderenţe','cea mai frecventă cauză'],[194]),

q(3,['Următoarele afirmații despre strangularea în ocluzia intestinului subțire sunt adevărate:',
 ['Febra, tahicardia, leucocitoza și sensibilitatea abdominală localizată cresc riscul de strangulare de la 7% (un semn) la 67% (toate patru)','Infarctul intestinal poate evolua și în absența acestor patru semne clinice','Prezența unui singur semn din cei patru permite prelungirea tratamentului conservator 72 de ore','În OIS extrem de proximală, vărsăturile persistente produc acidoză metabolică','Riscul de infarct scade dacă ocluzia de grad înalt este tratată non-chirurgical peste 48 de ore'],'AB',195,'Ocluzia intestinului subțire — Fiziopatologie',
 'Aplicarea celor patru markeri de strangulare și recunoașterea că infarctul nu este exclus de absența lor, față de tulburările acido-bazice după sediul ocluziei.',
 ['Intervalul 7–67% în funcție de numărul semnelor este citat explicit.','Textul precizează că infarctul poate evolua chiar în absența semnelor.','Dacă oricare dintre cei patru factori este prezent, se recomandă intervenție chirurgicală promptă.','OIS proximală produce alcaloză metabolică, nu acidoză; acidoza apare în OIS distală.','Riscul de infarct crește, nu scade, dacă ocluzia de grad înalt este tratată non-chirurgical peste 24–48 de ore.']],
 9,'Combină pragul cantitativ 7/67% cu inversarea acido-bazei după sediul ocluziei și cu falsa fereastră de 72 de ore.',['de la 7%','la 67%']),

q(4,['Care dintre următoarele afirmații diferențiază corect etiologiile ischemiei mezenterice acute?',
 ['Embolia AMS are, de regulă, origine cardiacă, este frecvent asociată cu fibrilația atrială și cheagul se depune adesea la originea arterei colice medii','Tromboza AMS începe de obicei la originea AMS și infarctizează întregul teritoriu tributar, inclusiv intestinul subțire distal de Treitz, cecul, colonul ascendent și transversul proximal','Tromboza VMS rezultă adesea din hipercoagulabilitate, cu hipertensiune venoasă, edem parietal și, în final, scăderea fluxului arterial','Ischemia mezenterică non-ocluzivă apare la pacienți în șoc, cu insuficiență cardiacă sau dializați, prin vasospasm splanhnic','Standardul de aur diagnostic este doar examenul clinic, arteriografia mezenterică fiind abandonată'],'ABCD',204,'Ischemia mezenterică acută — Fiziopatologie și diagnostic',
 'Diferențierea emboliei, trombozei AMS, trombozei VMS și ischemiei non-ocluzive, cu recunoașterea arteriografiei ca standard de aur.',
 ['Originea cardiacă, fibrilația atrială și locul de impact la artera colică medie sunt descrise explicit.','Sediul originei AMS și teritoriul de infarct sunt enumerate în text.','Hipercoagulabilitatea (antitrombină III, factor V Leiden) și secvența venoasă→arterială sunt menționate.','Contextul de șoc/dializă și vasospasmul splanhnic definesc forma non-ocluzivă.','Standardul de aur rămâne arteriografia mezenterică; CT-ul de înaltă rezoluție a înlocuit-o ca evaluare de primă intenție, nu ca etalon.']],
 9,'Cere mapa embolie versus tromboză versus VMS versus non-ocluziv, cu un distractor care confundă first-line CT cu standardul de aur.',['angină intestinală','fibrilaţia'],[205]),

q(5,['Selectați enunțurile adevărate despre evaluarea clinică a apendicitei acute:',
 ['Semnul Rovsing este durerea din cadranul inferior drept la palparea cadranului inferior stâng','Semnul psoasului (durere la extensia șoldului drept) sugerează un apendice retrocecal inflamat','La gravide, progresia spre perforație și peritonită asociază o rată a decesului fetal de 35% sau mai mult','Radiografiile abdominale simple sunt investigația de elecție, fecalitul fiind vizibil în majoritatea cazurilor','Clisma baritată are acuratețe aproape perfectă, fără rezultate fals pozitive sau negative'],'ABC',212,'Apendicita acută — Tablou clinic și evaluare',
 'Aplicarea semnelor Rovsing și psoas și a riscului fetal la gravida cu perforație, față de limitele radiografiei și clismei baritate.',
 ['Definiția semnului Rovsing este explicită.','Semnul psoasului este legat de apendicele retrocecal în contact cu iliopsoasul.','Rata decesului fetal de 35% sau mai mult după perforație este citată.','Radiografiile sunt rareori utile; fecalitul apare doar într-un procent mic de cazuri.','Clisma baritată are 10–15% rezultate fals pozitive și fals negative.']],
 8,'Împerechează semne de localizare cu un prag obstetric memorabil și cu două investigații istorice supraevaluate.',['Rovsing','semnul psoasului']),

q(6,['Precizați enunțul corect privind tumorile apendicelui:',
 ['Pentru carcinoidele cu diametrul >2 cm este recomandată hemicolectomia dreaptă, care permite îndepărtarea mai largă a drenajului limfatic','Leziunile carcinoide <2 cm impun hemicolectomie dreaptă de principiu, metastazele limfatice fiind frecvente la acest prag','Rata totală de vindecare a adenocarcinomului apendicular este de 90–95% la 5 ani','Mucocelele nu se leagă de un carcinom de bază apendiculară','Pseudomixomul peritoneal apare doar după rezecția oncologică a leziunilor neperforate'],'A',214,'Tumorile apendicelui',
 'Aplicarea pragului de 2 cm care trece managementul carcinoidului de la apendicectomie simplă la hemicolectomie dreaptă.',
 ['Textul rezervă hemicolectomia dreaptă leziunilor >2 cm, pentru drenajul limfatic mai larg.','Leziunile <2 cm sunt tratate adecvat prin apendicectomie simplă.','Vindecarea adenocarcinomului apendicular este 50–60% la 5 ani, nu 90–95%.','Mucocelele pot fi legate de un carcinom de bază apendiculară (<1% dintre afecțiunile apendicelui).','Pseudomixomul se asociază mucocelului și carcinoamelor perforate, dar și unor leziuni fără perforație francă.']],
 8,'Inversează pragul de 2 cm și supraestimează supraviețuirea adenocarcinomului, pe un capitol unde apendicectomia simplă este alternativa evidentă.',['>2 cm','hemicolectomie dreaptă']),
];
