import {rewriter} from './rewrite-author';
import {RETIRED_INTESTIN} from './retired/intestin';

// Rewritten after the 2026-09-24 cue audit (Lawrence, cap. 14; syllabus p. 193–199 until
// «Boala Crohn a intestinului subțire», 204–214). Small-bowel Crohn items were retired.
const q=rewriter(RETIRED_INTESTIN,(p:number)=>p<=199?p-78:p-82,{shuffle:true});

export const INTESTIN_V2=[
q('intestin-adv-001',['Hernia Richter:',
 ['poate fi ireductibilă fără ocluzie intestinală','este o hernie internă paraduodenală','prinde întreaga circumferință a ansei','apare tipic după bypass gastric laparoscopic','se reduce ușor chiar după edemul peretelui'],'A',193,'Etiologia OIS — Cauze extrinseci',
 'Recunoașterea particularității herniei Richter.',
 ['Este prinsă doar porțiunea antimezenterică, lumenul rămânând permeabil.','Descrie o hernie internă.','Este prinsă doar porțiunea antimezenterică.','Descrie hernia internă post-bypass.','Edemul face hernia ireductibilă.']],
 [8,'Distractorii descriu alte tipuri de hernii.'],['Richter','antimezenterică']),

q('intestin-adv-002',['Etiologia ocluziei intestinului subțire:',
 ['aderențele sunt cauza principală în țările industrializate','laparoscopia produce cu ~80% mai puține aderențe','hernia este cauza principală unde chirurgia abdominală e rară','stricturile maligne produc frecvent strangulare','carcinomatoza este cauza principală în țările industrializate'],'ABC',193,'Etiologia OIS',
 'Fixarea cauzelor principale ale OIS.',
 ['Aderențele sunt cea mai frecventă cauză în țările industrializate.','Laparoscopia produce cu ~80% mai puține aderențe.','Hernia predomină unde chirurgia abdominală e rară.','Mezenterul nu este compromis, strangularea fiind improbabilă.','Carcinomatoza este o cauză frecventă, dar nu principală.']],
 [8,'Distractorii inversează ierarhia cauzelor.'],['80%','inghinală sau']),

q('intestin-adv-008',['Aderențele postoperatorii:',
 ['apar la cel mult 10% după o laparotomie','depășesc 90% după două sau mai multe intervenții','produc ulterior simptome de OIS la 3–9% dintre operați','produc ulterior simptome de OIS la 30–40% dintre operați','apar mai frecvent după laparoscopie'],'BC',193,'Etiologia OIS — Aderențele',
 'Fixarea datelor despre aderențele postoperatorii.',
 ['Nu: apar la cel puțin două treimi după o laparotomie.','Depășesc 90% după două sau mai multe intervenții.','3–9% dezvoltă ulterior simptome de OIS.','Proporția citată este 3–9%.','Laparoscopia produce mai puține aderențe.']],
 [8,'Distractorii umflă riscul și inversează efectul laparoscopiei.'],['două treimi','3-9%']),

q('intestin-adv-052',['Pot produce aderențe cu OIS fără intervenție chirurgicală:',
 ['diverticulita acută','boala inflamatorie pelvină','endometrioza','volvulusul congenital','hernia Richter'],'ABC',193,'Etiologia OIS — Aderențele',
 'Recunoașterea bolilor inflamatorii care produc aderențe.',
 ['Diverticulita acută este citată.','Boala inflamatorie pelvină este citată.','Endometrioza este citată.','Nu este o boală inflamatorie peritoneală.','Nu produce aderențe inflamatorii.']],
 [8,'Distractorii sunt cauze de OIS, dar nu inflamatorii.'],['endometrioza','boala inflamatorie pelvină']),

q('intestin-adv-007',['Ocluzia cu ansă închisă:',
 ['are risc crescut de strangulare','este o ocluzie parțială cu rezolvare conservatoare frecventă','este obstruată doar proximal, cu ansa distală liberă','definește ileusul paralitic fără obstacol mecanic','se tratează conservator 1–5 zile ca aderențele'],'A',193,'Ocluzia intestinului subțire',
 'Recunoașterea riscului ocluziei cu ansă închisă.',
 ['Are risc crescut de strangulare și viză chirurgicală imediată.','Este o obstrucție completă.','Este obstruată atât proximal, cât și distal.','Este o obstrucție mecanică.','Impune chirurgie imediată.']],
 [8,'Distractorii contrazic definiția.'],['ansă închisă','viză chirurgicală imediată']),

q('intestin-adv-009',['Carcinomatoza peritoneală ca și cauză de OIS:',
 ['se asociază de regulă cancerului ovarian sau de colon','este de regulă unifocală și curabilă','justifică tratament paliativ al obstrucției','este cauza principală de OIS în țările industrializate','se tratează curativ prin rezecție radicală'],'AC',194,'Etiologia OIS — Cauze extrinseci',
 'Aplicarea conduitei în OIS prin carcinomatoză.',
 ['Se asociază de regulă cancerului ovarian sau de colon.','Nu: este adesea multifocală și incurabilă.','Tratamentul paliativ rămâne indicat.','Aderențele sunt cauza principală.','Procesul este adesea incurabil.']],
 [8,'Distractorii supraestimează curabilitatea și frecvența.'],['ovarian','paliativ']),

q('intestin-adv-010',['În sindromul arterei mezenterice superioare este comprimată:',
 ['a treia porțiune a duodenului','prima porțiune a duodenului','a doua porțiune a duodenului','a patra porțiune a duodenului','prima ansă jejunală după Treitz'],'A',194,'Etiologia OIS — Cauze extrinseci',
 'Recunoașterea segmentului comprimat în SAMS.',
 ['D3 este comprimată între AMS și aortă.','Nu este segmentul citat.','Nu este segmentul citat.','Nu este segmentul citat.','Nu este segmentul citat.']],
 [8,'Distractorii sunt segmente învecinate.'],['a treia porţiune a duodenului','scăderi ponderale rapide']),

q('intestin-adv-012',['Volvulusul intestinului subțire:',
 ['se produce de obicei în jurul axului mezenteric','formează o ansă închisă cu risc mare de strangulare','apare doar pe intestin fără anomalii congenitale','are risc redus de strangulare, mezenterul fiind cruțat','se rezolvă conservator în aproximativ 80%'],'AB',194,'Etiologia OIS — Volvulusul',
 'Recunoașterea mecanismului și a riscului volvulusului.',
 ['Răsucirea se produce de obicei în jurul axului mezenteric.','Formează o ansă închisă cu risc mare de strangulare.','Nu: poate urma bridelor sau malrotațiilor congenitale.','Mezenterul este adesea implicat.','80% este rata ocluziei aderențiale parțiale.']],
 [8,'Distractorii confundă volvulusul cu ocluzia aderențială.'],['axului mezenteric','malrotaţiilor']),

q('intestin-adv-011',['Stricturile intestinului subțire:',
 ['benigne au drept cauză principală boala Crohn','nu apar după enterita postradioterapie','pot fi produse de ulcerele din consumul de AINS','produc frecvent strangulare a ansei','maligne se rezolvă de obicei nechirurgical'],'AC',194,'Etiologia OIS — Cauze intrinseci',
 'Recunoașterea etiologiei și evoluției stricturilor.',
 ['Boala Crohn este cea mai frecventă cauză benignă.','Nu: stricturile pot urma enteritei postradioterapie.','Ulcerele din consumul de AINS sunt citate.','Strangularea este improbabilă.','Majoritatea stricturilor maligne necesită chirurgie.']],
 [8,'Distractorii inversează riscul și conduita.'],['postradioterapie','AINS']),

q('intestin-adv-062',['Cauzele intraluminale de OIS includ:',
 ['fitobezoarii din fibre vegetale','ileusul biliar la vârstnici','corpii străini opriți la valvă','compresia duodenală prin artera mezenterică','carcinomatoza peritoneală'],'ABC',194,'Etiologia OIS — Cauze intraluminale',
 'Diferențierea cauzelor intraluminale de cele extrinseci.',
 ['Fitobezoarii sunt agregate de fibre vegetale.','Ileusul biliar apare mai ales la vârstnici.','Valva ileocecală poate opri corpii străini mari.','Este o cauză extrinsecă.','Este o cauză extrinsecă.']],
 [8,'Distractorii sunt cauze extrinseci.'],['Fitobezoarele','ileusul biliar']),

q('intestin-adv-033',['Deshidratarea din OIS se datorează:',
 ['vărsăturilor repetate','scăderii absorbției intestinale','secreției stimulate de distensia lumenului','pierderilor în spațiul al treilea','creșterii absorbției de sodiu și clor'],'ABCD',195,'Fiziopatologie',
 'Explicarea mecanismelor deshidratării în OIS.',
 ['Vărsăturile sunt mecanismul principal.','Absorbția este redusă.','Distensia stimulează hormonal secreția.','Edemul parietal și transsudatul produc pierderi în spațiul trei.','Absorbția ionilor este redusă.']],
 [8,'Singurul distractor inversează absorbția.'],['spaţiul al treilea','hipovolemie severă']),

q('intestin-adv-032',['În OIS extrem de proximală, vărsăturile persistente produc:',
 ['alcaloză metabolică','acidoză metabolică','acidoză lactică','alcaloză respiratorie','acidoză respiratorie'],'A',195,'Fiziopatologie',
 'Aplicarea tulburărilor acido-bazice după sediul ocluziei.',
 ['Sucul proximal este acid; vărsăturile produc alcaloză metabolică.','Apare în ocluzia distală.','Semnalează ischemia.','Nu este tulburarea citată.','Nu este tulburarea citată.']],
 [8,'Distractorii sunt tulburări acido-bazice reale.'],['alcaloză','foarte acid']),

q('intestin-adv-003',['Strangularea în OIS:',
 ['este mai frecventă în ocluziile cu ansă închisă','are risc de 67% când toate cele patru semne sunt prezente','poate apărea și fără cele patru semne','are risc de 67% când un singur semn este prezent','permite amânarea operației dacă un semn este prezent'],'ABC',195,'Fiziopatologie — Strangularea',
 'Interpretarea semnelor de strangulare.',
 ['Strangularea este mai frecventă în ansa închisă și ocluzia completă.','Febră, tahicardie, leucocitoză și sensibilitate: 67%.','Infarctul poate evolua și în absența semnelor.','Un singur semn corespunde riscului de 7%.','Oricare semn impune intervenția promptă.']],
 [8,'Distractorii inversează semnificația unui singur semn.'],['67%','strangulare']),

q('intestin-adv-054',['Durerea inițială din OIS acută este periombilicală deoarece:',
 ['inervația autonomă derivă din mezenteron','peritoneul parietal este iritat de la debut','distensia colonului precede distensia ileală','mezenterul este comprimat de la debut','ansa proximală se află sub ombilic'],'A',195,'Tablou clinic — Anamneză',
 'Explicarea localizării durerii viscerale.',
 ['Embriologia inervației autonome explică durerea periombilicală.','Durerea somatică sugerează ischemia.','Nu este mecanismul citat.','Nu este mecanismul citat.','Nu este mecanismul citat.']],
 [8,'Distractorii sunt mecanisme plauzibile, necitate.'],['periombilicală','inervaţie autonomă']),

q('intestin-adv-053',['Conform Tabelului 14-1, ocluzia proximală cu ansă deschisă:',
 ['produce vărsături mari, bilioase și dese','poate evolua fără distensie','produce durere colicativă agravată de vărsătură','produce vărsături fecaloide de la debut','produce distensie marcată'],'AB',195,'Tabelul 14-1',
 'Aplicarea semnelor de ocluzie după sediu.',
 ['Vărsăturile sunt mari, bilioase și dese.','Distensia poate lipsi.','Nu: durerea colicativă este ameliorată de vărsătură.','Vărsăturile fecaloide apar în ocluzia distală.','Distensia marcată apare distal.']],
 [8,'Distractorii preiau semnele ocluziei distale.'],['bilioase','ameliorată de']),

q('intestin-adv-034',['Simptomele OIS:',
 ['vărsăturile pot deveni fecaloide în ocluziile distale','distensia este mai evidentă în ocluziile distale','tranzitul poate persista în ocluzia parțială','distensia este maximă în ocluziile proximale','absența tranzitului apare imediat în ocluzia completă'],'ABC',196,'Tablou clinic — Anamneză',
 'Corelarea simptomelor cu sediul ocluziei.',
 ['Descompunerea bacteriană face vărsăturile fecaloide.','Distensia este mai evidentă distal.','Scaunul, gazele și diareea pot persista.','Distensia poate fi minimă proximal.','Poate să nu fie imediată, colonul golindu-se.']],
 [8,'Distractorii inversează sediul și cronologia.'],['fecaloid','parţială']),

q('intestin-adv-035',['Examenul pacientului cu OIS:',
 ['poate arăta mucoase uscate și tahicardie','relevă inițial borborisme și sunete înalte','poate arăta sensibilitate care cedează după decompresie','cu semne peritoneale impune chirurgie de urgență','relevă zgomote intestinale accentuate în peritonită'],'ABCD',196,'Tablou clinic — Examinare',
 'Interpretarea examenului obiectiv în OIS.',
 ['Deshidratarea produce mucoase uscate și tahicardie.','Inițial apar sunete înalte și borborisme.','Sensibilitatea difuză cedează după decompresie dacă nu există ischemie.','Semnele peritoneale impun chirurgie de urgență.','Activitatea intestinală scade în peritonită.']],
 [8,'Singurul distractor inversează auscultația.'],['borborisme','teama']),

q('intestin-adv-036',['Explorarea radiologică inițială în OIS:',
 ['include radiografii abdominale în clino- și ortostatism','include radiografie toracică în ortostatism','arată nivele hidroaerice care denotă alterarea peristalticii','poate sugera ansa închisă prin anomalii persistente pe seriate','arată de obicei intestinul distal destins'],'ABCD',196,'Aspecte radiologice',
 'Aplicarea radiografiilor simple în OIS.',
 ['Se fac radiografii în clino- și ortostatism.','Radiografia toracică în ortostatism este inclusă.','Nivelele hidroaerice denotă alterarea peristalticii.','Persistența localizată pe seriate sugerează ansa închisă.','Intestinul distal este colabat.']],
 [8,'Singurul distractor inversează aspectul distal.'],['clinostatism','Nivelele hidroaerice']),

q('intestin-adv-027',['Semnul vârtejului pe CT sugerează:',
 ['volvulusul','invaginația','diverticulul Meckel','ileusul paralitic','carcinomatoza peritoneală'],'A',196,'Aspecte radiologice — CT',
 'Interpretarea semnului vârtejului.',
 ['Rotirea mezenterului sugerează volvulus, ansă închisă sau hernie internă.','Nu este semnul citat.','Nu este semnul citat.','Nu este semnul citat.','Nu este semnul citat.']],
 [8,'Distractorii sunt cauze reale de OIS.'],['Rotirea mezenterului','volvulus']),

q('intestin-adv-055',['Investigațiile cu contrast ale intestinului subțire în OIS:',
 ['sunt utile în simptomele obstructive parțiale persistente','ajută la diferențierea ileusului de obstrucția mecanică','se fac după excluderea obstrucției colonice','sunt de primă intenție în urgența majoră','se fac înaintea clismei și a angiografiei mezenterice'],'ABC',197,'Aspecte radiologice — Contrast',
 'Aplicarea indicațiilor studiilor cu contrast.',
 ['Sunt utile în simptomele parțiale persistente.','Ajută la diferențierea ileusului paralitic.','Obstrucția colonică și boala mezenterică se exclud înainte.','Nu sunt necesare de obicei în urgența majoră.','Contrastul ar masca angiografia.']],
 [8,'Distractorii inversează ordinea investigațiilor.'],['boala ocluzivă mezenterică','ileusului paralitic']),

q('intestin-adv-037',['Examinările de laborator în OIS:',
 ['acidoza hiperkalemică este frecventă','leucocitoza persistentă poate semnala ischemie','acidoza lactică poate semnala ischemie','absența acidozei lactice exclude infarctul intestinal','hiperamilazemia marcată exclude diagnosticul de OIS'],'BC',197,'Examinările de laborator',
 'Interpretarea analizelor în OIS.',
 ['Nu: alcaloza hipokalemică de contracție este frecventă.','Leucocitoza persistentă poate semnala ischemie.','Acidoza lactică poate semnala ischemie.','Infarctul poate exista fără acidoză.','Hiperamilazemia poate apărea în OIS.']],
 [8,'Distractorii supraestimează valoarea de excludere a analizelor.'],['contracţie','acidoză']),

q('intestin-adv-016',['Ileusul paralitic:',
 ['poate fi produs de hipokaliemie și hipomagneziemie','arată radiologic dilatare difuză, fără zonă de tranziție','se recunoaște prin absența aerului în colon','arată o zonă de tranziție clară pe CT','este un diagnostic diferențial rar al OIS'],'AB',197,'Diagnosticul diferențial',
 'Diferențierea ileusului paralitic de OIS mecanică.',
 ['Deficitele de K, Ca, Mg și fosfat produc ileus.','Radiografia arată dilatare difuză fără zonă de tranziție.','Nu: ileusul se recunoaște prin prezența aerului în sigmoid și rect.','Zona de tranziție caracterizează OIS mecanică.','Este cel mai frecvent diagnostic diferențial.']],
 [8,'Distractorii preiau semnele OIS mecanice.'],['hipotiroidismul','sigmoid distal'],[198]),

q('intestin-adv-038',['Reechilibrarea în OIS și ileusul postoperator:',
 ['normovolemia se restabilește înaintea potasiului','diureza de cel puțin 0,5 mL/kg/oră indică resuscitare adecvată','alvimopanul scade durata ileusului postoperator','potasiul se corectează agresiv înaintea volemiei','protocolul de circuit rapid impune sonda nazogastrică'],'ABC',198,'Tratament — Reechilibrarea',
 'Aplicarea principiilor reechilibrării.',
 ['Normovolemia precede înlocuirea agresivă a potasiului.','Diureza ≥0,5 mL/kg/oră indică resuscitare adecvată.','Alvimopanul scade durata IPO.','Potasiul poate crește rapid fără perfuzie renală.','Protocolul evită sondele nazogastrice.']],
 [8,'Distractorii inversează ordinea și protocolul.'],['0,5 mL/kg/oră','alvimopan']),

q('intestin-adv-056',['Decompresia nazogastrică în OIS:',
 ['controlează vărsăturile','crește volumul lichidelor care pot fi aspirate','crește riscul de microaspirație','închide joncțiunea gastroesofagiană','elimină riscul de aspirație'],'AC',198,'Tratament — Decompresia',
 'Recunoașterea efectelor decompresiei nazogastrice.',
 ['Controlează vărsăturile.','Nu: decompresia reduce volumul lichidelor care pot fi aspirate.','Suprimă reflexul de vărsătură și deschide joncțiunea GE.','Deschide joncțiunea GE.','Riscul de microaspirație crește.']],
 [8,'Distractorii inversează efectul asupra joncțiunii GE.'],['microaspiraţie','joncţiunii gastroesofagiene']),

q('intestin-adv-017',['Studiile randomizate recente arată rezoluție mai rapidă a OIS după:',
 ['contrast hidrosolubil oral','decompresie nazogastrică prelungită','regim strict nimic per os','clismă baritată precoce','antibioterapie profilactică'],'A',198,'Tratament',
 'Recunoașterea rolului contrastului hidrosolubil oral.',
 ['Contrastul hidrosolubil oral a accelerat rezoluția și a scăzut rata operațiilor.','Nu este intervenția citată.','Dogma NPO este contestată.','Nu este intervenția citată.','Nu este intervenția citată.']],
 [8,'Distractorii sunt măsuri tradiționale.'],['hidrosolubile oral','dogma']),

q('intestin-adv-015',['Șansa de rezolvare conservatoare a unei OIS parțiale aderențiale este de aproximativ:',
 ['80%','20%','50%','95%','35–40%'],'A',199,'Tratament — Conservator',
 'Fixarea prognosticului tratamentului conservator.',
 ['OIS parțială aderențială se rezolvă în ~80%.','Nu este valoarea citată.','Nu este valoarea citată.','Nu este valoarea citată.','Nu este valoarea citată.']],
 [8,'Distractorii sunt valori plauzibile.'],['80%','aderenţială']),

q('intestin-adv-039',['Reducerea herniilor încarcerate în OIS:',
 ['se încearcă dacă este posibilă','poate fi o reducere în masă, cu conținut compromis','permite externarea imediată','vindecă definitiv, fără reparare ulterioară','este contraindicată la orice hernie încarcerată'],'AB',199,'Tratament — Herniile',
 'Aplicarea conduitei în herniile încarcerate.',
 ['Herniile încarcerate se reduc dacă este posibil.','Sacul se poate reduce cu conținutul compromis.','Nu: reducerea impune monitorizare atentă ulterioară.','Hernia se repară după remiterea obstrucției.','Reducerea se încearcă dacă este posibilă.']],
 [8,'Distractorii contrazic repararea și indicația.'],['reducere în masă','unitate']),

q('intestin-adv-057',['Se pregătesc pentru chirurgie promptă pacienții cu OIS:',
 ['fără antecedente chirurgicale și fără hernie evidentă','cu obstrucție completă sau de grad înalt','cu agravare clinică sub tratament conservator','cu ocluzie precoce postoperatorie','cu carcinomatoză cunoscută și ocluzii recurente'],'ABC',199,'Tratament — Indicații chirurgicale',
 'Aplicarea indicațiilor chirurgiei în OIS.',
 ['Mulți au neoplazii sau hernii interne.','Riscul de remitere e scăzut și cel de ischemie crescut.','Agravarea impune chirurgia.','Ocluzia precoce postoperatorie se temporizează.','Pot fi candidați pentru tratament conservator mai lung.']],
 [8,'Distractorii sunt situații de temporizare.'],['hernie internă','grad înalt']),

q('intestin-adv-018',['Ocluzia precoce postoperatorie:',
 ['se rezolvă de obicei în 2 săptămâni','se tratează inițial conservator','face periculoasă reintervenția după prima săptămână','impune laparotomie în primele 48 de ore','se rezolvă de obicei în 48 de ore'],'ABC',199,'Tratament — Ocluzia precoce postoperatorie',
 'Aplicarea temporizării în ocluzia precoce postoperatorie.',
 ['Majoritatea se rezolvă în 2 săptămâni.','Necesită temporizare.','Aderențele acute cresc riscul de enterotomii.','Se temporizează.','Intervalul citat este de 2 săptămâni.']],
 [8,'Distractorii scurtează intervalul și grăbesc chirurgia.'],['2 săptămâni','enterotomii']),

q('intestin-adv-058',['La laparotomia pentru OIS:',
 ['antibioticele acoperă aerobii și anaerobii gram-negativi','viabilitatea îndoielnică se evaluează cu fluoresceină sau Doppler','suspiciunea persistentă justifică reintervenția la 24 de ore','intestinul cu viabilitate îndoielnică se rezecă de principiu','fluoresceina este un test infailibil'],'ABC',199,'Tratament — Laparotomia',
 'Aplicarea evaluării intraoperatorii a viabilității.',
 ['Antibioticele acoperă aerobii și anaerobii gram-negativi.','Fluoresceina și Doppler completează evaluarea clinică.','Reintervenția la 24 de ore poate fi indicată.','Se rezecă intestinul compromis, nu cel îndoielnic.','Niciun test nu este infailibil.']],
 [8,'Distractorii supraestimează testele și rezecția.'],['fluoresceină','anaerobilor gram-negativi']),

q('intestin-adv-040',['În chirurgia OIS:',
 ['rezecțiile extinse se evită când restantul se apropie de 100 cm','invaginația adultului impune rezecție','invaginația copilului se poate reduce prin clismă','invaginația adultului se reduce prin clismă pneumatică','anastomoza primară este de obicei imposibilă'],'ABC',199,'Tratament — Laparotomia',
 'Aplicarea principiilor rezecției în OIS.',
 ['Sub 100 cm crește dependența de nutriția parenterală.','Adultul are frecvent o leziune în punctul de rezistență.','La copil, clisma pneumatică sau cu contrast o poate reduce.','La adult se recomandă rezecția.','Anastomoza primară este în general posibilă.']],
 [8,'Distractorii inversează conduita adult–copil.'],['clismei pneumatice','punctul de rezistenţă']),

q('intestin-adv-059',['Laparoscopia în OIS:',
 ['reușește într-un număr modest de cazuri','este facilitată de distensia intestinală','servește mai ales ocluziilor aderențiale simple','este preferată în abdomenul multiplu operat','a înlocuit laparotomia în strangulare'],'AC',199,'Tratament — Laparoscopia',
 'Recunoașterea locului laparoscopiei în OIS.',
 ['Succesul este documentat într-un număr modest de cazuri.','Nu: laparoscopia este limitată de distensia intestinală.','Este utilă în ocluziile aderențiale necomplicate și proximale.','Abdomenul multiplu operat limitează tehnica.','Nu a înlocuit laparotomia.']],
 [8,'Distractorii supraestimează indicațiile.'],['număr modest','ostil']),

q('intestin-adv-019',['După laparotomia pentru OIS:',
 ['mortalitatea este sub 1% în OIS necomplicată','mortalitatea depășește 25% după strangulare sau perforație','bariera cu hialuronat crește aderențele','bariera cu hialuronat reduce ocluzia recurentă','mortalitatea este de 10% în OIS necomplicată'],'AB',199,'Complicații',
 'Fixarea mortalității și a rolului barierelor antiaderențiale.',
 ['Mortalitatea este <1% în OIS necomplicată.','Depășește 25% după strangulare sau perforație.','Nu: bariera cu hialuronat reduce aderențele.','Nu s-a asociat cu scăderea ocluziei recurente.','Mortalitatea este <1%.']],
 [8,'Distractorii supraestimează efectul barierei.'],['hialuronat','25%']),

q('intestin-adv-004',['Etiologia ischemiei mezenterice acute:',
 ['embolia AMS este de obicei de origine cardiacă','embolul se oprește adesea la originea arterei colice medii','tromboza AMS începe de obicei la originea arterei','tromboza VMS rezultă adesea din hipercoagulabilitate','embolul se oprește de obicei la originea AMS'],'ABCD',204,'Ischemia mezenterică acută — Fiziopatologie',
 'Diferențierea mecanismelor ischemiei mezenterice acute.',
 ['Embolia este de obicei cardiacă, frecvent cu fibrilație atrială.','Cheagul se depune adesea la originea colicei medii.','Tromboza începe de obicei la originea AMS.','Tromboza VMS rezultă din hipercoagulabilitate.','Tromboza, nu embolia, începe la originea AMS.']],
 [8,'Singurul distractor confundă embolia cu tromboza.'],['fibrilaţia atrială','colice medii'],[205]),

q('intestin-adv-029',['Durerea clasică din ischemia mezenterică acută este:',
 ['disproporționată față de examenul fizic','localizată în fosa iliacă dreaptă','ameliorată de vărsătură','postprandială, cronică, cu frică de alimentație','asociată precoce cu apărare musculară'],'A',205,'Ischemia mezenterică acută — Tablou clinic',
 'Recunoașterea durerii din ischemia mezenterică acută.',
 ['Durerea bruscă, severă, cu examen neconcludent este clasică.','Nu este localizarea citată.','Descrie ocluzia proximală.','Descrie angina intestinală cronică.','Peritonita indică infarct deja instalat.']],
 [8,'Distractorii sunt tipuri reale de durere abdominală.'],['disproporţionată','neconcludentă']),

q('intestin-adv-044',['Ischemia mezenterică acută:',
 ['poate evolua spre necroză doar după peste 7 zile','prin tromboză venoasă are debut insidios','non-ocluzivă are ca trăsătură principală instabilitatea hemodinamică','prin embolie are debut insidios, de săptămâni','cu peritonită are de regulă prognostic bun'],'BC',205,'Ischemia mezenterică acută — Tablou clinic',
 'Recunoașterea evoluției și a formelor clinice.',
 ['Nu: poate evolua spre necroză după peste 12 ore.','Tromboza VMS are debut insidios.','IMNO se caracterizează prin instabilitate hemodinamică.','Embolia are debut brusc.','Peritonita indică infarct și mortalitate mare.']],
 [8,'Distractorii inversează debutul și prognosticul.'],['12 ore','insidios']),

q('intestin-adv-061',['Examinările de laborator în ischemia mezenterică acută:',
 ['nu pot stabili singure diagnosticul de IMA','cu valori normale nu exclud boala','cu acidoză metabolică persistentă o sugerează','arată constant acid lactic crescut de la debut','normale permit amânarea investigațiilor'],'ABC',205,'Ischemia mezenterică acută — Laborator',
 'Interpretarea analizelor în ischemia mezenterică.',
 ['Nicio analiză nu stabilește diagnosticul.','Valorile normale nu exclud boala.','Durerea cu acidoză metabolică persistentă impune suspiciunea.','Acestea sunt modificări tardive, neobligatorii.','Așteptarea întârzie diagnosticul.']],
 [8,'Distractorii supraestimează analizele.'],['nicio analiză','acidoză metabolică persistentă']),

q('intestin-adv-028',['Tratamentul ischemiei mezenterice acute:',
 ['embolia AMS impune embolectomie prin laparotomie','tromboza AMS necesită adesea bypass sau stent','tromboza VMS se tratează inițial cu heparină','ischemia non-ocluzivă beneficiază de digoxină','intestinul cu aspect ischemic se excizează imediat'],'ABC',205,'Ischemia mezenterică acută — Tratament',
 'Aplicarea tratamentului după etiologie.',
 ['Embolectomia se face prin laparotomie.','AMS îngustată aterosclerotic necesită revascularizare.','Heparina IV este prima intenție.','Digoxina agravează vasospasmul.','Intestinul ischemic poate rămâne viabil după revascularizare.']],
 [8,'Distractorii agravează vasospasmul sau rezecția.'],['embolectomia','heparină intravenoasă']),

q('intestin-adv-045',['Pe cateterul mezenteric, după revascularizare, se poate administra:',
 ['papaverină','digoxină','vasopresoare α-adrenergice','heparină nefracționată','alteplază'],'A',206,'Ischemia mezenterică acută — Tratament',
 'Recunoașterea tratamentului vasospasmului după revascularizare.',
 ['Papaverina ameliorează vasospasmul.','Agravează spasmul.','Agravează spasmul.','Nu este agentul citat.','Nu este agentul citat.']],
 [8,'Distractorii agravează spasmul sau nu sunt citați.'],['papave','vasospasmul']),

q('intestin-adv-030',['Evaluarea endoscopică a intestinului subțire:',
 ['capsula transmite două imagini pe secundă','capsula nu permite biopsii','enteroscopia cu balon dublu vede până la două treimi din intestin','capsula permite polipectomia','enteroscopia cu balon dublu vede întregul intestin'],'ABC',206,'Tumorile intestinului subțire — Endoscopia',
 'Compararea capsulei cu enteroscopia cu balon dublu.',
 ['Capsula transmite două imagini pe secundă.','Nu permite biopsii sau gesturi terapeutice.','Enteroscopia cu balon dublu vede până la două treimi.','Nu permite gesturi terapeutice.','Vizualizează până la două treimi.']],
 [8,'Distractorii supraestimează capacitățile.'],['două imagini pe secundă','acordeon']),

q('intestin-adv-046',['Tumorile intestinului subțire:',
 ['sunt mai rare decât cele colorectale','se diagnostichează frecvent prin enterografie CT','benigne sunt mult mai frecvente decât cele maligne','maligne sunt mai frecvente decât cele benigne','sunt mai frecvente datorită tranzitului lent'],'ABC',206,'Tumorile intestinului subțire',
 'Fixarea epidemiologiei tumorilor intestinului subțire.',
 ['Sunt mai rare decât cele colorectale.','Enterografia CT este frecvent folosită.','Benignele sunt mult mai frecvente.','Benignele sunt mai frecvente.','Tranzitul este rapid, ceea ce le face rare.']],
 [8,'Distractorii inversează frecvența și mecanismul.'],['timp de tranzit scăzut','enterografie CT']),

q('intestin-adv-065',['Tumorile benigne ale intestinului subțire:',
 ['sunt în majoritate asimptomatice','afectează egal ambele sexe','au incidența maximă în decada a șasea','au incidența maximă în decada a doua','predomină la femei'],'ABC',206,'Tumorile benigne',
 'Fixarea caracteristicilor epidemiologice ale tumorilor benigne.',
 ['Majoritatea sunt asimptomatice.','Ambele sexe sunt afectate egal.','Incidența maximă este în decada a șasea.','Vârful este în decada a șasea.','Ambele sexe sunt afectate egal.']],
 [8,'Distractorii schimbă vârsta și sexul.'],['decada a şasea','Ambele sexe']),

q('intestin-adv-066',['Tumorile benigne ale intestinului subțire:',
 ['lipoamele sunt mai frecvente la bărbați','hemangioamele sunt adesea multiple','adenoamele viloase au risc de malignizare de ~30%','GIST-urile au originea în celulele Cajal','hemangioamele reprezintă ~50% din leziunile benigne'],'ABCD',207,'Tumorile benigne',
 'Diferențierea tipurilor de tumori benigne.',
 ['Lipoamele sunt mai frecvente la bărbați.','Hemangioamele sunt adesea multiple (Osler-Weber-Rendu).','Adenoamele viloase au risc global de 30%.','GIST-urile au originea în celulele interstițiale Cajal.','Hemangioamele reprezintă 5%.']],
 [8,'Singurul distractor umflă proporția hemangioamelor.'],['Osler-Weber-Rendu','30%']),

q('intestin-adv-068',['Adenocarcinoamele intestinului subțire:',
 ['reprezintă aproximativ jumătate din tumorile maligne','sunt mai frecvente în duoden','au supraviețuire la 5 ani de 10–30%','au supraviețuire la 5 ani de 70–90%','se prezintă frecvent cu sângerare masivă'],'ABC',207,'Tumorile maligne — Adenocarcinoamele',
 'Fixarea caracteristicilor adenocarcinomului intestinal.',
 ['Reprezintă aproximativ jumătate din malignele intestinului subțire.','Sunt mai frecvente în duoden.','Supraviețuirea la 5 ani este 10–30%.','Supraviețuirea este 10–30%.','Sângerarea masivă este rară.']],
 [8,'Distractorii umflă prognosticul și sângerarea.'],['10-30%','duoden']),

q('intestin-adv-031',['Tumorile carcinoide ale intestinului subțire:',
 ['au originea în celulele Kulchitsky','metastazează la 90% când depășesc 2 cm','sunt mai frecvente în ileon','se prezintă cel mai frecvent prin ocluzie','metastazează la 90% când depășesc 1 cm'],'ABCD',207,'Tumorile carcinoide',
 'Recunoașterea caracteristicilor tumorilor carcinoide.',
 ['Au originea în celulele Kulchitsky.','Metastazele apar la 90% peste 2 cm.','Sunt mai frecvente în ileon.','Ocluzia, prin reacție desmoplastică, este prezentarea cea mai frecventă.','Sub 1 cm metastazează doar 2%.']],
 [8,'Singurul distractor schimbă pragul.'],['Kulchitsky','desmoplastice']),

q('intestin-adv-047',['Sindromul carcinoid:',
 ['necesită metastaze hepatice în cazul unui primar intestinal','se confirmă prin 5-HIAA urinar','poate produce leziuni cutanate asemănătoare pelagrei','poate fi declanșat de alcool sau anestezie','apare frecvent dintr-un primar ileal fără metastaze'],'ABCD',208,'Sindromul carcinoid',
 'Explicarea condițiilor de apariție și confirmare.',
 ['Ficatul epurează serotonina portală; sunt necesare metastaze hepatice.','5-HIAA urinar confirmă sindromul.','Devierea triptofanului produce leziuni pelagroide.','Efortul, emoția, alcoolul și anestezia pot declanșa episoade.','Ficatul epurează serotonina.']],
 [8,'Singurul distractor ignoră epurarea hepatică.'],['5-HIAA','pelagra'],[207]),

q('intestin-adv-048',['Limfomul intestinului subțire:',
 ['are aici cea mai comună localizare extraganglionară','ileonul este cel mai frecvent afectat','reprezintă 10–15% din cancerele intestinului subțire','jejunul este segmentul cel mai frecvent afectat','reprezintă aproximativ 50% dintre toate limfoamele'],'ABC',208,'Limfomul',
 'Fixarea epidemiologiei limfomului intestinal.',
 ['Este cea mai comună localizare extraganglionară.','Ileonul, prin plăcile Peyer, este cel mai afectat.','Reprezintă 10–15% din cancerele intestinului subțire.','Ileonul este cel mai afectat.','Doar 5% dintre limfoame se află aici.']],
 [8,'Distractorii schimbă sediul și proporția.'],['extraganglionară','plăcilor Peyer']),

q('intestin-adv-064',['Limfomul intestinului subțire:',
 ['se prezintă ca urgență abdominală la până la o pătrime','poate perfora prin liză tumorală sub chimioterapie','are supraviețuire medie de peste 10 ani la diagnosticul imagistic','are supraviețuire la 5 ani de 20–40% după rezecția de urgență','se tratează de elecție prin rezecție chirurgicală'],'ABCD',209,'Limfomul',
 'Recunoașterea prezentării și prognosticului limfomului.',
 ['Până la o pătrime se prezintă ca urgență.','Chimioterapia poate produce perforație prin liză.','Supraviețuirea medie depășește 10 ani.','După rezecția de urgență supraviețuirea este 20–40%.','Diagnosticul imagistic duce la chimioterapie.']],
 [8,'Singurul distractor schimbă tratamentul de elecție.'],['o pătrime','20-40%']),

q('intestin-adv-070',['GIST-urile intestinului subțire:',
 ['au prognostic mai grav decât cele gastrice','recidivează la ~50% în primii 2 ani după excizie','exprimă proteina c-kit (CD117)','se tratează cu sunitinib la eșecul imatinibului','se tratează de primă intenție cu sunitinib'],'ABCD',209,'Tumorile stromale gastrointestinale',
 'Recunoașterea prognosticului și tratamentului GIST.',
 ['Prognosticul este mai grav decât al celor esofagiene și gastrice.','50% recidivează în primii 2 ani.','Exprimă universal c-kit.','Sunitinibul se folosește la refractari sau intoleranți.','Imatinibul este prima intenție.']],
 [8,'Singurul distractor inversează linia terapeutică.'],['imatinib','50%']),

q('intestin-adv-020',['Regula lui 2 pentru diverticulul Meckel include:',
 ['localizarea la maximum 60 cm de VIC','localizarea la maximum 2 cm de ligamentul Treitz','prevalența de ~20% în populație','frecvența de 2 ori mai mare la femei','simptomatologia la 2% dintre vârstnici'],'A',209,'Diverticulul Meckel',
 'Aplicarea regulii lui 2.',
 ['Este localizat la maximum 60 cm de VIC.','Nu este localizarea citată.','Prevalența este ~2%.','Este de 2 ori mai frecvent la bărbați.','Simptomele sunt extrem de rare la vârstnici.']],
 [8,'Distractorii deformează elementele regulii.'],['regula lui 2','60 cm']),

q('intestin-adv-021',['Diverticulul Meckel:',
 ['conține cel mai frecvent mucoasă gastrică ectopică','sângerează mai ales la copiii sub 2 ani','se diagnostichează scintigrafic cu pertechnetat în ~90%','se află pe marginea mezenterică a jejunului','devine mai frecvent simptomatic odată cu vârsta'],'ABC',209,'Diverticulul Meckel',
 'Recunoașterea caracteristicilor diverticulului Meckel.',
 ['Mucoasa gastrică este cea mai frecventă (50%).','Hemoragia apare mai ales sub 2 ani.','Scintigrafia diagnostichează ~90%.','Se află pe marginea antimezenterică a ileonului.','Frecvența simptomelor scade cu vârsta.']],
 [8,'Distractorii inversează localizarea și evoluția.'],['antimezenterică','gastrică (50%)'],[210]),

q('intestin-adv-049',['Diverticulul Meckel ca punct de invaginație:',
 ['se poate prezenta cu scaun în jeleu de coacăze','permite reducerea prin clismă la copil dacă intestinul e viabil','impune ulterior rezecția diverticulului','nu mai necesită rezecție după reducerea prin clismă','se reduce la adult prin clismă, fără rezecție'],'ABC',210,'Diverticulul Meckel — Tablou clinic',
 'Aplicarea conduitei în invaginația pe diverticul Meckel.',
 ['Scaunul în jeleu de coacăze și masa dreaptă sunt tipice.','Clisma poate reduce invaginația la copil.','Rezecția previne recurența.','Rezecția este necesară după reducere.','Rezecția este necesară.']],
 [8,'Distractorii omit rezecția.'],['coacăze','benzi mezodiverticulare']),

q('intestin-adv-050',['Malrotația cu volvulus al mezenteronului:',
 ['are ca simptom precoce vărsăturile bilioase','se evaluează cel mai rapid prin radiografia tractului GI superior','se tratează prin secționarea benzilor Ladd','include de obicei apendicectomia','lasă cecul fixat în fosa iliacă dreaptă'],'ABCD',210,'Malrotația',
 'Recunoașterea prezentării și tratamentului volvulusului de mezenteron.',
 ['Vărsăturile bilioase sunt precoce.','Explorarea radiografică a tractului GI superior este cea mai rapidă.','Se secționează benzile Ladd.','Apendicectomia evită confuzia diagnostică ulterioară.','Cecul este fixat în cadranul superior drept.']],
 [8,'Singurul distractor inversează poziția cecului.'],['Ladd','vărsăturile bilioase']),

q('intestin-adv-022',['Sindromul intestinului scurt la adult se definește prin intestin subțire restant sub:',
 ['180 cm','100 cm','60 cm','250 cm','300 cm'],'A',211,'Sindromul intestinului scurt',
 'Aplicarea definiției sindromului de intestin scurt.',
 ['Sub 180 cm definește sindromul la adult.','100 cm este pragul NPT fără colon și VIC.','60 cm este pragul NPT cu colon și VIC competente.','Nu este pragul citat.','Nu este pragul citat.']],
 [8,'Distractorii sunt pragurile pentru NPT.'],['Sindromul intestinului scurt','vitaminei B12']),

q('intestin-adv-051',['Apendicita acută:',
 ['este cea mai frecventă urgență chirurgicală','afectează mai ales vârstele de 5–35 de ani','are risc de perforație aproape dublu la copii și vârstnici','afectează mai frecvent femeile decât bărbații','se prezintă de obicei după 72 de ore de la debut'],'ABC',211,'Apendicita acută — Incidență',
 'Fixarea epidemiologiei apendicitei acute.',
 ['Este cea mai frecventă urgență chirurgicală.','Majoritatea au 5–35 de ani.','Prezentarea atipică dublează aproape riscul de perforație.','Afectează 6,7% dintre femei și 8,6% dintre bărbați.','Se prezintă de obicei în 24–48 de ore.']],
 [8,'Distractorii inversează sexul și intervalul.'],['6,7%','5-35']),

q('intestin-adv-071',['Apendicele și apendicita:',
 ['artera apendiculară provine din artera ileocolică','foliculii limfatici sunt foarte numeroși la 10–20 de ani','infecția necontrolată poate produce pileflebită','artera apendiculară provine direct din aorta abdominală','perforația apare în până la 80% din cazuri'],'ABC',211,'Apendicita acută — Anatomie și fiziopatologie',
 'Recunoașterea anatomiei și complicațiilor apendicitei.',
 ['Artera apendiculară provine din ileocolică.','Foliculii sunt foarte numeroși la 10–20 de ani.','Infecția poate produce pileflebită și abcese hepatice.','Provine din artera ileocolică.','Perforația apare în până la 20%.']],
 [8,'Distractorii schimbă originea arterială și frecvența perforației.'],['ileocolică','pileflebita']),

q('intestin-adv-023',['Obstrucția lumenului apendicular:',
 ['se datorează cel mai frecvent hiperplaziei limfoide','poate fi produsă de fecaliți, observați la 35%','poate evolua spre perforație în până la 20%','se datorează cel mai frecvent tumorilor apendiculare','se datorează fecaliților la 60% dintre pacienți'],'ABC',211,'Apendicita acută — Fiziopatologie',
 'Recunoașterea etiologiei obstrucției apendiculare.',
 ['Hiperplazia limfoidă (60%) este cea mai frecventă.','Fecaliții apar histologic la 35%.','Gangrena și perforația apar în până la 20%.','Hiperplazia limfoidă este cea mai frecventă.','60% este proporția hiperplaziei limfoide.']],
 [8,'Distractorii permută proporțiile.'],['Hiperplazia limfoidă','35%']),

q('intestin-adv-005',['Evaluarea clinică a apendicitei acute:',
 ['semnul Rovsing: durere în FID la palparea FIS','semnul psoasului sugerează un apendice retrocecal','semnul obturatorului sugerează un apendice pelvin','semnul psoasului sugerează un apendice pelvin','radiografia simplă arată de obicei fecalitul'],'ABC',212,'Apendicita acută — Tablou clinic',
 'Interpretarea semnelor clinice ale apendicitei.',
 ['Rovsing: durere în FID la palparea FIS.','Psoasul sugerează apendice retrocecal.','Obturatorul sugerează inflamație pelvină.','Psoasul sugerează poziția retrocecală.','Radiografiile sunt rareori utile.']],
 [8,'Distractorii permută semnele.'],['Rovsing','obturator']),

q('intestin-adv-024',['Apendicita acută:',
 ['punctul McBurney este la o treime de spina iliacă antero-superioară','la gravide, perforația se asociază cu deces fetal ≥35%','managementul non-operator evită apendicectomia la 70–90%','fecaliții recomandă tratamentul non-operator','clisma baritată nu are rezultate fals pozitive sau fals negative'],'ABC',212,'Apendicita acută — Evaluare și tratament',
 'Aplicarea evaluării și a opțiunilor terapeutice.',
 ['McBurney este la o treime de SIAS spre ombilic.','Rata decesului fetal este ≥35%.','70–90% evită apendicectomia.','Fecaliții contraindică tratamentul non-operator.','Are 10–15% fals pozitive și fals negative.']],
 [8,'Distractorii contrazic contraindicațiile și limitele.'],['spina iliacă','70-90%'],[211,213]),

q('intestin-adv-006',['Carcinoidul apendicular cu diametrul peste 2 cm se tratează prin:',
 ['hemicolectomie dreaptă','apendicectomie simplă','rezecție ileocecală','colectomie totală','octreotid, fără rezecție'],'A',214,'Tumorile apendicelui',
 'Alegerea tratamentului carcinoidului apendicular după dimensiune.',
 ['Peste 2 cm se recomandă hemicolectomia dreaptă.','Se aplică leziunilor <2 cm.','Nu este tratamentul citat.','Nu este tratamentul citat.','Nu este tratamentul citat.']],
 [8,'Distractorul principal este tratamentul leziunilor mici.'],['hemicolectomie dreaptă','<2 cm'],[213]),

q('intestin-adv-026',['Mucocelele și adenocarcinomul apendicular:',
 ['mucocelul poate ascunde un carcinom apendicular','carcinomul reprezintă sub 1% din afecțiunile apendicelui','leziunile perforate se pot asocia cu pseudomixom peritoneal','adenocarcinomul are vindecare la 5 ani de 50–60%','adenocarcinomul are vindecare la 5 ani de 90–95%'],'ABCD',214,'Tumorile apendicelui',
 'Recunoașterea tumorilor mucinoase apendiculare.',
 ['Mucocelele pot fi legate de un carcinom de bază.','Carcinomul reprezintă <1% din afecțiunile apendicelui.','Leziunile perforate se asociază cu pseudomixom.','Vindecarea la 5 ani este 50–60%.','Vindecarea este 50–60%.']],
 [8,'Singurul distractor umflă prognosticul.'],['burta de jeleu','50-60%']),
];
