import {chapter} from './author';
export const MEDICINE_A=[
...chapter('sepsis','https://www.sccm.org/clinical-resources/guidelines/guidelines/surviving-sepsis-guidelines-2021',`
Ce componentă bacteriană activează predominant răspunsul inflamator prin TLR4 în infecțiile cu bacili Gram-negativi? | Lipopolizaharidul~Peptidoglicanul~Acidul teichoic~Capsula polizaharidică~Flagelina | A | Lipidul A al lipopolizaharidului este endotoxina recunoscută prin complexul TLR4.
Un pacient septic rămâne hipotensiv după resuscitare volemică adecvată. Care vasopresor este uzual prima alegere? | Dopamina~Noradrenalina~Dobutamina~Fenilefrina~Izoprenalina | B | Noradrenalina crește tonusul vascular; dobutamina este predominant inotropă.
Ce parametru aparține scorului qSOFA? | Puls peste 100/min~Temperatură peste 38°C~Leucocitoză~Frecvență respiratorie de cel puțin 22/min~Lactat peste 4 mmol/L | D | qSOFA include tahipnee, tensiune sistolică de cel mult 100 mmHg și alterarea stării mentale.
Ce mecanism explică rezistența MRSA la majoritatea beta-lactaminelor? | Modificarea proteinei de legare a penicilinei~Blocarea subunității ribozomale 30S~Pierderea acidului folic~Modificarea ADN-girazei~Inhibarea sintezei ergosterolului | A | PBP2a, codificată de mecA, are afinitate redusă pentru beta-lactaminele uzuale.
Ce clasă antibiotică are efect bactericid dependent de concentrație și risc de ototoxicitate? | Macrolide~Tetracicline~Aminoglicozide~Lincosamide~Oxazolidinone | C | Aminoglicozidele necesită atenție la funcția renală, concentrații și toxicitatea auditivă.
Ce modificări pot contribui la hipotensiunea din șocul septic? | Vasodilatație sistemică~Creșterea permeabilității capilare~Depresie miocardică~Creșterea obligatorie a rezistenței vasculare~Reducerea volumului circulant eficient | ABCE | Vasoplegia, extravazarea lichidului și disfuncția cardiacă pot coexista.
Care afirmații diferențiază bacteriemia de sepsis? | Bacteriemia desemnează bacterii în sânge~Sepsisul presupune disfuncție de organ~Hemocultura negativă exclude sepsisul~Bacteriemia poate fi tranzitorie~Orice bacteriemie impune diagnosticul de șoc septic | ABD | Bacteriemia este o constatare microbiologică; sepsisul este un sindrom clinic de disfuncție de organ.
Ce măsuri favorizează interpretarea corectă a hemoculturilor? | Recoltarea înaintea antibioticelor când nu întârzie tratamentul~Antisepsia tegumentului~Recoltarea din situsuri distincte~Folosirea unui volum adecvat~Interpretarea oricărui stafilococ coagulazo-negativ drept patogen cert | ABCD | Contaminarea și volumul insuficient afectează rezultatul; semnificația se stabilește clinic.
Ce caracteristici susțin șocul septic, conform definiției Sepsis-3? | Necesitatea vasopresorului pentru MAP de cel puțin 65 mmHg~Lactat peste 2 mmol/L în pofida corecției hipovolemiei~Febră obligatorie~Sepsis prezent~Hemocultură pozitivă obligatorie | ABD | Definiția asociază sepsisul, necesarul vasopresor și hiperlactatemia după resuscitare adecvată.
În administrarea empirică a antibioticelor pentru sepsis sunt relevante: | Focarul probabil~Expunerile antibiotice recente~Epidemiologia rezistenței locale~Funcția renală~Alegerea exclusiv după valoarea CRP | ABCD | Spectrul și dozele se adaptează focarului, riscului microbiologic și farmacocineticii.
Ce situații pot necesita control intervențional al sursei? | Abces intraabdominal~Colangită obstructivă~Țesut necrotic infectat~Bacteriurie asimptomatică izolată~Cateter intravascular infectat | ABCE | Colecțiile, obstrucția și materialul infectat pot întreține infecția în ciuda antibioticelor.
Care sunt particularități ale beta-lactaminelor? | Inhibă sinteza peretelui bacterian~Eficacitatea depinde de timpul peste CMI~Au activitate directă asupra ribozomului 50S~Pot determina reacții de hipersensibilitate~Sunt active asupra virusurilor anvelopate | ABD | Beta-lactaminele vizează peretele bacterian și au farmacodinamică predominant dependentă de timp.
Ce reacții adverse trebuie urmărite la vancomicină? | Nefrotoxicitate~Reacție legată de perfuzarea rapidă~Ruptură de tendon ca toxicitate caracteristică~Necesitatea monitorizării expunerii în infecții grave~Colorarea portocalie a secrețiilor | ABD | Vancomicina necesită dozare atentă; reacția de perfuzie nu echivalează automat cu alergia IgE.
Care asocieri antibiotic–țintă sunt corecte? | Macrolide–subunitatea 50S~Aminoglicozide–subunitatea 30S~Fluorochinolone–ADN-girază~Beta-lactamine–membrană nucleară~Metronidazol–lezarea ADN în germeni susceptibili | ABCE | Clasele antibiotice au ținte bacteriene distincte; bacteriile nu au membrană nucleară.
În reevaluarea antibioterapiei după identificarea agentului sunt adecvate: | Restrângerea spectrului când este posibil~Adaptarea la antibiogramă~Reevaluarea duratei~Menținerea obligatorie a combinației inițiale~Reconsiderarea diagnosticului dacă evoluția este nefavorabilă | ABCE | De-escaladarea reduce expunerea inutilă fără a compromite acoperirea agentului documentat.
Ce constatări pot sugera disfuncție de organ în infecția severă? | Creșterea creatininei~Trombocitopenie~Hipoxemie~Creșterea bilirubinei~Leucocitoză izolată fără altă modificare | ABCD | Afectarea renală, hematologică, respiratorie și hepatică intră în evaluarea disfuncției de organ.
Care afirmații despre procalcitonină sunt corecte? | Poate crește în infecții bacteriene sistemice~Se interpretează împreună cu tabloul clinic~Valoarea mică exclude sigur infecția precoce~Dinamica poate ajuta decizia de oprire a antibioticelor~Înlocuiește recoltarea culturilor | ABD | Un biomarker izolat nu confirmă și nu exclude toate infecțiile; evoluția sa poate sprijini reevaluarea.
La pacientul septic cu insuficiență renală, antibioterapia necesită: | Ajustarea unor doze de întreținere~Considerarea epurării extrarenale~Monitorizarea medicamentelor cu fereastră terapeutică îngustă~Reducerea identică a dozei pentru orice antibiotic~Reevaluare pe măsura schimbării funcției renale | ABCE | Clearance-ul diferă între antibiotice și se modifică dinamic în boala critică.
Care germeni sunt în mod obișnuit acoperiți de metronidazol? | Bacteroides fragilis~Clostridioides difficile sensibil~Pseudomonas aeruginosa~Enterococcus faecalis~Fusobacterium | ABE | Metronidazolul are activitate asupra anaerobilor susceptibili, nu asupra aerobului Pseudomonas.
Ce elemente susțin monitorizarea răspunsului la resuscitare? | Perfuzia periferică~Diureza~Evoluția lactatului~Starea de conștiență~Normalizarea izolată a temperaturii drept dovadă suficientă | ABCD | Răspunsul se apreciază integrat; normalizarea unui singur semn nu dovedește corecția hipoperfuziei.
`),
...chapter('electroliti','https://www.msdmanuals.com/professional/nephrology/acid-base-regulation-and-disorders/acid-base-disorders',`
Un pacient are Na 140, Cl 104 și HCO₃ 12 mmol/L. Care este hiatusul anionic calculat fără potasiu? | 12 mmol/L~16 mmol/L~24 mmol/L~36 mmol/L~48 mmol/L | C | Hiatusul anionic este Na minus suma Cl și HCO₃: 140−104−12=24.
La pH 7,29, PaCO₂ 60 mmHg și bicarbonat crescut compensator, tulburarea primară este: | Acidoză respiratorie~Alcaloză respiratorie~Alcaloză metabolică~Acidoză metabolică~Tulburare fără acidemie | A | Creșterea PaCO₂ explică acidemia; bicarbonatul crescut reprezintă compensare renală.
Ce mecanism explică hiponatremia din SIADH? | Pierdere izolată de sodiu prin piele~Retenție de apă mediată de vasopresină~Deficit de cortizol obligatoriu~Exces primar de aldosteron~Aport insuficient de potasiu | B | În SIADH retenția de apă diluează sodiul, în condiții de osmolalitate plasmatică redusă.
Ce complicație este asociată corecției prea rapide a hiponatremiei cronice? | Edem pulmonar unilateral~Encefalopatie Wernicke~Hemoragie subarahnoidiană~Sindrom de demielinizare osmotică~Meningită aseptică | D | Adaptarea cerebrală la hiponatremia cronică face periculoasă creșterea rapidă a natremiei.
Care soluție are rol imediat de stabilizare miocardică în hiperkaliemia cu modificări ECG? | Glucoză 5% singură~Bicarbonat oral~Gluconat de calciu intravenos~Clorură de potasiu~Apă liberă | C | Calciul reduce excitabilitatea miocardică anormală, dar nu elimină potasiul din organism.
Care sunt cauze de acidoză metabolică cu hiatus anionic crescut? | Cetoacidoză~Acidoză lactică~Intoxicație cu metanol~Diaree izolată~Insuficiență renală avansată | ABCE | Acumularea de anioni nemăsurați crește hiatusul; diareea produce tipic acidoză hipercloremică.
Ce situații favorizează alcaloza metabolică? | Vărsături prelungite~Aspirație nazogastrică~Diuretice de ansă~Diaree cu pierdere de bicarbonat~Exces mineralocorticoid | ABCE | Pierderea de acid gastric, contracția volemică și pierderea renală de hidrogen favorizează alcaloza.
În hipokaliemie pot fi întâlnite: | Unde U proeminente~Slăbiciune musculară~Ileus~Unde T ascuțite ca modificare tipică~Aritmii | ABCE | Deficitul de potasiu afectează mușchiul, motilitatea intestinală și repolarizarea cardiacă.
Ce medicamente favorizează hiperkaliemia? | Spironolactonă~Inhibitori ai enzimei de conversie~Amilorid~Furosemid ca efect direct obișnuit~Blocanți ai receptorului angiotensinei | ABCE | Blocarea sistemului renină–angiotensină și diureticele economisitoare de potasiu reduc excreția sa.
În SIADH sunt compatibile următoarele rezultate: | Osmolalitate plasmatică scăzută~Urină inadecvat concentrată~Euvolemie clinică~Hipernatremie persistentă~Excluderea insuficienței suprarenale și hipotiroidismului sever | ABCE | Diagnosticul presupune hiponatremie hipotonică și excluderea cauzelor endocrine care o pot imita.
Care afirmații despre hipernatremie sunt corecte? | Indică deficit relativ de apă~Poate apărea în diabetul insipid~Setea protejează pacientul cu acces la apă~Se tratează prin creșterea aportului de sodiu~Formele cronice necesită corecție controlată | ABCE | Hipernatremia reflectă de regulă pierdere de apă sau acces insuficient la aceasta.
Ce teste ajută la diferențierea cauzelor hiponatremiei? | Osmolalitate plasmatică~Osmolalitate urinară~Sodiu urinar~Evaluarea volemiei~D-dimeri ca test etiologic principal | ABCD | Tonicitatea, răspunsul renal și statusul volemic ghidează diagnosticul diferențial.
Ce intervenții deplasează potasiul din spațiul extracelular în celule? | Insulină cu glucoză~Beta-2-agonist~Hemodializă prin mecanism de redistribuție~Calciu intravenos prin captare celulară~Corectarea unei acidoze metabolice în contexte selectate | ABE | Insulina și stimularea beta-2 redistribuie potasiul; dializa îl elimină, iar calciul stabilizează membrana.
Care cauze pot produce hipocalcemie? | Hipoparatiroidism~Deficit de vitamina D~Insuficiență renală cronică~Hiperparatiroidism primar necomplicat~Pancreatită acută | ABCE | Deficitul PTH/vitaminei D, retenția de fosfat și saponificarea pot reduce calcemia.
Ce constatări sunt compatibile cu hipocalcemia simptomatică? | Parestezii periorale~Spasm carpopedal~Prelungirea QT~Semnul Trousseau~Scurtarea QT ca modificare caracteristică | ABCD | Hipocalcemia crește excitabilitatea neuromusculară și prelungește repolarizarea ventriculară.
În hipomagneziemie sunt relevante: | Poate întreține hipokaliemia~Poate determina hipocalcemie~Poate favoriza torsada vârfurilor~Exclude tulburările nutriționale~Poate apărea după pierderi digestive | ABCE | Deficitul de magneziu afectează homeostazia potasiului și secreția sau acțiunea PTH.
Ce situații pot determina alcaloză respiratorie? | Hiperventilație anxioasă~Embolie pulmonară~Hipoxemie la altitudine~Deprimare respiratorie prin opioide~Ventilație mecanică excesivă | ABCE | Eliminarea crescută a CO₂ produce alcaloză; opioidele tind să determine retenție de CO₂.
Care afirmații despre compensarea acido-bazică sunt corecte? | Se poate estima matematic~Compensarea respiratorie este relativ rapidă~Compensarea renală necesită timp~Normalizează obligatoriu pH-ul~O compensare necorespunzătoare sugerează tulburare mixtă | ABCE | Compensarea reduce modificarea pH-ului; abaterile de la răspunsul așteptat sugerează al doilea proces.
La interpretarea calciului total trebuie considerate: | Concentrația albuminei~Calciul ionizat în situații selectate~Modificările pH-ului~Echivalența obligatorie cu fracția activă~Contextul clinic | ABCE | Calciul total depinde de legarea proteică; fracția ionizată este activă biologic.
Ce constatări susțin depleția volumului extracelular? | Hipotensiune ortostatică~Tahicardie compensatorie~Scăderea presiunii venoase jugulare~Edem periferic obligatoriu~Reducerea diurezei | ABCE | Pierderea volemică reduce întoarcerea venoasă și poate activa conservarea renală de apă și sodiu.
`),
...chapter('ati','https://www.msdmanuals.com/professional/critical-care-medicine/respiratory-failure-and-mechanical-ventilation/overview-of-respiratory-failure',`
Care este caracteristica definitorie a insuficienței respiratorii de tip II? | Hipocapnie~Hipercapnie~Hiperglicemie~Methemoglobinemie~Alcaloză metabolică | B | Tipul II presupune ventilație alveolară insuficientă cu retenție de CO₂.
Un pacient cu pneumonie are hipoxemie și PaCO₂ normală sau scăzută. Încadrarea uzuală este: | Insuficiență respiratorie tip I~Insuficiență respiratorie tip II obligatorie~Hipoventilație izolată~Acidoză respiratorie cronică~Ventilație alveolară absentă | A | Insuficiența hipoxemică poate exista fără retenție de CO₂.
Care parametru se folosește pentru clasificarea severității ARDS în definiția Berlin? | Raport PaO₂/FiO₂~Raport FEV₁/FVC~Hemoglobina glicată~Presiunea pulsului~Raport uree/creatinină | A | Severitatea hipoxemiei se exprimă prin PaO₂/FiO₂ în condițiile de suport respirator specificate.
La calcularea volumului curent protector în ARDS se utilizează predominant: | Greutatea corporală actuală~Greutatea corporală prezisă după înălțime și sex~Suprafața arsă~Circumferința abdominală~Greutatea maximă din antecedente | B | Volumul pulmonar se corelează cu înălțimea, nu cu excesul de țesut adipos.
În intoxicația cu opioide, mecanismul principal al hipercapniei este: | Șunt intracardiac~Hipoventilație alveolară~Creștere izolată a difuziunii~Hiperventilație reflexă~Scăderea producției de CO₂ | B | Deprimarea centrului respirator scade ventilația alveolară și crește PaCO₂.
Care mecanisme produc hipoxemie? | Dezechilibru ventilație/perfuzie~Șunt dreapta–stânga~Limitarea difuziunii~Hipoventilație alveolară~Creșterea concentrației inspirate de oxigen | ABCD | Hipoxemia poate avea mecanisme diferite; oxigenul inspirat suplimentar este o intervenție terapeutică.
Ce elemente sunt compatibile cu definiția Berlin a ARDS? | Debut în prima săptămână după agresiune~Opacități pulmonare bilaterale~Edem explicat integral de insuficiența cardiacă~Hipoxemie cuantificată prin PaO₂/FiO₂~Necesitatea excluderii unei explicații exclusiv hidrostatice | ABDE | ARDS reprezintă leziune pulmonară acută cu edem neexplicat complet prin insuficiență cardiacă.
Ce agresiuni pot precipita ARDS? | Sepsis~Aspirație gastrică~Pneumonie severă~Traumatism major~Rinită alergică izolată | ABCD | Atât leziunile pulmonare directe, cât și inflamația sistemică pot iniția ARDS.
În ventilația protectoare pentru ARDS se urmăresc: | Volume curente reduse~Limitarea presiunii de platou~PEEP adecvat~Volume mari pentru normalizarea forțată a PaCO₂~Reducerea supradistensiei alveolare | ABCE | Ventilația protectoare limitează volutrauma și presiunile excesive; normocapnia nu este singurul obiectiv.
Ce complicații poate produce ventilația mecanică invazivă? | Pneumonie asociată ventilatorului~Barotraumă~Leziune pulmonară indusă de ventilator~Reducerea întoarcerii venoase~Creșterea garantată a debitului cardiac | ABCD | Presiunea pozitivă influențează plămânul și hemodinamica; beneficiul respirator presupune monitorizare.
Care situații limitează utilizarea ventilației noninvazive? | Incapacitatea protejării căii aeriene~Vărsături active~Instabilitate hemodinamică severă~Cooperare bună a pacientului~Traumatism facial incompatibil cu masca | ABCE | Siguranța căii aeriene, toleranța măștii și stabilitatea sunt esențiale pentru suportul noninvaziv.
Ce constatări pot semnala epuizarea respiratorie? | Alterarea conștienței~Reducerea efortului după tahipnee intensă~Creșterea PaCO₂~Respirație paradoxală~Ameliorarea izolată a culorii tegumentelor ca dovadă suficientă | ABCD | Scăderea efortului poate reprezenta oboseală, mai ales dacă ventilația și starea neurologică se agravează.
Ce cauze favorizează insuficiența respiratorie hipercapnică? | Exacerbare BPOC~Boală neuromusculară~Deprimare centrală medicamentoasă~Deformare toracică severă~Anemie izolată cu ventilație normală | ABCD | Hipercapnia apare când pompa ventilatorie nu asigură eliminarea adecvată a CO₂.
Care afirmații despre pulsoximetrie sunt corecte? | Estimează saturația periferică~Nu măsoară direct PaCO₂~Poate fi înșelătoare în intoxicația cu CO~Este influențată de perfuzia periferică~Înlocuiește gazometria în orice insuficiență respiratorie | ABCD | Pulsoximetria nu cuantifică ventilația și are limitări în dishemoglobinemii și hipoperfuzie.
În șuntul intrapulmonar sunt corecte: | Sângele perfuzează unități neventilate~Atelectazia poate contribui~Răspunsul la oxigen poate fi incomplet~PaCO₂ trebuie să fie crescută în toate cazurile~Recrutarea alveolară poate ameliora oxigenarea | ABCE | Unitățile neventilate nu beneficiază direct de oxigenul inspirat, explicând hipoxemia refractară.
Ce efecte poate avea PEEP? | Prevenirea colabării alveolare~Ameliorarea oxigenării~Reducerea întoarcerii venoase~Supradistensie la valori excesive~Eliminarea riscului de pneumotorax | ABCD | PEEP menține alveole deschise, dar excesul poate compromite plămânul și circulația.
Care afirmații despre poziționarea în decubit ventral în ARDS sunt corecte? | Poate îmbunătăți raportul ventilație/perfuzie~Necesită protejarea tubului și cateterelor~Poate produce leziuni de presiune~Înlocuiește tratamentul cauzei~Se folosește în forme severe selectate | ABCE | Pronația este o componentă a tratamentului, aplicată cu monitorizare și prevenirea complicațiilor.
La evaluarea gazometriei în insuficiența respiratorie se interpretează: | pH~PaCO₂~PaO₂ raportată la FiO₂~Bicarbonat~Doar saturația fără context ventilator | ABCD | Interpretarea integrată diferențiază oxigenarea, ventilația și tulburările acido-bazice.
Ce constatări pot sugera pneumotorax la pacientul ventilat? | Desaturare bruscă~Creșterea presiunilor în căile aeriene~Murmur vezicular redus unilateral~Hipotensiune în forma compresivă~Creștere progresivă izolată a hemoglobinei | ABCD | Aerul pleural poate compromite ventilația și întoarcerea venoasă, necesitând evaluare urgentă.
În îngrijirea pacientului intubat sunt importante: | Verificarea poziției tubului~Evaluarea zilnică a necesității ventilației~Igiena orală~Prevenirea aspirației~Menținerea sedării profunde fără reevaluare | ABCD | Reducerea complicațiilor presupune îngrijirea căii aeriene și reevaluarea suportului și sedării.
`),
...chapter('hematologie','https://www.msdmanuals.com/professional/hematology/anemias-caused-by-deficient-erythropoiesis/anemia-of-chronic-disease',`
O femeie cu menstruații abundente are Hb 9 g/dL, VEM 68 fL și feritină redusă. Diagnosticul cel mai probabil este: | Anemie feriprivă~Deficit de folat~Anemie aplastică~Hemoliză autoimună~Anemie prin deficit B12 | A | Microcitoza și depozitele reduse de fier susțin feriprivia prin pierderi cronice.
Ce marker este de regulă redus în hemoliza intravasculară? | LDH~Bilirubină indirectă~Reticulocite~Haptoglobină~Hemoglobină plasmatică liberă | D | Haptoglobina leagă hemoglobina liberă și se consumă în hemoliza intravasculară.
Ce test demonstrează imunoglobuline sau complement fixate pe eritrocite? | Test antiglobulinic direct~Timp de protrombină~Electroforeza proteinelor~Feritină serică~Test de fragilitate capilară | A | Testul Coombs direct evidențiază acoperirea eritrocitelor cu anticorpi sau complement.
Ce deficit explică anemia megaloblastică asociată cu parestezii și tulburări proprioceptive? | Fier~Vitamina B12~Vitamina C~Cupru exclusiv~Vitamina K | B | Deficitul B12 poate afecta măduva hematopoietică și cordoanele posterioare/laterale.
Ce mecanism are hepcidina în anemia inflamației? | Crește eliberarea fierului prin ferroportină~Degradează ferroportina și reduce disponibilitatea fierului~Stimulează direct sinteza B12~Distruge anticorpii eritrocitari~Crește absorbția fierului intestinal | B | Hepcidina limitează absorbția intestinală și mobilizarea fierului din depozite.
Ce profil sugerează feriprivie? | Feritină redusă~Saturație a transferinei redusă~Capacitate totală de legare a fierului crescută~VEM frecvent redus~Feritină obligatoriu crescută | ABCD | Feriprivia epuizează depozitele; inflamația poate totuși modifica interpretarea feritinei.
În anemia inflamației se pot întâlni: | Fier seric redus~Feritină normală sau crescută~Transferină redusă~Hepcidină crescută~Depozite de fier obligatoriu absente | ABCD | Fierul este sechestrat și insuficient disponibil eritropoiezei, fără epuizarea obligatorie a depozitelor.
Ce cauze pot determina macrocitoză? | Deficit B12~Deficit de folat~Consumul cronic de alcool~Hipotiroidism~Talasemie minoră ca aspect tipic | ABCD | Macrocitoza poate fi megaloblastică sau nonmegaloblastică; talasemia este tipic microcitară.
În anemia megaloblastică sunt posibile: | Neutrofile hipersegmentate~Macroovalocite~Eritropoieză ineficientă~LDH crescut~Microcitoză ca semn definitoriu | ABCD | Sinteza deficitară de ADN produce asincronie nucleo-citoplasmatică și distrugere intramedulară.
Care factori predispun la deficit B12? | Anemie pernicioasă~Rezecție ileală~Gastrectomie~Dietă vegană nesuplimentată de lungă durată~Menoragie izolată | ABCD | Absorbția necesită factor intrinsec și ileon funcțional; aportul alimentar poate deveni insuficient.
Ce constatări susțin hemoliza? | Reticulocitoză în măduvă reactivă~Bilirubină neconjugată crescută~LDH crescut~Haptoglobină redusă~Reticulocite constant absente | ABCD | Distrugerea eritrocitară crește produșii de degradare și stimulează de regulă răspunsul medular.
În hemoliza autoimună la cald sunt caracteristice: | Anticorpi predominant IgG~Hemoliză predominant extravasculară~Sferocite posibile~Test Coombs direct pozitiv~Anticorpi exclusiv IgM activi la rece | ABCD | Eritrocitele acoperite cu IgG sunt îndepărtate mai ales splenic.
Care afirmații despre aglutininele la rece sunt corecte? | Sunt frecvent IgM~Pot activa complementul~Expunerea la frig poate agrava simptomele~Produc obligatoriu deficit de fier~Pot asocia acrocianoză | ABCE | Anticorpii activi la temperaturi joase pot produce aglutinare și hemoliză mediată de complement.
Ce indicii susțin o talasemie minoră față de feriprivie? | Microcitoză disproporționată față de anemie~Număr eritrocitar relativ păstrat sau crescut~Istoric familial~Feritină redusă obligatoriu~HbA₂ crescută în beta-talasemia minoră | ABCE | Talasemia afectează sinteza globinei; depozitele de fier nu sunt obligatoriu scăzute.
La un bărbat adult cu feriprivie confirmată sunt justificate: | Căutarea unei pierderi digestive~Anamneza medicației ulcerogene~Evaluarea aportului și absorbției~Tratament cu fier fără investigarea cauzei în toate cazurile~Considerarea neoplaziei digestive | ABCE | Substituția fierului nu înlocuiește identificarea sursei unei pierderi cronice.
Ce afirmații despre tratamentul cu fier oral sunt corecte? | Poate provoca greață~Poate colora scaunul închis~Răspunsul se urmărește hematologic~Se oprește obligatoriu la prima reticulocitoză~Refacerea depozitelor necesită timp | ABCE | Creșterea hemoglobinei precedă uneori refacerea completă a depozitelor.
Ce situații pot indica fier intravenos în context potrivit? | Intoleranță importantă la fier oral~Malabsorbție~Necesitate de repleție rapidă selectată~Deficit B12 izolat~Răspuns insuficient la administrare orală corectă | ABCE | Calea intravenoasă este utilă când absorbția, toleranța sau timpul limitează administrarea orală.
Care elemente diferențiază deficitul de folat de deficitul B12? | Folatul nu corectează leziunea neurologică prin deficit B12~Acidul metilmalonic crește în deficitul B12~Ambele pot crește homocisteina~Deficitul de folat produce tipic neuropatia combinată subacută~Ambele pot produce megaloblastoză | ABCE | Acidul metilmalonic și afectarea neurologică ajută diferențierea; folatul poate masca anemia din deficit B12.
Ce cauze pot determina anemie hemolitică dobândită? | Autoimunitate~Proteză valvulară mecanică~Microangiopatie trombotică~Medicamente~Mutație ereditară a beta-globinei ca mecanism dobândit | ABCD | Hemoliza dobândită include cauze imune și mecanice; hemoglobinopatiile genetice sunt ereditare.
Ce constatări sunt sugestive pentru hemoliză microangiopatică? | Schistocite~LDH crescut~Trombocitopenie în sindroame asociate~Fragmentare mecanică eritrocitară~Macroovalocite ca semn caracteristic unic | ABCD | Eritrocitele se fragmentează în microcirculația lezată; frotiul arată schistocite.
`)
];
