import {chapter} from './author';
export const MEDICINE_B=[
...chapter('reumatologie','https://www.msdmanuals.com/professional/musculoskeletal-and-connective-tissue-disorders/joint-disorders/rheumatoid-arthritis-ra',`
Care distribuție articulară sugerează cel mai mult artrită reumatoidă precoce? | MCP și IFP simetric~IFD izolate~Prima MTF unilateral~Articulații sacroiliace izolate~Genunchi după traumatism | A | Sinovita simetrică a articulațiilor mici, cu cruțarea relativă a IFD, este sugestivă.
Care anticorp are specificitate ridicată pentru artrita reumatoidă? | Anti-centromer~Anti-CCP~Anti-mitocondrie~Anti-receptor TSH~Anti-transglutaminază | B | Anticorpii anti-peptide citrulinate susțin diagnosticul și pot anticipa boala erozivă.
Durerea lombară care se ameliorează prin exercițiu și trezește pacientul noaptea sugerează: | Lombalgie mecanică~Spondiloartrită axială~Claudicație arterială~Colică renală~Fractură de efort tibială | B | Durerea inflamatorie se agravează la repaus și se ameliorează prin mobilizare.
Artrita reumatoidă, splenomegalia și neutropenia definesc: | Sindrom Felty~Sindrom Sjögren~Sindrom Reiter~Sindrom CREST~Boală Still | A | Triada Felty apare în contextul artritei reumatoide și crește riscul infecțios.
Ce modificare imagistică este caracteristică spondilitei anchilozante? | Osteofite izolate lombare~Sacroiliită~Condrocalcinoză~Necroză de cap femural~Eroziuni IFD izolate | B | Inflamația sacroiliacă este un reper al afectării axiale.
În artrita reumatoidă sunt posibile: | Redoare matinală prelungită~Sinovită persistentă~Eroziuni marginale~Osteofite ca leziune dominantă precoce~Noduli subcutanați | ABCE | Inflamația sinovială persistentă poate distruge cartilajul și osul marginal.
Ce investigații urmăresc activitatea inflamatorie în artrita reumatoidă? | VSH~CRP~Anticorpi anti-HBs~Troponină~Examinarea articulațiilor tumefiate | ABE | Activitatea se apreciază clinic și prin reactanți de fază acută, nu printr-un anticorp viral.
Metotrexatul în artrita reumatoidă necesită atenție la: | Hemogramă~Funcție hepatică~Sarcină~Administrare zilnică standard~Funcție renală | ABCE | Metotrexatul se administrează uzual săptămânal și necesită monitorizare hematologică, hepatică și renală.
Care sunt medicamente modificatoare de boală convenționale? | Metotrexat~Sulfasalazină~Hidroxiclorochină~Ibuprofen~Paracetamol | ABC | AINS și paracetamolul pot controla simptomele, dar nu sunt DMARD convenționale.
Ce manifestări extraarticulare pot însoți artrita reumatoidă? | Pleurită~Boală pulmonară interstițială~Sclerită~Gușă toxică obligatorie~Vasculită | ABCE | Inflamația sistemică poate interesa seroasele, plămânul, ochiul și vasele.
Care afirmații despre factorul reumatoid sunt corecte? | Poate apărea în alte boli~Poate lipsi în artrita reumatoidă~Confirmă singur diagnosticul~Este identic cu anti-CCP~Se interpretează clinic | ABE | Factorul reumatoid nu este nici universal prezent, nici specific exclusiv artritei reumatoide.
În spondiloartrite sunt frecvente asocierile: | Entezită~Dactilită~Uveită anterioară~Noduli reumatoizi definitorii~Sacroiliită | ABCE | Entezele, degetele, ochiul și articulațiile sacroiliace pot fi afectate.
Ce caracteristici susțin lombalgia inflamatorie? | Debut insidios la adult tânăr~Ameliorare prin mișcare~Ameliorare exclusiv prin repaus~Durere nocturnă~Debut imediat după ridicarea unei greutăți | ABD | Tiparul temporal și răspunsul la mișcare o diferențiază de multe cauze mecanice.
Despre HLA-B27 sunt corecte: | Se asociază cu spondiloartrita axială~Poate fi prezent la persoane sănătoase~Pozitivitatea echivalează cu diagnosticul~Absența exclude orice spondiloartrită~Modifică probabilitatea în context clinic | ABE | HLA-B27 este un factor de asociere, nu un test diagnostic autonom.
Ce măsuri au rol în spondiloartrita axială? | Exercițiu regulat~AINS la pacienți potriviți~Terapie biologică în boală activă selectată~Imobilizare prelungită preventivă~Evaluarea manifestărilor extraarticulare | ABCE | Tratamentul combină mobilitatea, controlul inflamației și evaluarea sistemică.
Care constatări pot apărea în lupusul sistemic? | Fotosensibilitate~Ulcerații orale~Serozită~Eroziuni articulare obligatorii~Citopenii | ABCE | Lupusul este multisistemic; artrita sa este de regulă neerozivă.
Ce markeri pot ajuta evaluarea nefritei lupice active? | Proteinurie~Sediment urinar activ~Complement scăzut~Anti-ADN dublu catenar crescuți~Anti-CCP izolați | ABCD | Afectarea renală se apreciază prin urină, funcție renală și markeri imunologici.
Ce afirmații despre ANA sunt corecte? | Au sensibilitate mare pentru lupus~Pot fi pozitivi fără lupus~Pozitivitatea izolată stabilește boala~Trebuie corelați cu manifestările~Sunt exclusiv markeri de infecție bacteriană | ABD | ANA susțin evaluarea imunologică, dar specificitatea izolată este limitată.
În tratamentul lupusului sunt utile, după context: | Fotoprotecție~Hidroxiclorochină~Imunosupresie adaptată organului afectat~Aceeași doză de glucocorticoid la orice pacient~Supravegherea toxicității retiniene a antimalaricelor | ABCE | Tratamentul se adaptează severității; hidroxiclorochina necesită monitorizare oculară.
Înainte de terapie anti-TNF se evaluează în special: | Tuberculoză latentă~Hepatită B~Infecții active~Grup sanguin drept criteriu de eligibilitate~Capacitatea de a tolera contrast iodat obligatoriu | ABC | Reactivarea infecțiilor este un risc relevant al blocării TNF.
`),
...chapter('endocrinologie','https://www.thyroid.org/thyroid-function-tests/',`
TSH crescut și FT4 redus indică, în context obișnuit: | Hipotiroidism primar~Hipertiroidism primar~Hipotiroidism central tipic~Eutiroidism~Rezistență izolată la insulină | A | Tiroida insuficientă reduce FT4, iar hipofiza răspunde prin creșterea TSH.
TSH suprimat și FT4 crescut sunt compatibile cu: | Hipotiroidism primar~Tireotoxicoză~Deficit izolat de iod fără consecințe~Eutiroidism cert~Insuficiență hipofizară izolată | B | TSH scade prin feedback în excesul de hormoni tiroidieni.
Ce anticorp susține boala Graves? | Anti-receptor TSH~Anti-CCP~Anti-mitocondrie~Anti-centromer~Anti-membrană bazală | A | Anticorpii stimulatori ai receptorului TSH cresc sinteza și eliberarea hormonilor tiroidieni.
Pacientul sub tiamazol dezvoltă febră și odinofagie. Ce complicație trebuie exclusă urgent? | Hipercalcemie~Agranulocitoză~Policitemie~Hipernatremie~Retenție urinară | B | Febra și odinofagia pot indica neutropenie severă indusă de antitiroidian.
Carcinomul medular tiroidian derivă din: | Celule foliculare~Celule parafoliculare C~Limfocite B~Paratiroide~Celule hipofizare | B | Celulele C produc calcitonină; carcinomul medular este distinct de tumorile foliculare.
Care manifestări sugerează hipotiroidism? | Intoleranță la frig~Constipație~Bradicardie~Tremor fin~Tegumente uscate | ABCE | Reducerea efectelor hormonilor tiroidieni încetinește metabolismul și tranzitul intestinal.
În tireotoxicoză pot apărea: | Scădere ponderală~Intoleranță la căldură~Fibrilație atrială~Constipație cu bradicardie tipică~Hiperreflexie | ABCE | Excesul hormonal crește termogeneza și sensibilitatea cardiovasculară adrenergică.
Ce constatări sunt mai sugestive pentru Graves decât pentru o tiroidită simplă? | Orbitopatie specifică~Anticorpi anti-receptor TSH~Captare difuză crescută~Captare scăzută obligatorie~Durere tiroidiană intensă obligatorie | ABC | Graves implică sinteză hormonală stimulată; tiroidita distructivă eliberează hormoni preformați.
Despre levotiroxină sunt corecte: | Este tratament substitutiv~Absorbția poate scădea cu fierul~Doza se individualizează~Se folosește pentru blocarea sintezei în Graves~Calciul poate interfera cu absorbția | ABCE | Interacțiunile de absorbție și necesarul individual influențează controlul TSH.
Ce rezultate sugerează hipotiroidism central? | FT4 scăzut~TSH inadecvat normal sau scăzut~TSH obligatoriu foarte crescut~Posibile alte deficite hipofizare~FT4 obligatoriu crescut | ABD | TSH nu crește adecvat în insuficiența hipotalamo-hipofizară.
Care factori pot altera interpretarea analizelor tiroidiene? | Biotina în anumite imunoteste~Boala sistemică severă~Medicamentele~Ora recoltării ca unic diagnostic~Sarcina | ABCE | Analizele trebuie interpretate cu metoda de laborator și contextul fiziologic sau medicamentos.
Tionamidele au următoarele caracteristici: | Inhibă sinteza hormonilor tiroidieni~Pot produce erupții~Pot produce agranulocitoză~Distrug imediat toate rezervele hormonale~Necesită informarea pacientului despre febră și odinofagie | ABCE | Efectul nu este instantaneu, deoarece hormonii stocați persistă.
Beta-blocantele în tireotoxicoză pot reduce: | Tahicardia~Tremorul~Gușa prin ablație directă~Anticorpii prin distrugere~Simptomele adrenergice | ABE | Ele controlează simptomele, fără a înlocui tratamentul mecanismului tireotoxicozei.
Ce elemente pot apărea în criza tireotoxică? | Hipertermie~Tahiaritmie~Alterare neuropsihică~Hipotermie cu bradicardie caracteristică~Factor precipitant infecțios | ABCE | Criza este o decompensare severă, adesea precipitată de infecție sau întreruperea tratamentului.
În coma mixedematoasă sunt posibile: | Hipotermie~Hipoventilație~Hiponatremie~Agitație hipermetabolică obligatorie~Bradicardie | ABCE | Hipotiroidismul sever decompensat afectează termoreglarea, respirația și starea de conștiență.
Carcinomul papilar tiroidian se caracterizează prin: | Origine foliculară~Diseminare ganglionară cervicală posibilă~Asociere cu expunerea la radiații~Secreție caracteristică de calcitonină~Origine în celulele C | ABC | Este un carcinom diferențiat; calcitonina este asociată carcinomului medular.
Despre carcinomul folicular sunt corecte: | Invazia capsulară contează diagnostic~Invazia vasculară contează diagnostic~Citologia singură separă sigur adenomul de carcinom~Poate disemina hematogen~Provine din limfocite | ABD | Diagnosticul malignității necesită evaluarea invaziei, imposibilă doar din celule aspirate.
Carcinomul medular poate asocia: | MEN2~Mutații RET~Calcitonină crescută~Răspuns obișnuit la iod radioactiv ca tumorile diferențiate~Origine parafoliculară | ABCE | Originea parafoliculară explică markerul și lipsa captării terapeutice tipice de iod.
Ce constatări cresc suspiciunea de malignitate într-un nodul tiroidian? | Adenopatii suspecte~Răgușeală persistentă~Margini ecografice neregulate~Microcalcificări~TSH normal ca dovadă de benignitate | ABCD | Funcția tiroidiană normală nu exclude cancerul; caracteristicile locale ghidează evaluarea.
Tiroidita subacută dureroasă poate prezenta: | Durere cervicală~VSH crescut~Fază tranzitorie de tireotoxicoză~Captare crescută difuză tipică Graves~Eliberare de hormoni preformați | ABCE | Distrugerea foliculară eliberează hormon stocat și reduce captarea în faza tireotoxică.
`),
...chapter('diabet','https://www.niddk.nih.gov/health-information/diabetes/overview/insulin-medicines-treatments',`
Ce mecanism predomină în diabetul de tip 1? | Distrucție autoimună a celulelor beta~Exces de glucagon fără deficit insulinic~Exces de insulină~Rezistență izolată la leptină~Deficit de cortizol | A | Pierderea celulelor beta determină deficit insulinic absolut.
Ce clasă reduce predominant producția hepatică de glucoză? | Sulfoniluree~Biguanide~Glinide~Insuline rapide~Inhibitori de alfa-glucozidază | B | Metforminul reduce gluconeogeneza hepatică și îmbunătățește sensibilitatea la insulină.
Respirația Kussmaul la un diabetic sugerează în primul rând: | Compensarea acidozei metabolice~Alcaloză metabolică~Obstrucție laringiană~Respirație normală de somn~Deficit izolat de fier | A | Hiperventilația reduce PaCO₂ ca răspuns la acidoza cetoacidozei.
Ce marker reflectă glicemia medie pe aproximativ 2–3 luni? | Glicozurie~HbA1c~Cetonurie~Insulinemie punctuală~Peptid C | B | Glicarea hemoglobinei integrează expunerea eritrocitară la glucoză.
Care mecanism explică glicozuria indusă de inhibitorii SGLT2? | Blocarea reabsorbției renale a glucozei~Stimularea glicogenolizei~Distrugerea celulelor beta~Inhibarea absorbției lactozei~Creșterea secreției glucagonului ca țintă unică | A | SGLT2 transportă glucoza în tubul proximal; inhibarea crește eliminarea urinară.
Ce elemente diferențiază cetoacidoza de starea hiperosmolară tipică? | Cetoză semnificativă~Acidoză metabolică~Deficit insulinic mai pronunțat~Absența deshidratării~pH obligatoriu alcalin | ABC | Starea hiperosmolară are de regulă cetoză mai redusă, deși pot exista forme mixte.
În cetoacidoză, potasiul necesită supraveghere deoarece: | Depozitele totale pot fi reduse~Valoarea serică inițială poate fi crescută~Insulina îl deplasează intracelular~Hipokaliemia severă nu influențează administrarea insulinei~Diureza osmotică produce pierderi | ABCE | Potasiul seric inițial nu reflectă fidel deficitul total, iar tratamentul poate scădea rapid concentrația.
Care sunt factori precipitanți ai crizelor hiperglicemice? | Infecții~Omiterea insulinei~Infarct miocardic~Tratament glucocorticoid~Aport de fibre ca mecanism obișnuit | ABCD | Stresul biologic și insuficiența relativă sau absolută de insulină precipită decompensarea.
Ce manifestări adrenergice apar în hipoglicemie? | Tremor~Palpitații~Transpirații~Hemianopsie fixă obligatorie~Hipotermie ca simptom adrenergic definitoriu | ABC | Manifestările autonome pot preceda neuroglicopenia, dar pot lipsi la unii pacienți.
Ce semne pot reprezenta neuroglicopenie? | Confuzie~Convulsii~Tulburări de comportament~Comă~Poliurie osmotică | ABCD | Creierul suferă prin lipsa glucozei; poliuria osmotică este legată de hiperglicemie.
Sulfonilureele pot determina: | Hipoglicemie~Creștere ponderală~Stimularea secreției insulinice~Glicozurie prin blocarea SGLT2~Încetinirea absorbției glucidelor ca mecanism principal | ABC | Stimularea secreției de insulină explică hipoglicemia și creșterea în greutate.
Agoniștii receptorului GLP-1 pot avea: | Efect de sațietate~Scădere ponderală~Greață~Stimulare insulinică dependentă de glucoză~Hipoglicemie severă obligatorie în monoterapie | ABCD | Efectul insulinotrop dependent de glucoză limitează hipoglicemia izolată, fără a elimina riscul în combinații.
Inhibitorii SGLT2 impun atenție la: | Infecții genitale micotice~Depleție volemică~Cetoacidoză cu glicemie nu foarte mare~Agranulocitoză ca efect de clasă tipic~Context perioperator | ABCE | Glicozuria și diureza osmotică explică unele riscuri; cetoacidoza poate fi euglicemică.
Ce afirmații despre tiazolidindione sunt corecte? | Ameliorează sensibilitatea la insulină~Pot determina edeme~Pot agrava insuficiența cardiacă~Produc scădere ponderală constantă~Sunt substitut al insulinei în tipul 1 | ABC | Retenția hidrosalină limitează utilizarea la pacienți cu insuficiență cardiacă.
Ce complicații sunt predominant microvasculare? | Retinopatie~Nefropatie diabetică~Neuropatie~Infarct miocardic aterosclerotic~Accident vascular aterotrombotic | ABC | Ateroscleroza coronariană și cerebrală reprezintă afectare macrovasculară.
Ce factori contribuie la ulcerul piciorului diabetic? | Pierderea sensibilității protectoare~Ischemie~Deformări cu hiperpresiune~Traumatisme nerecunoscute~Hipertiroidism izolat obligatoriu | ABCD | Neuropatia și ischemia favorizează leziuni, iar distribuția presiunii întreține ulcerul.
La evaluarea nefropatiei diabetice sunt utile: | Raport albumină/creatinină urinară~Rata estimată a filtrării glomerulare~Tensiunea arterială~Cetonurie ca singur marker cronic~Repetarea albuminuriei pentru confirmare | ABCE | Albuminuria și filtrarea renală sunt complementare; o determinare poate fi influențată tranzitoriu.
HbA1c poate fi dificil de interpretat în: | Hemoliză~Transfuzie recentă~Unele hemoglobinopatii~Schimbări ale duratei de viață eritrocitare~Orice miopie izolată | ABCD | Modificarea eritrocitelor poate decupla HbA1c de glicemia medie reală.
Ce recomandări privind insulina sunt corecte? | Rotația locurilor de injectare~Recunoașterea hipoglicemiei~Adaptarea la alimentație și efort~Oprirea insulinei bazale în tipul 1 la orice infecție~Verificarea tehnicii de injectare | ABCE | Infecția poate crește necesarul; oprirea necontrolată a insulinei în tipul 1 poate precipita cetoacidoză.
În starea hiperosmolară sunt frecvente: | Hiperglicemie marcată~Deshidratare importantă~Alterarea conștienței~Cetoză severă obligatorie~Osmolalitate efectivă crescută | ABCE | Diureza osmotică produce deficit hidric major; cetogeneza poate fi relativ limitată.
`),
...chapter('neurologie','https://www.msdmanuals.com/professional/neurologic-disorders/stroke/ischemic-stroke',`
Un deficit motor brusc al hemicorpului drept cu afazie sugerează o leziune predominant: | Emisferică stângă dominantă~Cerebeloasă dreaptă~Medulară lombară~Occipitală dreaptă izolată~Nervoasă periferică bilaterală | A | Afazia indică afectarea emisferei dominante, cel mai frecvent stânga.
Ce investigație exclude rapid hemoragia intracraniană în evaluarea inițială a AVC? | CT cerebral nativ~EEG~Radiografie de craniu~EMG~Ecografie abdominală | A | CT fără contrast identifică sângele acut și orientează tratamentul imediat.
Cefaleea bruscă, maximală de la debut, impune excluderea prioritară a: | Migrenei cronice~Hemoragiei subarahnoidiene~Neuropatiei diabetice~Nevralgiei postherpetice~Sinuzitei cronice simple | B | Cefaleea în lovitură de trăsnet este un semnal de alarmă pentru hemoragia subarahnoidiană.
Care agent este asociat clasic encefalitei temporale necrozante? | HSV-1~Rotavirus~Virus hepatitic A~Parvovirus B19~Virus rabic exclusiv | A | Encefalita herpetică are predilecție temporală și necesită tratament antiviral precoce.
Ce cauză reversibilă trebuie verificată imediat la pacientul cu alterarea conștienței? | Hipoglicemie~Miopie~Osteoporoză~Hiperuricemie asimptomatică~Deficit de fier izolat | A | Glicemia se verifică precoce deoarece hipoglicemia poate mima AVC sau comă.
În AVC ischemic, evaluarea inițială include: | Momentul ultimei stări normale~Glicemie~Imagistică cerebrală~Tratament trombolitic înaintea excluderii hemoragiei~Evaluarea deficitului neurologic | ABCE | Timpul, contraindicațiile și imagistica determină eligibilitatea pentru reperfuzie.
Ce factori favorizează AVC cardioembolic? | Fibrilație atrială~Tromb ventricular~Proteză valvulară trombogenă~Otită externă~Miopie | ABC | Sursele cardiace de tromb pot emboliza arterele cerebrale.
Care manifestări sugerează circulația vertebrobazilară? | Diplopie~Ataxie~Disartrie~Vertij cu semne neurologice asociate~Afazie izolată tipică dominantă | ABCD | Trunchiul cerebral și cerebelul sunt irigate predominant de sistemul vertebrobazilar.
Ce măsuri sunt relevante după AVC pentru prevenirea complicațiilor? | Evaluarea deglutiției~Mobilizare adaptată~Prevenirea tromboembolismului după context~Administrare orală înaintea evaluării deglutiției~Controlul temperaturii și glicemiei | ABCE | Disfagia și imobilizarea cresc riscul de aspirație și tromboză.
Ce rezultate LCR sugerează meningită bacteriană? | Pleocitoză predominant neutrofilă~Proteinorahie crescută~Glicorahie scăzută~LCR obligatoriu normal~Presiune de deschidere posibil crescută | ABCE | Profilul combinat este sugestiv, dar antibioterapia anterioară poate modifica rezultatele.
În meningita virală sunt mai frecvente: | Pleocitoză limfocitară~Glicorahie relativ păstrată~Proteinorahie moderat crescută~Bacterii la colorația Gram~Hipoglicorahie profundă obligatorie | ABC | Tiparul viral este de regulă limfocitar, cu glucoză păstrată, fără a înlocui identificarea etiologică.
Ce elemente pot justifica imagistică înaintea puncției lombare? | Deficit focal~Papiledem~Suspiciune de proces expansiv~Imunosupresie relevantă~Cefalee banală izolată ca indicație universală | ABCD | Semnele de leziune expansivă sau hipertensiune intracraniană impun evaluarea riscului puncției.
Ce afirmații despre encefalita herpetică sunt corecte? | Poate produce tulburări comportamentale~Poate produce convulsii~PCR din LCR este utilă~Aciclovirul se amână obligatoriu până la confirmare~RMN poate arăta afectare temporală | ABCE | Tratamentul precoce este important când suspiciunea este mare, în paralel cu investigațiile.
Ce complicații pot urma hemoragiei subarahnoidiene? | Resângerare~Hidrocefalie~Ischemie cerebrală întârziată~Vasospasm~Ciroză imediată ca efect direct | ABCD | Sângele subarahnoidian poate afecta circulația LCR și perfuzia cerebrală.
Hipertensiunea cronică poate favoriza hemoragia în: | Ganglionii bazali~Talamus~Punte~Cerebel~Nervul sciatic ca localizare intracraniană | ABCD | Arterele perforante profunde sunt vulnerabile la leziunile hipertensive.
Ce elemente intră în scala Glasgow? | Deschiderea ochilor~Răspuns verbal~Răspuns motor~Reflex rotulian~Diametrul pupilar | ABC | Glasgow evaluează trei răspunsuri; pupilele se examinează separat.
Ce constatări pot sugera herniere uncală? | Midriază unilaterală~Alterarea conștienței~Deficit motor~Compresia nervului III~Mioză bilaterală reactivă obligatorie | ABCD | Compresia oculomotorului poate produce midriază în context de hipertensiune intracraniană.
Ce diferențe ajută între comă metabolică și leziune focală? | Simetria semnelor poate orienta metabolic~Deficitul focal orientează structural~Pupilele și reflexele de trunchi sunt relevante~Simetria exclude sigur orice leziune structurală~Imagistica poate rămâne necesară | ABCE | Acestea sunt indicii probabilistice, nu reguli absolute de excludere.
În atacul ischemic tranzitor sunt importante: | Evaluarea urgentă~Identificarea fibrilației atriale~Evaluarea stenozelor relevante~Neglijarea episodului după remiterea semnelor~Prevenția secundară adaptată mecanismului | ABCE | Remiterea deficitului nu anulează riscul precoce de AVC.
Ce constatări pot apărea în tromboza venoasă cerebrală? | Cefalee~Convulsii~Deficit focal~Hipertensiune intracraniană~Absența obligatorie a hemoragiei | ABCD | Obstrucția drenajului venos poate produce infarcte venoase inclusiv hemoragice.
`)
];
