import {ELECTROLYTES_SOURCE} from './electrolytes-source';
import {SEPSIS_SOURCE} from './sepsis-source';
import {chapter} from './author';
export const MEDICINE_A=[
...SEPSIS_SOURCE,
...ELECTROLYTES_SOURCE,
...chapter('ati','https://www.msdmanuals.com/professional/critical-care-medicine/respiratory-failure-and-mechanical-ventilation/overview-of-respiratory-failure',`
Care este caracteristica definitorie a insuficienței respiratorii de tip II? | Hipocapnie~Hipercapnie~Hiperglicemie~Methemoglobinemie~Alcaloză metabolică | B | Tipul II presupune ventilație alveolară insuficientă cu retenție de CO₂.
Un pacient cu pneumonie are hipoxemie și PaCO₂ normală sau scăzută. Încadrarea uzuală este: | Insuficiență respiratorie tip I~Insuficiență respiratorie tip II obligatorie~Hipoventilație izolată~Acidoză respiratorie cronică~Ventilație alveolară absentă | A | Insuficiența hipoxemică poate exista fără retenție de CO₂.
Care parametru se folosește pentru clasificarea severității ARDS în definiția Berlin? | Raport PaO₂/FiO₂~Raport FEV₁/FVC~Hemoglobina glicată~Presiunea pulsului~Raport uree/creatinină | A | Severitatea hipoxemiei se exprimă prin PaO₂/FiO₂ în condițiile de suport respirator specificate.
La calcularea volumului curent protector în ARDS se utilizează predominant: | Greutatea corporală actuală~Greutatea corporală prezisă după înălțime și sex~Suprafața arsă~Circumferința abdominală~Greutatea maximă din antecedente | B | Volumul pulmonar se corelează cu înălțimea, nu cu excesul de țesut adipos.
În intoxicația cu opioide, mecanismul principal al hipercapniei este: | Șunt intracardiac~Hipoventilație alveolară~Creștere izolată a difuziunii~Hiperventilație reflexă~Scăderea producției de CO₂ | B | Deprimarea centrului respirator scade ventilația alveolară și crește PaCO₂.
Care mecanisme produc hipoxemie? | Dezechilibru ventilație/perfuzie~Șunt dreapta–stânga~Limitarea difuziunii~Hipoventilație alveolară~Creșterea concentrației inspirate de oxigen | ABCD | Hipoxemia poate avea mecanisme diferite; oxigenul inspirat suplimentar este o intervenție terapeutică.
Ce elemente sunt compatibile cu definiția Berlin a ARDS? | Debut în prima săptămână după agresiune~Opacități pulmonare bilaterale~Edem explicat integral de insuficiența cardiacă~Hipoxemie cuantificată prin PaO₂/FiO₂~Necesitatea excluderii unei explicații exclusiv hidrostatice | ABDE | ARDS reprezintă leziune pulmonară acută cu edem neexplicat complet prin insuficiență cardiacă.
Ce agresiuni pot precipita ARDS? | Sepsis~Aspirație gastrică~Pneumonie severă~Traumatism major~Rinită alergică izolată | ABCD | Atât leziunile pulmonare directe, cât și inflamația sistemică pot iniția ARDS.
În ventilația protectoare pentru ARDS se urmăresc: | Volume curente reduse~Limitarea presiunii de platou~PEEP adecvat~Volume mari pentru normalizarea forțată a PaCO₂~Reducerea supradistensiei alveolare | ABCE | Ventilația protectoare limitează volutrauma și presiunile excesive; normocapnia nu este singurul obiectiv.
Ce complicații poate produce ventilația mecanică invazivă? | Pneumonie asociată ventilatorului~Barotraumă~Leziune pulmonară indusă de ventilator~Reducerea întoarcerii venoase~Creșterea garantată a debitului cardiac | ABCD | Presiunea pozitivă influențează plămânul și hemodinamica; beneficiul respirator presupune monitorizare.
Care situații limitează utilizarea ventilației noninvazive? | Incapacitatea protejării căii aeriene~Vărsături active~Instabilitate hemodinamică severă~Cooperare bună a pacientului~Traumatism facial incompatibil cu masca | ABCE | Siguranța căii aeriene, toleranța măștii și stabilitatea sunt esențiale pentru suportul noninvaziv.
Ce constatări pot semnala epuizarea respiratorie? | Alterarea conștienței~Reducerea efortului după tahipnee intensă~Creșterea PaCO₂~Respirație paradoxală~Ameliorarea izolată a culorii tegumentelor ca dovadă suficientă | ABCD | Scăderea efortului poate reprezenta oboseală, mai ales dacă ventilația și starea neurologică se agravează.
Ce cauze favorizează insuficiența respiratorie hipercapnică? | Exacerbare BPOC~Boală neuromusculară~Deprimare centrală medicamentoasă~Deformare toracică severă~Anemie izolată cu ventilație normală | ABCD | Hipercapnia apare când pompa ventilatorie nu asigură eliminarea adecvată a CO₂.
Care afirmații despre pulsoximetrie sunt corecte? | Estimează saturația periferică~Nu măsoară direct PaCO₂~Poate fi înșelătoare în intoxicația cu CO~Este influențată de perfuzia periferică~Înlocuiește gazometria în orice insuficiență respiratorie | ABCD | Pulsoximetria nu cuantifică ventilația și are limitări în dishemoglobinemii și hipoperfuzie.
În șuntul intrapulmonar sunt corecte: | Sângele perfuzează unități neventilate~Atelectazia poate contribui~Răspunsul la oxigen poate fi incomplet~PaCO₂ trebuie să fie crescută în toate cazurile~Recrutarea alveolară poate ameliora oxigenarea | ABCE | Unitățile neventilate nu beneficiază direct de oxigenul inspirat, explicând hipoxemia refractară.
Ce efecte poate avea PEEP? | Prevenirea colabării alveolare~Ameliorarea oxigenării~Reducerea întoarcerii venoase~Supradistensie la valori excesive~Eliminarea riscului de pneumotorax | ABCD | PEEP menține alveole deschise, dar excesul poate compromite plămânul și circulația.
Care afirmații despre poziționarea în decubit ventral în ARDS sunt corecte? | Poate îmbunătăți raportul ventilație/perfuzie~Necesită protejarea tubului și cateterelor~Poate produce leziuni de presiune~Înlocuiește tratamentul cauzei~Se folosește în forme severe selectate | ABCE | Pronația este o componentă a tratamentului, aplicată cu monitorizare și prevenirea complicațiilor.
La evaluarea gazometriei în insuficiența respiratorie se interpretează: | pH~PaCO₂~PaO₂ raportată la FiO₂~Bicarbonat~Doar saturația fără context ventilator | ABCD | Interpretarea integrată diferențiază oxigenarea, ventilația și tulburările acido-bazice.
Ce constatări pot sugera pneumotorax la pacientul ventilat? | Desaturare bruscă~Creșterea presiunilor în căile aeriene~Murmur vezicular redus unilateral~Hipotensiune în forma compresivă~Creștere progresivă izolată a hemoglobinei | ABCD | Aerul pleural poate compromite ventilația și întoarcerea venoasă, necesitând evaluare urgentă.
În îngrijirea pacientului intubat sunt importante: | Verificarea poziției tubului~Evaluarea zilnică a necesității ventilației~Igiena orală~Prevenirea aspirației~Menținerea sedării profunde fără reevaluare | ABCD | Reducerea complicațiilor presupune îngrijirea căii aeriene și reevaluarea suportului și sedării.
`),
...chapter('hematologie','https://www.msdmanuals.com/professional/hematology/anemias-caused-by-deficient-erythropoiesis/anemia-of-chronic-disease',`
O femeie cu menstruații abundente are Hb 9 g/dL, VEM 68 fL și feritină redusă. Diagnosticul cel mai probabil este: | Anemie feriprivă~Deficit de folat~Anemie aplastică~Hemoliză autoimună~Anemie prin deficit B12 | A | Microcitoza și depozitele reduse de fier susțin feriprivia prin pierderi cronice.
Ce marker este de regulă redus în hemoliza intravasculară? | LDH~Bilirubină indirectă~Reticulocite~Haptoglobină~Hemoglobină plasmatică liberă | D | Haptoglobina leagă hemoglobina liberă și se consumă în hemoliza intravasculară.
Ce test demonstrează imunoglobuline sau complement fixate pe eritrocite? | Test antiglobulinic direct~Timp de protrombină~Electroforeza proteinelor~Feritină serică~Test de fragilitate capilară | A | Testul Coombs direct evidențiază acoperirea eritrocitelor cu anticorpi sau complement.
Ce deficit explică anemia megaloblastică asociată cu parestezii și tulburări proprioceptive? | Fier~Vitamina B12~Vitamina C~Cupru exclusiv~Vitamina K | B | Deficitul B12 poate afecta măduva hematopoietică și cordoanele posterioare/laterale.
Ce mecanism are hepcidina în anemia inflamației? | Crește eliberarea fierului prin ferroportină~Degradează ferroportina și reduce disponibilitatea fierului~Stimulează direct sinteza B12~Distruge anticorpii eritrocitari~Crește absorbția fierului intestinal | B | Hepcidina limitează absorbția intestinală și mobilizarea fierului din depozite.
Ce profil sugerează feriprivie? | Feritină redusă~Saturație a transferinei redusă~Capacitate totală de legare a fierului crescută~VEM frecvent redus~Feritină obligatoriu crescută | ABCD | Feriprivia epuizează depozitele; inflamația poate totuși modifica interpretarea feritinei.
În anemia inflamației se pot întâlni: | Fier seric redus~Feritină normală sau crescută~Transferină redusă~Hepcidină crescută~Depozite de fier obligatoriu absente | ABCD | Fierul este sechestrat și insuficient disponibil eritropoiezei, fără epuizarea obligatorie a depozitelor.
Ce cauze pot determina macrocitoză? | Deficit B12~Deficit de folat~Consumul cronic de alcool~Hipotiroidism~Talasemie minoră ca aspect tipic | ABCD | Macrocitoza poate fi megaloblastică sau nonmegaloblastică; talasemia este tipic microcitară.
În anemia megaloblastică sunt posibile: | Neutrofile hipersegmentate~Macroovalocite~Eritropoieză ineficientă~LDH crescut~Microcitoză ca semn definitoriu | ABCD | Sinteza deficitară de ADN produce asincronie nucleo-citoplasmatică și distrugere intramedulară.
Care factori predispun la deficit B12? | Anemie pernicioasă~Rezecție ileală~Gastrectomie~Dietă vegană nesuplimentată de lungă durată~Menoragie izolată | ABCD | Absorbția necesită factor intrinsec și ileon funcțional; aportul alimentar poate deveni insuficient.
Ce constatări susțin hemoliza? | Reticulocitoză în măduvă reactivă~Bilirubină neconjugată crescută~LDH crescut~Haptoglobină redusă~Reticulocite constant absente | ABCD | Distrugerea eritrocitară crește produșii de degradare și stimulează de regulă răspunsul medular.
În hemoliza autoimună la cald sunt caracteristice: | Anticorpi predominant IgG~Hemoliză predominant extravasculară~Sferocite posibile~Test Coombs direct pozitiv~Anticorpi exclusiv IgM activi la rece | ABCD | Eritrocitele acoperite cu IgG sunt îndepărtate mai ales splenic.
Care afirmații despre aglutininele la rece sunt corecte? | Sunt frecvent IgM~Pot activa complementul~Expunerea la frig poate agrava simptomele~Produc obligatoriu deficit de fier~Pot asocia acrocianoză | ABCE | Anticorpii activi la temperaturi joase pot produce aglutinare și hemoliză mediată de complement.
Ce indicii susțin o talasemie minoră față de feriprivie? | Microcitoză disproporționată față de anemie~Număr eritrocitar relativ păstrat sau crescut~Istoric familial~Feritină redusă obligatoriu~HbA₂ crescută în beta-talasemia minoră | ABCE | Talasemia afectează sinteza globinei; depozitele de fier nu sunt obligatoriu scăzute.
La un bărbat adult cu feriprivie confirmată sunt justificate: | Căutarea unei pierderi digestive~Anamneza medicației ulcerogene~Evaluarea aportului și absorbției~Tratament cu fier fără investigarea cauzei în toate cazurile~Considerarea neoplaziei digestive | ABCE | Substituția fierului nu înlocuiește identificarea sursei unei pierderi cronice.
Ce afirmații despre tratamentul cu fier oral sunt corecte? | Poate provoca greață~Poate colora scaunul închis~Răspunsul se urmărește hematologic~Se oprește obligatoriu la prima reticulocitoză~Refacerea depozitelor necesită timp | ABCE | Creșterea hemoglobinei precedă uneori refacerea completă a depozitelor.
Ce situații pot indica fier intravenos în context potrivit? | Intoleranță importantă la fier oral~Malabsorbție~Necesitate de repleție rapidă selectată~Deficit B12 izolat~Răspuns insuficient la administrare orală corectă | ABCE | Calea intravenoasă este utilă când absorbția, toleranța sau timpul limitează administrarea orală.
Care elemente diferențiază deficitul de folat de deficitul B12? | Folatul nu corectează leziunea neurologică prin deficit B12~Acidul metilmalonic crește în deficitul B12~Ambele pot crește homocisteina~Deficitul de folat produce tipic neuropatia combinată subacută~Ambele pot produce megaloblastoză | ABCE | Acidul metilmalonic și afectarea neurologică ajută diferențierea; folatul poate masca anemia din deficit B12.
Ce cauze pot determina anemie hemolitică dobândită? | Autoimunitate~Proteză valvulară mecanică~Microangiopatie trombotică~Medicamente~Mutație ereditară a beta-globinei ca mecanism dobândit | ABCD | Hemoliza dobândită include cauze imune și mecanice; hemoglobinopatiile genetice sunt ereditare.
Ce constatări sunt sugestive pentru hemoliză microangiopatică? | Schistocite~LDH crescut~Trombocitopenie în sindroame asociate~Fragmentare mecanică eritrocitară~Macroovalocite ca semn caracteristic unic | ABCD | Eritrocitele se fragmentează în microcirculația lezată; frotiul arată schistocite.
`)
];
