import {advancedQuestion} from './advanced-author';
import type {SourceRow} from './source-author';

const pdfOffset=(p:number)=>p<=1368?p-1020:p<=1387?p-1036:p-1040;
const q=(n:number,row:SourceRow,score:number,reason:string,expressions:string[],related:number[]=[])=>
 advancedQuestion('nefrologie',36,pdfOffset,`nefrologie-adv-${String(n).padStart(3,'0')}`,row,[score,reason],expressions,undefined,related);

export const NEFROLOGIE_ADVANCED=[
q(1,['Care dintre următoarele afirmații diferențiază corect sindromul nefrotic de sindromul nefritic?',
 ['Sindromul nefrotic se caracterizează prin proteinurie masivă (>3,5 g/zi), hipoalbuminemie, edeme, lipidurie și hiperlipidemie','Cauza cea mai frecventă a sindromului nefrotic este malfuncția sau lezarea podocitelor','Glomerulonefrita acută include hematurie glomerulară, proteinurie de rang non-nefrotic, edeme, hipertensiune și afectare renală tranzitorie','Podocitele sunt principal implicate în bolile care se prezintă ca nefrită, iar celulele endoteliale și mezangiale în sindromul nefrotic','Proteinuria din sindromul nefrotic este de regulă sub 1 g/zi, fără hiperlipidemie'],'ABC',1353,'Glomerulul și afectarea glomerulară — Clasificarea clinică: sindrom nefrotic versus nefritic',
 'Diferențierea celor două sindroame glomerulare majore după proteinurie, compartimentul celular predominant afectat și tabloul nefritic acut.',
 ['Textul definește sindromul nefrotic prin proteinurie masivă (>3,5 g/zi), hipoalbuminemie, edeme, lipidurie și hiperlipidemie.','Textul precizează că respectiva cauză cea mai frecventă este malfuncția sau lezarea podocitelor.','Glomerulonefrita acută este descrisă prin debut brusc al hematuriei glomerulare, proteinurie non-nefrotică, edeme, hipertensiune și afectare renală tranzitorie.','Textul indică inversul: podocitele (compartimentul urinar) sunt principal implicate în sindromul nefrotic, iar celulele endoteliale și mezangiale în nefrită.','Pragul de 3,5 g/zi și hiperlipidemia definesc sindromul nefrotic; proteinuria sub 1 g/zi nu corespunde acestei definiții.']],
 8,'Distractorii inversează compartimentele celulare din același paragraf și coboară proteinuria nefrotice sub pragul explicit de 3,5 g/zi.',['>3,5 g/zi','malfuncţia sau lezarea podocitelor']),

q(2,['În tratamentul general al sindromului nefrotic se recomandă:',
 ['Dietă bogată în proteine (80–90 g/zi), pentru a compensa pierderile urinare de albumină','Evitarea repausului prelungit la pat, tromboembolismul fiind foarte frecvent, în special în nefropatia membranoasă','Profilaxia antibiotică pe termen lung, preferată depistării precoce și tratamentului agresiv al infecțiilor','IECA și/sau antagoniști ai receptorilor angiotensinei II, pentru proprietățile lor antiproteinurice','La pacienții neresponsivi, furosemid 40–120 mg/zi asociat cu spironolactonă 5 mg/zi'],'BD',1354,'Glomerulul și afectarea glomerulară — Sindromul nefrotic: tratament, măsuri generale',
 'Aplicarea măsurilor generale corecte în sindromul nefrotic (aport proteic, profilaxia trombozei, abordarea infecțiilor, blocada SRA, diuretice) și evitarea erorilor frecvente.',
 ['Textul recomandă aportul normal de proteine; o dietă bogată în proteine (80-90 g/zi) crește proteinuria și poate fi dăunătoare.','Repausul prelungit la pat trebuie evitat deoarece tromboembolismul este foarte frecvent, mai ales în nefropatia membranoasă.','Textul preferă depistarea precoce și tratamentul agresiv al infecțiilor, nu profilaxia antibiotică pe termen lung.','IECA și/sau ARA II sunt indicați pentru proprietățile lor antiproteinurice în toate glomerulonefropatiile, mai ales în sindromul nefrotic.','Diureticul adăugat la furosemid la pacienții neresponsivi este amiloridul 5 mg/zi, nu spironolactona.']],
 8,'Distractorii inversează două recomandări intuitive (dieta hiperproteică, profilaxia antibiotică) și schimbă diureticul economisitor de potasiu din text.',['proprietăţile lor antiproteinurice','tromboembolismul este foarte frecvent']),

q(3,['Nefropatia cu leziuni minime:',
 ['Proteinuria este de obicei „înalt selectivă", cu pierdere de albumină, dar nu de imunoglobuline','Reprezintă 20–25% din cazurile de sindrom nefrotic la adulți','Atopia este prezentă în aproximativ 30% din cazuri, reacțiile alergice putând declanșa sindromul nefrotic','Imunofluorescența evidențiază depozite granulare de complexe imune la nivel glomerular','Două treimi dintre copii prezintă recidive după corticoterapie și necesită cure suplimentare'],'ABCE',1354,'Glomerulul și afectarea glomerulară — Cauzele sindromului nefrotic: nefropatia cu leziuni minime',
 'Recunoașterea caracteristicilor clinice, epidemiologice și imunohistologice ale nefropatiei cu leziuni minime, inclusiv rata de recidivă la copii.',
 ['Textul precizează că proteinuria este de obicei „înalt selectivă": se pierde albumina, dar nu imunoglobulinele.','Textul indică 20-25% din cazurile de sindrom nefrotic la adulți.','Atopia este prezentă în 30% din cazuri, iar reacțiile alergice pot declanșa sindromul nefrotic.','La imunofluorescență nu se evidențiază nici complexe imune, nici anticorpi anti-MBG.','Două treimi din copii prezintă recidive după corticoterapie și necesită cure suplimentare de corticosteroizi.']],
 8,'Cere reținerea mai multor procente exacte și a aspectului negativ la imunofluorescență, distractorul împrumutând un aspect din glomerulonefritele cu complexe imune.',['înalt selectivă','Atopia este prezentă în 30%'],[1355]),

q(4,['Care dintre următoarele afirmații diferențiază corect glomeruloscleroza focală și segmentară (GSFS) primară de cea secundară?',
 ['Fuziunea masivă a pedicelelor podocitare, atât în glomerulii sclerozați cât și în cei normali, pledează pentru GSFS primară','Hipoalbuminemia este caracteristică GSFS secundare și neobișnuită în forma primară','Varianta histologică perihilară se observă frecvent în GSFS primară','Recidiva pe rinichiul transplantat, uneori la câteva zile, este tipică GSFS secundare','Ștergerea pedicelelor evidentă izolat la nivelul glomerulilor sclerozați sugerează GSFS primară'],'A',1355,'Glomerulul și afectarea glomerulară — Glomeruloscleroza focală și segmentară: morfopatologie',
 'Diferențierea GSFS primare de cea secundară pe baza gradului și distribuției fuziunii pedicelelor podocitare și a trăsăturilor clinice asociate.',
 ['Textul precizează că fuziunea masivă, atât în glomerulii sclerozați cât și în cei normali, indică cel mai probabil GSFS primară.','În GSFS secundară proteinuria poate fi importantă, dar hipoalbuminemia este neobișnuită; relația este inversată.','Varianta perihilară se observă frecvent în GSFS secundară, nu în cea primară.','Recidiva pe rinichiul transplantat, uneori la câteva zile, caracterizează GSFS primară.','Ștergerea pedicelelor evidentă izolat în glomerulii sclerozați face improbabilă GSFS primară.']],
 8,'Fiecare distractor inversează o relație reală primar/secundar din același paragraf, cerând cunoașterea criteriului ultrastructural de diferențiere.',['fuziunea este masivă','joncţiunii corticomedulare'],[1356]),

q(5,['Un bărbat de 52 de ani se prezintă cu edeme și proteinurie de 6 g/zi; biopsia renală arată îngroșarea anselor capilare cu excrescențe ale membranei bazale la colorația argentică, iar serologia este pozitivă pentru anticorpi anti-PLA2R. Care dintre următoarele afirmații despre această afecțiune sunt adevărate?',
 ['La aproximativ 75% dintre pacienții cu forma autoimună, autoanticorpii sunt de tip IgG4 și vizează receptorul PLA2R de tip M','Anticorpii anti-THSD7A sunt identificați la aproximativ 10% dintre pacienții PLA2R-negativi','Corticosteroizii orali în monoterapie sunt eficienți în inducerea remisiunii','La microscopia electronică depozitele electronodense sunt subendoteliale, cu dublarea membranei bazale','O treime sau mai mulți prezintă remisiune spontană la urmărirea de 6–12 luni, mai ales cu titru redus de anti-PLA2R'],'ABE',1357,'Glomerulul și afectarea glomerulară — Glomerulonefrita membranoasă: patogeneză și tratament',
 'Integrarea tabloului histologic și serologic al glomerulonefritei membranoase autoimune cu datele de patogeneză (PLA2R, THSD7A), evoluție naturală și tratament.',
 ['Textul precizează că 75% dintre pacienți prezintă autoanticorpi IgG4 împotriva receptorului fosfolipazei A2 de tip M.','Anticorpii anti-THSD7A sunt identificați la 10% dintre pacienții PLA2R-negativi (și la 3% dintre cei PLA2R-pozitivi).','Corticosteroizii orali nu prezintă niciun beneficiu singuri, ci doar aditiv cu alte medicamente.','Depozitele electronodense sunt subepiteliale, înconjurate de excrescențe ale membranei bazale; aspectul subendotelial cu dublare este al GNMC tip 1.','O treime sau mai mulți suferă remisiuni spontane dacă sunt urmăriți 6-12 luni, mai ales cu funcție renală normală, titru redus anti-PLA2R și proteinurie mică.']],
 8,'Vignetă care cere corelarea serologiei cu procente exacte, cu localizarea ultrastructurală a depozitelor și cu lipsa de eficiență a corticoterapiei singure.',['receptorului de fosfolipazei A2','remisiuni spontane']),

q(6,['Un bărbat de 61 de ani cu diabet zaharat tip 2 de 15 ani și proteinurie de 2,8 g/zi este supus biopsiei renale, care evidențiază glomeruloscleroză nodulară intercapilară cu leziuni Kimmelstiel-Wilson, glomeruloscleroza globală interesând 30% din glomeruli. Conform clasificării Societății de Patologie Renală, nefropatia diabetică se încadrează în:',
 ['Clasa I','Clasa IIa','Clasa IIb','Clasa III','Clasa IV'],'D',1359,'Glomerulul și afectarea glomerulară — Nefropatia diabetică: clasificarea Societății de Patologie Renală',
 'Aplicarea criteriilor histologice (leziuni nodulare și procentul de glomeruloscleroză globală) pentru încadrarea nefropatiei diabetice în clasele I–IV.',
 ['Clasa I înseamnă îngroșarea izolată a MBG, fără expansiune mezangială sau glomeruloscleroză globală >50%.','Clasa IIa corespunde expansiunii mezangiale ușoare, fără leziuni nodulare.','Clasa IIb corespunde expansiunii mezangiale severe, fără leziuni nodulare.','Cadranul 36.11 definește clasa III prin glomeruloscleroză nodulară intercapilară (≥1 leziune Kimmelstiel-Wilson) și <50% glomeruloscleroză globală.','Clasa IV necesită glomeruloscleroză diabetică avansată cu >50% glomeruloscleroză globală, prag nedepășit în cazul prezentat.']],
 8,'Vignetă numerică ce impune aplicarea pragului de 50% glomeruloscleroză globală pentru a separa clasa III de clasa IV.',['Kimmelstiel-Wilson','glomeruloscleroză globală']),

q(7,['Alegeți afirmațiile corecte referitoare la nefropatia cu IgA:',
 ['Histologic se evidențiază GN proliferativă focală și segmentară cu depozite mezangiale de IgA1 polimerice','Hematuria macroscopică recurentă este un semn de prognostic nefavorabil, indicând boală avansată','Până la 50% dintre pacienți prezintă IgA seric crescut, de tip policlonal','Riscul de BCR terminală este de aproximativ 25% la cei cu proteinurie peste 1 g/zi','La pacienții cu risc crescut și eGFR sub 60 ml/min, prednisolonul cu ciclofosfamidă timp de 3 luni a demonstrat beneficiu clar'],'ACD',1362,'Glomerulul și afectarea glomerulară — Nefropatia cu IgA: histologie, tablou clinic, tratament',
 'Cunoașterea trăsăturilor histologice, a factorilor de prognostic (inclusiv semnificația paradoxală a hematuriei macroscopice) și a limitelor imunosupresiei în nefropatia cu IgA.',
 ['Textul descrie o GN proliferativă focală și segmentară cu depozite mezangiale de IgA1 polimerice.','În mod surprinzător, hematuria macroscopică recurentă este un semn de prognostic bun, pacienții prezentându-se precoce.','Până la 50% dintre pacienți prezintă IgA seric crescut (policlonal).','Riscul de BCR terminală este de aproximativ 25% la cei cu proteinurie peste 1 g/zi, creatinină crescută, HTA, izoforma DD a ECA și fibroză tubulointerstițială.','Prednisolonul singur sau cu ciclofosfamidă timp de 3 luni nu a reușit să demonstreze vreun beneficiu la acești pacienți.']],
 8,'Exploatează semnificația contraintuitivă a hematuriei macroscopice recurente și un rezultat negativ al imunosupresiei ușor de presupus pozitiv.',['lgA seric crescut','hematuria macroscopică recurentă'],[1361]),

q(8,['Nefrita tubulointerstițială acută indusă de medicamente:',
 ['Medicamentele sunt responsabile de aproximativ 70% din cazurile de NTI acută, cel mai adesea penicilinele, AINS și inhibitorii de pompă de protoni','Eozinofiluria este frecvent prezentă, iar histologia arată infiltrat interstițial care include adesea eozinofile','AINS pot asocia o glomerulopatie cu leziuni minime, cu prezentare ca sindrom nefrotic','Prednisonul în doze mari (60 mg/zi) poate reduce riscul de insuficiență renală acută severă cu necesar de dializă','Infecțiile reprezintă aproximativ 40% din cauzele de NTI acută, depășind cauzele idiopatice și NTIU'],'ABCD',1385,'Nefritele tubulointerstițiale — Nefrita tubulointerstițială acută indusă de medicamente',
 'Recunoașterea etiologiei predominant medicamentoase a NTI acute, a markerilor eozinofilici, a asocierii AINS–leziuni minime și a rolului corticoterapiei.',
 ['Textul precizează că în aproximativ 70% din cazuri NTI acută apare ca reacție de hipersensibilitate la medicamente, cel mai adesea peniciline, AINS sau IPP.','Mulți pacienți au eozinofilie și eozinofilurie, iar histologia evidențiază infiltrat interstițial care adesea include eozinofile.','AINS pot produce glomerulopatie cu leziuni minime asociată cu NTI, pacientul prezentându-se cu sindrom nefrotic.','Dozele mari de prednison (60 mg/zi) pot reduce riscul de IRA severă cu necesar de dializă și timpul de recuperare.','Cadranul 36.27 atribuie infecțiilor 15% din cazuri, nu 40%.']],
 8,'Combină procentele din Cadranul 36.27 cu un mecanism dublu (NTI plus leziuni minime) al AINS, distractorul folosind un procent greșit din același tabel.',['eozinofilie şi eozinofilurie','reacţie de hipersensibilitate'],[1386]),

q(9,['Identificați afirmația corectă referitoare la stadializarea bolii cronice de rinichi (BCR):',
 ['Un pacient cu RFG estimată de 75 ml/min/1,73 m² fără alte manifestări ale afectării renale este încadrat în stadiul G2','Stadiul 3 a fost divizat în categoriile 3a (RFG 45–59) și 3b (RFG 30–44), pacienții din stadiul mai avansat având mai multe complicații cardiovasculare','Stadiul G4 (RFG 15–29 ml/min) definește boala renală terminală','Cistatina C a fost propusă ca marker mai fidel al RFG pentru stratificarea riscului la pacienții în stadiul 5','Prevalența globală a BCR este estimată la 11–15%, majoritatea cazurilor fiind în stadiul 4'],'B',1392,'Boala cronică de rinichi — Stadializarea și prevalența',
 'Aplicarea corectă a categoriilor G ale clasificării KDIGO, inclusiv condiția suplimentară pentru stadiul G2 și motivul divizării stadiului 3.',
 ['Pacienții din stadiul G2 nu au boala decât dacă există și o altă manifestare a afectării renale (hematurie, proteinurie, modificări structurale etc.).','Textul precizează divizarea stadiului 3 în 3a și 3b deoarece pacienții în stadii mai avansate au mai multe complicații cardiovasculare, cu pragurile 45-59 și 30-44 ml/min.','Boala renală terminală corespunde stadiului G5 (RFG <15 ml/min); G4 înseamnă RFG foarte scăzută.','Cistatina C a fost propusă pentru pacienții în stadiul 3 al BCR, pentru o mai bună stratificare a riscului.','Prevalența este estimată la 11-15%, dar majoritatea cazurilor sunt în stadiul 3, nu în stadiul 4.']],
 8,'Distractorii mută praguri și stadii cu o singură treaptă și omit condiția suplimentară necesară pentru diagnosticul în stadiul G2.',['G3bA3','majoritatea cazurilor fiind în stadiul 3'],[1393]),

q(10,['Un pacient hemodializat, cu hemoglobină 88 g/L, nu răspunde la epoetină-α 300 U/kg pe săptămână; feritina serică este 620 µg/L, iar proteina C reactivă este crescută. Care dintre următoarele afirmații sunt adevărate?',
 ['Lipsa răspunsului la această doză impune excluderea deficitului de fier, sângerărilor, infecțiilor, malignităților sau anticorpilor anti-eritropoietină','Feritina peste 500 µg/L exclude deficitul funcțional de fier, astfel încât suplimentarea cu fier nu este indicată','Hepcidina, sintetizată hepatic ca răspuns la IL-6, inhibă absorbția intestinală a fierului și îl sechestrează în ficat','Ținta hemoglobinei este 100–120 g/L; valorile mai mari nu au arătat beneficii la pacienții în predializă','Fierul oral este preferat celui intravenos pentru optimizarea răspunsului la agenții stimulatori ai eritropoiezei'],'ACD',1394,'Boala cronică de rinichi — Complicațiile BCR: anemia și tratamentul cu ASE',
 'Interpretarea rezistenței la eritropoietină în BCR, inclusiv conceptul de deficit funcțional de fier în inflamație și rolul hepcidinei.',
 ['Textul cere evaluarea pacienților care nu răspund la 300 U/kg epoetină-α pe săptămână pentru deficit de fier, sângerări, malignități, infecții, inflamații sau anticorpi neutralizanți.','Deficitul funcțional de fier apare frecvent în inflamația cronică chiar cu feritina >500 µg/L, iar fierul intravenos optimizează răspunsul la ASE.','Hepcidina, reactant de fază acută produs de ficat ca răspuns la IL-6, inhibă absorbția intestinală a fierului și îl sechestrează în ficat.','Ținta hemoglobinei este 100-120 g/L; studiile în predializă nu au arătat beneficii pentru ținte >120 g/L.','Suplimentarea cu fier intravenos este preferată administrării orale pentru optimizarea răspunsului la ASE.']],
 8,'Vignetă cu valori de laborator care par să excludă deficitul de fier, testând conceptul de deficit funcțional și inversând calea de administrare preferată.',['Deficitul funcţional de fier','hepcidină']),

q(11,['Tulburările minerale osoase asociate bolii cronice de rinichi (TMO-BCR):',
 ['FGF23, eliberat din osteocite ca răspuns la retenția de fosfat, induce fosfaturie și inhibă 1α-hidroxilaza renală','Hiperparatiroidismul secundar se asociază cu hipocalcemie, hiperfosfatemie, PTH crescut și fosfatază alcalină crescută','În boala osoasă adinamică fosfataza alcalină serică este normală, iar PTH-ul este scăzut','Aspectul de „tricou de rugby" al coloanei vertebrale este expresia radiologică a osteomalaciei','La pacienții dializați se urmărește o valoare a PTH de 2–3 ori limita superioară a normalului, pentru a evita boala osoasă adinamică'],'ABCE',1395,'Boala cronică de rinichi — Tulburările minerale osoase asociate BCR: patogeneză și tratament',
 'Corelarea modificărilor biochimice și radiologice cu tipurile de boală osoasă din BCR și înțelegerea rolului FGF23 și al țintei terapeutice pentru PTH.',
 ['Fosforul reținut determină eliberarea de FGF23 din osteocite, care induce fosfaturie și inhibă 1α-hidroxilaza renală.','Modificările biochimice caracteristice hiperparatiroidismului secundar sunt hipocalcemia, hiperfosfatemia, PTH ridicat și fosfataza alcalină crescută.','În boala osoasă adinamică fosfataza alcalină serică este normală iar PTH-ul este scăzut, cu osteopenie la DXA.','Aspectul de „tricou de rugby" se datorează osteosclerozei din hiperparatiroidismul persistent, nu osteomalaciei.','La pacienții dializați se dorește PTH de 2-3 ori valoarea maximă a normalului, pentru ca turnoverul osos să continue și boala adinamică să nu apară.']],
 8,'Cere diferențierea profilurilor biochimice ale mai multor tipuri de boală osoasă și atribuirea corectă a unui semn radiologic clasic.',['osteita fibroasă chistică','tricou de rugby'],[1394]),

q(12,['Selectați enunțurile adevărate despre prevenția nefropatiei de contrast:',
 ['Diabetul zaharat, prin el însuși, nu este considerat un factor de risc','Metforminul poate precipita acidoza lactică și ar trebui oprit dacă creatinina depășește 130 µmol/L','Dopamina, teofilina și dializa profilactică s-au dovedit benefice în prevenție','N-acetilcisteina administrată 48 de ore înainte oferă un beneficiu major, demonstrat consistent','Hidratarea peri-procedurală trebuie evitată, pentru a nu precipita supraîncărcarea volemică'],'AB',1392,'Boala cronică de rinichi — Nefropatia de contrast: prevenție (context de injurie renală acută)',
 'Aplicarea măsurilor reale de prevenție a IRA post-contrast și recunoașterea intervențiilor fără beneficiu (dopamină, teofilină, dializă profilactică).',
 ['Textul precizează explicit că diabetul în sine nu este un factor de risc.','Textul indică oprirea metforminului dacă creatinina depășește 130 µmol/L, cu reluare doar când funcția renală revine la nivelul de bază.','Textul afirmă că dopamina, teofilina și dializa profilactică nu sunt benefice.','N-acetilcisteina poate oferi cel mult un beneficiu marginal, nu unul major.','Prevenția include hidratarea cu 1 L ser fiziologic 0,9% sau bicarbonat 1,4%, cu evitarea supraîncărcării doar la pacienții la risc, nu omiterea hidratării.']],
 8,'Capcana principală este statutul diabetului ca factor de risc, pe care textul îl neagă, alături de intervenții profilactice frecvent prescrise fără evidență.',['Diabetul în sine nu este un factor de risc','130 µmol/L']),

q(13,['Următoarele afirmații despre hemodializă și momentul inițierii sunt adevărate:',
 ['Există o tendință generală de a începe dializa la o RFG în jur de 10 ml/min, decizia fiind adaptată simptomelor și preferințelor pacientului','O dializă eficientă necesită un debit sanguin de 250–450 mL/min prin abordul vascular','Rata de reducere a ureei (URR) are ca valoare țintă peste 65% pe ședință','Un dializant cu potasiu 1–3 mmol/L produce un bilanț pozitiv al potasiului de 1–2 mmol/kg pe ședință','Amiloidoza asociată dializei rezultă din eliminarea deficitară a albuminei, o moleculă de 11,8 kDa'],'ABC',1399,'Boala cronică de rinichi — Hemodializa: inițiere, principii și obiective',
 'Reținerea pragului practic de inițiere (RFG ~10 ml/min), a parametrilor cantitativi ai hemodializei și a mecanismului amiloidozei asociate dializei.',
 ['Textul precizează tendința generală de a începe dializa la o RFG în jur de 10 ml/min, adaptat fiecărui pacient după simptome și preferințe.','Textul precizează că o dializă eficientă necesită un debit sanguin între 250 și 450 mL/min.','URR are valoare țintă >65% pe ședință, ca parametru minim al unei dialize adecvate.','Dializantul cu potasiu redus (1-3 mmol/L) permite un bilanț negativ al potasiului de 1-2 mmol/kg pe ședință, nu pozitiv.','Amiloidoza asociată dializei se datorează eliminării deficitare a β2-microglobulinei (11,8 kDa), nu a albuminei.']],
 8,'Testează pragul de inițiere și valori numerice precise, inversând totodată sensul bilanțului potasiului și molecula implicată în amiloidoză.',['în jur de 10 ml/min','250 şi 450 mL/min'],[1400]),

q(14,['Caracteristicile bolii polichistice renale autozomal dominante (BPRAD) includ:',
 ['Mutațiile genei PKD1, situată pe cromozomul 16, sunt responsabile de aproximativ 85% din cazuri','Calculii renali apar la 10–20% dintre pacienți și sunt cel mai frecvent din oxalat de calciu, radioopaci','Circa 10% dintre pacienți au un anevrism intracranian asimptomatic, screeningul fiind recomandat la 18–40 de ani celor cu istoric familial','Forma autozomal recesivă se datorează mutațiilor genei PKD2 de pe cromozomul 4','Probabilitatea de a supraviețui până la 70 de ani fără substituție renală este de aproximativ 70%'],'AC',1405,'Bolile renale chistice — Boala polichistică renală autozomal dominantă',
 'Cunoașterea bazei genetice a BPRAD, a complicațiilor extrarenale (anevrisme intracraniene) și a datelor prognostice, cu diferențierea de forma autozomal recesivă.',
 ['Textul precizează că mutațiile PKD1 (cromozomul 16) sunt responsabile de 85% din cazuri, restul fiind date de PKD2.','Calculii apar la 10-20% dintre pacienți, dar sunt compuși mai frecvent din acid uric și sunt radiotransparenți.','Aproximativ 10% au un anevrism intracranian asimptomatic; screeningul se recomandă între 18 și 40 de ani la cei cu istoric familial pozitiv.','Forma autozomal recesivă se datorează mutațiilor genei PKHD1 de pe cromozomul 6p21.1-p12; PKD2 (cromozomul 4) aparține formei dominante.','Probabilitatea de a supraviețui până la 70 de ani fără necesar de substituție renală este de 30%, nu 70%.']],
 8,'Amestecă genele și cromozomii formelor dominantă și recesivă și inversează compoziția calculilor și procentul de supraviețuire fără dializă.',['policistina','anevrism intracranian asimptomatic']),
];
