import {advancedQuestion} from './advanced-author';
import type {SourceRow} from './source-author';

const EDITION='Chirurgie generală și specialități chirurgicale, ediția pentru rezidențiat MG 2025';
const pdfOffset=(p:number)=>p-327;
const q=(n:number,row:SourceRow,score:number,reason:string,expressions:string[],related:number[]=[])=>
 advancedQuestion('orl',27,pdfOffset,`orl-adv-${String(n).padStart(3,'0')}`,row,[score,reason],expressions,undefined,related,'Lawrence',EDITION);

export const ORL_ADVANCED=[
q(1,['Impactul patologiilor din sfera ORL:',
 ['Mai mult de 60% dintre consulturile medicale la copii sunt consecința unor patologii din sfera ORL','Peste 50% dintre consulturile la adulți sunt consecința unor patologii din sfera ORL','Rinosinuzita are cel mai mare impact financiar asupra economiei din SUA, prin scăderea productivității și costurile serviciilor medicale','Hipoacuzia neurosenzorială depășește rinosinuzita ca impact financiar asupra economiei din SUA','Cele mai frecvente intervenții chirurgicale din SUA, în acest capitol, sunt laringectomiile totale'],'ABC',548,'Otorinolaringologia — Introducere',
 'Recunoașterea ponderii consulturilor ORL la copii și adulți și a rinosinuzitei ca principală povară economică, distinctă de intervențiile timpanale și amigdaliene.',
 ['Textul citează explicit pragul de peste 60% dintre consulturile pediatrice.','Pragul de peste 50% la adulți este enunțat în aceeași frază.','Rinosinuzita este identificată ca având cel mai mare impact financiar în SUA.','Textul atribuie impactul financiar maxim rinosinuzitei, nu hipoacuziei.','Intervențiile citate ca fiind printre cele mai frecvente sunt tonsilectomiile/adenoidectomiile și plasarea de aeratoare timpanale, nu laringectomia.']],
 8,'Distractorii înlocuiesc rinosinuzita cu hipoacuzia și substituie tonsilectomia/timpanostomia cu laringectomia, două confuzii de ierarhie epidemiologico-chirurgicală.',['mult de 60%','Rinosinuzita are cel mai mare impact financiar']),

q(2,['Conductul auditiv extern se caracterizează prin:',
 ['Treimea laterală are o porțiune cartilaginoasă','Două treimi mediale au o porțiune osoasă','Tegumentul porțiunii cartilaginoase conține foliculi piloși și glande ceruminoase','Treimea medială este cartilaginoasă, iar cele două treimi laterale sunt osoase','Urechea internă este constituită din trompa lui Eustachio, membrana timpanică și lanțul osicular'],'ABC',549,'Urechea — Anatomie',
 'Diferențierea segmentului cartilaginos lateral al conductului de porțiunea osoasă medială și de conținutul urechii medii.',
 ['Textul plasează porțiunea cartilaginoasă în treimea laterală.','Porțiunea osoasă ocupă două treimi mediale.','Foliculii piloși și glandele ceruminoase sunt descrise în tegumentul porțiunii cartilaginoase.','Raportul cartilaj/os este inversat față de text.','Trompa, timpanul și oscioarele definesc urechea medie, nu urechea internă.']],
 8,'Inversează raportul 1/3 față de 2/3 al conductului și mută conținutul urechii medii în urechea internă.',['treimea laterală','glande ceruminoase']),

q(3,['Alegeți afirmațiile corecte referitoare la urechea internă și nervul facial:',
 ['Urechea internă este alcătuită din cohlee, canalele semicirculare și conductul auditiv intern','Organul lui Corti se află în cohlee, macula în utriculă și saculă, iar crestele ampulare în canalele semicirculare','Conductul auditiv intern conține nervii cranieni VII și VIII','Nervul facial se află postero-inferior de segmentele auditive și vestibulare ale nervului VIII','Fibrele secretomotorii ale nervului intermediar se opresc la glanda parotidă, fără a atinge glandele lacrimale'],'ABC',549,'Urechea internă și nervul facial — Anatomie',
 'Recunoașterea celor trei organe senzoriale ale urechii interne și a conținutului conductului auditiv intern.',
 ['Cele trei componente ale urechii interne sunt enumerate explicit.','Cele trei organe senzoriale și sediile lor sunt descrise în text.','Nervii VII și VIII sunt citați ca fiind conținuți în conductul auditiv intern.','Textul plasează nervul facial antero-superior, nu postero-inferior, față de VIII.','Nervul intermediar destinează fibre secretomotorii glandelor sublinguală, submandibulară, lacrimale și mucoaselor nazale și palatine.']],
 8,'Inversează poziția facialului față de VIII și limitează greșit teritoriul secretomotor al nervului intermediar.',['Organul lui Corti','conductul auditiv intern']),

q(4,['Egalizarea presiunilor în urechea medie se realizează prin:',
 ['Deschiderea periodică a trompei lui Eustachio, în mod normal închisă, produsă de masticație sau deglutiție','Menținerea trompei lui Eustachio permanent deschisă, cu închidere doar în timpul deglutiției','Contracția continuă a mușchiului scăriței, independent de deglutiție','Comunicarea directă a urechii medii cu fereastra rotundă, fără rol tubar','Egalizarea pasivă prin porțiunea osoasă a conductului auditiv extern'],'A',549,'Urechea medie — Fiziologie',
 'Identificarea deschiderii intermitente a trompei lui Eustachio ca mecanism de egalizare a presiunilor.',
 ['Textul descrie dilatarea periodică a cavității aeriene prin masticație sau deglutiție, care deschide trompa normal închisă.','Trompa este descrisă ca fiind în mod normal închisă, nu permanent deschisă.','Muşchii scăriței și ai ciocanului nu sunt mecanismul de egalizare a presiunilor.','Fereastra ovală, nu rotundă, este contactul piciorului scăriței; egalizarea rămâne tubară.','Conductul auditiv extern nu egalizează presiunea din urechea medie.']],
 8,'Inversează starea de repaus a trompei (închisă față de deschisă) și atribuie egalizarea unor structuri ale urechii interne sau externe.',['trompei lui Eustachio','masticaţie sau deglutiţie']),

q(5,['Pe audiograma tonală, intervalul care definește hipoacuzia moderată este:',
 ['0–20 dB','25–40 dB','40–70 dB','70–90 dB','peste 90 dB'],'C',553,'Evaluare — Audiometria tonală',
 'Aplicarea pragurilor audiometrice care separă hipoacuzia ușoară de cea moderată, severă și profundă.',
 ['0–20 dB este considerat auz normal.','25–40 dB definește hipoacuzia ușoară.','Textul atribuie intervalul 40–70 dB hipoacuziei moderate.','70–90 dB corespunde hipoacuziei severe.','Pragul peste 90 dB definește hipoacuzia profundă.']],
 8,'Cele cinci intervale consecutive din aceeași frază sunt ușor de permutat, mai ales pragul de 40 dB partajat între ușoară și moderată.',['40-70 dB hipoacuzie mo','70-90 dB hipoacuzie severă']),

q(6,['Care dintre următoarele afirmații privind testele cu diapazonul sunt adevărate?',
 ['Testul Weber folosește un diapazon de 512 Hz plasat central pe frunte, dorsum nasi sau maxilar','Lateralizarea Weber într-o singură ureche semnalează hipoacuzie neurosenzorială contralaterală sau de conducere ipsilaterală','Un pacient cu hipoacuzie de conducere aude diapazonul Rinne mai bine pe mastoidă decât la 2 cm de conduct','Audiometria tonală evaluează recunoașterea vorbirii și discriminarea silabelor','Testul Rinne este mai informativ când hipoacuzia este mixtă și simetrică, decât când este pură și unilaterală'],'ABC',553,'Evaluare — Testele cu diapazonul',
 'Interpretarea Weber și Rinne în hipoacuzia pură unilaterală și recunoașterea limitei audiometriei tonale.',
 ['Frecvența de 512 Hz și locurile de plasare sunt specificate pentru Weber.','Regula contralateral-neurosenzorial / ipsilateral-conducere este enunțată explicit.','În hipoacuzia de conducere, conducerea osoasă pe mastoidă depășește calea aeriană.','Textul precizează că audiometria tonală nu evaluează recunoașterea vorbirii sau discriminarea.','Textul atribuie valoare diagnostică mai mare testelor când hipoacuzia este doar de conducere sau doar neurosenzorială și unilaterală.']],
 8,'Inversează regula de lateralizare Weber și atribuie audiometriei tonale o funcție (discriminarea vorbirii) pe care textul o exclude.',['diapazon de 512 Hz','2 cm de conductul auditiv']),

q(7,['Tumorile glandelor salivare se caracterizează prin:',
 ['Aproximativ 85% își au originea la nivelul glandei parotide','Din tumorile parotidei, 75% sunt benigne, față de 50% la submandibulară și 30% la glandele minore','Aproximativ 80% dintre tumorile benigne sunt adenoame pleomorfe','Cea mai frecventă malignitate a glandelor salivare principale este carcinomul adenoid chistic','Tumora Warthin apare predominant la femeile nefumătoare, în lobul profund al parotidei'],'ABC',579,'Glandele salivare — Tumorile benigne și maligne',
 'Compararea ratelor de benignitate pe sediu și recunoașterea adenomului pleomorf, distincție de carcinomul mucoepidermoid și de tumora Warthin.',
 ['Proporția de 85% cu origine parotidiană este explicită.','Cele trei procente de benignitate (75%, 50%, 30%) sunt enumerate pe sedii.','Adenomul pleomorf/tumora mixtă reprezintă aproximativ 80% dintre benigne.','Carcinomul mucoepidermoid este cea mai frecventă malignitate a glandelor principale; adenoidul chistic este cel mai frecvent în afara parotidei.','Tumora Warthin apare în 8% din cazuri, la bărbați fumători, preponderent în coada parotidei.']],
 8,'Permutează ierarhia mucoepidermoid față de adenoid chistic și profilul Warthin (sex, fumat, coada parotidei).',['glandei parotide','adenoame pleomorfe']),

q(8,['Care dintre următoarele afirmații diferențiază corect chistul de canal tireoglos de anomalia de arc branhial?',
 ['Chistul tireoglos se situează pe linia mediană, de la baza limbii la istmul tiroidian','Chistul tireoglos ascensionează atât la deglutiție, cât și la protruzia limbii','Tratamentul chistului tireoglos este operația Sistrunk','Anomaliile de arc branhial se tratează prin operația Sistrunk, identic chistului tireoglos','Fistula de canal tireoglos este o malformație congenitală prezentă de la naștere'],'ABC',581,'Anomalii congenitale cervicale — Tabelul 27-11',
 'Contrastarea localizării mediane, a mobilității cu limba și a operației Sistrunk față de traiectul lateral și tehnica McFee.',
 ['Localizarea aproape mediană, de la baza limbii la istm, este enunțată pentru canalul tireoglos.','Ascensionarea la deglutiție și la protruzia limbii este semnul clinic distinctiv.','Tabelul indică operația Sistrunk ca tratament al anomaliei tireoglose.','Anomaliile de arc branhial sunt tratate prin tehnica McFee „în scară”, nu prin Sistrunk.','Tabelul precizează că fistula tireoglosă nu este congenitală, ci urmează infecției sau rezecției inadecvate.']],
 8,'Schimbă operația Sistrunk cu McFee și transformă fistula tireoglosă dobândită într-una congenitală.',['Operaţia Sistrunk','protruzia limbii']),

q(9,['Traumatismele pavilionului auricular și ale membranei timpanice:',
 ['Hematomul auricular separă cartilajul de pericondru și, netratat, duce la deformarea de „ureche conopidiformă”','Aproximativ 90% dintre perforațiile timpanice posttraumatice se vindecă fără sechele','Dacă perforația nu se închide în câteva luni, se recomandă timpanoplastie cu grefă din fascia temporalis','Degerăturile urechii impun debridare agresivă imediată a escarei și presiune continuă pe cartilajul expus','Fracturile longitudinale de os temporal însumează aproximativ 15% din fracturile acestui os'],'ABC',556,'Trauma auriculară — Perforații și fracturi de os temporal',
 'Aplicarea drenajului hematomului auricular, a ratei de vindecare a perforațiilor și a predominanței fracturilor longitudinale.',
 ['Mecanismul de forfecare și sechela de ureche conopidiformă sunt descrise explicit.','Rata de 90% de vindecare spontană a perforațiilor posttraumatice este citată.','Timpanoplastia cu fascia temporalis este recomandată dacă vindecarea întârzie câteva luni.','Textul cere debridare conservativă, păstrarea umedă a cartilajului și evitarea presiunii.','Fracturile longitudinale însumează aproximativ 85% din fracturile de os temporal, nu 15%.']],
 8,'Inversează rata 85% față de 15% a fracturilor longitudinale și transformă debridarea conservativă într-una agresivă.',['conopidifonnă','timpanoplastia']),

q(10,['În fractura longitudinală de os temporal, paralizia de nerv facial este:',
 ['Frecventă, în jur de 50% din cazuri','Rară, în jur de 15% din cazuri','Prezentă în toate fracturile cu hemotimpan','Mai frecventă decât în fractura orizontală','Independentă de mecanismul de producere, identică în ambele tipuri'],'B',557,'Fracturile de os temporal — Tabelul 27-5',
 'Reținerea contrastului numeric dintre paralizia facială rară (~15%) din fractura longitudinală și cea frecventă (~50%) din fractura orizontală.',
 ['Pragul de ~50% aparține fracturii orizontale, nu celei longitudinale.','Tabelul indică paralizie facială rară (~15%) în fractura longitudinală.','Hemotimpanul figurează la fractura orizontală; nu implică paralizie facială constantă.','Fractura orizontală, nu cea longitudinală, asociază paralizie facială frecventă.','Tabelul leagă procentele de tipul de fractură (longitudinală față de orizontală).']],
 8,'Permutează pragurile 15% și 50% între fractura longitudinală și cea orizontală, confuzie clasică de tabel.',['Rar(-15%)','Frecvent']),

q(11,['Otita externă difuză, denumită și „urechea înotătorului”:',
 ['Cel mai frecvent agent patogen implicat este Pseudomonas','Tratamentul include toaletarea conductului pentru a permite accesul soluțiilor topice','Dacă edemul împiedică picăturile, se plasează un pansament mic, cu instilații de 2–4 ori pe zi','Agentul etiologic dominant este Streptococcus pneumoniae, ca în otita medie acută','Fungii sunt agenții primari ai otitei externe difuze, înaintea oricărei bacterii'],'ABC',557,'Otita externă — Formă difuză',
 'Recunoașterea Pseudomonas ca agent principal și a strategiei de toaletă plus pansament, distinctă de flora otitei medii.',
 ['Pseudomonas este citat ca cel mai frecvent agent patogen.','Toaletarea conductului este descrisă ca etapă care facilitează soluțiile topice.','Pansamentul cu instilații de 2–4 ori pe zi este indicația când conductul este obstruat de edem.','S. pneumoniae este agent al otitei medii acute, nu agentul dominant al otitei externe difuze.','Fungii sunt incriminați de obicei în infecții secundare pe epiteliu descuamat, nu ca agenți primari.']],
 8,'Mută S. pneumoniae din OMA în otita externă și promovează fungii din rol secundar în rol etiologic primar.',['urechea înotătorului','Cel mai frecvent agent patogen']),

q(12,['Otita externă necrotizantă, numită anterior otită externă malignă:',
 ['Reprezintă osteomielita osului temporal și a bazei craniului','Cel mai frecvent agent este Pseudomonas aeruginosa','Pacienții la risc sunt diabeticii și imunocompromișii','Infecția nu răspunde la tratamentul topic, necesitând antibioterapie sistemică și topică luni de zile','Debridarea chirurgicală este inutilă chiar în stadiile precoce, fiind rezervată doar sechelelor tardive'],'ABCD',557,'Otita externă necrotizantă',
 'Recunoașterea osteomielitei de bază de craniu la diabetic și a eșecului terapiei doar topice.',
 ['Definiția de osteomielită a osului temporal și a bazei craniului este explicită.','Pseudomonas aeruginosa este agentul cel mai frecvent citat.','Diabetul zaharat și imunocompromiterea sunt grupurile la risc.','Lipsa răspunsului la topic și durata de luni a terapiei agresive sunt descrise pe pagina următoare.','Textul precizează că debridarea chirurgicală poate fi utilă în stadiile precoce.']],
 8,'Acceptă corect eșecul topic, dar distractorul final neagă debridarea precoce, confuzie între urgența medicală și fereastra chirurgicală.',['Pseudomonas aeruginosa','diabet zaharat'],[558]),

q(13,['Următoarele afirmații despre otita medie acută sunt adevărate:',
 ['În SUA este cea mai frecventă infecție pentru care se prescriu antibiotice copiilor','Până la vârsta de 2 ani, 75% dintre copii suferă cel puțin trei episoade','Agenții cei mai frecvenți sunt Streptococcus pneumoniae, Moraxella catarrhalis și Haemophilus influenzae','Dacă se utilizează antibiotice, doza mare de amoxicilină (90 mg/kgc/zi) este de primă linie','Timpanocenteza rămâne tratamentul de bază, recomandat de rutină în era antibioticelor'],'ABCD',558,'Otita medie acută — Diagnostic și tratament',
 'Aplicarea epidemiologiei, a tridentului bacterian și a dozei de amoxicilină, cu recunoașterea rolului actual marginal al timpanocentezei.',
 ['Afirmația despre prescrierea de antibiotice la copii este explicită.','Procentul de 75% până la 2 ani, cu cel puțin trei episoade, este citat.','Cei trei agenți sunt enumerați în această ordine.','Doza de 90 mg/kgc/zi de amoxicilină este recomandarea de primă linie.','Textul precizează că timpanocenteza este rar recomandată în prezent, deși permite cultură.']],
 8,'Păstrează doza de 90 mg/kgc/zi ca fapt memorabil, dar inversează statutul actual al timpanocentezei din era pre-antibiotică.',['90 mg/kgc/zi','75% dintre copii']),

q(14,['Plasarea de tub prin timpanostomie este luată în considerare după:',
 ['6 episoade de otită medie acută în 6 luni','Un singur episod de OMA cu febră, fără alte criterii','3 episoade de OMA pe tot parcursul copilăriei','Otita medie seroasă rezolvată în prima lună de urmărire','Orice OMA tratată cu azitromicină pentru alergie la penicilină'],'A',558,'Otita medie acută — Timpanostomia',
 'Reținerea pragului de 6 episoade în 6 luni ca indicație de tub de timpanostomie în OMA recurentă.',
 ['Textul definește candidații prin 6 episoade de OMA în 6 luni.','Un episod izolat nu îndeplinește criteriul de recurență.','Pragul nu este 3 episoade pe tot parcursul copilăriei.','OMS autolimitată la 3 luni nu este indicația de tub din acest paragraf; paragraful citează OMA recurentă.','Alergia la penicilină orientează spre macrolid, nu spre timpanostomie de principiu.']],
 8,'Distractează cu pragul de 3 episoade (folosit la copii pentru OMA ca epidemiologie) în locul criteriului 6 în 6 luni.',['6 episoade','tub prin timpanostomie']),

q(15,['Otita medie seroasă:',
 ['Constă în lichid în urechea medie, fără semne și simptome de infecție','Este o boală autolimitată; urmărirea 3 luni este recomandată dacă nu există risc de tulburări de limbaj','Antibioticele, antihistaminicele, decongestionantele și steroizii nu și-au dovedit eficiența','Este cea mai frecventă patologie a urechii medii, înaintea otitei medii acute','Miringotomia cu tuburi de ventilație se indică din prima săptămână, fără perioadă de observație'],'ABC',558,'Otita medie seroasă',
 'Recunoașterea OMS ca a doua patologie ca frecvență, autolimitată, fără beneficiu demonstrat al medicației antiinflamatorii sau antihistaminice.',
 ['Definiția prin lichid fără semne de infecție este explicită.','Ghidul citat recomandă urmărire 3 luni în absența riscului de limbaj.','Ineficiența antibioticelor, antihistaminicelor, decongestionantelor și steroizilor este enunțată.','Textul o plasează ca a doua cea mai frecventă patologie a urechii medii, după OMA.','Tuburile se recomandă dacă lichidul persistă peste 3 luni, nu din prima săptămână.']],
 8,'Inversează locul OMS față de OMA și comprimă fereastra de 3 luni într-o indicație chirurgicală imediată.',['Timpanometria este utilă','3 luni'],[559]),

q(16,['Colesteatomul urechii medii:',
 ['Este un chist acoperit de tegument, producător de keratină, cu origine posibilă într-o membrană timpanică patologică','Enzimele osteolitice din baza membranei produc osteonecroză, cu risc de eroziune a oscioarelor, a nervului facial și a cohleei','Răspunde durabil la antibiotice topice, similar otitei externe difuze','Se dezvoltă pe fondul unei presiuni pozitive continue în urechea medie','Otoscopia arată o masă eritematoasă pulsatilă în spatele unui timpan translucid, ca în glomus tympanicum'],'AB',559,'Colesteatomul',
 'Recunoașterea naturii de sac de retracție keratinizant și a osteonecrozei enzimatice, distincte de glomus și de otita externă.',
 ['Definiția de chist tegumentar producător de keratină este explicită.','Lista structurilor erodabile și osteonecroza enzimatică sunt descrise.','Tratamentul necesar este excizia chirurgicală, nu terapia topică ca în otita externă.','Colesteatomul se dezvoltă pe disfuncție tubară cronică și presiune negativă, nu pozitivă.','Masa albicioasă cu granulație și perforație este aspectul otoscopic; masa eritematoasă pulsatilă descrie glomus tympanicum.']],
 8,'Inversează semnul presiunii (negativă față de pozitivă) și substituie aspectul albicios cu masa pulsatilă a glomusului de pe pagina următoare.',['produce keratină','Enzimele osteolitice']),

q(17,['Identificați afirmația corectă referitoare la otoscleroză:',
 ['Afectează cel mai frecvent adulții tineri și produce hipoacuzie de transmisie prin fixarea piciorului scăriței','Fixează ciocanul, nu scărița, și produce hipoacuzie neurosenzorială pură de la debut','Nu are predispoziție genetică și se ameliorează caracteristic în sarcină','Stapedectomia este inutilă, proteza auditivă fiind singura opțiune acceptată de majoritatea pacienților','Afectează doar bărbații, fără implicare cohleară posibilă'],'A',559,'Otoscleroza',
 'Recunoașterea fixării piciorului scăriței ca mecanism al hipoacuziei de transmisie la adultul tânăr.',
 ['Vârsta, tipul de hipoacuzie și fixarea scăriței sunt enunțate explicit.','Osul spongios afectează piciorul scăriței; hipoacuzia neurosenzorială apare doar dacă este antrenată și cohleea.','Textul descrie predispoziție genetică și agravare în sarcină, nu ameliorare.','Majoritatea pacienților preferă înlocuirea chirurgicală a scăriței (stapedectomie).','Afectează femeile și bărbații; cohleea poate fi antrenată secundar.']],
 8,'Schimbă oscicul fixat (ciocan față de scăriță) și inversează evoluția din sarcină (agravare față de ameliorare).',['piciorul scăriţei','stapedectomie']),

q(18,['Hipoacuzia neurosenzorială dobândită:',
 ['Presbiacuzia rezultă din degenerare cohleară și afectează 75% dintre oameni până la 80 de ani','Expunerea prelungită la zgomote cu frecvența peste 90 dB lezează celulele păroase, pe frecvențe medii și înalte','Eritromicina și aspirina pot determina o hipoacuzie neurosenzorială reversibilă','Hipoacuzia de cauză genetică pediatrică afectează 1 din 200 de copii, de obicei cu transmitere dominantă','Aminoglicozidele lezează doar celulele păroase ale urechii medii, fără impact vestibular'],'ABC',559,'Hipoacuzia neurosenzorială',
 'Separarea presbiacuziei, a pragului de 90 dB și a ototoxicității reversibile (eritromicină, aspirină) de leziunea aminoglicozidică vestibulo-cohleară.',
 ['Procentul de 75% până la 80 de ani este citat pentru presbiacuzie.','Pragul de peste 90 dB și topografia pe frecvențe medii și înalte sunt explicite.','Reversibilitatea hipoacuziei induse de eritromicină și aspirină este menționată.','Textul citează 1 din 2.000 de copii, de obicei cu model recesiv, nu 1 din 200 dominant.','Aminoglicozidele lezează cohleea și celulele păroase vestibulare, nu urechea medie.']],
 8,'Permutează 1/2.000 cu 1/200 și mută leziunea aminoglicozidică din labirint în urechea medie, lângă pragul de 90 dB comun cu hipoacuzia profundă.',['75% dintre oameni','aspirina']),

q(19,['Care dintre următoarele afirmații diferențiază corect neuronita vestibulară de vertijul pozițional paroxistic benign?',
 ['Neuronita vestibulară produce vertij sever cu durată de câteva zile și ameliorare în câteva săptămâni','Vertijul pozițional paroxistic benign durează de la câteva secunde până la câteva minute și se diagnostichează prin manevra Dix-Hallpike','BPPV este determinat de canalolitiază sau otoconii libere în endolimfa canalelor semicirculare','Manevra Epley este inutilă în BPPV, procedurile distructive vestibulare fiind prima intenție','Inhibitorii vestibulari se prescriu luni de zile în neuronită, ca tratament de fond, nu 1–2 zile'],'ABC',559,'Patologia vestibulară — Neuronita și BPPV',
 'Contrastarea duratei (zile față de secunde-minute) și a diagnosticului Dix-Hallpike, cu rezervarea procedurilor distructive cazurilor refractare.',
 ['Durata de zile cu ameliorare în săptămâni este caracteristică neuronitei.','Fereastra de secunde-minute și manevra Dix-Hallpike definesc BPPV.','Canalolitiaza/otoconiile libere sunt mecanismul enunțat.','Manevrele de repoziționare (Epley) sunt foarte eficiente; procedurile distructive sunt rezervate cazurilor refractare.','Inhibitorii vestibulari se folosesc pe termen scurt, 1–2 zile, nu luni.']],
 8,'Inversează durata episoadelor și promovează distrucția vestibulară ca primă linie în locul manevrei Epley.',['Dix-Hallpike','câteva secunde'],[560]),

q(20,['Boala Meniere:',
 ['Este hidrops endolimfatic, cu hipoacuzie episodică, vertij debilitant de câteva ore, tinitus și plenitudine auriculară','Este de obicei unilaterală și se asociază cu bombarea sau ruperea membranei Reissner','Tratamentul medical constă în regim hiposodat și diuretice','Decompresia sacului endolimfatic este tratamentul inițial, înaintea oricărei măsuri dietetice','Vertijul durează câteva secunde și se reproduce prin manevra Dix-Hallpike'],'ABC',560,'Boala Meniere — Hidropsul endolimfatic',
 'Recunoașterea tetradei Meniere și a duratei de ore, distinctă de BPPV, cu ierarhia hiposodat/diuretice înaintea chirurgiei.',
 ['Tetrada clinică și identificarea ca hidrops endolimfatic sunt explicite.','Unilateralitatea și leziunea membranei Reissner sunt descrise.','Regimul hiposodat și diureticele constituie tratamentul medical.','Chirurgia sacului sau a nervului vestibular este rezervată vertijului debilitant neresponsiv.','Durata de secunde și Dix-Hallpike definesc BPPV, nu Meniere.']],
 8,'Mută durata de secunde a BPPV asupra Meniere și inversează ierarhia medical-chirurgicală a sacului endolimfatic.',['hidropsul endolimfatic','membranei Reissner']),

q(21,['Paralizia Bell:',
 ['Este cea mai frecventă formă de paralizie facială, idiopatică, cu infecție herpetică confirmată prin PCR','Se instalează în câteva ore, poate deveni completă, asociază durere mastoidiană și durează sub 72 de ore','Leziunile supranucleare, ca ischemia cerebrovasculară, afectează caracteristic fruntea, lipsită de inervație încrucișată','Majoritatea cazurilor necesită explorare chirurgicală imediată a conductului auditiv intern','Paralizia persistentă sau recurentă nu justifică imagistică, prognosticul fiind rezervat doar în traumatism'],'AB',560,'Patologia nervului facial — Paralizia Bell',
 'Recunoașterea ferestrei sub 72 de ore și a sparing-ului frunții în leziunea supranucleară, opus paraliziei Bell periferice.',
 ['Caracterul idiopatic, frecvența maximă și confirmarea HSV prin PCR sunt enunțate.','Cinetica de ore, durerea mastoidiană și pragul de 72 de ore sunt descrise.','Textul precizează că leziunile supranucleare nu afectează frecvent fruntea, datorită fibrelor corticobulbare directe și încrucișate.','Majoritatea cazurilor se vindecă spontan; chirurgia nu este tratamentul inițial.','Paralizia persistentă sau recurentă impune imagistică pentru a exclude o tumoră.']],
 8,'Inversează semnul frunții (supranuclear față de periferic) și transformă evoluția spontană într-o indicație chirurgicală de urgență.',['paralizie Bell','<72 de ore']),

q(22,['Semnul patognomonic al schwanomului vestibular este:',
 ['Hipoacuzie neurosenzorială cu discriminare vocală slabă, însoțită de tinitus','Hipoacuzie de transmisie simetrică, cu Rinne negativ bilateral','Otoree purulentă cronică și masă albicioasă timpanică','Tinitus pulsatil cu masă eritematoasă în spatele unui timpan translucid','Fixarea piciorului scăriței, agravată în sarcină'],'A',560,'Neoplazii otologice — Schwanomul vestibular',
 'Diferențierea triadei SNHL plus discriminare slabă plus tinitus de glomus, colesteatom și otoscleroză, toate din același capitol.',
 ['Textul numește explicit această asociere semn patognomonic.','Hipoacuzia de transmisie cu Rinne negativ descrie otoscleroza sau patologia de ureche medie.','Otoreea și masa albicioasă descriu colesteatomul.','Tinitusul pulsatil și masa eritematoasă descriu glomus tympanicum.','Fixarea scăriței definește otoscleroza, nu schwanomul de VIII.']],
 8,'Așază patognomonicul schwanomului lângă trei entități otologice din aceeași pagină (glomus, otoscleroză, colesteatom) cu semne aproape superpozabile.',['Semnul patognomonic','discriminare vocală']),

q(23,['Drenajul sinusurilor paranazale se caracterizează prin:',
 ['Canalul nazo-lacrimal se deschide în meatul inferior','Sinusurile etmoidal anterior, maxilar și frontal se deschid în meatul mijlociu','Regiunea sinusului etmoid anterior plus meatul mijlociu alcătuiește complexul ostio-meatal','Celulele etmoidale posterioare și sinusul sfenoidal drenează în meatul superior','Sinusul sfenoidal și celulele etmoidale posterioare drenează în meatul inferior, alături de canalul nazo-lacrimal'],'ABCD',561,'Nasul și sinusurile — Anatomie',
 'Maparea celor trei meate: lacrimal inferior, ostio-meatal mijlociu, sfenoid-etmoid posterior superior.',
 ['Drenajul nazo-lacrimal în meatul inferior este explicit.','Cele trei sinusuri anterioare se deschid în meatul mijlociu.','Definiția complexului ostio-meatal este dată în text.','Drenajul posterior (etmoid posterior și sfenoid) în meatul superior este enunțat.','Meatul inferior primește canalul nazo-lacrimal, nu sfenoidul sau etmoidul posterior.']],
 8,'Permutează meatul superior cu cel inferior pentru sfenoid și etmoidul posterior, confuzie anatomică clasică.',['complex ostio-meatal','meatului mijlociu']),

q(24,['Sediul cel mai frecvent al epistaxisului anterior este:',
 ['Plexul Kiesselbach de pe septul nazal, cu ramuri din carotida internă și din cea externă','Artera sfenopalatină izolată, fără contribuție din carotida internă','Arterele etmoidale, ramuri desprinse din carotida externă, fără aport oftalmic','Plexul pterigoid, prin vene fără valve către sinusul cavernos','Ostiumul sinusului sfenoidal, în meatul superior'],'A',561,'Vascularizația nasului — Plexul Kiesselbach',
 'Identificarea plexului Kiesselbach ca zonă de confluență internă-externă, distinctă de sfenopalatină ca sursă principală posterioară.',
 ['Textul identifică plexul Kiesselbach ca sediul cel mai frecvent al sângerărilor nazale, cu dublă origine carotidă.','Artera sfenopalatină este principala sursă a cavităților nazale, dar sediul tipic al epistaxisului anterior este plexul septal.','Arterele etmoidale sunt ramuri oftalmice din carotida internă, nu din cea externă.','Plexul pterigoid explică diseminarea infecțioasă, nu originea epistaxisului anterior.','Ostiumul sfenoidal nu este sediul clasic al epistaxisului anterior.']],
 8,'Confruntă plexul Kiesselbach cu sfenopalatina (sursa principală posterioară) și cu originea etmoidalelor (carotidă internă, nu externă).',['Kiesselbach','sfenopalatină']),

q(25,['Indicați afirmațiile corecte privind managementul epistaxisului:',
 ['Cea mai frecventă cauză este traumatismul mucoasei nazale','Angiofibromul nazo-faringian juvenil trebuie suspicionat la adolescentul de sex masculin cu epistaxis unilateral recurent','Pacienții cu tamponament posterior se spitalizează, cu oxigen umidificat și antibioterapie profilactică','Ligatura arterelor etmoidale este procedurile de elecție pentru sângerarea posterioară','Tamponamentul anterior este suficient când sângele continuă să se exteriorizeze în faringe'],'ABC',563,'Epistaxisul — Cauze și tratament',
 'Ierarhia traumatism–cauterizare–tamponament și recunoașterea angiofibromului juvenil, cu distincția ligaturii etmoidale față de maxilara internă.',
 ['Traumatismul este numit cea mai frecventă cauză.','Profilul adolescent masculin cu sângerare unilaterală este clasic pentru angiofibrom.','Spitalizarea, oxigenul umidificat și antibioterapia profilactică sunt cerute după tamponament posterior.','Pentru sângerarea posterioară se leagă sau se embolizează artera maxilară internă; etmoidalele vizează epistaxisul antero-superior.','Continuarea sângerării faringiene după un tamponament anterior bine realizat impune tamponament posterior.']],
 8,'Inversează teritoriul ligaturii (etmoidale față de maxilară internă) și tratează eșecul tamponamentului anterior ca pe un succes.',['Kisselbach','tamponament nazal anterior']),

q(26,['Rinita alergică:',
 ['Afectează 20% din populație și este mediată de imunoglobulinele E','Un istoric familial pozitiv este întâlnit la 50% dintre pacienți','Imunoterapia alergen-specifică este eficientă și în rinitele non-IgE, după o singură injecție','Cromoglicatul de sodiu acționează prin vasoconstricție directă a cornetelor, similar decongestionantelor','Testele cutanate sunt caracteristic negative, diagnosticul bazându-se doar pe paloarea mucoasei'],'AB',564,'Rinita alergică',
 'Reținerea prevalenței de 20%, a agregării familiale de 50% și a mecanismului IgE, opus rinitei medicamentoase sau hormonale.',
 ['Prevalența de 20% și medierea IgE sunt explicite.','Procentul de 50% cu istoric familial este citat.','Imunoterapia este eficientă doar în boala mediată de IgE și necesită ani de întreținere.','Cromoglicatul previne degranularea mastocitelor, nu vasoconstricția.','Testele cutanate sunt adesea pozitive, iar aspectul rinoscopic nu este specific.']],
 8,'Extinde imunoterapia dincolo de IgE și confundă cromoglicatul cu un decongestionant vasoconstrictor.',['20% din populaţie','imunoglobulinele E']),

q(27,['Polipoza nazală:',
 ['Presupune mase bilaterale, multiple, translucide, care apar la complexul ostio-meatal','Polipii unilaterali, mai ales cu sângerare, cresc suspiciunea unei neoplazii','Sinuzita polipoasă este rară la copii și impune excluderea fibrozei chistice sau a imunodeficienței','Excizia chirurgicală este prima intenție, înaintea oricărei cure de steroizi','Polipii sunt aproape toți unilaterali la adultul tânăr, fără legătură cu astmul sau cu aspirina'],'ABC',564,'Polipoza nazală',
 'Recunoașterea bilateralității ca regulă și a polipului unilateral sângerând ca semnal oncologic, plus alerta de fibroză chistică la copil.',
 ['Morfologia bilaterală translucidă la complexul ostio-meatal este caracteristică.','Textul subliniază raritatea polipilor unilaterali și suspiciunea de neoplazie.','Alerta de fibroză chistică sau imunodeficiență la copil este explicită.','Gestionarea inițială include steroizi topici și o cură scurtă orală; chirurgia este rezervată eșecului sau contraindicației.','Polipoza se asociază cu astm, hipersensibilitate la aspirină și fibroză chistică; polipii sunt rar unilaterali.']],
 8,'Inversează regula bilateral/unilateral și pune chirurgia înaintea steroizilor, două erori de triage ale masei nazale.',['polipii unilaterali','fibroza chistică'],[565]),

q(28,['Un nou-născut cianozează și se sufoacă la hrănire, iar simptomele se ameliorează temporar la plâns. Atrezia coanală bilaterală este susținută de:',
 ['Imposibilitatea de a trece un cateter mic prin nas în nazofaringe','Faptul că atrezia bilaterală este o urgență medico-chirurgicală','Necesitatea stentării imediate cu o cale aeriană orală sau a intubației endotraheale','Faptul că atrezia unilaterală, nu cea bilaterală, constituie urgența neonatală','Reducerea închisă a dorsum nasi ca tratament definitiv, similar fracturii nazale'],'ABC',565,'Atrezia coanală',
 'Recunoașterea urgenței atreziei bilaterale, a ameliorării la plâns și a diagnosticului prin eșecul cateterului nazal.',
 ['Eșecul trecerii cateterului sugerează diagnosticul, conform textului.','Atrezia coanală bilaterală este numită urgență medico-chirurgicală.','Stentarea orală sau intubația sunt măsurile imediate.','Urgența este forma bilaterală, deoarece nou-născutul respiră nazal; unilaterala nu este prezentată ca urgență identică.','Reducerea închisă privește fracturile nazale fără deplasare septală, nu atrezia coanală.']],
 8,'Inversează care formă (uni- față de bilaterală) este urgența și confundă corecția coanală cu reducerea unei fracturi nazale.',['Atrezia coanală','intubare endotraheală']),

q(29,['Fractura oaselor nazale:',
 ['Oasele nazale sunt oasele cel mai des fracturate ale corpului','Hematomul septal impune drenaj prompt pentru a preveni abcesul și deformarea cu „nas în șa”','Hematomul septal se lasă să se resorbă spontan, pentru a nu leza pericondrul','Fracturile fără deplasare necesită reducere deschisă de principiu','Loviturile laterale aplatizează dorsum nasi, iar cele frontale deplasează un os lateral'],'AB',565,'Deformarea nazală și septală',
 'Recunoașterea oaselor nazale ca cel mai frecvent fracturate și a urgenței hematomului septal, opus fracturii nedeplasate.',
 ['Afirmația că oasele nazale sunt cel mai des fracturate este explicită.','Drenajul prompt previne abcesul, resorbția cartilajului și nasul în șa.','Netratarea hematomului duce la resorbție cartilaginoasă; drenajul este necesar, nu expectativă.','Fracturile fără deplasare nu necesită reducere; reducerea deschisă este pentru leziuni complexe cu deplasare septală.','Textul inversează: lovitura laterală înfundă un os și deplasează contralateralul; lovitura frontală aplatizează și lărgește dorsum nasi.']],
 8,'Inversează indicația de drenaj al hematomului septal și oglindește vectorul loviturii laterale față de cea frontală.',['nas în şa','Oasele nazale sunt cel mai des fracturate']),

q(30,['Sinuzita acută:',
 ['Apare adesea ca o complicație a unei infecții virale de tract respirator superior','Organismele des incriminate sunt S. pneumoniae, H. influenzae și M. catarrhalis','Tratamentul empiric include amoxicilină-acid clavulanic sau cefuroximă timp de 7–14 zile','Diagnosticul cere CT coronal înaintea oricărui tratament, chiar în formele necomplicate','Complexul ostio-meatal este sediul a doar 10% dintre bolile inflamatorii sinusale cronice'],'ABC',565,'Sinuzita acută',
 'Recunoașterea tridentului bacterian comun cu OMA și a ferestrei de 7–14 zile, fără a pretinde CT în forma necomplicată.',
 ['Legătura cu guturaiul comun este explicită.','Cei trei agenți sunt enumerați identic.','Durata de 7–14 zile și exemplele de antibiotice (inclusiv amoxicilină-clavulanat și cefuroximă) sunt citate.','În cazurile necomplicate tratamentul se inițiază empiric, pe criterii clinice.','În sinuzita cronică, complexul ostio-meatal este sediul a 90% dintre cazuri, nu 10%.']],
 8,'Permutează 90% cu 10% pentru complexul ostio-meatal și impune CT acolo unde textul acceptă tratamentul empiric.',['7-14 zile','complexului ostio-meatal']),

q(31,['Infecțiile rinosinusale micotice și papilomul invertit:',
 ['Organismele oportuniste implicate includ Phycomycetes (Mucor, Rhizopus) și Aspergillus','Diagnosticul infecției invazive depinde de identificarea histologică; exudatul nazal este insuficient','Papiloamele invertite sunt invazive local, iar 10–15% pot degenera în carcinoame scuamoase','Biopsia angiofibromului juvenil este procedura de elecție, hemoragia fiind neglijabilă','Osteomul simptomatic al sinusurilor se doar monitorizează, fără excizie chiar la creștere progresivă'],'ABC',566,'Infecțiile rinosinusale micotice — Neoplazii benigne',
 'Separarea urgenței histologice a mucormicozei de riscul de 10–15% al papilomului invertit și de interdicția biopsiei angiofibromului.',
 ['Cele două grupuri fungice sunt enumerate.','Textul precizează că exudatul nazal este insuficient și că diagnosticul este histologic.','Procentul 10–15% de degenerare și indicația de excizie largă sunt explicite.','Diagnosticul angiofibromului este clinic și radiologic, deoarece biopsia poate produce hemoragie riscantă.','Osteoamele asimptomatice se monitorizează; cele cu creștere progresivă se îndepărtează chirurgical.']],
 8,'Transformă biopsia angiofibromului (riscantă) în gest de elecție și inversează indicația osteomului în creștere.',['I 0-15 %','Aspergillus']),

q(32,['Abcesul periamigdalian și indicațiile infecțioase ale tonsilectomiei:',
 ['Abcesul periamigdalian asociază asimetria amigdalelor, tumefacția palatului moale, deviația uvulei și voce stinsă','Printre indicațiile infecțioase figurează 6 episoade de amigdalită acută într-un an','Faringita streptococică se caracterizează, printre altele, prin absența notabilă a tusei (criterii Centor)','Prezența tusei este criteriul Centor care confirmă faringita streptococică','Abcesele peritonsilare se rezolvă doar cu antibiotice orale, fără aspirație sau drenaj'],'ABC',568,'Faringitele — Abcesul periamigdalian și Tabelul 27-9',
 'Recunoașterea tetradei abcesului periamigdalian, a pragului de 6 episoade/an și a absenței tusei ca semn Centor.',
 ['Cele patru elemente clinice ale abcesului sunt enumerate.','Tabelul 27-9 listează 6 episoade într-un an ca indicație.','Absența tusei este subliniată ca element al criteriilor Centor.','Textul vorbește despre absența, nu prezența, tusei.','Abcesele peritonsilare necesită de obicei aspirație sau drenaj chirurgical.']],
 8,'Inversează semnul tusei din criteriile Centor și minimizează drenajul abcesului la antibiotice orale.',['criterii Centor','6 episoade într-un an']),

q(33,['Un sugar cu hipoplazie mandibulară, glosoptoză și palatoschizis. Sunt adevărate următoarele:',
 ['Asocierea descrie sindromul Pierre Robin, cu risc de obstrucție prin deplasarea posterioară a limbii','Corecția palatoschizisului se realizează înainte de vârsta de 2 ani, pentru dezvoltarea limbajului','Apneea se definește prin scăderea cu cel puțin 90% a semnalului termic oro-nazal, timp de cel puțin 10 secunde','La copiii cu apnee obstructivă, indicele de masă corporală este de obicei normal, cu hipertrofie adeno-amigdaliană','Regula lui 10 pentru cheiloschizis cere greutate sub 2 kg și hemoglobină sub 8 g/dL'],'ABCD',569,'Anomalii congenitale — Pierre Robin, palatoschizis, apneea obstructivă',
 'Recunoașterea triadei Pierre Robin, a vârstei de 2 ani pentru palat și a definiției apneei ≥90%/10 s, opus regulii lui 10 a buzei.',
 ['Triada hipoplazie mandibulară–glosoptoză–palatoschizis este explicită.','Vârsta de 2 ani pentru corecția palatului este citată.','Definiția polisomnografică (90% și 10 secunde) este dată.','La copii, IMC este de obicei normal, cu hipertrofie adenoidiană și amigdaliană.','Regula lui 10 cere copil >10 săptămâni, >4,53 kg și Hb >10, nu valorile inversate.']],
 8,'Inversează pragurile regulii lui 10 și atribuie copiilor cu OSA obezitatea adultului, două capcane de prag și de fenotip.',['Pierre Robin','90% din valoarea']),

q(34,['Inervația laringelui:',
 ['Nervul laringeu superior asigură funcția senzitivă și inervează mușchiul crico-tiroidian','Nervul laringeu recurent inervează ceilalți mușchi intrinseci','Nervul laringeu recurent stâng are traiect toracic mai lung și este mai susceptibil leziunilor','Mușchiul crico-aritenoidian posterior produce adducția corzilor vocale pentru fonație','Drenajul limfatic supraglotic este sărac și doar ipsilateral, spre deosebire de glotă'],'ABC',570,'Laringele — Inervație și limfatice',
 'Separarea laringelui superior (senzitiv plus crico-tiroidian) de recurent (restul mușchilor), cu vulnerabilitatea recurentului stâng.',
 ['Teritoriul nervului laringeu superior este enunțat astfel.','Recurentul deservește funcțiile motorii ale celorlalți mușchi intrinseci.','Lungimea și vulnerabilitatea recurentului stâng sunt explicite.','Crico-aritenoidianul posterior produce abducția (deschiderea) corzilor, nu adducția.','Supraglota are drenaj limfatic bine reprezentat, bilateral, către ganglionii jugulari profunzi; glota și subglota au limfatice rare.']],
 8,'Inversează abducția crico-aritenoidianului posterior cu adducția și oglindește densitatea limfatică supraglotică față de glotică.',['laringeu recurent','crico-tiroidian']),

q(35,['Tipul de stridor orientează localizarea stenozei astfel:',
 ['Îngustarea deasupra corzilor vocale produce stridor inspirator','Stenoza la nivelul corzilor sau al traheei extratoracice produce stridor bifazic','Obstrucția parțială a traheei intratoracice produce stridor expirator','Stridorul expirator este patognomonic pentru laringomalacie și exclude astmul','Îngustarea deasupra corzilor produce stridor expirator, iar cea intratoracică produce stridor inspirator'],'ABC',572,'Stridorul — Corelația cu nivelul obstrucției',
 'Aplicarea regulii inspirator-supraglotic, bifazic-glottic/extratoracic, expirator-intratoracic.',
 ['Regula inspiratorului pentru stenoza de deasupra corzilor este explicită.','Bifazicul este atribuit corzilor sau traheei extratoracice.','Expiratorul este atribuit traheei intratoracice.','Stridorul expirator este des interpretat eronat drept astm; laringomalacia produce stridor inspirator.','Opțiunea inversează complet mapa nivel-fază din text.']],
 8,'Oglindește cele trei etaje ale hărții stridorului și confundă expiratorul cu laringomalacia (inspiratorie).',['stridorul inspirator','Stridorul expirator'],[573]),

q(36,['Cea mai frecventă cauză de stridor la copii, însumând 60% dintre cazuri, este:',
 ['Laringomalacia','Epiglotita','Crupul (laringo-traheo-bronșita)','Stenoza subglotică postintubație','Hemangiomul subglotic'],'A',573,'Patologie pediatrică structurală — Laringomalacia',
 'Identificarea laringomalaciei ca primă cauză (60%) de stridor pediatric, distinctă de crup, epiglotită și stenoza subglotică.',
 ['Textul atribuie laringomalaciei 60% dintre cauzele de stridor la copii.','Epiglotita este o cauză de stridor inspirator, dar nu cea mai frecventă.','Crupul produce stridor bifazic, fără a deține ponderea de 60%.','Stenoza subglotică este frecvent post-traumatică/postintubație, nu prima cauză.','Hemangiomul subglotic figurează printre cauzele bifazice, nu ca entitate dominantă.']],
 8,'Celelalte cauze pediatrice din Tabelul 27-10 sunt aproape-egale ca notorietate, dar textul rezervă 60% laringomalaciei.',['60% dintre cauzuri','Laringomalacia']),

q(37,['Care dintre următoarele afirmații diferențiază corect epiglotita de crup?',
 ['Epiglotita este provocată de obicei de H. influenzae și afectează cu precădere copiii între 3 și 6 ani','În epiglotită se evită apăsătorul de limbă, din riscul de laringospasm reflex','Crupul afectează de regulă copiii ≤2 ani, are etiologie virală și tuse lătrătoare, cu semnul „turlei gotice”','Edemul din crup se remite mai greu, deseori în 5–7 zile, față de detubarea din epiglotită în primele 72 de ore','Crupul este o infecție bacteriană cu H. influenzae, iar epiglotita este virală subglotică'],'ABCD',574,'Epiglotita și crupul',
 'Contrastarea vârstei, a agentului, a manevrei interzise (apăsătorul) și a ferestrelor 72 de ore față de 5–7 zile.',
 ['Agentul și intervalul 3–6 ani sunt explicitate pentru epiglotită.','Interdicția apăsătorului de limbă este subliniată.','Vârsta ≤2 ani, etiologia virală, tusea lătrătoare și semnul turlei gotice definesc crupul.','Comparația 5–7 zile față de 72 de ore este enunțată.','Opțiunea inversează complet etiologia și etajul anatomic al celor două boli.']],
 8,'Permutează H. influenzae între epiglotită și crup și oglindește etajul (supraglotic față de subglotic) împreună cu ferestrele de remisie.',['turlei gotice','primele 72 ore']),

q(38,['Paralizia de coardă vocală:',
 ['Forma unilaterală produce de obicei voce de intensitate redusă, „șoptită”, și tuse la deglutiția lichidelor','Forma bilaterală lasă vocea aproape normală, dar asociază stridor bifazic marcat','Dacă după 6–12 luni mobilitatea nu revine și paralizia este necompensată, coarda poate fi tracționată medial','Traheotomia este prima intenție în papilomatoza laringiană a copilului, pentru a preveni însămânțarea','Nodulii de coardă vocală sunt asimetrici, situați la comisura posterioară, lângă procesul vocal'],'ABC',575,'Paralizia corzilor vocale — Noduli și papiloame',
 'Contrastarea vocii șoptite unilaterale cu vocea aproape normală plus stridor bifazic din paralizia bilaterală.',
 ['Tabloul unilateral (voce șoptită, tuse la lichide) este explicit.','Tabloul bilateral (voce aproape normală, stridor bifazic) este explicit.','Fereastra 6–12 luni și medializarea sunt descrise.','Traheostomia trebuie evitată în papilomatoză, fiind rezervată cazurilor avansate, din riscul de însămânțare.','Nodulii sunt albi, simetrici, la unirea treimii anterioare cu cele două treimi posterioare, nu la procesul vocal (sediul granuloamelor).']],
 8,'Inversează tabloul vocal al formei uni- față de bilaterale și mută nodulii pe locul granuloamelor de proces vocal.',['şoptită','6-12 luni']),

q(39,['Carcinomul scuamos laringian:',
 ['Reprezintă cea mai frecventă leziune malignă a laringelui; celelalte tipuri însumează sub 5%','Tumorile supraglotice au rată ridicată de metastazare limfatică, astfel încât chiar leziunile mici, fără adenopatii palpabile, necesită tratamentul regiunilor limfatice cervicale','După laringectomie totală, pacientul nu va mai putea fi intubat oral','Adenopatia cervicală concomitentă crește rata de supraviețuire la 5 ani cu până la 70%','Radioterapia tumorilor glotice mici impune un volum cervical similar celui din cancerele supraglotice'],'ABC',576,'Tumori maligne ale laringelui',
 'Recunoașterea densității limfatice supraglotice, a interdicției intubației orale post-laringectomie și a impactului negativ al adenopatiei.',
 ['Dominanța carcinomului scuamos și pragul sub 5% pentru celelalte tipuri sunt explicite.','Necesitatea tratării limfaticelor cervicale chiar fără adenopatii palpabile este enunțată pentru supraglotă.','Textul subliniază că laringectomizatul nu va mai putea fi intubat oral.','Adenopatia este factor de prognostic negativ, reducând (nu crescând) supraviețuirea la 5 ani cu până la 70%.','Iradierea supraglotică include o proporție semnificativ mai mare a gâtului decât iradierea glotică, cu morbiditate mai mare.']],
 8,'Inversează direcția impactului adenopatiei asupra supraviețuirii (scade, nu crește, cu 70%) și egalizează greșit volumele de iradiere glotă-supraglotă.',['Laringectomia totală','intubat oral']),

q(40,['Cricotirotomia și traheotomia:',
 ['Cricotirotomia este cea mai rapidă și sigură intervenție când intubația orotraheală eșuează în obstrucția acută','La copiii mici cricotirotomia nu este posibilă, calea aeriană fiind asigurată prin traheotomie imediat subcricoidiană','Din riscul de stenoză subglotică, cricotirotomia se convertește prudent la traheostomie dacă intubația va fi necesară mai multe zile','Traheotomia este preferată cricotirotomiei ca prim gest în obstrucția acută, deoarece nu există risc de stenoză','Dependența ventilatorie prelungită anticipată, de obicei peste 2 săptămâni, nu figurează printre indicațiile traheotomiei'],'ABC',583,'Calea aeriană asigurată chirurgical — Tabelul 27-12',
 'Ierarhia cricotirotomie de urgență față de traheotomie planificată și conversia precoce din cauza stenozei subglotice, cu excepția copilului mic.',
 ['Textul numește cricotirotomia cea mai rapidă și sigură soluție după eșecul intubației.','Excepția copilului mic, cu traheotomie între cricoid și primul inel, este explicită.','Conversia la traheostomie din riscul de stenoză este recomandată dacă intubația depășește câteva zile.','În obstrucția acută cu eșec al intubației, cricotirotomia precede traheotomia.','Tabelul 27-12 include dependența ventilatorie prelungită anticipată, de obicei peste 2 săptămâni.']],
 8,'Inversează ordinea de urgență cricotiroidotomie-traheotomie și neagă indicația de >2 săptămâni din tabelul de traheotomie.',['cricotirotomie','Tabelul 27-12']),
];
