import {advancedQuestion} from './advanced-author';
import type {SourceRow} from './source-author';

const EDITION='Chirurgie generală și specialități chirurgicale, ediția pentru rezidențiat MG 2025';
const pdfOffset=(p:number)=>p-327;
const q=(n:number,row:SourceRow,score:number,reason:string,expressions:string[],related:number[]=[])=>
 advancedQuestion('orl',27,pdfOffset,`orl-adv-${String(n).padStart(3,'0')}`,row,[score,reason],expressions,undefined,related,'Lawrence',EDITION);

export const ORL_D=[
q(101,['Pragul de inteligibilitate a vorbirii (PIV) reprezintă cea mai mică intensitate la care pacientul repetă cu succes cuvinte bisilabice în:',
 ['50% din timp','10% din timp, analog persistenței lichidului după OMA','90% din timp, analog supraviețuirii la 3 ani a tumorilor glotice mici','75% din timp, analog presbiacuziei până la 80 de ani','100% din timp, discriminarea monosilabică fiind superfluă'],'A',553,'Audiometrie vocală — Pragul de inteligibilitate a vorbirii',
 'Memorarea definiției PIV ca 50% succes la cuvinte din două silabe, distinctă de scorul de recunoaștere a monosilabelor.',
 ['Textul definește pragul vocii conversaționale ca cea mai mică intensitate cu repetare reușită în 50% din timp.','10% este ponderea copiilor cu lichid persistând 10–12 săptămâni după OMA, nu PIV.','90% este supraviețuirea la 3 ani a tumorilor glotice mici.','75% este ponderea presbiacuziei până la 80 de ani.','Discriminarea se măsoară separat, pe monosilabe echilibrate fonetic.']],
 8,'Permutează 50% al PIV cu alte procente din capitol (10%, 75%, 90%).',['două silabe','50% din timp']),

q(102,['Audiometria tonală se efectuează pe cel puțin șase frecvențe. Sunt adevărate:',
 ['Frecvențele testate sunt 250, 500, 1.000, 2.000, 4.000 și 8.000 Hz','Discriminarea vorbirii este procentul de cuvinte monosilabice, echilibrate fonetic, repetate cu succes','Audiometria tonală evaluează recunoașterea vorbirii, făcând inutil PIV-ul','Cele șase frecvențe încep de la 125 Hz și se opresc la 4.000 Hz, analog vocii conversaționale','Discriminarea se testează cu cuvinte bisilabice, identic PIV-ului'],'AB',553,'Audiometria tonală — Șase frecvențe și discriminarea monosilabică',
 'Separarea listei de frecvențe (250–8.000 Hz) de scorul de recunoaștere pe monosilabe, față de PIV-ul bisilabic.',
 ['Cele șase frecvențe sunt enumerate explicit.','Discriminarea ca procent de monosilabe echilibrate fonetic este enunțată.','Audiometria tonală nu evaluează recunoașterea vorbirii; aceasta este rolul PIV și al discriminării.','Lista începe la 250 Hz și include 8.000 Hz.','Cuvintele bisilabice definesc PIV-ul, nu discriminarea.']],
 8,'Atribuie audiometriei tonale funcția vocală și schimbă monosilabele discriminării cu bisilabele PIV.',['8.000 Hz','cuvinte monosilabice']),

q(103,['Conform tabelului 27-5, fractura transversală (orizontală) de os temporal se deosebește de cea longitudinală prin:',
 ['Mecanism: lovitură frontală sau occipitală, care intersectează axul lung al osului pietros','Vertij frecvent, membrană timpanică în general intactă și hemotimpan','Paralizie de nerv facial frecventă (circa 50%) și hipoacuzie în general neurosenzorială','Mecanism: lovitură laterală, paralelă cu axul pietros, cu otoree hemoragică și semn Battle','Hipoacuzie de transmisie și paralizie facială rară, analog longitudinalei'],'ABC',557,'Fracturile de os temporal — Tabelul 27-5, forma transversală',
 'Contrastarea loviturii fronto-occipitale, a timpanului intact cu hemotimpan, a vertijului și a facialului ~50% cu tabloul longitudinalei (lateral, Battle, transmisie).',
 ['Lovitura frontală/occipitală care intersectează axul pietros este explicită.','Vertijul, timpanul intact și hemotimpanul figurează în tabel.','Facialul frecvent (~50%) și hipoacuzia neurosenzorială sunt citate.','Lovitura laterală, otoreea hemoragică și semnul Battle definesc longitudinalea.','Transmisia și facialul rar (~15%) sunt ale longitudinalei, nu ale transversalei.']],
 8,'Atribuie transversalei semnul Battle și hipoacuzia de transmisie, discriminatorii clasice ale longitudinalei.',['Intersectează axul','~50%']),

q(104,['Otita externă localizată (foliculita conductului auditiv extern) este cauzată cel mai frecvent de traumă cu:',
 ['Unghia sau agrafe de păr, cu durere intensă la mobilizarea pavilionului; tratamentul implică antibiotice antistafilococice, drenaj sau ambele','Pseudomonas din apa de înot, analog urechii înotătorului difuze','Aspergillus pe epiteliul descuamat, ca infecție secundară fungică','Proteus la diabeticul cu osteomielită de bază de craniu','Un corp străin caustic, care impune anestezie generală de la prima tentativă'],'A',557,'Otita externă localizată — Foliculita de conduct',
 'Recunoașterea traumei cu unghia/agrafă, a durerii la mobilizarea pavilionului și a antibioticului antistafilococic, distincte de Pseudomonas-ul otitei difuze.',
 ['Trauma cu unghia sau agrafele, durerea la mobilizarea pavilionului și antistafilococicele/drenajul sunt explicite.','Pseudomonas este agentul otitei externe difuze (urechea înotătorului).','Fungii sunt incriminați de obicei în infecții secundare ale formei difuze.','Proteus/Klebsiella figurează la otita externă necrotizantă.','Corpul străin caustic este o urgență de extracție, nu foliculita.']],
 8,'Confundă foliculita antistafilococică cu Pseudomonas-ul înotătorului sau cu otita necrotizantă a diabeticului.',['Unghia','antistafilococice']),

q(105,['Corpii străini auriculari la preșcolar:',
 ['Reprezintă o urgență doar dacă obiectul este caustic','Copiii permit, de obicei, o singură încercare; dacă eșuează, este necesară anestezia generală','Toți corpii străini, inclusiv un bob de mazăre, impun extracție imediată sub anestezie generală, fără tentativă trează','Corticoterapia locală este contraindicată între tentative','Un bob de popcorn se extrage prin irigare forțată, analog dopului de ceară'],'AB',558,'Corpii străini de conduct auditiv — Urgența caustică și o tentativă',
 'Recunoașterea urgenței doar pentru obiectul caustic și a regulii unei singure tentative treze, urmată de anestezie generală.',
 ['Doar obiectul caustic face din corpul străin o urgență.','O singură încercare, apoi anestezie generală, este explicită.','Nu toți corpii impun AG de la prima tentativă.','Între timp, corticoterapia locală este utilă.','Textul nu recomandă irigarea forțată a boabelor.']],
 8,'Transformă orice corp străin (mazăre, popcorn) în urgență de AG, ignorând regula obiectului caustic și a unei tentative.',['obiectul este caustic','anestezia generală']),

q(106,['Când trompa lui Eustachio nu se deschide suficient, mecanismul otitei medii include:',
 ['Crearea unui vacuum, cu absorbția oxigenului și a azotului în mucoasa urechii medii și în celulele mastoidiene','Creșterea permeabilității capilare și stimularea activității glandulare, cu lichid sau pungi de retracție','Dacă sunt prezenți agenți infecțioși, transudatul este un excelent mediu de cultură','Presiune pozitivă continuă, analog colesteatomului prin hiperpresiune','Deschiderea permanentă a trompei, cu reflux nazofaringian steril, fără vacuum'],'ABC',558,'Otita medie — Vacuum tubar și transudat',
 'Reconstituirea lanțului vacuum → absorbție O2/N2 → permeabilitate capilară și lichid, ca premisă a otitei când intervin germenii.',
 ['Vacuumul și absorbția oxigenului și azotului sunt explicite.','Permeabilitatea capilară, activitatea glandulară, lichidul și pungile de retracție sunt descrise.','Transudatul ca mediu de cultură este enunțat.','Colesteatomul se dezvoltă pe presiune negativă, nu pozitivă.','Trompa este în mod normal închisă și se deschide intermitent; nu rămâne permanent deschisă.']],
 8,'Inversează vacuumul (presiune negativă) în hiperpresiune și trompa permanent deschisă.',['oxigenul şi azotul','pungi de retracţie']),

q(107,['Ghidul AAP 2004 pentru otita medie acută prevede:',
 ['Dacă simptomele nu sunt grave sau diagnosticul este neclar, se recomandă inițial doar monitorizarea, cu reevaluare în 48–72 de ore','Azitromicina, claritromicina sau eritromicina pot fi folosite la alergicii la peniciline','După inițierea antibioticului, durerea cedează în 3 zile, iar funcția trompei revine în 2 săptămâni','Dacă infecția persistă după 3 zile, se trece la doză mare de amoxicilină-clavulanat; apoi, dacă eșuează, o cură de 3 zile de ceftriaxonă parenteral','Antibioticele, antihistaminicele și steroizii sunt inutile în OMA, analog otitei seroase'],'ABCD',558,'Otita medie acută — Observație 48–72 de ore și eskalare antibiotică',
 'Aplicarea observației 48–72 de ore, a macrolidului la alergici, a ferestrelor 3 zile/2 săptămâni și a treptei amox-clav apoi ceftriaxonă.',
 ['Monitorizarea inițială și reevaluarea în 48–72 de ore sunt explicite.','Cele trei macrolide la alergicii la penicilină sunt enumerate.','Cedarea durerii în 3 zile și a funcției tubare în 2 săptămâni sunt citate.','Amox-clavulatul la eșecul de 3 zile și ceftriaxona 3 zile sunt enunțate.','Ineficiența antibioticelor/antihistaminicelor/steroizilor este afirmată pentru OMS, nu pentru OMA tratată.']],
 8,'Mută ineficiența medicației din OMS (3 luni de observație) peste OMA, unde ghidul detaliază trepte antibiotice.',['48-72 de ore','ceftriaxonă']),

q(108,['După un episod de otită medie acută, lichidul din urechea medie persistă peste 10–12 săptămâni la circa:',
 ['10% dintre copii','75% dintre copii, analog celor cu cel puțin trei OMA până la 2 ani','50% dintre copii, analog PIV-ului vocal','90% dintre copii, analog vindecării perforațiilor timpanice posttraumatice','2,2 milioane de cazuri pe an, cifra anuală a OMS în SUA, nu un procent'],'A',558,'Otita medie acută — Persistența lichidului 10–12 săptămâni',
 'Memorarea celor 10% de copii cu lichid persistând peste 10–12 săptămâni, ca justificare a urmăririi până la ureche medie liberă.',
 ['Procentul de circa 10% cu lichid peste 10–12 săptămâni este explicit.','75% este ponderea copiilor cu ≥3 OMA până la 2 ani.','50% este pragul PIV.','90% este rata de vindecare a perforațiilor posttraumatice.','2,2 milioane este estimarea anuală a OMS, nu procentul de persistență după OMA.']],
 8,'Permutează 10% cu 75% (epidemiologia OMA) și cu 90% (perforațiile), două cifre din același capitol otologic.',['I 0%','I 0-12 săptămâni']),

q(109,['Boala Meniere (hidropsul endolimfatic) se asociază cu:',
 ['Bombarea sau ruperea membranei Reissner și amestecarea endolimfei cu perilimfa, toxică pentru celulele păroase','Tratament medical prin regim hiposodat și diuretice','Decompresia sacului endolimfatic sau distrucția nervului vestibular, rezervate vertijului debilitant neresponsiv','Manevra Epley ca primă intenție, analog BPPV prin canalolitiază','Fixarea piciorului scăriței, analog otosclerozei adultului tânăr'],'ABC',560,'Boala Meniere — Membrana Reissner și tratamentul','Recunoașterea amestecului toxic endolimfă–perilimfă, a diureticelor hiposodate și a chirurgiei rezervate cazurilor refractare.',
 ['Ruptura membranei Reissner și toxicitatea amestecului pentru celulele păroase sunt explicite.','Regimul hiposodat și diureticele sunt tratamentul medical.','Decompresia sacului sau distrucția vestibulară sunt rezervate vertijului neresponsiv.','Epley este manevra BPPV, nu a hidropsului.','Fixarea scăriței definește otoscleroza, nu Meniere.']],
 8,'Înlocuiește diureticele și decompresia sacului cu Epley sau stapedectomie, două gesturi din patologii vestibulo-otice învecinate.',['membranei Reissner','regim hiposodat']),

q(110,['Paralizia Bell se caracterizează prin:',
 ['Infecție virală nervoasă cu herpes simplex, confirmată prin PCR','Instalare în câteva ore, cu posibilă progresie către paralizie completă','Durere mastoidiană asociată, cu durată sub 72 de ore','Vindecare spontană în majoritatea cazurilor; forma persistentă sau recurentă impune imagistică pentru a exclude o tumoră','Prognostic rezervat de rutină, analog leziunii complete prin tumoră malignă sau fractură de os temporal'],'ABCD',560,'Paralizia Bell — HSV, fereastra de 72 de ore și imagistica recurenței',
 'Integrarea confirmării PCR pentru HSV, a instalării în ore, a durerii mastoidiene <72 de ore și a imagisticii la persistență/recidivă.',
 ['HSV confirmat prin PCR este explicit.','Instalarea în câteva ore cu progresie posibilă către completă este descrisă.','Durerea mastoidiană sub 72 de ore este citată.','Vindecarea spontană majoritară și imagistica la persistență/recidivă sunt enunțate.','Prognosticul bun al leziunii incomplete/inflamatorii este opus celui rezervat al tumorii maligne sau al traumei temporale.']],
 8,'Atribuie Bell-ului prognosticul rezervat al tumorii maligne/fracturii temporale, ignorând vindecarea spontană și PCR-ul HSV.',['herpes simplex','<72 de ore']),

q(111,['Paralizia facială în context de otită medie acută, respectiv leziunea supranucleară, se deosebesc astfel:',
 ['În OMA, tratamentul este miringotomie largă plus antibioterapie topică și sistemică','Leziunile supranucleare (ischemie cerebrovasculară) nu afectează frecvent fruntea, ramurile fiind conectate cu fibre corticobulbare directe și încrucișate','Miringotomia este contraindicată în OMA cu pareză, analog aspirației prin celulită a artritei septice','Leziunea supranucleară șterge fruntea bilateral, analog leziunii de trunchi distal de ganglionul geniculat','Blefarorafia este primul gest în OMA, înaintea oricărei miringotomii'],'AB',560,'Paralizia facială — OMA (miringotomie) versus supranuclear (fruntea păstrată)',
 'Contrastarea miringotomiei largi din OMA cu păstrarea frunții în leziunea supranucleară prin inervație corticobulbară bilaterală.',
 ['Miringotomia largă plus antibiotic topic și sistemic sunt cerute în OMA cu paralizie facială.','Păstrarea frunții prin fibre directe și încrucișate este explicită.','Tabelul 27-6 include pareza facială ca indicație de miringotomie de urgență.','Fruntea este frecvent păstrată, nu ștearsă, în leziunea supranucleară.','Protecția oculară (lacrimi, benzi, greutăți de aur) este a lagoftalmiei, nu înlocuiește miringotomia din OMA.']],
 8,'Interzice miringotomia tocmai când tabelul o cere și șterge fruntea pe care inervația bilaterală o păstrează.',['miringotomie largă','fruntea']),

q(112,['Exostozele conductului auditiv extern se deosebesc de osteoame prin faptul că:',
 ['Sunt noduli multipli, indurați, netezi, de obicei bilaterali, pe când osteoamele sunt unice și unilaterale','Sunt unice și unilaterale, analog osteoamelor de sinus fronto-etmoidal','Se asociază cu tinitus pulsatil și masă eritematoasă în spatele timpanului, analog glomusului','Degeneră în 10–15% în carcinom scuamos, analog papilomului invertit','Răspund la picături antipseudomonas, analog urechii înotătorului'],'A',560,'Neoplazii otologice — Exostoză versus osteom',
 'Diferențierea exostozelor multiple bilaterale de osteomul unic unilateral al conductului.',
 ['Multiplicitatea, caracterul indurat neted și bilateralitatea exostozelor, versus osteomul unic unilateral, sunt explicite.','Unicitatea și unilateralitatea definesc osteomul, nu exostoza.','Masa pulsatilă eritematoasă este glomus tympanicum.','Degenerarea 10–15% este a papilomului invertit rinosinusal.','Picăturile antipseudomonas tratează otita externă difuză, nu exostozele.']],
 8,'Oglindește multiplicitatea exostozelor cu unicitatea osteomului și le confundă cu glomusul sau papilomul invertit.',['Exostozele','Osteoamele']),

q(113,['Glomus tympanicum, paragangliom vascular al urechii medii:',
 ['Este histologic similar tumorilor glomice ale corpului carotidian, ale nervului vag și ale bulbului jugular','Pacienții acuză de obicei tinitus pulsatil unilateral și hipoacuzie','O masă eritematoasă poate fi văzută otoscopic în spatele unei membrane timpanice translucide, altfel normale','Excizia chirurgicală este tratamentul de elecție','Masa albicioasă cu granulație și osteonecroză enzimatică definește glomusul, nu colesteatomul'],'ABCD',560,'Glomus tympanicum — Tinitus pulsatil și masă eritematoasă',
 'Recunoașterea identității histologice cu celelalte paraganglioame, a tinitusului pulsatil și a masei roșii în spatele timpanului translucid.',
 ['Similitudinea cu glomusul carotidian, vagal și jugular este explicită.','Tinitusul pulsatil unilateral și hipoacuzia sunt simptomele uzuale.','Masa eritematoasă în spatele timpanului translucid este descrisă.','Excizia chirurgicală este tratamentul de elecție.','Masa albicioasă cu osteonecroză enzimatică este colesteatomul, nu glomusul.']],
 8,'Schimbă masa roșie pulsatilă a glomusului cu masa albicioasă keratinizantă a colesteatomului.',['Glomus tympanicum','tinitus pulsatil']),

q(114,['Valva nazală, localizată în porțiunea anterioară a cavității nazale:',
 ['Este alcătuită din țesutul erectil al cornetului inferior, septul nazal și cartilajele nazale superioare laterale','La adult este frecvent zona cea mai îngustă a tractului respirator, sediu al obstrucției prin deviație de sept sau hipertrofie de cornet inferior','Este zona cea mai largă a căii aeriene, analog glotei adultului care tolerează edemul','Drenajul lacrimal se face aici, prin meatul mijlociu, analog complexului ostio-meatal','Plexul Kiesselbach se află pe cornetul inferior, nu pe sept'],'AB',561,'Nasul — Valva nazală ca zonă cea mai îngustă',
 'Identificarea valvei (cornet inferior erectil, sept, cartilaje superioare laterale) ca cel mai îngust segment respirator al adultului.',
 ['Cele trei componente ale valvei sunt enumerate.','Caracterul de zonă cea mai îngustă și cauzele de obstrucție (sept, cornet) sunt explicite.','Glota adultului este mai mare și tolerează edemul; valva este îngustă.','Canalul nazo-lacrimal se deschide în meatul inferior, nu la valvă prin meatul mijlociu.','Plexul Kiesselbach este pe septul nazal.']],
 8,'Transformă valva (cel mai îngust segment) în cel mai larg și mută drenajul lacrimal pe meatul mijlociu.',['Valva nazală','cea mai îngustă']),

q(115,['Aerul inspirat, la ieșirea din nas, are ca ținte optime:',
 ['Temperatura de 34°C, umiditate 80% și puține particule atmosferice','Vene fără valve către orbită și sinusul cavernos, ceea ce permite diseminarea infecțiilor feței și sinusurilor către orbită și SNC','Temperatura de 37°C și umiditate 100%, analog aerului alveolar','Vene cu valve competente care blochează orice propagare către sinusul cavernos','Inervație doar de la nervul II, fără fibre V, VII, simpatice sau parasimpatice'],'AB',561,'Fiziologia nazală — 34°C, 80% umiditate și vene fără valve',
 'Cuplarea țintelor de condiționare a aerului (34°C, 80%) cu absența valvelor venoase către orbită și sinusul cavernos.',
 ['Cele trei ținte (34°, 80%, puține particule) sunt explicite.','Comunicarea prin vene emisare fără valve cu orbita și sinusul cavernos este enunțată.','34°C și 80% nu sunt 37°C/100%.','Absența valvelor, nu prezența lor, explică diseminarea.','Nasul este inervat de I, V și VII plus simpatice și parasimpatice.']],
 8,'Înlocuiește 34°C/80% cu 37°C alveolar și inventează valve venoase care ar bloca propagarea către cavernos.',['34°','80%']),

q(116,['Polipii nazali unilaterali, rinita virală și rinita hormonală:',
 ['Polipii sunt rar unilaterali; un polip unilateral, mai ales cu sângerare, crește suspiciunea de neoplazie','Sinuzita polipoasă este rară la copii și cere evaluare promptă pentru fibroză chistică sau imunodeficiență','În guturai, regenerarea epiteliului are loc până în aproximativ ziua a 14-a, dar funcția ciliară poate întârzia săptămâni','Estrogenii (sarcină, perioada premenstruală, contraceptive orale) produc congestie vasculară nazală','Polipii unilaterali sunt varianta tipică a copilului, fără a necesita excluderea fibrozei chistice'],'ABCD',564,'Polipi unilaterali, ziua 14 a guturaiului și rinita de estrogen',
 'Alertarea pe polipul unilateral (neoplazie, FC la copil), pe regenerarea epitelială la 14 zile și pe congestia estrogenică.',
 ['Raritatea formei unilaterale și alerta de neoplazie sunt explicite.','Evaluarea pentru FC sau imunodeficiență la copilul cu sinuzită polipoasă este cerută.','Ziua 14 a regenerării epiteliale, cu întârzierea cililor, este citată.','Estrogenii ca cauză de congestie (sarcină, premenstruu, COC) sunt enunțați.','Forma unilaterală nu este tipică; la copil impune excluderea FC.']],
 8,'Tratează polipul unilateral ca variantă pediatrică banală, anulând alerta de neoplazie și de fibroză chistică.',['Polipii sunt rar unilaterali','ziua a 14-a']),

q(117,['Rinita alergică neresponsivă la evitare și farmacoterapie, respectiv inflamația cronică nazală, se caracterizează prin:',
 ['Cromoglicatul de sodiu topic previne degranularea mastocitelor','Imunoterapia alergen-specifică stimulează reglarea sintezei IgE de către limfocitele T supresoare și cere ani de întreținere','Dacă simptomele cronice persistă sub tratament, culturile și biopsia exclud TBC, sifilis, rinosclerom (Klebsiella rhinoscleromatis) și lepră','Imunoterapia este eficientă și în rinitele non-IgE, după o singură injecție','Rinoscleromul este o infecție virală autolimitată, analog guturaiului de 14 zile'],'ABC',564,'Rinita alergică — Cromoglicat, limfocite T și rinosclerom',
 'Recunoașterea cromoglicatului, a imunoterapiei mediate de T supresoare pe ani și a biopsiei pentru rinosclerom/Klebsiella când simptomele cronice persistă.',
 ['Prevenirea degranulării mastocitelor de către cromoglicat este explicită.','Reglarea IgE prin T supresoare și durata de ani sunt descrise.','Klebsiella rhinoscleromatis figurează pe lista de infecții de exclus prin cultură/biopsie.','Imunoterapia este eficientă doar în boala mediată de IgE și cere ani, nu o injecție.','Rinoscleromul este o infecție bacteriană (Klebsiella), nu un guturai viral.']],
 8,'Extinde imunoterapia la non-IgE și transformă rinoscleromul (Klebsiella) într-un guturai de 14 zile.',['Cromoglicatul de sodiu','rinoscleromul']),

q(118,['Fractura oaselor nazale, cele mai des fracturate oase ale corpului:',
 ['Lovitura laterală înfundă un os nazal și deplasează lateral osul contralateral; lovitura frontală aplatizează și lărgește dorsum nasi','Hematomul septal, între cartilaj și mucopericondru, trebuie drenat prompt pentru a preveni abcesul și resorbția, cu deformare „nas în șa”','Lovitura severă transmisă posterior poate produce fractură nazo-orbito-etmoidală, cu rinolicvoree, hipertelorism și anosmie','Fracturile nedeplasate impun reducere deschisă de principiu, analog deplasărilor septale complexe','Hematomul septal se resorbe spontan, drenajul fiind rezervat nasului în șa deja constituit'],'ABC',565,'Fractura nazală — Nas în șa, NOE și direcția loviturii',
 'Maparea loviturii laterale versus frontale, a urgenței hematomului septal (nas în șa) și a triadei NOE (LCR, hipertelorism, anosmie).',
 ['Cele două tipare de deformare după direcția loviturii sunt explicite.','Drenajul prompt al hematomului septal pentru a preveni nasul în șa este cerut.','Rinolicvoreea, hipertelorismul și anosmia fracturii NOE sunt enumerate.','Nedeplasatele nu necesită reducere; deschiderea este pentru leziunile complexe cu deplasare septală.','Drenajul este preventiv, nu se așteaptă nasul în șa.']],
 8,'Amână drenajul hematomului până după nasul în șa și cere reducere deschisă la nedeplasate.',['nas în şa','nazo-orbito-etmoidală']),

q(119,['Tratamentul medicamentos empiric al sinuzitei acute necomplicate se face, de regulă, timp de:',
 ['7–14 zile, cu amoxicilină-acid clavulanic, cefprozil, cefuroximă, claritromicină sau loracarbef, plus o cură scurtă de decongestionante topice și steroizi intranazali','3 zile de ceftriaxonă parenteral, analog eșecului OMA','48–72 de ore de observație fără antibiotic, analog OMA neclare','3 luni, analog ferestrei OMS fără risc de limbaj','O singură doză de amoxicilină 90 mg/kg, analog primei linii din OMA'],'A',565,'Sinuzita acută — Durata 7–14 zile și spectrul empiric',
 'Memorarea ferestrei 7–14 zile și a listei de molecule (amox-clav, cefalosporine orale, claritromicină, loracarbef) plus topițe scurte.',
 ['Intervalul 7–14 zile și lista de antibiotice plus decongestionant/steroid topic sunt explicite.','Ceftriaxona 3 zile este treapta de eșec a OMA, nu prima linie a sinuzitei.','Observația 48–72 de ore este a OMA neclare.','3 luni este urmărirea OMS.','90 mg/kg de amoxicilină este prima linie a OMA, nu durata sinuzitei.']],
 8,'Permutează 7–14 zile cu ferestrele OMA (48–72 de ore, 3 zile de ceftriaxonă) și cu 3 luni ale OMS.',['7-14 zile','loracarbef']),

q(120,['În infecția rinosinusală micotică invazivă a imunocompromisului, diagnosticul depinde de:',
 ['Identificarea histologică a fungilor invazivi în specimene bioptice; exudatul nazal este insuficient','Cultura din exudatul nazal, biopsia fiind superfluă dacă cornetele sunt negre','Timpanometrie plată, analog efuziunii otice','PCR pentru HSV, analog paraliziei Bell','Teste cutanate cu extracte de polen, analog rinitei IgE'],'A',566,'Infecțiile fungice rinosinusale — Biopsie, nu exudat',
 'Recunoașterea biopsiei cu fungi invazivi ca standard, exudatul nazal fiind declarat insuficient, lângă cornetele negre necrotice.',
 ['Dependența diagnosticului de histologia biopsiei și insuficiența exudatului sunt explicite.','Exudatul este declarat insuficient; cornetele negre sunt un semn clinic, nu un substitut al biopsiei.','Timpanograma plată privește urechea medie.','PCR HSV confirmă Bell-ul, nu mucormicoza.','Testele cutanate țin de rinita alergică.']],
 8,'Înlocuiește biopsia tisulară (singurul diagnostic) cu exudatul nazal sau cu PCR/teste cutanate din alte capitole.',['Exudatul nazal este insuficient','cornetele negre']),

q(121,['Angiofibromul juvenil nazo-faringian:',
 ['Se dezvoltă în fosa pterigomaxilară și se prezintă ca tumoră nazală unilaterală la băieții adolescenți, cu epistaxis și obstrucție','Diagnosticul este clinic și radiologic, biopsia putând produce hemoragie riscantă; embolizarea preoperatorie reduce sângerarea la excizie','Se biopsiază de rutină înaintea imagisticii, analog carcinomului scuamos oral','Afectează fetele premenstruale, analog rinitei estrogenice','Se monitorizează ca osteomul fronto-etmoidal asimptomatic, fără excizie'],'AB',566,'Angiofibromul juvenil — Fosa pterigomaxilară și interdicția biopsiei',
 'Recunoașterea adolescentului masculin, a fosei pterigomaxilare și a interdicției de biopsie, cu embolizare preoperatorie.',
 ['Sediul pterigomaxilar, sexul, vârsta, epistaxisul și obstrucția sunt explicite.','Diagnosticul clinic/radiologic, riscul biopsiei și embolizarea preoperatorie sunt enunțate.','Biopsia de rutină este tocmai gestul riscant.','Entitatea este a băieților adolescenți, nu a fetelor cu rinită hormonală.','Osteomul asimptomatic se monitorizează; angiofibromul se excizează după embolizare.']],
 8,'Cere biopsia de rutină (contraindicată) și mută tumora pe profilul rinitei estrogenice sau al osteomului monitorizat.',['pterigomaxilare','embolizarea preoperatorie']),

q(122,['Cea mai des întâlnită formă de cancer intranazal în rândul copiilor este:',
 ['Rabdomiosarcomul, o tumoră a musculaturii striate; chirurgia este adesea redusă la procedură de diagnostic, după progresele chemo- și radioterapiei','Osteomul fronto-etmoidal, cea mai frecventă tumoră a sinusurilor la adult','Papilomul invertit, cu degenerare în 10–15%','Neuroblastomul olfactiv (estezioneuroblastomul)','Carcinomul scuamos, care reprezintă 90% din tumorile maligne orale ale adultului'],'A',566,'Neoplazii rinosinusale — Rabdomiosarcomul copilului',
 'Identificarea rabdomiosarcomului ca cel mai frecvent cancer intranazal pediatric, cu chirurgie adesea doar diagnostică.',
 ['Textul numește rabdomiosarcomul cea mai des întâlnită formă de cancer intranazal la copii și reduce rolul chirurgiei la diagnostic.','Osteomul este cea mai frecventă tumoră sinusală (adesea benignă, la adult).','Papilomul invertit este al adultului, invaziv local.','Estezioneuroblastomul este o malignitate rară neuroectodermală.','90% scuamos privește cavitatea orală/faringele adultului, nu cancerul intranazal pediatric.']],
 8,'Înlocuiește rabdomiosarcomul pediatric cu osteomul, papilomul invertit sau scuamosul oral 90%, ierarhii din același paragraf de neoplazii.',['Rabdomiosarcomul','copiilor']),

q(123,['Inervația limbii se caracterizează prin:',
 ['Mișcările sunt controlate de perechi de mușchi extrinseci și intrinseci inervați de nervul hipoglos','Senzația gustativă din două treimi anterioare este transmisă de nervul lingual către coarda timpanului, ramură a facialului','Ramura linguală a glosofaringianului deservește fibrele gustative ale treimii posterioare','Gustul celor două treimi anterioare trece prin nervul IX, analog reflexului nauseos','Hipoglosul este strict senzitiv, motilitatea limbii depinzând de facial'],'ABC',566,'Limba — Hipoglos, coarda timpanului și IX',
 'Separarea motilității (XII) de gustul anterior (lingual → coarda timpanului/VII) și de gustul posterior (IX).',
 ['Inervația motorie prin hipoglos este explicită.','Calea lingual–coarda timpanului–facial pentru cele două treimi anterioare este descrisă.','Glosofaringianul lingual pentru treimea posterioară este enunțat.','IX nu deservește gustul celor două treimi anterioare.','Hipoglosul este motor, nu strict senzitiv.']],
 8,'Oglindește VII (coarda) cu IX pe cele două treimi anterioare și face din hipoglos un nerv senzitiv.',['coarda timpanului','glosofaringian']),

q(124,['În planificarea corecției cheiloschizisului se aplică regula lui 10, adică atunci când copilul:',
 ['Are peste 10 săptămâni, cântărește peste 4,53 kg și are Hb peste 10','Are peste 10 luni, 10 kg și Hb 14, analog adultului','Este operat înainte de 2 ani, analog palatoschizisului pentru limbaj','Are 1,5/1.000, analog incidenței displaziei de șold','Prezintă sindrom Pierre Robin, cu indicație de ham Pavlik'],'A',569,'Cheiloschizisul — Regula lui 10',
 'Memorarea triadei >10 săptămâni, >4,53 kg, Hb >10 ca prag de programare a cheiloplastiei.',
 ['Cele trei praguri ale regulii lui 10 sunt explicite.','10 luni/10 kg/Hb 14 nu sunt cifrele din text.','Înainte de 2 ani este ținta palatoschizisului pentru limbaj, nu regula lui 10 a buzei.','1,5/1.000 este incidența DDH.','Pierre Robin se tratează prin biberon special, fixarea limbii sau traheostomie, nu prin Pavlik.']],
 8,'Permutează 10 săptămâni/4,53 kg cu 10 luni/10 kg și cu fereastra de 2 ani a palatului.',['regula lui 1 O','>4,53 kg']),

q(125,['Corecția palatoschizisului se realizează înainte de vârsta de 2 ani pentru a permite dezvoltarea normală a limbajului. În plus:',
 ['Pacienții prezintă constant otită medie seroasă cronică, deoarece musculatura palatului este redirecționată, cu afectarea deschiderii trompei lui Eustachio','Tuburi de ventilație auriculară sunt inserate, de obicei, pentru a trata OMS recurentă','Palatoschizisul nu afectează trompa, OMS fiind întâmplătoare','Cheiloplastia se amână după 2 ani, regula lui 10 neavând rol în primele luni','Incompetența velo-faringiană îmbunătățește presiunile de deglutiție și deschide sfincterul esofagian superior'],'AB',569,'Palatoschizisul — OMS prin musculatura palatului și tuburi',
 'Legarea redirecționării mușchilor palatini de OMS cronică și de inserția de tuburi de ventilație, alături de ținta de 2 ani pentru limbaj.',
 ['OMS constantă prin redirecționarea musculaturii palatului și afectarea trompei este explicită.','Inserția uzuală a tuburilor de ventilație este enunțată.','Textul leagă explicit palatoschizisul de OMS.','Cheiloplastia începe din primele luni, după regula lui 10.','Incompetența velo-faringiană scade presiunile de deglutiție și împiedică deschiderea sfincterului esofagian superior.']],
 8,'Neagă legătura palat–trompa lui Eustachio și inversează ferestrele buzei (luni) versus palatului (înainte de 2 ani).',['înainte de vârsta de 2 ani','otită medie seroasă']),

q(126,['Apneea obstructivă în somn se definește, pe somnografie, prin scăderea semnalului termic oro-nazal cu cel puțin:',
 ['90% din valoarea de bază, pentru cel puțin 10 secunde','50% timp de 50% din noapte, analog PIV-ului','10% timp de 10–12 săptămâni, analog lichidului post-OMA','60% din ciclu, analog fazei de sprijin a mersului','25%, analog mortalității fasceitei necrozante'],'A',569,'Apneea de somn — Pragul 90% timp de 10 secunde',
 'Memorarea definiției polisomnografice: scădere ≥90% a senzorului termic, ≥10 secunde.',
 ['Pragurile 90% și 10 secunde sunt explicite.','50% este PIV-ul vocal.','10–12 săptămâni este persistența lichidului după OMA.','60% este faza de sprijin a mersului, din capitolul de ortopedie, nu definiția apneei.','25% este mortalitatea fasceitei necrozante.']],
 8,'Permutează 90%/10 secunde cu alte procente-prag din bancă (50%, 10%, 60%, 25%).',['90% din valoarea de bază','1 O secunde']),

q(127,['Apneea obstructivă a adultului obez, respectiv a copilului, se deosebesc prin:',
 ['La adult, obstrucția nazală și circumferința mare a gâtului sunt frecvente; CPAP nocturn este tratamentul, iar scăderea ponderală până la greutatea ideală este de obicei curativă','La copii, IMC este de obicei normal, dar este prezentă hipertrofia adenoidiană și amigdaliană','Dacă adultul nu tolerează CPAP sau nu slăbește, pot ajuta septoplastia, turbinoreducția, tonsilectomia sau uvulo-palato-faringoplastia','La copil, CPAP înlocuiește de principiu adenotonsilectomia, IMC-ul fiind crescut analog adultului','Traheostomia este primul gest la adultul obez, înaintea oricărui CPAP'],'ABC',569,'Apneea de somn — Adult (CPAP, gât) versus copil (adenoizi)',
 'Contrastarea adultului obez cu gât gros (CPAP, scădere ponderală, UPPP) cu copilul normoponderal cu hipertrofie adenotonsilară.',
 ['Obstrucția nazală, circumferința gâtului, CPAP și caracterul curativ al scăderii ponderale sunt explicite.','IMC normal plus hipertrofia adenotonsilară la copil sunt enunțate.','Lista de recalibrări chirurgicale (septoplastie, turbină, tonsile, UPPP) este citată.','La copil, hipertrofia adenotonsilară este mecanismul, nu IMC-ul de adult; CPAP nu înlocuiește de principiu adenotonsilectomia.','Traheostomia este rezervată cazurilor severe, nu este primul gest.']],
 8,'Atribuie copilului IMC-ul adultului și pune traheostomia înaintea CPAP-ului.',['CPAP','hipertrofia adenoidiană']),

q(128,['Dintre tumorile maligne ale cavității orale și faringelui, ponderea carcinoamelor scuamoase este de circa:',
 ['90%; la buză prognosticul este mai bun decât în cavitatea orală, dar mai agresiv decât scuamoasele cutanate similare','10%, analog raportului cancer laringian/pulmonar','5%, analog celorlalte histologii laringiene în afara scuamosului','50%, analog PIV-ului vocal','75%, analog presbiacuziei până la 80 de ani'],'A',569,'Carcinomul oral — 90% scuamos și prognosticul buzei',
 'Memorarea celor 90% scuamoase și a poziției prognostice a buzei (mai bună decât gura, mai agresivă decât pielea).',
 ['Ponderea de 90% și comparația prognostică buză–cavitate orală–piele sunt explicite.','10% este incidența cancerului laringian față de pulmonar.','Sub 5% sunt celelalte malignități laringiene.','50% este PIV.','75% este presbiacuzia.']],
 8,'Permutează 90% scuamos oral cu 10% laringe/pulmonar și cu 5% non-scuamos laringian.',['90% sunt carcinoame','buzei']),

q(129,['Laringomalacia, dincolo de ponderea de 60% a stridorului pediatric, se caracterizează prin:',
 ['Prezență la naștere, adesea la prematuri; majoritatea simptomelor apar în primele 2 luni','Stridor agravat în decubit dorsal sau la hrănire; diagnostic prin laringoscopie flexibilă cu colaps în ventilație spontană','Remisie spontană până în al doilea an de viață; părinții evită supinația, mai ales în somn','Supraglotoplastia este rezervată apneei alarmante și retardului de creștere','Stridorul se ameliorează în decubit dorsal și impune traheopexie, analog traheomalaciei'],'ABCD',573,'Laringomalacia — Decubit, 2 luni, remisie în anul 2, supraglotoplastie',
 'Completarea epidemiologiei de 60% cu agravarea în supinație, laringoscopia flexibilă, remisia până la 2 ani și indicația îngustă de supraglotoplastie.',
 ['Debutul la naștere/prematuri și fereastra de 2 luni sunt explicite.','Agravarea în decubit/hrănire și laringoscopia flexibilă sunt descrise.','Remisia până în anul 2 și evitarea supinației sunt enunțate.','Supraglotoplastia pentru apnee și eșec de creștere este citată.','Agravarea, nu ameliorarea, este în decubit; traheopexia este a traheomalaciei.']],
 8,'Inversează efectul decubitului și înlocuiește supraglotoplastia cu traheopexia traheomalaciei.',['decubit dorsal','al doilea an de viaţă']),

q(130,['Traheomalacia și stenoza subglotică a copilului:',
 ['Traheomalacia produce stridor expirator sau bifazic prin colaps antero-posterior; remisia este de regulă în primele 18 luni','La copii, spațiul subglotic este cea mai îngustă regiune a căii aeriene superioare','Exacerbările stenozei ușoare răspund de obicei la epinefrină racemică nebulizată și corticosteroizi sistemici','Diafragmele congenitale se formează când recanalizarea embrionară a laringelui eșuează','Subglota adultului este mai îngustă decât a copilului, analog glotei care nu tolerează edemul'],'ABCD',573,'Calea aeriană pediatrică — Traheomalacie 18 luni și subglota îngustă',
 'Integrarea colapsului AP cu remisia la 18 luni, a subglotei ca cel mai îngust segment pediatric și a adrenalinei racemice, plus diafragmele din eșecul recanalizării.',
 ['Stridorul expirator/bifazic, colapsul AP și 18 luni sunt explicite.','Subglota ca cea mai îngustă regiune la copil este enunțată.','Epinefrina racemică și steroizii sistemici sunt tratamentul exacerbărilor.','Eșecul recanalizării embrionare ca origine a diafragmelor este descris.','Glota adultului este mai mare și tolerează edemul; subglota copilului este îngustă, nu invers.']],
 8,'Oglindește calibrul subglotei copil versus adult și mută remisia de 18 luni pe o stenoză care s-ar agrava la adult.',['18 luni de viaţă','epinefrina racemică']),

q(131,['Un copil cu epiglotită, dincolo de agentul H. influenzae și de interdicția apăsătorului de limbă:',
 ['Incidența a scăzut substanțial după vaccinul anti-H. influenzae','Adoptă o poziție cu toracele ridicat și capul în hiperextensie, care aliniază laringele și traheea','Odată calea aeriană asigurată, se preferă intubația nazo-traheală datorită stabilității superioare','Vaccinul a crescut incidența, analog trecerii de la otita externă malignă la cea necrotizantă','Intubația oro-traheală este preferată nazo-trahealei, analog cricotirotomiei adultului'],'ABC',574,'Epiglotita — Vaccin, poziție de hiperextensie și intubație nazală',
 'Adăugarea scăderii post-vaccinale, a poziției cu toracele ridicat/cap în hiperextensie și a preferinței nazo-traheale, peste agentul și apăsătorul deja cunoscuți.',
 ['Scăderea incidenței după vaccin este explicită.','Poziția de aliniere laringe-trahee este descrisă.','Preferința nazo-traheală pentru stabilitate este enunțată.','Vaccinul a scăzut, nu a crescut, incidența.','Nazo-traheala este preferată oro-trahealei.']],
 8,'Inversează impactul vaccinului și preferința nazo- versus oro-traheală.',['vaccinului anti-H. influenzae','nazo-traheal']),

q(132,['Papilomatoza laringiană se tratează prin:',
 ['Ablație laser endoscopică; radioterapia este mai puțin eficientă','Terapii sistemice în studiu: α-interferon, ribavirină, aciclovir și indole-3, pentru cazurile severe','Traheotomie de primă intenție la copil, pentru a preveni însămânțarea distală','Radioterapie ca tratament de elecție, analog carcinomului glotic mic','β-blocant, analog hemangiomului subglotic care regresează la 4 ani'],'AB',576,'Papilomatoza laringiană — Laser versus radioterapie și antivirale în studiu',
 'Recunoașterea laserului endoscopic ca tratament, a ineficienței relative a radioterapiei și a antiviraleelor/interferonului încă în studiu.',
 ['Ablația laser și eficiența mai mică a radioterapiei sunt explicite.','α-interferonul, ribavirina, aciclovirul și indole-3 sunt enumerate ca terapii în studiu.','Traheostomia trebuie evitată la copil din riscul de însămânțare.','Radioterapia este mai puțin eficientă; la glota mică fără ganglioni este o opțiune oncologică, nu a papilomului.','β-blocantul este al hemangiomului subglotic.']],
 8,'Pune traheotomia sau radioterapia (sau β-blocantul hemangiomului) în locul laserului, trei capcane din același paragraf de leziuni vasculare și papilare.',['ablaţia laser','a-interferon']),

q(133,['Pentru tumorile glotice mici, superficiale, fără extensie paraglotică și fără adenopatii, chirurgia și radioterapia oferă la 3 ani o rată de supraviețuire de:',
 ['Peste 90%','Circa 10%, analog raportului laringe/pulmonar','Sub 5%, analog histologiilor non-scuamoase','70% în minus, analog impactului adenopatiei cervicale la 5 ani','25%, analog mortalității fasceitei necrozante'],'A',576,'Carcinomul glotic mic — Supraviețuire >90% la 3 ani',
 'Memorarea supraviețuirii >90% la 3 ani pentru glota mică tratată prin chirurgie sau radioterapie, distinctă de scăderea cu 70% pe care o aduce adenopatia.',
 ['Rata >90% la 3 ani pentru ambele modalități, la leziuni glotice mici fără extensie ganglionară, este explicită.','10% este incidența față de cancerul pulmonar.','Sub 5% sunt celelalte histologii.','Adenopatia reduce supraviețuirea la 5 ani cu până la 70%, nu este rata glotei mici.','25% este mortalitatea fasceitei.']],
 8,'Permutează >90% la 3 ani cu scăderea de 70% indusă de adenopatie și cu 10% laringe/pulmonar.',['>90%','corzilor vocale']),

q(134,['Adenita cervicală profundă a adultului, de regulă de origine dentară:',
 ['CT delimitează abcesul; la copil CT poate fi înșelător, interpretând flegmonul ca abces','Incizia cervicală laterală se face cu prudență, ganglionii și abcesele fiind în teaca carotidiană','Nedrenat, abcesul poate fuza de-a lungul planurilor până la mediastin, cu morbiditate și mortalitate crescute','Incizia mediană tip Sistrunk este calea de drenaj, analog chistului tireoglos','La copil, CT distinge infailibil abcesul de flegmon, făcând inutilă prudența operatorie'],'ABC',580,'Abcesul cervical profund — Teaca carotidă, mediastin și CT pediatric',
 'Recunoașterea capcanei CT-ului pediatric (flegmon vs abces), a tecii carotidiene și a riscului de fuzare mediastinală.',
 ['CT fidel la adult și înșelător la copil (flegmon ca abces) este explicit.','Incizia laterală prudentă în teaca carotidă este descrisă.','Fuzarea mediastinală cu morbiditate/mortalitate crescute este enunțată.','Sistrunk este operația chistului tireoglos, nu drenajul abcesului profund.','La copil CT poate fi înșelător, nu infailibil.']],
 8,'Cere Sistrunk ca drenaj și tratează CT-ul pediatric ca infailibil, două erori de gât congenital versus infecțios.',['teaca carotidiană','mediastinal']),

q(135,['Adenitele cervicale micobacteriene la copil, comparativ cu scrofula adultului:',
 ['Cazurile cu bacterii atipice (Mycobacterium avium-intracellulare) sunt mai frecvente la copii decât adenitele tuberculoase','Se prezintă ca formațiune nedureroasă fluctuentă, adesea parotidiană sau submandibulară, cu tegument violaceu; neglijată, fistulizează','Tratamentul optim al atipicelor rezistente este excizia grupelor ganglionare; antibioticele sunt rezervate recurențelor sau rezecției parțiale','Scrofula (adenita TBC) se tratează optim chirurgical, fără antibiotic, analog atipicelor','Majoritatea pacienților cu scrofulă asociază leziuni pulmonare concomitente'],'ABC',580,'Adenita micobacteriană — MAC pediatric versus scrofulă',
 'Contrastarea predilecției MAC la copil (excizie, tegument violaceu) cu scrofula tratată antibiotic, adesea fără leziuni pulmonare.',
 ['Predominanța atipicelor față de TBC la copii este explicită.','Forma fluctuentă, sediul parotidian/submandibular, violaceul și fistulizarea sunt descrise.','Excizia ca tratament optim al atipicelor, cu antibiotic la recurență/rezecție parțială, este enunțată.','Scrofula se tratează optim cu antibiotice; chirurgia este adjuvantă pentru histologie.','Textul notează că, în mod curios, majoritatea nu asociază leziuni pulmonare.']],
 8,'Oglindește tratamentul (excizie la atipice, antibiotic la scrofulă) și atribuie scrofula o leziune pulmonară concomitentă pe care textul o neagă.',['avium-intracellulare','violacee']),

q(136,['Indicațiile traheotomiei, conform tabelului 27-12, includ:',
 ['Ocolirea obstrucției căii aeriene superioare','Dependență ventilatorie prelungită anticipată, de obicei peste 2 săptămâni','Acces direct pentru irigare și aspirare (toaletă pulmonară)','Prevenirea aspirării cronice și reducerea spațiului mort la efort ventilator precar sau deprimare a SNC','Cricotirotomia de urgență ca substitut de tabel, fără conversie ulterioară'],'ABCD',583,'Traheotomia — Tabelul 27-12',
 'Lista completă a tabelului 27-12: bypass obstructiv, ventilație >2 săptămâni, toaletă pulmonară, prevenirea aspirației și reducerea spațiului mort.',
 ['Ocolirea obstrucției este primul item.','Pragul de obicei peste 2 săptămâni este citat.','Toaleta pulmonară prin irigare/aspirare figurează explicit.','Prevenirea aspirării cronice și reducerea spațiului mort încheie tabelul.','Cricotirotomia este gestul de urgență când intubația eșuează; tabelul 27-12 este al traheotomiei, iar cricotirotomia se convertește dacă intubația depășește câteva zile.']],
 8,'Înlocuiește itemii de toaletă/spațiu mort ai tabelului cu cricotirotomia neconvertită, o confuzie de procedură de urgență versus planificată.',['toaletă pulmonară','spaţiului mort']),

q(137,['Cricotirotomia, când intubația orotraheală eșuează, presupune:',
 ['Incizie verticală a tegumentului imediat deasupra membranei cricotiroidiene, apoi incizie orizontală a membranei, cu plasarea unei sonde traheale','Incizie orizontală a tegumentului și verticală a membranei, analog traheotomiei dintre inele','Traheotomie imediat subcricoidiană ca prim gest la adult, analog copilului mic','Laringectomie totală, pacientul nemaiputând fi intubat oral','Miringotomie largă, analog parezei faciale din OMA'],'A',583,'Cricotirotomia — Incizie cutanată verticală, membrană orizontală',
 'Recunoașterea secvenței piele verticală deasupra membranei, apoi membrană orizontală, distinctă de traheotomia subcricoidiană a copilului.',
 ['Secvența verticală pe piele, orizontală pe membrană și sonda traheală este explicită.','Orientările inciziilor sunt inverse față de text.','Subcricoidiana este calea copilului mic, la care cricotirotomia nu este posibilă.','Laringectomia totală ancorează traheea la tegument în cancer, nu în obstrucția acută.','Miringotomia privește OMA cu pareză facială.']],
 8,'Oglindește direcțiile de incizie (piele versus membrană) și înlocuiește gestul cu traheotomia copilului sau cu laringectomia.',['Incizarea ve1ticală','Membrana va fi incizată']),

q(138,['Electronistagmografia și posturografia pe platformă evaluează sistemul vestibular astfel:',
 ['ENG folosește electrozi periorbitali și tehnici calorice sau de rotire a capului pentru a cuantifica nistagmusul și integritatea vestibulară','Posturografia modifică feedback-ul vizual și proprioceptiv (încăpere fără indicii vizuale, platformă instabilă) pentru a izola contribuția vestibulară la orientare','ENG înlocuiește audiograma tonală în hipoacuzia de transmisie','Posturografia se face cu ochii deschiși pe platformă fixă, analog testului Rinne','Testul Weber de 512 Hz pe mastoidă este echivalentul ENG'],'AB',556,'Evaluare vestibulară — ENG caloric și posturografie',
 'Separarea cuantificării nistagmusului (electrozi periorbitali, caloric/rotire) de izolarea vestibulului prin scoaterea vederii și propriocepției.',
 ['Electrozii periorbitali, stimularea calorică/de rotație și cuantificarea nistagmusului sunt explicite.','Eliminarea feedback-ului vizual și proprioceptiv pe platformă instabilă este descrisă.','ENG nu înlocuiește audiograma de transmisie.','Testul cere tocmai alterarea vederii și a platformei, nu ochi deschiși pe suport fix.','Weber este un test cu diapazon, nu ENG.']],
 8,'Confundă ENG/posturografia cu Weber/Rinne și cu audiograma de transmisie, toate teste de ureche din același capitol.',['Electronistagmografia','Posturografia pe platformă']),

q(139,['Pavilionul auricular se formează din șase coliculi branhiali cartilaginoși ai primului și celui de-al doilea arc. Sunt adevărate:',
 ['Defectele duc la chisturi sau tracturi sinusale preauriculare, rezecabile dacă se infectează frecvent','Anomalii importante ale primului arc pot duce la absența pavilionului, a conductului sau a structurilor urechii medii/interne','Cele mai importante intervenții sunt evaluarea audiometrică și reabilitarea auditivă precoce cu proteze, ideal în primul an de viață; reconstrucția chirurgicală începe ulterior','Reconstrucția pavilionului precede orice protezare, chiar în primul an','Tracturile preauriculare se lasă netratate chiar după infecții repetate, analog exostozelor asimptomatice'],'ABC',556,'Anomalii congenitale auriculare — Șase coliculi și protezarea în primul an',
 'Recunoașterea originii din arcele 1–2, a tracturilor preauriculare infectate și a priorității reabilitării auditive în primul an, înaintea reconstrucției.',
 ['Chisturile/tracturile din defecte de unire a coliculilor și rezecția după infecții repetate sunt explicite.','Anomaliile majore ale primului arc, cu absența pavilionului/conductului/urechii medii-interne, sunt descrise.','Audiometria și protezarea în primul an, cu reconstrucție ulterioară, sunt enunțate.','Reabilitarea auditivă precoce precede seria reconstructivă.','Tracturile cu infecții frecvente se rezecă.']],
 8,'Pune reconstrucția înaintea protezării din primul an și lasă tracturile infectate netratate, analog exostozelor.',['primul an de viaţă','primului arc branhial']),

q(140,['Pentru a proteja corneea în paralizia facială cu lagoftalmie, pe lângă lacrimi artificiale, creme și benzi nocturne, pot fi necesare:',
 ['Blefarorafie sau atașarea de greutăți pe bază de plăcuțe de aur la nivelul pleoapei superioare','Stapedectomie, analog otosclerozei cu scăriță fixată','Manevra Epley, analog BPPV','Decompresia sacului endolimfatic, analog Meniere refractar','Embolizarea preoperatorie, analog angiofibromului juvenil'],'A',560,'Paralizia facială — Plăcuțe de aur palpebrale',
 'Recunoașterea blefarorafiei și a greutăților de aur pe pleoapa superioară ca gesturi de acoperire corneană, dincolo de lacrimi și benzi.',
 ['Blefarorafia și plăcuțele de aur palpebrale sunt citate explicit pentru o mai bună acoperire a corneei.','Stapedectomia tratează otoscleroza, nu lagoftalmia.','Epley repoziționează otoconii, nu închide pleoapa.','Decompresia sacului este a Meniere-ului neresponsiv.','Embolizarea reduce sângerarea angiofibromului, nu protejează corneea.']],
 8,'Înlocuiește greutățile de aur palpebrale cu stapedectomie, Epley sau embolizare, trei gesturi din același capitol otologic.',['plăcuţe de aur','pleoapei superioare']),
];
