import {advancedQuestion} from './advanced-author';
import type {SourceRow} from './source-author';

const EDITION='Chirurgie generală și specialități chirurgicale, ediția pentru rezidențiat MG 2025';
const pdfOffset=(p:number)=>p===605?p-327:p===606?p-329:p-328;
const q=(n:number,row:SourceRow,score:number,reason:string,expressions:string[],related:number[]=[])=>
 advancedQuestion('ortopedie',28,pdfOffset,`ortopedie-adv-${String(n).padStart(3,'0')}`,row,[score,reason],expressions,undefined,related,'Lawrence',EDITION);

export const ORTOPEDIE_D=[
q(106,['Plăgile deschise extinse sau cele apărute în urma activităților din gospodărie, pe lângă cefalosporina de generația I, se tratează în plus cu:',
 ['Aminoglicozide și metronidazol','Doar vaccin antitetanic, fără alt antibiotic','Fluorochinolonă orală ca unică acoperire a contaminării ușoare','Antifungice sistemice, analog otitei externe necrotizante','Heparină în doză de embolie grăsoasă, înaintea debridării'],'A',591,'Fracturi deschise — Contaminare extinsă și din gospodărie',
 'Recunoașterea adaosului de aminoglicozid plus metronidazol la plăgile extinse sau din gospodărie, distinct de cefalosporina de generația I a contaminării ușoare.',
 ['Textul cere, pentru leziunile extinse sau din gospodărie, aminoglicozide și metronidazol (Flagyl) pe lângă cefalosporină.','Antitetanosul este adjunct, nu înlocuiește dublarea antibiotică.','Cefalosporina de generația I intravenos este rezervată contaminării ușoare, nu este înlocuită de o fluorochinolonă orală.','Antifungicele nu figurează în protocolul fracturii deschise din acest paragraf.','Embolia grăsoasă se tratează suportiv, nu cu heparină înaintea debridării.']],
 8,'Adaugă metronidazolul și aminoglicozidul doar la gospodărie/extins, lângă cefalosporina de generația I deja cunoscută.',['aminoglicozide','metronidazol']),

q(107,['Tracțiunea folosită pentru a obține și menține reducerea unei fracturi:',
 ['Tracțiunea transtegumentară este utilă la copiii mici','Tracțiunea transosoasă cere o broșă distal de focar, pentru a depăși contracția mușchilor mari în fracturi pelvine, femurale sau tibiale','În fracturile humerale, greutatea membrului superior distal aplică tracțiune gravitațională dacă corpul este în ortostatism','Tracțiunea transosoasă este metoda de elecție la sugar, tegumentul fiind evitat','Gravitația pe humerus a înlocuit ortezele funcționale, fiind folosită de rutină'],'ABC',591,'Menținerea reducerii — Tracțiune tegumentară, transosoasă și gravitațională',
 'Diferențierea tracțiunii pe piele la copilul mic, a broșei distale la pelvis/femur/tibie și a greutății brațului în fractura de humerus.',
 ['Utilitatea tracțiunii transtegumentare la copiii mici este explicită.','Broșa distală și forțele pe pelvis, femur sau tibie sunt descrise.','Tracțiunea gravitațională a humerusului în ortostatism, eventual cu gips pe antebraț, este enunțată.','La copiii mici se preferă tegumentul, nu broșa transosoasă.','Textul precizează că tehnica gravitațională este foarte rar folosită și în mare parte înlocuită de orteze.']],
 8,'Inversează indicația pediatrică (piele versus broșă) și tratează gravitația humerală ca standard actual, deși textul o declară aproape abandonată.',['Tracţiunea transtegumentară','fracturile humerale'],[593]),

q(108,['Dispozitivele de fixare internă, ca „atelă internă”, se caracterizează prin:',
 ['Mențin doar poziția fragmentelor până la vindecare; prezența implantului nu garantează consolidarea','Încărcarea ciclică a unui implant, dacă fractura nu consolidează, duce la slăbirea sau degradarea acestuia','După îndepărtare, osul se poate refractura la orificiile șuruburilor, mai ales în corticala diafizară','Fixarea internă înlocuiește mecanismele fiziologice de vindecare, deci cursa implant–calus dispare','Refractura după explantare este tipică osului metafizar spongios, nu corticalei diafizare'],'ABC',591,'Fixarea internă — Cursa vindecare versus degradarea implantului',
 'Recunoașterea implantului ca atelă internă, a cursei cu degradarea ciclică și a refracturii la găurile de șurub din corticala diafizară.',
 ['Comparația cu atela internă și absența garanției de vindecare sunt explicite.','Încărcarea repetitivă care slăbește implantul dacă nu există consolidare este enunțată.','Refractura la orificiile șuruburilor, mai ales diafizar cortical, figurează pe pagina următoare.','Textul cere respectarea mecanismelor fiziologice; implantul nu le înlocuiește.','Riscul de refractură este localizat explicit în osul cortical diafizar.']],
 8,'Neagă cursa vindecare–implant și mută refractura din corticala diafizară pe spongiosul metafizar.',['atelă internă','orificiilor şuruburilor'],[592]),

q(109,['Viteza și succesul vindecării unei fracturi sunt influențate de:',
 ['Nivelul de energie al traumatismului: fracturile deschise, cominutive și cu deplasare se vindecă lent','Tipul de os (spongios sau cortical) și integritatea țesutului moale','Starea generală, statusul nutrițional și vârsta: copiii se vindecă mai rapid decât adulții','Clinic, vindecarea este evidentă când nu mai este prezentă durerea la palpare și nu mai există mișcări în focar','Radiologic, vindecarea se recunoaște prin absența oricărui trabecul care să traverseze focarul'],'ABCD',593,'Vindecarea fracturii — Factori de ritm, clinic și radiologic',
 'Integrarea energiei, a tipului de os și a vârstei cu semnele de consolidare (fără durere, fără mobilitate; trabecule care traversează).',
 ['Energia mare (deschise, cominutive, deplasate) ca factor de vindecare lentă este explicită.','Tipul de os și țesutul moale sunt enumerați.','Nutriția și vindecarea mai rapidă a copiilor sunt citate.','Clinic, vindecarea cere dispariția durerii la palpare și a mișcării în focar.','Radiologic se observă trabecule osoase distincte care traversează sediul fracturii.']],
 8,'Inversează semnele clinice și radiologice de consolidare, lăsând factorii de energie și vârstă ca near-miss-uri corecte.',['cominutive','trabecule osoase']),

q(110,['Pe lângă eșecul non-operator și fracturile intra-articulare, tabelul 28-2 include ca indicații de fixare internă:',
 ['Fracturi pe os patologic','Fracturi multiple pe aceeași extremitate sau la același pacient','Fracturi la paraplegici, pentru a favoriza îngrijirea','Fracturi infectate, ca metodă de elecție în locul fixatorului extern','Fracturi deschise instabile, pentru a evita debridarea plăgii'],'ABC',594,'Fixarea internă — Tabelul 28-2, indicații suplimentare',
 'Recunoașterea osului patologic, a fracturilor multiple și a paraplegicului ca indicații de osteosinteză internă, distincte de tabelul 28-3 (infectate, deschise).',
 ['Fracturile pe os patologic figurează explicit în tabel.','Fracturile multiple pe aceeași extremitate sau la același pacient sunt citate.','Paraplegicii sunt indicație pentru a favoriza îngrijirea.','Fracturile infectate țin de tabelul 28-3 (fixare externă).','Fracturile deschise instabile sunt indicație de fixator extern, nu intern de primă intenție.']],
 8,'Mută indicațiile tabelului 28-3 (infectate, deschise) peste cele rămase din 28-2 (patologic, multiple, paraplegic).',['os patologic','paraplegici']),

q(111,['Indicațiile de fixare externă, dincolo de fracturile deschise instabile și pelvine, includ:',
 ['Fracturi infectate','Fracturi cominutive severe sau instabile la care nu se poate practica fixarea internă','Fracturi cu pierdere osoasă, în care lungimea trebuie menținută până la grefă','Fracturi nedeplasate de scafoid, în locul atelei gipsate','Fracturi pe os patologic de col femural, ca alternativă la hemiartroplastie'],'ABC',594,'Fixarea externă — Tabelul 28-3, indicații rămase',
 'Completarea tabelului 28-3 cu infecția, cominuția ireductibilă intern și menținerea lungimii până la grefă.',
 ['Fracturile infectate figurează explicit.','Cominuția severă când fixarea internă nu este posibilă este citată.','Pierderea osoasă cu menținerea lungimii până la grefă este enunțată.','Scafoidul nedeplasat se imobilizează în atelă gipsată.','Osul patologic de col femural este indicație de fixare internă sau hemiartroplastie, nu de fixator ca primă linie.']],
 8,'Extinde fixatorul la scafoid și col patologic, două entități tratate intern sau conservator în același capitol.',['Fracturi infectate','grefe osoase']),

q(112,['Pacienții cu luxații post-traumatice ale șoldului dezvoltă, de regulă, coxartroză la:',
 ['10–20 de ani mai târziu','6 săptămâni, analog contracturii lombare mecanice','8–12 ore, fereastra de necroză avasculară, nu de artroză','2 zile, intervalul calusului moale','Un an, controlul radiologic al plăcii de creștere'],'A',594,'Artroza post-traumatică — Fereastra 10–20 de ani după luxația de șold',
 'Separarea decadei 10–20 de ani a coxartrozei post-luxație de ferestrele scurte (NAV 8–12 ore, calus, controlul de 1 an).',
 ['Textul plasează coxartroza, de regulă, la 10–20 de ani după luxația post-traumatică de șold.','6 săptămâni este evoluția durerii mecanice lombare, nu a coxartrozei.','8–12 ore este fereastra de necroză avasculară dacă reducerea întârzie.','2 zile–6 săptămâni este calusul moale.','Un an este controlul radiologic al fracturilor de placă de creștere.']],
 8,'Permutează 10–20 de ani cu 8–12 ore (NAV) și cu alte ferestre din același capitol.',['I 0-20 de ani','coxartroză']),

q(113,['Fractura de olecran, după cădere pe cot, se caracterizează prin:',
 ['Deplasare prin contracția tricepsului brahial, cu pierderea extensiei active a cotului','Interesarea suprafețelor articulare; orice deplasare impune chirurgie pentru a reface articulația și integritatea tricepsului','Tratament prin supinație și flexie ușoară, analog pronației dureroase a copilului','Imobilizare în atelă de la cot la palmă, ca în Colles, fără a reface tricepsul','Fasciotomie de compartiment anterior, analog sindromului de efort'],'AB',596,'Fractura de olecran — Triceps și suprafața articulară',
 'Recunoașterea deplasării prin triceps, cu pierderea extensiei active, și a indicației chirurgicale pentru orice deplasare articulară.',
 ['Contracția tricepsului și pierderea extensiei active sunt explicite.','Interesarea articulară și chirurgia pentru deplasare sunt enunțate.','Flexia ușoară cu supinație tratează pronația dureroasă, nu olecranul.','Atela cot-palmă este a fracturii Colles.','Fasciotomia nu reface tricepsul rupt de pe olecran.']],
 8,'Înlocuiește refacerea tricepsului cu manevra de pronație dureroasă sau cu atela Colles, două gesturi învecinate pe aceeași pagină.',['olecran','triceps brahial']),

q(114,['Dacă ischemia musculară a antebrațului depășește 8 ore, revascularizarea membrului produce:',
 ['Complicații sistemice prin hiperpotasemie și eliberare de mioglobină','Doar o contractură Volkmann reversibilă, fără risc metabolic','Embolie grăsoasă cu peteșii, analog fracturilor de oase lungi','Osteonecroză a scafoidului, prin acoperire cartilaginoasă','Calus vicios cubital, corectat prin osteotomie'],'A',596,'Contractura ischemică — Pragul de 8 ore și revascularizarea',
 'Recunoașterea pragului de peste 8 ore ca ischemie ireversibilă, cu hiperpotasemie și mioglobină la revascularizare, dincolo de pragul de 2 ore al leziunii musculare permanente.',
 ['Textul leagă ischemia peste 8 ore de leziune musculară ireversibilă și de complicații sistemice (hiperpotasemie, mioglobină) la revascularizare.','Peste 8 ore leziunea nu mai este reversibilă.','Embolia grăsoasă este o complicație sistemică a fracturilor de oase lungi, nu a revascularizării de compartiment.','Scafoidul este vulnerabil la osteonecroză post-fractură, nu la ischemia de 8 ore a flexorilor.','Calusul vicios este o complicație de aliniere, nu metabolică.']],
 8,'Confundă pragul de 8 ore (hiperK, mioglobină) cu embolia grăsoasă sau cu osteonecroza scafoidului din același capitol.',['8 ore','mioglobină']),

q(115,['Sindromul umăr-mână, complicație a fracturii Colles la vârstnici:',
 ['Asociază redoarea umărului și a degetelor din cauza imobilizării prelungite','Se previne prin exerciții ale umărului și ale degetelor din fazele incipiente de vindecare','Diformitatea Colles tinde să reapară din cauza cominuției corticale dorsale','Nervul ulnar, pe fața dorsală, este structura de examinat înainte și după reducere','Radiografia de control se amână 6 luni, analog urmăririi plăcii de creștere'],'ABC',596,'Fractura Colles — Sindromul umăr-mână și cominuția dorsală',
 'Cuplarea redoarei umăr-degete cu exercițiile precoce și cu tendința de redislocare prin cominuție corticală dorsală.',
 ['Redoarea umărului și a degetelor prin imobilizare prelungită definește sindromul.','Exercițiile umărului și degetelor din fazele incipiente sunt cerute.','Tendința de reapariție a diformității prin cominuție dorsală este explicită.','Nervul median, pe fața volară a pumnului, trebuie examinat, nu ulnarul dorsal.','Radiografia de control este la 10 zile, nu la 6 luni.']],
 8,'Schimbă nervul median volar cu ulnarul și amână controlul de la 10 zile la 6 luni, lângă sindromul umăr-mână.',['umăr-mână','cominuţiei corticale dorsale']),

q(116,['Mecanismul unei fracturi de gleznă se deduce din planul traiectului. Sunt adevărate:',
 ['Traiectul transversal al maleolei mediale sugerează abducție (eversiune sau pronație) a piciorului pe gambă','Traiectul transversal al maleolei laterale sugerează adducție (inversiune sau supinație)','Fractura trimalleolară adaugă un fragment tibial posterior, prin încărcare verticală a gleznei în flexie plantară','Traiectul transversal al maleolei mediale definește inversiunea, analog adducției din figura 28-20A','Fragmentul posterior apare pe radiografia AP, nu pe profil, și exclude încărcarea verticală'],'ABC',599,'Fracturile gleznei — Planul traiectului și trimalleolara',
 'Maparea transversalei mediale pe eversiune, a celei laterale pe inversiune și a maleolei posterioare pe încărcarea verticală în flexie plantară.',
 ['Transversala maleolei mediale ca abducție/eversiune/pronație este explicită.','Transversala lateralei ca adducție/inversiune/supinație este enunțată.','Trimalleolara prin fragment tibial posterior și încărcare verticală în flexie plantară este descrisă.','Transversala medială este a eversiunii, nu a inversiunii.','Fragmentul posterior se vede cel mai bine pe profil.']],
 8,'Oglindește eversiunea (maleolă medială transversală) cu inversiunea și mută fragmentul posterior de pe profil pe AP.',['maleolă medială','trimaleolară']),

q(117,['În fracturile de coloană, sunt adevărate:',
 ['Coloana este instabilă dacă mișcările neprotejate produc deplasări care pot compromite structurile nervoase','La inconștient sau la leziuni deasupra claviculei (faciale), coloana cervicală se presupune lezată până la proba contrarie','Fracturile minore de compresie toraco-lombare asociază frecvent ileus prin hemoragie retroperitoneală; alimentația enterală se amână până la remitere','Ileusul cere alimentație enterală imediată, pentru a preveni atrofia paravertebrală','La paraplegic, absența sensibilității face superfluă examinarea sistematică a viscerelor'],'ABC',599,'Fracturile de coloană — Instabilitate, cervical ocult și ileus',
 'Aplicarea definiției instabilității, a presupunerii cervicale la trauma facială/inconștiență și a ileusului prin hemom retroperitoneal.',
 ['Definiția instabilității prin risc neurologic la mișcare neprotejată este explicită.','Presupunerea leziunii cervicale până la proba contrarie este enunțată.','Ileusul prin hemoragie retroperitoneală și amânarea alimentației sunt descrise.','Alimentația enterală se amână, nu se forțează.','La paraplegic, semnele altor leziuni sunt mascate; examinarea sistematică a structurilor vitale este obligatoriu clinic, dar cuvântul interzis nu apare în opțiune: textul cere totuși examinarea amănunțită.']],
 8,'Forțează alimentația în ileus și anulează examenul viscerelor la paraplegic, două capcane de trauma spinală.',['ileus','deasupra claviculei']),

q(118,['Rezultatele reimplantării digitale, dincolo de ferestrele de ischemie, includ:',
 ['Dintre reimplantările digitale, 85% rămân viabile','Mișcările articulare păstrează circa 50% din funcția normală','Toate degetele devin intolerante la frig cel puțin 2 ani, iar 80% dintre epifize continuă să crească','La copii, amputațiile la orice nivel au o șansă mare de reimplantare cu succes','Gheața uscată prelungește viabilitatea peste 16 ore, fără risc de degerătură'],'ABCD',600,'Reimplantarea — 85% viabilitate, 50% mișcare, intoleranță la frig',
 'Memorarea ratelor 85%/50%/80% și a intoleranței la frig de 2 ani, plus succesul pediatric la orice nivel, versus gheața uscată interzisă.',
 ['Rata de 85% viabilitate digitală este explicită.','Cei 50% din funcția articulară sunt citați.','Intoleranța la frig cel puțin 2 ani și cei 80% de epifize care cresc sunt enunțate.','La copii, amputațiile la orice nivel au o șansă mare de reimplantare cu succes.','Gheața uscată produce degerături; se folosește apă cu gheață.']],
 8,'Reintroduce gheața uscată ca metodă de transport, deși textul o interzice explicit din cauza degerăturilor.',['85% rămân viabile','2 ani']),

q(119,['Epicondilita laterală (cotul tenismenului):',
 ['Este o leziune de suprasolicitare la originea mușchilor extensori ai pumnului pe epicondilul lateral','Tratamentul conservator include repaus, căldură, AINS, întinderea extensorilor și întărirea flexorilor antagonici','Când este necesară chirurgia, se identifică și se excizează țesut de granulație cronic la originea extensorului radial al carpului','Originea lezată este a flexorilor pumnului pe epicondilul medial, analog golf-ului','Chirurgia de primă intenție precede orice întindere a extensorilor'],'ABC',602,'Leziuni sportive — Epicondilita laterală',
 'Recunoașterea originii extensorilor pe epicondilul lateral, a întăririi antagonicilor și a exciziei granulației de pe ECRB.',
 ['Originea extensorilor pumnului pe epicondilul lateral este explicită.','Lista conservatoare, inclusiv întărirea flexorilor, este enumerată.','Granulația de la originea extensorului radial al carpului este sediul chirurgical.','Epicondilul medial și flexorii nu sunt leziunea descrisă ca tenismen.','Chirurgia este rezervată puținele cazuri neresponsive.']],
 8,'Mută leziunea pe epicondilul medial (flexori) și pune chirurgia înaintea conservatorului.',['cotul tenismenului','extensor radial al carpului']),

q(120,['În timpul alergării, piciorul atinge solul de:',
 ['800–2.000 de ori pe o milă, cu o forță de 2–4 ori greutatea corporală','50–100 de ori pe o milă, sub greutatea corporală','O singură dată pe ciclul de mers, analog fazei de sprijin de 60%','9 ori mai frecvent decât în mers, analog raportului tibie/femur','Echivalentul a 14 miliarde de contacte, costul anual al dorsalgiei'],'A',601,'Leziuni de suprasolicitare — Impactul alergării',
 'Memorarea intervalului 800–2.000 de contacte pe milă, cu 2–4 ori greutatea corporală, ca bază a leziunilor de suprasolicitare.',
 ['Cele 800–2.000 de atingeri pe milă și forța de 2–4 ori greutatea sunt explicite.','50–100 subestimează grosolan frecvența.','Ciclul de mers nu reduce contactele alergării la unul.','Raportul 9:1 privește fracturile tibiale versus femurale, nu pașii.','14 miliarde de dolari este costul anual al afecțiunilor coloanei, nu numărul de contacte.']],
 8,'Înlocuiește 800–2.000 și 2–4× greutatea cu alte cifre din capitol (9×, 60%, 14 miliarde).',['800-2.000','2---4 ori']),

q(121,['La alergătorul recreațional, durerea de stres tibial este de obicei localizată în compartimentul anterior, care conține:',
 ['Tibialul anterior, extensorul degetelor și extensorul lung al halucelui','Tibialul posterior, flexorii degetelor și flexorul lung al halucelui','Solearul și gastrocnemianul, analog compartimentului posterior superficial','Peronierul lung și scurt, analog compartimentului lateral','Flexorul lung al degetelor mâinii, analog tenosinovitei Kanavel'],'A',604,'Sindromul de stres tibial — Compartimentul anterior al recreaționalului',
 'Identificarea triadei anteriorului (tibial anterior, EDL, EHL) la alergătorul recreațional, distinctă de posteriorul profund al competitivului.',
 ['Cei trei mușchi ai compartimentului anterior sunt enumerați explicit.','Triada posteriorului profund este a alergătorului competitiv.','Solearul și gastrocnemianul definesc posteriorul superficial.','Peronierii definesc compartimentul lateral.','Flexorii mâinii țin de tenosinovita Kanavel, nu de gambă.']],
 8,'Schimbă anteriorul recreaționalului cu posteriorul profund al competitivului, cele două topografii din același paragraf.',['compartimentul anterior','extensor lung al halucelui']),

q(122,['Disjuncția acromio-claviculară de gradul II se recunoaște prin:',
 ['Ruptura ligamentului acromioclavicular cu întinderea ligamentelor coracoclaviculare și subluxație claviculară','Radiografii de stres cu greutăți la încheieturi: distanța claviculă–coracoid mai mare pe partea afectată','Clavicula ridicată vizibil deasupra acromionului, cu ruptura ambelor ligamente, analog gradului III','Imobilizarea DIP în extensie 6 săptămâni, analog degetului Mallet','Reducere închisă și gips, analog fracturii boxerului a metacarpianului V'],'AB',607,'Disjuncția acromio-claviculară — Gradul II și radiografiile de stres',
 'Diferențierea gradului II (AC rupt, coracoclaviculare întinse, greutăți la încheieturi) de clavicula ridicată a gradului III.',
 ['Ruptura AC cu întinderea coracoclavicularelor și subluxația definesc gradul II.','Radiografiile de stres cu greutăți și distanța claviculă–coracoid crescută sunt descrise.','Clavicula ridicată deasupra acromionului, cu ambele ligamente rupte, este gradul III.','Cele 6 săptămâni în extensie DIP sunt tratamentul Mallet.','Gipsul boxerului nu evaluează distanța coracoclaviculară.']],
 8,'Confundă gradul II (subluxație la stres) cu gradul III (claviculă ridicată) și cu Mallet/boxer de pe aceeași pagină.',['gradul II','procesul coracoid']),

q(123,['Pentru testul de stres al ligamentului colateral ulnar al MCP-ului policelui, articulația se plasează în:',
 ['Flexie de 35°, pentru a relaxa aponevroza palmară și flexorul scurt al policelui','Extensie completă, analog imobilizării Mallet a IFD','Abducție de 90°, analog luxației anterioare de umăr','Flexie de 90°, analog sertarului anterior al genunchiului','Neutru, fără flexie, pentru a tensiona aponevroza adductorului'],'A',607,'Policele schiorului — Flexia de 35° la testarea UCL',
 'Recunoașterea flexiei de 35° a MCP ca poziție care relaxează aponevroza palmară și FSB, permițând testarea UCL.',
 ['Textul cere 35° de flexie pentru a relaxa aponevroza palmară și flexorul scurt.','Extensia completă este a imobilizării Mallet, nu a testului UCL.','90° de abducție privește mecanismul luxației anterioare de umăr.','90° de flexie este a sertarului anterior al genunchiului.','Relaxarea, nu tensionarea aponevrozei, este scopul flexiei.']],
 8,'Permutează 35° cu 90° (umăr sau genunchi) și cu extensia Mallet, toate unghiuri din capitolul de leziuni sportive.',['35° de','flexor scurt al policelui']),

q(124,['Cele mai comune diformități rotaționale ale piciorului copilului se atribuie uneia dintre trei zone. Sunt adevărate:',
 ['Cele trei zone sunt femurul (anteversie/retroversie), tibia (rotație internă/externă) și antepiciorul (adducția metatarsienelor)','Cea mai frecventă cauză este poziționarea intrauterină; posturile de somn sau șezut pot întârzia rezolvarea','Majoritatea copiilor ating aproape jumătate din dimensiunea de adult în primii 2 ani','Anteversia se evaluează cu copilul în supinație, rotația internă fiind irelevantă','Adducția metatarsienelor se recunoaște printr-o margine laterală concavă, analog genu varum'],'ABC',610,'Torsiunea pediatrică — Trei zone și mulajul intrauterin',
 'Maparea femur–tibie–antepicior, a cauzei intrauterine și a creșterii din primii 2 ani (jumătate din talia adultă).',
 ['Cele trei zone sunt enumerate explicit.','Poziționarea intrauterină ca cea mai frecventă cauză este enunțată.','Jumătatea din statura adultă în primii 2 ani este citată.','Diformitățile de rotație se evaluează mai bine în pronație.','Marginea laterală convexă (nu concavă) semnalează adducția metatarsienelor.']],
 8,'Inversează pronația ca poziție de evaluare și concavitatea marginei laterale, două detalii de semiotica torsiunii.',['poziţionarea in￾trauterină','primii 2 ani'],[611]),

q(125,['Genu varum care persistă peste vârsta de 2 ani poate justifica evaluare radiologică, deoarece cauzele patologice includ:',
 ['Afectarea cartilajului de creștere a metafizei mediale tibiale','Nanismul condrodisplazic','Rahitismul rezistent la vitamina D (hipofosfatemic sau renal)','Varumul fiziologic de 20° al sugarului, care nu s-a corectat încă la 18 luni','Aliniamentul adult de 7° valgus, interpretat ca varum patologic'],'ABC',611,'Diformități angulare — Genu varum patologic',
 'Separarea cauzelor patologice (fiză tibială medială, condrodisplazie, rahitism rezistent) de varumul fiziologic care se corectează la 18 luni.',
 ['Afectarea fizei metafizei mediale tibiale este prima cauză patologică citată.','Nanismul condrodisplazic figurează pe listă.','Rahitismul rezistent la vitamina D este enunțat.','Varumul fiziologic de 20° se corectează la circa 18 luni; persistența peste 2 ani ridică suspiciunea patologică.','7° valgus după 3 ani este aliniamentul adult normal, nu un varum.']],
 8,'Tratează varumul fiziologic și valgusul adult de 7° ca și cauze patologice, ignorând pragul de 2 ani.',['rahitism rezistent','2 ani']),

q(126,['Boala Legg-Calvé-Perthes, dincolo de epidemiologia 4–8 ani și 8/1, se caracterizează prin:',
 ['Evoluție autolimitată, cu durată între 2 și 4 ani','Cele mai importante modificări radiografice în stadiul de revascularizare, când osul nou apare dens (sclerotic)','Tratament inițial prin tracțiune pentru mobilitate, apoi orteze care mențin membrele în abducție','Predilecție feminină 8/1, analog scoliozei idiopatice','Tratament prin ham Pavlik, identic displaziei de dezvoltare a șoldului'],'ABC',614,'Perthes — Istorie naturală 2–4 ani și orteze în abducție',
 'Recunoașterea ferestrei 2–4 ani, a densității maxime la revascularizare și a ortezelor în abducție, distincte de Pavlik și de sex-ratio-ul inversat.',
 ['Durata autolimitată 2–4 ani este explicită.','Stadiul de revascularizare ca moment al modificărilor radiografice maxime, cu os dens, este descris.','Tracțiunea apoi ortezele în abducție sunt enunțate.','Raportul 8/1 este masculin/feminin, nu invers.','Hamul Pavlik este tratamentul DDH precoce, nu al Perthes.']],
 8,'Oglindește sex-ratio-ul 8/1 și înlocuiește ortezele în abducție cu hamul Pavlik al DDH.',['2 şi 4 ani','revascularizare']),

q(127,['Boala Osgood-Schlatter afectează inserția tendonului rotulian pe tuberozitatea tibială. Sunt adevărate:',
 ['Reprezintă o avulsie parțială a tuberozității, soldată cu necroză avasculară a porțiunii avulsionate','Durerea se agravează la îngenunchiere, palpare și alergare; zona proemină și este sensibilă','Este de obicei autolimitată și dispare odată cu închiderea cartilajelor de creștere','Se tratează prin osteotomie tibială de valgizare, analog gonartrozei mediale a adultului tânăr','Fixarea cu multiple șuruburi a capului femural, analog epifiziolizei, este gestul de primă intenție'],'ABC',614,'Osgood-Schlatter — Avulsie a tuberozității tibiale',
 'Recunoașterea avulsiei parțiale cu NAV, a durerii la îngenunchiere și a remisiei la închiderea fizei, versus osteotomia adultului sau șuruburile epifiziolizei.',
 ['Avulsia parțială și necroza porțiunii avulsionate sunt explicite.','Agravarea la îngenunchiere, palpare și sport, cu proeminență sensibilă, este descrisă.','Caracterul autolimitat până la închiderea cartilajelor este enunțat.','Osteotomia tibială privește gonartroza medială a tânărului, nu Osgood-Schlatter.','Șuruburile multiple fixează epifizioliza femurală proximală, nu tuberozitatea.']],
 8,'Mută tratamentul pe osteotomia de genu varum sau pe șuruburile epifiziolizei, două gesturi pediatrice/tinere învecinate.',['Osgood-Schaltter','tuberozităţii tibiale']),

q(128,['Piciorul strâmb congenital (talipes equinovarus) se caracterizează prin:',
 ['Incidență de 1/1.000 nou-născuți, de două ori mai frecvent la băieți, bilateral în 33%','Triada: gleznă în flexie plantară (equinus), retropicior în varus și antepicior în adducție/supinație','Netratat, pacientul calcă pe marginea laterală; mușchii posteriori ai gambei sunt atrofiați și contractați','Incidență de 1,5/1.000, analog displaziei de șold, cu predilecție feminină','Tratament de primă intenție prin ham Pavlik, fără serie de gipsuri'],'ABC',614,'Piciorul varus-equin — Epidemiologie și triada deformării',
 'Aplicarea ratei 1/1.000, a predilecției masculine 2:1, a bilateralității de 33% și a triadei equinus–varus–adductus.',
 ['Incidența, sex-ratio-ul și bilateralitatea de 33% sunt explicite.','Cele trei caracteristici anatomice sunt enumerate.','Călcarea pe marginea laterală și contractura posteriorului sunt descrise.','1,5/1.000 și predilecția feminină țin de DDH, nu de piciorul strâmb.','Tratamentul începe cu corecții gipsate seriate, nu cu ham Pavlik.']],
 8,'Schimbă 1/1.000 masculin cu 1,5/1.000 feminin al DDH și pune Pavlik în locul gipsurilor.',['I/I .OOO','equinus'],[615]),

q(129,['Fasceita necrozantă, dincolo de tipurile 1 și 2, se caracterizează prin:',
 ['Tipul 3 este cauzat de bacterii marine','Scorul LRINEC folosește creșterea leucocitelor, glicemiei, PCR și creatininei și scăderea sodiului și hemoglobinei','La debridare, necroza are aspect purulent de „apă murdară”, cu miros fetid','Tipul 3 este polimicrobian al diabeticului, analog tipului 1','LRINEC se bazează pe hipercalcemie și pe scăderea VSH, analog osteomielitei'],'ABC',618,'Fasceita necrozantă — Tipul 3 marin și scorul LRINEC',
 'Completarea clasificării cu bacteriile marine, cu componentele LRINEC și cu aspectul de apă murdară la debridare.',
 ['Tipul 3 prin bacterii marine este explicit.','Cele șase analize ale LRINEC (creșteri și scăderi) sunt enumerate.','Aspectul de apă murdară fetidă la debridare este descris.','Polimicrobianul imunocompromisului este tipul 1, nu 3.','LRINEC nu folosește calciu sau VSH; VSH-ul urmărește osteomielita.']],
 8,'Confundă tipul 3 marin cu tipul 1 polimicrobian și înlocuiește LRINEC cu markeri de osteomielită.',['bacterii marine','LRINEC']),

q(130,['Artroza trapezo-metacarpiană a policelui și medicația osteoartrozei:',
 ['La mână, artroza afectează uzual articulația trapezo-metacarpiană, cu durere la bază ca o ciupitură','Acetaminofenul s-a dovedit eficient în durerea musculoscheletală; narcoticele cronice trebuie evitate','Injectarea repetată de corticosteroizi poate accelera deteriorarea articulară prin efecte nocive pe metabolismul cartilajului','Glucozamina și condroitin sulfatul au beneficiu dovedit prin studii, înlocuind AINS','Cartilajul articular este bogat inervat, deci durerea artrozică nu poate avea origine periarticulară'],'ABC',619,'Osteoartroza — Trapezo-metacarpiana și injecțiile de steroid',
 'Recunoașterea TMC a policelui, a acetaminofenului și a riscului injecțiilor steroidiene repetate asupra cartilajului.',
 ['Sediul trapezo-metacarpian și durerea de ciupitură sunt explicite.','Eficiența acetaminofenului și evitarea narcoticelor cronice sunt enunțate.','Efectul nociv al steroizilor repețați pe metabolismul cartilajului este citat.','Beneficiul glucozaminei/condroitinei a fost pretins, dar nu dovedit prin studii.','Cartilajul nu are inervație; durerea are originea în structurile periarticulare.']],
 8,'Atribuie suplimentelor un beneficiu dovedit și inervează cartilajul, două mituri din același paragraf de tratament.',['trapezo-metacarpiană','corticosteroizi']),

q(131,['Selectați enunțurile adevărate despre artroplastia parțială, cea totală și artrodeza genunchiului:',
 ['Artroplastia parțială cere un singur compartiment afectat, ligamente încrucișate intacte și mobilitate în limite funcționale','Artroplastia totală reduce durerea în mai mult de 90% din cazuri și se rezervă artrozei avansate cu stil de viață relativ sedentar','Artrodeza este durabilă la tineri foarte activi, cu o articulație izolată (haluce, coloană, gleznă); este contraindicată în artrita inflamatorie sistemică multiplă','Artrodeza articulațiilor mari este indicația de elecție în poliartrita reumatoidă multiplă','Artroplastia parțială se folosește când ambele încrucișate sunt rupte și toate trei compartimentele sunt uzate'],'ABC',620,'Gonartroza — Unicompartimentală, totală și artrodeză',
 'Contrastarea criteriilor unicompartimentale, a ratei >90% a TKA la sedentar și a artrodezei tânărului activ, contraindicată în boala inflamatorie multiplă.',
 ['Cele trei condiții ale artroplastiei parțiale sunt explicite.','Rata de peste 90% și rezervarea la artroză avansată sedentară sunt citate.','Indicația tânăr activ cu articulație izolată și contraindicația în artrita inflamatorie multiplă sunt enunțate.','Artrodeza marilor articulații este contraindicată tocmai în artrita inflamatorie sistemică multiplă.','Încrucișatele intacte și un singur compartiment sunt cerințe, nu contraindicații inversate.']],
 8,'Oglindește contraindicația artrodezei în PR multiplă și cere parțiala tocmai când încrucișatele și toate compartimentele sunt compromise.',['90% din cazuri','Artrodeza']),

q(132,['Hernia de disc cervicală: cele mai frecvente rupturi și rădăcinile corespunzătoare din tabelul 28-5:',
 ['Cele mai frecvente rupturi sunt la C5–C6 și C6–C7, unde flexia-extensia este cea mai amplă','Rădăcina C6: hipoestezie față laterală antebraț și palmară police, slăbire a extensiei pumnului, diminuare reflex brahioradial','Rădăcina C7: hipoestezie degetul 3, slăbire extensie degete și triceps, diminuare reflex tricipital','Rădăcina C6 slăbește deltoidul și bicepsul, cu diminuarea reflexului bicipital, analog C5','Rădăcina C7 se recunoaște prin hipoestezie pe degetul 5 și slăbirea flexiei degetelor, analog C8'],'ABC',626,'Discul cervical — C5–C6/C6–C7 și rădăcinile C6, C7',
 'Maparea predilecției C5–C6 și C6–C7 pe rădăcinile C6 (police, extensie pumn, BR) și C7 (deget 3, triceps).',
 ['Interspațiile C5–C6 și C6–C7 ca cele mai frecvente sunt explicite.','Triada senzitiv-motor-reflex a C6 din tabel este citată.','Triada C7 (deget 3, extensie degete/triceps, tricipital) este enunțată.','Deltoid, biceps și bicipital definesc C5, nu C6.','Degetul 5 și flexia degetelor definesc C8, nu C7.']],
 8,'Permutează C6 cu C5 (biceps) și C7 cu C8 (degetul 5), capcane clasice de radiculopatie cervicală.',['C5-C6','reflex brahioradial']),

q(133,['Implicarea coloanei cervicale în artrita reumatoidă urmează, de obicei, unul dintre trei modele:',
 ['Sinovita atlas–odontoid întinde ligamentul transvers, cu subluxație atlanto-axială (C1–C2) în flexie și comprimarea măduvei de dintele deplasat posterior','Sinovita erozivă atlas–condil occipital cauzează impactare occipito-atlanto-axială, cu protruzia odontoidului în foramen magnum','Sinovita fațetelor sub axis produce instabilitate de segment (subluxație subaxială), vizibilă pe laterala cu înclinare sau deplasare AP','Cele trei modele se exclud reciproc de impactarea odontoidului, care protejează canalul','Subluxația C1–C2 apare caracteristic în extensie, ligamentul transvers rămânând intact'],'ABC',626,'Artrita reumatoidă cervicală — Cele trei modele de instabilitate',
 'Recunoașterea triadei C1–C2 (ligament transvers), impactare occipito-atlanto-axială și subluxație subaxială.',
 ['Mecanismul ligamentului transvers și al dintelui posterior este explicit.','Impactarea cu odontoidul în foramen magnum este descrisă.','Subluxația subaxială pe laterala cu înclinare/deplasare este enunțată.','Cele trei modele coexistă ca tipare posibile; impactarea comprimă, nu protejează.','Subluxația atlanto-axială este de obicei în flexie.']],
 8,'Inversează flexia C1–C2 cu extensia și tratează impactarea odontoidului ca protectoare a măduvei.',['atlanto-axiale','foramen magnum'],[627]),

q(134,['Primele manifestări clinice ale osteoporozei involutive includ frecvent fracturi prin compresie vertebrală și fracturi de:',
 ['Femur proximal (șold), humerus și radius distal (Colles)','Scafoid, analog tabacherei anatomice a tânărului','Olecran prin avulsia tricepsului','Platou tibial impactat de energie redusă, analog metafizei copilului','Diafiză femurală de mare energie, analog politraumatismului'],'A',627,'Osteoporoza — Primele fracturi de fragilitate',
 'Identificarea triadei șold–humerus–Colles, alături de vertebre, ca prime manifestări ale osteoporozei involutive.',
 ['Textul enumeră corpii vertebrali, femurul proximal, humerusul și radiusul distal (Colles) ca prime manifestări.','Scafoidul este fractura tânărului prin FOOSH, nu prima manifestare osteoporotică din listă.','Olecranul este o cădere pe cot, nu exemplul de fragilitate.','Platoul tibial impactat este un exemplu de fractură metafizară, nu lista osteoporozei.','Diafiza femurală cere energie mare la tineri, opusul fragilității.']],
 8,'Înlocuiește triada șold–humerus–Colles cu scafoid, olecran sau diafiză de mare energie, toate din același capitol de traumatologie.',['humerusului','Colles']),

q(135,['Rahitismul, forma pediatrică a osteomalaciei, se recunoaște radiografic prin:',
 ['Cartilaje de creștere anormal de largi și metafize în formă de cupă; oasele lungi moi pot fi încurbate','Zone Looser ca primă imagine, fără lărgirea fizei','Spiculi „raze de soare” metafizari, analog osteosarcomului','Aspect de „bulb de ceapă” diafizar, analog sarcomului Ewing','Pensare localizată, osteofite și chiste subcondrale, analog osteoartrozei'],'A',628,'Rahitismul — Fize largi și metafize în cupă',
 'Diferențierea imaginii de rahitism (fiză largă, metafiză în cupă, oase încurbate) de Looser-ul adultului, de tumorile din tabelul 28-9 și de OA.',
 ['Lărgirea cartilajelor de creștere, metafizele în cupă și încurbarea oaselor moi sunt explicite.','Zona Looser este caracteristica adultului cu osteomalacie, cel mai des la col femural sau ramuri pubiene.','Razele de soare definesc osteosarcomul.','Bulbul de ceapă definește Ewing-ul.','Cele patru semne radiologice OA nu descriu rahitismul.']],
 8,'Mută imaginea de rahitism pe Looser, raze de soare sau bulb de ceapă, trei pattern-uri radiologice din același capitol.',['formă de cupă','cartilaje de creştere']),
];
