import {rewriter} from './rewrite-author';
import {RETIRED_PANCREAS} from './retired/pancreas';

// Rewritten after the 2026-09-24 cue audit (Lawrence, cap. 17, p. 257–275).
const q=rewriter(RETIRED_PANCREAS,(p:number)=>p-89,{shuffle:true});

export const PANCREAS_V2=[
q('pancreas-adv-007',['Pancreasul:',
 ['este un organ retroperitoneal','are procesul uncinat ca prelungire a capului','are coada extinsă spre hilul splinei','are corpul situat la stânga VMS','are istmul situat la stânga VMS'],'ABCD',257,'Anatomie',
 'Recunoașterea raporturilor celor patru părți ale pancreasului.',
 ['Pancreasul este un organ retroperitoneal.','Procesul uncinat este o prelungire posterioară și inferioară a capului.','Coada se extinde spre hilul splinei.','Corpul se întinde la stânga VMS.','Nu: istmul este situat imediat deasupra VMS; corpul este la stânga ei.']],
 [8,'Distractorul mută istmul în poziția corpului.'],['organ retroperitoneal','potcoava duodenală']),
q('pancreas-adv-084',['Vena mezenterică superioară marchează joncțiunea dintre:',
 ['capul și istmul pancreatic','istmul și corpul pancreatic','corpul și coada pancreatică','procesul uncinat și restul capului','coada și hilul splenic'],'A',257,'Anatomie',
 'Folosirea VMS ca reper între cap și istm.',
 ['VMS marchează joncțiunea dintre cap și istm.','Nu: corpul se întinde la stânga VMS, iar istmul stă deasupra ei.','Nu: coada este porțiunea cea mai distală, spre splină.','Nu: uncinatul este o prelungire a capului, fără reper venos citat.','Nu: coada se extinde spre hilul splinei.']],
 [8,'Distractorii mută reperul pe alte joncțiuni.'],['marchează joncţiunea','capul şi istmul']),
q('pancreas-adv-008',['Embriologia pancreasului:',
 ['mugurii apar la 30 de zile de gestație','ductele fuzionează în săptămâna a 8-a','mugurele dorsal devine procesul uncinat','mugurele ventral se rotește în sens antiorar','mugurii rămân separați până în săptămâna 12'],'AB',257,'Embriologie',
 'Cronologia formării și fuziunii mugurilor pancreatici.',
 ['La 30 de zile, endodermul duodenal formează mugurii ventral și dorsal.','În săptămâna a 8-a, parenchimul și ductele fuzionează.','Nu: mugurele ventral devine procesul uncinat.','Nu: mugurele ventral se rotește în sensul acelor de ceasornic.','Nu: până în săptămâna a 6-a mugurii sunt deja alipiți.']],
 [8,'Distractorii inversează mugurii, sensul rotației și cronologia.'],['30 de zile de gestaţie','sensul acelor de ceasornic']),
q('pancreas-adv-009',['Pancreasul divisum:',
 ['apare la aproximativ 10% din populație','este asimptomatic la 90% dintre pacienți','drenează corpul și coada prin papila mare','rezultă din rotirea incompletă a mugurelui ventral','are orificiul papilei secundare prea larg'],'AB',257,'Embriologie',
 'Frecvența și mecanismul pancreasului divisum.',
 ['Aproximativ 10% au ducte ventral și dorsal nefuzionate complet.','90% dintre pacienții cu pancreas divisum sunt asimptomatici.','Nu: pancreasul dorsal drenează prin canalul accesor Santorini.','Nu: rotirea incompletă a mugurelui ventral produce pancreasul inelar.','Nu: orificiul ductului secundar este prea mic pentru volumul secreției.']],
 [8,'Distractorii confundă divisum cu pancreasul inelar și inversează papilele.'],['pancreas divisum','asimptomatici']),
q('pancreas-adv-010',['Pancreasul inelar care obstruează duodenul se tratează prin:',
 ['duodeno-jejunostomie de șuntare','secționarea inelului pancreatic','duodenopancreatectomie cefalică','sfincterotomie endoscopică','gastrojejunostomie cu vagotomie'],'A',258,'Embriologie',
 'Tratamentul pancreasului inelar fără secționarea parenchimului.',
 ['Tratamentul este șuntarea chirurgicală (duodeno-jejunostomie).','Nu: secționarea parenchimului are o rată mare de fistule.','Nu: nu este tratamentul citat.','Nu: obstrucția este duodenală, nu papilară.','Nu: nu este tratamentul citat.']],
 [8,'Distractorul principal este secționarea inelului, evitată în text.'],['Pancreasul inelar','duodeno-jejunostomie']),
q('pancreas-adv-011',['Variațiile arteriale relevante în chirurgia pancreatică:',
 ['artera hepatică dreaptă lipsește la ~20%','lobul drept poate fi irigat din AMS','hepatica stângă provine la 20% din gastrica stângă','vasele din AMS se pot leza în Whipple','hepatica dreaptă din AMS apare sub 1%'],'ABCD',258,'Vascularizație',
 'Recunoașterea variațiilor arteriale hepatice cu risc în duodenopancreatectomie.',
 ['Artera hepatică dreaptă lipsește la aproximativ 20% din populație.','Lobul drept este irigat atunci de o arteră hepatică dreaptă din AMS.','La 20%, artera hepatică stângă provine din artera gastrică stângă.','Vasele din AMS pot fi lezate în duodenopancreatectomie dacă nu sunt identificate.','Nu: variația apare la aproximativ 20% din populație.']],
 [8,'Distractorul subestimează frecvența variației.'],['arteră hepatică dreaptă din AMS','artera gastrică stângă']),
q('pancreas-adv-085',['Vascularizația arterială a pancreasului:',
 ['capul primește sânge prin artera gastroduodenală','corpul și coada primesc ramuri din artera splenică','trunchiul celiac dă artera hepatică comună','artera pancreatică dorsală provine din AMI','arcadele superioare provin din artera colică medie'],'ABC',258,'Vascularizație',
 'Sursele arteriale ale capului, corpului și cozii pancreatice.',
 ['Capul și duodenul sunt irigate prin artera gastroduodenală.','Corpul și coada primesc ramurile pancreatice ale arterei splenice.','Trunchiul celiac se trifurcă în gastrica stângă, splenica și hepatica comună.','Nu: artera pancreatică dorsală are adesea originea în AGD.','Nu: arcadele pancreaticoduodenale superioare provin din AGD.']],
 [8,'Distractorii mută originea vaselor pe artere din alte teritorii.'],['arterei gastroduodenale','ramurile pancreatice ale arterei splenice']),
q('pancreas-adv-041',['Artera mezenterică superioară:',
 ['se situează imediat posterior de pancreas','dă ca primă ramură pancreaticoduodenala inferioară','trece posterior de procesul uncinat','ia naștere din peretele posterior al aortei','vascularizează colonul descendent'],'AB',258,'Vascularizație',
 'Traiectul AMS și prima sa ramură.',
 ['AMS se situează imediat posterior de pancreas.','Prima ramură este artera pancreaticoduodenală inferioară.','Nu: trece anterior și medial de procesul uncinat.','Nu: ia naștere din peretele anterior al aortei.','Nu: irigă intestinul subțire, colonul drept și transversul.']],
 [8,'Distractorii inversează raporturile anterior–posterior.'],['imediat posterior de pancreas','artera pancreaticoduodenală inferioară']),
q('pancreas-adv-028',['Arcadele pancreaticoduodenale se formează prin anastomoza:',
 ['pancreaticoduodenalelor superioare și inferioare','arterei splenice cu artera gastrică stângă','AMS cu artera mezenterică inferioară','arterei hepatice proprii cu artera cistică','gastroepiploicei drepte cu artera colică medie'],'A',258,'Vascularizație',
 'Anastomoza celiaco-mezenterică din jurul capului pancreatic.',
 ['Ramurile inferioare din AMS se anastomozează cu omonimele superioare din AGD.','Nu: nu este anastomoza citată.','Nu: colateralele AMS–AMI sunt descrise separat, nu ca arcade.','Nu: nu este anastomoza citată.','Nu: nu este anastomoza citată.']],
 [8,'Distractorii propun anastomoze din alte teritorii.'],['pancreaticoduodenale superioare','se anastomozează']),
q('pancreas-adv-034',['Artera pancreatică dorsală:',
 ['interconectează trunchiul celiac și AMS','este o arteră terminală, fără colaterale','provine constant din artera mezenterică inferioară','irigă în principal capul pancreatic','se anastomozează cu artera renală stângă'],'A',260,'Vascularizație',
 'Rolul colateral al arterei pancreatice dorsale.',
 ['Interconectează trunchiul celiac și AMS în mai multe locuri.','Nu: are rol de colaterală.','Nu: poate avea origini diferite, adesea AGD.','Nu: participă la irigarea corpului și cozii.','Nu: nu este anastomoza citată.']],
 [8,'Distractorii o transformă în arteră terminală.'],['Artera pancreatică dorsală','interconecta']),
q('pancreas-adv-069',['Secreția exocrină pancreatică:',
 ['are un volum zilnic de 500–800 mL','are Na+ și K+ egale cu plasma','are clorul invers proporțional cu bicarbonatul','este un fluid acid, hiperton','are un volum zilnic de 50–80 mL'],'ABC',260,'Fiziologie',
 'Compoziția și volumul sucului pancreatic.',
 ['Pancreasul secretă zilnic 500–800 mL.','Sodiul și potasiul au concentrații egale cu plasma.','Clorul variază invers proporțional cu bicarbonatul.','Nu: este un fluid alcalin izoton.','Nu: volumul este 500–800 mL.']],
 [8,'Distractorii inversează pH-ul și volumul.'],['fluid alcalin izoton','invers proporţional']),
q('pancreas-adv-042',['Secretina:',
 ['este eliberată de mucoasa duodenală','crește secreția de bicarbonat','este eliberată la pH duodenal peste 8','contractă vezicula biliară','inhibă secreția de bicarbonat pancreatic'],'AB',260,'Fiziologie',
 'Stimulul și efectul secretinei.',
 ['Mucoasa duodenală eliberează secretina.','Secretina stimulează un lichid bogat în bicarbonat.','Nu: stimulul este acidul gastric cu pH <3.','Nu: contracția veziculei este efectul CCK.','Nu: o stimulează.']],
 [8,'Distractorii inversează stimulul și confundă cu CCK.'],['secretinei','bogat în bicarbonat']),
q('pancreas-adv-012',['Colecistokinina (CCK):',
 ['este eliberată de acizii grași liberi','stimulează contracția veziculei biliare','stimulează secreția enzimelor pancreatice','stimulează puternic bicarbonatul','este eliberată de mucoasa gastrică la pH <3'],'ABC',260,'Fiziologie',
 'Stimulii și efectele CCK.',
 ['Peptidele, aminoacizii și acizii grași liberi eliberează CCK.','CCK stimulează contracția veziculei biliare.','Secreția enzimelor este stimulată de CCK, acetilcolină, VIP și secretină.','Nu: CCK stimulează slab producția de bicarbonat.','Nu: CCK este duodenală; acidul duodenal eliberează secretina.']],
 [8,'Distractorii atribuie CCK efectele secretinei.'],['Colecistokinina','contracţia veziculei biliare']),
q('pancreas-adv-043',['Singura enzimă pancreatică secretată în formă activă este:',
 ['amilaza','tripsina','chimotripsina','elastaza','fosfolipaza'],'A',260,'Fiziologie',
 'Excepția amilazei printre enzimele pancreatice.',
 ['Amilaza este singura enzimă secretată în forma activă.','Nu: se secretă ca tripsinogen.','Nu: se secretă ca chimotripsinogen.','Nu: se secretă ca precursor inactiv.','Nu: se secretă ca precursor inactiv.']],
 [8,'Distractorii sunt enzime secretate ca precursori.'],['Amilaza reprezintă','precursori inactivi']),
q('pancreas-adv-070',['Insulele Langerhans:',
 ['sunt mai abundente în coada pancreatică','conțin celule α care secretă glucagon','sunt mai abundente în capul pancreatic','conțin celule α care secretă insulină','nu produc somatostatină sau polipeptid pancreatic'],'AB',261,'Fiziologie',
 'Distribuția insulelor și rolul celulelor α.',
 ['Insulele sunt mai abundente la nivelul cozii.','Celulele α secretă glucagon la glicemie scăzută.','Nu: predomină în coadă.','Nu: celulele α secretă glucagon.','Nu: insulele produc și somatostatină și PP.']],
 [8,'Distractorii inversează localizarea și hormonul.'],['Insulele sunt mai abundente','glucagonul']),
q('pancreas-adv-001',['Diagnosticul de pancreatită acută după clasificarea Atlanta:',
 ['cere cel puțin două dintre trei criterii','poate folosi amilaza sau lipaza crescută','cere constant confirmare prin CT','cere îndeplinirea tuturor celor trei criterii','este exclus de un CT normal'],'AB',262,'Pancreatita acută',
 'Aplicarea regulii „două din trei” din clasificarea Atlanta.',
 ['Diagnosticul este cert la cel puțin două din trei criterii.','Amilazele sau lipazele crescute sunt unul dintre criterii.','Nu: CT-ul este doar unul dintre criterii.','Nu: sunt suficiente două criterii.','Nu: clinica și enzimele pot stabili diagnosticul.']],
 [8,'Distractorii fac din CT un criteriu indispensabil.'],['cel puţin două','Clasificarea Atlanta']),
q('pancreas-adv-046',['Conform Tabelului 17-1, pancreatita acută:',
 ['ușoară nu are complicații locale sau sistemice','moderată are insuficiență de organ sub 48 h','severă are insuficiență multiplă de organ persistentă','moderată are necroză pancreatică infectată','ușoară are insuficiență de organ tranzitorie'],'ABC',262,'Pancreatita acută',
 'Gradele de severitate din clasificarea Atlanta.',
 ['Forma ușoară nu are complicații locale sau sistemice.','Forma moderată are insuficiență de organ tranzitorie, sub 48 h.','Forma severă are MSOF persistentă.','Nu: necroza infectată ține de forma severă.','Nu: insuficiența tranzitorie definește forma moderată.']],
 [8,'Distractorii mută criteriile între grade.'],['Fără complicaţii locale','Insuficienţă de organ tranzitorie']),
q('pancreas-adv-014',['Etiologia pancreatitei acute:',
 ['alcoolul și litiaza explică ~85% din cazuri','primul episod etanolic urmează 6–8 ani de consum','~60% dintre neconsumatori au calculi biliari','post-ERCP apare la 1–5% dintre pacienți','formele idiopatice reprezintă 40–50%'],'ABCD',262,'Pancreatita acută',
 'Ponderea cauzelor pancreatitei acute.',
 ['Alcoolul și calculii biliari explică aproximativ 85%.','Primul episod este precedat de 6–8 ani de consum excesiv.','60% dintre pacienții care nu consumă alcool au calculi biliari.','Pancreatita post-ERCP apare la 1–5%.','Nu: formele idiopatice sunt 8–10%.']],
 [8,'Distractorul supraestimează formele idiopatice.'],['aproximativ 85%','6-8 ani de consum excesiv']),
q('pancreas-adv-071',['Conform Tabelului 17-2, cauze de pancreatită acută sunt:',
 ['hipertrigliceridemia','veninul de scorpion','virusul Coxsackie B','hipocalcemia de orice cauză','hipotiroidismul'],'ABC',263,'Pancreatita acută',
 'Cauzele metabolice și infecțioase din Tabelul 17-2.',
 ['Hipertrigliceridemia este cauză metabolică.','Veninul de scorpion este cauză metabolică.','Virusul Coxsackie B este cauză infecțioasă.','Nu: cauza citată este hipercalcemia.','Nu: nu este cauza citată.']],
 [8,'Distractorul principal inversează calcemia.'],['veninul de scorpion','hipertrigliceridemia']),
q('pancreas-adv-045',['Tabloul clinic al pancreatitei acute:',
 ['durere epigastrică constantă, cu iradiere posterioară','durere atenuată de poziția șezândă','poate asocia ileus adinamic cu distensie','asociază greață și vărsături','durere colicativă, cu iradiere în umăr'],'ABCD',263,'Pancreatita acută',
 'Caracterele durerii din pancreatita acută.',
 ['Durerea este severă, constantă, necolicativă, cu iradiere posterioară.','Poziția șezândă sau ortostatismul o pot atenua.','Unii pacienți dezvoltă ileus adinamic cu distensie.','Durerea se asociază cu greață și vărsături.','Nu: durerea este necolicativă și iradiază posterior.']],
 [8,'Distractorul descrie durerea biliară colicativă.'],['ortostatism','ileus adinamic']),
q('pancreas-adv-015',['Semnul Cullen reprezintă:',
 ['echimoza periombilicală','hematomul pe flancuri','echimoza mastoidiană','icterul sclerelor','echimoza periorbitală'],'A',263,'Pancreatita acută',
 'Distincția dintre semnele Cullen și Grey Turner.',
 ['Echimoza periombilicală este semnul Cullen.','Nu: hematomul pe flancuri este semnul Grey Turner.','Nu: ține de fractura bazei craniului.','Nu: nu este semnul citat.','Nu: ține de fractura bazei craniului.']],
 [8,'Distractorul principal este semnul Grey Turner.'],['semnul Cullen','semnul Grey Turner']),
q('pancreas-adv-002',['Interpretată separat, creșterea amilazei de 3 ori peste normal are:',
 ['specificitate 95%, sensibilitate 61%','sensibilitate 95%, specificitate 61%','specificitate 61%, sensibilitate 39%','sensibilitate și specificitate de 95%','specificitate 80%, sensibilitate 95%'],'A',263,'Pancreatita acută',
 'Performanța diagnostică a amilazei izolate.',
 ['Specificitatea este 95%, sensibilitatea 61%.','Nu: valorile sunt inversate.','Nu: specificitatea este 95%.','Nu: sensibilitatea este doar 61%.','Nu: sensibilitatea de 95% ține de asocierea amilază ×1,5 plus lipază ×5.']],
 [8,'Distractorii inversează sau combină cifrele.'],['specificitate de 95%','creşterea de 3 ori']),
q('pancreas-adv-030',['Amilaza serică în pancreatita acută:',
 ['crește rapid în primele 12 ore','revine de obicei la normal în 3–5 zile','crește și în sarcina ectopică','rămâne crescută câteva săptămâni','este criteriu Ranson de severitate'],'ABC',263,'Pancreatita acută',
 'Cinetica și specificitatea amilazei.',
 ['Amilaza crește rapid în primele 12 ore.','Revine de obicei la normal în 3–5 zile.','Sarcina ectopică apare în Tabelul 17-3 al hiperamilazemiilor.','Nu: revine la normal în 3–5 zile.','Nu: amilaza nu este inclusă în criteriile Ranson.']],
 [8,'Distractorii prelungesc cinetica și o includ în Ranson.'],['primele 12 ore','Sarcină ectopică']),
q('pancreas-adv-087',['Diagnosticul diferențial al pancreatitei acute include:',
 ['ulcerul peptic perforat','ischemia acută mezenterică','infarctul miocardic','perforația esofagiană','hernia hiatală de alunecare'],'ABCD',263,'Pancreatita acută',
 'Afecțiunile citate în diagnosticul diferențial.',
 ['Ulcerul peptic perforat este citat.','Ischemia acută mezenterică este citată.','Infarctul miocardic este citat.','Perforația esofagiană este citată.','Nu: nu este citată în diagnosticul diferențial.']],
 [8,'Distractorul este o afecțiune epigastrică necitată.'],['ischemia acută mezenterică','perforaţia esofagiană']),
q('pancreas-adv-072',['SIRS din pancreatita acută severă poate produce:',
 ['injurie renală acută','sindrom de detresă respiratorie','hipocalcemie','hiperglicemie','hipercalcemie'],'ABCD',263,'Pancreatita acută',
 'Consecințele sistemice ale SIRS în pancreatita severă.',
 ['Injuria renală acută este citată.','ARDS este citat.','Hipocalcemia este citată.','Hiperglicemia este citată.','Nu: apare hipocalcemia.']],
 [8,'Distractorul inversează calcemia.'],['injuria renală acută','hipocalcemie']),
q('pancreas-adv-035',['Explorarea radiologică inițială în pancreatita acută suspectată:',
 ['radiografia toracică exclude pneumoperitoneul','radiografia abdominală poate arăta calcificări','ecografia caută litiaza biliară','CT-ul este necesar pentru diagnostic la toți','ecografia este ideală la pacienții obezi'],'ABC',263,'Pancreatita acută',
 'Rolul radiografiilor și ecografiei înaintea CT.',
 ['Radiografia toracică exclude pneumoperitoneul.','Radiografia abdominală arată calcificări de pancreatită cronică.','Ecografia identifică litiaza și dilatarea ductului comun.','Nu: CT-ul nu este de obicei necesar pentru diagnostic.','Nu: ecografia are valoare limitată la obezi.']],
 [8,'Distractorii fac CT-ul obligatoriu și ignoră limitele ecografiei.'],['pneumoperitoneului','meteorism']),
q('pancreas-adv-039',['Necroza pancreatică pe CT:',
 ['apare ca țesut care nu captează contrastul','nu este prin ea însăși indicație operatorie','este vizibilă de obicei din prima zi','impune necrectomie în primele 72 de ore','apare la majoritatea pacienților'],'AB',263,'Pancreatita acută',
 'Semnificația necrozei pe CT.',
 ['Necroza este țesutul care nu captează contrastul i.v.','Majoritatea pacienților cu necroză se recuperează fără operație.','Nu: apare cel mai frecvent la zile sau săptămâni.','Nu: diagnosticul radiologic nu este indicație chirurgicală.','Nu: necroza apare la aproximativ 20%.']],
 [8,'Distractorii fac din necroză o indicație operatorie precoce.'],['nu captează substanţa de contrast','se vor recupera']),
q('pancreas-adv-003',['Criteriile Ranson:',
 ['includ cinci variabile măsurate la internare','indică forma severă la trei sau mai multe criterii','includ amilaza și lipaza serică','se evaluează integral în primele 6 ore','indică forma severă de la un singur criteriu'],'AB',264,'Pancreatita acută',
 'Structura și pragul criteriilor Ranson.',
 ['Cinci variabile sunt măsurate la internare.','Trei sau mai multe criterii indică pancreatita severă.','Nu: amilaza și lipaza nu sunt incluse.','Nu: șase variabile se măsoară în următoarele 48 de ore.','Nu: pragul este de trei criterii.']],
 [8,'Distractorii includ enzimele și scurtează intervalul.'],['Cinci variabile','trei sau mai multe criterii']),
q('pancreas-adv-047',['Conform Tabelului 17-4, în pancreatita non-biliară, criteriile Ranson includ:',
 ['vârsta la internare >55 de ani','leucocite >16.000/mm³','sechestrarea de fluide >6 L','glicemia >300 mg/dl','creșterea BUN >2 mg/dl'],'ABC',264,'Pancreatita acută',
 'Pragurile Ranson în forma non-biliară.',
 ['Vârsta >55 de ani (non-biliar).','Leucocite >16.000.','Sechestrarea de fluide >6 L.','Nu: pragul este >200 mg/100 ml.','Nu: pragul non-biliar este >5 mg/dl; >2 mg/dl este biliar.']],
 [8,'Distractorii folosesc pragul biliar sau o valoare greșită.'],['Sechestrare de fluide','Scădere hematocrit']),
q('pancreas-adv-048',['Tratamentul medical al pancreatitei acute:',
 ['include repaus alimentar până la dispariția durerii','cere resuscitare volemică în formele severe','monitorizează funcția respiratorie prin pulsoximetrie','urmărește diametrul VCI ecocardiografic','folosește aprotinina, cu beneficiu dovedit'],'ABCD',264,'Pancreatita acută',
 'Măsurile suportive în pancreatita acută.',
 ['Repausul alimentar continuă până la dispariția durerii.','Formele severe pot cere câțiva litri de soluție izotonă.','Funcția respiratorie este monitorizată prin pulsoximetru.','Ecocardiografia evaluează diametrul venei cave inferioare.','Nu: inhibitorii enzimatici nu au demonstrat beneficiu.']],
 [8,'Distractorul atribuie beneficiu aprotininei.'],['repaus alimentar','pulsoximetrului']),
q('pancreas-adv-004',['Antibioticele în pancreatita acută:',
 ['nu sunt indicate profilactic în formele ușoare','profilactice nu modifică mortalitatea în formele severe','sunt importante odată ce infecția este identificată','profilactice modifică tiparele de rezistență','sunt indicate profilactic în necroza sterilă'],'ABCD',265,'Pancreatita acută',
 'Locul antibioticelor profilactice și terapeutice.',
 ['Profilaxia nu este indicată în formele ușoare și moderate.','În formele severe nu modifică mortalitatea.','Antibioticele sunt importante după identificarea infecției.','Profilaxia modifică tiparele de rezistență ale germenilor.','Nu: nu este indicată nici în necroza sterilă.']],
 [8,'Distractorul extinde profilaxia la necroza sterilă.'],['profilaxia antibiotică','necroză sterilă']),
q('pancreas-adv-049',['Suportul nutrițional în pancreatita acută severă:',
 ['preferă nutriția enterală precoce','preferă nutriția parenterală totală precoce','preferă alimentația nazojejunală celei nazogastrice','amână orice alimentare până la normalizarea amilazei','contraindică sonda nazogastrică de alimentare'],'A',265,'Pancreatita acută',
 'Alegerea căii de nutriție.',
 ['Nutriția enterală precoce este preferabilă.','Nu: parenterala se rezervă tractului nefuncțional.','Nu: nu există diferențe între cele două.','Nu: suportul trebuie asigurat formelor severe.','Nu: calea nazogastrică este echivalentă.']],
 [8,'Distractorii inversează preferința enterală.'],['Nutriţia enterală precoce','nazojejunală']),
q('pancreas-adv-050',['Pancreatita acută biliară ușoară sau moderată:',
 ['impune colecistectomie în cursul internării','recidivează la ~50% fără colecistectomie','se tratează prin colecistectomie în primele 24 de ore','recidivează la ~50% după colecistectomie','impune ERCP de rutină la toți pacienții'],'AB',265,'Pancreatita acută',
 'Momentul colecistectomiei și beneficiul ei.',
 ['Colecistectomia se face în internarea curentă, după remisiune.','Riscul unui nou episod este de ~50% fără colecistectomie.','Nu: se face după remisiunea simptomelor.','Nu: colecistectomia scade riscul la ~5%.','Nu: ERCP se face la litiază coledociană sau colangită.']],
 [8,'Distractorii grăbesc operația și inversează riscul.'],['de la aproximativ 50%','colecis']),
q('pancreas-adv-052',['Necroza pancreatică infectată:',
 ['apare la ~5% dintre pacienții cu necroză','este principala cauză de mortalitate','apare de obicei la 2–3 săptămâni','are mortalitate care poate depăși 40%','apare la ~50% dintre pacienții cu necroză'],'ABCD',265,'Pancreatita acută',
 'Frecvența, momentul și gravitatea necrozei infectate.',
 ['Doar ~5% dintre pacienții cu necroză dezvoltă infecție.','Necroza infectată este principala cauză de mortalitate.','Infecția apare de obicei la 2–3 săptămâni.','Mortalitatea poate depăși 40%.','Nu: infecția apare la ~5%.']],
 [8,'Distractorul supraestimează rata infecției.'],['principala cauză de mortalitate','2-3 săptămâni']),
q('pancreas-adv-073',['Diagnosticul necrozei pancreatice infectate:',
 ['CT arată aer retroperitoneal sau în bursa omentală','poate folosi puncția aspirativă ghidată CT','este exclus de absența aerului retroperitoneal','nu necesită culturi pentru fungi','se confirmă prin nivelul amilazei serice'],'AB',266,'Pancreatita acută',
 'Semnele CT și rolul puncției în necroza infectată.',
 ['Aerul retroperitoneal sau din bursa omentală sugerează infecția.','Puncția ghidată CT este utilă la suspiciune mare.','Nu: unele microorganisme nu produc aer.','Nu: lichidul se trimite și pentru fungi.','Nu: nu este metoda citată.']],
 [8,'Distractorii fac din aer un criteriu obligatoriu.'],['bursei omentale','inclusiv pentru fungi']),
q('pancreas-adv-065',['Tratamentul necrozei pancreatice infectate:',
 ['include debridare și drenaj larg','folosește proceduri endoscopice și minim invazive','rezervă necrectomia deschisă eșecurilor','se limitează la antibioterapie, fără drenaj','are necrectomia deschisă ca primă intenție'],'ABC',266,'Pancreatita acută',
 'Abordul în trepte al necrozei infectate.',
 ['Sunt necesare debridări, drenaje largi și antibiotice.','Procedurile endoscopice și minim invazive au scăzut morbiditatea.','Necrectomia deschisă se rezervă eșecului metodelor conservatoare.','Nu: sunt necesare debridarea și drenajul.','Nu: necrectomia deschisă este de ultimă intenție.']],
 [8,'Distractorii renunță la drenaj sau revin la necrectomia deschisă.'],['minim invazive','Necrectomia deschisă']),
q('pancreas-adv-051',['Tromboza venei splenice sau porte după pancreatita acută severă:',
 ['poate determina varice gastrice mari','se tratează prin splenectomie când varicele sângerează','produce în principal varice esofagiene','se tratează definitiv prin șunt portosistemic','nu poate produce ischemie mezenterică'],'AB',265,'Pancreatita acută',
 'Hipertensiunea portală stângă după pancreatită.',
 ['Hipertensiunea portală stângă produce varice gastrice mari.','Splenectomia este tratamentul definitiv al varicelor hemoragice.','Nu: varicele citate sunt gastrice.','Nu: tratamentul definitiv este splenectomia.','Nu: tromboza portală poate produce ischemie mezenterică acută.']],
 [8,'Distractorii confundă cu hipertensiunea portală sistemică.'],['varice gastrice mari','splenectomie']),
q('pancreas-adv-074',['Colecțiile lichidiene peripancreatice:',
 ['sunt cea mai frecventă complicație','se resorb spontan în majoritatea cazurilor','pot evolua spre pseudochist în 3–4 săptămâni','au perete epitelial încă de la debut','impun drenaj extern în majoritatea cazurilor'],'ABC',266,'Pancreatita acută',
 'Evoluția colecțiilor peripancreatice.',
 ['Sunt cea mai frecventă complicație a pancreatitei acute.','Cele mai multe se resorb spontan.','Cele persistente formează pseudochist în 3–4 săptămâni.','Nu: sunt delimitate de viscere și țesut inflamator.','Nu: majoritatea se resorb.']],
 [8,'Distractorii le dau perete epitelial și indicație de drenaj.'],['cea mai frecventă complicaţie','se resorb spontan']),
q('pancreas-adv-018',['Pseudochistul pancreatic:',
 ['nu are strat epitelial în perete','poate comunica cu ductul pancreatic','se evaluează cel mai bine prin CT','se evaluează cel mai bine prin ERCP','are perete tapetat de epiteliu cubic'],'ABC',266,'Pancreatita acută',
 'Definiția și evaluarea pseudochistului.',
 ['Peretele nu are straturi epiteliale.','Pseudochisturile pot fi comunicante sau necomunicante.','CT-ul este cea mai bună metodă imagistică.','Nu: CT-ul este metoda cea mai bună.','Nu: peretele nu are epiteliu.']],
 [8,'Distractorii îi dau epiteliu și schimbă metoda imagistică.'],['fără straturi epiteliale','cea mai bună metodă']),
q('pancreas-adv-053',['Drenajul pseudochistului pancreatic este indicat când acesta:',
 ['are un diametru de peste 5 cm','persistă de mai mult de un an','are sub 2 cm, fără simptome','are sub două săptămâni de evoluție','este mic și descoperit întâmplător'],'AB',266,'Pancreatita acută',
 'Indicațiile de drenaj ale pseudochistului.',
 ['Cele >5 cm tind să crească și să dea simptome.','Cele care persistă peste un an merită drenaj.','Nu: pseudochisturile mici, asimptomatice, se urmăresc.','Nu: peretele nu este matur înainte de 4 săptămâni.','Nu: se urmăresc.']],
 [8,'Distractorii propun drenajul leziunilor mici sau imature.'],['Pseudochisturile mici','asimptomatice']),
q('pancreas-adv-019',['Drenajul pseudochistului comunicant:',
 ['se face intern, în stomac sau duoden','poate folosi o ansă Roux','este funcțional în peste 90% din cazuri','folosește anastomoza directă a peretelui','se face de elecție extern, percutanat'],'ABCD',267,'Pancreatita acută',
 'Drenajul intern al pseudochistului comunicant.',
 ['Se drenează intern în stomac sau duoden.','O ansă Roux poate fi folosită.','Drenajul intern este funcțional în peste 90%.','Peretele se anastomozează direct cu organul de drenaj.','Nu: drenajul extern este contraindicat (fistulă cronică).']],
 [8,'Distractorul propune drenajul extern contraindicat.'],['ansă Roux','90% dintre cazuri']),
q('pancreas-adv-054',['În drenajul intern al unui pseudochist, examenul extemporaneu al peretelui urmărește:',
 ['excluderea unui neoplasm chistic','stabilirea comunicării cu ductul','cultura germenilor anaerobi','dozarea amilazei din perete','evaluarea grosimii peretelui pentru sutură'],'A',267,'Pancreatita acută',
 'Motivul examenului pe secțiuni înghețate.',
 ['Se exclude posibilitatea ca chistul să fie un neoplasm.','Nu: comunicarea se apreciază la MRCP sau ERCP.','Nu: nu este scopul citat.','Nu: nu este scopul citat.','Nu: grosimea se apreciază pe CT.']],
 [8,'Distractorii dau alte scopuri examenului.'],['secţiuni îngheţate','neoplasm']),
q('pancreas-adv-020',['Pancreatita cronică:',
 ['este cauzată de alcool în ~70% din cazuri','are distrucție glandulară ireversibilă','poate fi cauzată de fibroza chistică','este cauzată de alcool în ~20% din cazuri','are distrucție reversibilă după abstinență'],'ABC',267,'Pancreatita cronică',
 'Etiologia și ireversibilitatea pancreatitei cronice.',
 ['Alcoolul explică aproximativ 70%.','Distrucția nu mai este reversibilă și este progresivă.','Fibroza chistică este o cauză genetică.','Nu: proporția este ~70%.','Nu: distrucția este ireversibilă.']],
 [8,'Distractorii scad ponderea alcoolului și fac leziunea reversibilă.'],['70% dintre cazurile de pancreatită cronică','fibroza chistică']),
q('pancreas-adv-075',['Pancreatita cronică avansată:',
 ['produce durere surdă epigastrică','are durere agravată adesea de alimentație','produce insuficiență exocrină la distrucție de 90%','asociază deficit de vitamine liposolubile','are durere ameliorată de alimentație'],'ABCD',267,'Pancreatita cronică',
 'Durerea și insuficiența glandulară în pancreatita cronică.',
 ['Durerea este surdă, epigastrică, cu iradiere posterioară.','Mâncarea agravează adesea durerea.','La distrucția a 90% apare insuficiența exo- și endocrină.','Apare deficitul de vitamine liposolubile.','Nu: mâncarea agravează durerea.']],
 [8,'Distractorul inversează efectul alimentației.'],['vitamine liposolubile','Mâncarea agravează']),
q('pancreas-adv-055',['Procedura Puestow (pancreaticojejunostomia laterală):',
 ['se indică la duct pancreatic dilatat >4 mm','ameliorează durabil durerea la ~70%','păstrează țesutul pancreatic funcțional','se indică la ductele pancreatice nedilatate','ameliorează durerea la sub 10%'],'ABC',268,'Pancreatita cronică',
 'Indicația și rezultatele procedurii de drenaj.',
 ['Drenajul funcționează cel mai bine la duct >4 mm.','Durerea se ameliorează durabil la ~70%.','Drenajul păstrează țesutul funcțional.','Nu: ductele nedilatate primesc proceduri de rezecție.','Nu: ameliorarea apare la ~70%.']],
 [8,'Distractorii inversează indicația și rezultatul.'],['Puestow','pancreaticojejunostomie laterală']),
q('pancreas-adv-029',['În pancreatita cronică fără dilatație ductală:',
 ['se pot indica procedurile Beger sau Frey','se poate face duodenopancreatectomie cefalică','pancreatectomia totală este indicația de elecție','splanhnicectomia are rezultate durabile','se preferă procedura Puestow'],'AB',268,'Pancreatita cronică',
 'Procedurile de rezecție în pancreatita cronică.',
 ['Beger sau Frey rezecă capul cu prezervarea duodenului.','Duodenopancreatectomia cefalică este o procedură de rezecție.','Nu: pancreatectomia totală nu este indicată (disfuncție severă).','Nu: rezultatele au fost dezamăgitoare.','Nu: Puestow cere duct dilatat.']],
 [8,'Distractorii propun drenaj sau proceduri abandonate.'],['Beger sau Frey','splanhnicectomie']),
q('pancreas-adv-056',['Adenocarcinomul pancreatic:',
 ['reprezintă peste 90% din cancerele pancreatice','are ca factor de risc major fumatul','apare în două treimi din cazuri cefalic','reprezintă 7% din cancerele pancreatice','apare predominant în coada pancreasului'],'ABC',268,'Tumorile pancreatice',
 'Frecvența, factorii de risc și localizarea adenocarcinomului.',
 ['Peste 90% dintre cancerele pancreatice sunt adenocarcinoame.','Fumatul dublează riscul.','Două treimi se dezvoltă cefalic.','Nu: 7% este ponderea TPN.','Nu: două treimi sunt cefalice.']],
 [8,'Distractorii iau cifra TPN și mută localizarea.'],['Peste 90%','Două treimi']),
q('pancreas-adv-040',['Conform Tabelului 17-7, sunt leziuni premaligne:',
 ['neoplasmul mucinos chistic','neoplasmul solid pseudopapilar','chistadenomul seros microchistic','chistadenocarcinomul mucinos','chistul pancreatic simplu'],'AB',268,'Tumorile pancreatice',
 'Clasificarea tumorilor pancreatice non-endocrine.',
 ['Neoplasmul mucinos chistic este premalign.','Neoplasmul solid pseudopapilar (Hamoudi) este premalign.','Nu: este benign.','Nu: este malign.','Nu: este benign.']],
 [8,'Distractorii sunt din categoriile benignă și malignă.'],['tumora Hamoudi','Premaligne']),
q('pancreas-adv-066',['Mutația cea mai frecventă și mai precoce în cancerul pancreatic afectează:',
 ['oncogena K-ras','gena supresoare p53','gena SMAD4/DPC','receptorul HER2','gena APC'],'A',268,'Tumorile pancreatice',
 'Rolul K-ras în progresia cancerului pancreatic.',
 ['K-ras este mutația cea mai frecventă și cea mai precoce.','Nu: supresoarele sunt inactivate în etapele următoare.','Nu: supresoarele sunt inactivate în etapele următoare.','Nu: este un receptor de factor de creștere.','Nu: supresoarele sunt inactivate în etapele următoare.']],
 [8,'Distractorii sunt gene din Tabelul 17-8.'],['K-ras','oncogenele']),
q('pancreas-adv-005',['Tabloul clinic al tumorilor pancreatice:',
 ['periampularele dau icter precoce, cu prognostic mai bun','corporeo-caudalele debutează cu dureri de spate','semnul Courvoisier sugerează malignitatea','corporeo-caudalele dau precoce icter obstructiv','periampularele au prognostic mai prost decât cele cefalice'],'ABC',269,'Tumorile pancreatice',
 'Prezentarea clinică după localizarea tumorii.',
 ['Periampularele dau icter nedureros mai devreme și au prognostic mai bun.','Durerile de spate sunt de obicei primul simptom corporeo-caudal.','Vezicula palpabilă nedureroasă cu icter sugerează malignitatea.','Nu: sunt la distanță de calea biliară.','Nu: au prognostic mai bun.']],
 [8,'Distractorii inversează localizările.'],['semnul Courvoisier','Carcinoamele periampulare']),
q('pancreas-adv-057',['Evaluarea pacientului icteric suspect de tumoră pancreatică:',
 ['ecografia este prima explorare imagistică','CT-ul este cea mai bună examinare a pancreasului','ERCP este prima explorare imagistică','transaminazele cresc marcat, cu FA normală','CT-ul nu poate identifica metastazele hepatice'],'AB',269,'Tumorile pancreatice',
 'Succesiunea explorărilor în icterul obstructiv.',
 ['Ultrasonografia este prima opțiune.','CT-ul este cea mai bună modalitate de examinare a pancreasului.','Nu: ecografia este prima.','Nu: FA și γ-GGT cresc semnificativ, transaminazele ușor.','Nu: CT-ul identifică metastazele hepatice.']],
 [8,'Distractorii inversează ordinea și profilul biochimic.'],['prima opţiune','metastazele hepatice']),
q('pancreas-adv-044',['Pe CT, criterii de nerezecabilitate a tumorii pancreatice sunt:',
 ['invazia arterei mezenterice superioare','prezența ascitei','invazia joncțiunii VP–VMS','icterul obstructiv','dilatarea ductului pancreatic'],'ABC',269,'Tumorile pancreatice',
 'Definiția rezecabilității pe CT.',
 ['Invazia AMS exclude rezecabilitatea.','Ascita exclude rezecabilitatea.','Invazia joncțiunii VP–VMS face tumora nerezecabilă.','Nu: icterul este frecvent la tumorile rezecabile.','Nu: nu este criteriu citat.']],
 [8,'Distractorii sunt semne frecvente, dar compatibile cu rezecția.'],['rezecabilităţii','joncţiunea VP-VMS']),
q('pancreas-adv-006',['Biopsia preoperatorie a unei tumori pancreatice rezecabile nu este de rutină deoarece:',
 ['are o rată crescută de rezultate fals negative','are o rată crescută de rezultate fals pozitive','modifică stadializarea TNM','este contraindicată în icterul obstructiv','nu poate fi ghidată prin ultrasonografie endoscopică'],'A',270,'Tumorile pancreatice',
 'Motivele evitării biopsiei preoperatorii.',
 ['Rata de fals negative este crescută.','Nu: problema citată sunt fals negativele.','Nu: nu este motivul citat.','Nu: nu este motivul citat.','Nu: EUS poate obține diagnosticul histopatologic.']],
 [8,'Distractorul principal inversează tipul de eroare.'],['fals negative','hemoragiei postprocedurale']),
q('pancreas-adv-077',['Pregătirea preoperatorie a pacientului icteric cu tumoră pancreatică rezecabilă:',
 ['corectează coagulopatia legată de vitamina K','evaluează albumina și timpul de protrombină','evită de regulă drenajul biliar preoperator','impune drenaj biliar preoperator de rutină','impune biopsie preoperatorie la toți pacienții'],'ABC',270,'Tumorile pancreatice',
 'Pregătirea icterului obstructiv înaintea rezecției.',
 ['Coagulopatia prin vitamina K se corectează înaintea intervenției.','Albumina, transferina, prealbumina și TP evaluează statusul.','Drenajul biliar preoperator nu este indicat.','Nu: crește complicațiile infecțioase.','Nu: biopsia nu este întotdeauna indicată.']],
 [8,'Distractorii impun drenaj și biopsie de rutină.'],['vitamina K','Drenajul']),
q('pancreas-adv-058',['Duodenopancreatectomia cefalică clasică (Whipple):',
 ['rezecă antrul gastric și duodenul în totalitate','rezecă calea biliară principală distală','are mortalitate sub 5%, cu complicații frecvente','are mortalitate de peste 20% în centrele mari','nu include pancreaticojejunostomia'],'ABC',270,'Tumorile pancreatice',
 'Rezecția și rezultatele procedurii Whipple.',
 ['În forma clasică se rezecă antrul, capul pancreatic și duodenul.','Se rezecă porțiunea distală a CBP.','Mortalitatea este <5%, complicațiile frecvente.','Nu: mortalitatea este <5%.','Nu: reconstrucția include pancreaticojejunostomia.']],
 [8,'Distractorii exagerează mortalitatea și omit o anastomoză.'],['antrul gastric','pancreaticojejunostomie']),
q('pancreas-adv-032',['Tumorile corpului și cozii pancreatice se tratează prin:',
 ['pancreatectomie distală cu splenectomie','duodenopancreatectomie cefalică clasică','pancreatectomie totală de principiu','enucleere cu păstrarea splinei','bypass biliar și gastrojejunostomie'],'A',270,'Tumorile pancreatice',
 'Rezecția potrivită localizării corporeo-caudale.',
 ['Pancreatectomia distală include cel mai adesea splenectomia.','Nu: se indică pentru tumorile cefalice.','Nu: nu este tratamentul citat.','Nu: nu este tratamentul citat.','Nu: sunt proceduri paliative.']],
 [8,'Distractorii aplică rezecții pentru alte localizări.'],['pancreatectomie distală','splenectomia']),
q('pancreas-adv-022',['Paliația cancerului pancreatic nerezecabil:',
 ['bypass biliar dacă nerezecabilitatea apare intraoperator','gastrojejunostomie la obstrucția gastrică distală','neuroliza plexului celiac pentru durerile posterioare','stentare biliară endoscopică pentru prurit','duodenopancreatectomie paliativă de principiu'],'ABCD',271,'Tumorile pancreatice',
 'Opțiunile paliative în cancerul pancreatic.',
 ['La nerezecabilitate intraoperatorie se face bypass biliar.','Obstrucția gastrică distală cere gastrojejunostomie.','Neuroliza plexului celiac ameliorează durerea.','Stentarea biliară tratează pruritul.','Nu: nu este un gest paliativ citat.']],
 [8,'Distractorul transformă rezecția în paliație.'],['bypass biliar paliativ','gastrojejunostomie paliativă']),
q('pancreas-adv-021',['Prognosticul adenocarcinomului pancreatic:',
 ['nerezecabil: supraviețuire medie de ~6 luni','rezecat R0 cu adjuvant: ~19 luni','tumora >3 cm este factor nefavorabil','rezecat R0: supraviețuire la 5 ani de ~70%','invazia perineurală este factor favorabil'],'ABC',271,'Tumorile pancreatice',
 'Cifrele de supraviețuire și factorii prognostici.',
 ['Boala nerezecabilă are supraviețuire medie de ~6 luni.','Rezecția cu margini negative și adjuvant extinde durata la ~19 luni.','Tumorile >3 cm sunt factor nefavorabil.','Nu: supraviețuirea la 5 ani este probabil de 20%.','Nu: este factor nefavorabil.']],
 [8,'Distractorii exagerează supraviețuirea și inversează un factor.'],['19 luni','invazia perineurală']),
q('pancreas-adv-059',['Tratamentul adjuvant și neoadjuvant în cancerul pancreatic:',
 ['neoadjuvantul cere diagnostic histopatologic prealabil','CONKO-1 a arătat beneficiul gemcitabinei adjuvante','ESPAC-1 a arătat beneficiul chimioradierii','neoadjuvantul are eficacitate dovedită','neoadjuvantul se începe fără diagnostic tisular'],'AB',271,'Tumorile pancreatice',
 'Datele studiilor adjuvante și condiția terapiei neoadjuvante.',
 ['Diagnosticul histopatologic este necesar înaintea terapiei neoadjuvante.','CONKO-1 a arătat beneficiul gemcitabinei adjuvante.','Nu: ESPAC-1 a arătat beneficiu pentru chimioterapie, nu pentru chimioradiere.','Nu: eficacitatea rămâne incertă.','Nu: diagnosticul tisular este necesar.']],
 [8,'Distractorii inversează concluziile studiilor.'],['ESPAC-1','CONKO-1']),
q('pancreas-adv-060',['Tumorile pancreatice neuroendocrine (TPN):',
 ['reprezintă ~7% din cancerele pancreatice','sunt nefuncționale în aproximativ 50%','au incidența maximă între 30 și 60 de ani','se clasifică după prezența sindromului secretor','sunt mai frecvente decât adenocarcinoamele'],'ABCD',271,'Tumorile neuroendocrine',
 'Epidemiologia și clasificarea TPN.',
 ['TPN reprezintă aproximativ 7%.','Aproximativ 50% sunt nefuncționale.','Incidența maximă este între 30 și 60 de ani.','Clasificarea funcțional/nefuncțional depinde de sindromul clinic.','Nu: sunt mai puțin frecvente.']],
 [8,'Distractorul inversează frecvența relativă.'],['7% din cancerele pancreatice','nefuncţionale']),
q('pancreas-adv-023',['Conform Tabelului 17-9, sunt în majoritate maligne:',
 ['gastrinoamele','glucagonoamele','VIPoamele','somatostatinoamele','insulinoamele'],'ABCD',271,'Tumorile neuroendocrine',
 'Potențialul malign al TPN funcționale.',
 ['Gastrinoamele sunt în majoritate maligne.','Glucagonoamele sunt în majoritate maligne.','VIPoamele sunt în majoritate maligne.','Somatostatinoamele sunt în majoritate maligne.','Nu: insulinoamele sunt în majoritate benigne.']],
 [8,'Distractorul este singura TPN benignă în majoritate.'],['Gastrinoame','Somatostatinoame']),
q('pancreas-adv-061',['Insulinomul:',
 ['este cea mai frecventă TPN funcțională','este benign în 85–90% din cazuri','este de obicei solitar și sub 2 cm','este localizat în cap în ~75% din cazuri','asociază MEN 1 în ~50% din cazuri'],'ABC',272,'Tumorile neuroendocrine',
 'Epidemiologia și localizarea insulinomului.',
 ['Insulinoamele sunt cele mai frecvente tumori funcționale.','85–90% sunt benigne.','Majoritatea sunt solitare și <2 cm.','Nu: ~75% sunt în corp și coadă.','Nu: ~10% au MEN 1.']],
 [8,'Distractorii mută localizarea și exagerează MEN 1.'],['solitare','MEN l']),
q('pancreas-adv-078',['Al treilea element al triadei Whipple este:',
 ['dispariția simptomelor după glucoză i.v.','creșterea insulinei după secretină','peptidul C sub 200 pmol/L','glicemia sub 70 mg/dL à jeun','scăderea cortizolului seric'],'A',272,'Tumorile neuroendocrine',
 'Componentele triadei Whipple.',
 ['Triada: simptome, glicemie 40–50 mg/dL, dispariția simptomelor după glucoză i.v.','Nu: insulinomul nu răspunde la secretină.','Nu: criteriul este peptid-C ≥200 pmol/L.','Nu: glicemia citată este 40–50 mg/dL.','Nu: nu este element al triadei.']],
 [8,'Distractorii inversează criteriile de laborator.'],['Triada Whipple','dispariţia simptomelor']),
q('pancreas-adv-079',['Criteriile de laborator ale insulinomului includ:',
 ['glicemie ≤45 mg/dL concomitent','insulină serică ≥36 µU/L','peptid-C ≥200 pmol/L','β-hidroxibutirat ≥5 mmol/L','prezența sulfonilureei în urină'],'ABC',272,'Tumorile neuroendocrine',
 'Cele șase criterii biochimice ale insulinomului.',
 ['Glicemia ≤45 mg/dL este criteriu.','Insulina concomitentă ≥36 µU/L este criteriu.','Peptidul C ≥200 pmol/L este criteriu.','Nu: β-hidroxibutiratul este ≤2,7 mmol/L.','Nu: criteriul este absența sulfonilureei.']],
 [8,'Distractorii inversează direcția criteriilor.'],['sulfonilureei','peptid-C']),
q('pancreas-adv-037',['La pacientul cu insulinom, injectarea de secretină:',
 ['nu crește producția de insulină','crește marcat producția de insulină','crește gastrina cu peste 200 pg/mL','scade glicemia sub 40 mg/dL','stimulează eliberarea de glucagon'],'A',272,'Tumorile neuroendocrine',
 'Interpretarea testului cu secretină în insulinom.',
 ['Insulinoamele nu eliberează insulină la secretină și inhibă răspunsul celulelor β.','Nu: răspunsul lipsește.','Nu: descrie testul pozitiv din gastrinom.','Nu: nu este efectul citat.','Nu: nu este efectul citat.']],
 [8,'Distractorii confundă cu testul la secretină al gastrinomului.'],['secretinei','celulele']),
q('pancreas-adv-031',['Tratamentul insulinomului:',
 ['enucleere la tumora mică, departe de duct','diazoxid sau streptozocină în boala metastatică','enucleere la tumora mare, adiacentă ductului','diazoxid ca tratament curativ al formelor mici','pancreatectomie totală de principiu'],'AB',272,'Tumorile neuroendocrine',
 'Alegerea între enucleere, pancreatectomie și tratament medical.',
 ['Tumorile mici, la distanță de duct, pot fi enucleate.','Diazoxidul sau streptozocina se folosesc în boala nerezecabilă.','Nu: tumorile mari, adiacente ductului, cer pancreatectomie.','Nu: tratamentul curativ este chirurgical.','Nu: nu este tratamentul citat.']],
 [8,'Distractorii inversează indicația enucleerii.'],['enucleate','diazoxidul']),
q('pancreas-adv-024',['Gastrinomul:',
 ['apare sporadic în trei pătrimi din cazuri','se află în peretele duodenal în peste 50%','este multicentric în jumătate din cazuri','metastazează frecvent în ficat','este localizat în coada pancreatică în peste 50%'],'ABCD',272,'Tumorile neuroendocrine',
 'Epidemiologia și localizarea gastrinomului.',
 ['Trei pătrimi apar sporadic.','Peste 50% sunt în peretele duodenal.','Gastrinoamele sunt multicentrice în jumătate din cazuri.','Tind să metastazeze în ganglioni și ficat (50%).','Nu: peste 50% sunt în peretele duodenal.']],
 [8,'Distractorul mută localizarea în coadă.'],['Trei pătrimi','peretelui duodenal']),
q('pancreas-adv-080',['Triunghiul gastrinoamelor este delimitat, printre altele, de:',
 ['confluența cisticului cu hepaticul','hilul splenic și coada pancreatică','joncțiunea corp–coadă a pancreasului','ligamentul Treitz și jejunul proximal','porțiunea a patra a duodenului'],'A',272,'Tumorile neuroendocrine',
 'Limitele triunghiului gastrinoamelor.',
 ['Joncțiunea cisticului cu hepaticul comun este o limită.','Nu: limitele sunt la dreapta, spre duoden.','Nu: limita este joncțiunea col–corp pancreatic.','Nu: nu este limită citată.','Nu: limita este joncțiunea porțiunilor a doua și a treia.']],
 [8,'Distractorii mută limitele spre stânga.'],['triunghiului gastrinoamelor','hepaticul comun']),
q('pancreas-adv-081',['Diagnosticul biochimic al gastrinomului:',
 ['gastrina >1.000 pg/mL cu pH gastric <2','testul la secretină cu creștere >200 pg/mL','dozarea calciului seric pentru MEN 1','secretina scade gastrina în gastrinom','gastrina <1.000 pg/mL exclude diagnosticul'],'ABC',272,'Tumorile neuroendocrine',
 'Pragurile de gastrină și testul la secretină.',
 ['Gastrina >1.000 pg/mL la pH <2 are valoare diagnostică.','O creștere >200 pg/mL după secretină este test pozitiv.','Calciul seric se dozează pentru excluderea MEN 1.','Nu: secretina scade gastrina în mod normal, nu în gastrinom.','Nu: două treimi au gastrină <1.000 pg/mL.']],
 [8,'Distractorii inversează răspunsul la secretină.'],['pH gastric','calciul seric']),
q('pancreas-adv-088',['Hipergastrinemia poate apărea în:',
 ['gastrita atrofică','insuficiența renală cronică','tratamentul cu IPP','infecția cu H. pylori','insulinomul pancreatic'],'ABCD',273,'Tumorile neuroendocrine',
 'Cauzele de hipergastrinemie din afara gastrinomului.',
 ['Gastrita atrofică este citată.','Insuficiența renală cronică este citată.','Inhibitorii pompei de protoni sunt citați.','Infecția cu H. pylori este citată.','Nu: nu este cauză citată.']],
 [8,'Distractorul este o altă TPN.'],['gastrita atrofică','obstrucţia gastrică distală']),
q('pancreas-adv-063',['Glucagonomul:',
 ['derivă din celulele α ale pancreasului','asociază eritemul migrator necrolitic','asociază frecvent tromboze venoase profunde','se localizează mai ales în capul pancreatic','este de obicei o leziune mică, benignă'],'ABC',273,'Tumorile neuroendocrine',
 'Tabloul clinic și localizarea glucagonomului.',
 ['Glucagonoamele derivă din celulele α.','Peste jumătate au eritem migrator necrolitic.','Trombozele venoase profunde sunt frecvente.','Nu: predomină în corp și coadă.','Nu: pacienții au de obicei leziuni mari și metastaze.']],
 [8,'Distractorii mută localizarea și subestimează extensia.'],['eritemul migrator necrolitic','tromboze venoase profunde']),
q('pancreas-adv-062',['VIPomul (sindromul Verner-Morrison):',
 ['produce diaree apoasă de 6–8 L/zi','asociază hipopotasemie și hipoclorhidrie','persistă diareea în repaus alimentar','produce acidoză metabolică','asociază hiperpotasemie și alcaloză'],'ABCD',273,'Tumorile neuroendocrine',
 'Sindromul diareei apoase.',
 ['Diareea este abundentă, 6–8 L/zi.','Triada include hipopotasemia și hipoclorhidria.','Diareea persistă în repaus alimentar.','Pacienții prezintă acidoză metabolică.','Nu: apar hipopotasemie și acidoză.']],
 [8,'Distractorul inversează potasiul și echilibrul acido-bazic.'],['Verner-Morrison','repaus alimentar']),
q('pancreas-adv-076',['Somatostatinomul:',
 ['este localizat în capul pancreatic în ~60%','este malign în până la 90% din cazuri','se tratează de elecție prin enucleere','este de obicei sub 1 cm la diagnostic','stimulează contracția veziculei biliare'],'AB',273,'Tumorile neuroendocrine',
 'Localizarea, dimensiunea și tratamentul somatostatinomului.',
 ['60% sunt în capul pancreatic.','Până la 90% sunt maligne.','Nu: enucleerea nu este indicată; se face rezecție.','Nu: sunt de obicei >5 cm.','Nu: somatostatina inhibă contracția veziculei.']],
 [8,'Distractorii îl tratează ca pe un insulinom mic.'],['enucleerea nu este indicată','calculi biliari']),
q('pancreas-adv-086',['Explorarea imagistică a TPN:',
 ['tumorile funcționale sunt mai mici la diagnostic','octreoscanul este util în boala metastatică','ASVS ghidează localizarea insulinomului','octreoscanul detectează insulinomul peste 90%','calcificările sugerează o leziune benignă'],'ABC',273,'Tumorile neuroendocrine',
 'Alegerea explorărilor pentru localizarea TPN.',
 ['Tumorile funcționale se prezintă mai repede și sunt mai mici.','Octreoscanul este extrem de util în boala metastatică.','ASVS orientează rezecția spre porțiunea cu insulinom.','Nu: sensibilitatea pentru insulinom este <50%.','Nu: calcificările sugerează malignitatea.']],
 [8,'Distractorii exagerează octreoscanul și inversează un semn.'],['Octreoscanul','ASVS']),
q('pancreas-adv-038',['Tratamentul chirurgical al TPN:',
 ['vizează rezecția tumorii primare și a metastazelor','include citoreducție hepatică dacă se extirpă ≥90%','se contraindică la metastaze osoase','se face și la metastaze extraabdominale','cere citoreducție chiar sub 50% din volum'],'ABC',273,'Tumorile neuroendocrine',
 'Indicațiile rezecției și citoreducției în TPN.',
 ['Tratamentul curativ cere îndepărtarea tumorii primare și a metastazelor.','Citoreducția este utilă dacă se extirpă cel puțin 90%.','Rezecția nu se face la metastaze osoase.','Nu: metastazele extraabdominale contraindică rezecția.','Nu: pragul este de cel puțin 90%.']],
 [8,'Distractorii extind indicația rezecției.'],['cel puţin 90%','extraabdominale']),
q('pancreas-adv-082',['Analogii de somatostatină în TPN:',
 ['controlează simptomele la aproape 100%','nu prelungesc supraviețuirea','prelungesc semnificativ supraviețuirea','controlează simptomele la sub 30%','au toxicitate semnificativă'],'AB',274,'Tumorile neuroendocrine',
 'Beneficiul simptomatic al analogilor de somatostatină.',
 ['Controlează simptomele la aproape 100% dintre pacienți.','Nu prelungesc supraviețuirea.','Nu: nu prelungesc supraviețuirea.','Nu: controlul este aproape 100%.','Nu: sunt bine tolerați.']],
 [8,'Distractorii inversează efectul asupra supraviețuirii.'],['aproape 100%','nu prelungesc']),
q('pancreas-adv-025',['Chistadenomul seros pancreatic:',
 ['este o leziune chistică benignă','nu necesită de regulă rezecție','conține stromă ovariană','este invaziv la 40% la diagnostic','are ACE crescut în lichidul chistic'],'AB',274,'Leziunile chistice',
 'Conduita în chistadenomul seros.',
 ['Chistadenoamele seroase sunt benigne.','Nu necesită rezecție.','Nu: stroma ovariană caracterizează neoplasmele mucinoase.','Nu: 40% invazive este cifra neoplasmelor mucinoase.','Nu: ACE crescut caracterizează leziunile mucinoase.']],
 [8,'Distractorii atribuie caractere mucinoase.'],['Chistadenoamele seroase','nu necesită rezecţie']),
q('pancreas-adv-026',['Neoplasmul chistic mucinos:',
 ['apare mai ales la femei de vârstă mijlocie','conține stromă ovariană','este invaziv la diagnostic în 40%','trebuie rezecat','apare mai ales în capul pancreatic'],'ABCD',274,'Leziunile chistice',
 'Caracterele neoplasmului chistic mucinos.',
 ['Apare aproape întotdeauna la femei de vârstă mijlocie.','Conține stromă ovariană.','40% sunt invazive la diagnostic.','Aceste leziuni trebuie rezecate.','Nu: predomină în corp și coadă.']],
 [8,'Distractorul mută localizarea.'],['stromă ovariană','40% dintre tumori']),
q('pancreas-adv-064',['Neoplasmul mucinos papilar intraductal (IPMN):',
 ['nu conține stromă ovariană','este mai frecvent la bărbați','de duct principal este mai frecvent malign','de duct principal se urmărește prin CT','este mai frecvent la femei'],'ABC',274,'Leziunile chistice',
 'Diferențierea IPMN de neoplasmul chistic mucinos.',
 ['IPMN nu conține stromă ovariană.','Este mai frecvent la bărbați.','Forma de duct principal este mai frecvent malignă.','Nu: aproape toate IPMN de duct principal se rezecă.','Nu: este mai frecvent la bărbați.']],
 [8,'Distractorii preiau caracterele neoplasmului mucinos.'],['IPMN','ductul pancreatic principal']),
q('pancreas-adv-027',['IPMN de ramură laterală se rezecă dacă:',
 ['are diametrul peste 3 cm','prezintă noduli la examinarea CT','are diametrul peste 1 cm','ductul principal are sub 5 mm','este descoperit întâmplător'],'AB',275,'Leziunile chistice',
 'Criteriile de rezecție ale IPMN de ramură.',
 ['Diametrul >3 cm este indicație de rezecție.','Nodulii la CT sunt indicație de rezecție.','Nu: pragul este 3 cm.','Nu: dilatarea >5 mm sugerează afectarea ductului principal.','Nu: leziunile asimptomatice se urmăresc.']],
 [8,'Distractorii coboară pragul sau folosesc criterii necitate.'],['citologie','simptomatice']),
q('pancreas-adv-083',['Conform Tabelului 17-11, stroma ovariană la biopsie caracterizează:',
 ['chistadenomul mucinos','IPMN-ul','chistadenomul seros','pseudochistul','chistadenocarcinomul seros'],'A',274,'Leziunile chistice',
 'Semnificația stromei ovariene în leziunile chistice.',
 ['Chistadenomul mucinos are stromă ovariană.','Nu: IPMN nu are stromă ovariană.','Nu: nu are stromă ovariană.','Nu: nu are stromă ovariană.','Nu: nu are stromă ovariană.']],
 [8,'Distractorul principal este IPMN.'],['stromă ovariană','Chistadenomul mucinos']),
];
