import {advancedQuestion} from './advanced-author';
import type {SourceRow} from './source-author';

const EDITION="Chirurgie generală și specialități chirurgicale, ediția pentru rezidențiat MG 2025";
const q=(n:number,row:SourceRow,score:number,reason:string,expressions:string[],related:number[]=[])=>
 advancedQuestion('perioperator',1,0,`perioperator-adv-${String(n).padStart(3,'0')}`,row,[score,reason],expressions,undefined,related,'Lawrence',EDITION);

export const PERIOPERATOR_D=[
q(31,['Identificați afirmația corectă privind indicațiile dializei perioperatorii la pacientul cu BRC sau IRA:',
 ['Dializa poate fi necesară la supraîncărcare de volum cu ICC la un pacient anuric, la hiperkaliemie amenințătoare de viață sau la acidoză refractară','Dializa se indică de principiu la pacientul Child A, indiferent de bilanțul hidric','Hipokaliemia ușoară, fără aritmie, impune hemodializă de urgență înaintea herniei inghinale','Acidoza metabolică corectată prin bicarbonat rămâne o indicație neselectivă de dializă','Monitorizarea CVP sau Doppler esofagian înlocuiește dializa în anuria cu edem pulmonar'],'A',3,'Disfuncție renală — Indicațiile dializei perioperatorii',
 'Recunoașterea triadei supraîncărcare-anurie/ICC, hiperkaliemie amenințătoare și acidoză refractară, distinctă de Child sau de hipokaliemie.',
 ['Textul enumeră aceste trei situații ca exemple de dializă când echilibrul hidric sau detoxifierea sunt inadecvate.','Child-Pugh privește ficatul, nu indicația de dializă renală.','Textul citează hiperkaliemia amenințătoare, nu hipokaliemia ușoară.','Acidoza refractară, nu cea deja corectată, figurează ca indicație.','Monitorizarea invazivă ghidează volemia; nu înlocuiește dializa în anuria cu ICC.']],
 8,'Permutează hiperkaliemia amenințătoare cu hipokaliemia și mută Child A pe dializa renală.',['hiperkalemia ameninţătoare','acidoza refractară']),

q(32,['Mortalitatea perioperatorie în funcție de scorul MELD se caracterizează prin:',
 ['La colecistectomia laparoscopică, MELD <8 asociază mortalitate 0%, iar MELD >8 aproximativ 6%','În chirurgia abdominală (alta decât colecistectomia laparoscopică), ortopedică și cardiovasculară, MELD ≤7 asociază mortalitate 5%','Același grup de intervenții: MELD 8–11 asociază mortalitate 10%','Același grup: MELD 12–15 asociază mortalitate 25%','Colecistectomia laparoscopică cu MELD <8 asociază mortalitate 25%, identică intervalului 12–15'],'ABCD',3,'Disfuncție hepatică — Praguri MELD și mortalitate',
 'Aplicarea perechilor 0%/6% (colecistectomie) versus 5%/10%/25% (alte intervenții) pe intervalele MELD tabelate.',
 ['Perechea <8 → 0% și >8 → ≈6% este explicită pentru colecistectomia laparoscopică.','Pragul ≤7 cu 5% este enunțat pentru chirurgia abdominală/ortopedică/cardiovasculară.','Intervalul 8–11 cu 10% este citat.','Intervalul 12–15 cu 25% este citat.','25% aparține intervalului 12–15, nu colecistectomiei cu MELD <8.']],
 8,'Oglindește 0% al MELD <8 cu 25% al intervalului 12–15, două cifre consecutive din același paragraf.',['MELD <8','mortalitate de 25%']),

q(33,['Un diabetic cu plenitudine postprandială prelungită, constipație și clapotaj gastric pe stomac care ar trebui gol, este evaluat preoperator. Sunt adevărate afirmațiile:',
 ['Gastropareza prin neuropatie vegetativă întârzie evacuarea și crește riscul de aspirație; clapotajul pe stomacul care ar trebui gol o sugerează','Hiperglicemia alterează în special activitatea fagocitară; pulsul periferic poate fi prezent chiar în ischemie tisulară, vaselor mici fiind afectate preferențial','Afectarea vaselor mici se extinde profund, cruțând tegumentul, ca un con cu baza la periferie și vârful proximal; un panarițiu sau o plagă minoră de picior pot duce la amputație sau deces','Gastropareza crește specificitatea leucocitozei ca marker de peritonită, clapotajul fiind un semn de evacuare accelerată','Pulsul absent la glezne este regula ischemiei diabetice de vase mici, tegumentul fiind primul afectat'],'ABC',4,'Pacientul diabetic — Gastropareză, fagocitoză și vase mici',
 'Integrarea clapotajului ca semn de gastropareză, a defectului fagocitar și a pattern-ului conic de ischemie a vaselor mici.',
 ['Plenitudinea, constipația și clapotajul pe stomacul care ar trebui gol sunt semnele citate de gastropareză.','Alterarea fagocitozei și prezența pulsului în ischemia de vase mici sunt explicite.','Metafora conului și gravitatea panarițiului/plăgii de picior sunt enunțate.','Gastropareza întârzie, nu accelerează, evacuarea; leucocitoza de sarcină, nu gastropareza, reduce utilitatea analizei.','Textul precizează că pulsul poate fi prezent; tegumentul este cruțat.']],
 8,'Inversează prezența pulsului în ischemia de vase mici și tratează clapotajul ca evacuare accelerată.',['Clapotajul gastric','con cu baza']),

q(34,['Pentru perspectiva dozelor de substituție, pacienții cu sindrom Cushing produc echivalentul a:',
 ['36 mg hidrocortizon/zi','20 mg prednison/zi, identic pragului de supresie HPA','100 mg hidrocortizon la inducție, ca stresul chirurgical major','50 mg hidrocortizon IV înaintea artroplastiei de șold','200 mg hidrocortizon la 4 ore, ca stresul minor'],'A',5,'Insuficiența adrenală — Producția din sindromul Cushing',
 'Fixarea cifrei de 36 mg hidrocortizon/zi ca referință fiziologică, distinctă de pragul prednison 20 mg și de schemele Tabelului 1-3.',
 ['Textul precizează echivalentul de 36 mg hidrocortizon/zi produs de pacienții cu sindrom Cushing.','20 mg prednison ≥3 săptămâni este pragul de supresie HPA, nu producția cushingoidă.','100 mg la inducție este schema stresului major, nu producția endogenă.','50+25 mg definește stresul moderat din Tabelul 1-3.','Stresul minor nu se suplimentează; 200 mg/4 h nu figurează.']],
 8,'Permutează 36 mg/zi cu 20 mg prednison sau cu dozele 50/100 mg din Tabelul 1-3.',['36 mg hidrocortizon','sindrom Cushing']),

q(35,['Modificările respiratorii și digestive din sarcină includ:',
 ['Frecvența respiratorie și volumul curent cresc; ventilația pe minut crescută scade PaCO2, în ciuda reducerii CRF și a volumului rezidual prin uterul gravid','Cauza principală a refluxului este evacuarea gastrică întârziată prin progesteron, care reduce contractilitatea musculaturii netede; producția acidă este doar ușor crescută','PaCO2 crește prin hipoventilație, CRF fiind crescută de mobilitatea diafragmatică','Refluxul se datorează hipersecreției acide ca mecanism principal, progesteronul accelerând evacuarea','Grețurile din primul trimestru exclud patologia chirurgicală digestivă, fără diagnostic diferențial'],'AB',6,'Pacienta însărcinată — Ventilație, CRF și reflux prin progesteron',
 'Contrastarea hipocapniei prin hiperventilație (CRF redusă) de mecanismul progesteronic al refluxului, versus hipersecreția ca cauză unică.',
 ['Creșterea FR/VT, scăderea PaCO2 și reducerea CRF/VR sunt explicite.','Progesteronul ca cauză principală a evacuării întârziate, cu aciditate doar ușor crescută, este enunțat.','Textul descrie scăderea, nu creșterea, PaCO2 și reducerea CRF.','Hipersecreția este secundară; mecanismul principal este evacuarea întârziată.','Grețurile din T1 pot fi confundate cu afecțiuni chirurgicale, deci diagnosticul diferențial rămâne.']],
 8,'Inversează PaCO2/CRF și atribuie refluxul hipersecreției, două mecanisme din același paragraf de fiziologie gravidă.',['volumul curent','acţiunii progesteronului']),

q(36,['La gravida traumatizată, explorarea chirurgicală este indicată pentru:',
 ['Hemoragie intraperitoneală','Traumatism al organelor cavitare, plagă penetrantă abdominală sau injurie uterină/fetală','Explorările paraclinice cu valoare diagnostică trebuie recomandate, nu evitate de teama efectului teratogen','Monitorizarea fetală se amână până după naștere, oxigenarea maternă fiind superfluă','Plaga penetrantă abdominală se observă, laparotomia fiind rezervată doar fracturilor de membre'],'ABC',6,'Pacienta însărcinată — Indicațiile explorării în traumă',
 'Recunoașterea celor patru indicații de explorare și a principiului de a nu evita diagnosticul imagistic de teama teratogenezei.',
 ['Hemoragia intraperitoneală este prima indicație enumerată.','Organele cavitare, plaga penetrantă și injuria uterină/fetală completează lista.','Textul cere explorări diagnostice, nu evitarea lor.','Monitorizarea fetală precoce este esențială; resuscitarea fetală cere volum și oxigenare materne.','Plaga penetrantă abdominală este tocmai o indicație de explorare.']],
 8,'Transformă teama de teratogeneză într-o interdicție imagistică și amână monitorizarea fetală.',['plagă penetrantă','efectului teratogen']),

q(37,['Foaia de observație, potrivit capitolului, se caracterizează prin:',
 ['Are trei obiective: consemnarea statusului și a raționamentului, transmiterea instrucțiunilor în rubrica de tratament și consemnarea evenimentelor din îngrijire','Consemnarea imediat postoperator notează complicații, pierderi sanguine, refacere volemică și diureză','Biletul de externare cuprinde diagnosticul principal, rezumatul evoluției, tratamentul după externare, destinația, nivelul de activitate și planul de urmărire, fără fiecare detaliu al internării','Copierea din foaia electronică poate propaga informații false sau denaturate și trebuie folosită responsabil','Biletul de externare trebuie să reproducă fiecare rezultat de laborator din spitalizare, cele trei obiective fiind superfluă'],'ABCD',7,'Documentația — Trei roluri ale foii și biletul de externare',
 'Fixarea celor trei obiective, a conținutului notei intraoperatorii și a biletului concis, plus riscul copy-paste electronic.',
 ['Cele trei obiective sunt enumerate explicit.','Elementele notei imediat postoperatorii sunt listate.','Conținutul biletului de externare și interdicția detaliului exhaustiv sunt enunțate.','Avertismentul privind copierea electronică este citat.','Textul cere un bilet concis, nu transcrierea fiecărui detaliu.']],
 8,'Transformă biletul concis într-o transcriere exhaustivă și anulează cele trei obiective din același paragraf de documentație.',['obiective principale','Biletul de externare']),

q(38,['În recomandările medicale, înștiințarea medicului este cerută, între altele, când:',
 ['Diureza scade sub 30 mL/oră','Drenajul toracic depășește 100 mL/oră','Investigațiile de laborator „de rutină” sau „zilnice” sunt standardul de urmărire, fără reper temporal','Hematocritul se cere o singură dată, fără fereastră (ex. la 6 ore timp de 24 de ore)','Poziționarea pacientului nu influențează aspirația pe sonda de alimentație'],'AB',8,'Recomandări medicale — Praguri 30 mL/oră și 100 mL/oră',
 'Aplicarea pragurilor de alarmă (diureză <30 mL/oră, drenaj toracic >100 mL/oră) versus interdicția analizelor „zilnice” neselective.',
 ['Pragul <30 mL/oră este exemplul explicit de înștiințare.','Pragul >100 mL/oră pentru drenajul toracic este citat în aceeași paranteză.','Textul califică investigațiile „de rutină”/„zilnice” drept risipă, de evitat.','Exemplul cerut este hematocrit la 6 ore timp de 24 de ore, cu reper temporal.','Poziționarea este esențială în prevenția aspirației la alimentația pe sondă.']],
 8,'Anulează pragurile 30/100 mL și promovează analizele zilnice neselective, contrar aceluiași paragraf de ordine.',['<30 mL/oră','> 100 mL/oră']),

q(39,['Drenurile chirurgicale și sondele urinare/respiratorii se caracterizează prin:',
 ['Drenurile cu sistem închis de aspirație, uzual Jackson-Pratt și Hemovac, evacuează colecții prezente sau potențiale, conectate la un burduf pliabil','Drenurile Davol (aspirative cu sifon) sunt voluminoase, relativ rigide, pe aspirație continuă, pentru drenaj dens sau particulat','Tuburile de nefrostomie se plasează în pelvisul renal, amonte de o obstrucție sau de o anastomoză ureterală delicată','Sondele de traheostomă sunt rezervate ventilației de două ore, canula orotraheală fiind pentru luni','Jackson-Pratt este un drenaj pasiv din latex, identic Penrose, fără recipient compresibil'],'ABC',9,'Sonde și drenuri — JP/Hemovac, Davol și nefrostomie',
 'Diferențierea drenului închis aspirativ (JP/Hemovac) și a Davol-ului rigid de nefrostomie, versus confuzia cu Penrose sau inversarea traheostomă/orotraheală.',
 ['JP/Hemovac, colecțiile și burduful pliabil sunt explicite.','Davol: volum, rigiditate, aspirație continuă și drenaj particulat sunt citate.','Sediul în pelvisul renal și indicațiile (obstrucție/anastomoză) sunt enunțate.','Traheostomia este pentru termen lung; orotraheala pentru termen scurt.','Penrose este pasiv din latex; JP/Hemovac sunt aspirative închise.']],
 8,'Inversează JP (închis aspirativ) cu Penrose și limitează traheostomia la două ore, două distincții din pagini alăturate.',['Jackson-Pratt','Davol']),

q(40,['Datele epidemiologice și conduita în infecția de plagă chirurgicală includ:',
 ['Dintre peste 27 de milioane de intervenții anuale, peste 500.000 asociază infecții de plagă, reprezentând un sfert din infecțiile nosocomiale','Drenajul prompt minimizează consecințele, antibioticele având un rol secundar în absența circumstanțelor agravante; persistența tahicardiei, febrei sau ileusului sugerează o localizare profundă','Infecția de plagă este cea mai rară infecție nosocomială, sub 1% dintre intervenții','Antibioticele înlocuiesc drenajul, tahicardia precoce fiind un semn de vindecare','Cele 500.000 de cazuri reprezintă totalul infecțiilor nosocomiale, nu un sfert'],'AB',10,'IPC — 500.000/27 milioane și rolul secundar al antibioticelor',
 'Fixarea cifrelor 27 de milioane / 500.000 / un sfert nosocomial și a ierarhiei drenaj înaintea antibioticelor.',
 ['Cifrele 27 de milioane, 500.000 și un sfert din nosocomiale sunt explicite.','Rolul secundar al antibioticelor și semnele de infecție profundă sunt enunțate.','Textul o plasează ca a doua cea mai frecventă nosocomială, la 2–5% dintre chirurgicali.','Drenajul, nu antibioticele izolate, este manevra cheie; tahicardia poate fi primul semn de infecție.','500.000 este un sfert din nosocomiale, nu totalul.']],
 8,'Minimizează 500.000 la sub 1% și inversează drenajul cu antibioticele, două mesaje din același paragraf de IPC.',['27 de milioane','500.000 de cazuri']),
];
