import {rewriter} from './rewrite-author';
import {RETIRED_PERIOPERATOR} from './retired/perioperator';

// Rewritten after the 2026-09-24 cue audit (Lawrence, cap. 1, p. 1–12).
const q=rewriter(RETIRED_PERIOPERATOR,0,{shuffle:true,salt:'2'});

export const PERIOPERATOR_V2=[
q('perioperator-adv-001',['Screeningul de laborator preoperator la pacienții asimptomatici:',
 ['aduce costuri ridicate fără garanția beneficiului','are un prejudiciu potențial mai mare decât beneficiul','produce rezultate anormale ignorate în aproximativ 5%','se recomandă pentru definirea stării bazale','se repetă dacă analizele normale au sub 4 săptămâni'],'AB',1,'Testele de screening preoperatorii',
 'Aplicarea principiilor screeningului preoperator selectiv.',
 ['Screeningul neselectiv aduce costuri fără garanția rezultatelor.','Prejudiciul potențial depășește beneficiul.','Nu: aproximativ 60% din rezultatele anormale sunt ignorate.','Obținerea stării bazale nu este recomandată.','Analizele normale din ultimele 4 săptămâni nu se repetă.']],
 [8,'Distractorii contrazic recomandările explicite.'],['60% din rezultatele anormale','4 săptămâni']),

q('perioperator-adv-009',['Screeningul de rutină al hemoglobinei preoperator se face la pacienții:',
 ['cu pierderi sanguine anticipate peste 500 mL','asimptomatici supuși oricărei intervenții elective','cu pierderi sanguine anticipate peste 100 mL','vârstnici, pentru definirea stării bazale','programați pentru chirurgie sub anestezie locală'],'A',1,'Testele de screening preoperatorii',
 'Aplicarea indicațiilor dozării hemoglobinei.',
 ['Se face la pierderi tipic >500 mL sau anemie de cauză necunoscută.','Screeningul neselectiv nu este recomandat.','Pragul citat este 500 mL.','Starea bazală nu justifică screeningul.','Nu este indicația citată.']],
 [8,'Distractorii modifică pragul sau generalizează testarea.'],['>500 mL','anemie de cauză necunoscută']),

q('perioperator-adv-010',['Investigațiile preoperatorii țintite:',
 ['ionograma se recomandă și la vârstnici','sumarul de urină se face la simptome urinare','consultul de specialitate cuantifică riscul operator','consultul de specialitate contraindică operația','sumarul de urină se face înaintea procedurilor urologice'],'ABCE',1,'Testele de screening și consulturile de specialitate',
 'Aplicarea indicațiilor investigațiilor țintite.',
 ['Vârstnicii au risc de deshidratare cronică.','Sumarul de urină se face la simptome, boală urinară cronică sau proceduri urologice.','Consultul stabilește riscul și pregătirea optimă.','Scopul consultului nu este de a contraindica operația.','Sumarul de urină se face la simptome, boală urinară cronică sau proceduri urologice.']],
 [8,'Distractorii contrazic scopul consultului și al testării.'],['deshidratare cro','sumarului de urină']),

q('perioperator-adv-002',['Evaluarea cardiacă preoperatorie:',
 ['stresul chirurgical crește necesarul miocardic de oxigen','stresul chirurgical suprimă sistemul fibrinolitic','ECG se indică la pacienții care urmează o operație cu risc înalt','screeningul de rutină se recomandă la pacienții cu risc scăzut','riscul înalt cu capacitate funcțională păstrată impune test de efort'],'ABC',2,'Evaluarea cardiacă',
 'Aplicarea indicațiilor evaluării cardiace.',
 ['Catecolaminele cresc necesarul miocardic de oxigen.','Supresia fibrinolizei predispune la tromboză.','ECG este indicată înaintea operațiilor cu risc înalt.','Screeningul de rutină nu se recomandă la risc scăzut.','Acești pacienți ar putea să nu necesite evaluare amănunțită.']],
 [8,'Distractorii generalizează testarea cardiacă.'],['fibrinolitic','catecolamine']),

q('perioperator-adv-003',['Riscul pulmonar perioperator:',
 ['complicațiile pulmonare apar la 2–9%','radiografia toracică de rutină nu este în general necesară','clasificarea ASA are 3 categorii','clasa ASA a fost creată pentru riscul operator','radiografia toracică precede orice laparotomie'],'AB',2,'Evaluarea pulmonară',
 'Aplicarea evaluării riscului pulmonar.',
 ['Incidența raportată este 2–9%.','Radiografia și probele funcționale nu sunt necesare de rutină.','Nu: ASA are 6 categorii, inclusiv donatorii de organe.','ASA nu a fost elaborată pentru prezicerea riscului operator.','Radiografia se indică în chirurgia intratoracică sau boala pulmonară activă.']],
 [8,'Distractorii contrazic scopul clasificării ASA și al radiografiei.'],['2-9%','6 categorii']),

q('perioperator-adv-011',['Disfuncția renală perioperatorie:',
 ['BRC presupune afectare renală de cel puțin 3 luni','cea mai frecventă cauză de IRA perioperatorie este NTA','riscul de IRA la pacienții chirurgicali este de aproximativ 20%','BRC în stadiu terminal indică un grad specific de filtrare','fracția de ejecție sub 50% este pragul de risc pentru IRA'],'AB',2,'Pacientul cu disfuncție renală',
 'Fixarea definițiilor și a riscului de IRA.',
 ['BRC presupune afectare de cel puțin 3 luni.','Necroza tubulară acută este cea mai frecventă cauză.','Nu: riscul este de aproximativ 1%.','Stadiul terminal indică necesitatea dializei sau transplantului.','Pragul citat este fracția de ejecție <35%.']],
 [8,'Distractorii schimbă definiția și pragul.'],['necroza','1,7 L/']),

q('perioperator-adv-012',['Trombocitopatia din boala renală cronică poate fi gestionată preoperator cu:',
 ['DDAVP','vitamina K','plasmă proaspătă congelată','protamină','acid tranexamic'],'A',3,'Pacientul cu disfuncție renală',
 'Alegerea tratamentului trombocitopatiei uremice.',
 ['DDAVP eliberează factor von Willebrand din endoteliu.','Nu este tratamentul citat.','Nu este tratamentul citat.','Nu este tratamentul citat.','Nu este tratamentul citat.']],
 [8,'Distractorii sunt agenți hemostatici reali.'],['DDAVP','von Willenbrand'],[2]),

q('perioperator-adv-031',['La pacientul cu BRC, reprezintă indicație de dializă perioperatorie:',
 ['hiperkaliemia amenințătoare de viață','hipokaliemia ușoară fără aritmii','acidoza metabolică corectată cu bicarbonat','anemia normocromă normocitară cronică','coagulopatia asociată heparinizării de dializă'],'A',3,'Pacientul cu disfuncție renală',
 'Recunoașterea indicațiilor dializei perioperatorii.',
 ['Hiperkaliemia amenințătoare de viață este indicație.','Nu este indicație.','Acidoza refractară, nu cea corectată, este indicație.','Anemia este de obicei bine tolerată.','Nu este indicație de dializă.']],
 [8,'Distractorii sunt probleme reale ale BRC.'],['acidoza refractară','hiperkalemia']),

q('perioperator-adv-013',['Evaluarea hepatică preoperatorie:',
 ['NASH este cea mai frecventă boală hepatică cronică în SUA','testele hepatice de rutină nu se recomandă la asimptomatici','biopsia hepatică rămâne standardul de aur','hepatita alcoolică este cea mai frecventă cauză în SUA','serologia a înlocuit biopsia în stadializare'],'ABC',3,'Pacientul cu disfuncție hepatică',
 'Aplicarea evaluării hepatice preoperatorii.',
 ['Steatohepatita non-alcoolică este cea mai frecventă cauză în SUA.','Testele de rutină nu se recomandă la asimptomatici fără risc.','Biopsia rămâne standardul de aur.','NASH este cea mai frecventă.','Biopsia rămâne standardul de aur.']],
 [8,'Distractorii inversează etiologia și rolul biopsiei.'],['non-alcoolică','standardul de aur']),

q('perioperator-adv-021',['Conform Tabelului 1-1, contraindică chirurgia electivă la pacientul hepatic:',
 ['hepatita virală acută','injuria renală acută','cardiomiopatia','ciroza Child A','coagulopatia corectabilă'],'ABC',3,'Tabelul 1-1',
 'Recunoașterea contraindicațiilor chirurgiei elective hepatice.',
 ['Hepatita virală acută este contraindicație.','IRA este contraindicație.','Cardiomiopatia este contraindicație.','Chirurgia este bine tolerată în Child A.','Doar coagulopatia severă refractară este contraindicație.']],
 [8,'Distractorii sunt situații în care chirurgia este posibilă.'],['Hepatita virală acută','Cardiomiopatia']),

q('perioperator-adv-004',['Chirurgia electivă la pacientul cirotic:',
 ['este în general bine tolerată în clasa Child A','este posibilă cu pregătire în clasa Child B','este contraindicată în clasa Child C','este contraindicată în toate cazurile Child B','se evaluează și prin MELD (bilirubină, creatinină, INR)'],'ABCE',3,'Pacientul cu disfuncție hepatică',
 'Aplicarea clasificării Child-Pugh la decizia chirurgicală.',
 ['Child A tolerează bine chirurgia electivă.','Child B este posibilă cu pregătire, cu excepții.','Child C contraindică chirurgia electivă.','Excepțiile Child B sunt rezecțiile hepatice extinse și chirurgia cardiacă.','MELD folosește bilirubina, creatinina și INR.']],
 [8,'Distractorii generalizează contraindicațiile.'],['Child A','Child C']),

q('perioperator-adv-022',['Conform Tabelului 1-2 (Child-Pugh):',
 ['clasa A are albumină peste 3,5 g/dL','clasa B are mortalitate de 40%','clasa C are bilirubină peste 3,0 mg/dL','clasa A are mortalitate de 40%','clasa C are albumină 3,0–3,5 g/dL'],'ABC',4,'Tabelul 1-2',
 'Fixarea criteriilor clasificării Child-Pugh.',
 ['Clasa A: albumină >3,5.','Clasa B: mortalitate 40%.','Clasa C: bilirubină >3,0.','Clasa A are mortalitate <10%.','Albumina 3,0–3,5 corespunde clasei B.']],
 [8,'Valorile sunt permutate între clase.'],['3,0-3,5','Acceptabil'],[3]),

q('perioperator-adv-032',['Scorul MELD:',
 ['se bazează pe bilirubină, creatinină și INR','variază între 6 și 40','peste 8 la colecistectomia laparoscopică: mortalitate ~6%','12–15 în chirurgia abdominală: mortalitate ~25%','se bazează pe albumină, ascită și encefalopatie'],'ABCD',3,'Pacientul cu disfuncție hepatică — MELD',
 'Aplicarea scorului MELD în estimarea mortalității.',
 ['MELD folosește bilirubina, creatinina și INR.','Scorul variază între 6 și 40.','MELD >8 la colecistectomia laparoscopică: ~6%.','MELD 12–15: mortalitate 25%.','Acestea sunt criterii Child-Pugh.']],
 [8,'Singurul distractor preia criteriile Child-Pugh.'],['creatininei','12-15']),

q('perioperator-adv-025',['Controlul preoperator al ascitei:',
 ['include restricție sodată de maximum 2 g/zi','folosește spironolactonă asociată cu furosemid','poate include șunt porto-sistemic transjugular','include restricție sodată de 6–8 g/zi','se face prin drenaj intraoperator, cu efect definitiv'],'ABC',4,'Pacientul cu disfuncție hepatică — Ascita',
 'Aplicarea controlului preoperator al ascitei.',
 ['Restricția sodată este de maximum 2 g/zi.','Se asociază spironolactonă și furosemid.','TIPS este recomandat în controlul ascitei.','Restricția este de maximum 2 g/zi.','Ascita drenată se reacumulează în câteva zile.']],
 [8,'Distractorii contrazic restricția și evoluția ascitei.'],['2g/zi','spironolactonă'],[3]),

q('perioperator-adv-014',['Sindromul de sevraj etanolic perioperator:',
 ['are simptome majore maxime de obicei în ziua 3','poate debuta cu simptome ușoare între zilele 1 și 5','poate fi prevenit prin benzodiazepine profilactice','are mortalitate de până la 50% în delirium tremens netratat','are mortalitate de 50% și sub tratament adecvat'],'ABCD',4,'Pacientul cu disfuncție hepatică — Sevrajul',
 'Recunoașterea cronologiei și tratamentului sevrajului.',
 ['Simptomele majore sunt maxime în ziua 3.','Simptomele ușoare debutează între zilele 1 și 5.','Benzodiazepinele profilactice pot preveni simptomele majore.','Delirium tremens netratat are mortalitate de până la 50%.','Tratamentul reduce mortalitatea la 10%.']],
 [8,'Singurul distractor neagă efectul tratamentului.'],['ziua 3','benzodiazepinele']),

q('perioperator-adv-024',['Sindromul Wernicke-Korsakoff poate apărea perioperator dacă:',
 ['tiamina nu este administrată înaintea glucozei','glucoza nu este administrată înaintea tiaminei','magneziul nu este administrat înaintea potasiului','benzodiazepinele sunt administrate profilactic','folații nu sunt administrați înaintea vitaminei K'],'A',4,'Pacientul cu disfuncție hepatică — Deficitele',
 'Recunoașterea condiției de apariție a sindromului Wernicke-Korsakoff.',
 ['Sindromul apare dacă tiamina nu precede glucoza.','Ordinea este inversată.','Nu este condiția citată.','Nu este condiția citată.','Nu este condiția citată.']],
 [8,'Distractorii inversează ordinea sau înlocuiesc substanța.'],['Wernicke','tiamina']),

q('perioperator-adv-033',['La pacientul diabetic evaluat preoperator:',
 ['gastropareza crește riscul de aspirație','clapotajul gastric pe nemâncate sugerează gastropareză','pulsul periferic poate fi prezent în ischemia tisulară','hiperglicemia afectează în special activitatea fagocitară','afectarea vasculară interesează în special vasele mari'],'ABCD',4,'Pacientul diabetic',
 'Recunoașterea complicațiilor diabetului relevante perioperator.',
 ['Gastropareza întârzie evacuarea și crește riscul de aspirație.','Clapotajul pe stomacul care ar trebui gol sugerează gastropareza.','Afectarea vaselor mici permite puls periferic prezent.','Hiperglicemia afectează în special fagocitoza.','Sunt afectate în special vasele mici.']],
 [8,'Singurul distractor inversează calibrul vaselor afectate.'],['clapotajul','fagocitară']),

q('perioperator-adv-005',['Controlul glicemic perioperator:',
 ['urmărește o glicemie de 120–180 mg/dL','preferă valorile spre limita inferioară a intervalului','nu exclude cetoacidoza la glicemii sub 250 mg/dL','folosește ca standard infuzia intravenoasă de insulină','urmărește o glicemie de 80–110 mg/dL'],'AC',5,'Pacientul diabetic — Management',
 'Aplicarea țintelor glicemice perioperatorii.',
 ['Ținta este 120–180 mg/dL.','Nu: limita superioară se preferă din cauza riscului de hipoglicemie.','CAD depinde de absența insulinei, nu de glicemie.','Scala subcutanată este metoda standard.','Ținta este 120–180 mg/dL.']],
 [8,'Distractorii schimbă ținta și metoda standard.'],['120-180','250 mg/']),

q('perioperator-adv-023',['Managementul perioperator al insulinei:',
 ['insulina rapidă se oprește la începerea postului','insulina lungă: 2/3 din doza de seară','antidiabeticele orale lungi se opresc cu 48–72 de ore înainte','glucoza 5% asigură 25 g glucoză pe oră','glicemia se monitorizează la fiecare 12 ore'],'ABC',5,'Pacientul diabetic — Management',
 'Aplicarea ajustării perioperatorii a antidiabeticelor.',
 ['Insulina rapidă se oprește când pacientul nu se mai alimentează.','Se administrează 2/3 din doza de seară în noaptea dinainte.','Preparatele orale lungi se opresc cu 48–72 de ore înainte.','Infuzia asigură 10 g glucoză pe oră.','Monitorizarea se face cel puțin la 6 ore.']],
 [8,'Distractorii schimbă aportul și frecvența monitorizării.'],['48-72 de ore','2/3 din doza']),

q('perioperator-adv-015',['Conform Tabelului 1-3, substituția glucocorticoidă:',
 ['nu necesită suplimentare la cura herniei inghinale','folosește 50 mg hidrocortizon IV la artroplastia de șold','folosește 100 mg hidrocortizon IV la esofagogastrectomie','folosește 100 mg hidrocortizon IV la artroplastia de șold','omite doza matinală de steroid'],'ABC',5,'Tabelul 1-3',
 'Aplicarea dozelor de substituție după stresul chirurgical.',
 ['Procedurile minore nu necesită suplimentare.','Stresul moderat primește 50 mg IV, apoi 25 mg la 8 ore.','Stresul major primește 100 mg IV la inducție.','Artroplastia de șold este stres moderat.','Doza matinală se administrează în toate situațiile.']],
 [8,'Distractorii mută intervențiile între categorii.'],['hidrocortizon IV','esofagogastrectomie']),

q('perioperator-adv-006',['Chirurgia la pacienta gravidă:',
 ['se preferă, când este necesară, în al doilea trimestru','laparoscopia este sigură în trimestrul doi cu presiune redusă','volumul plasmatic scăzut accentuează hipovolemia','se preferă, când este necesară, în primul trimestru','declanșarea travaliului se datorează în principal anesteziei'],'AB',6,'Pacienta însărcinată',
 'Aplicarea principiilor chirurgiei în sarcină.',
 ['Trimestrul doi are cel mai mic risc de avort și travaliu prematur.','Laparoscopia se poate face cu presiune de insuflație redusă.','Nu: volumul plasmatic crescut din sarcină poate masca hipovolemia.','Se preferă trimestrul doi.','Travaliul pare determinat de patologie, nu de anestezie.']],
 [8,'Distractorii schimbă trimestrul și cauza travaliului.'],['al doilea trimestru','presiunii']),

q('perioperator-adv-035',['Modificările fiziologice din sarcină:',
 ['ventilația pe minut crescută scade PaCO2','refluxul se datorează în principal evacuării gastrice întârziate','hematocritul scade prin diluție','capacitatea reziduală funcțională crește','leucocitoza crește utilitatea hemogramei'],'ABC',6,'Pacienta însărcinată',
 'Recunoașterea modificărilor respiratorii, digestive și hematologice.',
 ['Creșterea ventilației pe minut scade PaCO2.','Progesteronul întârzie evacuarea gastrică.','Volumul plasmatic crește mai mult decât cel eritrocitar.','CRF scade prin uterul mărit.','Leucocitoza de sarcină reduce utilitatea analizei.']],
 [8,'Distractorii inversează efectul uterului și al leucocitozei.'],['progesteronului','capacităţii reziduale funcţionale']),

q('perioperator-adv-026',['În sarcină:',
 ['boala hemoroidală apare sau se agravează la 1/3 din gravide','una din 14 sarcini se complică cu traumă','CID poate apărea în câteva ore de la dezlipirea de placentă','semnele clasice de șoc exclud suferința fetală','vena cavă este comprimată mai ales în decubit ventral'],'ABC',6,'Pacienta însărcinată',
 'Fixarea complicațiilor și a datelor epidemiologice din sarcină.',
 ['Compresia venoasă pelvină produce hemoroizi la 1/3 din gravide.','Una din 14 sarcini se complică cu traumă.','CID apare în câteva ore de la dezlipire sau embolie amniotică.','Semnele de șoc semnifică suferință fetală în evoluție.','Compresia apare în decubit dorsal.']],
 [8,'Distractorii inversează semnificația șocului și poziția.'],['14 sarcini','lichid amniotic'],[5]),

q('perioperator-adv-016',['La gravida traumatizată:',
 ['pierderea fătului apare la 15% în trauma severă','dezlipirea de placentă poate urma unei traume minore','uterul dur, mărit, sugerează ruptura de placentă','dezlipirea de placentă se însoțește constant de sângerare vaginală','semnele vitale materne normale exclud suferința fetală'],'ABC',6,'Pacienta însărcinată — Trauma',
 'Recunoașterea complicațiilor obstetricale ale traumei.',
 ['Pierderea fătului apare în 15% din trauma severă.','Dezlipirea poate urma traumelor minore.','Uterul dur, mai mare decât vârsta gestațională, sugerează ruptura.','Sângerarea vaginală nu este întotdeauna prezentă.','Semnele vitale normale pot masca suferința fetală.']],
 [8,'Distractorii contrazic capcanele clinice descrise.'],['15% din gravidele','uter dur']),

q('perioperator-adv-036',['La gravida traumatizată:',
 ['explorarea chirurgicală se indică la hemoragie intraperitoneală','explorările paraclinice necesare nu se evită de teama teratogenității','gravidele Rh-negative primesc imunoglobulină anti-D','testul de sarcină se face la orice femeie fertilă traumatizată','monitorizarea fetală se amână după stabilizarea mamei'],'ABCD',6,'Pacienta însărcinată — Trauma',
 'Aplicarea conduitei la gravida traumatizată.',
 ['Hemoragia intraperitoneală indică explorarea.','Explorările trebuie recomandate, nu evitate.','Excepție: leziunea minoră la distanță de uter.','Testul de sarcină se face la orice femeie fertilă cu traumă.','Monitorizarea fetală precoce este esențială.']],
 [8,'Singurul distractor amână monitorizarea fetală.'],['anti-D','teratogen']),

q('perioperator-adv-017',['Consimțământul informat:',
 ['este un proces, nu un moment','se reduce la semnarea formularului','se obține adesea în mai multe sesiuni','se obține de regulă într-o singură discuție','exclude prezentarea opțiunii de a nu opera'],'AC',7,'Consimțământul informat',
 'Aplicarea conceptului de consimțământ informat.',
 ['Consimțământul este un proces, nu un moment.','Nu: formularul doar consemnează rezultatul discuțiilor.','Adesea se obține în mai multe sesiuni.','Se obține adesea în mai multe sesiuni.','Opțiunea de a nu se opera trebuie discutată.']],
 [8,'Distractorii reduc consimțământul la o formalitate.'],['un proces','mai multe sesiuni'],[6]),

q('perioperator-adv-027',['Când pacientul nu poate decide:',
 ['înlocuitorul este de obicei ruda cea mai apropiată','directiva în avans exprimă nivelul de îngrijire dorit','directiva în avans este un document legal','formularul de consimțământ înlocuiește directiva în avans','înlocuitorul este desemnat de regulă de chirurg'],'ABC',7,'Consimțământul informat — Înlocuitorul',
 'Aplicarea conceptelor de înlocuitor și directivă în avans.',
 ['Înlocuitorul este de obicei ruda cu gradul cel mai apropiat.','Directiva exprimă nivelul de îngrijire dorit.','Directiva în avans este un document legal.','Sunt documente diferite.','Înlocuitorul este de obicei ruda cea mai apropiată.']],
 [8,'Distractorii confundă documentele și rolurile.'],['surrogate','directiva în avans']),

q('perioperator-adv-037',['Foaia de observație:',
 ['are trei obiective principale','consemnează imediat postoperator pierderile sanguine și diureza','include în biletul de externare planul de urmărire','biletul de externare cuprinde fiecare detaliu','poate propaga informații false prin copiere'],'ABCE',7,'Documentația',
 'Aplicarea regulilor de documentare medicală.',
 ['Foaia are 3 obiective principale.','Se notează complicațiile, pierderile sanguine, refacerea volemică și diureza.','Biletul include planul de urmărire.','Biletul nu trebuie să menționeze fiecare detaliu.','Copierea electronică poate propaga informații false.']],
 [8,'Distractorii contrazic regulile de concizie și siguranță.'],['3 obiective','Biletul de externare']),

q('perioperator-adv-038',['Înștiințarea medicului este cerută când drenajul toracic depășește:',
 ['100 mL/oră','50 mL/oră','200 mL/oră','30 mL/oră','500 mL/oră'],'A',8,'Recomandări medicale',
 'Fixarea pragurilor de înștiințare din recomandările medicale.',
 ['Drenajul toracic >100 mL/oră impune înștiințarea.','Nu este pragul citat.','Nu este pragul citat.','30 mL/oră este pragul pentru diureză.','Nu este pragul citat.']],
 [8,'Distractorii includ pragul diurezei.'],['30 mL/oră','drenaj toracic']),

q('perioperator-adv-018',['Sondele digestive perioperatorii:',
 ['sonda nazo-gastrică de tip sifon se folosește în aspirație continuă','sondele nazo-enterale de alimentație sunt rigide, cu lumen larg','poziția sondei de alimentație se confirmă sigur prin radiografie','auscultația epigastrică confirmă sigur poziția gastrică','sonda de tip sifon se folosește în aspirație intermitentă'],'AC',8,'Sonde și tuburi de dren',
 'Aplicarea utilizării în siguranță a sondelor digestive.',
 ['Sonda de tip sifon se folosește în aspirație continuă.','Nu: sondele de alimentație sunt moi, cu lumen subțire.','Radiografia sau palparea intraoperatorie confirmă poziția.','Auscultația poate fi înșelătoare.','Se folosește în aspirație continuă.']],
 [8,'Distractorii contrazic regulile de siguranță.'],['sifon','poate fi înşelătoare']),

q('perioperator-adv-019',['Sondele și drenurile toracice și respiratorii:',
 ['tubul toracic folosește de obicei aspirație de 20 cm H2O','drenajul sub apă previne pătrunderea aerului în pleură','sonda de traheostomă servește ventilației pe termen lung','sonda endotraheală servește ventilației pe termen lung','tubul toracic folosește de obicei aspirație de 50 cm H2O'],'ABC',9,'Sondele de tract respirator',
 'Recunoașterea funcțiilor tuburilor toracice și ale sondelor respiratorii.',
 ['Aspirația continuă este de obicei 20 cm H2O.','Drenajul sub apă previne pătrunderea aerului.','Traheostoma se folosește pentru ventilație pe termen lung.','Sonda endotraheală servește ventilației pe termen scurt.','Valoarea este de 20 cm H2O.']],
 [8,'Distractorii inversează durata și valoarea aspirației.'],['20 cm H2O','drenaj sub apă']),

q('perioperator-adv-039',['Drenurile chirurgicale:',
 ['Jackson-Pratt și Hemovac sunt drenuri închise aspirative','drenurile Davol se folosesc pentru drenaj dens sau particulat','drenajul Penrose este o cale cu dublu-sens pentru bacterii','cateterele pigtail sunt un exemplu de drenaj pasiv','drenajul Penrose se conectează la aspirație continuă'],'ABCD',9,'Drenurile chirurgicale',
 'Diferențierea tipurilor de drenuri chirurgicale.',
 ['Jackson-Pratt și Hemovac sunt drenuri cu sistem închis de aspirație.','Drenurile Davol sunt folosite pentru drenaj dens sau particulat.','Penrose nu are aspirație și permite bacteriilor dublu sens.','Cateterele pigtail sunt drenaje pasive.','Penrose este un drenaj pasiv, fără aspirație.']],
 [8,'Singurul distractor inversează mecanismul Penrose.'],['Jackson-Pratt','pigtail']),

q('perioperator-adv-028',['Îngrijirea plăgilor per secundam:',
 ['folosește o meșă îmbibată cu ser fiziologic','evită împachetarea strânsă a cavității','folosește soluția Dakin fără avantaj față de ser','folosește soluția Dakin, superioară serului fiziologic','se aplică tipic după suturarea marginilor plăgii'],'ABC',9,'Îngrijirea plăgilor',
 'Aplicarea îngrijirii plăgilor lăsate deschise.',
 ['Meșa îmbibată cu ser umple cavitatea.','Împachetarea strânsă produce ischemie tisulară.','Soluțiile de meșă nu au avantaj față de serul steril.','Nu există avantaj față de ser.','Marginile rămân neapoziționate.']],
 [8,'Distractorii inversează comparația soluțiilor și definiția.'],['Dakin','ischemie tisulară']),

q('perioperator-adv-007',['Atelectazia postoperatorie:',
 ['afectează până la 90% dintre pacienții cu anestezie generală','este favorizată de anestezicele generale, indiferent de agent','este redusă semnificativ de chirurgia minim invazivă','apare doar după anestezicele inhalatorii','crește fracția de șunt și produce hipoxie'],'ABCE',10,'Atelectazia',
 'Recunoașterea mecanismelor și a prevenției atelectaziei.',
 ['Afectează până la 90% dintre pacienții cu anestezie generală.','Colabarea alveolară este favorizată indiferent de agent.','Chirurgia minim invazivă reduce incidența.','Apare indiferent de agentul anestezic.','Atelectazia crește fracția de șunt și produce hipoxie.']],
 [8,'Singurul distractor restrânge cauza la un tip de agent.'],['90%','şunt'],[9]),

q('perioperator-adv-020',['Complicațiile plăgii chirurgicale:',
 ['scurgerea spontană de lichid seros precede dehiscența fascială','infecția de plagă apare la 2–5% dintre pacienții chirurgicali','tahicardia poate fi primul semn al infecției de plagă','infecția de plagă este cea mai frecventă infecție nosocomială','dehiscența fascială acută se tratează conservator'],'ABC',10,'Dehiscența și infecțiile plăgii',
 'Recunoașterea semnelor și frecvenței complicațiilor plăgii.',
 ['Lichidul seros spontan precede dehiscența fascială acută.','Infecția apare la 2–5%.','Tahicardia poate fi primul semn.','Este a doua cea mai frecventă infecție nosocomială.','Plaga se examinează și se închide în sala de operație.']],
 [8,'Distractorii schimbă rangul și conduita.'],['lichid seros','2-5%']),

q('perioperator-adv-040',['Infecția plăgii chirurgicale:',
 ['reprezintă un sfert din infecțiile nosocomiale','se tratează în primul rând prin drenaj prompt','cu drenaj spontan indică recunoaștere precoce','se tratează în primul rând prin antibiotice','reprezintă jumătate din infecțiile nosocomiale'],'AB',10,'Infecțiile plăgii chirurgicale',
 'Aplicarea conduitei în infecția de plagă.',
 ['Reprezintă un sfert din infecțiile nosocomiale.','Drenajul prompt minimizează consecințele.','Drenajul spontan indică întârziere în recunoaștere.','Antibioticele au rol secundar.','Proporția este un sfert.']],
 [8,'Distractorii inversează rolul antibioticelor și semnificația drenajului.'],['un sfert','Drenajul prompt']),

q('perioperator-adv-029',['Febra postoperatorie, conform ghidului SCCM:',
 ['se investighează de la 37,5°C','se evaluează întâi prin analiza circumstanțelor','impune examen fizic țintit înaintea testelor','impune culturi și imagistică de primă intenție','este o stare postoperatorie normală, fără investigații'],'BC',10,'Febra',
 'Aplicarea etapelor de evaluare a febrei postoperatorii.',
 ['Nu: investigațiile încep la ≥38,3°C.','Primul pas este analiza circumstanțelor.','Al doilea pas este examenul fizic țintit.','Testele urmează abia după cei doi pași.','Nu este o stare normală.']],
 [8,'Distractorii inversează ordinea evaluării.'],['38,3','examenul fizic']),

q('perioperator-adv-008',['Conform National Quality Forum, reprezintă o situație care nu trebuie să aibă loc niciodată:',
 ['chirurgia pe partea greșită a corpului','febra postoperatorie de 38,3°C în prima zi','atelectazia segmentară din primele zile postoperator','infecția superficială de plagă chirurgicală','necesitatea transfuziei intraoperatorii'],'A',11,'Tabelul 1-5',
 'Recunoașterea evenimentelor din lista National Quality Forum.',
 ['Chirurgia pe partea greșită este inclusă în Tabelul 1-5.','Este o complicație, nu un eveniment din listă.','Este o complicație, nu un eveniment din listă.','Este o complicație, nu un eveniment din listă.','Nu este inclusă în listă.']],
 [8,'Distractorii sunt complicații postoperatorii reale.'],['partea greşită','National Quality Forum']),

q('perioperator-adv-030',['Siguranța perioperatorie a pacientului:',
 ['raportul IOM estimează 44.000–98.000 de decese anuale prin erori','NSQIP oferă estimarea rezultatului ajustată la risc','campania 100.000 Lives a salvat aproximativ 12.000 de vieți','campania 100.000 Lives a promovat 12 strategii','NSQIP a fost dezvoltat de Joint Commission'],'AB',11,'Siguranța perioperatorie',
 'Fixarea inițiativelor de siguranță perioperatorie.',
 ['IOM estimează 44.000–98.000 de decese anuale.','NSQIP oferă estimări ajustate la risc.','Nu: campania a salvat aproximativ 122.000 de vieți.','Campania a promovat 6 strategii.','NSQIP a fost dezvoltat de Department of Veterans Affairs.']],
 [8,'Distractorii schimbă numărul strategiilor și autorul.'],['44.000-98.000','NSQIP'],[12]),
];
