import {advancedQuestion} from './advanced-author';
import type {SourceRow} from './source-author';
const pdfOffset=(p:number)=>p<=961?p-789:p<=972?p-790:p-792;
const q=(n:number,row:SourceRow,score:number,reason:string,expressions:string[],related:number[]=[])=>
 advancedQuestion('pneumologie',28,pdfOffset,`pneumologie-adv-${String(n).padStart(3,'0')}`,row,[score,reason],expressions,undefined,related);

export const PNEUMOLOGIE_D=[
q(103,['Identificați afirmația corectă referitoare la tusea cronică de cauză medicamentoasă:',
 ['În evaluarea tusei cronice trebuie verificat dacă pacientul ia un inhibitor al enzimei de conversie a angiotensinei','IECA-urile sunt tratamentul de primă intenție al rinoreei posterioare','Beta-blocantele sub formă de picături oculare înlocuiesc IECA-ul ca unică măsură empirică','Tusea indusă de IECA se tratează cu 8 săptămâni de corticosteroid topic nazal','Manometria esofagiană se face înainte de a întreba despre IECA'],'A',949,'Tusea cronică — Cauze medicamentoase',
 'Reținerea verificării IECA înaintea investigațiilor de treaptă superioară.',
 ['Textul cere explicit să vă asigurați că pacientul nu ia un IECA.','Rinoreea posterioară se abordează cu corticosteroid topic nazal, nu cu IECA.','Picăturile beta-blocante țin de astm, nu înlocuiesc verificarea IECA.','Corticosteroidul nazal este pentru rinoree, nu pentru tusea de IECA.','Manometria este o investigație ulterioară, după eșecul empiric, nu primul pas.']],
 8,'IECA-ul stă pe aceeași listă cu IPP și corticosteroidul, deci se inversează ușor ca „tratament” în loc de cauză.',['inhibitor al enzimei','tusea cronică']),

q(104,['Dacă tusea cronică nu se rezolvă după tratamentul empiric, investigațiile ulterioare pot include:',
 ['CT toracic și bronhoscopie','Test de provocare bronșică','Manometrie esofagiană și imagistică sinusală','Scintigrafie de ventilație-perfuzie ca primă investigație, fără anamneză','Oprirea oricărei evaluări, diagnosticul fiind închis după 3 zile de IPP'],'ABC',949,'Tusea cronică — Investigații ulterioare',
 'Recunoașterea pachetului de investigații de treaptă a doua, distinct de probele empirice.',
 ['CT-ul toracic și bronhoscopia figurează pe listă.','Testul de provocare bronșică este enumerat.','Manometria esofagiană și imagistica sinusală închid lista.','Scintigrafia V/Q nu este investigația citată aici.','Textul prevede investigații, nu închiderea după 3 zile de IPP.']],
 8,'Lista de investigații (CT, bronhoscopie, manometrie) este ușor de înlocuit cu probele empirice de pe aceeași pagină.',['bronhoscopie','imagistică sinusală']),

q(105,['Prevalența astmului, dincolo de cifrele mondiale, se caracterizează prin:',
 ['Creștere în multe țări de la jumătatea anilor 1980, îndeosebi la copii și adulți tineri, afectând până la 15% din populație','Studii ocupaționale care sugerează că 15–20% din forța de muncă ar putea deveni astmatică dacă ar fi expusă unor factori puternic sensibilizanți','Rate mai scăzute în Europa Centrală și de Est față de Marea Britanie','Debut clasic după 70 de ani, fără forme pediatrice','O genă singulară, suficientă pentru a explica boala, independent de mediu'],'ABC',949,'Astmul — Prevalență; Genetică',
 'Separarea plafonului de 15% și a estimării ocupaționale 15–20% de geografia vest versus est.',
 ['Creșterea de la mijlocul anilor 1980 și plafonul de 15% sunt explicite.','Intervalul 15–20% din forța de muncă este citat.','Europa Centrală și de Est figurează printre zonele cu rate mai scăzute.','Debutul clasic este între 3 și 5 ani.','Textul precizează că nu există o genă singulară.']],
 8,'15% populațional și 15–20% ocupațional stau pe aceeași pagină și se confundă ușor cu 300 de milioane.',['15% din populaţie','15-20%']),

q(106,['Alte fenotipuri clinice de astm recunoscute în text includ:',
 ['Astmul instabil (brittle asthma) și astmul cortico-rezistent','Bronșita eozinofilică, cu eozinofilie în spută fără wheezing','Astmul ocupând 90% din forța de muncă, fără endotipuri','Lipsa oricărei inflamații eozinofilice, ca regulă a astmului persistent','Bronșita eozinofilică, definită prin wheezing fără eozinofile'],'AB',949,'Alte fenotipuri clinice',
 'Diferențierea endotipurilor (brittle, cortico-rezistent) de bronșita eozinofilică fără wheezing.',
 ['Cele două subtipuri sunt numite explicit.','Bronșita eozinofilică este descrisă cu eozinofilie de spută fără wheezing.','Textul vorbește de endotipuri, nu de 90% ocupațional.','Inflamația eozinofilică este deseori prezentă.','Wheezing-ul lipsește, nu eozinofilele, în bronșita eozinofilică.']],
 8,'Capcana este inversarea eozinofilie/wheezing din definiția bronșitei eozinofilice.',['brittle asthma','bronşită eozino']),

q(107,['Alegeți afirmațiile corecte referitoare la mecanismele astmului ocupațional:',
 ['Compușii cu greutate moleculară mică (izocianați, anhidride acide) se leagă de celulele epiteliale și furnizează haptene recunoscute de limfocitele T','Compușii cu greutate moleculară mare (făină, pulberi organice) implică anticorpi IgE specifici','Indivizii atopici dezvoltă astm ocupațional mai repede la agenții care induc IgE specific','Non-atopicii sunt protejați complet, indiferent de durata expunerii','Haptenele sunt rezervate compușilor proteici de mare greutate moleculară'],'ABC',950,'Sensibilizanții ocupaționali — Mecanisme',
 'Contrastul haptenă/limfocit T versus IgE, plus viteza mai mare la atopici.',
 ['Mecanismul haptenic al compușilor mici este descris.','Compușii mari implică IgE.','Atopicii dezvoltă boala mai repede la aceiași agenți.','Non-atopicii pot dezvolta astm după o expunere mai lungă.','Haptenele țin de greutatea moleculară mică, nu de proteinele mari.']],
 8,'Inversează haptenă versus IgE și viteza atopic versus non-atopic.',['haptene recunoscute','mai repede când sunt expuşi']),

q(108,['Radiografia toracică în astm:',
 ['Nu există elemente diagnostice pe radiografia toracică','Hiperinflația este caracteristică episoadelor acute sau formelor cronice severe','Poate fi utilă pentru excluderea unui pneumotorax sau pentru detecția infiltratelor din aspergiloza bronhopulmonară alergică','Este suficientă pentru diagnosticul pozitiv, fără spirometrie','Hiperinflația lipsește sistematic, chiar în criza acută'],'ABC',951,'Investigații — Radiografia toracică',
 'Reținerea absenței semnelor diagnostice și a celor două indicații (pneumotorax, ABPA).',
 ['Absența elementelor diagnostice este explicită.','Hiperinflația în acut/sever cronic este caracteristică.','Pneumotoraxul și ABPA sunt indicațiile citate.','Diagnosticul nu se pune pe radiografie.','Hiperinflația este tocmai semnul descris în criză.']],
 8,'ABPA și pneumotoraxul stau pe aceeași frază și se omit ușor când se reține doar „radiografie normală”.',['Nu există elemente diagnostice','aspergilozei bronho']),

q(109,['Testele alergologice în diagnosticul astmului:',
 ['Testele cutanate prick ar trebui efectuate în toate cazurile, pentru identificarea factorilor declanșatori','IgE alergen-specifice se pot măsura în ser dacă nu sunt disponibile facilități pentru prick, pacientul ia antihistaminic sau lipsesc extracte adecvate','Provocarea alergenică inhalatorie este testul de primă linie în astmul obișnuit','Prick-ul se omite sistematic la copii','IgE specifice înlocuiesc spirometria ca unic criteriu de reversibilitate'],'AB',951,'Testele cutanate; Provocarea alergenică',
 'Ierarhia prick universal versus IgE serică ca alternativă, distinct de provocarea ocupațională.',
 ['Indicația de prick în toate cazurile este explicită.','Cele trei situații pentru IgE serică sunt listate.','Provocarea inhalatorie este instrument de cercetare, necesară în ocupațional, nu în formele obișnuite.','Copiii nu sunt excluși.','Reversibilitatea se demonstrează spirometric, nu prin IgE.']],
 8,'Provocarea ocupațională se mută ușor ca test universal, deși textul o rezervă cercetării.',['Testele cutanate prick','lgE alergen']),

q(110,['Prognosticul astmului ocupațional după încetarea expunerii, conform textului, este că:',
 ['În jur de o treime dintre indivizii sensibilizați ar putea fi vindecați dacă evită permanent expunerea','Vindecarea este certă la 90% în prima săptămână, fără evicție','Evicția este inutilă, boala fiind autonomă după sensibilizare','O treime se vindecă doar dacă continuă expunerea, pentru desensibilizare','Vindecarea cere transplant pulmonar, nu evicție'],'A',952,'Controlul factorilor externi — Ocupațional',
 'Reținerea ponderii de o treime și a condiției de evicție permanentă.',
 ['Cifra de o treime și evicția permanentă sunt juxtapuse.','90% în o săptămână nu este cifra din text.','Evicția este condiția vindecării, nu o măsură inutilă.','Continuarea expunerii nu vindecă.','Transplantul nu figurează ca terapie a astmului ocupațional.']],
 8,'„O treime” se confundă ușor cu 15% din totalul cazurilor de astm ocupațional de pe pagina anterioară.',['o treime din indivizii','evite permanent expunerea']),

q(111,['Efectele nedorite și ajustarea dozei de corticosteroizi inhalatori:',
 ['Candidoza orală și disfonia impun clătirea gurii după inhalator','Cataracta subcapsulară este rară, dar poate apărea la vârstnici','Osteoporoza este mai puțin probabilă decât la steroizii orali, dar poate apărea la doze mari (beclometazonă sau budesonid >800 µg zilnic)','La copii, doze >400 µg/zi s-au asociat cu întârzierea creșterii pe termen scurt, fără afectarea înălțimii finale','Doza trebuie crescută automat odată ce astmul este controlat, fără treaptă inferioară'],'ABCD',953,'Corticosteroizii inhalatori — Efecte secundare',
 'Integrarea pragurilor 800 µg (osteoporoză) și 400 µg (creștere) cu clătirea gurii.',
 ['Candidoza și disfonia, cu clătire, sunt primele efecte listate.','Cataracta rară la vârstnici este citată.','Comparația cu oralii și pragul >800 µg sunt explicite.','Întârzierea scurtă fără afectarea înălțimii finale este precizată.','Textul cere reducerea pe o treaptă inferioară odată controlat.']],
 8,'Cele două praguri (400 versus 800 µg) și mitul înălțimii finale se inversează ușor.',['candidoza orală','800 r1g zilnic']),

q(112,['Terapii speciale în astmul sever:',
 ['Termoplastia bronșică folosește curent de radiofrecvență pentru a încălzi peretele bronșic și a reduce masa de mușchi neted','Mepolizumab, reslizumab și benralizumab acționează împotriva IL-5 sau a receptorului acesteia și sunt cost-eficace la exacerbări recurente sub CSI în doză mare','Sunt în dezvoltare anticorpi împotriva citokinelor Th2, precum limfopoietina stromală timică','Termoplastia înlocuiește oxigenul de urgență în exacerbarea amenințătoare de viață','Anti-IL-5 sunt indicați ca monoterapie de primă linie în astmul intermitent ușor'],'ABC',954,'Termoplastia bronșică; Anticorpii anti-IL-5',
 'Separarea termoplastiei (radiofrecvență, masă musculară) de biologicele anti-IL-5.',
 ['Mecanismul radiofrecvență/mușchi neted este descris.','Cei trei anticorpi și indicația de cost-eficacitate sunt listate.','TSLP figurează printre țintele în dezvoltare.','Termoplastia este o procedură electivă, nu de urgență.','Anti-IL-5 țin de astmul eozinofilic cu exacerbări, nu de forma ușoară.']],
 8,'Termoplastia se confundă ușor cu o manevră de urgență, iar anti-IL-5 cu omalizumab anti-IgE.',['Termoplastia bronşică','limfopoie']),

q(113,['Un adult cu exacerbare astmatică și PEF de 180 L/min, tratat prin nebulizare. Conform textului:',
 ['Internarea se impune la un PEF sub 400 L/min, indiferent de răspunsul la nebulizare','Dacă PEF este >150 L/min, pacienții se pot ameliora major cu terapie prin nebulizare și pot să nu necesite internarea','PEF-ul nu ghidează locul de îngrijire','Ameliorarea prin nebulizare este posibilă doar sub 80 L/min','Internarea se decide doar pe baza pulsului paradoxal'],'B',954,'Exacerbările astmatice — Locul de îngrijire',
 'Reținerea pragului de 150 L/min ca fereastră de tratament extra-spitalicesc prin nebulizare.',
 ['400 L/min nu este pragul citat.','Pragul >150 L/min și posibilitatea de a evita internarea sunt explicite.','PEF ghidează explicit locul de îngrijire.','80 L/min nu este cifra din acest paragraf.','Pulsul paradoxal este prezent doar la 45% și nu este esențial.']],
 8,'150 L/min apare și ca PEF amenințător (<33%); direcția inegalității se inversează ușor.',['> 150 L/min','terapie prin nebulizare']),

q(114,['Definiția și contextul sistemic al BPOC, conform textului:',
 ['Este caracterizată prin obstrucție difuză a căilor aeriene care nu este complet reversibilă, de obicei progresivă','Cuprinde emfizem, boala căilor aeriene mici și bronșita cronică','Se asociază frecvent cu boală cardiacă ischemică, hipertensiune, diabet, insuficiență cardiacă și cancer, sugerând un proces inflamator sistemic','Obstrucția este complet reversibilă după un singur bronhodilatator, ca în astmul intermitent','Comorbiditățile cardiovasculare exclud diagnosticul de BPOC'],'ABC',955,'BPOC — Definiție',
 'Recunoașterea caracterului incomplet reversibil și a listei de comorbidități sistemice.',
 ['Definiția de obstrucție incomplet reversibilă este fraza de deschidere.','Cele trei sindroame clinice sunt enumerate.','Lista de comorbidități și interpretarea sistemică sunt explicite.','Reversibilitatea completă ar orienta spre astm.','Comorbiditățile sunt asociate, nu exclud BPOC.']],
 8,'Lista de comorbidități se mută ușor ca criteriu de excludere, deși textul o vede ca proces sistemic.',['nu este complet reversibilă','proces inflamator sistemic']),

q(115,['Clasificarea anatomică a emfizemului și consecințele mecanice includ:',
 ['Emfizemul centro-acinar, cea mai frecventă formă, distensie în jurul bronhiolei terminale cu păstrarea alveolelor distale','Emfizemul pan-acinar, mai puțin frecvent, asociat deficitului de alfa-1-antitripsină, putând transforma plămânul într-o colecție de bule','Emfizemul neregulat, cu fibroză parcelară independentă de structura acinară','Creșterea CPT se datorează pierderii reculului elastic','Emfizemul centro-acinar este forma rară rezervată deficitului de alfa-1-antitripsină'],'ABCD',956,'Emfizemul — Tipuri; Consecințe',
 'Ierarhia centro-acinar (frecvent) versus pan-acinar (AAT) și legătura CPT–recul elastic.',
 ['Distribuția centro-acinară și frecvența maximă sunt descrise.','Pan-acinarul, AAT și bulele sunt juxtapuse.','Forma neregulată independentă de acin este a treia.','Pierderea reculului elastic explică creșterea CPT.','AAT se asociază pan-acinarului, nu centro-acinarului.']],
 8,'Inversează centro- versus pan-acinar ca formă a deficitului de alfa-1-antitripsină.',['Emfizem centro-acinar','reculului elastic']),

q(116,['Măsurarea nivelului seric și a genotipului de alfa-1-antitripsină este recomandată la:',
 ['Toți fumătorii peste 80 de ani cu BPOC ușoară, ca screening de masă','Pacienți nefumători sau cu debut prematur al bolii','Doar copiii cu astm intermitent','Pacienții cu pneumonie comunitară ușoară, fără spirometrie','Niciun pacient, genotipul fiind abandonat'],'B',957,'Investigații — Alfa-1-antitripsină',
 'Reținerea celor două indicații (nefumător, debut prematur), nu a screeningului universal.',
 ['Vârsta înaintată a fumătorului nu este criteriul.','Nefumătorii și debutul prematur sunt indicațiile citate.','Astmul pediatric nu figurează aici.','Pneumonia comunitară nu este indicația.','Măsurarea este recomandată, nu abandonată.']],
 8,'Indicația se lărgește ușor la „toți cu BPOC”, deși textul o limitează la nefumători/debut prematur.',['nefumători sau cu debut prematur','genotipului de o.1-antitripsină']),

q(117,['În studiile de oxigenoterapie continuă citate, dintre cei care nu au primit oxigen pe termen lung au supraviețuit peste 5 ani:',
 ['Aproximativ 30%','Aproximativ 90%','Niciun pacient','Toți pacienții, oxigenul neinfluențând mortalitatea','Doar cei tratați 12 ore/zi, identic cu 19 ore/zi'],'A',958,'Oxigenoterapia — Supraviețuire',
 'Reținerea cifrei de 30% la 5 ani fără LTOT, distinctă de pragul de 19 ore/zi.',
 ['Cifra de 30% este explicită.','90% nu este supraviețuirea fără oxigen.','Supraviețuirea nu este zero.','Oxigenul îmbunătățește supraviețuirea.','Beneficiul substanțial de mortalitate a fost la 19 ore/zi, nu la 12.']],
 8,'30% la 5 ani se confundă cu 19 ore/zi sau cu 15 ore/zi (scăderea presiunii pulmonare).',['30% din cei ce nu au primit','peste 5 ani']),

q(118,['Măsurile adiționale în BPOC, dincolo de flebotomie și Venturi, includ:',
 ['Curele de recuperare respiratorie ameliorează dispneea, astenia și toleranța la efort','O singură doză de vaccin pneumococic polizaharidic polivalent și vaccinare antigripală anuală','Valvele endobronșice obstruează bronhiile din plămânii emfizematoși hiperinflați, cu îmbunătățirea calității vieții și a efortului la selecționați','Un studiu controlat la emfizem sever a arătat creștere a mortalității după chirurgia de reducere a volumului','Vaccinul pneumococic se repetă lunar, iar valvele sunt contraindicate la hiperinflație'],'ABCD',959,'Recuperare; Vaccinuri; Chirurgie; Valve',
 'Integrarea reabilitării și a vaccinării unice cu contrastul LVRS (mortalitate crescută) versus valve.',
 ['Beneficiile reabilitării sunt din studii controlate.','Doza unică pneumococică și gripală anuală sunt juxtapuse.','Mecanismul valvelor și beneficiul la selecționați sunt descrise.','Creșterea mortalității după LVRS în emfizemul sever este citată.','Vaccinul nu se repetă lunar; valvele vizează tocmai hiperinflația.']],
 8,'LVRS „îmbunătățește tot” se ciocnește de studiul care a crescut mortalitatea; valvele par atunci superfluе.',['Vaccinurile','Valvele endobronşice']),

q(119,['Contraindicațiile absolute ale VNI pe secție, conform cadranului, sunt:',
 ['Deformări faciale severe și arsuri faciale','Astm și vărsături','Un pH de 7,40 cu PaCO2 normală, ca unică indicație de VNI','BPOC cu FR >23/min, ca contraindicație absolută','Indicele BODE 0–2, care interzice orice suport ventilator'],'AB',961,'Cadranul 28.26 — Contraindicațiile VNI',
 'Memorarea celor patru contraindicații absolute (față, arsuri, astm, vărsături), distincte de cele relative (pH, GCS).',
 ['Deformările și arsurile faciale deschid lista absolută.','Astmul și vărsăturile completează contraindicațiile absolute.','pH 7,40 nu este contraindicație; acidoza este indicație.','BPOC cu FR >23 este indicație, nu contraindicație.','BODE ghidează prognosticul/transplantul, nu contraindicația de VNI.']],
 8,'Astmul ca contraindicație absolută de VNI pe secție contrazice intuiția „obstructiv = VNI”.',['Arsuri faciale','Vărsături']),

q(120,['Simptomele de apnee obstructivă în somn și ponderile din cadran includ:',
 ['Cefalee matinală la 30% și senzație de sufocare nocturnă la 30%','Scăderea libidoului la 20%','„Stare de ebrietate” matinală și edeme gambiere, fiecare la 5%','Sforăit la 5%, fără somnolență diurnă','Cefaleea matinală lipsește din listă, fiind specifică doar hipercapniei neuromusculare'],'ABC',961,'Cadranul 28.28 — Simptomele ASO',
 'Reținerea ponderilor mai puțin citate (30/30/20/5), dincolo de sforăit 95% și somnolență 90%.',
 ['Cefaleea și sufocarea, ambele 30%, sunt în cadran.','Scăderea libidoului 20% este listată.','Cele două itemuri de 5% închid tabelul.','Sforăitul este 95%, somnolența 90%.','Cefaleea matinală figurează la 30%.']],
 8,'Ponderile 30/20/5 se uită în favoarea celor două dominante (95% și 90%).',['Cefalee matinală 30','Scăderea libidoului 20']),

q(121,['Cadranul riscurilor legate de fumatul matern include:',
 ['Greutate scăzută la naștere','Creșterea mortalității fetale și neonatale','Creșterea incidenței astmului','Protecție față de astmul copilului, prin nicotină transplacentară','Creștere ponderală fetală, ca efect anabolic al gudronului'],'ABC',963,'Cadranul 28.32 — Fumatul matern',
 'Recunoașterea triadei neonatale (greutate, mortalitate, astm) din cadran.',
 ['Greutatea scăzută la naștere este primul item.','Mortalitatea fetală/neonatală este al doilea.','Incidența astmului este al treilea.','Fumatul matern crește, nu scade, incidența astmului.','Gudronul nu este anabolic fetal în acest cadran.']],
 8,'Triada maternă se confundă cu itemii de fumat pasiv (pneumonie, bronșită la sugari) de pe aceeași listă.',['Greutate scăzută la naştere','Creşterea mortalităţii fetale']),

q(122,['Clasificarea pneumoniei după contextul de dobândire include:',
 ['Pneumonia comunitară, la o persoană fără imunosupresie sau neoplazie subiacentă','Pneumonia nosocomială, uneori numită „asociată asistenței medicale”, reflectând rolul căminelor','Pneumonia asociată ventilației, dobândită prin ventilație mecanică în terapie intensivă','Pneumonia comunitară, rezervată doar gazdei cu HIV nediagnosticat','Pneumonia de aspirație, definită prin condensare la 6 luni de la orice contact medical'],'ABC',964,'Pneumonia — Clasificare',
 'Separarea celor cinci contexte, cu accent pe „asociată asistenței” și VAP.',
 ['Definiția PC fără imunosupresie/neoplazie este explicită.','Sinonimul și rolul căminelor sunt precizate.','VAP este o categorie distinctă.','HIV ține de pneumonia imunodeprimatului, nu definește PC.','Aspirația ține de deglutiție/conținut gastric, nu de un interval de 6 luni.']],
 8,'Căminele mută ușor cazul din comunitar în „asociat asistenței”, capcana de clasificare.',['dobândită în colectivitate','asociată asistenţei medicale']),

q(123,['Radiografia toracică în pneumonia comunitară ușoară, tratată la domiciliu:',
 ['Se cere de rutină la forma ușoară, în prima oră, înaintea amoxicilinei','Nu este recomandată de rutină, cu excepția absenței ameliorării după 48–72 de ore','Înlocuiește CURB-65 ca unică evaluare de severitate','Se repetă zilnic, chiar dacă pacientul se ameliorează','Este superfluă și la internat, hemoleucograma fiind suficientă'],'B',965,'Evaluarea inițială — Radiografia',
 'Reținerea ferestrei 48–72 de ore ca excepție de la omiterea radiografiei în forma ușoară.',
 ['Radiografia nu este de rutină în forma ușoară.','Excepția 48–72 de ore este explicită.','CURB-65/CRB-65 rămân instrumentele de severitate.','Repetarea zilnică nu este cerută la domiciliu.','La internat, radiografia este cerută.']],
 8,'48–72 de ore (lipsa ameliorării) se confundă cu 6 săptămâni (excluderea cancerului) de pe aceeași pagină.',['48-72 ore','Radiografia toracică nu este recomandată']),

q(124,['Analizele de sânge care orientează spre Streptococcus pneumoniae în pneumonia comunitară includ:',
 ['Leucocite de obicei >15×10³/µL, cu neutrofilie 90%','VSH >100 mm/oră','PCR >100 mg/L','Leucocite normale, ca în Mycoplasma, fără neutrofilie','Limfopenie fără leucocitoză, hiponatremie și transaminaze mari, ca în Legionella'],'ABC',965,'Analize de sânge — Pneumococ',
 'Constelația pneumococică (leucocitoză, VSH>100, PCR>100) versus profilele Mycoplasma/Legionella.',
 ['Pragul de leucocite și neutrofilia 90% sunt explicite.','VSH >100 este citat.','PCR >100 mg/L închide probele inflamatorii.','Leucocitele normale țin de Mycoplasma.','Profilul Legionella este cel de limfopenie/hiponatremie/transaminaze.']],
 8,'Cele trei profile de laborator stau pe aceeași listă și se permută ușor între pneumococ, Mycoplasma și Legionella.',['>15 x','VSH)']),

q(125,['Cauzele pneumoniei lent rezolutive, din cadran, includ:',
 ['Rezistență antibiotică, doză/durată inadecvată, non-aderență sau malabsorbție','Empiem, abces pulmonar sau leziune obstructivă/carcinom bronhioloalveolar','Tromboembolism pulmonar, pneumonie în organizare criptogenică, pneumonie eozinofilică sau hemoragie alveolară','Vindecarea rapidă în 24 de ore, ca marker de lent-rezolutiv','Vaccinarea antigripală, ca etiologie a nerezoluției'],'ABC',965,'Cadranul 28.31 — Pneumonia lent rezolutivă',
 'Recunoașterea celor trei pachete (tratament, complicație locală, diagnostic alternativ).',
 ['Itemii de tratament inadecvat deschid cadranul.','Complicațiile și neoplazia subiacentă continuă lista.','Diagnosticile alternative sunt enumerate.','Lent-rezolutivul înseamnă nerezolvare, nu vindecare în 24 de ore.','Vaccinarea antigripală este prevenție, nu cauză de nerezoluție.']],
 8,'Diagnosticile alternative (TEP, COP, eozinofilică) se omit când se rețin doar empiemul și abcesul.',['lent rezolutive','Hemoragie alveolară']),

q(126,['Dacă se dezvoltă empiemul parapneumonic, textul precizează că lichidul:',
 ['Se lasă pe loc până la pahipleurită, pentru a crește randamentul culturii','Trebuie drenat urgent, pentru a preveni pahipleurita sau spitalizarea prelungită','Se tratează doar cu fizioterapie, fără drenaj','Are pH pleural >7,6 ca semn de urgență chirurgicală','Nu crește riscul de deces față de pleurezia simplă'],'B',966,'Empiemul — Drenaj',
 'Reținerea urgenței drenajului ca prevenire a pahipleuritei, nu ca manevră amânată.',
 ['Amânarea până la pahipleurită este opusul recomandării.','Drenajul urgent și prevenirea pahipleuritei/spitalizării sunt explicite.','Fizioterapia nu înlocuiește drenajul empiemului.','pH <7,2 este sugestiv pentru empiem, nu >7,6.','Empiemul crește suplimentar riscul de deces.']],
 8,'pH-ul 7,2 (diagnostic) se inversează, iar urgența drenajului se amână greșit „până la organizare”.',['drenat urgent','pahipleurita']),

q(127,['Pneumonia asociată ventilației se caracterizează prin:',
 ['Apariție în contextul ventilației mecanice în unitățile de terapie intensivă','Micro-organisme Gram-negative cu multiple rezistențe, cum ar fi Acinetobacter baumannii','Necesitatea selecției atente a antibioticului, în colaborare cu un microbiolog clinician','Etiologie identică cu pneumonia comunitară a gazdei imunocompetente','Tratament empiric cu amoxicilină orală 500 mg, fără consult microbiologic'],'ABC',967,'Pneumonia asociată ventilației',
 'Identificarea nișei UTI și a exemplului Acinetobacter baumannii ca germene multirezistent.',
 ['Contextul de ventilație în UTI este definiția.','Acinetobacter baumannii este exemplul de Gram-negativ multirezistent.','Colaborarea cu microbiologul este cerută.','Spectrul diferă de PC.','Amoxicilina orală este schema de PC ușoară, nu de VAP.']],
 8,'Acinetobacter din lista de PN se mută în VAP; amoxicilina de CRB-65=0 se aplică greșit aici.',['Acinetobacter baumani','microbiolog']),

q(128,['Leziunea granulomatoasă din tuberculoza primară:',
 ['Constă dintr-o zonă centrală de material necrotic denumit cazeum, înconjurată de celule epitelioide și celule gigante Langhans','Unii noduli calcificați conțin micobacterii dormante, izolate de sistemul imun și de mediul acid hipoxic — focarul Ghon','Pe radiografie, focarul Ghon poate fi vizibil ca un mic nodul calcificat','Granulomul este un abces rece cervical, fără necroză cazeoasă','Focarul Ghon este o cavernă apicală unică, fără calcificare'],'ABC',968,'Tuberculoza primară — Granulomul; Focarul Ghon',
 'Asocierea cazeum/Langhans cu dormanța în mediu acid hipoxic a focarului Ghon.',
 ['Arhitectura cazeum–epitelioide–Langhans este descrisă.','Dormanța în mediu acid hipoxic definește focarul Ghon.','Aspectul de mic nodul calcificat este radiologic.','Abcesul rece ține de TB ganglionară, nu de granulomul primar.','Ghon este nodul calcificat, nu o cavernă apicală.']],
 8,'Langhans și cazeumul se mută ușor la adenopatia cervicală (abces rece) de pe pagina următoare.',['celule gigante Langhans','focarul Ghon']),

q(129,['Izolarea spitalicească în tuberculoza pulmonară:',
 ['Pacienții cu spută microscopic pozitivă sunt considerați contagioși și trebuie izolați','Cei cu microscopie negativă sunt mai puțin contagioși și, în general, nu trebuie izolați, cu atenție sporită dacă printre contacți sunt imunodeprimați','Un singur frotiu negativ certifică non-contagiozitatea față de orice contact HIV','Izolarea se rezervă doar TB osoase, nu pulmonarei','Microscopia pozitivă permite salonul comun, cultura fiind singurul criteriu de izolare'],'AB',969,'TB pulmonară — Contagiozitate',
 'Contrastul smear-pozitiv (izolare) versus smear-negativ (de regulă fără izolare, exceptând contacții imunodeprimați).',
 ['Regula de izolare a smear-pozitivilor este explicită.','Nuanța smear-negativ plus atenția la imunodeprimați este precizată.','Un singur frotiu nu închide riscul față de HIV.','Izolarea vizează forma pulmonară contagioasă.','Microscopia pozitivă, nu cultura, ghidează izolarea inițială.']],
 8,'Smear-negativul „nu se izolează” se absolutizează, deși textul cere prudență la contacții imunodeprimați.',['microscopic pozitivă','imunodeprimaţi']),

q(130,['Supravegherea hepatică și interacțiunile din tratamentul anti-TB de primă linie:',
 ['Medicamentele se opresc dacă bilirubina serică este crescută sau transaminazele depășesc de peste trei ori limita','Hepatita la izoniazidă apare la mai puțin de 1% din cazuri, dar continuarea poate evolua spre transplant sau deces','Rifampicina face contracepția orală ineficientă, impunând metode alternative; poate da trombocitopenie','Pirazinamida reduce excreția renală a acidului uric și poate precipita guta hiperuricemică','Transaminazele se ignoră până la o creștere de 20 de ori, bilirubina nefiind relevantă'],'ABCD',971,'Efecte nedorite — Hepatită; Rifampicină; Pirazinamidă',
 'Pragul de oprire (bilirubină sau AST/ALT ×3) plus OCP ineficientă și guta de pirazinamidă.',
 ['Regula de oprire este explicită.','Ponderea <1% și riscul de transplant/deces sunt citate.','OCP ineficientă și trombocitopenia țin de rifampicină.','Reducerea excreției de urat și guta sunt ale pirazinamidei.','Pragul este ×3, nu ×20; bilirubina contează.']],
 8,'Guta se atribuie greșit etambutolului, iar OCP ineficientă se uită ca interacțiune a rifampicinei.',['peste trei ori','contracepţia orală']),

q(131,['Incidența co-infecției HIV printre cazurile de TB la nivel mondial este de circa:',
 ['10%, TB fiind responsabilă de aproximativ un sfert din decesele legate de SIDA','90%, fără mortalitate asociată SIDA','1%, identică MDR-TB din țările dezvoltate','0%, HIV-ul protejând față de TB','50%, limitată la Europa de Vest, fără Africa'],'A',971,'TB în situații speciale — Co-infecția HIV',
 'Cuplarea cifrei de 10% co-infecție cu ponderea de un sfert din decesele SIDA.',
 ['Cele două ponderi (10% și un sfert) sunt juxtapuse.','90% nu este cifra mondială citată.','1% este incidența MDR în țările dezvoltate, nu a co-infecției.','HIV crește, nu protejează față de TB.','Povara este mare în Africa sub-sahariană, India, Europa de Est și Rusia.']],
 8,'10% (co-infecție) se schimbă ușor cu 1% (MDR) sau 10% (monorezistență la izoniazidă) de pe aceeași pagină.',['în jur de 10%','un sfert din decesele']),

q(132,['Vaccinarea BCG, conform textului:',
 ['Este un vaccin viu atenuat derivat din M. bovis care și-a pierdut virulența','Este recomandat în anumite situații în țările dezvoltate, dar nu în SUA, și nu mai este oferit de rutină tuturor din cauza cost-eficacității','În Marea Britanie este oferit nou-născuților din regiunile cu risc înalt, cu preocupări de siguranță la copiii cu HIV','Este strategia de rutină la toți adulții din SUA, ca măsură cost-eficientă','Este un vaccin inactivat proteic, fără legătură cu M. bovis'],'ABC',972,'Vaccinarea BCG',
 'Geografia BCG (UK nou-născuți cu risc, nu SUA de rutină) și originea M. bovis atenuat.',
 ['Originea M. bovis atenuat este explicită.','Excepția SUA și abandonul rutinei universale sunt precizate.','Politica britanică pentru nou-născuții din zone de risc și alerta HIV sunt citate.','SUA nu oferă BCG de rutină.','Este vaccin viu, nu inactivat proteic.']],
 8,'Politica SUA versus UK se inversează; originea M. bovis se confundă cu vaccin inactivat.',['nu în SUA','nou-născuţilor din regiunile']),

q(133,['Tehnica aspirației simple a pneumotoracelui, din cadran, prevede introducerea unei canule de calibru 16:',
 ['Subdiafragmatic, pentru a evita pleura','Prin carină, sub ghidaj bronhoscopic','3–4 cm prin pleură, în spațiul 2 intercostal pe linia medioclaviculară, conectată la un robinet cu trei căi și o seringă de 50 ml; se aspiră până la 2,5 L','În spațiul 8 posterior, fără anestezie','Doar după intubație, ca manevră unică în trauma majoră'],'C',975,'Cadranul 28.49 — Aspirația simplă',
 'Reținerea pachetului tehnic (16G, 3–4 cm, spațiul 2 medioclavicular, 50 ml, plafon 2,5 L).',
 ['Calea subdiafragmatică nu este descrisă.','Bronhoscopia nu este calea de aspirație.','Toate elementele tehnice sunt în cadran.','Spațiul 8 fără anestezie contrazine lidocaina 2% din cadran.','În trauma majoră aspirația nu este, de regulă, recomandată.']],
 8,'Spațiul 2 medioclavicular (aspirație) se schimbă cu spațiul 4 axilar (dren intercostal) de pe aceeași pagină.',['calibru de 16','2,5 L de aer']),

q(134,['După un pneumotorace, sfaturile privind fumatul, sportul și urmărirea includ:',
 ['Canabisul, în special, poate determina modificări emfizematoase marcate la tineri, cu formare de bule','Sportul de contact trebuie evitat timp de una sau două săptămâni','Controlul ambulatoriu trebuie programat în termen de 10 zile','Scufundările sunt permise imediat, fără pleurodeză','Controlul se amână 6 luni, în absența simptomelor'],'ABC',975,'Pneumotoracele — Fumat; Sport; Urmărire',
 'Separarea ferestrei de 10 zile și a sportului de contact 1–2 săptămâni de interdicția scufundărilor.',
 ['Efectul canabisului asupra bulelor este explicit.','Fereastra de 1–2 săptămâni pentru contact este citată.','Controlul în 10 zile este precizat.','Scufundările cer pleurodeză chirurgicală.','10 zile, nu 6 luni, este intervalul de control.']],
 8,'10 zile (control) se confundă cu 1 săptămână (zbor) sau 1–2 săptămâni (sport de contact).',['Canabisul','10 zile']),

q(135,['În etiologia cancerului bronhopulmonar, dincolo de fumat, textul menționează:',
 ['Factori de mediu: radon, azbest, hidrocarburi aromatice policiclice și radiații ionizante; expunere profesională la arsen, crom, nichel, produse petroliere și uleiuri','Factori de gazdă: boli pulmonare preexistente precum fibroza pulmonară, infecția HIV și factori genetici','Incidență mai mare în mediul urban decât în cel rural, chiar după ajustarea pentru fumat','Incidență mai mică urban decât rural, după ajustarea pentru fumat','Absența oricărui rol al radonului sau al azbestului după controlul fumatului'],'ABC',975,'Cancerul bronhopulmonar — Etiologie',
 'Lista de mediu/profesie plus contrastul urban-rural independent de fumat.',
 ['Agenții de mediu și profesionali sunt enumerați.','Fibroza, HIV și genetica sunt factorii de gazdă.','Gradientul urban > rural după ajustare este explicit.','Textul afirmă opusul gradientului.','Radonul și azbestul rămân etiologici.']],
 8,'Gradientul urban-rural se inversează ușor, iar lista profesională se reduce greșit la fumat.',['expunere la radon','fibroza pulmonară']),

q(136,['Pe radiografia toracică, formațiunile tumorale pulmonare sunt vizibile dacă au diametrul:',
 ['Peste 1 cm; pot fi spiculate, cavitare sau cu margini netede','Sub 2 mm, ca micronoduli miliari','Doar dacă ocupă un hemitorace întreg','Indiferent de dimensiune, inclusiv leziuni microscopice','Peste 7 cm, pragul T4 fiind condiția vizibilității'],'A',977,'Cadranul 28.51 — Formațiuni tumorale',
 'Reținerea pragului de vizibilitate de 1 cm, distinct de definiția nodulului solitar (3 cm) sau de T4 (7 cm).',
 ['Pragul >1 cm și morfotipurile sunt în cadran.','2 mm ține de TB miliară, nu de vizibilitatea masei.','Ocuparea hemitoracelui nu este condiția vizibilității.','Leziunile microscopice nu se văd pe radiografie.','7 cm este criteriu T4, nu de vizibilitate radiologică.']],
 8,'1 cm (vizibilitate) se schimbă cu 3 cm (nodul solitar) sau 7 cm (T4).',['>1 cm în dia','Spiculate, cavitare']),

q(137,['Tipurile histologice de cancer pulmonar, dincolo de scuamosul „cel mai comun în Europa”, includ:',
 ['Adenocarcinomul, 27–30%, probabil cel mai comun tip din Marea Britanie în viitorul apropiat; creșterea din 2005 e legată de conținutul scăzut de gudron','Carcinomul cu celule mari, 10–15%, de obicei slab diferențiat, cu metastaze relativ precoce','Carcinomul cu celule mici, 20%, origine din celule neuroendocrine (APUD), adesea central, cu metastaze precoce și secreție de hormoni polipeptidici','Adenocarcinomul, sub 5%, limitat la fumătorii grei cu cavități de necroză','Carcinomul cu celule mici, 70%, fără origine neuroendocrine'],'ABC',976,'Cadranul 28.50 — Tipuri celulare',
 'Ponderile 27–30 / 10–15 / 20 și legătura adenocarcinom–gudron scăzut.',
 ['Ponderea 27–30% și explicația gudronului sunt explicite.','10–15% și profilul slab diferențiat sunt listate.','20%, APUD, sediul central și hormonii sunt descrise.','Adenocarcinomul este în creștere, nu sub 5%, și e cel mai comun la nefumători.','SCLC este 20%, cu origine neuroendocrine.']],
 8,'Ponderile din cadran (35 / 27–30 / 10–15 / 20) se redistribuie ușor între tipuri.',['27-30','celule APUD']),

q(138,['Manifestările extrapulmonare non-metastatice ale cancerului bronșic includ:',
 ['Aproximativ 10% din tumorile cu celule mici produc hormoni ectopici, cauzând sindroame paraneoplazice','Hipocratismul digital la circa 30% și osteoartropatia hipertrofică pulmonară (± ginecomastie) la 3%','Sindromul Lambert-Eaton, listat printre afecțiunile musculare','Hipocratismul, prezent la sub 1%, doar în adenocarcinomul periferic','HPOA la 30%, identic ponderii hipocratismului'],'ABC',978,'Cadranul 28.52 — Non-metastatice',
 'Separarea ponderilor 10% (ectopic SCLC), 30% (hipocratism) și 3% (HPOA).',
 ['Cifra de 10% pentru hormonii ectopici este în text.','30% și 3% sunt în cadran.','Lambert-Eaton figurează la musculare.','Hipocratismul este 30%, nu <1%.','HPOA este 3%, nu 30%.']],
 8,'Cele trei procente (10 / 30 / 3) se permută între ectopic, hipocratism și HPOA.',['Hipocratism (30%)','Osteartropatie hipertrofică']),

q(139,['În Marea Britanie, la momentul prezentării, o formă avansată de cancer pulmonar, care exclude tratamentul radical, este întâlnită la aproximativ:',
 ['10% din pacienți','75% din pacienți','2% din pacienți, restul fiind operați cu viză curativă','Toți pacienții sub 40 de ani nefumători','Niciun pacient cu NSCLC, radicalul fiind regula'],'B',978,'Tratament — Prezentare avansată',
 'Reținerea ponderii de 75% prezentare avansată, distinctă de supraviețuirea 25–30% la 1 an.',
 ['10% nu este ponderea de formă avansată.','Cifra de 75% este explicită.','Majoritatea nu sunt candidați la radical.','Vârsta <40 nefumători nu inversează statistica de prezentare.','NSCLC avansat este frecvent inoperabil.']],
 8,'75% (prezentare avansată) se confundă cu 25–30% (supraviețuire la 1 an) de pe aceeași pagină.',['aproximativ 75%','tratamentul radical nu este o opţiune']),

q(140,['În stadializarea TNM, sunt corecte:',
 ['T3 descrie tumora >5 cm dar ≤7 cm, sau invazia pleurei parietale, peretelui toracic (inclusiv Pancoast), nervului frenic, pericardului parietal, sau noduli în același lob','T4 este tumora >7 cm sau invazia diafragmului, mediastinului, cordului, vaselor mari, traheei, recurentului, esofagului, corpului vertebral sau carinei, ori noduli în alt lob ipsilateral','N3 înseamnă metastaze în ganglionii mediastinali contralaterali, hilari contralaterali sau scaleni/supraclaviculari ipsi- sau contralaterali','T3 include invazia carinei și a esofagului, iar N3 se limitează la ganglionii intrapulmonari ipsilaterali','M1a exclude revărsatul pleural malign, acesta fiind M0'],'ABC',979,'Cadranul 28.53 — T3, T4, N3',
 'Diferențierea T3 (același lob, frenic, Pancoast) de T4 (carină, esofag, alt lob ipsilateral) și N3 contralateral/scalen.',
 ['Criteriile T3 sunt din cadran.','Criteriile T4 sunt din cadran.','Teritoriul N3 este descris.','Carina și esofagul sunt T4; N1 este hilar/intrapulmonar ipsilateral.','Revărsatul pleural/pericardic malign este M1a.']],
 8,'Frontiera T3/T4 (același lob versus alt lob; frenic versus recurent) este capcana clasică de TNM.',['nervul frenic','corpul vertebral']),

q(141,['Supraviețuirea la 5 ani în NSCLC, din cadranul de stadii, arată circa:',
 ['92% în IA1, 83% în IA2 și 77% în IA3','10% în IVA și 0% în IVB','60% în stadiul IVB, identic IA1','92% în IVB, prognosticul fiind independent de stadializare','0% în IA1, screeningul neinfluențând stadiul'],'AB',980,'Cadranul 28.56 — Supraviețuire pe stadii',
 'Ancorarea extremelor IA1 92% versus IVB 0% / IVA 10%.',
 ['Tripletul IA1–IA3 este din tablou.','IVA 10% și IVB 0% închid tabloul.','IVB nu are 60%.','92% este al IA1, nu al IVB.','IA1 are cea mai bună, nu cea mai slabă, supraviețuire.']],
 8,'92% (IA1) și 0% (IVB) se atribuie greșit stadiului opus.',['IAl 92','IV8 o']),

q(142,['Tumorile benigne și nodulul pulmonar, conform textului:',
 ['Hamartomul este cea mai frecventă tumoră benignă pulmonară, de obicei o leziune rotundă bine delimitată de 1–2 cm, periferică, cu creștere extrem de lentă','Adenomul bronșic se dezvoltă din glandele mucoase și ductele căilor respiratorii','Tumorile benigne traheale includ papilomul scuamos, leiomiomul și hemangioamele','Hamartomul este cea mai frecventă metastază osteosarcomatoasă, cu creștere explozivă','Papilomul scuamos este forma dominantă de NSCLC la fumători'],'ABC',982,'Tumorile benigne; Hamartomul',
 'Separarea hamartomului 1–2 cm de adenomul mucos și de trio-ul traheal benign.',
 ['Definiția hamartomului (frecvență, 1–2 cm, periferic, lent) este explicită.','Originea din glande mucoase este a adenomului.','Cele trei tumori traheale benigne sunt listate.','Hamartomul este benign, nu o metastază.','Papilomul scuamos este benign traheal, nu NSCLC.']],
 8,'Hamartomul 1–2 cm se confundă cu pragul de vizibilitate de 1 cm sau cu nodulul solitar <3 cm.',['1-2 cm','papilomul scuamos'],[981]),
];
