import {advancedQuestion} from './advanced-author';
import type {SourceRow} from './source-author';
const pdfOffset=(p:number)=>p<=961?p-789:p<=972?p-790:p-792;
const q=(n:number,row:SourceRow,score:number,reason:string,expressions:string[],related:number[]=[])=>
 advancedQuestion('pneumologie',28,pdfOffset,`pneumologie-adv-${String(n).padStart(3,'0')}`,row,[score,reason],expressions,undefined,related);

export const PNEUMOLOGIE_C=[
q(63,['Durata tratamentului de probă cu inhibitor de pompă de protoni, când tusea cronică este atribuită refluxului acid, este de:',
 ['3 zile','2 săptămâni','8 săptămâni','6 luni','Un an, fără reevaluare'],'C',949,'Tusea cronică — Tratament de probă',
 'Reținerea ferestrei de 8 săptămâni pentru IPP, distinctă de cele 2 săptămâni de corticosteroid pentru tusea nocturnă.',
 ['3 zile este prea scurtă față de proba citată pentru reflux.','2 săptămâni este durata probei cu corticosteroid pentru tuse nocturnă sau wheezing, nu pentru IPP.','Textul indică 8 săptămâni de inhibitor de pompă de protoni pentru refluxul acid.','6 luni depășește durata empirică descrisă.','Proba este limitată și urmată, dacă eșuează, de investigații (CT, bronhoscopie), nu de un an nedirijat.']],
 8,'Cele două durate empirice (2 versus 8 săptămâni) stau pe aceeași listă și se inversează ușor.',['8 săptămâni cu inhibitor','2 săptămâni cu corticosteroid']),

q(64,['Impactul epidemiologic al astmului, conform textului:',
 ['La nivel mondial omoară în jur de 1.000 de oameni pe zi','Aproximativ 300 de milioane de oameni au astm','Numărul se așteaptă să crească la 400 de milioane până în 2025','Prevalența cea mai înaltă este în Asia de Est și Africa, nu în Marea Britanie','Debutează clasic după 60 de ani, nu între 3 și 5 ani'],'ABC',949,'Astmul — Prevalență',
 'Cuantificarea mortalității zilnice și a proiecției 300–400 de milioane, distinct de geografia vest versus est.',
 ['Cifra de 1.000 de decese pe zi este explicită.','Cele 300 de milioane de bolnavi sunt citate.','Proiecția la 400 de milioane până în 2025 este alăturată.','Cele mai înalte prevalențe sunt în Marea Britanie, Noua Zeelandă și Australia; ratele sunt mai scăzute în Asia de Est și Africa.','Debutul clasic este în copilărie, între 3 și 5 ani.']],
 8,'Inversează geografia prevalenței și vârsta de debut, două fapte din aceeași pagină.',['300 de milioane','400 de milioane']),

q(65,['Atopia și testele alergologice în astm:',
 ['În jur de 90% dintre copiii și 70% dintre adulții cu astm persistent au teste cutanate prick pozitive la alergene inhalatorii comune','IgE alergen-specifice sunt prezente la 30–40% din populația Marii Britanii','Nivelurile de IgE serice totale nu sunt influențate de factori genetici sau de mediu','Testele prick pozitive lipsesc la copiii cu astm persistent','Atopia a fost definită fără agregare familială și fără anticorpi alergen-specifici'],'AB',949,'Clasificare — Atopia și alergia',
 'Reținerea ponderilor prick (90%/70%) și a seroprevalenței IgE de 30–40% în populația britanică.',
 ['Procentele 90% (copii) și 70% (adulți) sunt juxtapuse în text.','Intervalul 30–40% pentru IgE alergen-specifice este citat.','Textul precizează că IgE totale sunt influențate de factori genetici și de mediu.','Majoritatea copiilor cu astm persistent au prick pozitiv, nu negativ.','Atopia a fost descrisă prin agregare familială, prick pozitiv și anticorpi alergen-specifici.']],
 8,'Distractorii neagă tocmai agregarea familială și ponderile prick din definiția istorică a atopiei.',['90% dintre copiii','30-40% din populaţia']),

q(66,['Alegeți afirmațiile corecte referitoare la astmul ocupațional ca boală profesională:',
 ['Peste 250 de materiale de la locul de muncă pot cauza astm ocupațional','Pacienții angajați cu carte de muncă sunt eligibili pentru despăgubiri dacă aplică în termen de 10 ani de la părăsirea locului de muncă','Fumatul crește riscul de a dezvolta unele forme de astm ocupațional','Procentul de angajați afectați depinde în principal de nivelul de expunere','Izolarea proceselor industriale și ventilația nu modifică riscul'],'ABCD',950,'Sensibilizanții ocupaționali',
 'Integrarea listei de peste 250 de agenți cu fereastra de 10 ani a despăgubirilor și cu rolul dozei de expunere.',
 ['Cifra de peste 250 de materiale este explicită.','Fereastra de 10 ani de la părăsirea locului de muncă este criteriul de eligibilitate.','Fumatul este citat ca factor care crește riscul unor forme.','Nivelul de expunere determină procentul de angajați afectați.','Izolarea corectă sau ventilația corespunzătoare reduc riscul în mare măsură.']],
 8,'Ultimul distractor neagă măsurile de control pe care textul le plasează imediat după doza de expunere.',['Peste 250 de materiale','în termen de 10 ani']),

q(67,['Doza și durata tratamentului de probă cu prednison oral, la obstrucția bronșică difuză severă, sunt:',
 ['10 mg zilnic timp de 3 zile','Prednison oral 30 mg zilnic timp de 2 săptămâni, cu măsurarea funcției pulmonare înainte și imediat după cură','60 mg o dată, fără reevaluare spirometrică','5 mg în zile alterne, 6 luni','Hidrocortizon topic nazal 1 săptămână'],'B',951,'Tratamentul de probă cu corticosteroizi',
 'Reținerea schemei 30 mg × 2 săptămâni și a pragului >15% VEMS care prezice răspunsul la CSI.',
 ['Doza și durata sunt sub cele din text.','Aceasta este schema formală: 30 mg zilnic, 2 săptămâni, cu spirometrie înainte și după.','O doză unică de 60 mg nu este proba de reversibilitate descrisă aici.','Schema de 6 luni nu este proba scurtă; curele ≤2 săptămâni se pot opri brusc.','Calea este orală (prednison), nu topic nazală.']],
 8,'60 mg și 30 mg apar ambele în capitolul de astm (exacerbare versus probă), deci se confundă ușor.',['prednison oral 30 mg','2 săptămâni']),

q(68,['Controlul factorilor externi și markerii de inflamație în astm:',
 ['Imunoterapia sublinguală cu acarieni a arătat o reducere a exacerbărilor la copii, dar nu este recomandată la adulți','Oxidul nitric din aerul expirat măsoară inflamația căilor aeriene și este un indice al răspunsului la corticosteroizi','Eozinofilele periferice pot depăși 0,4×10³/µL, însă eozinofilia sputei are specificitate diagnostică mai mare','SLIT cu acarieni este tratamentul de primă linie la toți adulții cu astm ușor','Beta-blocantele sub formă de picături oculare pot fi folosite fără risc la astmatici'],'ABC',951,'Controlul factorilor externi; Oxidul nitric; Teste sanguine',
 'Separarea indicației pediatrice a SLIT de FeNO ca marker de răspuns steroidian și de ierarhia eozinofiliei.',
 ['Textul limitează beneficiul SLIT la copii și o contraindică implicit la adulți prin nerespectarea recomandării.','FeNO este descris ca indice al inflamației și al răspunsului la corticosteroizi.','Pragul 0,4×10³/µL și superioritatea specificității sputei sunt explicite.','SLIT nu este recomandată la adulți.','Fumatul activ/pasiv și beta-blocantele (comprimate sau picături oculare) trebuie evitate.']],
 8,'Extinde SLIT de la copii la adulți și „scapă” picăturile oculare de beta-blocant, ambele din același paragraf.',['Imunoterapia sublinguală','0,4 x 103/µL'],[952]),

q(69,['Camerele de inhalare (spacers) în terapia inhalatorie a astmului:',
 ['Reduc viteza particulelor și cantitatea de medicament depusă la nivelul gurii','Reduc necesitatea coordonării între activarea dispozitivului și inspir','Sunt utile la copii și vârstnici și reduc riscul de candidoză','Măresc depunerea faringiană față de MDI-ul fără spacer','Sunt rezervate doar adulților tineri cu tehnică MDI perfectă'],'ABC',952,'Cadranul 28.19 — Camere de inhalare (Spacers)',
 'Recunoașterea celor trei avantaje mecanice și de siguranță ale spacer-ului față de MDI-ul brut.',
 ['Reducerea vitezei și a depunerii orale este scopul constructiv.','Coordonarea activare–inspir este tocmai punctul slăbit pe care îl ocolesc.','Utilitatea pediatrică/geriatrică și scăderea candidozei sunt listate.','Spacer-ul scade, nu crește, depunerea la nivelul gurii.','Sunt concepute tocmai pentru cei cu coordonare deficitară, nu pentru tehnica perfectă.']],
 8,'Inversează efectul asupra depunerii orale — motivul pentru care spacer-ul există.',['Camere de inhalare','riscul de candidoză']),

q(70,['Cromoglicatul disodic și nedocromilul sodic:',
 ['Previn activarea mastocitelor, eozinofilelor și celulelor epiteliale, dar nu a limfocitelor','Blochează un canal de clor, cu oprirea influxului de calciu','Sunt eficiente la formele mai ușoare, dar nu sunt utilizate în mod obișnuit','Sunt anticorpi monoclonali anti-IL-5 administrați subcutanat lunar','Înlocuiesc corticosteroizii inhalatori ca treaptă unică în astmul sever'],'ABC',953,'Medicamente antiinflamatorii — Cromoglicat și nedocromil',
 'Reținerea țintelor celulare (fără limfocite) și a canalului de clor, distinct de biologicele anti-IL-5.',
 ['Lista celulară cu excepția limfocitelor este explicită.','Mecanismul canalului de clor → stoparea influxului de Ca2+ este descris.','Utilizarea la forme ușoare, nu de rutină, este precizată.','Anti-IL-5 (mepolizumab, reslizumab, benralizumab) sunt altă clasă, de pe pagina următoare.','Nu înlocuiesc CSI; sunt agenți de nișă, rar folosiți.']],
 8,'Confundă cromonele cu anticorpii anti-IL-5 din paragraful imediat următor.',['Cromoglicatul disodic','canal de clor'],[954]),

q(71,['În tratamentul la domiciliu al exacerbării astmatice severe, doza de salbutamol prin nebulizare menționată în cadran este:',
 ['0,5 mg','5 mg','50 mg','500 mg intravenos','Salbutamolul nebulizat lipsește din algoritmul de acasă'],'B',954,'Cadranul 28.21 — Tratamentul exacerbării astmatice severe',
 'Reținerea dozei de 5 mg salbutamol (sau 10 mg terbutalină) din treapta de acasă.',
 ['0,5 mg este doza de ipratropium din treapta de spital, nu de salbutamol.','5 mg de salbutamol (sau 10 mg terbutalină) este pasul 3 al algoritmului de acasă.','50 mg depășește doza citată.','Calea de acasă este nebulizarea, nu 500 mg i.v.','Nebulizarea cu salbutamol figurează explicit înaintea hidrocortizonului.']],
 8,'5 mg (salbutamol) și 0,5 mg (ipratropium) stau în același cadran și se inversează ușor.',['5 mg de salbutamol','10 mg de terbutalină']),

q(72,['Manifestările unei exacerbări astmatice amenințătoare de viață, respectiv foarte severe, includ:',
 ['Silențium respirator, cianoză sau respirație superficială','PEF <33% din valoarea prezisă (aproximativ 150 L/min la adulți) sau SpO2 <92%','PaCO2 >45 mmHg (>6 kPa) ca marker de formă foarte severă','Hipoxemie severă: PaO2 <60 mmHg (<8 kPa) în pofida oxigenoterapiei','Pulsul paradoxal prezent la peste 90% din cazuri, esențial pentru diagnostic'],'ABCD',954,'Exacerbarea amenințătoare de viață',
 'Separarea semnelor clinice/PEF/SpO2 de criteriile gazometrice foarte severe și de inutilitatea pulsului paradoxal.',
 ['Silențiul, cianoza și respirația superficială sunt listate la amenințarea de viață.','Pragurile PEF <33% și SpO2 <92% sunt explicite.','PaCO2 >45 mmHg definește forma foarte severă.','PaO2 <60 mmHg sub oxigen este al doilea criteriu gazometric foarte sever.','Pulsul paradoxal este prezent în doar 45% din cazuri și nu este util.']],
 8,'Pune alături treapta clinică amenințătoare și pragurile ABG foarte severe; distractorul supraevaluează pulsul paradoxal din aceeași listă.',['PEF <33%','P.CO2 crescută >45 mmHg']),

q(73,['Povara socioeconomică a BPOC în Marea Britanie:',
 ['Este responsabilă anual de aproximativ 18 milioane de zile de concediu medical la bărbați și 2,1 milioane la femei','Reprezintă aproximativ 7% din numărul total de zile de concediu medical','Numărul internărilor a crescut constant de la mijlocul anilor 1980','Dieta a fost demonstrată ca factor etiologic major la oameni, independent de fumat','Toți fumătorii dezvoltă BPOC, fără predispoziție individuală'],'AB',955,'BPOC — Epidemiologie și etiologie',
 'Cuantificarea zilelor de concediu (18 vs 2,1 milioane) și a ponderii de 7%, distinct de trendul internărilor.',
 ['Cifrele 18 și 2,1 milioane de zile sunt cele din text.','Ponderea de 7% din totalul concediilor medicale este citată.','Internările au scăzut constant de la mijlocul anilor 1980, nu au crescut.','Dieta este sugerată doar de studii pe animale, nedemonstrată la oameni.','Doar 10–20% dintre fumători dezvoltă BPOC, ceea ce sugerează predispoziție individuală.']],
 8,'Inversează trendul internărilor și extinde etiologia dietetică de la animale la oameni.',['18 milioane de zile','2,1 milioane']),

q(74,['Studiile clasice ale lui Fletcher și Peto au demonstrat, la pacienții cu BPOC, o scădere anuală a VEMS de aproximativ:',
 ['50 ml/an, față de 20 ml/an la indivizii sănătoși','5 ml/an, identică cu cea a nefumătorilor','200 ml/lună','1 L/an la toți fumătorii, indiferent de BPOC','Nicio scădere, VEMS fiind stabil pe tot parcursul vieții'],'A',956,'Fiziopatologie — Declinul VEMS',
 'Reținerea perechii 50 versus 20 ml/an și a observației ulterioare (40 ml/an la 38% din pacienți).',
 ['Aceasta este cifra clasică Fletcher–Peto.','5 ml/an subestimează net declinul descris.','200 ml/lună ar fi un colaps funcțional, nu rata anuală.','1 L/an nu este rata citată; nu toți fumătorii au BPOC.','Declinul există; nu a fost identificat un marker fiabil al ratei.']],
 8,'50 și 20 ml/an sunt perechea numerică de pe aceeași figură; distractorii schimbă ordinul de mărime.',['50 ml/an','20 ml/an']),

q(75,['Investigațiile în BPOC arată că:',
 ['Factorul de transfer gazos al monoxidului de carbon este scăzut în prezența unui grad semnificativ de emfizem','Radiografia toracică este adesea normală, chiar și în stadiile avansate','Virușii sunt responsabili pentru majoritatea exacerbărilor infecțioase','DLCO este caracteristic crescut, ca în astm','Sputa de exacerbare izolează aproape numai Mycobacterium tuberculosis'],'ABC',957,'BPOC — Investigații',
 'Contrastul DLCO scăzut (emfizem) versus normal (astm) și recunoașterea predominanței virale a exacerbărilor.',
 ['Scăderea transferului CO în emfizem este explicită.','Normalitatea radiografiei chiar în boala avansată este subliniată.','Virușii, nu bacteriile, produc majoritatea exacerbărilor infecțioase.','DLCO scăzut deosebește emfizemul de astm (unde este normal).','Bacteriile citate sunt S. pneumoniae, H. influenzae și Moraxella catarrhalis.']],
 8,'Inversează DLCO-ul astm versus emfizem, test clasic de diferențiere din același capitol.',['transfer gazos al monoxidului','Virușii sunt responsabili']),

q(76,['Măsurile adiționale în BPOC stabil includ:',
 ['Flebotomie dacă hematocritul este >55% în policitemia secundară','Substituție i.v. de alfa-1-antitripsină la nivel seric <310 mg/L și funcție pulmonară alterată','Lorazepam sublingual sau un opioid ca măsură paliativă în dispneea refractară','Măști Venturi care furnizează 24%, 28% și 35% oxigen','Flebotomia de rutină la hematocrit 40%, la toți pacienții cu BPOC ușoară'],'ABCD',959,'Măsuri adiționale — Policitemie; Substituție; Paliație; Venturi',
 'Aplicarea pragurilor Hct >55% și AAT <310 mg/L, plus concentrațiile fixe ale măștii Venturi.',
 ['Pragul de hematocrit >55% declanșează flebotomia.','Pragul <310 mg/L cu disfuncție pulmonară este indicația de substituție.','Lorazepamul sublingual și opioidul sunt paliativele citate pentru dispneea refractară.','Cele trei concentrații Venturi sunt enumerate la figura de performanță fixă.','Flebotomia vizează policitemia cu Hct >55%, nu BPOC-ul ușor cu hematocrit normal.']],
 8,'Amestecă pragul de flebotomie (55%) cu un hematocrit fiziologic și ignorează caracterul paliativ al sedării.',['hematocritul este >55%','<310 mg/L']),

q(77,['În algoritmul exacerbării acute de BPOC, după oxigen controlat și nebulizări, gazometria arterială se repetă:',
 ['Imediat, la fiecare 2 minute, indiferent de evoluție','Peste 30–60 de minute, dacă pH-ul a fost scăzut sau dacă dispneea se intensifică','După 7 zile de antibiotic oral, ca unică reevaluare','Doar la externare, nu în urgență','Pulsoximetria înlocuiește complet gazometria, fără recoltare arterială'],'B',960,'Fig. 28.26 — Algoritm pentru insuficiența respiratorie în BPOC',
 'Reținerea ferestrei 30–60 de minute pentru re-ABG înainte de decizia de VNI.',
 ['Reevaluarea la 2 minute nu este intervalul din algoritm.','Algoritmul cere repetarea gazometriei peste 30–60 de minute.','Reevaluarea de 7 zile nu ghidează VNI-ul acut.','Decizia de VNI se ia în urgență, nu la externare.','Gazometria rămâne necesară când există risc de hipercapnie decompensată.']],
 8,'Fereastra 30–60 min este ușor de înlocuit cu „imediat” sau „doar la externare”.',['peste 30-60 minute','mască Venturi']),

q(78,['Apneea obstructivă în somn și VNI în bolile neuromusculare:',
 ['Somnolența diurnă este raportată la 90% dintre simptomaticii cu ASO','Prevalența ASO este mai mare la menopauză, în acromegalie și hipotiroidism','La boli neuromusculare, VNI pe secție se poate indica la FR >20/min dacă capacitatea vitală uzuală este <1 L, chiar dacă PaCO2 <49 mmHg','ASO apare doar la copii, nu la bărbații de vârstă mijlocie','Cefaleea matinală lipsește din lista de simptome ASO'],'ABC',961,'ASO — Simptome; Cadranul 28.25 VNI neuromusculară',
 'Asocierea somnolenței de 90% și a endocrinopatiilor cu pragul de CV <1 L pentru VNI neuromusculară.',
 ['Cadranul 28.28 listează somnolența diurnă la 90%.','Menopauza, acromegalia și hipotiroidismul sunt factorii enumerați.','Criteriul neuromuscular (FR >20 și CV <1 L, chiar fără hipercapnie) este în cadranul de indicații VNI.','ASO este cea mai frecventă la bărbați de vârstă mijlocie supraponderali; copiii sunt un subgrup.','Cefaleea matinală figurează la 30%.']],
 8,'Mută ASO exclusiv la copii și neagă cefaleea matinală, deși ambele sunt în același cadran de simptome.',['Somnolenţă diurnă 90','capacitatea vitală']),

q(79,['Selectați enunțurile adevărate despre povara fumatului:',
 ['OMS estimează că tutunul este responsabil de 7 milioane de decese anual','Prevalența în Marea Britanie a scăzut de la 51% (bărbați) și 41% (femei) în 1974 la 17,2% din adulți în 2015','Fumatul pasiv afecta în 2004 circa 40% dintre copii','Fumul conține hidrocarburi aromatice policiclice și nitrozamine, carcinogeni puternici','Prevalența fumatului de țigarete a crescut constant în lumea vestică după 1974'],'ABCD',963,'Fumatul — Prevalență; Efecte toxice',
 'Cuantificarea deceselor OMS, a declinului 51/41→17,2% și a expunerii pasive a copiilor.',
 ['Cele 7 milioane de decese anuale sunt estimația OMS.','Cele trei prevalențe britanice sunt juxtapuse.','Cei 40% dintre copii sunt cifra globală din 2004.','Hidrocarburile aromatice policiclice și nitrozaminele sunt carcinogenii citați.','Textul deschide capitolul cu declinul prevalenței în lumea vestică.']],
 8,'Inversează trendul prevalenței, deși 51% și 17,2% stau în aceeași frază.',['7 milioane de decese','17,2% din populaţia adultă']),

q(80,['Dacă abstinența tabagică nu a fost obținută, tratamentul de substituție nicotinică trebuie schimbat după:',
 ['3 zile','3 săptămâni','3 luni','3 ani','Nicio reevaluare, aceeași schemă pe termen nedefinit'],'C',963,'Oprirea fumatului',
 'Reținerea pragului de 3 luni după care se schimbă substituția dacă abstinența a eșuat.',
 ['3 zile este prea scurt față de fereastra citată.','3 săptămâni nu este intervalul din text.','Textul cere schimbarea tratamentului după 3 luni dacă abstinența nu a fost obținută.','3 ani depășește reevaluarea descrisă.','Reevaluarea la 3 luni este explicită; prima prescripție acoperă 2 săptămâni după data-țintă.']],
 8,'3 luni (schimbare) și 2 săptămâni (prima prescripție) sunt ferestrele alăturate din același paragraf.',['după 3 luni','substituţie nicotinică']),

q(81,['Alți markeri de pneumonie comunitară severă, în afara CURB-65, includ:',
 ['Afectarea a mai mult de un lob pe radiografia toracică','PaO2 <60 mmHg (8 kPa)','Albumină serică <3,5 g/dl','Leucocite între 6 și 8×10³/µL, ca unică anomalie','Febră înaltă la vârstnici, ca semn de prognostic bun'],'ABC',964,'Cadranul 28.35 — Alți markeri',
 'Recunoașterea markerilor suplimentari (multilobar, hipoxemie, hipoalbuminemie) față de scorul CURB-65.',
 ['Afectarea multilobară este listată ca marker de severitate.','PaO2 <60 mmHg figurează în aceeași listă.','Albumina <3,5 g/dl este un marker enumerat.','Leucocitele de alarmă sunt <4 sau >20×10³/µL, nu valorile normale.','Absența febrei la vârstnici, nu febra înaltă, este markerul de gravitate.']],
 8,'Înlocuiește pragurile de leucocite <4/>20 și absența febrei la vârstnici cu valori „liniștitoare”.',['Albumina serică scăzută','P,D2']),

q(82,['O femeie de 68 de ani este internată cu suspiciune de pneumonie, dar radiografia inițială este normală. Următoarele sunt adevărate:',
 ['Anomaliile radiologice pot apărea mai târziu față de semnele clinice','Radiografia normală la prezentare trebuie repetată după 2–3 zile dacă suspiciunea clinică persistă','Tromboprofilaxia cu HGMM în doză mică este indicată la internarea >12 ore, în absența contraindicațiilor','Radiografia inițială normală exclude definitiv pneumonia','Tromboprofilaxia se omite sistematic, pneumonia nefiind o stare procoagulantă'],'ABC',965,'Investigații — Radiografia; Abordare terapeutică generală',
 'Articularea întârzierii radiologice (reevaluare 2–3 zile) cu tromboprofilaxia după 12 ore de internare.',
 ['Decalajul clinic–radiologic este explicit.','Repetarea la 2–3 zile este cerută când suspiciunea persistă.','Pragul de 12 ore pentru HGMM și ciorapi este listat.','Radiografia normală nu exclude, de aceea se repetă.','Tromboprofilaxia este o rubrică distinctă a abordării generale.']],
 8,'Neagă atât decalajul radiologic cât și tromboprofilaxia, două măsuri din aceeași pagină de management.',['după 2-3 zile','internat >12 ore']),

q(83,['Antibioticele parenterale din pneumonia comunitară internată se înlocuiesc cu orale după ce temperatura s-a stabilizat pentru:',
 ['2 ore','6 ore','24 de ore, dacă nu există contraindicație orală','14 zile de febră continuă','Nicio conversie, calea i.v. se menține până la externare'],'C',965,'Abordare terapeutică generală — Antibiotice',
 'Reținerea ferestrei de 24 de ore afebrilă pentru switch-ul i.v.–oral.',
 ['2 ore este prea scurtă.','6 ore nu este pragul din text.','Stabilizarea termică 24 de ore, fără contraindicație orală, autorizează înlocuirea.','14 zile de febră ar semnala eșec, nu momentul conversiei.','Textul cere explicit trecerea la oral după stabilizare, nu menținerea i.v. rituală.']],
 8,'24 de ore (switch) se confundă cu fereastra de o oră a primei doze, de pe aceeași pagină.',['perioadă de 24 de ore','Prima doză de antibiotic']),

q(84,['În algoritmul CRB-65/CURB-65 al pneumoniei comunitare:',
 ['La CRB-65 = 0, amoxicilina orală 500 mg × 3/zi (sau doxiciclina 100 mg/zi după încărcare 200 mg) este o opțiune','La CURB-65 3–5, co-amoxiclav 1,2 g × 3/zi i.v. plus claritromicină 500 mg × 2/zi i.v. este schema citată','Pacienții >65 de ani nevaccinați, spitalizați cu PC, trebuie să primească vaccinul pneumococic înainte de externare','La CRB-65 = 0 se impune co-amoxiclav i.v. și antigen urinar Legionella de rutină','Doxiciclina se încarcă cu 20 mg, nu cu 200 mg'],'ABC',966,'Fig. 28.29 — Algoritm PC; Prevenție',
 'Potrivirea treptei CRB-65 0 (oral) cu treapta CURB 3–5 (co-amoxiclav i.v.) și cu vaccinul la externare.',
 ['Dozele orale de amoxicilină/doxiciclină pentru riscul mic sunt în figură.','Schema i.v. co-amoxiclav + claritromicină este cea a treptei 3–5.','Vaccinul pneumococic înainte de externare este cerut la >65 de ani nevaccinați.','Formele ușoare nu necesită microbiologie de rutină nici co-amoxiclav i.v.','Doza de încărcare a doxiciclinei este 200 mg, apoi 100 mg/zi.']],
 8,'Mută schema i.v. a treptei severe asupra CRB-65 0, o confuzie de treaptă din aceeași figură.',['Amoxicilină oral 500 mg','vaccinul pneu­mococic']),

q(85,['Pneumonia nosocomială este definită prin tuse și expectorație purulentă cu condensare radiologică la pacienți:',
 ['Spitalizați de cel puțin 2 zile sau care au fost într-o instituție medicală în ultimele 3 luni','Prezentați din comunitate în prima oră, fără contact sanitar','Cu simptome de 3 săptămâni de tuse, fără internare','Doar după 6 luni de la orice contact medical','Rezervată copiilor, nu adulților din cămine'],'A',967,'Pneumonia nosocomială (dobândită în spital)',
 'Reținerea ferestrelor 2 zile de spitalizare sau 3 luni de instituție (inclusiv cămine).',
 ['Aceasta este definiția: ≥2 zile internare sau instituție în ultimele 3 luni.','Prezentarea comunitară fără contact sanitar definește PC, nu PN.','Tusea de 3 săptămâni este pragul de alarmă oncologic, nu definiția PN.','Fereastra instituțională este 3 luni, nu 6.','PN este a doua infecție nosocomială ca frecvență, cu risc la vârstnici.']],
 8,'2 zile și 3 luni trebuie ținute împreună; distractorii le înlocuiesc cu ferestre din alte capitole.',['cel puţin 2 zile','ultimele 3 luni']),

q(86,['Pneumonia nosocomială, comparativ cu cea comunitară:',
 ['Este a doua cea mai frecventă infecție nosocomială, după infecțiile de tract urinar','Micro-organismele diferă de cele ale PC; cadranul listează Pseudomonas, Escherichia, Klebsiella, anaerobi, S. aureus (inclusiv MRSA) și Acinetobacter','Virușii și fungii afectează gazdele imunocompetente în aceeași măsură ca bacteriile Gram-negative','Este mai rară decât orice altă infecție nosocomială','Aspirația gastrică în sarcină (Mendelson) este forma ușoară, autolimitată, a PN'],'AB',967,'Pneumonia nosocomială; Cadranul 28.39',
 'Ierarhia „a doua după ITU” și spectrul Gram-negativ/MRSA, distinct de PC și de Mendelson.',
 ['Locul doi după ITU este explicit.','Lista de germeni din cadran deosebește PN de PC.','Virușii sau fungii afectează doar gazdele imunodeprimate.','Textul o plasează a doua, nu ultima.','Mendelson este pneumonia de aspirație gastrică, extrem de severă, nu o PN banală.']],
 8,'Confundă PN cu Mendelson și inversează ierarhia infecțiilor nosocomiale.',['a doua cea mai frecventă','Acinetobacter spp.']),

q(87,['Epidemiologia tuberculozei, conform textului:',
 ['Este estimat că o treime din populația globului este infectată','A fost responsabilă de 1,6 milioane de decese în 2017, din care 20% la co-infectați HIV','Incidența mare într-o țară este definită ca >40/100.000','Deficiența de vitamină D figurează printre factorii de imunodeficiență asociați riscului','TB a dispărut din țările dezvoltate, fără factori de risc residuali'],'ABCD',968,'Tuberculoza — Epidemiologie; Cadranul 28.40',
 'Cuantificarea infecției globale (1/3), a mortalității 2017 și a pragului epidemiologic >40/100.000.',
 ['Fracția de o treime este cifra de deschidere.','1,6 milioane și ponderea de 20% HIV sunt explicite.','Pragul >40/100.000 definește țara cu incidență mare.','Vitamina D este listată la imunodeficiență.','Cadranul enumeră numeroși factori de risc și în țările dezvoltate.']],
 8,'1,6 milioane și 20% HIV se țin împreună; distractorul neagă persistența riscului în țările dezvoltate.',['1,6 milioane de decese','>40/100.000']),

q(88,['Tuberculoza miliară se manifestă radiografic prin micronoduli similari cu:',
 ['Calciile pleurale de azbest','Semințele de mei','Nivoul hidroaeric al abcesului','Semnul inelului cu pecete','O cavernă unică apicală, fără diseminare'],'B',969,'Alte forme de TB — TB miliară',
 'Reținerea analogiei „semințe de mei” și a indicației de RMN cerebral la toți pacienții.',
 ['Plăcile de azbest țin de mezoteliom, nu de miliara TB.','Termenul „miliară” vine din aspectul de semințe de mei.','Nivoul hidroaeric descrie abcesul pulmonar.','Inelul cu pecete este semnul HRCT al bronșiectaziilor.','Miliara este diseminare hematogenă cu micronoduli multipli, nu o cavernă izolată.']],
 8,'Toate analogiile imagistice apar în capitol, dar doar meiurile definesc miliara.',['seminţele de mei','diseminare hematogenă']),

q(89,['În diagnosticul formelor extrapulmonare de TB sunt adevărate:',
 ['Aspiratul gastric poate fi util la pacienții pediatrici','Sputa indusă (salină hipertonă) are randament comparabil cu prelevările bronhoscopice','În TB a SNC, proteinele LCR sunt de obicei >2–3 g/L, glucoza LCR <½ din cea sanguină, cu limfocitoză','Un singur eșantion de spută de după-amiază înlocuiește protocolul de dimineață','RMN-ul cerebral se omite sistematic, neexistând risc de afectare a SNC'],'ABC',970,'Cadranul 28.42 — Localizări și investigații TB',
 'Asocierea aspiratului gastric pediatric și a sputei induse cu triada biochimică a LCR din TB a SNC.',
 ['Aspiratul gastric este rubrica pediatrică din cadran.','Comparabilitatea cu bronhoscopia este explicită.','Triada proteină înaltă – hipoglicorahie – limfocitoză este listată.','Cadranul cere ≥2 eșantioane pentru a crește randamentul; protocolul matinal rămâne standard.','IRM cerebrală urmată de PL trebuie făcute în toate cazurile de miliara, absența contraindicațiilor.']],
 8,'Triada LCR se confundă ușor cu un lichid bacterian clasic; distractorii taie probele pediatrice și RMN-ul.',['Aspiratul gastric','>2-3 g/L'],[969]),

q(90,['Precizați enunțul corect referitor la etambutol în tratamentul TB:',
 ['Se oprește doar dacă apare gută hiperuricemică, fără evaluare oftalmologică','Doza este 50 mg/kg, fără plafon','Nevrita optică se manifestă cu discromatopsie pentru albastru, nu pentru verde','Colorează urina în roșu/roz, ca rifampicina','Doza este de 15 mg/kg, cu o doză maximă de 1,2 g; acuitatea și vederea în culori se evaluează înainte (Snellen, Ishihara)'],'E',971,'Efecte nedorite — Etambutolul',
 'Reținerea dozei 15 mg/kg (max. 1,2 g) și a discromatopsiei pentru verde, distincte de rifampicină și pirazinamidă.',
 ['Guta ține de pirazinamidă; etambutolul cere evaluare oftalmologică.','50 mg/kg depășește doza și plafonul citați.','Discromatopsia descrisă este pentru verde.','Colorarea roșu/roz a secrețiilor este a rifampicinei.','Doza, plafonul și testele Snellen/Ishihara sunt cele din text.']],
 8,'Mută guta (pirazinamidă) și culoarea urinei (rifampicină) asupra etambutolului, păstrând același cadran de toxicitate.',['15 mg/kg','planşele lshihara']),

q(91,['Vaccinarea BCG și infecția cu micobacterii netuberculoase:',
 ['BCG este un vaccin viu atenuat derivat din M. bovis care și-a pierdut virulența','Tratamentul NTM se recomandă dacă tabloul este compatibil și organismul e izolat dintr-un prelevat invaziv sau din minimum două eșantioane de spută la momente diferite','Chimioprofilaxia ITBL se oferă celor care urmează să înceapă agenți biologici (ex. infliximab)','BCG este oferit de rutină tuturor adulților din SUA, ca strategie cost-eficientă','M. gordonae este descris ca cel mai virulent patogen pulmonar la imunocompetent'],'ABC',972,'Vaccinarea BCG; Infecția cu NTM',
 'Distingerea originii BCG (M. bovis atenuat) de criteriile de tratament NTM (2 spute sau prelevat invaziv).',
 ['Originea din M. bovis atenuat este explicită.','Criteriul celor două spute sau al prelevatului invaziv este regula de tratament.','Infliximab-ul figurează pe lista de indicații ale chimioprofilaxiei ITBL.','Textul precizează că BCG nu mai este oferit de rutină tuturor (și nu în SUA), din lipsa cost-eficacității.','M. gordonae este listat printre NTM; virulența înaltă la imunocompetent nu este atribuită acestei specii în textul de față.']],
 8,'Extinde BCG la SUA și la toți adulții, contrar precizării de lipsă a cost-eficacității.',['vaccin viu atenuat','minimum două eşantioane']),

q(92,['Toracocenteza (aspirația) pneumotoracelui se poate lua în considerare la pacienții simptomatici cu un pneumotorace:',
 ['>2 cm (primar) sau 1 cm (secundar)','<2 mm, asimptomatic, fără control radiologic','Doar dacă este hipertensiv, după intubație','Orice lamă de aer, inclusiv la trauma majoră, ca primă manevră','Tubul de dren intercostal este unica manevră acceptată, aspirația fiind abandonată'],'A',975,'Toracocenteza; Cadranul 28.49',
 'Reținerea pragurilor 2 cm (primar) și 1 cm (secundar) care autorizează aspirația simplă.',
 ['Acestea sunt pragurile dimensionale din text.','O lamă de 2 mm asimptomatică se gestionează conservator, nu prin aspirație.','Pneumotoracele hipertensiv/traumatic orientează spre dren intercostal, nu spre aspirație ca primă intenție.','În trauma, aspirația nu se recomandă în general.','Aspirația este o opțiune intermediară, înaintea drenului.']],
 8,'2 cm versus 1 cm (primar/secundar) se amestecă ușor cu indicația de dren din același paragraf.',['>2 cm','1 cm în pneumotoracele se­cundar']),

q(93,['Drenajul pleural intercostal în pneumotorace, când este indicat, se introduce de regulă:',
 ['În spațiul 2 intercostal pe linia medioclaviculară, ca unică cale','În spațiul 4 intercostal pe linia axilară medie, conectat la un tub imersat în apă ținut sub nivelul toracelui','Subdiafragmatic, pentru a evita pleura','Prin carină, sub ghidaj bronhoscopic','În apexul posterior, fără recipient'],'B',975,'Drenajul pleural intercostal',
 'Reținerea locului (spațiul 4, linia axilară medie) distinct de punctul de aspirație simplă (spațiul 2 medioclavicular).',
 ['Spațiul 2 medioclavicular este al aspirației simple (cadranul 28.49), nu al drenului.','Spațiul 4 pe linia axilară medie și imersia în apă sub torace sunt pașii descriși.','Inserția subdiafragmatică ar leza abdomenul.','Bronhoscopia nu este calea de dren pleural.','Recipientul și poziția sub torace sunt obligatorii pentru siguranța sigiliului hidraulic.']],
 8,'Confundă punctul de aspirație (IC2 medioclavicular) cu cel de dren (IC4 axilar mediu), ambele pe aceeași pagină.',['spaţiul 4 intercostal','linia axilară medie']),

q(94,['Cancerul bronhopulmonar, ca povară epidemiologică:',
 ['Determină aproximativ 1,76 milioane de decese anual','Este a cincea cea mai frecventă cauză de deces în Marea Britanie','Reprezintă cea mai frecventă cauză de deces prin cancer atât la bărbați, cât și la femei','A fost depășit, ca mortalitate prin cancer, de melanomul cutanat la ambele sexe','Incidența este mai mică în mediul urban decât în cel rural, după ajustarea pentru fumat'],'ABC',975,'Cancerul bronhopulmonar — Introducere',
 'Poziționarea mortalității globale (1,76 milioane) și a rangului 5 în UK, plus întâietatea pe sexe.',
 ['Cifra 1,76 milioane este de deschidere.','Rangul 5 în Marea Britanie este explicit.','Întâietatea ca deces prin cancer la ambele sexe este citată.','Textul îl plasează ca cea mai frecventă cauză de deces prin cancer, nu ca fiind depășit de melanom.','Incidența este mai mare în mediul urban, chiar după ajustarea pentru fumat.']],
 8,'Inversează gradientul urban–rural și detronarea pe sexe, două fapte din primul paragraf.',['1,76 milioane de decese','a cincea cea mai frecventă']),

q(95,['Wheezing-ul din cancerul bronșic și metastazele suprarenaliene:',
 ['Wheezing-ul este monofonic atunci când se datorează obstrucției parțiale a unei căi aeriene de către tumoră','Metastazele suprarenaliene nu duc de obicei la insuficiență suprarenală și sunt în general asimptomatice','Wheezing-ul astmatic difuz, polifonic, este mecanismul descris aici','Metastazele suprarenaliene produc clasic criză addisoniană la prezentare','Disfonia se datorează compresiei nervului frenic, nu a laringeului recurent stâng'],'AB',976,'Efectele locale; Metastazarea la distanță',
 'Diferențierea wheezing-ului monofonic tumoral de cel astmatic și a tăcerii clinice a metastazelor suprarenaliene.',
 ['Caracterul monofonic al obstrucției parțiale tumorale este explicit.','Absența obișnuită a insuficienței suprarenaliene este precizată.','Wheezing-ul de aici este local, monofonic, nu polifonic difuz.','Textul le descrie ca în general asimptomatice.','Disfonia ține de nervul laringeu recurent stâng; frenicul dă paralizie diafragmatică.']],
 8,'Mută disfonia pe frenicul (paralizie diafragmatică) și inventează criza addisoniană, contrar „asimptomatic”.',['Wheezingul. Este monofonic','glandele suprarenale']),

q(96,['Limfangita carcinomatoasă pe radiografia toracică:',
 ['În cancerul bronșic este de obicei unilaterală și asociată cu dispnee frapantă','În forma bilaterală trebuie cercetat rapid un situs primar extrapulmonar (sân, stomac sau colon)','O radiografie normală nu exclude o tumoră subiacentă, în special la fumătorii peste 40 de ani cu hemoptizie','Limfangita este aproape doar bilaterală în cancerul bronșic primar','Radiografia normală la fumătorul de peste 40 de ani cu hemoptizie închide investigațiile'],'ABC',977,'Cadranul 28.51 — Aspecte radiografice',
 'Separarea limfangitei unilaterale (primar pulmonar) de cea bilaterală (sân/stomac/colon) și a valorii negative limitate a radiografiei.',
 ['Unilateralitatea și dispneea frapantă sunt caracteristicile din cadran.','Sânul, stomacul și colonul sunt situsurile de cercetat în forma bilaterală.','Avertismentul despre radiografia normală la fumătorul >40 de ani cu hemoptizie închide cadranul.','În cancerul bronșic limfangita este de obicei unilaterală.','Textul cere să nu se descurajeze investigațiile ulterioare.']],
 8,'Inversează lateralitatea limfangitei (uni- versus bilaterală) — cheia de localizare a primarului.',['limfangita carcinomatoasă','sânul, stomacul sau colonul']),

q(97,['Evaluarea ganglionilor și imagistica în cancerul pulmonar:',
 ['Ganglionii <1 cm pe CT nu sunt clasificați ca măriți, dar totuși pot conține celule maligne','RMN nu este utilă pentru diagnosticul tumorilor pulmonare primare, în afară de tumorile Pancoast cu invazie nervoasă sau de peretele toracic preoperator','Statusul de performanță ECOG trebuie evaluat la toți pacienții cu suspiciune de malignitate','Ganglionii <1 cm pe CT exclud metastaza N și fac PET-CT superfluu','RMN este investigația de primă intenție a oricărei mase pulmonare periferice'],'ABC',978,'Stadializare imagistică; ECOG',
 'Aplicarea limitei de 1 cm (fără certitudine de benignitate) și a nișei RMN (Pancoast/perete), plus ECOG obligatoriu.',
 ['Pragul de 1 cm și prezența posibilă a celulelor maligne sunt explicite.','Excepțiile Pancoast și perete toracic sunt singurele indicații de RMN pentru primar.','ECOG figurează ca evaluare la toți suspecții.','Chiar ganglionii nemăriți pot fi maligni; PET-CT și biopsia rămân necesare dacă se vizează tratament curativ.','RMN nu este utilă pentru diagnosticul tumorii pulmonare primare obișnuite.']],
 8,'Transformă pragul de 1 cm într-o excludere a malignității, deși textul avertizează opusul.',['diametru mai mic de 1 cm','tumorile Pancoast']),

q(98,['Radioterapia paliativă în neoplasmul pulmonar ameliorează:',
 ['Durerile osoase și ale peretelui toracic din metastaze sau invazie directă','Hemoptizia','Obstrucția bronșică și obstrucția venei cave superioare','Hipercalcemia paraneoplazică a scuamosului, ca efect metabolic direct','Screening-ul NLST, înlocuind CT-ul cu doză mică'],'ABC',980,'Radioterapia paliativă',
 'Reținerea celor patru ținte simptomatice ale iradierii scurte și a consolidării post-chimioterapie în SCLC.',
 ['Durerea osoasă/de perete este prima indicație listată.','Hemoptizia răspunde favorabil la iradierea pe termen scurt.','Obstrucția bronșică și cea de VCS sunt în aceeași listă.','Hipercalcemia este paraneoplazică, nu o indicație de RT paliativă din acest paragraf.','NLST este un studiu de screening CT, nu un efect al RT paliative.']],
 8,'Adaugă hipercalcemia (paraneoplazie scuamoasă) pe lista de indicații ale RT, deși textul enumeră doar simptome locale.',['Durerile osoase','obstrucţia venei cave superioare']),

q(99,['Tehnicile endobronșice paliative în cancerul pulmonar inoperabil:',
 ['Laserul Nd-Yag inserat prin fibrobronhoscop vaporizează carcinomul intraluminal pe segmente scurte de trahee sau bronșie principală','Crioterapia îngheață și dezgheață tumora repetat, restabilind permeabilitatea fără a provoca sângerare; țesutul poate fi trimis la histologie','Stenturile din silicon sau metalice expandabile se inseră la stricturi, compresie externă sau colaps al peretelui','Laserul Nd-Yag este rezervat metastazelor cerebrale, nu căilor aeriene','Crioterapia este contraindicată pentru că produce hemoptizie incoercibilă de rutină'],'ABC',980,'Laserterapia, crioterapia și stenturile traheobronșice',
 'Diferențierea vaporizării Nd-Yag de criosonda care păstrează țesut pentru histologie și de stentul de calibru.',
 ['Indicația Nd-Yag pe trahee/bronșie principală este explicită.','Ciclu îngheț–dezgheț, absența sângerării și trimiterea la histologie sunt descrise.','Cele două materiale de stent și cele trei indicații sunt listate.','Nd-Yag este o tehnică endobronșică, nu cerebrală.','Textul subliniază tocmai absența sângerării la crioterapie.']],
 8,'Mută Nd-Yag în creier și inversează avantajul hemostatic al crioterapiei.',['neodim-Yag','Criosonda']),

q(100,['Identificați afirmația corectă referitoare la tumorile pulmonare secundare:',
 ['Primarul tipic este un carcinom bazocelular cutanat, fără alte origini','Limfangita carcinomatoasă din stomac, pancreas sau sân dă dispnee progresivă severă, cu adenopatii hilare unilaterale izolate, fără opacități liniare','Metastazele unice se rezecă fără PET-CT preoperator, radiografia fiind suficientă','Primarul este localizat tipic la rinichi, prostată, sân, oase, tract gastrointestinal, col uterin sau ovar','Hamartomul este cea mai frecventă metastază osteosarcomatoasă'],'D',981,'Tumorile secundare',
 'Reținerea listei de primare (rinichi, prostată, sân…) și a necesității PET-CT înaintea rezecției unei metastaze unice.',
 ['Carcinomul bazocelular nu figurează pe lista de primare tipice.','Limfangita din stomac/pancreas/sân este bilaterală, cu opacități liniare bazale, nu doar o adenopatie unilaterală.','CT descoperă metastaze mici ratate de radiografie; PET-CT preoperator este esențial.','Aceasta este lista de origini tipice din text.','Hamartomul este tumora benignă pulmonară cea mai frecventă, nu o metastază.']],
 8,'Înlocuiește lista viscerală de primare cu un cancer cutanat sau cu hamartomul benign de pe aceeași pagină.',['rinichiul, prostatei, sânului','scanarea PET-CT']),

q(101,['Screeningul cancerului pulmonar prin CT elicoidal cu doze mici, în studiul american citat, a vizat fumători și ex-fumători cu vârste:',
 ['25–35 de ani, cu un beneficiu de mortalitate de 2%','55–74 de ani, cu un beneficiu de 20% privind mortalitatea','80–90 de ani, nefumători, fără beneficiu măsurat','Copii cu hipertrofie amigdaliană','Doar femei sub 40 de ani, nefumătoare'],'B',981,'Screeningul cancerului pulmonar',
 'Reținerea ferestrei 55–74 de ani și a reducerii de 20% a mortalității din studiul american.',
 ['25–35 de ani nu este populația NLST.','Vârstele 55–74 și beneficiul de 20% sunt cifrele din text.','Studiul a vizat fumători/ex-fumători, nu nefumători octogenari.','Hipertrofia amigdaliană ține de ASO pediatrică, nu de screeningul oncologic.','Populația este de fumători/ex-fumători 55–74 de ani, nu tinere nefumătoare.']],
 8,'55–74 și 20% trebuie ținute împreună; distractorii mută vârsta în alte capitole (ASO, tuse cronică).',['55 şi 74 de ani','beneficiu de 20%'],[982]),

q(102,['Tumorile carcinoide bronșice:',
 ['Sunt de obicei neoplasme cu grad scăzut de malignitate și creștere lentă, provenite din tumori neuroendocrine, circa 1% din tumorile bronșice','Secretă de obicei ACTH (derivate ale proenteronului), dar de obicei nu secretă 5-hidroxitriptamină','Stadializarea este aceeași ca pentru NSCLC; chirurgia este tratamentul de elecție, cu supraveghere pe termen lung','Sunt cele mai frecvente cancere pulmonare la fumători, depășind scuamosul','Secretă 5-hidroxitriptamină ca tumorile intestinului mijlociu, nu ACTH'],'ABC',982,'Tumorile carcinoide bronșice',
 'Asocierea originii neuroendocrine (1%) cu secreția de ACTH (nu 5-HT) și cu stadializarea tip NSCLC.',
 ['Gradul scăzut, originea neuroendocrine și ponderea de 1% sunt explicite.','Contrastul ACTH versus 5-HT (intestin mijlociu/posterior) este precizat.','Stadializarea NSCLC, chirurgia și supravegherea lungă sunt descrise.','Ponderea de 1% le face rare, nu tipul dominant al fumătorului.','Textul precizează opusul: de obicei nu secretă 5-hidroxitriptamină.']],
 8,'Inversează profilul secretor ACTH versus 5-HT, capcana clasică a carcinoidului bronșic versus intestinal.',['aproximativ 1%','hormon adrenocorticotrop']),
];
