import {rewriter} from './rewrite-author';
import {RETIRED_PSIHIATRIE} from './retired/psihiatrie';

// Rewritten after the 2026-09-24 cue audit (Sinopsis, cap. 14, p. 319–330).
const q=rewriter(RETIRED_PSIHIATRIE,(p:number)=>p-222,{shuffle:true});

export const PSIHIATRIE_V2=[
q('psihiatrie-adv-001',['Schizofrenia:',
 ['debutează tipic în adolescența târzie sau la adultul tânăr','cere afectarea funcționării sociale peste 6 luni','are prognostic mai prost când predomină simptomele negative','cere un singur simptom caracteristic timp de o lună','are o rată mai mică la persoanele fără domiciliu'],'ABC',319,'Schizofrenia',
 'Recunoașterea criteriilor și a prognosticului schizofreniei.',
 ['Debutul tipic este în adolescența târzie sau la adultul tânăr.','Funcționarea socială este afectată peste 6 luni.','Simptomele negative și suportul slab agravează prognosticul.','Sunt necesare cel puțin două simptome.','Rata este crescută la persoanele fără domiciliu.']],
 [8,'Distractorii reduc numărul de simptome și inversează factorul social.'],['adolescenţa târzie','6 luni'],[320]),

q('psihiatrie-adv-038',['Conform Tabelului 14-1, neurolepticele cu potență ridicată:',
 ['includ haloperidolul și flufenazina','se folosesc în controlul de urgență al agitației','produc mai multe efecte extrapiramidale','produc mai multe efecte anticolinergice','blochează în principal receptorii serotoninergici'],'ABC',319,'Tabelul 14-1',
 'Diferențierea neurolepticelor după potență.',
 ['Haloperidolul și flufenazina sunt de potență ridicată.','Sunt folosite în controlul de urgență al psihozei sau agitației.','Au mai multe efecte extrapiramidale.','Au mai puține efecte anticolinergice.','Blochează receptorii D2.']],
 [8,'Distractorii preiau profilul potenței reduse și al atipicelor.'],['Controlul de urgenţă','extrapiramidal']),

q('psihiatrie-adv-030',['Conform Tabelului 14-1, antipsihoticele atipice:',
 ['sunt de primă linie în tratamentul de întreținere','blochează receptorii dopaminei și serotoninei','includ clozapina, rezervată psihozei refractare','pot produce creștere ponderală','au mai multe efecte adverse decât cele clasice'],'ABCD',319,'Tabelul 14-1',
 'Recunoașterea locului antipsihoticelor atipice.',
 ['Sunt de primă linie în întreținerea tulburărilor psihotice.','Blochează receptorii dopaminei și serotoninei.','Clozapina este rezervată psihozei refractare (agranulocitoză).','Creșterea ponderală este un efect advers citat.','Au mai puține efecte secundare decât cele tradiționale.']],
 [8,'Singurul distractor inversează profilul de siguranță.'],['Medicamente de primă linie','agranulocitoză']),

q('psihiatrie-adv-023',['Conform Tabelului 14-2, sindromul neuroleptic malign se deosebește de sindromul serotoninergic prin:',
 ['rigiditate plastică și reflexe scăzute','debut abrupt și evoluție rapid rezolutivă','mioclonii și hipertonie la membrele inferioare','piele uscată și ileus','tratament cu ciproheptadină'],'A',320,'Tabelul 14-2',
 'Diferențierea sindromului neuroleptic malign de sindromul serotoninergic.',
 ['SNM are rigiditate „țeavă de plumb” și reflexe scăzute.','Descrie sindromul serotoninergic.','Descrie sindromul serotoninergic.','Descrie sindromul anticolinergic.','Ciproheptadina tratează sindromul serotoninergic.']],
 [8,'Distractorii preiau trăsăturile celorlalte sindroame din tabel.'],['ţeavă de plumb','Ciproheptadină']),

q('psihiatrie-adv-040',['Conform Tabelului 14-2, sindromul toxic anticolinergic se caracterizează prin:',
 ['piele uscată','midriază','zgomote intestinale diminuate','tratament cu fizostigmină','transpirații profuze'],'ABCD',320,'Tabelul 14-2',
 'Recunoașterea sindromului anticolinergic.',
 ['Pielea este uscată.','Pupilele sunt midriatice („orb ca liliacul”).','Apare ileus.','Fizostigmina este tratamentul adjuvant.','Transpirațiile apar în celelalte sindroame.']],
 [8,'Singurul distractor preia semnul celorlalte sindroame.'],['Fizostigmină','liliacul']),

q('psihiatrie-adv-047',['Sindromul neuroleptic malign:',
 ['apare la câteva zile de la inițierea antipsihoticului','are o rată înaltă de mortalitate','asociază CPK crescută și rigiditate musculară','impune continuarea antipsihoticului în doză redusă','are evoluție rapid rezolutivă, în câteva ore'],'ABC',321,'Sindromul neuroleptic malign',
 'Recunoașterea și conduita în sindromul neuroleptic malign.',
 ['Apare la câteva zile de la inițiere.','Are o rată înaltă de mortalitate.','„FEVER”: enzime (CPK) crescute, rigiditate.','Medicamentul se oprește imediat.','Evoluția este prelungită, zile până la săptămâni.']],
 [8,'Distractorii contrazic oprirea medicamentului și evoluția.'],['înaltă de mortalitate','FEVER'],[320]),

q('psihiatrie-adv-032',['Diskinezia tardivă:',
 ['este o complicație a medicației antipsihotice','produce mișcări faciale repetitive, de tip masticator','apare după câteva luni de tratament','poate fi ireversibilă','apare în primele ore după prima doză'],'ABCD',321,'Diskinezia tardivă',
 'Recunoașterea diskineziei tardive.',
 ['Este o complicație a antipsihoticelor.','Mișcările sunt faciale, masticatorii, plescăit.','Apare după câteva luni.','Poate fi ireversibilă chiar după oprire.','Apare după luni de tratament.']],
 [8,'Singurul distractor inversează momentul apariției.'],['plescăit','ireversibilă']),

q('psihiatrie-adv-002',['Alegeți afirmațiile corecte privind tulburările psihotice:',
 ['tulburarea schizofreniformă durează între o lună și 6 luni','tulburarea psihotică scurtă durează între o zi și o lună','tulburarea delirantă nu întrunește criteriile de schizofrenie','psihoza scurtă include simptomele negative între criterii','în schizoafectivă, psihoza apare doar în episodul afectiv'],'ABC',320,'Alte tulburări psihotice',
 'Diferențierea tulburărilor psihotice după durată și criterii.',
 ['Durata este de cel puțin o lună, fără a depăși 6 luni.','Durata este de cel puțin o zi, fără a depăși o lună.','Delirul durează ≥1 lună fără criteriile de schizofrenie.','Simptomele negative sunt excluse.','Psihoza trebuie să existe și separat de episodul afectiv.']],
 [8,'Distractorii inversează excepțiile din criterii.'],['schizofreniformă','o zi']),

q('psihiatrie-adv-039',['Spre deosebire de tulburarea depresivă majoră cu simptome psihotice, tulburarea schizoafectivă cere:',
 ['psihoză prezentă și separat de episodul afectiv','psihoză limitată strict la durata episoadelor afective','cel puțin un episod maniacal complet','simptome psihotice peste 2 ani','absența oricărui episod depresiv'],'A',320,'Tulburarea schizoafectivă',
 'Diferențierea tulburării schizoafective de tulburările afective cu psihoză.',
 ['Psihoza trebuie să existe distinct de simptomele afective.','Descrie TDM sau mania cu psihoză.','Poate apărea și cu episod depresiv.','Nu este criteriul citat.','Episodul poate fi depresiv sau maniacal.']],
 [8,'Distractorii preiau criteriile tulburărilor afective.'],['schizoafectivă','distinct']),

q('psihiatrie-adv-003',['Tulburarea depresivă majoră:',
 ['cere cinci simptome pe o durată de peste 2 săptămâni','cere prezența dispoziției depresive sau a anhedoniei','recidivează la aproximativ 50% după remisiune','cere prezența ideației suicidale în toate cazurile','poate fi diagnosticată la 3 simptome dacă există anhedonie'],'ABC',321,'Tulburarea depresivă majoră',
 'Aplicarea criteriilor de diagnostic ale TDM.',
 ['Sunt necesare cinci simptome peste 2 săptămâni.','Unul dintre ele este dispoziția depresivă sau anhedonia.','Rata de recurență este de 50%.','Ideația suicidală este doar unul dintre simptome.','Sunt necesare cinci simptome.']],
 [8,'Distractorii schimbă numărul și natura criteriilor.'],['rată de recurenţă de 50%','anhedonia']),

q('psihiatrie-adv-043',['Conform textului, pot produce simptome depresive:',
 ['glucocorticoizii','interferonul α','hipotiroidismul','boala Parkinson','hipertiroidismul'],'ABCD',321,'Tulburarea depresivă majoră',
 'Recunoașterea cauzelor iatrogene și medicale de depresie.',
 ['Glucocorticoizii sunt citați.','Interferonul α este citat.','Hipotiroidismul este citat.','Boala Parkinson este citată.','Lista citează hipotiroidismul și hiperparatiroidismul.']],
 [8,'Singurul distractor inversează disfuncția tiroidiană.'],['glucocorticoizii','boala Parkinson']),

q('psihiatrie-adv-041',['Subtipurile tulburării depresive majore:',
 ['forma cu simptome atipice este cea mai frecventă','forma atipică asociază hiperfagie și hipersomnie','forma sezonieră se tratează cu fototerapie','forma peripartum debutează în sarcină sau în primele 4 săptămâni postpartum','forma atipică asociază insomnie și scădere ponderală'],'ABCD',321,'Subtipuri de TDM',
 'Diferențierea subtipurilor de TDM.',
 ['Forma atipică este cel mai frecvent subtip.','Include hiperfagie, hipersomnie, „membre de plumb”.','Fototerapia tratează forma sezonieră.','Debutul este în sarcină sau în primele 4 săptămâni după naștere.','Forma atipică are hiperfagie și hipersomnie.']],
 [8,'Singurul distractor inversează semnele vegetative.'],['fototerapie','membre de plumb']),

q('psihiatrie-adv-042',['Tulburarea depresivă persistentă:',
 ['cere simptome depresive pe o perioadă de peste 2 ani','cere disforie plus cel puțin două alte simptome','poate include depresia majoră cronică','cere simptome depresive pe o perioadă de peste 6 luni','exclude pacienții care întrunesc criteriile de TDM'],'ABC',321,'Tulburarea depresivă persistentă',
 'Aplicarea criteriilor tulburării depresive persistente.',
 ['Durata este de peste 2 ani.','Disforia plus cel puțin două simptome.','Include depresia majoră cronică.','Durata este de peste 2 ani.','Poate include depresia majoră cronică.']],
 [8,'Distractorii scurtează durata și exclud TDM cronică.'],['disforiei','Depresia majoră cronică']),

q('psihiatrie-adv-024',['Conform Tabelului 14-3:',
 ['ADT în supradoză pot fi fatale prin alungirea QTc','IMAO plus tiramină pot provoca crize hipertensive','bupropionul scade pragul convulsivant','SSRI își ating efectul terapeutic în 24 de ore','mirtazapina reduce apetitul alimentar și greutatea'],'ABC',322,'Tabelul 14-3',
 'Recunoașterea efectelor adverse ale antidepresivelor.',
 ['Supradoza de 5 ori doza terapeutică poate fi fatală prin QTc.','Alimentele cu tiramină pot provoca crize hipertensive.','Bupropionul scade pragul convulsivant, fără disfuncție sexuală.','SSRI necesită 3–4 săptămâni.','Mirtazapina stimulează apetitul.']],
 [8,'Distractorii inversează latența și efectul pe apetit.'],['crize hipertensive','QTc']),

q('psihiatrie-adv-045',['Conform Tabelului 14-3, indicațiile antidepresivelor includ:',
 ['SNRI în depresia comorbidă cu durere neuropată','bupropionul în renunțarea la fumat','trazodona în depresia cu insomnie semnificativă','mirtazapina în depresia cu insomnie sau anorexie','IMAO ca tratament de primă linie al depresiei'],'ABCD',322,'Tabelul 14-3',
 'Alegerea antidepresivului după comorbidități.',
 ['SNRI sunt de primă linie în depresia cu durere neuropată.','Bupropionul este indicat în renunțarea la fumat.','Modulatorii serotoninei: depresie cu insomnie.','Mirtazapina: depresie cu insomnie și/sau anorexie.','IMAO sunt folosiți rar.']],
 [8,'Singurul distractor inversează locul IMAO.'],['insomnie semnificativă','renunţarea la fumat']),

q('psihiatrie-adv-025',['Episodul hipomaniacal:',
 ['durează cel puțin 4 zile','cere trei sau mai multe simptome de manie','nu produce o afectare semnificativă a funcționării','durează cel puțin o săptămână','impune internare pentru afectarea funcționării'],'ABC',322,'Episodul hipomaniacal',
 'Diferențierea hipomaniei de manie.',
 ['Durata minimă este de 4 zile.','Sunt necesare trei sau mai multe simptome de manie.','Funcționarea nu este afectat semnificativ.','O săptămână este durata episodului maniacal.','Funcționarea nu este afectată semnificativ.']],
 [8,'Distractorii preiau criteriile maniei.'],['cel puţin 4 zile','hipomaniacal']),

q('psihiatrie-adv-026',['Tulburarea bipolară de tip II cere:',
 ['cel puțin un episod hipomaniacal și unul depresiv major','cel puțin un episod maniacal, depresia majoră fiind opțională','cicluri ușoare de peste 2 ani, fără eutimie','un episod maniacal și unul depresiv major','cel puțin două episoade hipomaniacale, fără depresie'],'A',322,'Tulburarea bipolară — Tipuri',
 'Diferențierea tipurilor de tulburare bipolară.',
 ['Tipul II: hipomanie și depresie majoră.','Descrie tipul I.','Descrie ciclotimia.','Mania definește tipul I.','Depresia majoră este necesară.']],
 [8,'Distractorii descriu tipul I și ciclotimia.'],['Tipul II','hipomaniacal']),

q('psihiatrie-adv-004',['Litiul:',
 ['este frecvent prima linie în întreținerea maniei','acționează probabil prin inozitoltrifosfat','poate produce diabet insipid nefrogen și hipotiroidism','este teratogen, putând produce anomalia Ebstein','produce frecvent scădere ponderală și hipertiroidism'],'ABCD',323,'Tulburarea bipolară — Tratament',
 'Recunoașterea profilului litiului.',
 ['Este frecvent prima linie în tratamentul de lungă durată al maniei.','Mecanismul implică probabil inozitoltrifosfatul.','Diabetul insipid nefrogen și hipotiroidismul sunt citate.','Anomalia Ebstein este efectul teratogen.','Produce creștere ponderală și hipotiroidism.']],
 [8,'Singurul distractor inversează efectele metabolice.'],['inozitoltrifosfatului','anomalia Ebstein']),

q('psihiatrie-adv-046',['Înainte de a prescrie un antidepresiv unui pacient cu suspiciune de TDM, trebuie exclus prin anamneză:',
 ['istoricul personal de manie','istoricul de tulburare de panică','istoricul de tulburare de anxietate socială','istoricul de fobie specifică în copilărie','istoricul familial de schizofrenie'],'A',323,'Tulburarea bipolară',
 'Aplicarea precauției antidepresivelor în tulburarea bipolară.',
 ['Antidepresivul fără stabilizator poate induce manie.','Nu este precauția citată.','Nu este precauția citată.','Nu este precauția citată.','Nu este precauția citată.']],
 [8,'Distractorii sunt antecedente psihiatrice plauzibile.'],['Istoricul personal de manie','episod maniacal']),

q('psihiatrie-adv-027',['Tulburarea ciclotimică:',
 ['are o durată de peste 2 ani','nu întrunește criteriile de manie sau depresie majoră','se tratează cu psihoterapie sau stabilizatori','permite perioade de eutimie de peste 2 luni','cere cel puțin un episod hipomaniacal complet'],'ABC',323,'Tulburarea ciclotimică',
 'Recunoașterea criteriilor ciclotimiei.',
 ['Ciclurile durează peste 2 ani.','Criteriile de TDM, manie sau hipomanie nu sunt întrunite.','Psihoterapie sau stabilizatori ai dispoziției.','Nu există dispoziție normală peste 2 luni.','Criteriile de hipomanie nu sunt întrunite.']],
 [8,'Distractorii contrazic excluderile din criterii.'],['Cicluri rapide','stabilizatori']),

q('psihiatrie-adv-006',['Tulburarea de panică:',
 ['debutează tipic în adolescență','are atacuri care durează până la maximum 30 de minute','se tratează pe termen lung cu SSRI sau SNRI','are atacuri declanșate de un obiect fobic anume','se tratează pe termen lung cu benzodiazepine'],'ABC',323,'Tulburarea de panică',
 'Recunoașterea și tratamentul tulburării de panică.',
 ['Debutul tipic este în adolescență.','Atacurile durează până la 30 de minute.','SSRI și SNRI sunt folosite pe termen lung.','Atacurile sunt spontane și imprevizibile.','Benzodiazepinele se folosesc pentru atacul de moment.']],
 [8,'Distractorii confundă panica cu fobia și tratamentul acut.'],['30 de minute','adolescenţă']),

q('psihiatrie-adv-028',['Conform Tabelului 14-4:',
 ['alprazolamul este util mai ales în atacurile de panică','clonazepamul este preferat în terapia de durată','buspirona se preferă când abuzul este un factor de risc','buspirona acționează prin stimularea inhibiției GABA-ergice','benzodiazepinele au sevraj care poate include convulsii'],'ABCE',323,'Tabelul 14-4',
 'Diferențierea anxioliticelor.',
 ['Debut rapid, timp de înjumătățire scurt.','Clonazepamul și diazepamul sunt utile în terapia prelungită.','Buspirona este indicată când abuzul sau sedarea sunt risc.','Mecanismul buspironei ține de receptorii serotoninei și dopaminei.','Sevrajul include neliniște, insomnie, convulsii.']],
 [8,'Singurul distractor atribuie buspironei mecanismul benzodiazepinelor.'],['Alprazolamul','Buspirona']),

q('psihiatrie-adv-007',['Antagonistul care poate anula efectele supradozei de benzodiazepine este:',
 ['flumazenilul','naloxona','naltrexona','bromocriptina','dantrolenul'],'A',324,'Supradoza de benzodiazepine',
 'Alegerea antidotului în supradoza de benzodiazepine.',
 ['Flumazenilul este antagonistul benzodiazepinelor.','Naloxona antagonizează opioizii.','Naltrexona este folosită în dependența de alcool și opioizi.','Bromocriptina se folosește în SNM.','Dantrolenul tratează hipertermia malignă.']],
 [8,'Distractorii sunt antidoturi din alte intoxicații.'],['Flumazenilul','doza letală']),

q('psihiatrie-adv-011',['Tulburarea de anxietate generalizată:',
 ['cere anxietate excesivă pe o durată de peste 6 luni','afectează de două ori mai frecvent femeile','cere trei simptome, precum tensiunea musculară','se tratează de durată mai sigur cu benzodiazepine','cere anxietate excesivă peste 2 săptămâni'],'ABC',324,'Tulburarea anxietății generalizate',
 'Aplicarea criteriilor și tratamentului GAD.',
 ['Durata este de peste 6 luni.','Riscul femeilor este dublu.','Sunt necesare trei simptome.','Buspirona este mai sigură pe termen lung.','Durata este de peste 6 luni.']],
 [8,'Distractorii scurtează durata și inversează siguranța.'],['riscul femeilor','tensiune musculară'],[323]),

q('psihiatrie-adv-017',['Tulburarea de anxietate socială:',
 ['se poate trata cu β-blocante în cazurile ușoare','răspunde frecvent la SSRI','poate folosi benzodiazepine ca alternativă în anxietatea acută','nu implică teama de evaluare din partea celorlalți','produce anxietate, dar fără atacuri de panică'],'ABC',324,'Tulburarea de anxietate socială',
 'Recunoașterea anxietății sociale și a tratamentului.',
 ['β-blocantele previn tahicardia în cazurile ușoare.','SSRI sunt frecvent eficace.','Benzodiazepinele sunt o opțiune alternativă.','Frica privește evaluarea de către alții.','Anxietatea poate ajunge la atacuri de panică.']],
 [8,'Distractorii contrazic definiția și severitatea.'],['evaluării din partea celorlalţi','opţiune alternativă']),

q('psihiatrie-adv-029',['Fobia specifică:',
 ['apare tipic în copilărie','poate produce reacție vasovagală la confruntare','se tratează prin desensibilizare sistematică','pacientul nu recunoaște caracterul irațional al fricii','se tratează de primă linie cu β-blocante'],'ABC',324,'Fobia specifică',
 'Recunoașterea fobiei specifice.',
 ['Apare tipic în copilărie.','Unii pacienți au leșin vasovagal.','Desensibilizarea prin expuneri repetate.','Pacientul realizează aspectul irațional.','Tratamentul este psihoterapeutic.']],
 [8,'Distractorii contrazic insight-ul și tratamentul.'],['desensibilizare sistematică','vasovagală']),

q('psihiatrie-adv-012',['Tulburarea obsesiv-compulsivă:',
 ['are obsesii percepute ca ego-distonice','are prevalență egală la femei și bărbați','se asociază cu tulburări afective în ~70% din cazuri','debutează în medie în jurul vârstei de 20 de ani','are comportamente percepute ca dezirabile'],'ABCD',324,'Tulburarea obsesiv-compulsivă',
 'Diferențierea TOC de tulburarea de personalitate obsesiv-compulsivă.',
 ['Obsesiile sunt nedorite (ego-distonice).','Prevalența este egală pe sexe.','Tulburările afective sunt comorbide în ~70%.','Vârsta de debut este de 20 de ani.','Descrie TPOC (ego-sintonic).']],
 [8,'Singurul distractor preia trăsătura TPOC.'],['ego-DIStonice','20 de ani']),

q('psihiatrie-adv-018',['Tulburarea dismorfică corporală:',
 ['debutează tipic în adolescență','este mai frecventă la rudele de gradul I ale pacienților cu TOC','impune evitarea operațiilor inutile','dispare de regulă după corectarea chirurgicală','debutează tipic după vârsta de 50 de ani'],'ABC',325,'Tulburarea dismorfică corporală',
 'Recunoașterea tulburării dismorfice corporale.',
 ['Debutul tipic este în adolescență.','Prevalența este mai mare la rudele pacienților cu TOC.','Operațiile inutile trebuie evitate.','Pacientul persistă în a-și imagina defectul.','Debutul tipic este în adolescență.']],
 [8,'Distractorii contrazic evoluția și vârsta.'],['chirurgul plastician','adolescenţă']),

q('psihiatrie-adv-048',['Tratamentul tulburării de acumulare compulsivă, conform textului, este:',
 ['TCC țintită pe acumulare','antipsihoticele atipice în doze mari','desensibilizarea sistematică prin expunere','litiul, ca stabilizator al dispoziției','fototerapia zilnică'],'A',325,'Tulburarea de acumulare',
 'Alegerea tratamentului tulburării de acumulare.',
 ['Terapia cognitiv-comportamentală țintită pe acumulare.','Nu este tratamentul citat.','Tratează fobia specifică.','Nu este tratamentul citat.','Tratează depresia sezonieră.']],
 [8,'Distractorii sunt tratamente ale altor tulburări.'],['acumulare','foarte dificil de tratat']),

q('psihiatrie-adv-031',['Tulburarea de adaptare:',
 ['debutează în primele 3 luni de la eveniment','se remite în 6 luni de la dispariția stresorului','poate asocia dispoziție depresivă sau anxietate','debutează în prima lună și se remite într-o lună','cere un eveniment cu amenințare cu moartea sau viol'],'ABC',325,'Tulburarea de adaptare',
 'Diferențierea tulburării de adaptare de stresul acut și PTSD.',
 ['Debutul este în primele 3 luni.','Remisiunea are loc în 6 luni.','Poate avea dispoziție depresivă, anxietate sau tulburări de conduită.','Descrie tulburarea acută de stres.','Descrie traumele din PTSD.']],
 [8,'Distractorii preiau criteriile stresului acut și PTSD.'],['primele 3 luni','dispoziţie depresivă']),

q('psihiatrie-adv-008',['Tulburarea acută de stres se caracterizează prin:',
 ['debut în prima lună și remisiune într-o lună','debut în primele 3 luni și remisiune în 6 luni','simptome care durează cel puțin 6 luni','debut la peste 6 luni de la eveniment','debut în prima lună și evoluție de peste un an'],'A',325,'Tulburarea acută de stres',
 'Diferențierea tulburării acute de stres.',
 ['Debutează în prima lună și se remite într-o lună.','Descrie tulburarea de adaptare.','Nu este criteriul citat.','Nu este criteriul citat.','Remisiunea are loc într-o lună.']],
 [8,'Distractorii preiau intervalele tulburării de adaptare.'],['Tulburarea acută de stres','se remite într-o lună']),

q('psihiatrie-adv-013',['Tulburarea de stres post-traumatic:',
 ['cere simptome cu durată de cel puțin o lună','poate apărea și la martorii evenimentului','poate beneficia de prazosin pentru coșmaruri','folosește antipsihotice atipice de primă linie','include amnezie pentru aspecte ale evenimentului'],'ABCE',325,'Tulburarea de stres post-traumatic',
 'Recunoașterea criteriilor și tratamentului PTSD.',
 ['Simptomele durează cel puțin o lună.','Evenimentul poate fi trăit ca martor.','Prazosinul ameliorează coșmarurile.','Atipicele sunt pentru simptome refractare la SSRI/SNRI.','Amnezia este un simptom cognitiv citat.']],
 [8,'Singurul distractor devansează antipsihoticele.'],['cel puţin 1 lună','martor'],[326]),

q('psihiatrie-adv-049',['Tulburarea conversivă:',
 ['are de regulă un debut acut','poate produce crize asemănătoare epilepsiei','se remite spontan în 40–50% după educarea pacientului','asociază tipic „la belle indifférence”','produce anxietate marcată față de simptome'],'ABCD',326,'Tulburarea conversivă',
 'Recunoașterea tulburării conversive.',
 ['Debutul este acut.','Crizele asemănătoare epilepsiei sunt citate.','Educarea duce la remisiune în 40–50%.','Pacienții par detașați emoțional.','Anxietatea marcată caracterizează tulburarea cu simptome somatice.']],
 [8,'Singurul distractor preia trăsătura tulburării somatice.'],['belle indifference','40-50%']),

q('psihiatrie-adv-033',['Tulburarea factice se deosebește de simularea premeditată prin faptul că:',
 ['nu există un beneficiu evident pentru pacient','simptomele sunt produse fără intenție conștientă','pacientul urmărește scutirea de muncă sau narcotice','simptomele lipsesc, existând doar teama de boală','predomină la bărbați'],'A',326,'Tulburările factice',
 'Diferențierea tulburării factice de simulare.',
 ['În tulburarea factice nu există beneficiu evident.','Pacientul induce deliberat simptomele.','Descrie simularea premeditată.','Descrie nosofobia.','Simularea este mai frecventă la bărbați.']],
 [8,'Distractorii descriu entitățile învecinate.'],['beneficiu evident','Simularea premeditată']),

q('psihiatrie-adv-009',['Tulburarea cu simptome somatice:',
 ['are o îngrijorare care durează peste 6 luni','determină frecvent consultarea multor medici','răspunde la ADT, SSRI și terapie cognitiv-comportamentală','cere absența unei condiții medicale identificate','impune consultarea mai multor medici specialiști'],'ABC',326,'Tulburarea cu simptome somatice',
 'Recunoașterea tulburării cu simptome somatice.',
 ['Îngrijorarea durează peste 6 luni.','Pacienții practică „doctor-shopping”.','ADT, SSRI și TCC sunt utile.','Simptomele pot sau nu avea o cauză medicală.','Pacientul este îndrumat spre un singur medic de familie.']],
 [8,'Distractorii contrazic definiția și conduita.'],['doctor-shop','medic de familie']),

q('psihiatrie-adv-050',['Preocuparea de a avea o boală gravă, în absența simptomelor somatice semnificative, definește:',
 ['tulburarea nosofobică','tulburarea conversivă','tulburarea cu simptome somatice','tulburarea factice','simularea premeditată'],'A',326,'Tulburarea nosofobică',
 'Diferențierea nosofobiei de tulburările somatice învecinate.',
 ['Definește tulburarea nosofobică.','Conversia produce deficite neurologice.','Aceasta are simptome somatice.','Aceasta implică falsificarea simptomelor.','Aceasta urmărește un beneficiu.']],
 [8,'Distractorii sunt entitățile din aceeași secțiune.'],['nosofobică','boală gravă']),

q('psihiatrie-adv-044',['Tulburările factice (sindromul Münchausen):',
 ['pot implica autoadministrarea de insulină','se tratează dificil din cauza negării','impun limitarea îngrijirilor la un singur medic','au o formă prin transfer, considerată abuz asupra copilului','impun explorări repetate pentru confirmarea bolii'],'ABCD',326,'Tulburările factice',
 'Aplicarea conduitei în tulburările factice.',
 ['Autoadministrarea de insulină este citată.','Negarea face tratamentul dificil.','Îngrijirile se limitează la un singur medic.','Münchausen prin transfer este abuz și se raportează.','Nu se inițiază terapii inutile.']],
 [8,'Singurul distractor contrazice limitarea investigațiilor.'],['insulină','abuz asupra copilului'],[327]),

q('psihiatrie-adv-010',['Anorexia nervosa:',
 ['are greutatea corporală în general sub 85% din cea ideală','asociază amenoree, lanugo și bradicardie','are mortalitate pe 10 ani de 6%','răspunde bine la farmacoterapia de fond','asociază tahicardie și intoleranță la căldură'],'ABC',327,'Anorexia nervosa',
 'Recunoașterea anorexiei nervosa.',
 ['Greutatea este în general <85% din cea ideală.','Amenoree, lanugo, bradicardie.','Mortalitatea pe 10 ani este 6%.','Farmacoterapia nu și-a dovedit utilitatea.','Apar bradicardie și intoleranță la frig.']],
 [8,'Distractorii inversează semnele și eficacitatea medicației.'],['lanugo','6%']),

q('psihiatrie-adv-034',['Sindromul de realimentare:',
 ['asociază hipofosfatemie','asociază hipomagneziemie și hipocalcemie','poate produce rabdomioliză și convulsii','apare prin comutarea de la glucide spre lipide','asociază hiperfosfatemie'],'ABC',327,'Sindromul de realimentare',
 'Recunoașterea sindromului de realimentare.',
 ['Hipofosfatemia este citată.','Hipomagneziemia și hipocalcemia sunt citate.','Rabdomioliza, confuzia și convulsiile sunt complicații.','Comutarea este de la lipide spre glucide.','Fosfatul scade.']],
 [8,'Distractorii inversează direcția metabolică și fosfatul.'],['hipofosfatemie','rabdomioliză']),

q('psihiatrie-adv-035',['Bulimia nervosa:',
 ['are episoade săptămânale timp de peste 3 luni','poate crește amilaza serică prin parotidită','are ca medicație aprobată de FDA fluoxetina','asociază tipic o greutate corporală scăzută sub 85%','se tratează de primă linie cu litiu'],'ABC',327,'Bulimia nervosa',
 'Recunoașterea bulimiei nervosa.',
 ['Episoadele apar săptămânal peste 3 luni.','Inflamația parotidelor poate crește amilaza.','Fluoxetina este medicația aprobată.','Greutatea este în general normală.','Litiul nu este tratamentul citat.']],
 [8,'Distractorii preiau greutatea din anorexie.'],['Fluoxetină','parotide']),

q('psihiatrie-adv-051',['Tulburarea de alimentație compulsivă se deosebește de bulimie prin:',
 ['absența comportamentelor compensatorii','frecvența episoadelor de cel puțin o dată pe lună','durata minimă de 6 luni a episoadelor','răspunsul superior la farmacoterapie','greutatea corporală de regulă scăzută'],'A',327,'Tulburarea de alimentație compulsivă',
 'Diferențierea tulburării de alimentație compulsivă de bulimie.',
 ['Nu există comportamente compensatorii.','Episoadele sunt săptămânale.','Durata este de peste 3 luni.','Psihoterapia este mai eficace.','Pacientele sunt adesea supraponderale.']],
 [8,'Distractorii schimbă frecvența, durata și greutatea.'],['fără comportamente compensatorii','supraponderale sau obeze']),

q('psihiatrie-adv-005',['Tulburările de personalitate:',
 ['apar tipic în adolescența târzie','sunt persistente și inflexibile','sunt dificil de tratat, pacienții nu recunosc nevoia de ajutor','pot fi atribuite consumului de substanțe','se clasifică drept NOS dacă nu întrunesc criteriile definite'],'ABCE',328,'Tulburările de personalitate',
 'Recunoașterea trăsăturilor generale ale tulburărilor de personalitate.',
 ['Apar tipic în adolescența târzie.','Sunt persistente și inflexibile.','Pacienții nu conștientizează nevoia de ajutor.','Nu pot fi atribuite substanțelor.','Tulburările nespecificate sunt NOS.']],
 [8,'Singurul distractor contrazice criteriul de excludere.'],['adolescenţa târzie','inflexibil'],[329]),

q('psihiatrie-adv-014',['Grupul B al tulburărilor de personalitate include tipurile:',
 ['histrionic','narcisist','borderline','antisocial','schizotipal'],'ABCD',329,'Tulburările de personalitate — Grupe',
 'Clasificarea tulburărilor de personalitate.',
 ['Histrionicul este în grupul B.','Narcisistul este în grupul B.','Borderline este în grupul B.','Antisocialul este în grupul B.','Schizotipalul este în grupul A.']],
 [8,'Singurul distractor aparține grupului A.'],['extravagant','histrionic']),

q('psihiatrie-adv-052',['Grupul C al tulburărilor de personalitate include tipurile:',
 ['evitant','dependent','obsesiv-compulsiv','schizoid','histrionic'],'ABC',329,'Tulburările de personalitate — Grupe',
 'Clasificarea tulburărilor de personalitate.',
 ['Evitantul este în grupul C.','Dependentul este în grupul C.','Obsesiv-compulsivul este în grupul C.','Schizoidul este în grupul A.','Histrionicul este în grupul B.']],
 [8,'Distractorii aparțin grupurilor A și B.'],['anxios sau temător','obsesiv-compulsiv']),

q('psihiatrie-adv-019',['Conform Tabelului 14-5, tulburarea de personalitate borderline:',
 ['are frică de abandon și impulsivitate','este mai frecventă la femei','asociază gândire de tip „alb și negru”','cere tulburare de conduită înainte de 15 ani','este mai frecventă la bărbați'],'ABC',328,'Tabelul 14-5',
 'Recunoașterea tulburării borderline.',
 ['Frica de abandon și impulsivitatea sunt citate.','Este mai frecventă la femei.','Gândirea „alb și negru” este citată.','Este criteriul antisocialului.','Antisocialul este mai frecvent la bărbați.']],
 [8,'Distractorii preiau criteriile antisocialului.'],['frică de abandon','alb şi negru']),

q('psihiatrie-adv-015',['Conform Tabelului 14-5, tulburarea de personalitate antisocială:',
 ['cere vârsta de peste 18 ani','cere tulburare de conduită înainte de 15 ani','este mai frecventă la bărbați','asociază lipsa remușcării','asociază frică de abandon marcată'],'ABCD',328,'Tabelul 14-5',
 'Recunoașterea tulburării antisociale.',
 ['Vârsta peste 18 ani este cerută.','Tulburarea de conduită înainte de 15 ani.','Este mai frecventă la bărbați.','Lipsa remușcării este citată.','Frica de abandon caracterizează borderline.']],
 [8,'Singurul distractor preia trăsătura borderline.'],['15 ani','remuşcării']),

q('psihiatrie-adv-036',['Conform Tabelului 14-5:',
 ['personalitatea schizotipală asociază convingeri bizare','personalitatea narcisică asociază invidie față de alții','personalitatea dependentă asociază dificultatea de a lua decizii','personalitatea evitantă asociază minciuna patologică','personalitatea schizoidă asociază comportament seducător'],'ABC',328,'Tabelul 14-5',
 'Asocierea trăsăturilor cu tipul de personalitate.',
 ['Convingerile bizare sunt schizotipale.','Invidia este narcisică.','Dificultatea decizională este dependentă.','Minciuna patologică este antisocială.','Comportamentul seducător este histrionic.']],
 [8,'Distractorii mută trăsături între tipuri.'],['convingeri bizare','invidie faţă de alţii']),

q('psihiatrie-adv-016',['Sevrajul alcoolic:',
 ['poate produce delirium tremens','poate asocia halucinații tactile','are delirium tremens prevenit prin benzodiazepine','se tratează cu flumazenil ca antidot','produce tipic mioză și depresie respiratorie'],'ABC',329,'Tabelul 14-6 — Alcool',
 'Recunoașterea și prevenția sevrajului alcoolic.',
 ['Delirium tremens este citat.','Halucinațiile tactile sunt citate.','Benzodiazepinele previn delirium tremens.','Flumazenilul antagonizează benzodiazepinele.','Descrie intoxicația cu opioizi.']],
 [8,'Distractorii preiau antidoturi și semne din alte intoxicații.'],['tactile','benzodiazepinele previn']),

q('psihiatrie-adv-020',['Chestionarul CAGE evaluează:',
 ['dorința de a reduce consumul','frustrarea față de sugestia altora de a opri','vinovăția legată de consum','consumul dimineața, la trezire','toleranța la doze tot mai mari'],'ABCD',329,'Chestionarul CAGE',
 'Aplicarea chestionarului CAGE.',
 ['Cut down.','Annoyance.','Guilt.','Eye-opener.','Toleranța nu face parte din CAGE.']],
 [8,'Singurul distractor este un criteriu al tulburării de consum.'],['CAGE','Eye']),

q('psihiatrie-adv-021',['Intoxicația cu opioizi se caracterizează prin:',
 ['mioză și depresie respiratorie','midriază și hipertensiune arterială','nistagmus vertical și orizontal','conjunctive injectate și apetit crescut','halucinații și tremurături'],'A',330,'Tabelul 14-6 — Opioizi',
 'Recunoașterea intoxicației cu opioizi.',
 ['Mioză, scăderea vigilității, depresie respiratorie.','Descrie amfetaminele.','Descrie fenciclidina.','Descrie marijuana.','Descrie halucinogenele.']],
 [8,'Distractorii descriu celelalte intoxicații din tabel.'],['mioză','depresie respiratorie']),

q('psihiatrie-adv-037',['Conform Tabelului 14-6:',
 ['naloxona se folosește în supradoza acută de opioizi','fenciclidina produce nistagmus vertical și orizontal','cocaina poate produce moarte subită de cauză cardiacă','sevrajul opioid produce diaree și mialgii','marijuana produce mioză și depresie respiratorie'],'ABCD',330,'Tabelul 14-6',
 'Recunoașterea efectelor și tratamentului substanțelor.',
 ['Naloxona tratează supradoza cu depresie respiratorie.','PCP produce nistagmus vertical și orizontal.','Cocaina poate produce moarte subită cardiacă.','Sevrajul opioid include diaree și mialgii.','Descrie opioizii.']],
 [8,'Singurul distractor atribuie marijuanei efectele opioizilor.'],['nistagmus','naloxona'],[329]),

q('psihiatrie-adv-022',['Etapa în care pacientul admite necesitatea unei schimbări la un moment nespecificat, fără planuri imediate, este:',
 ['contemplarea','precontemplarea','pregătirea','acțiunea','menținerea'],'A',330,'Etapele schimbării',
 'Recunoașterea etapelor schimbării.',
 ['Contemplarea: admiterea necesității, fără planuri.','Precontemplarea: fără conștiința problemei.','Pregătirea: planuri concrete.','Acțiunea: implementarea schimbărilor.','Menținerea: schimbările sunt menținute.']],
 [8,'Distractorii sunt celelalte etape.'],['Contemplarea','Precontemplarea']),
];
