import {rewriter} from './rewrite-author';
import {RETIRED_REUMATOLOGIE} from './retired/reumatologie';

// Rewritten after the 2026-09-24 cue audit (Kumar, cap. 18, p. 437–454 și 457–459).
// The extract has no p. 455–456, so p. 457–459 are PDF 85–87 (p - 372).
const q=rewriter(RETIRED_REUMATOLOGIE,(p:number)=>p<=454?p-370:p-372,{shuffle:true});

export const REUMATOLOGIE_V2=[
q('reumatologie-adv-014',['Cele trei subtipuri principale de afecțiuni articulare inflamatoare sunt:',
 ['artrita reumatoidă','spondilartrita','artrita microcristalină','artroza erozivă a mâinii','polimialgia reumatică'],'ABC',437,'Afecțiuni articulare inflamatorii — Cadranul 18.24',
 'Enumerarea subtipurilor de afecțiuni articulare inflamatoare.',
 ['AR, asociată cu autoanticorpi.','Spondilartrita, asociată cu HLA-B27.','Artrita metabolică sau microcristalină.','Artroza nu este o afecțiune inflamatorie din această clasificare.','Polimialgia este un diagnostic diferențial, nu un subtip.']],
 [8,'Distractorii sunt afecțiuni reumatice reale din afara clasificării.'],['Cadranul 18.24','microcristale']),

q('reumatologie-adv-039',['Diagnosticul afecțiunilor articulare inflamatoare este ajutat de:',
 ['numărul și tipul articulațiilor afectate','prezența unei boli non-articulare','periodicitatea artritei','VSH și PCR de obicei crescute','absența redorii matinale'],'ABCD',437,'Afecțiuni articulare inflamatorii — Evaluare',
 'Identificarea elementelor care orientează diagnosticul artritei inflamatoare.',
 ['Numărul și tipul articulațiilor (simetric/asimetric, mici/mari) ajută diagnosticul.','Boala non-articulară orientează diagnosticul.','Periodicitatea (unică acută, recurentă, cronică progresivă) este un criteriu.','VSH și PCR sunt de obicei crescute în afecțiunile inflamatoare.','Redoarea matinală prelungită este caracteristică inflamației.']],
 [8,'Distractorii descriu artroza, nu artrita inflamatorie.'],['periodicităţii','simet']),

q('reumatologie-adv-040',['Orientează diagnosticul spre spondilartrită:',
 ['psoriazisul cutanat','iridociclita','uretrita nespecifică','nodulii reumatoizi','sinovita MCF'],'ABC',437,'Afecțiuni articulare inflamatorii — Boli non-articulare asociate',
 'Recunoașterea indiciilor non-articulare de spondilartrită.',
 ['Psoriazisul sugerează spondilartrită.','Iridociclita sugerează spondilartrită.','Uretrita nespecifică și dizenteria recentă sugerează spondilartrită.','Nodulii reumatoizi caracterizează AR seropozitivă.','Afectarea simetrică a MCF este tipică AR.']],
 [8,'Distractorii sunt semne caracteristice AR.'],['iridociclita','uretrita nespecifică']),

q('reumatologie-adv-064',['Epidemiologia artritei reumatoide:',
 ['afectează 0,5–1% din populație','are o preponderență feminină de 3:1','debutează cel mai frecvent între 60 și 80 de ani','are prevalență crescută la chinezi','are o preponderență masculină de 3:1'],'AB',437,'Artrita reumatoidă — Epidemiologie',
 'Fixarea datelor epidemiologice ale AR.',
 ['AR afectează 0,5–1% din populație.','Raportul femei:bărbați este 3:1.','Nu: vârsta cea mai frecventă de debut este 30–50 de ani.','Prevalența este scăzută la negrii din Africa și la chinezi.','Preponderența este feminină.']],
 [8,'Distractorii inversează sexul și grupurile cu prevalență scăzută.'],['0,5-1%','30 şi 50 de ani']),

q('reumatologie-adv-065',['Factorii genetici în artrita reumatoidă:',
 ['concordanța la gemenii monozigoți ajunge la 15%','HLA-DR4 este prezent la 50–75% dintre pacienți','HLA-DR4 se corelează cu un prognostic bun','HLA-B27 este prezent la 95% dintre pacienți','concordanța la gemenii monozigoți ajunge la 70%'],'AB',437,'Artrita reumatoidă — Factori genetici',
 'Recunoașterea asocierilor genetice ale AR.',
 ['Concordanța la gemenii monozigoți este de până la 15%.','HLA-DR4 apare la 50–75% dintre pacienți.','Nu: HLA-DR4 se corelează cu un prognostic slab.','HLA-B27 este asociat cu spondilartrita.','70% este concordanța din spondilita anchilozantă.']],
 [8,'Distractorii preiau datele genetice ale spondilitei anchilozante.'],['HLA-DR4','15%']),

q('reumatologie-adv-066',['Factorii de mediu care predispun la AR ACPA-pozitivă includ:',
 ['fumatul, sinergic cu HLA-DRB1','boala parodontală','modificările microbiomului intestinal','consumul moderat de alcool','expunerea la radiații ultraviolete'],'ABC',437,'Artrita reumatoidă — Factori de mediu',
 'Identificarea factorilor de mediu asociați AR ACPA-pozitive.',
 ['Fumatul acționează sinergic cu HLA-DRB1 pentru a crește riscul de ACPA.','Boala parodontală este asociată cu apariția AR.','Modificările microbiomului intestinal pot facilita imunitatea predispozantă.','Nu este citat ca factor de mediu.','Razele UV sunt factor declanșator în LES.']],
 [8,'Distractorii sunt factori de mediu ai altor boli autoimune.'],['stres bronşic','parodontale'],[438]),

q('reumatologie-adv-016',['Autoanticorpii din artrita reumatoidă:',
 ['FR sunt prezenți la 75–80% dintre pacienți','FR țintesc porțiunea Fc a IgG','ACPA sunt mai puțin specifici decât FR','FR au valoare predictivă mare în populația generală','FR țintesc porțiunea Fab a IgG'],'AB',438,'Artrita reumatoidă — Autoanticorpi',
 'Recunoașterea caracteristicilor FR și ACPA.',
 ['FR se găsesc la 75–80% dintre pacienții cu AR.','FR țintesc porțiunea Fc a IgG.','Nu: ACPA sunt mai specifici și mai sensibili decât FR.','FR au valoare predictivă mică în populația generală.','Ținta este porțiunea Fc.']],
 [8,'Distractorii inversează ținta și valoarea predictivă a FR.'],['porţiunea Fc','75-80%']),

q('reumatologie-adv-041',['În imunopatogenia artritei reumatoide:',
 ['TNF-α este produs în exces de macrofage','TNF-α stimulează sinteza de IL-6','osteoblastele distrug osul și cartilajul','TNF-α inhibă sinteza de IL-6 sinovial','limfocitele Th17 sunt suprimate de TGF-β'],'AB',438,'Artrita reumatoidă — Imunologie',
 'Recunoașterea mecanismelor imune ale sinovitei reumatoide.',
 ['Excesul de TNF-α rezultă din interacțiunea macrofagelor cu limfocitele T și B.','TNF-α stimulează sinteza în exces de IL-6.','Nu: osteoclastele cauzează distrugerea osului și cartilajului.','TNF-α stimulează IL-6.','TGF-β suprimă limfocitele T reglatoare, permițând dezvoltarea Th17.']],
 [8,'Distractorii inversează relațiile de reglare citokinică.'],['TNF-a','Osteoclastele'],[439]),

q('reumatologie-adv-001',['Fibroblastele sinoviale din AR exprimă:',
 ['VCAM-1, care susține supraviețuirea limfocitelor B','DAF, care previne liza indusă de complement','caderina 11, care mediază interacțiunile intercelulare','DAF, care susține diferențierea limfocitelor B','VCAM-1, care previne liza indusă de complement'],'ABC',438,'Artrita reumatoidă — Fibroblastele sinoviale',
 'Asocierea moleculelor fibroblastelor sinoviale cu rolul lor.',
 ['VCAM-1 susține supraviețuirea și diferențierea limfocitelor B.','DAF previne liza celulară indusă de complement.','Caderina 11 mediază interacțiunile intercelulare.','Acesta este rolul VCAM-1.','Acesta este rolul DAF.']],
 [8,'Funcțiile celor trei molecule sunt permutate.'],['VCAM-1','caderina']),

q('reumatologie-adv-017',['Pannusul sinovial în artrita reumatoidă:',
 ['se extinde de la marginile articulare pe cartilaj','blochează nutriția cartilajului','produce leziuni vizibile IRM în primele 3–6 luni','apare pe radiografie înaintea modificărilor IRM','protejează cartilajul subiacent'],'ABC',439,'Artrita reumatoidă — Patologie',
 'Recunoașterea mecanismului și a cronologiei leziunilor din AR.',
 ['Sinovita hiperplazică se răspândește de la marginile articulare pe cartilaj.','Pannusul blochează calea normală de nutriție a cartilajului.','IRM arată procesul în primele 3–6 luni, înaintea radiografiei.','Eroziunile radiografice apar după modificările IRM.','Pannusul afectează cartilajul.']],
 [8,'Distractorii inversează cronologia imagistică și efectul pannusului.'],['pannus','3-6 luni']),

q('reumatologie-adv-042',['Factorii reumatoizi de tip IgM și ACPA:',
 ['FR IgM sunt detectați de cele mai frecvente teste clinice','absența FR IgM nu exclude AR','ACPA prezic mai bine persistența sinovitei','FR IgM sunt diagnostici pentru AR','ACPA sunt mai slabi predictori decât FR'],'ABC',439,'Factorii reumatoizi și ACPA',
 'Interpretarea FR IgM și ACPA în AR.',
 ['Cele mai frecvente teste clinice detectează FR IgM.','FR IgM nu sunt diagnostici, iar absența lor nu exclude boala.','ACPA sunt predictori mai puternici ai tranziției spre sinovită persistentă.','FR IgM nu sunt diagnostici.','ACPA sunt predictori mai puternici.']],
 [8,'Distractorii supraestimează FR și subestimează ACPA.'],['seronegativă','ACPA sunt factori predictivi']),

q('reumatologie-adv-019',['Tabloul clinic tipic al artritei reumatoide:',
 ['poliartrită periferică simetrică, progresivă','debut între 30 și 50 de ani','interesare a MCF, IFP și MTF','interesare predominantă a IFD','afectare asimetrică a articulațiilor mari'],'ABC',440,'Artrita reumatoidă — Afectarea tipică',
 'Recunoașterea prezentării tipice a AR.',
 ['AR se prezintă de obicei ca poliartrită periferică simetrică, progresivă.','Debutul tipic este între 30 și 50 de ani.','Sunt afectate MCF, IFP și MTF.','IFD sunt de obicei cruțate.','Afectarea asimetrică a articulațiilor mari este tipică spondilartritei.']],
 [8,'Distractorii descriu artroza nodulară și spondilartrita.'],['cruţate','simetrică']),

q('reumatologie-adv-044',['Conform Cadranului 18.26, prezic un prognostic negativ în AR precoce:',
 ['vârsta înaintată la debut','sexul feminin al pacientului','redoarea matinală sub 10 minute','sexul masculin','afectarea asimetrică a genunchilor'],'AB',440,'Cadranul 18.26 — Factori de prognostic negativ',
 'Identificarea factorilor de prognostic negativ din AR precoce.',
 ['Vârsta înaintată este factor negativ.','Sexul feminin este factor negativ.','Nu: redoarea matinală peste 30 de minute este factor negativ.','Sexul feminin, nu masculin, este citat.','Afectarea simetrică a articulațiilor mici este citată.']],
 [8,'Distractorii inversează sexul și tipul afectării.'],['Redoarea matinală >30','Fumat']),

q('reumatologie-adv-067',['Conform Cadranului 18.27, diagnosticul diferențial al AR precoce include:',
 ['artrita postvirală cu eritrovirus','spondilartrita','polimialgia reumatică','guta tofacee a MTF1','artrita septică gonococică'],'ABC',440,'Cadranul 18.27 — Diagnosticul diferențial al AR precoce',
 'Enumerarea diagnosticelor diferențiale ale AR precoce.',
 ['Artritele postvirale (rubeolă, hepatită B, eritrovirus) sunt citate.','Spondilartrita este citată.','Polimialgia reumatică este citată.','Nu figurează în cadran.','Nu figurează în cadran.']],
 [8,'Distractorii sunt artrite reale, absente din cadran.'],['eritrovirus','Polimialgia']),

q('reumatologie-adv-018',['Conform criteriilor ACR/EULAR 2010, un pacient se clasifică drept AR la un scor de:',
 ['cel puțin 4 puncte','cel puțin 5 puncte','cel puțin 6 puncte','cel puțin 7 puncte','cel puțin 10 puncte'],'C',440,'Cadranul 18.28 — Criteriile ACR/EULAR 2010',
 'Fixarea pragului de clasificare ACR/EULAR 2010.',
 ['Nu este pragul citat.','Nu este pragul citat.','Clasificarea drept AR se face la ≥6 puncte.','Nu este pragul citat.','10 puncte este scorul maxim.']],
 [8,'Distractorii sunt praguri numerice apropiate.'],['6 puncte','ACR/EULAR 2010']),

q('reumatologie-adv-045',['În criteriile ACR/EULAR 2010, primesc un punct:',
 ['2–10 articulații medii sau mari','reactanții de fază acută normali','durata simptomelor de cel puțin 6 săptămâni','o singură articulație medie sau mare','FR sau ACPA pozitivi în titru mare'],'AC',440,'Cadranul 18.28 — Punctaje',
 'Aplicarea punctajelor pe domenii ale criteriilor ACR/EULAR 2010.',
 ['2–10 articulații medii/mari valorează 1 punct.','Nu: reactanții de fază acută normali valorează 0 puncte.','Durata ≥6 săptămâni valorează 1 punct.','O articulație medie/mare valorează 0 puncte.','Serologia în titru mare valorează 3 puncte.']],
 [8,'Distractorii sunt valori ale altor trepte din același cadran.'],['2-10 articulaţii','Reactanţi în fază acută']),

q('reumatologie-adv-043',['În AR precoce, cel mai bun mod de a selecta pacienții pentru tratament precoce combină:',
 ['cel puțin o articulație tumefiată peste 6 săptămâni','un test ACPA pozitiv','absența antecedentelor de spondilartrită sau psoriazis','prezența eroziunilor radiografice','prezența manifestărilor extra-articulare'],'ABC',440,'Artrita reumatoidă — Selecția pentru tratament precoce',
 'Recunoașterea criteriilor de selecție pentru tratamentul precoce.',
 ['O articulație tumefiată peste 6 săptămâni este un element.','Testul ACPA pozitiv este un element.','Absența antecedentelor de spondilartrită sau psoriazis este un element.','Eroziunile sunt modificări tardive.','Manifestările extra-articulare sunt tardive.']],
 [8,'Distractorii sunt modificări tardive, evitate de criteriile noi.'],['ACPA pozitiv','6 săptămâni']),

q('reumatologie-adv-046',['La vârstnic, artrita reumatoidă poate imita:',
 ['polimialgia reumatică','artroza nodulară','spondilartrita axială','guta tofacee','artrita septică'],'A',440,'Artrita reumatoidă — Pacientul vârstnic',
 'Recunoașterea prezentării AR la vârstnic.',
 ['AR a vârstnicului poate imita polimialgia; sinovita devine evidentă la reducerea glucocorticoizilor.','Nu este imitația citată.','Nu este imitația citată.','Nu este imitația citată.','Nu este imitația citată.']],
 [8,'Distractorii sunt diagnostice reumatologice ale vârstnicului.'],['polimialgia reumatică','glucocorticoizi']),

q('reumatologie-adv-047',['Reumatismul palindromic:',
 ['are episoade de monoartrită de 24–48 de ore','are remisiune completă între atacuri','evoluează spre AR cronică la aproximativ 5%','are sinovită persistentă între atacuri','are episoade care durează 6–12 luni'],'AB',441,'Alte tipuri de prezentare — Reumatismul palindromic',
 'Recunoașterea evoluției reumatismului palindromic.',
 ['Episoadele de monoartrită acută durează 24–48 de ore.','Articulația se remite complet.','Nu: aproximativ 50% dezvoltă sinovită reumatoidă cronică.','Remisiunea este completă între atacuri.','Atacurile durează 24–48 de ore.']],
 [8,'Distractorii confundă forma palindromică cu cea cronică.'],['24-48','50%']),

q('reumatologie-adv-068',['Artrita reumatoidă seronegativă:',
 ['afectează inițial degetele mai des decât carpul','are un model mai puțin simetric','are un prognostic mai bun pe termen lung','are un prognostic mai prost pe termen lung','afectează inițial mai ales IFD'],'BC',441,'Alte tipuri de prezentare — AR seronegativă',
 'Recunoașterea particularităților AR seronegative.',
 ['Nu: AR seronegativă afectează inițial carpul mai des.','Are un model de afectare mai puțin simetric.','Are un prognostic mai bun pe termen lung.','Prognosticul este mai bun.','IFD sunt tipice artritei psoriazice.']],
 [8,'Distractorii inversează prognosticul.'],['carpul','mai puţin simetric']),

q('reumatologie-adv-048',['Complicațiile artritei reumatoide necontrolate includ:',
 ['artrita septică pe articulația reumatoidă','amiloidoza secundară de tip AA','semne accentuate de artrită septică la imunodeprimați','amiloidoza AL, drept complicație tipică','neutropenia febrilă ca manifestare obișnuită'],'AB',441,'Artrita reumatoidă — Complicații',
 'Recunoașterea complicațiilor AR necontrolate.',
 ['Artrita septică are morbiditate și mortalitate semnificativă.','AR este cea mai frecventă cauză de amiloidoză AA secundară.','Nu: la imunodeprimați, semnele tipice de inflamație pot lipsi.','Amiloidoza AL produce o poliartrită care imită AR.','Nu este complicația citată.']],
 [8,'Distractorii confundă tipurile de amiloidoză.'],['amiloidozei de tip AA','imunodeprimaţi']),

q('reumatologie-adv-020',['Deformările mâinii în AR constituită includ:',
 ['devierea ulnară a MCF','subluxația palmară a MCF','deformarea în butonieră a IFP','devierea radială a MCF','subluxația dorsală a MCF'],'ABC',441,'Afectarea articulară — Mâinile',
 'Recunoașterea deformărilor mâinii reumatoide.',
 ['Devierea ulnară a MCF este caracteristică.','Subluxația palmară a MCF însoțește devierea ulnară.','Flexia fixă a IFP este deformarea în butonieră.','Devierea este ulnară.','Subluxația este palmară.']],
 [8,'Distractorii inversează direcția deformărilor.'],['deviere ulnară','butonieră']),

q('reumatologie-adv-003',['Subluxația dorsală a stiloidei ulnare în AR poate produce:',
 ['ruptura tendoanelor extensorilor degetelor','incapacitatea folosirii degetelor 4 și 5','durere în carp','ruptura tendoanelor flexorilor degetelor','sindrom de tunel carpian prin compresie'],'ABC',441,'Afectarea articulară — Carpul',
 'Recunoașterea consecinței subluxației dorsale a stiloidei ulnare.',
 ['Poate provoca ruptura tendoanelor extensorilor.','Rezultă incapacitatea folosirii degetelor 4 și 5.','Subluxația provoacă dureri în carp.','Tendoanele rupte sunt extensorii.','Tunelul carpian este produs de tenosinovita flexorilor.']],
 [8,'Distractorii confundă extensorii cu flexorii.'],['stiloidei ulnare','degetelor 4 şi 5']),

q('reumatologie-adv-049',['Inițial, afectarea umărului în AR imită:',
 ['tendinoza calotei rotatorilor','capsulita adezivă','instabilitatea gleno-humerală','artrita acromio-claviculară','bursita subdeltoidiană septică'],'A',441,'Afectarea articulară — Umerii',
 'Recunoașterea prezentării inițiale a umărului reumatoid.',
 ['Simptomele inițiale imită tendinoza calotei rotatorilor, cu arc dureros.','Nu este imitația citată.','Nu este imitația citată.','Nu este imitația citată.','Nu este imitația citată.']],
 [8,'Distractorii sunt afecțiuni reale ale umărului.'],['calo','arc dureros']),

q('reumatologie-adv-069',['Afectarea coatelor și a altor articulații în AR:',
 ['sinovita cotului produce flexie fixă','pierderea extensiei cotului îngreunează hrănirea','articulația crico-aritenoidă este cruțată','cotul rămâne cruțat până în stadiul terminal','articulația temporo-mandibulară nu este afectată'],'AB',441,'Afectarea articulară — Coatele și alte articulații',
 'Recunoașterea afectării cotului și a articulațiilor atipice în AR.',
 ['Sinovita coatelor produce deformare în flexie fixă.','Pierderea extensiei îngreunează hrănirea.','Nu: articulația crico-aritenoidă poate fi afectată.','Cotul este afectat frecvent.','Articulația temporo-mandibulară poate fi afectată.']],
 [8,'Distractorii exclud articulații citate explicit.'],['flexie fixă','crico-aritenoidă'],[442]),

q('reumatologie-adv-021',['Afectarea picioarelor în AR include:',
 ['tumefierea dureroasă precoce a MTF','degetele în ciocan ale piciorului','glezna deformată frecvent în valg','glezna deformată frecvent în varus','cruțarea MTF până în stadiul tardiv'],'ABC',441,'Afectarea articulară — Picioarele',
 'Recunoașterea afectării piciorului reumatoid.',
 ['Tumefierea dureroasă a MTF este una dintre primele manifestări.','Piciorul se lățește, cu degete în ciocan.','Glezna se deformează frecvent în valg.','Deformarea tipică este în valg.','MTF sunt afectate precoce.']],
 [8,'Distractorii inversează direcția deformării gleznei și cronologia.'],['MTF','valg'],[442]),

q('reumatologie-adv-050',['Afectarea genunchilor și a șoldurilor în AR:',
 ['revărsatul genunchiului răspunde la aspirație și glucocorticoizi','lichidul persistent crește riscul de chist popliteal','osteoscleroza juxta-articulară previne protrusio acetabulae','șoldul este afectat mai frecvent decât genunchiul','chistul popliteal nu are legătură cu revărsatul genunchiului'],'AB',442,'Afectarea articulară — Genunchii și șoldurile',
 'Recunoașterea afectării genunchilor și șoldurilor în AR.',
 ['Revărsatul genunchiului răspunde bine la aspirație și glucocorticoizi.','Lichidul persistent crește riscul de chist popliteal și ruptură.','Nu: osteoporoza juxta-articulară poate permite protrusio acetabulae.','Șoldurile sunt afectate mai rar decât genunchii.','Chistul popliteal este legat de acumularea de lichid sinovial.']],
 [8,'Distractorii inversează frecvența relativă a afectării.'],['chistului popliteal','protrusio acetabulae']),

q('reumatologie-adv-022',['Afectarea coloanei cervicale în AR:',
 ['sinovita C1–C2 produce instabilitate atlanto-axială','CT-ul, nu IRM, este imagistica de primă intenție','slăbiciunea picioarelor poate fi urgență neurochirurgicală','radiografia simplă exclude instabilitatea','afectează tipic coloana cervicală inferioară, C5–C7'],'AC',442,'Afectarea articulară — Coloana cervicală',
 'Recunoașterea instabilității atlanto-axiale și a conduitei.',
 ['Sinovita C1–C2 și a burselor odontoidului produce instabilitate atlanto-axială.','Nu: IRM este imagistica de primă intenție.','Mersul dificil, slăbiciunea picioarelor sau pierderea controlului sfincterian sunt urgențe neurochirurgicale.','Radiografiile în flexie și extensie obiectivează instabilitatea.','Afectarea este a coloanei cervicale superioare.']],
 [8,'Distractorii schimbă nivelul și investigația.'],['atlanto-axială','urgenţă neurochirurgicală']),

q('reumatologie-adv-051',['Manifestările non-articulare ale AR includ:',
 ['nodulii reumatoizi la punctele de presiune','degetul în resort prin tenosinovita flexorilor','sclerita în boala severă seropozitivă','nodulii reumatoizi în boala seronegativă non-erozivă','nodulii care recidivează după excizie'],'ABCE',442,'Manifestări non-articulare',
 'Recunoașterea manifestărilor de țesut moale și oculare din AR.',
 ['Nodulii apar la punctele de presiune: coate, degete, Ahile.','Tenosinovita flexorilor poate produce deget în resort.','Sclerita și episclerita apar în boala severă seropozitivă.','Nodulii apar în boala erozivă seropozitivă.','Nodulii tind să se formeze din nou după excizie.']],
 [8,'Distractorii inversează terenul serologic al nodulilor.'],['Nodulii reumatoizi','deget în resort'],[443]),

q('reumatologie-adv-070',['Afectarea pulmonară din AR include:',
 ['bronșiolita obliterantă și bronșiectazia','fibroza pulmonară bazală, interstițială','noduli cu pneumoconioză (Felty)','fibroza pulmonară apicală','tuberculoza prevenită de DMARD biologice'],'AB',443,'Manifestări non-articulare — Plămânii',
 'Recunoașterea formelor de afectare pulmonară din AR.',
 ['Afectarea căilor aeriene variază de la bronșiectazie la bronșiolită obliterantă.','Boala interstițială produce fibroză pulmonară bazală.','Nu: nodulii cu pneumoconioză definesc sindromul Caplan.','Fibroza descrisă este bazală.','Tuberculoza poate apărea la pacienții cu DMARD biologice.']],
 [8,'Distractorii schimbă sediul fibrozei și inversează riscul infecțios.'],['bronşiolită obliterantă','Caplan']),

q('reumatologie-adv-005',['Manifestările extra-articulare ale AR și mecanismele lor:',
 ['mononevrita multiplex, prin vasculita vasa nervorum','sindromul de tunel carpian, prin sinovită','sindromul Felty, cu splenomegalie și neutropenie','sindromul Felty, cu splenomegalie și trombocitoză','compresia medulară, prin subluxație atlanto-axială'],'ABCE',443,'Manifestări non-articulare — Sistemul nervos și splina',
 'Asocierea manifestărilor extra-articulare cu mecanismul lor.',
 ['Mononevrita multiplex se datorează vasculitei vasa nervorum.','Tunelul carpian este o neuropatie de compresie prin sinovită.','Sindromul Felty asociază splenomegalie și neutropenie.','Felty asociază neutropenie.','Subluxația atlanto-axială produce compresie medulară.']],
 [8,'Distractorii asociază manifestări reale cu mecanisme greșite.'],['vasa nervorum','Felty']),

q('reumatologie-adv-023',['Afectarea cardiovasculară în AR:',
 ['AR slab controlată este factor de risc cardiovascular independent','pericardita este rareori simptomatică','boala miocardică se evidențiază postmortem la ~20%','pericardita este frecvent simptomatică','riscul cardiovascular scade prin controlul bolii'],'ABCE',443,'Manifestări non-articulare — Cordul',
 'Recunoașterea afectării cardiovasculare din AR.',
 ['AR slab controlată, cu PCR crescut, este factor de risc independent.','Pericardita este rareori simptomatică.','Endocardita și boala miocardică apar postmortem la ~20%.','Pericardita este rareori simptomatică.','Controlul bolii reduce riscul cardiovascular.']],
 [8,'Distractorii inversează frecvența simptomelor și rolul controlului bolii.'],['factor de risc cardiovascular','20%']),

q('reumatologie-adv-071',['Modificările hematologice din AR:',
 ['anemia este de obicei normocromă, normocitară','trombocitoza apare în boala activă','pancitopenia poate apărea în sindromul Caplan','anemia este de obicei macrocitară','trombocitopenia este regula în boala activă'],'AB',443,'Manifestări non-articulare — Sângele',
 'Recunoașterea modificărilor hematologice din AR.',
 ['Anemia este de obicei normocromă, normocitară.','Trombocitoza apare în boala activă.','Nu: pancitopenia provine din hipersplenismul sindromului Felty sau din DMARD.','Anemia este normocitară.','Trombocitoza, nu trombocitopenia, apare în boala activă.']],
 [8,'Distractorii inversează direcția modificărilor.'],['normocromă','Trombocitoza']),

q('reumatologie-adv-052',['Pacientul cu artrită persistentă trebuie trimis urgent la reumatolog dacă:',
 ['sunt afectate articulațiile mici ale mâinilor','este afectată mai mult de o articulație','au trecut peste 3 luni de la debut','există eroziuni radiografice deja constituite','articulația afectată este una mare'],'ABC',443,'Artrita reumatoidă — Trimiterea la reumatolog',
 'Aplicarea criteriilor de trimitere urgentă la reumatolog.',
 ['Afectarea articulațiilor mici ale mâinilor sau picioarelor justifică trimiterea.','Afectarea a mai mult de o articulație justifică trimiterea.','O întârziere de peste 3 luni justifică trimiterea.','Eroziunile nu sunt un criteriu de trimitere.','Criteriul privește articulațiile mici.']],
 [8,'Distractorii condiționează trimiterea de modificări tardive.'],['trimis urgent','3 luni']),

q('reumatologie-adv-072',['În investigarea artritei reumatoide:',
 ['ACPA pot preceda boala cu mulți ani','FR sunt prezenți în 75–80% din cazuri','ANA în titru scăzut apar la aproximativ 30%','ANA în titru înalt apar la 90%','ANA în titru înalt apar la aproximativ 90%'],'ABC',443,'Diagnostic și investigații',
 'Interpretarea serologiei în AR.',
 ['ACPA pot fi prezenți precoce și pot preceda boala cu mulți ani.','FR sunt prezenți în 75–80% din cazuri.','ANA în titru scăzut apar în 30% din cazuri.','Titrul este scăzut, la 30%.','ACPA pot preceda boala.']],
 [8,'Distractorii inversează cronologia ACPA și titrul ANA.'],['anti-nucleari','75-80%']),

q('reumatologie-adv-024',['Scorul DAS28 indică:',
 ['activitate înaltă peste 5,1','activitate scăzută sub 3,2','remisiune sub 2,6','remisiune sub 3,2','activitate înaltă peste 3,2'],'ABC',444,'Terapia medicamentoasă — DAS28',
 'Interpretarea pragurilor DAS28.',
 ['DAS28 >5,1 implică activitate înaltă.','DAS28 <3,2 implică activitate scăzută.','DAS28 <2,6 implică remisiune.','Remisiunea este sub 2,6.','Activitatea înaltă este peste 5,1.']],
 [8,'Pragurile sunt permutate între categorii.'],['5,1','2,6']),

q('reumatologie-adv-053',['În managementul simptomatic al AR:',
 ['30% dintre pacienți își pierd locul de muncă în 2 ani','majoritatea necesită un AINS pentru durerea nocturnă','peste 65 de ani se evită inhibitorii de pompă de protoni','AINS înlocuiesc DMARD la pacienții tineri','sub 2% își pierd locul de muncă în 10 ani'],'AB',444,'Tratament — Măsuri generale și AINS',
 'Aplicarea managementului simptomatic și social al AR.',
 ['30% își pierd locul de muncă în 2 ani de la diagnostic.','Majoritatea necesită AINS pentru durerea nocturnă și redoarea matinală, pe lângă DMARD.','Nu: peste 65 de ani sau cu efecte digestive se adaugă un IPP.','AINS se dau pe lângă DMARD, nu în locul lor.','Proporția citată este 30% în 2 ani.']],
 [8,'Distractorii subestimează impactul social și rolul DMARD.'],['30%','peste 65 de ani']),

q('reumatologie-adv-025',['Strategia treat-to-target în AR nou diagnosticată:',
 ['începe cu csDMARD și glucocorticoizi pe termen scurt','trece la bDMARD dacă ținta nu este atinsă','poate folosi inhibitori JAK, similari ca efect cu bDMARD','începe cu bDMARD ca primă linie, la toți pacienții','evită glucocorticoizii pe termen lung'],'ABCE',444,'Terapia medicamentoasă — Treat to target',
 'Aplicarea strategiei treat-to-target în AR.',
 ['Tratamentul începe cu csDMARD și glucocorticoizi cu doză/durată limitată.','bDMARD se prescriu dacă csDMARD nu ating ținta.','tsDMARD au biodisponibilitate orală și eficacitate similară bDMARD.','bDMARD urmează csDMARD.','Glucocorticoizii pe termen lung sunt de evitat.']],
 [8,'Distractorii inversează ordinea claselor terapeutice.'],['csDMARD','JAK']),

q('reumatologie-adv-054',['Glucocorticoizii în AR:',
 ['injecțiile i.m. de depozit ajută la inducerea remisiunii','osteoporoza poate apărea în 3 luni la doze peste 7,5 mg/zi','vitamina D și bifosfonații se evită la tratament peste 3 luni','sunt de preferat ca monoterapie orală pe termen lung','produc osteoporoză doar după mai mulți ani'],'AB',444,'Glucocorticoizi',
 'Aplicarea utilizării și profilaxiei glucocorticoizilor în AR.',
 ['Metilprednisolonul depot ajută la inducerea remisiunii până acționează csDMARD.','Osteoporoza se poate dezvolta în 3 luni la doze peste 7,5 mg/zi.','Nu: vitamina D și bifosfonații se asociază la tratament peste 3 luni.','Glucocorticoizii orali pe termen lung sunt de evitat.','Osteoporoza poate apărea în 3 luni.']],
 [8,'Distractorii subestimează riscul osos și promovează monoterapia.'],['40-120 mg','7,5 mg'],[445]),

q('reumatologie-adv-073',['DMARD sintetice convenționale (csDMARD):',
 ['au efect evident abia după 2–3 luni','aduc în monoterapie o îmbunătățire de 20–50%','pot fi combinate până la patru medicamente','au efect clinic complet în primele 24–48 de ore','nu pot fi combinate, din cauza toxicității'],'ABC',445,'Medicamente antireumatice modificatoare de boală',
 'Recunoașterea cineticii și a combinațiilor de csDMARD.',
 ['Efectul benefic necesită 2–3 luni.','Ca monoterapie, csDMARD obțin o îmbunătățire de 20–50%.','Se pot combina până la patru medicamente.','Efectul nu este imediat.','Combinațiile sunt uzuale.']],
 [8,'Distractorii contrazic cinetica lentă și combinațiile uzuale.'],['2-3 luni','patru medicamente']),

q('reumatologie-adv-026',['Metotrexatul în AR:',
 ['se începe cu 7,5–10 mg pe săptămână','se asociază cu acid folic','nu se folosește în sarcină','se crește apoi la 15–25 mg pe săptămână','este preferat la femeile gravide'],'ABCD',445,'Metotrexat',
 'Aplicarea schemei și a precauțiilor metotrexatului.',
 ['Doza săptămânală inițială de 7,5–10 mg crește la 15–25 mg.','Acidul folic oral reduce efectele secundare.','Metotrexatul nu trebuie utilizat în sarcină.','Doza săptămânală inițială crește la 15–25 mg.','Este contraindicat în sarcină.']],
 [8,'Distractorii schimbă ritmul de administrare și siguranța în sarcină.'],['7,5-10 mg','Acidul folie']),

q('reumatologie-adv-027',['Sulfasalazina și hidroxiclorochina în AR:',
 ['sulfasalazina poate fi folosită în sarcină','sulfasalazina are răspuns la ~90% în 3–6 săptămâni','hidroxiclorochina impune control oftalmologic anual','sulfasalazina este contraindicată în sarcină','hidroxiclorochina nu necesită control oftalmologic'],'AC',445,'Sulfasalazină și hidroxiclorochină',
 'Recunoașterea particularităților sulfasalazinei și hidroxiclorochinei.',
 ['Sulfasalazina poate fi utilizată în sarcină.','Nu: aproximativ 50% răspund în 3–6 luni.','Hidroxiclorochina impune examinare oftalmologică în primul an, apoi anual.','Sulfasalazina poate fi folosită în sarcină.','Riscul de retinopatie impune control oftalmologic.']],
 [8,'Distractorii inversează siguranța în sarcină și monitorizarea retiniană.'],['Sulfasalazina','retinopatie']),

q('reumatologie-adv-055',['Leflunomida:',
 ['blochează dihidro-orotat-dehidrogenaza','are un timp de înjumătățire lung, de 4–28 de zile','se preferă la femeile care planifică o sarcină','are un timp de înjumătățire scurt, de ore','nu necesită monitorizare de laborator'],'AB',445,'Leflunomidă',
 'Recunoașterea mecanismului și a precauțiilor leflunomidei.',
 ['Blochează dihidro-orotat-dehidrogenaza, oprind expansiunea clonală T.','Timpul de înjumătățire este de 4–28 de zile.','Nu: timpul de înjumătățire lung impune evitarea la femeile care planifică sarcina.','Timpul de înjumătățire este lung.','Monitorizarea de laborator este necesară.']],
 [8,'Distractorii inversează farmacocinetica.'],['dihidro-orotat','4-28 de zile']),

q('reumatologie-adv-028',['Blocanții TNF-α în AR:',
 ['se folosesc după eșecul a cel puțin două csDMARD','se asociază de obicei cu metotrexat','nu se folosesc în insuficiența cardiacă severă','se folosesc ca primă linie, înaintea csDMARD','sunt indicați preferențial în insuficiența cardiacă'],'ABC',445,'Blocanții TNF-α',
 'Aplicarea indicațiilor și contraindicațiilor anti-TNF.',
 ['Se folosesc după eșecul a cel puțin două csDMARD.','Se asociază de obicei cu metotrexat.','Nu trebuie folosiți în insuficiența cardiacă severă.','Urmează după csDMARD.','Insuficiența cardiacă severă este contraindicație.']],
 [8,'Distractorii inversează locul în terapie și contraindicația.'],['două csDMARD','insuficienţă cardiacă severă'],[447]),

q('reumatologie-adv-056',['Structura blocanților TNF-α:',
 ['etanerceptul este proteină de fuziune receptor p75–IgG1','certolizumabul este un fragment Fab pegilat, fără Fc','golimumabul este anticorp monoclonal IgG1 uman','etanerceptul este anticorp monoclonal IgG1','certolizumabul are transfer placentar minim'],'ABCE',445,'Blocanții TNF-α — Structură',
 'Asocierea blocanților TNF cu structura lor moleculară.',
 ['Etanerceptul este proteină de fuziune IgG1–receptor p75.','Certolizumabul este un fragment Fab pegilat, fără porțiune Fc.','Golimumabul este anticorp monoclonal IgG1-κ uman.','Etanerceptul nu este anticorp monoclonal.','Lipsa porțiunii Fc explică transferul placentar minim.']],
 [8,'Structurile moleculare sunt permutate între agenți.'],['p75','Fab']),

q('reumatologie-adv-074',['Conform Cadranului 18.32, dozele blocanților TNF includ:',
 ['etanercept 50 mg s.c. săptămânal','adalimumab 40 mg s.c. la 2 săptămâni','golimumab 50 mg s.c. lunar','etanercept 25 mg s.c. de două ori pe săptămână','golimumab 50 mg s.c. săptămânal'],'ABCD',446,'Cadranul 18.32 — DMARD',
 'Fixarea schemelor de administrare ale blocanților TNF.',
 ['Etanercept: 25 mg de două ori pe săptămână sau 50 mg săptămânal.','Adalimumab: 40 mg la 2 săptămâni.','Golimumab: 50 mg lunar.','Etanercept: 25 mg de două ori pe săptămână sau 50 mg săptămânal.','Golimumabul se dă lunar.']],
 [8,'Intervalele de administrare sunt permutate între agenți.'],['40 mg la 2 săptămâni','lunar 50 mg']),

q('reumatologie-adv-076',['Siguranța blocanților TNF-α:',
 ['infecțiile sunt mai frecvente în primele luni','registrele arată un risc net crescut de limfom non-Hodgkin','reactivarea TB este probabil mai rară cu etanercept','infecțiile cresc continuu după primul an','etanerceptul reactivează TB mai des decât ceilalți'],'AC',445,'Blocanții TNF-α — Date privind siguranța',
 'Interpretarea datelor de siguranță ale anti-TNF.',
 ['Ratele de infecție cresc în primele luni, apoi scad.','Nu: registrele nu au indicat risc crescut de LNH.','Reactivarea TB este probabil mai puțin frecventă cu etanercept.','Frecvența infecțiilor scade ulterior.','Reactivarea este probabil mai rară cu etanercept.']],
 [8,'Distractorii inversează cronologia infecțiilor și riscul TB.'],['primele câteva luni','etaner'],[447]),

q('reumatologie-adv-006',['Mecanismele DMARD:',
 ['leflunomida inhibă sinteza de pirimidine','rituximabul țintește CD20 de pe limfocitele B','tocilizumabul blochează receptorul IL-6','abataceptul inhibă sinteza de pirimidine','tofacitinibul este un inhibitor JAK'],'ABCE',445,'DMARD — Mecanisme',
 'Asocierea DMARD cu ținta lor moleculară.',
 ['Leflunomida blochează dihidro-orotat-dehidrogenaza și producerea de pirimidine.','Rituximabul este anti-CD20 (limfocite pre-B și B mature).','Tocilizumabul și sarilumabul sunt anticorpi anti-receptor IL-6.','Abataceptul blochează costimularea limfocitelor T.','Tofacitinibul este un DMARD sintetic țintit (inhibitor JAK).']],
 [8,'Distractorii atribuie mecanisme altor clase.'],['pirimidinei','CD20'],[447]),

q('reumatologie-adv-002',['Abataceptul:',
 ['este o proteină de fuziune CTLA4–Fc IgG1','blochează costimularea limfocitelor T','este contraindicat după eșecul anti-TNF','este un anticorp anti-CD20','este un inhibitor JAK administrat oral'],'AB',447,'Alți agenți biologici — Abatacept',
 'Recunoașterea structurii și indicației abataceptului.',
 ['Abataceptul este proteină de fuziune CTLA4–Fc IgG1.','Modulează activarea limfocitelor T prin blocarea costimulării.','Nu: poate fi folosit la non-responderii la anti-TNF.','Anti-CD20 este rituximabul.','Inhibitorii JAK sunt tofacitinib și baricitinib.']],
 [8,'Distractorii descriu alte biologice.'],['CTLA4','costimulării']),

q('reumatologie-adv-057',['Rituximabul în AR seropozitivă:',
 ['produce limfopenie B timp de 6–9 luni','răspunde la aproximativ 20% dintre pacienții FR pozitivi','impune monitorizarea imunoglobulinelor','produce limfopenie B permanentă','crește predictibil imunoglobulinele'],'AC',447,'Alți agenți biologici — Rituximab',
 'Recunoașterea efectelor și monitorizării rituximabului.',
 ['Limfopenia B durează 6–9 luni.','Nu: aproximativ 80% dintre pacienții FR pozitivi răspund.','Imunoglobulinele pot scădea la administrări repetate și se monitorizează.','Limfopenia durează 6–9 luni.','Imunoglobulinele pot scădea.']],
 [8,'Distractorii contrazic reversibilitatea și efectul asupra imunoglobulinelor.'],['6-9 luni','80%']),

q('reumatologie-adv-007',['La pierderea răspunsului la blocanții TNF-α:',
 ['nivelul terapeutic de medicament orientează spre un non-anti-TNF','nivelul subterapeutic sugerează non-complianță sau anticorpi','nivelul subterapeutic permite trecerea la alt anti-TNF','nivelul terapeutic orientează spre alt anti-TNF','nivelul subterapeutic exclude anticorpii anti-medicament'],'ABC',447,'Schimbarea terapiilor DMARD',
 'Interpretarea nivelurilor de medicament la pierderea răspunsului.',
 ['La nivel terapeutic se preferă un preparat non-anti-TNF.','Nivelul subterapeutic sugerează non-complianță sau anticorpi anti-medicament.','Se poate trece la alt anti-TNF sau la altă clasă.','La nivel terapeutic se schimbă clasa.','Anticorpii sunt o explicație a nivelului scăzut.']],
 [8,'Distractorii inversează logica deciziei.'],['non-anti-TNF','anti-medicament']),

q('reumatologie-adv-029',['La pacienții cu AR în remisiune susținută peste un an, este obișnuită:',
 ['reducerea dozei de DMARD','creșterea dozei de bDMARD','oprirea tuturor DMARD','trecerea la un inhibitor JAK','adăugarea unui glucocorticoid'],'A',447,'Schimbarea terapiilor DMARD — Tapering',
 'Aplicarea reducerii tratamentului în remisiunea susținută.',
 ['Se încearcă reducerea dozei sau prelungirea intervalului dintre administrări.','Nu este conduita citată.','Nu este conduita citată.','Nu este conduita citată.','Nu este conduita citată.']],
 [8,'Distractorii sunt modificări terapeutice reale, dar neindicate aici.'],['remisiunea susţinută','intervalului']),

q('reumatologie-adv-077',['Conform Cadranului 18.33 (ACR/EULAR 2011), remisiunea AR în studii cere:',
 ['cel mult o articulație dureroasă','cel mult o articulație tumefiată','PCR de cel mult 1 mg/L','DAS28 sub 3,2, fără alte criterii','includerea picioarelor și gleznelor'],'ABCE',447,'Cadranul 18.33 — Remisiunea ACR/EULAR 2011',
 'Aplicarea definiției remisiunii ACR/EULAR 2011.',
 ['Numărul articulațiilor dureroase ≤1, inclusiv picioarele.','Numărul articulațiilor tumefiate ≤1.','PCR ≤1 mg/L.','DAS28 <3,2 este activitate scăzută, nu această definiție.','Picioarele și gleznele sunt incluse.']],
 [8,'Distractorii amestecă definiția cu pragurile DAS28.'],['PCR Sl mg/L','inclusiv picioarele']),

q('reumatologie-adv-078',['Indică un prognostic negativ în AR:',
 ['debutul insidios al bolii','titrurile ridicate de ACPA și FR','eroziunile radiografice precoce','debutul exploziv, peste noapte','sexul feminin'],'ABCE',447,'Artrita reumatoidă — Prognostic',
 'Recunoașterea factorilor de prognostic negativ în AR.',
 ['Debutul insidios, mai degrabă decât exploziv, indică prognostic negativ.','Titrurile ridicate de ACPA și FR indică prognostic negativ.','Eroziunile precoce indică prognostic negativ.','Debutul insidios este factorul negativ.','Sexul feminin este factor negativ.']],
 [8,'Distractorii inversează tipul de debut și sexul.'],['insidios','eroziv']),

q('reumatologie-adv-030',['Grupul spondilartritelor cuprinde:',
 ['spondilita anchilozantă','artrita psoriazică','artrita enteropatică','artrita reumatoidă seronegativă','polimialgia reumatică'],'ABC',447,'Spondilartrita — Cadranul 18.34',
 'Enumerarea formelor de spondilartrită.',
 ['Spondilartrita axială include spondilita anchilozantă.','Artrita psoriazică face parte din grup.','Artrita enteropatică face parte din grup.','AR seronegativă nu este o spondilartrită.','Polimialgia nu face parte din grup.']],
 [8,'Distractorii sunt afecțiuni seronegative din afara grupului.'],['Artrita psoriazică','enteropatică']),

q('reumatologie-adv-079',['Spondilartrita, comparativ cu AR:',
 ['are sinovită fără FR și ACPA','are entezită și anchiloză mai frecvente','se asociază cu HLA-DR4, ca AR','produce FR în titru înalt, ca AR','are anchiloză mai rară decât AR'],'AB',448,'Spondilartrita — Caracteristici',
 'Diferențierea spondilartritei de AR.',
 ['Sinovita este similară histologic, dar fără FR și ACPA.','Entezita și anchiloza sunt mai frecvente decât în AR.','Nu: spondilartritele se asociază cu HLA-B27; HLA-DR4 ține de AR.','Spondilartrita nu produce FR.','Anchiloza este mai frecventă.']],
 [8,'Distractorii atribuie spondilartritei trăsături ale AR.'],['entezei','HLA-B27']),

q('reumatologie-adv-058',['Spondilita anchilozantă:',
 ['are un raport bărbați:femei de 3:1','afectează adulții tineri','are HLA-B27 la 95% dintre pacienții albi','are un raport femei:bărbați de 3:1','HLA-B27 la ~8% din populația albă generală'],'ABCE',448,'Spondilita anchilozantă — Epidemiologie',
 'Fixarea datelor epidemiologice ale spondilitei anchilozante.',
 ['Raportul bărbați:femei este 3:1.','Afectează în principal adulții tineri.','95% dintre pacienții albi au HLA-B27.','Predomină la bărbați.','8% este frecvența HLA-B27 în populația albă generală.']],
 [8,'Distractorii inversează sexul și confundă populația cu bolnavii.'],['3:1','95%']),

q('reumatologie-adv-008',['Mecanismele din spondilartrita axială:',
 ['prezentarea peptidului de către HLA-B27 limfocitelor T CD8+','plierea greșită a HLA-B27 duce la producerea de IL-23','entezita se vindecă prin formare de sindesmofite','prezentarea peptidului limfocitelor T CD4+ prin MHC II','sindesmofitele apar la inserțiile ligamentare'],'ABCE',448,'Spondilita anchilozantă — Etiologie',
 'Recunoașterea mecanismelor patogenice ale spondilartritei axiale.',
 ['HLA-B27 prezintă peptidul limfocitelor T CD8+.','Plierea greșită a HLA-B27 produce IL-23.','Eroziunea la inserția ligamentelor se vindecă prin sindesmofite.','HLA-B27 este MHC de clasa I, cu limfocite CD8+.','Sindesmofitele apar la inserțiile ligamentare.']],
 [8,'Distractorii schimbă clasa MHC și sediul leziunii.'],['IL-23','sindesmofite']),

q('reumatologie-adv-059',['În spondilita anchilozantă:',
 ['lombalgia se ameliorează la efort','testul Schober cu creștere sub 5 cm implică rigiditate','uveita anterioară acută apare la ~30%','lombalgia nu se ameliorează la repaus','testul Schober cu creștere sub 15 cm este normal'],'ABCD',448,'Spondilita anchilozantă — Tablou clinic',
 'Aplicarea criteriilor clinice și a testului Schober.',
 ['Ameliorarea la efort este criteriu de lombalgie inflamatoare.','O creștere sub 5 cm la testul Schober implică rigiditate spinală.','Uveita anterioară acută apare la ~30%.','Lipsa ameliorării la repaus este criteriu de lombalgie inflamatoare.','Pragul de rigiditate este creșterea sub 5 cm.']],
 [8,'Distractorii inversează răspunsul la efort și pragul Schober.'],['Schober','30%']),

q('reumatologie-adv-031',['În spondilita anchilozantă:',
 ['HLA-B27 nu este un test diagnostic','insuficiența aortică apare la aproximativ 1%','sub 20% își păstrează activitatea profesională','HLA-B27 pozitiv confirmă singur diagnosticul','anomaliile de conducere nu apar'],'AB',449,'Spondilita anchilozantă — Investigații și prognostic',
 'Interpretarea testului HLA-B27 și a prognosticului SA.',
 ['HLA-B27 nu este diagnostic din cauza frecvenței în populație.','Insuficiența aortică apare la ~1% dintre cei cu SA constituită.','Nu: peste 80% își păstrează activitatea profesională.','HLA-B27 doar consolidează un diagnostic suspectat.','Anomaliile de conducere apar la ~5%.']],
 [8,'Distractorii supraestimează HLA-B27 și neagă afectarea cardiacă.'],['HLA-827','80%'],[450]),

q('reumatologie-adv-080',['Manifestările extra-spinale ale spondilitei anchilozante includ:',
 ['insuficiența renală, legată mai ales de AINS','osteoporoza axială la ~25%','fractura vertebrală la ~10%','nefropatia IgA ca principală cauză renală','osteoporoza axială la ~75%'],'ABC',449,'Spondilita anchilozantă — Manifestări extra-spinale',
 'Recunoașterea manifestărilor extra-spinale ale SA.',
 ['Insuficiența renală (10–35%) este legată mai ales de AINS.','Osteoporoza axială apare la ~25%.','Fractura vertebrală apare la ~10%.','Cauza citată este utilizarea cronică de AINS.','Proporția citată este ~25%.']],
 [8,'Distractorii schimbă cauza renală și frecvența osteoporozei.'],['10-35%','25%']),

q('reumatologie-adv-081',['În managementul spondilitei anchilozante:',
 ['exercițiile se încep înaintea formării sindesmofitelor','AINS cu acțiune lungă seara ajută somnul și exercițiile','sulfasalazina ajută artrita periferică','sulfasalazina ajută afectarea spinală','exercițiile se amână după formarea sindesmofitelor'],'ABC',449,'Spondilita anchilozantă — Tratament',
 'Aplicarea tratamentului non-farmacologic și farmacologic în SA.',
 ['Exercițiile preventive se încep înaintea sindesmofitelor.','AINS cu acțiune lungă seara îmbunătățesc somnul și exercițiile.','Sulfasalazina poate fi utilă pentru artrita periferică.','Nu este utilă pentru afectarea spinală.','Exercițiile se încep precoce.']],
 [8,'Distractorii inversează indicația sulfasalazinei și momentul exercițiilor.'],['sindesmofitelor','Sulfasalazina poate fi utila']),

q('reumatologie-adv-060',['Blocanții TNF-α în spondilita anchilozantă:',
 ['reduc substanțial simptomele spinale și periferice','nu reduc convingător progresia radiografică','permit tratament intermitent','opresc progresia radiografică în formele vechi','produc recădere după oprirea tratamentului'],'ABCE',450,'Spondilita anchilozantă — Blocanții TNF',
 'Evaluarea beneficiilor și limitelor anti-TNF în SA.',
 ['Reduc substanțial simptomele spinale și periferice.','Nu s-au găsit dovezi convingătoare de reducere a progresiei radiografice.','Recăderea poate fi întârziată cu luni, permițând tratament intermitent.','Dovezile nu sunt convingătoare.','Recăderea apare la întreruperea tratamentului.']],
 [8,'Distractorii supraestimează efectul structural.'],['progresiei radiografice','intermitent'],[449]),

q('reumatologie-adv-032',['Artrita psoriazică:',
 ['apare la aproximativ 10% dintre pacienții cu psoriazis','precede afectarea cutanată în ~15% din cazuri','are HLA-B27 doar la 50% în forma spondilitică','urmează afectarea cutanată în toate cazurile','impune evitarea hidroxiclorochinei'],'ABCE',450,'Artrita psoriazică — Epidemiologie și tratament',
 'Recunoașterea datelor epidemiologice și a precauțiilor terapeutice în APs.',
 ['Aproximativ 10% dintre pacienții cu psoriazis dezvoltă APs.','APs precede boala de piele în ~15% din cazuri.','Doar 50% din forma spondilitică au HLA-B27.','APs poate preceda pielea.','Hidroxiclorochina se evită (reacții psoriazice acute).']],
 [8,'Distractorii contrazic cronologia și contraindicația hidroxiclorochinei.'],['10%','15%']),

q('reumatologie-adv-009',['Formele clinice ale artritei psoriazice includ:',
 ['artrita IFD cu distrofie unghială','dactilita (deget în cârnat)','artrita mutilantă, cu scurtarea oaselor','artrita mutilantă, fără osteoliză','eroziunile centrale, în „toc în călimară”'],'ABCE',450,'Artrita psoriazică — Tablou clinic',
 'Recunoașterea formelor clinice ale artritei psoriazice.',
 ['Artrita IFD se asociază cu distrofie unghială.','Dactilita este o manifestare caracteristică.','Artrita mutilantă produce osteoliză și scurtarea oaselor.','Oasele se scurtează prin osteoliză.','Eroziunile sunt centrale, cu aspect de toc în călimară.']],
 [8,'Distractorii contrazic mecanismul și sediul eroziunilor.'],['Dactilita','toc în călimară']),

q('reumatologie-adv-011',['Terapiile țintite în artrita psoriazică:',
 ['secukinumab și ixekizumab inhibă IL-17','ustekinumab inhibă IL-12/23','apremilastul inhibă PDE4','ustekinumabul blochează receptorul IL-6','tofacitinibul este un inhibitor JAK'],'ABCE',450,'Artrita psoriazică — Terapii biologice și țintite',
 'Asocierea terapiilor țintite cu mecanismul lor.',
 ['Secukinumab și ixekizumab inhibă IL-17.','Ustekinumabul inhibă IL-12/23.','Apremilastul este inhibitor oral al PDE4.','Receptorul IL-6 este ținta tocilizumabului.','Inhibitorul JAK citat este tofacitinibul.']],
 [8,'Țintele moleculare sunt permutate între agenți.'],['secukinumab','PDE4']),

q('reumatologie-adv-033',['Artrita reactivă:',
 ['apare la 1–2% după dizenterie sau infecție sexuală','HLA-B27 crește riscul de 30–50 de ori la bărbați','10% se recuperează complet în primele 6 luni','afectează mai frecvent femeile decât bărbații','apare la toți purtătorii de HLA-B27 după infecție'],'AB',450,'Artrita reactivă',
 'Recunoașterea epidemiologiei și evoluției artritei reactive.',
 ['Spondilartrita apare la 1–2% după dizenterie sau infecție sexuală.','La bărbați, HLA-B27 crește riscul de 30–50 de ori.','Nu: 70% se recuperează complet în 6 luni.','Femeile sunt mai rar afectate.','Nu toți pacienții au HLA-B27.']],
 [8,'Distractorii inversează sexul și generalizează rolul HLA-B27.'],['1-2%','30-50']),

q('reumatologie-adv-082',['Declanșatorii artritei reactive includ:',
 ['Salmonella și Shigella','Yersinia enterocolitica','Chlamydia trachomatis','Streptococcus pyogenes','Neisseria gonorrhoeae'],'ABC',450,'Artrita reactivă — Etiologie',
 'Identificarea microorganismelor declanșatoare ale artritei reactive.',
 ['Salmonella și Shigella declanșează artrita post-dizenterică.','Yersinia produce diaree și artrită reactivă.','Chlamydia și Ureaplasma declanșează artrita post-uretritică.','Artrita post-streptococică are o bază genetică diferită.','Artrita gonococică are o bază genetică diferită.']],
 [8,'Distractorii produc artrite cu altă bază genetică.'],['Yersinia','Chlamydia']),

q('reumatologie-adv-010',['Leziunile cutaneo-mucoase și tendinoase ale artritei reactive:',
 ['balanita circinată nedureroasă','keratoderma blennorragică','fasciita plantară','uveita asincronă cu artrita','keratodermă cu histologie lupică'],'ABCD',451,'Artrita reactivă — Tablou clinic',
 'Recunoașterea leziunilor din artrita reactivă.',
 ['Balanita circinată produce ulcerații superficiale nedureroase.','Keratoderma blennorragică este histologic similară psoriazisului pustular.','Entezita produce fasciită plantară sau afectare ahiliană.','Uveita nu este sincronă cu artrita.','Histologia este similară psoriazisului pustular.']],
 [8,'Distractorii contrazic cronologia uveitei și histologia leziunilor.'],['Balanita circinată','Keratoderma']),

q('reumatologie-adv-034',['Artrita enteropatică asociată BII:',
 ['apare la până la 10–15% dintre pacienți','este asimetrică, predominant la membrele inferioare','se remite de obicei după colectomie totală în colita ulcerativă','nu este influențată de colectomie în colita ulcerativă','este simetrică, a articulațiilor mici ale mâinilor'],'ABC',451,'Artrita enteropatică',
 'Recunoașterea caracteristicilor artritei enteropatice.',
 ['Sinovita enteropatică apare la până la 10–15%.','Artrita este asimetrică, predominant la membrele inferioare.','Remisiunea colitei și colectomia totală duc de obicei la remisiunea articulară.','Colectomia influențează favorabil artrita din CU.','Afectarea este asimetrică, a membrelor inferioare.']],
 [8,'Distractorii contrazic distribuția și efectul colectomiei.'],['10-15%','colectomia totală']),

q('reumatologie-adv-035',['Guta:',
 ['are un raport bărbați:femei de 5:1','este idiopatică în 85–90% din cazuri','apare prin reducerea excreției de acid urat la ~90%','apare prin eroare enzimatică la sub 1%','are un raport femei:bărbați de 5:1'],'ABCD',452,'Guta și hiperuricemia — Epidemiologie',
 'Recunoașterea epidemiologiei și a mecanismului hiperuricemiei.',
 ['Guta este mai frecventă la bărbați (5:1).','85–90% din cazuri sunt idiopatice.','Aproximativ 90% au reducerea excreției acidului uric.','Eroarea enzimatică explică sub 1% din cazuri.','Predomină la bărbați.']],
 [8,'Distractorii inversează mecanismul dominant și sexul.'],['5:1','85-90%']),

q('reumatologie-adv-083',['Eliminarea și transportul uratului:',
 ['uratul se elimină renal (66%) și intestinal (33%)','ABCG2 este un transportor secretor intestinal','diureticele tiazidice scad excreția de urat','uratul se elimină integral renal','diureticele tiazidice cresc excreția de urat'],'ABC',452,'Guta — Patogeneză',
 'Recunoașterea căilor de eliminare a uratului.',
 ['Eliminarea uratului este renală (66%) și intestinală (33%).','ABCG2 este un transportor secretor prezent în intestin.','Tiazidele afectează excreția acidului uric.','Există și o cale intestinală.','Tiazidele scad excreția.']],
 [8,'Distractorii ignoră calea intestinală și inversează efectul tiazidelor.'],['66%','ABCG2']),

q('reumatologie-adv-084',['Formarea cristalelor de urat:',
 ['are loc peste 408 µmol/L la pH și temperatură fiziologică','poate apărea la 360 µmol/L la 35°C','este legată de activarea inflamazomului NLRP3','cere un acid uric peste 800 µmol/L','depinde de temperatura tisulară'],'ABCE',452,'Guta — Formarea cristalelor',
 'Aplicarea pragurilor de cristalizare a uratului.',
 ['Hiperuricemia patologică este 408 µmol/L, prag de cristalizare in vitro.','Cristalele pot apărea la 360 µmol/L la 35°C.','Cristalele activează inflamazomul NLRP3.','Nu este pragul citat.','Temperatura mai joasă scade pragul de cristalizare.']],
 [8,'Distractorii contrazic influența temperaturii.'],['408','NLRP3']),

q('reumatologie-adv-061',['Atacul de gută:',
 ['netratat durează aproximativ 7 zile','afectează altă articulație decât MTF1 în 25% din atacuri','are acid uric constant crescut imediat după atac','netratat durează aproximativ 24 de ore','afectează MTF1 în toate atacurile'],'AB',453,'Guta — Tablou clinic și investigații',
 'Recunoașterea evoluției atacului și interpretarea uricemiei.',
 ['Atacurile netratate durează aproximativ 7 zile.','În 25% din atacuri este afectată altă articulație.','Nu: uricemia scade imediat după atac; se recontrolează după săptămâni.','Durata este de aproximativ 7 zile.','25% afectează alte articulații.']],
 [8,'Distractorii scurtează evoluția și generalizează sediul.'],['7 zile','25%']),

q('reumatologie-adv-036',['În tratamentul gutei:',
 ['naproxenul se dă 750 mg imediat, apoi 500 mg la 8–12 ore','ținta acidului uric este sub 360 µmol/L','alopurinolul nu se începe în luna de după un atac','alopurinolul se începe în plin atac','alopurinolul se începe în plin atac, pentru control rapid'],'ABC',453,'Guta — Tratament',
 'Aplicarea tratamentului atacului și a țintei hipouricemiante.',
 ['Naproxen: 750 mg imediat, apoi 500 mg la 8–12 ore.','Ținta este sub 360 µmol/L (sub 300 în guta severă).','Alopurinolul nu se începe în termen de o lună de la un atac.','Alopurinolul poate precipita un atac dacă e început precoce.','Ținta citată este sub 360 µmol/L.']],
 [8,'Distractorii schimbă ținta și momentul inițierii.'],['750 mg','360 pmol']),

q('reumatologie-adv-086',['Febuxostatul și pegloticaza:',
 ['febuxostatul se metabolizează hepatic','febuxostatul are mortalitate cardiovasculară mai mare decât alopurinolul','pegloticaza este rezervată gutei severe refractare','febuxostatul este prima alegere, înaintea alopurinolului','pegloticaza se administrează intravenos'],'ABCE',453,'Guta — Febuxostat și pegloticază',
 'Poziționarea febuxostatului și pegloticazei în tratamentul gutei.',
 ['Febuxostatul se metabolizează hepatic, fiind mai sigur în insuficiența renală.','Mortalitatea de toate cauzele și cea cardiovasculară sunt mai mari decât cu alopurinol.','Pegloticaza este rezervată gutei severe refractare.','Alopurinolul rămâne prima alegere.','Pegloticaza se administrează intravenos.']],
 [8,'Distractorii inversează ierarhia și calea de administrare.'],['Febuxostat','Pegloticaza'],[454]),

q('reumatologie-adv-062',['Losartanul este menționat în gută deoarece:',
 ['este uricozuric la hipertensivii cu gută','este inhibitor de xantin-oxidază','este analog non-purinic al alopurinolului','crește producția endogenă de urat','inhibă transportorul ABCG2'],'A',453,'Guta — Losartan',
 'Recunoașterea efectului uricozuric al losartanului.',
 ['Losartanul este uricozuric la hipertensivii cu gută și poate reduce riscul în sindromul metabolic.','Inhibitorii de xantin-oxidază sunt alopurinolul și febuxostatul.','Febuxostatul este analogul non-purinic.','Nu este efectul citat.','Nu este mecanismul citat.']],
 [8,'Distractorii descriu mecanismele altor hipouricemiante.'],['Losartanul','uricozuric']),

q('reumatologie-adv-037',['Artropatia prin depunere de pirofosfat de calciu:',
 ['este cea mai frecventă artrită inflamatorie','afectează mai frecvent femeile în vârstă','are cristale romboidale cu birefringență pozitivă slabă','are cristale aciculare cu birefringență negativă','are un tratament specific de eliminare a cristalelor'],'BC',454,'Artropatia prin depunere de PFCD',
 'Recunoașterea caracteristicilor artropatiei PFCD.',
 ['Nu: este a treia cea mai frecventă artrită inflamatorie.','Este mai frecventă la femeile în vârstă, la genunchi sau carp.','Cristalele sunt romboidale, cu birefringență pozitivă slabă.','Cristalele aciculare sunt de urat.','Nu există tratament specific de eliminare a cristalelor.']],
 [8,'Distractorii preiau caracteristicile cristalelor de urat.'],['romboidale','a treia']),

q('reumatologie-adv-087',['Boala prin depunere de fosfat de calciu bazic:',
 ['include hidroxiapatita și fosfatul tricalcic','produce periartrită calcifiantă a supraspinosului','se asociază cu umărul Milwaukee','include și fosfatul octacalcic','are cristale aciculare cu birefringență negativă'],'ABCD',454,'Boala prin depunere de fosfat de calciu bazic',
 'Recunoașterea formelor și a diagnosticului bolii FCB.',
 ['Cristalele includ hidroxiapatita, fosfatul tricalcic și octacalcic.','Depozitele produc periartrită calcifiantă, mai ales în supraspinos.','Artropatia distructivă apare la umeri (umărul Milwaukee).','Cristalele includ hidroxiapatita, fosfatul tricalcic și octacalcic.','Aceste cristale sunt de urat.']],
 [8,'Distractorii supraestimează specificitatea colorației.'],['hidroxiapatita','Milwaukee']),

q('reumatologie-adv-063',['Tabloul clinic al lupusului eritematos sistemic:',
 ['afectarea articulară apare la peste 90%','miozita adevărată apare la sub 5%','nefrita clinică apare doar la 30%','eroziunile osoase sunt frecvente, ca în AR','afectarea cutanată apare la aproximativ 85%'],'ABCE',458,'Lupus eritematos sistemic — Tablou clinic',
 'Fixarea frecvențelor manifestărilor LES.',
 ['Articulațiile sunt afectate la peste 90%.','Mialgia apare la ~50%, dar miozita adevărată la sub 5%.','Afectarea renală clinică apare doar la 30%.','Eroziunile osoase sunt rare.','Tegumentul este afectat în 85%.']],
 [8,'Distractorii preiau frecvențe ale altor organe sau alte boli.'],['5%','30%']),

q('reumatologie-adv-038',['Investigațiile în lupusul eritematos sistemic:',
 ['VSH crește cu activitatea bolii','PCR este de obicei normală','C3 și C4 scad în boala activă','PCR crește paralel cu activitatea bolii','C3 și C4 cresc în boala activă'],'ABC',459,'Lupus eritematos sistemic — Investigații',
 'Interpretarea markerilor inflamatori și a complementului în LES.',
 ['VSH-ul este crescut în raport cu activitatea bolii.','PCR este de obicei normală, cu excepții (serozite, artrită, infecție).','C3 și C4 sunt adesea scăzute în boala activă.','PCR este de obicei normală.','Complementul scade în boala activă.']],
 [8,'Distractorii inversează comportamentul PCR și al complementului.'],['VSH-ul este crescut','C3 şi C4']),

q('reumatologie-adv-088',['Tratamentul, prognosticul și sarcina în LES:',
 ['hidroxiclorochina poate produce modificări retiniene','micofenolatul a înlocuit în mare parte ciclofosfamida','supraviețuirea la 10 ani este de 90%','micofenolatul este sigur în sarcină','supraviețuirea la 10 ani este sub 50%'],'ABC',459,'Lupus eritematos sistemic — Tratament și prognostic',
 'Recunoașterea tratamentului și prognosticului LES.',
 ['Modificările retiniene apar la până la 7,5% dintre tratații pe termen lung.','Micofenolatul a înlocuit la scară largă ciclofosfamida.','Supraviețuirea la 10 ani este de 90%.','Micofenolatul se oprește în sarcină.','Supraviețuirea la 10 ani este de 90%.']],
 [8,'Distractorii inversează siguranța în sarcină și prognosticul.'],['micofenolatul','90%']),
];
