import {advancedQuestion} from './advanced-author';
import type {SourceRow} from './source-author';
const pdfOffset=(p:number)=>p===458?86:p-370;
const q=(n:number,row:SourceRow,score:number,reason:string,expressions:string[],related:number[]=[])=>
 advancedQuestion('reumatologie',18,pdfOffset,`reumatologie-adv-${String(n).padStart(3,'0')}`,row,[score,reason],expressions,undefined,related);

export const REUMATOLOGIE_C=[
q(39,['Identificați afirmația corectă referitoare la evaluarea artritei inflamatoare precoce:',
 ['Diagnosticul este ajutat de numărul și tipul articulațiilor (simetric/asimetric, mari/mici), de boala non-articulară, de antecedentele personale sau familiale și de periodicitate (unică acută, recurentă, cronică progresivă)','Diagnosticul se bazează doar pe eroziunile radiografice tardive, fără evaluarea periodicității','Markerii inflamatori VSH și PCR sunt de obicei normali în sinovita inflamatoare, spre deosebire de artroză','Durerea inflamatoare se ameliorează la repaus și se agravează imediat la efort, identic artrozei','Separarea genetică MHC dispare odată ce artrita a devenit simetrică'],'A',437,'Afecțiuni articulare inflamatoare — Evaluare diagnostică',
 'Reținerea pachetului de evaluare (număr/tip, extra-articular, familie, periodicitate), distinct de eroziunile tardive.',
 ['Cele patru axe de evaluare sunt enumerate explicit.','Textul precizează că în artrita precoce diagnosticul specific poate lipsi până la evoluție; eroziunile nu sunt criteriul de start.','VSH și PCR sunt de obicei crescuți în afecțiunile inflamatoare.','Durerea și redoarea inflamatoare sunt mai accentuate dimineața, durând adesea câteva ore, și se ameliorează cu activitatea.','Separarea MHC (clasa II în AR, B27/clasa I în SpA) este descrisă ca distinctă, independent de simetrie.']],
 8,'Distractorii mută diagnosticul pe eroziuni tardive și inversează redoarea inflamatoare versus mecanică din același paragraf.',['numărului şi tipului','periodicităţii artritei']),

q(40,['Alegeți afirmațiile corecte referitoare la indiciile extra-articulare și la redoarea matinală:',
 ['Psoriazisul, iridociclita, bolile inflamatorii intestinale, uretrita nespecifică sau dizenteria recentă sugerează spondilartrită','Pot exista dovezi de boală virală recentă (rubeolă, hepatită B sau eritrovirus), febră reumatică sau mușcătură de căpușă cu erupție (boala Lyme)','Durerea și redoarea inflamatoare sunt mai accentuate dimineața, adesea durând câteva ore și îmbunătățindu-se odată cu activitatea, spre deosebire de redoarea scurtă și durerea mecanică din OA','Iridociclita și BII orientează către artrita microcristalină, nu către SpA','Redoarea matinală de câteva ore este tipică artrozei, nu sinovitei'],'ABC',437,'Afecțiuni articulare inflamatoare — Indicii extra-articulare',
 'Contrastarea indiciilor de SpA și a etiologiilor virale/Lyme cu redoarea matinală prelungită versus OA.',
 ['Lista extra-articulară de SpA este cea din paragraf.','Cele trei etiologii virale, febra reumatică și Lyme sunt enumerate.','Contrastul cu OA (redoare scurtă, durere mecanică) este explicit.','Psoriazisul, iridociclita și BII sugerează SpA, nu cristale.','Redoarea de câteva ore caracterizează inflamatorul, nu OA.']],
 8,'Distractorii mută iridociclita/BII pe cristale și atribuie redoarea prelungită artrozei, inversând contrastul din text.',['iridociclita','câteva ore']),

q(41,['În imunopatogenia AR, dincolo de VCAM-1/DAF deja consacrate, sunt adevărate:',
 ['Producerea în exces de TNF-α, determinată de interacțiunea macrofagelor cu limfocitele T și B, duce la sinovită și distrugerea articulațiilor; TNF-α stimulează sinteza în exces de IL-6','Osteoclastele cauzează distrugerea osului și cartilajului','Celulele sinoviale predominante sunt condrocitele hialine, osteoclastul fiind absent din leziune','TNF-α inhibă IL-6, motiv pentru care anti-TNF agravează sinovita','Limfocitele Th17 sunt suprimate de TGF-β, iar T reglatoarele se dezvoltă nestingherit'],'AB',438,'Artrita reumatoidă — Imunologie',
 'Plasarea excesului de TNF-α/IL-6 și a osteoclastului în lanțul distructiv, distinct de moleculele de adeziune deja acoperite.',
 ['Excesul de TNF-α și inducerea IL-6 sunt enunțate.','Rolul osteoclastelor este listat printre disfuncțiile celulare.','Sinoviocitele asemănătoare fibroblastelor și macrofagelor predomină; osteoclastul este prezent și distructiv.','TNF-α stimulează, nu inhibă, IL-6.','Textul precizează că T reglatoarele normale sunt suprimate, permițând Th17 să se dezvolte.']],
 8,'Distractorii inversează inducerea IL-6 de către TNF-α și soarta Th17/Treg din același paragraf.',['TNF-a','Osteoclastele'],[439]),

q(42,['Selectați enunțurile adevărate despre FR de tip IgM și despre ACPA, dincolo de prevalența 75-80%:',
 ['Cele mai frecvente teste clinice detectează FR de tip IgM; „AR seronegativă” se folosește când testele standard pentru FR IgM sunt persistent negative, acești pacienți având un tip mai limitat de sinovită','FR IgM nu sunt diagnostici pentru AR și absența lor nu exclude boala; un titru persistent ridicat în boala precoce implică sinovită persistent activă și mai multe leziuni, justificând DMARD precoce','ACPA sunt factori predictivi mai puternici pentru tranziția de la artrita inflamatorie tranzitorie precoce la sinovita persistentă; prezența asociată FR și ACPA este și mai specifică','FR IgM negativ infirmă definitiv AR, indiferent de clinică','ACPA sunt mai slabi predictori de persistență decât FR IgM izolat'],'ABC',439,'Factorii reumatoizi și ACPA',
 'Separarea valorii non-diagnostice a FR IgM de puterea predictivă superioară a ACPA și de specificitatea combinației.',
 ['Definiția seronegativității și sinovita mai limitată sunt explicite.','Absența valorii diagnostice și rolul prognostic al titrului înalt sunt enunțate.','Puterea predictivă a ACPA și specificitatea combinației sunt din închiderea paragrafului.','Absența FR IgM nu exclude boala.','Textul atribuie ACPA predicția mai puternică, nu mai slabă.']],
 8,'Distractorii transformă un marker prognostic (FR IgM) într-un test de excludere și inversează ierarhia ACPA versus FR.',['AR seronegativă','mai puternici']),

q(43,['La un pacient cu poliartrită inflamatorie de 8 săptămâni, un test ACPA pozitiv, fără psoriazis personal sau familial, combinat cu cel puțin o articulație tumefiată peste 6 săptămâni, reprezintă, potrivit capitolului:',
 ['Cel mai bun mod de a selecta pacienții pentru tratament precoce, pentru a evita leziunile articulare','Un motiv de a amâna DMARD până apar eroziunile radiografice clasice','O indicație de a clasifica imediat cazul ca spondilartrită, independent de ACPA','Un argument că criteriile 2010 sunt inferioare celor vechi, deoarece cer extra-articularul tardiv','O contraindicație de tratament, ACPA având valoare doar retrospectivă'],'A',440,'Artrita reumatoidă — Selecția pentru tratament precoce',
 'Reținerea combinației ≥1 articulație tumefiată >6 săptămâni + ACPA, fără teren de SpA, ca selector de tratament precoce.',
 ['Această combinație este descrisă ca cel mai bun mod de selecție; abordarea reduce riscul de leziuni permanente.','Criteriile 2010 tocmai evită așteptarea eroziunilor tardive.','Absența terenului de SpA și ACPA orientează către AR, nu către SpA.','Textul spune că criteriile 2010 sunt mai potrivite pentru artrita precoce decât versiunile anterioare.','ACPA pot preceda clinic boala și ghidează tratamentul precoce.']],
 8,'Distractorii amână tratamentul până la eroziuni, inversând tocmai argumentul criteriilor 2010 din același paragraf.',['mai mult de 6 săptămâni','test ACPA pozitiv']),

q(44,['Conform Cadranului 18.26, factorii care prezic un prognostic negativ pentru progresia AR precoce includ:',
 ['Vârstă înaintată și sexul feminin','Afectarea simetrică a articulațiilor mici și redoarea matinală peste 30 de minute','Peste 4 articulații tumefiate și fumatul','FR și ACPA pozitivi, plus comorbidități','Debut exploziv la bărbat tânăr, monoarticular, fără redoare matinală'],'ABCD',440,'Cadranul 18.26 — Prognostic negativ în AR precoce',
 'Recunoașterea clusterului de rău prognostic (vârstă, sex, simetrie, redoare >30 min, >4 articulații, fumat, serologie).',
 ['Vârsta și sexul feminin figurează în cadran.','Simetria articulațiilor mici și redoarea >30 de minute sunt listate.','Pragul >4 articulații tumefiate și fumatul completează lista.','FR/ACPA și comorbiditățile sunt ultimele rânduri.','Profilul exploziv monoarticular masculin nu este clusterul de rău prognostic al cadranului.']],
 8,'Patru elemente reale din același cadran; distractorul descrie tocmai reversul (bărbat tânăr, mono, fără redoare).',['>30 de minute','>4 articulaţii tumefiate']),

q(45,['În Cadranul 18.28 (ACR/EULAR 2010), punctajele de domeniu, dincolo de pragul ≥6, includ:',
 ['O articulație medie/mare valorează 0 puncte; 2-10 articulații medii/mari valorează 1 punct','FR sau ACPA pozitivi în titru mare valorează 3 puncte; reactanții de fază acută anormali valorează 1 punct','Durata simptomelor ≥6 săptămâni valorează 1 punct; sub 6 săptămâni valorează 0','O articulație medie/mare valorează 5 puncte, suficientă singură pentru clasificare','Durata sub 6 săptămâni valorează 3 puncte, identic serologiei în titru mare'],'ABC',440,'Cadranul 18.28 — Punctajele ACR/EULAR 2010',
 'Reținerea punctajelor de domeniu (0 pentru o articulație mare, 3 pentru serologie înaltă, 1 pentru durată ≥6 săptămâni), nu doar a pragului de 6.',
 ['Perechea 0 / 1 pentru articulații mari este din tabel.','3 puncte pentru titru mare și 1 pentru PCR/VSH anormal sunt explicite.','Durata ≥6 săptămâni = 1, <6 = 0.','5 puncte revin a >10 articulații cu cel puțin o articulație mică, nu unei singure articulații mari.','Durata scurtă valorează 0, nu 3.']],
 8,'Distractorii permută punctajele reale 0, 1, 3 și 5 între domenii, capcana clasică a tabelului de clasificare.',['2-10 articulaţii','e:6 săptămâni']),

q(46,['Un pacient de 78 de ani tratat ca polimialgie reumatică observă reaparția sinovitei pe măsură ce se scade doza de glucocorticoizi. Capitolul descrie acest scenariu ca:',
 ['AR a vârstnicului, care poate imita polimialgia reumatică, sinovita devenind evidentă la reducerea glucocorticoizilor','Artroză nodulară acutizată, fără sinovită demascabilă la scăderea steroizilor','Spondilartrită axială de novo, tipică decadei a opta','Gută tofacee, deoarece PMR exclude AR','O reacție la hidroxiclorochină, nu o formă de AR'],'A',440,'Alte tipuri de prezentare — AR a vârstnicului',
 'Recunoașterea mimetismului PMR la vârstnic, cu demascarea sinovitei la taperingul glucocorticoizilor.',
 ['Fraza despre AR a vârstnicului care imită PMR este explicită.','Cadranul 18.27 listează PMR și acutizarea artrozei printre diagnosticele diferențiale, dar scenariul descris este AR.','AxSpA privește adultul tânăr, nu debutul octogenar tipic PMR.','Guta nu este explicația dată pentru acest mimetism.','Hidroxiclorochina nu este invocată în acest paragraf.']],
 8,'Vigneta cere recunoașterea demascării AR la scăderea steroizilor, nu a PMR „pură” sau a artrozei din același diagnostic diferențial.',['polimialgia reumatică','glucocorticoizi']),

q(47,['Reumatismul palindromic, în datele de prevalență și conversie:',
 ['Este rar (circa 5%) și constă din episoade de 24-48 de ore de monoartrită acută, cu remisiune completă între atacuri','Aproximativ 50% dezvoltă sinovită reumatoidă cronică tipică după luni sau ani; detectarea FR sau ACPA prezice conversia','Este forma cea mai frecventă de AR (peste 70%), cu sinovită continuă între episoade','Conversia la sinovită cronică este infirmată de prezența FR sau ACPA','Atacurile durează 6-12 luni, identic formei tranzitorii'],'AB',441,'Cadranul 18.29 — Reumatism palindromic',
 'Reținerea rarității de 5%, a ferestrei 24-48 de ore și a ratei de conversie de 50% prezise de FR/ACPA.',
 ['Prevalența 5% și durata 24-48 de ore sunt din paragraf.','Rata 50% și valoarea predictivă a FR/ACPA sunt explicite.','Forma palindromică este rară, nu majoritară.','FR/ACPA prezic, nu infirmă, conversia.','6-12 luni definește forma tranzitorie, nu palindromică.']],
 8,'Distractorii confundă palindromicul (ore, 5%) cu forma tranzitorie (<12 luni) și inversează semnificația serologiei.',['5%','24-48 de ore']),

q(48,['Complicațiile AR necontrolate, dincolo de extra-articularul clasic, includ:',
 ['Artrita septică are morbiditate și mortalitate semnificativă; la imunodeprimați, articulațiile afectate pot să nu genereze semnele tipice de inflamație cu febră','AR este cea mai frecventă cauză a amiloidozei de tip AA secundare','Amiloidoza AL provoacă o poliartrită care seamănă cu AR în distribuție și se asociază adesea cu tunel carpian și noduli subcutanați','Amiloidoza AA este cauza majoritară de AR seropozitivă, nu o complicație rară','La imunodeprimați, febra înaltă și semnele locale floride sunt constante, screeningul fiind superfluu'],'ABC',441,'Complicații — Artrita septică; Amiloidoza',
 'Contrastarea artritei septice silențioase a imunodeprimatului cu AA secundară AR versus AL care mimează AR.',
 ['Absența semnelor tipice la imunodeprimați este avertismentul citat.','AR ca cea mai frecventă cauză de AA este explicită.','AL cu tunel carpian și noduli este distincția de diagnostic diferențial.','AA este o complicație rară a AR necontrolate, nu cauza AR.','Textul precizează tocmai că semnele pot lipsi.']],
 8,'Distractorii inversează direcția AA (complicație versus cauză) și anulează silențiozitatea infecției la imunodeprimat.',['amiloidozei de tip AA','imunodeprimaţi']),

q(49,['Inițial, afectarea umărului în AR imită de regulă:',
 ['Tendinoza calotei rotatorilor, cu sindrom de arc dureros și durere în partea superioară a brațelor pe timp de noapte','Instabilitatea atlanto-axială, ca primă manifestare scapulară','Protruzia acetabulară, umărul fiind cruțat până în stadiul terminal','Ruptura extensorilor 4 și 5, prin subluxația stiloidei ulnare','Bursita poplitee, cu chist Baker scapular'],'A',441,'Afectarea articulară — Umerii',
 'Recunoașterea mimetismului de calotă rotatorilor înaintea rigidizării globale și a rupturii de cuff.',
 ['Imitarea tendinozei calotei, arcul dureros și durerea nocturnă sunt fraza de deschidere.','Instabilitatea atlanto-axială privește coloana cervicală.','Protrusio este o leziune de șold.','Ruptura extensorilor 4-5 este o leziune de stiloidă ulnară.','Chistul popliteu privește genunchiul.']],
 8,'Distractorii reciclează leziuni reale din aceleași pagini (C1-C2, protrusio, stiloidă, Baker) atribuite greșit umărului precoce.',['calotei rotatorilor','arc dureros']),

q(50,['Afectarea genunchilor și a șoldurilor în AR constituită se caracterizează prin:',
 ['Sinovita masivă și revărsatul genunchiului răspund bine la aspirație și injecție cu glucocorticoizi; lichidul persistent crește riscul de chist popliteal și ruptură','Eroziunea duce la pierderea spațiului articular pe compartimentele medial, lateral și/sau retropatelar, cu deformare în varus sau valgus și gonartroză secundară','Șoldurile sunt afectate ocazional în AR precoce, dar mai puțin frecvent decât genunchii; osteoporoza juxta-articulară poate permite protrusio acetabulae','Șoldul este sediul cel mai precoce și cel mai frecvent, genunchiul fiind cruțat','Chistul popliteal este o leziune de bursă olecraniană, fără legătură cu genunchiul'],'ABC',442,'Afectarea articulară — Genunchii; Șoldurile',
 'Contrastarea frecvenței genunchi versus șold și recunoașterea chistului popliteal versus protrusio.',
 ['Aspirația, injecția și riscul de chist popliteal sunt enunțate.','Cele trei compartimente și varus/valgus sunt din paragraf.','Frecvența mai mică a șoldului și protrusio sunt explicite.','Relația de frecvență este inversă.','Chistul popliteal este al genunchiului, nu al cotului.']],
 8,'Distractorii inversează ierarhia genunchi/șold și mută chistul Baker pe bursa olecraniană din aceeași secțiune.',['chistului popliteal','protrusio acetabulae']),

q(51,['Manifestările non-articulare de țesut moale și extra-articulare mai puțin acoperite anterior includ:',
 ['Nodulii reumatoizi subcutanați sunt fermi, intradermici, la puncte de presiune (coate, degete, Ahile) la pacienții cu boală erozivă seropozitivă și tind să recidiveze după excizie','Tenosinovita flexorilor poate provoca un deget în resort; tumefierea tecii extensorilor pe fața dorsală a pumnului este frecventă','Sindromul Felty asociază splenomegalie și neutropenie; HLA-DR4 se găsește la 95% dintre acești pacienți, față de 50-75% în AR fără Felty','Sclerita și episclerita apar în boala severă seropozitivă, ca ochi roșii dureroși','Nodulii apar tipic în AR seronegativă non-erozivă și nu recidivează după excizie'],'ABCD',442,'Țesuturi moi; Sindromul Felty; Ochii',
 'Integrarea nodulilor de presiune, a degetului în resort, a HLA-DR4 din Felty (95% vs 50-75%) și a scleritei.',
 ['Sediile de presiune, terenul eroziv seropozitiv și recidiva sunt din paragraf.','Degetul în resort și tenosinovita extensorilor sunt explicite.','Cifrele HLA-DR4 95% versus 50-75% sunt din pagina următoare.','Sclerita/episclerita din boala severă seropozitivă completează extra-articularul.','Nodulii țin de boala erozivă seropozitivă și recidivează.']],
 8,'Patru asocieri reale; distractorul inversează terenul seropozitiv al nodulilor și neagă recidiva post-excizie.',['Nodulii reumatoizi','95%'],[443]),

q(52,['Un pacient cu artrită persistentă a articulațiilor mici ale mâinilor, de 14 săptămâni, ar trebui, potrivit capitolului, trimis urgent la reumatolog deoarece:',
 ['Trimiterea se impune dacă sunt afectate articulațiile mici ale mâinilor sau picioarelor, dacă este afectată mai mult de o articulație sau dacă a existat deja o întârziere de mai mult de 3 luni de la debut','Trimiterea se amână până la eroziuni radiografice, independent de durata simptomelor','Doar monoartrita de șold, sub 2 săptămâni, justifică urgența','Terapia precoce în primele 3 luni reduce șansa remisiunii, deci se așteaptă forma constituită','Taperingul este imposibil dacă remisiunea a fost indusă precoce'],'A',443,'Diagnostic și investigații — Trimiterea urgentă',
 'Reținerea celor trei praguri de trimitere (mâini/picioare, >1 articulație, >3 luni) și a ferestrei de 3 luni pentru remisiune.',
 ['Cele trei condiții de trimitere sunt enumerate explicit; terapia în primele 3 luni crește șansa remisiunii susținute cu tapering ulterior.','Așteptarea eroziunilor contrazice urgența descrisă.','Monoartrita scurtă de șold nu este criteriul de trimitere al paragrafului.','Textul spune că terapia precoce face remisiunea mai probabilă, nu mai puțin.','Taperingul este tocmai obiectivul după remisiune indusă precoce.']],
 8,'Vigneta aplică pragul de 3 luni; distractorii amână trimiterea până la eroziuni, inversând fereastra de remisiune.',['mai mult de 3 luni','primele 3 luni']),

q(53,['În managementul non-farmacologic și simptomatic al AR sunt adevărate:',
 ['Pacienții trebuie ajutați să rămână la locul de muncă, deoarece 30% își pierd locul de muncă în termen de 2 ani de la diagnostic','Cei mai mulți pacienți necesită un AINS pentru durerea nocturnă și redoarea matinală, pe lângă DMARD; dacă efectele digestive sunt pronunțate sau vârsta depășește 65 de ani, se adaugă un inhibitor de pompă de protoni','AINS înlocuiesc DMARD la toți pacienții tineri, IPP fiind inutil după 65 de ani','Pierderea locului de muncă este rară, sub 2% la 10 ani','Paracetamolul este interzis, singurul analgezic permis fiind un opioid de treaptă înaltă'],'AB',444,'Tratamentul AR — Muncă; AINS',
 'Reținerea cifrei de 30% la 2 ani și a regulii AINS plus IPP după 65 de ani sau la toxicitate digestivă.',
 ['Cifra 30% în 2 ani este explicită.','AINS pentru noapte/redoare și IPP la >65 ani sau GI sunt din paragraful despre AINS.','AINS sunt adjuvante, nu înlocuitori de DMARD; IPP se adaugă tocmai după 65 de ani.','30% nu este o raritate.','Textul permite un analgezic simplu (paracetamol sau combinație cu codeină/dihidrocodeină).']],
 8,'Distractorii inversează cifra ocupațională 30%/2 ani și regula IPP după 65 de ani din același capitol de tratament.',['30%','peste 65 de ani']),

q(54,['Glucocorticoizii în AR, dincolo de startul T2T, se caracterizează prin:',
 ['Injecțiile intramusculare de depozit (40-120 mg metilprednisolon) ajută la inducerea remisiunii până acționează csDMARD și la controlul puseelor severe','Osteoporoza se poate dezvolta în 3 luni la doze peste 7,5 mg pe zi; se asociază vitamina D și bifosfonați dacă se anticipează tratament peste 3 luni','Injecțiile intra-articulare cu preparate semicristaline au efect puternic, uneori de scurtă durată','Glucocorticoizii orali pe termen lung sunt de preferat ca monoterapie de fond, fără csDMARD','Osteoporoza glucocorticoidă apare doar după 10 ani, profilaxia fiind inutilă sub 3 luni'],'ABC',444,'Glucocorticoizi; Cadranul 18.31',
 'Reținerea dozei IM 40-120 mg, a pragului 7,5 mg/zi în 3 luni și a locului injecțiilor IA, distinct de monoterapia orală cronică.',
 ['Schema IM de depozit este enunțată.','Pragurile 3 luni și 7,5 mg/zi plus profilaxia sunt din cadran.','Efectul puternic, uneori scurt, al IA este explicit.','Oralele pe termen lung sunt cel mai bine evitate; efectele adverse sunt inevitabile.','Osteoporoza poate apărea în 3 luni, nu după 10 ani.']],
 8,'Distractorii transformă GC orali cronici în fond terapeutic și anulează fereastra de 3 luni/7,5 mg a osteoporozei.',['40-120 mg','7,5 mg'],[445]),

q(55,['Leflunomida, ca csDMARD, se caracterizează prin:',
 ['Blochează dihidro-orotat-dehidrogenaza, împiedicând expansiunea clonală a limfocitelor T; timpul de înjumătățire este lung, 4-28 de zile','Doza este 20 mg pe zi (10 mg dacă diareea este o problemă); debutul acțiunii este după 4 săptămâni, cu îmbunătățiri suplimentare la 2 ani','Timpul de înjumătățire scurt (2 ore) o face preferată la femeile care planifică sarcina','Nu necesită monitorizare de laborator, spre deosebire de metotrexat','Este inactivă la non-responderii la metotrexat, fiind rezervată spondilitei'],'AB',445,'Leflunomidă',
 'Integrarea mecanismului DHODH cu t½ 4-28 de zile și doza 20/10 mg, plus interdicția la planificarea sarcinii.',
 ['Mecanismul și t½ 4-28 de zile sunt din paragraf.','Doza 20 mg (10 mg la diaree) și ferestrele 4 săptămâni/2 ani sunt explicite.','t½ lung face ca leflunomida să fie evitată la femeile care planifică să procreeze.','Monitorizarea (hemogramă, trombocite, biochimie hepatică) este cerută.','Textul o descrie ca eficientă la unii non-responderi la metotrexat.']],
 8,'Distractorii aplică un t½ de 2 ore (cinetica DOAC) asupra leflunomidei, al cărei t½ lung interzice concepția.',['4-28 de zile','20 mg pe zi']),

q(56,['Particularitățile unor blocanți TNF, dincolo de regula „după două csDMARD”, includ:',
 ['Etanerceptul este proteină de fuziune p75–IgG1; circa 65% dintre pacienți răspund bine','Certolizumab pegol este fragment Fab pegilat, fără porțiune Fc, cu transfer minim în placentă și lapte matern','Golimumabul se administrează subcutanat o dată pe lună; există biosimilare pentru etanercept, infliximab și adalimumab','Etanerceptul se administrează doar intravenos lunar, fără răspuns clinic descris','Porțiunea Fc a certolizumabului explică pasajul transplacentar masiv, contraindicând orice sarcină monitorizată'],'ABC',445,'Blocanții TNF-α — Structuri și posologie',
 'Contrastarea etanercept 65%, a absenței Fc la certolizumab (transfer minim) și a golimumabului lunar, plus biosimilarele.',
 ['Structura p75 și rata 65% sunt din listă.','PEG, lipsa Fc și transferul minim sunt explicite.','Posologia lunară și biosimilarele ETN/IFX/ADA sunt enunțate.','Etanerceptul este s.c., cu ~65% răspuns.','Lipsa Fc reduce transferul; textul spune că nu există dovezi convingătoare de efect advers pe sarcină, dar monitorizarea este esențială.']],
 8,'Distractorii inversează calea etanerceptului și atribuie certolizumabului un Fc pe care textul tocmai îl neagă.',['aproximativ 65%','lipsa porţiunii Fc'],[447]),

q(57,['Rituximabul în AR seropozitivă, dincolo de ținta CD20:',
 ['Produce îmbunătățire semnificativă timp de 8 luni până la câțiva ani; limfopenia B durează 6-9 luni, recăderea însoțind adesea revenirea limfocitelor B și creșterea PCR','Aproximativ 80% dintre pacienții FR pozitivi răspund, 50-60% cu control persistent; imunoglobulinele trebuie monitorizate la administrări repetate','Răspunsul este nul la seropozitivi, medicamentul fiind rezervat AR seronegative','Limfopenia B este permanentă și interzice orice readministrare','Imunoglobulinele cresc predictibil, monitorizarea fiind superfluă'],'AB',447,'Alți agenți biologici — Rituximab',
 'Reținerea ferestrei 8 luni–câțiva ani, a limfopeniei B de 6-9 luni și a ratelor 80% / 50-60% la FR pozitivi.',
 ['Durata răspunsului și limfopenia 6-9 luni sunt din paragraf.','80% răspuns și 50-60% control persistent, plus monitorizarea Ig, sunt explicite.','Rituximabul este folosit tocmai în AR seropozitivă.','Readministrarea la recădere este bine tolerată.','Ig pot scădea la administrări repetate, deci se monitorizează.']],
 8,'Distractorii inversează indicația (sero+ versus sero−) și transformă limfopenia reversibilă de 6-9 luni într-una permanentă.',['6-9 luni','80% dintre pacienţii']),

q(58,['Spondilartrita axială și spondilita anchilozantă, în epidemiologie:',
 ['AxSpA apare la 1% din populația generală și afectează articulațiile sacroiliace sau articulațiile fibroase și sinoviale ale coloanei, detectabile pe IRM; termenul SA se folosește când există modificări radiografice sacroiliace','Prevalența SA este circa 0,2-0,5% în Europa de Nord și circa 0,5% în SUA, la adulți tineri, cu raport bărbați:femei 3:1; femeile prezintă boala mai târziu și sunt subdiagnosticate','La albi cu SA, 95% au HLA-B27, față de 8% în majoritatea populațiilor albe; concordanța la gemeni monozigoți B27 ajunge până la 70%, versus 20-25% la dizigoți','Frecvența AxSpA este paralelă cu incidența HLA-B27 (scăzută în Africa și Japonia, ridicată la indienii Haida)','SA este o boală a femeii vârstnice, cu raport femei:bărbați 9:1, independentă de HLA-B27'],'ABCD',448,'Spondilartrita axială — Epidemiologie; Etiologie',
 'Integrarea prevalențelor 1% / 0,2-0,5%, a raportului 3:1 și a HLA-B27 95% versus 8%, plus concordanța gemenilor.',
 ['Definiția AxSpA 1% și distincția radiografică SA sunt din paragraf.','Cifrele europene/SUA și raportul 3:1 sunt explicite.','95% versus 8% și 70% versus 20-25% sunt din etiologia genetică.','Paralela populațională Africa/Japonia versus Haida este enunțată.','Raportul 3:1 este masculin, nu feminin 9:1 (cifră de LES).']],
 8,'Patru trepte epidemiologice; distractorul aplică sex-ratio-ul LES (9:1 feminin) asupra SA, al cărei raport este 3:1 masculin.',['1% din populaţia','3:1']),

q(59,['Criteriile lombalgiei inflamatoare și măsurarea rigidității în AxSpA/SA includ:',
 ['Cadranul 18.35 cere vârstă de debut sub 45 de ani, debut insidios, ameliorare la efort, lipsa ameliorării la repaus și durere nocturnă cu ameliorare la ridicare; 4 din 5 criterii sugerează SA cu sensibilitate de 80%','Testul Schober marchează pielea la 5 cm sub și 10 cm deasupra interliniei crestelor iliace; o creștere sub 5 cm la flexia anterioară implică rigiditate spinală','Uveita anterioară acută apare la circa 30% dintre pacienții cu AxSpA și poate fi manifestarea de prezentare, fiind urgență (durere, fotofobie, vedere încețoșată)','Ameliorarea la repaus și absența durerii nocturne definesc lombalgia inflamatoare','Schober pozitiv înseamnă o creștere peste 15 cm, specifică artrozei'],'ABC',448,'Cadranul 18.35 — Lombalgie inflamatoare; Schober; Uveită',
 'Aplicarea pragului 4/5 criterii (sensibilitate 80%), a pragului Schober <5 cm și a uveitei de 30%.',
 ['Cele cinci criterii și sensibilitatea 80% sunt din cadran.','Marcajele 5/10 cm și pragul <5 cm sunt procedura descrisă.','30% și caracterul de urgență sunt explicite.','Inflamatorul se ameliorează la efort, nu la repaus.','Pragul este o creștere <5 cm, nu >15 cm.']],
 8,'Distractorii inversează ameliorarea efort/repaus și înlocuiesc pragul Schober <5 cm cu o valoare absurd de mare.',['4 dintre cele 5','testul Schober']),

q(60,['În tratamentul spondilitei anchilozante, după eșecul AINS, sunt adevărate:',
 ['Sulfasalazina poate fi utilă pentru artrita periferică, dar nu și pentru afectarea spinală','Blocanții TNF reduc substanțial simptomele spinale și periferice și îmbunătățesc funcția și calitatea vieții, dar nu s-au găsit dovezi convingătoare de reducere a progresiei radiografice în formele vechi; recăderea la întrerupere poate fi întârziată cu luni, permițând tratament intermitent','Sulfasalazina este csDMARD-ul de elecție al coloanei, anti-TNF fiind inutili pe periferic','Anti-TNF opresc convingător progresia radiografică în boala veche, recăderea la stop fiind inexistentă','Exercițiile se evită, cifoza dorsală fiind preventivă'],'AB',449,'Spondilita anchilozantă — Tratament',
 'Contrastarea sulfasalazinei (doar periferic) cu anti-TNF (simptom, nu progresie radiografică convingătoare în boala veche).',
 ['Limita spinală a sulfasalazinei este explicită.','Beneficiul simptomatic fără dovezi convingătoare pe radiografie și recăderea întârziată sunt din pagina următoare.','Relația SSZ–coloană versus periferic este inversată.','Textul neagă dovezile convingătoare de haltare radiografică în formele vechi.','Cheia managementului este tocmai regimul de exerciții înaintea sindesmofitelor.']],
 8,'Distractorii inversează indicația sulfasalazinei (periferic versus spinal) și pretind haltare radiografică pe care textul o slăbește.',['nu şi pentru afectarea spinală','progresiei radiografice'],[450]),

q(61,['Atacul de gută, în tabloul clinic și în investigații (dincolo de epidemiologia 2,5%/3,9%):',
 ['Atacurile netratate durează aproximativ 7 zile; recuperarea se asociază de obicei cu descuamarea pielii adiacente','În 25% din atacuri este afectată o articulație diferită de MTF1; celulita microcristalină face distincția de celulita infecțioasă dificilă','Acidul uric seric este de obicei crescut (>600 µmol/L); dacă nu, se recontrolează la câteva săptămâni, uricemia scăzând imediat după atac','Atacul durează de regulă 24 de ore și nu recade în următorii 10 ani','Uricemia nu scade după atac, deci un AUS normal în plin puseu infirmă guta'],'ABC',453,'Gută — Atacul acut; Investigații',
 'Reținerea duratei de 7 zile, a proporției 25% non-MTF1 și a capcanei AUS scăzut intra-critic, cu recontrol ulterior.',
 ['Cele 7 zile și descuamarea sunt din deschiderea paginii.','25% non-MTF1 și mimetismul de celulită sunt explicite.','Pragul >600 µmol/L și scăderea post-atac sunt din investigații.','Al doilea atac apare probabil în 2 ani, nu după 10 ani fără recădere.','Textul cere recontrol tocmai pentru că uricemia scade imediat după atac.']],
 8,'Distractorii comprimă atacul la 24 de ore și transformă scăderea AUS intra-critică într-un test de excludere.',['7 zile','>600 pmol/L']),

q(62,['La un hipertensiv cu gută, losartanul este menționat în capitol deoarece:',
 ['Este un antagonist al receptorilor angiotensinei I și este uricozuric, putând reduce riscul de gută la pacienții cu sindrom metabolic','Este un inhibitor de xantin-oxidază, înlocuind alopurinolul ca primă linie','Este un analog non-purinic identic febuxostatului, cu metabolizare doar renală','Nu are efect pe urat, fiind evitat în sindromul metabolic','Înlocuiește pegloticaza intravenoasă în guta tofacee refractară'],'A',453,'Losartan; Agenți uricozurici',
 'Identificarea efectului uricozuric al losartanului la hipertensivul cu gută, distinct de xantin-oxidază și uricază.',
 ['Statutul de antagonist AT1 uricozuric și potențialul de a reduce riscul în sindromul metabolic sunt enunțate.','Inhibitorii de xantin-oxidază sunt alopurinolul și febuxostatul.','Febuxostatul este analogul non-purinic hepatic; losartanul nu este din această clasă.','Textul îi atribuie tocmai efect uricozuric.','Pegloticaza este uricază pegilată i.v., rezervată gutei severe refractare.']],
 8,'Distractorii confundă losartanul uricozuric cu xantin-oxidaza sau cu uricaza pegilată din aceleași paragrafe de tratament.',['Losartanul','uricozuric']),

q(63,['Tabloul clinic al LES, în datele de frecvență din figura și textul paginii 458:',
 ['Afectarea articulară este cea mai frecventă manifestare clinică (>90%); articulațiile sunt dureroase dar au aspect clinic adesea normal; rar apare artropatia Jaccoud','Mialgia este prezentă la circa 50%, dar miozita adevărată la mai puțin de 5%; tegumentul este afectat în 85%, cu eritem în fluture și fotosensibilitate la 40-50% (mai ales anti-Ro)','Afectarea pulmonară apare la până la 50% (pleurezii/revărsate adesea bilaterale); inima în 25%; nefrita clinică doar în 30%, deși histologia postmortem este foarte frecventă','Sistemul nervos este interesat în până la 60%; sindromul Sjögren secundar în 15%','Eroziunile osoase sunt regula, identic AR, iar miozita adevărată depășește 50%'],'ABCD',458,'LES — Tablou clinic; Fig. 18.36',
 'Integrarea frecvențelor 90%/50%/<5%/85%/50%/25%/30%/60%/15% și a artropatiei Jaccoud non-erozive.',
 ['>90% articular, aspectul clinic normal și Jaccoud sunt din paragraf.','Mialgie 50% versus miozită <5%, tegument 85% și fotosensibilitate 40-50% sunt explicite.','Pulmonar 50%, cord 25% și nefrită clinică 30% versus histologie frecventă completează spectrul.','60% neurologic și 15% Sjögren secundar sunt din închidere.','Eroziunile sunt rare; miozita adevărată este <5%, nu >50%.']],
 8,'Patru clustere de prevalență; distractorul atribuie LES eroziunile AR și umflă miozita de la <5% la >50%.',['>90%','artropatia Jaccoud']),
];
