import {advancedQuestion as q} from './advanced-author';

export const RHEUMATOLOGY_ADVANCED=[
q('reumatologie',18,-370,'reumatologie-adv-013',[
 'Care corespondență între blocanții TNF-α și structura lor moleculară este corectă?',
 ['Etanercept — anticorp monoclonal IgG1; certolizumab — fragment Fab pegilat; golimumab — proteină de fuziune p75–IgG1','Etanercept — proteină de fuziune p75–IgG1; certolizumab — fragment Fab pegilat fără porțiune Fc; golimumab — anticorp monoclonal IgG1 uman','Etanercept — proteină de fuziune CTLA4–IgG1; certolizumab — fragment Fab pegilat; golimumab — anticorp monoclonal IgG1 uman','Etanercept — proteină de fuziune p75–IgG1; certolizumab — anticorp IgG1 pegilat cu porțiune Fc; golimumab — anticorp monoclonal IgG1 uman','Etanercept — proteină de fuziune p75–IgG1; certolizumab — fragment Fab pegilat fără porțiune Fc; golimumab — fragment Fab uman fără porțiune Fc'],'B',445,'Terapii biologice — Blocanții TNF-α',
 'Diferențierea structurilor moleculare între medicamente care au aceeași țintă.',
 ['Structurile etanerceptului și golimumabului sunt inversate.','Toate cele trei structuri corespund descrierii din bibliografie.','Componenta etanerceptului este receptorul p75; CTLA4 aparține abataceptului.','Certolizumab este fragment Fab și nu conține porțiunea Fc.','Golimumab este anticorp IgG1 uman, nu fragment Fab fără Fc.']],
 [8,'Aceeași țintă pentru toate medicamentele; variantele diferă numai prin domeniul receptorului, fragmentul Fab și prezența Fc.'],
 ['proteină de fuziune','fragment Fab','lipsa porțiunii Fc'],undefined,[447]),
q('reumatologie',18,-370,'reumatologie-adv-001',[
 'Care asociere între moleculele exprimate de fibroblastele sinoviale și rolurile lor în sinovita reumatoidă este corectă?',
 ['VCAM-1 — prevenirea lizei prin complement; DAF — supraviețuirea limfocitelor B; caderina 11 — interacțiuni intercelulare','VCAM-1 — supraviețuirea limfocitelor B; DAF — interacțiuni intercelulare; caderina 11 — prevenirea lizei prin complement','VCAM-1 — supraviețuirea și diferențierea limfocitelor B; DAF — prevenirea lizei prin complement; caderina 11 — interacțiuni intercelulare','VCAM-1 — interacțiuni intercelulare; DAF — supraviețuirea limfocitelor B; caderina 11 — prevenirea lizei prin complement','VCAM-1 — prevenirea lizei prin complement; DAF — interacțiuni intercelulare; caderina 11 — supraviețuirea limfocitelor B'],'C',438,'Artrita reumatoidă — Imunologie',
 'Asocierea fiecărei molecule sinoviale cu funcția descrisă.',
 ['Rolurile VCAM-1 și DAF sunt inversate.','Rolurile DAF și caderinei 11 sunt inversate.','Succesiunea corespunde celor trei funcții din text.','Funcțiile atribuite DAF și caderinei 11 nu corespund; suportul limfocitelor B este atribuit VCAM-1.','Prevenirea lizei revine DAF, iar suportul limfocitelor B revine VCAM-1.']],
 [8,'Toate variantele folosesc aceleași trei molecule și funcții reale; trebuie păstrată corespondența completă.'],
 ['supraviețuirea și diferențierea limfocitelor B','liza celulară indusă de complement','interacțiunile intercelulare']),
q('reumatologie',18,-370,'reumatologie-adv-002',[
 'Care asociere între terapia utilizată în artrita reumatoidă, structura sa și ținta funcțională este corectă?',
 ['Abatacept — proteină de fuziune CTLA4–Fc IgG1, blocarea costimulării limfocitelor T','Etanercept — proteină de fuziune CTLA4–Fc IgG1, neutralizarea TNF-α','Rituximab — anticorp monoclonal anti-CD20, blocarea costimulării limfocitelor T','Tocilizumab — anticorp monoclonal anti-IL-6, blocarea receptorului CD20','Abatacept — proteină de fuziune receptor p75–Fc IgG1, neutralizarea TNF-α'],'A',447,'Alți agenți biologici',
 'Diferențierea proteinelor de fuziune de anticorpii monoclonali și a țintelor acestora.',
 ['Structura și blocarea costimulării sunt descrise pentru abatacept.','Etanercept neutralizează TNF, dar componenta receptorului este p75, nu CTLA4.','Rituximab are ținta CD20, însă efectul descris privește limfocitele B.','Tocilizumab se leagă de receptorul IL-6, nu de CD20.','Structura și ținta din opțiune descriu etanerceptul.']],
 [8,'Diferențierea necesită atât structura moleculei, cât și etapa imunologică țintită; numele clasei nu este suficient.'],
 ['proteină de fuziune recombinantă','blocarea costimulării','receptorului de IL-6'],undefined,[445]),
q('reumatologie',18,-370,'reumatologie-adv-003',[
 'În artrita reumatoidă, care asociere descrie corect leziunea locală și consecința ei funcțională?',
 ['Tenosinovita flexorilor — subluxație dorsală a stiloidei ulnare — ruptura extensorilor degetelor 4 și 5','Subluxația dorsală a stiloidei ulnare — ruptura tendoanelor extensorilor — afectarea degetelor 4 și 5','Subluxația palmară a articulațiilor MCF — ruptura tendoanelor flexorilor — afectarea degetelor 4 și 5','Tenosinovita flexorilor — compresie în tunelul carpian — deformare fixă în hiperextensie a IFP','Subluxația dorsală a stiloidei ulnare — compresie în tunelul carpian — deformare fixă în flexie a IFP'],'B',441,'Afectarea articulară — Articulațiile mâinilor și carpul',
 'Distingerea leziunii tendinoase de neuropatia de compresie și deformarea articulară.',
 ['Textul leagă tenosinovita flexorilor de tunelul carpian; ruptura extensorilor este asociată stiloidei ulnare.','Această succesiune este descrisă pentru tumefacția și subluxația dorsală a stiloidei ulnare.','Subluxația MCF este descrisă împreună cu devierea ulnară; nu este mecanismul rupturii extensorilor.','Tunelul carpian este posibil, dar hiperextensia fixă a IFP este o deformare articulară distinctă.','Sunt reunite mecanisme diferite: leziunea extensorilor, tunelul carpian și deformarea în butonieră.']],
 [8,'Toate elementele provin din afectarea aceleiași regiuni; relația cauzală și tendonul implicat trebuie cunoscute precis.'],
 ['subluxația dorsală a stiloidei ulnare','ruptura tendoanelor extensorilor','degetelor 4 și 5']),
q('reumatologie',18,-370,'reumatologie-adv-004',[
 'În imunopatogenia artritei reumatoide sunt corecte următoarele afirmații:',
 ['Factorii reumatoizi de tip IgM și IgA leagă porțiunea Fc a IgG și pot forma complexe imune în membrana sinovială','Complexele imune stimulează macrofagele prin receptorii Fc IgG și pot amplifica producția de citokine','TNF-α stimulează sinteza IL-6, iar factorii reumatoizi recunosc porțiunea Fab a IgG','Limfocitele B sinoviale produc autoanticorpi, iar DAF susține diferențierea acestor limfocite','Sinoviocitele asemănătoare fibroblastelor produc citokine, iar caderina 11 previne liza prin complement'],'AB',438,'Artrita reumatoidă — Imunologie',
 'Legarea autoanticorpilor de bucla de amplificare și separarea moleculelor de suprafață.',
 ['Ambele clase și ținta Fc sunt descrise.','Această stimulare întreține producția de IL-1, IL-8, TNF și alte citokine.','Inducerea IL-6 este corectă; ținta factorului reumatoid este Fc, nu Fab.','Producția de autoanticorpi este corectă; suportul diferențierii B este atribuit VCAM-1.','Producția de citokine este corectă; protecția față de complement revine DAF.']],
 [8,'Distractorii conservă o afirmație imunologică adevărată și schimbă ținta sau rolul moleculei asociate.'],
 ['porțiunea Fc','complexelor imune în membrana sinovială','sinoviocite asemănătoare fibroblastelor']),
q('reumatologie',18,-370,'reumatologie-adv-005',[
 'Care asocieri privind afectarea extraarticulară în artrita reumatoidă corespund bibliografiei?',
 ['Mononevrită multiplex — vasculită a vasa nervorum; sindrom de tunel carpian — neuropatie de compresie prin sinovită','Proteinurie cu amiloidoză secundară — depunere AL; poliartrită care mimează AR — depunere AA','Noduli pulmonari cu pneumoconioză — sindrom Caplan; splenomegalie cu neutropenie — sindrom Felty','Neuropatie periferică simetrică — subluxație atlanto-axială; compresie medulară — vasculită a vasa nervorum','Boală inflamatorie activă — trombocitopenie reactivă; hipersplenism în sindrom Felty — trombocitoză'],'AC',443,'Manifestări extraarticulare; Sistemul nervos; Rinichi; Sânge',
 'Compararea mecanismelor neurologice, tipurilor de amiloid și sindroamelor sistemice.',
 ['Ambele mecanisme sunt enumerate în afectarea neurologică.','Tipurile sunt inversate: AA este amiloidoza secundară AR, iar AL poate mima distribuția poliartritei.','Ambele asocieri sunt descrise.','Compresia medulară ține de subluxația atlanto-axială; vasculita produce neuropatiile periferice descrise.','Boala activă poate produce trombocitoză, iar hipersplenismul poate produce pancitopenie.']],
 [8,'Sunt cerute perechi complete de asocieri apropiate; distractorii permută mecanisme și tipuri de afectare care apar toate în capitol.'],
 ['vasculitei vasa nervorum','pneumoconioză','splenomegalie și neutropenie'],undefined,[441]),
q('reumatologie',18,-370,'reumatologie-adv-006',[
 'Despre medicamentele antireumatice modificatoare de boală descrise în bibliografie sunt corecte afirmațiile:',
 ['Leflunomida blochează dihidro-orotat-dehidrogenaza și împiedică expansiunea clonală a limfocitelor T','Abatacept blochează costimularea limfocitelor T prin inhibarea sintezei pirimidinelor','Rituximab țintește CD20 de pe limfocitele pre-B și B mature; administrările repetate pot scădea imunoglobulinele','Tocilizumab și sarilumab sunt anticorpi împotriva receptorului IL-6','Tofacitinib și baricitinib sunt inhibitori JAK administrați oral, încadrați ca DMARD biologice'],'ACD',447,'Alți agenți biologici; DMARD sintetice țintite',
 'Separarea țintei, structurii și clasei terapiilor cu efecte imune apropiate.',
 ['Acesta este mecanismul leflunomidei descris la p. 445.','Blocarea costimulării este corectă; inhibarea sintezei pirimidinelor aparține leflunomidei.','Ținta și motivul monitorizării imunoglobulinelor sunt descrise pentru rituximab.','Ambele medicamente țintesc receptorul IL-6.','Ținta și calea sunt corecte; încadrarea este DMARD sintetice țintite, nu biologice.']],
 [8,'Fiecare distractor păstrează ținta sau efectul corect și greșește un atribut apropiat: mecanismul intermediar ori clasificarea.'],
 ['expansiunea clonală a limfocitelor T','limfocitele pre-B','DMARD sintetice țintite'],undefined,[445]),
q('reumatologie',18,-370,'reumatologie-adv-007',[
 'La pierderea răspunsului la blocanții TNF-α în artrita reumatoidă, bibliografia descrie următoarele:',
 ['Concentrație terapeutică de medicament — preferință pentru un preparat non-anti-TNF-α','Concentrație subterapeutică — investigarea non-complianței sau a anticorpilor anti-medicament neutralizanți','Anticorpi anti-medicament neutralizanți — argument pentru excluderea non-complianței ca altă explicație posibilă a nivelului scăzut','Concentrație subterapeutică — posibilitatea trecerii la alt blocant TNF-α sau la altă clasă de bDMARD','Concentrație terapeutică — dovadă a neutralizării medicamentului, cu preferință pentru repetarea aceleiași clase'],'ABD',447,'Schimbarea terapiilor DMARD și taperingul',
 'Interpretarea nivelului de medicament în eșecul secundar fără confundarea farmacocineticii cu ținta terapeutică.',
 ['Aceasta este preferința formulată pentru un nivel terapeutic la pierderea răspunsului.','Textul menționează ambele explicații pentru nivelul subterapeutic.','Identificarea unei explicații nu exclude non-complianța asociată; textul nu stabilește o asemenea excludere.','Ambele alternative sunt descrise pentru acest context.','Nivelul terapeutic nu dovedește neutralizarea; textul preferă un preparat non-anti-TNF.']],
 [8,'Se schimbă conduita după concentrația medicamentului, iar opțiunile disting eșecul de țintă de expunerea insuficientă.'],
 ['non-responderi secundari','anticorpilor anti-medicament','nivelul de medicament este terapeutic']),
q('reumatologie',18,-370,'reumatologie-adv-008',[
 'În spondilartrita axială sunt corecte următoarele relații patogenice și anatomice:',
 ['Prezentarea peptidului de către HLA-B27 — participarea limfocitelor T CD8+','Entezita — eroziune la inserția ligamentelor, urmată de formare de os nou sub formă de sindesmofite','Afectarea articulațiilor costovertebrale — reducerea măsurabilă a expansiunii toracelui','Plierea necorespunzătoare HLA-B27 — producere de IL-23 și răspuns al limfocitelor T rezidente în enteze','Formarea sindesmofitelor — depunere de os nou în centrul cartilajului articular, după sinovită fără afectarea inserțiilor ligamentare'],'ABCD',448,'Spondilita anchilozantă — Etiologie; Tablou clinic',
 'Integrarea prezentării antigenice cu sediul inflamației și repararea osoasă.',
 ['Aceasta este calea propusă în ipoteza peptidului artritogenic din text.','Eroziunea la inserție se vindecă prin formare osoasă.','Expansiunea toracică redusă este legată de aceste articulații.','Este una dintre căile patogenice prezentate.','Textul localizează procesul la inserțiile ligamentare; alternativa transferă sediul în cartilaj.']],
 [8,'Cere conexiunea exactă între mecanismul imun, enteză, reparare și anatomie; alternativa eronată păstrează osteogeneza, dar schimbă sediul.'],
 ['limfocitelor T CD8+','inserției ligamentelor','formarea de os nou']),
q('reumatologie',18,-370,'reumatologie-adv-009',[
 'Despre formele clinice ale artritei psoriazice sunt corecte afirmațiile:',
 ['Artrita interfalangiană distală se poate asocia cu distrofie unghială prin entezită extinsă la rădăcina unghiei','Dactilita reprezintă tumefierea unui deget întreg, cu afectare articulară și a tecii tendonului','Forma mutilantă produce scurtarea degetelor prin fibroză capsulară, cu păstrarea lungimii osoase','Aspectul de toc în călimară este legat în descriere de eroziunile centrale și osteoliză','Poliartrita începe frecvent asimetric, iar trecerea la simetrie o reîncadrează în artrită reumatoidă'],'ABD',450,'Artrita psoriazică — Tablou clinic',
 'Diferențierea mecanismelor deformărilor și a distribuției care poate mima AR.',
 ['Această continuitate anatomică este descrisă.','Nu este o tumefacție limitată la o singură articulație.','Forma mutilantă produce osteoliză periarticulară și scurtare osoasă.','Textul și figura leagă aspectul de eroziunea centrală și osteoliză.','Poliartrita psoriazică poate deveni simetrică și greu de distins clinic de AR; simetria nu schimbă singură diagnosticul.']],
 [8,'Distractorii păstrează manifestarea recognoscibilă, dar schimbă mecanismul deformării ori interpretarea distribuției.'],
 ['entezita care se extinde în rădăcina unghiilor','degete telescopate','toc în călimară']),
q('reumatologie',18,-370,'reumatologie-adv-010',[
 'În artrita reactivă, care asocieri clinice și cutaneo-mucoase sunt corecte?',
 ['Balanită circinată la bărbat necircumcis — ulcerații superficiale nedureroase ale glandului','Balanită circinată la bărbat circumcis — leziune proeminentă, eritematoasă și scuamoasă','Keratoderma blennorragică — plăci și pustule similare histologic psoriazisului pustular','Uveită anterioară în boala severă sau recurentă — evoluție sincronă cu artrita','Entezită — fasciită plantară sau afectarea tendonului lui Ahile'],'ABCE',451,'Artrita reactivă — Tablou clinic',
 'Distingerea aspectului leziunilor după context și a relației temporale oculo-articulare.',
 ['Acesta este aspectul descris la bărbatul necircumcis.','Acesta este aspectul descris după circumcizie.','Asemănarea histologică este precizată în text.','Uveita poate complica boala severă sau recurentă, dar nu este sincronă cu artrita.','Ambele localizări sunt descrise pentru entezită.']],
 [8,'Cere distincția morfologică dependentă de circumcizie și independența evoluției oculare, dincolo de triada uzuală.'],
 ['ulcerații superficiale nedureroase','eritematoasă și scuamoasă','nu este sincronă cu artrita']),
q('reumatologie',18,-370,'reumatologie-adv-011',[
 'Privind terapiile țintite menționate pentru artrita psoriazică, sunt corecte asocierile:',
 ['Secukinumab și ixekizumab — inhibitori de IL-17','Ustekinumab — inhibitor al receptorului IL-6','Apremilast — inhibitor oral al PDE4','Tofacitinib — inhibitor oral JAK','Golimumab — proteină de fuziune cu receptorul p75 pentru TNF'],'ACD',450,'Artrita psoriazică — Tratament și prognostic',
 'Diferențierea țintelor biologice de enzimele intracelulare și a structurii anti-TNF.',
 ['Ambele sunt încadrate ca inhibitori IL-17.','Ustekinumab țintește IL-12/23; receptorul IL-6 este ținta tocilizumabului și sarilumabului.','Apremilast este inhibitor PDE4.','Tofacitinib este inhibitor JAK.','Golimumab este anticorp monoclonal; proteina de fuziune p75 este etanerceptul.']],
 [8,'Toate variantele sunt terapii reale pentru boli inflamatorii apropiate; două schimbă o țintă sau structură din aceeași familie terapeutică.'],
 ['inhibitori de IL-17','inhibitor oral al PDE4','inhibitor JAK'],undefined,[445,447]),
q('reumatologie',18,-370,'reumatologie-adv-012',[
 'În formele clinice ale artritei reumatoide descrise în bibliografie sunt corecte asocierile:',
 ['Reumatism palindromic — episoade monoarticulare de 24–48 de ore, cu remisiune completă între atacuri','Formă tranzitorie — durată sub 12 luni, fără afectare articulară permanentă','Formă remisivă — activitate de câțiva ani, apoi remisiune cu leziuni minime','Formă cronică persistentă — evoluție recidivantă și remitentă, posibilă atât cu FR IgM pozitivi, cât și negativi','Formă rapid progresivă — leziuni articulare severe și invaliditate, de obicei în absența FR și ACPA'],'ABCD',441,'Cadranul 18.29 — Tipuri de afectare clinică în AR',
 'Distingerea formelor evolutive după durată, sechele și serologie.',
 ['Aceste episoade pot preceda sinovita cronică, dar se remit complet între atacuri.','Aceasta este definiția formei tranzitorii din tabel.','Această evoluție definește forma remisivă.','Seronegativitatea nu exclude forma cronică persistentă.','Primele elemente sunt corecte; forma rapid progresivă este de obicei FR și ACPA pozitivă.']],
 [7,'Tiparele sunt apropiate, dar seronegativitatea formei rapid progresive este unicul distractor și rămâne prea previzibil; versiune nepublicată.'],
 ['tranzitorie','remisivă','cronică, persistentă']),
];
