import {rewriter} from './rewrite-author';
import {RETIRED_SEPSIS} from './retired/sepsis';

// Rewritten after the 2026-09-24 cue audit (Kumar, cap. 8, p. 151–168).
const q=rewriter(RETIRED_SEPSIS,(p:number)=>p-146,{shuffle:true});

export const SEPSIS_V2=[
q('sepsis-adv-011',['Conform capitolului, sepsisul:',
 ['afectează anual aproximativ 49 de milioane de oameni','provoacă anual aproximativ 11 milioane de decese','impune antibioterapie empirică în primele 6 ore de la prezentare','se abordează prin pachetul de îngrijiri Sepsis Six','impune revizuirea antibioterapiei la 7 zile'],'ABD',151,'Introducere',
 'Fixarea datelor epidemiologice și a ferestrelor terapeutice din sepsis.',
 ['Se estimează 49 de milioane de cazuri anual.','Se estimează 11 milioane de decese anual.','Antibioterapia empirică trebuie prescrisă în interval de o oră.','Abordarea se bazează pe pachetul Sepsis Six.','Antibioterapia se revizuiește la 72 de ore.']],
 [8,'Ferestrele de timp sunt deplasate în distractori.'],['49 de milioane','Sepsis Six']),

q('sepsis-adv-056',['Conform Cadranului 8.1, localizarea simptomelor orientează spre sediul infecției astfel:',
 ['tusea, sputa și dispneea – torace','disuria și durerea în flancuri – tract urinar','cefaleea și meningismul – sistem nervos central','icterul și durerea în abdomenul superior – tegumente','semnele de celulită – tract biliar'],'ABC',152,'Cadranul 8.1 — Caracteristici anamnestice',
 'Asocierea simptomelor cu sediul infecției.',
 ['Tusea, sputa și dispneea orientează spre torace.','Disuria, incontinența și durerea în flancuri orientează spre tractul urinar.','Cefaleea și meningismul orientează spre SNC.','Icterul și durerea în abdomenul superior orientează spre tractul biliar.','Semnele de celulită orientează spre tegumente și țesuturi moi.']],
 [8,'Distractorii inversează sistemele pentru simptome reale.'],['meningism','durere în flancuri']),

q('sepsis-adv-057',['Conform Fig. 8.1, criteriile de disfuncție de organ care susțin suspiciunea de sepsis includ:',
 ['creatinina serică >170 µmol/L','INR >1,5','trombocite <150 × 10⁹/L','lactat seric >2,0 mmol/L','bilirubina >17 µmol/L'],'ABD',152,'Fig. 8.1 — Abordarea pacientului cu suspiciune de sepsis',
 'Aplicarea pragurilor de disfuncție de organ din algoritmul de sepsis.',
 ['Creatinina >170 µmol/L este criteriu.','INR >1,5 este criteriu.','Pragul pentru trombocite este <100 × 10⁹/L.','Lactatul >2,0 mmol/L este criteriu.','Pragul pentru bilirubină este ≥32 µmol/L.']],
 [8,'Distractorii folosesc praguri apropiate, dar mai puțin severe decât cele din figură.'],['Trombocite','170 µmol']),

q('sepsis-adv-041',['La examenul obiectiv al pacientului cu sepsis:',
 ['tahipneea este un semn-cheie al deteriorării clinice','hipoxia poate sugera infecția tractului respirator inferior','pulsul poate fi amplu, prin vasodilatație','somnolența și confuzia sunt semne rare de sepsis la vârstnici','presiunea venoasă jugulară este de obicei crescută'],'ABC',153,'Examenul obiectiv',
 'Interpretarea semnelor vitale și generale în sepsis.',
 ['Tahipneea este semnul-cheie al deteriorării.','Hipoxia poate sugera o infecție respiratorie inferioară.','Pulsul poate fi amplu prin vasodilatație sau de volum mic prin hipovolemie relativă.','Somnolența și confuzia sunt semne frecvente de sepsis la vârstnici.','PVJ poate fi redusă în deshidratare sau depleție volemică.']],
 [8,'Distractorii inversează frecvența confuziei și direcția PVJ.'],['Tahipnee','amplitudine mare']),

q('sepsis-adv-063',['La pacientul cu sepsis fără focar evident, examenul obiectiv poate orienta astfel:',
 ['sensibilitatea spinală localizată – discită sau abces spinal','sensibilitatea în flancul stâng – diverticulită','un suflu nou sau modificat – endocardită infecțioasă','sensibilitatea în cadranul superior drept – apendicită','tampoanele vaginale uitate – boală inflamatorie pelvină'],'ABC',153,'Examenul obiectiv — Sedii și semne de infecție',
 'Corelarea semnelor locale cu sediul probabil al infecției.',
 ['Sensibilitatea spinală localizată poate indica discită sau abces spinal.','Sensibilitatea în flancul stâng este comună în diverticulită.','Un suflu nou sau modificat poate indica endocardita.','Cadranul superior drept orientează spre sepsis biliar.','Tampoanele uitate pot provoca sindromul șocului toxic.']],
 [8,'Distractorii asociază semne reale cu sedii vecine greșite.'],['discită','diverticulită']),

q('sepsis-adv-037',['În fiziopatologia sepsisului:',
 ['PAMP activează imunitatea înnăscută prin receptori Toll-like','citokinele implicate includ TNF-α, IL-1 și IL-6','capcanele neutrofile extracelulare (NETs) contribuie la imunotromboză','răspunsul se limitează la limfocitele T citotoxice','imunotromboza previne coagularea intravasculară diseminată'],'ABC',154,'Fiziopatologie',
 'Recunoașterea verigilor răspunsului înnăscut în sepsis.',
 ['PAMP activează imunitatea înnăscută prin receptori Toll-like, lectină tip C, NOD-like și RIG-I.','Sunt produse TNF-α, IL-1 și IL-6.','Microparticulele și NETs determină imunotromboza.','Răspunsul descris este al imunității înnăscute.','Imunotromboza difuză și complementul provoacă CID.']],
 [8,'Distractorii inversează tipul de imunitate și efectul imunotrombozei.'],['receptori Toll-like','imunotromboză']),

q('sepsis-adv-038',['Disfuncția de organ în sepsis se caracterizează prin:',
 ['creșterea rezistenței periferice totale prin vasoconstricție','edem tisular prin extravazare capilară, cu scăderea livrării de oxigen','translocare bacteriană prin lezarea epiteliului intestinal','afectare renală acută frecventă, asociată cu mortalitate crescută','efect inotrop pozitiv al acidozei asociate'],'BCD',154,'Fiziopatologie — Disfuncția de organ',
 'Recunoașterea mecanismelor disfuncției multiple de organ.',
 ['Vasoplegia reduce rezistența periferică totală.','Extravazarea capilară produce edem care reduce livrarea de oxigen.','Lezarea epiteliului intestinal produce malabsorbție și translocare bacteriană.','Afectarea renală acută este frecventă și crește mortalitatea.','Sindromul și acidoza pot fi inotrop negative.']],
 [8,'Distractorii inversează direcția efectelor hemodinamice.'],['Vasoplegia','translocarea']),

q('sepsis-adv-012',['Conform consensului Sepsis-3, sepsisul este definit ca:',
 ['sindrom de răspuns inflamator sistemic (SIRS) de cauză infecțioasă','infecție confirmată prin hemoculturi pozitive repetate','disfuncție de organ prin răspuns anormal al gazdei la infecție','infecție cu scor qSOFA de cel puțin 2 puncte la triaj','infecție cu lactat seric persistent peste 2 mmol/L'],'C',154,'Definiția (consensul Sepsis-3)',
 'Enunțarea definiției Sepsis-3 și separarea ei de criterii de risc.',
 ['SIRS nu mai este folosit pentru definirea sepsisului.','Hemoculturile nu sunt criteriu de definiție.','Sepsis-3: disfuncție de organ amenințătoare de viață provocată de un răspuns anormal al gazdei la infecție.','qSOFA indică doar risc ridicat, nu diagnostic.','Lactatul >2 mmol/L este un criteriu al șocului septic, alături de vasopresor.']],
 [8,'Distractorii sunt definiția veche și criterii reale ale altor concepte.'],['răspuns anormal al gazdei','Sepsis-3']),

q('sepsis-adv-036',['Scorul qSOFA este pozitiv dacă se întrunesc minim două dintre:',
 ['Glasgow <15, FR ≥22/min, TA sistolică ≤100 mmHg','Glasgow <13, FR ≥25/min, TA sistolică ≤90 mmHg','febră >38°C, leucocitoză >12.000/mm³, tahicardie >90/min','lactat >2 mmol/L, TA medie <65 mmHg, diureză redusă','Glasgow <15, FR ≥22/min, TA medie ≤65 mmHg'],'A',154,'Definiția — qSOFA',
 'Fixarea celor trei criterii qSOFA și a pragurilor lor.',
 ['qSOFA: GCS <15, FR ≥22/min, TAS ≤100 mmHg.','Pragurile sunt deplasate (FR 25 și TAS 90 sunt criterii NICE de risc înalt).','Acestea sunt criterii de tip SIRS, abandonate.','Aceste elemente țin de șocul septic și de disfuncția de organ.','Criteriul tensional este TA sistolică ≤100 mmHg, nu TA medie.']],
 [8,'Toate variantele folosesc praguri reale din capitol, combinate diferit.'],['qSOFA','22 respiraţii']),

q('sepsis-adv-013',['În recunoașterea riscului de sepsis:',
 ['Colegiul Regal al Medicilor recomandă screening la NEWS 2 ≥5','qSOFA și NEWS 2 nu au rol diagnostic pentru sepsis','lactatul ridicat indică insuficiență organică chiar la pacientul aparent stabil','diagnosticul se amână până la rezultatele de laborator','biomarkerii actuali au specificitate suficientă pentru diagnostic'],'ABC',154,'Definiția — NEWS 2 și lactatul',
 'Folosirea corectă a scorurilor de risc și a lactatului.',
 ['NEWS 2 ≥5 este pragul de screening recomandat în Marea Britanie.','qSOFA și NEWS 2 indică doar risc ridicat, nu diagnostic.','Lactatul crescut nu trebuie ignorat, chiar dacă pacientul pare să evolueze bine.','Așteptarea rezultatelor de laborator este contraproductivă.','Niciun biomarker nu are specificitate suficientă.']],
 [8,'Distractorii contrazic caracterul clinic și rapid al diagnosticului.'],['NEWS 2','valoare prognostică'],[155]),

q('sepsis-adv-039',['Clinic, șocul septic este definit, după resuscitare volemică adecvată, prin:',
 ['TA sistolică <90 mmHg și lactat >4 mmol/L','nevoia de vasopresor pentru TA medie ≥65 mmHg și lactat >2 mmol/L','qSOFA ≥2 și lactat >2 mmol/L','nevoia de vasopresor pentru TA medie ≥70 mmHg, independent de lactat','TA medie <65 mmHg și diureză <0,5 ml/kg/oră'],'B',154,'Șocul septic',
 'Aplicarea criteriilor clinice ale șocului septic.',
 ['Nu sunt criteriile Sepsis-3.','Șocul septic: vasopresor pentru TAM ≥65 mmHg și lactat >2 mmol/L, după resuscitare volemică adecvată.','qSOFA nu definește șocul septic.','Pragul de TAM este 65 mmHg și lactatul este obligatoriu în definiție.','Sunt criterii de disfuncție de organ, nu definiția șocului.']],
 [8,'Distractorii combină praguri reale ale altor definiții.'],['vasopresor','>2 mmol']),

q('sepsis-adv-014',['Grupele cu risc crescut de a dezvolta sepsis includ:',
 ['vârstnicii peste 65 de ani și nou-născuții','pacienții cu sepsis în antecedente','femeile însărcinate','adulții tineri fără comorbidități','pacienții cu asplenism sau ciroză'],'ABCE',155,'Recunoașterea sepsisului — Grupele aflate la risc',
 'Enumerarea grupelor cu risc crescut de sepsis.',
 ['Vârstnicii și nou-născuții sunt la risc.','Sepsisul în antecedente crește riscul.','Gravidele sunt listate.','Adulții tineri sănătoși nu sunt un grup de risc citat.','Asplenismul și ciroza sunt afecțiuni imunosupresoare listate.']],
 [8,'Singurul distractor este populația fără factor de gazdă.'],['nou-născuţi','asplenism']),

q('sepsis-adv-042',['În supravegherea intraspitalicească a pacientului care se deteriorează:',
 ['stopul cardiac este de obicei precedat de alterări fiziologice progresive','semnele clinice pot prima față de scorurile numerice','nu există un test binar pentru sepsis','diagnosticul se bazează pe observații clinice și teste la patul bolnavului','lactatul măsurat la patul bolnavului nu are valoare prognostică'],'ABCD',155,'Supravegherea intraspitalicească',
 'Recunoașterea principiilor de detectare precoce a deteriorării.',
 ['Stopul cardiac este de obicei precedat de alterări reflectate de NEWS 2.','Semnele clinice primează față de scorurile numerice.','Nu există un test binar pentru sepsis.','Diagnosticul se pune pe observații clinice și teste POC, fără a aștepta laboratorul.','Lactatul are valoare prognostică.']],
 [8,'Singurul distractor neagă valoarea prognostică a lactatului.'],['test binar','SBAR']),

q('sepsis-adv-040',['Referitor la originea sepsisului:',
 ['sepsisul comunitar se instalează în primele 48 de ore de la internare','sepsisul dobândit în spital se instalează după peste 48 de ore','sepsisul asociat asistenței medicale include pacienții externați în ultimele 30 de zile','pacienții hemodializați au sepsis dobândit strict comunitar','sepsisul asociat asistenței medicale include rezidenții comunităților închise'],'ABC',155,'Originea sepsisului',
 'Clasificarea sepsisului după momentul și contextul instalării.',
 ['Comunitar: primele 48 de ore de la internare.','Dobândit în spital: după peste 48 de ore.','Asociat asistenței medicale: externare în ultimele 30 de zile, îngrijiri cronice, tratament ambulator.','Hemodializa este un exemplu de sepsis asociat asistenței medicale.','Locuitorii comunităților închise sunt excluși.']],
 [8,'Distractorii inversează două excepții explicite ale definiției.'],['48 de ore','30 de zile']),

q('sepsis-adv-002',['Comparativ cu infecțiile nosocomiale, cele dobândite comunitar sunt produse de microorganisme:',
 ['mai puțin virulente, dar multirezistente','virulente, dar de regulă sensibile','mai puțin virulente și mai sensibile la antibiotice','virulente și multirezistente','cu virulență și rezistență similare'],'B',155,'Originea sepsisului — Comunitar versus nosocomial',
 'Diferențierea profilului de virulență și rezistență comunitar/nosocomial.',
 ['Acesta este profilul nosocomial.','Patogenii comunitari sunt virulenți, dar mai degrabă sensibili.','Nu este profilul citat.','Nu este profilul citat.','Textul descrie profiluri diferite.']],
 [8,'Toate combinațiile de virulență/rezistență sunt prezente; doar una corespunde.'],['virulente dar mai degrabă sensibile','Stenotrophomonas']),

q('sepsis-adv-003',['Conform Cadranului 8.3 (NICE), sunt criterii de risc înalt la adultul cu suspiciune de sepsis:',
 ['alura ventriculară de 91–130 bătăi/min','frecvența respiratorie ≥25 respirații/min','TA sistolică ≤90 mmHg','absența diurezei în ultimele 18 ore','temperatura timpanică <36°C'],'BCD',156,'Cadranul 8.3 — Stratificarea riscului',
 'Separarea criteriilor de risc înalt de cele de risc moderat.',
 ['Alura de 91–130/min este criteriu de risc moderat spre crescut.','FR ≥25/min este criteriu de risc înalt.','TAS ≤90 mmHg (sau >40 mmHg sub normal) este criteriu de risc înalt.','Absența diurezei în 18 ore este criteriu de risc înalt.','Temperatura timpanică <36°C este criteriu de risc moderat spre crescut.']],
 [8,'Distractorii sunt criterii reale, din coloana de risc moderat.'],['25 respiraţii','18 ore']),

q('sepsis-adv-060',['Tabloul clinic al sepsisului:',
 ['nu include simptome patognomonice','poate evolua abrupt, în câteva ore, spre disfuncție multiplă de organ','poate avea puține semne inflamatorii la imunodeprimați','se recunoaște sigur prin febra intermitentă','exclude oliguria în fazele precoce'],'ABC',156,'Tablou clinic',
 'Recunoașterea variabilității tabloului clinic al sepsisului.',
 ['Nu există simptome patognomonice.','Unii pacienți se deteriorează abrupt, în câteva ore.','Imunodeprimații pot avea puține semne de inflamație.','Nu există un semn patognomonic.','Oliguria este un semn sistemic de disfuncție de organ.']],
 [8,'Distractorii impun un semn patognomonic inexistent.'],['patognomonice','imunodeprimaţi']),

q('sepsis-adv-001',['La pacientul febril întors dintr-o zonă endemică:',
 ['febra hemoragică virală se ia în calcul dacă febra apare în primele 21 de zile','MERS-CoV se ia în calcul la simptome respiratorii în primele 14 zile','investigațiile minime includ hemoculturi și screeningul malariei','profilaxia malariei exclude diagnosticul de malarie','MERS-CoV se ia în calcul la febră apărută în primele 21 de zile'],'ABC',156,'Sepsisul în situații speciale — Pacienții întorși din călătorii',
 'Aplicarea ferestrelor temporale pentru infecțiile de import.',
 ['Febra hemoragică virală: febră în primele 21 de zile.','MERS-CoV: simptome respiratorii în primele 14 zile.','Investigațiile minime includ hemoculturi și screeningul malariei.','Profilaxia trebuie documentată, dar nu exclude malaria.','Fereastra MERS-CoV este de 14 zile, pentru simptome respiratorii.']],
 [8,'Ferestrele de 14 și 21 de zile sunt permutate.'],['21 de zile','MERS-CoV']),

q('sepsis-adv-055',['La utilizatorii de droguri injectabile cu sepsis:',
 ['majoritatea episoadelor țin de tromboflebite sau abcese locale','patogenii frecvenți sunt S. aureus și S. pyogenes','infecția tricuspidiană poate da abcese pulmonare multiple','patogenul dominant este Pseudomonas aeruginosa de mediu','endoftalmita fungică este o complicație frecventă a sepsisului'],'ABC',156,'Sepsisul în situații speciale — Dependenții de droguri injectabile',
 'Recunoașterea focarelor și patogenilor tipici la utilizatorii de droguri i.v.',
 ['Majoritatea episoadelor sunt legate de tromboflebite sau abcese locale.','S. aureus (MSSA/MRSA) și S. pyogenes sunt cei mai frecvenți.','Endocardita tricuspidiană produce embolii pulmonare cu abcese multiple.','Pseudomonas nu este citat ca patogen dominant.','Endoftalmita fungică apare rar, legată de sucul de lămâie.']],
 [8,'Distractorii transformă o raritate în regulă.'],['tromboflebite','valva tricus']),

q('sepsis-adv-016',['La pacienții neutropenici și la cei imobilizați cu sepsis:',
 ['empiricul neutropenicului cuprinde piperacilină/tazobactam, ± aminoglicozid','riscul de bacil piocianic motivează schema empirică a neutropenicului','la imobilizați, cel mai mare risc îl reprezintă dispozitivele medicale','empiricul neutropenicului se limitează la un glicopeptid','escarele nu pot fi prevenite prin rotirea pacientului'],'ABC',157,'Sepsisul în situații speciale — Neutropenici și imobilizați',
 'Alegerea empiricului la neutropenic și sursele de risc la imobilizat.',
 ['Empiricul cuprinde piperacilină/tazobactam, cu sau fără aminoglicozid.','Riscul de Pseudomonas motivează această schemă.','Cateterele venoase centrale, urinare și sondele endotraheale reprezintă cel mai mare risc.','Glicopeptidul nu acoperă Pseudomonas.','Escarele se previn cu saltele potrivite și rotire periodică.']],
 [8,'Distractorii omit acoperirea antipseudomonas.'],['piocianic','rotirea periodică']),

q('sepsis-adv-015',['La un pacient cu leziune a măduvei spinării, o infecție situată sub nivelul leziunii se manifestă de regulă prin:',
 ['semne inflamatorii locale intense','semne și simptome de disautonomie','meningism și redoare de ceafă','febră înaltă cu frisoane','durere localizată la nivelul focarului'],'B',157,'Sepsisul în situații speciale — Leziunile medulare',
 'Recunoașterea prezentării atipice a infecției la pacientul medular.',
 ['Semnele locale sunt atenuate sub nivelul leziunii.','Infecția sub nivelul leziunii se manifestă prin disautonomie.','Meningismul nu este prezentarea citată.','Nu este prezentarea citată.','Durerea nu este percepută sub nivelul leziunii.']],
 [8,'Distractorii sunt manifestările tipice ale infecției la pacientul fără leziune medulară.'],['disautonomie','măduvei spinării']),

q('sepsis-adv-017',['Pachetul Sepsis Six (Cadranul 8.4) include:',
 ['oxigen pentru SpO₂ >94%','recoltarea hemoculturilor','măsurarea lactatului','vasopresorul ca primă măsură','monitorizarea orară a diurezei'],'ABCE',157,'Cadranul 8.4 — Sepsis Six',
 'Enumerarea componentelor pachetului Sepsis Six.',
 ['Oxigen pentru SpO₂ >94%.','Hemoculturile sunt a doua componentă.','Măsurarea lactatului este inclusă.','Vasopresorul nu face parte din Sepsis Six; lichidele se administrează rapid.','Diureza și bilanțul hidric se monitorizează orar.']],
 [8,'Singurul distractor este o măsură reală din tratamentul șocului, dar nu din pachet.'],['Sp02 >94%','lactatului']),

q('sepsis-adv-044',['Resuscitarea volemică timpurie în sepsis, conform capitolului:',
 ['SSC recomandă cel puțin 30 ml/kg cristaloide în primele 3 ore','cristaloidele sunt fluidul de primă intenție','soluțiile de hidroxietil amidon sunt recomandate','două studii din țări cu venituri mici au arătat creșterea mortalității','resuscitarea în bolus aduce beneficiu tuturor pacienților'],'ABD',157,'Tratamentul sepsisului — Resuscitarea volemică',
 'Aplicarea recomandărilor și a limitelor resuscitării volemice.',
 ['SSC: cel puțin 30 ml/kg cristaloide în primele 3 ore.','Cristaloidele sunt fluidul de primă intenție.','Hidroxietil amidonul trebuie evitat.','Resuscitarea volemică a crescut mortalitatea în două studii din țări cu venituri mici.','Resuscitarea în bolus nu este benefică tuturor pacienților.']],
 [8,'Distractorii contrazic recomandarea privind amidonul și dovezile recente.'],['30 ml/kg','hidroxietil']),

q('sepsis-adv-043',['După instalarea hipotensiunii, riscul de deces crește, pentru fiecare oră de întârziere a antibioticului cu spectru larg, cu aproximativ:',
 ['2%','4%','7,6%','15%','30%'],'C',157,'Tratamentul sepsisului — Terapia antimicrobiană',
 'Fixarea impactului întârzierii antibioterapiei în șocul septic.',
 ['Nu este valoarea citată.','Nu este valoarea citată.','Riscul de deces a crescut cu 7,6% pentru fiecare oră de întârziere.','Nu este valoarea citată.','Nu este valoarea citată.']],
 [8,'Distractorii sunt valori numerice plauzibile.'],['7,6%','fiecare oră']),

q('sepsis-adv-006',['La un tânăr cu suspiciune de septicemie meningococică, în departamentul de urgență:',
 ['antibioticul se amână până la recoltarea a două seturi de hemoculturi','antibioticul se administrează fără întârziere','se așteaptă pozitivarea hemoculturii pentru antibioterapie țintită','se recoltează de elecție tampoane din leziunile cutanate','se face PCR, apoi se începe antibioterapia'],'B',158,'Probe biologice utile — Excepția meningococică',
 'Aplicarea singurei excepții de la regula recoltării hemoculturilor înaintea antibioticului.',
 ['Regula recoltării prealabile nu se aplică în suspiciunea de septicemie meningococică.','Aceasta este singura excepție: antibioticul nu trebuie întârziat.','Pozitivarea durează în jur de 24 de ore.','Tampoanele superficiale sunt rar utile.','PCR poate detecta patogenul chiar după antibiotic; nu justifică amânarea.']],
 [8,'Distractorii aplică regula generală într-o situație care este excepția ei.'],['septicemie meningococică','întârziată']),

q('sepsis-adv-045',['Recoltarea hemoculturilor la adultul cu sepsis:',
 ['presupune cel puțin 5 ml de sânge în flacoane aerob și anaerob','se face înaintea antibioticului, chiar la pacientul decompensat','poate fi negativă dacă antibioticul a fost administrat anterior','exclude utilitatea PCR după începerea antibioticului','se efectuează după 72 de ore de antibioterapie'],'ABC',158,'Probe biologice utile și examinarea în laborator',
 'Aplicarea regulilor de recoltare a hemoculturilor.',
 ['La adult se recoltează minim 5 ml în flacoane aerob și anaerob.','Există întotdeauna timp pentru hemoculturi înaintea antibioticului, chiar la pacientul acut.','Antibioterapia prealabilă poate negativiza culturile.','PCR pentru ADN bacterian poate detecta patogenul și după antibiotic.','Hemoculturile se recoltează înaintea tratamentului.']],
 [8,'Distractorii contrazic rolul PCR și momentul recoltării.'],['5 ml de sânge','ADN bacterian']),

q('sepsis-adv-020',['Conform Cadranului 8.6, metodele moleculare de identificare în sepsis:',
 ['PCR 16S amplifică regiunile hipervariabile ale ARN ribozomal 16S','PCR 16S nu oferă date despre susceptibilitate','MALDI-TOF generează un profil spectral unic pentru fiecare specie','MALDI-TOF oferă o antibiogramă fenotipică completă','PCR 16S este inutilă în probele expuse la antibiotic'],'ABC',158,'Cadranul 8.6 — Identificarea moleculară',
 'Diferențierea PCR 16S de MALDI-TOF.',
 ['Secvențierea regiunilor hipervariabile identifică specia.','Spre deosebire de culturi, PCR 16S nu oferă date de susceptibilitate.','Fiecare fragment proteic generează un profil spectral unic de specie.','MALDI-TOF detectează doar uneori gene de rezistență.','PCR 16S este valoroasă tocmai în probele negativate de antibiotic.']],
 [8,'Distractorii supraestimează MALDI-TOF și inversează utilitatea PCR 16S.'],['16S','MALDI']),

q('sepsis-adv-019',['Controlul sursei în sepsis poate include:',
 ['nefrostoma în obstrucția urinară','drenajul colecțiilor paraspinale','lavajul artroscopic în infecția intraarticulară','valvectomia în endocardita acută cu S. aureus','menținerea cateterelor urinare blocate'],'ABCD',158,'Controlul sursei',
 'Recunoașterea procedurilor de control al sursei.',
 ['Stentul biliar, cateterul urinar sau nefrostoma rezolvă obstrucția.','Colecțiile paraspinale necesită drenaj.','Infecția intraarticulară necesită lavaj artroscopic.','Valvectomia este tot mai folosită în endocardita acută cu S. aureus.','Cateterele infectate, mai ales blocate, se îndepărtează.']],
 [8,'Singurul distractor contrazice principiul controlului sursei.'],['nefrostomă','Valvectomia']),

q('sepsis-adv-062',['Obiectivele de prescriere din Marea Britanie (CQUIN și KPI) prevăd:',
 ['reducerea prescrierii de carbapeneme și de piperacilină-tazobactam','revizuirea antibioticelor la 72 de ore','nitrofurantoină în loc de trimetoprim în ITU joasă necomplicată','creșterea utilizării de ciprofloxacină în medicina de familie','co-amoxiclav de primă intenție în ITU joasă'],'ABC',159,'Obiective specifice în Marea Britanie',
 'Recunoașterea indicatorilor de administrare prudentă a antibioticelor.',
 ['Indicatorii vizează reducerea carbapenemelor și a piperacilină-tazobactamului.','Revizuirea la 72 de ore este un indicator.','Nitrofurantoina se prescrie în loc de trimetoprim.','Utilizarea ciprofloxacinei trebuie redusă.','Utilizarea co-amoxiclavului trebuie redusă.']],
 [8,'Distractorii inversează sensul indicatorilor din medicina de familie.'],['CQUIN','nitrofurantoin']),

q('sepsis-adv-021',['Înaintea începerii antibioterapiei empirice trebuie evaluate:',
 ['microbiologia anterioară, ca o colonizare ESBL','politica locală, după rezistența locală','nivelurile terapeutice ale gentamicinei','o schemă unică, aceeași în fiecare spital','sediul infecției, ca unic criteriu de alegere'],'ABC',159,'Aspecte de avut în vedere înaintea antibioterapiei empirice',
 'Identificarea parametrilor care ghidează alegerea empiricului.',
 ['Colonizarea anterioară cu ESBL poate justifica o carbapenemă.','Politica empirică diferă după prevalența locală a rezistenței.','Nivelurile terapeutice sunt necesare, de exemplu pentru gentamicină sau amikacină.','Politica diferă de la spital la spital.','Se evaluează multipli parametri, nu doar sediul.']],
 [8,'Distractorii ignoră variabilitatea locală și parametrii farmacologici.'],['ESBL','gentamicină sau amikacină']),

q('sepsis-adv-061',['La 72 de ore, când culturile sunt disponibile, deciziile posibile includ:',
 ['oprirea antibioticului, dacă se consideră că nu a existat infecție','trecerea la oral după 2–3 zile în pielonefrita necomplicată','schimbarea la carbapenem i.v. în bacteriemia cu E. coli ESBL','continuarea tratamentului i.v. în meningită','extinderea spectrului pentru a preveni C. difficile'],'ABCD',159,'Antibioterapia după 72 de ore',
 'Aplicarea celor cinci decizii de la 72 de ore.',
 ['Oprirea este potrivită dacă pacientul nu a avut infecție.','Dezescaladarea la oral se face în infecțiile necomplicate, la pacientul stabil.','Rezistența neanticipată (ESBL) impune carbapenem i.v.','Meningita și artrita septică impun continuarea i.v.','Spectrul îngust reduce riscul de C. difficile.']],
 [8,'Singurul distractor inversează relația spectru – C. difficile.'],['cinci decizii','pielonefrită']),

q('sepsis-adv-070',['Alegerea unui antibiotic cu spectru îngust, la dezescaladarea după culturi, urmărește:',
 ['menținerea acoperirii anaerobe în orice infecție','reducerea riscului de infecție cu C. difficile','scurtarea duratei totale a tratamentului','evitarea monitorizării nivelurilor serice','creșterea biodisponibilității orale'],'B',159,'Antibioterapia după 72 de ore — Dezescaladarea',
 'Recunoașterea scopului dezescaladării.',
 ['Nu este scopul citat.','Dezescaladarea reduce riscul de C. difficile și de colonizare cu organisme multirezistente.','Nu este scopul citat.','Nu este scopul citat.','Nu este scopul citat.']],
 [8,'Distractorii sunt beneficii plauzibile, dar necitate.'],['Clostrid','spectru îngust']),

q('sepsis-adv-022',['Antibioterapia parenterală în ambulatoriu (OPAT):',
 ['folosește doze unice zilnice, ca ceftriaxona','preferă Hickman sau PICC pentru tratament de peste 7 zile','nu este destinată utilizatorilor de droguri intravenoase','exclude endocardita infecțioasă, chiar după stabilizare','impune monitorizarea biologică la cel mult 2 săptămâni'],'ABC',160,'Antibioterapia parenterală în ambulatoriu',
 'Aplicarea criteriilor de eligibilitate și de monitorizare OPAT.',
 ['Ceftriaxona, ertapenemul, amikacina, teicoplanina și daptomicina se dau o dată pe zi.','Pentru >7 zile se preferă Hickman sau PICC.','Utilizatorii de droguri i.v. și pacienții psihiatrici severi nu sunt eligibili.','Endocardita infecțioasă este o afecțiune potrivită pentru OPAT, după stabilizare.','Monitorizarea biologică se face cel puțin săptămânal.']],
 [8,'Distractorii restrâng nejustificat indicațiile și rarefiază monitorizarea.'],['PICC','ceftriaxona']),

q('sepsis-adv-023',['Referitor la alergia raportată la penicilină:',
 ['aproximativ 10% din populație relatează alergie la penicilină','valoarea reală este de aproximativ 1%','în alergia IgE-mediată se evită și cefalosporinele și carbapenemele','în erupția blândă, non-severă, monobactamii sunt contraindicați','desensibilizarea nu este posibilă'],'ABC',160,'Evaluarea riscului alergic',
 'Aplicarea evaluării alergiei la penicilină.',
 ['Aproximativ 10% relatează alergie.','Datele atestă o valoare reală de circa 1%.','În tipul 1 și alte alergii severe se evită și cefalosporinele și carbapenemele.','În alergia non-severă pot fi folosite cu prudență cefalosporinele, carbapenemele și monobactamii.','Desensibilizarea este posibilă cu doze progresive.']],
 [8,'Distractorii restrâng opțiunile din alergia non-severă.'],['10% din populaţie','monobactamii']),

q('sepsis-adv-008',['Conform Cadranului 8.7, chemoprofilaxia antibiotică include:',
 ['rifampicină 600 mg de două ori pe zi, 2 zile, la contacții de meningococ','ciprofloxacină 500 mg p.o. doză unică, la contacții de meningococ','rifampicină 600 mg zilnic, 4 zile, la contacții de H. influenzae tip B','fenoximetilpenicilină 500 mg de două ori pe zi după splenectomie','profilaxia endocarditei înaintea procedurilor dentare'],'ABCD',161,'Cadranul 8.7 — Chemoprofilaxia antibiotică',
 'Asocierea schemelor de chemoprofilaxie cu situațiile clinice.',
 ['Contacții de meningococ: rifampicină 600 mg x2/zi, 2 zile.','Alternativa: ciprofloxacină 500 mg p.o. sau ceftriaxonă 250 mg i.m., doză unică.','H. influenzae tip B: rifampicină 600 mg zilnic, 4 zile.','Splenectomie: fenoximetilpenicilină 500 mg x2/zi.','Profilaxia și clorhexidina nu sunt recomandate înaintea procedurilor dentare.']],
 [8,'Distractorul este o practică veche, contrazisă explicit de cadran.'],['rifampicină 600','clorhexidină']),

q('sepsis-adv-071',['Conform Cadranului 8.7, profilaxia secundară în reumatismul articular acut folosește:',
 ['fenoximetilpenicilină 500 mg de două ori pe zi, pe termen lung','fenoximetilpenicilină 250 mg de două ori pe zi','rifampicină 600 mg zilnic, 4 zile','izoniazidă 300 mg zilnic, 6 luni','ciprofloxacină 500 mg în doză unică'],'B',161,'Cadranul 8.7 — Reumatismul articular acut',
 'Distingerea schemelor de chemoprofilaxie după indicație.',
 ['500 mg x2/zi este schema post-splenectomie.','RAA: fenoximetilpenicilină 250 mg x2/zi sau sulfadiazină 1 g la alergie.','Schema pentru contacții de H. influenzae tip B.','Schema pentru tuberculoză.','Alternativa pentru contacții de meningococ.']],
 [8,'Toate variantele sunt scheme reale din același cadran.'],['250 mg doză dublă','sulfadia']),

q('sepsis-adv-024',['Profilaxia antibiotică perioperatorie, pentru majoritatea intervențiilor:',
 ['constă de obicei într-o doză unică la inducție','se continuă 5–7 zile postoperator','se continuă până la scoaterea drenurilor și a sondelor','se începe după incizia tegumentară','se continuă 48–72 de ore postoperator'],'A',161,'Chemoprofilaxia antibiotică — Profilaxia chirurgicală',
 'Aplicarea duratei profilaxiei antibiotice perioperatorii.',
 ['Pentru majoritatea operațiilor este suficientă o doză unică la inducție; nu se depășesc 24 de ore.','Profilaxia nu trebuie să depășească 24 de ore.','Nu este criteriul citat.','Administrarea se face la inducție.','Durata maximă este de 24 de ore.']],
 [8,'Distractorii sunt practici prelungite, frecvente, dar contrazise de text.'],['doză unică la inducţie','24 de ore']),

q('sepsis-adv-064',['Antibioticele β-lactamice:',
 ['se leagă de proteinele de legare a penicilinei (peptidaze)','sunt bactericide dependent de timp','pot avea spectrul extins prin modificarea nucleului β-lactamic','sunt bacteriostatice dependent de concentrație','acționează prin inhibarea ADN-girazei'],'ABC',161,'Antibiotice β-lactamice',
 'Recunoașterea mecanismului și a farmacodinamicii β-lactaminelor.',
 ['Blochează sinteza peretelui prin inactivarea peptidazelor.','Sunt în general bactericide, dependent de timp.','Modificarea nucleului sau a lanțului adiacent extinde spectrul.','Sunt bactericide dependent de timp.','ADN-giraza este ținta chinolonelor.']],
 [8,'Distractorii descriu farmacodinamica și ținta altor clase.'],['dependentă de timp','penicilină, peptidaze'],[163]),

q('sepsis-adv-072',['Benzilpenicilina:',
 ['se administrează doar parenteral','rămâne de primă intenție în endocardita streptococică','se asociază în fasceita necrozantă cu streptococ de grup A','se folosește empiric, fără confirmarea sensibilității','este activă pe stafilococii producători de penicilinază'],'ABC',163,'Penicilinele — Benzilpenicilina',
 'Aplicarea indicațiilor și a limitelor benzilpenicilinei.',
 ['Benzilpenicilina se administrează doar parenteral.','Rămâne de primă intenție în infecții severe streptococice, inclusiv endocardita.','În fasceita necrozantă cu S. pyogenes se combină cu alte antibiotice.','Nu se folosește empiric fără confirmarea sensibilității.','Stafilococii producători de penicilinază necesită flucloxacilină.']],
 [8,'Distractorii contrazic rezerva privind utilizarea empirică.'],['parenteral','fasceită necrozantă']),

q('sepsis-adv-025',['Referitor la peniciline:',
 ['flucloxacilina este prima intenție în infecțiile severe cu MSSA','amoxicilina produce erupție la 90% din pacienții cu mononucleoză infecțioasă','co-amoxiclavul produce icter colestatic mai rar decât amoxicilina','ticarcilina este activă pe Pseudomonas','amoxicilina este rezistentă la β-lactamaze'],'ABD',163,'Penicilinele',
 'Recunoașterea indicațiilor și a efectelor adverse ale penicilinelor.',
 ['Flucloxacilina rămâne prima intenție în MSSA sever.','Amoxicilina și ampicilina produc erupție la 90% în mononucleoză.','Co-amoxiclavul produce icter colestatic de șase ori mai frecvent decât amoxicilina.','Ticarcilina este activă pe Pseudomonas.','Amoxicilina este susceptibilă la β-lactamază.']],
 [8,'Distractorii inversează frecvența icterului și stabilitatea la β-lactamaze.'],['mononucleoză','icter colestatic']),

q('sepsis-adv-049',['Pivmecilinamul și temocilina:',
 ['sunt active pe E. coli producător de ESBL','sunt inactive pe Pseudomonas aeruginosa','temocilina favorizează mai puțin infecția cu C. difficile','temocilina este activă pe Acinetobacter','pivmecilinamul este activ pe MRSA'],'ABC',163,'Penicilinele — Pivmecilinamul și temocilina',
 'Delimitarea spectrului penicilinelor Gram-negative cu spectru îngust.',
 ['Ambele acționează și pe tulpini producătoare de ESBL.','Niciuna nu este activă pe P. aeruginosa.','Temocilina favorizează mai puțin C. difficile și protejează carbapenemele.','Temocilina nu este activă pe Acinetobacter.','Ambele au spectru Gram-negativ.']],
 [8,'Distractorii extind spectrul spre germenii explicit excluși.'],['Temocilina','ESBL']),

q('sepsis-adv-048',['Cefalosporinele:',
 ['nu sunt inactivate de penicilinazele stafilococice','nu sunt active pe enterococi','sunt toate active pe Pseudomonas','în generația a cincea sunt inactive pe MRSA','au alergie încrucișată de circa 50%'],'AB',163,'Cefalosporinele',
 'Recunoașterea spectrului și a limitelor cefalosporinelor.',
 ['Sunt superioare penicilinelor prin rezistența la penicilinazele stafilococice.','Nu sunt active pe enterococi și pe anaerobii Gram-negativi.','Doar anumite cefalosporine (ceftazidimă, cefepim) sunt active pe P. aeruginosa.','Ceftarolina și ceftobiprolul sunt excepția activă pe MRSA.','Alergia încrucișată este de aproximativ 10%.']],
 [8,'Distractorii inversează excepția MRSA și cifra alergiei încrucișate.'],['penicilinazele stafilococice','enterococilor']),

q('sepsis-adv-065',['Dintre cefalosporine, sunt active pe Pseudomonas aeruginosa:',
 ['cefuroxima și cefalexina','ceftazidima și cefepimul','cefotaxima și ceftriaxona','cefazolina și cefalexina','cefuroxima și cefotaxima'],'B',163,'Cefalosporinele — Activitatea antipseudomonas',
 'Identificarea cefalosporinelor antipseudomonas.',
 ['Nu sunt citate ca antipseudomonas.','Textul numește ceftazidima și cefepimul.','Nu sunt citate ca antipseudomonas.','Nu sunt citate ca antipseudomonas.','Nu sunt citate ca antipseudomonas.']],
 [8,'Distractorii sunt perechi de cefalosporine reale, fără activitate antipseudomonas.'],['ceftazidima','cefepim']),

q('sepsis-adv-073',['Cefalosporinele de generația a doua și a treia sunt rezervate anumitor infecții severe deoarece:',
 ['au nefrotoxicitate tubulară proximală marcată și frecventă','producția de ESBL poate face empiricul ineficient','se administrează doar intravenos','au spectru îngust Gram-pozitiv','nu difuzează în lichidul cefalorahidian'],'B',163,'Cefalosporinele — Restricția de utilizare',
 'Motivarea restricției cefalosporinelor de generațiile II–III.',
 ['Nefrotoxicitatea a fost a derivaților timpurii.','ESBL poate face empiricul ineficient, iar riscul de C. difficile crește.','Nu este motivul citat.','Nu este motivul citat.','Nu este motivul citat.']],
 [8,'Distractorii sunt dezavantaje plauzibile, dar necitate.'],['ESBL','diffici']),

q('sepsis-adv-046',['Aztreonamul:',
 ['nu are alt inel decât cel β-lactamic','are spectru limitat la Gram-negativi aerobi','este activ pe unele tulpini cu metalo-β-lactamază','este activ pe MRSA și pe enterococi','este activ pe anaerobi, ca și carbapenemele'],'ABC',163,'Monobactamii',
 'Recunoașterea structurii și spectrului aztreonamului.',
 ['Monobactamul are doar inelul β-lactamic.','Spectrul este limitat la bacilii Gram-negativi aerobi.','Este activ pe unele tulpini rezistente la carbapeneme producătoare de metalo-β-lactamază.','Nu acoperă Gram-pozitivii.','Nu acoperă anaerobii.']],
 [8,'Distractorii extind spectrul aztreonamului la cel al carbapenemelor.'],['monobactam','metalo']),

q('sepsis-adv-047',['Carbapenemele:',
 ['sunt active pe Gram-pozitivi, Gram-negativi și anaerobi','sunt active pe MRSA, spre deosebire de glicopeptide','includ ertapenemul, inactiv pe Pseudomonas','includ imipenemul, asociat cu cilastatin','sunt elementul-cheie în infecția severă cu ESBL'],'ACDE',163,'Carbapenemele',
 'Recunoașterea spectrului și a particularităților carbapenemelor.',
 ['Au cel mai larg spectru, inclusiv anaerobi.','Nu sunt active pe MRSA.','Ertapenemul nu este activ pe Pseudomonas sau Acinetobacter.','Imipenemul este inactivat parțial renal și se asociază cu cilastatin.','Sunt elementul-cheie în infecția severă cu ESBL.']],
 [8,'Singurul distractor este excepția clasică a spectrului.'],['cilastatin','Ertapenem']),

q('sepsis-adv-066',['Efectele adverse ale carbapenemelor includ:',
 ['greață, vărsături și diaree la sub 5% din cazuri','convulsii la imipenem și ertapenem','risc convulsivant care contraindică meropenemul în meningită','ototoxicitate dependentă de doză','prelungirea intervalului QT'],'AB',163,'Carbapenemele — Efecte adverse',
 'Recunoașterea efectelor adverse ale carbapenemelor.',
 ['Greața, vărsăturile și diareea apar la sub 5%.','Imipenemul și ertapenemul pot produce convulsii.','Meropenemul este alternativa în meningită.','Ototoxicitatea este caracteristică aminoglicozidelor.','Prelungirea QT este descrisă la chinolone și macrolide.']],
 [8,'Distractorii sunt efecte adverse reale ale altor clase.'],['convulsii','meropenem']),

q('sepsis-adv-026',['Avibactamul:',
 ['este primul inhibitor non-β-lactamic al β-lactamazelor','se combină cu ceftazidima','pare neafectat de majoritatea ESBL și de KPC și OXA-48','este un inhibitor suicidar β-lactamic, ca acidul clavulanic','este activ și pe tulpinile producătoare de NDM'],'ABC',164,'Combinații β-lactamice/inhibitori de β-lactamază',
 'Recunoașterea particularităților avibactamului.',
 ['Avibactamul este primul inhibitor non-β-lactamic.','Se combină cu ceftazidima.','Combinația pare neafectată de majoritatea ESBL și de unele carbapenemaze (KPC, OXA-48).','Inhibitorii clasici sunt β-lactamici suicidari; avibactamul nu.','Tulpinile NDM rămân sensibile doar la colistin, fosfomicină și tigeciclină.']],
 [8,'Distractorii atribuie avibactamului mecanismul clasic și activitate pe NDM.'],['Avibactam','OXA-48']),

q('sepsis-adv-027',['Chinolonele:',
 ['inhibă topoizomeraza IV și ADN-giraza','pot produce ruptură de tendon în primele 48 de ore','prelungesc intervalul QT','sunt de primă intenție în sarcină','au rezistență rară la E. coli și Klebsiella'],'ABC',164,'Chinolonele',
 'Recunoașterea mecanismului, efectelor adverse și limitelor chinolonelor.',
 ['Inhibă topoizomeraza IV și ADN-giraza.','Leziunile de tendon pot apărea în primele 48 de ore.','Există îngrijorări privind prelungirea QT.','Utilizarea se evită în sarcină și la copii.','În multe țări, >80% dintre E. coli și Klebsiella sunt rezistente.']],
 [8,'Distractorii contrazic restricțiile și datele de rezistență.'],['topoizomerazei IV','48 de ore']),

q('sepsis-adv-028',['Aminoglicozidele:',
 ['se administrează în majoritatea cazurilor în doză unică zilnică','se monitorizează prin nivel seric la 6–14 ore după doză','se dau în doze mici la 12 ore în endocardită','sunt sigure în miastenia gravis','au ototoxicitatea asociată mutației m.1555A>G la majoritatea populației'],'ABC',164,'Aminoglicozidele',
 'Aplicarea schemelor de dozare și a precauțiilor aminoglicozidelor.',
 ['Doza unică zilnică este indicată în majoritatea cazurilor.','Nivelul seric se determină la 6–14 ore, apoi se folosește nomograma.','În endocardită se dau doze mici la 12 ore.','Blocajul neuromuscular impune evitarea în miastenia gravis.','Mutația apare la sub 1% din populație.']],
 [8,'Distractorii contrazic precauțiile și frecvența mutației.'],['m.1555A','6-14 ore']),

q('sepsis-adv-029',['Teicoplanina, comparativ cu vancomicina:',
 ['este mai nefrotoxică','este mai puțin nefrotoxică','se administrează numai oral','nu necesită monitorizarea nivelurilor serice','este activă pe bacilii Gram-negativi'],'B',164,'Glicopeptidele',
 'Compararea glicopeptidelor după toxicitate și administrare.',
 ['Teicoplanina este mai puțin nefrotoxică.','Este mai puțin nefrotoxică și permite doza unică zilnică sau de trei ori pe săptămână.','Se administrează intravenos.','Nivelurile predoză se monitorizează.','Glicopeptidele acționează pe Gram-pozitivi.']],
 [8,'Distractorii inversează comparația și calea de administrare.'],['Teicoplanina','trei ori pe săptămână']),

q('sepsis-adv-030',['Daptomicina:',
 ['are spectru similar vancomicinei','se folosește în infecțiile cutanate complicate cu MRSA','este o alternativă în endocardită','se administrează oral, cu biodisponibilitate bună','este activă și pe Pseudomonas aeruginosa'],'ABC',164,'Lipopeptidele',
 'Recunoașterea spectrului și indicațiilor daptomicinei.',
 ['Daptomicina are spectru similar vancomicinei.','Se folosește în infecțiile complicate ale pielii și țesuturilor moi, inclusiv MRSA.','Este alternativă în endocardită, infecții osteoarticulare și septicemii Gram-pozitive.','Se administrează intravenos.','Spectrul este Gram-pozitiv.']],
 [8,'Distractorii extind nejustificat calea și spectrul.'],['Daptomicina','ţesuturilor moi']),

q('sepsis-adv-031',['Oxazolidinonele:',
 ['se leagă de ARN-ul ribozomal 23S','au biodisponibilitate orală de 100%','tedizolidul se administrează o dată pe zi','linezolidul este mai puțin medulotoxic','nu interacționează serotoninergic'],'ABC',165,'Oxazolidinonele',
 'Recunoașterea mecanismului și a diferențelor linezolid/tedizolid.',
 ['Se leagă de ARN-ul ribozomal 23S.','Biodisponibilitatea orală este de 100%.','Tedizolidul se administrează o dată pe zi, linezolidul de două ori.','Tedizolidul este mai puțin medulotoxic.','Sunt inhibitori MAO non-selectivi, cu interacțiuni serotoninergice.']],
 [8,'Distractorii inversează comparația medulotoxică și interacțiunile MAO.'],['23S','Tedizolid'],[164]),

q('sepsis-adv-067',['Tigeciclina și tetraciclinele:',
 ['tigeciclina evită pompele de eflux bacterian','tigeciclina este activă pe VRE și Acinetobacter baumannii','tetraciclinele colorează dinții în dezvoltare','tigeciclina este activă pe Pseudomonas','eficiența tetraciclinelor este crescută de antiacide'],'ABC',165,'Tetraciclinele',
 'Recunoașterea spectrului tigeciclinei și a precauțiilor tetraciclinelor.',
 ['Tigeciclina evită pompele de eflux.','Este activă pe VRE, MRSA și Acinetobacter baumannii.','Colorează maroniu dinții în dezvoltare; se evită la copii și gravide.','Nu este activă pe Pseudomonas sau Proteus.','Antiacidele și fierul reduc eficiența.']],
 [8,'Distractorii inversează excepțiile de spectru și interacțiunea cu antiacidele.'],['pompele de eflux','antiacide']),

q('sepsis-adv-032',['Macrolidele:',
 ['nu sunt utilizate curent în endocardită sau meningită','azitromicina are biodisponibilitate serică scăzută','azitromicina are timp de înjumătățire mai lung decât eritromicina','eritromicina intravenoasă este bine tolerată venos','prelungirea QT nu este descrisă la macrolide'],'ABC',165,'Macrolidele',
 'Recunoașterea limitelor și a farmacocineticii macrolidelor.',
 ['Macrolidele nu sunt folosite curent în infecțiile severe.','Biodisponibilitatea serică scăzută face problematică utilizarea azitromicinei în bacteriemii.','Azitromicina are t½ mai lung, permițând doza unică zilnică.','Eritromicina i.v. este iritantă și cauzează flebită.','Prelungirea QT este un efect recunoscut.']],
 [8,'Distractorii contrazic efectele adverse cunoscute.'],['torsadei','Biodisponibilitatea serică']),

q('sepsis-adv-033',['Polimixinele (colistimetatul sodic):',
 ['colistimetatul este un prodrog metabolizat în colistin','rup membrana bacteriană prin legarea de LPS','sunt active pe Proteus și Providencia','au rezistență plasmidică descrisă prin enzima MCR-1','sunt antibiotice de primă linie în infecțiile comunitare'],'ABD',165,'Polimixinele',
 'Recunoașterea mecanismului, spectrului și rezistenței polimixinelor.',
 ['CMS este un prodrog inactiv, metabolizat în colistin.','Rup membrana prin legarea de LPS.','Proteus și Providencia sunt excepțiile de spectru.','Rezistența plasmidică MCR-1 modifică LPS.','Sunt ultima alegere, în Gram-negativii multirezistenți.']],
 [8,'Distractorul de spectru inversează excepția citată.'],['colistimeth','MCR-1'],[166]),

q('sepsis-adv-004',['Fusidatul de sodiu:',
 ['are structură asemănătoare sărurilor biliare','asigură o concentrație bună la nivel osos','se administrează în combinație cu alt antistafilococic','se asociază de elecție cu statinele','se recomandă de rutină topic în impetigo'],'ABC',166,'Fusidatul de sodiu',
 'Recunoașterea proprietăților și a regulilor de utilizare ale fusidatului.',
 ['Are structură asemănătoare sărurilor biliare.','Asigură o concentrație bună la nivel osos.','Se combină cu alt antistafilococic pentru a preveni rezistența.','Utilizarea concomitentă a statinelor trebuie evitată.','Preparatele topice trebuie evitate pentru a limita rezistența.']],
 [8,'Distractorii inversează două precauții explicite.'],['sărurilor biliare','concentraţie bună la nivel osos']),

q('sepsis-adv-034',['Metronidazolul:',
 ['este de elecție în infecția moderată cu C. difficile','produce o reacție de tip disulfiram cu etanolul','intensifică efectul anticoagulant al warfarinei','are absorbție rectală neglijabilă, supozitorul fiind ineficient','este inactiv pe anaerobii din genul Bacteroides'],'ABC',166,'Nitroimidazolii',
 'Recunoașterea indicațiilor și interacțiunilor metronidazolului.',
 ['Este de elecție în infecția moderată cu C. difficile, amibiază, giardiază și trichomoniază.','Produce reacție de tip disulfiram.','Intensifică efectul warfarinei.','Supozitorul are absorbție bună.','Are rol important în infecțiile cu Bacteroides.']],
 [8,'Distractorii contrazic calea rectală și spectrul anaerob.'],['disulfiram','supozitor']),

q('sepsis-adv-035',['Clindamicina:',
 ['inhibă producția toxinei TSST-1','asigură concentrație ridicată la nivel osos','este activă pe anaerobi, în special Bacteroides','este de primă intenție de rutină în sepsisul comunitar','nu se asociază cu infecția cu C. difficile'],'ABC',166,'Alte antibiotice — Clindamicina',
 'Recunoașterea efectului antitoxinic și a limitelor clindamicinei.',
 ['Inhibă TSST-1 și toxina alfa; rol în S. aureus secretor de PVL.','Asigură concentrație osoasă ridicată.','Este activă pe anaerobi, mai ales Bacteroides.','Nu este folosită pe scară largă.','Asocierea cu C. difficile îi limitează utilizarea.']],
 [8,'Distractorii contrazic motivul utilizării limitate.'],['TSST-1','Bacteroides']),

q('sepsis-adv-010',['Mecanismele de rezistență sau de evitare a rezistenței descrise includ:',
 ['amikacina rezistă mai bine decât gentamicina la enzimele modificatoare','tigeciclina evită pompele de eflux','enzima MupA explică eșecul mupirocinului la MRSA','enzima FosA explică eșecul mupirocinului la MRSA','ESBL conferă rezistență la aztreonam'],'ABCE',164,'Mecanisme de rezistență',
 'Asocierea mecanismelor de rezistență cu antibioticul corespunzător.',
 ['Amikacina este mai rezistentă la fosforilare, adenilare sau acetilare.','Tigeciclina evită pompele de eflux.','MupA plasmidică explică rezistența MRSA la mupirocin.','FosA distruge fosfomicina, nu mupirocinul.','ESBL conferă rezistență la peniciline, cefalosporine și aztreonam.']],
 [8,'Enzimele MupA și FosA sunt permutate în distractor.'],['fosforilare','MupA'],[165,166,167]),

q('sepsis-adv-050',['Staphylococcus aureus rezistent la meticilină (MRSA):',
 ['are rezistența mediată de PBP2a','diseminează hematogen în aproximativ 5% din cazuri','impune îndepărtarea cateterului în infecția asociată dispozitivelor','este sensibil la flucloxacilină','diseminează hematogen în aproximativ 50% din cazuri'],'ABC',167,'Tratamentul infecțiilor cu organisme multirezistente — MRSA',
 'Recunoașterea mecanismului și a evoluției infecției cu MRSA.',
 ['Rezistența este mediată de PBP2a, neinhibată de meticilină sau flucloxacilină.','Diseminarea hematogenă apare în aproximativ 5% din cazuri.','Îndepărtarea cateterului face parte din tratament.','Flucloxacilina nu inhibă PBP2a.','Proporția citată este de aproximativ 5%.']],
 [8,'Distractorii sunt contrariul mecanismului și o cifră deplasată.'],['proteinei 2a','5% dintre cazuri']),

q('sepsis-adv-051',['În tratamentul MRSA:',
 ['vancomicina necesită niveluri de 15–20 mg/L','durata minimă a tratamentului este de două săptămâni','linezolidul are avantajul administrării orale','linezolidul este nefrotoxic','rifampicina adjuvantă a demonstrat beneficiu clinic clar'],'ABC',167,'MRSA — Tratament',
 'Aplicarea parametrilor de tratament în infecția cu MRSA.',
 ['Nivelurile eficiente de vancomicină sunt 15–20 mg/L.','Durata minimă este de două săptămâni.','Linezolidul se administrează per os, fără nefrotoxicitate.','Linezolidul nu este nefrotoxic; poate produce mielosupresie.','Studiul britanic nu a demonstrat beneficiul rifampicinei adjuvante.']],
 [8,'Distractorii inversează profilul toxic al linezolidului și dovezile pentru rifampicină.'],['15-20 mg/L','două săptămâni']),

q('sepsis-adv-052',['Enterococii rezistenți la vancomicină (VRE):',
 ['au precursori modificați la D-Ala-D-Lac','produc frecvent infecții nosocomiale','au sedii frecvente urinare și biliare','au virulență ridicată și evoluție severă','se tratează oral cu vancomicină sau teicoplanină'],'ABC',167,'Enterococi rezistenți la vancomicină',
 'Recunoașterea mecanismului și a tratamentului VRE.',
 ['D-Ala-D-Lac împiedică legarea glicopeptidelor.','Multe infecții cu VRE sunt nosocomiale.','Sediile frecvente sunt tractul urinar și cel biliar.','VRE are virulență scăzută.','Singurul tratament oral este linezolidul.']],
 [8,'Distractorii inversează virulența și tratamentul oral.'],['peptidoglican','linezolid']),

q('sepsis-adv-053',['Enterobacteriile producătoare de ESBL:',
 ['au tulpina E. coli CTX-M-15 apărută în Marea Britanie în 2004','reprezintă aproximativ 15% din tulpinile de E. coli în Marea Britanie','se tratează de elecție cu o carbapenemă','se tratează de elecție cu piperacilină/tazobactam dacă MIC este favorabilă','sunt de obicei sensibile la ciprofloxacină'],'ABC',167,'Enterobacterii producătoare de ESBL',
 'Recunoașterea epidemiologiei și tratamentului infecțiilor cu ESBL.',
 ['CTX-M-15 a apărut brusc în 2004.','Aproximativ 15% dintre tulpinile de E. coli sunt ESBL.','Tratamentul principal este o carbapenemă.','Piperacilina/tazobactam este inferioară carbapenemelor chiar la MIC favorabilă.','Tulpinile sunt adesea multirezistente, inclusiv la ciprofloxacină.']],
 [8,'Distractorul principal este o capcană reală descrisă explicit.'],['CT X-M-15','15%']),

q('sepsis-adv-007',['Enterobacteriile rezistente la carbapeneme (CRE):',
 ['în Marea Britanie sunt cel mai frecvent de tip OXA-48, NDM și KPC','cele producătoare de NDM rămân de regulă sensibile la colistin','cele producătoare de OXA-48 sau KPC sunt de regulă rezistente la chinolone','cele producătoare de KPC au frecvent rezistență la ceftazidimă/avibactam','produc cel mai frecvent pneumonie'],'AB',167,'Enterobacterii rezistente la carbapeneme',
 'Recunoașterea tipurilor de carbapenemaze și a opțiunilor terapeutice.',
 ['Tipurile frecvente în Marea Britanie sunt OXA-48, NDM și KPC.','Tulpinile NDM rămân sensibile la colistin, fosfomicină și tigeciclină.','Tulpinile OXA-48 și KPC sunt susceptibile la chinolone și aminoglicozide.','Rezistența la ceftazidimă/avibactam rămâne rară.','CRE provoacă cel mai frecvent ITU.']],
 [8,'Distractorii inversează sensibilitatea tulpinilor OXA-48/KPC.'],['OXA-48','NDM']),

q('sepsis-adv-054',['În infecțiile cu CRE, când testarea susceptibilității este puțin standardizată, tratamentul principal este:',
 ['colistinul','ertapenemul','ceftazidima/avibactam','piperacilina/tazobactam','temocilina'],'A',168,'Enterobacterii rezistente la carbapeneme — Tratament',
 'Identificarea tratamentului principal al CRE.',
 ['Colistinul este tratamentul principal; tigeciclina și fosfomicina sunt adjuvante.','Nu este tratamentul principal citat.','Nu este tratamentul principal citat pentru această situație.','Nu este activă pe CRE.','Nu este tratamentul citat.']],
 [8,'Distractorii sunt antibiotice active pe alte Enterobacterii rezistente.'],['colistinul','heterorezistenţa']),

q('sepsis-adv-074',['Conform Cadranului 8.8, dozele uzuale în sepsis includ:',
 ['piperacilină/tazobactam (4 g + 0,5 g) × 3 i.v.','gentamicină 5 mg/kg × 1 i.v.','amikacină 20 mg/kg × 1 i.v.','fosfomicină orală 3 g în doză unică','gentamicină 20 mg/kg × 1 i.v.'],'ABCD',162,'Cadranul 8.8 — Doze',
 'Recunoașterea dozelor standard din Cadranul 8.8.',
 ['Piperacilina/tazobactam (4 g + 0,5 g) × 3 i.v. este doza standard.','Gentamicina 5 mg/kg × 1 i.v. (maxim 7 mg/kg).','Amikacina 20 mg/kg × 1 i.v. (maxim 30 mg/kg).','Fosfomicina orală: 3 g doză unică.','20 mg/kg este doza amikacinei.']],
 [8,'Singurul distractor atribuie gentamicinei doza amikacinei.'],['20 mg/kg','5 mg/kg']),
q('sepsis-adv-058',['Conform Cadranului 8.2 (scorul SOFA), primesc 2 puncte:',
 ['creatinina de 110–170 µmol/L','trombocitele <100 × 10⁹/L','scorul Glasgow de 13–14','bilirubina de 33–101 µmol/L','scorul Glasgow de 10–12'],'BDE',155,'Cadranul 8.2 — Scorul SOFA',
 'Aplicarea treptelor scorului SOFA pe sisteme de organ.',
 ['Creatinina de 110–170 µmol/L valorează 1 punct.','Trombocitele <100 × 10⁹/L valorează 2 puncte.','Glasgow 13–14 valorează 1 punct.','Bilirubina de 33–101 µmol/L valorează 2 puncte.','Glasgow 10–12 valorează 2 puncte.']],
 [8,'Distractorii sunt treptele de 1 punct ale acelorași sisteme.'],['33-101','171-299']),
];
