import {rewriter} from './rewrite-author';
import {RETIRED_STOMAC} from './retired/stomac';

// Rewritten after the 2026-09-24 cue audit (Lawrence, cap. 13, p. 167–168, 172–174, 179–191).
const q=rewriter(RETIRED_STOMAC,(p:number)=>p<=168?p-70:p<=174?p-73:p-77,{shuffle:true});

export const STOMAC_V2=[
q('stomac-adv-067',['Stomacul are raporturi anatomice cu:',
 ['diafragmul, superior','splina și ficatul, inferior','pancreasul, posterior','colonul sigmoid, inferior','rinichiul drept, anterior'],'AC',167,'Anatomie — Stomacul',
 'Recunoașterea raporturilor anatomice ale stomacului.',
 ['Diafragmul este superior.','Nu: splina și ficatul sunt laterale.','Pancreasul este posterior.','Inferior se află marele epiploon.','Rinichiul drept nu este citat ca raport.']],
 [8,'Distractorii sunt organe abdominale vecine, dar cu orientare greșită.'],['diafr agmul','pancreasul posterior']),

q('stomac-adv-007',['La indivizii sănătoși, sfincterul esofagian inferior:',
 ['este intraperitoneal','are o lungime de peste 2 cm','rezistă la o presiune de cel mult 2 mm Hg','este retroperitoneal','are o lungime de peste 8 cm'],'AB',167,'Anatomie — Joncțiunea gastroesofagiană',
 'Fixarea parametrilor sfincterului esofagian inferior normal.',
 ['SEI este intraperitoneal.','Are >2 cm lungime.','Nu: rezistă la o presiune de peste 6 mm Hg.','SEI normal este intraperitoneal.','Lungimea citată este >2 cm.']],
 [8,'Distractorii deplasează poziția și lungimea sfincterului.'],['intraperitoneal','6 mm Hg']),

q('stomac-adv-001',['Celulele G producătoare de gastrină sunt localizate în:',
 ['antru','fundus','corpul gastric','pilor','cardia'],'A',167,'Anatomie — Regiunile stomacului',
 'Localizarea celulelor G și separarea de masa celulelor parietale.',
 ['Antrul conține celule G, dar nu celule parietale.','Fundusul asigură relaxarea receptivă și conține pacemakerul.','Corpul conține masa celulelor parietale, principale și ECL.','Pilorul este o valvă musculară.','Cardia nu este citată ca sediu al celulelor G.']],
 [8,'Distractorii sunt celelalte regiuni gastrice, cu funcții distincte.'],['celule G','nu şi celule parietale']),

q('stomac-adv-008',['Regiunile și peretele stomacului se caracterizează prin:',
 ['fundusul asigură relaxarea receptivă vagală','corpul conține majoritatea celulelor parietale','pacemakerul gastric este în stratul longitudinal antral','antrul conține celule parietale și celule G','musculara are două straturi, longitudinal și circular'],'AB',167,'Anatomie — Regiunile și peretele stomacului',
 'Atribuirea funcțiilor regiunilor și a straturilor peretelui gastric.',
 ['Stimularea vagală relaxează fundusul (relaxare receptivă).','Corpul conține cea mai mare parte a celulelor parietale.','Nu: stimulatorul gastric fundic este în stratul muscular circular.','Antrul conține celule G, dar nu parietale.','Musculara are trei straturi: longitudinal, circular și oblic.']],
 [8,'Distractorii omit stratul oblic și plasează parietalele în antru.'],['relaxare receptivă','oblic']),

q('stomac-adv-011',['Vascularizația arterială a stomacului cuprinde:',
 ['arterele gastrice dreaptă și stângă','arterele gastroepiploice dreaptă și stângă','arterele gastrice scurte','artera mezenterică inferioară','artera gastroduodenală'],'ABCE',167,'Anatomie — Vascularizația arterială',
 'Enumerarea arterelor stomacului.',
 ['Arterele gastrice dreaptă și stângă sunt citate.','Arterele gastroepiploice sunt citate.','Arterele gastrice scurte sunt citate, alături de gastroduodenală.','AMI irigă colonul stâng.','Artera gastroduodenală este citată alături de arterele gastrice scurte.']],
 [8,'Distractorii sunt artere digestive din teritorii vecine.'],['gastroepiploice','gastrice scurte']),

q('stomac-adv-009',['Inervația vagală a stomacului:',
 ['trunchiul vagal stâng intră anterior de esofag','vagul drept poate da nervul criminal al lui Grassi','vagul stâng trimite o ramură hepatică prin ligamentul gastrohepatic','trunchiul vagal stâng intră posterior de esofag','ramurile distale urmează mica curbură'],'ABCE',167,'Anatomie — Inervația vagală',
 'Descrierea traiectului vagilor și a ramurilor lor.',
 ['Trunchiul stâng intră anterior de esofag.','Vagul drept trimite uneori nervul criminal al lui Grassi.','Vagul stâng trimite ramura hepatică prin ligamentul gastrohepatic.','Trunchiul drept intră posterior.','Ramurile continuă de-a lungul micii curburi.']],
 [8,'Distractorii inversează partea și curbura.'],['nervul criminal','ligamentul gastrohepatic']),

q('stomac-adv-040',['Lezarea distală a nervului Latarjet determină:',
 ['pierderea relaxării pilorului','relaxarea permanentă a pilorului','denervarea izolată a colecistului și a căilor biliare','atonia izolată a fundusului','hipersecreție de gastrină'],'A',168,'Anatomie — Nervul Latarjet',
 'Recunoașterea consecinței leziunii distale a nervului Latarjet.',
 ['Pilorul pierde capacitatea de a se relaxa ca răspuns la stimuli fiziologici.','Efectul este inversul relaxării.','Ramura hepatică este cea care inervează colecistul.','Nu este consecința citată.','Nu este consecința citată.']],
 [8,'Distractorii sunt efecte ale altor ramuri vagale.'],['Latarjet','relaxa']),

q('stomac-adv-010',['Duodenul:',
 ['are o lungime de 25–30 cm','este în mare parte retroperitoneal','are ampula Vater deschisă anterolateral','se continuă cu jejunul la valva ileocecală','este în întregime intraperitoneal'],'AB',167,'Anatomie — Duodenul',
 'Descrierea anatomică a duodenului.',
 ['Duodenul are 25–30 cm.','Este situat în mare parte retroperitoneal.','Nu: ampula Vater se deschide posteromedial.','Continuarea cu jejunul este la ligamentul Treitz.','Devine intraperitoneal abia la ligamentul Treitz.']],
 [8,'Distractorii deplasează joncțiunea duodenojejunală și peritonizarea.'],['25-30 cm','posteromedial']),

q('stomac-adv-069',['Ca organ endocrin, duodenul:',
 ['secretă secretină','secretă colecistokinină','răspunde la acidul gastric și la grăsimile ingerate','secretă gastrină antrală','secretă pepsinogen'],'ABC',167,'Anatomie — Duodenul ca organ endocrin',
 'Recunoașterea funcției endocrine a duodenului.',
 ['Duodenul secretă secretină.','Duodenul secretă CCK.','Stimulii sunt acidul gastric și grăsimile ingerate.','Gastrina este produsă de celulele G antrale.','Pepsinogenul este produs de celulele principale gastrice.']],
 [8,'Distractorii sunt secreții gastrice, nu duodenale.'],['secretină','colecistokinină']),

q('stomac-adv-039',['Artera gastroduodenală:',
 ['este situată posterior de duoden','poate fi erodată de ulcere penetrante posterioare','este ramură a arterei splenice','provine din artera mezenterică superioară','trece prin ligamentul gastrohepatic'],'AB',168,'Anatomie — Artera gastroduodenală',
 'Localizarea arterei gastroduodenale și relevanța ei hemoragică.',
 ['Artera este situată posterior de duoden.','Ulcerele penetrante posterioare o pot eroda, cu hemoragie.','Nu: textul o descrie ca prima ramură a arterei hepatice.','AMS dă arcadele pancreaticoduodenale inferioare.','Prin ligamentul gastrohepatic trece ramura hepatică a vagului.']],
 [8,'Distractorii confundă originea arterei cu a arcadelor inferioare.'],['gastroduodenală','posterior de duoden']),

q('stomac-adv-037',['Secreția bazală de acid gastric:',
 ['are nivel maxim în timpul nopții','are nivel maxim dimineața','este absentă în afara meselor','este produsă de celulele principale','nu variază circadian'],'A',168,'Fiziologie — Secreția de acid clorhidric',
 'Recunoașterea ritmului circadian al secreției acide bazale.',
 ['Secreția bazală are ritm circadian, maximă noaptea.','Nivelurile sunt inferioare dimineața.','Acidul este secretat și bazal.','Acidul este secretat de celulele parietale.','Secreția are ritm circadian.']],
 [8,'Distractorii inversează ritmul circadian.'],['ritm circadian','nopţii']),

q('stomac-adv-041',['Secreția acidă gastrică:',
 ['este proporțională cu masa celulelor parietale','este inhibată de IPP, la nivelul pompei de protoni','are faze cefalică, gastrică și intestinală','este independentă de masa celulelor parietale','este stimulată de inhibitorii pompei de protoni'],'ABC',168,'Fiziologie — Mecanisme de stimulare',
 'Recunoașterea determinanților și a blocării secreției acide.',
 ['Capacitatea secretorie este aproape liniar asociată cu masa parietală.','IPP blochează pompele de protoni.','Secreția are trei faze: cefalică, gastrică și intestinală.','Secreția depinde de masa parietală.','IPP inhibă producția de acid.']],
 [8,'Distractorii contrazic relația cu masa parietală și mecanismul IPP.'],['masa celulară parietală','pompele de protoni']),

q('stomac-adv-038',['Faza cefalică a secreției acide:',
 ['este mediată de sistemul nervos central','este stimulată de vederea sau mirosul alimentelor','este transmisă prin nervii splanhnici','este mediată de secretină și CCK','este abolită de antrectomie, nu de vagotomie'],'AB',168,'Fiziologie — Faza cefalică',
 'Descrierea mecanismului fazei cefalice.',
 ['Faza cefalică este mediată de SNC.','Este stimulată de vederea, mirosul sau ideea alimentelor.','Nu: eferența pornește de la hipotalamus prin vag.','Secretina și CCK sunt hormoni duodenali.','Vagotomia, nu antrectomia, inhibă acest răspuns.']],
 [8,'Distractorii confundă faza cefalică cu mecanisme intestinale sau cu alt gest chirurgical.'],['cefalică','hipotalamus']),

q('stomac-adv-012',['Sindromul Mallory-Weiss:',
 ['este o ruptură liniară a mucoasei la joncțiunea gastroesofagiană','apare după o manevră Valsalva intensă','necesită hemostază endoscopică în majoritatea cazurilor','este o ruptură transmurală a esofagului toracic','se tratează inițial chirurgical'],'AB',172,'Sindromul Mallory-Weiss',
 'Recunoașterea mecanismului și conduitei în sindromul Mallory-Weiss.',
 ['Este o ruptură liniară a mucoasei la joncțiunea GE.','Apare după Valsalva intens: vărsături, alcool, naștere, greutăți, convulsii.','Nu: majoritatea sângerărilor se opresc fără alte intervenții.','Leziunea este mucoasă, nu transmurală.','Chirurgia este ultima soluție.']],
 [8,'Distractorii confundă leziunea cu sindromul Boerhaave.'],['Mallo','Valsalva']),

q('stomac-adv-027',['În gastrita hemoragică cu sângerare persistentă:',
 ['angiografia selectivă cu embolizare este o opțiune','sutura in situ controlează hemoragia la aproximativ 50%','gastrectomia totală urmează dacă sângerarea reapare','sutura in situ controlează hemoragia la aproximativ 90%','sutura in situ se poate asocia cu vagotomie și piloroplastie'],'ABCE',172,'Gastrita hemoragică — Sângerarea persistentă',
 'Ierarhizarea conduitei în gastrita hemoragică persistentă.',
 ['Angiografia selectivă (de obicei gastrica stângă) cu embolizare este o opțiune.','Sutura in situ, cu sau fără vagotomie și piloroplastie, controlează hemoragia la aproximativ 50%.','Gastrectomia totală este linia următoare dacă sângerarea continuă.','Proporția citată este de aproximativ 50%.','Sutura in situ se poate face cu sau fără vagotomie și piloroplastie.']],
 [8,'Distractorii umflă eficiența suturii și inversează ordinea.'],['gastrice stângi','50%']),

q('stomac-adv-013',['Polipii gastrici:',
 ['hiperplastici sunt mai frecvenți și de obicei benigni','adenomatoși au risc mai mare de degenerare sub 0,5 cm','impun căutarea altor polipi și a sindroamelor polipozice','hiperplastici au risc malign mai mare decât adenomatoșii','adenomatoși sunt hamartoame fără potențial malign'],'AC',172,'Polipii gastrici',
 'Diferențierea polipilor gastrici hiperplastici de cei adenomatoși.',
 ['Polipii hiperplastici sunt mai frecvenți și de obicei benigni.','Nu: riscul adenomatoșilor crește mai ales peste 1,5 cm.','Trebuie căutați alți polipi GI și sindroame polipozice.','Riscul mai mare aparține polipilor adenomatoși.','Hamartoamele caracterizează sindromul Peutz-Jeghers.']],
 [8,'Distractorii inversează riscul celor două tipuri histologice.'],['hiperplastici','1,5 cm']),

q('stomac-adv-042',['Sindromul Peutz-Jeghers:',
 ['este autozomal dominant, cu penetrabilitate ridicată','are polipi hamartomatoși, rareori maligni','are pete de melanină pe buze și mucoasa bucală','se tratează de regulă conservator','are polipi adenomatoși cu risc malign înalt'],'ABCD',172,'Polipii gastrici — Sindromul Peutz-Jeghers',
 'Recunoașterea caracteristicilor sindromului Peutz-Jeghers.',
 ['Este autozomal dominant, cu penetrabilitate ridicată.','Tumorile sunt hamartoame, rareori maligne.','Petele de melanină pe buze și mucoasa bucală sunt caracteristice.','Managementul conservator este adecvat.','Polipii sunt hamartomatoși.']],
 [8,'Distractorii confundă sindromul cu polipoza adenomatoasă.'],['Peutz-Jeghers','melanină']),

q('stomac-adv-043',['Epidemiologia adenocarcinomului gastric:',
 ['aproximativ 95% din cancerele de stomac sunt adenocarcinoame','incidența a scăzut constant în ultimii 50 de ani','emigranții din zonele cu risc au incidență mai mică în SUA','incidența este mult mai mare în Asia','incidența a crescut constant în ultimii 50 de ani'],'ABCD',172,'Adenocarcinomul gastric — Epidemiologie',
 'Recunoașterea datelor epidemiologice ale adenocarcinomului gastric.',
 ['Aproximativ 95% sunt adenocarcinoame.','Incidența generală a scăzut constant în ultimii 50 de ani.','Emigranții stabiliți în SUA au incidență mai mică, alimentația fiind incriminată.','Incidența este considerabil mai mare în Asia (Japonia, China).','Incidența a scăzut.']],
 [8,'Distractorii inversează tendința și geografia bolii.'],['95%','emigranţii']),

q('stomac-adv-072',['Factorii de risc pentru adenocarcinomul gastric includ:',
 ['infecția cu H. pylori','anemia pernicioasă','leziunile caustice în antecedente','tiloza palmoplantară ereditară','sindromul Plummer-Vinson'],'ABC',172,'Adenocarcinomul gastric — Factori de risc',
 'Enumerarea factorilor de risc ai adenocarcinomului gastric.',
 ['H. pylori este factor de risc.','Anemia pernicioasă și achlorhidria sunt factori de risc.','Leziunile caustice prin sodă caustică cresc riscul.','Tiloza este factor de risc pentru carcinomul scuamos esofagian.','Plummer-Vinson este factor de risc pentru carcinomul scuamos esofagian.']],
 [8,'Distractorii sunt factori de risc ai carcinomului esofagian.'],['H. pylori','sodă caustică']),

q('stomac-adv-002',['Adenocarcinomul gastric de tip difuz:',
 ['este slab diferențiat, cu celule în inel cu pecete','apare la pacienți mai tineri','se asociază cu grupa sanguină 0','diseminează predominant hematogen','are un prognostic mai bun decât tipul intestinal'],'AB',172,'Adenocarcinomul gastric — Tipuri histologice',
 'Diferențierea tipului difuz de tipul intestinal.',
 ['Tipul difuz este slab diferențiat, cu celule în inel cu pecete.','Apare la pacienți mai tineri.','Nu: se asociază cu grupa de sânge A.','Diseminarea hematogenă caracterizează tipul intestinal.','Prognosticul mai bun aparține tipului intestinal.']],
 [8,'Distractorii sunt trăsăturile tipului intestinal.'],['inel cu pecete','grupa de sânge A']),

q('stomac-adv-070',['Clasificarea endoscopică a cancerelor gastrice:',
 ['cuprinde forme ulcerate, polipoide, schiroase și extinse superficial','are carcinoamele ulcerate drept cea mai frecventă formă','are o valoare prognostică excelentă','are formele polipoide drept cea mai frecventă formă','înlocuiește clasificarea histologică în stabilirea prognosticului'],'AB',172,'Adenocarcinomul gastric — Clasificare endoscopică',
 'Recunoașterea formelor endoscopice și a valorii lor prognostice.',
 ['Formele endoscopice sunt ulcerate, polipoide, schiroase sau extinse superficial.','Carcinoamele ulcerate sunt de departe cele mai frecvente.','Nu: valoarea prognostică a sistemului este limitată.','Forma ulcerată este cea mai frecventă.','Valoarea prognostică este limitată.']],
 [8,'Distractorii supraestimează valoarea prognostică și schimbă forma dominantă.'],['ulcerate','valoarea prognostică']),

q('stomac-adv-003',['Semnele de diseminare a cancerului gastric la examenul fizic includ:',
 ['nodulul supraclavicular stâng (Virchow)','nodulul ombilical (Sister Mary Joseph)','formațiunea rectală palpabilă (Blumer)','nodulul supraclavicular drept','hepatomegalia dureroasă, ca semn izolat de diseminare'],'ABC',173,'Adenocarcinomul gastric — Tablou clinic',
 'Recunoașterea semnelor clinice de boală gastrică diseminată.',
 ['Nodulul Virchow indică diseminarea.','Nodulul Sister Mary Joseph indică diseminarea.','Semnul Blumer sugerează diseminare peritoneală.','Nodulul citat este supraclavicular stâng.','Nu este semnul citat.']],
 [8,'Distractorii schimbă lateralitatea semnului Virchow.'],['Virchow','Blumer']),

q('stomac-adv-095',['Laparoscopia de stadializare în cancerul gastric:',
 ['identifică leziuni peritoneale, hepatice sau omentale','include lavaj peritoneal','este practicată de rutină la toți pacienții','este inutilă, CT-ul detectând ușor metastazele peritoneale','nu modifică indicația de rezecție curativă'],'AB',173,'Adenocarcinomul gastric — Stadializare',
 'Aplicarea rolului laparoscopiei de stadializare.',
 ['Explorarea identifică leziuni peritoneale, hepatice sau omentale.','Se practică lavaj peritoneal.','Nu: majoritatea chirurgilor o practică selectiv.','Metastazele peritoneale sunt greu de identificat pe CT.','Metastazele sau lavajul pozitiv contraindică rezecția curativă.']],
 [8,'Distractorii supraestimează CT-ul și neagă impactul terapeutic.'],['lavaj peritoneal','selectiv']),

q('stomac-adv-044',['În adenocarcinomul gastric distal localizat:',
 ['intervenția electivă este gastrectomia subtotală radicală','se îndepărtează aproximativ 85% din stomac și marele epiploon','marginea proximală se verifică extemporaneu înainte de reconstrucție','gastrectomia totală este regula pentru orice leziune antrală','gastrectomia totală se face la leziunile distale întinse'],'ABCE',173,'Adenocarcinomul gastric — Tratament chirurgical',
 'Aplicarea rezecției curative pentru leziunile distale.',
 ['Pentru leziunile distale, intervenția electivă este gastrectomia subtotală radicală.','Se îndepărtează aproximativ 85% din stomac și marele epiploon.','Examenul extemporaneu al marginii proximale precede reconstrucția.','Gastrectomia totală se face pentru leziuni distale întinse sau proximale.','Gastrectomia totală se face pentru leziuni distale întinse sau proximale.']],
 [8,'Distractorii schimbă extinderea rezecției și ordinea pașilor.'],['85%','Roux-en-Y']),

q('stomac-adv-074',['Pentru o rezecție gastrică curativă, pot fi incluse în bloc, când este necesar:',
 ['splenectomia','pancreatectomia distală','colectomia parțială','duodenopancreatectomia cefalică','hepatectomia dreaptă'],'ABC',173,'Adenocarcinomul gastric — Rezecția în bloc',
 'Identificarea organelor care pot fi incluse în rezecția în bloc.',
 ['Splenectomia poate fi inclusă.','Pancreatectomia distală poate fi inclusă.','Colectomia parțială poate fi inclusă.','Nu este citată.','Nu este citată.']],
 [8,'Distractorii sunt rezecții majore vecine, necitate.'],['splenectomia','colectomia']),

q('stomac-adv-045',['Limfadenectomia și terapia adjuvantă în cancerul gastric:',
 ['japonezii au abandonat limfadenectomia extinsă','în Occident, disecțiile extinse cresc morbiditatea fără beneficiu clar','chimioterapia preoperatorie se recomandă la invazie dincolo de lamina propria','în Occident, limfadenectomia extinsă a dublat supraviețuirea','leziunile limitate la submucoasă necesită de regulă neoadjuvant'],'BC',173,'Adenocarcinomul gastric — Limfadenectomie și adjuvanță',
 'Compararea practicii japoneze și occidentale și a indicațiilor neoadjuvante.',
 ['Nu: japonezii susțin limfadenectomia dincolo de ganglionii perigastrici.','Țările occidentale nu au replicat beneficiul; disecțiile extinse cresc morbiditatea.','Chimioterapia preoperatorie se recomandă la invazie dincolo de lamina propria sau N+.','Rezultatele japoneze nu au fost replicate în Occident.','Leziunile limitate la submucoasă pot fi excizate fără neoadjuvant.']],
 [8,'Distractorii generalizează rezultatele japoneze și extind neoadjuvantul.'],['limfadenectomia radicală','lamina propria']),

q('stomac-adv-096',['Stadializarea patologică postoperatorie a cancerului gastric:',
 ['este cel mai bun predictor al supraviețuirii','ghidează îngrijirea postoperatorie','folosește examinarea macroscopică și microscopică a piesei','este inferioară clasificării endoscopice','se bazează pe tranzitul baritat postoperator'],'ABC',173,'Adenocarcinomul gastric — Stadializarea patologică',
 'Recunoașterea rolului stadializării patologice.',
 ['Este cel mai bun predictor al supraviețuirii.','Este cel mai bun ghid pentru îngrijirea postoperatorie.','Folosește examinarea macroscopică și microscopică a piesei.','Clasificarea endoscopică are valoare prognostică limitată.','Se bazează pe piesa de rezecție.']],
 [8,'Distractorii înlocuiesc piesa cu investigații de valoare mai mică.'],['cel mai bun predictor','macroscopice']),

q('stomac-adv-014',['Prognosticul adenocarcinomului gastric:',
 ['chiar în forma superficială din Japonia, supraviețuirea la 5 ani este sub 50%','după rezecție curativă în țările anglofone, supraviețuirea la 5 ani este sub 10%','cancerul descoperit incidental, fără metastaze, se apropie de 25% la 5 ani','rezecția curativă din Occident depășește 50% supraviețuire la 5 ani','forma superficială din Japonia depășește 90% supraviețuire la 5 ani'],'AB',174,'Adenocarcinomul gastric — Prognostic',
 'Fixarea cifrelor de supraviețuire în cancerul gastric.',
 ['Chiar în forma superficială, supraviețuirea la 5 ani este sub 50%.','În țările anglofone, rezecția curativă are supraviețuire sub 10% la 5 ani.','Nu: carcinomul descoperit incidental se apropie de 75% la 5 ani.','Supraviețuirea citată este sub 10%.','Supraviețuirea este sub 50%.']],
 [8,'Distractorii umflă cifrele de supraviețuire.'],['<50%','75%']),

q('stomac-adv-076',['Paliația adenocarcinomului gastric avansat:',
 ['rezecțiile paliative se limitează la obstrucție sau sângerare','include stentul endoscopic și terapia cu laser','chimioterapia și radioterapia oferă puțin ajutor în aceste cazuri','rezecția paliativă extinsă este regula în boala metastatică','rezecția paliativă este opțională, axată pe calitatea vieții'],'ABCE',174,'Adenocarcinomul gastric — Paliație',
 'Recunoașterea opțiunilor paliative în cancerul gastric avansat.',
 ['Rezecțiile paliative se limitează la derivații pentru obstrucție sau controlul sângerării.','Stentul endoscopic și laserul sunt proceduri paliative.','Chimioterapia și radioterapia oferă puțin ajutor.','Rezecția paliativă este opțională, axată pe calitatea vieții.','Rezecția paliativă este opțională, axată pe calitatea vieții.']],
 [8,'Distractorii supraestimează rezecția și chimioterapia în paliație.'],['derivaţii','terapia cu laser']),

q('stomac-adv-016',['Limfomul gastric:',
 ['este localizat în stomac în aproape două treimi din limfoamele GI','este predominant non-Hodgkin, la vârstnici','se tratează majoritar prin gastrectomie totală','este predominant Hodgkin, la tineri','nu se asociază cu risc de perforație sub chimioterapie'],'AB',174,'Limfomul gastric',
 'Recunoașterea caracteristicilor și a tratamentului limfomului gastric.',
 ['Stomacul găzduiește aproape două treimi din limfoamele GI.','Tipul predominant este non-Hodgkin, la vârstnici.','Nu: majoritatea specialiștilor pledează pentru chimioterapie.','Tipul predominant este non-Hodgkin.','Chimioterapia poate provoca perforație sau hemoragie.']],
 [8,'Distractorii inversează tipul histologic și riscul terapeutic.'],['două treimi','non-Hodgkin']),

q('stomac-adv-004',['Tumorile stromale gastrointestinale (GIST) gastrice:',
 ['sugerează malignitate la dimensiuni peste 6 cm','sunt maligne dacă au peste 10 mitoze la 50 de câmpuri','metastazează cel mai frecvent în ganglionii regionali','au frecvent invazie ganglionară','sunt diagnosticate de regulă prin biopsie endoscopică'],'AB',174,'Tumori stromale gastrointestinale',
 'Recunoașterea criteriilor de malignitate și a diseminării GIST.',
 ['Dimensiunea >6 cm și necroza sugerează comportament malign.','Peste 10 mitoze la 50 de câmpuri de mare putere dovedesc malignitatea.','Nu: ficatul este cel mai frecvent loc; invazia ganglionară este rară.','Invazia ganglionară este rară.','Biopsia este de obicei nondiagnostică.']],
 [8,'Distractorii aplică GIST regulile adenocarcinomului.'],['necroza tumorală','Ficatul este cel mai frecvent']),

q('stomac-adv-047',['Tratamentul GIST gastric:',
 ['constă în excizie locală','include o marjă de 2–3 cm la tumorile mari','poate folosi imatinib preoperator pentru tumorile mari invazive','impune gastrectomie totală cu limfadenectomie D2','folosește testarea c-KIT și PDGFRA'],'ABCE',174,'Tumori stromale gastrointestinale — Tratament',
 'Aplicarea tratamentului chirurgical și medical al GIST.',
 ['Tratamentul implică excizie locală.','La tumorile mari se include o marjă de 2–3 cm.','Imatinibul preoperator poate reduce stadiul tumorilor mari invazive.','Invazia ganglionară este rară; limfadenectomia nu este regula.','Testarea c-KIT și PDGFRA ajută la estimarea eficienței imatinibului.']],
 [8,'Distractorii aplică GIST principii oncologice ale adenocarcinomului.'],['2-3 cm','imatinib']),

q('stomac-adv-077',['Ulcerul duodenal necomplicat:',
 ['apare de obicei în bulbul duodenal','are ca factori de risc H. pylori și AINS','se transformă rareori malign','se transformă frecvent malign','apare de obicei pe a treia porțiune a duodenului'],'ABC',174,'Afecțiuni duodenale benigne — Ulcerul duodenal',
 'Recunoașterea sediului, factorilor de risc și a riscului malign.',
 ['Ulcerul duodenal apare de obicei la nivelul bulbului.','H. pylori, AINS și tutunul sunt factori de risc.','Rareori se transformă malign, spre deosebire de ulcerul gastric.','Transformarea malignă este rară.','Sediul tipic este bulbul.']],
 [8,'Distractorii aplică ulcerului duodenal riscul ulcerului gastric.'],['bulbului duodenal','rareori se transformă malign']),

q('stomac-adv-046',['Durerea ulcerului duodenal necomplicat, spre deosebire de ulcerul gastric:',
 ['apare la 1–3 ore după mese, și noaptea','este maximă în timpul mesei','se asociază tipic cu scădere ponderală prin teamă de a mânca','este agravată de antiacide','este independentă de alimentație'],'A',174,'Ulcerul duodenal — Tablou clinic',
 'Diferențierea clinică a durerii ulceroase duodenale.',
 ['Durerea este mai intensă în post, la 1–3 ore după mese, și trezește din somn.','Nu este caracteristica duodenală.','Mesele ameliorează durerea, cu posibilă creștere ponderală.','Antiacidele ameliorează durerea.','Durerea este legată de post și de mese.']],
 [8,'Distractorii descriu durerea ulcerului gastric.'],['1-3 ore','trezeşte']),

q('stomac-adv-021',['Vagotomia supraselectivă, în locul celei tronculare, este avantajoasă la pacienții cu risc crescut de complicații postgastrectomie, în special la:',
 ['femeile tinere și slabe','bărbații vârstnici obezi','pacienții cu ulcer gastric','pacienții cu MEN-1','pacienții fumători'],'A',179,'Chirurgia bolii ulceroase — Pacienții vulnerabili',
 'Identificarea pacienților vulnerabili la sindroame postgastrectomie.',
 ['Femeile tinere și slabe sunt deosebit de vulnerabile.','Nu este grupul citat.','Nu este grupul citat.','Nu este grupul citat.','Nu este grupul citat.']],
 [8,'Distractorii sunt grupuri plauzibile clinic, dar necitate.'],['femeile tinere','vagotomiei supraselective']),

q('stomac-adv-018',['Polipii duodenali din polipoza adenomatoasă familială:',
 ['impun supraveghere endoscopică gastroduodenală','impun excizie dacă conțin cancer sau adenom vilos','se asociază de obicei cu colectomie profilactică precoce','au potențial de degenerare malignă','se tratează conservator, fără supraveghere endoscopică'],'ABCD',179,'Polipii duodenali',
 'Aplicarea supravegherii și tratamentului polipilor duodenali în PAF.',
 ['Toți pacienții au nevoie de supraveghere endoscopică de rutină, cu polipectomie.','Cancerul sau adenomul vilos impun excizie chirurgicală.','Majoritatea necesită colectomie profilactică precoce.','Polipii au potențial de degenerare malignă.','Supravegherea endoscopică este necesară.']],
 [8,'Distractorii subestimează potențialul malign al polipilor din PAF.'],['adenomului vilos','supraveghere endoscopică']),

q('stomac-adv-005',['Sindromul Zollinger-Ellison:',
 ['are peste două treimi dintre gastrinoame în triunghiul gastrinomului','are gastrina à jeun peste 100 pg/mL diagnostică','are aproximativ 60% din gastrinoame maligne','se diagnostichează sub IPP, fără întreruperea tratamentului','are gastrinoamele maligne în aproximativ 10% din cazuri'],'AC',179,'Sindromul Zollinger-Ellison',
 'Aplicarea criteriilor de diagnostic și a datelor despre gastrinom.',
 ['Peste două treimi sunt în triunghiul gastrinomului.','Nu: pragul diagnostic este >1.000 pg/mL.','Aproximativ 60% dintre gastrinoame sunt maligne.','IPP se oprește cu cel puțin o săptămână înainte, deoarece cresc gastrina.','Proporția citată este de aproximativ 60%.']],
 [8,'Distractorii ignoră efectul IPP și subestimează malignitatea.'],['triunghiul gastrinomului','1.000 pg/mL']),

q('stomac-adv-048',['Suspiciunea de sindrom Zollinger-Ellison este ridicată de:',
 ['simptome ulceroase cu diaree cronică','ulcere duodenale multiple','ulcerații în jejun sau ileon','ulcer unic al bulbului duodenal','dispepsie fără ulcer'],'ABC',179,'Sindromul Zollinger-Ellison — Tablou clinic',
 'Recunoașterea tabloului clinic care sugerează gastrinomul.',
 ['Simptomele ulceroase cu diaree cronică sugerează diagnosticul.','Ulcerele duodenale multiple sunt sugestive.','Ulcerațiile în localizări atipice (jejun, ileon) sunt sugestive.','Ulcerul unic bulbar este forma banală.','Nu este element de suspiciune.']],
 [8,'Distractorii sunt prezentări obișnuite ale bolii ulceroase.'],['diaree cronică','localizări atipice']),

q('stomac-adv-078',['Localizarea gastrinomului se bazează pe:',
 ['tomografia computerizată și IRM','scintigrafia receptorilor somatostatinici','ecografia endoscopică','colangiografia retrogradă endoscopică','tranzitul baritat'],'ABC',179,'Sindromul Zollinger-Ellison — Localizare',
 'Identificarea investigațiilor de localizare a gastrinomului.',
 ['CT, IRM și ultrasonografia sunt citate.','Scintigrafia receptorului de somatostatină este citată.','Ecografia endoscopică este citată.','Nu este citată.','Nu este citată.']],
 [8,'Distractorii sunt investigații digestive fără rol de localizare.'],['somatostatină','ecografia endoscopică']),

q('stomac-adv-079',['În tratamentul sindromului Zollinger-Ellison:',
 ['tratamentul începe cu IPP în doze mari','antagoniștii H2 au devenit linia a doua','gastrectomia totală este astăzi foarte rar practicată','gastrectomia totală rămâne tratamentul de primă intenție','antagoniștii H2 sunt tratamentul de primă intenție'],'ABC',179,'Sindromul Zollinger-Ellison — Tratament',
 'Aplicarea ierarhiei terapeutice în sindromul Zollinger-Ellison.',
 ['Tratamentul începe cu IPP în doze mari.','Antagoniștii H2 au devenit terapia de linia a doua.','Gastrectomia totală este o intervenție foarte rar practicată.','Gastrectomia totală a fost abandonată ca rutină.','IPP sunt prima linie.']],
 [8,'Distractorii reflectă practica istorică.'],['IPP în doze mari','foarte rar practicată'],[180]),

q('stomac-adv-028',['În gastrinomul asociat MEN-1 sau metastatic:',
 ['paratiroidectomia scade eliberarea de gastrină','octreotidul stimulează eliberarea de gastrină','IPP se continuă dacă rezecția este incompletă','paratiroidectomia crește eliberarea de gastrină','IPP se opresc după diagnosticul de boală metastatică'],'AC',180,'Sindromul Zollinger-Ellison — MEN-1 și boala metastatică',
 'Conduita în gastrinomul din MEN-1 și în boala metastatică.',
 ['Paratiroidectomia favorizează diminuarea eliberării de gastrină.','Nu: octreotidul suprimă gastrina și încetinește creșterea tumorii.','Toți pacienții cu rezecție incompletă sau metastaze necesită IPP continuu.','Efectul este de scădere.','IPP continuă în boala metastatică.']],
 [8,'Distractorii inversează efectul paratiroidectomiei și rolul IPP.'],['paratiroidectomiea','octreotidul']),

q('stomac-adv-017',['Adenocarcinomul duodenal:',
 ['duodenul este sediul său cel mai frecvent în intestinul subțire','aproximativ două treimi sunt pe D2, periampular','la N+, supraviețuirea la 5 ani este sub 15%','aproximativ două treimi sunt pe a patra porțiune','la N+, supraviețuirea la 5 ani depășește 50%'],'ABC',180,'Adenocarcinomul duodenal',
 'Recunoașterea sediului și prognosticului adenocarcinomului duodenal.',
 ['Duodenul este cea mai frecventă localizare în intestinul subțire.','Aproximativ două treimi sunt pe D2, periampular.','La ganglioni pozitivi, supraviețuirea la 5 ani este sub 15%.','Sediul dominant este D2.','Supraviețuirea este sub 15%.']],
 [8,'Distractorii deplasează sediul și prognosticul.'],['două treimi','15%']),

q('stomac-adv-019',['Evaluarea unui sindrom postgastrectomie folosește:',
 ['tranzitul baritat','masa marcată cu radionuclizi','endoscopia cu biopsie','manometria anorectală','colonoscopia virtuală'],'ABC',180,'Sindroame postgastrectomie — Evaluare',
 'Alegerea investigațiilor pentru sindroamele postgastrectomie.',
 ['Tranzitul baritat documentează rezecția, reconstrucția și evacuarea.','Masa marcată cu radionuclizi evaluează mai fiziologic evacuarea.','Endoscopia permite vizualizare directă și biopsie.','Nu este relevantă.','Nu este relevantă.']],
 [8,'Distractorii sunt investigații digestive fără rol aici.'],['radionuclizi','Endoscopia']),

q('stomac-adv-006',['Comparativ cu dumpingul tardiv, dumpingul precoce:',
 ['debutează la 15–30 de minute după masă','asociază doar simptome vasomotorii, fără greață','se datorează golirii rapide a conținutului hiperosmolar','se datorează hipoglicemiei hiperinsulinemice','debutează la 1–3 ore după masă'],'AC',180,'Dumpingul precoce și tardiv — Tabelul 13-2',
 'Diferențierea dumpingului precoce de cel tardiv.',
 ['Debutul este la 15–30 de minute.','Nu: asociază simptome abdominale și vasomotorii.','Mecanismul este golirea rapidă hiperosmolară, cu eliberare de substanțe vasoactive.','Hipoglicemia hiperinsulinemică explică dumpingul tardiv.','1–3 ore este debutul dumpingului tardiv.']],
 [8,'Distractorii sunt trăsăturile dumpingului tardiv.'],['15-30 minute','hiperosmolar'],[181]),

q('stomac-adv-080',['În dumpingul precoce:',
 ['se incriminează serotonina, neurotensina și histamina','analogul de somatostatină poate bloca aceste substanțe','se recomandă mese frecvente cu volum mic','lichidele se administrează înaintea mesei','propranololul rămâne tratamentul de primă intenție'],'ABCD',180,'Dumpingul precoce — Mecanisme și tratament',
 'Recunoașterea mediatorilor și a măsurilor terapeutice în dumpingul precoce.',
 ['Serotonina, neurotensina, histamina și alte substanțe contribuie la simptome.','Analogul de somatostatină poate bloca aceste substanțe.','Se recomandă mese frecvente, mici (ex. 6 pe zi).','Lichidele se dau înainte de masă sau la cel puțin 30 de minute după.','Propranololul a fost înlocuit de somatostatină.']],
 [8,'Distractorii reflectă recomandări abandonate sau inversate.'],['serotonină','somatostatină']),

q('stomac-adv-081',['Tratamentul dumpingului tardiv include:',
 ['o gustare mică la 2 ore după masă','acarboza, inhibitor de α-glucozidază','conversia la Billroth I sau Roux-en-Y, la refractari','propranololul cu 20 de minute înaintea meselor','reducerea aportului de grăsimi la fiecare masă'],'ABC',181,'Dumpingul tardiv — Tratament',
 'Aplicarea tratamentului conservator și chirurgical al dumpingului tardiv.',
 ['O gustare mică la 2 ore după masă ameliorează simptomele.','Acarboza este folosită în prezent.','Conversia la Billroth I sau Roux-en-Y este necesară dacă tratamentul conservator eșuează.','Propranololul a fost folosit în dumpingul precoce.','Grăsimile se recomandă în dumpingul precoce, pentru a încetini golirea.']],
 [8,'Distractorii sunt măsuri aplicate dumpingului precoce.'],['acarboza','gustări']),

q('stomac-adv-020',['Diareea post-vagotomie:',
 ['apare, sub formă modificată, la aproape jumătate dintre vagotomiile tronculare','este severă și refractară la sub 1% dintre pacienți','poate fi explozivă, necorelată cu mesele','apare tipic la 1–3 ore după masă, prin hipoglicemie','este severă la majoritatea pacienților'],'ABC',181,'Diareea post-vagotomie',
 'Recunoașterea frecvenței și caracteristicilor diareei post-vagotomie.',
 ['Aproape jumătate au modificarea tranzitului.','Sub 1% au diaree severă care nu se ameliorează.','Diareea poate avea debut exploziv, necorelat cu mesele.','Mecanismul hipoglicemic descrie dumpingul tardiv.','Forma severă este rară.']],
 [8,'Distractorii confundă diareea post-vagotomie cu dumpingul tardiv.'],['vagotomie tronculară','exploziv']),

q('stomac-adv-049',['În diareea post-vagotomie severă, refractară, se poate monta:',
 ['un segment jejunal antiperistaltic de 10 cm','un segment jejunal izoperistaltic de 40 cm','o ansă Roux lungă, de 40 cm','o piloroplastie Heineke-Mikulicz izolată','o gastrojejunostomie Billroth II'],'A',181,'Diareea post-vagotomie — Tratament chirurgical',
 'Identificarea montajului chirurgical pentru diareea refractară.',
 ['Segment jejunal antiperistaltic de 10 cm, la 100 cm de unghiul Treitz.','Nu este montajul citat.','40 cm este distanța minimă Roux în gastrita de reflux alcalin.','Nu întârzie tranzitul intestinal.','Nu este montajul citat.']],
 [8,'Distractorii folosesc cifre reale din alte montaje.'],['antiperistaltic','Treitz']),

q('stomac-adv-031',['Stenoza ansei aferente după Billroth II se caracterizează prin:',
 ['crampe severe imediat postprandial','vărsătură amară, fără alimente, ca uleiul de motor','agravarea durerii abdominale după vărsătură','hipoglicemie la 1–3 ore după masă','vărsătură alimentară, fără conținut biliar'],'AB',181,'Stenoza ansei aferente',
 'Recunoașterea tabloului stenozei ansei aferente.',
 ['Crampele severe apar imediat după masă.','Vărsătura este brun-închisă, amară, fără alimente, ca uleiul de motor.','Nu: simptomele se ameliorează după vărsătură.','Hipoglicemia descrie dumpingul tardiv.','Vărsătura nu conține alimente.']],
 [8,'Distractorii contrazic caracterul biliar al vărsăturii.'],['uleiului de motor','ansei aferente']),

q('stomac-adv-050',['Sindromul de ansă oarbă:',
 ['este mai frecvent după Billroth II decât după Roux-en-Y','produce anemie megaloblastică prin deficit de B12','se tratează cu antibiotice orale cu spectru aerob și anaerob','are testul Schilling normal înaintea tratamentului','recidivează frecvent după antibioterapie'],'ABCE',181,'Sindromul de ansă oarbă',
 'Recunoașterea mecanismului și tratamentului sindromului de ansă oarbă.',
 ['Este mai frecvent după Billroth II.','Bacteriile interferă cu B12 și folatul, cu anemie megaloblastică.','Tratamentul folosește antibiotice orale cu spectru larg (ex. tetraciclină).','Testul Schilling este adesea anormal.','Regenerarea bacteriană este frecventă; antibioterapia doar temporizează.']],
 [8,'Distractorii contrazic evoluția testului Schilling și recidiva.'],['ansă oarbă','Schilling']),

q('stomac-adv-032',['Gastrita de reflux alcalin:',
 ['are la endoscopie epiteliu edemațiat, pătat bilios','are la biopsie vase submucoase în tirbușon','se corectează prin Roux-en-Y cu ansă de cel puțin 40 cm','răspunde inconstant la tratamentul medical','se corectează prin Roux-en-Y cu ansă de 10 cm'],'ABCD',182,'Gastrita de reflux alcalin',
 'Recunoașterea aspectului și a corecției chirurgicale a gastritei de reflux alcalin.',
 ['Endoscopia arată epiteliu edemațiat, pătat bilios, atrofic și eritematos.','Biopsia arată vase submucoase în tirbușon.','Distanța minimă a ansei Roux este 40 cm.','Niciun regim medical nu este uniform satisfăcător.','Distanța minimă este 40 cm.']],
 [8,'Distractorii scurtează ansa Roux și supraestimează tratamentul medical.'],['tirbuşon','40  cm']),

q('stomac-adv-051',['Ulcerul marginal după gastrojejunostomie:',
 ['apare pe versantul jejunal al anastomozei','are ca etiologie principală gastrinomul','se tratează inițial prin oprirea fumatului și IPP','apare pe versantul gastric al anastomozei','impune revizie chirurgicală de primă intenție'],'AC',182,'Ulcerul marginal',
 'Recunoașterea sediului, etiologiei și tratamentului ulcerului marginal.',
 ['Ulcerul marginal apare pe partea jejunală a anastomozei.','Nu: etiologia este de obicei ischemia; fumatul contribuie.','Prima linie: oprirea fumatului și IPP.','Sediul este jejunal.','Revizia se face doar la ulcerul refractar.']],
 [8,'Distractorii schimbă versantul și ordinea terapeutică.'],['partea jejunală','ischemia']),

q('stomac-adv-052',['Recurența ulceroasă după chirurgia bolii ulceroase:',
 ['are drept cauză cea mai frecventă vagotomia incompletă','are rata cea mai mică după vagotomie tronculară cu antrectomie (~2%)','are rata cea mai mare după vagotomia supraselectivă (~12%)','are rata cea mai mare după vagotomie tronculară cu antrectomie','are drept cauză cea mai frecventă gastrinomul'],'ABC',182,'Boala ulceroasă recurentă',
 'Aplicarea ratelor de recurență și a cauzelor recurenței ulceroase.',
 ['Vagotomia incompletă este cauza cea mai frecventă.','Vagotomia tronculară cu antrectomie are recurență de ~2%.','Vagotomia supraselectivă are recurență de ~12%.','Rata cea mai mare este după vagotomia supraselectivă.','Gastrinomul se caută după verificarea vagotomiei complete.']],
 [8,'Distractorii inversează ratele de recurență.'],['vagotomie incompletă','12%']),

q('stomac-adv-033',['Atonia gastrică după gastrojejunostomie Roux-en-Y:',
 ['apare scintigrafic la peste jumătate dintre pacienți','este simptomatică doar la aproximativ jumătate dintre cei cu evacuare întârziată','se tratează cu mese fracționate și prokinetice','se ameliorează frecvent fără chirurgie','este simptomatică la toți pacienții cu evacuare întârziată'],'ABCD',182,'Atonia gastrică',
 'Recunoașterea frecvenței și tratamentului atoniei gastrice.',
 ['Peste jumătate au întârziere a evacuării la scintigrafie.','Doar aproximativ jumătate dintre aceștia sunt simptomatici.','Tratamentul: mese mici, fracționate, evitarea tutunului/alcoolului, metoclopramid sau eritromicină.','Simptomele se ameliorează frecvent fără chirurgie.','Doar jumătate sunt simptomatici.']],
 [8,'Distractorii supraestimează severitatea atoniei.'],['scintigrafia cu albumină','metoclopramidul']),

q('stomac-adv-034',['Anemiile după rezecția gastrică:',
 ['sunt cele mai frecvente anomalii metabolice','includ anemie megaloblastică la până la 20% dintre pacienți','includ anemie microcitară feriprivă în 50% din cazuri','includ anemie megaloblastică la majoritatea pacienților','includ deficit de fier rar, la sub 5% dintre pacienți'],'ABC',182,'Tulburări metabolice — Anemiile',
 'Fixarea frecvenței anemiilor postgastrectomie.',
 ['Anemiile sunt cele mai frecvente anomalii metabolice.','Deficitul de B12 sau folat produce anemie megaloblastică la până la 20%.','Deficitul de fier produce anemie microcitară în 50% din cazuri.','Proporția citată este de până la 20%.','Deficitul de fier apare în 50% din cazuri.']],
 [8,'Distractorii inversează frecvențele celor două tipuri de anemie.'],['20%','microcitară']),

q('stomac-adv-082',['După reconstrucțiile gastrice, osteomalacia:',
 ['apare prin chelarea calciului de grăsimile intestinale','apare în contextul tranzitului accelerat cu steatoree','poate fi prevenită prin calciu și bifosfonați','apare prin exces de vitamina D din suplimente','este prevenită prin restricția aportului de calciu'],'ABC',182,'Tulburări metabolice — Osteomalacia',
 'Recunoașterea mecanismului și prevenției osteomalaciei postgastrectomie.',
 ['Calciul și magneziul chelează grăsimile, scăzând absorbția.','Tranzitul accelerat produce steatoree.','Aportul de calciu și bifosfonații pot preveni afectarea osoasă.','Mecanismul este malabsorbția.','Calciul se suplimentează.']],
 [8,'Distractorii inversează mecanismul și profilaxia.'],['osteomalaciei','bifosfonaţi']),

q('stomac-adv-053',['Conform Tabelului 13-3, medicația sindroamelor postgastrectomie include:',
 ['acarboză pentru dumpingul tardiv','sucralfat pentru ulcerul marginal','metoclopramid pentru gastrita atonă','somatostatină pentru diareea post-vagotomie','acarboză pentru gastrita de reflux alcalin'],'ABCD',183,'Tabelul 13-3 — Medicația sindroamelor postgastrectomie',
 'Asocierea medicamentelor cu indicațiile postgastrectomie.',
 ['Acarboza este indicată în dumpingul tardiv.','Sucralfatul este indicat în ulcerul marginal și gastrita de reflux alcalin.','Metoclopramidul este indicat în gastrita atonă.','Somatostatina este indicată în diareea post-vagotomie și dumping.','Gastrita de reflux alcalin primește colestiramină sau sucralfat.']],
 [8,'Singurul distractor asociază acarboza unei indicații greșite.'],['Acarboză','Sucralfat']),

q('stomac-adv-054',['Axul hormonal al apetitului:',
 ['ghrelina este eliberată din celulele oxintice gastrice','ghrelina stimulează centrul foamei','leptina din adipocit activează centrul sațietății','leptina din adipocit stimulează centrul foamei','deficitul receptorului de leptină produce obezitate'],'ABCE',183,'Fiziologia reglării apetitului',
 'Recunoașterea rolului ghrelinei și leptinei.',
 ['Ghrelina provine din celulele oxintice gastrice.','Ghrelina stimulează centrul foamei hipotalamic.','Leptina activează centrul sațietății.','Leptina scade aportul alimentar.','Deficitul receptorului de leptină produce obezitate.']],
 [8,'Distractorii inversează rolurile hormonale.'],['ghrelină','leptină']),

q('stomac-adv-056',['Indicele de masă corporală (IMC):',
 ['se calculează ca greutate (kg) / înălțime (m)²','poate supraestima grăsimea corporală la culturiști','poate supraestima grăsimea corporală la vârstnici','măsoară direct procentul de grăsime corporală','se calculează ca greutate (kg) / înălțime (cm)'],'AB',184,'Clasificarea obezității — IMC',
 'Aplicarea formulei și a limitelor IMC.',
 ['IMC = greutate (kg) / [înălțime (m)]².','Poate supraestima grăsimea la culturiști.','Nu: la vârstnici IMC poate subestima grăsimea.','IMC este un indicator brut, nu o măsurare directă.','Înălțimea se folosește în metri, la pătrat.']],
 [8,'Distractorii supraestimează precizia IMC și schimbă formula.'],['culturiştilor','vârstnici']),

q('stomac-adv-057',['Contraindicațiile relative ale chirurgiei bariatrice includ:',
 ['insuficiența cardiacă severă','ciroza cu hipertensiune portală','dependența necontrolată de alcool','IMC ≥40 fără comorbidități asociate','eșecul dietelor anterioare'],'ABC',184,'Managementul obezității — Contraindicații',
 'Enumerarea contraindicațiilor relative ale chirurgiei bariatrice.',
 ['Insuficiența cardiacă severă este contraindicație relativă.','Ciroza cu hipertensiune portală este contraindicație relativă.','Dependența necontrolată de droguri sau alcool este contraindicație relativă.','IMC ≥40 este indicație.','Eșecul dietelor este criteriu de selecție.']],
 [8,'Distractorii sunt criterii de indicație.'],['hipertensiune po','contraindicaţii absolute']),

q('stomac-adv-066',['Criteriile NIH 1991 pentru chirurgia obezității severe cer ca pacienții adulți:',
 ['să fi eșuat regimurile de dietă și exerciții','să fie motivați și bine informați','să nu aibă afecțiuni psihologice semnificative','să aibă IMC peste 30 fără comorbidități','să nu fi încercat tratament farmacologic'],'ABC',184,'Managementul obezității — Criterii NIH',
 'Aplicarea criteriilor NIH de selecție pentru chirurgia bariatrică.',
 ['Regimurile de dietă și exerciții trebuie să fi eșuat.','Pacienții trebuie să fie motivați și bine informați.','Nu trebuie să aibă afecțiuni psihologice semnificative.','Pragul este IMC ≥40 sau 35–40 cu comorbidități.','Nu este criteriu citat.']],
 [8,'Distractorii coboară pragul și adaugă criterii inexistente.'],['motivaţi','afecţiuni psihologice']),

q('stomac-adv-084',['Pregătirea preoperatorie pentru chirurgia bariatrică include:',
 ['evaluarea psihologică','consilierea nutrițională','uneori o dietă hipocalorică pentru reducerea volumului hepatic','ECG și, eventual, testul de efort','omiterea explorării respiratorii'],'ABCD',184,'Managementul obezității — Pregătirea preoperatorie',
 'Recunoașterea componentelor pregătirii preoperatorii bariatrice.',
 ['Majoritatea intervențiilor sunt precedate de evaluare psihologică.','Consilierea nutrițională este inclusă.','Dieta hipocalorică poate reduce volumul hepatic pentru abordul minim invaziv.','ECG și eventual testul de efort sunt incluse.','Radiografia, gazele sanguine și probele funcționale sunt incluse.']],
 [8,'Distractorii omit evaluări explicite.'],['volumul hepatic','evaluare psihologică']),

q('stomac-adv-022',['Conform ghidului NIH din 1998 (Tabelul 13-5), chirurgia este o opțiune la:',
 ['IMC de 40 sau mai mare','IMC 35,0–39,9 cu comorbidități','IMC 30,0–34,9 fără comorbidități','IMC 27,0–29,9 cu comorbidități','IMC 25,0–26,9 cu comorbidități'],'AB',185,'Tabelul 13-5 — Ghidul NIH',
 'Aplicarea pragurilor IMC pentru indicația chirurgicală.',
 ['La IMC ≥40, chirurgia este o opțiune.','La IMC 35–39,9 chirurgia este o opțiune în prezența comorbidităților.','Chirurgia nu este indicată la IMC 30–34,9.','La 27–29,9 se folosesc modificarea comportamentului și farmacoterapia.','La 25–26,9 se folosește modificarea comportamentului.']],
 [8,'Distractorii sunt treptele IMC pentru alte tratamente.'],['35,0-39,9','comorbidi']),

q('stomac-adv-085',['În terapia comportamentală a obezității:',
 ['auto-monitorizarea este piatra de temelie','persoanele obeze își subestimează adesea aportul','cei care își înregistrează aportul pierd mai mult în greutate','persoanele obeze își supraestimează aportul','înregistrarea aportului nu influențează rezultatul'],'ABC',185,'Modificarea comportamentului',
 'Recunoașterea rolului auto-monitorizării.',
 ['Auto-monitorizarea este piatra de temelie.','Persoanele obeze își subestimează aportul.','Cei care înregistrează aportul pierd mai mult în greutate.','Aportul este subestimat.','Înregistrarea aportului îmbunătățește rezultatul.']],
 [8,'Distractorii inversează direcția erorii de estimare.'],['piatra  de temelie','subestimează']),

q('stomac-adv-086',['Creșterea consumului energetic prin exercițiu în obezitate:',
 ['produce reduceri ponderale minime','este mai puțin eficientă decât scăderea aportului','ajută la menținere, cu antrenament de forță','este mai eficientă decât scăderea aportului caloric','nu influențează menținerea greutății după scădere'],'ABC',185,'Intervenție dietetică — Exercițiul',
 'Evaluarea rolului exercițiului în tratamentul obezității.',
 ['Creșterea consumului energetic produce reduceri minime.','Este mult mai puțin eficientă decât scăderea aportului.','Combinată cu antrenamentul de forță previne recâștigul.','Dieta este mai eficientă.','Are rol în menținerea greutății.']],
 [8,'Distractorii supraestimează exercițiul și neagă rolul lui în menținere.'],['1.000 kcal','antrenamentul de forţă']),

q('stomac-adv-087',['Farmacoterapia antiobezitate aprobată FDA include:',
 ['fentermina','orlistatul','liraglutida','metforminul','acarboza'],'ABC',185,'Farmacoterapie',
 'Identificarea medicamentelor antiobezitate aprobate.',
 ['Fentermina este aprobată (1959) și cel mai frecvent prescrisă.','Orlistatul este aprobat.','Liraglutida este aprobată.','Nu este în lista citată.','Acarboza este folosită în dumpingul tardiv.']],
 [8,'Distractorii sunt medicamente metabolice din alte indicații.'],['Fentennină','Liraglutidă']),

q('stomac-adv-093',['Dintre tratamentele obezității, doar chirurgia bariatrică:',
 ['a obținut scădere ponderală durabilă','nu necesită modificarea comportamentului','nu necesită monitorizare pe termen lung','este indicată la orice IMC peste 30','are rezultate inferioare farmacoterapiei'],'A',185,'Managementul obezității',
 'Recunoașterea poziției chirurgiei bariatrice între opțiunile terapeutice.',
 ['Doar chirurgia a reușit scăderea ponderală semnificativă, fără recâștig.','Modificarea comportamentului rămâne parte a tratamentului.','Pacienții necesită monitorizare pe viață.','Indicația cere IMC ≥40 sau 35–40 cu comorbidități.','Nu este susținut de text.']],
 [8,'Distractorii sunt generalizări greșite despre chirurgie.'],['recâştiga','chirurgia bariatrică']),

q('stomac-adv-058',['Gastrectomia longitudinală (sleeve):',
 ['este o procedură restrictivă','îndepărtează aproximativ 85% din stomac','secționează inervația pilorului','este reversibilă','este o procedură predominant malabsorbtivă'],'AB',186,'Intervenția chirurgicală — Gastrectomia longitudinală',
 'Recunoașterea mecanismului și a particularităților gastrectomiei longitudinale.',
 ['GL este o procedură restrictivă.','Se îndepărtează aproximativ 85% din stomac.','Nu: inervația pilorului și a stomacului rămân intacte.','Procedura nu este reversibilă.','DBP/DBP-SD sunt malabsorbtive.']],
 [8,'Distractorii contrazic ireversibilitatea și mecanismul restrictiv.'],['85%','nu este reversibilă']),

q('stomac-adv-024',['Gastrectomia longitudinală produce, în primii 2 ani, o scădere medie de:',
 ['20–55% din greutatea corporală în exces','60–75% din greutatea corporală în exces','70–90% din greutatea corporală în exces','10–20% din greutatea corporală în exces','90–100% din greutatea corporală în exces'],'B',187,'Gastrectomia longitudinală — Rezultate',
 'Fixarea scăderii ponderale după gastrectomia longitudinală.',
 ['20–55% corespunde bandării gastrice.','Media este 60–75% din GCE în primii 2 ani.','70–90% corespunde DBP/DBP-SD.','Nu este intervalul citat.','Nu este intervalul citat.']],
 [8,'Distractorii sunt intervalele reale ale altor proceduri.'],['60-75%','GCE']),

q('stomac-adv-023',['Bypass-ul gastric Roux-en-Y:',
 ['rămâne standardul de aur al procedurilor bariatrice','are o ansă Roux de 75–150 cm','produce o scădere de 60–80% din GCE în 2 ani','are o ansă Roux scurtă, de 15–40 cm lungime','are probleme nutriționale mai puțin severe decât DBP'],'ABCE',187,'Bypass-ul gastric Roux-en-Y',
 'Recunoașterea parametrilor bypass-ului gastric Roux-en-Y.',
 ['BGRNY rămâne standardul de aur.','Ansa Roux măsoară 75–150 cm.','Scăderea medie este de 60–80% din GCE în 2 ani.','Lungimea citată este 75–150 cm.','Problemele nutriționale sunt mai puțin severe decât la DBP.']],
 [8,'Distractorii modifică lungimea ansei și severitatea carențelor.'],['75-150 cm','60-80%']),

q('stomac-adv-025',['Bandarea gastrică ajustabilă:',
 ['produce o scădere de 20–55% din GCE în primii ani','are portul de acces fixat pe peretele gastric','și-a pierdut din popularitate din cauza complicațiilor','este standardul de aur al chirurgiei bariatrice','produce o scădere de 70–90% din GCE'],'AC',187,'Bandarea gastrică ajustabilă',
 'Recunoașterea parametrilor și a limitelor bandării gastrice.',
 ['Pacienții pierd 20–55% din GCE în primii ani.','Nu: portul se poziționează pe fascia mușchilor abdominali.','Popularitatea a scăzut prin variabilitatea rezultatelor și complicații.','Standardul de aur este BGRNY.','70–90% corespunde DBP/DBP-SD.']],
 [8,'Distractorii atribuie bandării rezultatele altor proceduri.'],['20-55%','pars  flaccida']),

q('stomac-adv-026',['Diversia biliopancreatică (cu sau fără switch duodenal):',
 ['exclude din circuit o porțiune semnificativă de intestin subțire','produce pierderi de 70–90% din GCE în primii ani','are risc de probleme nutriționale severe','este cea mai populară procedură bariatrică din SUA','are un risc mai mare de complicații'],'ABCE',187,'Diversia biliopancreatică',
 'Recunoașterea mecanismului și a riscurilor diversiei biliopancreatice.',
 ['O porțiune semnificativă de intestin subțire este exclusă din circuit.','Pierderile sunt de 70–90% din GCE.','Problemele nutriționale pot fi severe.','Nu s-a bucurat de aceeași popularitate.','Are risc mai mare de complicații, inclusiv mortalitate.']],
 [8,'Distractorii inversează popularitatea și riscul.'],['70-90%','switch duodenal']),

q('stomac-adv-089',['Conform Tabelului 13-7, sunt complicații tardive specifice:',
 ['hernia internă, după bypass-ul Roux-en-Y','derapajul inelului, după bandarea gastrică','ulcerația pe inel, după bypass-ul Roux-en-Y','hernia internă, după bandarea gastrică','derapajul inelului, după bypass-ul Roux-en-Y'],'AB',187,'Tabelul 13-7 — Complicațiile chirurgiei bariatrice',
 'Asocierea complicațiilor tardive cu procedura bariatrică.',
 ['Hernia internă este specifică bypass-ului gastric.','Derapajul inelului este specific bandării.','Nu: ulcerația pe inel este specifică bandării gastrice.','Hernia internă nu este specifică bandării.','Derapajul inelului nu apare după bypass.']],
 [8,'Distractorii permută complicațiile între proceduri.'],['Hernie internă','Derapajul']),

q('stomac-adv-035',['Fistula anastomotică după chirurgia bariatrică:',
 ['apare la 10–20% după gastrectomie longitudinală, bypass sau DBP/SD','este situată cel mai frecvent la gastrojejunostomie, după bypass','se poate manifesta prin tahicardie inexplicabilă, fără peritonită clasică','este situată cel mai frecvent la jejunojejunostomie, după bypass','impune explorare chirurgicală și la pacientul stabil'],'BC',188,'Complicații precoce — Fistula anastomotică',
 'Recunoașterea frecvenței, sediului și prezentării fistulei anastomotice.',
 ['Nu: fistulele apar la 1–5%.','La bypass, sediul cel mai frecvent este gastrojejunostomia.','Tahicardia inexplicabilă, tahipneea și hipoxia ridică suspiciunea.','Sediul tipic este gastrojejunostomia.','La pacientul stabil, tratamentul conservator este o opțiune.']],
 [8,'Distractorii mută sediul și exclud tratamentul conservator.'],['1-5%','gastrojejunostomiei']),

q('stomac-adv-059',['Sângerarea postoperatorie după bypass gastric:',
 ['apare la 1–5% dintre pacienți','poate fi intra-abdominală sau intraluminală','impune reintervenție imediată dacă este substanțială în primele ore','este mai frecventă după gastrectomie longitudinală','este de regulă intraluminală după gastrectomie longitudinală'],'ABC',188,'Complicații precoce — Sângerarea',
 'Recunoașterea tipurilor și conduitei în sângerarea post-bypass.',
 ['Sângerarea este o complicație gravă de 1–5%.','Poate fi intra-abdominală sau intraluminală.','Hemoragia substanțială din primele ore necesită reintervenție.','După GL apare mai rar (0,5%).','După GL este de cele mai multe ori intra-abdominală.']],
 [8,'Distractorii inversează comparația dintre proceduri.'],['1-5%','intraluminală']),

q('stomac-adv-060',['Deficitele nutriționale după bypass gastric:',
 ['deficitul de fier este cel mai frecvent','deficitul de B12 este al doilea ca frecvență','B12 se administrează de rutină intramuscular sau sublingual','deficitul de B12 este cel mai frecvent','absorbția fierului scade, duodenul fiind ocolit'],'ABCE',188,'Complicații tardive — Tulburări nutriționale',
 'Recunoașterea deficitelor nutriționale după bypass gastric.',
 ['Deficitul de fier este cel mai frecvent, la până la 50%.','Deficitul de B12 este al doilea ca frecvență.','B12 se administrează de rutină IM sau sublingual.','Fierul este cel mai frecvent.','Absorbția fierului scade, duodenul fiind ocolit.']],
 [8,'Distractorii inversează ierarhia deficitelor.'],['50% din pacienţii','sublingual']),

q('stomac-adv-090',['Ulcerul marginal după bypass gastric:',
 ['rezultă din alterarea perfuziei mucoasei jejunale','poate fi favorizat de fumat și AINS','poate apărea precoce sau la 1 an postoperator','apare numai după 5 ani de la operație','se tratează cu IPP și sucralfat'],'ABCE',188,'Complicații tardive — Ulcerul marginal',
 'Recunoașterea mecanismului și cronologiei ulcerului marginal post-bypass.',
 ['Ulcerul rezultă din alterarea perfuziei mucoasei jejunale.','Fumatul, AINS și steroizii contribuie.','Poate apărea la câteva săptămâni sau la 1 an.','Poate apărea și precoce.','Tratamentul este IPP și sucralfat.']],
 [8,'Distractorii restrâng cronologia și inversează tratamentul.'],['perfuziei mucoasei','prednisonul']),

q('stomac-adv-061',['După bypass gastric:',
 ['strictura gastrojejunală apare în primele 3 luni','strictura se tratează de elecție prin dilatare pneumatică','hernia internă impune explorare chirurgicală','hernia internă se tratează inițial conservator','obstrucția ansei biliopancreatice produce vărsături biloase'],'ABC',188,'Complicații tardive — Strictura și hernia internă',
 'Recunoașterea cronologiei și conduitei în strictură și hernia internă.',
 ['Strictura apare în primele 3 luni.','Dilatarea cu balon pneumatic este tratamentul.','Hernia internă cere explorare chirurgicală, nu tratament conservator.','Explorarea este necesară.','Vărsăturile sunt nonbiloase.']],
 [8,'Distractorii aplică regula obstrucției aderențiale herniei interne.'],['primele 3 luni','breşe mezenterice'],[189]),

q('stomac-adv-036',['Pentru prevenirea litiazei veziculare după bypass gastric, acidul ursodeoxicolic se administrează:',
 ['300 mg de două ori pe zi, 6 luni','300 mg de două ori pe zi, 6 săptămâni','600 mg o dată pe zi, 12 luni','150 mg de două ori pe zi, 3 luni','300 mg o dată pe zi, pe viață'],'A',189,'Complicații tardive — Litiaza veziculară',
 'Fixarea schemei profilactice cu acid ursodeoxicolic.',
 ['Schema: 300 mg de două ori pe zi, 6 luni, cu risc redus la ~2%.','Durata este de 6 luni.','Nu este schema citată.','Nu este schema citată.','Nu este schema citată.']],
 [8,'Distractorii variază doza și durata.'],['300 mg','6  luni']),

q('stomac-adv-063',['Alunecarea inelului gastric ajustabil:',
 ['arată la tranzit dilatație proximală și orientare inferioară a inelului','se tratează inițial prin deflația completă a inelului','poate necesita repoziționare sau înlocuire operatorie','se tratează inițial prin umflarea suplimentară a inelului','se diagnostichează prin tranzit baritat'],'ABCE',190,'Complicațiile bandării gastrice',
 'Recunoașterea diagnosticului și tratamentului alunecării inelului.',
 ['Tranzitul arată dilatație proximală, încetinirea contrastului și orientare inferioară.','Tratamentul inițial este deflația completă.','Reducerea operatorie cu repoziționare sau înlocuire este deseori necesară.','Inelul se dezumflă, nu se umflă.','Diagnosticul se face prin tranzit baritat.']],
 [8,'Distractorii inversează gestul inițial.'],['deflaţia completă','orientarea necorespunzătoare']),

q('stomac-adv-062',['Eroziunea inelului gastric ajustabil în stomac apare la aproximativ:',
 ['1% dintre pacienți','5% dintre pacienți','10% dintre pacienți','20% dintre pacienți','50% dintre pacienți'],'A',190,'Complicațiile bandării gastrice — Eroziunea',
 'Fixarea frecvenței eroziunii inelului gastric.',
 ['Eroziunea este relativ rară, de aproximativ 1%.','Nu este valoarea citată.','Nu este valoarea citată.','Nu este valoarea citată.','50% este frecvența deficitului de fier post-bypass.']],
 [8,'Distractorii sunt frecvențe plauzibile.'],['aproximativ I%','Eroziunea inelului']),

q('stomac-adv-064',['Conform Tabelului 13-8, în profilaxia și tratamentul trombozei după chirurgia bariatrică:',
 ['heparina se dă profilactic 5.000 unități SC de 3 ori pe zi','enoxaparina se dă profilactic 40 mg SC o dată sau de două ori pe zi','warfarina se titrează pentru INR 2–3','enoxaparina se dă profilactic 1 mg/kg SC de două ori pe zi','warfarina se titrează pentru INR 3–4'],'ABC',190,'Tabelul 13-8 — Medicația complicațiilor bariatrice',
 'Aplicarea schemelor anticoagulante din Tabelul 13-8.',
 ['Heparina profilactică: 5.000 unități SC de 3 ori pe zi.','Enoxaparina profilactică: 40 mg SC zilnic sau de două ori pe zi.','Warfarina: INR țintă 2–3.','1 mg/kg SC de două ori pe zi este doza terapeutică.','Ținta este INR 2–3.']],
 [8,'Distractorii confundă doza profilactică cu cea terapeutică.'],['5.000 unităţi','INR ţintă = 2-3']),

q('stomac-adv-065',['Beneficiile chirurgiei bariatrice, în meta-analiza a 22.094 de pacienți, includ:',
 ['vindecarea diabetului la 76% dintre pacienți','vindecarea hipertensiunii la 61,7% dintre pacienți','vindecarea apneei obstructive de somn la 85,7% dintre pacienți','vindecarea diabetului la 30% dintre pacienți','vindecarea hipertensiunii la 90% dintre pacienți'],'ABC',190,'Beneficiile operațiilor bariatrice',
 'Fixarea ratelor de vindecare a comorbidităților.',
 ['Diabetul s-a vindecat la 76%.','Hipertensiunea s-a vindecat la 61,7%.','Apneea obstructivă s-a vindecat la 85,7%.','Rata citată este 76%.','Rata citată este 61,7%.']],
 [8,'Distractorii modifică ratele reale.'],['76%','61,7%']),

q('stomac-adv-094',['Scăderea ponderală cu 10%:',
 ['reduce hipertensiunea și diabetul de tip II','scade incidența preconizată a bolilor de inimă','crește speranța de viață','nu modifică hipercolesterolemia','crește riscul de accident vascular cerebral'],'ABC',190,'Beneficiile operațiilor bariatrice — Scăderea cu 10%',
 'Recunoașterea beneficiilor unei scăderi ponderale de 10%.',
 ['Reduce hipertensiunea, hipercolesterolemia și diabetul de tip II.','Scade incidența preconizată a bolilor de inimă și a AVC.','Crește speranța de viață.','Reduce și hipercolesterolemia.','Scade incidența AVC.']],
 [8,'Distractorii contrazic beneficiile enumerate.'],['10%','hipercolesterolemia'],[191]),
];
