import {advancedQuestion} from './advanced-author';
import type {SourceRow} from './source-author';

const EDITION="Chirurgie generală și specialități chirurgicale, ediția pentru rezidențiat MG 2025";
const pdfOffset=(p:number)=>p-57;
const q=(n:number,row:SourceRow,score:number,reason:string,expressions:string[],related:number[]=[])=>
 advancedQuestion('trauma',9,pdfOffset,`trauma-adv-${String(n).padStart(3,'0')}`,row,[score,reason],expressions,undefined,related,'Lawrence',EDITION);

export const TRAUMA_ADVANCED=[
q(1,['Metoda definitivă de securizare a căilor aeriene la pacientul traumatizat este:',
 ['Intubația orotraheală, cu tub prevăzut cu manșetă gonflabilă, plasat printre corzile vocale','Dispozitivele nazofaringiene, inclusiv atunci când există leziuni faciale extensive','Intubația nazală, ca procedură de primă intenție la pacientul obnubilat','Cricotiroidotomia cu ac, considerată superioară intubației orotraheale ca metodă definitivă','Ridicarea bărbiei, realizată fără menținerea imobilizării coloanei cervicale'],'A',87,'Evaluarea inițială — Căile aeriene',
 'Recunoașterea intubației orotraheale ca metodă definitivă, distinctă de manevrele temporare și de contraindicațiile abordului nazal.',
 ['Textul precizează că metoda definitivă de securizare a căilor aeriene este intubația orotraheală.','Dispozitivele nazofaringiene nu pot fi utilizate dacă există leziuni la nivelul feței.','La pacientul obnubilat se restabilește permeabilitatea prin intubație nazală sau orală, nu nazală ca unică primă intenție definitivă.','Cricotiroidotomia (deschisă sau cu ac) este rezervată situației în care glota nu poate fi intubată pe cale orală.','Ridicarea bărbiei și tracționarea mandibulei se fac menținând coloana cervicală imobilizată.']],
 8,'Distractorii promovează manevre temporare sau contraindicate (nazal în leziuni faciale) ca și cum ar fi metoda definitivă.',['intubația orotraheală','cricotiroidotomie']),

q(2,['Alegeți afirmațiile corecte referitoare la pneumotoraxul în tensiune:',
 ['Diagnosticul se bazează pe examenul fizic, confirmat de triada absența zgomotelor respiratorii, șoc și scăderea intensității zgomotelor cardiace','Decompresia se obține prin angiocateter cu alezaj mare în al doilea spațiu intercostal pe linia medioclaviculară sau prin tub toracic în spațiul 4 sau 5, pe linia axilară anterioară','Confirmarea tomografică este necesară înaintea oricărei decompresii','Leziunile identificate la un pas al evaluării primare se tratează abia după parcurgerea întregului ABCDE','Dispozitivele nazofaringiene sunt preferate în fracturile faciale complexe'],'AB',87,'Evaluarea primară — Respirația',
 'Aplicarea triadei clinice a pneumotoraxului în tensiune și a celor două căi de decompresie imediată, fără a amâna tratamentul pentru imagistică.',
 ['Triada clinică este enunțată explicit ca confirmare a diagnosticului.','Ambele căi de decompresie (angiocateter ICS 2 medioclavicular și tub ICS 4–5 axilară anterioară) sunt descrise.','Diagnosticul este clinic; amânarea pentru CT lasă hipertensiunea intrapleurală netratată.','Leziunile de la fiecare pas ABCDE sunt tratate înainte de a trece la pasul următor.','Dispozitivele nazofaringiene nu se folosesc în leziunile faciale.']],
 8,'Inversează caracterul clinic al diagnosticului și ordinea ABCDE, două erori ATLS frecvente.',['pneumotoraxului în tensiune','al doilea spațiu intercostal']),

q(3,['Următoarele afirmații despre evaluarea neurologică a traumatismului cranio-cerebral sunt adevărate:',
 ['Reflexul Cushing asociază creșterea presiunii arteriale medii cu bradicardie și scăderea frecvenței respiratorii','Hipotensiunea la pacienții cu leziuni cranio-cerebrale indică prezența hemoragiei și nu trebuie atribuită injuriei cerebrale','Scorurile Glasgow de 3 și 4 se asociază cu evoluție favorabilă în marea majoritate a cazurilor','Echimoză periorbitală („ochi de raton”), echimoză perimastoidiană (semnul Battle), hemotimpanul și extravazarea de LCR sunt semne de fractură de bază de craniu','Hematumul epidural se prezintă tipic concav sau semilunar pe CT nativ'],'ABD',90,'Traumatismele cranio-cerebrale — Examen clinic',
 'Diferențierea reflexului Cushing și a semnelor de fractură de bază de craniu de interpretarea greșită a hipotensiunii și a morfologiei hematomului.',
 ['Răspunsul precoce la creșterea PIC (PAM crescută, bradicardie, frecvență respiratorie scăzută) este numit reflex Cushing.','Textul precizează că hipotensiunea indică hemoragie, nu injuria cerebrală.','Scorurile 3 și 4 se asociază cu mortalitate sau stare vegetativă în aproape 97% din cazuri.','Lista semnelor de fractură de bază de craniu este enumerată explicit.','Colecția convexă/lenticulară este tipică pentru hematomul epidural; forma concavă/semilunară descrie hemoragia subdurală.']],
 8,'Inversează prognosticul GCS 3–4 și morfologia CT epidural vs subdural, pe fondul reflexului Cushing.',['reflex Cushing','ochi de raton'],[89]),

q(4,['Selectați enunțurile adevărate despre managementul presiunii intracraniene după traumatism cranio-cerebral:',
 ['Hiperventilația moderată până la o PaCO2 de 32–35 mmHg scade temporar PIC, fără a produce ischemie cerebrală, dar este folosită doar în creșteri acute ale PIC','Manitolul reduce edemul cerebral, însă poate cauza hipotensiune la pacienții cu hemoragie ocultă','În 15% din cazuri, traumatismele cerebrale se însoțesc de leziuni la nivelul coloanei cervicale','Hemoragia subarahnoidiană și leziunea axonală difuză se evacuează chirurgical de rutină','Hematoamele epidurale au prognostic rezervat chiar și după evacuarea promptă'],'ABC',91,'Managementul traumatismelor cranio-cerebrale',
 'Aplicarea măsurilor de limitare a PIC și a indicațiilor chirurgicale diferențiate pe tipul de hemoragie extra-axială.',
 ['Intervalul PaCO2 32–35 mmHg și caracterul temporar, rezervat creșterilor acute, sunt explicite.','Efectul osmotic al manitolului și riscul de hipotensiune în hemoragia ocultă sunt menționate.','Asocierea de 15% cu leziuni cervicale impune examinarea concomitentă a coloanei.','HSA și DAI sunt tratate, în general, non-chirurgical, din cauza riscului de lezare a parenchimului.','Prognosticul hematomului epidural este, în general, bun dacă intervenția este promptă.']],
 8,'Inversează indicația chirurgicală a HSA/DAI și prognosticul hematomului epidural după evacuare promptă.',['32-35 mmHg','coloanei cervicale']),

q(5,['Hemotoraxul masiv este definit prin:',
 ['Pierderea a cel puțin 1.500 mL de sânge în spațiul pleural în prima oră de la traumatism sau pierdere continuă de cel puțin 200 mL pe oră în primele 4 ore','Orice colecție pleurală vizibilă pe radiografia toracică de urgență','Un volum de 500 mL acumulat în primele 30 de minute, indiferent de debitul ulterior','Asocierea pneumotoraxului cu hemotorax, independent de volum','Doar sângerarea din parenchimul pulmonar, nu din vasele intercostale'],'A',94,'Leziuni amenințătoare de viață — Hemotoraxul masiv',
 'Recunoașterea celor două praguri volumetrice care definesc hemotoraxul masiv și impun toracotomie de control hemoragic.',
 ['Definiția cu pragurile 1.500 mL în prima oră sau 200 mL/oră timp de 4 ore este explicită.','Vizibilitatea radiologică nu definește hemotoraxul masiv.','Pragul de 500 mL/30 min nu figurează în text.','Asocierea cu pneumotorax nu înlocuiește criteriile volumetrice.','Sursa cea mai frecventă sunt vasele intercostale, nu doar parenchimul.']],
 8,'Distractorii înlocuiesc pragurile 1.500/200 mL cu volume arbitrare sau cu sursa anatomică greșită.',['1.500 mL','200 mL de sânge pe oră']),

q(6,['Sunt adevărate următoarele afirmații despre tamponada cardiacă traumatică:',
 ['Prezentarea cu zgomote cardiace de intensitate scăzută, turgescență jugulară și hipotensiune (triada Beck) este sugestivă la pacientul cu traumatism penetrant precordial','Ecografia FAST este metoda de diagnostic principală pentru tamponadă și hemopericard','Pericardiocenteza este o opțiune de temporizare, cu rate foarte scăzute de succes, când nu există echipă pentru toracotomie de resuscitare','Scenariul cel mai frecvent este plaga prin înjunghiere la marginea sternală dreaptă, cu lezarea ventriculului drept','Absența semnului Kussmaul sau a pulsului paradoxal exclude diagnosticul de tamponadă'],'ABC',94,'Tamponada cardiacă',
 'Recunoașterea triadei Beck și a rolului FAST, față de limita pericardiocentezei și de variabilitatea semnelor clinice adiționale.',
 ['Triada Beck este descrisă explicit în contextul traumatismului penetrant precordial.','FAST este numită metoda de diagnostic principală pentru tamponadă și hemopericard.','Pericardiocenteza este rezervată temporizării, cu succes scăzut.','Scenariul tipic este plaga la marginea sternală stângă, cu lezarea ventriculului stâng.','Textul precizează că aceste manifestări sunt variabile, iar absența lor nu exclude diagnosticul.']],
 8,'Inversează sediul anatomic (stern stâng/VS) și transformă semnele variabile în criterii de excludere.',['triada Beck','toracotomia de resuscitare']),

q(7,['Identificați afirmațiile corecte privind laparotomia de control lezional și sindromul de compartiment abdominal:',
 ['„Triada letală” include hipotermia, acidoza și coagulopatia','Chirurgia de control lezional durează, de obicei, între 60 și 90 de minute, urmată de resuscitare în terapie intensivă','După aproximativ 12–48 de ore, pacientul revine în sală pentru reconstrucție digestivă și îndepărtarea câmpurilor','Sindromul de compartiment abdominal se suspectează când presiunea intra-abdominală depășește 25 mmHg și asociază insuficiență de organ','Diagnosticul se bazează pe măsurarea presiunii în vena cavă inferioară, nu pe presiunea vezicală'],'ABCD',101,'Controlul lezional — Sindromul de compartiment abdominal',
 'Aplicarea duratei și a triadei letale în damage control, precum și a pragului de 25 mmHg cu disfuncție de organ pentru SCA.',
 ['Cele trei componente ale triadei letale sunt enumerate explicit.','Intervalul 60–90 de minute este citat pentru durata intervenției de control lezional.','Reintervenția la 12–48 de ore este descrisă după stabilizare.','Pragul de peste 25 mmHg plus insuficiență de organ definește suspiciunea de SCA.','Presiunea vezicală corespunde indirect presiunii intraperitoneale; nu vena cavă este metoda descrisă.']],
 8,'Distractorul final înlocuiește presiunea vezicală cu o măsurătoare venoasă, pe fondul a trei praguri cantitative memorabile.',['25 mmHg','60 și 90 de minute'],[100]),

q(8,['Care dintre următoarele afirmații privind fracturile de bazin sunt adevărate?',
 ['Mecanismul de compresie laterală este cel mai frecvent și cel mai stabil, cu rată mică de rupturi ligamentare sacroiliace','Compresia antero-posterioară corespunde fracturii tip „carte deschisă”, cu ruptură a simfizei pubiene','Forfecarea verticală este cel mai rar și cel mai instabil mecanism, adesea asociat cu alte leziuni abdominale, pelvine sau vasculare','Explorarea chirurgicală prin deschiderea peritoneului este metoda de elecție pentru controlul hemoragiei venoase pelvine','Un vas arterial este sursa hemoragiei la aproximativ jumătate dintre pacienții cu fractură de bazin'],'ABC',101,'Fracturile bazinului',
 'Clasificarea după mecanism (lateral vs AP vs forfecare verticală) și recunoașterea limitei explorării peritoneale în hemoragia pelvină.',
 ['Compresia laterală este descrisă ca cea mai frecventă și cea mai stabilă.','Fractura tip „carte deschisă” este identificată cu mecanismul AP.','Forfecarea verticală este numită cel mai rar și cel mai instabil mecanism.','Deschiderea peritoneului anulează tamponamentul hematomului retroperitoneal; embolizarea pe cateter este metoda optimă pentru sângerarea arterială.','Sursa arterială este menționată la aproximativ 10% dintre pacienți, nu la jumătate.']],
 8,'Inversează ierarhia de stabilitate a mecanismelor și promovează laparotomia ca tratament al sângerării venoase pelvine.',['compresie laterală','simfizei pubiene'],[102]),

q(9,['Prezentarea clasică a șocului neurogen după leziune spinală proximală include:',
 ['Tetraplegie, hipotensiune, bradicardie și extremități calde','Extremități palide și reci, însoțite de tahicardie','Hipertensiune cu tahicardie compensatorie','Hipotensiune cu tahicardie, fără modificare a temperaturii extremităților','Hipertensiune, bradicardie și extremități reci, ca în reflexul Cushing'],'A',92,'Leziunile coloanei — Șocul neurogen',
 'Diferențierea clinică a șocului neurogen (bradicardie, extremități calde) de șocul hemoragic.',
 ['Cele patru elemente ale prezentării clasice sunt enumerate explicit.','Extremitățile palide, reci și tahicardia descriu șocul hemoragic, nu pe cel neurogen.','Hipertensiunea nu face parte din tabloul șocului neurogen.','Hipotensiunea neînsoțită de tahicardie este semnul discriminator, nu tahicardia.','Reflexul Cushing aparține hipertensiunii intracraniene, nu șocului spinal.']],
 8,'Distractorii amestecă semnele șocului hemoragic și ale reflexului Cushing cu tabloul vasodilatației neurogene.',['șocului neurogen','extremități calde']),

q(10,['În traumatismul pediatric, resuscitarea volemică se caracterizează prin:',
 ['Volumul sangvin reprezintă aproximativ 8% din greutatea corporală, respectiv 80 mL/kg','Bolusul inițial este de 20 mL/kg de cristaloizi izotoni (ser fiziologic 0,9% sau Ringer lactat)','După al doilea bolus de cristaloid fără ameliorarea perfuziei se administrează 10 mL/kg masă eritrocitară izogrup sau O negativ','O tensiune arterială normală pentru vârstă exclude hipovolemia, deoarece copilul nu își menține tensiunea prin tahicardie','Saturația arterială sub 90% în aer atmosferic este, de regulă, fără semnificație la copilul fără boli pulmonare preexistente'],'ABC',105,'Traumatismele pediatrice',
 'Aplicarea volumului circulant pediatric și a secvenței 20 mL/kg cristaloid, apoi 10 mL/kg masă eritrocitară, față de falsa reasigurare a TA normale.',
 ['Cifrele 8% și 80 mL/kg sunt citate explicit.','Bolusul de 20 mL/kg cristaloid izoton este regula de start.','Bolusul de 10 mL/kg masă eritrocitară după al doilea cristaloid este descris.','TA este menținută prin tahicardie și vasoconstricție; o valoare normală nu reflectă un volum adecvat.','Saturația <90% în aer atmosferic indică, în general, un schimb de gaze ineficient.']],
 8,'Inversează interpretarea tensiunii „normale” la copil și a saturației <90%, două capcane de triaj pediatric.',['80 mL/kg','20 mL/kg']),
];
