import {rewriter} from './rewrite-author';
import {RETIRED_TROMBOEMBOLISM} from './retired/tromboembolism';

// Rewritten after the 2026-09-24 cue audit (Kumar, cap. 29, p. 1001–1017).
const q=rewriter(RETIRED_TROMBOEMBOLISM,-810,{shuffle:true});

export const TROMBOEMBOLISM_V2=[
q('tromboembolism-adv-016',['Tromboembolismul venos:',
 ['apare pe parcursul vieții la peste 5% din oameni','are etiologie necunoscută în aproape 50% din cazuri','face din EP a doua cauză cardiovasculară de deces','este o boală rară a adultului tânăr','are etiologie necunoscută în sub 5% din cazuri'],'AB',1001,'Noțiuni de bază și introducere',
 'Fixarea datelor generale despre tromboembolismul venos.',
 ['TEV apare la peste 5% din oameni pe parcursul vieții.','Etiologia rămâne necunoscută în aproape 50% din cazuri.','EP este a treia, nu a doua, cauză cardiovasculară de deces, după IMA și AVC.','Riscul crește cu vârsta.','Proporția citată este de aproape 50%.']],
 [8,'Distractorii subestimează frecvența și proporția neexplicată.'],['5% din oameni','50% din cazuri']),

q('tromboembolism-adv-041',['Tromboza, spre deosebire de hemostaza fiziologică:',
 ['formează masa solidă în interiorul vasului','produce un tromb atașat de peretele vascular','nu poate genera emboli la distanță','formează un cheag situat în afara endoteliului','apare doar ca răspuns la o leziune vasculară'],'AB',1001,'Patogeneza trombozei',
 'Diferențierea trombozei de hemostaza fiziologică.',
 ['Tromboza produce o masă solidă în interiorul vasului.','Trombii se formează pe perete și sunt atașați de el.','Nu: fragmentele (emboli) se pot desprinde și obstrua vasele din aval.','Cheagul din afara endoteliului caracterizează hemostaza.','Formarea cheagului ca răspuns la leziune descrie hemostaza.']],
 [8,'Distractorii descriu hemostaza fiziologică.'],['hemostaza fiziologică','embofl']),

q('tromboembolism-adv-066',['Trombii arteriali sunt descriși ca:',
 ['trombi albi, bogați în trombocite','trombi roșii, bogați în hematii','trombi roșii, bogați în trombocite','trombi albi, bogați în hematii','trombi mixți, bogați în leucocite'],'A',1001,'Tromboza arterială și venoasă',
 'Diferențierea trombilor arteriali de cei venoși.',
 ['Coagulii arteriali sunt trombi albi, bogați în trombocite și fibrină.','Trombii roșii, bogați în hematii, sunt venoși.','Trombii roșii sunt venoși și bogați în hematii.','Trombii albi sunt bogați în trombocite.','Nu este descrierea citată.']],
 [8,'Distractorii descriu trombii venoși.'],['trombi albi','plăcilor ateromatoase']),

q('tromboembolism-adv-001',['În triada lui Virchow:',
 ['staza și hipercoagulabilitatea favorizează tromboza venoasă','turbulența și leziunea parietală favorizează tromboza arterială','hemoliza intravasculară este una dintre cele trei componente','staza este determinantul principal al trombozei arteriale','ruptura plăcii ateromatoase inițiază tromboza venoasă'],'AB',1002,'Factorii care influențează tromboza',
 'Aplicarea triadei Virchow la tromboza arterială și venoasă.',
 ['Staza și hipercoagulabilitatea sunt mai relevante pentru tromboza venoasă.','Turbulența și disfuncția peretelui, prin plăci ateromatoase, sunt factori arteriali.','Nu: componentele sunt fluxul, peretele și hipercoagulabilitatea.','Staza este relevantă pentru tromboza venoasă.','Ruptura plăcii este un factor arterial.']],
 [8,'Distractorii inversează ponderea componentelor între artere și vene.'],['Virchow','Staza şi hipercoagulabilitatea'],[1001]),

q('tromboembolism-adv-017',['Tromboza venoasă profundă:',
 ['începe frecvent în buzunarul unei valve venoase','este definită ca proximală de la vena femurală în sus','apare în alte sedii decât membrele inferioare în ~10%','este definită ca proximală când se limitează la gambă','apare în alte sedii decât membrele inferioare în ~50%'],'AC',1002,'Definiții',
 'Recunoașterea originii și a definițiilor TVP.',
 ['Procesul începe probabil în buzunarul unei valve venoase.','TVP proximală începe de la vena poplitee, nu de la vena femurală.','Aproximativ 10% dintre episoade apar în alte sedii.','Trombul limitat la gambă definește TVP distală.','Proporția citată este de ~10%.']],
 [8,'Distractorii inversează definițiile proximal/distal.'],['buzunarul','vena poplitee']),

q('tromboembolism-adv-018',['Epidemiologia TEV:',
 ['incidența anuală este de aproximativ 1 la 1.000','incidența se apropie de 1 la 100 la vârstnici','aproximativ 25% dintre decesele din spital sunt prin EP','incidența se apropie de 1 la 100 la adulții tineri','aproximativ 90% dintre episoade se prezintă ca EP'],'AB',1002,'Epidemiologie și factori de risc',
 'Fixarea datelor de incidență ale TEV.',
 ['Incidența anuală este estimată la 1 la 1.000.','La vârstnici se apropie de 1 la 100 pe an.','Proporția citată este de aproximativ 10%.','La adulții tineri incidența este de 1 la 10.000.','Aproximativ 60% se prezintă ca TVP și 40% ca EP.']],
 [8,'Distractorii permută incidențele pe grupe de vârstă.'],['1 la 1.000','10% dintre decesele']),

q('tromboembolism-adv-019',['Conform Cadranului 29.1, factorii de risc tranzitori pentru TEV includ:',
 ['imobilizarea cu repaus la pat peste 3 zile','călătoriile recente de peste 4 ore','cateterul venos central','indicele de masă corporală peste 30 kg/m²','trombofiliile ereditare'],'ABC',1002,'Cadranul 29.1 — Factori de risc',
 'Diferențierea factorilor de risc tranzitori de cei persistenți.',
 ['Imobilizarea peste 3 zile este factor tranzitor.','Călătoriile recente de peste 4 ore sunt factor tranzitor.','Cateterul venos central este factor tranzitor.','Obezitatea este factor persistent.','Trombofiliile ereditare sunt factori persistenți.']],
 [8,'Distractorii sunt factori reali din coloana persistenților.'],['repaus la pat','Călătorii recente']),

q('tromboembolism-adv-068',['Gradul de creștere a riscului de TEV:',
 ['chirurgia majoră crește riscul de 10–50 de ori','sarcina crește riscul de 3–10 ori','obezitatea crește riscul de până la 3 ori','obezitatea crește riscul de 10–50 de ori','sarcina crește riscul de până la 3 ori'],'ABC',1002,'Epidemiologie — Puterea factorilor de risc',
 'Ierarhizarea factorilor de risc după puterea lor.',
 ['Factorii puternici (chirurgie majoră, traumă, repaus) cresc riscul de 10–50 de ori.','Factorii moderați (sarcină, estrogeni) cresc riscul de 3–10 ori.','Factorii slabi (obezitate, călătorii) cresc riscul de până la 3 ori.','Obezitatea este factor slab.','Sarcina este factor moderat.']],
 [8,'Distractorii mută factorii între categorii.'],['10-50 de ori','3-10 ori']),

q('tromboembolism-adv-069',['Incidența TEV este cea mai mare la:',
 ['persoanele de descendență africană','persoanele de descendență asiatică','persoanele de descendență europeană','populația din estul Asiei','populația mediteraneeană'],'A',1002,'Epidemiologie — Etnia',
 'Fixarea variației etnice a incidenței TEV.',
 ['Incidența cea mai mare este la descendența africană.','Asiaticii au incidența cea mai scăzută.','Populația albă are incidență intermediară.','Asiaticii au incidența cea mai scăzută.','Nu este grupul citat.']],
 [8,'Distractorii inversează ierarhia etnică.'],['descendenţă africană','asiatici']),

q('tromboembolism-adv-020',['Embolia pulmonară se prezintă clinic:',
 ['cu durere pleuritică și dispnee la ~65%','cu dispnee izolată la ~25%','cu sincopă sau șoc la ~10%','cu dispnee izolată la ~65% din cazuri','cu sincopă sau șoc la ~25% din cazuri'],'ABC',1003,'Aspecte clinice',
 'Fixarea formelor de prezentare ale EP.',
 ['Aproximativ 65%: durere pleuritică și dispnee.','Aproximativ 25%: dispnee izolată.','Aproximativ 10%: sincopă, hipotensiune sau șoc.','Dispneea izolată apare la ~25%.','Forma severă apare la ~10%.']],
 [8,'Proporțiile sunt permutate între forme.'],['65%','sincopale'],[1002]),

q('tromboembolism-adv-021',['Investigațiile inițiale în suspiciunea de EP:',
 ['aspectul S1Q3T3 apare doar la o minoritate','tahicardia sinusală este mai frecventă decât S1Q3T3','gazometria arată tipic hipoxemie și hipocapnie','S1Q3T3 este prezent la majoritatea pacienților','gazometria arată tipic hipercapnie'],'ABC',1003,'Investigații inițiale',
 'Interpretarea investigațiilor nespecifice din EP.',
 ['S1Q3T3 este prezent doar la o minoritate.','Tahicardia sinusală se observă mai frecvent.','Gazometria arată tipic hipoxemie și hipocapnie.','S1Q3T3 apare la o minoritate.','Se observă hipocapnie.']],
 [8,'Distractorii supraestimează semnul clasic ECG.'],['S1Q3T3','hipocapnia']),

q('tromboembolism-adv-070',['Pe ECG-ul din EP acută se pot observa:',
 ['unde T inversate în derivațiile inferioare','unde T inversate în V1–V4','bloc de ramură dreaptă incomplet','bloc de ramură stângă complet','tahicardie sinusală'],'ABCE',1003,'Investigații inițiale — ECG',
 'Recunoașterea modificărilor ECG de suprasolicitare dreaptă.',
 ['Suprasolicitarea VD inversează T în II, III, aVF.','T inversate apar în precordialele drepte V1–V4.','Figura 29.1 arată bloc de ramură dreaptă incomplet.','Nu este aspectul citat.','Tahicardia sinusală este modificarea cea mai frecventă.']],
 [8,'Distractorii descriu aspecte opuse suprasolicitării drepte.'],['V1-V4','bloc de ramură dreaptă']),

q('tromboembolism-adv-043',['Scorul Wells cu două niveluri pentru TVP (Cadranul 29.3) include:',
 ['cancerul activ în ultimele 6 luni','chirurgia majoră în ultimele 12 săptămâni','gamba mai mare cu cel puțin 1 cm','prezența hemoptiziei','alura ventriculară peste 100/min'],'AB',1004,'Cadranul 29.3 — Scorul Wells pentru TVP',
 'Recunoașterea itemilor scorului Wells pentru TVP.',
 ['Cancerul activ este un item.','Chirurgia majoră în ultimele 12 săptămâni este un item.','Nu: itemul cere gamba edemațiată cu cel puțin 3 cm.','Hemoptizia aparține scorului Wells pentru EP.','Tahicardia aparține scorului Wells pentru EP.']],
 [8,'Distractorii sunt itemi reali ai scorului pentru EP.'],['12 săptămâni','3 cm']),

q('tromboembolism-adv-071',['Scorul Wells cu două niveluri pentru EP (Cadranul 29.4) include:',
 ['semnele clinice de TVP','alura ventriculară peste 100/min','prezența hemoptiziei','cancerul activ','gamba mai mare cu ≥3 cm'],'ABCD',1004,'Cadranul 29.4 — Scorul Wells pentru EP',
 'Recunoașterea itemilor scorului Wells pentru EP.',
 ['Semnele de TVP valorează 3 puncte.','Alura ventriculară >100/min valorează 1,5 puncte.','Hemoptizia valorează 1 punct.','Cancerul activ valorează 1 punct.','Diferența de 3 cm aparține scorului TVP.']],
 [8,'Distractorii sunt itemi ai scorului pentru TVP.'],['Hemoptizie','Alura ventriculară']),

q('tromboembolism-adv-002',['În algoritmul NICE pentru suspiciunea de TVP:',
 ['TVP improbabilă impune dozarea D-dimerilor','TVP probabilă impune ultrasonografie proximală','D-dimerii crescuți la TVP improbabilă impun imagistică','D-dimerii normali la scor improbabil fac TVP puțin probabilă','D-dimerii normali exclud cu certitudine absolută TEV'],'ABCD',1004,'Diagnosticul TVP și al EP',
 'Aplicarea algoritmului diagnostic NICE în TVP.',
 ['La scor improbabil, următorul pas sunt D-dimerii.','La scor probabil se face ultrasonografie proximală.','D-dimerii crescuți la scor improbabil impun imagistică.','D-dimerii normali au valoare predictivă negativă ridicată (eșec <2% în 3 luni).','Rămâne o rată mică de eșec (<2% în 3 luni).']],
 [8,'Distractorii supraestimează D-dimerii.'],['D-dimerilor','improbabil']),

q('tromboembolism-adv-044',['D-dimerii în diagnosticul TEV:',
 ['sunt produși de degradare a fibrinei','au valoare predictivă negativă ridicată','sunt crescuți nespecific în sarcină și cancer','au valoare predictivă pozitivă ridicată','impun imagistică atunci când sunt crescuți'],'ABCE',1004,'Măsurarea D-dimerilor',
 'Interpretarea D-dimerilor în TEV.',
 ['D-dimerii sunt produși de degradare a fibrinei.','Importanța lor stă în valoarea predictivă negativă ridicată.','Sunt crescuți nespecific la vârstnici, în infecții, cancer și sarcină.','Nu sunt specifici TEV.','Nivelurile crescute impun imagistică.']],
 [8,'Distractorii confundă valoarea predictivă negativă cu cea pozitivă.'],['degradare a fibrinei','predictivă negativă']),

q('tromboembolism-adv-072',['După un scor Wells improbabil cu D-dimeri normali, rata de TEV ratat în 3 luni este:',
 ['sub 2%','aproximativ 5%','aproximativ 10%','aproximativ 25%','zero'],'A',1004,'Măsurarea D-dimerilor — Rata de eșec',
 'Fixarea ratei de eșec a strategiei Wells–D-dimeri.',
 ['Rata de eșec este sub 2% în 3 luni.','Nu este rata citată.','Nu este rata citată.','Nu este rata citată.','TEV nu poate fi exclus complet.']],
 [8,'Distractorii sunt valori plauzibile.'],['<2%','3 luni']),

q('tromboembolism-adv-045',['Ultrasonografia venoasă în suspiciunea de TVP:',
 ['are sensibilitate peste 95% pentru TVP proximală','are sensibilitate de ~70% pentru TVP distală','negativă proximal, la Wells probabil, se repetă la 5–7 zile','are sensibilitate peste 95% pentru TVP distală','negativă proximal exclude TVP la Wells probabil'],'ABC',1004,'Examinarea imagistică a TVP',
 'Interpretarea ultrasonografiei venoase în TVP.',
 ['Sensibilitatea pentru TVP proximală este >95%.','Sensibilitatea pentru TVP distală este ~70%.','O scanare proximală negativă la Wells probabil se repetă după 5–7 zile.','Sensibilitatea distală este ~70%.','Scanarea proximală negativă nu exclude TVP distală.']],
 [8,'Distractorii supraestimează sensibilitatea distală.'],['>95%','5-7 zile'],[1005]),

q('tromboembolism-adv-003',['În explorarea imagistică a embolismului pulmonar:',
 ['CTPA este tehnica cea mai comună','CTPA poate oferi un diagnostic alternativ','o scintigrafie V/Q normală exclude EP','scintigrafia V/Q este cea mai comună','defectele de perfuzie cu ventilație normală sugerează EP'],'ABCE',1005,'Examinarea imagistică a EP',
 'Compararea CTPA cu scintigrafia V/Q.',
 ['CTPA este tehnica cea mai comună.','CTPA poate oferi diagnosticul alternativ.','Scintigrafia V/Q normală exclude EP.','CTPA este cea mai comună.','EP se diagnostichează pe defecte de perfuzie cu ventilație normală.']],
 [8,'Distractorii inversează criteriul scintigrafic.'],['CTPA','ventilaţie-perfuzie']),

q('tromboembolism-adv-004',['O primă doză de anticoagulant se administrează dacă investigarea se anticipează că va depăși:',
 ['o oră, în suspiciunea de EP','4 ore, în suspiciunea de TVP','24 de ore, pentru completarea investigațiilor','4 ore, în suspiciunea de EP','o oră, în suspiciunea de TVP'],'AB',1005,'Calendarul efectuării investigațiilor',
 'Aplicarea pragurilor de anticoagulare empirică.',
 ['Pragul pentru EP este de o oră.','Pragul pentru TVP este de 4 ore.','24 de ore este termenul de completare a investigațiilor.','Pragul pentru EP este de o oră.','Pragul pentru TVP este de 4 ore.']],
 [8,'Pragurile sunt permutate între EP și TVP.'],['o oră','4 ore']),

q('tromboembolism-adv-048',['La suspiciunea de EP cu hipotensiune, când CTPA de urgență nu este posibilă, se face:',
 ['ecocardiografie transtoracică','scintigrafie de ventilație-perfuzie','dozarea D-dimerilor','ultrasonografie venoasă a membrelor inferioare','angiografie pulmonară convențională'],'A',1005,'Prezentările în urgență',
 'Alegerea investigației în EP cu instabilitate hemodinamică.',
 ['Ecocardiografia la pat poate arăta hipertensiune pulmonară acută și disfuncție VD.','Nu este alternativa citată în urgență.','D-dimerii nu sunt utili în această situație.','Nu este alternativa citată.','Nu este alternativa citată.']],
 [8,'Distractorii sunt investigații reale, nepotrivite instabilului.'],['ecocardiografia transtoracică','hipertensiunii pulmonare acute']),

q('tromboembolism-adv-075',['Tromboza venoasă profundă a membrului superior:',
 ['se evaluează de regulă prin ultrasonografie','se tratează diferit de TVP a membrului inferior','la cateter, se anticoagulează minimum 3 luni','are un algoritm de diagnostic bine stabilit','nu necesită anticoagulare dacă e legată de cateter'],'AC',1006,'TVP a membrului superior',
 'Recunoașterea diagnosticului și tratamentului TVP de membru superior.',
 ['Pacienții cu durere și edem de braț necesită ultrasonografie.','Nu: tratamentul urmează aceleași principii ca TVP a membrului inferior.','Anticoagularea durează cel puțin 3 luni, mai mult dacă cateterul rămâne.','Algoritmul nu este bine stabilit.','Se anticoagulează.']],
 [8,'Distractorii exclud tratamentul standard.'],['membrului superior','cateterul rămâne'],[1010]),

q('tromboembolism-adv-022',['În tratamentul tradițional al TEV cu heparină și warfarină:',
 ['heparina acționează după 24–48 de ore','warfarina are efect după minimum 5 zile','heparina se oprește la INR ≥2 două zile','warfarina acționează în primele 2 ore','heparina se oprește când INR ≥1,5 o zi'],'BC',1006,'Tratamentul inițial — Tratamentul tradițional',
 'Aplicarea tranziției de la heparină la warfarină.',
 ['Activitatea heparinei se instalează aproape imediat.','Warfarina necesită cel puțin 5 zile.','Heparina se oprește la INR ≥2,0 timp de 2 zile consecutive.','Warfarina are debut lent.','Pragul este INR ≥2,0 timp de 2 zile.']],
 [8,'Distractorii scurtează debutul warfarinei și coboară pragul INR.'],['2 zile consecutive','cel puţin 5 zile']),

q('tromboembolism-adv-005',['Fazele tratamentului anticoagulant în TEV:',
 ['faza acută durează 5–10 zile','faza de menținere durează minimum 3 luni','faza acută urmărește dizolvarea trombului','faza acută durează 3 luni','faza de menținere urmărește dizolvarea trombului'],'AB',1006,'Tratament — Fazele anticoagulării',
 'Recunoașterea fazelor și a obiectivelor anticoagulării.',
 ['Faza acută durează 5–10 zile.','Faza de menținere durează minimum 3 luni.','Nu: faza acută previne extinderea trombului și embolizarea; anticoagulantele nu dizolvă trombul.','Faza acută durează 5–10 zile.','Anticoagulantele nu dizolvă trombul; ulterior se previne recurența.']],
 [8,'Distractorii inversează durata și obiectivul fazelor.'],['5-10 zile','minimum 3 luni']),

q('tromboembolism-adv-023',['Îngrijirea în ambulatoriu și instabilitatea în EP:',
 ['EP cu risc scăzut PESI poate fi tratată ambulator','multe TVP pot fi îngrijite ambulator','șocul din EP se definește prin TAS <90 mmHg','șocul include scăderea TAS cu peste 40 mmHg','șocul din EP se definește prin TAS <110 mmHg'],'ABCD',1007,'Îngrijirea în ambulatoriu',
 'Aplicarea selecției pentru tratament ambulator și definiția EP instabile.',
 ['EP cu risc scăzut (PESI) poate fi tratată ambulator sau cu externare precoce.','Mulți pacienți cu TVP pot fi îngrijiți ambulator.','Șocul: TAS <90 mmHg sau scădere >40 mmHg peste 15 minute.','Șocul: TAS <90 mmHg sau scădere >40 mmHg peste 15 minute.','Pragul este TAS <90 mmHg.']],
 [8,'Distractorii exclud îngrijirea ambulatorie și deplasează pragul.'],['PESI','15 minute'],[1006]),

q('tromboembolism-adv-006',['Anticoagularea în sarcină și alăptare:',
 ['LMWH este tratamentul de elecție în sarcină','warfarina produce embriopatie între săptămânile 6 și 12','warfarina este contraindicată la alăptare','DOAC sunt sigure în sarcină','warfarina este sigură pe tot parcursul sarcinii'],'AB',1007,'Situații speciale — Femeile gravide',
 'Aplicarea alegerii anticoagulantului în sarcină și alăptare.',
 ['LMWH nu traversează placenta și este tratamentul de elecție.','Warfarina produce embriopatie între săptămânile 6 și 12.','Nu: warfarina și LMWH sunt sigure la alăptare.','DOAC traversează placenta și nu se folosesc în sarcină.','Warfarina este sigură doar până în săptămâna 6.']],
 [8,'Distractorii contrazic interdicțiile explicite.'],['hipoplazia nazală','6-a şi a 12-a'],[1008]),

q('tromboembolism-adv-051',['În PESI simplificat, mortalitatea la 30 de zile la 0 puncte este de aproximativ:',
 ['1%','4%','10,9%','24,5%','15%'],'A',1008,'Cadranul 29.5 — PESI',
 'Aplicarea stratificării PESI simplificat.',
 ['0 puncte: mortalitate 1%.','Nu este valoarea citată.','10,9% corespunde ≥1 punct.','24,5% este limita superioară a clasei V din PESI original.','Nu este valoarea citată.']],
 [8,'Valorile sunt permutate între trepte.'],['10,9%','PESI']),

q('tromboembolism-adv-077',['PESI original (Cadranul 29.5) stratifică riscul astfel:',
 ['clasa I: ≤65 de puncte','clasa V: peste 125 de puncte','statusul mental alterat: +60 de puncte','clasa V are mortalitate de 10–24,5%','statusul mental alterat: +10 puncte'],'ABCD',1008,'Cadranul 29.5 — PESI original',
 'Fixarea claselor și a punctajelor PESI original.',
 ['Clasa I: ≤65 de puncte, mortalitate 0–1,6%.','Clasa V: >125 de puncte, mortalitate 10–24,5%.','Statusul mental alterat valorează +60 de puncte.','Clasa V: >125 de puncte, mortalitate 10–24,5%.','Statusul mental valorează +60.']],
 [8,'Distractorii permută clasele și punctajul.'],['+60 puncte','Clasa V']),

q('tromboembolism-adv-087',['În TEV asociat cancerului activ:',
 ['LMWH a fost mai eficientă decât warfarina','DOAC pot fi la fel de eficiente ca LMWH','DOAC pot crește riscul de sângerare','DOAC reduc riscul de sângerare față de LMWH','warfarina este mai eficientă decât LMWH'],'ABC',1008,'Situații speciale — Pacienții cu cancer',
 'Compararea anticoagulantelor în tromboza asociată cancerului.',
 ['LMWH a fost mai eficientă decât warfarina.','DOAC pot fi cel puțin la fel de eficiente ca LMWH.','DOAC pot crește riscul de sângerare.','Riscul de sângerare poate crește.','LMWH a fost superioară warfarinei.']],
 [8,'Distractorii inversează profilul de siguranță.'],['cancer activ','sângerare']),

q('tromboembolism-adv-007',['În embolismul pulmonar masiv cu TAS ≤90 mmHg, tromboliza sistemică:',
 ['poate restabili rapid perfuzia pulmonară','are un risc de hemoragie intracraniană de ~20%','poate salva viața pacientului','sângerează mai rar decât anticoagularea','nu dizolvă trombul'],'AC',1008,'Rolul trombolizei',
 'Recunoașterea beneficiilor și riscurilor trombolizei în EP masivă.',
 ['Tromboliza restabilește rapid perfuzia pulmonară.','Nu: riscul de hemoragie intracraniană este de ~2%.','Poate salva viața în EP masivă.','Riscul hemoragic este mai mare decât al anticoagulării.','Tromboliticele dizolvă trombul.']],
 [8,'Distractorii inversează diferența dintre trombolitice și anticoagulante.'],['hemoragie intracraniană','restabilirea rapidă']),

q('tromboembolism-adv-078',['Tromboliza și filtrele de venă cavă inferioară:',
 ['rolul trombolizei în EP cu risc intermediar rămâne controversat','filtrele VCI reduc EP recurentă față de anticoagulare','filtrele recuperabile sunt preferate celor permanente','tromboliza este standardul în EP cu risc intermediar','filtrele permanente sunt preferate'],'AC',1008,'Rolul trombolizei și filtrele VCI',
 'Recunoașterea indicațiilor controversate și a limitelor filtrelor VCI.',
 ['Rolul trombolizei în EP intermediară rămâne controversat.','Nu: filtrele VCI nu reduc EP recurentă față de anticoagulare.','Filtrele recuperabile sunt preferate și se îndepărtează când anticoagularea devine sigură.','Tromboliza nu este standard în EP intermediară.','Filtrele recuperabile sunt preferate.']],
 [8,'Distractorii transformă controversele în reguli.'],['risc intermediar','recuperabile']),

q('tromboembolism-adv-008',['Filtrele de venă cavă inferioară:',
 ['se folosesc la contraindicația anticoagulării','se asociază independent cu risc crescut de TVP','nu împiedică complet embolii pulmonari','reduc EP recurentă față de anticoagulare','se folosesc la risc major de sângerare'],'ABCE',1008,'Abordări intervenționale — Filtrele VCI',
 'Aplicarea indicațiilor și limitelor filtrelor VCI.',
 ['Se folosesc la contraindicația anticoagulării sau risc major de sângerare.','Se asociază independent cu risc crescut de TVP.','Filtrele nu împiedică în totalitate embolii.','Nu reduc EP recurentă față de anticoagulare.','Se folosesc la contraindicația anticoagulării sau la risc major de sângerare.']],
 [8,'Distractorii supraestimează eficiența filtrelor.'],['vena cava inferioară','risc crescut de TVP']),

q('tromboembolism-adv-079',['Anticoagularea după TVP proximală sau EP:',
 ['durează minimum 3 luni','reduce riscul relativ de recurență cu 80–90%','are un risc de hemoragie majoră de 5–7% pe an','nu reduce riscul relativ de recurență','are un risc de hemoragie majoră de 10% pe an'],'AB',1008,'Durata tratamentului',
 'Aplicarea datelor de eficacitate și risc ale anticoagulării.',
 ['Anticoagularea continuă minimum 3 luni.','Reduce riscul relativ de recurență cu 80–90%.','Riscul absolut este de 1–3% pe an, nu 5–7%.','Reducerea relativă este de 80–90%.','Riscul este de 1–3% pe an.']],
 [8,'Distractorii subestimează eficiența și umflă riscul.'],['80-90%','1-3%']),

q('tromboembolism-adv-009',['Recurența după oprirea anticoagulării administrate minimum 3 luni pentru TEV:',
 ['este de ~5% în anul următor','este mai mare după TEV neprovocat','nu scade prin prelungirea tratamentului','este mai mică la bărbați','este de ~30% în anul următor'],'ABC',1009,'Durata tratamentului — Recurența',
 'Interpretarea riscului de recurență după oprirea anticoagulării.',
 ['Riscul este de ~5% în anul următor.','Riscul este mai mare după TEV neprovocat.','O durată mai lungă nu reduce recurența după oprire.','Riscul este mai mare la bărbați.','30% la 5 ani este riscul pentru TEV neprovocat.']],
 [8,'Distractorii inversează sexul și confundă intervalele.'],['5% în următorul an','cel puţin 3 luni'],[1010]),

q('tromboembolism-adv-054',['Riscul de recurență după TEV:',
 ['TEV neprovocat: ~10% la 1 an și ~30% la 5 ani','este mai mare la bărbați','este mai mare după EP sau TVP proximală decât după TVP distală','este mai mare după TVP distală decât după EP','TEV neprovocat: ~30% la 1 an'],'ABC',1010,'Riscul de recurență',
 'Fixarea factorilor care modifică riscul de recurență.',
 ['TEV neprovocat: ~10% la 1 an și 30% la 5 ani.','Riscul este mai mare la bărbați.','EP și TVP proximală au risc mai mare decât TVP distală.','TVP distală are risc mai mic.','30% corespunde intervalului de 5 ani.']],
 [8,'Distractorii inversează ierarhia și intervalele.'],['30% la 5 ani','bărbaţi']),

q('tromboembolism-adv-025',['Complicațiile TEV:',
 ['sindromul post-trombotic apare la ~40% după TVP proximală','mortalitatea la 1 lună în EP este în jur de 15%','cancerul este principala cauză de deces la 1 an','sindromul post-trombotic apare la sub 5% după TVP proximală','mortalitatea la 1 lună în EP depășește 30%'],'AC',1010,'Complicații — Mortalitatea și SPT',
 'Fixarea datelor despre mortalitate și sindromul post-trombotic.',
 ['SPT apare la ~40% după TVP proximală.','Mortalitatea la 1 lună în EP este ~5%, nu 15%.','Cancerul este principala cauză de deces.','Proporția SPT este de ~40%.','Mortalitatea la 1 lună este ~5%.']],
 [8,'Distractorii subestimează SPT și umflă mortalitatea precoce.'],['40%','5%']),

q('tromboembolism-adv-055',['Sindromul post-trombotic:',
 ['poate produce lipodermatoscleroză','produce ulcerație de membru inferior la 5–10%','are rolul ciorapilor de 24 mmHg în prevenție controversat','produce ulcerație la majoritatea pacienților','se previne sigur prin ciorapi de compresie'],'ABC',1010,'Sindromul post-trombotic',
 'Recunoașterea formelor severe și a prevenției SPT.',
 ['Forma severă produce roșeață, hiperpigmentare, ectazii și lipodermatoscleroză.','5–10% dezvoltă ulcerație de membru inferior.','Rolul ciorapilor de cel puțin 24 mmHg rămâne controversat.','Ulcerația apare la 5–10%.','Eficiența ciorapilor este controversată.']],
 [8,'Distractorii supraestimează severitatea și eficiența prevenției.'],['lipoder','24 mmHg']),

q('tromboembolism-adv-024',['Tromboza asociată cancerului (sindromul Trousseau):',
 ['reprezintă 10–20% din episoadele de TEV','este urmată de cancer diagnosticat în 12 luni la până la 5% din TEV neprovocate','are o patogeneză multifactorială','reprezintă sub 1% din episoadele de TEV','nu justifică evaluare suplimentară după TEV neprovocat'],'ABC',1010,'Complicații — Cancerul asociat',
 'Recunoașterea asocierii dintre cancer și TEV.',
 ['10–20% dintre episoadele de TEV apar la persoane cu cancer.','Până la 5% dintre TEV neprovocate sunt urmate de diagnostic de cancer în 12 luni.','Patogeneza include hipercoagulabilitate, chirurgie, chimioterapie, imobilitate, catetere.','Proporția este de 10–20%.','NICE recomandă evaluare suplimentară peste 40 de ani.']],
 [8,'Distractorii subestimează asocierea.'],['Trousseau','10-20%']),

q('tromboembolism-adv-038',['Hipertensiunea pulmonară tromboembolică cronică:',
 ['apare la până la 5% după EP','se diagnostichează prin scintigrafie de perfuzie, CTPA și ecocardiografie','poate fi tratată prin endarterectomie pulmonară','apare la aproximativ 40% după EP','se tratează prin tromboliză sistemică tardivă'],'ABC',1011,'Complicații — Hipertensiunea pulmonară',
 'Recunoașterea frecvenței, diagnosticului și tratamentului CTEPH.',
 ['Până la 5% dintre pacienți rămân cu CTEPH.','Diagnosticul folosește scintigrafia de perfuzie, CTPA și ecocardiografia.','Unii pacienți sunt tratați prin endarterectomie pulmonară.','40% este frecvența SPT după TVP proximală.','Nu este tratamentul citat.']],
 [8,'Distractorii confundă CTEPH cu sindromul post-trombotic.'],['endarterectomie','CTEPH'],[1010]),

q('tromboembolism-adv-035',['Testarea trombofiliei în TEV:',
 ['trombofiliile ereditare apar la ~20% dintre cazurile de TEV','trombofiliile ereditare nu au rol semnificativ în tromboza arterială','indicațiile testării rămân controversate','trombofiliile ereditare explică majoritatea trombozelor arteriale','testarea se face de rutină înaintea primei doze de anticoagulant'],'ABC',1011,'Testarea trombofiliei',
 'Recunoașterea rolului și a limitelor testării trombofiliei.',
 ['Trombofiliile ereditare apar în ~20% din TEV.','Nu joacă un rol semnificativ în tromboza arterială.','Indicațiile testării rămân controversate.','Nu au rol semnificativ în tromboza arterială.','Testarea se face de preferință după faza acută.']],
 [8,'Distractorii generalizează testarea și rolul arterial.'],['20% din cazurile','controversate']),

q('tromboembolism-adv-010',['Factorul V Leiden:',
 ['face factorul Va rezistent la proteina C activată','crește riscul de TEV de ~5 ori la heterozigoți','este prezent la ~50% dintre cazurile de TEV','scade nivelul de protrombină','crește riscul de TEV de ~50 de ori la heterozigoți'],'AB',1011,'Trombofiliile ereditare — Factorul V Leiden',
 'Recunoașterea mecanismului și a riscului conferit de factorul V Leiden.',
 ['Factorul Va devine rezistent la proteina C activată.','Heterozigoții au risc de TEV de cinci ori mai mare.','Factorul V Leiden este prezent la ~20%, nu 50%, din cazurile de TEV.','Mutația protrombinei crește nivelul de protrombină.','Riscul este de ~5 ori.']],
 [8,'Distractorii confundă mecanismul cu cel al mutației protrombinei.'],['proteina C activată','cinci ori']),

q('tromboembolism-adv-056',['Factorul V Leiden:',
 ['heterozigot este prezent la ~5% dintre europeni','lipsește în populațiile din estul Asiei','crește riscul de ~30 de ori asociat cu contraceptivul oral combinat','homozigot are risc de ~10 ori mai mare decât heterozigotul','asociat cu contraceptivul oral depășește un risc absolut de 5% pe an'],'ABCD',1011,'Trombofiliile ereditare — Factorul V Leiden',
 'Fixarea prevalenței și a interacțiunilor factorului V Leiden.',
 ['Heterozigotul este prezent la ~5% dintre europeni și mediteraneeni.','Nu se găsește în estul Asiei.','Cu pilula combinată, riscul crește de ~30 de ori.','Homozigoții au risc de ~10 ori mai mare decât heterozigoții.','Riscul absolut rămâne sub 0,5% pe an.']],
 [8,'Singurul distractor umflă riscul absolut.'],['30 de ori','estul Asiei']),

q('tromboembolism-adv-057',['Mutația G20210A a genei protrombinei:',
 ['crește nivelul de protrombină','crește riscul de TEV de 2–3 ori','este prezentă la ~12% din populația albă','scade nivelul de protrombină','crește riscul de TEV de 30 de ori'],'AB',1011,'Trombofiliile ereditare — Mutația protrombinei',
 'Recunoașterea mecanismului și riscului mutației protrombinei.',
 ['Mutația crește nivelul de protrombină.','Riscul de TEV crește de 2–3 ori.','Este prezentă la ~2%, nu 12%, din populația albă.','Nivelul crește.','30 de ori este riscul FV Leiden cu contraceptiv.']],
 [8,'Distractorii inversează mecanismul și împrumută cifre ale FV Leiden.'],['G20210A','2-3 ori']),

q('tromboembolism-adv-011',['Deficitele anticoagulanților naturali:',
 ['deficitul heterozigot de antitrombină crește riscul de ~10 ori','deficitele de proteină C și S cresc riscul de cel puțin 5 ori','deficitul de antitrombină se identifică prin activitate','deficitul de antitrombină se diagnostichează genetic','deficitul de antitrombină crește sensibilitatea la heparină'],'ABC',1011,'Trombofiliile ereditare — Pierderea funcției anticoagulante',
 'Aplicarea diagnosticului și riscului deficitelor anticoagulante.',
 ['Deficitul heterozigot de antitrombină crește riscul de ~10 ori.','Deficitele de proteină C și S cresc riscul de cel puțin 5 ori.','Se măsoară activitatea antitrombinei, nu testarea genetică.','Au fost descrise multiple mutații; testarea genetică nu este metoda.','Pacienții pot fi relativ rezistenți la heparină.']],
 [8,'Distractorii inversează metoda de diagnostic și răspunsul la heparină.'],['10 ori','activităţii antitrombinei']),

q('tromboembolism-adv-058',['Deficitul de antitrombină:',
 ['poate fi dobândit după heparină','poate fi dobândit în sindromul nefrotic','produce rezistență relativă la heparină','poate fi dobândit după warfarină','crește sensibilitatea la heparină'],'ABC',1011,'Trombofiliile ereditare — Antitrombina',
 'Interpretarea nivelurilor scăzute de antitrombină.',
 ['Nivelul scăzut poate fi dobândit după heparină.','Poate fi dobândit și în boli hepatice sau sindrom nefrotic.','Antitrombina este necesară acțiunii heparinei, deci pot exista rezistențe.','Cauzele dobândite citate sunt heparina, bolile hepatice și sindromul nefrotic.','Poate exista rezistență relativă.']],
 [8,'Distractorii neagă cauzele dobândite și inversează răspunsul la heparină.'],['sindromul nefrotic','rezistenţi la heparină']),

q('tromboembolism-adv-059',['Proteinele C și S:',
 ['sunt dependente de vitamina K','inhibă factorii Va și VIIIa','scad sub tratament cu warfarină','au deficit homozigot cu purpură fulminantă','inhibă factorii Xa și IIa'],'ABCD',1012,'Trombofiliile ereditare — Proteinele C și S',
 'Recunoașterea mecanismului și a diagnosticului deficitelor de proteină C și S.',
 ['Proteinele C și S sunt dependente de vitamina K.','Ele inhibă factorii Va și VIIIa.','Nivelurile pot fi scăzute sub warfarină.','Deficiențele homozigote produc purpură fulminantă neonatală.','Antitrombina inhibă Xa și trombina.']],
 [8,'Distractorii preiau ținta antitrombinei și schimbă manifestarea homozigotă.'],['purpura fulminantă','deficit de vitamina K']),

q('tromboembolism-adv-060',['Diagnosticul de sindrom antifosfolipidic trebuie luat în considerare la:',
 ['TEV neprovocat sub 50 de ani','tromboză arterială inexplicabilă sub 50 de ani','APTT prelungit incidental','TEV provocat de chirurgie majoră la vârstnic','timp de sângerare prelungit izolat'],'ABC',1012,'Sindromul antifosfolipidic',
 'Recunoașterea situațiilor care sugerează SAFL.',
 ['TEV la vârstă tânără, mai ales neprovocat.','Tromboza arterială inexplicabilă sub 50 de ani.','APTT prelungit incidental, cu tendință protrombotică.','Nu este criteriul citat.','Nu este criteriul citat.']],
 [8,'Distractorii sunt situații cu risc protrombotic banal.'],['<50 de ani','APTT']),

q('tromboembolism-adv-084',['În sindromul antifosfolipidic:',
 ['riscul de recurență a TEV este crescut','DOAC pot fi mai puțin eficiente decât warfarina','forma obstetricală primește aspirină și LMWH','DOAC sunt mai eficiente decât warfarina','forma obstetricală primește warfarină'],'ABC',1012,'Sindromul antifosfolipidic — Tratament',
 'Aplicarea tratamentului în sindromul antifosfolipidic.',
 ['SAFL se asociază cu risc crescut de recurență.','DOAC ar putea fi mai puțin eficiente decât warfarina.','Femeile cu SAFL obstetrical primesc aspirină și LMWH profilactică.','Warfarina pare mai eficientă.','Warfarina este teratogenă.']],
 [8,'Distractorii inversează ierarhia anticoagulantelor.'],['DOAC ar putea fi mai puţin','aspirină în doză mică'],[1013]),

q('tromboembolism-adv-026',['Profilaxia TEV la internare:',
 ['toți adulții internați necesită evaluarea riscului','o treime până la jumătate dintre TEV sunt provocate de internare sau chirurgie','la risc hemoragic se poate aplica profilaxia mecanică','profilaxia farmacologică este indicată și la risc hemoragic înalt','evaluarea riscului se rezervă pacienților chirurgicali'],'ABC',1013,'Profilaxia',
 'Aplicarea principiilor tromboprofilaxiei.',
 ['Toți adulții internați necesită evaluare formală a riscului.','O treime până la jumătate dintre TEV sunt provocate de chirurgie sau internare.','La risc hemoragic se aplică profilaxia mecanică.','La risc hemoragic, profilaxia farmacologică poate fi improprie.','Toți adulții internați se evaluează.']],
 [8,'Distractorii contrazic regula evaluării universale.'],['evaluare formală','profilaxia mecanică']),

q('tromboembolism-adv-027',['Profilaxia mecanică a TEV:',
 ['include mobilizarea precoce','include ciorapii antiembolie','include compresia pneumatică intermitentă','include ciorapii în AVC acut','include ciorapii în arteriopatia periferică'],'ABC',1013,'Profilaxia mecanică',
 'Enumerarea măsurilor mecanice și a contraindicațiilor ciorapilor.',
 ['Mobilizarea precoce este o măsură mecanică.','Ciorapii antiembolie sunt o măsură mecanică.','Dispozitivele de compresie intermitentă sunt o măsură mecanică.','Ciorapii nu se folosesc în AVC.','Ciorapii nu se folosesc în boala arterială periferică.']],
 [8,'Distractorii sunt contraindicații explicite ale ciorapilor.'],['ciorapilor anti-emboliei','compresie intermitentă']),

q('tromboembolism-adv-039',['Profilaxia farmacologică a TEV:',
 ['folosește doze subterapeutice','folosește cel mai adesea LMWH','poate continua după externare în cancer','folosește doze terapeutice','se oprește la externare în chirurgia oncologică'],'ABC',1013,'Profilaxia farmacologică',
 'Aplicarea principiilor profilaxiei farmacologice.',
 ['Profilaxia folosește doze mai mici decât cele terapeutice.','Cel mai adesea se folosesc LMWH.','După chirurgia abdominală pentru cancer poate continua după externare.','Dozele sunt subterapeutice.','Poate continua după externare.']],
 [8,'Distractorii contrazic dozarea și durata.'],['doze mai mici','cancer']),

q('tromboembolism-adv-083',['DOAC în doză mică după artroplastia majoră de șold sau genunchi:',
 ['au fost aprobate pentru prevenția TEV','se continuă 2–5 săptămâni postoperator','se administrează ca doză unică intraoperatorie','se continuă 6 luni postoperator','sunt contraindicate după artroplastie'],'AB',1013,'Profilaxia farmacologică — Artroplastia',
 'Aplicarea profilaxiei cu DOAC după artroplastie.',
 ['DOAC în doză mică au fost aprobate după artroplastie.','Se continuă 2–5 săptămâni după operație.','Nu este schema citată.','Durata citată este 2–5 săptămâni.','Sunt aprobate în acest context.']],
 [8,'Distractorii schimbă durata și indicația.'],['2-5 săptămâni','artroplastie']),

q('tromboembolism-adv-082',['După artroplastia majoră de șold sau genunchi, aspirina:',
 ['reduce riscul de tromboză venoasă','crește riscul de tromboză venoasă','nu influențează riscul de tromboză venoasă','este contraindicată','înlocuiește profilaxia mecanică'],'A',1013,'Profilaxia farmacologică — Aspirina',
 'Recunoașterea rolului aspirinei în profilaxia după artroplastie.',
 ['Aspirina reduce riscul de tromboză venoasă după artroplastie.','Nu este efectul citat.','Deși tradițional nu se credea util, s-a dovedit că reduce riscul.','Nu este citată contraindicația.','Nu este afirmația citată.']],
 [8,'Distractorul principal reflectă opinia tradițională contrazisă de text.'],['aspirina reduce riscul','artroplastie']),

q('tromboembolism-adv-081',['Conform Cadranului 29.6, reprezintă risc de sângerare:',
 ['trombocitele sub 75 × 10⁹/L','hipertensiunea necontrolată ≥230/120 mmHg','puncția lombară în ultimele 4 ore','vârsta peste 60 de ani','obezitatea cu IMC peste 30 kg/m²'],'ABC',1013,'Cadranul 29.6 — Riscul de TEV și sângerare',
 'Diferențierea factorilor de risc hemoragic de cei trombotici.',
 ['Trombocitopenia <75 × 10⁹/L este risc de sângerare.','HTA necontrolată ≥230/120 mmHg este risc de sângerare.','Puncția lombară în ultimele 4 ore este risc de sângerare.','Vârsta >60 de ani este risc de tromboză.','Obezitatea este risc de tromboză.']],
 [8,'Distractorii sunt factori de risc trombotic din același cadran.'],['75 x','230/120']),

q('tromboembolism-adv-040',['Inițierea coagulării începe prin legarea:',
 ['factorului VII de factorul tisular','factorului XII de factorul tisular','factorului X de factorul tisular','factorului VII de trombomodulină','factorului XI de factorul tisular'],'A',1014,'Medicația anticoagulantă — Coagularea',
 'Recunoașterea etapelor inițierii coagulării.',
 ['Inițierea începe prin legarea factorului VII de factorul tisular.','Nu este mecanismul citat.','Factorul X este activat ca rezultat, nu se leagă inițial.','Nu este mecanismul citat.','Nu este mecanismul citat.']],
 [8,'Distractorii schimbă factorul inițiator și ocolesc trombina.'],['factorul tisular','sistemului intrinsec']),

q('tromboembolism-adv-028',['Heparina nefracționată:',
 ['acționează prin antitrombină','inhibă mai ales trombina și factorul Xa','se monitorizează prin APTT','se absoarbe complet oral','se elimină predominant renal'],'ABC',1014,'Heparina',
 'Recunoașterea mecanismului și monitorizării UFH.',
 ['Heparina crește activitatea antitrombinei de cel puțin 1.000 de ori.','Inhibă mai ales trombina și factorul Xa.','Se monitorizează prin APTT, țintă 1,5–2,5 ori controlul.','Heparina este distrusă în stomac.','UFH nu are excreție renală.']],
 [8,'Distractorii contrazic calea de administrare și eliminare.'],['antitrombina','APTT']),

q('tromboembolism-adv-062',['Un avantaj al heparinei nefracționate față de LMWH este:',
 ['lipsa excreției renale','administrarea o dată pe zi','biodisponibilitatea orală','inhibarea selectivă a factorului Xa','monitorizarea de laborator inutilă'],'A',1014,'Heparina nefracționată',
 'Recunoașterea proprietăților favorabile ale UFH.',
 ['UFH nu are excreție renală, spre deosebire de LMWH.','Timpul scurt de înjumătățire impune administrări repetate.','Nu se administrează oral.','Inhibiția selectivă a Xa caracterizează LMWH.','UFH se monitorizează prin APTT.']],
 [8,'Distractorii contrazic farmacocinetica UFH.'],['1 oră','protamină']),

q('tromboembolism-adv-061',['Heparina cu greutate moleculară mică:',
 ['inhibă factorul Xa mai mult decât trombina','are activitate maximă la 4 ore','se elimină pe cale renală','inhibă trombina mai mult decât factorul Xa','este complet reversibilă cu protamină'],'ABC',1014,'Heparina cu greutate moleculară mică',
 'Diferențierea LMWH de UFH.',
 ['Lanțurile scurte inhibă Xa mai mult decât trombina.','Activitatea maximă este la 4 ore.','LMWH se excretă renal.','Inhibarea trombinei cere lanțuri de cel puțin 18 zaharide.','Protamina inversează doar parțial LMWH.']],
 [8,'Distractorii inversează selectivitatea și reversibilitatea.'],['18 zaharide','4 ore']),

q('tromboembolism-adv-029',['Fondaparinuxul:',
 ['inhibă doar factorul Xa','are un timp de înjumătățire de aproximativ 8 ore','nu este inversat de protamină','inhibă și trombina','are un timp de înjumătățire de 1 oră'],'AC',1015,'Fondaparinux',
 'Recunoașterea proprietăților fondaparinuxului.',
 ['Prin lanțul scurt, fondaparinuxul inhibă doar Xa.','Timpul de înjumătățire este de ~18 ore, nu 8.','Efectul nu este inversat de protamină.','Nu inhibă trombina.','1 oră este timpul de înjumătățire al UFH.']],
 [8,'Distractorii preiau proprietăți ale UFH.'],['pentazaharid','18 ore']),

q('tromboembolism-adv-012',['Trombocitopenia indusă de heparină:',
 ['se manifestă predominant prin sângerare cutanată','apare de obicei la 5–14 zile de la heparină','are un risc de tromboză de 50% fără tratament','se manifestă predominant prin sângerare','apare de obicei în prima oră de la heparină'],'ABC',1015,'Trombocitopenia indusă de heparină',
 'Recunoașterea mecanismului și a cronologiei HIT.',
 ['HIT este mediată de IgG împotriva complexului heparină–FP4.','Apare de obicei la 5–14 zile.','Fără tratament, riscul de tromboză este de 50%.','HIT are o tendință protrombotică.','Debutul este la 5–14 zile.']],
 [8,'Distractorii inversează consecința clinică și cronologia.'],['factorul 4 plachetar','5-14']),

q('tromboembolism-adv-013',['La suspiciunea sau confirmarea HIT:',
 ['se oprește orice heparină, inclusiv la catetere','se administrează anticoagulant non-heparinic','se pot folosi argatroban sau fondaparinux','se înlocuiește heparina nefracționată cu LMWH','se poate reexpune ulterior la heparină'],'ABC',1015,'Trombocitopenia indusă de heparină — Management',
 'Aplicarea conduitei în HIT.',
 ['Orice heparină se întrerupe, inclusiv la spălarea cateterelor.','Se administrează un anticoagulant non-heparinic.','Alternativele includ danaparoid, argatroban și fondaparinux.','LMWH este tot o heparină.','Pacienții nu trebuie reexpuși la heparină.']],
 [8,'Distractorii propun reexpunerea la heparine.'],['argatroban','spălarea cateterelor']),

q('tromboembolism-adv-031',['Warfarina:',
 ['inhibă sinteza factorilor II, VII, IX și X','inhibă sinteza proteinelor C și S','are efect complet după cel puțin 5 zile','inhibă direct factorul Xa și trombina','are efect complet în primele 2 ore'],'ABC',1016,'Antagoniștii vitaminei K',
 'Recunoașterea mecanismului și cineticii warfarinei.',
 ['Warfarina inhibă sinteza factorilor II, VII, IX și X.','Inhibă și sinteza proteinelor C și S.','Efectul complet necesită cel puțin 5 zile.','Inhibitorii direcți de Xa sunt DOAC.','2 ore este Tmax al DOAC.']],
 [8,'Distractorii atribuie warfarinei proprietăți ale DOAC.'],['protrombina','cel puţin 5 zile']),

q('tromboembolism-adv-032',['Monitorizarea și riscurile warfarinei:',
 ['ținta INR este 2,0–3,0 la majoritatea pacienților','riscul de sângerare majoră este de ~10% pe an','este sigură la alăptare','majoritatea sângerărilor apar la INR peste 5','ținta INR este 3,0–4,0 la majoritatea pacienților'],'AC',1016,'Warfarina — Monitorizare și riscuri',
 'Aplicarea țintelor INR și a riscurilor warfarinei.',
 ['Ținta INR este 2,0–3,0 la majoritatea pacienților.','Riscul de sângerare majoră este de 2%, nu 10%, pe an.','Warfarina nu trece în laptele matern.','Majoritatea sângerărilor apar la INR în intervalul terapeutic.','3,0–4,0 se folosește la o minoritate.']],
 [8,'Distractorii inversează ținta și distribuția sângerărilor.'],['2,0-3,0','2% pe an']),

q('tromboembolism-adv-085',['Interacțiunile warfarinei:',
 ['inductorii citocromului P450 scad INR-ul','aspirina crește riscul hemoragic prin efect antiplachetar','alcoolul și alimentele interacționează cu warfarina','aspirina crește nivelul plasmatic de warfarină','warfarina are un indice terapeutic larg'],'ABC',1016,'Warfarina — Interacțiuni',
 'Recunoașterea tipurilor de interacțiuni ale warfarinei.',
 ['Inductorii P450 reduc nivelurile de warfarină și INR.','Aspirina și clopidogrelul sporesc riscul hemoragic prin efect antiplachetar.','Warfarina interacționează cu factori alimentari și alcool.','Aspirina nu modifică nivelul warfarinei.','Warfarina are un indice terapeutic îngust.']],
 [8,'Distractorii confundă interacțiunea farmacodinamică cu cea farmacocinetică.'],['citocromului P450','clopidogrelul']),

q('tromboembolism-adv-063',['Conform Cadranului 29.8, la INR peste 5,0 fără sângerare:',
 ['se oprește warfarina','se reduce doza de întreținere','se investighează cauza INR-ului crescut','se administrează complex protrombinic','se administrează vitamina K 5 mg i.v.'],'ABC',1016,'Cadranul 29.8 — INR crescut',
 'Aplicarea conduitei la INR crescut fără sângerare.',
 ['Se oprește warfarina.','Se reduce doza de întreținere.','Se investighează cauza INR-ului crescut.','PCC se administrează la sângerare majoră.','Vitamina K 5 mg i.v. se dă la sângerare majoră.']],
 [8,'Distractorii sunt măsurile rezervate sângerării majore.'],['INR >5,0','Se reduce doza']),

q('tromboembolism-adv-086',['Conform Cadranului 29.8, la sângerare majoră sub warfarină:',
 ['se administrează complex protrombinic 25–50 U/kg','se administrează vitamina K 5 mg i.v.','se repetă INR-ul după complexul protrombinic','se oprește warfarina','se continuă warfarina în doză redusă'],'ABCD',1016,'Cadranul 29.8 — Sângerarea majoră',
 'Aplicarea conduitei la sângerarea majoră sub warfarină.',
 ['Se administrează PCC 25–50 U/kg (sau plasmă 15 ml/kg).','Se administrează vitamina K 5 mg i.v.','INR se repetă după PCC.','Warfarina se oprește.','Warfarina se oprește, nu se continuă.']],
 [8,'Distractorii aplică schema INR-ului crescut fără sângerare.'],['25-50 u/kg','vitamină K 5 mg']),

q('tromboembolism-adv-033',['Conform Cadranului 29.9, anticoagulantele orale directe:',
 ['au efect maxim la aproximativ 2 ore','dabigatranul are eliminare renală de ~80%','antidotul dabigatranului este idarucizumab','rivaroxabanul și apixabanul inhibă factorul Xa','antidotul dabigatranului este vitamina K'],'ABCD',1017,'Cadranul 29.9 — DOAC',
 'Compararea proprietăților farmacologice ale DOAC.',
 ['Efectul maxim apare la ~2 ore.','Dabigatranul are eliminare renală de 80%.','Idarucizumab este antidotul dabigatranului.','Rivaroxabanul și apixabanul sunt inhibitori ai factorului Xa.','Vitamina K este antidotul warfarinei.']],
 [8,'Distractorii permută eliminarea renală și antidotul.'],['ldarucizumab','80%']),

q('tromboembolism-adv-034',['Situațiile speciale ale anticoagulantelor orale directe:',
 ['nu se folosesc în sarcină','sunt contraindicate la valve mecanice','cresc sângerarea digestivă în cancer','sunt contraindicate în stenoza mitrală severă','pot fi folosite în siguranță la alăptare'],'ABCD',1017,'DOAC — Situații speciale',
 'Aplicarea contraindicațiilor DOAC.',
 ['DOAC traversează placenta și nu se folosesc în sarcină.','Sunt contraindicate la protezele valvulare mecanice.','În cancer cresc riscul de sângerare gastrointestinală.','Sunt contraindicate în stenoza mitrală moderată sau severă.','Nu se folosesc la alăptare.']],
 [8,'Distractorii contrazic contraindicațiile explicite.'],['stenoză mitrală','sângerare gastrointestinală']),

q('tromboembolism-adv-064',['Profilul hemoragic al anticoagulantelor orale directe:',
 ['are un risc redus de hemoragie intracraniană','are un risc crescut de hemoragie gastrointestinală','impune la sângerare majoră oprirea DOAC și tratament suportiv','are un risc crescut de hemoragie intracraniană','are un risc redus de hemoragie gastrointestinală'],'ABC',1017,'DOAC — Sângerarea',
 'Recunoașterea profilului hemoragic al DOAC.',
 ['DOAC au risc redus de hemoragie intracraniană.','Riscul redus este contrabalansat de risc crescut de hemoragie gastrointestinală.','La sângerare majoră se oprește DOAC și se dă suport.','Riscul intracranian este redus.','Riscul gastrointestinal este crescut.']],
 [8,'Distractorii inversează profilul hemoragic.'],['hemoragie intracraniană','gastrointestinală']),

q('tromboembolism-adv-088',['Diagnosticul hipertensiunii pulmonare tromboembolice cronice se bazează pe:',
 ['scintigrafia pulmonară de perfuzie','angiografia pulmonară CT','ecocardiografie','dozarea D-dimerilor','radiografia toracică izolată'],'ABC',1010,'Complicații — Hipertensiunea pulmonară',
 'Identificarea investigațiilor de diagnostic ale CTEPH.',
 ['Monitorizarea prin scintigrafie de perfuzie este citată.','CTPA dovedește ocluzia reziduală.','Ecocardiografia sugerează hipertensiunea pulmonară.','D-dimerii nu sunt citați.','Radiografia izolată nu este suficientă.']],
 [8,'Distractorii sunt investigații ale EP acute, nu ale CTEPH.'],['scintigrafie pulmonară de perfuzie','CTPA'],[1011]),

q('tromboembolism-adv-037',['Femeile cu sindrom antifosfolipidic în context obstetrical primesc, în general:',
 ['aspirină în doză mică și LMWH profilactică','warfarină pe tot parcursul sarcinii','DOAC în doză profilactică','doar aspirină după săptămâna 36','LMWH în doză terapeutică asociată cu clopidogrel'],'A',1013,'Sindromul antifosfolipidic — Sarcina',
 'Aplicarea tratamentului SAFL obstetrical.',
 ['Se administrează aspirină în doză mică și LMWH profilactică, pe tot parcursul sarcinii.','Warfarina este teratogenă.','DOAC traversează placenta.','Nu este schema citată.','Nu este schema citată.']],
 [8,'Distractorii sunt anticoagulante nepotrivite sarcinii.'],['aspirină în doză mică','context obstetrical']),
];
