import {advancedQuestion} from './advanced-author';
import type {SourceRow} from './source-author';

const EDITION='Chirurgie generală și specialități chirurgicale, ediția pentru rezidențiat MG 2025';
const pdfOffset=(p:number)=>p-329;
const q=(n:number,row:SourceRow,score:number,reason:string,expressions:string[],related:number[]=[])=>
 advancedQuestion('urologie',29,pdfOffset,`urologie-adv-${String(n).padStart(3,'0')}`,row,[score,reason],expressions,undefined,related,'Lawrence',EDITION);

export const UROLOGIE_D=[
q(92,['Identificați afirmația corectă referitoare la secrețiile și evoluția prostatei:',
 ['Secrețiile glandei prostatice reprezintă aproximativ 20% din volumul ejaculatului normal și furnizează substanțe nutritive pentru motilitatea spermatozoizilor','Prostata înconjoară uretra pe o distanță de 8–10 cm, analog uretrei feminine','Glanda rămâne latentă până în a șaptea decadă, când începe secreția exocrină','Lichidul prostatic inhibă motilitatea spermatozoizilor, reducând volumul ejaculatului sub 5%','Creșterea în volum începe din prima decadă de viață și nu conduce la hiperplazie'],'A',635,'Prostata — Secreții (20% din ejaculat) și lag-ul pubertar',
 'Recunoașterea cotei de 20% din ejaculat și a latenței până la pubertate, distincte de uretra prostatică de 2–3 cm.',
 ['Textul precizează că secrețiile reprezintă aproximativ 20% din volumul ejaculatului și hrănesc motilitatea spermatozoizilor.','Uretra prostatică măsoară 2–3 cm, nu 8–10 cm.','Prostata rămâne latentă de la naștere până la pubertate, apoi funcționează ca glandă exocrină.','Lichidul prostatic susține motilitatea, nu o inhibă.','Creșterea în volum începe din a patra decadă și poate conduce la HBP.']],
 8,'Permutează cota de 20% din ejaculat cu lungimea uretrei și mută debutul creșterii din decada a patra în copilărie.',['20% din volumul ejaculatului','a patra decadă']),

q(93,['Hiperplazia benignă de prostată se caracterizează prin:',
 ['Combină hiperplazia (proliferarea numărului de celule) cu hipertrofia (creșterea în volum a celulelor) în zona tranzițională','Procesul poate fi demonstrat histologic încă din a treia decadă a vieții; simptomele sunt mai puțin întâlnite înainte de 50 de ani','Nu există o corelație directă între mărimea prostatei și simptomatologie','Simptomele HBP sunt tipice înainte de 30 de ani, zona centrală fiind sediul proliferării','HBP cauzează, demonstrat, carcinomul prostatic, prin aceeași hipertrofie acinară'],'ABC',636,'HBP — Hiperplazie plus hipertrofie din decada a treia',
 'Potrivirea dublului mecanism celular, a debutului histologic din decada a treia și a lipsei de corelație volum–simptom.',
 ['Definiția prin hiperplazie și hipertrofie, în zona tranzițională, este explicită.','Dovada histologică din a treia decadă și rarisimitatea simptomelor înainte de 50 de ani sunt citate.','Absența corelației directe mărime–simptomatologie este enunțată.','Simptomele sunt mai puțin întâlnite înainte de 50 de ani; sediul este zona tranzițională, nu cea centrală.','Textul neagă o asociere cauzală între HBP și cancer.']],
 8,'Mută debutul histologic din decada a treia înainte de 30 de ani și inventează cauzalitatea HBP–cancer din același paragraf epidemiologic.',['zona tranziţională','a treia decadă']),

q(94,['Selectați enunțurile adevărate despre cuantificarea simptomelor și chirurgia transuretrală a HBP:',
 ['Cistoscopia dezvăluie hiperplazia trilobară și, nu de puține ori, un lob median cu mecanism de „valvă cu bilă”','Riscul de incontinență după TURP este scăzut (1–2%)','Pacientul rămâne internat 7–10 zile după TURP, micțiunea fiind amânată până la controlul de o lună','Simptomele sunt cuantificate adesea cu chestionarul Asociației Urologice Americane, îmbunătățirea scorului măsurând răspunsul','Disfuncția sexuală asociată TURP apare la peste jumătate dintre pacienți'],'ABD',637,'HBP — Valva cu bilă, scor AUA și incontinența 1–2%',
 'Citirea cistoscopiei cu lob median „valvă cu bilă”, a internării scurte și a incontinenței de 1–2%, față de disfuncția sexuală <5%.',
 ['Hiperplazia trilobară și analogia „valvă cu bilă” a lobului median sunt explicite.','Pragul de incontinență 1–2% este citat la finalul paginii.','Internarea este de una sau două nopți, cu micțiune adecvată la externare.','Chestionarul AUA și folosirea scorului ca măsură obiectivă sunt descrise.','Disfuncția sexuală asociată procedurii apare la <5% dintre pacienți, pe pagina următoare.']],
 8,'Umflă internarea de 1–2 nopți la o săptămână și disfuncția sexuală de sub 5% la peste 50%.',['valvă cu bilă','1-2%'],[638]),

q(95,['Procedura cel mai frecvent utilizată, în afară de TURP, pentru simptomele de tract urinar inferior este:',
 ['Termoterapia transuretrală cu microunde, încă folosită pe scară largă pentru ameliorare majoră','Tratamentul cu laser GreenLight, prin vaporizarea țesutului prostatic, cu hemoragie mai redusă decât electrorezecția','Ablația transuretrală cu ac, superioară electrorezecției pentru controlul oncologic','Prostatectomia radicală deschisă, ca tratament de primă intenție al HBP','Crioterapia prostatică, cu rezultate superioare TURP pentru adenom'],'B',638,'HBP — Laser GreenLight versus TUMT/TUNA',
 'Recunoașterea vaporizării GreenLight ca alternativă actuală la TURP, TUMT și TUNA nemaifiind folosite pe scară largă.',
 ['Termoterapia cu microunde și ablația cu ac nu mai sunt folosite pe scară largă, din cauza ameliorării modeste.','Textul numește laserul GreenLight procedura cel mai frecvent utilizată în afară de TURP, cu hemoragie mai redusă.','Ablația cu ac nu este superioară electrorezecției și nu are viză oncologică în HBP.','Prostatectomia radicală vizează cancerul, nu enuclearea HBP.','Crioterapia este discutată la cancerul localizat, cu rezultate inferioare metodelor curative.']],
 8,'Repune TUMT/TUNA — abandonate pentru ameliorare modestă — ca standard și confundă GreenLight-ul HBP cu crioterapia oncologică.',['GreenLight','Termoterapia transuretrală']),

q(96,['Care dintre următoarele afirmații privind IRM-ul prostatic, formele PSA și metastazele osoase sunt adevărate?',
 ['PSA-ul seric se regăsește sub două forme dominante, una conjugată cu α1-antichimotripsina și una liberă','Pentru standardizarea interpretării IRM s-a adoptat scorul PI-RADS în majoritatea centrelor','Metastazele osoase sunt tipic osteoblastice, pe scheletul axial; cele de părți moi fără leziuni osoase concomitente sunt rare','TRUS este principalul instrument de stadializare locală, tușeul rectal fiind superfluu','Un PSA de 3,9 ng/mL este considerat scăzut pentru un bărbat în decada a 6-a'],'ABC',639,'Carcinom prostatic — PI-RADS, antichimotripsină și osteoblaste',
 'Potrivirea dublei forme a PSA, a scorului PI-RADS și a pattern-ului osteoblastic axial, față de valoarea 3,9 „scăzută” în decada a 6-a.',
 ['Cele două forme (conjugată cu α1-antichimotripsina și liberă) sunt explicite.','Adoptarea PI-RADS pentru IRM-ul pre-biopsie este enunțată.','Tiparul osteoblastic axial și rarisimitatea metastazelor de părți moi izolate sunt citate.','Modalitatea principală de stadializare locală este tușeul; TRUS are valoare limitată în stadializare.','Un PSA de 3,9 ng/mL este considerat mărit pentru un bărbat în decada a 6-a.']],
 8,'Inversează pragul de vârstă al PSA-ului 3,9 ng/mL și pune TRUS-ul deasupra tușeului în stadializarea locală.',['Pl-RADS','antichimotripsina']),

q(97,['În prostatectomia radicală retropubică și limfodisecția pelvină se recomandă:',
 ['Limitele limfodisecției: bifurcația arterei iliace comune (proximal), vena iliacă circumflexă (distal), porțiunea mijlocie a arterei iliace externe (lateral) și peretele vezical (medial)','Piesa include prostata în întregime, capsula, veziculele seminale și porțiunea ampulară a ductelor deferente','După îndepărtare se realizează anastomoza dintre uretră și colul vezical','Prezervarea bandeletelor neuro-vasculare postero-laterale poate menține potența în aproximativ două treimi din cazuri','Marjele negative asociază o rată de supraviețuire fără boală la 15 ani de sub 10%'],'ABCD',640,'Prostatectomie radicală — Limite limfatice, ampula și NVB',
 'Memorarea reperelor de limfodisecție, a piesei (vezicule, ampula deferentelor) și a anastomozei uretro-vezicale, cu potența în 2/3.',
 ['Cele patru limite anatomice ale limfodisecției sunt enumerate explicit.','Conținutul piesei, inclusiv ampula deferentelor, este descris.','Anastomoza uretră–col vezical este pasul reconstructiv citat.','Păstrarea potenței în aproximativ două treimi, prin bandeletele postero-laterale, este enunțată.','Rata de supraviețuire fără boală la 15 ani, la marje negative, este de aproximativ 50%.']],
 8,'Înlocuiește supraviețuirea fără boală de 50% la 15 ani cu un prag sub 10%, păstrând corect restul piesei radicale.',['bandeletelor neuro-vasculare','15 ani']),

q(98,['Următoarele afirmații despre prostatectomia minim invazivă și boala rezistentă la castrare sunt adevărate:',
 ['În prezent, aproximativ 90% dintre prostatectomii se realizează laparoscopic sau robotic','Abordurile minim invazive asociază aspect estetic superior, risc transfuzional mai mic, recuperare mai scurtă și continență mai rapidă','Terapiile de linia a doua (abirateronă, enzalutamidă, apalutamidă) și chimioterapia cu taxani au eficacitate moderată în boala rezistentă la castrare','Supraviețuirea medie, în era PSA, la cancerul refractar hormonal este sub 6 luni','Rezultatele oncologice pe termen scurt ale tehnicilor minim invazive sunt inferioare abordului deschis'],'ABC',641,'Prostatectomie robotică 90% și linia a doua (abirateronă)',
 'Fixarea cotei de 90% minim invaziv, a celor patru avantaje perioperatorii și a tripletului abirateronă–enzalutamidă–apalutamidă plus taxani.',
 ['Cota de aproximativ 90% laparoscopic/robotic este explicită.','Cele patru avantaje față de abordul deschis sunt listate.','Abiraterona, enzalutamida, apalutamida și taxanii sunt numite terapii de linia a doua.','Supraviețuirea medie citată este de aproximativ 53 de luni.','Rezultatele oncologice pe termen scurt sunt echivalente intervenției deschise.']],
 8,'Reduce supraviețuirea din era PSA de la 53 de luni sub 6 luni și declară mini-invazivul oncologic inferior.',['90%','abirateronă']),

q(99,['Un pacient dezvoltă hiponatremie după TURP, iar altul acidoză după derivație urinară cu intestin. Sunt adevărate:',
 ['Hiponatremia prin absorbția lichidului de irigație definește sindromul post-TURP','Derivațiile care utilizează segmente intestinale pot produce acidoză metabolică hipercloremică','Vasul aberant polar superior, nu cel inferior, se asociază stenozei congenitale de joncțiune pielo-ureterală','Capsula fibroasă renală nu poate fi disecată de pe parenchim','Doar 5% din debitul cardiac este direcționat către rinichi'],'AB',642,'Fiziologie renală — Sindrom post-TURP și acidoza intestinală',
 'Legarea hiponatremiei de irigația TURP și a acidozei hipercloremice de conduitele intestinale, distincte de vasul polar inferior.',
 ['Sindromul post-TURP prin absorbția lichidului de irigație este exemplul citat de hiponatremie.','Acidoza metabolică hipercloremică după derivații cu intestin este enunțată.','Vasul aberant polar inferior, nu cel superior, se asociază stenozei de joncțiune.','Capsula fibroasă poate fi ușor disecată de pe suprafața parenchimului.','Aproximativ 20% din debitul cardiac este direcționat către rinichi.']],
 8,'Mută vasul polar inferior (stenoză de joncțiune) pe polul superior și reduce debitul renal de la 20% la 5%.',['sindrom post TURP','acidoza metabolică hipercloremică']),

q(100,['Corecția chirurgicală a rinichiului în potcoavă, când este necesară, presupune:',
 ['Incizia istmului care unește cei doi rinichi (simfiziotomie), uneori asociată refacerii joncțiunii pielo-ureterale','Nefrectomie bilaterală de principiu, istmul neputând fi abordat','Doar stent ureteral intern, fără simfiziotomie','Embolizarea arterei renale principale, analog traumatismului de grad V','Transplant renal ca gest inițial, înaintea oricărei simfiziotomii'],'A',643,'Rinichi în potcoavă — Simfiziotomia istmului',
 'Recunoașterea simfiziotomiei istmului, eventual cuplată cu plastia joncțiunii, ca gestul chirurgical al potcoavei simptomatice.',
 ['Textul numește incizia istmului (simfiziotomie) și posibila refacere a joncțiunii pielo-ureterale.','Nefrectomia bilaterală nu este reparația de elecție.','Stentul izolat nu înlocuiește simfiziotomia când operația este necesară.','Embolizarea ține de pattern-uri traumatice, nu de potcoavă.','Transplantul nu este gestul inițial al anomaliei de fuziune.']],
 8,'Înlocuiește simfiziotomia istmului cu nefrectomia, embolizarea de grad V sau transplantul.',['istmului','simfiziotornie']),

q(101,['Clasificarea traumatismelor renale din figura 29-11:',
 ['Gradul IV presupune lacerația corticalei și a medularei, afectând inclusiv sistemul colector; se pot asocia lacerații ale vaselor segmentare','Un pattern de grad IV este tromboza unei artere segmentare, cu ischemie teritorială, fără lacerație parenchimatoasă','Gradul V include tromboza ramului arterial principal, rinichiul fragmentat prin lacerații multiple și avulsia arterei sau venei principale','Gradul I asociază lacerație parenchimatoasă profundă cu extravazare în sistemul colector','Gradele I și II sunt considerate majore, iar III–V minore'],'ABC',644,'Traumatism renal — Pattern-urile de grad IV și V',
 'Separarea lacerației cortico-medulare de grad IV și a trombozei segmentare de triada de grad V (arteră principală, rinichi spart, avulsie).',
 ['Lacerația corticală și medulară cu sistem colector și vase segmentare definește un pattern de grad IV.','Tromboza arterei segmentare fără lacerație este celălalt pattern de grad IV din figură.','Cele trei pattern-uri de grad V (tromboză de ram principal, rinichi fragmentat, avulsie) sunt descrise.','Gradul I este contuzie sau hematom subcapsular, fără lacerație parenchimatoasă.','Gradele I–II sunt minore, iar III–V majore.']],
 8,'Umflă gradul I la lacerația cu extravazare și inversează scara minor/major din aceeași figură.',['sistemul colector renal','avulsia']),

q(102,['Alegeți afirmațiile corecte referitoare la PXG, chisturile complexe și etiologia CRCC:',
 ['Când urocultura este pozitivă în PXG, speciile E. coli și Proteus sunt cel mai frecvent incriminate','Nitrozaminele și substanțele cancerigene din fumul de țigară sunt implicate în apariția CRCC','Un chist renal complex (septuri, pereți îngroșați, calcificări) este considerat, de obicei, malign până la proba contrarie','Biopsia sau aspirația chistului exclude cu certitudine malignitatea, rezultatul negativ fiind definitiv','PXG afectează precumpănitor bărbații din decada a treia, rinichiul rămânând funcțional'],'ABC',645,'PXG — Proteus; CRCC — nitrozamine; chistul complex',
 'Potrivirea cuplului E. coli/Proteus din PXG, a nitrozaminelor din fumul de țigară și a chistului complex tratat ca malign.',
 ['E. coli și Proteus sunt speciile citate când urocultura obiectivează ITU în PXG.','Nitrozaminele și carcinogenii din fumul de țigară sunt implicate etiologic în CRCC.','Chistul complex este considerat malign până la proba contrarie, putând indica nefrectomie parțială sau radicală.','Biopsia sau aspirația au valoare diagnostică redusă, cu rezultate fals negative.','PXG afectează precumpănitor femeile (75%) în decadele 5–7, cu rinichi de obicei nefuncțional.']],
 8,'Declară aspirația chistului „certă” și inversează sexul/decadele PXG (femei 5–7 versus bărbați tineri).',['Proteus','nitrozaminele']),

q(103,['Bilanțul preoperator și prognosticul carcinomului renal cu celule clare:',
 ['Ratele de supraviețuire la 5 ani sunt de 80–90% în stadiile I–II și de 40–60% în stadiile III–IV','Bilanțul preoperator include radiografie toracică și evaluarea funcției hepatice','Scintigrafia osoasă este necesară în prezența durerilor osoase sau a fosfatazei alcaline crescute','Metastazele hepatice apar, de regulă, înaintea celor pulmonare','Complicațiile postoperatorii nu includ hemoragia, abcesul retroperitoneal sau ileusul paralitic'],'ABC',646,'CRCC — Supraviețuire I–II versus III–IV și scintigrafia',
 'Memorarea intervalelor 80–90% / 40–60% și a indicației de scintigrafie (durere osoasă sau fosfatază alcalină), față de ordinul plămân–os–creier.',
 ['Cifrele de supraviețuire la 5 ani pe stadii sunt explicite.','Radiografia toracică și testele hepatice fac parte din bilanț.','Scintigrafia osoasă este cerută la durere osoasă sau fosfatază alcalină crescută.','Metastazele urmează ordinul plămân, os, creier; ficatul poate fi tardiv.','Hemoragia, abcesul retroperitoneal, ileusul și embolia pulmonară sunt complicații citate.']],
 8,'Inversează ordinul metastatic (ficat înaintea plămânului) și neagă complicațiile enumerate în același paragraf chirurgical.',['80-90%','fosfatazei alcaline']),

q(104,['Un adult cu colică de flanc iradiată spre organele genitale, greață și microhematurie. Evaluarea corectă include:',
 ['Durerea este cauzată, de obicei, de obstrucție pe măsură ce calculul trece prin ureter, nu de calculul în sine','Calculul de acid uric este transparent pe radiografia renală simplă, dar alb strălucitor pe CT fără contrast','Evaluarea metabolică se face, de obicei, după eliminarea calculilor, când pacientul urmează o dietă obișnuită','Testele includ calciu seric, PTH, electroliți, pH urinar și colectarea urinei pe 24 de ore','Ecografia renală este superioară CT-ului în vizualizarea ureterelor și oferă date funcționale'],'ABCD',647,'Litiază — Colică, uric acid pe CT și bilanț metabolic',
 'Înlănțuirea mecanismului colicii, a contrastului radiologic al acidului uric și a ferestrei metabolice post-eliminare pe dietă obișnuită.',
 ['Textul atribuie durerea obstrucției ureterale, nu calculului în sine; iradierea genitală, greața și vărsăturile sunt descrise.','Acidul uric transparent pe radiografia simplă și alb strălucitor pe CT fără contrast este explicit.','Momentul post-eliminare, pe dieta obișnuită, este precizat.','Lista de laborator (calciu, PTH, electroliți, pH, urină 24 h) este enumerată.','Ecografia este lipsită de precizia anatomică a CT-ului, mai ales pe uretere, și nu oferă informații funcționale.']],
 8,'Declară ecografia superioară CT-ului pe uretere, exact limita pe care textul o subliniază.',['alb strălucitor','hormonului paratiroidian']),

q(105,['Anatomia ureterului intramural și diagnosticul obstrucției:',
 ['În prima jumătate a traiectului intramural, ureterul traversează musculara vezicală; în a doua jumătate se situează submucos','În porțiunile superioare, musculara are un model helicoidal neregulat; aproape de vezică fibrele sunt paralele cu lumenul','Atât CT, cât și UIV sunt investigații excelente pentru obstrucția ureterală, oferind informații anatomice și funcționale','Fibrele musculare din porțiunea intramurală sunt dispuse circular, concentric pe lumen','CT și UIV sunt investigații slabe pentru diagnosticul obstrucției ureterale'],'ABC',648,'Ureter — Jumătăți intramurale, helicoidal și CT/UIV',
 'Citirea împărțirii intramurale (musculară apoi submucoasă) și a modelului helicoidal proximal versus fibre paralele distale.',
 ['Traversarea muscularei în prima jumătate și poziția submucoasă în a doua sunt explicite.','Modelul helicoidal neregulat proximal și fibrele paralele cu lumenul lângă vezică sunt descrise.','CT și UIV sunt numite investigații excelente, anatomice și funcționale.','Lângă vezică și intramural, fibrele sunt paralele cu lumenul, nu circulare concentrice.','Textul afirmă opusul: CT și UIV sunt excelente pentru obstrucție.']],
 8,'Păstrează dispoziția „circular concentrică” respinsă de text și transformă CT/UIV din excelente în slabe.',['helicoidal','fibroza retroperitoneală']),

q(106,['Anatomia vezicii urinare:',
 ['Trigonul are două straturi musculare, unul superficial care fuzionează cu musculatura ureterală și unul profund, nedistinct de detrusor','La femei, condensările fasciei pelvine se numesc ligamente pubovezicale; ligamentul ombilical median (rămășița uracăi) fixează vezica de peretele abdominal anterior','Detrusorul corpului vezical este organizat în trei straturi circulare distincte pe toată circumferința','Vascularizația vezicală provine din artera spermatică internă, analog testiculului','Limfa vezicală drenează în ganglionii inghinali superficiali, nu în iliaci, hipogastrici, iliaci comuni și sacrali'],'AB',649,'Vezică — Trigonul bistratificat și ligamentele pubovezicale',
 'Diferențierea trigonului bistratificat de detrusorul fără straturi distincte și a ligamentelor pubovezicale de cele puboprostatice.',
 ['Cele două straturi ale trigonului, cu fuziunea superficială ureterală, sunt explicite.','Denumirea feminină pubovezicală și ligamentul ombilical median ca rămășiță a uracăi sunt descrise.','Detrusorul corpului este din fascicule intercalate, fără delimitarea unor straturi distincte.','Arterele vezicale superioare, medii și inferioare sunt ramuri ale arterei hipogastrice.','Drenajul limfatic citat este spre iliaci externi, hipogastrici, iliaci comuni și sacrali.']],
 8,'Inventă trei straturi circulare ale detrusorului și mută limfa vezicală pe ganglionii inghinali ai uretrei anterioare.',['ligamentele pubovezicale','ligamentul ombilical median']),

q(107,['Refluxul vezico-ureteral secundar și supravegherea copilului:',
 ['Refluxul secundar poate urma rezecției tumorilor de lângă orificiu, inciziei endoscopice pentru calculi, transplantului renal sau dilatării orificiului pentru ureteroscopie','Cistografia cu radionuclid necesită o doză mai mică de iradiere și detectează grade mici, dar detaliile anatomice sunt inferioare CUGM','Scintigrafia renală are sensibilitate superioară ecografiei pentru cicatricile parenchimatoase nou apărute','Creatinina serică, ureea, înălțimea, greutatea și tensiunea arterială ar trebui verificate anual','Cistoscopia este indicată de rutină la copiii cu reflux, înlocuind CUGM'],'ABCD',650,'RVU — Secundar, cistografie cu radionuclid și cicatrici',
 'Recunoașterea cauzelor iatrogene de reflux secundar, a cistografiei izotopice (iradiere mică, anatomie inferioară) și a DMSA pentru cicatrici.',
 ['Cele patru contexte de reflux secundar sunt enumerate.','Avantajul dozei și limita anatomică a cistografiei cu radionuclid sunt explicite.','Superioritatea scintigrafiei față de ecografie pentru cicatrici noi este citată.','Verificarea anuală a creatininei, ureei, taliei, greutății și TA este cerută.','Cistoscopia nu este indicată de rutină la copiii cu reflux.']],
 8,'Pune cistoscopia de rutină în locul CUGM și al cistografiei izotopice, inversând ierarhia diagnostică a paginii.',['cistografie cu radionuclid','scintigrafia renală']),

q(108,['Precizați enunțul corect privind tehnica Glenn-Anderson de reimplantare ureterală:',
 ['Se folosește când orificiul este suficient de înalt și lateral pentru un tunel submucos lung, fără a apropia noul meat de colul vezical','Este avansarea încrucișată trigonală, rezervată spațiului insuficient dintre hiatus și col','Creează un hiatus nou supero-lateral, fiind tehnica de reintervenție Politano-Leadbetter','Constă în injectarea de Deflux sub orificiu, procedura durând peste două ore fără anestezie','Urmărește scurtarea tunelului intramural sub diametrul ureterului, pentru a reduce rezistența'],'A',651,'Reimplantare — Glenn-Anderson (orificiu înalt lateral)',
 'Separarea avansării Glenn-Anderson (orificiu înalt/lateral, tunel lung) de Cohen (încrucișare trigonală) și de Politano-Leadbetter (hiatus nou).',
 ['Textul rezervă Glenn-Anderson orificiului suficient de înalt și lateral, cu tunel submucos lung, fără meat prea aproape de col.','Avansarea încrucișată trigonală definește procedura Cohen.','Hiatusul nou supero-lateral este al tehnicii Politano-Leadbetter.','Deflux-ul este o injecție endoscopică de sub 30 de minute, sub anestezie generală.','Obiectivul reimplantării este un tunel de 4–5 ori diametrul ureterului, nu scurtarea lui.']],
 8,'Permutează cele trei eponime de reimplantare (Glenn-Anderson, Cohen, Politano-Leadbetter) din paragrafe consecutive.',['tunel submucos','Gle1m-Anderson']),

q(109,['Un adult cu ruptură vezicală confirmată cistografic și, separat, un bărbat cu cistită acută. Enunțurile corecte sunt:',
 ['Filmul radiologic după îndepărtarea drenajului ajută la diagnosticarea a aproximativ 15% dintre rupturile vezicale','Rupturile intraperitoneale sau cele extraperitoneale mari/complicate se explorează prin incizie mediană, evitând hematomul pelvin, cu sutură cu fire resorbabile','Manipularea tractului urinar trebuie temporizată până la vindecarea infecției acute, pentru a preveni bacteriemia','Rupturile intraperitoneale se tratează doar cu sondă Foley 1–2 săptămâni, fără sutură','Carcinomul nu trebuie considerat când simptomele iritative persistă după sterilizarea urinei'],'ABC',654,'Ruptură vezicală — Filmul post-drenaj 15% și fire resorbabile',
 'Adăugarea filmului după golire (15%) și a suturii resorbabile pe linia mediană, plus temporizarea instrumentării în cistita acută.',
 ['Contribuția de aproximativ 15% a filmului după îndepărtarea drenajului este explicită.','Incizia mediană, evitarea hematomului pelvin și firele resorbabile sunt descrise pentru rupturile care cer chirurgie.','Temporizarea manipulării până la vindecarea infecției, pentru a preveni bacteriemia, este cerută.','Foley 1–2 săptămâni este rezervat rupturilor mici extraperitoneale, nu celor intraperitoneale.','Carcinomul trebuie luat în considerare dacă simptomele iritative persistă după sterilizarea urinei.']],
 8,'Aplică protocolul Foley al rupturii mici extraperitoneale pe ruptura intraperitoneală, care cere sutură.',['15%','fire resorbabile']),

q(110,['Cistita interstițială și fistula entero-vezicală se caracterizează prin:',
 ['Examenul histologic evidențiază inflamație cronică; biopsia arată frecvent fibroză și infiltrație mastocitară','Cistoscopia poate evidenția ulcerații Hunner sau glomerulații după hidrodistensia vezicală','CT-ul fără cateterizarea vezicii poate confirma fistula: aerul vezical susține diagnosticul','Uroculturile pentru bacterii, virusuri și fungi sunt, în mod tipic, pozitive','Fistula entero-vezicală se tratează doar cu antibiotice, fără rezecția ansei afectate'],'ABC',655,'Cistită interstițială — Mastocite, Hunner; aer vezical pe CT',
 'Potrivirea infiltratului mastocitar și a ulcerațiilor Hunner după hidrodistensie cu semnul aerului vezical pe CT necaterizat.',
 ['Inflamația cronică, fibroza și infiltrația mastocitară sunt explicite.','Ulcerațiile Hunner și glomerulațiile după hidrodistensie sunt descrise.','CT-ul fără cateter, cu aer vezical, confirmă diagnosticul de fistulă.','Uroculturile sunt, în mod tipic, negative.','Tratamentul include rezecția porțiunii de intestin afectat.']],
 8,'Declară uroculturile interstițiale pozitive și tratează fistula entero-vezicală doar medicamentos.',['Hunner','infiltraţie mastocitară']),

q(111,['Mecanismul principal al micțiunii normale este:',
 ['Relaxarea sfincterului extern, urmată de relaxarea și deschiderea colului vezical și de contracția detrusorului','Contracția detrusorului, sfincterul rămânând contractat până la golirea completă','Creșterea tonusului sfincterian concomitent cu contracția detrusorului','Relaxarea detrusorului și contracția sfincterului extern, analog umplerii','Doar presă abdominală, fără coordonare sfincter–detrusor'],'A',656,'Micțiune normală — Relaxarea sfincterului înaintea detrusorului',
 'Fixarea secvenței: sfincter extern → col vezical → detrusor, distinctă de contracția detrusorului cu sfincterul încă închis.',
 ['Textul descrie micțiunea voluntară ca începând cu relaxarea sfincterului extern, apoi colul, apoi detrusorul.','Contracția detrusorului cu sfincterul contractat inversează coordonarea descrisă.','Pe parcursul umplerii tonusul sfincterian este crescut; la micțiune el scade.','Relaxarea detrusorului ține de umplere (complianță), nu de golire.','Presa abdominală poate susține golirea în vezica autonomă, nu definește micțiunea normală.']],
 8,'Pornește micțiunea cu detrusorul contractat și sfincterul închis, inversul secvenței din ultimul paragraf.',['relaxarea sfincterului extern','complianţă']),

q(112,['Pareza vezicală de tip motor se recunoaște prin:',
 ['Absența activității detrusoriene, cu senzație micțională prezentă și capacitate normală sau crescută','Cauze posibile: poliomielită, traumatisme, mielomeningocel sau alte anomalii congenitale','Scăderea sau lipsa senzației, fără hiperreflexie, cu capacitate vezicală mare, ca în tabesul dorsal','Contracții neinhibate cu sfincter striat dissinergic, ca în leziunea medulară deasupra S2','Necesitatea de a urina la 150–250 mL, identică primei senzații a vezicii normale'],'AB',658,'Vezică neurogenă — Pareza motorie (poliomielită)',
 'Separarea parezei motorii (fără contracție, senzație păstrată) de vezica senzorială (fără senzație, capacitate mare) și de dissinergia suprasacrată.',
 ['Absența activității detrusoriene cu senzație prezentă și capacitate normală/crescută definește tipul motor.','Poliomielita, traumatismele, mielomeningocelul și anomaliile congenitale sunt enumerate.','Absența senzației fără hiperreflexie este vezica senzorială (tabes, diabet).','Dissinergia striată este a leziunii deasupra S2.','150–250 mL este prima senzație a vezicii normale, nu tabloul parezei motorii.']],
 8,'Schimbă pareza motorie (senzație păstrată) cu vezica senzorială sau cu dissinergia medulară din același tabel.',['poliomielită','mielomeningocel']),

q(113,['Carcinomul vezical — epidemiologie, histologie a domului și cistectomie la femeie:',
 ['Este al cincilea cel mai frecvent cancer în America și de 2,5 ori mai frecvent la bărbați','Este asociat și cu carcinogeni din industria materialelor plastice și a prelucrării petrolului','Adenocarcinoamele se asociază frecvent cu uracă patentă și tumori ale domului vezical','La femeie, cistectomia radicală îndepărtează vezica, peretele anterior vaginal, uterul și ganglionii limfatici','Stadiul T2 înseamnă carcinom in situ, fără invazia mușchiului detrusor'],'ABCD',659,'Carcinom vezical — Plastice/petrol, uracă și piesa feminină',
 'Adăugarea rangului al cincilea, a carcinogenilor industriali, a adenocarcinomului de uracă/dom și a piesei de cistectomie feminină.',
 ['Rangul al cincilea și raportul 2,5:1 masculin sunt explicite.','Industria materialelor plastice și a petrolului este citată alături de fumat.','Asocierea adenocarcinom–uracă patentă–dom vezical este enunțată.','Conținutul cistectomiei radicale la femeie este enumerat.','T2 este invazia detrusorului; Tis este carcinomul in situ.']],
 8,'Etichetează T2 ca in situ, confundând linia de stadializare cu piesa de cistectomie feminină.',['al cincilea','mate1ialelor plastice']),

q(114,['Vascularizația și drenajul limfatic ale penisului:',
 ['Arterele provin din ramuri ale arterei rușinoase interne, ramură a iliacei interne','Drenajul limfatic al glandului, corpului spongios și porțiunii distale a cavernoșilor se face către ganglionii iliaci externi, superficiali și inghinali profunzi','Porțiunea proximală a cavernoșilor și uretra posterioară drenează către ganglionii iliaci interni','Limfa glandului drenează direct în ganglionii preaortici, analog testiculului','Venele dorsale conduc sângele către vena spermatică internă, nu către iliace'],'ABC',659,'Penis — Artera rușinoasă internă și etajele limfatice',
 'Potrivirea pediculului din rușinoasa internă cu etajul distal (iliaci externi/inghinali) versus proximal (iliaci interni).',
 ['Originea din artera rușinoasă internă, ramură a iliacei interne, este explicită.','Tinta limfatică distală (iliaci externi, superficiali și inghinali profunzi) este descrisă.','Etajul proximal (cavernoși proximali și uretra posterioară) drenează în iliaci interni.','Ganglionii preaortici țin de drenajul testicular, nu de gland.','Venele dorsale superficiale și profunde conduc fluxul către venele iliace.']],
 8,'Mută limfa glandului pe preaorticii testiculului și venele dorsale pe spermatica internă.',['ruşinoase interne','iliaci interni']),

q(115,['Rata de vindecare la 5 ani după penectomia parțială pentru carcinomul scuamos penian este:',
 ['70–80%; leziunile distale mai mari sau cele proximale cer penectomie totală și uretrostomie perineală','Sub 10%, analog progresiei musculo-invazive a tumorilor vezicale Ta','15–20%, identică prevalenței varicocelului','Aproximativ 50%, analog marjelor negative la 15 ani după prostatectomie','Peste 95%, analog ponderii adenocarcinoamelor acinare prostatice'],'A',662,'Carcinom penian — Vindecare 70–80% după penectomie parțială',
 'Memorarea intervalului 70–80% la 5 ani după penectomie parțială și a saltului la penectomie totală plus uretrostomie perineală.',
 ['Textul citează 70–80% vindecare la 5 ani după penectomie parțială și trece leziunile mai mari/proximale pe penectomie totală cu uretrostomie perineală.','Sub 10% este pragul de progresie al Ta vezical, nu al penectomiei.','15–20% este prevalența varicocelului.','50% la 15 ani ține de prostatectomia cu marje negative.','Peste 95% este ponderea adenocarcinoamelor prostatice, nu rata de vindecare peniană.']],
 8,'Înlocuiește 70–80% după penectomie parțială cu praguri din prostată, vezică sau varicocel.',['70-80%','metrostomie perineală']),

q(116,['Un bărbat cu anemie falciformă prezintă erecție prelungită. Enunțurile corecte sunt:',
 ['Tratamentul vizează cauza subiacentă: hidratare, alcalinizare, analgezice și transfuzii','După injecție intracorporeală de vasoactive, dacă durata este sub 6 ore, se poate răspunde la fenilefrină intracorporeală','Fimoza este contractura fibrotică a prepuțului care nu permite retracția peste gland; diabetul este factor predispozant','Priapismul cu flux crescut are PO2 cavernos scăzută, identică ischemiei','Fimoza se tratează doar topic, circumcizia electivă fiind contraindicată'],'ABC',662,'Priapism falciform — Alcalinizare; fimoza diabetică',
 'Ierarhizarea protocolului din falciformă (hidratare, alcalinizare, transfuzie) și a ferestrei <6 ore pentru fenilefrină, plus fimoza diabetică.',
 ['Hidratarea, alcalinizarea, analgezicele și transfuziile sunt protocolul citat în anemia falciformă.','Fereastra <6 ore pentru fenilefrină după injecție vasoactivă este explicită.','Definiția fimozei și diabetul ca factor predispozant sunt enunțate.','În fluxul înalt PO2 este crescută, nu scăzută.','Fimoza se tratează prin igienă și, de multe ori, prin circumcizie electivă.']],
 8,'Inversează gazele cavernosului (PO2 scăzută în flux înalt) și interzice circumcizia electivă a fimozei.',['falciformă','alcalinizare'],[663]),

q(117,['Circumcizia la nou-născut și la adult:',
 ['La nou-născuți se pot folosi cleme Gomco sau Plastibell, fără anestezie','La adulți, un bloc penian permite circumcizia ca procedură ambulatorie','Se recomandă cauterul împreună cu clema Gomco, pentru hemostaza glandului','Incizia dorsală se oprește la 5 cm de șanțul coronal','Artera frenului nu sângerează și nu necesită ligatură'],'AB',664,'Circumcizie — Gomco/Plastibell și blocul penian',
 'Recunoașterea clemelor neonatale fără anestezie și a blocului penian ambulator la adult, față de cauterul interzis pe Gomco.',
 ['Gomco sau Plastibell, fără anestezie, sunt descrise la nou-născut.','Blocul penian și caracterul ambulator la adult sunt explicite.','Cauterul cu Gomco sau pense metalice similare riscă lezarea glandului.','Incizia dorsală ajunge până la aproximativ 1 cm de șanțul coronal.','Sângerarea arterei frenului necesită uneori ligatură.']],
 8,'Asociază cauterul cu Gomco — exact combinația pe care textul o interzice din cauza leziunii de gland.',['Gomco sau Plastibell','bloc penian']),

q(118,['Glandele uretrale și traumatismul uretrei posterioare:',
 ['Glandele Littre, producătoare de fluid pre-ejaculator, sunt localizate în uretra peniană','Glandele periuretrale Skene se deschid în uretra distală feminină','Leziunile uretrei prostatomembranoase apar la circa 10% dintre pacienții cu fracturi pelvine','Meatul feminin se deschide la 8 cm posterior de clitoris','Uretra distală feminină drenează limfa în ganglionii preaortici'],'ABC',664,'Uretră — Littre, Skene și 10% din fracturile pelvine',
 'Potrivirea glandelor Littre (peniană) și Skene (distal feminin) cu ponderea de 10% a leziunilor prostatomembranoase din fractura de bazin.',
 ['Sediul glandelor Littre în uretra peniană este explicit.','Deschiderea glandelor Skene în uretra distală feminină este descrisă.','Cifra de aproximativ 10% dintre fracturile pelvine este citată.','Meatul feminin se deschide la 2 cm posterior de clitoris.','Porțiunea distală feminină drenează în ganglionii inghinali, nu preaortici.']],
 8,'Mută meatul feminin de la 2 cm la 8 cm și limfa distală pe preaorticii testiculului.',['Glandele Littre','Skene']),

q(119,['Vascularizația și drenajul limfatic ale testiculului:',
 ['Artera spermatică internă are originea în aortă, sub emergența arterelor renale','Vena spermatică internă stângă drenează în vena renală stângă, iar dreapta în vena cavă inferioară','Limfa testiculară drenează în ganglionii preaortici și precavi, esențial pentru înțelegerea diseminării cancerului','Vena spermatică stângă drenează direct în vena cavă inferioară, analog dreptei','Artera deferențială provine din artera renală, nu din vezicala inferioară'],'ABC',669,'Testicul — Pedicul aortic, vena renală stângă și preaortici',
 'Fixarea originii sub-renale a arterei spermatice, a asimetrei venoase (stânga–renală, dreapta–VCI) și a țintei preaortice/precave.',
 ['Originea aortică sub arterele renale este explicită.','Asimetria venoasă stânga–vena renală versus dreapta–VCI este descrisă.','Drenajul preaortic și precav este numit esențial pentru diseminarea cancerului testicular.','Stânga drenează în vena renală stângă, nu direct în VCI.','Artera deferențială este ramură din artera vezicală inferioară.']],
 8,'Simetrizează venele spermatice ambele spre VCI și mută artera deferențială pe pediculul renal.',['vena renală stângă','preaortici']),

q(120,['Cateterismul vezical la adult:',
 ['La bărbat se folosește, de obicei, un cateter 16 French; se injectează 10 mL lubrifiant în uretră; se avansează până la bifurcația Foley; balonul se umflă cu 7–10 mL apă sterilă','La femeie, cateterul se avansează doar jumătate din lungime înainte de umflarea balonului','Avansarea la bărbat se oprește la prima apariție a urinei, fără a ajunge la bifurcație','Balonul se umflă cu 60 mL ser, analog irigației prin seringa Toomey','O mână nu trebuie să țină penisul, ambele fiind libere pentru câmpul steril'],'AB',673,'Cateterism — 16 French, 10 mL lubrifiant și balon 7–10 mL',
 'Aplicarea protocolului masculin (16 Fr, 10 mL lubrifiant, avansare până la bifurcație, balon 7–10 mL) și a avansării pe jumătate la femeie.',
 ['Calibrul 16 French, cei 10 mL de lubrifiant uretral, avansarea până la bifurcație și balonul de 7–10 mL sunt explicite.','La femeie avansarea pe jumătate din lungime înainte de umflarea balonului este precizată.','Textul cere să nu se oprească la prima vedere a urinei, ci să se ajungă la bifurcația sondei.','60 mL prin seringa Toomey este irigația de verificare, nu volumul balonului.','O mână ține permanent penisul odată ce procedura a început.']],
 8,'Oprește cateterul la prima picătură de urină și umflă balonul cu 60 mL, două erori din același algoritm practic.',['16 French','7-10 mL']),
];
