import {advancedQuestion} from './advanced-author';
import type {SourceRow} from './source-author';

const EDITION='Chirurgie generală și specialități chirurgicale, ediția pentru rezidențiat MG 2025';
const pdfOffset=(p:number)=>p-329;
const q=(n:number,row:SourceRow,score:number,reason:string,expressions:string[],related:number[]=[])=>
 advancedQuestion('urologie',29,pdfOffset,`urologie-adv-${String(n).padStart(3,'0')}`,row,[score,reason],expressions,undefined,related,'Lawrence',EDITION);

export const UROLOGIE_C=[
q(63,['Identificați afirmația corectă referitoare la vascularizația și ancorarea prostatei:',
 ['Vascularizația provine, în primul rând, din ramuri ale arterei hipogastrice care pătrund postero-lateral','Artera spermatică internă, cu origine sub arterele renale, este pediculul principal al prostatei','Ligamentele puboprostatice ancorează glanda posterior, de rect, nu de pube','Complexul venos dorsal de pe fața anterioară drenează splina, nu circulația peniană','Uretra membranoasă, cu sfincterul extern, este proximală de uretra prostatică'],'A',635,'Prostata — Vascularizație și ligamente',
 'Recunoașterea pediculului hipogastric postero-lateral și a ligamentelor puboprostatice, distincte de arterele testiculare.',
 ['Textul precizează că vascularizația provine în primul rând din ramuri ale arterei hipogastrice care intră postero-lateral.','Artera spermatică internă vascularizează testiculul, nu prostata.','Ligamentele puboprostatice ancorează glanda anterior la osul pubian.','Complexul venos dorsal de pe fața anterioară drenează circulația de la nivelul penisului.','Uretra membranoasă, împrejmuită de sfincterul extern, este distală de uretra prostatică.']],
 8,'Permutează pediculul hipogastric prostatic cu artera spermatică testiculară și inversează raportul uretră membranoasă–prostatică.',['arterei hipogastrice','Ligamentele puboprostatice']),

q(64,['Care dintre următoarele afirmații privind tușeul rectal și antigenul specific prostatic sunt adevărate?',
 ['Prostata normală este netedă, simetrică, cu consistența musculaturii eminenței tenare','80% dintre cancere se dezvoltă în zona periferică și, la dimensiune suficientă, sunt palpabile ca indurație sau noduli','PSA-ul este o serin-protează care clivează proteinele din sperma postejaculatorie','Veziculele seminale se palpează constant la un tușeu normal','Screening-ul PSA la pacienții cu risc crescut se amână, de principiu, după 70 de ani'],'ABC',638,'Carcinom prostatic — Tușeu și PSA ca serin-protează',
 'Potrivirea consistenței tenare, a palpabilității periferice de 80% și a funcției de serin-protează, față de veziculele nepalpabile.',
 ['Textul compară consistența prostatei normale cu musculatura eminenței tenare.','Ponderea de 80% în zona periferică și palparea ca indurație sau noduli sunt explicite.','Funcția de serin-protează asupra proteinelor postejaculatorii este enunțată.','În mod normal, veziculele seminale nu se pot palpa.','Pentru afroamericani și istoric familial, screening-ul poate fi considerat de la 40 de ani.']],
 8,'Transformă veziculele nepalpabile în semn „normal” și mută screening-ul de risc înalt de la 40 de ani la decadele tardive.',['eminenţei tenare','serin-protează']),

q(65,['Pragul de PSA sub care metastazele osoase sunt relativ rar întâlnite este:',
 ['<20 ng/mL','<4,0 ng/mL, prag sub care metastazele osoase sunt absente','0,5 ng/mL, valoarea care dovedește eradicarea după prostatectomie','100 ng/mL, singurul prag care justifică scintigrafia','1,0 ng/mL, identic țintei de după radioterapie'],'A',639,'Carcinom prostatic — Metastaze osoase și PSA',
 'Memorarea pragului PSA <20 ng/mL, sub care metastazele osoase sunt relativ rare, scintigrafia rămânând metoda cea mai sensibilă.',
 ['Textul precizează că metastazele osoase sunt relativ rar întâlnite la pacienții cu PSA <20 ng/mL.','Un PSA <4 ng/mL este convențional „normal”, dar 20–25% dintre cancere se află în acest interval; nu exclude metastazele prin sine.','0,5 ng/mL este o țintă discutată după radioterapie, nu pragul metastazelor osoase.','Scintigrafia osoasă este cea mai sensibilă metodă de detecție, fără a aștepta 100 ng/mL.','<1,0 ng/mL este ținta post-radioterapie, nu pragul metastazelor.']],
 8,'Amestecă pragul <20 ng/mL al metastazelor cu 4 ng/mL (screening) și cu 0,5–1,0 ng/mL (răspuns terapeutic).',['20 ng/mL','Scintigrafia osoasă']),

q(66,['După tratamentul cu viză curativă al cancerului de prostată și în stadiul metastatic:',
 ['Valorile PSA trebuie să scadă post-prostatectomie până la nedetectabile, celulele producătoare fiind îndepărtate odată cu piesa','După radioterapie, rezultate superioare se obțin când PSA scade sub 1,0 ng/mL sau chiar sub 0,5 ng/mL','Durata răspunsului hormonal în boala metastatică este, de regulă, 18–24 de luni, înainte de progresie','Peste jumătate din androgenii circulanți provin din glandele suprarenale','Analogii de LHRH nu produc manifestări vasomotorii'],'ABC',641,'Cancer de prostată — PSA post-tratament și hormonoterapie',
 'Fixarea PSA-ului nedetectabil post-prostatectomie, a țintei <1,0/0,5 ng/mL post-RT și a ferestrei hormonale 18–24 de luni.',
 ['Textul cere scăderea PSA-ului postoperator până la valori nedetectabile.','Pragurile <1,0 ng/mL și chiar <0,5 ng/mL după radioterapie sunt explicite.','Răspunsul hormonal durează, de regulă, 18–24 de luni.','Mai puțin de 10% din androgenii circulanți sunt produși de suprarenale.','Analogii de LHRH produc bufeuri în aproximativ două treimi din cazuri.']],
 8,'Umflă cota androgenilor suprarenali peste 50% și neagă bufeurile LHRH, două erori din același paragraf hormonal.',['nedetectabile','18-24 de luni']),

q(67,['Fascia Gerota și vascularizația renală:',
 ['Superior, foițele se unesc acoperind complet suprarenala; inferior rămân separate și se continuă de-a lungul ureterului','Aproximativ 20% din debitul cardiac este direcționat către rinichi; pediculul vascular este anterior de pelvisul renal','Circa 65% dintre rinichi prezintă cel puțin un vas aberant; ramurile arteriale sunt vase terminale','Pediculul vascular pătrunde posterior de pelvisul renal','Foițele mediale nu fuzionează, deci extravazarea de urină sau sânge nu este limitată'],'ABC',642,'Rinichiul — Fascia Gerota și vase aberante',
 'Potrivirea foițelor Gerota (unire superioară, separare inferioară), a celor 20% din debitul cardiac și a vaselor terminale aberante.',
 ['Dispoziția foițelor superioare și inferioare este descrisă explicit, inclusiv acoperirea suprarenalei.','Fracția de 20% din debitul cardiac și poziția anterioară a pediculului față de pelvis sunt enunțate.','Ponderea de circa 65% a vaselor aberante și caracterul terminal, cu infarct și hipertensiune ulterioară, sunt citate.','Pediculul pătrunde prin hil anterior de pelvisul renal, nu posterior.','Medial, foițele fuzionează și aderă la vase și pelvis, limitând extravazarea.']],
 8,'Inversează pediculul față de pelvis și neagă fuziunea medială care limitează extravazarea, două detalii din același paragraf.',['fascia renală Gerata','20% din debitul cardiac']),

q(68,['Diagnosticul stenozei de joncțiune pielo-ureterală se stabilește prin:',
 ['Doar tușeu rectal, analog evaluării HBP','Scintigrafie renală (renografie Lasix)','PSA seric, ca în carcinomul prostatic','Cistoscopie de rutină, considerată suficientă fără scintigrafie','Arteriografie ca investigație de primă intenție, în locul renografiei Lasix'],'B',643,'Stenoza de joncțiune pielo-ureterală — Renografie Lasix',
 'Recunoașterea renografiei Lasix ca test de diagnostic, distinct de screening-ul antenatal ecografic.',
 ['Tușeul rectal nu diagnostichează stenoza de joncțiune.','Textul numește scintigrafia renală (renografia Lasix) investigația de diagnostic.','PSA-ul nu are rol în obstrucția de joncțiune.','Cistoscopia nu înlocuiește renografia.','Diagnosticul antenatal este ecografic; arteriografia nu este testul citat.']],
 8,'Înlocuiește renografia Lasix cu tușeul, PSA-ul sau arteriografia, trei investigații din alte secțiuni ale capitolului.',['renografie Lasix','scintigrafie renală']),

q(69,['Un pacient diabetic febril, cu colecție renală pe CT. Enunțurile corecte sunt:',
 ['Traumatismul de grad III presupune lacerație corticală >1 cm, fără extravazare urinară','Abcesul renal se tratează, de obicei, prin antibioterapie asociată drenajului percutanat','Gradul I asociază lacerație parenchimatoasă profundă cu extravazare în sistemul colector','Extracția calculului este manevra inițială în pielonefrita obstructivă septică','Gradul II se definește prin avulsia pediculului vascular'],'AB',644,'Traumatism renal grad III și abcesul renal',
 'Separarea lacerației de grad III (>1 cm, fără extravazare) de drenajul percutanat al abcesului, față de extracția septică interzisă.',
 ['Figura 29-11 descrie gradul III ca lacerație corticală >1 cm, fără extravazare urinară.','Textul asociază antibioterapia cu drenajul percutanat al abcesului renal.','Gradul I este contuzie sau hematom subcapsular, fără lacerație parenchimatoasă.','Extragerea calculului este contraindicată ca tratament inițial al pielonefritei obstructive.','Avulsia pediculului definește un pattern de grad V.']],
 8,'Umflă gradul III la avulsia de pedicul (grad V) și promovează extracția calculului în faza septică.',['drenajul percutanat','laceraţia corticalei'],[645]),

q(70,['Carcinomul renal cu celule clare se caracterizează prin:',
 ['Origine, de obicei, în tubii contorți proximali; raport bărbați/femei de 2:1','Bilateral doar în circa 5% din cazuri; leziune sferică înconjurată de o pseudocapsulă','Triada clasică este raportată în doar 4–17% din cazuri; hematuria apare în 29–60%','LDH-ul și fosfataza alcalină sunt markeri tumorali specifici de certitudine','Chisturile simple se găsesc la sub 1% dintre adulți și impun nefrectomie de principiu'],'ABC',645,'CRCC — Epidemiologie și triada clasică',
 'Aplicarea originii în tubul proximal, a raportului 2:1, a bilateralității de 5% și a triadei rare (4–17%), față de absența markerilor.',
 ['Originea în tubii contorți proximali și raportul 2:1 sunt explicite.','Bilateralitatea de 5% și pseudocapsula sunt descrise.','Hematuria 29–60% și triada completă în 4–17% sunt citate.','Textul precizează că nu există markeri tumorali specifici pentru CRCC.','Chisturi simple se regăsesc la 33% dintre adulți și se urmăresc periodic.']],
 8,'Inventă markeri „specifici” pe care textul îi neagă și transformă chistul simplu (33%) în indicație de nefrectomie.',['2: I','4-17%']),

q(71,['În nefrectomia radicală pentru carcinomul cu celule clare se îndepărtează:',
 ['Rinichiul, grăsimea perirenală, fascia Gerota, suprarenala ipsilaterală și ganglionii limfatici regionali ipsilaterali','Doar polul inferior, cu păstrarea fasciei Gerota și a suprarenalei','Vezica, prostata și ganglionii pelvini, analog cistectomiei radicale','Ureterul până la orificiul vezical, ca în nefroureterectomia tranzițională','Tumora enucleată izolat, fără grăsime perirenală și fără control vascular prealabil'],'A',646,'CRCC — Conținutul nefrectomiei radicale',
 'Recunoașterea piesei de nefrectomie radicală (rinichi, grăsime, Gerota, suprarenală, ganglioni) și a controlului vascular înaintea disecției.',
 ['Textul enumeră rinichiul, grăsimea perirenală, fascia Gerota, suprarenala ipsilaterală și ganglionii regionali ipsilaterali.','Păstrarea fasciei și a suprarenalei contrazice definiția nefrectomiei radicale din text.','Cistectomia radicală vizează vezica, nu piesa renală.','Nefroureterectomia cu manșon vezical este tratamentul carcinomului tranzițional de cale superioară.','Vascularizația trebuie controlată înainte de manipulare; enuclearea izolată nu este nefrectomie radicală.']],
 8,'Confundă piesa radicală (Gerota + suprarenală) cu nefrectomia parțială sau cu nefroureterectomia tranzițională.',['fascia Gerata','nefrectomiei radicale']),

q(72,['Litiaza urinară — epidemiologie și tipuri de calculi:',
 ['Peste 500.000 de persoane sunt afectate anual, cu predominanță masculină și vârf la 30–50 de ani','Calculii de acid uric se asociază aportului ridicat de purine, gutei, deshidratării și hiperuricozuriei','Calculii de struvit (fosfat amonico-magnezian) apar în ITU cronice; când ocupă tot sistemul colector se numesc coraliformi','Calculii de acid uric se asociază urinei alcaline și unui aport scăzut de purine','Incidența maximă este după 70 de ani, cu predominanță feminină'],'ABC',647,'Litiază — Incidență, uric acid și coraliformi',
 'Potrivirea vârfului 30–50 de ani, a factorilor de uric acid (purine, gută) și a definiției calculului coraliform de struvit.',
 ['Cifra de peste 500.000, predominanța masculină și vârful 30–50 de ani sunt explicite.','Lista de risc a calculilor de acid uric include purinele, guta, deshidratarea și hiperuricozuria.','Struvitul din ITU cronice și denumirea de coraliform când ocupă tot sistemul colector sunt enunțate.','Urina alcalină dizolvă acidul uric; factorul de risc este aportul ridicat de purine, nu cel scăzut.','Vârful de vârstă citat este 30–50 de ani, cu predominanță masculină.']],
 8,'Inversează factorii de uric acid (purine scăzute, urină alcalină) și mută vârful epidemiologic după 70 de ani.',['500.000','coraliformi']),

q(73,['Gestionarea calculilor din sistemul colector renal:',
 ['Se realizează, de obicei, prin litotriție extracorporeală cu unde de șoc','Îndepărtarea percutanată este o opțiune alternativă, în special pentru litiaza multiplă','Chirurgia deschisă rămâne regula actuală de primă intenție','Calculii de acid uric nu se dizolvă prin alcalinizare urinară','Unda de șoc se focalizează pe rinichiul contralateral, nu pe calculul din F2'],'AB',648,'Litiază — ESWL și abordul percutanat',
 'Recunoașterea ESWL ca metodă obișnuită a calculilor din sistemul colector și a percutanei pentru litiaza multiplă.',
 ['Textul atribuie gestionarea obișnuită litotriției extracorporeale cu unde de șoc.','Percutana este opțiunea alternativă, mai ales în litiaza multiplă.','Chirurgia deschisă, frecventă în trecut, este rar indicată astăzi.','Calculii de acid uric se dizolvă la pH crescut, prin alcalinizare și aport de lichide.','Calculul se plasează în al doilea punct focal F2 al semi-elipsoidului.']],
 8,'Repune chirurgia deschisă ca regulă și mută focarul F2 pe rinichiul sănătos.',['Indepărtarea percutanată','litotriţie']),

q(74,['Alegeți afirmațiile corecte referitoare la obstrucția ureterală „din aval” și la leziunile iatrogene:',
 ['În obstrucția evacuării vezicii (HBP, cancer de prostată, strictură uretrală), ecografia arată hidronefroză și hidroureter bilaterale; inițial se cateterizează vezica','Leziunile iatrogene apar, în general, în chirurgia vasculară și ginecologică','În câmp contaminat, derivația proximală prin nefrostomie percutanată sau deschisă devine necesară','Reimplantarea ureterală este intervenția de elecție pentru orice leziune a ureterului lombar','În repararea anevrismului aortic, leziunea ureterală se lasă nereparată până la o a doua operație'],'ABC',649,'Ureter — Obstrucție din aval și iatrogenie',
 'Diferentierea cateterizării vezicii în obstrucția din aval de nefrostomia din câmp contaminat și de reimplantarea rezervată distalului.',
 ['Hidronefroza și hidroureterul bilaterale, cu cateterizarea vezicii ca prim gest, sunt explicite.','Contextul vascular și ginecologic al leziunilor iatrogene este enunțat.','Nefrostomia percutanată sau deschisă este cerută în câmp contaminat.','Reimplantarea este de elecție când este lezat ureterul distal, nu regula leziunii lombare.','La anevrismul aortic se repară mai întâi ureterul, apoi se acoperă cu epiploon.']],
 8,'Aplică reimplantarea distală pe ureterul lombar și amână repararea din anevrism, două erori din același paragraf iatrogen.',['nefrostomie percutanată','ginecolo']),

q(75,['Debitmetria și evoluția refluxului vezico-ureteral de grad mic:',
 ['Debitul maxim este de 20–25 mL/s la bărbați și 20–30 mL/s la femei, cu curbă în formă de clopot','Gradele I și II se pot remite în 20–30% din cazuri la fiecare 2 ani de creștere; 80% ajung la remisie completă','Cistoscopia este investigația de primă intenție, de rutină, la copilul cu reflux','Ecografia renală și UIV sunt suficiente, singure, pentru diagnosticul RVU','Debitul maxim normal la bărbat este sub 10 mL/s, identic pragului simptomatic al HBP'],'AB',650,'Urodinamică — Debit maxim și remisia RVU I–II',
 'Memorarea curbei în clopot (20–25 / 20–30 mL/s) și a remisiei 20–30% la 2 ani (80% completă) a gradelor I–II.',
 ['Valorile 20–25 mL/s (bărbați) și 20–30 mL/s (femei), cu curbă în clopot, sunt explicite.','Remisia 20–30% la fiecare 2 ani și ponderea finală de 80% sunt citate.','Cistoscopia nu este indicată de rutină la copiii cu reflux.','Ecografia și UIV evidențiază dilatații, dar nu diagnostichează singure RVU.','Pragul debitmetric al HBP simptomatice (<15 mL/s) nu este debitul maxim normal.']],
 8,'Permutează debitul maxim normal (20–25 mL/s) cu pragul obstructiv al HBP și anulează remisia de 80% a gradelor I–II.',['20-25 mL/secundă','80%']),

q(76,['Extrofia vezicală se caracterizează prin:',
 ['Incidență de circa 1:30.000 de nașteri, preponderență masculină 3:1 și risc crescut de adenocarcinom, cu supraveghere urologică pe tot parcursul vieții','Incidență 1:1.000, cu predominanță feminină 3:1','Absența dehiscenței simfizei pubiene, peretele abdominal fiind intact','Lipsa oricărui risc oncologic ulterior, monitorizarea fiind inutilă','Tratament prin observație, reconstrucția colului fiind contraindicată'],'A',651,'Extrofia vezicală — Incidență și adenocarcinom',
 'Fixarea incidenței 1:30.000, a raportului masculin 3:1 și a riscului de adenocarcinom cu supraveghere pe viață.',
 ['Cifra 1:30.000, preponderența masculină 3:1 și riscul de adenocarcinom cu monitorizare de-a lungul vieții sunt explicite.','1:1.000 cu predominanță feminină inversează atât incidența, cât și sexul.','Malformația include dehiscența simfizei pubiene și expunerea peretelui posterior vezical.','Riscul de adenocarcinom impune supraveghere urologică continuă.','Reconstrucția cu augmentare și refacerea colului este adesea necesară pentru continență și funcție renală.']],
 8,'Inversează sexul (3:1 masculin) și incidența (1:30.000 versus 1:1.000) din același paragraf de malformație rară.',['I :30.000','adenocarcinom']),

q(77,['Selectați enunțurile adevărate despre reimplantarea ureterală, uracă și diverticulii vezicali:',
 ['Procedura Cohen este avansarea încrucișată trigonală a ureterului','Tehnica Politano-Leadbetter creează un nou hiatus supero-lateral, cu stent ureteral','Vestigiile uracăi (diverticul la dom sau fistulă vezico-ombilicală) se tratează cel mai bine prin excizie simplă; persistența se asociază modificărilor adenocarcinomatoase','Prezența mușchiului în perete rămâne criteriul actual de diferențiere a diverticulilor congenitali de cei dobândiți','Diverticulul simptomatic se tratează doar medicamentos, fără excizie'],'ABC',652,'Vezică — Cohen, Politano-Leadbetter, uracă și diverticuli',
 'Citirea legendelor Cohen (încrucișare trigonală) și Politano-Leadbetter (hiatus supero-lateral), plus excizia simplă a vestigiilor de uracă.',
 ['Legenda figurii 29-17 numește procedura Cohen avansare încrucișată trigonală.','Legenda figurii 29-18 descrie noul hiatus supero-lateral și stentul ureteral.','Excizia simplă și asocierea adenocarcinomatoasă a vestigiilor de uracă sunt explicite.','Ipoteza mușchiului din perete ca marker congenital nu mai este valabilă.','Excizia diverticulului simptomatic este tratamentul de elecție în majoritatea situațiilor.']],
 8,'Păstrează criteriul „mușchi = congenital”, pe care textul îl respinge, și refuză excizia diverticulului simptomatic.',['Procedura Cohen','excizie simplă'],[651]),

q(78,['Un politraumatizat conștient, după accident rutier cu fractură de bazin, acuză durere severă suprapubiană și imposibilitatea de a micționa. Afirmația corectă este:',
 ['Rupturile vezicale cauzează aproape inevitabil hematurie; asocierea cu fractura de bazin impune și suspiciunea unei rupturi uretrale','Contuziile vezicii nu produc hematurie, spre deosebire de rupturi','Cistografia de adult se face cu circa 50 mL de contrast','Uretrografia retrogradă se practică după cateterizare, chiar dacă există sânge la meat','Diagnosticul se pune doar clinic, imagistica fiind superfluă la conștient'],'A',653,'Ruptura vezicală — Clinică și fractura de bazin',
 'Recunoașterea hematuriei aproape inevitabile și a asocierii fractură de bazin–ruptură uretrală, înaintea cistografiei.',
 ['Textul leagă ruptura de hematurie aproape inevitabilă și cere suspiciunea de ruptură uretrală la fractura de bazin.','Contuziile provoacă cel mai des hematurie.','La adult se introduc circa 350 mL de contrast steril.','Dacă există sânge la meat, uretrografia precede cateterizarea.','Cistografia este investigația cu mare acuratețe; la inconștient este esențial un grad ridicat de suspiciune.']],
 8,'Anulează hematuria contuziei și inversează ordinea uretrografie–cateter când există sânge la meat.',['fracturi de bazin','imposibilitatea de a micţiona'],[654]),

q(79,['Cistita bacteriană:',
 ['Orificiul vaginal extern se colonizează cu organisme din tubul digestiv înaintea apariției cistitei','La bărbați rezultă, în general, din evacuarea incompletă a vezicii','Cele mai frecvente patogene sunt bacili Gram-negativi din familia Enterobacteriaceae','Cu terapie adecvată, simptomele ar trebui să dispară în 3–5 zile','Febra este simptomul dominant al cistitei necomplicate și exclude infecția de tract superior'],'ABCD',654,'Cistită — Colonizare vaginală, Enterobacteriaceae și 3–5 zile',
 'Înlănțuirea colonizării introitului, a retenției la bărbat, a Enterobacteriaceae și a ferestrei simptomatice de 3–5 zile.',
 ['Colonizarea orificiului vaginal extern cu floră digestivă înaintea cistitei este explicită.','La bărbați, cistita urmează, în general, golirii incomplete.','Enterobacteriaceae, cu E. coli peste 80% din ITU, sunt cele mai frecvente patogene.','Simptomele ar trebui să dispară în 3–5 zile sub terapie adecvată.','Febra este neobișnuită în cistita necomplicată și poate indica infecția tractului superior.']],
 8,'Transformă febra — semnul de alarmă al tractului superior — în „simptom dominant” al cistitei necomplicate.',['3-5 zile','Enterobacteriaceae']),

q(80,['Următoarele afirmații despre cistita interstițială și fistulele vezicale sunt adevărate:',
 ['Instilațiile endovezicale pot include sulfoxid de dimetil, heparină și amitriptilină','Fistulele vezico-vaginale mici se pot evidenția prin instilare de albastru de metilen și tampon vaginal','Uroculturile din cistita interstițială sunt, în mod tipic, pozitive pentru bacterii','Fistula entero-vezicală se tratează doar cu antibiotice, fără rezecția ansei afectate','Albastrul de metilen se instilează după cistectomie totală, ca test de etanșeitate a neovezicii'],'AB',655,'Cistită interstițială — DMSO și testul cu albastru de metilen',
 'Recunoașterea instilațiilor (DMSO, heparină, amitriptilină) și a testului cu albastru de metilen plus tampon în fistula vezico-vaginală mică.',
 ['Cele trei substanțe de instilație sunt enumerate explicit.','Instilarea de albastru de metilen urmată de tampon vaginal este descrisă pentru fistulele mici.','Uroculturile pentru bacterii, virusuri și fungi sunt, în mod tipic, negative.','Tratamentul fistulei entero-vezicale include rezecția porțiunii de intestin afectat.','Testul cu albastru de metilen vizează fistula vezico-vaginală, nu neovezica.']],
 8,'Declară uroculturile interstițiale pozitive și tratează fistula entero-vezicală doar medicamentos, două inversiuni din aceeași pagină.',['sulfoxidul de dimetil','albastru de metilen']),

q(81,['Precizați enunțul corect privind sfincterul urinar artificial la bărbat:',
 ['Este rezervat incontinenței de efort feminine, analog bandeletei transvaginale comerciale','Include o manșetă pe uretra bulbară, un rezervor cu lichid și o pompă scrotală; pompa transferă lichidul din manșetă în rezervor la micțiune','Firele se leagă pe fața posterioară a simfizei, ca în procedura Marshall-Marchetti-Krantz','Se montează endoscopic, analog injectării de Deflux sub orificiul ureteral','Înlocuiește de primă intenție anticolinergicele din instabilitatea detrusorului fără obstrucție'],'B',656,'Incontinență masculină — Sfincterul artificial',
 'Recunoașterea celor trei componente (manșetă bulbară, rezervor, pompă scrotală) ale sfincterului artificial, distinct de MMK și de bandeletă.',
 ['Bandeletele transvaginale sunt preferate incontinenței de efort la femei, nu sfincterului masculin.','Textul descrie manșeta pe uretra bulbară, rezervorul și pompa scrotală, cu transferul lichidului la micțiune.','Marshall-Marchetti-Krantz fixează colul pe fața posterioară a simfizei la femeie.','Deflux-ul este terapia endoscopică a refluxului, nu a incontinenței masculine.','Instabilitatea detrusorului fără obstrucție răspunde la oxibutinină, nu la sfincter artificial.']],
 8,'Pune sfincterul masculin pe algoritmul feminin (MMK, bandeletă, Deflux) sau pe instabilitatea tratată medicamentos.',['sfincter urinar artificial','uretra bulbară']),

q(82,['Vezica neinhibată reflexă (lezare medulară suprasacrată) se caracterizează prin:',
 ['Contracții necontrolate, fazice, declanșate de stimulare intrinsică sau extrinsecă','În leziunile toracice înalte sau cervicale, sfincterul este frecvent dissinergic (dissinergism sfincter-detrusor)','Senzația și coordonarea sfincteriană rămân intacte, ca în vezica cerebrală neinhibată','Capacitatea de umplere este păstrată, fără golire incompletă','Rezultă din lezarea conului medular sau a plexului sacrat, analog vezicii autonome'],'AB',657,'Vezică neurogenă — Tipul reflex cu dissinergie',
 'Separarea vezicii reflexe suprasacrate cu dissinergie sfincter-detrusor de vezica cerebrală neinhibată (sfincter coordonat) și de cea autonomă sacrală.',
 ['Contracțiile fazice necontrolate, declanșate intrinsic sau extrinsec, sunt explicite.','Dissinergismul sfincter-detrusor al leziunilor toracice înalte sau cervicale este numit ca atare.','Senzația normală și coordonarea sfincteriană țin de vezica neinhibată cerebrală, nu de forma reflexă.','Contracțiile pot fi ineficiente, cu golire incompletă.','Leziunea sacrală, a conului sau a plexului produce vezica autonomă, nu pe cea reflexă.']],
 8,'Confundă dissinergia medulară înaltă cu sfincterul coordonat cerebral și cu areflexia sacrală, trei linii vecine de clasificare.',['dissinergism','sfincter-detrusor']),

q(83,['În disfuncția vezicală neurologică se recomandă:',
 ['Anticolinergice (tolterodină, oxibutinină) pentru a suprima contracțiile neinhibate și a îmbunătăți complianța','Autocateterizare intermitentă, preferată drenajului uretral sau suprapubian permanent din cauza ratei reduse de infecții','Cistoplastie de augmentare cu ansă intestinală dacă presiunile de umplere rămân înalte sub tratament medical','Sfincterotomie endoscopică, care favorizează incontinența gestionabilă cu un drenaj extern tip prezervativ urinar','Cateter transuretral cronic de primă intenție, rata infecțioasă fiind mai mică decât la autocateterizare'],'ABCD',658,'Vezică neurogenă — CIC, augmentare și sfincterotomie',
 'Ierarhizarea anticolinergicelor și a CIC, cu augmentarea sau sfincterotomia ca salvare a presiunilor înalte, față de Foley-ul cronic evitat.',
 ['Tolterodina și oxibutinina sunt citate pentru contracții neinhibate și complianță.','Autocateterizarea intermitentă este preferată drenajului permanent, prin rata redusă de infecții.','Augmentarea cu ansă intestinală urmează eșecului medical la presiuni înalte.','Sfincterotomia produce incontinență gestionată cu prezervativ urinar.','Drenajul uretral sau suprapubian cronic are rata infecțioasă mai mare; nu este prima linie.']],
 8,'Pune Foley-ul cronic înaintea autocateterizării, inversând argumentul infecțios al textului.',['Autocateterizarea intermitentă','sfincterotomie']),

q(84,['Carcinomul vezical — BCG, progresie și reconstrucție:',
 ['BCG-ul începe cu o cură de inducție de 6 săptămâni, urmată de întreținere 2–3 ani','Riscul de progresie musculo-invazivă este relativ redus (<10%) în Ta, dar crește în T1 sau la leziunile de grad înalt','La bărbat, cistectomia radicală îndepărtează vezica, prostata, grăsimea perivezicală și ganglionii pelvini','Neovezica ortotopică din intestin detubularizat se anastomozează direct la uretră, evitând derivația cutanată','Supraviețuirea la 5 ani după cistectomie pentru T3 este sub 10%'],'ABCD',659,'Carcinom vezical — Protocol BCG și neovezică',
 'Memorarea inducției BCG de 6 săptămâni, a progresiei <10% în Ta, a piesei de cistectomie masculină și a neovezicii ortotopice.',
 ['Cura de 6 săptămâni urmată de întreținere 2–3 ani este explicită.','Pragul <10% în Ta, cu creștere în T1 sau la grad înalt, este citat.','Conținutul cistectomiei radicale la bărbat este enumerat.','Anastomoza intestinului detubularizat la uretră evită stoma și cateterizarea.','Rata de supraviețuire la 5 ani după cistectomie pentru T3 este de aproximativ 60%.']],
 8,'Înlocuiește supraviețuirea de 60% din T3 cu recidiva de 50% a tumorilor superficiale sau cu un prag sub 10%.',['6 săptămâni','neovezică ortotopică']),

q(85,['Anatomia uretrei masculine și feminine:',
 ['Uretra prostatică este căptușită de epiteliu de tranziție; membranoasa, bulbară și peniană de epiteliu columnar pseudostratificat sau stratificat; meatul de epiteliu scuamos','Uretra feminină are circa 4 cm; treimea proximală este tranzițională, cele două treimi distale scuamoase','Glandele Cowper se deschid în uretra prostatică, nu în cea bulbară','Uretra anterioară include prostatica și membranoasa, nu peniana și bulbară','Drenajul limfatic al uretrei posterioare se face prin ganglionii inghinali superficiali, nu iliaci'],'AB',664,'Uretră — Epiteliu, lungime feminină și glande Cowper',
 'Potrivirea hartii epiteliale masculine și a uretrei feminine de 4 cm (1/3 tranziție, 2/3 scuamos), față de deschiderea Cowper în bulbară.',
 ['Harta epitelială (tranziție prostatică, columnar membranos/bulbar/penian, scuamos la meat) este explicită.','Cei 4 cm și împărțirea 1/3–2/3 sunt descrise.','Glandele bulbouretrale (Cowper) se secretă în uretra bulbară.','Segmentul posterior cuprinde prostatica și membranoasa; anteriorul include meatul, fosa naviculară, peniana și bulbară.','Uretra posterioară drenează în ganglionii obturatori și iliaci.']],
 8,'Mută Cowper din bulbară în prostatică și inversează anterior/posterior, două erori de hartă din aceeași figură.',['4 cm','Glandele bulbouretrale']),

q(86,['Stricturile uretrale:',
 ['Cauzele cele mai comune actuale sunt leziunile prin cădere „călare” pe perineu și instrumentarea uretrei','Pentru o strictură <1 cm, limitată la mucoasă, dilatarea sau uretrotomia optică internă pot fi soluții curative','Reconstrucția deschisă a unei stricturi bulbare scurte prin excizie și anastomoză primară are rată de succes permanent >98%','Stricturile lungi se dilată fără evaluare imagistică prealabilă, ca în practica istorică considerată suficientă','Grefele de mucoasă bucală sunt rezervate stricturilor mucoase scurte, nu celor lungi sau distale'],'ABC',666,'Strictură uretrală — Cauze actuale, VIU și succes >98%',
 'Actualizarea etiologiei (cădere călare, instrumentare), a ferestrei <1 cm pentru VIU și a succesului >98% al anastomozei bulbare scurte.',
 ['Textul înlocuiește gonoreea istorică cu traumatismul călare și instrumentarea.','Pragul <1 cm, limitat la mucoasă, pentru dilatare sau uretrotomie optică internă, este explicit.','Rata >98% după excizie și anastomoză primară a stricturii bulbare scurte este citată.','Managementul modern cere imagistică retrogradă și anterogradă plus uretroscopie înaintea tratamentului.','Mucoasa bucală (sau prepuțul) servește stricturilor lungi sau distale, nu pe cele scurte mucoase.']],
 8,'Păstrează dilatațiile „orbe” istorice și atribuie grefa bucală stricturii scurte, exact invers algoritmului modern.',['>98%','uretrotomia optică internă']),

q(87,['Un bărbat prezintă secreție uretrală galben-verzuie la o săptămână după un contact sexual neprotejat. Sunt adevărate:',
 ['După o incubație de 2–14 zile, majoritatea bărbaților cu gonoree au secreție galben-verzuie; circa 25% rămân asimptomatici','Diagnosticul se sprijină pe culturi pe mediu Thayer-Martin; pacientul și partenerii se tratează înaintea rezultatului bacteriologic','În practică, la suspiciune de BTS cu gonococ sau chlamydia se asociază ceftriaxona și azitromicina','Azitromicina 1 g oral este monoterapia de elecție a gonococului, fără ceftriaxonă','Incubația uretritei non-gonococice este de 2–14 zile, identică gonoreei'],'ABC',668,'Uretrite — Incubație, 25% asimptomatici și dublă terapie',
 'Înlănțuirea incubației 2–14 zile, a celor 25% asimptomatici, a mediului Thayer-Martin și a asocierii ceftriaxonă–azitromicină.',
 ['Incubația 2–14 zile, secreția galben-verzuie și ponderea de 25% asimptomatici sunt explicite.','Mediul Thayer-Martin și tratamentul înaintea rezultatului sunt descrise.','Asocierea ceftriaxonă plus azitromicină în suspiciunea de BTS mixtă este enunțată.','Azitromicina 1 g este tratamentul de elecție al uretritei non-gonococice, nu monoterapia gonococului.','Uretrita non-gonococică are incubație de 1–3 săptămâni.']],
 8,'Substituie doza IM de ceftriaxonă cu azitromicina orală a nongonococului și aliniază incubațiile (2–14 zile versus 1–3 săptămâni).',['Thayer-Mattin','25%']),

q(88,['Anorhidia și patența procesului vaginal:',
 ['Anorhidia reprezintă 3–5% dintre testiculele nepalpabile; majoritatea urmează torsiunii prenatale sau accidentelor vasculare','Semnul „mănușii de mătase” la rularea cordonului sugerează sac peritoneal; hidrocelul persistent după 1 an se tratează prin ligatură înaltă la inelul intern','Testiculul retractil rămâne blocat extra-scrotal și impune orhidopexie imediată','CT-ul este investigația de primă intenție pentru localizarea testiculului nepalpabil','Anorhia bilaterală nu necesită substituție hormonală la pubertate'],'AB',669,'Anorhidie 3–5% și semnul mănușii de mătase',
 'Separarea anorhidiei (3–5%, torsiune prenatală) de semnul mănușii de mătase și de ligatura înaltă a hidrocelului după 1 an.',
 ['Ponderea 3–5% și mecanismul (torsiune prenatală sau accident vascular, rar agenezie) sunt explicite.','Semnul mănușii de mătase și ligatura înaltă la inelul intern după 1 an sunt descrise.','Testiculele retractile coboară, de obicei, în scrot la pubertate.','CT și ecografia nu sunt utile, în general, în localizare; laparoscopia este adesea utilă.','Anorhia bilaterală conduce la sterilitate și necesită terapie de suplinire hormonală la pubertate.']],
 8,'Operează de urgență testiculul retractil (care coboară la pubertate) și promovează CT-ul pe care textul îl consideră inutil.',['3-5%','mănuşii de mătase']),

q(89,['La palparea scrotului, o masă adiacentă cordonului, percepută „ca un sac de râme”, sugerează:',
 ['Varicocel, prezent la circa 15–20% dintre bărbați, cu predilecție stângă; se corectează dacă asociază durere ipsilaterală, atrofie testiculară sau subfertilitate','Cancer testicular, cu indicație de orhidectomie scrotală imediată','Spermatocel care transiluminează prin testicul','Hidrocel prin exces de absorbție la foița parietală a vaginalei','Indicație de limfodisecție retroperitoneală de principiu, fără alte criterii'],'A',670,'Varicocelul — Sac de râme, 15–20% și indicații',
 'Recunoașterea varicocelului (15–20%, stânga, valvele venei testiculare) și a celor trei indicații de corecție, distinct de masa testiculară malignă.',
 ['Analogia „sac de râme”, ponderea 15–20%, predilecția stângă și criteriile (durere, atrofie, subfertilitate) sunt explicite.','Masa testiculară are probabilitate înaltă de malignitate; abordul este inghinal, nu scrotal.','Spermatocelul transiluminează deasupra sau sub testicul, nu palpează ca un sac de râme pe cordon.','Hidrocelul transiluminează prin testicul, prin scăderea absorbției (nu exces) la foița parietală.','RPLND ține de tumorile germinale după orhidectomie inghinală, nu de varicocel.']],
 8,'Tratează varicocelul ca cancer (orhidectomie scrotală, RPLND) și inversează mecanismul hidrocelului (scăderea absorbției).',['15-20%','sac de râme']),

q(90,['Evaluarea de laborator a infertilității masculine:',
 ['Factorul masculin este responsabil în 40% din cazuri și parțial responsabil în încă 20%','Se examinează trei probe, după minim 24 de ore de abstinență, la mai puțin de o oră de la colectare','Standardele WHO includ volum 1,5–5,0 mL, densitate >20 milioane/mL, mobilitate >60% și morfologie >60% normali','Ejaculatul se colectează într-un borcan de sticlă cu gură largă, plasticul putând fi spermicid','O singură probă, imediat după ejaculare într-un prezervativ lubrifiat, este suficientă'],'ABCD',671,'Infertilitate — Factor masculin 40%+20% și spermograma WHO',
 'Aplicarea ponderii 40%+20%, a protocolului cu trei probe și a standardelor WHO (volum, densitate, mobilitate, morfologie).',
 ['Cotele 40% (cauză unică) și încă 20% (parțial) sunt explicite.','Trei probe, abstinență minim 24 de ore și examinare sub o oră sunt cerute.','Tabelul 29-5 listează 1,5–5,0 mL, >20 milioane/mL, mobilitate >60% și morfologie >60%.','Borcanul de sticlă cu gură largă este precizat; plasticul poate fi spermicid.','O singură probă este insuficientă; lubrifianții pot avea efect spermicid.']],
 8,'Reduce evaluarea la o singură probă în prezervativ lubrifiat, exact ce textul interzice prin protocolul de trei probe în sticlă.',['1.5-5.0 ml','20 milioane/ml']),

q(91,['După eșecul unui Foley 16 French la un bărbat cu prostată mărită, afirmațiile corecte sunt:',
 ['Un cateter cu vârf cudat (18–20 French) se avansează păstrând portul de balon orientat în sus','Dacă urina nu apare, lumenul poate fi blocat de lubrifiant, care se dizolvă de obicei într-un minut; se poate iriga cu 60 mL ser cu seringa Toomey, fără a umfla balonul','Balonul se umflă de îndată ce vârful a trecut meatul, chiar fără scurgere de urină','Forțarea manevrei este metoda de elecție când lobul median opune rezistență','Strictura se trece, de regulă, cu un cateter 24 French, mai gros decât cel standard'],'AB',674,'Cateterism — Vârf cudat 18–20 Fr și seringa Toomey',
 'Aplicarea cateterului cudat 18–20 Fr cu portul în sus și a irigației Toomey cu 60 mL, fără umflarea balonului înaintea urinei.',
 ['Calibrul 18–20 French, vârful curbat în sus și orientarea portului de balon sunt explicite.','Blocajul temporar de lubrifiant (circa un minut) și irigația cu 60 mL prin seringa Toomey, fără umflarea balonului, sunt descrise.','Balonul nu se umflă până când cateterul avansează pe tot traiectul și urina devine vizibilă.','Forțarea riscă o leziune uretrală sau o cale falsă; se injectează lubrifiant adițional și se schimbă cateterul.','La strictură poate fi indicat un calibru mai mic (12–14 French), nu unul mai gros.']],
 8,'Umflă balonul în uretră, forțează lobul median și trece strictura cu un cateter mai gros — trei erori din același algoritm practic.',['18-20 French','seringa Toomey'],[673]),
];
