import {rewriter} from './rewrite-author';
import {RETIRED_VASCULAR} from './retired/vascular';

// Rewritten after the 2026-09-24 cue audit (Lawrence, cap. 26, p. 520–527 and 534–541).
const q=rewriter(RETIRED_VASCULAR,(p:number)=>p<=527?p-315:p-321,{shuffle:true});

export const VASCULAR_V2=[
q('vascular-adv-007',['Anevrismele de arteră femurală, comparativ cu cele poplitee:',
 ['embolizează și se trombozează mai rar','embolizează și se trombozează mai frecvent','se tratează de elecție prin graft-stent','au morbiditate mai mare','nu necesită tratament chirurgical'],'A',520,'Anevrismele periferice',
 'Compararea anevrismelor femurale cu cele poplitee.',
 ['Morbiditatea este redusă: embolizează și se trombozează mai rar.','Embolizează mai rar.','Graft-stentul nu este recomandat în zona de mobilitate.','Morbiditatea este redusă.','Tratamentul este bypass cu interpoziție de grefă.']],
 [8,'Distractorii inversează riscul și tratamentul.'],['arteră femurală','graft-stent']),

q('vascular-adv-048',['Disecția de aortă:',
 ['poate fi favorizată de sindroamele Marfan și Ehlers-Danlos','se propagă doar distal, prin adventice','creează un lumen fals de cel puțin 50% din circumferință','se confirmă prin radiografie toracică simplă','interesează inițial adventicea, apoi intima și media'],'AC',520,'Disecția de aortă',
 'Recunoașterea etiopatogeniei disecției de aortă.',
 ['Marfan și Ehlers-Danlos predispun la degenerarea mediei.','Nu: disecția se propagă proximal sau distal prin medie.','Lumenul fals reprezintă 50% sau mai mult din circumferință.','Se confirmă prin ETE, CT sau angiografie.','Dilacerarea merge dinspre intimă spre medie.']],
 [8,'Distractorii inversează sensul leziunii și metoda diagnostică.'],['Marfan','lumen dublu']),

q('vascular-adv-001',['Clasificarea și tratamentul disecției de aortă (Stanford):',
 ['tipul A interesează aorta ascendentă','tipul A impune chirurgie de urgență','tipul B începe distal de artera subclaviculară stângă','tipul B necomplicat impune chirurgie de urgență','tipul A începe distal de subclaviculara stângă'],'ABC',520,'Disecția de aortă',
 'Aplicarea clasificării Stanford.',
 ['Tipul A interesează aorta toracică ascendentă.','Tratamentul tipului A este chirurgical de urgență.','Tipul B este distal de subclaviculara stângă.','Tipul B se tratează inițial medical (TA, FC, dp/dt).','Tipul A interesează aorta ascendentă.']],
 [8,'Distractorii inversează tipurile.'],['Stanford','subclaviculară stângă']),

q('vascular-adv-049',['Complicațiile disecției de aortă ascendentă includ:',
 ['ischemia miocardică prin obstruarea coronarelor','insuficiența aortică acută','tamponada cardiacă','accidentul vascular cerebral','stenoza aortică acută'],'ABCD',520,'Disecția de aortă — Complicații',
 'Recunoașterea complicațiilor după sensul propagării.',
 ['Disecția retrogradă poate obstrua coronarele.','Extensia la cuspe produce insuficiență aortică.','Ruptura în pericard produce tamponadă.','Extensia la vasele brahiocefalice produce AVC.','Nu este complicația citată.']],
 [8,'Singurul distractor inversează valvulopatia.'],['cuspelor aortice','tamponadei cardiace']),

q('vascular-adv-050',['Indicația majoră de chirurgie reparatorie electivă în disecția de tip B este:',
 ['lărgirea disecției cronice cu anevrism asociat','orice disecție de tip B diagnosticată în primele 6 ore','hipertensiunea arterială controlată medical','disecția limitată, fără dilatare anevrismală','durerea toracică transfixiantă inițială'],'A',520,'Disecția de aortă — Tratament',
 'Aplicarea indicațiilor chirurgicale în disecția de tip B.',
 ['Lărgirea disecției cronice cu anevrism este indicația majoră electivă.','Tipul B se tratează inițial medical.','Nu este indicația citată.','Nu este indicația citată.','Nu este indicația citată.']],
 [8,'Distractorii sunt situații de tratament medical.'],['indicaţia majoră','chirurgie reparatorie electivă']),

q('vascular-adv-002',['Localizarea cea mai frecventă a bolii ocluzive femuro-popliteale este:',
 ['AFS, în canalul adductorilor','AFP, la emergența din femurala comună','trifurcația arterei poplitee','artera tibială anterioară','artera iliacă externă distală'],'A',520,'Boala arterială periferică',
 'Recunoașterea sediului tipic al bolii femuro-popliteale.',
 ['AFS în canalul adductorilor este sediul cel mai frecvent.','AFP asigură de obicei colateralele.','Boala tibială este tipică la diabetici.','Nu este sediul citat.','Nu este sediul citat.']],
 [8,'Distractorii sunt segmente arteriale învecinate.'],['canalul adductorilor','Hunter']),

q('vascular-adv-008',['Legea Poiseuille aplicată stenozei arteriale:',
 ['căderea de presiune este invers proporțională cu raza la puterea a patra','ΔP rămâne mică până la stenoza de 50% a diametrului','căderea de presiune nu depinde de vâscozitatea sângelui','căderea de presiune este independentă de lungimea arterei','fluxul scade semnificativ de la o stenoză de 10%'],'AB',520,'Boala arterială periferică — Fiziologie',
 'Aplicarea legii Poiseuille la stenoza arterială.',
 ['ΔP = 8QLη/πr⁴: raza are cel mai mare efect.','ΔP este mică până la 50% din diametru sau 75% din arie.','Nu: ΔP = 8QLη/πr⁴ include vâscozitatea η.','ΔP este direct proporțională cu lungimea.','Scăderea apare după pragul de 50%.']],
 [8,'Distractorii contrazic relațiile legii.'],['Poiseuille','75%']),

q('vascular-adv-009',['Evoluția naturală a claudicației netratate (Framingham):',
 ['riscul de amputație este de ~5% la 5 ani','simptomele se ameliorează la 50% cu stop fumat și exercițiu','cauza principală de deces este ateroscleroza sistemică','riscul de amputație este de ~50% la 5 ani','cauza principală de deces este ischemia de membru'],'ABC',521,'Boala arterială periferică — Evoluție',
 'Fixarea prognosticului claudicației.',
 ['Riscul de amputație este de numai 5% la 5 ani.','50% se ameliorează sau devin asimptomatici.','Decesul este prin evenimente cardiace sau cerebrale.','Riscul este de 5%.','Decesul este prin ateroscleroza sistemică.']],
 [8,'Distractorii umflă riscul local.'],['Framingham','5% la']),

q('vascular-adv-052',['Claudicația intermitentă:',
 ['este precipitată de efort și ameliorată de repaus','se explică prin conversia la metabolism anaerob','afectează predominant articulațiile','este prezentă și în repaus','afectează grupe musculare proximal de obstrucție'],'AB',521,'Tablou clinic — Claudicația',
 'Explicarea mecanismului și topografiei claudicației.',
 ['Durerea e precipitată de efort și ameliorată de repaus.','Ocluziile împiedică creșterea fluxului; apare acidoza.','Nu: claudicația cruță articulațiile și piciorul.','Durerea de repaus indică boală avansată.','Grupele afectate sunt distal de obstrucție.']],
 [8,'Distractorii inversează topografia și contextul.'],['claudatio','metabolismul anaerob']),

q('vascular-adv-010',['Topografia claudicației:',
 ['ocluzia aorto-iliacă produce sindromul Leriche','sindromul Leriche cruță funcția erectilă','ocluzia AFS produce claudicație de gambă','ocluzia AFS produce claudicație de coapsă','sindromul Leriche include hipertrofia musculaturii fesiere'],'AC',521,'Tablou clinic — Claudicația',
 'Corelarea nivelului ocluziei cu sediul claudicației.',
 ['Ocluzia aorto-iliacă determină sindromul Leriche.','Nu: sindromul Leriche include impotența.','Coapsa e irigată de AFP, deci AFS produce claudicație de gambă.','Coapsa este irigată de AFP.','Apare atrofia fesieră.']],
 [8,'Distractorii inversează sediul și troficitatea.'],['Leriche','artera femurala']),

q('vascular-adv-011',['Durerea ischemică de repaus:',
 ['cedează în poziție declivă','cedează la ridicarea piciorului','apare mai ales ziua, la efort','este localizată tipic la gambă','nu are modificări cutanate ischemice'],'A',521,'Tablou clinic — Durerea de repaus',
 'Recunoașterea durerii ischemice de repaus.',
 ['Presiunea hidrostatică în declivitate crește aportul de oxigen.','Ridicarea agravează ischemia.','Apare mai ales noaptea.','Este localizată la degete și metatarsiene distale.','Descrie crampele nocturne.']],
 [8,'Distractorii descriu crampele nocturne și claudicația.'],['declivă','hidrostatică']),

q('vascular-adv-012',['Ulcerele de membru inferior:',
 ['arteriale sunt de obicei dureroase, cu bază palidă sau necrotică','venoase apar de obicei imediat deasupra maleolelor','diabetice sunt nedureroase, plantare sau laterale','arteriale apar de obicei deasupra maleolelor','diabetice sunt intens dureroase, pe fața dorsală a piciorului'],'ABC',521,'Tablou clinic — Ulcerele',
 'Diferențierea ulcerelor arteriale, venoase și diabetice.',
 ['Ulcerele arteriale sunt dureroase, circumscrise, cu bază palidă.','Ulcerele venoase apar deasupra maleolelor.','Ulcerele diabetice sunt nedureroase, în zone de presiune.','Localizarea supramaleolară este venoasă.','Neuropatia le face nedureroase.']],
 [8,'Distractorii permută trăsăturile ulcerelor.'],['maleolelor','Charcot']),

q('vascular-adv-013',['Gangrena și amputația în boala arterială periferică:',
 ['gangrena uscată înseamnă mumificare fără infecție activă','gangrena umedă se asociază cu infecție activă','diabetul este cea mai frecventă cauză de amputație','diabeticul amputat are supraviețuire la 2 ani de ~50%','gangrena uscată are prognosticul cel mai sever'],'ABCD',522,'Tablou clinic — Gangrena',
 'Diferențierea formelor de gangrenă și prognosticul.',
 ['Gangrena uscată este mumificare fără drenaj purulent.','Gangrena umedă asociază infecție activă.','Diabetul este cea mai frecventă cauză de amputație.','Supraviețuirea la 2 ani este de 50%.','Gangrena umedă are prognosticul nefavorabil.']],
 [8,'Singurul distractor inversează severitatea.'],['Gangrena umedă','2 ani de 50%']),

q('vascular-adv-053',['Durerea din stenoza de canal medular, față de claudicația ischemică:',
 ['se ameliorează prin aplecarea înainte în timpul mersului','rămâne strict localizată la gambă','nu se remite imediat în repaus','dispare imediat la oprirea mersului','este localizată la grupele musculare majore'],'AC',522,'Evaluare — Diagnosticul diferențial',
 'Diferențierea claudicației neurogene de cea ischemică.',
 ['Aplecarea înainte ameliorează durerea.','Nu: durerea neurogenă radiază adesea de-a lungul membrului.','Nu se remite imediat în repaus.','Dispariția la oprire caracterizează claudicația ischemică.','Durerea neurogenă nu este localizată la grupele musculare.']],
 [8,'Distractorii descriu claudicația ischemică.'],['aplecarea înainte','canal medular']),

q('vascular-adv-003',['Evaluarea neinvazivă în boala arterială periferică:',
 ['un IGB peste 0,9 este normal','un IGB sub 0,4 se asociază cu durere de repaus','semnalul Doppler normal este monofazic','semnalul Doppler devine trifazic în stenoză','IGB crește la efort la pacientul claudicant'],'AB',522,'Evaluare — Doppler și IGB',
 'Interpretarea IGB și a semnalului Doppler.',
 ['IGB >0,9 este normal.','IGB <0,4 se asociază cu durere de repaus sau leziuni tisulare.','Nu: unda Doppler normală este trifazică.','Stenoza face unda bifazică, apoi monofazică.','IGB scade la efort la claudicant.']],
 [8,'Distractorii inversează evoluția undei și a IGB.'],['trifazică','0.9']),

q('vascular-adv-027',['Complicațiile angiografiei (tehnica Seldinger):',
 ['pseudoanevrismul la locul puncției','fistula arterio-venoasă iatrogenă','toxicitatea renală la contrast, mai frecventă la diabetici','tromboza apărută de obicei în primele 6 ore','embolia pulmonară, ca regulă după puncția femurală'],'ABCD',523,'Diagnosticul imagistic',
 'Recunoașterea complicațiilor angiografiei.',
 ['Pseudoanevrismul este o complicație citată.','Fistula AV iatrogenă este citată.','Toxicitatea renală este mai frecventă la diabetici.','Tromboza apare de obicei în primele 6 ore.','Nu este complicația citată.']],
 [8,'Singurul distractor nu este o complicație citată.'],['Seldinger','primele 6 ore']),

q('vascular-adv-029',['Angio-RM și angio-CT, față de arteriografie:',
 ['nu necesită puncție femurală','injectează contrastul într-o arteră periferică','pot, rar, produce fibroză subcutanată la insuficiența renală','permit angioplastia în aceeași ședință','nu implică niciun risc legat de contrast'],'AC',523,'Diagnosticul imagistic',
 'Compararea metodelor imagistice vasculare.',
 ['Fără puncție femurală, nu apar complicații locale.','Nu: contrastul se injectează într-o venă centrală.','Gadoliniumul poate produce rar fibroză subcutanată.','Arteriografia permite intervenția.','Există un risc mic de complicații.']],
 [8,'Distractorii atribuie metodelor capacități ale arteriografiei.'],['Gadolinium','venă centrală']),

q('vascular-adv-055',['Prevenția complicațiilor în boala arterială periferică:',
 ['steroizi și antihistaminice la hipersensibilitatea la contrast','anamneza alergică înaintea investigațiilor cu contrast','îngrijirea regulată a piciorului diabetic','hidratarea înainte și după angiografie','evitarea hidratării la insuficiența renală'],'ABCD',523,'Diagnosticul imagistic și managementul medical',
 'Aplicarea măsurilor preventive.',
 ['Steroizii și antihistaminicele reduc reacțiile.','Statusul alergic se chestionează atent.','Îngrijirea piciorului previne ulcerațiile.','Hidratarea este importantă, mai ales în insuficiența renală.','Hidratarea este esențială în insuficiența renală.']],
 [8,'Singurul distractor inversează recomandarea.'],['antihistaminice','calusurilor']),

q('vascular-adv-028',['Cauza principală de deces la pacienții cu boală arterială periferică este:',
 ['infarctul miocardic','amputația majoră','embolia pulmonară','ischemia mezenterică acută','ruptura de anevrism popliteu'],'A',523,'Managementul medical',
 'Recunoașterea cauzei principale de deces în BAP.',
 ['IM este cauza principală de deces.','Nu este cauza citată.','Nu este cauza citată.','Nu este cauza citată.','Nu este cauza citată.']],
 [8,'Distractorii sunt complicații vasculare reale.'],['infarctul','terapie antiplachetară']),

q('vascular-adv-045',['Angioplastia transluminală percutanată (PTA):',
 ['se poate complica prin ocluzie acută după disecție intimală','nu produce restenoză prin recul elastic','poate recanaliza subintimal o ocluzie, fără bypass','este limitată la stenozele scurte, fără ocluzii totale','nu necesită stentare după disecție'],'AC',524,'Tratamentul endovascular',
 'Recunoașterea posibilităților și complicațiilor PTA.',
 ['Ruptura plăcii sau disecția produc ocluzie acută.','Nu: reculul elastic produce restenoză.','Recanalizarea subintimală evită bypassul.','Tehnica s-a extins la ocluziile totale.','Complicațiile cer în general stentare.']],
 [8,'Distractorii subestimează tehnica și riscurile.'],['subintimală','reculul elastic']),

q('vascular-adv-014',['Stenturile în angioplastia periferică:',
 ['cele din oțel expandabile pe balon au forță radială mare','cele din oțel sunt indicate la originea arterei iliace comune','cele din nitinol sunt flexibile, pentru leziuni lungi','cele din nitinol au forța radială cea mai mare dintre stenturi','toate sunt sigure în zonele de flexie amplă'],'ABC',524,'Tratamentul endovascular — Stenturile',
 'Alegerea tipului de stent după leziune.',
 ['Oțelul expandabil pe balon are forță radială mare.','Este indicat la leziunile calcificate de la originea vaselor.','Nitinolul este flexibil, pentru leziuni lungi sau sinuoase.','Nitinolul are forță radială mai mică.','Toate stenturile riscă fractura în zonele de flexie.']],
 [8,'Distractorii inversează proprietățile stenturilor.'],['nitinol','forţă radială']),

q('vascular-adv-030',['Tehnicile adjuvante ale angioplastiei:',
 ['aterectomia îndepărtează placa','aterectomia are incidență ridicată a restenozei','stenturile acoperite au rezultate favorabile în restenoză','stenturile farmacologic active au patență promițătoare','aterectomia are incidență scăzută a restenozei'],'ABCD',524,'Tratamentul endovascular — Tehnici adjuvante',
 'Recunoașterea tehnicilor adjuvante ale PTA.',
 ['Aterectomia îndepărtează placa.','Suprafețele denudate cresc restenoza.','Stenturile acoperite sunt favorabile, mai ales la restenoză.','Studiile inițiale au arătat patență promițătoare.','Restenoza este ridicată.']],
 [8,'Singurul distractor inversează restenoza.'],['Aterectomia','stenturilor acoperite']),

q('vascular-adv-015',['Restenoza după intervenția endovasculară:',
 ['apare de obicei între 6 luni și 1 an','se explică prin hiperplazie neointimală','afectează infrainghinal sub 5% la 1 an','apare de obicei în primele 48 de ore','este prevenită definitiv de stenturile farmacologic active'],'AB',525,'Tratamentul endovascular — Restenoza',
 'Recunoașterea mecanismului și ratei restenozei.',
 ['Restenoza apare la 6 luni–1 an.','Mecanismul este remodelarea și hiperplazia neointimală.','Nu: restenoza sau eșecul infrainghinal este de 20–50% la 1 an.','Nu este intervalul citat.','Hiperplazia continuă să limiteze eficacitatea.']],
 [8,'Distractorii schimbă intervalul și supraestimează prevenția.'],['hiperplaziei neointimale','20% şi 50%']),

q('vascular-adv-004',['Revascularizarea în boala arterială periferică:',
 ['intervențiile iliace au patență primară de 70–90% la 1 an','bypassul aortofemural are patență la 5 ani peste 90%','clopidogrelul cu aspirina se dau cel puțin 6 săptămâni după stentare','endarterectomia este standardul pentru leziunile lungi ale membrului inferior','angioplastia tibială se rezervă riscului chirurgical sau ulcerului'],'ABCE',525,'Tratamentul endovascular și chirurgical',
 'Fixarea rezultatelor revascularizării.',
 ['Intervențiile iliace au 70–90% patență la 1 an.','Bypassul aortofemural are peste 90% la 5 ani.','Dubla antiagregare durează cel puțin 6 săptămâni.','Endarterectomia are utilitate limitată la membrul inferior.','Angioplastia tibială se rezervă riscului chirurgical sau ulcerului.']],
 [8,'Distractorii extind indicațiile.'],['70-90%','6 săptămâni']),

q('vascular-adv-056',['Endarterectomia femurală în boala arterială periferică:',
 ['este rar indicată în boala aorto-iliacă izolată','îmbunătățește fluxul unui bypass aortofemural','se asociază în procedurile hibride cu stentarea iliacă','reduce invazivitatea intervenției în abordarea hibridă','înlocuiește de principiu bypassul în boala infrainghinală'],'ABCD',525,'Managementul chirurgical',
 'Recunoașterea rolului endarterectomiei femurale.',
 ['Puțini pacienți aorto-iliaci sunt candidați.','Endarterectomia locală îmbunătățește fluxul protezei.','Este tot mai importantă în procedurile hibride.','Abordarea hibridă este mult mai puțin invazivă.','Bypassul rămâne principalul tratament chirurgical.']],
 [8,'Singurul distractor contrazice rolul bypassului.'],['hibridă','femurale profunde']),

q('vascular-adv-059',['Bypassul aortofemural:',
 ['descarcă prin artera femurală profundă când AFS este ocluzată','se ocluzează de obicei prin progresia bolii distale','este o procedură durabilă','descarcă prin AFS chiar când aceasta este ocluzată','se ocluzează de obicei prin infecția protezei'],'ABC',525,'Managementul chirurgical — Bypassul aortofemural',
 'Recunoașterea mecanismelor de patență și eșec.',
 ['AFP este vasul principal de descărcare.','Progresia bolii distale limitează descărcarea.','Patența la 5 ani depășește 90%.','Descărcarea se face prin AFP.','Cauza obișnuită este progresia distală.']],
 [8,'Distractorii schimbă vasul și cauza ocluziei.'],['vasul principal de descărcare','progresia bolii']),

q('vascular-adv-016',['Bypassurile extra-anatomice:',
 ['se folosesc în abdomenul ostil','includ bypassul axilo-femural și femuro-femural','impun de regulă anestezie generală profundă','au patență mai mare decât bypassul aortofemural','se tunelizează retroperitoneal'],'AB',525,'Managementul chirurgical — Extra-anatomic',
 'Aplicarea indicațiilor bypassului extra-anatomic.',
 ['Se folosesc în abdomenul ostil.','Includ axilo-femural și femuro-femural.','Nu: la pacienții critici se pot face sub anestezie locală cu sedare.','Patența este mai redusă.','Protezele se tunelizează subcutanat.']],
 [8,'Distractorii inversează patența și traseul.'],['extra-anatomice','anestezie locală']),

q('vascular-adv-057',['Profundoplastia cu endarterectomie femurală:',
 ['poate ameliora durerea ischemică de repaus','scade perfuzia prin colateralele AFP','este insuficientă singură în gangrenă','vindecă singură majoritatea ulcerațiilor','înlocuiește bypassul în leziunile tisulare'],'AC',525,'Managementul chirurgical — Profundoplastia',
 'Aplicarea indicațiilor profundoplastiei.',
 ['Poate ameliora majoritatea simptomelor de repaus.','Nu: profundoplastia crește perfuzia prin colaterale.','La gangrenă este necesar un bypass.','Este puțin probabil să vindece ulcerațiile.','Leziunile tisulare impun bypass.']],
 [8,'Distractorii supraestimează profundoplastia.'],['profundoplastie','colaterale']),

q('vascular-adv-017',['Bypassul infrainghinal:',
 ['deasupra genunchiului, vena și proteza au rezultate inițiale comparabile','sub genunchi, se preferă grefonul venos autolog','in situ, valvele safenei se distrug cu valvulotomul','sub genunchi, proteza sintetică este superioară venei','inversat, safena păstrează valvele contra fluxului'],'ABC',526,'Managementul chirurgical — Bypassul infrainghinal',
 'Alegerea grefonului în bypassul infrainghinal.',
 ['Deasupra genunchiului rezultatele inițiale sunt comparabile.','Sub genunchi, vena autologă este preferată.','Valvulotomul distruge valvele în tehnica in situ.','Protezele funcționează mai slab sub genunchi.','Inversarea aliniază valvele cu fluxul.']],
 [8,'Distractorii inversează superioritatea și orientarea.'],['valvulotom','venos autolog'],[525]),

q('vascular-adv-031',['Conform Tabelului 26-3, patența primară la 2 ani:',
 ['femuro-popliteu deasupra genunchiului, PTFE: 75%','femuro-popliteu sub genunchi, PTFE: 60%','femuro-tibial, PTFE: 30%','femuro-tibial, venă: 30%','femuro-popliteu deasupra genunchiului, PTFE: 30%'],'ABC',526,'Tabelul 26-3',
 'Compararea patenței grefoanelor infrainghinale.',
 ['PTFE deasupra genunchiului: 75%.','PTFE sub genunchi: 60%.','PTFE femuro-tibial: 30%.','Vena femuro-tibială: 70–75%.','PTFE deasupra genunchiului: 75%.']],
 [8,'Distractorii permută valorile între grefoane.'],['PTFE','femuro-tibial']),

q('vascular-adv-032',['Alternativele de grefon când safena ipsilaterală lipsește:',
 ['safena contralaterală, cu precauție','venele cefalice și bazilice unite cap la cap','proteza sintetică cu manșetă venoasă distală','criovena, cu patență superioară venei autologe','vena femurală profundă ipsilaterală'],'ABC',526,'Managementul chirurgical — Grefoanele',
 'Alegerea grefonului alternativ.',
 ['Safena contralaterală se folosește cu precauție.','Venele membrului superior pot fi unite.','Petecul sau manșeta venoasă îmbunătățesc anastomoza.','Patența criovenei este mult mai redusă.','Nu este alternativa citată.']],
 [8,'Distractorii supraestimează criovena.'],['cefalice','criovena']),

q('vascular-adv-033',['Urmărirea Doppler a bypassului safenian:',
 ['nu poate detecta stenozele anastomotice','permite patență asistată de ~90% la 2 ani','arată patență de ~30% dacă stenoza evoluează spre ocluzie','arată patență asistată de ~30% la 2 ani','face angioplastia stenozelor inutilă'],'BC',526,'Urmărirea bypassului',
 'Aplicarea supravegherii Doppler a grefoanelor.',
 ['Nu: Doppler identifică stenozele anastomotice și ale grefonului.','Patența asistată se apropie de 90%.','Stenoza lăsată să ocludă duce la 30%.','Patența asistată este ~90%.','Corecția prin angioplastie crește patența.']],
 [8,'Distractorii permută valorile.'],['asistate','30%']),

q('vascular-adv-058',['Complicațiile imediate ale bypassului arterial includ:',
 ['sângerarea anastomotică','tromboza grefonului','limfocelul','complicațiile cardiopulmonare','hiperperfuzia cerebrală'],'ABCD',526,'Managementul chirurgical — Complicații',
 'Recunoașterea complicațiilor imediate ale bypassului.',
 ['Sângerarea anastomotică este citată.','Tromboza grefonului este citată.','Limforagia produce limfocel.','Pacienții au frecvent boală coronariană sau BPOC.','Nu este complicația citată.']],
 [8,'Singurul distractor nu este citat.'],['limfocel','cardiopulmonare']),

q('vascular-adv-060',['Alegerea revascularizării la membrele inferioare:',
 ['claudicația se tratează inițial prin stop fumat și exercițiu','terapia endovasculară poate fi prima linie la claudicant','bypassul este adesea cea mai bună opțiune în gangrenă','bypassul deschis este prima linie în claudicația ușoară','tehnicile endovasculare se folosesc la riscul chirurgical ridicat'],'ABCE',527,'Managementul chirurgical — Individualizarea',
 'Aplicarea algoritmului de revascularizare.',
 ['Modificarea factorilor de risc tratează adecvat claudicația.','Endovascularul poate fi prima linie.','La durere de repaus sau gangrenă bypassul este adesea preferat.','Intervențiile se justifică doar la simptome debilitante.','Tehnicile endovasculare se folosesc la pacienții cu risc chirurgical ridicat.']],
 [8,'Distractorii inversează indicațiile.'],['renunţarea la fumat','gangrena']),

q('vascular-adv-034',['Nivelul amputației:',
 ['amputațiile distale au potențial de reabilitare mai bun','păstrarea genunchiului crește energia necesară deplasării','amputația de coapsă se indică la gangrena extinsă la genunchi','amputația de coapsă are cel mai bun potențial de reabilitare','amputația Syme se face la nivelul genunchiului'],'AC',527,'Amputația',
 'Alegerea nivelului amputației.',
 ['Cu cât e mai distală, cu atât reabilitarea e mai bună.','Nu: păstrarea genunchiului reduce energia necesară; proteza de coapsă cere mult mai multă.','Coapsa se indică la ischemie profundă cu gangrenă până la genunchi.','Reabilitarea este mai slabă.','Syme este la nivelul gleznei.']],
 [8,'Distractorii inversează reabilitarea și nivelul Syme.'],['Syme','genunchiului']),

q('vascular-adv-005',['Ischemia mezenterică cronică:',
 ['devine simptomatică frecvent când 2 din 3 artere viscerale sunt obstruate','produce durere postprandială în prima oră după masă','produce scădere ponderală prin frica de alimentație','este produsă de obicei de stenoza izolată a unui singur vas visceral','produce durere în cadranul inferior drept la efort'],'ABC',527,'Ischemia mezenterică cronică',
 'Recunoașterea fiziopatologiei și tabloului clinic.',
 ['Simptomatologia e frecventă când 2 vase sunt obstruate.','Durerea apare de obicei în prima oră după masă.','Frica de a mânca produce scădere ponderală.','Colateralele compensează un singur vas.','Nu este prezentarea citată.']],
 [8,'Distractorii ignoră colateralele.'],['prima oră','frica de a se alimenta']),

q('vascular-adv-061',['Diagnosticul ischemiei mezenterice cronice:',
 ['ecografia Doppler evidențiază stenozele de la emergența vaselor','ecografia Doppler este limitată de aerocolie și calcificări','angio-CT și angio-RM sunt cele mai indicate','angiografia se folosește pentru intervenții','ecografia Doppler este superioară angio-CT'],'ABCD',527,'Ischemia mezenterică cronică — Diagnostic',
 'Alegerea investigațiilor în ischemia mezenterică cronică.',
 ['Doppler evaluează fluxul și stenozele de la emergență.','Aerocolia și calcificările limitează Doppler.','Angio-CT și angio-RM sunt cele mai indicate.','Angiografia se folosește pentru intervenții.','Angio-CT este mai indicat.']],
 [8,'Singurul distractor inversează ierarhia.'],['aerocoliei','Angiografia este folosită pentru intervenţii']),

q('vascular-adv-062',['Revascularizarea în ischemia mezenterică cronică:',
 ['angioplastia are morbiditate imediată mai mică decât bypassul','bypassul are patență la 3 ani de peste 90%','se revascularizează de rutină cel puțin două vase','angioplastia are patență superioară bypassului','grefa venoasă autologă se folosește la risc infecțios'],'ABCE',527,'Ischemia mezenterică cronică — Tratament',
 'Aplicarea opțiunilor de revascularizare mezenterică.',
 ['Morbiditatea imediată a angioplastiei este mult redusă.','Bypassul are peste 90% la 3 ani, față de ~70% pentru PTA.','Chirurgii experimentați revascularizează cel puțin două vase.','Patența PTA este mai mică.','Vena autologă se folosește la risc infecțios.']],
 [8,'Distractorii inversează patența și indicația venei.'],['două vase viscerale','risc crescut de infecţie']),

q('vascular-adv-006',['Sindromul de furt subclavicular:',
 ['inversează fluxul în artera carotidă internă la efortul brațului','este de 3–4 ori mai frecvent pe stânga','scade TA brahială ipsilaterală cu cel puțin 15 mmHg','este mai frecvent pe dreapta','scade TA brahială ipsilaterală cu sub 5 mmHg'],'BC',534,'Boala vertebro-bazilară',
 'Recunoașterea sindromului de furt subclavicular.',
 ['Nu: efortul brațului inversează fluxul în artera vertebrală.','Subclaviculara stângă, mai lungă, e afectată de 3–4 ori mai des.','TA brahială ipsilaterală scade cu cel puțin 15 mmHg.','Este mai frecvent pe stânga.','Scăderea este de cel puțin 15 mmHg.']],
 [8,'Distractorii inversează lateralitatea și gradientul.'],['furt subclavicular','15 mmHg']),

q('vascular-adv-019',['Epidemiologia bolii venoase:',
 ['aproximativ 40% dintre adulți vor avea o formă de boală venoasă','probabilitatea unui ulcer venos în viață este de ~6%','70% dintre adulții peste 70 de ani au boală venoasă cronică','probabilitatea unui ulcer venos în viață este de ~40%','boala venoasă scade în frecvență cu vârsta'],'ABC',534,'Bolile venelor',
 'Fixarea epidemiologiei bolii venoase.',
 ['Aproximativ 40% dintre adulți vor avea boală venoasă.','Probabilitatea ulcerului este de 6%.','70% peste 70 de ani au boală venoasă cronică.','Probabilitatea este de 6%.','Incidența crește cu vârsta.']],
 [8,'Distractorii permută cifrele și direcția.'],['40% dintre','6%']),

q('vascular-adv-063',['Sistemul venos:',
 ['sistemul central include venele cave, iliace și subclaviculare','valvele venoase sunt bicuspide','perforantele dirijează sângele din superficial spre profund','valvele permit refluxul spre periferie în ortostatism','perforantele dirijează sângele din profund spre superficial'],'ABC',534,'Bolile venelor — Anatomie',
 'Recunoașterea organizării sistemului venos.',
 ['Sistemul central include venele cave, iliace și subclaviculare.','Valvele sunt bicuspide.','Perforantele dirijează sângele spre profund.','Valvele previn refluxul.','Direcția normală este spre profund.']],
 [8,'Distractorii inversează direcția fluxului.'],['bicuspide','subclaviculare']),

q('vascular-adv-020',['Anatomia venelor membrului inferior:',
 ['venele tibiale și peroniere sunt de regulă pereche','gamba are șase vene profunde principale','safena mare și safena mică aparțin sistemului superficial','gamba are trei vene profunde principale','safena mare aparține sistemului venos profund'],'ABC',534,'Bolile venelor — Anatomie',
 'Recunoașterea anatomiei venoase profunde și superficiale.',
 ['Venele tibiale și peroniere sunt pereche.','Gamba are șase vene profunde principale.','Safenele sunt superficiale.','Gamba are șase vene, față de trei artere.','Safena mare este superficială.']],
 [8,'Distractorii confundă venele cu arterele.'],['pereche','şase vene']),

q('vascular-adv-018',['Vena „femurală superficială” a fost redenumită „femurală” pentru a:',
 ['sublinia riscul embolic al trombozei ei','sublinia că este o venă superficială','o alinia cu nomenclatura arterei femurale profunde','o exclude din definiția trombozei venoase profunde','justifica stripping-ul ei de rutină'],'A',534,'Bolile venelor — Anatomie',
 'Înțelegerea motivului redenumirii venei femurale.',
 ['Redenumirea evită confuzia și subliniază riscul de embolie.','Este o venă profundă.','Nu este motivul citat.','Tromboza ei este TVP.','Nu este motivul citat.']],
 [8,'Distractorii contrazic natura profundă a venei.'],['redenumită','embolie pulmonară']),

q('vascular-adv-021',['Fiziopatologia bolii venoase:',
 ['triada Virchow include staza, leziunea endotelială și hipercoagulabilitatea','traumatismele membrelor sunt o cauză frecventă de TVP','lipodermatoscleroza este stadiul final al hipertensiunii venoase','venele superficiale beneficiază de pompa musculară','lipodermatoscleroza apare predominant la membrul superior'],'ABC',535,'Bolile venelor — Fiziopatologie',
 'Explicarea mecanismelor bolii venoase.',
 ['Virchow: stază, leziune endotelială, hipercoagulabilitate.','Traumatismele sunt o cauză frecventă.','Lipodermatoscleroza este rezultatul final.','Venele superficiale nu au compartimente musculare.','Apare la gambă, unde presiunea este maximă.']],
 [8,'Distractorii inversează rolul pompei și localizarea.'],['Virchow','lipodermatoscleroza']),

q('vascular-adv-036',['Tromboza venoasă superficială:',
 ['se tratează cu antiinflamatoare nesteroidiene','se tratează cu comprese calde','poate beneficia de LMWH timp de 4–6 săptămâni','se tratează cu warfarină, cu INR țintă de 4–5','contraindică excizia chirurgicală a trombului'],'ABC',536,'Tromboza venoasă superficială',
 'Aplicarea tratamentului tromboflebitei superficiale.',
 ['AINS sunt citate.','Compresele calde sunt citate.','LMWH se pot folosi 4–6 săptămâni.','Nu este tratamentul citat.','Excizia trombului ameliorează imediat durerea.']],
 [8,'Distractorii contrazic conduita citată.'],['comprese calde','4-6 săptămâni'],[535]),

q('vascular-adv-035',['Tromboza venoasă profundă:',
 ['afectează aproximativ 900.000 de pacienți pe an','are mortalitate în spital peste 10% dacă apare embolia pulmonară','este asimptomatică în aproape 50% din cazurile intraspitalicești','este asimptomatică în sub 5% din cazurile intraspitalicești','are mortalitate în spital sub 1% după embolie pulmonară'],'ABC',536,'Tromboza venoasă profundă',
 'Fixarea epidemiologiei TVP.',
 ['Aproximativ 900.000 de pacienți pe an.','Mortalitatea depășește 10% după EP.','Aproape 50% sunt asimptomatice.','Proporția este de aproape 50%.','Mortalitatea depășește 10%.']],
 [8,'Distractorii subestimează asimptomaticii și mortalitatea.'],['900.000','10%']),

q('vascular-adv-037',['Diagnosticul TVP de membru inferior:',
 ['TVP iliacă stângă este mai frecventă prin sindromul May-Thurner','semnul Homan este prezent în sub 50% din cazuri','ecografia Doppler are sensibilitate peste 95%','D-dimerii pozitivi trebuie urmați de ecografie','semnul Homan este prezent în peste 90% din cazuri'],'ABCD',537,'Tromboza venoasă profundă — Diagnostic',
 'Aplicarea investigațiilor în TVP.',
 ['May-Thurner explică predominanța iliacă stângă.','Homan este prezent în sub 50%.','Sensibilitatea Doppler este >95%.','D-dimerii sunt sensibili, dar nespecifici.','Homan este prezent în sub 50%.']],
 [8,'Singurul distractor supraestimează semnul Homan.'],['May-Thurner','>95%']),

q('vascular-adv-064',['Ecografia Doppler în TVP:',
 ['fluxul venos scade normal în inspir','acuratețea este redusă la venele tibiale','arată pierderea augmentării la compresia distală','fluxul venos crește normal în inspir','acuratețea este maximă la venele tibiale'],'ABC',537,'Tromboza venoasă profundă — Diagnostic',
 'Interpretarea ecografiei Doppler venoase.',
 ['Presiunea abdominală crescută în inspir scade fluxul.','Venele tibiale mici sunt greu de vizualizat.','Doppler documentează pierderea augmentării.','Fluxul scade în inspir.','Acuratețea tibială este redusă.']],
 [8,'Distractorii inversează fiziologia și acuratețea.'],['inspiraţia','venelor tibiale']),

q('vascular-adv-038',['La TVP spontană (idiopatică), evaluarea hipercoagulabilității include:',
 ['proteina C, proteina S și antitrombina III','D-dimerii și fibrinogenul seric','grupul sanguin ABO și factorul Rh','timpul de sângerare și numărul de trombocite','feritina și saturația transferinei'],'A',537,'Tromboza venoasă profundă — Hipercoagulabilitatea',
 'Alegerea panelului de trombofilie.',
 ['Panelul include și factorul V Leiden, mutația protrombinei și anticorpii anticardiolipină.','Nu evaluează trombofilia.','Nu este citat.','Nu este citat.','Nu este citat.']],
 [8,'Distractorii sunt teste incomplete sau necitate.'],['anticardiolipină','idiopatică']),

q('vascular-adv-065',['Profilaxia TVP perioperatorii:',
 ['include dispozitive de compresie intermitentă','include mobilizarea precoce','include heparina subcutanat sau warfarina','se intensifică la vârstnici și la pacienții cu cancer','se evită la pacienții cu cancer'],'ABCD',538,'Tromboza venoasă profundă — Profilaxie',
 'Aplicarea profilaxiei TVP.',
 ['Compresia segmentară intermitentă este măsură mecanică.','Mobilizarea precoce este citată.','Heparina subcutanat sau warfarina sunt citate.','Vârstnicii, procedurile lungi, TVP anterioară și cancerul cresc riscul.','Cancerul crește riscul.']],
 [8,'Singurul distractor inversează riscul oncologic.'],['compresie segmentară','cancer']),

q('vascular-adv-039',['Anticoagularea clasică a TVP cu heparină și warfarină:',
 ['warfarina se începe după heparinizarea adecvată','ținta INR de întreținere este între 2 și 3','există o fereastră hipercoagulabilă la inițierea warfarinei','heparina se oprește înaintea primei doze de warfarină','proteinele C și S au timp de înjumătățire mai lung'],'ABC',538,'Tromboza venoasă profundă — Tratament',
 'Aplicarea tranziției heparină–warfarină.',
 ['Warfarina se începe după heparinizare.','INR țintă 2–3.','Proteinele C și S scad primele, creând hipercoagulabilitate.','Heparina se menține la începutul warfarinei.','Au timp de înjumătățire mai scurt.']],
 [8,'Distractorii inversează cinetica și tranziția.'],['INR între 2 şi 3','Necroza cutanată']),

q('vascular-adv-046',['Anticoagulantele orale noi, față de warfarină:',
 ['permit anticoagulare imediată, fără heparină','nu necesită monitorizare','au risc de sângerare similar','au toate antidot specific','necesită monitorizarea INR'],'ABC',538,'Tromboza venoasă profundă — Tratament',
 'Compararea anticoagulantelor orale noi cu warfarina.',
 ['Permit anticoagulare imediată.','Biodisponibilitatea stabilă face monitorizarea inutilă.','Riscurile de sângerare sunt similare.','Doar unul are antidot în prezent.','Nu necesită monitorizare.']],
 [8,'Distractorii supraestimează antidoturile.'],['antidot','biodisponibilitate stabilă']),

q('vascular-adv-040',['Reprezintă indicație clară de tromboliză venoasă:',
 ['tromboza venei subclavii','tromboza venelor tibiale asimptomatică','tromboza venei safene mici','TVP distală veche de peste 6 luni','tromboflebita superficială'],'A',538,'Tromboza venoasă profundă — Tromboliza',
 'Recunoașterea indicațiilor clare ale trombolizei venoase.',
 ['Tromboza subclaviei, a venei renale și a VMS sunt indicații clare.','Nu este indicație.','Nu este indicație.','Nu este indicație.','Nu este indicație.']],
 [8,'Distractorii sunt tromboze fără indicație de tromboliză.'],['venei subclavii','venei renale']),

q('vascular-adv-041',['Tromboliza și trombectomia în TVP iliofemurală:',
 ['ACCP recomandă tromboliza la simptome sub 14 zile','trombectomia mecanică are mai puține contraindicații','phlegmasia se tratează primar prin trombectomie mecanică sau tromboliză','trombectomia chirurgicală este tratamentul de primă intenție','ACCP cere speranță de viață sub 1 an'],'ABC',538,'Tromboza venoasă profundă — Tromboliza',
 'Aplicarea criteriilor de tromboliză și trombectomie.',
 ['ACCP: simptome <14 zile, stare bună, speranță de viață >1 an.','Agentul rămâne izolat în vena trombozată.','Phlegmasia se tratează primar prin tehnici endovasculare.','Trombectomia chirurgicală este rară.','Speranța de viață trebuie să fie >1 an.']],
 [8,'Distractorii inversează criteriile.'],['phlegmasia','14 zile']),

q('vascular-adv-022',['Conform Tabelului 26-4, în embolia pulmonară:',
 ['dispneea și tahipneea apar la ~80%','durerea toracică pleuritică apare la ~70%','tahicardia apare la ~45%','hemoptizia apare la ~70%','radiografia arată constant imaginea de pană'],'ABC',539,'Embolia pulmonară — Tabelul 26-4',
 'Fixarea frecvenței manifestărilor EP.',
 ['Dispneea și tahipneea: 80%.','Durerea pleuritică: 70%.','Tahicardia: 45%.','Hemoptizia: 25–30%.','Imaginea de pană este rară.']],
 [8,'Distractorii permută frecvențele.'],['80%','25%-30%']),

q('vascular-adv-023',['Diagnosticul definitiv al emboliei pulmonare se face prin:',
 ['CT toracic','radiografie toracică','D-dimeri','electrocardiogramă','ecografie Doppler venoasă'],'A',539,'Embolia pulmonară — Diagnostic',
 'Alegerea investigației definitive în EP.',
 ['CT, scintigrafia V/Q sau angiografia pulmonară dau diagnosticul definitiv.','Radiografia este rareori diagnostică.','D-dimerii sunt test de screening.','ECG arată disfuncția dreaptă, nu diagnosticul.','Doppler-ul diagnostichează TVP.']],
 [8,'Distractorii sunt investigații reale, nedefinitive.'],['Diagnosticul definitiv','>98%']),

q('vascular-adv-024',['Tratamentul emboliei pulmonare:',
 ['anticoagularea previne noi emboli','tromboliza se ia în calcul la pacientul stabil, dar simptomatic','filtrul cav se folosește la contraindicația anticoagulării','filtrul cav se lasă definitiv','mărimea embolului prezice direct supraviețuirea'],'ABC',539,'Embolia pulmonară — Tratament',
 'Aplicarea tratamentului EP.',
 ['Anticoagularea previne noi emboli și propagarea.','Tromboliza se consideră la stabilul simptomatic.','Filtrul se folosește la contraindicație sau eșec.','Filtrele se îndepărtează când nu mai sunt utile.','Nu există corelație directă.']],
 [8,'Distractorii contrazic recomandările explicite.'],['filtru cav','inotrop']),

q('vascular-adv-025',['Tratamentul varicelor primare:',
 ['sistemul profund asigură 85–90% din întoarcerea venoasă','ligatura safenei are recidivă mai mare decât stripping-ul','ablația cu radiofrecvență se face prin puncție ecoghidată sub genunchi','stripping-ul este tehnica cea mai puțin dureroasă','ablația superficială este contraindicată dacă profundul e patent'],'ABC',540,'Venele varicoase — Tratament',
 'Aplicarea opțiunilor de tratament al varicelor.',
 ['Sistemul profund asigură 85–90% din întoarcere.','Ligatura are recidivă mai mare.','ARF se face prin puncție ecoghidată sub genunchi.','Stripping-ul este mai dureros.','Patența profundului permite ablația.']],
 [8,'Distractorii inversează durerea și indicația.'],['85-90%','ecoghidată'],[539]),

q('vascular-adv-026',['Insuficiența venoasă cronică:',
 ['este consecința hipertensiunii venoase locale','produce edem și hiperpigmentare maleolară','poate duce la lipodermatoscleroză','produce ulcere tipic pe pulpa degetelor','este o arteriopatie a trifurcației'],'ABC',540,'Insuficiența venoasă cronică',
 'Recunoașterea insuficienței venoase cronice.',
 ['Este consecința hipertensiunii venoase locale.','Piciorul este edemațiat și hiperpigmentat maleolar.','Lipodermatoscleroza este stadiul terminal.','Ulcerele apar maleolar.','Este o boală venoasă.']],
 [8,'Distractorii descriu patologia arterială.'],['hipertensiunii venoase','hiperpigmentat']),

q('vascular-adv-066',['Tratamentul insuficienței venoase cronice cu lipodermatoscleroză:',
 ['începe cu ciorapi de contenție elastică','are complianță adesea slabă la ciorapi','folosește la ulcer pansamente compresive din 3–4 straturi','folosește grefă de piele înaintea controlului refluxului','evită pansamentele compresive la ulcer'],'ABC',541,'Insuficiența venoasă cronică — Tratament',
 'Aplicarea tratamentului insuficienței venoase cronice.',
 ['Ciorapii de contenție sunt tratamentul inițial.','Complianța este slabă.','Pansamentele din 3–4 straturi comprimă.','Grefa se face după controlul refluxului și edemului.','Pansamentele compresive sunt recomandate.']],
 [8,'Distractorii inversează ordinea terapeutică.'],['contenţie elastică','trei sau patru']),

q('vascular-adv-042',['Traumatismele vasculare:',
 ['contuzia rezultă frecvent din fracturi de oase lungi','flapul intimal poate tromboza după ore sau zile','pulsul distal poate persista după leziune','pulsul distal prezent exclude o leziune arterială','fistulele arteriovenoase post-traumatice nu produc sufluri'],'ABC',541,'Traumatismele vasculare',
 'Recunoașterea prezentărilor subtile ale traumei vasculare.',
 ['Contuzia se produce cel mai frecvent prin fracturi de oase lungi.','Tromboza pe flap intimal poate fi întârziată.','Pulsul lipsește doar dacă fluxul este restricționat.','Pulsul prezent nu exclude leziunea.','Fistulele se asociază cu triluri sau sufluri.']],
 [8,'Distractorii se bazează pe semne incomplete.'],['flapul intimai','fractura oaselor lungi']),

q('vascular-adv-043',['La suspiciunea de traumatism vascular de extremitate:',
 ['IGB de 1 cu membru viabil face leziunea improbabilă','membrul ischemic impune arteriografie','IGB de 1 permite continuarea evaluării prin Doppler','IGB de 1 impune arteriografie de urgență','membrul ischemic contraindică arteriografia'],'ABC',541,'Traumatismele vasculare — Diagnostic',
 'Aplicarea algoritmului diagnostic în trauma vasculară.',
 ['IGB 1 cu membru viabil face diagnosticul improbabil.','Membrul ischemic impune arteriografie.','Vasele adiacente se examinează prin Doppler și ecografie.','Arteriografia se rezervă membrului ischemic.','Arteriografia este indicată.']],
 [8,'Distractorii inversează indicația arteriografiei.'],['viabilă','arteriografia']),
];
