// Generated by scripts/retire-topic.ts. Frozen copies of published questions that
// were replaced or withdrawn; they keep old attempts and drafts scoreable.
import type {Question} from '../../models';
import {RETIRED_ATI} from './ati';
import {RETIRED_BILIAR} from './biliar';
import {RETIRED_DERMATO} from './dermato';
import {RETIRED_ENDOCRINOLOGIE} from './endocrinologie';
import {RETIRED_EPIDEMIO} from './epidemio';
import {RETIRED_ESOFAG} from './esofag';
import {RETIRED_FICAT_SPLINA} from './ficat-splina';
import {RETIRED_HEMATOLOGIE} from './hematologie';
import {RETIRED_HEMOSTAZA} from './hemostaza';
import {RETIRED_HERNII} from './hernii';
import {RETIRED_HTA} from './hta';
import {RETIRED_INFECTII_CHIR} from './infectii-chir';
import {RETIRED_INTESTIN} from './intestin';
import {RETIRED_PERIOPERATOR} from './perioperator';
import {RETIRED_PSIHIATRIE} from './psihiatrie';
import {RETIRED_REUMATOLOGIE} from './reumatologie';
import {RETIRED_SEPSIS} from './sepsis';
import {RETIRED_STOMAC} from './stomac';
import {RETIRED_TRAUMA} from './trauma';
import {RETIRED_TROMBOEMBOLISM} from './tromboembolism';
import {RETIRED_VASCULAR} from './vascular';

export const RETIRED_QUESTIONS:Question[]=[...RETIRED_ATI,...RETIRED_BILIAR,...RETIRED_DERMATO,...RETIRED_ENDOCRINOLOGIE,...RETIRED_EPIDEMIO,...RETIRED_ESOFAG,...RETIRED_FICAT_SPLINA,...RETIRED_HEMATOLOGIE,...RETIRED_HEMOSTAZA,...RETIRED_HERNII,...RETIRED_HTA,...RETIRED_INFECTII_CHIR,...RETIRED_INTESTIN,...RETIRED_PERIOPERATOR,...RETIRED_PSIHIATRIE,...RETIRED_REUMATOLOGIE,...RETIRED_SEPSIS,...RETIRED_STOMAC,...RETIRED_TRAUMA,...RETIRED_TROMBOEMBOLISM,...RETIRED_VASCULAR];
