// Generated by scripts/retire-topic.ts. Frozen copies of published questions that
// were replaced or withdrawn; they keep old attempts and drafts scoreable.
import type {Question} from '../../models';
import {RETIRED_ESOFAG} from './esofag';
import {RETIRED_HEMOSTAZA} from './hemostaza';
import {RETIRED_HERNII} from './hernii';
import {RETIRED_SEPSIS} from './sepsis';

export const RETIRED_QUESTIONS:Question[]=[...RETIRED_ESOFAG,...RETIRED_HEMOSTAZA,...RETIRED_HERNII,...RETIRED_SEPSIS];
