// Generated by scripts/retire-topic.ts. Frozen copies of published questions that
// were replaced or withdrawn; they keep old attempts and drafts scoreable.
import type {Question} from '../../models';

export const RETIRED_QUESTIONS:Question[]=[];
