import {Component,computed,inject} from '@angular/core';
import {RouterLink} from '@angular/router';
import {Store} from './store';
import {QUESTIONS,QUESTION_HISTORY} from './questions';
import {TOPICS} from './topics';
import {improvement,summarize,topicStats,wrongIds} from './scoring';
import {IconComponent} from './icon.component';
import {ChartComponent} from './chart.component';
@Component({standalone:true,imports:[RouterLink,IconComponent,ChartComponent],template:`
<div class="page-heading"><div><div class="eyebrow">FIECARE ZI CONTEAZĂ</div><h1>Pregătirea ta, în progres<span class="serif-dot">.</span></h1><p>Un loc pentru tot ce înveți. O direcție clară pentru ce urmează.</p></div><a class="button primary" routerLink="/teste"><app-icon name="book"/>Începe un test<app-icon name="arrow"/></a></div>
@if(store.draft()){<div class="notice"><span>Ai un test în desfășurare, salvat pe acest dispozitiv.</span><a routerLink="/test">Continuă testul →</a></div>}
<section class="hero"><div class="hero-copy"><span class="hero-label"><span class="status-dot"></span> REZIDENȚIAT 2026 · MEDICINĂ</span><h2>Viitorul tău începe<br>cu întrebarea de azi.</h2><p>Exersează cu sens. Înțelege unde greșești.<br>Construiește încredere, pas cu pas.</p><a class="button lime" routerLink="/teste">Hai să exersăm<app-icon name="arrow"/></a><div class="hero-meta">{{count}} grile originale <span>·</span> {{topics.length}} capitole <span>·</span> 3 volume</div></div><div class="hero-art" aria-hidden="true"><div class="orbit orbit-one"></div><div class="orbit orbit-two"></div><div class="orbit orbit-three"></div><div class="floating-note"><span class="note-check">✓</span><span>Încă un pas<br><strong>spre halatul alb.</strong></span></div><svg class="hero-plant" viewBox="0 0 270 290"><path d="M130 260C125 186 169 120 166 45" fill="none" stroke="#cfe4b6" stroke-width="3"/><path d="M141 181C77 186 65 135 78 104c49 1 74 32 63 77z" fill="#acc88d"/><path d="M151 150c-8-59 28-93 65-83 5 46-13 76-65 83z" fill="#d5e7b7"/><path d="M129 231c-58 3-88-24-87-64 56-6 81 22 87 64z" fill="#638b62"/><path d="M135 216c12-51 45-66 83-50-2 43-36 58-83 50z" fill="#98b987"/><path d="M165 94c-33-23-42-55-18-80 30 15 37 43 18 80z" fill="#c3dba4"/><path d="M88 262h92l-13 24h-66z" fill="#e3d8c0"/></svg><span class="art-spark one">✧</span><span class="art-spark two">✧</span><div class="countdown"><strong>{{days}}</strong><span>{{days===1?'zi rămasă':'zile rămase'}}<br>până la examen</span></div></div></section>
<section class="stats-grid" aria-label="Statisticile tale"><article class="stat"><span class="stat-icon mint"><app-icon name="book"/></span><div><span>Grile rezolvate</span><strong>{{summary().answered}}<small> / {{summary().total}} în teste</small></strong><small>{{store.attempts().length}} sesiuni finalizate</small></div></article><article class="stat"><span class="stat-icon peach"><app-icon name="target"/></span><div><span>Punctaj cumulat</span><strong>{{summary().max?summary().percent+'%':'—'}}</strong><small>{{summary().max?summary().points+' din '+summary().max+' puncte':'Începe pentru a-ți vedea scorul'}}</small></div></article><article class="stat"><span class="stat-icon lavender"><app-icon name="chart"/></span><div><span>Evoluție săptămânală</span><strong>{{delta()===null?'—':(delta()!>0?'+':'')+delta()+' pp'}}</strong><small>Ultimele 7 zile vs. cele precedente</small></div></article><article class="stat"><span class="stat-icon sand"><app-icon name="refresh"/></span><div><span>De recapitulat</span><strong>{{wrong().length}}<small> grile</small></strong><small>După cel mai recent răspuns</small></div></article></section>
<div class="dashboard-columns"><section class="panel"><div class="section-heading"><div><h3>Cum evoluezi</h3><p>Procentul de puncte obținute la ultimele sesiuni</p></div><a routerLink="/progres" class="text-link">Vezi progresul <span>↗</span></a></div><app-trend [points]="points()"/><div class="chart-legend"><span class="status-dot"></span>Punctajul tău <span class="muted">Fiecare test este un nou reper.</span></div></section><section class="panel focus-panel"><div class="section-heading"><div><span class="eyebrow">URMĂTORUL PAS</span><h3>{{weakest()?'Aici merită să revii':'Găsește-ți ritmul'}}</h3></div><app-icon name="spark"/></div>@if(weakest();as t){<p>Capitolul cu cel mai mic punctaj dintre cele exersate:</p><h2>{{t.name}}</h2><span class="badge peach">{{t.percent}}% din punctaj · {{t.total}} grile</span><p>Începe cu întrebările care încă îți dau de gândit.</p><a class="button secondary full" routerLink="/teste" [queryParams]="{topic:t.id}">Exersează capitolul<app-icon name="arrow"/></a>}@else{<span class="focus-symbol"><app-icon name="target"/></span><h2>20 de grile.<br>Un început bun.</h2><p>După primul test, îți arătăm capitolele care au nevoie de mai multă atenție.</p><a class="button secondary full" routerLink="/teste">Alege un antrenament<app-icon name="arrow"/></a>}</section></div>
<div class="section-heading lower-heading"><div><h3>Învață pe capitole</h3><p>Alege unde vrei să faci următorul pas.</p></div><a routerLink="/teste" class="text-link">Toate capitolele →</a></div><div class="topic-preview">@for(t of featured;track t.id){<a class="topic-card" routerLink="/teste" [queryParams]="{topic:t.id}"><span class="topic-icon" [class.peach]="$index===1" [class.lavender]="$index===2"><app-icon [name]="$index===0?'heart':$index===1?'book':'leaf'"/></span><div><small>{{t.book}}</small><h3>{{t.name}}</h3><span>{{questionCount(t.id)}} grile disponibile</span></div><app-icon name="chevron"/></a>}</div>
`})
export class DashboardComponent {store=inject(Store);topics=TOPICS;count=QUESTIONS.length;days=Math.max(0,Math.ceil((new Date('2026-11-15T00:00:00+02:00').getTime()-Date.now())/86400000));summary=computed(()=>summarize(this.store.attempts().flatMap(a=>a.answers),QUESTION_HISTORY));delta=computed(()=>improvement(this.store.attempts(),QUESTION_HISTORY));wrong=computed(()=>wrongIds(this.store.attempts(),QUESTIONS));points=computed(()=>[...this.store.attempts()].sort((a,b)=>a.completedAt.localeCompare(b.completedAt)).slice(-10).map(a=>({value:summarize(a.answers,QUESTION_HISTORY).percent,label:new Date(a.completedAt).toLocaleDateString('ro-RO',{day:'numeric',month:'short'})})));weakest=computed(()=>TOPICS.map(t=>({...t,...topicStats(this.store.attempts(),QUESTION_HISTORY,t.id)})).filter(t=>t.total>0).sort((a,b)=>a.percent-b.percent)[0]);featured=TOPICS.filter(t=>['cardiologie','ortopedie','pediatrie'].includes(t.id));questionCount(id:string){return QUESTIONS.filter(q=>q.topicId===id).length;}}
