import {Component,computed,inject,signal} from '@angular/core';
import {FormsModule} from '@angular/forms';
import {ActivatedRoute,Router,RouterLink} from '@angular/router';
import {Store} from './store';
import {TOPICS} from './topics';
import {QUESTIONS} from './questions';
import {examQuestions,shuffled,wrongIds} from './scoring';
import {IconComponent} from './icon.component';
@Component({standalone:true,imports:[FormsModule,RouterLink,IconComponent],template:`<div class="page-heading"><div><div class="eyebrow">ANTRENAMENT CU DIRECȚIE</div><h1>Un test pe ritmul tău.</h1><p>Alege capitolele, rezolvă grilele și înțelege fiecare răspuns.</p></div></div>
@if(store.draft()){<div class="notice"><span>Ai deja un test în desfășurare. Continuă-l sau finalizează-l înainte de a începe altul.</span><a routerLink="/test">Continuă →</a></div>}
<div class="mode-grid"><button class="mode-card" [class.selected]="mode()==='practice'" (click)="mode.set('practice')"><span class="stat-icon mint"><app-icon name="book"/></span><span><strong>Antrenament</strong><small>Explicații după fiecare răspuns. Înveți în ritmul tău.</small></span><span class="radio-dot"></span></button><button class="mode-card" [class.selected]="mode()==='exam'" (click)="mode.set('exam')"><span class="stat-icon peach"><app-icon name="clock"/></span><span><strong>Simulare de examen</strong><small>200 de grile · 4 ore · maximum 950 de puncte</small></span><span class="radio-dot"></span></button></div>
<div class="setup-layout"><section class="panel">@if(mode()==='practice'){<div class="section-heading"><div><h3>Ce vrei să exersezi?</h3><p>Selectează unul sau mai multe capitole.</p></div><button class="text-link" (click)="selected.set(selected().length===topics.length?[]:topics.map(topicId))">{{selected().length===topics.length?'Deselectează':'Selectează tot'}}</button></div><label class="search-input"><app-icon name="search"/><input aria-label="Caută un capitol" placeholder="Caută un capitol…" [ngModel]="search()" (ngModelChange)="search.set($event)"></label><div class="book-tabs">@for(b of books;track b){<button [class.active]="book()===b" (click)="book.set(b)">{{b}}</button>}</div><div class="chapter-list">@for(t of visibleTopics();track t.id){<label class="chapter-option"><input type="checkbox" [checked]="selected().includes(t.id)" (change)="toggle(t.id)"><span><strong>{{t.name}}</strong><small>{{t.book}} · Cap. {{t.chapter}}</small></span><span class="count">{{countFor(t.id)}} grile</span></label>}@empty{<p class="empty-inline">Niciun capitol nu corespunde căutării.</p>}</div>}@else{<span class="eyebrow">CONCENTRARE. RĂBDARE. ÎNCREDERE.</span><h2>Exersează formatul<br>concursului național.</h2><p class="lead">O sesiune completă, cu întrebări originale din toate cele trei volume.</p><div class="exam-rules"><div><strong>50</strong><span>complement simplu<br>4 puncte / grilă</span></div><div><strong>150</strong><span>complement multiplu<br>5 puncte / grilă</span></div><div><strong>4h</strong><span>timp de lucru<br>fără pauză de cronometru</span></div></div><p>Poți reveni la orice întrebare și poți marca grilele pentru revizuire. Rezultatul și explicațiile se afișează după predare.</p><div class="notice">Format și punctaj după metodologia anilor anteriori. Banca este de antrenament și nu reproduce un caiet oficial; dificultatea nu este calibrată față de concurs.</div>}</section>
<aside class="panel setup-summary"><span class="eyebrow">SESIUNEA TA</span><h3>{{mode()==='exam'?'Simulare completă':'Antrenament personalizat'}}</h3>@if(mode()==='practice'){<label class="field-label">Număr de grile<select [(ngModel)]="count"><option [ngValue]="10">10 grile</option><option [ngValue]="20">20 de grile</option><option [ngValue]="40">40 de grile</option><option [ngValue]="80">80 de grile</option></select></label><label class="check-line"><input type="checkbox" [ngModel]="onlyWrong()" (ngModelChange)="onlyWrong.set($event)">Doar grile de recapitulat</label><div class="summary-row"><span>Capitole selectate</span><strong>{{selected().length}}</strong></div><div class="summary-row"><span>Grile disponibile</span><strong>{{pool().length}}</strong></div><div class="summary-row"><span>În acest test</span><strong>{{actualCount()}}</strong></div><p class="small muted">Dacă un capitol are mai puține grile, testul include doar întrebările disponibile, fără repetări.</p>}@else{<div class="summary-row"><span>Grile distincte</span><strong>200</strong></div><div class="summary-row"><span>Punctaj maxim</span><strong>950</strong></div><div class="summary-row"><span>Durată</span><strong>240 min</strong></div>}<button class="button primary full" (click)="start()" [disabled]="!!store.draft()||!store.ready()||(mode()==='practice'&&!actualCount())">Începe {{mode()==='exam'?'simularea':'antrenamentul'}}<app-icon name="arrow"/></button>@if(error()){<p class="error" role="alert">{{error()}}</p>}<p class="small muted">{{store.user()?'Rezultatele finalizate se sincronizează în contul tău.':'Exersezi ca vizitator. Rezultatele se păstrează doar în acest browser.'}}</p>@if(!store.user()){<a routerLink="/cont" class="text-link">Conectează-te pentru sincronizare →</a>}</aside></div>`})
export class PracticeComponent {store=inject(Store);router=inject(Router);route=inject(ActivatedRoute);topics=TOPICS;books=['Toate','Kumar & Clark','Lawrence','Sinopsis'];book=signal('Toate');search=signal('');mode=signal<'practice'|'exam'>('practice');selected=signal<string[]>(TOPICS.map(t=>t.id));onlyWrong=signal(false);count=20;error=signal('');topicId=(t:typeof TOPICS[number])=>t.id;
 constructor(){const t=this.route.snapshot.queryParamMap.get('topic');if(t&&TOPICS.some(x=>x.id===t))this.selected.set([t]);if(this.route.snapshot.queryParamMap.get('wrong'))this.onlyWrong.set(true);}
 visibleTopics=computed(()=>TOPICS.filter(t=>(this.book()==='Toate'||t.book===this.book())&&t.name.toLocaleLowerCase('ro').normalize('NFD').replace(/\p{Diacritic}/gu,'').includes(this.search().toLocaleLowerCase('ro').normalize('NFD').replace(/\p{Diacritic}/gu,''))));
 pool=computed(()=>{const wrong=wrongIds(this.store.attempts(),QUESTIONS);return QUESTIONS.filter(q=>this.selected().includes(q.topicId)&&(!this.onlyWrong()||wrong.includes(q.id)));});actualCount(){return Math.min(this.count,this.pool().length);}countFor(id:string){return QUESTIONS.filter(q=>q.topicId===id).length;}toggle(id:string){this.selected.update(a=>a.includes(id)?a.filter(x=>x!==id):[...a,id]);}
 start(){try{const qs=this.mode()==='exam'?examQuestions(QUESTIONS):shuffled(this.pool()).slice(0,this.count);if(!qs.length||this.store.draft())return;this.store.saveDraft({id:crypto.randomUUID(),owner:this.store.owner(),mode:this.mode(),startedAt:new Date().toISOString(),deadline:this.mode()==='exam'?Date.now()+4*60*60*1000:null,questionIds:qs.map(q=>q.id),answers:{},checked:[],flagged:[],index:0});void this.router.navigate(['/test']);}catch(e){this.error.set((e as Error).message);}}
}
