import type {Question} from './models';
import {KUMAR} from './questions-kumar';
import {SURGERY} from './questions-surgery';
import {SYNOPSIS} from './questions-synopsis';
import {HEMATOLOGY_SOURCE} from './bank/hematology-source';
import {INTENSIVE_CARE_SOURCE} from './bank/intensive-care-source';
import {ELECTROLYTES_SOURCE} from './bank/electrolytes-source';
import {SEPSIS_SOURCE} from './bank/sepsis-source';
import {ADVANCED_REVISIONS} from './bank/advanced-revisions';
import {THYROID_ADVANCED} from './bank/thyroid-advanced';
import {DIABETES_ADVANCED} from './bank/diabetes-advanced';
import {DIABETES_COMPLICATIONS_ADVANCED} from './bank/diabetes-complications-advanced';
import {HIPERTENSIUNE_ADVANCED} from './bank/hipertensiune-advanced';
import {PNEUMOLOGIE_ADVANCED} from './bank/pneumologie-advanced';
import {INFECTII_CHIR_ADVANCED} from './bank/infectii-chir-advanced';
import {DERMATO_ADVANCED} from './bank/dermato-advanced';
import {EPIDEMIO_ADVANCED} from './bank/epidemio-advanced';
import {HIV_ADVANCED} from './bank/hiv-advanced';
import {NEUROLOGIE_ADVANCED} from './bank/neurologie-advanced';
import {CARDIOLOGIE_ADVANCED} from './bank/cardiologie-advanced';
import {GASTRO_ADVANCED} from './bank/gastro-advanced';
import {HEPATOLOGIE_ADVANCED} from './bank/hepatologie-advanced';
import {NEFROLOGIE_ADVANCED} from './bank/nefrologie-advanced';
import {ARSURI_ADVANCED} from './bank/arsuri-advanced';
import {COLON_ADVANCED} from './bank/colon-advanced';
import {PANCREAS_ADVANCED} from './bank/pancreas-advanced';
import {PEDIATRIE_ADVANCED} from './bank/pediatrie-advanced';
import {GINECO_ADVANCED} from './bank/gineco-advanced';
import {OBSTETRICA_ADVANCED} from './bank/obstetrica-advanced';
import {PSIHIATRIE_ADVANCED} from './bank/psihiatrie-advanced';
import {ORL_ADVANCED} from './bank/orl-advanced';
import {ORTOPEDIE_ADVANCED} from './bank/ortopedie-advanced';
import {UROLOGIE_ADVANCED} from './bank/urologie-advanced';
import {FICAT_SPLINA_ADVANCED} from './bank/ficat-splina-advanced';
import {ELECTROLITI_ADVANCED} from './bank/electroliti-advanced';
import {ATI_ADVANCED} from './bank/ati-advanced';
import {HEMATOLOGIE_ADVANCED} from './bank/hematologie-advanced';
import {CARDIOLOGIE_B} from './bank/cardiologie-b';
import {CARDIOLOGIE_C} from './bank/cardiologie-c';
import {NEFROLOGIE_B} from './bank/nefrologie-b';
import {HEPATOLOGIE_B} from './bank/hepatologie-b';
import {PNEUMOLOGIE_B} from './bank/pneumologie-b';
import {DIABET_B} from './bank/diabet-b';
import {NEUROLOGIE_B} from './bank/neurologie-b';
import {HIV_B} from './bank/hiv-b';
import {GASTRO_B} from './bank/gastro-b';
import {ELECTROLITI_B} from './bank/electroliti-b';
import {HEMATOLOGIE_B} from './bank/hematologie-b';
import {ENDOCRINOLOGIE_B} from './bank/endocrinologie-b';
import {HTA_B} from './bank/hta-b';
import {ATI_B} from './bank/ati-b';
import {COLON_B} from './bank/colon-b';
import {PANCREAS_B} from './bank/pancreas-b';
import {ARSURI_B} from './bank/arsuri-b';
import {INFECTII_CHIR_B} from './bank/infectii-chir-b';
import {ORTOPEDIE_B} from './bank/ortopedie-b';
import {ORL_B} from './bank/orl-b';
import {UROLOGIE_B} from './bank/urologie-b';
import {FICAT_SPLINA_B} from './bank/ficat-splina-b';
import {PEDIATRIE_B} from './bank/pediatrie-b';
import {GINECO_B} from './bank/gineco-b';
import {OBSTETRICA_B} from './bank/obstetrica-b';
import {PSIHIATRIE_B} from './bank/psihiatrie-b';
import {DERMATO_B} from './bank/dermato-b';
import {EPIDEMIO_B} from './bank/epidemio-b';
import {CARDIOLOGIE_D} from './bank/cardiologie-d';
import {CARDIOLOGIE_E} from './bank/cardiologie-e';
import {NEFROLOGIE_C} from './bank/nefrologie-c';
import {HEPATOLOGIE_C} from './bank/hepatologie-c';
import {PNEUMOLOGIE_C} from './bank/pneumologie-c';
import {DIABET_C} from './bank/diabet-c';
import {NEUROLOGIE_C} from './bank/neurologie-c';
import {HIV_C} from './bank/hiv-c';
import {GASTRO_C} from './bank/gastro-c';
import {ELECTROLITI_C} from './bank/electroliti-c';
import {HEMATOLOGIE_C} from './bank/hematologie-c';
import {ENDOCRINOLOGIE_C} from './bank/endocrinologie-c';
import {HTA_C} from './bank/hta-c';
import {ATI_C} from './bank/ati-c';
import {COLON_C} from './bank/colon-c';
import {PANCREAS_C} from './bank/pancreas-c';
import {ARSURI_C} from './bank/arsuri-c';
import {INFECTII_CHIR_C} from './bank/infectii-chir-c';
import {ORTOPEDIE_C} from './bank/ortopedie-c';
import {ORL_C} from './bank/orl-c';
import {UROLOGIE_C} from './bank/urologie-c';
import {FICAT_SPLINA_C} from './bank/ficat-splina-c';
import {PEDIATRIE_C} from './bank/pediatrie-c';
import {GINECO_C} from './bank/gineco-c';
import {OBSTETRICA_C} from './bank/obstetrica-c';
import {PSIHIATRIE_C} from './bank/psihiatrie-c';
import {DERMATO_C} from './bank/dermato-c';
import {EPIDEMIO_C} from './bank/epidemio-c';
import {CARDIOLOGIE_F} from './bank/cardiologie-f';
import {CARDIOLOGIE_G} from './bank/cardiologie-g';
import {NEFROLOGIE_D} from './bank/nefrologie-d';
import {HEPATOLOGIE_D} from './bank/hepatologie-d';
import {PNEUMOLOGIE_D} from './bank/pneumologie-d';
import {DIABET_D} from './bank/diabet-d';
import {NEUROLOGIE_D} from './bank/neurologie-d';
import {HIV_D} from './bank/hiv-d';
import {GASTRO_D} from './bank/gastro-d';
import {ELECTROLITI_D} from './bank/electroliti-d';
import {HEMATOLOGIE_D} from './bank/hematologie-d';
import {ENDOCRINOLOGIE_D} from './bank/endocrinologie-d';
import {HTA_D} from './bank/hta-d';
import {ATI_D} from './bank/ati-d';
import {COLON_D} from './bank/colon-d';
import {PANCREAS_D} from './bank/pancreas-d';
import {ARSURI_D} from './bank/arsuri-d';
import {INFECTII_CHIR_D} from './bank/infectii-chir-d';
import {ORTOPEDIE_D} from './bank/ortopedie-d';
import {ORL_D} from './bank/orl-d';
import {UROLOGIE_D} from './bank/urologie-d';
import {FICAT_SPLINA_D} from './bank/ficat-splina-d';
import {PEDIATRIE_D} from './bank/pediatrie-d';
import {GINECO_D} from './bank/gineco-d';
import {OBSTETRICA_D} from './bank/obstetrica-d';
import {PSIHIATRIE_D} from './bank/psihiatrie-d';
import {DERMATO_D} from './bank/dermato-d';
import {EPIDEMIO_D} from './bank/epidemio-d';
import {HEMOSTAZA_V2} from './bank/hemostaza-v2';
import {ESOFAG_V2} from './bank/esofag-v2';
import {HERNII_V2} from './bank/hernii-v2';
import {SEPSIS_V2} from './bank/sepsis-v2';
import {STOMAC_V2} from './bank/stomac-v2';
import {REUMATOLOGIE_V2} from './bank/reumatologie-v2';
import {TROMBOEMBOLISM_V2} from './bank/tromboembolism-v2';
import {BILIAR_V2} from './bank/biliar-v2';
import {PERIOPERATOR_V2} from './bank/perioperator-v2';
import {TRAUMA_V2} from './bank/trauma-v2';
import {INTESTIN_V2} from './bank/intestin-v2';
import {VASCULAR_V2} from './bank/vascular-v2';
import {advancedEligibilityErrors} from './bank/advanced-author';
import {RETIRED_QUESTIONS} from './bank/retired';

export const PREVIOUS_SOURCE_QUESTIONS:Question[]=[...SEPSIS_SOURCE,...ELECTROLYTES_SOURCE,...INTENSIVE_CARE_SOURCE,...HEMATOLOGY_SOURCE];
const ALL_ADVANCED=[...ADVANCED_REVISIONS,...THYROID_ADVANCED,...DIABETES_ADVANCED,...DIABETES_COMPLICATIONS_ADVANCED,...HIPERTENSIUNE_ADVANCED,...PNEUMOLOGIE_ADVANCED,...INFECTII_CHIR_ADVANCED,...DERMATO_ADVANCED,...EPIDEMIO_ADVANCED,...HIV_ADVANCED,...NEUROLOGIE_ADVANCED,...CARDIOLOGIE_ADVANCED,...GASTRO_ADVANCED,...HEPATOLOGIE_ADVANCED,...NEFROLOGIE_ADVANCED,...ARSURI_ADVANCED,...COLON_ADVANCED,...PANCREAS_ADVANCED,...PEDIATRIE_ADVANCED,...GINECO_ADVANCED,...OBSTETRICA_ADVANCED,...PSIHIATRIE_ADVANCED,...ORL_ADVANCED,...ORTOPEDIE_ADVANCED,...UROLOGIE_ADVANCED,...FICAT_SPLINA_ADVANCED,...ELECTROLITI_ADVANCED,...ATI_ADVANCED,...HEMATOLOGIE_ADVANCED,...CARDIOLOGIE_B,...CARDIOLOGIE_C,...NEFROLOGIE_B,...HEPATOLOGIE_B,...PNEUMOLOGIE_B,...DIABET_B,...NEUROLOGIE_B,...HIV_B,...GASTRO_B,...ELECTROLITI_B,...HEMATOLOGIE_B,...ENDOCRINOLOGIE_B,...HTA_B,...ATI_B,...COLON_B,...PANCREAS_B,...ARSURI_B,...INFECTII_CHIR_B,...ORTOPEDIE_B,...ORL_B,...UROLOGIE_B,...FICAT_SPLINA_B,...PEDIATRIE_B,...GINECO_B,...OBSTETRICA_B,...PSIHIATRIE_B,...DERMATO_B,...EPIDEMIO_B,...CARDIOLOGIE_D,...CARDIOLOGIE_E,...NEFROLOGIE_C,...HEPATOLOGIE_C,...PNEUMOLOGIE_C,...DIABET_C,...NEUROLOGIE_C,...HIV_C,...GASTRO_C,...ELECTROLITI_C,...HEMATOLOGIE_C,...ENDOCRINOLOGIE_C,...HTA_C,...ATI_C,...COLON_C,...PANCREAS_C,...ARSURI_C,...INFECTII_CHIR_C,...ORTOPEDIE_C,...ORL_C,...UROLOGIE_C,...FICAT_SPLINA_C,...PEDIATRIE_C,...GINECO_C,...OBSTETRICA_C,...PSIHIATRIE_C,...DERMATO_C,...EPIDEMIO_C,...CARDIOLOGIE_F,...CARDIOLOGIE_G,...NEFROLOGIE_D,...HEPATOLOGIE_D,...PNEUMOLOGIE_D,...DIABET_D,...NEUROLOGIE_D,...HIV_D,...GASTRO_D,...ELECTROLITI_D,...HEMATOLOGIE_D,...ENDOCRINOLOGIE_D,...HTA_D,...ATI_D,...COLON_D,...PANCREAS_D,...ARSURI_D,...INFECTII_CHIR_D,...ORTOPEDIE_D,...ORL_D,...UROLOGIE_D,...FICAT_SPLINA_D,...PEDIATRIE_D,...GINECO_D,...OBSTETRICA_D,...PSIHIATRIE_D,...DERMATO_D,...EPIDEMIO_D,...HEMOSTAZA_V2,...ESOFAG_V2,...HERNII_V2,...SEPSIS_V2,...STOMAC_V2,...REUMATOLOGIE_V2,...TROMBOEMBOLISM_V2,...BILIAR_V2,...PERIOPERATOR_V2,...TRAUMA_V2,...INTESTIN_V2,...VASCULAR_V2];
// A retired version never stays live, even when its source file also holds other topics.
const RETIRED_IDS=new Set(RETIRED_QUESTIONS.map(q=>q.id));
export const ADVANCED_CANDIDATES=ALL_ADVANCED.filter(q=>!RETIRED_IDS.has(q.id));
export const SOURCE_CHECKED_QUESTIONS=ADVANCED_CANDIDATES.filter(q=>advancedEligibilityErrors(q).length===0);
export const LEGACY_QUESTIONS:Question[]=[...KUMAR,...SURGERY,...SYNOPSIS];
// Old stems/options/keys remain addressable for saved attempts and open drafts.
// New sessions use the revised chapter; they never silently rescore old IDs.
export const QUESTIONS:Question[]=[...SOURCE_CHECKED_QUESTIONS];
export const BANK_TARGET=800;
export const EXAM_AVAILABLE=QUESTIONS.filter(q=>q.type==='CS').length>=50&&QUESTIONS.filter(q=>q.type==='CM').length>=150;
export {RETIRED_QUESTIONS};
// Replaced advanced versions stay here so saved attempts keep their original scoring.
export const QUESTION_HISTORY:Question[]=[...LEGACY_QUESTIONS,...PREVIOUS_SOURCE_QUESTIONS,...RETIRED_QUESTIONS,...SOURCE_CHECKED_QUESTIONS];
