import {group} from './question-builder';
export const KUMAR=[
...group('sepsis','https://www.cdc.gov/sepsis/about/index.html',[
 ['Care este elementul definitoriu al sepsisului?', ['Febra izolată','Disfuncția de organ determinată de un răspuns dereglat la infecție','O hemocultură pozitivă fără manifestări clinice','Leucocitoza izolată','Orice infecție virală ușoară'],[1],'Sepsisul presupune disfuncție de organ în contextul unui răspuns dereglat la infecție; febra sau leucocitoza singure nu îl definesc.'],
 ['La un pacient cu infecție, ce constatare sugerează hipoperfuzie tisulară?', ['Diureză crescută','Extremități constant calde fără alte modificări','Creșterea lactatului seric','Hemoglobină normală','Saturație normală izolată'],[2],'Lactatul crescut poate semnala hipoperfuzie, dar se interpretează în context; nu este specific exclusiv sepsisului.'],
 ['Ce manifestări pot ridica suspiciunea de sepsis în context infecțios?', ['Alterarea stării mentale','Tahipnee','Hipotensiune','Oligurie','Absența obligatorie a disfuncției de organ'],[0,1,2,3],'Alterarea conștienței, tahipneea, hipotensiunea și scăderea diurezei pot indica afectare sistemică și de organ.'],
 ['Care afirmații despre controlul sursei infecțioase sunt corecte?', ['Un abces poate necesita drenaj','Țesutul necrotic infectat poate necesita debridare','Antibioticele înlocuiesc întotdeauna drenajul','Un dispozitiv infectat poate necesita îndepărtare','Controlul sursei este lipsit de importanță în sepsis'],[0,1,3],'Controlul sursei poate include drenaj, debridare și îndepărtarea unui dispozitiv infectat, alături de antimicrobiene.'],
 ['Despre evaluarea microbiologică în suspiciunea de sepsis sunt corecte:', ['Hemoculturile pot identifica agentul patogen','O cultură negativă exclude întotdeauna sepsisul','Probele se recoltează, când este posibil, înaintea antibioticelor fără întârziere semnificativă','Antibiograma poate ghida ajustarea tratamentului','Rezultatul culturilor trebuie așteptat înaintea oricărui tratament la pacientul instabil'],[0,2,3],'Recoltarea precoce și antibiograma sprijină tratamentul țintit. Culturile negative nu exclud sepsisul, iar tratamentul urgent nu așteaptă rezultatele.']
]),
...group('electroliti','https://www.msdmanuals.com/professional/nephrology/acid-base-regulation-and-disorders/acid-base-disorders',[
 ['Un pH arterial de 7,25, cu bicarbonat redus și PaCO₂ compensator redusă, indică în primul rând:', ['Alcaloză respiratorie','Alcaloză metabolică','Acidoză respiratorie','Acidoză metabolică','Echilibru acido-bazic normal'],[3],'Acidemia asociată cu reducerea primară a bicarbonatului definește acidoza metabolică; hiperventilația scade compensator PaCO₂.'],
 ['Care ion este principalul cation al compartimentului extracelular?', ['Potasiul','Magneziul','Sodiul','Fosfatul','Calciul intracelular'],[2],'Sodiul este principalul cation extracelular, iar potasiul este predominant intracelular.'],
 ['Ce situații pot produce acidoză metabolică?', ['Cetoacidoza diabetică','Acidoza lactică','Pierderea digestivă de bicarbonat prin diaree','Vărsături gastrice prelungite ca mecanism izolat','Retenția de acizi în insuficiența renală'],[0,1,2,4],'Cetoacizii, lactatul, pierderea bicarbonatului și eliminarea renală redusă a acizilor produc acidoză. Vărsăturile favorizează alcaloza metabolică.'],
 ['În hiperkaliemia severă pot apărea:', ['Tulburări de ritm cardiac','Slăbiciune musculară','Unde T înalte, ascuțite','Lărgirea complexului QRS','Protecție completă împotriva aritmiilor'],[0,1,2,3],'Hiperkaliemia poate afecta excitabilitatea neuromusculară și conducerea cardiacă, cu modificări ECG și aritmii.'],
 ['Care afirmații despre tulburările acido-bazice sunt corecte?', ['PaCO₂ reflectă componenta respiratorie','Bicarbonatul reflectă componenta metabolică','Compensarea exclude existența unei tulburări mixte','Hipoventilația poate produce acidoză respiratorie','Hiperventilația poate produce alcaloză respiratorie'],[0,1,3,4],'PaCO₂ și bicarbonatul caracterizează componentele respiratorie și metabolică. Compensarea se evaluează pentru a identifica inclusiv tulburări mixte.']
]),
...group('ati','https://www.msdmanuals.com/professional/critical-care-medicine/respiratory-failure-and-mechanical-ventilation/acute-hypoxemic-respiratory-failure-ahrf-ards',[
 ['Insuficiența respiratorie hipercapnică se caracterizează prin:', ['Creșterea PaCO₂','Creșterea obligatorie a pH-ului','Absența hipoventilației','PaCO₂ permanent scăzută','Excluderea afectării neuromusculare'],[0],'Hipercapnia reflectă ventilația alveolară insuficientă în raport cu producția de CO₂.'],
 ['Care investigație măsoară direct PaO₂, PaCO₂ și pH-ul arterial?', ['Pulsoximetria','Spirometria simplă','Gazometria arterială','Radiografia toracică','Electrocardiograma'],[2],'Gazometria oferă presiunile parțiale arteriale și pH-ul. Pulsoximetria estimează saturația, fără măsurarea PaCO₂.'],
 ['Care situații pot declanșa sindromul de detresă respiratorie acută?', ['Sepsisul','Pneumonia severă','Aspirația conținutului gastric','Traumatismul major','Miopia necomplicată'],[0,1,2,3],'SDRA poate apărea după leziuni pulmonare directe sau în cadrul unui răspuns inflamator sistemic sever.'],
 ['Despre evaluarea insuficienței respiratorii sunt corecte:', ['Efortul respirator trebuie evaluat clinic','Pulsoximetria înlocuiește întotdeauna gazometria','Alterarea conștienței poate însoți hipercapnia','Cauza insuficienței respiratorii trebuie căutată','O saturație normală exclude orice creștere a PaCO₂'],[0,2,3],'Examenul clinic și identificarea cauzei sunt esențiale. Saturația nu evaluează direct ventilația și poate fi normală în hipercapnie.'],
 ['În SDRA sunt caracteristice:', ['Debutul acut în contextul unui factor declanșator','Hipoxemia','Opacitățile pulmonare bilaterale','Edemul explicat exclusiv prin insuficiență cardiacă','Afectarea barierei alveolo-capilare'],[0,1,2,4],'SDRA implică leziune alveolo-capilară, hipoxemie și opacități bilaterale; tabloul nu este explicat exclusiv de insuficiența cardiacă.']
]),
...group('hematologie','https://www.msdmanuals.com/professional/hematology-and-oncology/anemias-caused-by-deficient-erythropoiesis/iron-deficiency-anemia',[
 ['Care profil este tipic deficitului de fier necomplicat de inflamație?', ['Feritină crescută și microcitoză','Feritină scăzută și microcitoză','Macrocitoză cu vitamina B12 crescută','Reticulocitoză masivă izolată','Hemoglobină crescută'],[1],'Deficitul de fier scade rezervele reflectate de feritină și poate produce anemie microcitară. Inflamația poate crește feritina.'],
 ['Ce deficit poate asocia anemie megaloblastică și manifestări neurologice?', ['Deficitul de sodiu','Deficitul de vitamina C izolat','Deficitul de vitamina B12','Deficitul de clor','Deficitul de vitamina K izolat'],[2],'Deficitul de B12 poate determina megaloblastoză și afectare neurologică, inclusiv parestezii și tulburări de sensibilitate profundă.'],
 ['Ce constatări susțin hemoliza?', ['Creșterea bilirubinei indirecte','Creșterea LDH','Scăderea haptoglobinei','Reticulocitoză când măduva răspunde adecvat','Creșterea obligatorie a haptoglobinei'],[0,1,2,3],'Distrugerea eritrocitară crește LDH și bilirubina indirectă; consumul haptoglobinei și răspunsul reticulocitar pot completa tabloul.'],
 ['Ce cauze pot determina anemie microcitară?', ['Deficitul de fier','Talasemia','Deficitul izolat de vitamina B12 ca aspect tipic','Unele forme de anemie din inflamația cronică','Deficitul izolat de folat ca aspect tipic'],[0,1,3],'Microcitoza apare în deficitul de fier, talasemii și uneori în inflamația cronică. B12 și folatul produc tipic macrocitoză.'],
 ['Despre anemia hemolitică autoimună sunt corecte:', ['Poate avea test antiglobulinic direct pozitiv','Este determinată întotdeauna de deficit de fier','Poate asocia icter','Poate asocia reticulocitoză','Exclude distrugerea eritrocitară periferică'],[0,2,3],'Anticorpii sau complementul de pe eritrocite pot fi detectați prin testul antiglobulinic direct. Icterul și reticulocitoza sunt compatibile cu hemoliza.']
]),
...group('reumatologie','https://www.msdmanuals.com/professional/musculoskeletal-and-connective-tissue-disorders/joint-disorders/rheumatoid-arthritis-ra',[
 ['Care distribuție articulară este tipică artritei reumatoide?', ['Afectare exclusivă a interfalangienelor distale','Poliartrită simetrică a articulațiilor mici ale mâinilor','Monoartrită traumatică izolată','Afectare exclusivă a coloanei lombare','Absența sinovitei'],[1],'Artrita reumatoidă afectează frecvent simetric articulațiile metacarpofalangiene și interfalangiene proximale.'],
 ['Care manifestare sugerează durere lombară inflamatorie?', ['Ameliorarea exclusivă prin repaus','Debutul numai după 80 de ani','Ameliorarea prin mișcare','Durerea de câteva secunde după traumatism','Absența rigidității matinale în toate cazurile'],[2],'Durerea inflamatorie tinde să se amelioreze prin mișcare și poate asocia rigiditate matinală, spre deosebire de multe dureri mecanice.'],
 ['În artrita reumatoidă pot fi întâlnite:', ['Redoare matinală prelungită','Tumefacție articulară','Anticorpi anti-CCP','Eroziuni articulare','Afectare exclusiv cutanată fără artrită'],[0,1,2,3],'Sinovita, redoarea și eroziunile sunt caracteristice; anti-CCP sprijină diagnosticul, fără a fi obligatorii la fiecare pacient.'],
 ['Lupusul eritematos sistemic poate asocia:', ['Fotosensibilitate','Afectare renală','Citopenii','Artrită','Afectare obligatoriu limitată la piele'],[0,1,2,3],'LES este o boală sistemică și poate implica pielea, rinichii, sângele și articulațiile.'],
 ['Care manifestări se pot asocia spondiloartritelor?', ['Sacroiliită','Entezită','Uveită anterioară','Dactilită','Noduli reumatoizi obligatorii'],[0,1,2,3],'Spondiloartritele pot asocia afectare axială, entezite, dactilită și manifestări extraarticulare precum uveita.']
]),
...group('endocrinologie','https://www.niddk.nih.gov/health-information/endocrine-diseases/hypothyroidism',[
 ['Ce profil hormonal este tipic hipotiroidismului primar manifest?', ['TSH scăzut, FT4 crescut','TSH crescut, FT4 scăzut','TSH scăzut, FT4 normal în toate cazurile','TSH normal, FT4 crescut obligatoriu','TSH și FT4 crescute obligatoriu'],[1],'În hipotiroidismul primar, scăderea hormonilor tiroidieni stimulează creșterea compensatoare a TSH.'],
 ['Care manifestare este mai sugestivă pentru hipertiroidism?', ['Intoleranța la frig','Bradicardia constantă','Constipația izolată','Scăderea ponderală cu apetit păstrat sau crescut','Somnolența ca unic semn obligatoriu'],[3],'Hipermetabolismul din hipertiroidism poate provoca scădere ponderală în ciuda unui apetit păstrat sau crescut.'],
 ['Hipotiroidismul poate determina:', ['Intoleranță la frig','Constipație','Tegumente uscate','Bradicardie','Tremor fin și hipersudorație ca semne tipice'],[0,1,2,3],'Reducerea efectelor hormonilor tiroidieni explică intoleranța la frig, tranzitul lent, pielea uscată și bradicardia.'],
 ['Boala Graves poate asocia:', ['Hipertiroidism','Gușă difuză','Orbitopatie','Anticorpi împotriva receptorului TSH','TSH constant crescut în forma netratată'],[0,1,2,3],'Graves este o boală autoimună cu stimularea receptorului TSH; în forma manifestă netratată, TSH este de regulă suprimat.'],
 ['Care afirmații despre nodulii tiroidieni sunt corecte?', ['Ecografia evaluează caracteristicile nodulului','Puncția aspirativă poate fi indicată după evaluarea riscului','Toți nodulii sunt maligni','Un nodul poate exista cu funcție tiroidiană normală','Dimensiunea este singurul criteriu de malignitate'],[0,1,3],'Evaluarea combină ecografia, funcția tiroidiană și, când este indicată, citologia. Nici prezența, nici dimensiunea singură nu definesc malignitatea.']
]),
...group('diabet','https://www.niddk.nih.gov/health-information/diabetes/overview/what-is-diabetes',[
 ['Care mecanism caracterizează diabetul zaharat de tip 1?', ['Excesul primar de insulină','Distrugerea celulelor beta cu deficit de insulină','Excesul izolat de glucagon fără afectare beta','Rezistența exclusiv renală la apă','Hipoglicemia permanentă netratată'],[1],'Diabetul de tip 1 presupune pierderea celulelor beta, de obicei autoimună, cu deficit sever de insulină.'],
 ['Care analiză reflectă aproximativ controlul glicemic din ultimele 2–3 luni?', ['Glicemia dintr-o singură probă','Ureea','HbA1c','Sodiul','Albumina urinară'],[2],'HbA1c reflectă glicarea hemoglobinei în timpul vieții eritrocitelor; unele afecțiuni hematologice îi pot altera interpretarea.'],
 ['Ce manifestări sunt compatibile cu hiperglicemia simptomatică?', ['Poliurie','Polidipsie','Scădere ponderală neintenționată','Vedere încețoșată','Anurie obligatorie de la debut'],[0,1,2,3],'Diureza osmotică explică poliuria și setea; pierderea calorică și modificările osmotice pot produce scădere ponderală și vedere încețoșată.'],
 ['Cetoacidoza diabetică poate asocia:', ['Cetoză','Acidoză metabolică','Deshidratare','Respirație Kussmaul','Alcaloză metabolică izolată ca element definitoriu'],[0,1,2,3],'Deficitul de insulină favorizează cetogeneza și acidoza, cu pierderi hidroelectrolitice și hiperventilație compensatoare.'],
 ['Care sunt complicații microvasculare ale diabetului?', ['Retinopatia','Nefropatia','Neuropatia diabetică','Infarctul miocardic ca leziune microvasculară tipică','Boala arterială periferică ca leziune microvasculară tipică'],[0,1,2],'Retinopatia, nefropatia și neuropatia sunt complicații microvasculare clasice; boala coronariană și periferică sunt macrovasculare.']
]),
...group('neurologie','https://www.ninds.nih.gov/health-information/disorders/stroke',[
 ['La un pacient cu deficit neurologic focal instalat brusc, ce diagnostic trebuie suspectat prioritar?', ['Dermatită de contact','Accident vascular cerebral','Artroză','Hipotiroidism subclinic','Rinită alergică'],[1],'Debutul brusc al unui deficit focal este sugestiv pentru AVC și impune evaluare urgentă.'],
 ['Care investigație este utilizată frecvent inițial pentru identificarea unei hemoragii intracraniene acute?', ['Radiografia de craniu','CT cerebral fără contrast','Electromiografia','Spirometria','Ecografia abdominală'],[1],'CT cerebral nativ poate identifica rapid hemoragia și este frecvent investigația inițială în suspiciunea de AVC.'],
 ['Ce manifestări pot apărea într-un AVC?', ['Asimetrie facială bruscă','Slăbiciune unilaterală','Tulburare bruscă de vorbire','Pierderea bruscă a vederii','Prurit cronic izolat ca semn focal tipic'],[0,1,2,3],'AVC poate afecta motricitatea, limbajul și vederea, cu debut de regulă brusc.'],
 ['Meningita bacteriană poate asocia:', ['Febră','Cefalee','Redoare de ceafă','Alterarea stării de conștiență','Absența obligatorie a inflamației meningeale'],[0,1,2,3],'Aceste semne sunt compatibile cu meningita; absența unuia dintre ele nu exclude diagnosticul.'],
 ['În evaluarea unui pacient în comă sunt importante:', ['Evaluarea căilor aeriene și a respirației','Determinarea glicemiei','Examinarea pupilelor','Căutarea cauzelor toxice și metabolice','Presupunerea că orice comă este psihogenă'],[0,1,2,3],'Evaluarea inițială caută instabilitatea vitală și cauze tratabile, inclusiv hipoglicemia, intoxicațiile și tulburările metabolice.']
]),
...group('pneumologie','https://www.msdmanuals.com/professional/pulmonary-disorders/asthma-and-related-disorders/asthma',[
 ['Care trăsătură este caracteristică astmului?', ['Obstrucție variabilă a fluxului expirator','Absența inflamației căilor aeriene','Distrugerea obligatorie a tuturor alveolelor','Revărsat pleural în fiecare caz','Imposibilitatea oricărei reversibilități'],[0],'Astmul se caracterizează prin simptome variabile și limitare variabilă a fluxului expirator, în context inflamator.'],
 ['Care expunere este un factor major de risc pentru BPOC?', ['Fumatul','Consumul de apă','Lumina solară moderată','Utilizarea ochelarilor','Exercițiul fizic regulat'],[0],'Fumatul este un factor major de risc; expunerea la biomasă și noxe profesionale poate contribui de asemenea.'],
 ['Astmul poate asocia:', ['Wheezing','Dispnee episodică','Tuse nocturnă','Variabilitatea simptomelor','Hemoptizie masivă obligatorie'],[0,1,2,3],'Wheezingul, dispneea și tusea variabile, uneori nocturne, sunt caracteristice astmului.'],
 ['Care manifestări sunt compatibile cu pneumonia?', ['Febră','Tuse','Infiltrat pulmonar nou în context clinic adecvat','Durere toracică pleuritică','Absența obligatorie a simptomelor respiratorii'],[0,1,2,3],'Pneumonia poate asocia manifestări sistemice și respiratorii cu un infiltrat nou; prezentarea variază cu vârsta și agentul.'],
 ['Despre tuberculoza pulmonară sunt corecte:', ['Se poate transmite pe cale aeriană','Poate determina tuse persistentă','Poate asocia transpirații nocturne','Poate asocia scădere ponderală','Se transmite exclusiv prin înțepătura țânțarului'],[0,1,2,3],'Tuberculoza pulmonară contagioasă se transmite aerian și poate produce simptome respiratorii și constituționale.']
]),
...group('tromboembolism','https://www.cdc.gov/blood-clots/about/index.html',[
 ['Care investigație este utilizată uzual pentru confirmarea trombozei venoase profunde a membrului inferior?', ['Electroencefalograma','Ecografia venoasă de compresie','Radiografia de craniu','Audiograma','Endoscopia digestivă'],[1],'Ecografia venoasă de compresie evaluează permeabilitatea și compresibilitatea venelor profunde.'],
 ['Ce complicație poate rezulta din migrarea unui tromb venos profund?', ['Embolie pulmonară','Otită externă','Cataractă','Hipotiroidism','Apendicită'],[0],'Trombul din sistemul venos profund poate migra prin cordul drept către circulația pulmonară.'],
 ['Care factori cresc riscul tromboembolismului venos?', ['Imobilizarea prelungită','Intervenția chirurgicală majoră','Neoplazia activă','Antecedentele de tromboembolism venos','Mobilizarea precoce ca factor favorizant tipic'],[0,1,2,3],'Staza, leziunea vasculară și hipercoagulabilitatea favorizează tromboza; mobilizarea este o măsură preventivă.'],
 ['Embolia pulmonară poate asocia:', ['Dispnee bruscă','Durere pleuritică','Tahicardie','Hemoptizie','Bradicardie obligatorie cu excluderea hipoxemiei'],[0,1,2,3],'Manifestările emboliei pulmonare sunt variabile și pot include dispnee, durere, tahicardie și uneori hemoptizie.'],
 ['Care afirmații despre D-dimeri sunt corecte?', ['Pot crește și în alte situații decât tromboza','Un rezultat pozitiv confirmă singur embolia pulmonară','Un rezultat negativ poate ajuta la excludere în probabilitate clinică adecvată','Interpretarea depinde de contextul clinic','Sunt complet independenți de vârstă și inflamație'],[0,2,3],'D-dimerii sunt sensibili, dar nespecifici. Se utilizează în algoritmi bazați pe probabilitatea clinică și, când este indicat, pe praguri ajustate.']
]),
...group('cardiologie','https://www.msdmanuals.com/professional/cardiovascular-disorders/heart-failure/acute-heart-failure',[
 ['Ce tulburare de ritm produce tipic un puls neregulat-neregulat?', ['Fibrilația atrială','Ritmul sinusal normal','Tahicardia sinusală regulată','Blocul atrioventricular de grad I izolat','Ritmul atrial regulat'],[0],'Conducerea ventriculară variabilă în fibrilația atrială produce tipic un ritm neregulat-neregulat.'],
 ['Care biomarker este preferat pentru identificarea leziunii miocardice?', ['Troponina cardiacă','Amilaza','Bilirubina','Ureea','Albumina'],[0],'Troponina indică leziune miocardică; diagnosticul infarctului necesită și dovezi de ischemie, nu doar o valoare crescută.'],
 ['Insuficiența cardiacă stângă poate determina:', ['Dispnee','Ortopnee','Raluri pulmonare','Dispnee paroxistică nocturnă','Ameliorarea obligatorie în decubit complet'],[0,1,2,3],'Congestia pulmonară explică dispneea, ortopneea și ralurile; poziția culcată poate accentua simptomele.'],
 ['Ce manifestări pot apărea în insuficiența cardiacă dreaptă?', ['Edeme periferice','Turgescență jugulară','Hepatomegalie de stază','Ascită','Absența obligatorie a congestiei venoase'],[0,1,2,3],'Creșterea presiunii venoase sistemice se poate manifesta prin edeme, jugulare turgescente, hepatomegalie și ascită.'],
 ['Care afirmații despre endocardita infecțioasă sunt corecte?', ['Poate produce vegetații valvulare','Hemoculturile au rol diagnostic','Ecocardiografia poate identifica leziuni','Pot apărea embolii septice','Este întotdeauna exclusă în absența febrei la un moment dat'],[0,1,2,3],'Diagnosticul integrează microbiologia și imagistica; vegetațiile pot emboliza, iar manifestările pot fi nespecifice.'],
 ['În stenoza aortică severă pot apărea:', ['Angină','Sincopă la efort','Dispnee','Suflu sistolic de ejecție','Suflu diastolic de regurgitare ca semn definitoriu al stenozei'],[0,1,2,3],'Triada clinică include angină, sincopă și dispnee, iar obstrucția ejecției produce suflu sistolic.'],
 ['Despre pericardita acută sunt corecte:', ['Durerea poate fi pleuritică','Durerea se poate ameliora la aplecarea înainte','Poate exista frecătură pericardică','Poate asocia revărsat pericardic','Durerea este obligatoriu absentă'],[0,1,2,3],'Inflamația pericardică poate provoca durere dependentă de poziție și respirație, frecătură și revărsat.'],
 ['Ce constatări pot susține tamponada cardiacă?', ['Hipotensiune','Turgescență jugulară','Puls paradoxal','Compresiune cardiacă prin lichid pericardic','Creșterea obligatorie a debitului cardiac'],[0,1,2,3],'Presiunea pericardică crescută împiedică umplerea cardiacă și poate reduce debitul cardiac.'],
 ['Care afirmații despre fibrilația atrială sunt corecte?', ['Poate crește riscul de AVC embolic','Poate fi asimptomatică','ECG poate arăta absența undelor P distincte','Necesitatea anticoagulării se evaluează individual','Toți pacienții au automat risc embolic identic'],[0,1,2,3],'Fibrilația atrială poate favoriza tromboembolismul; riscul și indicația anticoagulării depind de factorii individuali.'],
 ['Care situații pot crește troponina în afara unui infarct aterotrombotic?', ['Miocardita','Embolia pulmonară cu afectare cardiacă','Sepsisul sever','Insuficiența cardiacă acută','Troponina crește exclusiv în infarctul de tip 1'],[0,1,2,3],'Troponina marchează leziunea miocardică, care poate avea multiple mecanisme ischemice și nonischemice.']
]),
...group('hta','https://www.who.int/news-room/fact-sheets/detail/hypertension',[
 ['Care afirmație despre hipertensiunea arterială este corectă?', ['Este întotdeauna simptomatică','Poate evolua mult timp fără simptome','Nu afectează rinichii','Este diagnosticată printr-o singură senzație de cefalee','Nu influențează riscul cardiovascular'],[1],'Hipertensiunea este adesea asimptomatică; măsurarea corectă a tensiunii este esențială pentru identificare.'],
 ['Ce organe pot fi afectate de hipertensiunea cronică?', ['Cordul','Creierul','Rinichii','Retina','Niciun organ dacă pacientul nu are cefalee'],[0,1,2,3],'Hipertensiunea poate produce afectare cardiacă, cerebrovasculară, renală și retiniană chiar în absența simptomelor.'],
 ['Ce măsuri pot contribui la controlul tensiunii arteriale?', ['Reducerea excesului de sare','Activitate fizică adaptată','Controlul greutății','Limitarea consumului excesiv de alcool','Creșterea sistematică a aportului de sare'],[0,1,2,3],'Modificările stilului de viață sprijină controlul tensiunii și completează tratamentul când acesta este indicat.'],
 ['Ce afecțiuni pot produce hipertensiune secundară?', ['Boală renală parenchimatoasă','Hiperaldosteronism primar','Feocromocitom','Stenoză de arteră renală','Miopie simplă'],[0,1,2,3],'Cauzele renale, renovasculare și endocrine sunt importante în hipertensiunea secundară.'],
 ['O urgență hipertensivă cu afectare acută de organ poate asocia:', ['Encefalopatie','Edem pulmonar acut','Leziune renală acută','Disecție de aortă','Doar o valoare crescută fără afectare de organ, ca definiție obligatorie'],[0,1,2,3],'Prezența afectării acute de organ diferențiază urgența hipertensivă majoră de o creștere severă izolată a tensiunii.']
]),
...group('gastro','https://www.niddk.nih.gov/health-information/digestive-diseases/acid-reflux-ger-gerd-adults',[
 ['Care simptom este caracteristic bolii de reflux gastroesofagian?', ['Pirozisul','Hematuria','Diplopia','Hipoacuzia','Claudicația'],[0],'Pirozisul reprezintă senzația de arsură retrosternală caracteristică refluxului, frecvent asociată cu regurgitație.'],
 ['Ce afirmații despre Helicobacter pylori sunt corecte?', ['Poate determina gastrită cronică','Se asociază cu ulcerul peptic','Poate fi identificat prin test respirator cu uree','Este întotdeauna o bacterie nepatogenă','Se asociază cu un risc crescut pentru anumite neoplazii gastrice'],[0,1,2,4],'H. pylori poate cauza gastrită și ulcer și se asociază cu adenocarcinom gastric și limfom MALT.'],
 ['Boala Crohn poate prezenta:', ['Inflamație transmurală','Leziuni discontinue','Fistule','Afectare ileală','Afectare limitată obligatoriu la rect'],[0,1,2,3],'Crohn poate afecta segmente diferite ale tubului digestiv; inflamația transmurală explică stenozele și fistulele.'],
 ['Rectocolita ulcero-hemoragică se caracterizează frecvent prin:', ['Afectarea mucoasei colonice','Diaree cu sânge','Inflamație continuă cu debut rectal','Fistule transmurale ca trăsătură definitorie','Afectare exclusiv jejunală'],[0,1,2],'Boala afectează colonul, de regulă continuu dinspre rect, cu inflamație predominant mucoasă și diaree sangvinolentă.'],
 ['Ce manifestări reprezintă semnale de alarmă la un pacient cu simptome digestive superioare?', ['Disfagie progresivă','Scădere ponderală neintenționată','Hemoragie digestivă','Anemie feriprivă neexplicată','Pirozis rar izolat ca echivalent obligatoriu al cancerului'],[0,1,2,3],'Disfagia progresivă, pierderea ponderală, sângerarea și anemia necesită evaluare pentru cauze organice relevante.']
]),
...group('hepatologie','https://www.niddk.nih.gov/health-information/liver-disease/cirrhosis',[
 ['Care este o consecință a hipertensiunii portale?', ['Varice esofagiene','Hipertiroidism','Otită medie','Cataractă','Hernie de disc'],[0],'Presiunea portală crescută favorizează circulația colaterală portosistemică, inclusiv varice esofagiene.'],
 ['Ciroza hepatică decompensată poate asocia:', ['Ascită','Encefalopatie hepatică','Hemoragie variceală','Icter','Absența obligatorie a hipertensiunii portale'],[0,1,2,3],'Ascita, encefalopatia, hemoragia și icterul sunt manifestări importante ale decompensării hepatice.'],
 ['Ce factori pot precipita encefalopatia hepatică?', ['Hemoragia digestivă','Infecția','Constipația','Tulburările hidroelectrolitice','Imunitatea obligatorie față de efectul sedativelor'],[0,1,2,3],'Creșterea încărcăturii azotate, infecțiile și tulburările metabolice pot precipita encefalopatia.'],
 ['Despre hepatitele virale sunt corecte:', ['Hepatita A se poate transmite fecal-oral','Hepatita B se poate transmite prin sânge','Hepatita C poate deveni cronică','Toate hepatitele virale se transmit exclusiv prin alimente','Există vaccin împotriva hepatitei B'],[0,1,2,4],'Virusurile hepatitice au căi de transmitere și potențial de cronicizare diferite; vaccinarea anti-HBV este disponibilă.'],
 ['Ce constatări pot indica reducerea funcției de sinteză hepatice?', ['Albumină scăzută','INR prelungit în context adecvat','Transaminaze normale ca dovadă absolută de sinteză normală','Timp de protrombină prelungit','Hemoglobină crescută ca marker specific'],[0,1,3],'Albumina și parametrii coagulării pot reflecta sinteza hepatică, dar au și alte cauze de modificare; transaminazele nu măsoară direct sinteza.']
]),
...group('nefrologie','https://www.niddk.nih.gov/health-information/kidney-disease/chronic-kidney-disease-ckd',[
 ['Ce durată minimă a modificărilor renale este utilizată în definirea bolii cronice de rinichi?', ['24 de ore','3 zile','3 luni','1 săptămână','12 ore'],[2],'Boala cronică de rinichi presupune anomalii de structură sau funcție prezente cel puțin trei luni.'],
 ['Sindromul nefrotic poate asocia:', ['Proteinurie importantă','Hipoalbuminemie','Edeme','Hiperlipidemie','Absența obligatorie a proteinuriei'],[0,1,2,3],'Pierderea urinară de proteine se asociază cu hipoalbuminemie și edeme; hiperlipidemia este frecventă.'],
 ['Sindromul nefritic poate include:', ['Hematurie','Hipertensiune','Scăderea filtrării glomerulare','Cilindri eritrocitari','Absența obligatorie a inflamației glomerulare'],[0,1,2,3],'Inflamația glomerulară poate produce hematurie glomerulară, cilindri eritrocitari, reducerea filtrării și retenție hidrosalină.'],
 ['Ce complicații pot apărea în boala cronică de rinichi avansată?', ['Anemie','Hiperkaliemie','Acidoză metabolică','Tulburări minerale și osoase','Creșterea obligatorie a sintezei de eritropoietină'],[0,1,2,3],'Afectarea renală reduce funcțiile excretorii și endocrine, favorizând anemia și dezechilibrele metabolice.'],
 ['Nefrita interstițială acută medicamentoasă poate asocia:', ['Leziune renală acută','Expunere recentă la un medicament declanșator','Erupție cutanată','Eozinofilie','Prezența obligatorie a tuturor semnelor clasice la fiecare pacient'],[0,1,2,3],'Manifestările alergice pot exista, dar triada clasică nu este prezentă la toți pacienții. Contextul medicamentos este important.']
]),
...group('hiv','https://www.cdc.gov/hiv/about/index.html',[
 ['Ce populație celulară este afectată central în infecția HIV?', ['Limfocitele T CD4','Eritrocitele mature ca țintă principală','Trombocitele exclusiv','Osteocitele exclusiv','Adipocitele exclusiv'],[0],'HIV afectează în special celulele care exprimă CD4 și coreceptori, cu scăderea progresivă a imunității celulare.'],
 ['Care sunt căi de transmitere a HIV?', ['Contact sexual cu expunere infectantă','Utilizare comună de ace contaminate','Transmitere materno-fetală sau perinatală','Strângerea mâinii','Alăptare în condiții de risc de transmitere'],[0,1,2,4],'HIV se poate transmite sexual, parenteral și vertical, inclusiv prin laptele matern; contactul social obișnuit nu transmite virusul.'],
 ['Despre monitorizarea infecției HIV sunt corecte:', ['Viremia reflectă replicarea virală','Numărul CD4 ajută la evaluarea imunității','O viremie nedetectabilă înseamnă obligatoriu eradicare','Aderența influențează eficacitatea tratamentului','Infecțiile oportuniste pot apărea în imunodepresie'],[0,1,3,4],'Tratamentul poate suprima replicarea fără eradicarea rezervorului viral. CD4 și viremia oferă informații complementare.'],
 ['Ce infecții oportuniste sunt asociate imunodepresiei avansate din HIV?', ['Pneumocistoza','Toxoplasmoza cerebrală','Criptococoza','Candidoza esofagiană','Orice rinită alergică drept infecție oportunistă'],[0,1,2,3],'Imunodepresia avansată favorizează aceste infecții; rinita alergică nu este o infecție.'],
 ['Care afirmații despre tratamentul antiretroviral sunt corecte?', ['Utilizează combinații de medicamente','Poate reduce viremia','Poate permite refacerea imunitară','Necesită aderență','Este înlocuit definitiv de antibiotice antibacteriene obișnuite'],[0,1,2,3],'Terapia antiretrovirală combinată suprimă replicarea HIV și poate ameliora funcția imună; antibioticele obișnuite nu o înlocuiesc.']
])];
