import {group} from './question-builder';
export const SYNOPSIS=[
...group('dermato','https://www.niams.nih.gov/health-topics/psoriasis',[
 ['Ce descrie o maculă dermatologică?', ['Modificare circumscrisă de culoare, fără relief','Colecție purulentă profundă','Leziune solidă obligatoriu de 5 cm','Pierdere completă a dermului','Veziculă cu lichid'],[0],'Macula este o leziune plană caracterizată prin modificarea culorii pielii.'],
 ['Psoriazisul poate prezenta:', ['Plăci eritemato-scuamoase','Afectare a suprafețelor de extensie','Modificări unghiale','Artrită asociată','Transmitere obligatorie prin atingere'],[0,1,2,3],'Psoriazisul este o boală inflamatorie necontagioasă, cu posibile manifestări cutanate, unghiale și articulare.'],
 ['Dermatita atopică poate asocia:', ['Prurit','Xeroză cutanată','Evoluție recidivantă','Antecedente personale sau familiale de atopie','Absența obligatorie a pruritului'],[0,1,2,3],'Pruritul și pielea uscată sunt caracteristice; boala poate avea evoluție cronică recidivantă.'],
 ['Ce elemente ale regulii ABCDE ridică suspiciunea de melanom?', ['Asimetrie','Borduri neregulate','Culoare neuniformă','Evoluție în timp','Stabilitate obligatorie a oricărei leziuni maligne'],[0,1,2,3],'ABCDE orientează evaluarea leziunilor pigmentare; modificarea în timp este importantă, fără a fi singurul criteriu.'],
 ['Urticaria se poate manifesta prin:', ['Papule sau plăci edematoase pruriginoase','Leziuni individuale tranzitorii','Asociere posibilă cu angioedem','Cicatrici profunde obligatorii după fiecare leziune','Infecție bacteriană obligatorie în toate cazurile'],[0,1,2],'Leziunile urticariene sunt de obicei tranzitorii și pruriginoase; pot avea multiple mecanisme și nu lasă tipic cicatrici.']
]),
...group('pediatrie','https://www.cdc.gov/rsv/infants-young-children/index.html',[
 ['Care virus este o cauză frecventă de bronșiolită la sugar?', ['Virusul sincițial respirator','Virusul hepatitic C','HIV exclusiv','Virusul rabic','Virusul papiloma uman'],[0],'VSR este o cauză importantă de infecție a căilor respiratorii inferioare și bronșiolită la sugar.'],
 ['Deshidratarea la copil poate asocia:', ['Diureză redusă','Mucoase uscate','Absența lacrimilor','Letargie în forme severe','Diureză crescută obligatorie'],[0,1,2,3],'Pierderile de lichid se reflectă prin scăderea diurezei și semne clinice de deshidratare.'],
 ['Bronșiolita sugarului poate prezenta:', ['Tahipnee','Tiraj','Wheezing','Dificultăți de alimentație','Necesitatea obligatorie a antibioticelor în fiecare caz'],[0,1,2,3],'Bronșiolita este de obicei virală; dificultățile respiratorii pot împiedica alimentația, iar antibioticele nu sunt sistematice.'],
 ['Convulsia febrilă simplă este caracterizată tipic prin:', ['Caracter generalizat','Durată sub 15 minute','Un singur episod în 24 de ore','Context febril fără infecție a sistemului nervos central','Deficit neurologic focal persistent obligatoriu'],[0,1,2,3],'Convulsia febrilă simplă are durată scurtă, este generalizată și nu recidivează în 24 de ore, după excluderea altor cauze relevante.'],
 ['În evaluarea creșterii copilului sunt utile:', ['Greutatea','Lungimea sau înălțimea','Evoluția pe curbe de creștere','Perimetrul cranian la vârstele corespunzătoare','O singură măsurare ca înlocuitor complet al urmăririi'],[0,1,2,3],'Măsurătorile seriate și traiectoria de creștere sunt mai informative decât o valoare izolată.']
]),
...group('gineco','https://www.cancer.gov/types/breast',[
 ['Ce manifestare după menopauză necesită evaluare ginecologică?', ['Sângerarea vaginală','Ochelarii de citit','Părul grizonat','Somnul normal','Apetitul păstrat'],[0],'Sângerarea postmenopauză necesită investigarea cauzei, inclusiv excluderea patologiei endometriale.'],
 ['Endometrioza poate asocia:', ['Dismenoree','Durere pelvină cronică','Dispareunie','Infertilitate','Localizarea obligatorie a țesutului doar în cavitatea uterină'],[0,1,2,3],'Endometrioza implică țesut asemănător endometrului în afara cavității uterine și poate afecta durerea și fertilitatea.'],
 ['Ce modificări mamare necesită evaluare?', ['Nodul nou palpabil','Retracție mamelonară nouă','Secreție mamelonară sangvinolentă','Modificări cutanate persistente','Orice modificare este sigur benignă înaintea evaluării'],[0,1,2,3],'Modificările noi sau persistente trebuie evaluate; aspectul clinic singur nu poate exclude malignitatea.'],
 ['Infecția persistentă cu tipuri HPV cu risc înalt:', ['Este implicată în carcinogeneza cervicală','Poate fi prevenită parțial prin vaccinare','Are legătură cu programele de screening cervical','Este exclusiv o infecție respiratorie','Produce obligatoriu cancer la fiecare persoană infectată'],[0,1,2],'Infecția persistentă cu HPV oncogen este un factor cauzal major; majoritatea infecțiilor nu evoluează însă spre cancer.'],
 ['Fibroamele uterine pot determina:', ['Sângerări menstruale abundente','Simptome de compresiune','Durere sau presiune pelvină','Anemie secundară sângerării','Transformare malignă obligatorie'],[0,1,2,3],'Leiomiomul este o tumoră benignă; simptomele depind de mărime și localizare.']
]),
...group('obstetrica','https://www.nichd.nih.gov/health/topics/preeclampsia',[
 ['Preeclampsia apare tipic după:', ['Săptămâna 2 de sarcină','Săptămâna 20 de sarcină','Numai după 10 ani de la naștere','Exclusiv înaintea sarcinii','Doar în primul trimestru fără excepții'],[1],'Preeclampsia este asociată sarcinii, tipic după 20 de săptămâni, și poate fi recunoscută și postpartum.'],
 ['Preeclampsia poate asocia:', ['Hipertensiune','Proteinurie','Afectare renală sau hepatică','Trombocitopenie','Excludere sigură în absența proteinuriei'],[0,1,2,3],'Proteinuria poate exista, dar afectarea de organ în contextul hipertensiunii poate susține diagnosticul și fără proteinurie.'],
 ['Sarcina ectopică poate prezenta:', ['Amenoree','Durere pelvină','Sângerare vaginală','Instabilitate hemodinamică în caz de ruptură','Implantare obligatorie în cavitatea uterină'],[0,1,2,3],'Implantarea extrauterină poate produce durere și sângerare, iar ruptura poate determina hemoragie internă severă.'],
 ['Cauzele hemoragiei postpartum includ:', ['Atonie uterină','Resturi placentare','Traumatisme ale tractului genital','Tulburări de coagulare','Doar hipertensiunea arterială ca mecanism unic'],[0,1,2,3],'Evaluarea cauzelor urmărește tonusul, țesutul restant, trauma și tulburările coagulării.'],
 ['Despre placenta praevia sunt corecte:', ['Placenta poate acoperi orificiul cervical intern','Poate produce sângerare nedureroasă','Localizarea placentei se evaluează ecografic','Este sinonimă cu sarcina tubară','Are relevanță pentru planificarea nașterii'],[0,1,2,4],'Localizarea joasă placentară poate cauza sângerare și influențează conduita obstetricală.']
]),
...group('psihiatrie','https://www.nimh.nih.gov/health/topics/depression',[
 ['Care este un simptom central al episodului depresiv major?', ['Anhedonia','Euforia permanentă obligatorie','Creșterea nevoii de socializare în toate cazurile','Absența oricărei modificări afective','Hiperactivitatea ca unic criteriu suficient'],[0],'Pierderea interesului sau plăcerii este un simptom central, alături de dispoziția depresivă.'],
 ['Un episod depresiv poate asocia:', ['Tulburări de somn','Modificări ale apetitului','Sentimente de inutilitate','Dificultăți de concentrare','Dispoziție euforică obligatorie'],[0,1,2,3],'Depresia poate implica manifestări afective, cognitive și somatice.'],
 ['Un episod maniacal poate prezenta:', ['Dispoziție elevată sau iritabilă','Nevoie redusă de somn','Logoree','Comportamente riscante','Încetinire psihomotorie obligatorie ca trăsătură definitorie'],[0,1,2,3],'Mania asociază modificări afective și creșterea energiei sau activității, uneori cu consecințe importante.'],
 ['Atacul de panică poate asocia:', ['Palpitații','Senzație de sufocare','Frică intensă','Transpirații','Excluderea automată a tuturor cauzelor somatice fără evaluare'],[0,1,2,3],'Manifestările vegetative pot fi intense; contextul clinic poate necesita excluderea unor cauze somatice.'],
 ['Deliriumul se caracterizează prin:', ['Debut acut sau subacut','Fluctuații ale manifestărilor','Tulburarea atenției','O cauză medicală sau toxică posibilă','Evoluție lentă obligatorie timp de ani, fără fluctuații'],[0,1,2,3],'Deliriumul este un sindrom acut fluctuant, cu afectarea atenției și conștienței, frecvent legat de o cauză organică.']
]),
...group('epidemio','https://www.cdc.gov/csels/dsepd/ss1978/lesson3/section2.html',[
 ['Ce măsoară incidența unei boli?', ['Cazurile noi apărute într-o populație într-un interval definit','Toate cazurile existente la un moment dat','Numai decesele','Doar durata spitalizării','Doar costul tratamentului'],[0],'Incidența descrie apariția cazurilor noi, în timp ce prevalența descrie cazurile existente.'],
 ['Care afirmații despre performanța unui test sunt corecte?', ['Sensibilitatea privește identificarea persoanelor bolnave','Specificitatea privește identificarea persoanelor fără boală','Valoarea predictivă pozitivă depinde de prevalență','Valoarea predictivă negativă poate depinde de prevalență','Sensibilitatea și specificitatea sunt întotdeauna identice'],[0,1,2,3],'Sensibilitatea și specificitatea caracterizează clasificarea în raport cu boala; valorile predictive depind și de contextul populațional.'],
 ['Într-un studiu randomizat controlat:', ['Repartizarea aleatorie poate reduce confuzia','Există un grup de comparație','Orbirea poate reduce unele surse de eroare','Randomizarea elimină garantat orice eroare posibilă','Rezultatele necesită interpretarea aplicabilității clinice'],[0,1,2,4],'Randomizarea și orbirea reduc anumite erori, fără a garanta absența lor sau aplicabilitatea universală.'],
 ['Principiile etice relevante în practica medicală includ:', ['Autonomia','Beneficiența','Nonmaleficiența','Justiția','Ignorarea preferințelor pacientului capabil ca regulă generală'],[0,1,2,3],'Cele patru principii orientează respectul pentru decizie, binele pacientului, evitarea răului și echitatea.'],
 ['Despre confidențialitatea medicală sunt corecte:', ['Protejează informațiile personale ale pacientului','Se aplică și datelor electronice','Accesul trebuie limitat la persoanele autorizate','Poate avea excepții prevăzute de lege','Permite divulgarea liberă pe rețele sociale'],[0,1,2,3],'Confidențialitatea se aplică indiferent de suport, cu excepții și obligații stabilite legal; divulgarea publică neautorizată nu este permisă.']
])];
