import type {Question} from './models';
import {KUMAR} from './questions-kumar';
import {SURGERY} from './questions-surgery';
import {SYNOPSIS} from './questions-synopsis';
import {HEMATOLOGY_SOURCE} from './bank/hematology-source';
import {INTENSIVE_CARE_SOURCE} from './bank/intensive-care-source';
import {ELECTROLYTES_SOURCE} from './bank/electrolytes-source';
import {SEPSIS_SOURCE} from './bank/sepsis-source';
import {ADVANCED_REVISIONS} from './bank/advanced-revisions';
import {RHEUMATOLOGY_ADVANCED} from './bank/rheumatology-advanced';
import {THYROID_ADVANCED} from './bank/thyroid-advanced';
import {DIABETES_ADVANCED} from './bank/diabetes-advanced';
import {DIABETES_COMPLICATIONS_ADVANCED} from './bank/diabetes-complications-advanced';
import {TROMBOEMBOLISM_ADVANCED} from './bank/tromboembolism-advanced';
import {HIPERTENSIUNE_ADVANCED} from './bank/hipertensiune-advanced';
import {PNEUMOLOGIE_ADVANCED} from './bank/pneumologie-advanced';
import {PERIOPERATOR_ADVANCED} from './bank/perioperator-advanced';
import {HEMOSTAZA_ADVANCED} from './bank/hemostaza-advanced';
import {INFECTII_CHIR_ADVANCED} from './bank/infectii-chir-advanced';
import {DERMATO_ADVANCED} from './bank/dermato-advanced';
import {EPIDEMIO_ADVANCED} from './bank/epidemio-advanced';
import {SEPSIS_ADVANCED} from './bank/sepsis-advanced';
import {HIV_ADVANCED} from './bank/hiv-advanced';
import {NEUROLOGIE_ADVANCED} from './bank/neurologie-advanced';
import {CARDIOLOGIE_ADVANCED} from './bank/cardiologie-advanced';
import {GASTRO_ADVANCED} from './bank/gastro-advanced';
import {HEPATOLOGIE_ADVANCED} from './bank/hepatologie-advanced';
import {NEFROLOGIE_ADVANCED} from './bank/nefrologie-advanced';
import {TRAUMA_ADVANCED} from './bank/trauma-advanced';
import {ARSURI_ADVANCED} from './bank/arsuri-advanced';
import {HERNII_ADVANCED} from './bank/hernii-advanced';
import {ESOFAG_ADVANCED} from './bank/esofag-advanced';
import {STOMAC_ADVANCED} from './bank/stomac-advanced';
import {INTESTIN_ADVANCED} from './bank/intestin-advanced';
import {COLON_ADVANCED} from './bank/colon-advanced';
import {BILIAR_ADVANCED} from './bank/biliar-advanced';
import {PANCREAS_ADVANCED} from './bank/pancreas-advanced';
import {VASCULAR_ADVANCED} from './bank/vascular-advanced';
import {PEDIATRIE_ADVANCED} from './bank/pediatrie-advanced';
import {GINECO_ADVANCED} from './bank/gineco-advanced';
import {OBSTETRICA_ADVANCED} from './bank/obstetrica-advanced';
import {PSIHIATRIE_ADVANCED} from './bank/psihiatrie-advanced';
import {ORL_ADVANCED} from './bank/orl-advanced';
import {ORTOPEDIE_ADVANCED} from './bank/ortopedie-advanced';
import {UROLOGIE_ADVANCED} from './bank/urologie-advanced';
import {FICAT_SPLINA_ADVANCED} from './bank/ficat-splina-advanced';
import {ELECTROLITI_ADVANCED} from './bank/electroliti-advanced';
import {ATI_ADVANCED} from './bank/ati-advanced';
import {HEMATOLOGIE_ADVANCED} from './bank/hematologie-advanced';
import {CARDIOLOGIE_B} from './bank/cardiologie-b';
import {CARDIOLOGIE_C} from './bank/cardiologie-c';
import {NEFROLOGIE_B} from './bank/nefrologie-b';
import {HEPATOLOGIE_B} from './bank/hepatologie-b';
import {PNEUMOLOGIE_B} from './bank/pneumologie-b';
import {DIABET_B} from './bank/diabet-b';
import {NEUROLOGIE_B} from './bank/neurologie-b';
import {HIV_B} from './bank/hiv-b';
import {GASTRO_B} from './bank/gastro-b';
import {SEPSIS_B} from './bank/sepsis-b';
import {REUMATOLOGIE_B} from './bank/reumatologie-b';
import {TROMBOEMBOLISM_B} from './bank/tromboembolism-b';
import {ELECTROLITI_B} from './bank/electroliti-b';
import {HEMATOLOGIE_B} from './bank/hematologie-b';
import {ENDOCRINOLOGIE_B} from './bank/endocrinologie-b';
import {HTA_B} from './bank/hta-b';
import {ATI_B} from './bank/ati-b';
import {TRAUMA_B} from './bank/trauma-b';
import {COLON_B} from './bank/colon-b';
import {PANCREAS_B} from './bank/pancreas-b';
import {ESOFAG_B} from './bank/esofag-b';
import {STOMAC_B} from './bank/stomac-b';
import {INTESTIN_B} from './bank/intestin-b';
import {ARSURI_B} from './bank/arsuri-b';
import {HERNII_B} from './bank/hernii-b';
import {BILIAR_B} from './bank/biliar-b';
import {VASCULAR_B} from './bank/vascular-b';
import {PERIOPERATOR_B} from './bank/perioperator-b';
import {INFECTII_CHIR_B} from './bank/infectii-chir-b';
import {HEMOSTAZA_B} from './bank/hemostaza-b';
import {ORTOPEDIE_B} from './bank/ortopedie-b';
import {ORL_B} from './bank/orl-b';
import {UROLOGIE_B} from './bank/urologie-b';
import {FICAT_SPLINA_B} from './bank/ficat-splina-b';
import {PEDIATRIE_B} from './bank/pediatrie-b';
import {GINECO_B} from './bank/gineco-b';
import {OBSTETRICA_B} from './bank/obstetrica-b';
import {PSIHIATRIE_B} from './bank/psihiatrie-b';
import {DERMATO_B} from './bank/dermato-b';
import {EPIDEMIO_B} from './bank/epidemio-b';
import {advancedEligibilityErrors} from './bank/advanced-author';

export const PREVIOUS_SOURCE_QUESTIONS:Question[]=[...SEPSIS_SOURCE,...ELECTROLYTES_SOURCE,...INTENSIVE_CARE_SOURCE,...HEMATOLOGY_SOURCE];
export const ADVANCED_CANDIDATES=[...ADVANCED_REVISIONS,...RHEUMATOLOGY_ADVANCED,...THYROID_ADVANCED,...DIABETES_ADVANCED,...DIABETES_COMPLICATIONS_ADVANCED,...TROMBOEMBOLISM_ADVANCED,...HIPERTENSIUNE_ADVANCED,...PNEUMOLOGIE_ADVANCED,...PERIOPERATOR_ADVANCED,...HEMOSTAZA_ADVANCED,...INFECTII_CHIR_ADVANCED,...DERMATO_ADVANCED,...EPIDEMIO_ADVANCED,...SEPSIS_ADVANCED,...HIV_ADVANCED,...NEUROLOGIE_ADVANCED,...CARDIOLOGIE_ADVANCED,...GASTRO_ADVANCED,...HEPATOLOGIE_ADVANCED,...NEFROLOGIE_ADVANCED,...TRAUMA_ADVANCED,...ARSURI_ADVANCED,...HERNII_ADVANCED,...ESOFAG_ADVANCED,...STOMAC_ADVANCED,...INTESTIN_ADVANCED,...COLON_ADVANCED,...BILIAR_ADVANCED,...PANCREAS_ADVANCED,...VASCULAR_ADVANCED,...PEDIATRIE_ADVANCED,...GINECO_ADVANCED,...OBSTETRICA_ADVANCED,...PSIHIATRIE_ADVANCED,...ORL_ADVANCED,...ORTOPEDIE_ADVANCED,...UROLOGIE_ADVANCED,...FICAT_SPLINA_ADVANCED,...ELECTROLITI_ADVANCED,...ATI_ADVANCED,...HEMATOLOGIE_ADVANCED,...CARDIOLOGIE_B,...CARDIOLOGIE_C,...NEFROLOGIE_B,...HEPATOLOGIE_B,...PNEUMOLOGIE_B,...DIABET_B,...NEUROLOGIE_B,...HIV_B,...GASTRO_B,...SEPSIS_B,...REUMATOLOGIE_B,...TROMBOEMBOLISM_B,...ELECTROLITI_B,...HEMATOLOGIE_B,...ENDOCRINOLOGIE_B,...HTA_B,...ATI_B,...TRAUMA_B,...COLON_B,...PANCREAS_B,...ESOFAG_B,...STOMAC_B,...INTESTIN_B,...ARSURI_B,...HERNII_B,...BILIAR_B,...VASCULAR_B,...PERIOPERATOR_B,...INFECTII_CHIR_B,...HEMOSTAZA_B,...ORTOPEDIE_B,...ORL_B,...UROLOGIE_B,...FICAT_SPLINA_B,...PEDIATRIE_B,...GINECO_B,...OBSTETRICA_B,...PSIHIATRIE_B,...DERMATO_B,...EPIDEMIO_B];
export const SOURCE_CHECKED_QUESTIONS=ADVANCED_CANDIDATES.filter(q=>advancedEligibilityErrors(q).length===0);
export const LEGACY_QUESTIONS:Question[]=[...KUMAR,...SURGERY,...SYNOPSIS];
// Old stems/options/keys remain addressable for saved attempts and open drafts.
// New sessions use the revised chapter; they never silently rescore old IDs.
export const QUESTIONS:Question[]=[...SOURCE_CHECKED_QUESTIONS];
export const BANK_TARGET=800;
export const EXAM_AVAILABLE=QUESTIONS.filter(q=>q.type==='CS').length>=50&&QUESTIONS.filter(q=>q.type==='CM').length>=150;
export const QUESTION_HISTORY:Question[]=[...LEGACY_QUESTIONS,...PREVIOUS_SOURCE_QUESTIONS,...SOURCE_CHECKED_QUESTIONS];
