import type {Question} from './models';
import {KUMAR} from './questions-kumar';
import {SURGERY} from './questions-surgery';
import {SYNOPSIS} from './questions-synopsis';
import {HEMATOLOGY_SOURCE} from './bank/hematology-source';
import {INTENSIVE_CARE_SOURCE} from './bank/intensive-care-source';
import {ELECTROLYTES_SOURCE} from './bank/electrolytes-source';
import {SEPSIS_SOURCE} from './bank/sepsis-source';
import {ADVANCED_REVISIONS} from './bank/advanced-revisions';
import {RHEUMATOLOGY_ADVANCED} from './bank/rheumatology-advanced';
import {THYROID_ADVANCED} from './bank/thyroid-advanced';
import {DIABETES_ADVANCED} from './bank/diabetes-advanced';
import {DIABETES_COMPLICATIONS_ADVANCED} from './bank/diabetes-complications-advanced';
import {TROMBOEMBOLISM_ADVANCED} from './bank/tromboembolism-advanced';
import {HIPERTENSIUNE_ADVANCED} from './bank/hipertensiune-advanced';
import {PNEUMOLOGIE_ADVANCED} from './bank/pneumologie-advanced';
import {PERIOPERATOR_ADVANCED} from './bank/perioperator-advanced';
import {HEMOSTAZA_ADVANCED} from './bank/hemostaza-advanced';
import {INFECTII_CHIR_ADVANCED} from './bank/infectii-chir-advanced';
import {DERMATO_ADVANCED} from './bank/dermato-advanced';
import {EPIDEMIO_ADVANCED} from './bank/epidemio-advanced';
import {SEPSIS_ADVANCED} from './bank/sepsis-advanced';
import {HIV_ADVANCED} from './bank/hiv-advanced';
import {NEUROLOGIE_ADVANCED} from './bank/neurologie-advanced';
import {CARDIOLOGIE_ADVANCED} from './bank/cardiologie-advanced';
import {GASTRO_ADVANCED} from './bank/gastro-advanced';
import {HEPATOLOGIE_ADVANCED} from './bank/hepatologie-advanced';
import {NEFROLOGIE_ADVANCED} from './bank/nefrologie-advanced';
import {TRAUMA_ADVANCED} from './bank/trauma-advanced';
import {ARSURI_ADVANCED} from './bank/arsuri-advanced';
import {HERNII_ADVANCED} from './bank/hernii-advanced';
import {ESOFAG_ADVANCED} from './bank/esofag-advanced';
import {STOMAC_ADVANCED} from './bank/stomac-advanced';
import {INTESTIN_ADVANCED} from './bank/intestin-advanced';
import {COLON_ADVANCED} from './bank/colon-advanced';
import {BILIAR_ADVANCED} from './bank/biliar-advanced';
import {PANCREAS_ADVANCED} from './bank/pancreas-advanced';
import {VASCULAR_ADVANCED} from './bank/vascular-advanced';
import {PEDIATRIE_ADVANCED} from './bank/pediatrie-advanced';
import {GINECO_ADVANCED} from './bank/gineco-advanced';
import {OBSTETRICA_ADVANCED} from './bank/obstetrica-advanced';
import {PSIHIATRIE_ADVANCED} from './bank/psihiatrie-advanced';
import {ORL_ADVANCED} from './bank/orl-advanced';
import {ORTOPEDIE_ADVANCED} from './bank/ortopedie-advanced';
import {UROLOGIE_ADVANCED} from './bank/urologie-advanced';
import {FICAT_SPLINA_ADVANCED} from './bank/ficat-splina-advanced';
import {ELECTROLITI_ADVANCED} from './bank/electroliti-advanced';
import {ATI_ADVANCED} from './bank/ati-advanced';
import {HEMATOLOGIE_ADVANCED} from './bank/hematologie-advanced';
import {advancedEligibilityErrors} from './bank/advanced-author';

export const PREVIOUS_SOURCE_QUESTIONS:Question[]=[...SEPSIS_SOURCE,...ELECTROLYTES_SOURCE,...INTENSIVE_CARE_SOURCE,...HEMATOLOGY_SOURCE];
export const ADVANCED_CANDIDATES=[...ADVANCED_REVISIONS,...RHEUMATOLOGY_ADVANCED,...THYROID_ADVANCED,...DIABETES_ADVANCED,...DIABETES_COMPLICATIONS_ADVANCED,...TROMBOEMBOLISM_ADVANCED,...HIPERTENSIUNE_ADVANCED,...PNEUMOLOGIE_ADVANCED,...PERIOPERATOR_ADVANCED,...HEMOSTAZA_ADVANCED,...INFECTII_CHIR_ADVANCED,...DERMATO_ADVANCED,...EPIDEMIO_ADVANCED,...SEPSIS_ADVANCED,...HIV_ADVANCED,...NEUROLOGIE_ADVANCED,...CARDIOLOGIE_ADVANCED,...GASTRO_ADVANCED,...HEPATOLOGIE_ADVANCED,...NEFROLOGIE_ADVANCED,...TRAUMA_ADVANCED,...ARSURI_ADVANCED,...HERNII_ADVANCED,...ESOFAG_ADVANCED,...STOMAC_ADVANCED,...INTESTIN_ADVANCED,...COLON_ADVANCED,...BILIAR_ADVANCED,...PANCREAS_ADVANCED,...VASCULAR_ADVANCED,...PEDIATRIE_ADVANCED,...GINECO_ADVANCED,...OBSTETRICA_ADVANCED,...PSIHIATRIE_ADVANCED,...ORL_ADVANCED,...ORTOPEDIE_ADVANCED,...UROLOGIE_ADVANCED,...FICAT_SPLINA_ADVANCED,...ELECTROLITI_ADVANCED,...ATI_ADVANCED,...HEMATOLOGIE_ADVANCED];
export const SOURCE_CHECKED_QUESTIONS=ADVANCED_CANDIDATES.filter(q=>advancedEligibilityErrors(q).length===0);
export const LEGACY_QUESTIONS:Question[]=[...KUMAR,...SURGERY,...SYNOPSIS];
// Old stems/options/keys remain addressable for saved attempts and open drafts.
// New sessions use the revised chapter; they never silently rescore old IDs.
export const QUESTIONS:Question[]=[...SOURCE_CHECKED_QUESTIONS];
export const BANK_TARGET=800;
export const EXAM_AVAILABLE=QUESTIONS.filter(q=>q.type==='CS').length>=50&&QUESTIONS.filter(q=>q.type==='CM').length>=150;
export const QUESTION_HISTORY:Question[]=[...LEGACY_QUESTIONS,...PREVIOUS_SOURCE_QUESTIONS,...SOURCE_CHECKED_QUESTIONS];
